### ISSUE TITLE
Favourite or Tracking list Enhancement

### ISSUE THREAD

**Issue by dahappychappy** [Stellarium/stellarium#100]
Hi,
I am looking for a favourites feature, so I can add a few objects to my list. Then when I click on my list I can see what is up and quickly look at different targets instead of always having to type in the name. A way to sync my list on my pc and my mobile would be great.
Eg.
I am trying to observe comets and typing out their full names is slow and I can't find some on my mobile app either, a feature like this would make it easier to plan a night observing if you can click on a short list and quickly figure out what you want to observe.
I hope this makes sense.
Thanks for this program, it is the BEST!!

**Comment by alex-w** [comment]
Alt-B in desktop application?

**Comment by gzotti** [comment]
Is @dahappychappy happy with the bookmarks? We cannot change the Mobile or any other spinoffs here.

**Comment by dahappychappy** [comment]
I have tried out the bookmarks, it's pretty cool! Is there a way i can hit a toggle that will show all my bookmarks? like there is an icon that shows galaxies with a symbol that I can visually see what is where? and what is up? Then I can pre visualise and take screen shots of my targets to make print outs for when I go out? That would be a super cool addition

**Comment by gzotti** [comment]
One entry in the bookmark list may include a view, including location and time. So you cannot toggle all at once, just like you cannot open all bookmarks in a book at once. 
Custom object lists are a long-standing request. May come some time, but it is not available at the moment.

**Comment by alex-w** [comment]
@dahappychappy please check the version 0.18.3 - we added small improvement to the Bookmarks tool ;)

**Comment by Jocelyn1109** [comment]
As agreed with Alex I will work on it: sort the bookmarks list and after implement the multiple bookmarks list.

**Comment by Jocelyn1109** [comment]
Hi developpment  is done on my side. I created a pull request.

**Comment by axd1967** [comment]
Superseded by #976

**Comment by alex-w** [comment]
But the request is not superseded by #976 - please read the body of request.

**Comment by gzotti** [comment]
OP has not answered for >3years, and the topic is covered in the Bookmarks discussion. 

I do not understand why @axd1967 first notes this is superseded, and then agrees (giving thumbs-up) with @alex-w that this is *not* superseded. Is thumbs-up just your indicator to every message you have read? Then please abstain from that practice.

In total, given its close relationship to the more recent and (hopefully) active observing lists discussion, IMHO this issue can be closed.

**Comment by axd1967** [comment]
just **linking** issues in order to create a larger context, that's all. 

"superseded" came first to my mind because we no longer have bookmarks, but observing lists; but that's not entirely correct, as @alex-w pointed out. and so I modified my message.

and meanwhile this helps weed out open issues that can be **rightly** closed. it's all part of the general effort of participating in an open source project.

(and there is no formal definition on how to use emoji, so everybody is free to interpret them however they like. (for example, what's :eyes: ?). and I just wanted to give @alex-w a positive signal.)

**Comment by alex-w** [comment]
Including random comment to partially related or unrelated issues not increased order, this behavior increases chaos
