### ISSUE TITLE
Stellarium cannot be installed in macOS Catalina 10.15.3 because the computer says cannot verify whether the programme contains bad software or not. Any solution?

### ISSUE THREAD

**Issue by Kekropas1831** [Stellarium/stellarium#1003]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Fixed in latest betas

**Comment by alex-w** [comment]
Double of #931

**Comment by Kekropas1831** [comment]
Hello,
I tried twice today to install the Stellarium-0.19.3.dmg in macOS Catalina 10.15.3 but I still confront the same problem. The system cannot verify the creator of the Application and cannot also find whether or not there is a malicious software. Processor 8-Core Intel Core i9, 64 bit, Graphics Intel UHD Graphics 630 1536 MB. 
Any solution?

**Comment by gzotti** [comment]
The sentence "Fixed in latest betas" should have been enough suggestion to download the current beta version (this means pre-release or intermediate version) from https://stellarium.org. You get there by clicking on the beta symbol instead of the Mac symbol.
