### ISSUE TITLE
Date & Time window scaled incorrectly

### ISSUE THREAD

**Issue by Jimjolnir** [Stellarium/stellarium#1005]
### Expected Behaviour
A slim, regular looking Date & Time window.
### Actual Behaviour
(I would add a screenshot, but don't know how)
The Date & Time window takes up half of the screen. It's the right width, but about seven times the height! I think it occurred after an automatic update. It's been like that for weeks, finally uninstalled and installed the latest version, I first checked that my graphics driver was up to date.

(I've used Stellarium for many happy years now, this is my first bug. 
I have two feature suggestions; 
1 - an option to show the moons phases clearly, currently it's just a white blur until zoomed in enough. Either show the phases in the sky at all zooms, or have a separate little window top left or something. 
2 - Save points in the 'Date & Time' window, to save some date points for reference, keep saves on exit, warn when overwriting.)

### Steps to reproduce
Be me.
### System
* Stellarium version: stellarium-0.19.3.1-win64
* Operating system: Windows 10 Pro, Build 1903
* Graphics Card: NVidia, Geforce 360, driver version 23.21.13.9135

### Logfile 
I'd attach the log file, but don't know how to do that, either.

**Comment by Jimjolnir** [comment]
Apparently you just drag and drop attachments. Who knew :| 
![Screenshot (121)](https://user-images.githubusercontent.com/62386435/77078071-c242f880-69fe-11ea-878e-f7601f56d6ae.png)
[log.txt](https://github.com/Stellarium/stellarium/files/4355083/log.txt)

**Comment by gzotti** [comment]
You can as well just drag and drop the lower edge of this panel to resize it. Size is then permanently stored in config.ini.

**Comment by Jimjolnir** [comment]
facepalm. I swear I tried that. I'll open my eyes next time. All the years and I never had that happen, I'd never want to expand the date window, anyway.
Will those suggestions be noticed here, or is there a better place to leave them?

**Comment by gzotti** [comment]
We can safely close this. Resizing windows is not so non-obvious.
