### ISSUE TITLE
Time runs slower when a solar system object is selected?

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1006]
I don't know if this only affects me, but it seems that the time in Stellarium goes slightly slower when a solar system object is selected.

1. Select a solar system object (Sun, Moon, whatever).
2. Notice how the time runs a bit slower. Especially prominent if you choose current time (press 8), and wait a few seconds (Stellarium will not have kept up with current timeflow).

Latest beta on Windows 10 64 bit.

**Comment by gzotti** [comment]
May have to do with countless computations for the information text. Thanks for reporting.

**Comment by alex-w** [comment]
The effect is obtained after enabling displaying the proper motions

**Comment by gzotti** [comment]
Yes, just working on it.

**Comment by Atque** [comment]
The problem is still present (as of 0.20.1) for comets...

**Comment by gzotti** [comment]
Indeed, forgot to copy solution...

**Comment by alex-w** [comment]
@gzotti +minor planets

**Comment by victorman1998** [comment]
> The problem is still present (as of 0.20.1) for comets...

I agree. Same bug here.
