### ISSUE TITLE
The program can't start because MSVCR120.dll is missing

### ISSUE THREAD

**Issue by fieldsja2112** [Stellarium/stellarium#101]
### Expected Behaviour
The program runs for a while, then crashes.  It will not run scripts.
### Actual Behaviour
![image](https://user-images.githubusercontent.com/26529337/36010701-703e704a-0d18-11e8-8a75-1f00ad8cbe4c.png)

### System
* Stellarium version: Stellarium 0.17.0:
* Operating system: Windows 8.1; 
* Graphics Card: Intel Core i7 4700 MQ 64 bit

**Comment by alex-w** [comment]
Please check latest beta
