### ISSUE TITLE
Effects about globular clusters

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#1016]
![image](https://user-images.githubusercontent.com/32613953/77750183-53991700-705e-11ea-98a4-99d46cbb2926.png)

![image](https://user-images.githubusercontent.com/32613953/77750256-6d3a5e80-705e-11ea-8260-dbf4e8b6f6ea.png)

This kind of effect of GCL in Stellarium is common. It does not match visible forms or photographes, and may also causes some misleading. The causes may come from star catalogs and the particularity of global cluster. I consider ripping stars in filed as one of feasible measures.

**Comment by gzotti** [comment]
Of course this is a catalog artifact and mix of photo and simulated catalog stars. Volunteer fixes welcome!
