### ISSUE TITLE
my apple IOS will not allow installation of latest version

### ISSUE THREAD

**Issue by jbmcmath** [Stellarium/stellarium#1020]
my apple IOS will not allow installation of the latest version on grounds it cannot verify the source.  Please advise.

**Comment by alex-w** [comment]
iOS? Maybe macOS?

**Comment by gzotti** [comment]
#1003, #931, https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#unsigned-installer-dangerous-to-download-malware

**Comment by jbmcmath** [comment]
Yes, sorry, mac OS

On Mar 28, 2020, at 6:59 PM, Alexander Wolf <notifications@github.com<mailto:notifications@github.com>> wrote:



iOS? Maybe macOS?

**Comment by alex-w** [comment]
The problem is fixed in beta, plus we will release version 0.20.0 later today.
