### ISSUE TITLE
0.20.0 throws away custom sat groups

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1022]
### Expected Behaviour

* don't touch the existing config, 
* give at least a warning. 
* write this UP FRONT in the release notes !
* run a conversion tool to re-import the existing groups into the new config

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: 0.20.0
* Operating system:Kubuntu 18

* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/4399616/log.txt)

**Comment by alex-w** [comment]
Please check v0.20.2.18046 - we changed tool for checking version of satellites.json file.

**Comment by alex-w** [comment]
@axd1967, please attach your satellites.json file.

**Comment by axd1967** [comment]
(I just built 0.20.2 (but not 0.20.2.XXXXX) and lost my groups again.)

**Comment by axd1967** [comment]
and lost data again. 

it is possible that this happens when stellarium is opened twice or closed in an uncontrolled way.

i just get a **small, barely readable ** warning that the format is invalid, and then I lose my groups.

is it **please** possible to 

a satellite format that has become incompatible should NEVER be discarded. the pattern is (1) to store a version id in the file and (2) to write a series of update routines that carry a file format to the next file format version. as such, no data should be lost.

ALSO

don't create just `xxx.old` because that could overwrite a previous XXX.OLD file. instead, add a **time stamp** to a filename that has become obsolete: `<filename>.<extension>.OLD-YYYYMMDD-HHMMSS` This way, it is possible that many files might be created, but at least no file is ever **overwritten**. It is up to the user to clean up these `*OLD*` files.

**Comment by axd1967** [comment]
lost data again.

**Comment by alex-w** [comment]
Please check 0.20.3RC2

**Comment by axd1967** [comment]
@alex-w I'm sure your work is OK, but I'm not so sure a loss of data is easy to test - I can only hope it won't happen again, but when it does, I'll leave a comment here.

First of all, I don't know how to test this. I assume the data loss happens when killing the application , or maybe when the application is launched twice.

**Comment by axd1967** [comment]
a reason data _could_ be lost...

https://github.com/Stellarium/stellarium/blob/691c9d0853c6baca3e49abf820f77f6fa0bf5a93/plugins/Satellites/src/Satellites.cpp#L82-L85

**Comment by axd1967** [comment]
about upgrading config files having version info: sometimes there is a need to add/remove/change fields in a JSON file. usually, adding JSON fields should be trivial, but what if existing fields need some kind of conversion?

removing the old file might be dangerous - imagine that for some reason, the user discovers data has been lost and the `.old` file has meanwhile been replaced too

https://github.com/Stellarium/stellarium/blob/1e617e49918ab2e5e5fad318dd1ab4024eb1e41c/src/main.cpp#L319-L326

the problematic bit to be replaced is 

https://github.com/Stellarium/stellarium/blob/1e617e49918ab2e5e5fad318dd1ab4024eb1e41c/src/main.cpp#L320-L321

and we need to replace  `QString("old")` with something like `QString(Date::now())` or similar


same issue here:

https://github.com/Stellarium/stellarium/blob/915a10740311075f3f0e15dcb4631fdf64ebb1e1/src/core/modules/StarMgr.cpp#L430-L433



a general pattern for upgrading a file that has a changing format is to save the previous version with a timestamp in the filename and use a cascading upgrade scheme.

here is a trivial implementation with  IF constructs.

```
current_version = getversion(file)

// optionally:
if current_version < someoldvalue then
print("version really too old to upgrade")
break
...
if current_version == 12 then
   backup() // copies current version to a copy having a time stamp in the filename
   upgrade_12_to_13()  // reads a v12 file and performs an upgrade to v13, probably also writes bacjk that file
   current_version = 13
end

if current_version == 13 then
   backup()
   upgrade_13_to_14()
   current_version = 14
end

if current_version == 14 then
   backup()
   upgrade_14_to_15()
   current_version = 15
end

// etcetera, up to the latest version

// whenever a new version appears, a new section tests for the previous version and upgrades to the current version, as necessary
// this pattern allows to upgrade any version to the most recent version without losing a file that might be needed to recover critical data (eg by re-running an older version of Stellarium)


```

a _much_ more efficient approach is to use a `switch` combined with a [`[[fallthrough]]`](https://en.cppreference.com/w/cpp/language/attributes/fallthrough).

**Comment by axd1967** [comment]
satellite data keeps getting lost in an unpredictable way for some unknown reason.

I suspect that there is a read-erase-write cycle that is not properly guarded against accidental data loss.

this is happening far too often.

(I guard against this by separately versioning the JSON data)

**Comment by axd1967** [comment]
Unfortunately it is difficult to reproduce, yet I still experience it today (0.22 for example) : the sat data is completely lost. 

**Workaround** for now: make sure to locally and frequently version the config data so that it can be restored and then updated.

This issue should not be closed as there IS a bug somewhere.

**Comment by axd1967** [comment]
25.2: custom sat groups lost (again) in one of the sessions.

**Comment by axd1967** [comment]
and again.
I open Stellarium 25.2 and discover that my `satellite.json` file is empty.

there must be something that empties the file; I assume that in the time between emptying the file and  before the file is written back, the app might be closed by the user, therefore leaving the file empty.

**Comment by 10110111** [comment]
Is there a log file from that run? I suppose it would say something like `[Satellites] copied default satellites.json to ...`, right?

**Comment by 10110111** [comment]
BTW, what OS are you on now? I remember there was a peculiarity in some versions of ext4 that a file that hadn't been closed cleanly before a system crash would be reset to empty on journal "recovery".

**Comment by axd1967** [comment]
> BTW, what OS are you on now? I remember there was a peculiarity in some versions of ext4 that a file that hadn't been closed cleanly before a system crash would be reset to empty on journal "recovery".

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-216-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

**Comment by axd1967** [comment]
> Is there a log file from that run? I suppose it would say something like `[Satellites] copied default satellites.json to ...`, right?

I'll try to find this.

Also, I tried to search in the code where the file might be emptied; it looks like things could go wrong here:

https://github.com/Stellarium/stellarium/blob/c720e866dde60bfd86df09fef338897eb3c3da33/plugins/Satellites/src/Satellites.cpp#L315

Question is why one would delete a file, but I didn't dig further in the code.

The function name (actually the entire function) is already suspect: it had better read something like `bool Satellites::isItAllowedToBackupTheCatalog(bool deleteOriginal)` (or maybe `okToDeleteCatalog()`) and the argument is also fishy.

Also, I would choose for renaming to a copy such as `satellite.json.YYYYMMDDHHMMSS.` rather than delete and rebuild it, so that the user can restore an old version of `satellite.json`.  Thee trouble is that this file can become huge (mine has 15Mb...).

So maybe copy it first and only delete it when it has been rewritten sounds like a better approach.

**Comment by 10110111** [comment]
> So maybe copy it first and only delete it when it has been rewritten sounds like a better approach.

Indeed, and this is how many text editors save files. But there will still be a problem if the rewritten file gets empty data due to an error (one case of which has been fixed, but there might be others).

**Comment by axd1967** [comment]
And again.  All sats lost.

V25.3

**Comment by axd1967** [comment]
And again.
V26.2, all groups lost.

There really is a bug in this "low importance" issue.
(The custom groups are not lost, but empty.)

**Comment by axd1967** [comment]
Again, lost all groups (and in fact, all satellites). (V26.2)

There is a fragility issue here. I suspect that Stellarium tries to write back satellite data and when this is interrupted, the app ends up without data. There is no implementation of a transaction; there is a Missing Transaction Isolation: The software lacks a safety mechanism—like writing to a temporary file first and renaming it only after the write succeeds—to protect data from workflow interruptions.

**Comment by 10110111** [comment]
@axd1967 You should really instrument your installation with some logging of what's being done, when a file is deleted/overwritten, etc. before you report your once in a couple months instance of this issue. This way we'll at least know the actual reproduction scenario. Otherwise these messages are just as useful as sending "BUMP" in dead threads on forums.

Also note that if we are going to fix this in this particular case, we should do likewise in other plugins that automatically update their data.

**Comment by alex-w** [comment]
Satellites plugin hasn't a real groups of satellites - all these "groups" just a collection of keywords, which was assigned to satellites. Yes, it allow grouping the satellites. If by some reasons you deleted all satellites then you also deleted all "groups". If you have a bad connection to the internet then uncheck "On update, remove the satellites that are not longer listed in the updated sources".

**Comment by axd1967** [comment]
Unfortunately, I can't compile until further notice... (BTW - I already use a fresh logfile for each session.)

Actually I'm talking about `satellites.json` (hereafter called S). This file also contains custom group information.

I'm never deleting this file. Why would I?

Maybe that is a good indication: the automatic update (sic) that removes sats that no longer exist. 

Is it possible to add in v26.3 at least emit a debug when opening S  _before_ starting a write action and _when closing it_?

**What I do notice is that following workaround does not help:**

1. I overwrite S with an older (15mb) copy of S, with the intention to then launch an update of the sat data 
2. after clicking the update button, I end up with a small (66kb) S file!

Maybe Stellarium is not able to deal with an outdated version of the sat file. If that's the case (which I've described higher in this issue), this bug will bite again every time. Stellarium must be able to cope with file format migrations rather than take the easy way and start over from scratch.

Relevant log lines:

```
... etc
[   190.391][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=orbcomm&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
... etc
... 
[   192.214][DBG ] Satellite removed: "38038" "ZIYUAN 1-02C (ZY 1-02C)"
[   192.214][DBG ] Satellite removed: "41556" "ZIYUAN 3-02 (ZY 3-02)"
... etc
[   192.214][DBG ] [Satellites]  13018 satellites proposed for removal,  13003  removed,  95  remain.
[   192.237][DBG ] [Satellites] update finished. 94 / 13098 updated, 0 added, 13018 missing or removed. 506 source entries parsed.

```

I would not expect the network errors to cause deletion, but I didn't investigate further.

Maybe the reason that decides to remove sats is fishy?

[log_2026-08-31T12:43:16+00:00 (2).txt](https://github.com/user-attachments/files/31655022/log_2026-08-31T12.43.16%2B00.00.2.txt)

**Comment by axd1967** [comment]
Ok...
I'll  (try to) no longer complain about data migration, there is none for the moment:

https://github.com/Stellarium/stellarium/blob/43b152fa8d79c7f45f3b738f6232fef95a1a0c06/plugins/Satellites/src/Satellites.cpp#L488-L491

Data migration patterns are a good starting point for new developers with some advanced skills.

The broad lines of such a pattern are to repeatedly go through a fallthrough switch so as to proceed from one version to the next until the current version has been reached.

**Comment by alex-w** [comment]
In the log:
```
[   190.387][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=supplemental/starlink&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.388][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/supplemental/sup-gp.php?FILE=starlink&FORMAT=tle". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.388][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=x-comm&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.388][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=weather&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.388][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=visual&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.388][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=tdrss&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.388][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=swarm&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.388][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=stations&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.389][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=starlink&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.389][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=spire&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.389][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=science&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.389][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=sbas&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.389][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=sarsat&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.389][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=resource&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.389][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=raduga&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.390][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=radar&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.390][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=planet&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.390][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=other-comm&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.391][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=other&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.391][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=orbcomm&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.391][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=oneweb&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.391][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=noaa&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.391][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=nnss&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.391][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=molniya&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.392][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=last-30-days&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.392][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=iridium-NEXT&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.392][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=iridium&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.392][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=intelsat&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.392][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=gps-ops&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.392][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=gorizont&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.392][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=goes&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.392][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=gnss&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.392][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=globalstar&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.393][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=glo-ops&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.393][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=geodetic&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.393][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=geo&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.393][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=galileo&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.393][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=engineering&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.393][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=education&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.393][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=dmc&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.393][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=cubesat&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.393][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=beidou&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.393][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=argos&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.394][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=analyst&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.394][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=amateur&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
[   190.394][WARN] [Satellites] FAILED to download "https://celestrak.org/NORAD/elements/gp.php?GROUP=active&FORMAT=TLE". Error QNetworkReply::TimeoutError: "Socket operation timed out"
```

So, you download zero sources and zero satellites and if option "On update, remove the satellites that are not longer listed in the updated sources" is checked then Satellites plugin deleted all satellites from the file. It doing just as expected!

Is it possible to switch to new sources format? Yes, but it required press a button "Reset sources list to its defaults" and no, we do not removing/updating custom list of sources automatically, because this is custom list.

Why celestrak.org blocked you? I don't know. Maybe you have old SSL/TLS libraries and Stellarium can't establish the connection or maybe you're in blacklist, or, maybe it's a firewall rule.

**Comment by axd1967** [comment]
- I don't know why I would "download zero sats".
- blacklisting? that's new. as an example, https://celestrak.org/NORAD/elements/gp.php?GROUP=geodetic&FORMAT=TLE works fine 
- No firewall

what i tried:

1. reset to default list
2. manually deleted all sats
3. unchecked "... remove ... no longer listed"
4. choose a minimal set of groups in sources: `stations` and `visual`
6. triggered "Update now".Custom groups are still there, that's OK.

Celestrak downloads went fine, so no SSL/TLS library issue

If the issue doesn't reappear I'll start playing with the "remove unlisted sats".
