### ISSUE TITLE
0.20: ALT + arrow crash

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1023]
### Expected Behaviour
trying to ttest #946 

### Actual Behaviour
crash

### Steps to reproduce
1. start stellarium
2. type ALT + LEFT ARROW

### System
* Stellarium version: 0.20
* Operating system: Kubuntu 18
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/4399716/log.txt)

**Comment by gzotti** [comment]
Do you observe from a valid location on Earth?

**Comment by axd1967** [comment]
All I did was to open Stellarium and press ALT + arrow left.

**Interestingly, when I changed the location, the crash no longer appears.** Possibly Stellarium has reset something somewhere.

And I now discover that this combination is assigned to "rotate sensor frame 15 deg" and the sensor text appears but without a sensor active.

![image](https://user-images.githubusercontent.com/3529789/77863246-38c2d000-7221-11ea-9ac9-60371464c008.png)

**Comment by alex-w** [comment]
By default no any combination is assigned to "rotate sensor frame 15 deg"...

**Comment by gzotti** [comment]
When loading the hotkeys a test may indeed be useful to detect collisions. Some hotkeys are not loaded when the whole module is not active.  Output to log.txt should be sufficient, or add a warning popup that says "shortkey collisions detected. See logfile".. 

For the case here, alt-arrow moves the observer when on an "observer" planet. Now, did that crash in StelMovementMgr, or in the Oculars plugin?

@axd1967 please disable the Oculars plugin and check if it still crashes.

**Comment by alex-w** [comment]
@axd1967 please attach your config.ini file

**Comment by axd1967** [comment]
I think we can close this - in 0.20.1 I cannot reproduce this.
