### ISSUE TITLE
0.20 comet C/2019 Y4 unavailable

### ISSUE THREAD

**Issue by iBeny** [Stellarium/stellarium#1027]
Hi

Version 0.20 is supposed to have added comet C/2019 Y4 (Atlas) in it ! Where is it ? 

In the Find tool, no "C/2019 Y4" (ATLAS) shows ! only C/2019 Q4 (Borisov)...
In the Find  | List tab, no "2019" comets shows in the "Comets" section !?

What's up doc ?

Best regards
Benoit

**Comment by alex-w** [comment]
You need reset Solar system data through Solar System Editor plugin (or add this comet by same pluign).

By default installer delete the old Solar system data and "new comet" is coming after copying "new" ssystem_minor.ini into User Directory.

**Comment by iBeny** [comment]
Please explain the procedure thoroughly :
1- Configuration (F2) | PlugIns | Solar System Editor
2- Press "Configure"
3- Which tab ? Which button ?

**Comment by alex-w** [comment]
First tab, see "Reset to defaults" button or second tab, see "Import..." button

**Comment by iBeny** [comment]
1- Configuration (F2) | PlugIns | Solar System Editor
2- Press "Configure"
3.1- Configuration file | press "Import and replace..."
3.2- Configuration file | press "Import and add..."
3.3- Solar system | press "Import orbital elements... "

Explain what to do and the difference between each #3 points.

**Comment by iBeny** [comment]
Just checked and ATLAS comet is foundable Now ! Was it because of the #3 "Reset" action ? or some other 4.4 things I did at random ? Don't know...
