### ISSUE TITLE
let partition marks be on top of horizon

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1028]
**Is your feature request related to a problem? Please describe.**
When a landscape is active, I cannot see the horizon marks

![image](https://user-images.githubusercontent.com/3529789/78017805-22199780-734d-11ea-8309-7429917fe0ef.png)

![image](https://user-images.githubusercontent.com/3529789/78017855-2e9df000-734d-11ea-930e-5c8f9edd22b8.png)

**Describe the solution you'd like**
raise the priority of the horizon marks

**Describe alternatives you've considered**
Toggle the landscape

**Additional context**

Thank you for this great software.

**Comment by gzotti** [comment]
Just use the CompassMarks plugin that existed before. The horizon line is usually covered by the landscape, regardless of where the small marks are pointing.

**Comment by axd1967** [comment]
Well - I almost forgot - 

1. is that plugin still needed?
1. I can activate it, but the configuration does not open (not sure if there is anything to configure though)

**Comment by gzotti** [comment]
(1) If you want horizon marks instead of the Cardinal marks plotted in front of the landscape: yes.
(2) Nothing to configure. Just press the "compass" button.

**Comment by Atque** [comment]
A related enhancement would be to orient the partitions and lables after the viewer. Look at this Milky Way screenshot from Australia, showing the galactic equator upside down:
![stellarium-036](https://user-images.githubusercontent.com/37028368/78044451-fdd1b100-7374-11ea-90e7-0d0904dac7a1.png)

**Comment by gzotti** [comment]
These labels *are* turned on the southern hemisphere, like all others in the sky. Just that there needs to be yet another rule for galactic/supergalactic, which may appear upside-down on any hemisphere depending on time. Probably it is even better to *not* rotate those two, though, as the reading sense will remain more consistent.

**Comment by axd1967** [comment]
> (2) Nothing to configure. Just press the "compass" button.

Maybe a module that has nothing to configure should have its "confgure" button removed?

**Comment by Atque** [comment]
@gzotti The lables should not be upside down as it is harder to read them. Maybe the partitions can be though.

**Comment by axd1967** [comment]
the overall rule could be that labels should be normally readable unless the gravity option has been activated.

**Comment by gzotti** [comment]
@axd1967 @Atque  There are worse problems, really. We accept working pull requests. But *we* make the rules :-)
