### ISSUE TITLE
Stell. on Fedora 31 after update errors

### ISSUE THREAD

**Issue by tuxedotje** [Stellarium/stellarium#1029]
stellarium
QSocketNotifier: Can only be used with threads started with QThread
Empty translation file for language  "en_US" in section "stellarium-scripts"
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Satellite has invalid orbit: "OBJECT H" "44346"
Satellite has invalid orbit: "DRAGON CRS-19 DEB" "44822"
Satellite has invalid orbit: "DRAGON CRS-19 DEB" "44823"
Satellite has invalid orbit: "SL-4 R/B" "44834"
Satellite has invalid orbit: "MOLNIYA 2-17" "9829"
[Novae] Download error: While trying to access "https://stellarium.org/json/novae.json" the following error occured: "Unknown error"
[Satellites] "44822" "DRAGON CRS-19 DEB" has invalid orbit and will be removed.
[Satellites] "44823" "DRAGON CRS-19 DEB" has invalid orbit and will be removed.
[Satellites] "9829" "MOLNIYA 2-17" has invalid orbit and will be removed.
[Satellites] "44346" "OBJECT H" has invalid orbit and will be removed.
[Satellites] "44834" "SL-4 R/B" has invalid orbit and will be removed.
[Satellites] purging objects that were not updated...
Satellite has invalid orbit: "DELTA 2 R/B(1)" "20362"
[Novae] already updating...  will not start again current update is complete.
[Novae] already updating...  will not start again current update is complete.
^[[1;2A[Novae] already updating...  will not start again current update is complete.
^[[1;2A^[[B[Novae] already updating...  will not start again current update is complete.

**Comment by gzotti** [comment]
empty translation file for translation from english to english(US) is harmless.
The satellite "errors" are just informative signs of action. 
wayland: Probably harmless.
novae: not sure.

**Comment by alex-w** [comment]
@tuxedotje could you check version 0.20.2?

**Comment by tuxedotje** [comment]
On Fedora 32 version 0.20.2 is OK, just seeing the sun rise on Stellarium. ( heavy clouded here) OK.
