### ISSUE TITLE
Location window may expand off the screen when selecting certain planets.

### ISSUE THREAD

**Issue by Austin-RR** [Stellarium/stellarium#103]
**BRIEF DESCRIPTION OF THE ISSUE**
In the Location window [F6], selecting a "Planet" with a large map image - such as either the Moon or Pluto - causes the Location window to resize to a size so large that the Location window may be difficult to use on smaller monitors such as those on laptops.

**DETAILED DESCRIPTION OF THE ISSUE**
When starting a default Stellarium (0.17.0 Windows x64) and opening the Location window, the default size of the Location window as well as the map of the Earth appear reasonable.  Remain in the Location window and go to the "Planet" drop-down menu to select "Moon".  The map of the Moon appears rather large which causes the entire Location window to appear rather large.

For some systems, this may be more than a cosmetic issue.  Users with larger desktop screens may still be able to completely view the Location window.  However, users with smaller screens - such as laptop screens - will find it to be an issue if the Location window's bottom buttons and menus (or maybe just the last few items in the menu list when the menu is opened) appear off of the screen's bottom edge.

The only apparent method of returning the Location window to a useful size is editing the "config.ini" file ("DialogSizes" -> "Location").  Restarting Stellarium does not reset the window's size.  Returning the "Planet" selection to "Earth", or another body, does not reset the window's size.  And, there appears to be no method of using Stellariums's GUI to resize the Location's window with the mouse.

**HOW TO REPRODUCE THE ISSUE:**
1. Start with a default Stellarium (Windows x64 0.17.0) configuration.
2. Open "Location window" [F6].
3. The Location window's size should appear reasonable and easily fit in just about any size monitor.
4. In the Location window, go to the "Planet" menu, and select "Moon".

The issue should now have appeared.  The Location window's size should now have greatly increased - especially in the vertical direction.  If the monitor is not large in size, a few of the bottom buttons or drop-down menus on the Location window can be difficult to use as they may appear off the screen.  The vertical size of the Location window has been increased from its default size of 551 pixels to 791 pixels.  This resizing may be an issue on a 15.6" laptop screen with a vertical resolution of 768 pixels, for example.

**OTHER NOTES:**
1. After investigating older Stellarium versions, it was determined that the issue first appeared with version 0.16.0.  The Windows x64 versions of Stellarium were used in every test:

-    0.14.3  NO issue. (Location window never resizes regardless of which "Planet" is selected.)
-    0.15.2  NO issue. (Location window never resizes regardless of which "Planet" is selected.)
-    0.16.0  Issue exists. (Location window resizes when larger "Planet" maps are selected.)
-    0.16.1  Issue exists. (Location window resizes when larger "Planet" maps are selected.)
-    0.17.0  Issue exists. (Location window resizes when larger "Planet" maps are selected.)

2. The vertical expanding issue is mostly prominent by selecting celestial bodies in the "Planet" drop-down menu that have a higher resolution map image.  Selecting either the Moon or Pluto will display the same issue as they both have the highest resolution size of 1024 x 512.  Selecting other images might also cause some expanding, but not to the extent as selecting the Moon or Pluto.  Down-sizing either the Moon's or Pluto's image to something smaller such as 512 x 256 prevents the Location window from experiencing a drastic change in size (or possibly no change at all) when either of these is selected for the first time after the down-sizing.
3. Should be noted that this issue can be present even in full-screen mode.
4. Same results were found after testing on two different computer systems.

**POSSIBLE SOLUTION:**
It appears that older versions (prior to 0.16.0) simply forced a map image of any resolution into a fixed predetermined size (appears to be 400 x 240) within the Location window.  A possible solution is simply to revert to that methodology rather than allowing the Location window to resize after selecting map images of different resolutions.

**SYSTEMS/FILE INFO:**

File: stellarium-0.17.0-win64.exe

**Laptop:**
Windows 7 Ultimate SP1 (x64)
CPU: AMD E2-1800 (1.7 GHz)
GPU: AMD Radeon HD 7340 Graphics
Driver: Catalyst - 15.200.1062.1004
OpenGL/GLSL: 4.5/4.40
Monitor Size/Native Resolution: 15.6" / 1366 x 768
(Expanding issue causes the Location window to expand off the smaller monitor.)

**Desktop:**
Windows 7 Home Premium SP1 (x64)
CPU: Intel Pentium G2030T (2.6 GHz)
GPU: Intel HD Graphics
Driver: 9.17.10.2867
OpenGL/GLSL: 4.0/4.00
Monitor Size/Native Resolution: 20" / 1600 x 900
(Same expanding issue exists, but the larger monitor allows all of the Location window to be visible.)

![location window screenshot](https://user-images.githubusercontent.com/36420819/36117169-acd6109e-1006-11e8-9c55-80b60b17d9c7.png)

**Comment by gzotti** [comment]
Thanks for reporting. Indeed, since V0.16 GUI windows can be resized and remember their sizes and positions between sessions (config.ini entries). This seemed esp. useful for today's standard-size (FullHD) screens when the location panel map appeared too small. (I assume 4k users will esp. welcome the resize option). Your observation seems right that the size jumps to a minimum of the native size of the texture, I had not seen this as problematic. We should try to limit auto-resize to something like 0.9x screen size, so that the resize corners (bottom edges of all GUI screens) can still be reached on low-res screens.

**Comment by EuklidAlexandria** [comment]
Is it ok, if it is reverted back to a constant size like 0.9x screen size?

**Comment by gzotti** [comment]
Yes, I think so. Same should go for the other dialogs of course, so the StelDialog class should be fixed.
