### ISSUE TITLE
Trails leave straight lines when jumping to future or past dates

### ISSUE THREAD

**Issue by diegorodriguezperegrin** [Stellarium/stellarium#1030]
For instance, when you let comet Atlas (or I guess any other object) go forward while leaving a trail behind and then you jump to a past or future date instead of running fast forward or backwards, Stellarium draws a straight line from current position to the new one. If a correct trail is still present, Stellarium will add a straight line connecting both ends, creating an awkward look.

Since Stellarium is not able to draw trails correctly when jumping to dates, it should draw trails only when fast forward/backwards buttons are used. Object should jump to dates without leaving traces.

As a side feature requests, 1) a quick switch to enable/delete trails should be placed for easy access so user should not need to dig into the menus to active/deactivate them. Also, 2) a day marker along the trail will be of great help in planning observations.

Many thanks.

**Comment by alex-w** [comment]
Are you tried use AstroCalc/Ephemeris tool?

**Comment by diegorodriguezperegrin** [comment]
Oh, yes. AstroCalc/Ephemeris tool solves pretty well the day marker request, but the beautiful representation of the comet tails that tracing makes, and an easy on/off switch for it is still needed.

**Comment by alex-w** [comment]
What is the problem to uncheck show line and show markers checkboxes?

**Comment by gzotti** [comment]
OP wants fading trails with ephemeris date markers. We cannot serve everybody. However, trails should probably be cleared on every manual date jump. (Or every jump >1 day or so? Or FoV-depending?)

**Comment by diegorodriguezperegrin** [comment]
"Trails should probably be cleared on every manual date jump." No, they may be good to stay. I'd just limit trails to fast back/forth clock. Any other manual jump should leave no trail, simply because its path is unknown, and certainly not a straight line.

**Comment by gzotti** [comment]
Bad fix. Working...

**Comment by gzotti** [comment]
@diegorodriguezperegrin There seems no way for the program to decide whether a longer jump is intentional and an inaccurate straight-line connection accepted, or trails should be recreated. I added another user-configurable action to trigger reset of trails via hotkey, in addition to the existing hotkey that toggles trails. This should fulfill (1). Side request (2) has been fulfilled by the method of plotting ephemeris lines with date markers in the AstroCalc panel.
