### ISSUE TITLE
A cluster-like object may not exist?

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#1032]
I found a cluster-like object around HR6692 (HIP 88012) in Sgr when I was making a DSO hunting plan. However it doesnot get any DSO label. The cluster-like object looks like below. The star catalog for Stellarium is "Star catalogues, v2.0" (extended data).
![image](https://user-images.githubusercontent.com/32613953/78101928-915dbd00-741b-11ea-8e90-0000c2bda975.png)

The object looks like Jewel Box and NGC3293 in FOV = 0.29°.

As I removed "Star catalogues, v2.0", the same field looks like below. The same confuse may not exist in Standard Version of Stellarium.
![image](https://user-images.githubusercontent.com/32613953/78102257-7a6b9a80-741c-11ea-8a96-16c5d003a3aa.png)

I checked same filed in Sky Safari and did not found the same struct.

The size of the "cluster-like object" is 0°2'30''. I searched in SIMBAD, and got the result ranked as Mag V as below. 

![image](https://user-images.githubusercontent.com/32613953/78102729-9885ca80-741d-11ea-8487-879392b15eb4.png)

http://simbad.u-strasbg.fr/simbad/sim-coo?Coord=17+58+39.04983636+-28+45+32.7174625&Radius=3&Radius.unit=arcmin&submit=submit+query

**Comment by gzotti** [comment]
Seems like catalog makers can get confused in dense star fields. You can always switch on DSS to check for real DSOs.

**Comment by gzotti** [comment]
DSS shows the single star in a dense field. Simbad has no cluster. Again a few stars too many in the catalogs.
