### ISSUE TITLE
0.20.0: ANGLE mode broken.

### ISSUE THREAD

**Issue by JuHyeonmin** [Stellarium/stellarium#1034]
안녕하세요. 문제가 있습니다. 스텔라리움을 설치하고 실행하면 하얀 창만 뜨고 전체화면 실행이 안됩니다. 이게 왜 이런거죠?

**Comment by gzotti** [comment]
Google Translate is helpful.
I assume you are running some version of Windows, and some version of Stellarium 0.20.0 or 0.20.0.1 for Windows 32 or 64 bit. 
Please try to install proper drivers for your graphics card. It seems ANGLE mode is broken in version 0.20.
Alternatively, please install an older version.

**Comment by JuHyeonmin** [comment]
Google Translate is helpful. lf you install Stellarium, the graphics card driver is installed normally. How do I install the old version of Stellarium?

**Comment by JuHyeonmin** [comment]
And in the next update, please fix the bug as soon as possible.  I want to write it quickly !!

**Comment by JuHyeonmin** [comment]
그래픽 카드 업데이트는 최신입니다.

**Comment by gzotti** [comment]
Stellarium does not install graphics drivers for you. 
If you have a reasonably new graphics card (post-2008 GeForce/AMD, post-2010 Intel) with OpenGL drivers installed, Stellarium should run with OpenGL subsystem provided by the graphics card drivers that the manufacturer of the graphics card has created for this card. As we always write, your logfile would say which card you have. People with very old computers or those who never installed drivers for their graphics cards fall back to ANGLE, which appears to be broken at the moment. In the start menu, you also have an option with MESA, which is slow but stable. 
For an introduction, read https://github.com/Stellarium/stellarium/wiki/FAQ#opengl-issues. The FAQ contains a development history of the graphics problems for the later versions.

**Comment by JuHyeonmin** [comment]
When do you fix errors for this bug?

**Comment by JuHyeonmin** [comment]
It's a question, but the old version download speed is too slow.  Why is this like this?  It was fast when I downloaded the latest version ...

**Comment by alex-w** [comment]
Please check new beta - https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by gzotti** [comment]
Full success confirmed for the 64bit version. OpenGL, ANGLE/DirectX9, ANGLE/DirectX11, MESA work.

**Comment by gzotti** [comment]
OK, we can build and release Windows versions again with Qt5.13 (or Qt5.12) and this set of ANGLE libs (I think from Qt5.6):

md5sum
8084e5b1d0040063021930820ffc28f2  libEGL.dll
203fd0634d7c4c531ee8ae114c73316b  libGLESv2.dll

This should allow releases with Qt's AltGr support. Now let's hope Qt5.15 comes with good, or still plays with the old ANGLE libraries...
