### ISSUE TITLE
스텔라리움 아이콘이 투명합니다.

### ISSUE THREAD

**Issue by JuHyeonmin** [Stellarium/stellarium#1035]
안녕하세요. 스텔라리움 0.19 버전을 실행하고 시간을 설정하려는데 아이콘이 투명해서 안보입니다. 설정창도 안켜지고요 사진을 참고해주세요.
![20200405_130701](https://user-images.githubusercontent.com/63132883/78466651-9afa6400-773e-11ea-8790-b773b039f48b.jpg)

**Comment by gzotti** [comment]
Your system reports DirecX11 compliance, but you have not installed graphics card drivers, or your system is not able to perform as needed. Use the dedicated "Stellarium (ANGLE mode)" button in your start menu.

https://github.com/Stellarium/stellarium/wiki/FAQ#angle-mode

YOUR PROBLEMS WILL PERSIST UNLESS YOU INSTALL PROPER GRAPHICS CARD DRIVERS.

**Comment by JuHyeonmin** [comment]
Later, the Direct X version was the Direct X 12 version. Please make sure to support version 12 when you update later.

**Comment by gzotti** [comment]
We did not develop ANGLE. Qt uses it as fallback on systems where the user has not installed GPU drivers, or where graphics hardware is incapable of delivering proper OpenGL support. ANGLE uses either DirectX9 or 11. "Stellarium (ANGLE mode)" forces version 9 and usually works.  

You still have not told us which graphics system you have, so we cannot give any further advice. If nothing works, use "Stellarium (MESA mode)".

**Comment by alex-w** [comment]
Please check new beta - https://github.com/Stellarium/stellarium-data/releases/tag/beta
