### ISSUE TITLE
Star directories are not loaded.

### ISSUE THREAD

**Issue by blacksaber91** [Stellarium/stellarium#1037]
### 

### Actual Behaviour
Describe or maybe attach a screenshot?

### Steps to reproduce
1) click settings
2) additional
3)getting the catalog 5 of 9

### System
* Stellarium version: Stellarium-0.20.0.1-win64
* Operating system: Microsoft Windows 7 Professional x64, OS version 6.1.7601.24545
* Graphics Card: NVIDIA, Model: Nvidia GeForce GT 630 (2 GB), DRIVER VERSION 23.21.13.9135
* Screen type (if applicable): LG w2261 (Digital) [22" LCD] (191195468)

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/4439456/log.txt)

**Comment by gzotti** [comment]
Is this really the logfile from the run where download was attempted?

**Comment by alex-w** [comment]
Please check v0.90.0.17814 - https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by blacksaber91** [comment]
Yes, during installation. As soon as I get home, I'll try and unsubscribe.19:09, 6 апреля 2020 г., Georg Zotti <notifications@github.com>:
Is this really the logfile from the run where download was attempted?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
С Уважением, Николай.Специалист IT-систем.+79625490833 (whatsapp & viber)instagramm: @nikola116russkype: nicksab1491

**Comment by blacksaber91** [comment]
I checked the beta version, but there is no problem.  07.04.2020, 14:04, "blacksaber91" <79625490833@yandex.ru>:Yes, during installation. As soon as I get home, I'll try and unsubscribe.19: 09, April 6, 2020, Georg Zotti < notifications@github.com>: Is this really the logfile from the run where download was attempted?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.With Respect, Nikolai.It systems specialist.+79625490833 (whatsapp & viber)instagramm: @nikola116russkype: nicksab1491  -- With respect,Nikolay Sabelnikov+79625490833 (cell and Whatsapp)skype:nicksab1491instagramm: @nikola116rus
