### ISSUE TITLE
Control Stellarium view remotely from IMU and GPS sensors via TCP

### ISSUE THREAD

**Issue by mgrouch** [Stellarium/stellarium#1038]
Control Stellarium view remotely from IMU and GPS sensors via TCP

I'd like to put Stellarium into a boat cockpit display and run
it as augmented reality app. The boat has IMU and GPS sensors
roll/pitch/yaw  heading and GPS location. All realtime changing.
I need a way to control Stellarium View on the cockpit display
with these real-time values. Some signle line TCP/IP protocol or something would be nice. (Boat use NMEA sentences)

It's going to help locating satellite for antennas and serve as validation tool for IMU magnetormenter readings.

Thanks,
--MG

**Comment by gzotti** [comment]
There is the RemoteControl HTTP API. Just set position and heading. See chapter 12.6 in the Stellarium User Guide.

**Comment by mgrouch** [comment]
I have Stellarium 0.18.3 on raspberry pi buster and there
is no RemoteControl in settings. Do I have to install this plugin somehow separately?

Thanks

**Comment by gzotti** [comment]
See chapter 11.1 in the Stellarium User Guide.

**Comment by mgrouch** [comment]
>See chapter 11.1 in the Stellarium User Guide.

That's exactly what I was doing. The plugin is not there

**Comment by gzotti** [comment]
Did you build Stellarium from source or did you install from some repository? I don't know if the plugin has been left away from RPi builds. Building on RPi 3 and 4 works well, see instructions in the wiki. (Basically, follow Linux build instructions, and expect problems with Scenery3D and surveys, but I am not aware of issues with RemoteControl.)

**Comment by gzotti** [comment]
Just checked: Plugin activated on my RPi4, and works in the webbrowser. I have built Stellarium following the Linux build instructions in the wiki (just command line, cmake/make.).

**Comment by mgrouch** [comment]
If I build from source I get this compile error


[ 23%] Building CXX object plugins/Scenery3d/src/CMakeFiles/Scenery3d-static.dir/Scenery3d.cpp.o
In file included from /home/pi/stellarium-0.19.3/plugins/Scenery3d/src/S3DRenderer.hpp:24,
                 from /home/pi/stellarium-0.19.3/plugins/Scenery3d/src/Scenery3d.cpp:35:
/home/pi/stellarium-0.19.3/src/gui/StelGui.hpp:30:10: fatal error: QGraphicsTextItem: No such file or directory
 #include <QGraphicsTextItem>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

Thanks

**Comment by mgrouch** [comment]
Same error when I try 0.20.0

**Comment by gzotti** [comment]
Did you install all dependencies?  
https://github.com/Stellarium/stellarium/wiki/Linux-build-dependencies

**Comment by mgrouch** [comment]
Yes using this command from that link

 sudo apt-get install build-essential cmake zlib1g-dev libgl1-mesa-dev gcc g++ \
      graphviz doxygen gettext git \
      qtscript5-dev libqt5svg5-dev qttools5-dev-tools qttools5-dev \
      libqt5opengl5-dev qtmultimedia5-dev libqt5multimedia5-plugins \
      libqt5serialport5 libqt5serialport5-dev qtpositioning5-dev libgps-dev \
      libqt5positioning5 libqt5positioning5-plugins

**Comment by mgrouch** [comment]
-- Configuring done
CMake Error in plugins/Scenery3d/src/CMakeLists.txt:
  Imported target "Qt5::Gui_EGL" includes non-existent path

    "/usr/include/libdrm"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in plugins/Scenery3d/src/CMakeLists.txt:
  Imported target "Qt5::Gui_EGL" includes non-existent path

    "/usr/include/libdrm"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in plugins/Scenery3d/src/CMakeLists.txt:
  Imported target "Qt5::Gui_EGL" includes non-existent path

    "/usr/include/libdrm"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

**Comment by mgrouch** [comment]
Looks like 

sudo apt-get install libdrm-dev

was missing in instructions

**Comment by gzotti** [comment]
Strange. Maybe those had been included previously as automatic dependencies. I updated the line in the wiki, thanks.

**Comment by gzotti** [comment]
@mgrouch did that solve your issue, and can we close it?

**Comment by mgrouch** [comment]
I've got it somewhat working. However I do not read directly from IMU. I use NMEA sentences from autopilot for heading.
It's not fast and sensitive enough to be called augmented reality app. Good enough for a boat keeping steady course.
Is there some kind of native IMU plugin in stellarium?
Thanks

**Comment by gzotti** [comment]
No.

> There is the RemoteControl HTTP API. Just set position and heading.
