### ISSUE TITLE
Error when searching for an object in the online service ephemerides of minor planets and comets

### ISSUE THREAD

**Issue by blacksaber91** [Stellarium/stellarium#1039]
### Expected Behaviour
The service searches for Ephemerides of minor planets and comets in the online service.
### Actual Behaviour
![2020-04-09 15-16-07](https://user-images.githubusercontent.com/22714555/78894748-504a5600-7a76-11ea-8fdc-2900c5518950.JPG)

### Steps to reproduce
1) Go to the settings of the solar system plugin. 
2) Import orbital elements in MPC format
3) "Search online" tab"
4) And typing in the search bar is what I need.

System
Stellarium version: Stellarium-0.20.0.1-win64
Operating system: Microsoft Windows 7 Professional x64, OS version 6.1.7601.24545
Graphics Card: NVIDIA, Model: Nvidia GeForce GT 630 (2 GB), DRIVER VERSION 23.21.13.9135
Screen type (if applicable): LG w2261 (Digital) [22" LCD] (191195468)
### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/4456083/log.txt)

**Comment by alex-w** [comment]
Please check new beta - https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by blacksaber91** [comment]
There was a big problem on beta. 09.04.2020, 15:39, "Alexander Wolf" <notifications@github.com>: Please check new beta - https://github.com/Stellarium/stellarium-data/releases/tag/beta—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  -- With respect,Nikolay Sabelnikov+79625490833 (cell and Whatsapp)skype:nicksab1491instagramm: @nikola116rus

**Comment by alex-w** [comment]
В каком смысле это большая проблема в бете?

**Comment by blacksaber91** [comment]
Sorry, I wrote it wrong. This problem is also observed in beta. 10.04.2020, 23:21, "Alexander Wolf" <notifications@github.com>: In what sense is this a big problem in beta?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  -- With respect,Nikolay Sabelnikov+79625490833 (cell and Whatsapp)skype:nicksab1491instagramm: @nikola116rus

**Comment by alex-w** [comment]
This is definitely not Stellarium problem, because MPC website will give no ephemeris for "c/2019 y4" object, because MPC known nothing about it. But it will search and get data for "C/2019 Y4" - apparently search engine on MPC website case sensitive now.
