### ISSUE TITLE
download

### ISSUE THREAD

**Issue by clementmarcotte** [Stellarium/stellarium#104]
Habitual Git-Hub incompétence. They stop download at 148/171 MB. Impossible tu resume. Retry from scratch. Git-Hub shit again.
GO TO HELL. I prefer forget stellarium
Upset of Git-Hub.
Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.Upset of Git-Hub.

**Comment by gzotti** [comment]
SEP
