### ISSUE TITLE
Linux Ubuntu Nvidia GTX 1080 App Crash/Hangs on Launch

### ISSUE THREAD

**Issue by csharpee** [Stellarium/stellarium#1040]
### Expected Behaviour
Application loads and populates configuration files

### Actual Behaviour
Describe or maybe attach a screenshot?
On opening of Stellarium-0.20.0-x86_64.AppImage, the splash screen loads and a small window box appears.

Note: This was working without any trouble. I updated packages today and recently upgraded GCC and installed Qt5

### Steps to reproduce
Open / Run app.image

### System
* Stellarium version: Stellarium-0.20.0-x86_64.AppImage & Stellarium-0.19.3-x86_64.AppImage
* Operating system: Linux Pop!_OS 19.10 (Ubuntu)
* Graphics Card: Nvidia  GeForce GTX 1080

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/4458501/log.txt)

### journalctl -f 

Apr 09 16:24:56 name org.gnome.Nautilus[2485]:  -----------------------------------------------------
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: [ This is Stellarium 0.20.0 - https://stellarium.org/ ]
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: [ Copyright (C) 2000-2020 Fabien Chereau et al.       ]
Apr 09 16:24:56 name org.gnome.Nautilus[2485]:  -----------------------------------------------------
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: Writing log file to: "/home/name/.stellarium/log.txt"
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: File search paths:
Apr 09 16:24:56 name org.gnome.Nautilus[2485]:   0 .  "/home/name/.stellarium"
Apr 09 16:24:56 name org.gnome.Nautilus[2485]:   1 .  "/tmp/.mount_Stella9dzR0O/usr/bin/../share/stellarium"
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: Config file is:  "/home/name/.stellarium/config.ini"
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: StelGLWidget constructor
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: StelGraphicsScene constructor
Apr 09 16:24:56 name kernel: NVRM: API mismatch: the client has the version 440.64, but
                             NVRM: this kernel module has the version 440.44.  Please
                             NVRM: make sure that this kernel module and all NVIDIA driver
                             NVRM: components have the same version.
Apr 09 16:24:56 name kernel: NVRM: API mismatch: the client has the version 440.64, but
                             NVRM: this kernel module has the version 440.44.  Please
                             NVRM: make sure that this kernel module and all NVIDIA driver
                             NVRM: components have the same version.
Apr 09 16:24:56 name kernel: NVRM: API mismatch: the client has the version 440.64, but
                             NVRM: this kernel module has the version 440.44.  Please
                             NVRM: make sure that this kernel module and all NVIDIA driver
                             NVRM: components have the same version.
Apr 09 16:24:56 name kernel: NVRM: API mismatch: the client has the version 440.64, but
                             NVRM: this kernel module has the version 440.44.  Please
                             NVRM: make sure that this kernel module and all NVIDIA driver
                             NVRM: components have the same version.
Apr 09 16:24:56 name kernel: NVRM: API mismatch: the client has the version 440.64, but
                             NVRM: this kernel module has the version 440.44.  Please
                             NVRM: make sure that this kernel module and all NVIDIA driver
                             NVRM: components have the same version.
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: QOpenGLWidget: Failed to create context
Apr 09 16:24:56 name kernel: NVRM: API mismatch: the client has the version 440.64, but
                             NVRM: this kernel module has the version 440.44.  Please
                             NVRM: make sure that this kernel module and all NVIDIA driver
                             NVRM: components have the same version.
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: QPainter::begin: Paint device returned engine == 0, type: 1
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: QPainter::setRenderHint: Painter must be active to set rendering hints
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: QPainter::worldTransform: Painter not active
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: QPainter::save: Painter not active
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: QPainter::restore: Unbalanced save/restore
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: QPainter::setWorldTransform: Painter not active
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: QPainter::end: Painter not active, aborted
Apr 09 16:24:56 name org.gnome.Nautilus[2485]: composeAndFlush: makeCurrent() failed
Apr 09 16:24:58 name org.gnome.Nautilus[2485]: composeAndFlush: makeCurrent() failed
Apr 09 16:24:58 name org.gnome.Nautilus[2485]: composeAndFlush: makeCurrent() failed
Apr 09 16:25:01 name kernel: AppRun[30359]: segfault at 8 ip 00007ffbb5dd7e60 sp 00007ffe4e10eab8 error 4 in libQt5Core.so.5[7ffbb5b34000+52e000]
Apr 09 16:25:01 name kernel: Code: 66 2e 0f 1f 84 00 00 00 00 00 53 48 89 fb e8 37 fc ff ff 48 89 df be 70 00 00 00 5b e9 c9 4f 0b 00 90 0f 1f 84 00 00 00 00 00 <48> 8b 47 08 f6 40 20 02 0f 85 9a 05 00 00 55 48 89 e5 41 57 41 56

**Comment by gzotti** [comment]
> NVRM: API mismatch: the client has the version 440.64, but
> NVRM: this kernel module has the version 440.44. Please
> NVRM: make sure that this kernel module and all NVIDIA driver
> NVRM: components have the same version.

Do other OpenGL applications work?

**Comment by csharpee** [comment]
No.

**Comment by gzotti** [comment]
It's obvious that you must fix your graphics drivers. There are certainly other GeForce users out there and respective user forums to find advice.

**Comment by csharpee** [comment]
After restart, the app launches as expected.

**Comment by gzotti** [comment]
Good. Please try such "fixes" first next time.
