### ISSUE TITLE
Jerky animation

### ISSUE THREAD

**Issue by NotSoRandomOne** [Stellarium/stellarium#1041]
#601 # Actual Behaviour
If I lock onto a planet, like Mars, then hit 'J' or 'L' a few times, to speed up or reverse the time flow, the animation is real jumpy, about one jump every second or so.  I've never seen it in Stellarium before.  I had made the ground invisible, and eliminated the fog and atmosphere, if that has anything to do with it, but toggling those doesn't seem to affect the problem. Only right-clicking on the background, to un-lock the currently locked object, makes the animation go smoothly again.

### Steps to reproduce
Open Stellarium, left click on the moon or a planet, then speed up the timeflow with 'J' a few times.

### System
* Stellarium version: 0.20.0
* Operating system: Win10
* Graphics Card: NVidia 960M

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/4459800/log.txt)

**Comment by gzotti** [comment]
Yes, it's a side effect of listing "hourly motion". Go into settings/Info and click away "Proper Motion". Currently I don't see a better solution.
