### ISSUE TITLE
Solar transit time is shown as 12h60m instead of 13h00m

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#1042]
How to reproduce:
1. Go to Saint Petersburg
1. Set time 2020-04-10 13:00:00 MSK
1. Select the Sun
1. In the information text see "Transit: 12h60m"

At 12:59:21 it's still "Transit: 13h00m" as expected, while at 12:59:22 it's already broken.

![stel](https://user-images.githubusercontent.com/6376882/78978494-86451400-7b22-11ea-9fef-3440b5a4397e.png)

**Comment by axd1967** [comment]
A bit late, but exceptionally it can happen that we see a 60 seconds display, think of the leap second.
