### ISSUE TITLE
Tracking telescope position

### ISSUE THREAD

**Issue by MasterPIC** [Stellarium/stellarium#1044]
Hi,
I'm thinking about two nice features:
1. periodic refresh (with user-defined refresh rate) of telescope position;
2. option to keep the chart centered on telescope position (to track the telescope).

CS
Armando

**Comment by gzotti** [comment]
You are thinking about them...

in the sense of contributing, or that somebody else should make it?

**Comment by MasterPIC** [comment]
Hi,
I just updated Stellarium and I found the features I was thinking about are already implemented. :D
Clear Skies!
Armando
