### ISSUE TITLE
Incorrect application of display gamma in ToneReproducer and associated shader

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#1047]
Display gamma applies to each of RGB color channels. Yet, `ToneReproducer` and `xyYToRGB.glsl` shader only apply it to luminance, leading to overly saturated colors.

This was particularly noticeable when I was using my (old) implementation of Bruneton's atmosphere in Stellarium (the `atmosphere` branch; now it's fixed) and wondering why it looks so much bluer than the sky outdoors, while the photos by a DSLR rendered on my calibrated monitor had more natural-looking color.

I've made a fix in my [`tone-reproducer-gamma-fix` branch](https://github.com/10110111/stellarium/tree/tone-reproducer-gamma-fix) (commit https://github.com/10110111/stellarium/commit/13d84cf6925c73346061d62d8f63f5d94feb3f17), but apparently the current Preetham's atmosphere model has been somewhat fine-tuned for the original mistaken tone reproducer (or maybe I've missed some other places where gamma is applied similarly incorrectly), so its colors are now blown out. So it'll have to be re-tuned for the corrected behavior of tone reproducer.

**Comment by alex-w** [comment]
Please propose PR

**Comment by 10110111** [comment]
My fix is incomplete. Do you really want a PR that leads to blown-out colors?

**Comment by alex-w** [comment]
> My fix is incomplete. Do you really want a PR that leads to blown-out colors?

Oh, no!

**Comment by gzotti** [comment]
Interesting. I have not looked into the topic and code for years but I would expect xyY MUST apply gamma only to the Y channel, before converting to (s)RGB?
On Preetham colors: my GZ_AtmosphereTweak branch had some experimental GUI to tweak the values. I also noted a discrepancy between Preetham's preprint available online, and the values as used in Stellarium.  But i don't have the final paper, so this remained an unsolved question. Also, I saw XYZ->AdobeRGB values in the converter, which was also questionable.  Or maybe it's that XYZ->AdobeRGB that causes oversaturation?

**Comment by 10110111** [comment]
> I would expect xyY MUST apply gamma only to the Y channel

Since gamma is a property of display, it doesn't make sense anywhere outside the display-specific color space. In the most common case it's sRGB, which is _the_ specification that introduced this nonlinearity in the first place. Others like Display P3 just followed sRGB in this. And given the fact that gamma application is a nonlinear operation, you can't apply it in any other color space to get the same result.

> Also, I saw XYZ->AdobeRGB values in the converter, which was also questionable. 

This was addressed in #718 and shouldn't be a problem now (unless some places were missed).

> Or maybe it's that XYZ->AdobeRGB that causes oversaturation?

I think it'd actually cause undersaturation, since the values for a larger color space would be displayed on a display capable of only smaller saturations.

**Comment by gzotti** [comment]
Ah yes, you brought it back, thanks. There was also some discontinuity in low brightness in the sRGB conversion. Question remains whether the values in Stellarium's implementation of Preetham have been modified from the original paper. I had concluded to continue improvements after fixing positions first. Still stuck in there and other areas... Thanks if you are improving further here.
