### ISSUE TITLE
no option to remove halo around stars

### ISSUE THREAD

**Issue by alexandervlpl** [Stellarium/stellarium#105]
There's a handy `halo` option to render bright solar system objects without a halo. Can you please add the same option for stars?

Currently bright stars are rendered with a large halo:
![halo](https://user-images.githubusercontent.com/8945883/36340406-48d35aee-13ed-11e8-917e-012e673743c0.png)

Part of this is the "glow" effect in the star texture file (star16x16.png), which is fine. But a large area of sky around the star is lighter too. It would be nice to have an option to disable this.

**Comment by gzotti** [comment]
This is by intention to highlight bright stars which else would need even larger disks or will appear too dim. What do you think is disturbing with this solution?

**Comment by alex-w** [comment]
Size of halo around stars may be customized by adjusting relative scale in stars section of sky tab - why you do not use this option?

**Comment by alexandervlpl** [comment]
@gzotti I know there's a purpose for this, but the effect can be distracting and unrealistic sometimes. This is probably why there is a `halo` option for solar system objects, right? Seems logical to have one for stars too.

@alex-w I've tried adjusting both relative and absolute scale in `config.ini`. To remove the halo effect completely for bright stars, the values have to be very low and many stars become way too small.

**Comment by alex-w** [comment]
@alexandervlpl seems you want to get an SkyChart behaviour in Stellarium - why you just do not use SkyChart in this case? Just for understanding - Stellarium never set the goal to be a cartographic planetarium (like SkyChart/Cartes du Ciel). The main goal of Stellarium is realistic sky.

**Comment by alexandervlpl** [comment]
@alex-w For me the glow actually makes the sky *less* realistic, especially at high resolutions when absolute and relative scale need to be increased. Maybe it's just my eyes.

I chose Stellarium over other tools exactly because the visuals are better and there are many options to customize them for any requirements and tastes. A star `halo` option would be a great addition to this. I'll be happy to see it in `config.ini`, no need to add it to the GUI.

**Comment by gzotti** [comment]
Just compiling to see how bad it will look...

**Comment by gzotti** [comment]
Looks bad, but we also allow twinkling in space so I will allow it via config.ini [star] / flag_star_halo=false. I won't bother with a GUI checkbox.

**Comment by alexandervlpl** [comment]
Perfect, thanks again @gzotti !

**Comment by gzotti** [comment]
Done.
