### ISSUE TITLE
Messier objects not filtered properly

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1052]
When showing DSO catalogs, some objects are still visible even though they shouldn't be. For example, show ONLY the Messier catalog, and you'll get a few  other DSO's visible (Dark Doodad Nebula in Musca and an object of unknown nature in Pisces, for example). See this screenshot:

<img width="1920" alt="stellwrong" src="https://user-images.githubusercontent.com/37028368/79598573-82962c00-80e4-11ea-905d-3c1989b5ac48.png">

BTW I don't think this "object of unknown nature" exists, because it happens to lie exactly on the vernal equinox point (J2000.0). A bug of some sort?

It is possible that other catalogs suffer from the same bug. I have not tested this thoroughly.

**Comment by alex-w** [comment]
A few objects are well-known and has names only (without designations) - are you proposes delete them?

**Comment by Atque** [comment]
@alex-w Well, if I choose only to see the Messier catalog, I would like to ONLY see Messier objects. :)

**Comment by gzotti** [comment]
Indeed, there is one at 0/0 in J2000 that is obviously some error.

**Comment by alex-w** [comment]
> @alex-w Well, if I choose only to see the Messier catalog, I would like to ONLY see Messier objects. :)

When you enable M and IC then you expect see objects, who exist in both catalogs only?

**Comment by gzotti** [comment]
(M || IC) but not "other". Probably we need that "other" category.
