### ISSUE TITLE
Angle Measure: retain starting point with SHIFT CLICK

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1053]
### Expected Behaviour
In earlier versions of Stellarium, it was possible to move the endpoint of the Angle Measure tool while keeping the start point fixed (this is not related to the "attach" feature).

This allows to search for specific points at specific distances without having to re-select the start point.

### Actual Behaviour
The AM no longer allows this.

### Steps to reproduce

1. enable AM module
1. left click a point to designate the start point
1. drag to some endpoint
1. LEFT CLICK on a different endpoint

Bug: the start point is moved to the last clicked point.

### System
* Stellarium version: 0.20
* Operating system: Kubuntu 18
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Define "earlier version"? The last real change was around 2014.
Click RIGHT to set a new endpoint.

**Comment by alex-w** [comment]
At least since version 0.10.6 (this is oldest version, which I had installed) the right click set a new endpoint and no exist the "shift + left click" combination.

**Comment by axd1967** [comment]
yes, it is my mistake - right-click moves the endpoint.
