### ISSUE TITLE
The horizon line does not appear. 0.20.0

### ISSUE THREAD

**Issue by mooadshaqour** [Stellarium/stellarium#1054]
![note](https://user-images.githubusercontent.com/63922964/79644568-7d071780-81b2-11ea-92ff-65b28f798d15.png)

**Comment by gzotti** [comment]
You configured to show labels on the horizon partitions (right checkbox), IF you had switched on partitions (center column), IF you had switched on horizon line (left checkbox). The tooltips which should appear when holding the mouse over it should help understanding what is what. Section 4.4.4 in the Stellarium User Guide also mentions this.
