### ISSUE TITLE
feature wish - celestial sphere export to dae / collada

### ISSUE THREAD

**Issue by teamobjective** [Stellarium/stellarium#106]
I'm building an iphone app - and have been digging into unity / collada / dae / obj models.
While it's possible to import simple objects - I'm looking to export the spheres in this view 

so I can import into xcode - 
<img width="328" alt="screen shot 2018-02-19 at 5 08 26 pm" src="https://user-images.githubusercontent.com/290152/36398941-869fab74-1597-11e8-82e5-3e4e96c9ec66.png">

the names / labels would be individual items allow me to make them the right way up 

![](https://user-images.githubusercontent.com/289994/33522013-19211aee-d7b0-11e7-8973-b56695de8e97.png)

**Comment by teamobjective** [comment]
or maybe - just export to star map - ![starmap_1_reflect_v4_02](https://user-images.githubusercontent.com/290152/36399027-ff957d2e-1597-11e8-83b0-03bd883eb769.png)

**Comment by gzotti** [comment]
Given the Open-Source aspect of this project, you can look into the code here to understand what we are doing. If you want to develop an App, *you* are the developer. Don't expect us to do your work.

If I understand your sketch, all you may need to export static snapshots will be a script that sets projection, view direction and does a snapshot. Look into the script examples for script examples.

**Comment by teamobjective** [comment]
thanks gzotti
