### ISSUE TITLE
Scripting: Can we change the texture of an object dynamically within a script

### ISSUE THREAD

**Issue by MRSPlanetarium** [Stellarium/stellarium#1060]
Question/Feature request.

**Scenario** 
When looking at certain objects it would be useful to be able to switch between the textures used from within a script. For example looking at Venus being able to switch between the cloudscape, to a surface map to a false colour topographical map or when viewing Earth take the continents back to Pangaea.

Similarly could be used for the Sun to show the Sun at difference wavelengths of the electromagnetic spectrum etc. 

I've search through gitHub, the manual and the scripting pages but can't find anything which is simply evidence that I didn't see it.

Advice please.

Thanks

Nigel
Mark Rutherford School
Bedford
UK

**Comment by gzotti** [comment]
Currently there is no such functionality. It would help if there were free textures to use.
Pangaea makes not much sense IMO. Date range is limited to +/-100.000 years, and planet positions will be outside valid range much earlier. Glacial sea-level changes could be nice, if anybody could provide them.

**Comment by t4saha** [comment]
Seasonal Texture for the Earth is available in NASA Blue Marble collection. https://visibleearth.nasa.gov/collection/1484/blue-marble

**Comment by MRSPlanetarium** [comment]
> Currently there is no such functionality. It would help if there were free textures to use.
> Pangaea makes not much sense IMO. Date range is limited to +/-100.000 years, and planet positions will be outside valid range much earlier. Glacial sea-level changes could be nice, if anybody could provide them.

I agree Pangaea makes no sense astronomically but this was only there as a side project of mine as I wanted an animation that I can control for teaching plate tectonics so was going to piggy back this on Stellarium if you do offer the dynamic textures feature. There are plenty of copyright free images that can be used.
So please don't get hung up on Pangaea as this only makes sense in a teaching environment but being able to use topographical maps of the various planets would be useful.

**Comment by MRSPlanetarium** [comment]
> Seasonal Texture for the Earth is available in NASA Blue Marble collection. https://visibleearth.nasa.gov/collection/1484/blue-marble

Yes these are nice, I'll admit to using one of these as my Earth texture.
