### ISSUE TITLE
Stellarium incompatible with Zoom Meeting?

### ISSUE THREAD

**Issue by WA-Ray** [Stellarium/stellarium#1062]
Stellarium incompatible with Zoom Meeting?

### Actual Behaviour  Stellarium opens in screen sharing and attendees see the first screen, but as I demo it their meeting attendee screens do not update.  Lightroom, Photoshop, PowerPoint all worked fine in Zoom screen share.  

Describe or maybe attach a screenshot?  n/a

### System
* Stellarium version: 0.19.3.0 installed this Feb/Mar
* Operating system: Win 10, current
* Graphics Card: NVIDIA GeForce GTX 1660 Ti
* Screen type (if applicable):  laptop screen

### Logfile   n/a
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
If Zoom does not forward an OpenGL window, it's a Zoom issue.

**Comment by WA-Ray** [comment]
Thanks.  I will certainly pass this to the Zoom support folks.  Given the huge increase in Zoom usage during the covid-19 crisis, which is sure to change the mix of how technical meetings will be done going forward, it might be in the interest of the Stellarium community to have this pursued as a bug fix.  
 
Sincerely,
 
Bill
 
-----Original Message-----

**Comment by gzotti** [comment]
No bug to fix. I just had a meeting with my other account and transferred Stellarium as produced on a Geforce M960 and seen in OpenGL, ANGLE and Spout receiver windows to another laptop with Geforce 580GTX. Just that data transfer takes ages over a slow line. You cannot compare Stellarium to an Excel sheet. Try to transfer some fast-paced ego shooter. I doubt Zoom was developed for that. Just prepare a few screenshots and show them.

**Comment by WA-Ray** [comment]
Does this look like the correct setup?
 
 
 
 
-----Original Message-----

**Comment by WA-Ray** [comment]
Sorry, too quick -- here is the driver setup -- is this current?

 
-----Original Message-----From: "Georg Zotti" <notifications@github.com>Sent: Friday, April 24, 2020 7:28amTo: "Stellarium/stellarium" <stellarium@noreply.github.com>Cc: "WA-Ray" <billray@apian.com>, "Author" <author@noreply.github.com>Subject: Re: [Stellarium/stellarium] Stellarium incompatible with Zoom Meeting? (#1062)

No bug to fix. I just had a meeting with my other account and transferred Stellarium as produced on a Geforce M960 and seen in OpenGL, ANGLE and Spout receiver windows to another laptop with Geforce 580GTX. Just that data transfer takes ages over a slow line. You cannot compare Stellarium to an Excel sheet. Try to transfer some fast-paced ego shooter. I doubt Zoom was developed for that. Just prepare a few screenshots and show them.
