### ISSUE TITLE
satellite group not saved by default, no warning issued

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1066]
### Expected Behaviour
when I create a satellite group, i expect this group to be remembered (OR some warning issued that I will LOSE data when I close Stellarium).

### Actual Behaviour
when I close Stellarium, newly created sat groups are not saved unless the plugin  button "settings > save as default" is clicked.

### Steps to reproduce
1. create a group
1. quit stellarium

### System
* Stellarium version:0.20.1
* Operating system:KUBUNTU
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Having to save most preferences or settings explicitly has been the way this program works probably since its inception. This is apparently by design, whether you personally like it or not.

**Comment by alex-w** [comment]
The behaviour for saving changes of satellites properties has been changes in master and probably this report is fixed already - please check it.

**Comment by alex-w** [comment]
Please check version 0.20.2.18113

**Comment by axd1967** [comment]
hasn't been happening for a while. I suspect that this was the result of code refactoring.

**Comment by alex-w** [comment]
I've checked right now - it works as expected
