### ISSUE TITLE
Rich Field Objects and Further

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#1067]
These Objects are funny, and useful for identify the structure of the Milky Way.
However rare of them are bound to existing DSO in catalogue. I also found some incorrectly points to the false objects, such as "Baade's Window" <--> "NGC 6522", although sometimes we only use it to locate the accurate field even if we known some problems with them. I advise to create a new feature code for recognizing them, such as "Region objects" (Large Sagittarius Cloud etc.) or "multi objects" (Burbidge Chain, Makarian's Chain ..).

here is part of the Rich Field Objects:
```
Scutum Star Cloud
Large Sagittarius Star Cloud
Norma Star Cloud (NGC 6067 and NGC 6188)
Cygnus Star Cloud (Maybe diff from existing sh2-101's mark)
the Great Rift
Baade's Window
the Prancing Horse Nebula
Funnel Cloud
```

![image](https://user-images.githubusercontent.com/32613953/80308138-c6cdae80-87ff-11ea-9716-16b7998ce1f0.png)
![image](https://user-images.githubusercontent.com/32613953/80308150-dbaa4200-87ff-11ea-9b60-efca7464339c.png)

reference:
https://skyandtelescope.org/observing/a-trip-down-the-great-rift/
Observing the milky way, part I: Sagittarius & Scorpius
https://www.cloudynights.com/topic/565226-classic-rich-field/

Further Rich Field Objects and so on:
1. OB Association (Alter, G., Balazs, B., and Ruprecht, J.  1970, Catalogue of Star Clusters and Associations, 2nd Edition)
2. Gould Belt
3. Arms of the Milky Way

**Comment by alex-w** [comment]
Could you prepare outlines for those regions?

**Comment by ultrapre** [comment]
> Could you prepare outlines for those regions?
It's processing.. I will give groups of RA Dec format as outlines.dat. Clockwise or anti-clockwise is allowed ?

**Comment by alex-w** [comment]
We use same format for outlines as in CdC and OpenNGC

**Comment by ultrapre** [comment]
> We use same format for outlines as in CdC and OpenNGC

Any else need except recording the (RA,Dec) below? 

![image](https://user-images.githubusercontent.com/32613953/80799472-7f696880-8bd9-11ea-9f64-118f06b0083f.png)

**Comment by alex-w** [comment]
See outlines.dat or, better, Stellarium User Guide for prepare complete outlines data

**Comment by ultrapre** [comment]
> See outlines.dat or, better, Stellarium User Guide for prepare complete outlines data

The test is okay, enter the direct below, outlines.dat is the append data, the Map.txt is the mapping file. outlines seems to not show when not binding to an existing object, so the next work need your help..

https://github.com/ultrapre/DSO/tree/master/%E5%85%B6%E4%BB%96/outlines

**Comment by alex-w** [comment]
I've checked your outlines and your collection is not acceptable to merge because outlines has a very small number of points and it looks weird. I think enabling HiPS/DSS layer (or TOAST/DSS) will be very helpful for you + please check S&T and Astronomy Magazines.

Important note: in next beta you may attach outlines directly to the DSO regions

**Comment by ultrapre** [comment]
> I've checked your outlines and your collection is not acceptable to merge because outlines has a very small number of points and it looks weird. I think enabling HiPS/DSS layer (or TOAST/DSS) will be very helpful for you + please check S&T and Astronomy Magazines.
> 
> Important note: in next beta you may attach outlines directly to the DSO regions

Thanks for your checks. I will soon make more points for a more detailed shape. About attaching outlines directly to the DSO regions, umm.. how to operate and can it be used for this work?

**Comment by alex-w** [comment]
>About attaching outlines directly to the DSO regions, umm.. how to operate and can it be used for this work?

The outlines are similar regular DSO, but using inner number for "designation" part of outline. For example you need set number 39 for Baade's Window (see names.dat file - numbers 39-47)

**Comment by ultrapre** [comment]
> > About attaching outlines directly to the DSO regions, umm.. how to operate and can it be used for this work?
> 
> The outlines are similar regular DSO, but using inner number for "designation" part of outline. For example you need set number 39 for Baade's Window (see names.dat file - numbers 39-47)

I have updated [outlines](https://github.com/ultrapre/DSO/tree/master/%E5%85%B6%E4%BB%96/outlines) again, please check again. 

I have finished the marks below:
```
     39              _("Baade's Window") # WP, SIMBAD
     40              _("Funnel Cloud Nebula") # ST6
     41              _("Northern Coalsack") # ST6
	 
     43              _("Scutum Star Cloud") # ST6
     44              _("Small Sagittarius Star Cloud") # ST6
     45              _("Patchy unnamed cloud") # ST6
     46              _("Large Sagittarius Star Cloud") # ST6
     47              _("Cygnus Star Cloud") # ST6

     ??              _("Norma Star Cloud") # 
     ??              _("the Prancing Horse Nebula") # 
```

names.dat still lack two objects below:
Norma Star Cloud
the Prancing Horse Nebula

My outlines except "the Great Rift", because it is difficult to define.

**Comment by alex-w** [comment]
Thank you very much for very good outlines! Maybe you will have some free time to improve other outlines?

**Comment by ultrapre** [comment]
> Thank you very much for very good outlines! Maybe you will have some free time to improve other outlines?

Sure. I am also looking into a scientific database for the outlines because measuring manually lacks accuracy. If you knew something above, let me know please.
