### ISSUE TITLE
Adding opitional Lat & Long and N & S pole grid lines to planets & moon(s)

### ISSUE THREAD

**Issue by Ironman65** [Stellarium/stellarium#1068]
This would be a nice and useful feature if possible and hopefully might not cause the program to crash. That is to add Lat & Long grid lines with the N & S pole lines to the Planets & Moon(s) and even the Sun as well. Such a feature would defiantly complement the nomenclature feature that already exists. A good example use of this feature would be is to zoom in on the moon turn on nomenclature along with the grid lines that way in an effect it would make a nice Lunar map and along with the planets go, it would show the planets orientation on the way it’s facing you. I know there are more important things that are being worked on; this entire feature request is for a future version of Stellarium in other words no big hurry, that’s if all of this is possible. If this feature is already on the back burner as I would say; please just disregard all of this. Thank you for all that you do.

**Comment by alex-w** [comment]
Double of #485
