### ISSUE TITLE
Rectangular Sensor Crop Overlay

### ISSUE THREAD

**Issue by bryanfarrell** [Stellarium/stellarium#1069]
The Show sensor crop overlay feature is nice when you trying to see what a particular telescope and sensor will capture in terms of FOV when you intend to crop the image to a specific size.  While it is nice to be able to add a square box with a specific pixel dimension, many times an image is cropped to a standard image size (4K, 1440p, 1080p, etc.). 

It would be really nice to be able to simply put in a rectangular crop dimension so that when sampling targets it's easy to see if you can get the FOV your looking at aligned in a cropped image without resizing the image (only cropping).

For example, the sensor I use is in 4:3 aspect ratio and I can crop these images to 4K 16:9 without resizing.  Having the sensor crop overlay be a rectangle of 3840 px by 2160 px would be really helpful.

**Comment by hughes** [comment]
This is a really neat improvement.
