### ISSUE TITLE
daily snaps on Fedora

### ISSUE THREAD

**Issue by ng0177** [Stellarium/stellarium#1071]
Hello, is any of these daily snaps supported?

[snapcraft:stellarium-daily](https://snapcraft.io/stellarium-daily)

[snapstats:stellarium-daily](https://snapstats.org/snaps/stellarium-daily)

How to use daily snaps on Fedora? Thanks.

**Comment by alex-w** [comment]
This is community-driven snaps. Please read the docs on proposed sites for using snaps in Fedora.

**Comment by ng0177** [comment]
Would you be able to point me to the right docs for it? Thanks.

**Comment by alex-w** [comment]
> Would you be able to point me to the right docs for it? Thanks.

See https://snapcraft.io/install/stellarium-daily/fedora as I understand

**Comment by ng0177** [comment]
Done. Is this a truie daily or and old one?

```
~ $ /var/lib/snapd/snap/stellarium-daily/35/bin/stellarium -v
QSocketNotifier: Can only be used with threads started with QThread
User config directory does not exist:  "/home/th6mas/.stellarium"
WARNING StelFileMgr::StelFileMgr: could not find install location: "/build/stellarium-daily/parts/stellarium-daily/src"  (we checked for  "/build/stellarium-daily/parts/stellarium-daily/src/data/ssystem_major.ini" ).
Maybe this is AppImage or something similar? Let's check relative path...
Stellarium 0.90.0.16365 [master]
```

**Comment by alex-w** [comment]
Oh! Looks like this snap is outdated. Could you contact to author of this snap (or to author of other snap - https://github.com/plars/stellarium-snap)? Or, maybe you want to create an own snap?

Just for understanding: development team do not use and do not produce official snap packages. I really hope than community may driven it herself.

**Comment by ng0177** [comment]
OK, [issue](https://github.com/plars/stellarium-snap/issues/5) raised.

**Comment by t4saha** [comment]
@ng0177 Snap package has been updated. [both stable (0.20.1) & edge channel]
https://snapcraft.io/stellarium-daily

**Comment by alex-w** [comment]
@t4saha thank you very much! Could you support those snaps as official packages?

**Comment by t4saha** [comment]
@alex-w thank you for considering. I will try to maintain stable builds.
