### ISSUE TITLE
Navi (Casiopea)

### ISSUE THREAD

**Issue by Alber210** [Stellarium/stellarium#1072]
In Casiopea, Stellariun names Cih (Gamma-Cas) as Navi, but Navi is the name of Segin (Epsilon-Cas.
You can ckeck it in ten web of NASA here: https://history.nasa.gov/afj/ap16fj/02_Day1_Pt2.html (the 3rd star in the Star Reference List of that web).

**Comment by alex-w** [comment]
Source for Navi name is: Jack W. Rhoads (1971). "Technical Memorandum 33-507-A Reduced Star Catalog Containing 537 Named Stars", Jet Propulsion Laboratory, California Institute of Technology; November 15, 1971 [http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19720005197_1972005197.pdf]

**Comment by gzotti** [comment]
https://www.hq.nasa.gov/alsj/a15/a15.postland.html#1051133 (linked below the list) says "Navi is gamma Cas". Uh oh, how did they come back?  :-o
