### ISSUE TITLE
Field Guide plugin for Detailed DSO

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#1075]
The idea may be similar to this:
https://github.com/Stellarium/stellarium/issues/499

This kind of objects like Trapezium region, Region Huygheniana etc, are often hiding in a great DSO.
Some of them has no Catalog name, and some of them will hard to add because they spread into many different catalogue. SIMBAD online search is a good idea but it could not make them all show in the Stellarium at once time.

![image](https://user-images.githubusercontent.com/32613953/80857273-89e03c80-8c83-11ea-83c6-a766cb7c24ac.png)

We can consider a new plugin that can show the interesting objects to user, just includes few terrain picture in the window as below, which is also convenient and easy. 
(I think stacking the tiny map into the main window is difficult and not elegant ).

![image](https://user-images.githubusercontent.com/32613953/80857055-a2e7ee00-8c81-11ea-9b73-ad185bc658d3.png)

And then I list the similar one below.

```
M8
M42
NGC 3372
...


M33 (HII and Globs, also include in NGCIC, maybe no need to consider)
M31 (Globs) and NGC206 detailed
M101 （HII , also include in NGCIC, maybe no need to consider)）
others (https://www.astronomy-mall.com/Adventures.In.Deep.Space/gcextra.htm)
...
```
M8
https://skyandtelescope.org/observing/wallow-a-while-in-the-lagoon-nebula/ 
http://www.astrophoton.com/emission_nebulae.htm 

![image](https://user-images.githubusercontent.com/32613953/80856847-0cff9380-8c80-11ea-9738-9c8a346387ef.png)

![image](https://user-images.githubusercontent.com/32613953/80856970-0b829b00-8c81-11ea-953e-1ee15b99b5a6.png)

![image](https://user-images.githubusercontent.com/32613953/80857391-59e56900-8c84-11ea-9c73-1c3ff92013f2.png)

M42
https://skyandtelescope.org/observing/see-orion-nebula-3d12172014/
http://www.astrosurf.com/patricio/DS/M42-topografia.htm 
![image](https://user-images.githubusercontent.com/32613953/80857273-89e03c80-8c83-11ea-83c6-a766cb7c24ac.png)
![image](https://user-images.githubusercontent.com/32613953/80857410-89947100-8c84-11ea-9187-ec74aa233df2.png)

NGC3372
https://peoplesguidetothecosmos.com/constellations/carina.htm 
It's sad because I could not found a feild guide into it.

![image](https://user-images.githubusercontent.com/32613953/80858028-2e18b200-8c89-11ea-9113-c5faf4fdad28.png)

M33
https://www.astronomy-mall.com/Adventures.In.Deep.Space/M33.HII-Star.Clouds.html
![image](https://user-images.githubusercontent.com/32613953/80857479-1fc89700-8c85-11ea-813d-5ea481b25cbb.png)

M31
http://www.astrosurf.com/patricio/DS/M31_globulares_extragalacticos.htm 
![image](https://user-images.githubusercontent.com/32613953/80857543-ab422800-8c85-11ea-8019-2a344c9bfc9b.png)

NGC206
...
![image](https://user-images.githubusercontent.com/32613953/80858190-43daa700-8c8a-11ea-8416-671cd2f2e960.png)

Veil Nebula
https://www.astronomy-mall.com/Adventures.In.Deep.Space/Veil.big.jpg

https://skyandtelescope.org/astronomy-blogs/explore-night-bob-king/explore-veil-nebula/

![image](https://user-images.githubusercontent.com/32613953/80857485-2d7e1c80-8c85-11ea-85d1-011996437cc3.png)

MCNEILS NEBULA with M78
https://images.mantrapskies.com/catalog/OTHER/MCNEILS_NEBULA/MCNEIL_L6X10RGB3X10ID.JPG 

IC 1396
http://www.astrophoton.com/IC1396A.htm

Some of then maybe under copyright, so if its using is not allowed, find a new one.

...

**Comment by gzotti** [comment]
I consider this as subject of a written book, and not of a graphic simulation. It takes decades of observer time, a large telescope and superb skies to develop a rich guide from scratch, or still a few years to collect such kind of information. That said, I don't consider this as something we are going to develop, however, anybody with 5 years worth of spare time for exclusive use is invited to do that.
