### ISSUE TITLE
Stellarium crashes when I go to Ocular view or Image Sensor Frame

### ISSUE THREAD

**Issue by ssglick** [Stellarium/stellarium#1078]

**Comment by alex-w** [comment]
https://github.com/Stellarium/stellarium/wiki/FAQ#Reporting_a_crash

**Comment by ssglick** [comment]
Let me add some additional info.  Everything was working fine a few days ago.  I have now updated to version 20.1.  When I hit either Sensor or ocular icon, Stellarium closes.  Possible bug?

**Comment by ssglick** [comment]
I am running Windows 64 bit version.

**Comment by alex-w** [comment]
Please attach your log and oculars.ini file

**Comment by ssglick** [comment]
Oculars is attached:


Here is the log:


2020-05-05T11:08:16

Operating System: Windows 10 (10.0)

Compiled using MSVC++ 14.0 (Visual Studio 2015)

Qt runtime version: 5.9.9

Qt compilation version: 5.9.9

Addressing mode: 64-bit

Total physical memory: 8109 MB

Available physical memory: 3694 MB

Physical memory in use: 54%

Processor speed: 2400 MHz

Processor name: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

Processor speed: 2400 MHz

Processor name: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

Processor speed: 2400 MHz

Processor name: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

Processor speed: 2400 MHz

Processor name: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

C:\Program Files\Stellarium\stellarium.exe

-----------------------------------------------------

[ This is Stellarium 0.20.1 - https://stellarium.org/ ]

[ Copyright (C) 2000-2020 Fabien Chereau et al. ]

-----------------------------------------------------

Writing log file to: "C:\\Users\\ssgli\\AppData\\Roaming\\Stellarium\\log.txt"

File search paths:

0 . "C:\\Users\\ssgli\\AppData\\Roaming\\Stellarium"

1 . "."

Config file is: "C:\\Users\\ssgli\\AppData\\Roaming\\Stellarium\\config.ini"

Default surface format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile QSurfaceFormat::OpenGLContextProfile(NoProfile))

Desired surface format: QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile QSurfaceFormat::OpenGLContextProfile(NoProfile))

StelGLWidget constructor

StelGraphicsScene constructor

initializeGL

OpenGL supported version: "4.5.0 - Build 25.20.100.6472"

Current Format: QSurfaceFormat(version 4.5, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))

StelMainView::init

Detected: OpenGL "4.5"

Driver version string: "4.5.0 - Build 25.20.100.6472"

GL vendor is "Intel"

GL renderer is "Intel(R) HD Graphics 520"

GL Shading Language version is "4.50 - Build 25.20.100.6472"

GLSL Version Number detected: 4.5

GLSL version is fine, we should not see a graphics problem.

Cache directory is: "C:\\Users\\ssgli\\AppData\\Local\\stellarium\\stellarium\\cache"

StelLocation::createFromLine(): TimeZone name for "Pinnacles" not found. Translating "system_default" to "system_default"

StelLocation::createFromLine(): TimeZone name for "Home" not found. Translating "system_default" to "system_default"

StelLocation::createFromLine(): TimeZone name for "Glacier Point" not found. Translating "system_default" to "system_default"

StelLocation::createFromLine(): TimeZone name for "Garland Ranch" not found. Translating "system_default" to "system_default"

StelLocation::createFromLine(): TimeZone name for "Chews Ridge" not found. Translating "system_default" to "system_default"

StelLocation::createFromLine(): TimeZone name for "laureles grade" not found. Translating "system_default" to "system_default"

StelLocation::createFromLine(): TimeZone name for "Home" not found. Translating "system_default" to "system_default"

Sky language is "en_US"

Planetary features language is "en_US"

Application language is "en_US"

Couldn't load translations for language "en_US" in section "stellarium-scripts"

Empty translation file for language "en_US" in section "stellarium-scripts"

Scripts language is "en_US"

Loading Solar System data (1: planets and moons) ...

Loading from : "./data/ssystem_major.ini"

SolarSystem has 83 entries.

Loaded 83 Solar System bodies

Loading Solar System data (2: minor bodies)...

Loading from : "C:\\Users\\ssgli\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"

SolarSystem has 190 entries.

Loaded 107 Solar System bodies

File ssystem_minor.ini is loaded successfully...

Loading nomenclature for Solar system bodies ...

Loaded 15663 / 15665 items of planetary surface nomenclature

WARNING - The next planets to assign nomenclature items is not found: "Dactyl"

Loading star data ...

"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"

"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"

"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"

"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"

Finished loading star catalogue data, max_geodesic_level: 3

Loading scientific star names from ".\\stars\\default\\name.fab"

Loaded 4507 / 4507 scientific star names

Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"

Loaded 6862 / 6862 variable stars

Loading double stars from ".\\stars\\default\\wds_hip_part.dat"

Loaded 16412 / 16412 double stars

Loading cross-identification data from ".\\stars\\default\\cross-id.dat"

Loaded 108338 / 108338 cross-identification data records for stars

Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"

Loaded 117703 / 117703 parallax error data records for stars

StelCore: Invalid timezone name: "" -- not setting timezone.

navigation/preset_sky_time is a double - treating as jday: "2451514.25001"

Loading DSO data ...

[...] "Stellarium DSO Catalog, version 3.9 (standard edition)"

Loaded 94393 DSO records

Loading DSO outline data ...

Loaded 72 DSO outline records successfully

LandscapeMgr: initialized Cache for 100 MB.

Got location "Salinas, California, United States (36.6704, -121.659; America/Los_Angeles)" for IP "71.198.79.111"

Loading star names from ".\\skycultures\\western\\star_names.fab"

Loaded 1004 / 1004 common star names

Loading DSO name data ...

Loaded 1111 / 1133 DSO name records successfully

WARNING - No position data for 22 objects: "PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124"

Loaded 88 / 88 constellation records successfully for culture "western"

Loaded 85 / 85 constellation art records successfully for culture "western"

Loaded 88 / 88 constellation names

Loading constellation boundary data ...

Loaded 782 constellation boundary segments

Error in Asterism "TA6" : can't find star with coordinates 2.14697 / 8.55097

ERROR reading asterism lines record at line 88 for culture "western"

Loaded 81 / 82 asterism records successfully for culture "western"

WARNING - asterism abbreviation "TA6" not found when loading asterism names

Loaded 71 / 72 asterism names

stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs

stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)

Initializing basic GL shaders...

Creating GUI ...

Loaded plugin "Exoplanets"

[Exoplanets] Version of the format of the catalog: 1

[Exoplanets] loading catalog file: "C:\\Users\\ssgli\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"

Loaded plugin "MeteorShowers"

[MeteorShowersMgr] Loading catalog file: "C:\\Users\\ssgli\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"

Loaded plugin "Novae"

[Novae] version of the catalog: 1

[Novae] loading catalog file: "C:\\Users\\ssgli\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"

Loaded plugin "Oculars"

Oculars::validateAndLoadIniFile() ocular.ini exists at: "C:\\Users\\ssgli\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...

Oculars::validateAndLoadIniFile() found existing ini file version 3.1

Loaded plugin "RemoteControl"

RemoteControl using QtWebApp version 1.6.4-stellarium

StaticFileController: docroot=C:/Program Files/Stellarium/webroot, encoding=UTF-8, maxAge=60

StaticFileController: cache timeout=60000, size=1048576

Couldn't load translations for language "en_US" in section "stellarium-remotecontrol"

Empty translation file for language "en_US" in section "stellarium-remotecontrol"

Loaded plugin "Satellites"

[Satellites] loading catalog file: "C:\\Users\\ssgli\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"

Loaded plugin "SolarSystemEditor"

Using the ssystem_minor.ini file that already exists in the user directory...

Loaded plugin "TelescopeControl"

[TelescopeControl] Only embedded telescope servers are available.

[TelescopeControl] Adding device model: "Meade AutoStar compatible" "Any telescope or telescope mount compatible with Meade's AutoStar controller." "TelescopeServerLx200" 500000

[TelescopeControl] Adding device model: "Meade LX200 (compatible)" "Any telescope or telescope mount compatible with Meade LX200." "TelescopeServerLx200" 500000

[TelescopeControl] Adding device model: "Meade ETX70 (#494 Autostar, #506 CCS)" "Meade's ETX70 with the #494 Autostar controller and the #506 Connector Cable Set." "TelescopeServerLx200" 1500000

[TelescopeControl] Adding device model: "Losmandy G-11" "Losmandy's G-11 telescope mount." "TelescopeServerLx200" 500000

[TelescopeControl] Adding device model: "Wildcard Innovations Argo Navis (Meade mode)" "Wildcard Innovations' Argo Navis DTC in Meade LX200 emulation mode." "TelescopeServerLx200" 500000

[TelescopeControl] Adding device model: "Celestron NexStar (compatible)" "Any telescope or telescope mount compatible with Celestron NexStar." "TelescopeServerNexStar" 500000

[TelescopeControl] Adding device model: "Sky-Watcher SynScan (version 3 or later)" "Any Sky-Watcher mount that uses version 3 or later of the SynScan hand controller." "TelescopeServerNexStar" 500000

[TelescopeControl] Adding device model: "Sky-Watcher SynScan AZ GOTO" "The Sky-Watcher SynScan AZ GOTO mount used in a number of telescope models." "TelescopeServerNexStar" 500000

[TelescopeControl] Loaded successfully 1 telescopes.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by alex-w** [comment]
Please use web interface to share oculars.ini file

**Comment by ssglick** [comment]
Attached



[ocular.txt](https://github.com/Stellarium/stellarium/files/4583287/ocular.txt)

**Comment by alex-w** [comment]
I see strange name in oculars.ini file:
> 0\name=ZWO ASI120MCfile:///C:/Users/ssgli/Documents/Astro

Are you tried attach file into input field?

**Comment by ssglick** [comment]
Thanks.  I removed that sensor, then re-input the sensor.  The new attached ocular.ini file no longer has the offending line, but the Stellarium still shuts down when I hit the ocular or sensor.


[ocular_new.txt](https://github.com/Stellarium/stellarium/files/4583546/ocular_new.txt)

**Comment by alex-w** [comment]
OK, I found source of the bug, but I don't understand how it was introduced in your case - are you deleted one lens?

Workaround for you: please reduce value of `lens_index` in your ocular.ini file (for example: `lens_index = 2`)
