### ISSUE TITLE
Program Crash; "Loading Nebulae"

### ISSUE THREAD

**Issue by andrewianbennett** [Stellarium/stellarium#1079]
I recently upgraded to the current version of Stellarium.

When I open the program it works while during daytime hours.

Once I adjusted the "date-time" to reflect a night time period the program constantly crashes.  I have noted in the bottom right of the program window the text "Loading Nebulae" appears and then the program promptly crashes.

Any thoughts on how I can resolve this situation?

Cheers,

Andrew

**Comment by alex-w** [comment]
https://github.com/Stellarium/stellarium/wiki/FAQ#Reporting_a_crash

**Comment by alex-w** [comment]
Please share you log from Stellarium

**Comment by andrewianbennett** [comment]
[Stellarium Crash - Log File, Andrew Bennett (May 6 2020).txt](https://github.com/Stellarium/stellarium/files/4590275/Stellarium.Crash.-.Log.File.Andrew.Bennett.May.6.2020.txt)

**Comment by alex-w** [comment]
Could you try run Stellarium in ANGLE mode?

**Comment by andrewianbennett** [comment]
I'm not 100% sure I know exactly what you mean as I am a new user.

I installed the "Angle Measure" add-in, restarted Stellarium and turned on the "Angle Measure" feature button in the ribbon.  I then moved time forward to the evening and then the same crash occurs.

Did I do what you wanted?

Andrew

**Comment by alex-w** [comment]
No, I meant run Stellarium trough shortcut “Stellarium (ANGLE mode)” (see Start -> Stellarium)

**Comment by andrewianbennett** [comment]
This appears to have fixed the problem.  The program no longer crashes.  Thanks!

What is going on here?

**Comment by alex-w** [comment]
Could you find what exactly given crash in OpenGL mode? What’s happening if atmosphere is off?

**Comment by andrewianbennett** [comment]
I opened stellarium in OpenGL mode.

When is uncheck "atmosphere visualization" the program immediately crashes.

**Comment by alex-w** [comment]
Please attach log immediately after crash.

Second test: could you run Stellarium, disable visualization Solar system bodies (press P) and disable atmosphere visualization?

**Comment by andrewianbennett** [comment]
[Stellarium Crash - Log File #2, Andrew Bennett May 6 2020.txt](https://github.com/Stellarium/stellarium/files/4590403/Stellarium.Crash.-.Log.File.2.Andrew.Bennett.May.6.2020.txt)

**Comment by andrewianbennett** [comment]
after pressing P the program immediately crashes

**Comment by alex-w** [comment]
Hmm... Could you rename your ssystem_minor.ini file and check it again?

**Comment by andrewianbennett** [comment]
I renamed the file and restarted the program.  After pressing P the program crashes.

**Comment by alex-w** [comment]
Wait! Stellarium crashes when you’re press P and you didn’t changes any other settings?

**Comment by andrewianbennett** [comment]
correct.  I launch the program and press P and then the program crashes.

**Comment by alex-w** [comment]
This is very strange. Please attach your config.ini and ssystem_*.ini files.

For final test: could you uninstall Stellarium and install it again?

**Comment by andrewianbennett** [comment]
[config.zip](https://github.com/Stellarium/stellarium/files/4590518/config.zip)
[ssystem_minor.zip](https://github.com/Stellarium/stellarium/files/4590532/ssystem_minor.zip)

I'll uninstall and install stellarium again tomorrow and will let you know what happens.

**Comment by alex-w** [comment]
Please attach ssystem_major.ini too

**Comment by andrewianbennett** [comment]
I'm unable to find this file

**Comment by alex-w** [comment]
Please check stellarium directory in Program Files

**Comment by andrewianbennett** [comment]
[ssystem_major.zip](https://github.com/Stellarium/stellarium/files/4590565/ssystem_major.zip)

**Comment by andrewianbennett** [comment]
Hi Alex,

I uninstalled and reinstalled Stellarium and my initial problem remains.  For now, it appears running the program in "angle mode" works and I can also use the web version if I have to.  I'm a novice user so I expect these modes will be sufficient for me.

Is there anything else I could provide you to help debug?  Just let me know.  Otherwise, I'll just close the issue.

Cheers,

Andrew

**Comment by alex-w** [comment]
I cannot reproduce issue on my linux. @gzotti could you check it on your windows 10 machine?

**Comment by gzotti** [comment]
I also cannot reproduce it. If you have no particularly valuable data or configurations (oculars setup, telescope plugin setup, self-made landscapes, ...), you may want to start over, i.e., uninstall Stellarium, delete Appdata/Roaming/Stellarium, reinstall and try again. (Actually, removing Appdata/Roaming/Stellarium should be enough.) If only ANGLE mode works, I'd be surprised on an otherwise working Geforce, but it should else be equivalent.

**Comment by andrewianbennett** [comment]
Ok.  

The next time there is an update to Stellarium I will do an uninstall and see what happens.  In the interim, I'll just make do with what works.  I'm a novice user so I don't need many of the features and the web version does most of what I want.  

Thanks for helping me try to resolve my issues.  Very much appreciated.

Cheers,
Andrew
