### ISSUE TITLE
Halley's comet

### ISSUE THREAD

**Issue by vagelen** [Stellarium/stellarium#1083]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vagelen** [comment]
According Wikipedia the aphelion is 35.082 AU. In the app it goes further. Is that right?

**Comment by gzotti** [comment]
How can we help you if you ignore the guidelines about what we want to know? 

Is this a Problem?
Which solution would you like?
Which alternatives have you considered?
In which context do you ask "right"?

Things that could help investigating your issue:
Which element set? How much further? When? 

Preliminary answer:
Data sources may differ slightly. Comet orbits are subject to changes.

**Comment by gzotti** [comment]
Timeout.
