### ISSUE TITLE
Sun position ignores local time

### ISSUE THREAD

**Issue by voyager2222** [Stellarium/stellarium#1084]
### Actual Behaviour
I open the app at 10 am PDT and it shows the sun low in the western sky.

### System
* Stellarium version: 0.20.1
* Operating system: OSX 10.13.6
* Graphics Card: NVIDIA GeForce GT 330M
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Please show screenshot

**Comment by gzotti** [comment]
You could set your location and time zone...

**Comment by gzotti** [comment]
Timeout.
