### ISSUE TITLE
Automatically adjust for sunset/sunrise times in the Date and Time panel

### ISSUE THREAD

**Issue by mgfasel-unige** [Stellarium/stellarium#1088]
If we want to visually observe and compare rising stars at sunset/sunrise during the year, it is difficult to keep track of the changing time at which the sunsets/sunrises occur.

It would be great if instead of manually ajusting the time each day, additional buttons would be available for sunset/sunrise or other meaningful periods in the Date and Time panel. The time would then be automatically adjusted for the date on the left.

I am somehow referring to this heliacal rising simulator: https://astro.unl.edu/classaction/animations/ancientastro/heliacalrisingsim.html that offers this feature.

There are maybe other cases/applications that could benefit from the suggestion.

Idea:
![Untitled](https://user-images.githubusercontent.com/63094676/81495166-89acf600-92ae-11ea-8686-0e79fe5cbbe0.png)

**Comment by gzotti** [comment]
You can already assign a shortcut key to "go to next setting of selected object".

**Comment by mgfasel-unige** [comment]
Thanks, I'm sure I understand correctly but the idea would be to be able to stand still looking due East at sunset all year round by simply changing the day. I don't see how shortcuts could help achieving this...

**Comment by gzotti** [comment]
"go to next setting of selected object" goes to the next sunset if you have selected the Sun. Repeated execution will advance the day. Just try it out. A shortcut can be edited by pressing "Edit keyboard shortcut..." in the F1/Help panel. An assigned shortcut is executed by pressing it. Just try it out.

**Comment by alex-w** [comment]
+1 to shortcuts - I've specially added them to creating a demonstrations

**Comment by alex-w** [comment]
Any feedback?

**Comment by mgfasel-unige** [comment]
Thanks for all your explainations but I didn't find how to do what I would like with the shortcuts. I found a script though that seems to do what I was in mind: Dawn/dusk/sunrise/sunset jumps on https://stellarium.org/scripts.html...

**Comment by axd1967** [comment]
@mgfasel-unige to assign a key shortcut do this:
1. hit F7
2. in the search box (just above "Primary shortcut") , type "**selected**"
3. click "Next setting of **selected** object"
4. in Alternative shortcut, type `)` (or any other key that fits your keyboard layout)
5. select e.g. Moon
6. type `)` or whatever key was assigned)

(Note: it is a good practice to use the "Alternative shortcut" to clearly distinguish your own key settings; but Primary shortcut works just as fine)

**Comment by axd1967** [comment]
(as a side note, the `actionNext_Rise/Transit/Setting` does not work well with the Moon, probably due to #1852 )
