### ISSUE TITLE
Input for desired minimum elevation in WUT-Dialog

### ISSUE THREAD

**Issue by VolkerHoeren** [Stellarium/stellarium#1089]
The WUT Dialog is a very nice feature and helps in planning observation sessions.
It would help even more if this Dialog could be expanded in the following ways:
 
- [ ]	An input field for a desired minimum elevation of an object. This could be used to delete from the result list those objects, which are below a desired elevation.
- [x]	A column, next to the transit column, showing the elevation of the object at transit times. 
- [ ]	Two more columns showing the elevation of the object at rise and set times with respect to the desired minimum elevation.

This would assist in selecting only those objects, which would be visible at a certain time span of the night taking into account local obstructions like trees, houses and the walls of e.g. my observatory.

A think an increased list creation time will only burden those users, who use the desired minimum elevation input.

**Comment by alex-w** [comment]
Please check latest beta (v0.20.1.17945)

**Comment by VolkerHoeren** [comment]
Hi Alexander,

many thanks for the desired change to the WUT-Dialog, which works flawlessly.

Regard

Volker

 

 

 

Von: Alexander Wolf <notifications@github.com> 
Gesendet: Donnerstag, 21. Mai 2020 12:26
An: Stellarium/stellarium <stellarium@noreply.github.com>
Cc: VolkerHoeren <hvolker@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [Stellarium/stellarium] Input for desired minimum elevation in WUT-Dialog (#1089)

 

Please check latest beta (v0.20.1.17945)

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
