### ISSUE TITLE
meteor shower plugin 2.0.6: radiants are twinkling

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1090]
### Actual Behaviour
Seems to be irrespective of the "twinkling stars" option

### Steps to reproduce
Activate the plugin

### System
* Stellarium version: 0.20.1
* Operating system: Kubuntu
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Please give us more details to reproduce the issue

**Comment by axd1967** [comment]
Just activate the plugin and observe the radiants are twinkling?

**Comment by gzotti** [comment]
MeteorShower.cpp line 342. The developer wanted a little twinkle, so that's intentional.

**Comment by axd1967** [comment]
ah, indeed, I see: 

https://github.com/Stellarium/stellarium/blob/06a3181bc7cd87e574bdffa70ef33628133d8551/plugins/MeteorShowers/src/MeteorShower.cpp#L342-L354

(small obs: the `alpha` calculation should move after the switch for readability.)

I still find this strange, and an unnecessary strain for someone who wants to preserve laptop battery, so I believe this should be a user setting. as a minimum, it makes more sense to connect this to the existing twinkle user setting. and to keep the original developer happy, but add more work, this could be a setting in the plugin.

especially when a radiant is a virtual concept... novody will ever see a "radiant" twinkle.

![image](https://user-images.githubusercontent.com/3529789/102091489-2e804a80-3e1f-11eb-8149-59398a32e6bc.png)
