### ISSUE TITLE
Error in the program.

### ISSUE THREAD

**Issue by 3245673** [Stellarium/stellarium#1091]
I am using the latest version of Stellarium(0.20.1), which was downloaded from the official site. When I use the program, a problem occurs. When I increase or decrease the distance to an object or just want to look deeper into space using the controller or the keyboard shortcut ctrl+down, ctrl+up, Stellarium stops working due to an error, and Windows closes the program. I am using the Windows 8.1 64x version. Is there a solution to this problem?

**Comment by alex-w** [comment]
https://github.com/Stellarium/stellarium/wiki/FAQ#Reporting_a_crash

**Comment by alex-w** [comment]
Please attach log.txt after crash

**Comment by gzotti** [comment]
Timeout.
