### ISSUE TITLE
Stellarium 20 not connecting to the internet over WiFi

### ISSUE THREAD

**Issue by Skipper197600** [Stellarium/stellarium#1095]
I can not find a way for Stellarium 20 to connect to the internet using WiFi. This means I can not add minor planets or access DSS overlay whilst working from the observatory.

I created an exception with Win 7 firewall. This does not work.

Is there something obvious that I am missing.

Any help would be be greatly appreciated.

**Comment by alex-w** [comment]
Please update Stellarium to version 0.20.1

**Comment by Skipper197600** [comment]
Sorry, this is 20.1

**Comment by alex-w** [comment]
Please show log.txt from Stellarium after trying to add minor planets or display the DSS layer

**Comment by Skipper197600** [comment]
[log.txt](https://github.com/Stellarium/stellarium/files/4651161/log.txt)

**Comment by alex-w** [comment]
Are you install v0.20.1 as upgrade or it was clean install?

**Comment by Skipper197600** [comment]
It would have been an upgrade.

**Comment by alex-w** [comment]
Could you try uninstall and install it again - I fear your issue is related to wrong version of OpenSSL libraries.

**Comment by Skipper197600** [comment]
OK. I have backed up my custom minor planet list and landscape. I will uninstall.

**Comment by Skipper197600** [comment]
Thanks. This has resolved the issue :)
