### ISSUE TITLE
Crash when attempting to install new landscape

### ISSUE THREAD

**Issue by HalvorRaknes** [Stellarium/stellarium#1097]
-->

### Expected Behaviour

When clicking to install a new landscape from a zip file this works

### Actual Behaviour

When I click to install nothing happens for perhaps a minute, the the app closes down

### System
* 0.18.0
* Operating system: 5.3.0-53-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
           Desktop: MATE 1.22.2 wm: marco dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 

* Graphics Card: Device-1: Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display vendor: ASUSTeK 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0f31 
           Display: x11 server: X.Org 1.20.5 driver: modesetting unloaded: fbdev,vesa 
           compositor: marco resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel Bay Trail v: 4.2 Mesa 19.2.8 compat-v: 3.0 
           direct render: Yes 
* Screen type (if applicable): Resolution, HighDPI, scaling
Laptop System: ASUSTeK product: X551MA v: 1.0 serial
[log.txt](https://github.com/Stellarium/stellarium/files/4670501/log.txt)

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Are you installed Stellarium from our PPA or from standard repository?

**Comment by gzotti** [comment]
- Probably more interesting is the landscape that causes an error. 
- Please try the current version 0.20.1, not some obsolete 0.18. 
- And attach the logfile of the crashed run, not after a regular run.

**Comment by alex-w** [comment]
@gzotti this is `Linux Mint 19.3`, so, it maybe well-known issue for Stellarium / Qt issue for crash when open file dialogs

**Comment by HalvorRaknes** [comment]
> Are you installed Stellarium from our PPA or from standard repository?

@alex-w I think I installed it from the mintinstall app accessible from the system main menu



> * Probably more interesting is the landscape that causes an error.
> * And attach the logfile of the crashed run, not after a regular run.

@gzotti It crashes prior to giving me the option of selecting which landscape to attempt to load.

Attaching log file from crashed run.
[log.txt](https://github.com/Stellarium/stellarium/files/4672333/log.txt)

> * Please try the current version 0.20.1, not some obsolete 0.18.

OK. Is there an easy command to upgrade my existing version? Why doesn't it update automatically like many other apps do?

**Comment by alex-w** [comment]
Please try snap:stellarium

**Comment by alex-w** [comment]
Which landscape you tried to install?

**Comment by HalvorRaknes** [comment]
I have now installed the latest version, but when I open it it still says it's 0.18.0.

**Comment by alex-w** [comment]
Hmm... Are you standard package - `apt remove stellarium` ?

**Comment by HalvorRaknes** [comment]
Is it a different program? Not just an upgraded version?

No, I haven't removed anything. IT doesn't seem normal to have to remove before upgrading.

**Comment by alex-w** [comment]
deb packages and span packages is a different type of packages

**Comment by HalvorRaknes** [comment]
OK, but don't they even recognize that the app is already installed?

**Comment by alex-w** [comment]
apt and span know nothing about each other

**Comment by HalvorRaknes** [comment]
OK. I have removed 0.18.0. But the new install is invisible in my menus. Can I fix that without having to reinstall?

**Comment by alex-w** [comment]
Run from terminal : snap run stellarium-daily.stellarium

**Comment by HalvorRaknes** [comment]
It still doesn't show up in my menus, and when I want to attempt loading the landscape, I am only shown the root directory.

**Comment by alex-w** [comment]
Please read the docs for snap - maybe reinstall snap package will add menu items

**Comment by HalvorRaknes** [comment]
I don't think I'm ready to read snap docs. I shall try and reinstall then.

**Comment by HalvorRaknes** [comment]
It won't reinstall. Do I REALLY have to uninstall and then install?

**Comment by alex-w** [comment]
`sudo snap remove stellarium-daily`
`sudo snap install --channel=stable stellarium-daily`

**Comment by HalvorRaknes** [comment]
It still doesn't show up in any menus.

**Comment by HalvorRaknes** [comment]
OK. It shows up now after I restarted the pc.

But the file selection dialogue doesn't show anything I know how to navigate.
![Skjermbilde på 2020-05-24 00-25-56](https://user-images.githubusercontent.com/65785947/82741805-3d55c180-9d56-11ea-9cb1-fbe04a53776d.png)

**Comment by gzotti** [comment]
Navigate to a ZIPfile with a downloaded (or self-made) Stellarium landscape inside.

**Comment by HalvorRaknes** [comment]
Now it works fine. Thanks to @gzotti @alex-w !
