### ISSUE TITLE
Crash while changing to camera/telescope mode

### ISSUE THREAD

**Issue by lxstinthesky** [Stellarium/stellarium#1098]
### Expected Behaviour
Changing the view in top right corner from normal to camera mode and seeing the red lines, etc.
### Actual Behaviour
Crash after attempting to change view. to camera or telescope

### Steps to reproduce
Change view in the top right to camera

### System
* Stellarium version: v0.20.1
* Operating system: Win 10
* Graphics Card: GTX 1060
* Screen type (if applicable): Res: 1920x1080

**Comment by gzotti** [comment]
Cannot reproduce it. Does the (missing) logfile give a hint after a crash? 
Do you have cameras defined? (Several come with the installation, but you could have deleted them?)

**Comment by alex-w** [comment]
Please check the latest beta - I think I found and fixed this issue couple weeks ago.

**Comment by lxstinthesky** [comment]
I added my own oculars and sensors and deleted the default ones. I am trying to install the latest beta now. 
I found the log.txt too, making the same steps as with the initial crash
[log.txt](https://github.com/Stellarium/stellarium/files/4672398/log.txt)

**Comment by alex-w** [comment]
Please share your oculars.ini

**Comment by lxstinthesky** [comment]
I rereinstalled the software, this time replacing all plugin data too. It fixed it but of course I had to add my equipment again. Probably the resbonsible file was corrupted in some way.
Thanks for the suggestions.
