### ISSUE TITLE
Time going by too slowly

### ISSUE THREAD

**Issue by victorman1998** [Stellarium/stellarium#1103]
When I set the clock to a different time than the system time, it often goes on much slower than a regular clock. It seems like it takes forever for a second to pass and this irks me a lot when exploring the app. It didn't use to happen before installing Stellarium 0.20.0 (I'm currently using Stellarium 0.20.1 64x-bit version).

**Comment by alex-w** [comment]
Please check latest beta - I think we fixed this issue around 3 weeks ago

**Comment by victorman1998** [comment]
> Please check latest beta - I think we fixed this issue around 3 weeks ago
> 
> Looks like duplicate of #1006

It is similar, indeed, but I encounter this problem regardless I select a celestial object or not.

**Comment by gzotti** [comment]
Does this only happen when you have some solar system object selected (text printed in upper-left corner), or always? Use F2/Information and deselect "Proper Motion" for a test.

**Comment by victorman1998** [comment]
> Please check latest beta - I think we fixed this issue around 3 weeks ago
> 
> Looks like duplicate of #1006

**Comment by victorman1998** [comment]
> Does this only happen when you have some solar system object selected (text printed in upper-left corner), or always? Use F2/Information and deselect "Proper Motion" for a test.

Oh, apparently, if "Proper Motion" is disabled, then times goes by the right way. So after all it is not an issue to worry about but something very natural for a body to have a different motion in time than actual seconds?

**Comment by victorman1998** [comment]
> Please check latest beta - I think we fixed this issue around 3 weeks ago
> 
> Looks like duplicate of #1006

It went the same with beta version, but yes, that issue seems the same. I apologise for not noticing enough that it happens only when selecting a celestial object.

**Comment by gzotti** [comment]
No it's a slight problem in the about 20 lines of code where we have to set and reset time to do that measurement, but the part of the code has variable execution speed that seems to require a totally different approach. It indicates that #1006 is still not completely solved.

**Comment by victorman1998** [comment]
> No it's a slight problem in the about 20 lines of code where we have to set and reset time to do that measurement, but the part of the code has variable execution speed that seems to require a totally different approach. It indicates that #1006 is still not completely solved.

OK, I see. Well I deselected that feature, but I hope this bug will be fixed as soon as possible in order to enable it back without any problems.

**Comment by alex-w** [comment]
@victorman1998 please attach your log.txt

**Comment by victorman1998** [comment]
> @victorman1998 please attach your log.txt
Where can I find it? I thought it was in Program Files\Stellarium folder, but I cannot find any "log.txt".

**Comment by victorman1998** [comment]
> @victorman1998 please attach your log.txt

[log.txt](https://github.com/Stellarium/stellarium/files/4707725/log.txt)

**Comment by gzotti** [comment]
The new solution seems to work, finally.

**Comment by alex-w** [comment]
Georg, what about comets and minor planets?

**Comment by gzotti** [comment]
My earlier restructuring of Planet::getInfoString avoids duplicate code :-)
