### ISSUE TITLE
Image sensor frame option does not display Telescope control after ocular view is used.

### ISSUE THREAD

**Issue by jimsmith93** [Stellarium/stellarium#1108]
### Expected Behaviour
Image sensor frame box should show telescope selector control.
![stel1](https://user-images.githubusercontent.com/66087824/83183188-54fac480-a11f-11ea-833c-0e99e2857814.jpg)

### Actual Behaviour
After using ocular view telescope control disappears...
![stel2](https://user-images.githubusercontent.com/66087824/83183281-75c31a00-a11f-11ea-90a8-aae843a1fddf.jpg)

### Steps to reproduce
Use image sensor frame, use ocular view, use image sensor frame.

### System
* Stellarium version: stellarium-0.20.1-win64.exe
* Operating system: Windows 10 Home 1909
* Graphics Card: Nvidia GeForce GTX 1050 Ti
* Screen type (if applicable): 2560x1440, 125% scaling

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/4697744/log.txt)

**Comment by alex-w** [comment]
Please attach you oculars.ini file

**Comment by jimsmith93** [comment]
Upload of .ini not allowed...
[ocular.pdf](https://github.com/Stellarium/stellarium/files/4697776/ocular.pdf)

**Comment by alex-w** [comment]
FF VIDEO and FF PHOTO is not defined in attached ocular.ini file and I cannot reproduce your issue with your config

**Comment by jimsmith93** [comment]
Is this not their definition?
[ccd]
0\name=FF PHOTO
0\resolutionX=4240
0\resolutionY=2832
0\chip_width=35.6
0\chip_height=23.8
0\pixel_width=8.4
0\pixel_height=8.4
1\name=FF VIDEO
1\resolutionX=1920
1\resolutionY=1080
1\chip_width=35.6
1\chip_height=20.02
1\pixel_width=9
1\pixel_height=9

**Comment by alex-w** [comment]
The fix will be available for testing in next beta
