### ISSUE TITLE
Missing Appimage for latest release 0.20.1. Please upload it.

### ISSUE THREAD

**Issue by Suvam4549** [Stellarium/stellarium#1109]
We need the appimage of this version like all previous ones. I am baffled that it has gone unnoticed for so long! Isn't it going to be maintained anymore?

**Comment by alex-w** [comment]
Please write us which linux distribution you are using and his version.

**Comment by Suvam4549** [comment]
> Please write us which linux distribution you are using and his version.

I am using Linux Mint XFCE 19.3. Since it's based on ubuntu LTS 18.04, Stellarium in repo is at least 5 versions behind.. I don't want to add any PPA.. Building from source is not an option for me either. So appimage is the best option for me to have the latest and greatest without any hassle. Can I know why the appimage build was dropped in this release?

**Comment by alex-w** [comment]
Mint 19 has OpenSSL 1.1, but AppImage do not support this version of OpenSSL - the network subsystem in Stellarium.AppImage won’t be work

**Comment by alex-w** [comment]
Are you tried use snap of flatpack packages of Stellarium instead?
