### ISSUE TITLE
Crash when opening Configuration window (beta 0.90.0.15828)

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#111]
There is an immediate crash when opening the configuration window (pressing F2) in the latest public test beta (0.90.0.15828 released on March 3rd).

Log attached.
[log.txt](https://github.com/Stellarium/stellarium/files/1777935/log.txt)

**Comment by DaveF290** [comment]
I have the same thing happening here. If this persists I'll re-install 0.90.0.15814 - which I had been running with no issues.

**Comment by gzotti** [comment]
Thanks for reporting. Small typo, will be OK in next beta.
