### ISSUE TITLE
Cannot use Screencast-o-matic to capture Stellarium

### ISSUE THREAD

**Issue by lsparks57** [Stellarium/stellarium#1112]
I'm an educator trying to transition astronomy labs online due to the pandemic using the screen video capture application Screencast-o-matic: https://screencast-o-matic.com/

### Expected Behaviour
Screencast-o-matic should capture everything happening on my screen, it has worked so far without any issues with every other program I've used.

### Actual Behaviour
While recording with screencast-o-matic, that software is unable to capture anything that I do in Stellarium. When I start up or alt-tab into Stellarium, whatever visual is showing initially is the only thing that is captured. Then any mouse movements or clicks or anything that I do in stellarium are captured as though over a still image. (For example I can tab in to show Ursa Major at 6pm, then if I set the time to 9pm and face a different direction, on the screen capture video we're still just seeing Ursa Major at 6pm the whole time.)

### Steps to reproduce
1. Start recording with Screencast-o-matic
2. Use Stellarium
3. Check recording

### System
* Stellarium version: stellarium-0.20.1-win64.exe
* Operating system: Windows 10
* Graphics Card: NVidia GeForce GTX 1660
* Screen type (if applicable): monitor set to 2560x1440, scaling at 100%

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
Here is the logfile: [log.txt](https://github.com/Stellarium/stellarium/files/4713675/log.txt)

**Comment by gzotti** [comment]
Don't you think this is an issue in Screencast-o-matic? Stellarium is not PowerPoint, however I have used e.g. Zoom successfully while others also experienced problems. Try running Stellarium in ANGLE mode, maybe your program only can grab DirectX output. You can also record movies with Windows' built-in game recording feature (Win+G). Or you start Spout mode and record the Spout output window.

**Comment by lsparks57** [comment]
ANGLE mode worked! Thank you so much!
