### ISSUE TITLE
"You should update graphics drivers, graphics hardware, or use the --mesa-mode option." -mesa and safe-mode not working

### ISSUE THREAD

**Issue by nam108** [Stellarium/stellarium#1119]
I'm sorry for making this report because probably this problem could be easily fixed and was mentioned here and there many times, but I am newbie to linux and also briefly searching some keywords and mentioned help links I didn't found solution.
I've tried the mesa and safe-mode option but it didn't worked

### Expected Behaviour
Stellarium working

### Actual Behaviour
Stellarium is not working and gives some log

### Steps to reproduce
Install Stellarium on Linux Mint 19.2 from mint software program - Stallarium ver. 18 on PC with only Intel Core i3 graphics

### System
* Stellarium version: 18
* Operating system: Linux Mint 19.2
* Graphics Card: Intel i3
* Linux inxi:
`inxi -Fxxxrz
System:
 Kernel: 4.15.0-101-generic x86_64 bits: 64 
  compiler: gcc v: 7.5.0 Desktop: Cinnamon 4.2.4 wm: muffin 4.2.2 
  dm: LightDM 1.26.0 Distro: Linux Mint 19.2 Tina base: Ubuntu 18.04 bionic 
CPU:
  Topology: Dual Core model: Intel Core i3 540 bits: 64 type: MT MCP 
  arch: Nehalem rev: 2 L2 cache: 4096 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 24472 
  Speed: 1409 MHz min/max: 1200/3067 MHz Core speeds (MHz): 1: 1440 2: 1403 
  3: 1388 4: 1408 
Graphics:
  Device-1: Intel Core Processor Integrated Graphics 
  vendor: Acer Incorporated ALI driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:0042 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1600x900~60Hz 
  OpenGL: renderer: Mesa DRI Intel Ironlake Desktop v: 2.1 Mesa 19.2.8 
  direct render: Yes 
Info:
  Processes: 227 Uptime: 1h 40m Memory: 5.50 GiB used: 1.13 GiB (20.5%) 
  Init: systemd v: 237 runlevel: 5 Compilers: gcc: 7.5.0 alt: 7 Shell: bash 
  v: 4.4.20 running in: gnome-terminal inxi: 3.0.32 `

### Logfile 
`2020-06-07T10:10:34
Operating System: Linux version 4.15.0-101-generic (buildd@lgw01-amd64-003) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020
Product Name: Linux Mint 19.2
Compiled using GCC 7.3.0
Qt runtime version: 5.9.5
Qt compilation version: 5.9.4
Addressing mode: 64-bit
MemTotal:        5768780 kB
MemFree:          124372 kB
MemAvailable:    3991544 kB
SwapTotal:       2097148 kB
model name	: Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz
cpu MHz		: 2448.708
model name	: Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz
cpu MHz		: 2501.333
model name	: Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz
cpu MHz		: 2564.528
model name	: Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz
cpu MHz		: 2532.071
00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 12) (prog-if 00 [VGA controller])
Kernel driver in use: i915
Kernel modules: i915
stellarium 
 -------------------------------------------------------
[ This is Stellarium 0.18.0 - http://www.stellarium.org ]
[ Copyright (C) 2000-2018 Fabien Chereau et al.         ]
 -------------------------------------------------------
Writing log file to: "/home/X/.stellarium/log.txt"
File search paths:
  0 .  "/home/X/.stellarium"
  1 .  "/usr/share/stellarium"
Config file is:  "/home/X/.stellarium/config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "2.1 Mesa 19.2.8"
Current Format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelMainView::init
Detected: OpenGL "2.1"
Driver version string: "2.1 Mesa 19.2.8"
GL vendor is "Intel Open Source Technology Center"
GL renderer is "Mesa DRI Intel(R) Ironlake Desktop "
GL Shading Language version is "1.20"
MESA Version Number detected:  19.2
Mesa version is fine, we should not see a graphics problem.
GLSL Version Number detected:  1.2
This is not enough: we need GLSL1.30 or later.
You should update graphics drivers, graphics hardware, or use the --mesa-mode option.
Else, please try to use an older version like 0.12.5, and try there with --safe-mode
You can try to run in an unsupported degraded mode by ignoring the warning and continuing.
But more than likely problems will persist.`

**Comment by alex-w** [comment]
Please try set main/check_requirements = false in ~/.stellarium/config.ini file.

**Comment by gzotti** [comment]
This GPU is blacklisted by Qt and may not work at all. Indeed, the suggestion trying --mesa-mode or --safe-mode should be given only on Windows.
