### ISSUE TITLE
Add equirectangular projection

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1120]
The request for adding support for [equirectangular projection](https://en.wikipedia.org/wiki/Equirectangular_projection) in Stellarium was published in small_planetarium mail list by Paul Bourke to improve using Stellarium by small planetariums.

**Comment by gzotti** [comment]
Erm, this is what "Cylindrical" actually has been doing for years. Or does he mean "create something that fills the screen, regardless of aspect ratio, and don't zoom"? You can always export such a map by setting a custom image size and 180°FoV.

**Comment by alex-w** [comment]
The full message from Paul Bourke:

I might not happen from me though, usually story ... I provide a solution for a client to meet their particular requirements, if they are happy with the pipeline/procedure then that is where it ends.

You may have noticed something similar was done with Celestia, summaries for both here
http://paulbourke.net/dome/stellariumsphere/
http://paulbourke.net/dome/celestiasphere/
I'm no expert in either. But it seemed that it was easy to automate the camera in Celestia to point in the 6 directions required but I couldn't automate the window dumping. On the other hand Stellarium had better window capture but i didn't see how to automate the camera. In both cases I already have the image combining solutions, dualfishe2sphere to create the equirectangular from the two fisheyes from Stellarium and cube2sphere to create the equirectangular from the 6 cubemaps in Celestia.

There are lots of negative comments I could make about both packages from a graphics and user interface perspective.
A few that affected this exercise
1. Antialiasing in Celestria seems very poor.
2. Both should switch to draw in "points" rather than pixels in order to behave properly on retina displays
3. In the case of Stellarium when saving the window contents to higher resolution images, the line and font sizes should be increased proportionately.
4. Since Stellarium has lots of projection mappings already why doesn't it do equirectangular (properly)?
5. Why is fisheye limited to 180 degrees in Stellarium? Not that it mattered in the end.
6. Why doesn't Celestia provide for window capture on Mac?

Some question for the gurus out there
1. Is it possible to (reliably and precisely) orientate the camera in Stellarium with scripting? I would rather create cubemaps also in Stellarium than used the dual fisheye approach.
2. How does one change the line thickness, star size, and font size in Celestia?

**Comment by gzotti** [comment]
The problem lies in libtess's handling of "cutting the seam", or our non-proper way of applying whatever libtess would have provided. The triangles at the edge would have to be cut properly. Find a student eager to do a master's work?

One solution may be to connect several instances of Stellarium with the RemoteSync plugin. I have no way to test whether projecting to 5 perspective squares will do what is required here.

**Comment by gzotti** [comment]
Of course, there has been the skybox script since late 2015.

**Comment by 10110111** [comment]
Note that the things described in [this comment](https://github.com/Stellarium/stellarium/issues/1120#issuecomment-728739257) also require a resolution of #2679.

**Comment by gzotti** [comment]
Not quite.  I am working on a new projection which will create a seamless 360x180 view regardless of screen size.

**Comment by alex-w** [comment]
Probably Mollweide projection should be added into TODO list too as most frequently used for surveys in astronomy

**Comment by 10110111** [comment]
> Uuh, right, distorting the star dots is yet another task...

In fact, there's a much larger general task: if the goal is to have something to wrap around a sphere, we want to have all the lines, labels etc. also distorted. This route seems quite a bumpy one. Cubemap seems to be an easier way, because distortion there is much smaller (or even Dymaxion projection? ;D), just needs careful placement of the labels.
