### ISSUE TITLE
Larger sensor sizes than 9999 pixels ?

### ISSUE THREAD

**Issue by The-J-BB** [Stellarium/stellarium#1123]
Is it planned to expand the sensor size option to more than 9999 x 9999 pixels? Sometimes it would be useful to see larger sensors in the window preview.

THX  
Jens

**Comment by alex-w** [comment]
Where you found oversized CCD chip?

**Comment by The-J-BB** [comment]
Hi Alexander,

a friend of mine is planning to evaluate a cmos system with IMX411 sensor which has more than 10.000 pixels effective horizontally and vertically. Now its of interest how the FOV is on several systems. In Stellarium, it is shown effectively and easy w/o calculating. If this is a problem in general forget my question ;-)

**Comment by alex-w** [comment]
I've increased limit of sensor size to 100000 pixels. The fix will be available to testing in next beta and stable release (v0.20.2)
