### ISSUE TITLE
Cannot open Stellarium 0.20.1

### ISSUE THREAD

**Issue by vladimirpootz** [Stellarium/stellarium#1124]
I am unable to open Stellarium 0.20.1 after a clean installation. When clicking on the installment, after the "initializing" of stars, location, etc... I am taken back to desktop. Has anyone experienced the same issue?

**Comment by alex-w** [comment]
Please attach log.txt from Stellarium (see Stellarium User Guide for details)

**Comment by gzotti** [comment]
Many. But only the logfile may help.

**Comment by vladimirpootz** [comment]
Where in the user in the user guide would I find more about this @alex-w  ?

**Comment by alex-w** [comment]
See chapter 5 (Files and Directories)

**Comment by vladimirpootz** [comment]
Спасибо болшой! @alex-w

**Comment by vladimirpootz** [comment]
@alex-w , I am sorry.  Opening the file as you have advised, I am unable to identify the problem. Might you be able to give me any further guidance as to what I should do?

**Comment by alex-w** [comment]
Just attach it in this topic (through web interface)

**Comment by vladimirpootz** [comment]
How am I to do that? Sorry,  I am not a programmer lol  @alex-w

**Comment by alex-w** [comment]
What about copy text from file and paste it in form for comments?

**Comment by vladimirpootz** [comment]
Might this file be under the names "change log" or "last run log" ?  By trying to search for the  file that you mentioned, I am only brought to these.

**Comment by vladimirpootz** [comment]
\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at:  "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Loaded plugin "Satellites"
[Satellites] loading catalog file: "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "1KUNS-PF" "43466"
Satellite has invalid orbit: "DEBRISSAT-2" "43680"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.

**Comment by vladimirpootz** [comment]
@alex-w

**Comment by alex-w** [comment]
Please share all text

**Comment by alex-w** [comment]
Please try run Start -> Programs -> Stellarium-> Stellarium (ANGLE mode)

**Comment by vladimirpootz** [comment]
2020-06-13T07:01:40
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 14.0 (Visual Studio 2015)
Qt runtime version: 5.9.9
Qt compilation version: 5.9.9
Addressing mode: 64-bit
Total physical memory: 8113 MB
Available physical memory: 3691 MB
Physical memory in use: 54%
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
C:\Program Files\Stellarium\stellarium.exe --angle-d3d11 
 -----------------------------------------------------
[ This is Stellarium 0.20.1 - https://stellarium.org/ ]
[ Copyright (C) 2000-2020 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "OpenGL ES 2.0 (ANGLE 2.1.99f075dade7c)"
Current Format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelMainView::init
Detected: OpenGL ES "2.0"
Driver version string: "OpenGL ES 2.0 (ANGLE 2.1.99f075dade7c)"
GL vendor is "Google Inc."
GL renderer is "ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)"
GL Shading Language version is "OpenGL ES GLSL ES 1.00 (ANGLE 2.1.99f075dade7c)"
VS Version Number detected:  5
PS Version Number detected:  5
vs/ps version is fine, we should not see a graphics problem.
GLSL ES Version Number detected:  1
GLSL ES version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\sebho\\AppData\\Local\\stellarium\\stellarium\\cache"
Sky language is  "en_US"
Planetary features language is  "en_US"
Application language is  "en_US"
Couldn't load translations for language  "en_US" in section "stellarium-scripts"
Empty translation file for language  "en_US" in section "stellarium-scripts"
Scripts language is  "en_US"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
SolarSystem has  190 entries.
Loaded 107 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15663 / 15665 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4507 / 4507 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
StelCore: Invalid timezone name: ""  -- not setting timezone.
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.9 (standard edition)"
Loaded 94393 DSO records
Loading DSO outline data ...
Loaded 72 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 1004 / 1004 common star names
Loading DSO name data ...
Loaded 1111 / 1133 DSO name records successfully
WARNING - No position data for 22 objects: "PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "western"
Loaded 81 / 82 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 71 / 72 asterism names
Got location "San Diego, California, United States (32.7638, -117.07; America/Los_Angeles)" for IP "98.175.108.218"
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "AngleMeasure"
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at:  "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Loaded plugin "Satellites"
[Satellites] loading catalog file: "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "1KUNS-PF" "43466"
Satellite has invalid orbit: "DEBRISSAT-2" "43680"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...

**Comment by vladimirpootz** [comment]
\Users\sebho\AppData\Roaming\Stellarium/log.txt:
2020-06-13T07:03:31
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 14.0 (Visual Studio 2015)
Qt runtime version: 5.9.9
Qt compilation version: 5.9.9
Addressing mode: 64-bit
Total physical memory: 8113 MB
Available physical memory: 3331 MB
Physical memory in use: 58%
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Processor speed: 2112 MHz
Processor name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
C:\Program Files\Stellarium\stellarium.exe --angle-d3d9 
 -----------------------------------------------------
[ This is Stellarium 0.20.1 - https://stellarium.org/ ]
[ Copyright (C) 2000-2020 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "OpenGL ES 2.0 (ANGLE 2.1.99f075dade7c)"
Current Format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelMainView::init
Detected: OpenGL ES "2.0"
Driver version string: "OpenGL ES 2.0 (ANGLE 2.1.99f075dade7c)"
GL vendor is "Google Inc."
GL renderer is "ANGLE (Intel(R) UHD Graphics 620 Direct3D9Ex vs_3_0 ps_3_0)"
GL Shading Language version is "OpenGL ES GLSL ES 1.00 (ANGLE 2.1.99f075dade7c)"
VS Version Number detected:  3
PS Version Number detected:  3
vs/ps version is fine, we should not see a graphics problem.
GLSL ES Version Number detected:  1
GLSL ES version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\sebho\\AppData\\Local\\stellarium\\stellarium\\cache"
Sky language is  "en_US"
Planetary features language is  "en_US"
Application language is  "en_US"
Couldn't load translations for language  "en_US" in section "stellarium-scripts"
Empty translation file for language  "en_US" in section "stellarium-scripts"
Scripts language is  "en_US"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
SolarSystem has  190 entries.
Loaded 107 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15663 / 15665 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4507 / 4507 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
StelCore: Invalid timezone name: ""  -- not setting timezone.
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.9 (standard edition)"
Loaded 94393 DSO records
Loading DSO outline data ...
Loaded 72 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Got location "San Diego, California, United States (32.7638, -117.07; America/Los_Angeles)" for IP "98.175.108.218"
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 1004 / 1004 common star names
Loading DSO name data ...
Loaded 1111 / 1133 DSO name records successfully
WARNING - No position data for 22 objects: "PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "western"
Loaded 81 / 82 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 71 / 72 asterism names
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "AngleMeasure"
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at:  "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Loaded plugin "Satellites"
[Satellites] loading catalog file: "C:\\Users\\sebho\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "1KUNS-PF" "43466"
Satellite has invalid orbit: "DEBRISSAT-2" "43680"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...

**Comment by alex-w** [comment]
Is stellarium works in ANGLE mode?

**Comment by vladimirpootz** [comment]
yes

**Comment by vladimirpootz** [comment]
but not as the installed application

**Comment by alex-w** [comment]
Please install drivers for graphics card from intel.com webiste

**Comment by vladimirpootz** [comment]
Intel® Graphics - Windows® 10 DCH Drivers

**Comment by vladimirpootz** [comment]
this ?

**Comment by alex-w** [comment]
Maybe. Your graphic card is Intel(R) UHD Graphics 620

**Comment by vladimirpootz** [comment]
I have went ahead and downloaded it. As the application can now open, there is major discoloration in the graphics. Perhaps it was the wrong one

**Comment by vladimirpootz** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/66872539/84572002-061e7300-ad4c-11ea-8214-1f6514056f4d.png)

**Comment by vladimirpootz** [comment]
this is what i see when opening stellarium @alex-w @gzotti

**Comment by alex-w** [comment]
This is definitely problem for drivers for graphics card.

**Comment by alex-w** [comment]
Please try http://www.intel.com/content/www/us/en/support/detect.html

**Comment by vladimirpootz** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/66872539/84572621-2f410280-ad50-11ea-907a-44ac19e484e3.png)

**Comment by vladimirpootz** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/66872539/84572627-3bc55b00-ad50-11ea-8cbb-7688181dd382.png)

**Comment by vladimirpootz** [comment]
it is all that I am given

**Comment by vladimirpootz** [comment]
everything is up to date...

**Comment by vladimirpootz** [comment]
still does not work

**Comment by alex-w** [comment]
This is very, very strange, because this graphics card should support OpenGL 4.6

**Comment by alex-w** [comment]
Please try https://downloadcenter.intel.com/download/29560/Intel-Graphics-BETA-Windows-10-DCH-Drivers?product=126789

**Comment by gzotti** [comment]
If ANGLE works for you, just use it.

**Comment by vladimirpootz** [comment]
even more strange; while my PC  uses a  64 bit operating system, the 32 bit version of stellarium works perfectly fine.

**Comment by vladimirpootz** [comment]
darn

**Comment by vladimirpootz** [comment]
well it did a second ago

**Comment by vladimirpootz** [comment]
lol

**Comment by vladimirpootz** [comment]
it no longer works

**Comment by gzotti** [comment]
> 
> even more strange; while my PC uses a 64 bit operating system, the 32 bit version of stellarium works perfectly fine.

Most Win32 applications run on Win64.

**Comment by gzotti** [comment]
https://www.zdnet.com/article/windows-10-2004-were-already-looking-into-these-10-issues-says-microsoft/
This is nothing we can do.

**Comment by vladimirpootz** [comment]
I see... Thank you both for the support. Perhaps a future update for Microsoft will allow me to use the application.  @gzotti  @alex-w

**Comment by gzotti** [comment]
See also #1114

**Comment by gzotti** [comment]
See also #1129.

**Comment by mtredway** [comment]
Yeah I have the exact same problem. I was able to get it to work with angle mode. I have the same graphics card too and its up to date.
