### ISSUE TITLE
Taiwan is not province of China

### ISSUE THREAD

**Issue by Charley-Wu** [Stellarium/stellarium#1125]
Taiwan is not province of China.
Taiwan **IS NOT** People's Republic of China (P.R.C.)
Taiwan has a **independent and  democratic** goverment.
P.R.C. is ruled by Communist Party of China, and **Communist Party of China is authoritarian**.
**Please correct this mistake**
In COVID-19, China conceal their epidemic, lead to COVID-19 Pandemic in all world.

**Comment by alex-w** [comment]
The international standard ISO 3166 1-alpha-2 defined Taiwan as province of China and The UN does not recognize the Taiwan as a sovereign state.

**Comment by kahnc** [comment]
The ISO 3166-1 standard is _not a politically neutral standard_. You should use an alternative source for names that is politically neutral like Unicode CLDR.

**Comment by gzotti** [comment]
Discuss your politics elsewhere.
