### ISSUE TITLE
The screen is distorted after startup.

### ISSUE THREAD

**Issue by wtnb-avocet** [Stellarium/stellarium#1129]
![ScreenShot0](https://user-images.githubusercontent.com/66896110/84611905-0b212500-aefa-11ea-90a1-708366dad501.jpg)
![ScreenShot](https://user-images.githubusercontent.com/66896110/84611927-15dbba00-aefa-11ea-8be5-f9fe107a97f0.jpg)
[log.txt](https://github.com/Stellarium/stellarium/files/4777711/log.txt)

I have been using Stellrium 19.3, but when I started it recently, the screen became confused and the normal screen was not displayed.
It is the same even if you restart the PC.
Attach the screenshot of the screen.
After upgrading to the latest version, 20.1, the symptom does not change.

### Actual Behavior
It will look like the screenshot attached at startup.
At startup
After starting

### System
* Stellarium version: stellarium-0.20.1-win64.exe
* Operating system: Windows 10 Home 64bit
* Graphics Card: Intel(R) UHD Graphics 630 Ver.27.20.100.8220
* Screen type (if applicable): Resolution, 2560 x 1440

### Logfile
If possible, attach the logfile `log.txt` from your user data directory.Look into the Guide for its location.

**Comment by alex-w** [comment]
Double of #1124

Please try use ANGLE mode

**Comment by wtnb-avocet** [comment]
It was OK when I started it in ANGLE mode.
I ran the shortcut "Stellarium (ANGLE mode)" in the folder "C:\Windows\ProgramData\Microsoft\Windows\StartMenu\Programs\Stellarium".
