### ISSUE TITLE
Mouse invisible when Mouse Trails on in Windows 10

### ISSUE THREAD

**Issue by Les-Ey** [Stellarium/stellarium#113]
### Expected Behaviour
Should be able to see the mouse pointer in full screen mode
### Actual Behaviour
Can only see the mouse when not in full screen mode

### Steps to reproduce
Tick 'display pointer trails' checkbox under Setup -> devices -> Mouse -> Additional mouse properties -> Pointer options

![image](https://user-images.githubusercontent.com/26347594/36972942-ff4b53d2-20c0-11e8-944e-4c82cb525714.png)

### System
* Stellarium version:  stellarium-0.17.0-win64.exe
* Operating system: Windows 10 Home 1709 16299.248
* Graphics Card: Standard HP Laptop graphics  card
AMD Radeon R4 Graphics 2.00 GHz

### Logfile 
N/A

**Comment by gzotti** [comment]
Before reporting, please check FAQ if issue is known. It has been known for eons.
https://github.com/Stellarium/stellarium/wiki/FAQ#Mouse_cursor_invisible

**Comment by BRUCEJ2** [comment]
Just dn ld'd the app - same issue - Saw this post and turned off mouse trails - Life is good - Thanks !!

**Comment by impeeza** [comment]
Sorry to necrobump this issue but for future release, I do use the attached Scripts to run stellarium, first turns off the mouse pointer trails and then turn on again once you close stellarium!

[StellariumNoMouseTrails.zip](https://github.com/user-attachments/files/18497414/StellariumNoMouseTrails.zip)
