### ISSUE TITLE
Slew telescope arrows won't work

### ISSUE THREAD

**Issue by RonKrc** [Stellarium/stellarium#1132]
**Configuration**: 
- MacBook 13" (2017) and/or iMac 27"
- Stellarium 0.20.1
- macOS 10.14.6
- Kstars/Ekos Indi server (version 3.4.3)
- Skywatcher EQ6-Pro mount
- EQ6-USB direct cable

**Issue**:
The above configuration works and allows me to pilot my mount. I wanted to add Stellarium on top on this. I configured the telescope plugin in Stellarium for INDI (see attachment).

Everything works well, I can point objects and the mount will slew, but the slewing arrows won't work. When I press any of them, the mount's motors tracking sound would slightly change, but it won't slew at all. 

Moving the _Min Max_ slider has no effect.

![Configuration](https://user-images.githubusercontent.com/67007335/84780069-6e3bb600-afe5-11ea-9fcd-1856e87251c0.jpg)
 

![Telescope window](https://user-images.githubusercontent.com/67007335/84778988-0df84480-afe4-11ea-9f01-c2da0b44e6ee.jpg)

**Comment by alex-w** [comment]
Could you check latest beta also?

**Comment by RonKrc** [comment]
Just downloaded the beta and tested, same thing. Not working.

Btw, on the beta, the arrow buttons have no arrow :-)

**Comment by alex-w** [comment]
Please check 0.20.3RC2

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by luzpaz** [comment]
@RonKrc :point_up_2:

**Comment by alex-w** [comment]
Fixed in commit 701d10c
