### ISSUE TITLE
Beta 0.20.1.18005: Import of Bookmarks

### ISSUE THREAD

**Issue by Ruediger3** [Stellarium/stellarium#1133]
When importing Bookmarks without deleting the existing list before, the column UUID is displayed. 

### Expected Behaviour
Import data without column UUID

### Actual Behaviour
Additional column UUID is displayed

### Steps to reproduce
Import bookmarks into not empty list

### System
* Stellarium version: 0.20.1.18005 HEAD
* Operating system: W10
* Graphics Card: AMD
* Screen type (if applicable): 1920x1200

![2020-06-17_22h40_52](https://user-images.githubusercontent.com/65772654/84949069-eccf4b00-b0ec-11ea-8529-93fb210d5f7a.png)

**Comment by alex-w** [comment]
Fixed, thanks!

**Comment by Ruediger3** [comment]
Thanks a lot for the quick fix!
Cheers
Rüdiger
