### ISSUE TITLE
Impossible (?) to deselect an ephemeris mark

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1134]
It seems impossible to easily deselect an ephemeris marker. 

To see what I mean, start on earth and calculate any ephemeris for any body. Now, in the list, select line from the list generated. A marker appears in the sky. If you choose another line, the marker will move to the date of that line. This works fine, but the marker can't be deselected.

The only way I've found to clear that marker, is to generate ephemerides for ALL planets, and then select a marker from any planet (but not Mercury), and then generate an ephemeris from a single planet again afterwards. Is this really the intention?

**Comment by alex-w** [comment]
Fixed, thanks!

Since version 0.20.2 just regenerate the ephemeris to deselect an ephemeris marker (no way to remove selection from list of ephemeris table).

**Comment by Atque** [comment]
@alex-w Thank you for a really quick solution! :)
