### ISSUE TITLE
Taiwan is Taiwan. DO NOT list it as Province of China. 

### ISSUE THREAD

**Issue by abitgeekie** [Stellarium/stellarium#1135]
@alex-w since you labeled previous issue as "won't fix", I have to bring it up here.

How come in the location setting Taiwan is labeled as Province of China? It's not.

When people mention China nowadays, it's clearly referring to People's Republic of China, not Republic of China. 
To avoid confusion, "Republic of China" is now better known as Taiwan. 
People of Taiwan never identify themselves as citizens of People's Republic of China.

Taiwan is at best part of "Republic of China" (ROC) according to its current constitution, but it's NEVER once governed by the People's of Republic of China (PRC). Not even a second.

Why are the territories actually governed by PRC NOT listing their names of province while Taiwan never governed by PRC is listed as Province of China? How ridiculous is that?

Just to name a few places within China...

- Beijing [a city name], China [why didn't you list the name of the province? Hubei]
- Haikou (Hainan), China [also an island. Hainan is a name of province. Why didn't you list that province of China?]
- Guangzhou [City name], China [Where is the name of its province?]
- Macau [Is it a country by its own?]
- Hong Kong [Is it a country by its own?]

This piece of software is clearly "location" sensitive. Users choose the locations most appropriately describe their need. Adding "Province of China" to Taiwan is against reality and is bogus. 

@Alexander Wolf
What make you feel if you see Barnaul listed as territory of USA? China? Germany?
Don't you feel offended at all?
If you do, that's exactly how people of Taiwan felt?

Don't tell me it's based on ISO 3166 1-alpha-2. It's against the fact that Taiwan is never a Province of China (PRC).

**Comment by gzotti** [comment]
https://en.wikipedia.org/wiki/ISO_3166-2:TW
Take note that the string "Province of China" is not the same as the string "Province of PRC".
Please complain at ISO. Make ISO change their codes and designation, and we will follow. We abstain from politics, this is an astronomy program.

**Comment by tsuiwade** [comment]
煞叼
