### ISSUE TITLE
artifact-like black lines in full-screen-mode

### ISSUE THREAD

**Issue by Rosika2** [Stellarium/stellarium#114]
Info:

My system:  Linux/Lubuntu 16.04.3. LTS, 64 bit
stellarium:   v.  0.17.0
                      actually running as appimage within firejail
                      appimage-version: 0.17.0.1-x86_64.AppImage

Hi,
when running stellarium in full-screen-mode there are black lines
showing in the sky.
They´re almost artefact-like, for lack of a better term.

Those lines appear only for a fracture of a second at irregular
intervals and are only visible at daytime of course.
When the sky is black they aren´t visible.

Curious: That phenomenon only is visible when operating stellarium in
full-screen-mode.

Can anyone tell something about it?

Thanks a lot in advance.

Greetings.
Rosika

**Comment by alex-w** [comment]
Please attach or show log.txt from Stellarium

**Comment by Rosika2** [comment]
Hi Alex,
tnx for your answer.
Here´s the log-file:

> 2018-03-05T14:53:39
> Operating System: Linux version 4.4.0-116-generic (buildd@lgw01-amd64-021) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018
> Product Name: Ubuntu 16.04.4 LTS
> Compiled using GCC 4.8.4
> Qt runtime version: 5.6.3
> Qt compilation version: 5.6.3
> Addressing mode: 64-bit
> MemTotal:        3963108 kB
> MemFree:          303988 kB
> MemAvailable:    1609132 kB
> SwapTotal:             0 kB
> model name	: Intel(R) Core(TM) i3-3240T CPU @ 2.90GHz
> cpu MHz		: 2893.429
> model name	: Intel(R) Core(TM) i3-3240T CPU @ 2.90GHz
> cpu MHz		: 2860.917
> model name	: Intel(R) Core(TM) i3-3240T CPU @ 2.90GHz
> cpu MHz		: 2530.816
> model name	: Intel(R) Core(TM) i3-3240T CPU @ 2.90GHz
> cpu MHz		: 2779.355
> 00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])
> Kernel driver in use: i915
> /run/firejail/appimage/.appimage-13602/AppRun 
>  -------------------------------------------------------
> [ This is Stellarium 0.17.0 - http://www.stellarium.org ]
> [ Copyright (C) 2000-2017 Fabien Chereau et al.         ]
>  -------------------------------------------------------
> Writing log file to: "/home/rosika/.stellarium/log.txt"
> File search paths:
>   0 .  "/home/rosika/.stellarium"
>   1 .  "/run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium"
> Config file is:  "/home/rosika/.stellarium/config.ini"
> Default surface format:  QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior 0, swapInterval 1, profile  0)
> Desired surface format:  QSurfaceFormat(version 2.1, options QFlags(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior 0, swapInterval 1, profile  0)
> StelGLWidget constructor
> StelGraphicsScene constructor
> initializeGL
> OpenGL supported version:  "3.0 Mesa 17.2.8"
> Current Format:  QSurfaceFormat(version 3.0, options QFlags(0x4), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior 0, swapInterval 1, profile  0)
> StelMainView::init
> Detected: OpenGL "3.0"
> Driver version string: "3.0 Mesa 17.2.8"
> GL vendor is "Intel Open Source Technology Center"
> GL renderer is "Mesa DRI Intel(R) Ivybridge Desktop "
> GL Shading Language version is "1.30"
> MESA Version Number detected:  17.2
> Mesa version is fine, we should not see a graphics problem.
> GLSL Version Number detected:  1.3
> GLSL version is fine, we should not see a graphics problem.
> Cache directory is:  "/home/rosika/.cache/stellarium/stellarium"
> Sky language is  "de_DE"
> Planetary features language is  "de_DE"
> Application language is  "de_DE"
> Loading Solar System data (1: planets and moons) ...
> Loading from : "/run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/data/ssystem_major.ini"
> Texture "/run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/textures/earth-shadow.png" does not exist
> Loaded 77 Solar System bodies
> Loading Solar System data (2: minor bodies)...
> Loading from : "/home/rosika/.stellarium/data/ssystem_minor.ini"
> Texture "/run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/textures/earth-shadow.png" does not exist
> Loaded 101 Solar System bodies
> File ssystem_minor.ini is loaded successfully...
> Loading nomenclature for Solar system bodies ...
> Loaded 15449 / 15454 items of planetary surface nomenclature
> Loading star data ...
> "Loading /run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/stars/default/stars_0_0v0_7.cat: 0_0v0_7; 4979"
> "Loading /run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/stars/default/stars_1_0v0_7.cat: 1_0v0_7; 21806"
> "Loading /run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/stars/default/stars_2_0v0_7.cat: 2_0v0_7; 150850"
> "Loading /run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/stars/default/stars_3_1v0_4.cat: 3_1v0_4; 425807"
> Finished loading star catalogue data, max_geodesic_level:  3
> Loading scientific star names from "/run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/stars/default/name.fab"
> Loaded 4506 / 4506 scientific star names
> Loading variable stars from "/run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/stars/default/gcvs_hip_part.dat"
> Loaded 6916 / 6916 variable stars
> Loading double stars from "/run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/stars/default/wds_hip_part.dat"
> Loaded 16412 / 16412 double stars
> Loading cross-identification data from "/run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/stars/default/cross-id.dat"
> Loaded 108338 / 108338 cross-identification data records for stars
> navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
> Loading DSO data ...
> [...] "Stellarium DSO Catalog, version 3.3 (standard edition)"
> Loaded 90416 DSO records
> Loading DSO outline data ...
> Loaded 63 DSO outline records successfully
> LandscapeMgr: initialized Cache for 100 MB.
> Loading star names from "/run/firejail/appimage/.appimage-13602/usr/bin/../share/stellarium/skycultures/western/star_names.fab"
> Loaded 847 / 847 common star names
> Loading DSO name data ...
> Loaded 1004 / 1021 DSO name records successfully
> WARNING - No position data for 17 objects: "PGC 621, PGC 2345, PGC 2906, PGC 2907, PGC 14098, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
> Loaded 88 / 88 constellation records successfully for culture "western"
> Loaded 85 / 85 constellation art records successfully for culture "western"
> Loaded 88 / 88 constellation names
> Loading constellation boundary data ... 
> Loaded 782 constellation boundary segments
> Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
> ERROR reading asterism lines record at line  63 for culture "western"
> Loaded 53 / 54 asterism records successfully for culture "western"
> WARNING - asterism abbreviation "TA6" not found when loading asterism names
> Loaded 43 / 44 asterism names
> stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
> stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
> Initializing basic GL shaders... 
> Creating GUI ...
> Loaded plugin "Exoplanets"
> [Exoplanets] Version of the format of the catalog: 1
> [Exoplanets] loading catalog file: "/home/rosika/.stellarium/modules/Exoplanets/exoplanets.json"
> Loaded plugin "FOV"
> Loaded plugin "MeteorShowers"
> MeteorShowersMgr: Loading catalog file: "/home/rosika/.stellarium/modules/MeteorShowers/showers.json"
> Loaded plugin "Novae"
> [Novae] version of the catalog: 1
> [Novae] loading catalog file: "/home/rosika/.stellarium/modules/Novae/novae.json"
> Loaded plugin "Oculars"
> Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
> Oculars::validateIniFile ocular.ini exists at:  "/home/rosika/.stellarium/modules/Oculars/ocular.ini" . Checking version...
> Oculars::validateIniFile found existing ini file version  3.1
> Loaded plugin "Satellites"
> [Satellites] loading catalog file: "/home/rosika/.stellarium/modules/Satellites/satellites.json"
> Satellite has invalid orbit: "FLOCK 2E-10" "41572"
> Satellite has invalid orbit: "FLOCK 2E-12" "41573"
> Satellite has invalid orbit: "FLOCK 2E-11" "41574"
> Satellite has invalid orbit: "FLOCK 2E'-10" "41576"
> Satellite has invalid orbit: "FLOCK 2E'-12" "41578"
> Satellite has invalid orbit: "STARS-C" "41895"
> Loaded plugin "SolarSystemEditor"
> Using the ssystem_minor.ini file that already exists in the user directory...
> Dubious result: Landscape  "Hurricane"  not calibrated. Opacity test represents mathematical horizon only.
> Unloaded plugin "SolarSystemEditor"
> Unloaded plugin "Satellites"
> Unloaded plugin "Oculars"
> Unloaded plugin "Novae"
> Unloaded plugin "MeteorShowers"
> Unloaded plugin "FOV"
> Unloaded plugin "Exoplanets"
> Downloaded 0 files (0 kbytes) in a session of 445.036 sec (average of 0 kB/s + 0 files from cache (0 kB)).
> LandscapeMgr: Clearing cache of 2 landscapes totalling about  17 MB.

Greetings
Rosika

**Comment by gzotti** [comment]
If artefact-like black lines appear to occasionally flicker through the screen at irregular intervals, then they are artefacts of the graphics system. I am afraid we cannot do much about them.

**Comment by Rosika2** [comment]
Hi gzotti,
tnx a lot.

O.K., that probably seems to be the case here.
It´s odd though that this only happens in full-screen-mode. 
Nevertheless as a workaround I can maximize the window, which is almost as good as full-screen-mode.
No artefacts there.

Greetings.
Rosika
