### ISSUE TITLE
Error in calculating the Contrast Index of Nebula

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#1145]
https://github.com/Stellarium/stellarium/blob/82d4b183e2e16c65d6aa65c8a7d9ca60f57953db/src/core/modules/Nebula.cpp#L615

When getSurfaceBrightnessWithExtinction is returning 99.f, the Contrast Index will be -30.02. The result of this should be ignored.

https://github.com/Stellarium/stellarium/blob/82d4b183e2e16c65d6aa65c8a7d9ca60f57953db/src/core/modules/Nebula.cpp#L594

BTW, some objects only have bmag, and bmag may be able to be used in getSurfaceBrightnessWithExtinction.

**Comment by alex-w** [comment]
Please check version 0.20.2.18060
