### ISSUE TITLE
Add toggle to show planet labels at all times

### ISSUE THREAD

**Issue by denDAY04** [Stellarium/stellarium#1146]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An option to enable planet labels to be shown at all times, when the planet is within the visible hemisphere. 

**Describe alternatives you've considered**
None.

**Additional context**
With the current options, the planet labels are not visible during daytime until you zoom in at their location. This makes it difficult to get a quick overview of where something is in the sky, unless you already know where to look/zoom in, or you search for it.

**Comment by alex-w** [comment]
Are you tried move right the slider "Labels and Markers" on SSO tab?

**Comment by denDAY04** [comment]
> Are you tried move right the slider "Labels and Markers" on SSO tab?

Yes, that does not have the desired effect; in fact I cannot perceive what effect that slider has in the first place.

**Comment by alex-w** [comment]
But you may make labels visible by daylight already - please open file config.ini and set value for option astro/labels_amount to 300 for example.

**Comment by denDAY04** [comment]
That does indeed achieve the desired result of making sure the planetary labels are visible during bright daylight. But achieving this should preferably be done through a toggle in the options menu, not manually editing an ini file.

**Comment by alex-w** [comment]
> That does indeed achieve the desired result of making sure the planetary labels are visible during bright daylight. But achieving this should preferably be done through a toggle in the options menu, not manually editing an ini file.

Why? I disagree. You are first person, who need visible labels for Solar system objects in wide FOV and daylight in last 10 years.

**Comment by denDAY04** [comment]
> Are you tried move right the slider "Labels and Markers" on SSO tab?

I just tried this again and realised I was looking at the wronger slider (under the wrong tab). Using the slider under the SSO tab, and moving it fully to the right position, does indeed make the labels visible like I was aiming for. So the feature is already natively supported in the application. My apologies.
