### ISSUE TITLE
Please allow bigger Number of segments for Orbital lines

### ISSUE THREAD

**Issue by fliker09** [Stellarium/stellarium#1148]
Maybe also Segment length limit can be reduced as well. The issue becomes evident on really close zoom in, which is required for ISS transits. ISS and the its orbital line are not aligned, which is kinda frustrating. I've attached a screenshot with an example. A note here - it's not a problem only for planetary transits, the problem is evident with Sun/Moon transits as well.
![Screenshot_20200627_155028](https://user-images.githubusercontent.com/18057950/85922824-d5335780-b88e-11ea-9f7d-59110081129f.png)

**Comment by gzotti** [comment]
A solution can follow the pattern for planet orbit lines, "only" add the satellite position into the chain of segments.

**Comment by alex-w** [comment]
Please check version 0.20.2.18060

**Comment by fliker09** [comment]
It took me a long time to get it checked... Finally back in business of ISS transits! Thanks a lot for the update, it does actually help!
