### ISSUE TITLE
Enabling Show artificial satellites as markers leads to ALL satellites being shown up

### ISSUE THREAD

**Issue by fliker09** [Stellarium/stellarium#1149]
### Expected Behaviour
It should show only the satellites enabled on the Sources tab.

### Actual Behaviour
Without the option enabled - only ISS is shown as expected. After enabling it - every possible satellite is shown up.

### Steps to reproduce
Enable only one satellite source (in my case a custom one, containing only ISS TLE).
Turn on the Show artificial satellites as markers option and get a sky filled with satellites (ISS is not lost, at least that's good)

### System
* Stellarium version: Stellarium-0.20.2-x86_64.AppImage
* Operating system: KDE neon 5.19.2
* Graphics Card: Nvidia GTX960, with 440.100-0ubuntu0.18.04.1 driver
* Screen type (if applicable): 1920x1200, no scaling

[log.txt](https://github.com/Stellarium/stellarium/files/4840591/log.txt)

![Screenshot_20200627_160212](https://user-images.githubusercontent.com/18057950/85923202-d619b880-b891-11ea-9b01-66435feb2c7b.png)
![Screenshot_20200627_160204](https://user-images.githubusercontent.com/18057950/85923204-d6b24f00-b891-11ea-937d-a40aec56199e.png)
![Screenshot_20200627_160153](https://user-images.githubusercontent.com/18057950/85923205-d74ae580-b891-11ea-9cbf-2e1f99911912.png)

**Comment by alex-w** [comment]
This is not a bug. I don't know why you expect to see very strange behaviour - every satellite has option "Displayed" to manage visibility of him.

**Comment by fliker09** [comment]
Expected behavior is that the satellites from chosen sources would be switched from star-mode to marker-mode, without making satellites from inactive sources visible.

**Comment by alex-w** [comment]
Seriously? The checkbox in sources tab allows adding new satellites from marked URLs. This option does not change visibility of satellites!

**Comment by fliker09** [comment]
Please take a look at the first screenshot - I've chosen only ONE source, which contains ISS and no other satellites at all.

**Comment by fliker09** [comment]
Oh... got it now. Ok, can we make it NOT show satellites which are not selected in the Sources tab?

**Comment by alex-w** [comment]
See second tab...

**Comment by fliker09** [comment]
How to make a mass-hiding of the satellites? By removing the sources? If yes - that seems kinda poor approach tbh :-\

**Comment by fliker09** [comment]
Ok, found it, holding Shift button does the trick :-) You can close it probably
