### ISSUE TITLE
When I click on Jupiter in 0.12.9, is the distance to Jupiter the distance at that instant?  Or, is the distane somehow adjusted for light travel?

### ISSUE THREAD

**Issue by jdumar** [Stellarium/stellarium#115]
Before reporting an issue, please *absolutely make sure* to check the closed issues 
(https://github.com/Stellarium/stellarium/issues?q=is%3Aissue+is%3Aclosed) 
whether it has been reported and solved/closed already! Don't report in this case.

Also look into the wiki (https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version) 
and check if you are attempting to report a known issue. Don't report in this case.

Also look into the User Guide before reporting unexpected but correct behaviour. Don't report in this case.

If you want to report a feature wish, delete these template lines above and below, and fill in. 

If you want to report a bug, please make sure to update and verify the bug still exists in the current version. 
In this case please also check current beta builds from http://stellarium.org
If bug still persists, delete text above down to and including this line and fill in:

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
As you see in the issues template which you totally ignored, this is about issues, bugs or feature wishes. Such questions are still handled in the SF forum. 

Why don't you click on the checkbox "light time correction" to answer your question?
