### ISSUE TITLE
A lot (?) of old comets' orbital data is inaccurate

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1152]
I've noticed that a lot of old comets' orbital data is inaccurate. I'm comparing some photos I took of C/2014 E2 (Jacques), and the official data fits better than the data downloaded through Solar System Editor. Look at this lousy photo of said comet taken on 2014-08-24, 00:01 UTC+2:
![20140824_Jacques](https://user-images.githubusercontent.com/37028368/85940545-4de0f500-b91d-11ea-88dd-2d5357766f97.png)

Compare this to Stellarium screenshots:

With old, incorrect parameters (taken from http://astro.vanbuitenen.nl/cometelements?format=mpc&mag=obs):
![stellarium-021](https://user-images.githubusercontent.com/37028368/85940562-723cd180-b91d-11ea-9c3e-af8376bdc8e3.png)

With new, accurate parameters:
![stellarium-018](https://user-images.githubusercontent.com/37028368/85940570-808aed80-b91d-11ea-8286-3a642a466422.png)

The new parameters were taken from https://ssd.jpl.nasa.gov/sbdb.cgi?sstr=C/2014%20E2. These seem to agree very well with the photo taken.

I've noticed this problem for a few other, non-bright comets. It seems Stellarium's sources are not quite accurate, at least if the comet dates back a few years. This is probably out of the dev team's reach anyway, but I think you should know. :) Maybe there is some better source out there that could be used?

**Comment by gzotti** [comment]
The Solar System Editor is accessing the elements hosted by the Minor Planetary Data Center, which is the institute best known for collecting orbital elements. Presumably, when you access elements for C/2014 XY in 2020, you get the most recent elements, which are far away from the epoch of observation. Of course they don't fit!

**Comment by Atque** [comment]
@gzotti Ah, I see, that's news to me. Then of course, they won't agree with my (or anyone else's) photos. This is a linked to #453, we wish for old orbital data.

**Comment by Atque** [comment]
Closing this since it's a duplicate.
