### ISSUE TITLE
Unit tests fail on i686

### ISSUE THREAD

**Issue by DarthGandalf** [Stellarium/stellarium#1153]
### Expected Behaviour
Tests pass

### Actual Behaviour
Unit tests fail. `testConversions::testVec3dToHtmlColor()` seems to started failing since #1055 and `TestStelSphericalGeometry::testSphericalPolygon()` seems to fail even on 0.19.3, I don't know when it started to fail.

### Steps to reproduce
1. Find a i686 machine, e.g. via qemu/kvm with "qemu32" CPU. (I haven't tested whether it's reproduceable on i686 binary on a x86_64 kernel.)
2. Compile stellarium
3. Run unit tests

### System
* Stellarium version: 0.20.2
* Operating system: Gentoo Linux
* Graphics Card: doesn't matter. Tests are running via Xvfb
* Screen type (if applicable): 

### Logfile 

[LastTest.log](https://github.com/Stellarium/stellarium/files/4848330/LastTest.log)
[build.log.zip](https://github.com/Stellarium/stellarium/files/4848336/build.log.zip)

**Comment by DarthGandalf** [comment]
https://bugs.gentoo.org/730116 has slightly cleaner logs from 0.20.1, though it exhibits only `testSphericalPolygon` failure.

**Comment by DarthGandalf** [comment]
I've tested i686 binary on x86_64 kernel, testSphericalPolygon also fails there.

**Comment by alex-w** [comment]
Confirmed on Debian Testing i386 with Qt 5.14.2 and GCC 9.3.0

**Comment by gzotti** [comment]
Win10, Qt5.13, MSVC2017:

```
PASS   : TestStelSphericalGeometry::testSphericalPolygon()
PASS   : TestConversions::testVec3dToHtmlColor()
```
The latter is apparently just a rounding error, still stupid.

**Comment by alex-w** [comment]
@gzotti are you tried 32-bit mode for MSVC?

**Comment by gzotti** [comment]
No, only 64bit build on a "current" system.

**Comment by DarthGandalf** [comment]
64bit build works on Linux as well. This is specifically about 32 bit.

**Comment by alex-w** [comment]
On all our 64-bit environments (Travis, AppVeyor, my system) all tests was passed. The issue on 32-bit environment only.

**Comment by DarthGandalf** [comment]
Thanks, fix confirmed
