### ISSUE TITLE
Object information font color

### ISSUE THREAD

**Issue by pad39b** [Stellarium/stellarium#1156]
The information of an object at least for me is hard to read when atmosphere is ON due to low contrast of the fonts against the sky.
I would like to see a better contrast of the fonts when atmosphere is ON.

I think about another color for fonts displayed as information of an object selected. Or maybe to have a way to choose a color from a list, so any user can set the font color which best fits for their own display. Hope this can be implemented. Thank you.
![font color](https://user-images.githubusercontent.com/67872238/86538418-f665fa80-bec3-11ea-91b5-aac5e46bd1ee.JPG)

**Comment by alex-w** [comment]
Just define color/daylight_text_color in config.ini file

**Comment by pad39b** [comment]
Yes, I know it is possible to change the color in the config file, but it takes a while to find the right color number combination ;-)

**Comment by alex-w** [comment]
Please check version 0.20.2.18060

**Comment by pad39b** [comment]
Great! after looking around I have found on the tools configuration menu the option to change the info text daylight color. Thank you!
