### ISSUE TITLE
Distance missing: when object "doesnot go beyond horizon"

### ISSUE THREAD

**Issue by GaVenga** [Stellarium/stellarium#1157]
object does not go beyond horizon - would like to know the distance anyway

**Comment by alex-w** [comment]
Distance is not touched by elevation of object. Which object does not have distance?

**Comment by gzotti** [comment]
OP presumably wants to know angular distance between upper culmination and mathematical horizon.

**Comment by alex-w** [comment]
@gzotti maybe yes, maybe not.

**Comment by GaVenga** [comment]
> ...Distance is not touched by elevation of object. Which object does not have distance?...
All always visible objects show the distance in Light-Years
all objects  that do not go beyond horizon -> do not show the distance in LJ but the remark "Objekt geht nicht über den Horizont"

**Comment by alex-w** [comment]
Please show screenshots

**Comment by gzotti** [comment]
@GaVenga I cannot reproduce that.

> Gacrux
> ...
> Transit: 0h04m
> Objekt geht nicht über Horizont
> IAU-Sternbild: Cru
> Entfernung: 88.56±0.43 LJ
> ...

**Comment by alex-w** [comment]
@GaVenga please show log and screenshot
