### ISSUE TITLE
Bookmarks: Posibility to add some text/notes and save "Date/Time" added field

### ISSUE THREAD

**Issue by Ruediger3** [Stellarium/stellarium#1158]
Hello Team,

I would appreciate to have the possibility to add some annotations to the bookmarks, since very often there is only "nameless star". Moreover I have noticed, that the Date/Time added is not stored, so you get easily confused when you have set multiple bookmarks for framing for a long term imaging project close to each other for an identical target. 

Would be great to have both features. Thank you in advance!

CS
Rüdiger

**Comment by gzotti** [comment]
To add date and time to the bookmark, enable "Add date and time" in the bookmark dialog.

**Comment by Ruediger3** [comment]
Sorry, I have overseen it. Maybe a good idea to make checked by default?
The request for custom annotations is still valid.

**Comment by gzotti** [comment]
Please participate in #976 for future changes of the Bookmarks. I close this as duplicate.
