### ISSUE TITLE
alternative HIPS server issue

### ISSUE THREAD

**Issue by doroshv** [Stellarium/stellarium#1159]
I'd like to load user-generated hips map to Stellarium and the approach I took was to follow section 10.2 of the manual and specify alternative sources/1/url as a local server, and then add hipslist file which would contain URL to my map. The problem is though, that Stellarium does not seem to list any surveys in this case. The problem is not related to my hipslist file as I started by replicating the list from  http://alaskybis. unistra.fr/hipslist locally, and also int his case the list of surveys in Stellarium is empty. The steps to reproduce issue are, therefore, to 

1) clone http://alaskybis. unistra.fr/hipslist to localhost server and verify that it is accessible
2) modify config.ini to 
[hips]
sources/size = 1
sources/1/url = "http://localhost/hipslist" 

3) open Stellarium, go to HIPS survey list, it's empty. If the [hips] section of the config is cleaned, the list reappears again

thanks!

**Comment by gzotti** [comment]
Currently I have no local server to try. One idea: can you try 

`sources/1/url = http://localhost/hipslist`

without quotes?

**Comment by doroshv** [comment]
thanks, but does not seem to change anything, the survey list remains empty. Can it have something to do with ~ in URL?

**Comment by gzotti** [comment]
You could simply try it...

**Comment by gzotti** [comment]
I just tested it with a XAMPP server on Windows. A URL without quotes works. I think cannot test a ~ URL with XAMPP though (?)
