### ISSUE TITLE
Sigma Ori C(mag 8.8) star missed from full star catalog

### ISSUE THREAD

**Issue by prokator** [Stellarium/stellarium#116]
Sigma Ori C(mag 8.8) star missed from full star catalog catalog
http://www.astronomyassociation.org/atlas/at/mst/mstso.gif

### Expected Behaviour
sigma Ori C present
### Actual Behaviour
Empty space
### Steps to reproduce
Open Stellarium
Find Sigma Ori star
Magnify to see sigma Ori D

### System
* Stellarium version: Stellarium 0.17.0
Win10
NVidia GTX 670

**Comment by i-grow-carrots** [comment]
@prokator   I'm far from being an expert here in any way, but I suspect it has something to do with the fact that this star doesn't have a Hipparchos number.

**Comment by prokator** [comment]
@i-grow-carrots you can spot a lot of stars without Hip number. So it is not a case. You can see a lot of noncatalog stars if you download all additional almanacs.
Additional link to Sigma Ori C (without alert from google chrome)
https://www.cloudynights.com/gallery/image/6269-sigma-ori/
