### ISSUE TITLE
Object lock feature

### ISSUE THREAD

**Issue by richardhendricks** [Stellarium/stellarium#1160]
**Is your feature request related to a problem? Please describe.**
I'm always running into issues where the object I am wanting to track/follow/etc keeps getting knocked off the cursor.

**Describe the solution you'd like**
A cursor lock function that "locks" the cursor onto an object such as a star/DSO/comet/etc and will not switch to a different object until unlocked. This would be included when saving default settings so that you can quit and restart and your object will still be locked.

**Describe alternatives you've considered**
Setting a marker kinda works, but isn't as elegant a solution, and doesn't work if the object moves quickly.

**Additional context**
I am a fairly inexperienced user, so I often misclick on the starfield when I mean to move or do another operation, forcing me to search yet again for my object of interest.
This feature would also be convenient for tracking an object across multiple sessions.

**Comment by richardhendricks** [comment]
An alternative would be an "object stack" that you can Undo/Redo object selections so you can select the object you want to focus on, then look at other objects and use ctrl-Z to undo and return to the previous object.

**Comment by alex-w** [comment]
Looks like OP want to get SkyChart (Cartes du Ciel). This is maybe strange, but are you tried stop time and use one click instead of double-click on the sky?

**Comment by Vigrond** [comment]
Gonna add my cents to this.  First time user.

You have way too many functions on the left mouse button

Left click:

- Clicks on various UI overlay elements such as buttons, etc.
- Focuses on a spot in the sky, overriding any previous selection
- If you hold left click and drag, it moves the viewport.  However it does NOT change focus or override.
- Double left clicking when something is in focus will shift the viewport to it.  But for some reason if nothing is focused, double click does nothing if clicking on an empty place in the sky.

Right click:
Deleselects everything and deletes your focus

We are all not mouse-ninjas with 100% accuracy on position and button clicks vs drags vs single clicks and double clicks.

I started using Stellarium to map out NEOWISE.  I had to re-enter neowise in the search and pull it up about 10x because I had to learn all the different mouse functions that deleted my focus by trial and error.

Is there a way to lock focus?  Can I "save" my object and pull it up via hotkey?  Can I make it stay on the screen while I map out things without worrying about misclicking a UI element by 5 pixels and having to restart my work?  I don't know.

Please think of usability in great software like this.

**Comment by alex-w** [comment]
>Is there a way to lock focus? 

Yes, just use keyboard for navigation.

>Can I "save" my object and pull it up via hotkey? 

Alt+B

>Can I make it stay on the screen while I map out things without worrying about misclicking a UI element by 5 pixels and having to restart my work?

Introducing an option to disable acceptance of mouse clicks to avoid "misclicking" is very strange, because this "issue" may be simply resolved by not producing an extra clicking.

**Comment by Vigrond** [comment]
> Introducing an option to disable acceptance of mouse clicks to avoid "misclicking" is very strange, because this "issue" may be simply resolved by not producing an extra clicking.

In the context of astrophotography, laying out objects in the sky and then "locking" them while you reposition the viewport, look for reference objects, and model your shots with the camera features seems extremely logical to me, especially considering that many of the aforementioned operations require many clicks, double clicks, and right clicks on UI elements that are either directly on the sky or very close to it.

Time spent planning shots can easily be a few hours.

Locking your mapped out celestial objects in the sky removes the extra requirement of "not producing an extra click in your operations of 500+ clicks over the period of a few hours".

**Comment by alex-w** [comment]
>In the context of astrophotography, laying out objects in the sky and then "locking" them while you reposition the viewport, look for reference objects, and model your shots with the camera features seems extremely logical to me, especially considering that many of the aforementioned operations require many clicks, double clicks, and right clicks on UI elements that are either directly on the sky or very close to it.

I really want to see video where you "planning shots", because I really don't understand your logic. You want to get a shortcut (or tool), which will block mouse clicks and you want use mouse for "many of the aforementioned operations require many clicks, double clicks, and right clicks on UI elements that are either directly on the sky or very close to it" in same time. Are you see problem here?

>This feature is extremely common in photo editing applications and is called "locking layers". It is not strange to people who work on those programs to lock a layer as to prevent misclicking an underlying element. Fortunately developers at Adobe did not think that was strange and also did not defer to the user's lack of mouse aptitude and clicking accuracy.

No problem, you may freely use Adobe Photoshop as tool for plannging observations and planetarium, go ahead.

**Comment by Vigrond** [comment]
> No problem, you may freely use Adobe Photoshop as tool for planning observations and as planetarium, go ahead.

Thank you for the suggestion.  Apparently Stellarium maintainers take offense to feature requests.  I'll go find other software to support.

**Comment by alex-w** [comment]
> An alternative would be an "object stack" that you can Undo/Redo object selections so you can select the object you want to focus on, then look at other objects and use ctrl-Z to undo and return to the previous object.

@richardhendricks  Are you tried use Bookmarks tool (Alt-B) to quick select of track object?

**Comment by gzotti** [comment]
@Vigrond  We can and will certainly not fulfill everybody's dreams on the call of the dog whistle. We develop our dreams, and you can also use the program. 
https://github.com/Stellarium/stellarium/wiki/FAQ#why-dont-you-implement
Most users who are familiar with the look and feel after ~2-5 minutes are happy. Some prefer other tools. That's OK for us.

**Comment by alex-w** [comment]
Why don’t use equatorial mount for track the celestial object with effect of “locking”? This is obvious solution for people, who understand celestial coordinate systems. Why many peoples use double clicks everywhere? Looks like a bad heritage of Windows users standard behavior.

**Comment by gzotti** [comment]
I think there is nothing in this request that cannot be handled with a simple bookmark ("I lost my object. Here it is again.") or even a startup.ssc including an object to select on startup. Large changes in the look and feel will irritate millions of currently happy users.

**Comment by axd1967** [comment]
bookmarks are an obvious workaround for this issue: just add the object to the bookmarks, and whenever the user loses the object for any reason, the bookmark can be double-clicked in order to jump back.

**Comment by gzotti** [comment]
And therefore this issue should have been closed long ago.

**Comment by richardhendricks** [comment]
As a developer myself, I also enjoy bellowing RTFM at questions. But I have some comments here before you close this ticket.

3 users complained about this issue. Why is that? Instead of saying RTFM, maybe the devs need to step back and ask that question first.

- When I submitted this ticket, I did my due diligence and searched the proper locations for a solution. The out-program keylist at the old wiki (http://stellarium.sourceforge.net/wiki/index.php/Keyboard_actions) does not mention the alt-B bookmark function, and the current wiki does not have a keyboard actions page.

- The current in-program keylist is very long, has no search function, and for some reason, is organized alphabetically by grouping. The bookmarks key is in the Windows(?) list at the bottom of the keylist, and is the only non-function key in that list. (Thanks, btw for adding the shortcut key to the popup help when hovering over a UI element, that is a nice feature.) 

- In addition, the Bookmarks window does not rate first-class treatment in the UI - keys like Show Exoplanets which require 3 keystrokes are on the top level UI with activate/de-activate buttons but Bookmarks is a "hidden" feature that a casual user will not even know exists. I understand reluctance to change a long-lasting UI that grew organically over time, believe me (I still complain heavily whenever MS changes their UI for no reason.) Perhaps a Bookmarks [Alt-B] tab can be added to the Find window to help highlight the function.

- Alex's responses to @Vigrond come off as pretty hostile, but perhaps that is due to cultural differences, idk. Stellarium is commonly recommended as a tool for astrophotographers and includes many astrophotography features baked in at the top level - such as the Oculars plugin enabled by default. Yes, setting up for astrophotography can take hours worth of time. Searching for which targets are available/worthwhile based on moon phase, checking the framing of that object with our available telescopes and camera (APs typically have multiple of both for different objects, setup time, and equipment features), determining where precisely to place the camera FOV will require lots of moving and rotating (ie, shooting the Leo Triplet to capture the asteroid Vesta, and including NGC3593 in the final capture: https://hendric.smugmug.com/Hobbies/Astronomy/20210611-Leo-Triplet-with-Vesta-from-Austin-Skies/i-ZN6TnNq/A)

- Thank you for #1168, that does help somewhat. But an object lock is still a distinctly different feature, and I still feel would be useful on its own. Overloading "Center on Selected Object [Space]" to add "/Lock selected Object [Shift-Space]" is certainly not "Large changes in the look and feel will irritate millions of currently happy users."

Finally, many thanks for your time and the efforts of the Stellarium team. I am a strong supporter of open source software and will put in a donation via Open Collective. I don't expect it (nor should it) change the disposition of this ticket. :)

**Comment by richardhendricks** [comment]
Ah, thanks! Interesting that the http://stellarium.sourceforge.net/wiki/index.php/Keyboard_actions didn't include the F7 key at all - probably added after the last edit? F7 is mentioned on the F1 Help keylist, but way down in the Windows section. Duplicate information I guess, I didn't look for a shortcuts key after I already found the keylist on the Help window.

Looking at the F7 window, it does look like bookmark functions aren't assignable. Could the Bookmark->Add Bookmark/Goto Bookmark (default with no bookmark selected be the most recently added) be added to that list so users can set them and goto the most recent via a personal key?

I'm also looking at scripting a possible solution as a kludge - setup a script slot hotkey, and on activation record the currently selected object and just repeatedly re-select it every X seconds to "lock" it.

**Comment by axd1967** [comment]
Indeed, the Bookmark feature still needs shortcuts to be added, you are right. For example, a very handy shortcut is to (un)highlight the bookmarks. (It is in my private todo list, but not high enough. )

**Comment by Zi7ar21** [comment]
I am having a fun time going through and reading Stellarium's Issue drama. I don't know why but people just really seem to take offense when you submit an Issue on GitHub sometimes, it's happened to me on another repository before. I do see the same pattern though:

1. Someone Submits an honest Issue. It may be silly or small sometimes but at least it's usually not a bad idea.
2. The aggressor enters the thread and explains why it's not necessary, acts stubborn and avoids any reason that the feature might be useful.
3. The person explains how it's useful and usually does a good job describing why it might not hurt. In this case, someone else actually stepped in. Thanks @Vigrond!
4. Fighting, which usually results in the issue being closed. On this repo, it seems that the aggressor finds a small mistake in someone's logic and trolls them with it. It's like their goal is just to make them mad.

I just came here after reading #1804. Good times, I recall this not being the first time that the same person in question on this repository has gotten upset and started beef. I understand this person in question has taken this repository as basically a second job without pay (unless there's donations?) and that they are probably very busy. But there's no need to be so rude. These innocent people submitting issues aren't trying to point out flaws in your work, they are offering feedback and you should be thankful. They are using their precious time, just as much as you are using yours, to help better the repository. So please, grow up. I'm watching this repository and I get notifications from it all the time. I personally love Stellarium, and I'm glad it's open source. I hope it gets better as people learn to act civilized when contributing.
