### ISSUE TITLE
Neowise search points to an older comet

### ISSUE THREAD

**Issue by gheja** [Stellarium/stellarium#1161]
### Expected Behaviour

Search for `neowise` should show `C/2020 F3`, the comet currently observable.

### Actual Behaviour

When searching for `neowise` the only result is `C/2016 U1`, the current comet `C/2020 F3` does not show up. It is missing from the Comet list as well.

### Steps to reproduce

Search for `neowise` or `C/2020 F3`.

### System
* Stellarium version: 0.20.2
* Operating system: Linux
* Graphics Card: n/a
* Screen type (if applicable): n/a

### Logfile 
n/a

**Comment by alex-w** [comment]
You can freely add any comet through Solar System Editor plugin

**Comment by gheja** [comment]
I tried to add the comet manually using the Solar System Editor based on [this guide](https://stargazerslounge.com/topic/327045-stellarium-adding-comets/?do=findComment&comment=3561474) but got "SSL Handshake Failed" message. As the message with the URL was printed to stderr I downloaded that URL that contained this comet, however when I added it by selecting local file Stellarium crashed with a segmentation fault message. However next time I started it was added.

I think it would be nice to have the comet added to the default list, also ranked higher than the earlier comet when searched for `neowise` as that would be much more convinent.

Well yeah, to be honest, I searched for it and haven't checked the catalog number, stayed up until 3 AM and looked in the wrong direction for a while, also trees covered the sky in the correct direction so I missed it :D I admit it was a user error.

**Comment by alex-w** [comment]
See https://github.com/Stellarium/stellarium/issues/999

Sorry, we can't fix SSL issue due AppImage architect problem.

**Comment by adamdullenty** [comment]
Is there a way to import this comet on the Android app please?

**Comment by alex-w** [comment]
> Is there a way to import this comet on the Android app please?

Just update android app

**Comment by alex-w** [comment]
See also #578

**Comment by alex-w** [comment]
Sorry, we discontinue support an AppImage builds since version 0.20.3 due technical problems of AppImage architecture! Please use snap packages instead.
