### ISSUE TITLE
Impossible to use the Phenomena tab in AstroCalc when not on earth?

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1162]
I was playing around with the comet C/2020 F3 NEOWISE, allowing myself to travel to it to study the path of the earth as seen from the comet. Earth seems very close to Vega on April 9. Neat. I tried to use the Phenomena tab of AstroCalc to see at which exact moment the angular distance between earth and Vega is the smallest. Sadly, the calculation couldn't be done. At least no results showed up.

Is it impossible to use that tool when standing on another solar system body? If so, then it might be advisable to lock it when outside of earth.

**Comment by alex-w** [comment]
Just not optimat time step for asteroids and comets

**Comment by alex-w** [comment]
Please check version 0.20.2.18060
