### ISSUE TITLE
Telescope control,  start/connect at startup greyed out

### ISSUE THREAD

**Issue by wbrady11** [Stellarium/stellarium#1164]
Hello
I have updated Stellarium to the latest version after using StellariumScope for some time now, Telescope control in plug-ins is ticked to load at startup, my scope shows as disconnected which is an AZ EQ6-GT, settings tab shows it as controlled by ASCOM, the ASCOM settings/ ASCOM telescope chooser has the EQMOD HEQ5/6 enabled which is what has always been used, but for some reason in telescope properties under Coordinate system the start/connect at start up tab is greyed out, im assuming because of the this is the reason my scope does not connect at start up? as soon as i connect all is well but i have to go into plug-ins every time, press configure and manually connect at which point eqmod loads up and the small telescope retical appears and shows around Polaris which is where my scope is parked...is it because stellariumscope is still on my system and maybe causing conflict somewhere although its not opened? or am i missing something simple somewhere? thanks all in advance
Wayne<!--

**Comment by alex-w** [comment]
Are you read the change log for version 0.20.2?

**Comment by wbrady11** [comment]
Hello Alex, yes i have, if we are referring to the "dirty fix" (GH: #928) Fixed (a temporary fix) crash Stellarium when autoconnect is enabled for ASCOM device, but device is not attached [Telescope Control] (GH: #928) stellarium does not crash for me when autoconnect is enabled it just does not connect at all, is this the same problem thats doing this? also was the update in the beta version?
Thanks

**Comment by ManyExposures** [comment]
Hello Alex. I have the same greyed out issue on telescope control on version 20.2. 
The connect on start up check box is only available the first time I configure an ASCOM telescope. In my case EQMOD. The telescope chooser comes up and I pick it. And it connects all good. But when I close Stellarium and open it again, it does not connect automatically. I can connect it manualy though. And as wdrady11 says, Stellarium does not crash. It just does not connect automatically at all.

I posted in another thread saying that I had found EQMOD to be tbe problem. But I was wrong and it is not. I had forgottent that I reinstalled 20.1 which has worked all the time.

**Comment by wbrady11** [comment]
ManyExposures are you saying that auto connect works fine with version 20.1? if so i dont mind rolling back if it works ok
cheers

**Comment by ManyExposures** [comment]
> ManyExposures are you saying that auto connect works fine with version 20.1? if so i dont mind rolling back if it works ok
> cheers

Yes, it has always worked. Only the latest 20.2 has a problem with it. All my other astro apps connect to EQMOD on start up too. I went back to Stellarium 20.1 again an it works once again.

**Comment by wbrady11** [comment]
Cheers, i think i shall revert to 20.1 until the issue is resolved, i havnt even tried it out yet without StellariumScope as i came for 19.0 or something, thanks

**Comment by hefy-jefy** [comment]
I have a similar related problem.  Been using latest version for some time with an ASCOM telescope.  For some reason Stellarium no longer connects.  Telescopes dialog just says "connecting" but never does.  Other apps (PHD2) connect to the ASCOM scope with no problem.  I just went back to v20.1 but that has NOT fixed the problem.  Tried deleting all the .ini files and resetting defaults but I am stuck.  This has worked faultlessly for some months...

**Comment by hefy-jefy** [comment]
Just installed Cartes du Ciel and its working OK.

**Comment by RobertLVV** [comment]
I am having the very same issue using v20.2 under Windows 10 Pro 64bit with a Atlas EZ/EQ-G Pro mount.  Start/connect at start up tab is grayed out and auto connect to mount does not work. Reverted back to 20.1 which continues to work great.   I no longer have StellariumScope installed and do not wish to re-install it so the revert to 20.1.

**Comment by alex-w** [comment]
Please check 0.20.3RC2

**Comment by ManyExposures** [comment]
thank you for bringing it back. Where I can download it

Thank you

**Comment by alex-w** [comment]
https://github.com/Stellarium/stellarium-data/releases/tag/beta
