### ISSUE TITLE
keyboard shortcut to calculate ephemeris

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1165]
**Is your feature request related to a problem? Please describe.**
I am running a lot of ephemeris calculations, and am hampered by the UI that is mainly mouse driven, I lose a lot of time moving the mouse to the "Calculate ephemeris" button, On a laptop with a touchpad this is even more difficult

**Describe the solution you'd like**

e.g. Alt-C executes the button, Alt-S saves, Alt-L cleanup

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/3529789/87199890-bb1c5f00-c2fb-11ea-8c2b-9035b7aadb1b.png)

**Comment by alex-w** [comment]
Please check version 0.20.2.18060

**Comment by axd1967** [comment]
Not working...
Logfile says "ambiguous shortcut overload"
Then I find out: I previously assigned Alt+C to another action.
But in the dialog, that Alt-C should get a higher priority than a (custom) shortcut keyboard -> new issue.

Note also: it seems to be possible to type in the dropdown, which is highly unusual.
 
![image](https://user-images.githubusercontent.com/3529789/87245917-ddbc8e00-c449-11ea-939a-928370f22673.png)

**Comment by alex-w** [comment]
Please check version 0.20.2.18074

**Comment by axd1967** [comment]
I checked this in 0.20.3 but this is not exactly what I had in mind. 

rather, buttons in the dialog should be associated with local shortcuts (these are recognised by an underscore in the button text).
But there is a snag: as the button texts are translated, what should happen with the shortcuts? No idea. So the implementation is not so trivial.

Also. I don't know if it makes sense to define a global shortcut for e.g. "Calculate ephemeris" as these will not change (because the parameters are fixed in the Astrocalc GUI).

Also,  a bug has appeared now: after assigning a global shortcut and restarting , the app crashes when invoking the custom shortcut, which is probably related to the fact that the astrocalc parameters are not correctly reinitialised. I will create a new issue for this.

**Comment by axd1967** [comment]
if I'm  not mistaken, this was reverted due to issues with the implementation.
