### ISSUE TITLE
dialog shortcuts should receive higher prio than custom shortcuts

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1166]
### Expected Behaviour
Shortcuts defined in dialogs (e.g. Alt-C in #1165) should always override a custom keyboard shortcut (F7)

### Actual Behaviour
When attempting to run the calculation via keyboard (Alt-C), nothing happens. This is because a global shortcut is taking precedence and doing something else.

### Steps to reproduce

1. Assign Alt-C to some custom action (e.g. "Show crosshairs")
1. open ephemeris dialog
1. press Alt-C
Observe that the custom action is invoked instead.

### System
* Stellarium version: 0.20.2.18060 (master)

* Operating system: KUbuntu 18.4

* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/4908475/log.txt)

**Comment by alex-w** [comment]
Please check version 0.20.2.18074

**Comment by axd1967** [comment]
I have the impression that the test procedure no longer works: I cannot assign ALT+C?

possibly related to #1294

**Comment by axd1967** [comment]
A tip to remember: many (if not all?) dialogs capture the keyboard shortcuts, thus preventing general keys such as e.g. "a" for atmosphere to work, because a dialog has focus. Sometimes you want to interact with the dialog (eg time window) via mouse **scrollwheel**, and at the same time want to trigger other keyboard driven actions.

To achieve this, you have to remove the focus from all dialogs.

To do so, open and then close some other dialog such as the search dialog (F3) or bookmarks or whatever. This will take away the focus from dialogs that need to stay open (eg time dialog, landscape dialog, etc) and you will be able to combine **scrollwheel** mouse actions in a dialog with general keyboard actions.
