### ISSUE TITLE
Comet import fails on Ubuntu (Permission denied on tmp file)

### ISSUE THREAD

**Issue by zxa** [Stellarium/stellarium#1171]
### Expected Behaviour

Show available objects when using the mpc file import from a bookmarked source in the solar system editor.

### Actual Behaviour

If i try to import a mpc file from the bookmarks in the solar system editor, no object is found. Logfile writes a "Permission denied" error. Starting stellarium as root bypasses the issue.

### Steps to reproduce

Import mpc file from bookmarks in solar system editor on Ubuntu 20.04.

### System
* Stellarium version: 20.2 from ppa (also on 19.3 )
* Operating system: Ubuntu 20.04

### Logfile 

Unable to open for reading "/tmp/stellarium.ujIkqL"
File error: "Permission denied"
No objects found in the file downloaded from "http://astro.vanbuitenen.nl/cometelements?format=mpc&mag=obs"

**Comment by alex-w** [comment]
This is definitely not Stellarium problem. Please check permissions and ownership of /tmp directory on your Ubuntu.

**Comment by zxa** [comment]
It's world writeable, as /tmp should be. I have no problem to create, read and delete files as a user in /tmp.

**Comment by alex-w** [comment]
I've installed Ubuntu 20.04 into VirtualBox, installed Stellarium from our PPA and tried to add NEOWISE comet - all works as expected without any problem.

**Comment by gzotti** [comment]
On my Ubuntu 20.04, Stellarium 0.20.2, import works just fine.

**Comment by axd1967** [comment]
Here too, never had this problem.

@zxa , 
* how do you launch Stellarium? (https://askubuntu.com/questions/633857/why-i-cant-write-a-file-in-tmp-even-when-it-is-rootroot-and-has-t-flag)
* try to install a version from https://github.com/Stellarium/stellarium/releases instead of using a PPA?
