### ISSUE TITLE
différence de calcul entre versions

### ISSUE THREAD

**Issue by bourriquet34** [Stellarium/stellarium#1172]
Bonjour,

J'ai utilisé ce matin 18/07/2020 à 09:20 (Montpellier) avec 
- 0.20.2 (win64)
- version mobile Plus.

En orientant au Sud Ouest, je trouve mars entre 230° et 235°, mais j'observe des différences importantes dans les positions des lunes de mars. Phobos, se trouve en bas à droite sur la version win64, alors qu'elle est en haut à gauche sur la version mobile.

Les versions mobiles et web, quand à elles, affichent la même chose, (ce qui est rassurant si le calcul est réalisé par un web-service)

Je ne peux pas vous donner de piste précise quand à la nature de ce problème, les possibilités ne manquent pas (erreur d'algo, erreur calcul numérique dégradé, erreur dans la base d'information, erreur de lecture de la base d'information...)
![Stellaris-2020-07-15T0945](https://user-images.githubusercontent.com/25798850/87518020-01691980-c680-11ea-9c65-0dc7e0645d84.png)

**Comment by gzotti** [comment]
The programs use different algorithms. Comparison with observations could tell us who is correct.

**Comment by axd1967** [comment]
Similar to #230?
