### ISSUE TITLE
Stellarium for Win 10 

### ISSUE THREAD

**Issue by b007rankin** [Stellarium/stellarium#1173]
Stellarium doesn't seem to work with windows 10 pro ver 18363. The splash screen pops up but nothing happens after that.

**Comment by alex-w** [comment]
Please show log.txt from Stellarium

**Comment by b007rankin** [comment]
I looked for *.txt files in the stellarium install folder, but only found your changelog file. Since I can't actually get into stellarium, how would I generate a log.txt file.

**Comment by alex-w** [comment]
https://github.com/Stellarium/stellarium/wiki/FAQ

**Comment by barry-devlin** [comment]
I have the same problem.

Here is the log.txt - can't see much of interest ;-)

2020-07-17T15:20:42
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 15.9 (Visual Studio 2017)
Qt runtime version: 5.12.6
Qt compilation version: 5.12.6
Addressing mode: 64-bit
Total physical memory: 32607 MB
Available physical memory: 25022 MB
Physical memory in use: 23%
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
C:\Program Files\Stellarium\stellarium.exe 
 -----------------------------------------------------
[ This is Stellarium 0.20.2 - https://stellarium.org/ ]
[ Copyright (C) 2000-2020 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "C:\\Users\\barry\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\barry\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\barry\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)

**Comment by alex-w** [comment]
Please try run Stellarium in ANGLE mode.

**Comment by barry-devlin** [comment]
Oh thank you! That works :-) Why?

**Comment by alex-w** [comment]
I see in the log that OpenGL session was not started properly, so, we have 2 way to resolve problem: use Direct3D as renderer (ANGLE mode enable converter OpenGL calls into Direct3D calls) or install drivers for graphics card from manufacturer to use OpenGL features of graphics card.

**Comment by b007rankin** [comment]
how do i run it in the angle mode?

**Comment by gzotti** [comment]
Just as described in the User Guide, section 2.4.1.
