### ISSUE TITLE
The track drawn disappears after some time

### ISSUE THREAD

**Issue by psknick** [Stellarium/stellarium#1174]
Good day!

After finishing building a track, after about 3 minutes, the track disappears spontaneously.

[track.ogg.zip](https://github.com/Stellarium/stellarium/files/4943767/track.ogg.zip)

[log.txt](https://github.com/Stellarium/stellarium/files/4943769/log.txt)

**Comment by alex-w** [comment]
Could you disable showing a proper motion and check it again?

**Comment by psknick** [comment]
"disable showing a proper motion" - I didn't understand where to do this ...

**Comment by alex-w** [comment]
F2 -> "Information" tab -> Proper Motion

**Comment by gzotti** [comment]
This is probably linked to #1030. When time is reset to a date > 5 days from the current date, the trails are started over, deliberately, to avoid bad connection lines. However, something also sets date where I don't currently see it.

**Comment by psknick** [comment]
"F2 -> "Information" tab -> Proper Motion"

in this mode the same fault

[track1.ogg.zip](https://github.com/Stellarium/stellarium/files/4943850/track1.ogg.zip)

**Comment by gzotti** [comment]
Your first video shows nothing unusual. You ran the simulation forward, then backward. Trails vanish after some time. This is what we can observe.

**Comment by gzotti** [comment]
The second shows the same. Old trail vertices are chopped off. This is intended.

**Comment by psknick** [comment]
he disappearance of a track 3 minutes after building - it should not be so. In 3 minutes it is impossible to analyze the relative position of the planets, it is impossible to have time to measure the angular distances between the stops of the planets and the location, for example, of the moon. In version 0.19.3, there was no disappearance of the track - it remained visible until I closed the program. Thank!

**Comment by psknick** [comment]
I use the program for historical research, in particular when researching Ancient Egypt and Ancient Rome. As it turned out, the ancient Egyptians in their zodiacs left a story about the movement of the planets. In the Egyptian zodiacs there is information about the motion of the planets, about the loops of the planets, about the rising and setting of the planets, etc. Stallarium allows you to simulate the movement of planets. Building tracks of planetary movements helps a lot to understand how everything was in the past. Thank!

**Comment by gzotti** [comment]
If you stop motion, the track should not vanish.

**Comment by psknick** [comment]
"If you stop motion, the track should not vanish."

This does not work. I attached the file "track1.ogg.zip", see above. The attached video shows that the track disappears, even if "stop motion".

**Comment by gzotti** [comment]
"Stop motion" would mean "stop so that time does not change, not even in real-time rate".

**Comment by psknick** [comment]
""Stop motion" would mean "stop so that time does not change, not even in real-time rate"."

This does not work. See the attached video.

[track2.ogg.zip](https://github.com/Stellarium/stellarium/files/4944689/track2.ogg.zip)

**Comment by gzotti** [comment]
I see. This is still the way the original developer has chosen. Not related to #1030.

**Comment by alex-w** [comment]
Please check version 0.20.2.18093

**Comment by psknick** [comment]
Good day!

Checked in different modes (on / off "Stop motion") and time (on / off "real time"). The track does not disappear. Many thanks to you and your colleagues!
