### ISSUE TITLE
Ability to show several objects' ephemerides simultaneously

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1177]
I wish for a way to show several (2-5 or something) ephemerides at the same time. Currently, we are locked to either 1, or the 5 planets visible to the naked eye. It would sometimes be helpful, such as in 2014 when Vesta and Ceres were close to each other during an extented period of time, to show more than one ephemeris. The trails feature could be used, but the ephemeris tool is superior.

So that in the list where an object is chosen, an additional list could be shown, where the user could pick "object 2". If no other object is needed, a checkbox could be clicked to ignore the second object (or the inverse; the user must click the checkbox to enable list for object 2). Also, customizable colors for the markers and lines could be added so the two or more objects easily could be separated.

**Comment by gzotti** [comment]
Do you need the data lists for several objects concurrently, or would keeping the marked line plot in the sky be enough, with some "Keep last N tracks"?

**Comment by Atque** [comment]
@gzotti No I'm thinking a separate drop-down list where the user can select the other objects. Not sure how many objects should be allowed to select, though. 2 would be nice and pretty useful, but some users might need 3 or more objects.

I'm thinking ephemeris list of two objects where both bodies' ephemerides follow a mutual date interval. Just like the naked eye planet list but with 2 (or more) user defined objects.

**Comment by gzotti** [comment]
And with #1176 you will then select steps in Object1's properties? (synodic years etc?). 
If more than 1 object, I opt for allowing at least 3. Triple conjunctions are rare but beautiful to follow.  But I would be happy to just "keep last N ephemeris plots", without data lists, if that shows to be much simpler to do (Just detach curve points and store in a list). Maybe allow different colors for different objects' ephemeris plots? Then it's possible to build up an annual plot for all planets plus 5 minor planets or so.

**Comment by Atque** [comment]
#1176 is unrelated to this. That is a separate request, which I could have filed under this, but I preferred to keep them separated.

I would prefer to have a list of positions as well. The feature I'm asking for is exactly the same as "naked eye planets", but where the user can define which bodies to include (2, 3, 4 or 5, or what number you dev's think is sufficient).

**Comment by alex-w** [comment]
I can add support 1, 2 or 5 celestial bodies for ephemeris due obvious useful reasons. But (!) I really propose use the scripting engine to demo an "ephemeris lines" on the sky for 3 and more celestial bodies.

**Comment by alex-w** [comment]
Please check version 0.20.2.18093
