### ISSUE TITLE
cannot create 300x binocular

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1178]
In Oculars, create an Eyepiece with 300x magnification.
Bug: Limit seems to be 99x

Reason: I want to try FOV of a Yasterx 10-300x40mm

![image](https://user-images.githubusercontent.com/3529789/88372641-9d88d400-cd96-11ea-8f36-c9479fa10fd4.png)

**Comment by gzotti** [comment]
300x magnification for 40mm diameter? Are you sure?

**Comment by alex-w** [comment]
Yeah... https://yasterx.com/products/super-telephoto

**Comment by gzotti** [comment]
Interersting product information. Does it include a flight to the Moon? Or how do you observe lunar longitude 135 with it? Too bad Tsiolkowski is in shadow...

**Comment by gzotti** [comment]
Just to note a few: 
* https://www.astronomics.com/info-library/how-to-pick-an-eyepiece/highest-useful-magnification/
* https://skyandtelescope.org/astronomy-equipment/choosing-your-telescopes-magnification/

Conventional wisdom would stop magnification around 60 for this device. What is the image quality at 300x?

**Comment by axd1967** [comment]
Those are right observations. However, I think we should not focus on such details. If someone wants to enter crazy magnification factors, let it be.
It is possible that Stellarium breaks down on such magnification levels (bugs, imprecision, etc), yet this is not a reason to limit to 100. why not limit to 200 then? who decided that 100x was the maximum allowable value? smells like a completely arbtrary value.
Secondly, nobody knows how technology will evolve. There is no hard physical law (well, we all suspect that a million time magnification is not realistic, and wave physics do also intervene) that prevents such (relatively moderate) magnifications.

Fact is that computer driven telescopes with no direct optical path but embedded optronics will become more common.

**Comment by gzotti** [comment]
Max=99 is based on it being 2-ciphered, and giving a wide range beyond what has been available based on 20th century optical engineering expertise and user practice. I am not aware of useful binoculars with magnifications beyond maybe 60 or so (which required image stabilisation or a giant tripod!). Or a Myauchi 2x 100mm superbino which comes with 33x/40x or yes - indeed, 150x.  I don't know whatever nanotech they claim to apply in manufacturing, but 300 magnification at 40mm aperture yields 0.13mm exit pupil. Conventional wisdom recommends to stay above 0.5mm (here: 80x), better above 1mm (40x). Sounds like the classical Shopping Mall telescope with 10.000x magnification in a box covered in Hubble images.   

The solution is just a tiny fix in the UI file. (Thanks, @alex-w ) And this is good as it covers the Myauchi diameter range and more... :-)

**Comment by alex-w** [comment]
This device proposed for use with cellphone cameras, not for eyes

**Comment by axd1967** [comment]
agree, it is all very smelly.

**Comment by alex-w** [comment]
Please check version 0.20.2.18093

**Comment by axd1967** [comment]
ok!
