### ISSUE TITLE
remember customized object informations settings

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1184]
**Is your feature request related to a problem? Please describe.**
When I toggle between the different object information modes, whenever I select "Customized", I have to re-select the custom settings.

e.g when I select "None" and then go to "Customized", I discover that all settings have been cleared

**Describe the solution you'd like**
The custom settings should be remembered for - at least - the current session, and ideally stored as a persistent user setting.

**Additional context**
![image](https://user-images.githubusercontent.com/3529789/88905107-38c9ef80-d256-11ea-9fc2-62d2a911eaf4.png)

**Comment by alex-w** [comment]
The feature of remembering is implemented few years ago - just use "Save settings" button for it.

**Comment by axd1967** [comment]
Sorry, but if I do this:

1. define a custom set
1. save settings (F2>Main)
1. click "None"
1. click "Customised"

I don't find back the settings I had defined in step 1; instead, see "Customised" but nothing is selected (as defined in step 1).

Tested on 0.20.2.18060 [master]

**Comment by alex-w** [comment]
Please check version 0.20.2.18113

**Comment by axd1967** [comment]
works, thanks!
