### ISSUE TITLE
Star catalog failure?

### ISSUE THREAD

**Issue by ghost** [Stellarium/stellarium#1189]
Line arranged stars are shown next to Antares. They are about 12-15 magnitude. I cannot see them in a photographic star atlas.

![image](https://user-images.githubusercontent.com/69102370/89117430-0c081900-d49e-11ea-8f56-8d12748b23c4.png)

**Comment by gzotti** [comment]
This is an obvious catalog artifact which occurs near the brightest stars. Look how it points to Antares, and look how the area around Antares appears void.
