### ISSUE TITLE
Stellarium version 0.17.0 crashes while working with it

### ISSUE THREAD

**Issue by Elbi-Z** [Stellarium/stellarium#119]
Reporting a crash: 
•	Platform and operating system: Dell Inspiron 7720   OS: Windows 7   64bit    16 GB RAM   Seagate 1 TB HD
•	What kind of graphics card do you have? Driver version?   There are two video cards listed:
o	Intel® HD Graphics 4000  PCI   2.06 GB  Driver Version: 9.17.10.2867, 9-26-2012
o	NVIDIA  GeForce GT 650M  PCI Express x16  2GB  Driver Version: 9.18.13.3788, 5-19-2014
Running dxdiag: 
Device
Name: Intel® HD Graphics 4000
Manufacturer: Inntel Corporation
Chip Type: Intel® HD Graphics Family
DAC Type: Internal
Approx. Total Memory:  1696 MB
Current Display Mode:  1920 x 1080 (32-bit) (60Hz)
Monitor: Generic PnP Monitor
DirectX Features:
DirectDraw Acceleration:  Enabled
Direct3D Acceleration: Enabled
AGP Texture Acceleration: Enabled 

Drivers:
Main driver:   igdumd64.dll, igd10umd64.dll, igd10u
Version:  9.17.10.2867
Date:  10/26/2012  112:09:06 AM
WHQL Logo’d: Yes
DDI Version:  11
Driver Model: WDDM 1.1

No problems found.
•	Which version of Stellarium causes problems: 
NAME OF THE DOWNLOADED FILE:  stellarium-0.17.0-win64.exe
•	The LOGFILE. From your program menu, there should be a link to "Last Run Log". Copy&Paste its contents. If logfile is empty (i.e., crash is really immediately, very early at start), please say so.
2018-03-17T09:35:13
Operating System: Windows 7
Product Name: Windows 7 SP 1 (6.1)
Compiled using MSVC++ 14.0 (Visual Studio 2015)
Qt runtime version: 5.9.3
Qt compilation version: 5.9.3
Addressing mode: 64-bit
Total physical memory: 16244 MB
Available physical memory: 12184 MB
Physical memory in use: 24%
Processor speed: 2394 MHz
Processor name: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Processor speed: 2394 MHz
Processor name: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Processor speed: 2394 MHz
Processor name: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Processor speed: 2394 MHz
Processor name: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Processor speed: 2394 MHz
Processor name: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Processor speed: 2394 MHz
Processor name: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Processor speed: 2394 MHz
Processor name: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Processor speed: 2394 MHz
Processor name: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
C:\Program Files\Stellarium\stellarium.exe 
 -------------------------------------------------------
[ This is Stellarium 0.17.0 - http://www.stellarium.org ]
[ Copyright (C) 2000-2017 Fabien Chereau et al.         ]
 -------------------------------------------------------
Writing log file to: "C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
qt.qpa.gl: Unable to disable rotation.
initializeGL
OpenGL supported version:  "4.0.0 - Build 9.17.10.2867"
Current Format:  QSurfaceFormat(version 4.0, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
StelMainView::init
Detected: OpenGL "4.0"
Driver version string: "4.0.0 - Build 9.17.10.2867"
GL vendor is "Intel"
GL renderer is "Intel(R) HD Graphics 4000"
GL Shading Language version is "4.00 - Build 9.17.10.2867"
GLSL Version Number detected:  4
GLSL version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\Elbi\\AppData\\Local\\stellarium\\stellarium\\cache"
StelLocation::createFromLine(): TimeZone name for  "Marietta-home"  not found. Translating ""  to  "UTC"
StelLocation::createFromLine(): TimeZone name for  "North Pole"  not found. Translating ""  to  "UTC"
Sky language is  "en_US"
Couldn't load translations for language  "en_US" in section "stellarium-planetary-features"
Empty translation file for language  "en_US" in section "stellarium-planetary-features"
Planetary features language is  "en_US"
Application language is  "en_US"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
Loaded 77 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
Loaded 101 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15449 / 15454 items of planetary surface nomenclature
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_7.cat: 0_0v0_7; 4979"
"Loading .\\stars\\default\\stars_1_0v0_7.cat: 1_0v0_7; 21806"
"Loading .\\stars\\default\\stars_2_0v0_7.cat: 2_0v0_7; 150850"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
"Loading C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_4_1v0_2.cat: 4_1v0_4; 1692779"
"Loading C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_5_2v0_1.cat: 5_2v0_1; 7083058"
"Loading C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_6_2v0_1.cat: 6_2v0_1; 24670782"
"Loading C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_7_2v0_1.cat: 7_2v0_1; 50733321"
"Loading C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_8_2v0_1.cat: 8_2v0_1; 92304337"
Finished loading star catalogue data, max_geodesic_level:  8
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4506 / 4506 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6916 / 6916 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
"StelPainter: Warnings while linking starShader shader program:\nNo errors.\n"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.3 (standard edition)"
Loaded 90416 DSO records
Loading DSO outline data ...
Loaded 63 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
"StelPainter: Warnings while linking atmosphere shader program:\nNo errors.\n"
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 847 / 847 common star names
Loading DSO name data ...
Loaded 1004 / 1021 DSO name records successfully
WARNING - No position data for 17 objects: "PGC 621, PGC 2345, PGC 2906, PGC 2907, PGC 14098, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Loaded 54 / 54 asterism records successfully for culture "western"
Loaded 44 / 44 asterism names
stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
"StelPainter: Warnings while linking basicShaderProgram shader program:\nNo errors.\n"
"StelPainter: Warnings while linking colorShaderProgram shader program:\nNo errors.\n"
"StelPainter: Warnings while linking texturesShaderProgram shader program:\nNo errors.\n"
"StelPainter: Warnings while linking texturesColorShaderProgram shader program:\nNo errors.\n"
Creating GUI ...
Loaded plugin "CompassMarks"
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "FOV"
Loaded plugin "MeteorShowers"
MeteorShowersMgr: Loading catalog file: "C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "NavStars"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
Oculars::validateIniFile ocular.ini exists at:  "C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateIniFile found existing ini file version  3.1
Loaded plugin "Pulsars"
[Pulsars] Version of the format of the catalog: 2
[Pulsars] Loading catalog file: "C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\modules\\Pulsars\\pulsars.json"
Loaded plugin "Quasars"
[Quasars] Version of the format of the catalog: 1
[Quasars] Loading catalog file: "C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\modules\\Quasars\\quasars.json"
Loaded plugin "Satellites"
[Satellites] loading catalog file: "C:\\Users\\Elbi\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "GRACE-1" "27391"
Satellite has invalid orbit: "FLOCK 2E-10" "41572"
Satellite has invalid orbit: "FLOCK 2E-12" "41573"
Satellite has invalid orbit: "FLOCK 2E-11" "41574"
Satellite has invalid orbit: "FLOCK 2E'-10" "41576"
Satellite has invalid orbit: "FLOCK 2E'-11" "41577"
Satellite has invalid orbit: "FLOCK 2E'-12" "41578"
Satellite has invalid orbit: "STARS-C" "41895"
Satellite has invalid orbit: "COLUMBIA" "42702"
Loaded plugin "Scenery3d"
Loaded 1 extensions for "Scenery3d"
stel.plugin.scenery3d: Scenery3d plugin - press KGA button to toggle 3D scenery, KGA tool button for settings
stel.plugin.scenery3d: Initializing Scenery3d renderer...
stel.plugin.scenery3d.renderer: Maximum texture size: 8192
stel.plugin.scenery3d.renderer: Maximum viewport dims: 8192 8192
stel.plugin.scenery3d.renderer: Maximum renderbuffer size: 4096
stel.plugin.scenery3d.renderer: Maximum framebuffer size: 4096
stel.plugin.scenery3d.renderer: Geometry shader supported
stel.plugin.scenery3d.renderer: GL_MAX_TEXTURE_IMAGE_UNITS: 16
stel.plugin.scenery3d.renderer: GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: 80
stel.plugin.scenery3d.renderer: Seamless cubemap filtering enabled
stel.plugin.scenery3d: Initializing Scenery3d renderer...done
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Initializing planets GL shaders... 
"StelPainter: Warnings while linking planetShaderProgram shader program:\nNo errors.\n"
"StelPainter: Warnings while linking ringPlanetShaderProgram shader program:\nNo errors.\n"
"StelPainter: Warnings while linking moonShaderProgram shader program:\nNo errors.\n"
"StelPainter: Warnings while linking objShaderProgram shader program:\nNo errors.\n"
"StelPainter: Warnings while linking objShadowShaderProgram shader program:\nNo errors.\n"
"StelPainter: Warnings while linking transformShaderProgam shader program:\nNo errors.\n"
Satellite has invalid orbit: "EAGLE 2" "39436"
Satellite has invalid orbit: "FLOCK 2E'-1" "41479"
Satellite has invalid orbit: "FLOCK 2E'-19" "41777"
Satellite has invalid orbit: "FLOCK 2E'-3" "41480"
Satellite has invalid orbit: "FLOCK 2E'-8" "41569"
Satellite has invalid orbit: "FLOCK 2E-3" "41486"
Satellite has invalid orbit: "FLOCK 2E-7" "41565"
Satellite has invalid orbit: "LEMUR-2-TRUTNA" "42067"
Satellite has invalid orbit: "ORS 1" "37728"
Satellite has invalid orbit: "SGSAT" "42703"
Satellite has invalid orbit: "TECHEDSAT 6" "43026"
Satellite has invalid orbit: "FLOCK 2E'-13" "41761"
Satellite has invalid orbit: "FLOCK 2E'-16" "41763"
Satellite has invalid orbit: "FLOCK 2E'-17" "41776"
Satellite has invalid orbit: "FLOCK 2E-1" "41483"
Satellite has invalid orbit: "IRIDIUM 40" "25041"
Satellite has invalid orbit: "AOBA-VELOX 3" "41935"
Satellite has invalid orbit: "CHALLENGER" "42721"
Satellite has invalid orbit: "DUTHSAT" "42724"
Satellite has invalid orbit: "FLOCK 2E-5" "41564"
Satellite has invalid orbit: "I-INSPIRE II" "42731"
Satellite has invalid orbit: "ICECUBE" "42705"
Satellite has invalid orbit: "KANOPUS-V 1" "38707"
Satellite has invalid orbit: "LEMUR-2-AUSTINTACIOUS" "42068"
Satellite has invalid orbit: "LEMUR-2-TRUTNAHD" "42069"
Satellite has invalid orbit: "LINK" "42714"
Satellite has invalid orbit: "OBJECT NC" "42913"
Satellite has invalid orbit: "SBIRS GEO 3 r" "41938"
Satellite has invalid orbit: "WASEDA-SAT3" "41933"
Satellite has invalid orbit: "EXALTA-1" "42734"
Satellite has invalid orbit: "FLOCK 2E'-20" "41782"
Satellite has invalid orbit: "FLOCK 2E'-5" "41567"
Satellite has invalid orbit: "HOOPOE" "42718"
Satellite has invalid orbit: "IRIDIUM 46" "24905"
Satellite has invalid orbit: "IRIDIUM 96" "27376"
Satellite has invalid orbit: "ITF-2" "41932"
Satellite has invalid orbit: "LEMUR-2-REDFERN-GOES" "42059"
Satellite has invalid orbit: "POLYITAN-2-SAU" "42732"
Satellite has invalid orbit: "QBITO" "42728"
Satellite has invalid orbit: "SILU-1 (SILKROAD 1)" "42903"
Satellite has invalid orbit: "STSAT-2C" "39068"
Satellite has invalid orbit: "UNSW-ECO" "42723"
Satellite has invalid orbit: "UPSAT" "42716"
Satellite has invalid orbit: "X-CUBESAT" "42707"
Satellite has invalid orbit: "AALTO-2" "42729"
Satellite has invalid orbit: "ALMASAT-1" "38078"
Satellite has invalid orbit: "BANXING-2" "41834"
Satellite has invalid orbit: "BIRD-G" "42821"
Satellite has invalid orbit: "BRAC ONNESHA" "42823"
Satellite has invalid orbit: "CXBN-2" "42704"
Satellite has invalid orbit: "HAVELSAT" "42700"
Satellite has invalid orbit: "LILACSAT-1" "42725"
Satellite has invalid orbit: "MAZAALAI (NUMSAT-1)" "42822"
Satellite has invalid orbit: "NO-83" "40655"
Satellite has invalid orbit: "OSIRIS-3U" "43027"
Satellite has invalid orbit: "QBEE50-LTU-OC" "42708"
Satellite has invalid orbit: "SNUSAT-1" "42727"
Satellite has invalid orbit: "SNUSAT-1B" "42733"
Satellite has invalid orbit: "SOMP 2" "42701"
Satellite has invalid orbit: "SPACECUBE" "42717"
Satellite has invalid orbit: "SUSAT" "42730"
Satellite has invalid orbit: "TOKI" "42820"
Satellite has invalid orbit: "AOXIANG-1" "42735"
Satellite has invalid orbit: "BEEAGLESAT" "42736"
Satellite has invalid orbit: "CSUNSAT 1" "42715"
Satellite has invalid orbit: "FLOCK 2E'-14" "41762"
Satellite has invalid orbit: "FLOCK 2E'-15" "41764"
Satellite has invalid orbit: "NIGERIAEDUSAT-1" "42824"
Satellite has invalid orbit: "OBJECT MZ" "42910"
Satellite has invalid orbit: "OBJECT NA" "42911"
Satellite has invalid orbit: "OBJECT NB" "42912"
Satellite has invalid orbit: "OBJECT ND" "42914"
Satellite has invalid orbit: "PHOENIX" "42706"
Satellite has invalid orbit: "USA 186" "28888"
Satellite has invalid orbit: "ZA-AEROSAT" "42713"
Satellite has invalid orbit: "IRIDIUM 23" "24906"
Satellite has invalid orbit: "NJUST-1" "42722"
Satellite has invalid orbit: "ALTAIR PATHFINDER" "42711"
Satellite has invalid orbit: "ASTERIA" "43020"
Satellite has invalid orbit: "FLOCK 2E'-18" "41769"
Satellite has invalid orbit: "ISON 70200" "90096"
Satellite has invalid orbit: "MOLNIYA 3-47" "23642"
Satellite has invalid orbit: "NO-84" "40654"
Satellite has invalid orbit: "SPEKTR-R" "37755"
Satellite has invalid orbit: "XMM-NEWTON" "25989"
Satellite has invalid orbit: "DIWATA-1" "41463"
Satellite has invalid orbit: "MOLNIYA 1-88" "23420"
Satellite has invalid orbit: "MOLNIYA 1-90" "24960"
Satellite has invalid orbit: "MOLNIYA 3-31" "17328"
Satellite has invalid orbit: "Ofeq 11" "41759"
Satellite has invalid orbit: "POLAR" "23802"
Satellite has invalid orbit: "SHARC" "42712"
Satellite has invalid orbit: "SHENZHOU-11 MODULE" "41868"
Satellite has invalid orbit: "IRIDIUM 19" "24965"
Satellite has invalid orbit: "ISON 47601" "90108"
Satellite has invalid orbit: "Unknown 060625" "90057"
Satellite has invalid orbit: "Unknown 060616" "90061"
Satellite has invalid orbit: "IRIDIUM 37" "24968"
Satellite has invalid orbit: "Unknown 120723" "90089"
Satellite has invalid orbit: "AKEBONO (EXOS-D)" "19822"
Satellite has invalid orbit: "NOSS 2 (A)" "10502"
Satellite has invalid orbit: "THEMIS A" "30580"
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.
Satellite has invalid orbit: "MOLNIYA 1-63" "15429"
Satellite has invalid orbit: "USA 224" "37348"
Satellite has invalid orbit: "MOLNIYA 1-71" "18946"
Satellite has invalid orbit: "MOLNIYA 1-80" "21118"
Satellite has invalid orbit: "Unknown 060624" "90059"
Satellite has invalid orbit: "ISON 49200" "90114"
Satellite has invalid orbit: "ISON 59700" "90106"
•	If crash was not immediately at startup, actions that lead to it. (Keypress sequence, some scenario to reliably recreate the crash.)
Crash was no immediate at startup.  I was working through a Stellarium worksheet for an Astronomy class.  I included the worksheet – 0-Stellarium10 00 UsingStellarium.pdf (160 KB).  I was just working on Part C when it crashed.  
PART C
One of Stellarium's most important features is its ability to change, slow down, speed up or reverse time and
watch how things move in the sky. Stellarium shows you the way the sky looks at any time, and it changes as the
real sky changes!

To see this, center the Eastern horizon on the screen (by dragging the sky until the “E” is in the center of the
screen), zoom in until the Field of View is about 10° (you may have to drag and recenter the “E” as you zoom to
keep it from drifting off screen), and set the Date and Time to March 21, 2008, at 6:50 AM. Make sure the
Atmosphere and Fog are turned off by using the “A” and “F” keys (or by using the toolbar at the bottom of the
screen). Open the View window and make sure there are checks in the boxes next to Stars and Planets in the
5

Labels and Markers section of the Sky sub-menu. Close the window and simply watch the sky. Keep watching
for 10 minutes.

•	What happens? _________________________________________________________________________
•	What time does it happen? ________________________________________________________________
Selected a star at random – and that’s when it crashed.  But, keep in mind I had already completed sections A and B prior to beginning C.

Here is a screen print of the crash from the event viewer 
– seems the culprit is Faulty module name:  ig7icd64.dll, version 9.17.10.2867, time stamp: 0x506351d0

 

[Last log run.txt](https://github.com/Stellarium/stellarium/files/1821983/Last.log.run.txt)
![stellarium error 1](https://user-images.githubusercontent.com/37477875/37559077-6069ee4e-2a17-11e8-9724-be38ebee8152.jpg)
[0-Stellarium10_00UsingStellarium.pdf](https://github.com/Stellarium/stellarium/files/1821986/0-Stellarium10_00UsingStellarium.pdf)

**Comment by gzotti** [comment]
While I cannot reproduce this issue, you could try to run Stellarium on your GeForce card. There must be a reason you paid for it. Configure this in the NVidia driver settings panel. If you have not done so, also consider updating graphics drivers every 6 months or so.

**Comment by gerardo1sanchez** [comment]
I Have a similar error using stellarium 0.16.1 on windows 8, seems to be some thing about an exception in Qt5 or code around it, i catch this error in VS 2012 and i attached some files describing error:
![stack trace error stellarium 0 16 1](https://user-images.githubusercontent.com/18900215/37569245-3f7fc418-2abe-11e8-995f-aa28e7a4ba33.png)
[log.txt](https://github.com/Stellarium/stellarium/files/1822991/log.txt)
[Output-Debug.txt](https://github.com/Stellarium/stellarium/files/1822992/Output-Debug.txt)

Note: Output-Debug.txt is output copied from visual studio's output window

I have a windows 8, core i5
NOTE 1: i recently reinstaled window 8, previuosly i had windows 8.1, same machine, and some previous stellarium version and stellariums ran prefectly.

NOTE 2: if you send me some .pdb files maybe i can take more detailed error's stack trace 

Thanks in advance

**Comment by gzotti** [comment]
@Elbi-Z , does updating the graphics drivers or/and running on the other GPU help? Your Intel driver is more than 5 years old! Geforce driver also almost 4 years!

**Comment by Elbi-Z** [comment]
I checked with Windows Driver Manager - I checked for Updates for both the NVIDIA GeForce GT 650M and the entry for Intel(R) HD Graphics-4000 driver,  The message returned: Windows has determined teh driver software for both of these devices is up-to-date.  under NVIDIA Control Panel - Managing 3D Setting - the manage updates settings is automatically check once a day.  If it does need to be updates, I certainly let it be done without hesitation.  The last installation date under NVIDIA Updates: 3/21/2018.  I ran the update check again - no new updates are available.  Under the tab (in Manage 3D Settings) Program settings, 1. Select a program to customize:  I looked at the different items under the drop-down box.  Stellarium was not one of those items.  I tried to add it, but It didn't take.  Maybe I am doing something wrong.  Is there anything you can suggest at this point?  I would really like to get Stellarium to work.  Any help would be appreciate.

**Comment by gzotti** [comment]
The NVidia Control Panel should allow you to add Stellarium to the 3D applications. If this does not work, ask NVidia to make it work. 
Make sure you have a driver version from at least 2017. Don't just check via Windows Update, go to nvidia.com and download a current driver package.  The same goes for Intel. Also, at least on Win10, there is a right-mouse-click option -- only for icons on the desktop -- to "run with ... Graphics Processor".

**Comment by gzotti** [comment]
@Elbi-Z , did that help?

**Comment by gzotti** [comment]
Timeout.
