### ISSUE TITLE
Mystery star near M51

### ISSUE THREAD

**Issue by LouisStrous** [Stellarium/stellarium#1192]
### Expected Behaviour
Don't show a magnitude-6 star near M51 where none exists in a picture I took recently.

### Actual Behaviour
Stellarium shows an unnamed magnitude-6 star near M51 where none exists in a picture of the sky I took recently in an attempt to record M51, and where the Hipparcos catalog (via [VizieR](https://vizier.u-strasbg.fr/viz-bin/VizieR-4)) doesn't list any stars within 15 arcmin.  The unnamed star shows up already with only the default star catalogs installed (i.e., Configuration / Extras says "Get catalog 5 of 9").

My picture: ![mystery-star-picture](https://user-images.githubusercontent.com/5446337/89123696-97e76880-d4d1-11ea-9aa8-9cd13a233c8f.jpg)

My picture shows stars down to about magnitude 10, so a magnitude-6 star should be very obvious.  The three stars HIP 66116 - HIP 65768 - HIP 66004 near the location of the mystery star have magnitudes near 7 and are clearly visible, yet the mystery star is not to be seen.

Screenshot of Stellarium showing roughly the same FOV and showing the star's properties: ![mystery-star-stellarium](https://user-images.githubusercontent.com/5446337/89123701-a170d080-d4d1-11ea-80eb-23d5bf0ff09e.jpg)

Note in particular that the star is listed by Stellarium to have a noticeable proper motion.  If the star was really some part of M51 mislabeled as a star then you'd expect it to have no proper motion, M51 being way too far away to show a noticeable proper motion.

### Steps to reproduce
In Stellarium, go to coordinates indicated in screenshot.  Observe star.

### System
* Stellarium version: 0.20.2
* Operating system: Windows 10 with the latest updates installed.
* Graphics Card: NVidia Geforce 940MX
* Laptop screen.

**Comment by ultrapre** [comment]
@alex-w 
I decoded the stars/default/*.cat, found a fake star (fake hip id = 1316384 ) that extactly matches the one. The guide book notes that stars_1 and stars_2 give hipparcos catalogue, however some data of them has nonexistent hip num. 

The same problem also exists in higher star data, the most serious is the actually nonexistent stars at the same position of bright Galactic Nuclei or globular cluster. For example, give a ramdom galaxy like NGC569, you can see a 13mag star in the center.

I advise to compile a new data from more accurate database like DR2.

refer:
https://wakata.nascom.nasa.gov//dist/generalProducts/attitude/ATT_SKYMAP.html
http://www.rssd.esa.int/index.php?project=HIPPARCOS
http://cdsarc.u-strasbg.fr/viz-bin/Cat?I/239
http://www.astro.ku.dk/~erik/Tycho-2/
http://www-gsss.stsci.edu/Catalogs/Catalogs.htm
http://www-gsss.stsci.edu/Catalogs/GSC/GSC1/GSC1.htm
http://www-gsss.stsci.edu/Catalogs/GSC/GSC2/GSC2.htm
http://www.sai.msu.su/groups/cluster/gcvs/gcvs/
http://ad.usno.navy.mil/wds/
http://ad.usno.navy.mil/wds/orb6.html
http://nstars.nau.edu/nau_nstars/
http://www.recons.org/
……

**Comment by gzotti** [comment]
You advise "just" using DR2. Great. How do we deal with the few hundred missing stars from DR2? I mean those on the bright end... And no, the format should change and take 3D motion into account. Just that "someone" has to find enough time do it.

**Comment by LouisStrous** [comment]
The problem that I found is resolved in stellarium-24.4-24215f9-qt6-win64.exe (weekly snapshot).

I downloaded that version and compared its results around M51 (field of view 9.59 degrees) with that of stellarium 24.4 (most recent official release) and stellarium 0.20.2 (the release in which I first noticed the problem).  The stars shown by 24.4 official and 0.20.2 look identical.  The main difference that 24.4-24215f9 brings is that the spurious magnitude-6 star on top of M51 has disappeared, as desired.

I noted a difference in the brightness of a very small number of stars in the field of view, such as V CVn, of which the magnitude changed from 7.35 to 6.74, but such differences are to be expected when a different data source is used.

**Comment by LouisStrous** [comment]
The issue is solved.  Thank you very much.

Regards,
Louis Strous

github-actions[bot] schreef op 2025-03-23 19:09:

> Hello @LouisStrous [1]!
> 
> Please check the latest stable version of Stellarium:
> https://github.com/Stellarium/stellarium/releases/latest
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
> 
> github-actions[bot] left a comment (Stellarium/stellarium#1192) [2]
> 
> Hello @LouisStrous [1]!
> 
> Please check the latest stable version of Stellarium:
> https://github.com/Stellarium/stellarium/releases/latest
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/LouisStrous
[2] 
https://github.com/Stellarium/stellarium/issues/1192#issuecomment-2746347042
[3]
