### ISSUE TITLE
Oculars: double-click to select item

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1193]
**Is your feature request related to a problem? Please describe.**
I often want to switcfh between various ocular elements, and the only way to do so is to step through the items (eyepieces/lenses/telescopes/sensors).

**Describe the solution you'd like**
From an open Oculars dialog, when I double-click an item, that item is selected

**Describe alternatives you've considered**

**Additional context**

**Comment by alex-w** [comment]
Alt+O?

**Comment by axd1967** [comment]
no, that is not speeding up things - that only opens the dialog in which the double-click should be implemented.

**Comment by axd1967** [comment]
in fact, it's the same double-clicking mechanism as in bookmarks or astrocalc.

**Comment by alex-w** [comment]
You may propose patch with correct processing of all 5 modes of Oculars plugin and updating all parts of GUI.

**Comment by axd1967** [comment]
thank you!
