### ISSUE TITLE
landscape reload does not work

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1195]
I'm working on a landscape (spherical model).
In older versions of Stellarium, it was enough to reselect (_edit added: select another, then select back_) a landscape to reload it. Now (0.20.2) this is no longer possible.

Even when I set this:

![image](https://user-images.githubusercontent.com/3529789/89403762-1f72e880-d719-11ea-98c8-4f2aac7562d3.png)

The landscape won't change without restarting Stellarium.

_Edit added: Ubuntu 20_

**Comment by gzotti** [comment]
Must have been very old versions. (0.15?) Does it not help to load another landscape in-between? Clicking on the active landscape will not trigger a reload.

**Comment by axd1967** [comment]
With "reload" I indeed mean switching between two landscapes.
If I'm not mistaken, in 0.19 this was possible.

**Comment by axd1967** [comment]
But what is the intention of the `cache_size_mb` flag then?

**Comment by gzotti** [comment]
I set:

> landscapeCache.setMaxCost(conf->value("landscape/cache_size_mb", 100).toInt());

From Qt Help:

> void QCache::setMaxCost(int cost)
> Sets the maximum allowed total cost of the cache to cost. If the current total cost is greater than cost, some objects are deleted immediately.

So, setting this to 0 expresses an intent to reduce cache size, however, I don't know the implementation internals and cannot guarantee cache is not used at all. 

I frequently create and edit landscapes. The loading of another landscape in-between always worked for me to force a refresh of the texture, at least on Windows.

**Comment by axd1967** [comment]
I now tried this: install 0.19.3  from Snap (gah) 
![image](https://user-images.githubusercontent.com/3529789/89439569-adb39280-d74a-11ea-9796-30b5abc878f3.png)

there also, when I install a landscape via .zip and then start fiddling in the landscape files, changes are not picked up.

**Comment by gzotti** [comment]
Of course not, the change was in early 2017... 

You can try to call a script with 

LandscapeMgr.removeCachedLandscape(name); 

You can try to experiment with the other cache-related calls from https://stellarium.org/doc/0.20/classLandscapeMgr.html.

**Comment by alex-w** [comment]
> I frequently create and edit landscapes. The loading of another landscape in-between always worked for me to force a refresh of the texture, at least on Windows.

@gzotti maybe you can add a new "hidden" method into LandscapeMgr class for developers, similar to ConstellationMgr::reloadSkyCulture()?

**Comment by axd1967** [comment]
works in 0.20.3!
