### ISSUE TITLE
increase FOV marker limits

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1196]
**Is your feature request related to a problem? Please describe.**
I want to have an idea of what a 2.1x40 wide binocular looks like (aFOV  26) but the GUI is limited to 25.

**Describe the solution you'd like**
increase FOV angles to **180**.
![image](https://user-images.githubusercontent.com/3529789/89437649-2533f280-d748-11ea-88bb-eab6e5adadb6.png)

yes, 180. 
otherwise, please explain why 25 is the limit, bearing in mind Y2K reasonings.

**repeat this for the Telrad.**
![image](https://user-images.githubusercontent.com/3529789/89437601-13eae600-d748-11ea-885f-006e9fccc6a1.png)

**Describe alternatives you've considered**
create an ocular. this works, but I cannot zoom out when ocular mode is active.

**Additional context**

**Comment by gzotti** [comment]
The limits have been created based on existing instruments. OK, there is this singular 2.1x40. Does it have a 26° FoV, precisely? Why not just set main screen FoV to 26°? We will never make you happy, I know. 180°? For what? Examples, please.

**Comment by alex-w** [comment]
OK, I'll change FOV limit up to 28 degrees: 
https://agenaastro.com/kasai-trading-wide-field-binoculars-28-true-field-view.html
http://www.holgermerlitz.de/opera2.3x40.html

**Comment by axd1967** [comment]
sorry, but these are wrong arguments.

you never know what future use cases will come up.

here is a case I now want to do: I want to show a square that represents the area of a photo, inside a screen that provides context.

![image](https://user-images.githubusercontent.com/3529789/90252766-57c4a600-de40-11ea-8b93-fb2233b61bfc.png)

but i'm limited by a feeble 26 degrees?

![image](https://user-images.githubusercontent.com/3529789/90253176-0832aa00-de41-11ea-97d9-2072456dab81.png)

something like this:

![image](https://user-images.githubusercontent.com/3529789/90253258-29939600-de41-11ea-90b1-afadb1b66c27.png)


why impose limits if there is no FUNDAMENTAL reason to IMPOSE such limits? 
just let the imagination go wild!
remember Y2K? develoeprs thought that would NEVER be needed.

the only reason I could accept is that the FOV rectangle is **mathematically not correct**, and you want to avoid bug reports because of that.

**Comment by axd1967** [comment]
One workaround is to create a sensor/lens/telescope combination that mimics the camera that was used.

**Comment by alex-w** [comment]
> Stellarium is a free open source planetarium for your computer. It shows a realistic sky in 3D, just like what you see with the naked eye, binoculars or a telescope.

Why not 360 degress? Or, maybe, 720 degress?

**Comment by axd1967** [comment]
exactly.

**Comment by gzotti** [comment]
This is not a workaround, it is the correct solution. The FoV box is a recent addition that gives a quick approximation for 95% of uses. Likewise, a Telrad finder is for pointing optical instruments, so a circle of 180° is arguably nonsense. But argue with a practical use case, don't say Y2k. And yes, probably showing a rectangle of excessive size may have mathematical issues. We leave it as *homework for you* to work out the error in Hammer-Aitoff projection with vertical offset. 

Implementing (most likely fraudulent) specifications of optical instruments like your 300x/40mm toy that allows Apollo side views of the Moon help nobody apart from a fraudulent dealer. This has not to do with Y2k, but with noise and "range pollution", like giving too many useless decimals in results. Rather see it the other way round: If Stellarium's range is not enough, there may be something fishy with the instrument.

**Comment by axd1967** [comment]
I just thought of yet another case: an all-sky (cloud) camera.

(and it's not because an **exotic** projection will not show the FOV frames correctly, that it should be restricted to some small values.)

but indeed, **if** there is a mathematical issue for the **common** projections, **then** THAT needs to be corrected rather than impose a limit (and let users believe it is correct for tha limit).

we are not talking about useless decimals here. we are talking about arbitrary limits that will be broken. if someone wants to select a foolish value, let them have fun!

and I'm not discussing "that" instrument (please don't insult me with Apollo references), I don't care about it. the real issue is this:  choosing **arbitrary** limits based on "existing instruments" is a recipe for future issues, that's guaranteed: someone will show you a real, existing instrument that exceeds your limits.

**Comment by alex-w** [comment]
@axd1967 please read twice the short description of planetarium on the first page at stellarium.org website and limit your fantasy.

**Comment by gzotti** [comment]
OK, with such new instrument's usefulness demonstrated, we may be going to change our arbitrary limits. Not before. Maybe it's time for you to look for better software then.
I see not need for any fov box in an all-sky camera.

**Comment by axd1967** [comment]
## workaround
For future reference: the archaeolines plugin provides a nice workaround via a **custom altitude**.

for_wishlist
