### ISSUE TITLE
AstroCalc keeps native planet names

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1203]
## Expected Behaviour
When a new sky culture is selected, names of planets in the ephemeris list change to the corresponding name in the sky culture. The names change when you change sky culture.

### Actual Behaviour
The names only change once.

### Steps to reproduce
1. Select a sky culture with distinct planet names, e.g. the Mongolian sky culture.
2. Open up AstroCalc, and the ephemeris list. Note how Mars is called "Angarag". Close down AstroCalc.
3. Now change to another culture, e.g. Western culture.
4. Look back into the AstroCalc. The planet names from the Mongolian culture will have been kept.

I can't remember this being an issue before, so I think it has been introduced quite recently.

Using the latest public beta, (0.20.2.18113).

**Comment by Atque** [comment]
The location dialog has the same problem...

Choose Almagest sky culture (before opening Location dialog)
Want to go to Mercury!
Can't go to Mercury, because it is now named Hermes.

Small problem, but the same as above. :)

**Comment by alex-w** [comment]
Please check version 0.20.3-4b8e7fd1c8: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
