### ISSUE TITLE
starlore and plugin dialogs do not honor UI font size

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1204]
### Expected Behaviour
Changing font size in settings does not change font size of plugin and starlore dialogs

### Actual Behaviour

![image](https://user-images.githubusercontent.com/3529789/89732003-e5248680-da4b-11ea-8bc4-955c2b0e9779.png)

![image](https://user-images.githubusercontent.com/3529789/89731993-d211b680-da4b-11ea-8f70-665b6b334e57.png)

![image](https://user-images.githubusercontent.com/3529789/89731982-bc03f600-da4b-11ea-9b1c-75ae305bb182.png)

### System
* Stellarium version: `master`
* Operating system: KUbuntu 20
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Descriptions of starlore or landscapes are just HTML pages and these pages do not relate to font settings of GUI.

**Comment by gzotti** [comment]
You can however scale the HTML descriptions nicely with Ctrl+Mousewheel.

**Comment by axd1967** [comment]
This is an acceptable although not intuitive workaround. (I guess there exists a HTML directive to change the base font size.)

**Comment by gzotti** [comment]
Users of 2021 likely have discovered they can scale their webbrowsers with Ctrl+wheel. They can do the same now in Stellarium. It takes a split second. 
Given that the default HTML font size seems good enough for (all-1) users, I will not put any effort into changing it.

**Comment by axd1967** [comment]
> Users of 2021 likely have discovered they can scale their webbrowsers with Ctrl+wheel. They can do the same now in Stellarium. It takes a split second.

Users of webbrowsers do know this. but I highly doubt that even a majority of Stellarium **desktop app** users know this, because this is not a typical application feature, and desktop users do not expect browser behaviour in desktop apps.

(I'm **almost 100%** certain that the handful of Stellarium that I **personally** know, are **NOT** aware of this).

**Comment by alex-w** [comment]
Fixed in commit b1b5db3d25bc304f09f2d73afe0d527e8ed7967e
