### ISSUE TITLE
Incorrect data for two DSOs

### ISSUE THREAD

**Issue by tiagohm** [Stellarium/stellarium#1208]
Hi,

I think I found two DSOs with incorrect data from Stellarium Standard Catalog v0.20.2: "Vela Junior" and "SNRG263.9-03.0".

![Captura de tela de 2020-08-10 17-36-13](https://user-images.githubusercontent.com/16495338/89829206-91d83400-db30-11ea-80fa-69e0c4a273d5.png)

![Captura de tela de 2020-08-10 17-36-54](https://user-images.githubusercontent.com/16495338/89829222-97357e80-db30-11ea-9887-1c36c2394951.png)

The SIMBAD reference: http://simbad.u-strasbg.fr/simbad/sim-id?Ident=RX+J0852.0-4622, http://simbad.u-strasbg.fr/simbad/sim-id?Ident=SNR+G263.9-03.0

**Comment by alex-w** [comment]
Which data is incorrect?

**Comment by tiagohm** [comment]
Type and RA/DEC
