### ISSUE TITLE
F-Droid Release

### ISSUE THREAD

**Issue by grravity** [Stellarium/stellarium#1209]
Would absolutely love to see an F-Droid release, was surprised to see it doesn't already exist..

**Comment by alex-w** [comment]
I mark this issue as "invalid" because question is related to mobile edition of Stellarium, but it was asked in issue tracker of desktop edition of him.

**Comment by rugk** [comment]
(Where) Is there any mobile/Android issue tracker? Did not find anyone on girhub here in the organisation?

**Comment by gzotti** [comment]
This repository maintains the desktop version. Some other people created their own forks for making Android builds, but they never provided usable PRs.

**Comment by alex-w** [comment]
https://stellarium-labs.com/

**Comment by gzotti** [comment]
Note that this is a new project, not a derivative.
