### ISSUE TITLE
Issues with Version 17: freezing, screen flashing, and mouse scrolling is slower and not smooth 

### ISSUE THREAD

**Issue by Zorando** [Stellarium/stellarium#121]
Before reporting an issue, please *absolutely make sure* to check the closed issues 
(https://github.com/Stellarium/stellarium/issues?q=is%3Aissue+is%3Aclosed) 
whether it has been reported and solved/closed already! Don't report in this case.

Also look into the wiki (https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version) 
and check if you are attempting to report a known issue. Don't report in this case.

Also look into the User Guide before reporting unexpected but correct behaviour. Don't report in this case.

If you want to report a feature wish, delete these template lines above and below, and fill in. 

If you want to report a bug, please make sure to update and verify the bug still exists in the current version. 
In this case please also check current beta builds from http://stellarium.org
If bug still persists, delete text above down to and including this line and fill in:

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
# Expected Behaviour
Reporter @Zorando reads FAQ and other sources as indicated
# Actual Behaviour
Apparently reporter @Zorando did not read FAQ or any other sources as indicated
# Resolution
Reporter @Zorando should read FAQ, act accordingly (install drivers, try ANGLE if on Windows, ...)  and in case of persisting problems fill in the questionnaire properly

**Comment by gzotti** [comment]
Timeout.
