### ISSUE TITLE
fix Dutch translation errors

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1210]
Follow-up of #1205 

I found various Dutch-nl translation issues that I corrected in Transifex. A few remarkable ones:

- mixup of "Waterman" and "Arend"
- wrong translation of Vela

Can you confirm when this is added to a Stellarium release?

**Comment by gzotti** [comment]
See GIT history. Entries like "Apply translations for public testing" appear almost every week, before a beta is put online. If you have descended to use the regular ("Uh, bad, slow, horrible, ...") Transifex interface, it will just be there. The next _release_ can be expected around autumn equinox.

**Comment by axd1967** [comment]
OK - just so that I know: how often are Transifex entries synced into the code base?

**Comment by gzotti** [comment]
> See GIT history. Entries like "Apply translations for public testing" appear almost every week, before a beta is put online.

**Comment by axd1967** [comment]
yes, it's the "almost" that made me wonder. I'll check again next week, thx.

**Comment by alex-w** [comment]
Closed by revision a1c82cd

**Comment by axd1967** [comment]
and confirmed, thank you!
