### ISSUE TITLE
Problems using the telescope funktion

### ISSUE THREAD

**Issue by Pikkusspecht** [Stellarium/stellarium#1214]
I am using Stellarium since many years for moving our telescope to starpositions. Our Mounting is a 30 jears old german mounting 7 – AD. And all the years ist was working perfekt. When I made the upload of the 0.18.2 version it was no longer possible to find the correct star position. Obviously something has chanched in this version. So we worked since that time all the years with version 18.1. Now I tried it again with the newest version 20.1. But it is not working correctly. We worked with Version 18.1 on the Divice setting Mead LX 200 and it was ok. This and all the other telescope divice settings do not work on Version 20.1. and lower. The programms accept the reference star, but if you want to got to another star, the telescope moves anywhere and not to the chosen star. Can anybody help me? Otherwise I have to continue working with the old version 18.1.

**Comment by gzotti** [comment]
Not that I could help here, but if you need assistance, you should not close this issue.

Is your mount compatible with some ASCOM driver or other 3rd-party software and working correctly? Then you could use that one. Else I remember we had some LX200 implementation correction that now adheres to the official protocol specification. If your device was working with the non-standard implementation, it may have been more luck than anything else. Or a typo in the official docs vs. protocol. I have no device to test this.

Maybe the logfile has some diagnostic messages that could help finding out what's going on, but when it comes to hardware, remote diagnosis is hardly possible.

**Comment by Pikkusspecht** [comment]
Sorry I am really new, how can I reopen this issue or do Ihave to built a new one ?

**Comment by Pikkusspecht** [comment]
Ok  it looks like it is open again,

We do not use Ascom driver with this mounting, we only work over a virtual  serial port.

**Comment by gzotti** [comment]
I have closed your duplicate and reopened this, because I answered this one. Open and close buttons are near the bottom of the webpage. 

Given that the serial communication does not work at the moment, I suggested that you may try ASCOM. But please use version 6.4, because the latest 6.5 seems not to work (yet) for us.

**Comment by RAHunt1960** [comment]
I am not sure what version I used successfully for many years to "go to" by picking an object and having stellarium provide the information for the telescope to get there.  I have been fighting a problem with it not working anymore and am tracing it to the Stellarium 0.20.2 I loaded a few weeks ago.  I have picked a star that on the Stellarium screen shows as a minus Dec value.  When I go to the Log file it looks like it was sent as a positive value.  When I select a star with a positive Dec value it sends that as a positive value as well.  I can see why my homemade telescope and my home brew program has a hard time "going to" the right place.  I am using the Meade200X compatible option.  It has worked great in the past.  What changed in going to the official standard Meade200X protocol.

**Comment by RAHunt1960** [comment]
I changed from 0.20.2 to 0.18.1 and after some tweaking of my program I seem to have everything working as it had been before.
One of the things I had forgotten was that I had made changes to the way I read the information sent from Stellarium to try to work with the changes to the newer versions in terms of the formating of the information sent.  There was a space removed in the Sr and Sd data and some other changes involved with the position of numbers etc.  One needs to look carefully at the log file and compare that with the way your program interprets the data from Stellarium.  It may be that when I made the changes to accommodate 0.20.2 that I missed something.  I will re-visit it at some time in the future.  For now I am just happy to have something that works.

**Comment by gzotti** [comment]
@RAHunt1960 are you referring to a logfile that contains protocol information from the LX200 telescope? We need somebody with as physical LX200 to finally decide whether the serial data protocol from the official Meade documentation works (to which we have changed some time ago) or whether the old implementation worked more correctly, despite it being in contradiction to the documentation. I don't have a telescope to find this out.

**Comment by Pikkusspecht** [comment]
Okay very much thanks for your information, give me some time to test this and I will send you an information about my Test. Thanks for your working. Many greetings Michael
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 17.09.20, 10:58, Georg Zotti <notifications@github.com> schrieb:

@RAHunt1960 are you referring to a logfile that contains protocol information from the LX200 telescope? We need somebody with as physical LX200 to finally decide whether the serial data protocol from the official Meade documentation works (to which we have changed some time ago) or whether the old implementation worked more correctly, despite it being in contradiction to the documentation. I don't have a telescope to find this out.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Stellarium/stellarium/issues/1214#issuecomment-694097515",
"url": "https://github.com/Stellarium/stellarium/issues/1214#issuecomment-694097515",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by RAHunt1960** [comment]
My telescope is not a MeadeX200.  Mine is home made and my program to run it is cobbled together from bits of code picked up here and there and tweaked or extended to work with my hardware. I am not a programmer and end up spending a lot of time trying to get things to work the way I would like them to and that is a moving target. The more I “improve” things, the more I see I would like to change.  When I first switched to 0.20.2 from something down around 0.15.X I spent a lot of time messing around before I found that I needed to change the way I decoded the information I received from Stellarium. I thought I had it fixed, but was changing lots of other things at about the same time and hadn’t actually had the telescope Outside at night to see if it really worked.  I am guessing that my decoding for 0.20.2 is close but not perfect. Going to 0.18.1 and some older code appears to work, but the proof will be when I try slewing between objects in the sky using Stellarium as my input.  I am guessing I can get 0.20.2 to work now that I have re-discovered where the problem originated. 
That’s a long answer to whether I have a MeadeX200 telescope. 
Ron

**Comment by RAHunt1960** [comment]
I have looked at things carefully and noticed that with 0.20.2 things worked if I was slewing to an object with a positive DEC value.  When I tried going to one with a negative value things didn't work well.  I failed to correct the position of the negative sign in the information Stellarium sent.  When I made that change things appears to work for both positive and negative values of DEC.  I think my initial indoors testing probably involved objects with positive DEC values.  When I noticed I had a problem was when I first tried to "go to" an object with a negative DEC value when I was outside and could clearly see that I wasn't getting even close to the object.  I hope someone finds my experience helpful.

**Comment by Pikkusspecht** [comment]
Hi, I am sorry,

I am not That well with working that logfile. The Teleskop of our Obsevatory ist an 30 year old Deutsche Montierung. And all I know is that with stellarium 18.1 it worked very well: Findig a reference star and than yousing the go to function. With stellarium 20.2. i can got to an objekt manuell but the go to function is not working.

 

 

 
 

Gesendet: Donnerstag, 17. September 2020 um 10:58 Uhr
Von: "Georg Zotti" <notifications@github.com>
An: "Stellarium/stellarium" <stellarium@noreply.github.com>
Cc: "Pikkusspecht" <Piekmich@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [Stellarium/stellarium] Problems using the telescope funktion (#1214)


 

@RAHunt1960 are you referring to a logfile that contains protocol information from the LX200 telescope? We need somebody with as physical LX200 to finally decide whether the serial data protocol from the official Meade documentation works (to which we have changed some time ago) or whether the old implementation worked more correctly, despite it being in contradiction to the documentation. I don't have a telescope to find this out.

**Comment by RAHunt1960** [comment]
I will be happy to provide such help as I can.  I don’t claim to be a programmer, so you will have to be patient with my help.
As I see it, there are some steps you must take, I will ask a series of questions and then provide some help:
1.  Have you found the LOGfile on your computer?
2. Have you checked the box in Stellarium so the file will be created?
3. Do you know which part of your telescope program decodes the information Stellarium sends?
4. Have you actually seen the LOGfile?  

When I first became aware there was a LOGfile I couldn’t find it on my computer.  It is pretty well hidden.  On my
Computer the path is as follows:

This PC  >  Windows(C:) >  Users > rahun > AppData > Roaming > Stellarium > LogFile

If the LOGfile isn’t there, go to Stellarium and select Configuration, then Plugins, then Telescope Control, then Options, then check the box under Files.  It will be labeled “Log Telescope Driver Messages to File”.  This will activate the file process but then you must make the connection to your telescope and attempt a “go to” sequence.  I found it helpful
To record the RA/Dec data on the screen when the object was selected.  This will help you locate the part of the logfile you need to pay attention to.

Becoming familiar with the part of your telescope software that decodes the Stellarium input is up to you.

I will try to attach a couple of files that are snippets from a Logfile for a star with a positive Dec value and one for a negative Dec value.  As I recall the major difference I noticed in going from 0.18.1 to 0.20.2 was a blank space was removed which altered the position of each of the numbers representing the  position of the object including the position of the negative sign.  Initially I hadn’t adjusted for the sign (+ or -).

I hope this will at least get you started.  The general format of the logfile is Requests for GR followed by the data sent by your telescope then a request for GD followed by the data from your telescope.  This repeats as your telescope provides Stellarium with your telescopes current position.  Pressing Control followed by the number of your telescope basically requests Stellarium to send the Sr and Sd data to your telescope.  Your telescope should send back a 1 for each set of data indicating it has received it.  Stellarium will continue to request GR and GD data.  I have found that you can usually find the part of the file with the Sr and Sd information by scanning through the file and looking at the longest lines.

You will probably want to compare Logfiles from both 0.18.1 and 0.20.0 to identify differences in the data sent.

I hope this is helpful.  Don”t hesitate to ask questions, I will help as much as I can.  I know how frustrating trying to figure out and correct this stuff can be.

Good Luck!

Ron Hunt



Sent from Mail for Windows 10

**Comment by RAHunt1960** [comment]
Looks like the files I tried to attach didn't make it here.  I will try to attach them here, I think they may have made it to the e-mail
[Logfile for negative Dec.docx](https://github.com/Stellarium/stellarium/files/5256732/Logfile.for.negative.Dec.docx)
[Logfile for positive Dec.docx](https://github.com/Stellarium/stellarium/files/5256736/Logfile.for.positive.Dec.docx)

**Comment by RAHunt1960** [comment]
The previous two files were from Stellarium 0.20.2.  I am going to attach another file with a snippet from the Stellarium 0.18.1 LogFile.  The information sent from Stellarium should be in RED.
[LogFile for 0.18.1.docx](https://github.com/Stellarium/stellarium/files/5257199/LogFile.for.0.18.1.docx)

**Comment by RAHunt1960** [comment]
The last upload had a break so the space isn't shown.  This one should show the space.
[LogFile.for.0.18.1 (1).docx](https://github.com/Stellarium/stellarium/files/5257282/LogFile.for.0.18.1.1.docx)

**Comment by RAHunt1960** [comment]
Let me try that again, looks like I picked the wrong file.
[LogFile.for.0.18.1.docx](https://github.com/Stellarium/stellarium/files/5257319/LogFile.for.0.18.1.docx)

**Comment by gzotti** [comment]
Please see #818 
Do all those telescopes work with version 0.19.2, and not work with version 0.19.3? And is there anybody out there with a real, physical Meade LX200 telescope to help us testing those two versions? I would like to know whether the official Meade protocol specs are better be ignored in order to support Meade telescopes.

**Comment by RAHunt1960** [comment]
As I indicated previously mine is not  a MeadeX200.  I have got mine to work with versions older than 0.18.1 and with 0.18.1 and with 0.20.2. I had to change the way my telescope software interpreted what Stellarium sent to get it to work with 0.20.2. 
I have no experience with newer versions than 0.18.1 other than 0.20.2.  I suspect at least some of the users had written their software for non-MeadeX200 to work with the older implementation and have problems with the newer. I can now use either but hope you will settle on one or the other and stay with it. 
Ron

**Comment by gzotti** [comment]
Yes, this is why I am asking for a test with a "real" Meade LX200. I'd prefer to support that, and if we find out that the protocol docs are wrong, we have to write some comment to the working code that the docs are off.  DIY solutions then should follow.

**Comment by RAHunt1960** [comment]
Did you check the box in Stellarium so the file would be created?  
Unless you can find the part of your telescope program that decodes the serial data Stellarium sends you will be better off just staying with 0.18.1. It sounds like the people who update Stellarium are not sure which implementation would better serve the community. The old version 0.18.1 and beyond didn’t agree with the published protocol for MeadeX200 telescopes. They updated it to comply with the published protocol and are trying to find someone with an actual MeadeX200 to see which works best. In the meantime people like you and me who have telescope programs set up to work with the old version either need to update our programs or stay with the older version.  The final version for Stellarium is still not decided. They could end up going back to the older version at some future update. 
I am still willing to help you if you want to pursue it more. 
Ron Hunt

**Comment by jfdavis668** [comment]
gzotti was looking for some logs from a Meade LX200 telescope. I connected using version 19.2, 19.3.1 and 20.3. I started on the star Altair, used Stellarium to move the scope to the northern star Vega, then to the southern star Nunki, then back to Altair. Logs from each version are attached.
[log_19.2.txt](https://github.com/Stellarium/stellarium/files/5314176/log_19.2.txt)
[log_19.3.1.txt](https://github.com/Stellarium/stellarium/files/5314177/log_19.3.1.txt)
[log_20.3.txt](https://github.com/Stellarium/stellarium/files/5314178/log_20.3.txt)
[log_TelescopeServer1_19.2.txt](https://github.com/Stellarium/stellarium/files/5314179/log_TelescopeServer1_19.2.txt)
[log_TelescopeServer1_19.3.1.txt](https://github.com/Stellarium/stellarium/files/5314180/log_TelescopeServer1_19.3.1.txt)
[log_TelescopeServer1_20.3.txt](https://github.com/Stellarium/stellarium/files/5314181/log_TelescopeServer1_20.3.txt)

**Comment by gzotti** [comment]
@jfdavis668 many thanks, excellent! It seems at least the answer given really is not what the protocol documentation promises. But I assume it worked with all systems? 
We are going to revert the asterisk symbol next. It's just weird that the used character strictly seen is not even allowed!

**Comment by jfdavis668** [comment]
Yes, the scope worked properly each time.

- Jim Davis

**Comment by alex-w** [comment]
@Pikkusspecht @RAHunt1960 @jfdavis668 please check version 0.21.3

**Comment by gzotti** [comment]
It seems that the applied changes (revert) worked, so we can close this.
