### ISSUE TITLE
The Chinese name of Kaus Australis (ε Sgr) is not correct

### ISSUE THREAD

**Issue by superacrux** [Stellarium/stellarium#1217]
### Expected Behaviour
The Chinese name of Kaus Australis (ε Sgr) is 箕宿三
### Actual Behaviour
Describe or maybe attach a screenshot?
The Chinese name of Kaus Australis (ε Sgr) is 萁宿三.
萁 should be 箕.
### Steps to reproduce
Display the Chinese name of Kaus Australis (ε Sgr).
### System
* Stellarium version: stellarium-0.20.2-win64.exe
* Operating system: Windows 10
* Graphics Card: NVIDIA GeForce GTX 1660Ti Max-Q
* Screen type (if applicable): 1920*1080

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Please use Transifex to fix translations: https://www.transifex.com/stellarium/stellarium/dashboard/

**Comment by alex-w** [comment]
@sunshuwei please check it on transifex

**Comment by sunshuwei** [comment]
OK, it is now fixed.
