### ISSUE TITLE
Earth - Moon tidal lock isn't depicted when observing Earth from the Moon

### ISSUE THREAD

**Issue by thulasidharan2k8** [Stellarium/stellarium#1218]
### Expected Behaviour
When watching a timelapse of Earth from the Moon, the tidal lock isn't depicted and the Earth actually rotates. 

### Actual Behaviour
Since the Moon is tidally locked with Earth, the Earth shouldn't rotate in this case.
https://youtu.be/43SuWGNZBRU

### Steps to reproduce
1. Launch Stellarium
2. Search for Moon
3. Ctrl+G - Move to the Moon
4. Search Earth and 'center on the selected object'
5. Start timelapse

### System
* Stellarium version: 0.20.1
* Operating system: Windows 10
* Graphics Card: NA
* Screen type (if applicable): NA

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Please learn astronomy or, at least, explain why we do not see duration of lunar month in 24 hours.
