### ISSUE TITLE
Incomplete Phenomena list at Astronomical calculations

### ISSUE THREAD

**Issue by Mauriciovigano** [Stellarium/stellarium#1219]
### Expected Behaviour

Generate list of all the Phenomena at Astronomical calculations.

### Actual Behaviour

List of phenomena is incomplete, missing several conjunctions and oppositions. 
Was using version 18.1 for a while and the list was complete, on November 2019 updated to version 19.2 and noticed the missing phenomena.
This is still happening with version 20.2.

### Steps to reproduce

Using latest version go to Phenomena at Astronomical calculations, generate list with parameters as image below and save as spreadsheet.
![stellarium 20 2](https://user-images.githubusercontent.com/69799080/90396458-a0f93d80-e06c-11ea-9476-a2d58bf92850.jpg)

Install version 18.1 and generate the list with the same parameters, save and compare with the list gerenated with version 20.2.

For this example (phenomena between moon and planets), version 18.1 shows 179 phenomena for 2021 while version 20.2 down to at least 19.2 shows only 92 phenomena.

### System
* Stellarium version: 19.2 and up
* Operating system: Windows 10
* Graphics Card: NVidia GeForce 940M, driver version 388.57

**Comment by gzotti** [comment]
Can you identify which phenomena are missing? Are the settings (distance etc) identical?

**Comment by Mauriciovigano** [comment]
Hello all, thank you for the quick reply and sorry not answering sooner.
It seems that the bug happened at the 19.2 version, the list generated with 19.1 was complete.
Will perform a few tests and go through the lists in detail to give more info.
