### ISSUE TITLE
Saving an event to calendar in system 

### ISSUE THREAD

**Issue by Worgin** [Stellarium/stellarium#122]
Perhaps this is a strange request, but it would be useful to lazy people and to facilitate the planning of observations. The feature I'm talking about is the possibility of saving astronomical events, such as conjunctions, to the calendar in the system. Windows 10 has the feature to save events in the calendar, I don't know how how about other versions of windows, but I think there are still some some solutions for that. In that feature, setting time of doing observations would be nice. I know it's a modest idea, is it likely that it'll be implemented in the future?

**Comment by gzotti** [comment]
You can use a Stellarium Bookmark for this. Entering an astronomical event into any operating system's own calendar is not in our plans, but probably we would accept a patch that optimally should work on several supported distributions of Linux, Mac and of course Windows in all currently used versions (7, 8.0, 8.1, 10).
