### ISSUE TITLE
GUI font issue

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1221]
### Expected Behaviour
Font of status text stays inside screen

### Actual Behaviour
Describe or maybe attach a screenshot?
![image](https://user-images.githubusercontent.com/3529789/90437246-56121100-e0d2-11ea-933a-463b0d3ea08c.png)

### System
* Stellarium version: 0.20.2
* Operating system: KUbuntu 20.04
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/5086448/log.txt)

**Comment by gzotti** [comment]
Didn't we enlarge it to excessive sizes particularly for you, so that you can have large fonts when making large screenshots?

**Comment by axd1967** [comment]
This happens when increasing the GUI font to large values.
At "normal" values (11-20) this is no problem; this starts to happen as the font size goes above 22.

**Comment by axd1967** [comment]
This "opinion" no longer appears in Version 24.3.301-4ee5f20 [master] Based on Qt 5.12.8 (or maybe earlier); possibly solved in dbf8e3eafb29c268b0b4e4cef7590c849777e05c by @10110111 (thx)
