### ISSUE TITLE
Year 1082

### ISSUE THREAD

**Issue by ftang9** [Stellarium/stellarium#1224]
Problem with year 1082 August 12.
On August 16, 2020:  year 1082, August 8, the moon was in between Sagittarius and Capricornus  
On August 17, 2020:   Year 1082 August 12, the moon was in Sagittarius 
In 2017: year 1082 August 12, the moon was in Aquarius 

Can you tell me which one is correct?

**Comment by gzotti** [comment]
Depending on time and timezone:

year 1082, August 8, the moon was in between Sagittarius and Capricornus --- CORRECT
Year 1082 August 12, the moon was in Sagittarius --- IMPOSSIBLE. Cannot go backwards by 1 day in 4 days
year 1082 August 12, the moon was in Aquarius --- moving from Aquarius to Pisces

Please show any evidence for "August 17, 2020: Year 1082 August 12"

**Comment by ftang9** [comment]
Thank you for your reply.
The location is eastern North America.
Using iPad version of stellarium
Now, still showing 1082 August 12, the moon was in Sagittarius ...

**Comment by gzotti** [comment]
This site only deals with the desktop version of Stellarium: Currently we are at Stellarium version 0.20.2, running on Linux/Windows/MacOSX. 

The mobile versions are different and have their own support sites, please go there for assistance.

**Comment by ftang9** [comment]
Looks like there is a discrepancy between the PC version and iPad version..

**Comment by ftang9** [comment]
Thank you for your help.

**Comment by gzotti** [comment]
Pure guesswork: "the iPad version" (whatever version that really means!)  uses a proleptic Gregorian calendar. That would mean, "use with caution for all dates before October 15, 1582". But I don't know the source code. People living in 1082 have seen the Moon in front of Aqr or Psc.

**Comment by gzotti** [comment]
Did Chinese poets really use the European/Latin month name "July" or "August" in 1082 AD? I would assume a translation problem in this case. 

There are calendar conversion tools between Chinese and Julian calendars.  Not sure if they are applicable for the 11th century, though.

If your "Sagittarius and Capricorn" relate to Zodiacal signs, not the stellar patterns forming visible constellations, this relates to an ecliptical longitude around 270°. The 15-day old Full Moon was there on June 13/14. But further analysis really needs much more insight in the context of this text. Use the desktop version of Stellarium for a good simulation. I cannot say whether there is a software problem in the iPad version.

**Comment by ftang9** [comment]
It says the  7th month of the year in the text. 

As Chinese we look at the asterisms. I think they moved about 25 degrees  in the last 2,000+years？The autumn equinox was near Spica then.

We know it was the day after the 7th month’s full moon.
It could only be the August full moon on the 11th  or the September full moon on the 9th. 
We know it was 1082.

Thank you for your help.

**Comment by gzotti** [comment]
If I am right, Chinese New Year was 1082-02-01. Then yes, Full Moon was August 11 (Julian; in China). On the 12 the Moon was moving from Aquarius to Pisces, or rather near the Chinese "Palace Guard" and "Line of Ramparts" asterisms. Use the Chinese skyculture in the desktop version to analyze the text with the (hopefully) right constellations. 
This is about all help I can give at the moment.

**Comment by ftang9** [comment]
Hi, 
Thank you very much for your help.
I looked at the pc version from year 1 to year 10, and from year 1580 - 1590
The August full moon was always near Aquarius or Pisces.
It did not move away for the last 2000 years. 

I would like to prove this mathematically, can you show me a good way to do this?
Thank you very much.
