### ISSUE TITLE
"custom object" type does not appear in Find dialog

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1226]
Translators are offered the possibility to translate "Custom Objects" (eg Custom Marker):
https://github.com/Stellarium/stellarium/blob/49616646344a26b3778a4f2c2949b34e8ab870c1/src/translations.h#L105-L106

But this type of object does not appear in the Find dialog:
![image](https://user-images.githubusercontent.com/3529789/90748789-ed45b700-e2d2-11ea-9ffa-1a387968cd7e.png)

(even when creating a marker).

**Comment by alex-w** [comment]
Please explain it:
![stellarium-089](https://user-images.githubusercontent.com/88731/90754606-4974ff00-e304-11ea-812d-d6e388e54038.png)

**Comment by axd1967** [comment]
Works now, thank you!

![image](https://user-images.githubusercontent.com/3529789/90759657-05bcce00-e2e1-11ea-9e51-70d51bea634d.png)
