### ISSUE TITLE
Request more features in WUT

### ISSUE THREAD

**Issue by Hans-Cong** [Stellarium/stellarium#1230]
WUT is a very good feature which help observers plan their observation. It will be more helpful if more features can be added to it as following.

**Describe the solution you'd like**

- [ ] Allow multiple choice of Categories. Sometimes you just want to see all nebulaes, or clusters, instead of a certain type. 

- [x] Allow filter the object by star category(Messier, NGC……). That will provide convenice for some users, especially for Messier Marathoners.

- [ ] Add maximum magnitude limit for advanced observers who are bored with bright objects.

- [ ] Current choice of time span is too vague ("In the evening", etc.). It would be better if a user can specify the time span by minute.

Btw, the addition of minimum elevation raised in issue #1089 is a good idea, but I didn't see it in my Stellarium V0.20.2. I wonder if you are still working on it. If so, please go ahead!

**Comment by alex-w** [comment]
This is may be strange for you, but items 2, 3 and partially 1 already available for usage on first tab (AstroCalc/Positions tool). For example to prepare for Messier Marathon you may select Messier Catalogue section, set required time and press button “Update positions” - and you will get list of Messier objects above horizon for your location and selected time.

**Comment by Hans-Cong** [comment]
Sorry for my neglecting that tab. After checking "Positions" tab, I found the Messier Category, that solves the problem. 

For the "Star Clusters", I thought it should be a intersection of all the star clusters(eg. open clusters, globular star clusters, etc.), but it actually contains very few objects, which confuses me. I mean I want a choice of collection of all the objects called star clusters(or nebulae). Maybe it is a minor demand, nevermind.

I suggest making the Position and WUT have the same category to be chosen. That is adding Messiers, NGCs to the WUT. After all, WUT gives rise, transit and set time, which is desirable.

Another thing that confuses me is since "Positions" tab mainly do the position calculation work, why it only show objects above the horizon?  This makes "Position" and "WUT" tab overlap in function. They both show objects above the horizon. I wonder if the function of these two tabs could be clearer.

**Comment by alex-w** [comment]
> Sorry for my neglecting that tab. After checking "Positions" tab, I found the Messier Category, that solves the problem.

No problem.

> For the "Star Clusters", I thought it should be a intersection of all the star clusters(eg. open clusters, globular star clusters, etc.), but it actually contains very few objects, which confuses me. I mean I want a choice of collection of all the objects called star clusters(or nebulae). Maybe it is a minor demand, nevermind.

I think I can add "Deep-sky objects" category for both tools and it may solve problem for users, who want just observe the sky without filtering deep-sky objects by their types.

> I suggest making the Position and WUT have the same category to be chosen. That is adding Messiers, NGCs to the WUT. After all, WUT gives rise, transit and set time, which is desirable.

OK, I'll add 3 new special categories for the WUT tool: Messier objects, NGC/IC objects and Caldwell objects as very famous catalogs for amateurs.

> Another thing that confuses me is since "Positions" tab mainly do the position calculation work, why it only show objects above the horizon? This makes "Position" and "WUT" tab overlap in function. They both show objects above the horizon. I wonder if the function of these two tabs could be clearer.

The short answer is: the AstroCalc/Positions and AstroCalc/WUT tools has different targets to usage. :)

**Comment by alex-w** [comment]
OK, I've added "Deep-sky objects" category for Positions and WUT tools + 4 new categories for WUT tool: Messier objects, NGC/IC objects, Caldwell objects and Herschel 400 objects. So, item 1 and 2 IMHO fixed now.

**Comment by alex-w** [comment]
Item 4 fixed by AstroCalc/Positions tool and I'll no fix it for AstroCalc/WUT tool

**Comment by alex-w** [comment]
Item 3 is strange. The upper limit for magnitude was introduced to filter the unobservable objects by objective reasons (limitation by eyes or telescope/binocular). Why you need set lower limit for magnitude? You can sort objects by magnitude and just do not use bright objects as targets.

**Comment by Hans-Cong** [comment]
> Item 4 fixed by AstroCalc/Positions tool and I'll no fix it for AstroCalc/WUT tool

OK

> Item 3 is strange. The upper limit for magnitude was introduced to filter the unobservable objects by objective reasons (limitation by eyes or telescope/binocular). Why you need set lower limit for magnitude? You can sort objects by magnitude and just do not use bright objects as targets.

I got that. Just ignore that item. 
I am new in Github. Do I have to tick the 4 boxes or let you developers do that?

**Comment by alex-w** [comment]
Let’s wait new weekly snapshot for testing changes...

**Comment by alex-w** [comment]
Please check latest beta: https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by alex-w** [comment]
@Hans-Cong any feedback please

**Comment by Hans-Cong** [comment]
I just checked the beta version. I think the functions have no problem. Thank you for your work.

There is another little problem. In the AstroCalc, I found that the icons of the tabs can be dragged and stop at a funny position(as screenshot below shows). It does not meant to be like that right?
![image](https://user-images.githubusercontent.com/70120434/93036971-d7c67180-f673-11ea-81cb-9c04f575a36c.png)

**Comment by alex-w** [comment]
Please check 0.20.3RC2

**Comment by Hans-Cong** [comment]
Sorry but where can I find 0.20.3RC2?

**Comment by alex-w** [comment]
https://github.com/Stellarium/stellarium-data/releases/tag/beta
