### ISSUE TITLE
Strict Gregorian calendar system

### ISSUE THREAD

**Issue by Orestes-3113** [Stellarium/stellarium#1235]
The current Date and Time window uses the Julian system when going back in time. The Gregorian calendar system uses intercalation to offset calendar drifts in relation to our solar year. 

I currently use a calculator to work my way around it:
https://keisan.casio.com/exec/system/1227757509

**Comment by gzotti** [comment]
Stellarium follows common practice and uses the Julian calendar before the Gregorian reform. Period.
