### ISSUE TITLE
Fixate the ecliptic to the vernal equinox

### ISSUE THREAD

**Issue by Orestes-3113** [Stellarium/stellarium#1236]
In astrotheology the tropics are observed over sidereal precession. Stellarium has proven to be a great tool to track ancient stories and take snapshots of the skies, however sidereal precession distorts image.

The vernal equinox could be fixated by a window option to 0° Aries, 0° Taurus, 0° Gemini, ...
depending on a user's input.

Where 0° Aries is defined by the star Torcular at 0° of the ecliptic.

**Comment by gzotti** [comment]
Unfortunately we are not speaking the same language. Developers, observers and users of astronomical software do not follow astrotheological theories. Precession of the equinoxes can be observed. These natural motions cannot be stopped. Please find other software to help you.

**Comment by Orestes-3113** [comment]
@gzotti I understand your views, I am not talking about theories but about calendar calibration much in the same way that the software has room for Starlore. The contex is scientific.

**Comment by gzotti** [comment]
We are not going to change the built-in ecliptical coordinate system. You are free to implement a plugin that shows whatever your coordinates are.
