### ISSUE TITLE
landscape data not remembered

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1237]
### Expected Behaviour
Selected landscape correctly loaded and shown

### Steps to reproduce

1. select a landscape
![image](https://user-images.githubusercontent.com/3529789/91548551-d41db580-e925-11ea-9fbb-f314ef5e18ac.png)

1. click "Set this landscape as default"
![image](https://user-images.githubusercontent.com/3529789/91549242-ef3cf500-e926-11ea-9abe-277c1f424be0.png)

1. save all settings
1. quit
1. start Stellarium

## Bug
landscape name lost
![image](https://user-images.githubusercontent.com/3529789/91549382-257a7480-e927-11ea-871d-fd66d52c489f.png)

![image](https://user-images.githubusercontent.com/3529789/91548610-e861b280-e925-11ea-917d-1b2c3cbee662.png)

Looks like there is a location issue 
![image](https://user-images.githubusercontent.com/3529789/91549492-50fd5f00-e927-11ea-83fa-47dc6603cac6.png)

That is my location, rather than the location defined in the landscape.

### Workaround
in landscape manager, select a different landscape, then re-select the (default) landscape.

(It looks like the landscape loading does not use the same logci that is ran when switching landscapes.)

### System
* Stellarium version: `master 0.20.2.18172`
* Operating system: KUbuntu 20.04
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/5141446/log.txt)

**Comment by gzotti** [comment]
Yes, these are separate. You should also add the landscape's location to the custom locations and store this location as default.

**Comment by axd1967** [comment]
* OK - now I (reluctantly) understand (and still need to test) ; but this is not trivial and not user friendly and should be documented/explained somehow
* if I create several landscapes around mee, do I need to add all those locations to the location database? no, because I am looking at a landscape that I made for Belgium, but _now I notice that the country is somehow set to **France_**:
![image](https://user-images.githubusercontent.com/3529789/91562547-a93f5b80-e93d-11ea-8d23-13e7c7db86b1.png)
That "Textiel" location cannot b e found in the DB, so where did the "France" bit come from?
![image](https://user-images.githubusercontent.com/3529789/91562957-5b772300-e93e-11ea-9222-e502d3c59587.png)

Also, I see no need to add such a location to the location database, because a landscape file defines all that is needed. in other words, when a landscape is selected, it should override all location information.

The solution could be to either

* remove the location data (coordinates) from the landscape file, replace with a name only and force the user to define a location in the location DB so that the landscape manager HAS to look up the coordinates from the location DB (and this is clumsy)
* use ALL information from the landscape (name+coordinates+time), overriding anything that might exist in the location DB

I also notice that there is an inconsistency between landscape and location data: the landscape contains a "State" field that is not present in the location DB. Maybe that "State" field should be dropped, what can be its purpose?


Also, the workaround indicates that there IS a bug. Having to deselect and reselect a landscape should NOT change the name in the status line.

**Comment by axd1967** [comment]
Also, I notiuce that when I switch to "Garching", the location window shows no country:
![image](https://user-images.githubusercontent.com/3529789/91564001-32f02880-e940-11ea-88e9-bcbfeb465da6.png)

**Comment by alex-w** [comment]
We need to check behavior of this feature in series 0.11/0.12 - I fear we was may broke some parts of it at one of iteration of refactoring.

**Comment by axd1967** [comment]
At one point I had the impression that the country field in the landscape had been overwritten because I found a city name in a country field; but I might be mistaken.

**Comment by alex-w** [comment]
OK, I've checked the behaviour of version 0.12.11 - this is not a bug! No need adding extra landscape locations to show location name at left botton corner of the screen.

> At one point I had the impression that the country field in the landscape had been overwritten because I found a city name in a country field; but I might be mistaken.

If country not defined in landscape.ini file then country field in Location dialog will be "empty".

**Comment by alex-w** [comment]
I cannot reproduce "lost of name" issue

**Comment by gzotti** [comment]
The point is to load the location provided by the landscape over the location provided as stored location, if "landscape loads location" is active.  The program never worked like this, but I had considered changing this long ago.

**Comment by alex-w** [comment]
Please check version 0.20.2.18210

**Comment by axd1967** [comment]
works, thanks!
