### ISSUE TITLE
Landscape takes whole screen

### ISSUE THREAD

**Issue by Ilisoi** [Stellarium/stellarium#1239]
### Expected Behaviour
Load landscape without any issues.

### Actual Behaviour
The ground fills the entire screen
https://imgur.com/O1CpWFQ 

### Steps to reproduce
Downloaded landscape from HeyWhatsThat.
Loaded in Stellarium.
Problem appears when elevation is higher than 10 (in my case)

Solution:

Add as first line 0 1
Add as last line 360 1

### System
* Stellarium version: 0.20.2
* Operating system: Windows 10 (10.0)
* Graphics Card: GeForce GTX 1050 Ti
* Screen type (if applicable): 1920x1080

**Comment by gzotti** [comment]
This is not our bug!

**Comment by alex-w** [comment]
Well, the issue is gone after defined 0/360 azimuth point and this point should have non-zero elevation - this is look like bug in our code for definition of end-start sector for contour.

**Comment by gzotti** [comment]
I don't have the horizon list here. But on a mountain peak there are such issues. And the provider of the data could make sure that his data work. HWT has made direct export possible only few weeks ago, this can of course be fine tuned.

**Comment by alex-w** [comment]
Hmm... see an example
[stellarium-landscape-fix.zip](https://github.com/Stellarium/stellarium/files/5145392/stellarium-landscape-fix.zip)

I've added first and end point into horizon.txt file by hands for resolve "broken contour" issue

**Comment by gzotti** [comment]
The correct solution as defined with version 0.15 is given above and in the Guide. I can possibly break this API and avoid this flag, but with some added effort.
