### ISSUE TITLE
Custom time step in ephemeris computation

### ISSUE THREAD

**Issue by Hood-fr** [Stellarium/stellarium#1240]
Would it be possible to specify a custom time step (in a choice of units) for ephemeris computation? I would like for example to draw a Moon analemma which requires a time step of 24h51 (average duration of the passage of the moon over the meridian), but I am not able to do so with the current choices.

Moon analemma example: https://apod.nasa.gov/apod/ap050713.html

Thanks

**Comment by alex-w** [comment]
Double of #1176
