### ISSUE TITLE
Stellarium v0.20.2 will not auto connect to ASCOM Temma mount. Can only do it manually. Is there a fix for this ?

### ISSUE THREAD

**Issue by TomPickett671** [Stellarium/stellarium#1243]
Stellarium v0.20.2 will not auto connect to ASCOM Temma mount. Can only do it manually. Is there a fix for this ?

**Comment by alex-w** [comment]
Duplicate of #1164

**Comment by alex-w** [comment]
Please check 0.20.3RC2
