### ISSUE TITLE
oculars: toggle crosshairs even with permanent crosshairs

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1247]
**Is your feature request related to a problem? Please describe.**
I want to see what is below the crosshairs of an ocular with permanent crosshairs.

**Describe the solution you'd like**
toggle the crosshair visibility.
Note that now, the crosshair button is not functional in case an ocular has permanent crosshairs. this is no reason to disable this feature. present issue just enhances this.

**Describe alternatives you've considered**

**Additional context**

**Comment by alex-w** [comment]
Reason of reject: if you defined some device as a device, who has permanent crosshair (e.g. finderscope), then the tool to toggle the temporary crosshair visualizer shouldn't work for this device. You cannot toggle off the crosshair in real finderscope too.

**Comment by axd1967** [comment]
> Reason for rejection: if you defined some device as a device, who has permanent crosshair (e.g. finderscope), then the tool to toggle the temporary crosshair visualizer shouldn't work for this device. You cannot toggle off the crosshair in real finderscope too.

this is **not** a good argument; you are turning logic the wrong way. Stellarium should allow to do things that you can't do with the physical hardware. there is no reason to block this useful crosshair feature.

and second, the feature proposed is a clean extension; because now, the "toggle crosshair" feature does not work at all when there is a permanent crosshair. in such a case, you should DISABLE the button. but if you do that, you could as well allow a temporary toggle. (in other words, the crosshair always comes up, but can be toggled away).

**Comment by axd1967** [comment]
and also, this should not be marked as "Done" but something like "Not done". nothing has been done in this case! this is an example of wrong management.

**Comment by gzotti** [comment]
Complain about github's automation features. Or just read it as "Decision has been implemented, we are done with this issue."

**Comment by alex-w** [comment]
> this is **not** a good argument; you are turning logic the wrong way. 

Please write a good argument, why you define permanent crosshair for device if you do not want to see this crosshair.

> Stellarium should allow to do things that you can't do with the physical hardware. 

Seriously? Like a pink sky, UFO and eyepiece with 720 degrees of FOV? Maybe we should include horoscopes also?

> and second, the feature proposed is a clean extension; because now, the "toggle crosshair" feature does not work at all when there is a permanent crosshair. in such a case, you should DISABLE the button. but if you do that, you could as well allow a temporary toggle. (in other words, the crosshair always comes up, but can be toggled away).

You have very, very strange logic.

**Comment by axd1967** [comment]
> Please write a good argument, why you define permanent crosshair for device if you do not want to see this crosshair.

sigh. 

let's try this again. the argument is simply (1) that the crosshair is interfering with what I want to see in Stellarium (it's similar to the reason why the choice of colors and transparency is problematic, see #678  ), and (2) the sky is the limit - which means Stellarium should allow more than is physically possible. This is a nice way to extend Stellarium in an elegant way without interfering with the normal operating mode.

The "fixed crosshair" feature should simply ensure that when the ocular is activated, the crosshair appears. That's all! If the user DOES want to remove it - even when the physical crosshair is permanent - just allow this! There is a reason why the user wants to remove that crosshair, let the user choose that reason.

Is that so complicated?

For example... you impose a limitation on the user - such as "_a fixed crosshair" cannot - even temporarily - be removed_". OK, so IF you want to be consequent, THEN you should not allow a user to look through the Earth either ! Because that is not possible either, just as you cannot remove the crosshair ! But no - you DO allow looking below the horizon - because that is just a matter of disabling the landscape. This is what I mean with "let users do things that are physically impossible".

Please stop talking about UFO and pink skies (the latter do exist) and astrology. You are mucking me, while this is a perfectly sound, clean issue with a simple and elegant solution that gives more freedom than just disabling the button.

**Comment by gzotti** [comment]
Can't you simply make a copy of the crosshaired ocular, defined without crosshair, and live with it?  Can't you ever find a way to use a program as you find it, without nagging at every single button, label or tiny implementation decision that the developers made in the last decade? If a physical eyepiece comes with crosshairs, it is a very special one and it should be displayed with it, because you bought it to observe with crosshairs. It is the optional crosshairs to switch on for general eyepieces that is the "what if" decision. 

Just define an ocular without crosshairs. How much of your valuable time does that take, and how much of our valuable time does it take to read all this nagging?

**Comment by axd1967** [comment]
Sorry, no nagging (especially not "at every single button"). The tone of the issue is **neutral** and **respectful**, the **spirit** is to improve Stellarium, because a software product(especially when open sourced) is **never finished** and new ideas will always creep up that could incite a developer (not necessarily you guys, you are already doing great work) to deliver a patch that solves the issue. Especially when the occasion exists to improve a product, something that is nearly impossible in commercial software, where manufacturers often decide to abandon software after a few years, a despicable attitude! (Unfortunately, the meta issue here is language related; I'm doing my best to clearly express ideas.)

Your proposal (copying) is a meagre workaround, because "copy-paste is evil" , remember? This also applies here.

**Comment by alex-w** [comment]
> let's try this again. the argument is simply (1) that the crosshair is interfering with what I want to see in Stellarium (it's similar to the reason why the choice of colors and transparency is problematic, see #678 ), and (2) the sky is the limit - which means Stellarium should allow more than is physically possible. This is a nice way to extend Stellarium in an elegant way without interfering with the normal operating mode.

Sigh, let's try this again. You enabled the option "always draw crosshairs without dependence on the status of the crosshair button" and now you want to disable crosshairs, because you do not want to see crosshairs. If you do not want to see permanent crosshairs then why are you enabled it? I really do not understand your very strange logic.

>The "fixed crosshair" feature should simply ensure that when the ocular is activated, the crosshair appears. That's all! If the user DOES want to remove it - even when the physical crosshair is permanent - just allow this! There is a reason why the user wants to remove that crosshair, let the user choose that reason.

If the user really DOES want to remove permanent crosshairs, then the user DO NOT enable this option.

>Is that so complicated?

Yes, because this is your synthetic problem, which is not a problem for all other users.

>For example... you impose a limitation on the user - such as "a fixed crosshair" cannot - even temporarily - be removed". OK, so IF you want to be consequent, THEN you should not allow a user to look through the Earth either ! Because that is not possible either, just as you cannot remove the crosshair ! But no - you DO allow looking below the horizon - because that is just a matter of disabling the landscape. This is what I mean with "let users do things that are physically impossible".

This is a very, very bad example because you propose to make the behaviour of crosshairs state over difficult to understand by generic users and add super complicated logic for it.

>Please stop talking about UFO and pink skies (the latter do exist) and astrology. You are mucking me, while this is a perfectly sound, clean issue with a simple and elegant solution that gives more freedom than just disabling the button.

This tool works as it was requested by users and your invention of the synthetic problem in the place where the problem does not exist is not a sufficient reason for overcomplicating the instrument.

**Comment by alex-w** [comment]
> Your proposal (copying) is a meagre workaround, because "copy-paste is evil" , remember? This also applies here.

Who exactly forbade you not to use permanent crosshairs in devices?

**Comment by axd1967** [comment]
I'm stopping this discussion because it leads nowhere, sorry.
