### ISSUE TITLE
ocular plugin: show FOV of currently selected ocular

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1248]
**Is your feature request related to a problem? Please describe.**
I want to have an idea what I will see through an ocular without having to switch to ocular view.

**Describe the solution you'd like**
Include a new FOV feature that tracks the currently selected ocular FOV, and can be toggled of/off.
The circle should appear above other FOV values (drawn later)

**Describe alternatives you've considered**
* Look up the FOV of the current ocular and change the circular FOV value
* Dial the ocular FOV value in a Telrad ring

**Additional context**

**Comment by alex-w** [comment]
Reason of reject: by the fact you are proposing to us to implement the secondary Ocular feature. Why do you not use enabling contour and semi-transparent background for eyepiece view to see what you will see outside the FOV? We also introduced the circular FOV feature into core with a super simple defining value of FOV.

**Comment by axd1967** [comment]
1. the transparency of the ocular is bad, almost unusable (remember #678) .
look at this screenshot:
![image](https://user-images.githubusercontent.com/3529789/92370751-00da8580-f0fb-11ea-84d5-a561e4cd6b3b.png)
compare with this:
![image](https://user-images.githubusercontent.com/3529789/92370786-0cc64780-f0fb-11ea-9cc0-e3e0877ee4e8.png)
2. the proposed feature prevents one from having to jump to ocular view all the time. AND it is dynamic - it tracks the currently selected ocular - this is something you can't do easily when manually modifying the FOV circle. in fact it is painful and **error-prone** - that's why we ask the computer to aid us.

software should aid the user, not make his life difficult!

so at least this issue should be left open for anyone wanting to implement it; technically it is not so difficult.
by closing this feature, you make a relatively good idea disappear. so please re-open this issue and put in in the **backlog**; some day, someone will implement it.

**Comment by gzotti** [comment]
There has been the optionally loaded Oculars plugin for ages, and a simple FoV circle in the main program in the most recent versions. The simple ocular circle feature does not read the optional plugin's data. 
You could also (ab)use the Telrad circles for a few FoV circles that give a hint about various FoVs. 
Just learn to use and understand the program. And read https://github.com/Stellarium/stellarium/wiki/FAQ#why-dont-you-implement for some insight why we don't feel obliged to implement or even keep open each of your ideas.

**Comment by axd1967** [comment]
> You could also (ab)use the Telrad circles for a few FoV circles that give a hint about various FoVs.

(Indeed. that's what I describe in the issue)

> Just learn to use and understand the program. 

@gzotti ... I think I can call myself an **advanced** Stellarium user. I have been learning and using the application for several years now.

> And read https://github.com/Stellarium/stellarium/wiki/FAQ#why-dont-you-implement for some insight why we don't feel obliged to implement or even keep open each of your ideas.

Don't worry, we all agree that all this is voluntary work, there is NEVER any obligation to do anything. This should be implied all the time, you don't need to remind me that.

But I stick to my point: this is a nice extra feature. However, as it is indeed linked to the **Ocular plugin**, it should be part of that module rather than end up in the Markings tab.

**Comment by alex-w** [comment]
> 1. the transparency of the ocular is bad, almost unusable (remember #678)

Of course it almost unusable because you just don't use semi-transparent background for eyepiece view.

**Comment by axd1967** [comment]
![image](https://user-images.githubusercontent.com/3529789/92995333-f78a5800-f502-11ea-85a7-a0968277a9c2.png)

**Comment by alex-w** [comment]
Please check 0.20.3RC2

**Comment by axd1967** [comment]
> Please check 0.20.3RC2

um... am I right that you added the transparency setting? 
![image](https://user-images.githubusercontent.com/3529789/94173267-fb6b9200-fe93-11ea-9aaa-a768dc69bedd.png)

that is nice, but this issue is about showing a new type of FOV that tracks the FOV of the currently selected ocular (and visible when NOT in ocular mode, of course).

**Comment by alex-w** [comment]
Oculars plugin may be not loaded or worse - he may be not included into binary package. What exactly you want to track in this case? At the moment Stellarium has 2 tools to show circled mask of FOV and you want to get a 3rd tool for same tasks - why?

**Comment by gzotti** [comment]
OP wants to show an ocular circle without zooming in to look through the ocular. This is pretty pointless IMHO. The program should remain usable and not be overloaded with hundreds of ways and combinations. In principle, implementation would best add another ocular-like button in the Oculars GUI that would show the ocular/telescope/lens GUI, but not zoom in and not show the ocular mask. Everything else would remain naked-eye. It may also be seen like a second Telrad mode, just with the Ocular interface, and no auto-zooming.

Just live with a 1° or 1/2° FOV circle from the main program and a bit of getting used to.

**Comment by axd1967** [comment]
> Oculars plugin may be not loaded or worse - he may be not included into binary package. 
> What exactly you want to track in this case? At the moment Stellarium has 2 tools to show circled mask of FOV and you want to get a 3rd tool for same tasks - why?

in case the plugin is not active, the option is simply not available - because it is part of the Ocular plugin.


the option should live in the Ocular interface, 

![image](https://user-images.githubusercontent.com/3529789/94175855-8c903800-fe97-11ea-9ca8-381001c0e3fa.png)

e.g. 
- an additional checkbox that says `always show FOV`, 
- or a dropdown "FOV:" with values `off` / `on` / `always` (where values off/on are the current behaviour)

where "always" means that the FOV of the currently selected ocular is also shown while ocular mode is not active.

the current circular FOV is fine as is, don't touch that.

remember: the use case is: I want to see the FOV without having to switch to ocular mode. (of course, if there is no ocular plugin, then this is meaningless).

**Comment by alex-w** [comment]
> In principle, implementation would best add another ocular-like button in the Oculars GUI that would show the ocular/telescope/lens GUI, but not zoom in and not show the ocular mask. Everything else would remain naked-eye. It may also be seen like a second Telrad mode, just with the Ocular interface, and no auto-zooming.

What about just disable option "Scale image circle"?
