### ISSUE TITLE
astrocalc - graph tab: include name of selected object in title

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1249]
**Is your feature request related to a problem? Please describe.**
The Graphs tab is not very user friendly. Where some other tabs take the currently selected object for output, the Graph tab forces the user to select an object. Because of this inconsequent behaviour, I am _often_ looking at the wrong graph.

**Describe the solution you'd like**
Include the name of the selected object in the title

_Note_: consider removing the dropbox and use the selected object, to make the UI more consistent and more easy to use. The dropbox is difficult to use because it does not allow to find an object by keyboard, so the user has to use the mouse to scroll down a lot. (this lack of keyboard detection in popup menus is very strange for Qt)

![image](https://user-images.githubusercontent.com/3529789/92112832-a8e80a00-edee-11ea-8ab4-13d4a269deca.png)

compare this with the other tabs:
![image](https://user-images.githubusercontent.com/3529789/92113170-388db880-edef-11ea-9663-56d056d9632a.png)
![image](https://user-images.githubusercontent.com/3529789/92113224-480d0180-edef-11ea-9f0b-d5b86162433b.png)
![image](https://user-images.githubusercontent.com/3529789/92113322-6f63ce80-edef-11ea-8a24-89618f4c51ed.png)

but there are more places that has this issue:
![image](https://user-images.githubusercontent.com/3529789/92113298-6541d000-edef-11ea-97fd-73a49cb0b0fa.png)

![image](https://user-images.githubusercontent.com/3529789/92113350-78ed3680-edef-11ea-972f-d1d2114ae411.png)

**Comment by alex-w** [comment]
Reason of reject: If you not see defined object (Celestial body) then adding name of defined object in other place will not help you. I do not understand also why you want to get an astronomical ravings for some tools in AstroCalc, e.g. why you want to see 2 horizontal lines for some star or DSO in Graphs tool or get an empty table for some star in Phenomena tool, or get an table with almost identical data in Ephemeris tool for DSO or star.

**Comment by axd1967** [comment]
this is very painful. if you don't understand the issue, please leave it open.

what is "an astronomical ravings"? what do you mean by "why you want to see 2 horizontal lines for some star or DSO in Graphs tool or get an empty table for some star in Phenomena tool, or get an table with almost identical data in Ephemeris tool for DSO or star" ? 

the core issue here is software ergonomy. all I'm asking is to add the title of the selected object! **that's all**. it is a trivial and helpful!

**Comment by alex-w** [comment]
> this is very painful. if you don't understand the issue, please leave it open.

Yes, I don't understand your issue, because I don't understand why you just ignore many parts of GUI. 

> what is "_an astronomical ravings_"? what do you mean by "_why you want to see 2 horizontal lines for some star or DSO in Graphs tool or get an empty table for some star in Phenomena tool, or get an table with almost identical data in Ephemeris tool for DSO or star_" ?

Please read your _Note_ and write the definitions of phase and phase angle for deep-sky objects and stars. Please explain how changes equatorial coordinates and heliocentric distance of DSO or stars by year. Please give us an example of conjunction of Polaris and Mars (for example).

> the core issue here is software ergonomy. all I'm asking is to add the title of the selected object! **that's all**. it is a trivial and helpful!

How many times should we write a name of the object for the state, when you will stop ignoring important parts of GUI? This is not "ergonomic" question.

**Comment by axd1967** [comment]
And the worst is that there IS ample space left!

![image](https://user-images.githubusercontent.com/3529789/96033285-2ed08980-0e60-11eb-92fe-151404182a64.png)

**Comment by gzotti** [comment]
There may be enough space on your (4k?) screen. Test on a 1024x768 as well! Nitpicking is incredibly easy. Better get your hands dirty, work out solutions and help fixing ~1 of those cosmetic issues per week!

**Comment by axd1967** [comment]
So I tried. See https://github.com/Stellarium/stellarium/pull/1326#issuecomment-719911052

**Comment by axd1967** [comment]
See also https://github.com/Stellarium/stellarium/issues/970#issuecomment-744480532

**Comment by axd1967** [comment]
bitten again by this issue: I wanted to see the monthly elevation graph of a planet, but didn't notice I had mis-clicked a comet instead. 

there is plenty of space in the graph to include the name of the currently selected object. instead, pixel space is wasted explaining to the user that an object has to be selected (and the user is never 100% sure the right one was selected, just by looking at the graph - this makes exporting such a graph problematic as the object name is not part of it)

![image](https://user-images.githubusercontent.com/3529789/118366117-b2da2380-b59f-11eb-9cc6-b28ad13f6ce7.png)



also, the Astrocalc dialog mixes two kinds of object selections:
- in some pages, the user has to select the object via a drop-down, which is a PITA because that drop-dwon has become _very_ large and is difficult to navigate (eg by typing some letters to filter it) (but the advantage is that the dialog then shows the currently selected object)
- in other pages, the user has to pre-select the object outside of the Astrocalc dialog (which is more intuitive, but allows for wrong manipulations)

**Comment by alex-w** [comment]
> bitten again by this issue: I wanted to see the monthly elevation graph of a planet, but didn't notice I had mis-clicked a comet instead.
> 
> there is plenty of space in the graph to include the name of the currently selected object. instead, pixel space is wasted explaining to the user that an object has to be selected (and the user is never 100% sure the right one was selected, just by looking at the graph - this makes exporting such a graph problematic as the object name is not part of it)

Ooooo, this is perfect example!!! All titles from graphs was removed by YOUR request and when I said that is bad you said "ergonomy", "bad usage of pixel space", etc. Enjoy the results and use tooltips!

**Comment by axd1967** [comment]
no @alex-w . I never asked to remove essential info. if you can show me where I asked this, I'm glad to review it.

**Comment by axd1967** [comment]
bitten again...

After checking the monthly elevation of C/2021 A1 ...

![image](https://user-images.githubusercontent.com/3529789/124086826-b9d6cb80-da51-11eb-9698-c713da4ddf9e.png)


I wanted to see its mag Graphs ...
![image](https://user-images.githubusercontent.com/3529789/124086895-c8bd7e00-da51-11eb-9c00-bc0bb7f32d98.png)


and then I realise that this UI uses a different selection method (look in the ... title).

ergonomy

**Comment by alex-w** [comment]
It's not an ergonomic, this is an idiotism!

**Comment by axd1967** [comment]
... fixed in f634a01db0, thank you.
