### ISSUE TITLE
*Reticulum System*  <=> PGC  3589 ?

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#1250]
https://github.com/Stellarium/stellarium/blob/956e2b80aca690d00f6d06c4937d061344cbca1c/nebulae/default/names.dat#L978

The name is from simbad, however it seems to be ESO 118-31 (Reticulum Dwarf Galaxy) rather than PGC  3589 (Sculptor Dwarf Galaxy).

http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Reticulum+System&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id

**Comment by alex-w** [comment]
Reticulum System != Reticulum Dwarf Galaxy

**Comment by sunshuwei** [comment]
![QQ图片20200907021950](https://user-images.githubusercontent.com/34102610/92332470-c21fdd80-f0b0-11ea-8f24-2d974873379e.png)
![QQ图片20200907022022](https://user-images.githubusercontent.com/34102610/92332478-cc41dc00-f0b0-11ea-898d-8736ff7710e3.png)

**Comment by alex-w** [comment]
And? All names are correct

**Comment by sunshuwei** [comment]
Reticulum System----ESO351-30, PGC3589 =Sculptor Dwarf Galaxy. Why is it located in Sculptor but is called Reticulum system?
