### ISSUE TITLE
Scrambled Graphics when Windowed non Full Screen

### ISSUE THREAD

**Issue by PeterZanette** [Stellarium/stellarium#1251]
I get a scrambled window when minimized to non full screen. For full screen is works well.
The latest Jun 2020 release was installed

![StellariumWindow](https://user-images.githubusercontent.com/70827840/92316943-dbe5f580-efc8-11ea-8a72-19f92a8e6d0f.png)

**Comment by alex-w** [comment]
Please check https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#OpenGL_problems_with_Intel_Graphics

**Comment by mtredway** [comment]
![2020-09-06](https://user-images.githubusercontent.com/61389747/92338094-ef9e6400-f07b-11ea-96f0-3f5d1dc7a535.png)
I am having the same problem

**Comment by gzotti** [comment]
For you and whoever else is having this problem, I repeat another time: please use ANGLE mode. It does not hurt performance noticeably.
