### ISSUE TITLE
String of stars on a streight line. Are they real?

### ISSUE THREAD

**Issue by dzach** [Stellarium/stellarium#1252]
### Expected Behaviour
Stars to be distributed rather more randomly. Initially I thought these where Starlink satellites, but no.
### Actual Behaviour
A picture is worth a thousand words:
![stellarium-003](https://user-images.githubusercontent.com/1109829/92327485-8ef63380-f049-11ea-9eb9-e12cb4fed6d7.png)
### Steps to reproduce
I have installed star catalogs `stars_4_1v0_2.cat`,  `stars_5_2v0_1.cat` and  `stars_6_2v0_1.cat`, from https://sourceforge.net/projects/stellarium/files/Extra-data-files.
As seen in the Info field, in the screenshot above, the string of stars lies around `16h32m15.41s/-26°26'31.6"`
### System
* Stellarium version: Stellarium 0.20.2 (Stellarium-0.20.2-x86_64.AppImage)
* Operating system: Kubuntu 18.04
* Graphics Card: Radeon HD 6530D, Radeon HD 4350
* Screen type: 2 X 1920x1080 (dual monitor)

**Comment by alex-w** [comment]
Doublicate of #1189
