### ISSUE TITLE
Wrong Starlink-1127 orbital data

### ISSUE THREAD

**Issue by dzach** [Stellarium/stellarium#1254]
Possibly not a Stellarium issue, but if so, just for the record.

### Expected Behaviour
Starlink satellites are expected to move at about the same speed.
### Actual Behaviour
Satellite Starlink-1127 moves around the globe at a rate of 1rev/25s, unrealistically faster than any other satellite.
### Steps to reproduce
1. Update satellite data
2. Make satellites visible
3. Search for Starlink-1127 and goto it.
4. Wait for at most 25" for it to come zooming into the screen. 
### System
* Stellarium version: Stellarium 0.20.2 (Stellarium-0.20.2-x86_64.AppImage)
* Operating system: Kubuntu 18.04
* Graphics Card: Radeon HD 6530D, Radeon HD 4350
* Screen type: 2 X 1920x1080 (dual monitor)

**Comment by alex-w** [comment]
I sent an email to Dr. Kelso

**Comment by alex-w** [comment]
Dr. Kelso said that Starlink-1127 had the data over 10 days old (last update Aug 28). This result appears to be a combination of factors, but it is likely the result of STARLINK-1127 performing some kind of maneuver and then not getting updated by SpaceX for some reason. At the moment Dr. Kelso deleted the input ephemeris for Starlink-1127, which will prevent CelesTrak generating SupTLEs until receiving new data again.

**Comment by alex-w** [comment]
The issue will not fix because this is not Stellarium issue

**Comment by dzach** [comment]
Thinking of ways to work around such problems, maybe a possible solution would be to create a black-list for objects that have ambiguous / wrong data coming from sources outside the Stellarium project and are difficult to fix, like this one.
