### ISSUE TITLE
Question about functionality

### ISSUE THREAD

**Issue by kenyac** [Stellarium/stellarium#1256]
Hi,
 
I'm looking to use this instead of Starry Night for a university course. The professor asked if I know offhand if it is possible to zoom in on the planet Jupiter and see the real-time position of its four major moons, and watch how they change as the time of observation is quickly advanced. Apparently this functionality is important and I would like to confirm it exists.

Thank you

**Comment by gzotti** [comment]
Yes, it does. About its accuracy, see #222 .
