### ISSUE TITLE
Scale minor bodies resets when ocular has been used

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1258]
The "Scale minor bodies" resets when ocular is being used. I guess this is not a feature, but a bug.

Steps to reproduce:
1. Go to Jupiter.
2. Turn on "Scale minor bodies". Jupiter's moons get big.
3. Use the ocular plugin.
4. Now, all moons will have their original sizes, and the checkbox "Scale minor bodies" is unchecked.

**Comment by gzotti** [comment]
I rather guess this is intended behaviour!

When you observe through a particular ocular/telescope combination, you want to see the object under real conditions. When just zooming in, you can have them larger. Of course, when exiting the ocular view, the previous setting should be restored. For me it does not make sense to simulate the view onto a blown-up moon.

**Comment by Atque** [comment]
@gzotti That is exactly how the "scale moon" feature behaves, and how the "Scale minor bodies" should behave, but the minor bodies do not return to scaled size once zoomed out.

**Comment by gzotti** [comment]
Oops, yes, the reset line is missing.
