### ISSUE TITLE
Stellarium 0.18.0 and DSO catalog 3.3 extended edition

### ISSUE THREAD

**Issue by OAStubby** [Stellarium/stellarium#126]
As indicated on the user guide I downloaded version 3.3 but this is not loaded, in the log the error reported is that version 3.4 is required.

When will it be available?

Tanks.

OAStubby

**Comment by alex-w** [comment]
Please download extended edition of DSO catalog version 3.4: https://github.com/Stellarium/stellarium-data/releases/tag/dso-3.4

Thanks for report and sorry for delay to uploading new version of DSO catalog.

**Comment by OAStubby** [comment]
Thank you for your attention and for the quick solution of the problem.

OAStubby
