### ISSUE TITLE
Wrong Jupiter rendering

### ISSUE THREAD

**Issue by luisfl** [Stellarium/stellarium#1261]
I'm not sure if this is actually a bug, sorry if it is not.

I took some shoots of Jupiter yesterday, and Stellarium showed a wrong rendering of the surface: the Big Red Spot was in the wrong side of the planet.

I am attaching a screenshot of SkyCharts, that agrees with my picture of Jupiter, with the BRS closer to Io than Europa. It seems the image of Jupiter showed by Stellarium is one hour early (yes, the time is correct in Stellarium, set as "System date and time"). Maybe a DST related issue? The images correspond to Sep 10, 2020 22:57 at Rio de Janeiro.

### Expected Behaviour

Rendering closer to reality.

### Actual Behaviour

This is skychart correct rendering:

![skychart_200911112737](https://user-images.githubusercontent.com/15525268/92951082-2e456d00-f434-11ea-8451-105edb0dc67e.jpg)

This is Stellarium rendering (observe the BRS):

![stellarium_200911112831](https://user-images.githubusercontent.com/15525268/92951085-2ede0380-f434-11ea-8bde-f7489eeffc7b.jpg)

This is my own picture:

![JupiterEuropaIo_EyepieceProjection-9 7mm_JN-200910-B+LX90_47170b](https://user-images.githubusercontent.com/15525268/92952422-50d88580-f436-11ea-996a-03382c540192.jpg)

### Steps to reproduce

Just zoom at Jupiter at  Sep 10, 2020 22:57, Rio de Janeiro.

### System
* Stellarium version: stellarium-0.20.2-1.fc32.x86_64
* Operating system: Fedora Core 32 fully updated

**Comment by alex-w** [comment]
Please check the longitude of GPS in both programs

**Comment by gzotti** [comment]
You say it may be a DST issue, and name a time 22:57 without giving a decisive detail. What is your exact setting for location, timezone, DST setting? (All on the location panel)

**Comment by luisfl** [comment]
As I wrote, I am at Rio de Janeiro (UTC -3):
S 22° 57' 13.39"
W 43° 11' 53.97"
Elevation 50m
We are in Winter, so no DST for Rio de Janeiro.

Attaching a screenshot with the status line.
![MyScreenshot_200911_202551](https://user-images.githubusercontent.com/15525268/92980580-2f46c080-f46d-11ea-8b0f-fa1d588781d3.jpg)

**Comment by alex-w** [comment]
Please show screenshot of SSO tab

**Comment by gzotti** [comment]
Not a DST error, "1 hour offset" is just by chance. It is really a problem even with correct custom longitude. Probably the position of the GRS in the texture has to be corrected differently, or some multiple of 90° added, I have to figure that out. Compare a few online photos given in the code.

**Comment by luisfl** [comment]
> Please show screenshot of SSO tab

![MyScreenshot_200912_093520](https://user-images.githubusercontent.com/15525268/92995618-6784e800-f4db-11ea-9de4-715af988447d.jpg)

**Comment by gzotti** [comment]
OK. @luisfl you can use the "Use custom settings of GRS" to adjust GRS longitude. I admit the number is not correct currently. Use something around 260° with today's date, not 340 as would be correct.

**Comment by luisfl** [comment]
> OK. @luisfl you can use the "Use custom settings of GRS" to adjust GRS longitude. I admit the number is not correct currently. Use something around 260° with today's date, not 340 as would be correct.

Unless there is something more besides the Jupiter surface rendering, like, e.g., the satellites positions, it is not a serious bug of course, at all. It is a bug of the lowest importance. Just wanted to report it.

**Comment by gzotti** [comment]
Yes, thank you. Still wrong enough to need a fix, although with the workaround, we can "hide" it for a while. I had thought it was fixed 2 years ago, but either something has changed since then, or it worked in 2018 rather by chance but drifted away again? Have to inquire deeper, but better not today.

**Comment by luisfl** [comment]
> Please check the latest stable version of Stellarium:
> https://github.com/Stellarium/stellarium/releases/latest

Appimage giving tons of Fontconfig errors, warnings, and libQt5XcbQpa.so (Fedora 33 fully updated). 
I will wait to check the RPMs.
