### ISSUE TITLE
Ability to change the scale of all planets not just the Moon

### ISSUE THREAD

**Issue by gshirleyUSA** [Stellarium/stellarium#1263]
l would love to have the ability to change the scale of all of the planets like is already available for the Moon in the "Solar System Objects" window.  I'm not an astronomer, I just fell in love with this program. It is incredibly beautiful and a testimony to God's creation.

**Comment by alex-w** [comment]
Why you need it? Could you describe use cases?

**Comment by gzotti** [comment]
The obvious use case is visualization with the Solar System Observer.  Here you could blow up the planets 20-500x (?) to make them more apparent. (Would we also have to blow up the moon orbits then to avoid collisions?) There are however online services which do that already for nice views. It may make sense at some later date when the "observers" will be finalized with working gimbal control.

**Comment by gshirleyUSA** [comment]
I’m sorry to bother you guys, I don’t really need it.  I’m just addicted to watching the stars and planets move across the screen.  I just thought it would be nice to see the planets as larger graphics, not in relation to the other planets, moon, stars, etc.  but purely aesthetic. I am aware that I can zoom in on the planets but thought it would be nice to see the nice graphics without having to zoom in.  I’m not doing any research or anything, I just love Stellarium for the beauty of it.  Don’t even give my original request a second thought.  I do appreciate you guys responding though.

**Comment by sureshsaragadam** [comment]
Ability to change the scale of all planets not just the Moon #1263, 

I too need to pseudo scale of the planets just like stellarium working with moon, (Not to the maximum scaling but should make difference in the visual differentiating other stars) No big difference adds in scaling the planets but simply making the visual more appealing to the screen so we can figure out the difference in other stars and our solar system planets and feel more comfortable.

![Screenshot_2021-01-16_16-14-22](https://user-images.githubusercontent.com/47267790/104809826-16cd2500-5816-11eb-95c3-ffdccf95da7c.png)

In the above picture the plants are just like ordinary stars, If we pseudo scale the planets, The above picture will me more appealing. I request this feature is added in stellarium.

**Comment by gzotti** [comment]
@sureshsaragadam it is fully clear what you want and how this will look like. Just that we have daytime jobs... Be more patient.

**Comment by gshirleyUSA** [comment]
Fantastic!  You guys are incredible!
