### ISSUE TITLE
Missing checksums for 0.20.2 release

### ISSUE THREAD

**Issue by tvataire** [Stellarium/stellarium#1264]
Some checksums are missing for 0.20.2 release (stellarium-0.20.2-win32.exe, stellarium-0.20.2-win64.exe and Stellarium-0.20.2.zip), whereas they are provided for previous releases.

**Comment by alex-w** [comment]
The windows and macos packages are signed and I didn‘t publish checksums for it. Is publication of checksums really need for signed packages?

**Comment by tvataire** [comment]
Hello,
Checksums allow to detect errors that may have been introduced during file transmission or its storage.
It an essential tool to make certain that the downloaded file is identical to the sever-side one.
Regards.

**Comment by alex-w** [comment]
OK, I'll publish checksums for release 0.20.3 (we planning it around this weekend)
