### ISSUE TITLE
include regions as bookmark objects

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1267]
**Is your feature request related to a problem? Please describe.**
Every time I bookmark a region, I end up with a star and lose the context why the object was bookmarked.

**Describe the solution you'd like**
Include regions as bookmarks

**Describe alternatives you've considered**
-

**Additional context**
Current behaviour: after selecting e.g. Scutum Star Cloud, this is bookmarked as "Unnamed star"
![image](https://user-images.githubusercontent.com/3529789/93115168-d6b93280-f6bb-11ea-944a-895353013c55.png)

Notice also Rotanev, which I bookmarked to mark Del. In short, anything that can be found in the search dialog should be bookmarkable under that name. This sounds less easy to do, as the underlying implementation possibly associates central stars to constellations, and those stars end up as a bookmark instead.

**Comment by alex-w** [comment]
Please check 0.20.3RC2

**Comment by axd1967** [comment]
Works like a charm, thanks!
