### ISSUE TITLE
V20.2 Fails to start Telescope/EQMOD

### ISSUE THREAD

**Issue by RobertLVV** [Stellarium/stellarium#1269]
V20.1 which I have reverted back to works fine but V20.2 Fails to start telescope via EQMOD/ASCOM. The Start Telescope check box is "grayed" out and no telescope marker/reticle is displayed on Stellarium Screen. I am not using StellariumScope as it was not needed with V20.1. All my settings are the same between the two versions. I am also using ASCOM 6.4 presently.  This is under Windows 10 Pro (64bit)  using an Atlas AZ/EQ-G Pro mount (Synta). I reported this some time ago on the original bug reporting site  Ubuntu #1888970 and have seen others mention this issue as well so it's not just me. This worked and continues to work perfect with version 20.1

Robert

**Comment by gzotti** [comment]
Duplicate. Please follow up in #1164. 
BTW this here is the current original bug reporting site.

**Comment by alex-w** [comment]
Please check 0.20.3RC2
