### ISSUE TITLE
Astrocalc: WUT screen 'Show objects which are up' filter not working correctly

### ISSUE THREAD

**Issue by mikenoname-github** [Stellarium/stellarium#1270]
### Expected Behaviour

When "In the evening" is selected I would expect to see things that are up between sunset and midnight. When "In the morning" is selected I would expect to see things that are up between midnight and sunrise.

### Actual Behaviour

What I am actually getting when I select "In the evening" are correct items mixed in with a whole bunch of other items that rise after midnight and set either later in the morning or the next afternoon, neither of which I should be seeing.

When I select "In the morning" I am seeing correct items along with items that rise after sunset and set later in the day or in the evening.

### System
* Stellarium version: 20.2
* Operating system: Windows 10 Pro
* Graphics Card: AMD

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Please share your location settings

**Comment by mikenoname-github** [comment]
![StellariumLocationSettings](https://user-images.githubusercontent.com/71414112/93514720-663d2c00-f8dc-11ea-9efd-232e2445c5fb.jpg)

Hopefully I attached it right. GitHub chat is very strange

**Comment by alex-w** [comment]
Thanks for screenshot! Could you check 0.20.3RC2 also?

**Comment by mikenoname-github** [comment]
Just installed 'stellarium-0.20.2.18252-win64.exe' and the problem is fixed!

Sorry, I checked the bug reports but didn't see that it was fixed recently.

Thanks, Alex!
