### ISSUE TITLE
Aberration of light

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1272]
A small positional inaccuracy is caused by not properly dealing with aberration of light. This definitely ruins accuracy with the beginnings of the seasons and may also cause issues with lunar occultations. Correction will require warping transformation matrices similar to what has been done for refraction. For demonstrations of the effect it should be possible to exaggerate it.

**Comment by gzotti** [comment]
Note that a recent typofix in the nutation matrix (submitted by an attentive user!) fixed the season times. However, I don't know ATM what causes the tens of seconds error for lunar occultations. There is a small figure mismatch for the Moon which we also don't model. In any case, Aberration correction is IMO one of the 2 stopping requirements for 1.0 (the other being planet axes).
