### ISSUE TITLE
Indian skyculture - native planet names beyond Saturn

### ISSUE THREAD

**Issue by vvasuki** [Stellarium/stellarium#1274]
Dr B S Shylaja of Bengaluru Planetarium https://www.taralaya.org/  reports: "Hindi texts translate Uranus as Varuna and Neptune as Yama." 

Regarding the translation of Uranus as varuNa - true, in olden times, hindu astronomical tradition was not aware of the existence of that planet - but the translation is useful and a very good one (from the comparative linguistics/ mythological perspective). Uranus/ Greek Ouranos and varuNa are indeed cognate; and we need a sanskritized name to talk about that planet in our languages (including sanskrit). But I am as unhappy with the translation of Neptune as Yama - wonder what the basis of that is. 

 We need to continue and refine/ correct the work of pioneers such as raghuvIra (who translated neptune as varuNa in his "The Consolidated Great English-indian Dictionary Of Technical Terms" https://archive.org/details/in.ernet.dli.2015.210535/page/n693/mode/2up ).

**Comment by gzotti** [comment]
@vvasuki This question must be solved by the community of Hindi speakers or adherents of the Indian skyculture. You can propose an updated translation on Transifex or updated skyculture description. The two of us are not able to solve it.

**Comment by vvasuki** [comment]
Got it - thanks!
