### ISSUE TITLE
script shortcuts do not run

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1275]
So... I try the Alt+G thing (and ALt+g, etc), but that doesn't trigger the script. Note that the script works fine. 

What am I doing wrong?

![image](https://user-images.githubusercontent.com/3529789/93002421-3e924080-f537-11ea-9fce-712802262418.png)

_Originally posted by @axd1967 in https://github.com/Stellarium/stellarium/issues/995#issuecomment-691528421_

**Comment by alex-w** [comment]
I've cannot reproduce the issue - both surveys works as expected

**Comment by alex-w** [comment]
Please attach your script

**Comment by axd1967** [comment]
```
//
// Name: Advance ISS passage
// Author: AD
// License: Public Domain
// Version: 0.1
// Shortcut: Ctrl+E
// Description: 
//

core.setDate("+92.98 minute")

**Comment by alex-w** [comment]
Who will fix the typo? ;)

**Comment by axd1967** [comment]
please help me instead of posing riddles? the script is running fine, so the typo seems to be in the key designation?

**Comment by alex-w** [comment]
Ctrl+E is working for me in release and in master

**Comment by axd1967** [comment]
now I know why it doesn't work.

the script must reside in `share/stellarium/scripts/` - I think only those scripts are scanned for the shortcut, not the scripts that are created via the editor.

https://github.com/Stellarium/stellarium/blob/bb6d6141857a335aec42faa5d413bb1cbfed3c70/src/scripting/StelScriptMgr.cpp#L367

**Comment by gzotti** [comment]
Presumably, the list of scripts is evaluated and shortcuts extracted only at startup. I expect that also user-created scripts in the right subdirectory of your user data directory should work.

**Comment by alex-w** [comment]
For each script from ~/.stellarium/scripts shortcuts works as expected

**Comment by axd1967** [comment]
that was it, confirmed!
todo
- add  user script directory path to the user guide, 5.2; 
- explain in 16.5.1 that the shortcut only works for those scripts
