### ISSUE TITLE
DSS Red and Color Will Not Work

### ISSUE THREAD

**Issue by krex51** [Stellarium/stellarium#1276]
When I select the DSS Color or DSS Red surveys, it starts downloading and the download bar flickers a bunch and i have to zoom in and out very fast to see the progress. I left Stellarium open for over 3 hours and it was in the same spot of the download. How do I get them to work?

**Comment by gzotti** [comment]
Some surveys seem to have problems. They are provided by the scientific community and are out of our hands. 
Note that DSS can also be seen if you enable the older style DSS mode.

**Comment by krex51** [comment]
Even with surveys that aren't DSS it just sticks on "Loading Nebulae" for hours.

**Comment by alex-w** [comment]
I've cannot reproduce the issue - both surveys works as expected

**Comment by alex-w** [comment]
@krex51 please check version 0.20.3RC2

**Comment by krex51** [comment]
Is 0.20.3RC2 released yet? I don't see the download.

**Comment by alex-w** [comment]
https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by krex51** [comment]
I will try it and let you know.

**Comment by krex51** [comment]
Is it normal for the download progress bar in the bottom right to flicker? I have to zoom in and out very quickly in order to check its progress.

**Comment by alex-w** [comment]
> Is it normal for the download progress bar in the bottom right to flicker?

Yes, this is normal behavior. The visibility of progress bar is dependent on speed of internet connection.

**Comment by krex51** [comment]
I will let it download overnight and see if it is still in the same place. Does that sound good?

**Comment by krex51** [comment]
It still didn't work. My internet is 100+ mbps so I don't think that's an issue.

**Comment by alex-w** [comment]
@gzotti are you really can reproduce the issue?

**Comment by gzotti** [comment]
Yes, I see occasional issues with *some* surveys. I have not found a systematic error, many work flawlessly. I don't know what happens here, maybe the HiPS format has evolved?

**Comment by axd1967** [comment]
Isn't the slow download related to @krex51 maybe having a large FOV?

**Comment by krex51** [comment]
Do you mean my image frame is large or im zoomed out?

**Comment by axd1967** [comment]
> Do you mean my image frame is large or im zoomed out?

what is your FOV while you are using a survey?

**Comment by krex51** [comment]
I mean I normally want the survey to be showing constantly, but I just tried with an FOV of 4 degrees and let it sit there for a minute and it didn't do anything.

**Comment by alex-w** [comment]
@krex51 in right side of GUI you may find URL of data source for selected survey - please try open it in browser and say us what's happening?

**Comment by krex51** [comment]
"Notice: Around the end of September 2020, archive.stsci.edu will begin using HTTPS exclusively. read more"

**Comment by alex-w** [comment]
> "Notice: Around the end of September 2020, archive.stsci.edu will begin using HTTPS exclusively. read more"

Please see **hips_service_url** parameter

**Comment by krex51** [comment]
hips_service_url https://data.stellarium.org/surveys/dss

**Comment by krex51** [comment]
The second DSS Color says this:  hips_service_url http://alasky.u-strasbg.fr/DSS/DSSColor

**Comment by krex51** [comment]
It still doesn't work so I don't think its my WiFi that is the issue. I'm not sure how to continue though.

**Comment by axd1967** [comment]
The first DSS is indeed not working. Also, the URL goes 
![image](https://user-images.githubusercontent.com/3529789/95029675-2c28a400-06aa-11eb-90ef-a9ce6f307775.png)

maybe the duplicate stems from the use of two master sources that both contain an almost identical datafile:

https://github.com/Stellarium/stellarium/blob/f5a720208dc1a789e7d982c43af7f3873a2d6e56/src/core/modules/HipsMgr.cpp#L104-L105

both sources contain "DSS colored" sections. maybe https://data.stellarium.org/surveys/hipslist needs to be updated?

**Comment by krex51** [comment]
So just don't use the survey?

**Comment by axd1967** [comment]
> So just don't use the survey?

I'm not sure, but I think it is a useless duplicate. the metadata look identical (I did not check all fields). @alex-w  or @gzotti  have to confirm this.

**Comment by krex51** [comment]
I've also tried 3 other surveys, and it looks like the same thing is happening. I checked Task Manager as well, and my computer is only using about 8-16kbps of my internet, so I'm not even sure if it is downloading.

**Comment by alex-w** [comment]
@krex51 please attach log.txt from your Stellarium

**Comment by krex51** [comment]
I solved the problem using the issue that @axd1967 mentioned. It was just a setting. I apologize for wasting all of your time.

**Comment by alex-w** [comment]
Please check version 0.20.3-4b8e7fd1c8: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
