### ISSUE TITLE
Stellarium 0.18 not working after successful installation.

### ISSUE THREAD

**Issue by HDFLHRI** [Stellarium/stellarium#128]
Hi, I have downloaded Stellarium a number of times, which works fine after initial installation, but for some reason it will not load, shows an error message that says windows is trying to find a solution and then closes. I used to get the same issues with version 0.17.
I am using 64 bit Windows 7 Home Premium.
Is there a fix in existence?

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/FAQ#Reporting_a_crash

So far we know you are using 64 bit Windows 7 Home Premium and tried versions 0.17 and 0.18.

**Comment by gzotti** [comment]
Timeout.
