### ISSUE TITLE
Stuttering on go to (ASCOM)

### ISSUE THREAD

**Issue by joenightsky** [Stellarium/stellarium#1280]
I use an ioptron cem60  with stellarium  every time  I do control 1 to go to the selected object it stutters three or four times and then sloughs perfectly to the object

**Comment by gzotti** [comment]
How do you connect it? Does it work with other programs?

**Comment by joenightsky** [comment]
With a new usb to rj cord it does it with my old cord as well

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gzotti** [comment]
What keys or options do you select in Stellarium's GUI to connect it after establishing physical connection with some cable? What protocol do you select? (I don't know what a cem60 is.)

**Comment by joenightsky** [comment]
A ioptron CEM-60 MOUNT   ascom-   J2000

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gzotti** [comment]
OK, ASCOM. 

Second part of the first question repeated: Does it work well with other programs that controls the telescope with the ASCOM protocol?

**Comment by joenightsky** [comment]
Yes it does

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by joenightsky** [comment]
It works fine with my remote pc

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by joenightsky** [comment]
Well I payed for stellarium as everyone should
I will keep it on my laptop but I will no longer use it to control my but thank you
I went with the asiair pro

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gzotti** [comment]
I mark this as duplicate of #2635, which is more complete.
