### ISSUE TITLE
Changing location Elevation makes no general difference to horizon

### ISSUE THREAD

**Issue by duderoony** [Stellarium/stellarium#1281]
Hi
using stellarium 20.2

when i change the elevation of the location the horizon view does not change.
.... except if i put in an extreme value of say 100,000 meters when the atmosphere disappears during daylight and the stars become visible. 
There is a slight change in the moon.

Astronomically speaking something more should happen? 

I realise that elevation at the location can mean 2 possibilities.
(a)       the observer is on an elevation spike and the horizon is unchanged (ie sea level)
(b )      the observer is on a plateau that extends in all directions far enough to have the horizon at the same elevation.

if (a) then topographic horizon changes could be considerable even without atmospherics.
if (b) then this would not even be an added variation to the ellipsoid versus spherical earth, since the horizon is changed the same in all directions? Also atmospherics are user defined and therefore unchanged by elevation.

I did notice a slight change in the moon position near horizon, (presumably parallax?)

Is location elevation thus (b), and therefore rising and settings of fairly distant objects (sun, planets, stars)  are unchanged, both for atmospherics and non atmospherics? 

I am trying to predict solar/lunar/planetary rising and setting for various locations, were elevation relative to the horizon is important. Even if 'elevation' was relative to the horizon (at sea level), this would be useful since parallax is negligible for most elevations, even with the moon.

I loaded version stellarium 12 and it seemed the same. 
I don't know if this is a bug or a facility issue.

regards

**Comment by gzotti** [comment]
Last answered in #1117
The landscape panorama is linked to the location. Raising elevation will not lower the landscape, unless you create a 3D scenery and use the 3D motion interface.
