### ISSUE TITLE
Double Stars: discoverer’s original designation

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#1282]
Many double star observations offer a kind of discoverer’s original designation format like Σ3050, Δ247 and h5390. However they are not be included in Software or Simbad Searching results. How about append built-in map data in searching list?

refer: _THE CAMBRIDGE DOUBLE STAR ATLAS_

**Comment by alex-w** [comment]
I believe SIMBAD using modern designation for those stars (according to THE CAMBRIDGE DOUBLE STAR ATLAS) - are you tried using STF 3050 for search as example?

**Comment by alex-w** [comment]
I think we may include these designations, but... could you prepare associative list from Appendix A of THE CAMBRIDGE DOUBLE STAR ATLAS: Catalog ID -> HIP number (not HD or SAO!)?

**Comment by ultrapre** [comment]
> I think we may include these designations, but... could you prepare associative list from Appendix A of THE CAMBRIDGE DOUBLE STAR ATLAS: Catalog ID -> HIP number (not HD or SAO!)?

I have a spreadsheets owning 2610 stars [Catalog ID->SAO], how about trying to convert HIP ?

**Comment by alex-w** [comment]
Please attach spreadsheets

**Comment by ultrapre** [comment]
> I believe SIMBAD using modern designation for those stars (according to THE CAMBRIDGE DOUBLE STAR ATLAS) - are you tried using STF 3050 for search as example?

WDS code Search also seems to be unavailable.

**Comment by ultrapre** [comment]
> Please attach spreadsheets

https://github.com/ultrapre/DeepSkyCatalogs/blob/master/DoubleStar/double_star_atlas_data_spreadsheets_070929.xls

**Comment by alex-w** [comment]
> WDS code Search also seems to be unavailable.

Please start typing WDS Jxxxxxxxx

**Comment by alex-w** [comment]
Please check version 0.20.3-4b8e7fd1c8: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by ultrapre** [comment]
> Please check version 0.20.3-4b8e7fd1c8: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

The data is well solved, thanks.
However I find a problem, the double stars with prefixes like '∑' and 'Δ' will occupy the searching box result before the Bayer Name of stars. Is that any way to distinguish the Case of Greek letters in the searching function ?

**Comment by alex-w** [comment]
Please check version 0.20.3-5f954765e3: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
