### ISSUE TITLE
Exoplanets plugin: star-with-exo-planet jumps on screen

### ISSUE THREAD

**Issue by erwindon** [Stellarium/stellarium#1286]
### Expected Behaviour
Star with exo-planets has a stable position on screen.
These are represented as as small green circle about half the size of the regular selection marker.

### Actual Behaviour
The green marker jumps a few times per second.
All other objects (stars/nebulas/galaxies/etc) do not have this effect.

### Steps to reproduce
Make stars with exo-planets visible.
Select a star with exo-planets.
Use Centre-on-selected-object so that it should stay in the centre of the screen.
Use FOV lower than about 73, or the star will not be shown.
Use FOV lower than about 5, or the star will obscure its marker.
This happens for all stars with exoplanets (at least for the 25 that I tried).

### System
* Stellarium version: stellarium-0.20.3-win64.exe
* Operating system: Windows 10
* Graphics Card: NVIDIA GeForce GTX 1050 Ti
* Screen type (if applicable): 1920x1080, no scaling

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/5288597/log.txt)

**Comment by gzotti** [comment]
Oops, my fault!

**Comment by alex-w** [comment]
Please check version 0.20.3-975ac97479: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by erwindon** [comment]
The effect has been solved for the exo-planet markers.
But it has not been solved for the exo-planet labels that go with it. Actually that applies to all object labels, not only exo-planets. I see the same effect on exo-planet names, star-names, planet-names, cluster-names, etc.

**Comment by alex-w** [comment]
I cannot reproduce the issue for any labels on linux. @gzotti could you check it on windows?

**Comment by gzotti** [comment]
Cannot reproduce jitter on Windows. 
Exoplanet Icons in current master are solid after this fix. Labels never shook.
Stellarium in WSL/Ubuntu 18.04.5 + Xming has version 0.20.3 with jittering icons (this bug), but solid labels. 
Zooming in to and locking on some object will make stars to slightly jitter. This is in fact numerical rounding, but also looks like atmospheric jitter, so not too bad either. 
As time goes by, of course labels will occasionally also jump by a pixel.

**Comment by erwindon** [comment]
I still clearly see the same effect as I originally noticed on the exo-planets.
The attachment has a (partial) screen recording of 2 planets and their labels from tonight's sky.
The planets and the surrounding stars are visually stable. The labels are jumpy. Also jumpy relative to their corresponding object.
Don't lock on the object, just use a FOV that has a relatively stable view, in my case fov=60
[stellarium.zip](https://github.com/Stellarium/stellarium/files/5323548/stellarium.zip)
The title-bar mentions the just downloaded version "Stellarium 0.20.3-975ac97479 [HEAD]".

**Comment by gzotti** [comment]
Exactly:

> As time goes by, of course labels will occasionally also jump by a pixel.

My oldest version to compare is 0.12.9. Showing exactly the same. Labels move by full pixels.
