### ISSUE TITLE
Stellarium v0.20.3 doesn't start on macOS Catalina 10.15.6 (19G2021)

### ISSUE THREAD

**Issue by martignoni** [Stellarium/stellarium#1287]
### Expected Behaviour

Stellarium launches without error when double-clicked on.

### Actual Behaviour

Stellarium does not start. A error dialog prints "Impossible to open Stellarium application." (See screenshot)
<img width="532" alt="Stellarium-error" src="https://user-images.githubusercontent.com/421392/94370394-176b6f80-00f0-11eb-94f3-4aff56dff596.png">

### Steps to reproduce

1. Download Stellarium v0.20.3 (https://github.com/Stellarium/stellarium/releases/download/v0.20.3/Stellarium-0.20.3.zip)
1. Unzip downloaded file
1. Double-click on Stellarium icon
1. Observe error dialog

### System
* Stellarium version: v0.20.3
* Operating system: macOS Catalina 10.15.6 (19G2021)
* Graphics Card: Radeon Pro 580X 8 Go
* Screen type (if applicable): 27'' (5120 x 2880)

### Logfile 
No logfile is produced.

### Additional note

Self compiled version 0.20.3-717f8caf38 [master] starts correctly.

**Comment by gzotti** [comment]
What happens when you click the question mark?

**Comment by martignoni** [comment]
Standard macOS help window opens with no content.

**Comment by chacha21** [comment]
I have not checked deeply, but the Stellarium.app/Contents/MacOS contains a "stellarium" file (instead of "Stellarium") which does not even have the "x" Unix flag.
Setting the "x" flag (chmod a+x) manually does not help, since code signing considers that as a change.
The packaging workflow for MacOS must be broken

**Comment by alex-w** [comment]
Cannot reproduce issue

**Comment by Hood-fr** [comment]
Here I cannot manage to unzip the 20.3 archive. Default unzipper will generate an error, and the Unarchiver.app manage to unzip but then the app is considered corrupt and will not launch.

Stellarium version: v0.20.3
iMac late 2015
Operating system: macOS Catalina 10.14.6 (19G2021)
Graphics Card: Radeon 395X 4 Go
Screen type (if applicable): 27'' (5120 x 2880)

**Comment by alex-w** [comment]
Please share hash of zip-archive (md5, sha1 or sha256)

**Comment by Hood-fr** [comment]
MD5 = a4c59fb4d6392293e7e4de8c6ee20b98

**Comment by chacha21** [comment]
MD5 = a4c59fb4d6392293e7e4de8c6ee20b98

**Comment by alex-w** [comment]
Please try https://github.com/Stellarium/stellarium/releases/download/v0.20.3/Stellarium-0.20.3.1.zip

**Comment by Hood-fr** [comment]
Works fine for me ! 👍 👍  Kudos to your reactivity to users' issues !

**Comment by alex-w** [comment]
OK, thanks for feedback! I've updated links for packages on stellarium.org

**Comment by martignoni** [comment]
> Please try https://github.com/Stellarium/stellarium/releases/download/v0.20.3/Stellarium-0.20.3.1.zip

Works OK for me too. Thanks.
