### ISSUE TITLE
More ephemeris steps possibilities in AstroCalc

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1289]
Thanks for this improvement. Would it be possible in future version to have either :
- decimals value instead of integer
- more than 4 digits
- a yy:dd:hh:mm:ss format

I am trying to plot moon analemma and I require to have a step value of 1490.5 minutes (a tidal day), or 43225min (29 tidal days) and I cannot enter such values. Having either of the 3 proposed formats would enable me to do so. Thanks in advance

__Originally posted by @Hood-fr in https://github.com/Stellarium/stellarium/issues/1176#issuecomment-699668673__

**Comment by axd1967** [comment]
@alex-w @Hood-fr at first sight it is not possible to enter fractional values (e.g. 1.4) - the input does not accept '.'
