### ISSUE TITLE
default confirmation dialog should put focus on "No"/ cancel option

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1292]
**Is your feature request related to a problem? Please describe.**
When triggering the confirmation dialog (#1277), the user might inadvertently lose data after all by hitting Enter/Spacebar. The intention of the dialog is to prevent accidental operations by forcing the user to choose a different option.

**Describe the solution you'd like**
Put the focus on the "No" button.

![image](https://user-images.githubusercontent.com/3529789/94461949-16ebdb00-01bb-11eb-8033-a3cdbc08bb6e.png)

Note that the current default is a bit darker (in this case the "Yes" button); this is dangerous.

**Comment by alex-w** [comment]
Alex, do you really think that all our users idiots and cannot read the simple question? Or you just confirm, that nobody reading these warning dialogs and all of them pressed the OK button by silence?

**Comment by axd1967** [comment]
First of all, I am not referring to all users, neither do I call them idiots. I do know that users should be protected against their mistakes, they are human. And I do know about ergonomy. And user friendliness. And you must be aware that keyboards can emit stray characters: and the ENTER and SPACEBAR keys are large and can easily be hit by mistake.

So, the problem is that keyboard users are quick but can make mistakes. By implementing this (trivial) issue, the user must make TWO distinct, separate actions to confirm a DESTRUCTIVE action (tab or arrow, then ENTER or spacebar; mouse users don't have this issue). Another example: a user can move the focus to a delete button, then hit ENTER or SPACEBAR ... twice. And then discover that (s)he accidentally hit the confirmation button.

here is some random literature on UX development.

1. https://www.nngroup.com/articles/confirmation-dialog/
2. https://ux.stackexchange.com/questions/126879/popups-default-focus-on-button-best-practice
3. https://ux.stackexchange.com/questions/33275/which-button-should-get-the-focus-at-delete-dialogs
4. https://uxmovement.com/buttons/how-to-design-destructive-actions-that-prevent-data-loss/
5. https://www.neowin.net/forum/topic/411094-the-default-answer-to-every-dialog-box-is-cancel/?tab=comments#comment-586957526
6. https://en.wikipedia.org/wiki/Alert_dialog_box

let's keep cool, @alex-w . there is an alternative: provide an Undo action...

**Comment by alex-w** [comment]
*facepalm* Alex, are you readed your "random literature on UX development"?

**Comment by alex-w** [comment]
Please check version 0.20.3-975ac97479: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
