### ISSUE TITLE
some custom landscapes have lost their polygon line

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1296]
example for one landscape 

## 0.20.2:
![image](https://user-images.githubusercontent.com/3529789/94473879-18260380-01cd-11eb-8b79-52ab66942a15.png)

## 0.20.3:
![image](https://user-images.githubusercontent.com/3529789/94473948-35f36880-01cd-11eb-88cd-0832f70cc0a9.png)

landscape folders symlink to the same folder, so both versions use exactly the same landscape files

```
[landscape]
name = _ Gz - windows
author = ad
description = Ganzendries, Gent


type = polygonal

polygonal_horizon_list = horizon_gz.txt
#polygonal_angle_rotatez = 0
# offset in azimut - FIXME
#angle_rotatez = 135

#polygonal_horizon_list = zero_horizon.txt

#type = fisheye
#maptex = window-test.png
#texturefov = 180

ground_color = .15,.45,.45
horizon_line_color =  .75,.45,.45


[location]
planet = Earth
country = Belgium
state = 
name = Ganzendries

timezone = Europe/Brussels

latitude = +51.933148
longitude = +3.211431
altitude = 8.5
```

```
# Horizon description file for Carte du Ciel
# 
# File format :
# Azimuth(integer) Altitude
#
# Be sure to begin at the North horizon (azimuth 0)
# Intermediate missing value are interpolated
 
000 03
008 03
022 01
027 06
041 06

#016 03
060 02
070 02
090 02

090 07
120 07
126 03
132 04
155 01
#155 60
160 01

161 3.2

# daken
180 7.0

# KBC

# daken
240 3.2


# schoolgebouw
240.476 10.0130	# L
301.5 10.62 #79.23
#302.393 11.044 	# R

#303 05
303.17 16.54 #73.46
306.87 5.28 #84.43
315.62 6.75 #83.15
320.23 19.5 #70.30
327.52 9 #81
329.37 14 376
338.63 14 #76
342.72 2.61 #87.27

#239 9.75 # est
#283 9.75
#305 9.75 # est
#305 05
#312 05

# GZN
#340 03
#341 03

351 05
351 01

# terras N
359 03

```

(https://github.com/Stellarium/stellarium/issues/821#issuecomment-687235717 also no longer works)

this is due to aa5cc9556295843ed57a45565a8919a9857e4dfa ; I recompiled with that commit removed, and I get the polygons.

this landscape still works fine:

![image](https://user-images.githubusercontent.com/3529789/94476020-33ded900-01d0-11eb-89ad-2ab5a761d57c.png)

```
[landscape]
name = _ Gz- parking Gz (0.1a)
author = ad
description = parking Ganzendries, Gent


type = polygonal

polygonal_horizon_list = horizon_gz.txt
#polygonal_angle_rotatez = 0
# offset in azimut - FIXME
#angle_rotatez = 135

#polygonal_horizon_list = zero_horizon.txt

#type = fisheye
#maptex = window-test.png
#texturefov = 180

ground_color = .15,.45,.45
horizon_line_color =  .75,.45,.45


[location]
planet = Earth
country = Belgium
state = 
name = Gent

timezone = Europe/Brussels

latitude = 53.032711
longitude = 3.911046
altitude = 8.5

```

```
# Horizon description file for Carte du Ciel
# 
# File format :
# Azimuth(integer) Altitude
#
# Be sure to begin at the North horizon (azimuth 0)
# Intermediate missing value are interpolated

# noprdelijke hoek parking
# twee putdaken 175
165  7
173  8 # puntdak
175  4.5
186  6.5 # puntdak
205  6 # parallel daken
218 10 # boom
226  4
236 14 # boom
244  6
# school
257  7
257 19

# zuidelijke hoek
# school
280  5
289 14
328  9

# loveling + boom enz

# ZW hoek
020 12
035  4
042  6.5
046  4

# app
#049  4
#049 15

# NW hoek

# half
055  6
067  7.5
# app
067 25

# midden app
078 24
124 27

# N
# app
145 15
162 11
# huis
# 176  8

```

## Note\
* some horizon files mention the comment "Azimuth (integer)" - this cannot be correct.

**Comment by gzotti** [comment]
> some horizon files mention the comment "Azimuth (integer)" - this cannot be correct.

Given that horizon_Geneve.txt was taken without change from CdC, this is apparently what CdC needs.

**Comment by gzotti** [comment]
The underlying class, SphericalRegion, is hard to comprehend. It may also have hidden bugs occasionally causing some extra lines, or I failed to understand it far enough. To make the first landscape work, avoid entries at 0 and 180 sharply, or apply a global rotation polygonal_angle_rotatez = 0.00001 or so. This rotation just makes these angles non-null. I cannot say now why this is required, technically.

You are cordially invited to submit a bugfix. Not one that "patches" 0 and 180, but one that corrects the underlying issue and avoids the spurious extra lines.  And when you have understood the class, it will be trivial for you to create your windows #821.

**Comment by axd1967** [comment]
I understand - it was a known issue, I lost track of it, my imstake.

The workaround works (and has always worked)  and does not justify further development.

Maybe a test on 0 could  be added while loading horizon and ini file, and emit a warning in the logfile.

**Comment by axd1967** [comment]
(a similar issue now exists for the +90 altitudes; workaround it to go for +89.999. this all points to this mystical z-axis issue, but I'm not surprised; it is indeed a strange beast from a library point of view).
