### ISSUE TITLE
No Chinese constellations anymore!

### ISSUE THREAD

**Issue by dutry** [Stellarium/stellarium#1298]
### Expected Behaviour

When I change the "sky culture language" in the setting, I want to see the Chinese constellation, I remember it used be able to  be seen in the old versions on Windows OS.

### Actual Behaviour
I can now only see the Greek constellations even when I transfer the language. The star names are in Chinese tradition style, but the constellations are not.

### Steps to reproduce
Click the F2, and change the "sky culture language".

### System
* Stellarium version: 0.20.3
* Operating system: macOS mojave 10.14.6
* Graphics Card: HD Graphics 615
* Screen type (if applicable): 12 inch 16:10, 2304 x 1440 pixel 226 PPI, APPA027, LED IPS, Retina display

**Comment by dutry** [comment]
@sunshuwei

I see you have done a lot of work about the Chinese constellations, and you also uploaded the modern style (Greek constellations), but now we can not see the traditional Chinese constellations, please notice that.

**Comment by sunshuwei** [comment]
I can't reproduce it.  China Sky Culture works well on my computer.

我无法重现你的问题。中国文化现在有三个，中国（即传统），中国中世纪（宋代为蓝本），中国当代。也就是中国星名+IAU星座。

I can't reproduce it.
![2020-09-29_111704](https://user-images.githubusercontent.com/34102610/94508864-85757b00-0245-11eb-84dc-b1f7c67124fd.png)

**Comment by dutry** [comment]
@sunshuwei 

I'm using macOS instead of Windows, it cannot be shown with macOS.

<img width="1280" alt="Screen Shot 2020-09-29 at 11 31 29 AM" src="https://user-images.githubusercontent.com/17509207/94509758-a17a1c00-0247-11eb-93c5-1aa86df65345.png">

**Comment by dutry** [comment]
Sorry, I made a mistake.
