### ISSUE TITLE
q: multiple same-named comets: what happens in this case?

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1299]
I was querying MPC and received this result:

![image](https://user-images.githubusercontent.com/3529789/94531560-00866380-023d-11eb-990e-425c55a90ad6.png)

(see also SUG 20.0.2, fig. 12.10)

What will happen when I select these identical names? Are these different records for the same comet (but why are they presented several times?) I assume that the end result is a single, logical update; and that the same would result from selecting one of the records rather than three of them.

While we are here, I have a few more questions that have been wrestling with for a long time:

1. what is the difference between "overwrite existing objects" and "update existing objects"? what is lost when overwriting existing objects?
1. what is NOT updated when ticking "Update only the orbital elements"? 
1. the dialog says "**bold** are listed names that match..." - but in my dialog I see _no_ bold names. maybe this appears only in a pristine Stellarium version, before starting to import orbital data updates?

Please bear with me: the UI is not very clear, I just want to clarify this; I suspect that the wording could be improved (or explanative tooltips added).

thank you

**Comment by gzotti** [comment]
Admitted. The original developer has left us years ago, and finding an answer takes a few days of code analysis, which I currently don't have. Feel free to inspect the code and add tooltips, cleanup inconsistencies etc. Presumably MPC now offers several element set for different epochs (which we don't support currently). I cannot say what happens if you select all 3.

**Comment by alex-w** [comment]
No, looks like this is bug on MPC side, because many comets have identical data for 2 lines.

**Comment by axd1967** [comment]
BUSY:
* the bold status no longer applies because the relevant section has been commented: 
https://github.com/Stellarium/stellarium/blob/365fa5ba5e3fe4a6e146de2f26c658d3d9b353b4/plugins/SolarSystemEditor/src/gui/MpcImportWindow.cpp#L394-L408
(i'm trying to dissect the code a bit in order to update the docs)

**Comment by axd1967** [comment]
about the triple comet data:
```
(
(("orbit_PericenterDistance", QVariant(double, 1.61516))("dust_brightnessfactor", QVariant(double, 1.5))("radius", QVariant(int, 5))("albedo", QVariant(double, 0.1))("section_name", QVariant(QString, "c2017t2(panstarrs)"))("dust_lengthfactor", QVariant(double, 0.4))("type", QVariant(QString, "comet"))("absolute_magnitude", QVariant(double, 5))("orbit_AscendingNode", QVariant(double, 64.3776))("slope_parameter", QVariant(double, 4))("orbit_good", QVariant(int, 1000))("name", QVariant(QString, "C/2017 T2 (PANSTARRS)"))("coord_func", QVariant(QString, "comet_orbit"))("orbit_TimeAtPericenter", QVariant(double, 2.45897e+06))("dust_widthfactor", QVariant(double, 1.5))("orbit_Inclination", QVariant(double, 57.2305))("orbit_Eccentricity", QVariant(double, 0.99955))("orbit_ArgOfPericenter", QVariant(double, 92.997))), 
(("orbit_PericenterDistance", QVariant(double, 1.61522))("dust_brightnessfactor", QVariant(double, 1.5))("radius", QVariant(int, 5))("albedo", QVariant(double, 0.1))("section_name", QVariant(QString, "c2017t2(panstarrs)"))("dust_lengthfactor", QVariant(double, 0.4))("type", QVariant(QString, "comet"))("absolute_magnitude", QVariant(double, 5))("orbit_AscendingNode", QVariant(double, 64.3775))("slope_parameter", QVariant(double, 4))("orbit_good", QVariant(int, 1000))("name", QVariant(QString, "C/2017 T2 (PANSTARRS)"))("coord_func", QVariant(QString, "comet_orbit"))("orbit_TimeAtPericenter", QVariant(double, 2.45897e+06))("dust_widthfactor", QVariant(double, 1.5))("orbit_Inclination", QVariant(double, 57.2308))("orbit_Eccentricity", QVariant(double, 0.999575))("orbit_ArgOfPericenter", QVariant(double, 92.9948))), 
(("orbit_PericenterDistance", QVariant(double, 1.61513))("dust_brightnessfactor", QVariant(double, 1.5))("radius", QVariant(int, 5))("albedo", QVariant(double, 0.1))("section_name", QVariant(QString, "c2017t2(panstarrs)"))("dust_lengthfactor", QVariant(double, 0.4))("type", QVariant(QString, "comet"))("absolute_magnitude", QVariant(double, 5))("orbit_AscendingNode", QVariant(double, 64.3776))("slope_parameter", QVariant(double, 4))("orbit_good", QVariant(int, 1000))("name", QVariant(QString, "C/2017 T2 (PANSTARRS)"))("coord_func", QVariant(QString, "comet_orbit"))("orbit_TimeAtPericenter", QVariant(double, 2.45897e+06))("dust_widthfactor", QVariant(double, 1.5))("orbit_Inclination", QVariant(double, 57.2306))("orbit_Eccentricity", QVariant(double, 0.99954))("orbit_ArgOfPericenter", QVariant(double, 92.998))))

```

MPC indeed returns small differerences in orbital parameters. this can result in small but wrong updates; at first sight there is no way for the user to see which set is correct

(https://www.minorplanetcenter.net/iau/MPCORB/CometEls.txt)

**Comment by axd1967** [comment]
I have the impression that this feature is still not working as one would expect.

The phrasing is still not OK, as it easily leads to importing all known comets from a selected source when the user just wants to UPDATE all loaded comets.
