### ISSUE TITLE
0.20.3 GUI scaling issue

### ISSUE THREAD

**Issue by GernotSchreider** [Stellarium/stellarium#1301]
### Expected Behaviour
pop-up windows for settings and display options are not clipped or can be resized
### Actual Behaviour
Describe or maybe attach a screenshot?
Please check the attached screen shots
The windows can not be fully seen and they can not be resized.
There is no way to change the font size.
![ScreenShot_1](https://user-images.githubusercontent.com/68224336/94615308-d6b65680-02a7-11eb-9b4d-67c804ec8d09.jpg)
![ScreenShot_2](https://user-images.githubusercontent.com/68224336/94615320-d9b14700-02a7-11eb-9f7d-d30c77e2fcc1.jpg)

I am running Win 10 on a Lenovo Laptop with the recommended settings
![Display_settings](https://user-images.githubusercontent.com/68224336/94615629-59d7ac80-02a8-11eb-90db-57ba19358474.jpg)

### Steps to reproduce
apply the windows display settings as indicated

### System
* Stellarium version: 0.20.3
* Operating system: Windows 10 Pro vers 1909 build 18363.1082
* Graphics Card: Intel UHD Graphics 620
* Screen type (if applicable): Resolution=1920x1080, scaling 150%
[log.txt](https://github.com/Stellarium/stellarium/files/5301891/log.txt)

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Stellarium needs some minimum screenspace. Display scaling now makes things even more difficult.
If you really need this 150% global scaling, you may try the following:

In your start menu, you find a program group "Stellarium". Inside, there is a link "Stellarium (scale 200%)". Right-click this link, say "Mehr-->Dateispeicherort öffnen".  

Make a copy of this link, name it "Stellarium (75%)". Then right-click: Eigenschaften (properties). See the command line:
`"C:\Program Files\Stellarium_0.20.3\stellarium.exe" --scale-gui 2.0 -platform windows:altgr
`
Edit this to read:
`"C:\Program Files\Stellarium_0.20.3\stellarium.exe" --scale-gui 0.75 -platform windows:altgr
`

Then launch this new link, and tell us whether this works.

... Hmm, it seems this works well only when the value is larger than 1. :-(

Can you live with a global scaling of 125%? The icons in the task bar can be scaled separately, they look pretty small.

**Comment by GernotSchreider** [comment]
Ok, my path and names do look a bit different but I did start Stellarium with the change in the parameter scale-gui  0.75 and it looks good for me.

Here are the two screen shots to compare with the ones in my previous report. 

 



 



 

If I set the parameter to 0.8 it still is ok, but at 0.9 the the windows are too big to fit, see below.

 



 

 

Interestingly the font size for names of constellation and for text in the pop-up windows is reduced in all cases compared to the standard scaling.

Please see here for comparison the larger fonts at standard



 

So to wrap it up, the work-around works for me, Thank you.

But I think the problem that the scaling does not work as it should is still there.

 

You were asking if I really need the 150% scaling. Yes, I do. This is the Windows recommended scaling for this laptop and I found it good to use.

Maybe this is because of my age and my sight impairment but I think the software should support such features for the benefit of the user.

 

Thanks 

Gernot

**Comment by f5eot** [comment]
Hello,
I have exactly the same problem as GernotSchreider with the latest version of STELLARIUM (0.20.3-win64) on my LENOVO pc on which the previous version works fine.
I have reinstalled and used version 0.20.2-win64 again.

Rgds

Michel

**Comment by f5eot** [comment]
Hello again,

I have just made the modification that you precaunize by passing the scale from 2.0 to 0.75 and everything is displayed perfectly.

Thank you
Rgds
Michel

**Comment by alex-w** [comment]
Please check version 0.20.3-975ac97479: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by KlausDerOptiker** [comment]
Hi friends of stellarium!
I just faced the same problem @ my Lenovo Yoga and followed your initial solution gzotti. It worked directly but I also needed to modify my desktop link... (adding --scale-gui 0.75 -platform windows:altgr) Might be that this step got lost.
All other hints and steps are very welcome but not been necessary.
All is fine :)

Best regards
Klaus

**Comment by gzotti** [comment]
Of course you must edit the link with which you start Stellarium, be that desktop, start menu or task bar.

**Comment by alex-w** [comment]
Could Windows 10 set scaling parameter for specific application only?

**Comment by KlausDerOptiker** [comment]
Hi Alexander!

Not that I am aware of… but that does not mean that there might be a possibility. – That’s a question to place to MICROSOFT.

 

Best regards

Klaus

 

Klaus Wolter

Lakronstraße 56
D-40625 Düsseldorf

+49 177 670 7711
 <mailto:kp@woltermgbh.com> kp@woltermgbh.com

 

Von: Alexander Wolf [mailto:notifications@github.com] 
Gesendet: Mittwoch, 18. November 2020 09:52
An: Stellarium/stellarium
Cc: KlausDerOptiker; Comment
Betreff: Re: [Stellarium/stellarium] 0.20.3 GUI scaling issue (#1301)

 

Could Windows 10 set scaling parameter for specific application only?

**Comment by gzotti** [comment]
Much has changed. We may probably come to a final solution of this topic. I hope I can even find a HiDPI screen somewhere.

https://doc.qt.io/qt-5/highdpi.html
https://doc.qt.io/qt-6/highdpi.html

**Comment by GernotSchreider** [comment]
Thank you for your perseverance, much appreciated.

**Comment by alex-w** [comment]
Hi @GernotSchreider 

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by gzotti** [comment]
I think there were so many changes concerning screen scaling that we can close this as solved (or at least there is a known workaround).
