### ISSUE TITLE
Navigation options

### ISSUE THREAD

**Issue by johnbellora** [Stellarium/stellarium#1303]
No problems detected.
Please add more stars to navigational library.  We need the additional stars option above the typical 58 . Suggest everything 2.1 and brighter so that the GHA and LHA can be displayed. Or just add both of those figures to the typical info of all stars.

Please  allow an option of GHA & LHA read outs to be in tenths of degrees down to 4 decimal place as well as minutes and it is now. One more decimal place would help as well in the minutes

Best Regards
John Bellora
858-776-2189
I have donated to Stellarium.

**Comment by alex-w** [comment]
Please uncheck option "Only show extra information for marked Navigational Stars" to show an additional data for all stars.

**Comment by alex-w** [comment]
Please check version 0.20.3-cc61c2cd7c: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by johnbellora** [comment]
Hello Alexander,
Thank you for considering my request    
   - Added ability to toggle show extra decimals in the navigational info (GH: #1303)
How do I go about or when can i download a version which has this feature? Forgive me I am not so disciplined in the art of computer lingo and culture.
Best Regards
John Bellora


-----Original Message-----
