### ISSUE TITLE
Unable to close windows opened from the side-bar "Location", "Date/Time", etc by mouse-click.

### ISSUE THREAD

**Issue by phorham** [Stellarium/stellarium#1305]
Unable to close windows opened from the side-bar or by their respective function keys, "Location", "Date/Time", etc, by mouse-click on the "X" icon.

### Expected Behaviour
Window closes upon click

### Actual Behaviour
Upon mouse-over the "X" is hi-lighted but does not respond to mouse-click. (Window can only be closed by de-selecting from the side-bar or by it's shortcut function key).

### Steps to reproduce
Open any window from the left side-bar or by it's shortcut function key.
Attempt to close by mouse-click using the "X" icon top right.

### System
* Stellarium:
Version: 0.20.3-1.1
Build Time: Mon 28 Sep 2020 13:33:40 BST
Source Package: stellarium-0.20.3-1.1

* Operating system:
openSUSE Tumbleweed 20200928
Kernel Version: 5.8.10-1-default

* Graphics/Screen:
Device-1: NVIDIA G84 [GeForce 8600 GTS]
  vendor: Micro-Star MSI
  driver: nouveau v: kernel bus ID: 01:00.0 chip ID: 10de:0400 
Display: x11 server: X.Org 1.20.9
  compositor: kwin_x11
  driver: nouveau (unloaded: fbdev,modesetting,nv,vesa) alternate: nvidia
  resolution: 1280x1024~60Hz s-dpi: 96 
OpenGL: renderer: NV84 v: 3.3 Mesa 20.1.8 direct render: Yes 

### Logfile 
2020-10-01T09:05:24
Operating System: openSUSE Tumbleweed
Compiled using GCC 10.2.1
Qt runtime version: 5.15.1
Qt compilation version: 5.15.1
Addressing mode: 64-bit
MemTotal:        4016000 kB
MemFree:         3120952 kB
MemAvailable:    3370252 kB
SwapTotal:       9319420 kB
model name	: AMD Athlon(tm) 64 X2 Dual Core Processor 5600+
cpu MHz		: 1800.000
model name	: AMD Athlon(tm) 64 X2 Dual Core Processor 5600+
cpu MHz		: 1800.000
/usr/bin/stellarium 
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names

**Comment by alex-w** [comment]
This is issue in Qt 5.15.1

**Comment by axd1967** [comment]
Strange, this does not happen in KUbuntu 0.20.3?
```
Operating System: Ubuntu 20.04.1 LTS
Compiled using GCC 9.3.0
Qt runtime version: 5.12.8
Qt compilation version: 5.12.8
```

[log.txt](https://github.com/Stellarium/stellarium/files/5339551/log.txt)

**Comment by alex-w** [comment]
Please check version 0.20.3-cc61c2cd7c: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by phorham** [comment]
Close button works just fine when running from the appimage

Not too familiar with using appimages - slightly confused by the log file which shows Qt 5.9.5 whereas this machine is using Qt 5.15.1

2020-10-25T10:25:18
Operating System: openSUSE Tumbleweed
Compiled using GCC 7.5.0
Qt runtime version: 5.9.5
Qt compilation version: 5.9.5
Addressing mode: 64-bit
MemTotal:        4016004 kB
MemFree:         2071540 kB
MemAvailable:    3095000 kB
SwapTotal:       4194300 kB
model name	: AMD Athlon(tm) 64 X2 Dual Core Processor 5600+
cpu MHz		: 2600.000
model name	: AMD Athlon(tm) 64 X2 Dual Core Processor 5600+
cpu MHz		: 2600.000
/tmp/.mount_Stella5rKqEN/usr/bin/stellarium 
 -------------------------------------------------------------------------
[ This is Stellarium 0.20.3-cc61c2cd7c [master] - https://stellarium.org/ ]
[ Copyright (C) 2000-2020 Fabien Chereau et al.                           ]
 -------------------------------------------------------------------------
Writing log file to: "/home/paul/.stellarium/log.txt"

snip remainder of log

Operating System: openSUSE Tumbleweed 20201022
KDE Plasma Version: 5.20.1
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.8.15-1-default
OS Type: 64-bit
Processors: 2 × AMD Athlon(tm) 64 X2 Dual Core Processor 5600+
Memory: 3.8 GiB of RAM
Graphics Processor: NV84

**Comment by phorham** [comment]
Apologies for the large bold font. That was unintentional...
