### ISSUE TITLE
AstroCalc: WUT Panel NGC objects inconsistency

### ISSUE THREAD

**Issue by mikenoname-github** [Stellarium/stellarium#1310]
### Expected Behaviour

In the WUT panel when clicking on the Herschel 400 category I see dozens of NGC objects, which is correct. When I then click on the NGC/IC category I would expect to see more NGC objects than those listed in the Herschel 400 list.

### Actual Behaviour

I see only two NGC objects in the NGC/IC category when I see dozens of NGC objects in the Herschel list. Please see screenshots.

![Herschel400WUT](https://user-images.githubusercontent.com/71414112/95007527-c19e3800-05c5-11eb-971c-ce0f0e6df964.jpg)

![NGC_WUT](https://user-images.githubusercontent.com/71414112/95007530-c2cf6500-05c5-11eb-8db0-bd7e6663890c.jpg)

### System
* Stellarium version: 20.3
* Operating system: Win10

**Comment by alex-w** [comment]
Please check version 0.20.3-975ac97479: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by mikenoname-github** [comment]
Alexander,

Looks fixed. Thank you!
