### ISSUE TITLE
odd survey interaction

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1314]
### Expected Behaviour

Loading of different HiPS surveys should not influence each other.

### Actual Behaviour

A specific combination of surveys causes a strange deformation

### Steps to reproduce

1. enable HiPS
1. activate "CO composite survey"
![image](https://user-images.githubusercontent.com/3529789/95243947-9f005f00-0811-11eb-8ca7-b39e20ffc06b.png)

1. activate "CGPS_II_1_8192_partial.fits" 
![image](https://user-images.githubusercontent.com/3529789/95243976-a7f13080-0811-11eb-99f4-f933fe44b861.png)

1. deactivate "CO composite survey"
![image](https://user-images.githubusercontent.com/3529789/95244056-c35c3b80-0811-11eb-8f9b-6bcb4ede77bd.png)

It looks like "CGPS_II_1_8192_partial.fits" is incorrectly drawn _when on its own_.

![image](https://user-images.githubusercontent.com/3529789/95244149-e38bfa80-0811-11eb-8459-ed0597aa444f.png)

Possibly due to a parameter in the data that is not being taken into account. The last figure shows the extent of the "-.fits"  data (black area).

### System
* Stellarium version: 0.20.3 
* Operating system: KUbuntu 20.04

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/5335908/log.txt)

**Comment by alex-w** [comment]
Step 3: incorrect drawing the survey

**Comment by alex-w** [comment]
Please check version 0.20.3-cc61c2cd7c: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by axd1967** [comment]
this seems to work, thanks!

![image](https://user-images.githubusercontent.com/3529789/102095000-45c13700-3e23-11eb-9e75-8a67e62c2af4.png)
