### ISSUE TITLE
Ocular Plugin: Mouse Navigation

### ISSUE THREAD

**Issue by Astro-Martin** [Stellarium/stellarium#1317]
-->Ocular Plugin: Mouse Navigation disabled in Ocular View

### Expected Behaviour
Ocular View should not disable 'mouse navigation'
You can use the arrow keys to shift the image;
However, there are no arrow keys on a tablet PC.
'Image sensor frame' and 'Telrad sight' do not disable 'mouse navigation'

### Actual Behaviour
Mouse navigation is enabled in the main application.
When switching to 'Ocular View', mouse navigation gets disabled.

### Steps to reproduce
Enable mouse navigation in main application.
Switch to 'Ocular View', Check settings; mouse navigation is disabled

### System
* Stellarium version: stellarium-0.20.3-win64.exe
* Operating system: windows 10 64-bit [Version 10.0.19041.508]
* Graphics Card: Intel(R) HD Graphics 4000
* Screen type (if applicable): 1366x768

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Mouse navigation is not diabled in eyepicece mode

**Comment by alex-w** [comment]
You can freely use mouse to shift the view in the eyepiece mode

**Comment by gzotti** [comment]
This is deliberate. You can select a new target, and it will be centered.

**Comment by Astro-Martin** [comment]
> 
> 
> You can freely use mouse to shift the view in the eyepiece mode

Sorry no. I can not.

**Comment by Astro-Martin** [comment]
> 
> 
> This is deliberate. You can select a new target, and it will be centered.

I thought so. But it would be nice if the user could configure it.

**Comment by alex-w** [comment]
> > You can freely use mouse to shift the view in the eyepiece mode
> 
> Sorry no. I can not.

Why? I can do it freely

**Comment by gzotti** [comment]
On Windows, you cannot drag the window when in Oculars mode.

**Comment by Astro-Martin** [comment]
> 
> 
> > > You can freely use mouse to shift the view in the eyepiece mode
> > 
> > 
> > Sorry no. I can not.
> 
> Why? I can do it freely
>
Don't know why. It doesn't work for others in our forum either

**Comment by alex-w** [comment]
> Don't know why. It doesn't work for others in our forum either

Please try double-click by any celestial object within ocular FOV

**Comment by gzotti** [comment]
Yes, jump from object to object. No free drag. And I think this is deliberate and intentional.

**Comment by Astro-Martin** [comment]
> 
> 
> On Windows, you cannot drag the window when in Oculars mode.

so it works on linux but not on windows?

**Comment by gzotti** [comment]
On WSL (Ubuntu under Windows) it works exactly as described for Windows, so I assume it works as described by me above also under native Linux. BTW only objects selected within the view circle are clickable. This is also intentional.

**Comment by alex-w** [comment]
No mouse drag, but yes for jumping by selection

**Comment by Astro-Martin** [comment]
I still think it's a bug, because 'Image sensor frame' and 'Telrad sight' don't disable mouse navigation.

**Comment by alex-w** [comment]
> I still think it's a bug, because 'Image sensor frame' and 'Telrad sight' don't disable mouse navigation.

This is not a bug

**Comment by gzotti** [comment]
This allows fine framing in sensor view. And a Telrad is usually attached on a Dobson which can also be shifted freely. 
This behaviour is fully intended and has been honed for a decade or more.

**Comment by Astro-Martin** [comment]
But that is also just an 'opinion'

**Comment by axd1967** [comment]
Just to be sure: with "mouse navigation" Martin means dragging with the mouse, right?

The core issue here is that (apparently) a tablet PC has no arrow keys - so I assume we are talking about a touch-sensitive screen and there is no keyboard (?), and on-screen gestures do not include simple left/right/up/down inputs. (Martin might want to add a model name or a picture of that specific Tablet PC.)

Note that if there is no visible (selectable) object, clicking in an eyepiece view does nothing, IMHO this is a needless limitation. The idea could be that the view just centers on the clicked position if there is no nearby object.  Sometimes a user just wants to centre an ocular circle over several objects, the workaround is then to use keyboard navigation for this. And this might not be possible on a Tablet PC.

**Comment by Astro-Martin** [comment]
Yes. I use google translate so it might be difficult for you to understand ...
In main application "enable mouse navigation" ist enabled.
If you switch to the 'eyepiece mode' and look at the settings again, the option is disabled.
You can set the option again, but if you switch to a different eyepiece, the setting is gone again.

I think it would be easy to implement so that the user can decide how the system should behave in this regard.

**Comment by gzotti** [comment]
A tablet PC fails to fulfill a minimum system requirement:
* keyboard

**Comment by Astro-Martin** [comment]
This is about "mouse navigation", not the keyboard. That was just an example. It is not logical that the operation of the software suddenly changes at one point.
I think it would be easy to implement so that the user can decide how the system should behave in this regard.

**Comment by gzotti** [comment]
Can you tell me the application case, benefit and purpose of not centering the ocular view on a visible object?
In Ocular view, the operation of the software changes also in other respects: You get information about how an object viewed with an optical instrument will appear in a circular-view eyepiece. Limiting magnitude can be limited to what the telescope may yield. If really absolutely needed, you can still Shift-click to set and center on a marker anywhere in the void.
