### ISSUE TITLE
AstroCalc Window Remembering Size and Position

### ISSUE THREAD

**Issue by mikenoname-github** [Stellarium/stellarium#1318]
During observation sessions I often open the AstroCalc window many times. I get frustrated when I have to resize it each time I open it because it does not remember its size and position between uses.

I would like it to remember its size and position between uses.

**Comment by gzotti** [comment]
It does.

**Comment by alex-w** [comment]
Yes, it does (just check right now).

**Comment by mikenoname-github** [comment]
No version of Stellarium I have ever run has it worked on. 

I am currently running 20.3-975ac97479 on a Win10 machine and it DOES NOT remember its size between uses.

**Comment by alex-w** [comment]
Hmm... please attach log.txt

**Comment by gzotti** [comment]
All subwindows store location and sizes in config.ini, sections DialogPositions and DialogSizes. There are definitely entries for AstroCalc in both sections.

**Comment by mikenoname-github** [comment]
2020-10-10T05:12:28
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 15.9 (Visual Studio 2017)
Qt runtime version: 5.12.6
Qt compilation version: 5.12.6
Addressing mode: 64-bit
Total physical memory: 8146 MB
Available physical memory: 4545 MB
Physical memory in use: 44%
Processor speed: 3392 MHz
Processor name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Processor speed: 3392 MHz
Processor name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Processor speed: 3392 MHz
Processor name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Processor speed: 3392 MHz
Processor name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Processor speed: 3392 MHz
Processor name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Processor speed: 3392 MHz
Processor name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Processor speed: 3392 MHz
Processor name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Processor speed: 3392 MHz
Processor name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
C:\Program Files\Stellarium\stellarium.exe -platform windows:altgr 
 -----------------------------------------------------------------------
[ This is Stellarium 0.20.3-975ac97479 [HEAD] - https://stellarium.org/ ]
[ Copyright (C) 2000-2020 Fabien Chereau et al.                         ]
 -----------------------------------------------------------------------
Writing log file to: "C:\\Users\\Mike\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\Mike\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\Mike\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.5.13399 Compatibility Profile Context 15.201.1151.1008"
Current Format:  QSurfaceFormat(version 4.5, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::sRGBColorSpace, profile  QSurfaceFormat::CompatibilityProfile)
StelMainView::init
Detected: OpenGL "4.5"
Driver version string: "4.5.13399 Compatibility Profile Context 15.201.1151.1008"
GL vendor is "ATI Technologies Inc."
GL renderer is "AMD Radeon HD 7000 series"
GL Shading Language version is "4.40"
GLSL Version Number detected:  4.4
GLSL version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\Mike\\AppData\\Local\\stellarium\\stellarium\\cache"
StelLocation::createFromLine(): TimeZone name for  "Tecopa, CA"  not found. Translating "system_default"  to  "system_default"
Sky language is  "en_US"
Planetary features language is  "en_US"
Application language is  "en_US"
Empty translation file for language  "en_US" in section "stellarium-scripts"
Scripts language is  "en_US"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\Mike\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
SolarSystem has  187 entries.
Loaded 104 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15632 / 15671 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl, Ryugu, Bennu"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4507 / 4507 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.11 (standard edition)"
Loaded 94671 DSO records
Loading DSO outline data ...
Loaded 82 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 1004 / 1004 common star names
Loading DSO name data ...
Loaded 1122 / 1144 DSO name records successfully
WARNING - No position data for 22 objects: "PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "western"
Loaded 81 / 82 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 71 / 72 asterism names
stel.OpenGLArray: Vertex Array Objects are supported
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\Mike\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\Mike\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\Mike\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at:  "C:\\Users\\Mike\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Loaded plugin "Satellites"
[Satellites] loading catalogue file: "C:\\Users\\Mike\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "SHENZHOU-11 MODULE" "41868"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Satellite has invalid orbit: "ATL-1" "44830"
Initializing planets GL shaders... 
  OpenType support missing for "Verdana", script 11
  OpenType support missing for "MS Shell Dlg 2", script 11
  OpenType support missing for "Arial", script 11
  OpenType support missing for "MS UI Gothic", script 11
  OpenType support missing for "SimSun", script 11
  OpenType support missing for "Verdana", script 12
  OpenType support missing for "MS Shell Dlg 2", script 12
  OpenType support missing for "Arial", script 12
  OpenType support missing for "MS UI Gothic", script 12
  OpenType support missing for "SimSun", script 12
  OpenType support missing for "Verdana", script 13
  OpenType support missing for "MS Shell Dlg 2", script 13
  OpenType support missing for "Arial", script 13
  OpenType support missing for "MS UI Gothic", script 13
  OpenType support missing for "SimSun", script 13
  OpenType support missing for "Verdana", script 14
  OpenType support missing for "MS Shell Dlg 2", script 14
  OpenType support missing for "Arial", script 14
  OpenType support missing for "MS UI Gothic", script 14
  OpenType support missing for "SimSun", script 14
  OpenType support missing for "Verdana", script 16
  OpenType support missing for "MS Shell Dlg 2", script 16
  OpenType support missing for "Arial", script 16
  OpenType support missing for "MS UI Gothic", script 16
  OpenType support missing for "SimSun", script 16
  OpenType support missing for "Verdana", script 17
  OpenType support missing for "MS Shell Dlg 2", script 17
  OpenType support missing for "Arial", script 17
  OpenType support missing for "MS UI Gothic", script 17
  OpenType support missing for "SimSun", script 17
  OpenType support missing for "Verdana", script 19
  OpenType support missing for "MS Shell Dlg 2", script 19
  OpenType support missing for "Arial", script 19
  OpenType support missing for "MS UI Gothic", script 19
  OpenType support missing for "SimSun", script 19
  OpenType support missing for "Verdana", script 20
  OpenType support missing for "MS Shell Dlg 2", script 20
  OpenType support missing for "Arial", script 20
  OpenType support missing for "MS UI Gothic", script 20
  OpenType support missing for "SimSun", script 20

**Comment by mikenoname-github** [comment]
I have a refinement. The window DOES remember its position. 

It also remembers its size, up to a certain window size of the AstroCalc window.

If I open the AstroCalc window and make it *smaller* it does remember its size. However, if I make it large (like nearly the full size of a 1280x1024 monitor), then when I come back into it it is much smaller than that full size.

**Comment by gzotti** [comment]
OK, it went from 3300px to 2700px width. Seems some mechanism limits that. Must have a look.

**Comment by gzotti** [comment]
Yes, a maximum window size of 0.8 of screen size is applied. (#108, tried to fix #103.) The location window may need further attention, and the max. size may have to allow 0.95 window size.

**Comment by mikenoname-github** [comment]
Thanks Georg!

**Comment by alex-w** [comment]
Please check version 0.20.3-4b8e7fd1c8: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by axd1967** [comment]
Interesting; why is there a limitation on the max size?

**Comment by gzotti** [comment]
See the history of this thread, #103 and #108. Probably we don't even need it, this is why this is not closed yet. Propose a better fix for #108.

**Comment by mikenoname-github** [comment]
> 
> 
> Please check version 0.20.3-4b8e7fd1c8: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

Works perfect! Thank you!

**Comment by alex-w** [comment]
Please check version 0.20.3-5f954765e3: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
