### ISSUE TITLE
Following planet Earth while on planet Earth makes me nauseous

### ISSUE THREAD

**Issue by PhoebeWCaulfield** [Stellarium/stellarium#1319]
## Expected Behavior

* View stays at azimuth = 180° (or some other constant value)

## Actual Behavior

* View is constantly jittering around alt = −90°
* the azimuth of planet Earth is constantly changing within the range [0°, 360°]

## Steps to reproduce

1. select planet earth
1. activate follow mode (hit the space bar)
1. run to the bathroom and throw up

## System
* Stellarium version: 0.14.3-1
* Operating system: GNU/Linux 4.2.0
* Graphics Card: Yes, there is one onboard.
* Screen type (if applicable): Resolution, HighDPI, scaling

## Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
The bug is gone at least since version 0.16.0 (I don't remember when I fixed it)

**Comment by axd1967** [comment]
no @alex-w ... it also happens in 0.20.3 but I haven't been able to reproduce it systematically yet.

**Comment by axd1967** [comment]
here is how I manage to trigger this bug
prepare following user script:

```javascript
//
// Name: nudge to horizon
// Author: AD
// License: Public Domain
// Version: 0.1
// Shortcut: Alt+h
// Description: Lowers the view so that the horizon is at the bottom of the viewport and top is at zenith


// var alt = core.getViewAltitudeAngle()
var az = core.getViewAzimuthAngle()

fov = StelMovementMgr.getCurrentFov()
//fov = 90
//fov = 60

alt = fov/2
core.moveToAltAzi(alt, az)

//StelMovementMgr.zoomTo(fov, 0.001)
//core.moveToAltAzi(alt, az)
//ht = core.getScreenHeight()
```

1. set FOV to 180 (ctl-alt-1)
1. go to zenith (shift-z)
1. perform alt-H repeatedly

**Comment by axd1967** [comment]
@PhoebeWCaulfield 

1. can you reproduce this by following the steps I mention
2. you should install a recent version!

**Comment by axd1967** [comment]
@alex-w  @gzotti this is still a bug.

**Comment by alex-w** [comment]
@axd1967 1) you tried reproduce other bug 2) please explain why azimuth at zenith and nadir should be exactly 180 degrees. It's astronomical nonsense.

**Comment by gzotti** [comment]
DUPLICATE of #754. Yes, we know, with a script you can break zenith view. Press Shift-Z for a good zenith view.
