### ISSUE TITLE
angle measurement: placement of output

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1320]
**Is your feature request related to a problem? Please describe.**
The output is often difficult to read and when zooming,not readable at all

![image](https://user-images.githubusercontent.com/3529789/95836572-e4f08200-0d3f-11eb-826e-446e2917b6f7.png)

![image](https://user-images.githubusercontent.com/3529789/95836703-0e111280-0d40-11eb-887b-974721e73023.png)

**Describe the solution you'd like**
Provide option to position the output:
- start point (current behaviour)
- end point
- location on screen (corner, middle) (si ilar as in Pointer Coordinates) 

**Describe alternatives you've considered**
-

**Additional context**

![image](https://user-images.githubusercontent.com/3529789/95837185-9abbd080-0d40-11eb-88a4-47407f99342b.png)

The current behaviour is logical wrt placement

![image](https://user-images.githubusercontent.com/3529789/95837259-b2935480-0d40-11eb-8e31-61e8319e5a51.png)
... as long as one doesn't need to zoom in.

**Comment by alex-w** [comment]
Fixed in revision b1552f96f6e764d318b1057320167dfe6f38b3ad
