### ISSUE TITLE
disable focus marker in hidden GUI mode

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1321]
**Is your feature request related to a problem? Please describe.**
The focus marker is sometimes disturbing the view:

![image](https://user-images.githubusercontent.com/3529789/95884047-f2c3f880-0d7b-11eb-81f3-b0fbcb5853ef.png)

Its color is not customisable but is sometimes distracting.

**Describe the solution you'd like**
Hide the marker when GUI mode is untoggled (Ctrl+T), _but keep the focus_. 

![image](https://user-images.githubusercontent.com/3529789/95884206-1dae4c80-0d7c-11eb-8979-1647328f7ef6.png)

A user who wants a marker can enable the FOV center marker:

![image](https://user-images.githubusercontent.com/3529789/95884250-2acb3b80-0d7c-11eb-9388-e30584ed3236.png)

**Describe alternatives you've considered**
Remove focus (Ctrl+space); but this disables tracking.

**Additional context**

**Comment by alex-w** [comment]
Hidden GUI mode was created for scripts and behaviour of GUI is not related to behaviour of the sky. Why you need this very strange behavior?

**Comment by axd1967** [comment]
As I write: "The focus marker is sometimes disturbing the view". Description updated.

**Comment by alex-w** [comment]
Please check version 0.20.3-cc61c2cd7c: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by axd1967** [comment]
thx. 
next good first issue is to add this as an option in the UI.
