### ISSUE TITLE
Stellarium .20.3 crashes when I change the sonar settings under ocular

### ISSUE THREAD

**Issue by moncadli** [Stellarium/stellarium#1322]
### Expected Behaviour
Go to Ocular >>  be able to enter sonar info
### Actual Behaviour
Go to enter sonar info and Stellarium closes

### Steps to reproduce
Mentioned above
### System
* Stellarium version: .20.3
* Operating system: Windows 10
* Graphics Card: No idea, I have a new computer
* Screen type (if applicable): No idea

### Logfile 
N/A

**Comment by alex-w** [comment]
Please attach your ocular.ini file

**Comment by gzotti** [comment]
I wonder what "sonar settings" are w.r.t. oculars?

**Comment by alex-w** [comment]
@moncadli any news?

**Comment by moncadli** [comment]
@alex-w i was able to fix it! All I needed to do was reboot my computer
