### ISSUE TITLE
HiPS odd cyclic behaviour

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1323]
### Actual Behaviour
When selecting the shown Survey, tiles seem to appear and disappear all the time .

![image](https://user-images.githubusercontent.com/3529789/96031894-3e4ed300-0e5e-11eb-85c4-8af0de369f88.png)

![image](https://user-images.githubusercontent.com/3529789/96031954-51fa3980-0e5e-11eb-9776-8464e06f3f26.png)

![image](https://user-images.githubusercontent.com/3529789/96031997-5cb4ce80-0e5e-11eb-92f2-56dc2abef9ee.png)

### System
* Stellarium version: 0.20.3
* Operating system: KUbuntu 20.04
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
Nothing significant in logfile
[log.txt](https://github.com/Stellarium/stellarium/files/5380264/log.txt)

**Comment by axd1967** [comment]
also on Stellarium 0.20.3-2290e7e5de [master]

**Comment by alex-w** [comment]
Possibe not our problem

**Comment by guillaumechereau** [comment]
I can reproduce this bug.  I'll have a look.

**Comment by guillaumechereau** [comment]
The bug could be due to the fact that this survey uses very small tiles (32x32px).

**Comment by guillaumechereau** [comment]
Commit 0cdfb7170 should fix that.

**Comment by alex-w** [comment]
Please check version 0.20.3-cc61c2cd7c: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by axd1967** [comment]
working now, thx @guillaumechereau  @alex-w
