### ISSUE TITLE
increase field widths

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1325]
This is a recurring issue in Stellarium that should deserve more attention.
Several control inputs are too small.

In this case, the fractional value of the brightness is not visible. On the other hand, there are loads of empty space available that are not used.

![image](https://user-images.githubusercontent.com/3529789/96032641-3f343480-0e5f-11eb-9667-c80c844cfa06.png)

See also #1249.

**Comment by alex-w** [comment]
Please check the master

**Comment by axd1967** [comment]
OK - thanks!
