### ISSUE TITLE
AstroCalc: Wider range of dates

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1327]
We're currently stuck with calculating positions and phenomena between 1600 and 9999 AD. It would help research and visualization if that range increased, so that we could use AstroCalc fully for e.g. antiquity.

**Comment by gzotti** [comment]
This is more than obvious. 1600 is a technical restriction which we want to lift ourselves. Just that it takes some effort...

**Comment by AntonioYague** [comment]
Hope this could be soon implemented. Many historical events like star of Betlehem now are only known graphically and it is difficult to be precise. Thanks

**Comment by alex-w** [comment]
Well, I can apply fast solution for this issue if I switch input fields for dates into using JD (with traditional dates as tooltips for JD) - is it acceptable?  

@gzotti ?

**Comment by gzotti** [comment]
Sorry, too busy to do much this week. I'd like to have a look how the calendar interface works, later today or this weekend.

**Comment by Atque** [comment]
@alex-w Couldn't one simply translate the JD into pre-Greogrian dates?

**Comment by gzotti** [comment]
@Atque AstroCalc uses a date panel which is apparently limited to the post-1600 Gregorian calendar. Of course, "one can simply translate that...". Just that somebody must do it.

**Comment by Atque** [comment]
@gzotti I understand. I'm just brainstorming here.

@alex-w About JD; I don't think JD should be used post-1600. I think it would confuse most people.

**Comment by AntonioYague** [comment]
Julian date is a good help as an intermediate step because there are some calculators that could change to day-month and year

**Comment by gzotti** [comment]
@AntonioYague We know that and use JD internally. The QDateTime widget is the problem. It only works in the Gregorian calendar, and for dates past Jan 1st, 100AD GREGORIAN. We can set it to allow dates from October 15, 1582, but earlier dates will cause confusion. The proper solution obviously is a replacement widget or some entirely new GUI element.

**Comment by alex-w** [comment]
We may use idea from AstroCalc/Eclipses tool - switch from DateFrom/DateTo to YearSince/TimeDepth

**Comment by gzotti** [comment]
I am much in favour of this option. We can just use full calendar years also here.

**Comment by alex-w** [comment]
> I am much in favour of this option. We can just use full calendar years also here.

No, IMHO from year/month to year/month will be better

**Comment by gzotti** [comment]
Whichever solution, just allow Julian/pre-1600 calendar dates.

**Comment by Atque** [comment]
Hm, this might have to remain open, as the ephemerides are still limited to Gregorian dates.
