### ISSUE TITLE
shortcuts window: double-click to execute action

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1328]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to see / test what the result is of a specific action, without having to define a shortcut. The shortcuts window (F7) has a nice feature to filter for e.g. "month", which then gives all month actions:

![image](https://user-images.githubusercontent.com/3529789/96086069-fbbee200-0ec1-11eb-9a3e-930f3b639a7a.png)

**Describe the solution you'd like**
When I double-click on a shortcut, I would like that action to trigger. E.g. when click on "subtract one draconic month", Stellarium executes it.

This could be a controversial issue, because it is not the task of the shortcut window to do this kind of things. But I see no immediate use for a double-click in this dialog, although plenty of counter arguments could be given (e.g. reset the action to default).

**Describe alternatives you've considered**
Assign a shortcut, press it, reassign the shortcut to a different key, press it, etc.

**Additional context**
Note that the arrangement of a dialog having actionable entries is a very nice alternative to execute actions.

A similar approach works in HiPS:
(note that the user needs to check rather than double-click, but this could easily be added; in fact, there is currently a small ergonomy issue in this behaviour as the user is forced to click inside the checkbox)
![image](https://user-images.githubusercontent.com/3529789/96086280-61ab6980-0ec2-11eb-9ace-cddd3a79e955.png)

in Oculars:
![image](https://user-images.githubusercontent.com/3529789/96086363-81db2880-0ec2-11eb-8ef3-7cf919422949.png)

In sats:
![image](https://user-images.githubusercontent.com/3529789/96086415-9b7c7000-0ec2-11eb-9d6d-362529b6ed0c.png)

**Comment by alex-w** [comment]
Double-click in shortcut dialog is enable editor of shortcut

**Comment by axd1967** [comment]
> Double-click in shortcut dialog is enable editor of shortcut

Dang - you mean this

https://github.com/Stellarium/stellarium/blob/ac0bfee840ccd2ae006256784cfdaa858bb39eec/src/gui/ShortcutsDialog.cpp#L307-L308

Back to the drawing board.

**Comment by alex-w** [comment]
Yes, you mark correct LOC
