### ISSUE TITLE
Not being able to select invisible stars

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1331]
I sometimes use the "magnitude limit" to help determine which stars will be visible from my area at what time. The problem is, when I activate it, Stellarium still allows hidden stars to be selected. Preferably, that would not happen. When the limit magnitude is set to +2, then stars of magnitude +3 should not be selectable from mouse clicking.

**Comment by alex-w** [comment]
Do you use Oculars plugin or not?

**Comment by Atque** [comment]
@alex-w This is without Oculars plugin.

**Comment by gzotti** [comment]
Fixed by 1db1f409280b121983e0142daa460afa900f9e20

**Comment by alex-w** [comment]
Please check version 0.20.3-5f954765e3: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
