### ISSUE TITLE
Ascom Sync HEQ5 Pro

### ISSUE THREAD

**Issue by swilleter** [Stellarium/stellarium#1337]
I've installed the latest version of stellarium and connected my HEQ5 Pro through ASCOM. When keying Ctrl + 1 it performs the goto OK but if I try to Sync with Ctrl + Shift + 1 nothing happens unless I am in Plugins with the telescope selected.

When I run the telescope control from the bottom menu on the main screen the goto and sync work OK. so I can get around the Shortcut Key to Sync but it's just a bit more hassle.

I'm uptodate with Windows 10 and using a HITEC eqdirect cable and previously used StellariumScope.

**Comment by alex-w** [comment]
Do you tried run sync command on selected object?
