### ISSUE TITLE
Close button on any subwindow does not work

### ISSUE THREAD

**Issue by WildPenquin** [Stellarium/stellarium#1338]
Close button of none of the internal windows / subwindows / dialogs (whatever one chooses to call them) does not work.

As a workaround, one can hit the graphical button that opened the dialog or shortcut key again to close. Some windows do not have a button to open them (for example, the one to modify keyboard shortcuts), and if the user does not know or remember the shortcut key, such dialog can be very difficult to close - or if the shortcut key is unset, or does not exist, impossible.

### Expected Behaviour

Clicking the "X" button at the right corner of any dialog in the GUI via mouse should close the dialog in question.

### Actual Behaviour

The dialog does not close by clicking the "X".

### Steps to reproduce

1. Open any dialog: for example, click any of the left-bottom corner icons, or press F1 (assuming default shortcut keys are set).
2. Press "X" button with mouse cursor.

### System
* Stellarium version: 0.20.3-1
* Operating system: Arch Linux
* DE: KDE Plasma
* Graphics Card: AMD Rx Vega 64
* Screen type (if applicable): 3440x1440 (full screen) or windowed (doesn't matter)

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/5411058/log.txt)

Not sure if that log file is complete; I tried to enable logging as per the [FAQ](https://github.com/Stellarium/stellarium/wiki/FAQ#Logfile_has_no_details) but that had no effect on the output. FWIW, that file already exists and has loads of rules already, and I added the wildcarded rules (with "*") to the end of the file - I'm not sure how the file handles wildcards in this case. In any case, the perhaps the FAQ should be upgraded so that it has Stellarium-specific log rules to not mess with other log rules on systems, which use qt quite widely (such as KDE Plasma).

**Comment by WildPenquin** [comment]
Ah, indeed already reported. I tried searching but didn't find the right words to search with :-) . Apologies!

**Comment by alex-w** [comment]
Please check version 0.20.3-cc61c2cd7c: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
