### ISSUE TITLE
Remote Sync in Stellarium

### ISSUE THREAD

**Issue by Stallare** [Stellarium/stellarium#1342]
I'm unable to connect to the server host address in client mode - Server mode port not active. this is presenting an error in Nina image source (Nasa Sky Survey ) 

can you assist please.

Kind Regards

**Comment by alex-w** [comment]
Are you sure that you need Remote Sync plugin? This plugin synced data between Stellarium’s instances.

**Comment by gzotti** [comment]
Please consult the Stellarium User Guide, section 12.7, and then describe your issue.
