### ISSUE TITLE
ability to jump to random location for celestial Nav game and practice

### ISSUE THREAD

**Issue by johnbellora** [Stellarium/stellarium#1345]
A great fun feature wound be to what amounts to is a game. Add Two button on the main screen when in the navigation mode that would randomly place you anywhere in the world every time you click it while hiding the longitude and latitude. This would pop up when using the Navigation option which would allow one to practice celestial navigation or make a game out of it with friends. Once determined longitude and latitude by what ever means, that operator can then uncover the Longitude and latitude from your screen and verify how close he was able to come. Clicking the button again send you off to another location anywhere in the world. The the Longitude and latitude disappear again until you choose to uncover it by clicking another button. An added feature would be once uncovered. A third button would zoom to that location in Google Earth.

I actually do this already on my own. using another planetarium program who the author was kind enough to modify for me. It does not however have the feature of zooming to the location on Google earth once the task was completed. I do that on my own for fun.

Best Regards
John Bellora

**Comment by gzotti** [comment]
This is something that IMHO does not really fit into the main program. You could program this as website and control Stellarium via (CORS enabled) RemoteControl API. 

Just jumping to a new location can be made with a script, and assigned to a hotkey.

**Comment by alex-w** [comment]
I can write a script to jump to random location and hiding location info from the GUI. But what about elevation of the random location?

**Comment by gzotti** [comment]
Well, for an astronav application we can safely assume altitude=0. For any random location, we would need an altitude raster to sample, at least with arcminute precision (21600x10800) to be useful. Another such raster could help finding if random point is on land or sea. Another raster (or better, GIS shapefile evaluation) could auto-identify timezones. Big wishlist...

**Comment by johnbellora** [comment]
Always be 0  or can be 2 meters as if someone standing at sea level. Either way.
Than you! 
John


-----Original Message-----

**Comment by alex-w** [comment]
Please check version 0.20.3-50e9bca0fd: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by alex-w** [comment]
@johnbellora did you tested the changes in Stellarium?

**Comment by johnbellora** [comment]
i tested the decimal calculation on the  LHA & GHA ans so far it seems fantastic. Did you add the option to jump to a random location? I have not tried this if you did..
John


-----Original Message-----

**Comment by johnbellora** [comment]
please send me the link to the latest additions


-----Original Message-----

**Comment by alex-w** [comment]
Please try shortcut Ctrl+D, L or run script “random_location.ssc” in the Scripts tab

**Comment by johnbellora** [comment]
for some reason this is not working for me. Do I simply press down Ctrl & "D" at the same time with the left hand and then right hand presses "L"?
John


-----Original Message-----

**Comment by axd1967** [comment]
it's ctrl+D, let go, then 'l' (small capital ell, without shift)
