### ISSUE TITLE
The screen is flickering

### ISSUE THREAD

**Issue by Rainer-Borchmann** [Stellarium/stellarium#1346]
Hi,
i have my notebook (Lenovo t 480 32 GB) updated to Windows 10 2H and stellarium to 20.3   . both on a vergin installation.
After starting stellarium the screen is flickering twice in ~10 seconds.
On Windows 10 2004 and Stellarium 20.1 i did not senn this Behavior.
What i shall do to fixed?

Bye
Rainer Borchmann

**Comment by gzotti** [comment]
Without a proper report (https://github.com/Stellarium/stellarium/wiki/FAQ#reporting-a-crash) we cannot do anything but guess.

- https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#opengl-problems-with-intel-graphics ?
- Run ANGLE mode?
- Update GPU drivers?

**Comment by Rainer-Borchmann** [comment]
Great, thank you for helping me , even on a sunday in Corona-times.
And YES in ANGLE-Modus it runs perfectly.
Bye
Rainer
