### ISSUE TITLE
Mystery moving star near xi UMa 

### ISSUE THREAD

**Issue by perseus245** [Stellarium/stellarium#1347]
Hi!  First time contributor.  Looked through the open listings, and found another mystery star (#1192) .  This item may be related, but as it's a separate star, I thought it might call for a separate entry.

### Expected Behaviour
I'd expect a star of magnitude 4.25 to have a name. 

### Actual Behaviour
Found a bright star with no Hipp or other ID.  Just 'star', as in 1192. 
The unnamed star in question is a 4.25 mag star, hidden today behind xi UMa (Alula Australis, mag 3.75).  But the unnamed star has a strong apparent motion; in Ptolemy's day, it would have been clearly distinct.

### Steps to reproduce
The figure shows screen-caps of the three paws of the Bear over a few thousand years.  

![image](https://user-images.githubusercontent.com/73799065/97816575-6ce8ee00-1c53-11eb-8c1f-492d7303ffe0.png)

I've looked for this star using other planetarium software, without result.  Not an exhaustive search, but enough to make one wonder. 
Comment:   In the course of development of software like Stellarium, a few artificial stars in the database, with specific developer-defined properties would be useful in evaluating the capabilities and limitations of code-in-progress.  
Is is possible that this fictitious nameless star was inserted into a core database during early development for QC purposes?  
If so, it might further be true that other 'mystery stars' are similar artifacts of development. 

### System
 I mostly use Stellarium 0.15.0, running under Windows 10 on an HP Pavillion laptop designed for Win7 (Intel i5 processor).  Key points reported here also are seen using Stellarium 0.19.3, running under Win10 on a separate machine.  Based on the thread in 1192, this seems to be not a hardware matter, but a database issue.

### Logfile 
First time visitor here.

**Comment by gzotti** [comment]
Stellarium has Hipparcos and other catalogues. This looks like yet another double entry with different data. The spurious and xi overlap in 2000 coordinates.  
By far not all stars have proper names. 
I have not seen anything that would indicate the addition of "QC objects". Just that nobody ever verified each single entry of the star catalogues.

**Comment by perseus245** [comment]
Thanks for the reply!
Some comments and clarifications:

'Stellarium has Hipparcos and other catalogues'    'By far not all stars have proper names'
Hipparcos claims to include all stars brighter that magnitude 7, and many more down to 11.  Hence, I'd expect a star listed as magnitude 4.25 to have a HIP designation.

'another double entry with different data'  
To clarify:  You're saying that this 'spurious' star is, in fact, not a real star but a faulty/errant entry in the database?  
(That's the conclusion I've come to.  For my own purposes, **this is the point I need to confirm**.)

* * * * * * * *   

I don't really need to know how or why an error occurred here.  
However, when faced with errors I'm just wired to wonder about causes.  
'QC objects' -- that was a poor description; my bad.  'Test objects' added to the star database for development purposes would better describe what I can easily imagine occurring during early stages of the development of Stellarium many years ago.  

Another point which has me thinking that this is an object created and placed by a team of coders and astronomers is the fact that this artificial star is hidden in the modern sky underneath xi UMa.  The southernmost star in the right hind paw of the Great Bear was the first double-star system to be identified (Herschel, 1780).  Maybe it's all just coincidence; but it seems to me that a team of coders and astronomers looking to hide an extra star behind an existing object might have purposefully chosen xi UMa to hide their fabricated test star. . .
