### ISSUE TITLE
sat plugin: orbits of invisible sats should also be invisible

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1349]
### Expected Behaviour

Orbits of invisible sats are hidden

### Actual Behaviour

Orbits are shown, which can produce a very cluttered display.

### Steps to reproduce

1. select a sat that is eclipsed
1. check "hide invisible artificial sats"

bug: observe that the symbol is hidden, but the orbit is still shown.

## proposed solution
one of
- hide the orbit
- add a separate button to show/hide orbits of invisible sats

### System
* Stellarium version: Stellarium 0.20.3-34d7dbd5df [master]

**Comment by alex-w** [comment]
Please check version 0.20.3-50e9bca0fd: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
