### ISSUE TITLE
Lunar magnitude formula incorrect?

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1350]
Comparing Stellarium to other planetaria (mainly Cartes du Ciel, but also some others such as CyberSky 5) shows that Stellarium is the odd man out when it comes to displaying the lunar apparent magnitude. A full supermoon has about -12.44 in Stellarium, while in the other programs the value is more like -12.7. The difference is more prominent when you compare full vs half moon. In Cartes du Ciel, the half moon is about -10, while in Stellarium its in -11. That means the difference between a full and half moon in Stellarium is about 1.4 magnitude (a factor 3.8 difference), while in the other programs it's 2.7 (a factor 12.2 in difference).

Stellarium also seems to lack the light boost effect of a full moon, which is present in the other programs I mentioned. The difference between a 95% and 100% illuminated moon in Stellarium is about 0.12 (factor of 1.11), while in Cartes du Ciel, it's a difference of 0.8 (factor 2.12).

This graph shows lunar magnitude as a function of its phase:
![alb01](https://user-images.githubusercontent.com/37028368/98210072-4c18e500-1f40-11eb-9972-2ad55d5f9868.jpg)

I guess there are better formulae online, but sadly I can't provide one.

**Comment by gzotti** [comment]
Yes, there must be better formulae, but sadly we have not found them yet. The current computation for the Moon is still the generalized model from Stellarium's early ages. Just develop an algorithm from your graph...

**Comment by Atque** [comment]
@gzotti It "should" be fairly easy considering several planetaria use the same formula. I'd love to help but I think my abilities are inadequate.

I have no idea how to validate this since I lack mathematical and programming experience apart from a few university courses, but a simple Google search gave this formula (Allen, 1976):
https://astronomy.stackexchange.com/questions/10246/is-there-a-simple-analytical-formula-for-the-lunar-phase-brightness-curve

It has the brightness boost.

**Comment by gzotti** [comment]
Thanks. These are at least some hints. Of course, the PASP paper may also contain a solution.

**Comment by gzotti** [comment]
Next reference for you or SB else to locate: Whitaker, E. A. 1969, in Analysis of Apollo 8 Photography and Visual Observations, NASA SP-201, 38.

**Comment by 10110111** [comment]
> Edit: It appears I can't read properly. It does NOT have the brightness boost. I better keep on searching.

Actually, although the paper by Allen doesn't have the opposition surge, the very link to Astronomy.SE you've posted does suggest a modification. Although it looks very ad hoc (and unreferenced), it might be better than nothing.

The final form would look like this:

   m = − 12.73 + 1.49|𝜓| + 0.043𝜓<sup>4</sup> − 2.5 log<sub>10</sub> max(1, 1.35 − 2.864|𝜓|),

where 𝜓 is phase angle in radians. The term with max is the opposition surge term.

**Comment by alex-w** [comment]
This is fun, but CdC is followed the table of lunar magnitudes is derived from relative intensities in Table 1 of M. Minnaert (1961) for compute Moon’s magnitude: https://github.com/pchev/skychart/blob/98b7ac40b660beb6acd33d3d183e401e9fe76388/skychart/cu_planet.pas#L1315

**Comment by 10110111** [comment]
But this table doesn't include opposition surge:

![Screenshot - 211120 - 22:53:31](https://user-images.githubusercontent.com/6376882/99886317-98586a80-2c4c-11eb-93a2-f9ca7c1cdb7b.png)

**Comment by Atque** [comment]
@10110111 I think your formula does not take distance into account. This is a main flaw in e.g. Cartes du Ciel's formula. A full micro moon is equally bright as a full supermoon, while in reality, the difference is roughly 30% (0.3 magnitude).

**Comment by 10110111** [comment]
> I think your formula does not take distance into account

I just omitted the (Δ<sub>0</sub>/Δ)<sup>2</sup> term that's also present in your link.

**Comment by Atque** [comment]
@10110111 Ah, I really need to read more carefully. Well, then I guess we have a better formula ready? If not perfect, it should be better than the formula used today.

**Comment by gzotti** [comment]
Thanks for all the input. I will be available again around December 15. Really interesting that there is apparently no easily found formulae since Minnaert.
