### ISSUE TITLE
Single pink panel in custom landscape

### ISSUE THREAD

**Issue by GaryMCurran** [Stellarium/stellarium#1352]
### Expected Behaviour
Normal operation of the user provided landscape photos
### Actual Behaviour
Describe or maybe attach a screenshot?
I upgraded to the latest version, 0.20.3 64 bit, and I have a custom landscape.  One panel in that landscape is a pink square.  It has not done this before on any other versions I've used this custom landscape on, and I've been using it for a few years.
As the daylight increases the pink fades away.  Please seen enclosed screen shot.
![stellarium pink](https://user-images.githubusercontent.com/74038041/98331383-50311b00-1fb1-11eb-98df-00fdc7367fd4.jpg)

### Steps to reproduce
Whenever I open Stellarium with this landscape only.
### System
* Stellarium version: <Stellarium-0.20.3-win64.exe>
* Operating system: <Windows 10 Pro>
* Graphics Card: <Manufacturer (AMD)

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
This is not a bug in the planetarium, but this is a bug in textures of the landscape ;)

**Comment by gzotti** [comment]
Look into landscape.ini and make sure entries like
`light<n>=lighttexture.png
`
are either correct or don't appear.

**Comment by GaryMCurran** [comment]
> This is not a bug in the planetarium, but this is a bug in textures of the landscape ;)
> 
> P.S. The pink color was introduced for visualize troubles with textures in the landscapes

I guess my question is then 'Why in all the previous versions did I not have any issues with that particular image?'  What is it about the image that may be causing this?

I'm going to upload the 'bad' photo and the .ini file in a .zip file, and if you can find something wrong with it, I sure would like to know.

Thanks in advance.
[battletest.zip](https://github.com/Stellarium/stellarium/files/5500515/battletest.zip)

**Comment by gzotti** [comment]
When I wrote 

> Look into landscape.ini and make sure entries like
> `light<n>=lighttexture.png`
> are either correct or don't appear.
> 

I meant you edit landscape.ini and either fix or remove that line.  In your case, remove the line

`light4 = guereins8-lgt.png`

when you don't use this PNG file in your landscape. The file is most likely useless and missing in your context, and therefore shown as pink square to indicate a problem. (In other similar problems with missing textures, the program used to crash. Now we urge the user to fix such problem with that pink tile.) 
In most cases, following the documentation is a good first hint to follow.

**Comment by GaryMCurran** [comment]
Georg,
THANK YOU!  I'm sorry I didn't understand at first what you wanted.  I thought that line had to be there, even though I didn't have the file for it.

But, removing the line removes the pink panel.  I understand a little bit better now.  I appreciate the help and the patience.

Warmest regards,

Gary
