### ISSUE TITLE
Tab Windows Size

### ISSUE THREAD

**Issue by JavierIbarraP** [Stellarium/stellarium#1356]
Cannot change the size of different tab windows. For example: Plugins tab is to large and cannot see the complete window missing configurations button or ticking the Load at start option

**Comment by alex-w** [comment]
Please fill system info:

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

**Comment by gzotti** [comment]
We recommend 1024x768 as bare minimum screen size for the current iteration of our GUI. The wiki has some hints for smaller screens.
https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#screen-issues

**Comment by JavierIbarraP** [comment]
It is an HP Pavilion x360- 14 with 1920 x 1080. So, tiene should be another reasonEnviado desde mi Galaxy
-------- Mensaje original --------De: Georg Zotti <notifications@github.com> Fecha: 9/11/20  18:48  (GMT+01:00) Para: Stellarium/stellarium <stellarium@noreply.github.com> Cc: JavierIbarraP <javier_ibarra@telefonica.net>, Author <author@noreply.github.com> Asunto: Re: [Stellarium/stellarium] Tab Windows Size (#1356) 
We recommend 1024x768 as bare minimum screen size for the current iteration of our GUI. The wiki has some hints for smaller screens.
https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#screen-issues

**Comment by JavierIbarraP** [comment]
Stellarium 0.20.3Windows 10Intel UHD graphicsIt is an HP PAVILION X360 14 INCHScreen 1920 x 1080Enviado desde mi Galaxy
-------- Mensaje original --------De: Alexander Wolf <notifications@github.com> Fecha: 9/11/20  18:42  (GMT+01:00) Para: Stellarium/stellarium <stellarium@noreply.github.com> Cc: JavierIbarraP <javier_ibarra@telefonica.net>, Author <author@noreply.github.com> Asunto: Re: [Stellarium/stellarium] Tab Windows Size (#1356) 
Please fill system info:
System

Stellarium version: <Name of downloaded installable file?>
Operating system: <Name, version number>
Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
Screen type (if applicable): Resolution, HighDPI, scaling

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#windows-gui-scaling

**Comment by JavierIbarraP** [comment]
Georg, 

 

Perfect. Now screen sizes are great.

 

Thanks

 

Javier

 

De: Georg Zotti <notifications@github.com> 
Enviado el: martes, 10 de noviembre de 2020 20:13
Para: Stellarium/stellarium <stellarium@noreply.github.com>
CC: JavierIbarraP <javier_ibarra@telefonica.net>; Author <author@noreply.github.com>
Asunto: Re: [Stellarium/stellarium] Tab Windows Size (#1356)

 

https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#windows-gui-scaling
