### ISSUE TITLE
Screen goes Black whenever a fly-over hint appears

### ISSUE THREAD

**Issue by pack-rat999** [Stellarium/stellarium#1357]
-->

### Expected Behaviour:  
When cursor hovers over buttons and times, a flyover hint appears.

### Actual Behaviour
 When the flyover tries to appear, the screen goes black for 1-2 seconds, then returns and the hint is visible.  When I move the cursor off the button, the screen goes black again for 1-2 seconds.  I have searched for a way to disable the flyover hints.

### System
* Stellarium version: stellarium-0.20.3-win64.exe
* Operating system:  Win10 ver2004
* Graphics Card: Intel HD Graphics 630
* Screen type (if applicable): Samsung SyncMaster 2233 set to 1920x1080

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/5520238/log.txt)
[log.txt](https://github.com/Stellarium/stellarium/files/5520260/log.txt)

**Comment by gzotti** [comment]
Have you tried ANGLE mode?

**Comment by pack-rat999** [comment]
> Have you tried ANGLE mode?

Thanks for your suggestion.  I was not familiar with ANGLE mode, but it appears to fix my problem.  Do I give up any functionality with ANGLE Mode?  If not then I can stick with it and be happy.

**Comment by gzotti** [comment]
No, ANGLE should look&feel exactly the same. It circumvents problems with some graphics drivers.

**Comment by pack-rat999** [comment]
Thanks for your help!  Problem solved.

**Comment by CapitanCaliban** [comment]
This exact problem appears on my computer. Stellarium 0.21.3. Have tried every mode, including angle, nothing solves the problem. I have the latest graphics drivers. Win10 64-bit. Intel UHD Graphics 620. Laptop with properties well exceeding the requirements.
[log.txt](https://github.com/Stellarium/stellarium/files/7876722/log.txt)

**Comment by gzotti** [comment]
We have had numerous issue reports, all around Intel GPU. This is certainly nasty, but solving Intel's GPU driver problems is out of our hands. Also other graphics programs are reportedly affected.

**Comment by CapitanCaliban** [comment]
But why does it work with older versions but not the latest?

Den sön 16 jan. 2022 kl 13:30 skrev Georg Zotti ***@***.***>:

**Comment by alex-w** [comment]
@CapitanCaliban please check all versions between 0.20.4 and 0.21.3 - when problem is coming?

**Comment by CapitanCaliban** [comment]
I went backwards fortunately and verified that stellarium-0.21.2-win64 works in angel-mode. 
Then I tried 0.21.3 once more and it still don't work in no modes. 
I uninstalled everytime before I installed.

**Comment by alex-w** [comment]
@CapitanCaliban Please try to disable aberration in version 0.21.3 and check it again.

**Comment by CapitanCaliban** [comment]
If you mean "Include aberration" I have now tried it both enabled and disabled, saved the settings and restarted Stellarium in between with the same result. Im sorry, but I dont have time to uninstall and reinstall anymore, have work to do in the program so I just use the old version. Thanks!
