### ISSUE TITLE
pinhole planetarium with 32 sides

### ISSUE THREAD

**Issue by hanjung95** [Stellarium/stellarium#1358]
I want to make a pinhole planetarium with 32 sides, but I need JPG files and other files to print 9.5-level celestial data to fit 32 sides. How can I get it?

**Comment by gzotti** [comment]
You can configure screenshots to be stored as JPG and various projections. Perspective mode may be most useful in this application. Working out the angles is left as exercise for you.

**Comment by hanjung95** [comment]
> You can configure screenshots to be stored as JPG and various projections. Perspective mode may be most useful in this application. Working out the angles is left as exercise for you.

How can I use Perspective mode? Where can I use it in Stellarium? I can't find it.

**Comment by alex-w** [comment]
See F4 -> Sky Tab
