### ISSUE TITLE
core.quitStellarium() does not close Stellarium

### ISSUE THREAD

**Issue by andrey-nakin** [Stellarium/stellarium#1363]
I have a script that ends with the following method call:

`core.quitStellarium();`

Stellarium is started by this command:

`stellarium --startup-script my-scrpt.ssc`

Stellarium does not close on the script end.

**Comment by alex-w** [comment]
Please share your script - I cannot reproduce the issue

**Comment by alex-w** [comment]
OK, I can reproduce the problem, thanks for report!

**Comment by andrey-nakin** [comment]
The patch helps. Thanks a lot!
