### ISSUE TITLE
adding "transit time"

### ISSUE THREAD

**Issue by johnbellora** [Stellarium/stellarium#1365]
I was hoping that along with LHA & GHA informations in the Navigation mode,  another very helpful line would be the hours, minutes and seconds until transit of the selected star. Not only transit time but how much time until transit. Please add this. I will make another donation so that you all won't to tired of me asking for mods.

Best regards

John Bellora

**Comment by alex-w** [comment]
But transit time for selected object already present in the info block in HM format (by low-accuracy computations).

**Comment by alex-w** [comment]
>Not only transit time but how much time until transit.

Please share definition for it.

**Comment by johnbellora** [comment]
The transit would be the exact moment a star passes East to West above the celestial pole & West to East transit below the celestial pole. Two added lines of information that are real 
John Belloratime being updated just as the LHA and the GHA are as the starts rotate in the circumpolar clock from the observers location. 

I am writing a program that that will tell longitude and latitude based on the moment a star transits. I use your program to verify results. Just below LHA I would like to see " amount of time in minutes & seconds until the high lighted NAV star transits by rotating and pass east to west and another line that indicates  the amount of time until the highlighted NAV star transits west to east viewed by the observers position.
I am sorry to request so much but i will make another donation today.
Best RegardsJohn Bellora


-----Original Message-----From: Alexander Wolf <notifications@github.com>
To: Stellarium/stellarium <stellarium@noreply.github.com>
Cc: johnbellora <bellora@aol.com>; Author <author@noreply.github.com>
Sent: Wed, Nov 18, 2020 7:49 am
Subject: Re: [Stellarium/stellarium] adding "transit time" (#1365)


Not only transit time but how much time until transit.
Please share definition for it.—

**Comment by johnbellora** [comment]
Hello,
 Yet is is but I am hoping for more accuracy and the West to East Transit as well n. I need  down to the second if possible. Please see attached.
John



-----Original Message-----

**Comment by johnbellora** [comment]
sorry  this is corrected


-----Original Message-----

**Comment by alex-w** [comment]
Github do not allow attachments in emails - please use web interface to share the files

**Comment by alex-w** [comment]
> The transit would be the exact moment a star passes East to West above the celestial pole & West to East transit below the celestial pole. Two added lines of information that are real time being updated just as the LHA and the GHA are as the starts rotate in the circumpolar clock from the observers location.  

So, you want to see time of crossing celestial meridian by selected star in HMS format (twice events per day)

> I am writing a program that that will tell longitude and latitude based on the moment a star transits. I use your program to verify results. Just below LHA I would like to see " amount of time in minutes & seconds until the high lighted NAV star transits by rotating and pass east to west and another line that indicates  the amount of time until the highlighted NAV star transits west to east viewed by the observers position. 

If I correct understand, then you want to see info, which given plugin Observability Analysis for selected star - please check it.

**Comment by alex-w** [comment]
@johnbellora any feedback please

**Comment by alex-w** [comment]
@johnbellora any feedback please

**Comment by axd1967** [comment]
@johnbellora as @alex-w indicates, the time until transit is indeed shown by the Observability plugin:

![image](https://user-images.githubusercontent.com/3529789/133255851-fd73a2f8-6ecf-4b37-82d1-e04abffce764.png)

**Comment by alex-w** [comment]
> Hello Alex, I am having a hard time signing into GITHUB. It does not accept my save password and rejects the email send security code from GitHUB.. I would like to request to please add earth's shadow in proper ac degrees diameter. This is wonderfully useful and educational to watch each full moon and see how far the shadow misses the earth and to watch the movement pattern as the earth  shadow zips by the moon every month. The planetarium software Aciqra has this feature and it is unique and great.  

Umbra and penumbra are implemented in main program (for the Moon) and in the Satellites plugin (for satellites or fixed distance) already

**Comment by johnbellora** [comment]
I will try it to see how it looks.
John


-----Original Message-----

**Comment by gzotti** [comment]
A basic astronomical coordinate is the hour angle of the object at current location. 0h means due south (or better, crossing the meridian). This is given in the regular coordinate set. 21h43m means you have 2h17m of Sidereal time left until transit. 

Can we close this, or what is missing?

**Comment by johnbellora** [comment]
Yes please close. I really appreciate you working with me on my questions.
Best regards
John Bellora
    On Saturday, December 9, 2023 at 10:15:44 AM GMT-8, Georg Zotti ***@***.***> wrote:  
 
 


A basic astronomical coordinate is the hour angle of the object at current location. 0h means due south (or better, crossing the meridian). This is given in the regular coordinate set. 21h43m means you have 2h17m of Sidereal time left until transit.

Can we close this, or what is missing?

**Comment by johnbellora** [comment]
Hello George,
Hope all is well. Please view this screen shot. I think if is a bug.

Best Regards
John Bellora
    On Saturday, December 9, 2023 at 10:15:44 AM GMT-8, Georg Zotti ***@***.***> wrote:   

 


A basic astronomical coordinate is the hour angle of the object at current location. 0h means due south (or better, crossing the meridian). This is given in the regular coordinate set. 21h43m means you have 2h17m of Sidereal time left until transit.

Can we close this, or what is missing?

**Comment by alex-w** [comment]
The screenshot is not attached

**Comment by gzotti** [comment]
You must upload the screenshot on github, it is filtered away from reply emails.
