### ISSUE TITLE
Search list adjust

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#1367]
I think the completly matched result should rank on top rather than history search.

For example, search "NGC 5581" first. Then enter "NGC 55", the [weekly release program](https://github.com/Stellarium/stellarium-data/releases/download/weekly-snapshot/stellarium-0.20.3-50e9bca0fd-win64.exe) marked "NGC 5581" on top, which should be adjusted.

**Comment by alex-w** [comment]
No, the current behavior of Search Tool is correct - it showing firstly items from history as was requested in #1050

**Comment by ultrapre** [comment]
it giveconfig item? decide to show history list or not.

**Comment by ultrapre** [comment]
For example, search M10 to M19, and then you have to find M1 on the bottom

**Comment by ultrapre** [comment]
I also remember my tour to search one by one at night's session. But mistake always was cause by NGC prefix. I think history search is good, and I always directly turn up and down to locate without input. 

On my *Stellarium Mobile* adaptation, I add the function that showing NGC item on top and Messier next when inputting pure number, because I know 99% amatuers prefer them.

**Comment by alex-w** [comment]
> it gives config item? decide to show history list or not. For example, search M10 to M19, and then you have to find M1 on the bottom.

Depth of history is configurable of course

**Comment by ultrapre** [comment]
Okay, making balance maybe difficult.
