### ISSUE TITLE
Add support for ecliptic and equatorial grids and data (and related items) of custom epoch

### ISSUE THREAD

**Issue by jamadagni** [Stellarium/stellarium#1369]
In relation to my work related to traditional Indian astronomy, I need to work with a sidereal grid which is most simply implemented as an ecliptic grid of a fixed epoch (in 285 CE per one tradition but there may be other opinions). This is needed if one is to use Stellarium both for teaching and research of traditional Indian astronomy.

I had previously tried to look into this possibility with Stellarium: https://sourceforge.net/p/stellarium/mailman/message/36052781/ but I was daunted by the complexity of the code and backed off. 😔

Now I am wondering if we already have support for displaying the grid etc of date vs J2000, it might not be trivially extended to a custom epoch the user can select rather than having to be implemented from deeper down.

I believe that the relevant support should be added in (at least) two places:

  - [ ] Sky/viewing options > Marking
  - [ ] Configuration > Information

IMO we can just replace J2000 by “custom epoch” where the custom epoch should be specified under Configuration > Time and be applicable throughout. This custom epoch defaults to J2000 for smooth transition of existing behaviour and those like me who wish for something else should just change it. Obviously it should be stored with the application settings and remembered for next startup.

I do not foresee a requirement of having multiple non-current epochs to be displayed and that would clutter the interface too much, so am suggesting replacing J2000 by a configurable custom epoch which defaults to J2000.

I hope and am really eager to see this implemented so that I can use Stellarium for teaching traditional Indian astronomy! 😊😊

**Comment by gzotti** [comment]
We will not replace J2000 because 100% of astronomers need it. Indian astronomy is highly interesting in itself, but this particular request asks for a separate plugin, even if just a single feature. Some other features particular for Indian traditions and cultures could also be handled by this plugin.

**Comment by jamadagni** [comment]
Hello. Thanks for your response.

The suggestion wasn't to *remove* J2000 but since it is also a fixed epoch, the suggestion was that it can be the default (and reset-to-able) value for a configurable fixed epoch, which would solve the requirement. Those who are working with J2000 will continue to do so. Those who are working with Indian astronomy would not be using J2000, at least not at the same time. 

The suggestion is made keeping in mind the need to avoid clutter. Under *Sky/viewing options > Marking*, the following items are already duplicated for J2000 vs of-date:

1. Equatorial grid
2. Ecliptic grid
3. Equinoxes
4. Solstices
5. Equator
6. Ecliptic
7. Celestial poles
8. Ecliptic poles

It is better to avoid adding 8 more items for custom epoch. Likewise under *Configuration > Information*, RA/dec and Ecliptic coords are duplicated for J2000 vs of-date.

Changing the UI to read in all these locations *(fixed/J2000)* would avoid adding new entries in all these places, and under *Configuration > Time*, we can have a UI:

Fixed epoch:  [ ]  J2000  [ ] Custom: YYYY-MM-DD HH:MM

which would solve the requirement.

Re plugin: I am not sure what other features are required for Indian astronomy. Celestial names and constellation shapes etc are already covered under Sky culture IIRC. This is about the mathematical part of it rather than cultural part of it.

**Comment by gzotti** [comment]
J2000 is the standard equinox with no computations required. Equinox of date requires computation of corrections applied to the date currently in use. Arbitrary equinox requires computing and drawing those. So we would at least need another one and let the user decide if he wants to use it for B1900.0, B1950.0, J2050.0 (those would be useful for "scientific" astronomy and are somehow on a looong unpublished list of possible things to add when more urgent issues have been solved), or any arbitrary date like -284 more targeted towards traditional and cultural astronomy. I understand you'd like to have it. Again, the fastest way to get it is DIY.

**Comment by alex-w** [comment]
This is  maybe strange question, but why just not enable showing required grids, lines and points (Equatorial grid, Ecliptic grid, Equinoxes, Solstices, Equator, Ecliptic, Celestial poles, Ecliptic poles) on date and set wanted date?

**Comment by gzotti** [comment]
As I understand, traditional Indian astronomy uses -284 as their reference year, just like modern astronomers use J2000. But they would refer all coordinates to J-284, even if computed for the present time. This is so special that I would favor having this as optional piece, a.k.a. plugin.

**Comment by alex-w** [comment]
J-284, not B-284?

**Comment by gzotti** [comment]
Whichever. Bessel and Julian years are different conventions, and I don't know the Indian definition. Let's call it I-284. :-)

**Comment by gzotti** [comment]
This may be equal or closely related to to #437. I must apologize for misreading, the epoch where Spica is at 180° ecl. longitude is indeed +285.
