### ISSUE TITLE
loss of focus when selecting telrad tool

### ISSUE THREAD

**Issue by dudrea** [Stellarium/stellarium#137]
Version 2.18.0 Windows 10
Regards

**Comment by alex-w** [comment]
Please give detailed description what exactly you are expected to see and what exactly you are see.

P.S. Version 2.18.0 is not exist!

**Comment by gzotti** [comment]
Timeout.

**Comment by CharlesCowles** [comment]
I've noticed a similar-sounding issue with the Telrad.  I've got version 0.19.2 on a Windows 10 PC.  My Oculars are set up to zoom without selecting an object.  If I select the Telrad icon right after launching Stellarium (because I want to orient myself and see where my virtual scope is pointed), my full-sky view zooms out to the maximum amount allowed (FOV 0.00139 degrees).  As a work-around, I can pick any part of the sky, select ocular (CTRL+O), de-select ocular (another CTRL+O, bringing me back out to FOV 60 degrees), and then select the Telrad.  After going in and out of ocular once, the Telrad toggles on and off normally (without zooming way out).
I tested and this behavior happens whether I have checked "Enable only if an object is selected" or not.

**Comment by dudrea** [comment]
Thank's
Same for me with 0.1.2 version on windows10 !

**Comment by alex-w** [comment]
@CharlesCowles Hmm... it's strange, but I cannot reproduce issue on linux. @gzotti can you check it on windows?

**Comment by gzotti** [comment]
After starting, the first mouse click goes to the Telrad icon. Stellarium zooms _in_ to 10 degrees FOV. 
This is both with and without the option "Enable only if an object is selected".

I can then zoom in or out. Everytime on activation of the Telrad, the view zooms to 10°, which seems to be a pretty useful setting. I cannot confirm any issue here.

To not zoom, or zoom to some other FOV, an additional "[ ] zoom to... degrees" (boolean plus value) could be added.

**Comment by alex-w** [comment]
@CharlesCowles please attach your oculars.ini file

**Comment by dudrea** [comment]
Thanks to all persons.
I've just put replaced true by false in "use_telrad_fov_scaling=false"
It"s better know, except a slight position shift when activating telrad image....
ocular.ini (changed to .txt) joined


[ocular.txt](https://github.com/Stellarium/stellarium/files/3813273/ocular.txt)

**Comment by alex-w** [comment]
@dudrea thanks for file, but I cannot reproduce the issue on linux

**Comment by dudrea** [comment]
Yes I understand : I've also a linux machine and I've not this problem on it.
However, Thanks for your assistance !

**Comment by CharlesCowles** [comment]
@Alexander Wolf: I don't see an oculars.ini file in C:\Program
Files\Stellarium, but I'm using the Oculars package (or thought I was).
Where should I be able to locate the file?

**Comment by dudrea** [comment]
For windows it's in C:\Users\USER\AppData\Roaming\Stellarium\modules\Oculars

**Comment by CharlesCowles** [comment]
I don't have an AppData folder in C:\Users\USER\.  Does that make sense?

**Comment by dudrea** [comment]
May be an authorization problem ? Have a look in explorer properties and masked elements "AppData" is a masked directory.

**Comment by gzotti** [comment]
Please read section 5.1.1 in the User Guide.

**Comment by CharlesCowles** [comment]
I believe this is my oculars.ini file.  Please let me know if you need
something different.  Thanks for your patience and everything you do for
Stellarium!

**Comment by alex-w** [comment]
Attachment is missing, please use web interface

**Comment by CharlesCowles** [comment]
GitHub gives me an error message of "We don’t support that file type. Try
again with a GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or
ZIP." when I try to use the web interface.

**Comment by alex-w** [comment]
Just rename to oculars.txt ;)

**Comment by CharlesCowles** [comment]
Will do.  One second...
