### ISSUE TITLE
Infostring value about the angular distance between a moon and a planet

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1372]
I frequently find myself manually measuring the angular distances between the Jovian moons and Jupiter, to see when they are the easiest seen (I only have binoculars). I wish for Stellarium to show the value in the infostring, so you click on e.g. Ganymede and find out "It's 3.2' from Jupiter", or something.

**Comment by alex-w** [comment]
I've added computation and displayed an angular distance between the selected moon and their host planet (between their centers) into InfoString (Elongation's block). But probably computation angular separation (angular distance between edges of the selected moon and their host planet) will be better here.

@gzotti ?

**Comment by gzotti** [comment]
Elongation of Jupiter's moons are commonly given center to center, that's perfect, thanks.

**Comment by alex-w** [comment]
> Elongation of Jupiter's moons are commonly given center to center, that's perfect, thanks.

Hmm... What about correct term - "Elongation" or "Angular distance"?

**Comment by Atque** [comment]
@alex-w I think "elongation" is exclusive to distance to the sun.

Thanks for a quick solution btw!

**Comment by gzotti** [comment]
Elongation is absolutely fine in this context.
