### ISSUE TITLE
Stellarium for ARM

### ISSUE THREAD

**Issue by edegraaff** [Stellarium/stellarium#1381]
**Is your feature request related to a problem? Please describe.**
Hi, since there is a Pi4 with plenty memory, and ubuntu 64 bits for arm, i am experimenting with appimages 
**Describe the solution you'd like**
Is it possible to build appimages for pi arm 64 ubunto architecture? 

**Describe alternatives you've considered**
It is possible to use the normal installer, but appimage seems nice, but seems also to have special demands to the platform

**Additional context**
none

**Comment by gzotti** [comment]
Just follow build instructions for Linux.

**Comment by alex-w** [comment]
I can write a recipe for appimage and update bash script for building an appimage from the recipe, but... I don’t have ARM (I think you meant aarch64 architecture) device for building package.

**Comment by edegraaff** [comment]
I am willing to test and build it, just for fun

**Comment by alex-w** [comment]
> I am willing to test and build it, just for fun

Thanks, but what about architecture details? Could you share result of running `uname -m`?

**Comment by alex-w** [comment]
@edegraaff please install prerequisite packages (see https://github.com/Stellarium/stellarium/blob/master/BUILDING.md#debian--ubuntu), get the source code from git and check the script `util/appimage/build-appimage.sh`

**Comment by edegraaff** [comment]
> > I am willing to test and build it, just for fun
> 
> Thanks, but what about architecture details? Could you share result of running `uname -m`?

eelco@pi4:~$ uname -m
aarch64

**Comment by alex-w** [comment]
@edegraaff could you test `build-appimage.sh` script?

**Comment by ultrapre** [comment]
Maybe you need to cross-compile a new kit for aarch64.

**Comment by alex-w** [comment]
Please test those packages (see artifacts section): https://github.com/Stellarium/stellarium/actions/runs/390046411

**Comment by edegraaff** [comment]
hi i am builing an new machine image with usb disk. the sd card was to small... i.will.get bet to you later this week when the system is rrady with enough resources to compile

**Comment by alex-w** [comment]
I prepared an AppImage - just test it :)

**Comment by edegraaff** [comment]
i will this evening great i am curious

**Comment by edegraaff** [comment]
> I prepared an AppImage - just test it :)
I downloaded 2 of them the x86 i have ignored on the pi4
Files rights changed to able to execute 

root@pi4:/home/eelco/Downloads# ./Stellarium-edge-aarch64.AppImage 
./Stellarium-edge-aarch64.AppImage: error while loading shared libraries: libz.so: cannot open shared object file: No such file or directory


root@pi4:/home/eelco/Downloads/Stellarium-edge-armv7# ./Stellarium-edge-armhf.AppImage 
bash: ./Stellarium-edge-armhf.AppImage: No such file or directory

**Comment by alex-w** [comment]
Thanks!

> root@pi4:/home/eelco/Downloads# ./Stellarium-edge-aarch64.AppImage
> ./Stellarium-edge-aarch64.AppImage: error while loading shared libraries: libz.so: cannot open shared object file: No such file or directory

This is very strange. :( 

> root@pi4:/home/eelco/Downloads/Stellarium-edge-armv7# ./Stellarium-edge-armhf.AppImage
> bash: ./Stellarium-edge-armhf.AppImage: No such file or directory

This is OK for aarch64

**Comment by alex-w** [comment]
@edegraaff could you check package `zlib1g` - is it installed into system?

**Comment by alex-w** [comment]
Probably this workaround could help you: `sudo link /lib/aarch64-linux-gnu/libz.so.1 /lib/aarch64-linux-gnu/libz.so`

**Comment by edegraaff** [comment]
> @edegraaff could you check package `zlib1g` - is it installed into system?
Reading state information... Done
zlib1g is already the newest version (1:1.2.11.dfsg-2ubuntu4).
zlib1g set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by edegraaff** [comment]
> Probably this workaround could help you: `sudo link /lib/aarch64-linux-gnu/libz.so.1 /lib/aarch64-linux-gnu/libz.so`

link: cannot create link '/lib/aarch64-linux-gnu/libz.so' to '/lib/aarch64-linux-gnu/libz.so.1': File exists

**Comment by alex-w** [comment]
This is weird... what about `ldd Stellarium-edge-aarch64.AppImage`?

**Comment by alex-w** [comment]
Possible workaround 1: `sudo apt-get install zlib1g-dev`

Possible workaround 2: `sudo apt-get install fuse`

**Comment by edegraaff** [comment]
darn both where already installed and the latest version

**Comment by alex-w** [comment]
@edegraaff any news?

@gzotti could you test it on your RPi?

**Comment by gzotti** [comment]
I am still out of town. Maybe next week.

**Comment by edegraaff** [comment]
> @edegraaff any news?
> 
> @gzotti could you test it on your RPi?

I did test it, see respond above both options where tested, and both where already installed and the latest version :-( grrr

**Comment by alex-w** [comment]
This is a good task for the community to participate in the contribution into Stellarium. Who wants to help us?

**Comment by gzotti** [comment]
What is the benefit of using an AppImage on a RPi? We support building and running out of the box on RPi4 and RPi3B+.

**Comment by alex-w** [comment]
> What is the benefit of using an AppImage on a RPi? We support building and running out of the box on RPi4 and RPi3B+.

Not all linux for RPi support the deb packages…

**Comment by gzotti** [comment]
But all RPi distros which have Qt5 available in some format (via own package manager or even self-compiled for the masochists) should allow building on-board, maybe with omissions (QtWebengine may not be available). Uncommon distros are usually used for special purposes, not to run astronomical applications. I understand the AppImage packs all required libraries again, so IMHO it's a waste of space on the small SD cards.

That said, What would I do to install and run such AppImage for a test? I have Raspbian/Buster in RPi3 and Ubuntu Mate 22.04 on my RPi4.

**Comment by alex-w** [comment]
I’m stopped the preparation the AppImages for ARM, but you can play with it: https://github.com/Stellarium/stellarium/actions/workflows/appimage-arm.yml

**Comment by alex-w** [comment]
The problem is outside of Stellarium and we cannot prepare runnable AppImage for ARM devices
