### ISSUE TITLE
FOV plugin not available in v0.20.3

### ISSUE THREAD

**Issue by leandroprz** [Stellarium/stellarium#1391]
### Expected Behaviour
I expected to see an option to select the FOV plugin in the program settings.

### Actual Behaviour
There's no FOV plugin available: https://i.imgur.com/D2UNoIA.png

The last time I remember it was working was on v0.18.3. This was the main plugin window: https://i.imgur.com/acblLsv.jpg

### Steps to reproduce
Install version 0.20.3 on Windows 10 x64. Open Stellarium and go to Config > Plugins.

### System
* Stellarium version: stellarium-0.20.3-win64.exe
* Operating system: Windows 10 Pro x64 v10.0.18363 N/A Build 18363
* Graphics Card: GeForce NVidia 1050 Ti, driver v457.30 Studio.
* Screen type (if applicable): monitor Dell 2209WA 1680x1050 100% scaling.

### Logfile 
Log file: https://pastebin.com/La6C7dtq

**Comment by alex-w** [comment]
The features of FOV plugin for standard values of FOV was moved into core of Stellarium. Or you expected to see editable values of FOV?

**Comment by leandroprz** [comment]
Yes, I wanted to edit the values to something different than what Stellarium offers by default.

**Comment by gzotti** [comment]
This is so rarely asked for that manual definition in the config.ini should be enough for now. Defaults and names must of course be mentioned in the SUG. Or else, a separate new dialogue (similar to the old plugin config panel) called with a [FOV presets...] button in the Settings/Tools tab.

**Comment by leandroprz** [comment]
> ch

I was aware there were some shorcuts, but didn't know I could override them. I'll look into it since I really need this. Thanks for the suggestion!
