### ISSUE TITLE
Support GL_MULTISAMPLE on ARM

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1396]
OpenGLES on ARM does not support GL_MULTISAMPLE and after merge PR #1388 we lost suport build Stellarium for ARM devices: https://launchpadlibrarian.net/510483453/buildlog_ubuntu-bionic-armhf.stellarium_0.99.1+202012090528~ubuntu18.04.1_BUILDING.txt.gz

Possible solutions:
1) Remove using GL_MULTISAMPLE 
2) Detecting the target architecture by cmake and use ifdef for GL_MULTISAMPLE 
3) Use compiler predefines in ifdef for GL_MULTISAMPLE

**Comment by gzotti** [comment]
I think we have another Desktop-GL only feature excluded by ifdef GLES constructs. Sorry no time today...

**Comment by alex-w** [comment]
> I think we have another Desktop-GL only feature excluded by ifdef GLES constructs. Sorry no time today...

Hmm... @gzotti @10110111 did you tried multisampling in AGNLE mode on Windows?

**Comment by 10110111** [comment]
I haven't tried, I don't have Windows. Does it not work for you?

**Comment by alex-w** [comment]
> I haven't tried, I don't have Windows. Does it not work for you?

I haven't tried too... :-/ We got problems for building packages for Ubuntu for armhf and arm64 architectures :(

**Comment by 10110111** [comment]
> we lost suport build Stellarium for ARM devices

What kind of devices are these? Android/iOS-based?

**Comment by alex-w** [comment]
> What kind of devices are these? Android/iOS-based?

No, it's devices like Raspberry Pi

**Comment by 10110111** [comment]
Hmm, I think I'll try making a test on Raspbian to see whether there's a problem with a missing `#include`.

**Comment by 10110111** [comment]
OK, seems like `GL_MULTISAMPLE` is not supported in core GLES. Instead of trying to work around the problem based on arch, one should check `#ifdef GL_MULTISAMPLE`.

**Comment by 10110111** [comment]
Note though, that it's the enable/disable functionality that's unavailable—the multiplesampled drawables themselves (and thus the multisampling technology) are supported and shouldn't be disabled. So the only things which should be conditionally excluded are the `glEnable`/`glDisable` calls, not the `setSamples` calls.

**Comment by alex-w** [comment]
@10110111 could you fix the issue?

**Comment by 10110111** [comment]
Well, I can post a PR, but I can't test directly, because Raspberry Pi is a slooooooow builder.
