### ISSUE TITLE
Support polygononal landscapes

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1397]
According to report https://astronomy.ru/forum/index.php/topic,21983.msg5205015.html#msg5205015 Stellarium do not render landscape properly

### Expected Behaviour
Support polygonal landscapes compatible with CdC

### Actual Behaviour
Current implementatyion of support polygonal landscapes is not compatible with CdC

[U.zip](https://github.com/Stellarium/stellarium/files/5664790/U.zip)

**Comment by gzotti** [comment]
Can you circumvent your extreme example by not assigning the zenith but 89.9 degrees of elevation? And maybe adding more intermediate points? The idea behind a polygonal horizon line is a landscape that consists of mountains, not cutting out windows.

**Comment by alex-w** [comment]
I tried this probable solution but has no successful results and this is very sad :-/

**Comment by gzotti** [comment]
A polygon list like this works:

```
0 0
0.5 0
1 89.5
90 89.5
179 89.5
179.5 0
180 0
180.5 0
181 89.9
270 89.9
359 89.9
359.5 0
```

I cannot say why a narrower gap has issues.

**Comment by gzotti** [comment]
What is the purpose of this weird thing, BTW?

**Comment by alex-w** [comment]
The original report (translated):
> Help please - I can not load the polygonal landscape.
> I would like to make sure that only the necessary sector is shown, the rest was sketched in the background.
> This landscape is in the file "observation_sector.txt". And he is drawn in Ciel, but not in Stellarium.
> There is some problem when drawing near azimuth 180: the landscape in the "t.txt" file is drawn normally, but not in the "t1.txt" file anymore.

observation_sector.txt in CdC looks like on screenshot
![Карта_1](https://user-images.githubusercontent.com/88731/101721884-97905700-3adb-11eb-97a2-d14b1468126e.png)

Of course this file is not drawn in Stellarium :(

**Comment by axd1967** [comment]
with some tweaking it is possible:

![image](https://user-images.githubusercontent.com/3529789/101751201-4cbd1200-3ad0-11eb-92ae-06e6aacc61a5.png)

by further fine tuning the altitudes it should be possible to attain the desired effect

![image](https://user-images.githubusercontent.com/3529789/101751295-65c5c300-3ad0-11eb-810b-b43cec99f4a4.png)


sometimes I have a subjective feeling that there is some kind of memory effect - as if not all objects are correctly refreshed.

some more logging inside the landscape drawing routines might be useful, maybe the logic decides to skip some vertices.

**it looks like the absence of 090 is maybe a culprit:**

![image](https://user-images.githubusercontent.com/3529789/101753275-b9391080-3ad2-11eb-9361-fcb0e28b2387.png)

maybe not only integer values must be avoided, but maybe there needs to be at least one value per 90-degree sector.

**Comment by gzotti** [comment]
> The idea behind a polygonal horizon line is a landscape that consists of mountains, not cutting out windows.

This implies many points in every quadrant. "Simply" understand SphericalRegion with all details to figure out what has to be done to cut out windows.

**Comment by axd1967** [comment]
> This implies many points in every quadrant. "Simply" understand SphericalRegion with all details to figure out what has to be done to cut out windows.

I beg to differ: you can't expect an average user to "understand SphericalRegion" (even if a large proportion of users probably are at an academic level). Can't we translate this to "user speak"?

So, populating each quadrant might be a requirement; and this can even be enforced by the software emitting a warning if this condition is not met. If this is the case, I'm not sure if this is highlighted in the User Manual.

**Comment by axd1967** [comment]
and requiring at least one point per quadrant - if that would be the case - is odd and an obvious shortcoming, but we are aware that the landscape plotting code is _far_ from trivial so we will have to live with this until enough understanding of the code has been acquired.

**Comment by gzotti** [comment]
I suggest YOU, not the average user, to make your hands dirty and understand SphericalRegion and work out a solution if you really need one. I repeat, the intended use is to create a landscape horizon of a location where the zenith is usually free of obstacles and some hills or houses are plotted. Of course this implies one value every few degrees at least, and by this, in every quadrant.

**Comment by axd1967** [comment]
hello @gzotti ...

I don't need a solution... I'm just trying to help whoever created the issue, help the community understand the issue, find workarounds. I'm trying to express that this is not an easy solution, I'm not criticising anyone...

in this case, my suggested workaround should at least help the user that created that landscape to go forward, and on the road we learn things.

**Comment by axd1967** [comment]
Same issue (0.20.3 as well as `master`)  with following data:
```
000 80
045 80
090 80

125 8

135 80
180 80

186 6
195 12
196 3
206 5
209 2
222 11
236 0
275 19
293 1

315 80
330 80

```
this is a frustrating experience, because there is no apparent reason why this shouldn't work

**Comment by axd1967** [comment]
there might be a bug that leads to parts of the drawn landscape to be clipped by the Qt routines that try to draw the final polygon.

**Comment by axd1967** [comment]
done some debugging, it looks like this piece of code is giving headaches:

https://github.com/Stellarium/stellarium/blob/5a27f254a8fcd64a2497f4e2114b29640743ba08/src/core/modules/Landscape.cpp#L243-L252

by just skipping this piece, I get a better result (horizon  has been fiddled a bit meanwhile):

![image](https://user-images.githubusercontent.com/3529789/103098029-a1e93f80-4609-11eb-8d11-836edf8e815b.png)

**Comment by axd1967** [comment]
> and requiring at least one point per quadrant - if that would be the case - is odd and an obvious shortcoming, but we are aware that the landscape plotting code is _far_ from trivial so we will have to live with this until enough understanding of the code has been acquired.

I suspect that the result of this "requirement" is that the zenith is almost always included in most "normal" landscapes (landscapes ) 

## kind of workaround
reversing the list of horizon points prevents triggering this test but then the user must show the polygon line only

![image](https://user-images.githubusercontent.com/3529789/103102632-327d4b00-461d-11eb-91be-dde0e9def1fc.png)


![image](https://user-images.githubusercontent.com/3529789/103102959-dfa49300-461e-11eb-8f09-cf6630b576ef.png)

**Comment by gzotti** [comment]
Skipping the zenith test adds the earlier problems. A landscape horizon usually has a free zenith, and a covered nadir. Not both. There are technical reasons deeply buried in the guts of used classes which required this incredibly restrictive behaviour. Cutting windows into a dome is NOT the application of a polygonal LANDSCAPE usually computed from 2.5D digital elevation models. Use a Spherical landscape and PAINT transparent windows into the texture as a WORKING SOLUTION.

**Comment by axd1967** [comment]
@gzotti if inclusion of the zenith is required for now (0a95d93324390e4b559a716b796ea4dccb7a1938), wouldn't it good to add at least a warning in the logfile? this problem is difficult to diagnose/visualise but easy to detect by the software.

I've added this in a PR: https://github.com/Stellarium/stellarium/compare/master...axd1967:contrib/issue/1397/landscape/polygon-bug?expand=1
