### ISSUE TITLE
download time out

### ISSUE THREAD

**Issue by jairoamaral** [Stellarium/stellarium#140]
I'm using Stellarium 0.18.0 in Windows 10. Since a few days ago, I can't download star catalogs nor surveys anymore. It says "time out". My internet is OK otherwise. Is some server down?

**Comment by gzotti** [comment]
@jairoamaral do you still have this problem?

**Comment by jairoamaral** [comment]
@gzotti Hi, I don't have the problem anymore. It disappeared by itself after a few days more. I still don't know what happened, though. Thank you for caring.
