### ISSUE TITLE
Ocular presentation does not match reality

### ISSUE THREAD

**Issue by donpgolden** [Stellarium/stellarium#1400]
Ocular presentation does not match reality

### Ocular view substantially smaller than the actual captured image
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>0.20.3 for OS X
* Operating system: <Name, version number>11.1 Beta (20C5048l)
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>. Apple iMac  Radeon Pro 850
* Screen type (if applicable): Resolution, HighDPI, scaling.  5120 x 2880 Retina

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

Stellarium view:  
![StellariumView](https://user-images.githubusercontent.com/60073505/101654009-9f7dc780-3a05-11eb-9a4c-db01e1ba4c6b.png)
Stellarium settings
![Telescope](https://user-images.githubusercontent.com/60073505/101654241-e5d32680-3a05-11eb-896c-97b1d53e54c0.png)
![Sensor](https://user-images.githubusercontent.com/60073505/101654358-0c915d00-3a06-11eb-9886-110ad7a08bb5.png)
![lens](https://user-images.githubusercontent.com/60073505/101654438-2763d180-3a06-11eb-803a-35e717a619be.png)
Actual image:

![M31_60_1600PI_crop_DBE_colorcllib_PCC_denoise_str_HDR_LHE](https://user-images.githubusercontent.com/60073505/101654772-7f023d00-3a06-11eb-9a8f-887b9e971f07.jpg)

**Comment by alex-w** [comment]
Did you used this reducer - https://www.skywatcherusa.com/products/reducer-corrector-85x-for-evostar-100 ?

**Comment by donpgolden** [comment]
Yes

Don Golden
txgoldens.com
281 772 2991

**Comment by alex-w** [comment]
I don't see problems:
![stellarium-000](https://user-images.githubusercontent.com/88731/101785561-7f4a2780-3b2f-11eb-92b1-0d714171cfc8.png)

**Comment by gzotti** [comment]
Guessing source of issues: "5120 x 2880 Retina" and some scaling trouble...

**Comment by alex-w** [comment]
> Guessing source of issues: "5120 x 2880 Retina" and some scaling trouble...

I see wrong sign of rotation angle for DSLR in settings, but not scaling.

**Comment by gzotti** [comment]
Indeed confirming just a different rotation angle, and maybe a very small deviation in focal length, nothing to be worried about. Or what exactly is wrong @donpgolden ?

![stellarium-000](https://user-images.githubusercontent.com/18099873/105416778-f00a5680-5c3a-11eb-90c2-27bca0b5ed7e.jpg)

**Comment by donpgolden** [comment]
I cannot find my original post in the forum.   Can you send me a link to it.

Don Golden  <><
don@txgoldens.com
mobile 281 772 2991

**Comment by gzotti** [comment]
Huh?

Click on the link "view it on Github" at the end of the email that says

**Comment by donpgolden** [comment]
I actually understand my misunderstanding.   My captured image is based on too few subs.   With more subs, I will see more of Andromeda and more nearly match the view from Stellarium.    Thanks for responding.

**Comment by gzotti** [comment]
The sensor frame can only give a view of the geometry, not of your exposure or processing...
