### ISSUE TITLE
Cursor (pointer) missing in Stellarium for Windows 64-bit

### ISSUE THREAD

**Issue by Tracker57** [Stellarium/stellarium#1405]
### Actual Behaviour: The mouse will select items as usual, but it is not visible. I recall this when I tried to use Stellarium many months ago.

Describe or maybe attach a screenshot?

The cursor is not visible, even though it has highlighted the "here" for submitting a new issue.
![image](https://user-images.githubusercontent.com/75850686/101925705-2a92c500-3ba0-11eb-9180-633a1537101a.png)

### System
* Stellarium version: <stellarium-0.20.3-win64.exe>
* Operating system: <Windows Pro 64-bit, 10.0.18363 Build 18363>
* Graphics Card: <Manufacturer nVidia, Model ( GeForce GTX 1060 6GB), 26.21.14.4587>
* Screen type (Dell 27" LCD): 4K

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Please read: https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#Mouse_cursor_invisible
