### ISSUE TITLE
Ocular plug-in crashes Stellarium when attempting to add a sensor

### ISSUE THREAD

**Issue by gav-b** [Stellarium/stellarium#1407]
### Expected Behaviour
I'm new to Stellarium and I'm attempting to configure a sensor in the Ocular plug-in.

### Actual Behaviour
When I attempt to configure a sensor Stellarium crashes.

### Steps to reproduce
1. Select Configuration > Plug-ins > Oculars > Configure.
2. Select the Sensors tab.
3. Click in Resolution x field. No change to the value.
4. Click in Resolution y field.
5. Stellarium crashes.

I've tried various things to add a sensor and they all result in Stellarium crashing.

### System
* Stellarium version: stellarium-0.20.3-win64.exe
* Operating system: Windows 10.0.19042.685 64-bit (This is the latest release)
* Graphics Card: Intel Iris Plus Graphics, driver version 26.20.100.7641 (This the latest release)
* Screen type (if applicable): 13" Surface Laptop 3, 2256 x 1504 pixels

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

[log.txt](https://github.com/Stellarium/stellarium/files/5683805/log.txt)
[ocular.txt](https://github.com/Stellarium/stellarium/files/5683806/ocular.txt)

**Comment by gzotti** [comment]
I just was able to crash Stellarium when I had deleted all sensors an try to select the next sensor. 
@gav-b Press "Add sensor" near the bottom of the dialog, so that you really have a sensor to configure. 
@alex-w we must make sure there is always at least one sensor in the list.

**Comment by gav-b** [comment]
I tried "Add sensor" and that crashed again. Here's what I did:

1. On the sensor tab clicked the Add button.
2. Entered the Name.
3. Entered the Resolution x.
4. Clicked the Resolution y field to enter a value.
5. Stellarium crashed. There appears to be a couple of seconds delay before the crash.

I also tried the following:

1. On the sensor tab clicked the Add button.
2. Entered the Name without changing anything else.
3. Exited the configuration and Stellarium.
4. Reopened Stellarium and went back to the sensor configuration.
5. Changed the default Resolution x from 4096 to 6248.
6. Clicked the Resolution y field to enter a value.
7. Stellarium crashed.

Finally I decided to enter the information directly into ocular.ini.

1. I edited ocular.ini manually to specify the correct configuration for the sensor.
2. Opened Stellarium and went to the sensor tab.
3. Clicked the Resolution x. I didn't changed anything.
4. Clicked the Resolution y. I didn't changed anything.
5. Stellarium crashed.

I think updating ocular.ini is a good enough workaround for me. Having done this, the image sensor frame displays correctly.

**Comment by alex-w** [comment]
> @alex-w we must make sure there is always at least one sensor in the list.

Or disable usage of some modes if equipment is not exist
