### ISSUE TITLE
label of weak mag satellite only shown in marker mode

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1408]
**Is your feature request related to a problem? Please describe.**
When using the "realistic" sat mode ("show as marker" disabled, _can someone propose a name for this state? Maybe "realistic" state? _ ), the label disappears if the sat is not bright enough, which confuses the uses as to whether satellites are shown at all.

**Describe the solution you'd like**
The label should follow the marker visibility logic (i.e. be visible hen the marker would be visible). (Note that the user can always filter out "invisible" satellites.)

**Describe alternatives you've considered**
Use marker mode

**Additional context**

In marker mode, a sat is always visible:
![image](https://user-images.githubusercontent.com/3529789/102062423-011ea700-3df5-11eb-82f3-ac7aea446890.png)

In realistic mode, the label also disappears if the sat is not bright enough:
![image](https://user-images.githubusercontent.com/3529789/102062466-11cf1d00-3df5-11eb-8145-c4e6584cc79d.png)

**Comment by alex-w** [comment]
This is correct behavior - if satellite is too faint then do not draw a star-like marker and label

**Comment by gzotti** [comment]
If satellites are not shown as markers they are shown only if they are bright enough (should follow star brightness point source algorithm). Not showing a satellite point and label when marker mode is not active and the satellite is too faint to be seen is absolutely the intended behaviour.

**Comment by axd1967** [comment]
I have a similar problem with orbits of invisible satellites:

does it make sense to show the **orbits** of satellites that are totally invisible?

![image](https://user-images.githubusercontent.com/3529789/102105272-80c96780-3e2f-11eb-9368-bc5a5f598f60.png)

**Comment by axd1967** [comment]
it's not a good idea to **close** an issue because of "_maybe in future we will back to this proposal or someone can implement it and propose pull request with solution!_ "

especially if tagged  "won't fix" .

the **reason** is that there is not much incentive to **dig** through **closed issues** to find new ideas.

therefore this issue should be tagged as e,g, "wishlist" or some other label.
