### ISSUE TITLE
Error in the Sky & Telescope sky culture

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1414]
There is a small error in the constellation lines of the Sky & Telescope sky culture.

Looking at the interactive star chart from S&T, we learn that Ursa Major includes the star HIP 50203 (Alula Australis/ξ UMa:
https://skyandtelescope.org/interactive-sky-chart/
![UMa wrong](https://user-images.githubusercontent.com/37028368/102470918-d894e800-4054-11eb-984e-bbac4d567935.PNG)

Stellarium however does not include that star, but instead has the star magnitude +6.55 HIP 50302... +6.55 is generally considered to be ouside of the human naked eye range.
![UMa wrong Stel](https://user-images.githubusercontent.com/37028368/102471076-0b3ee080-4055-11eb-9cbb-655cc2e50214.PNG)

The similarity in nomenclature between HIP 50203 and HIP 50302 leads me to believe this is an error.

**Comment by gzotti** [comment]
Thanks!

**Comment by alex-w** [comment]
See als:

![](https://www.iau.org/static/public/constellations/gif/UMA.gif)
