### ISSUE TITLE
navigation mode random locations bug of sorts

### ISSUE THREAD

**Issue by johnbellora** [Stellarium/stellarium#1416]
Stellarium wrote a script which when invoked, places the observer in random locations  some where in the world for the observer to have the opportunity to locate his longitude and latitude by star positions. Thank you this is working great. This should become a celestial navigation app for all seamen and airmen. 

**Problem!**
 The problem is the time reflects local time. In navigation mode. the time should always be UTC time no mater where you are. Local time is not used in celestial navigation. This confuses the calculations. UTC or GMT is the only time that is ever considered in celestial navigation.

**Requests**
* [x] Please have the time window reflect only UTC when in Navigation mode. Or add a secondary window labeled UTC
* [x] In the location window. Please have the longitude and latitude of current location reflect decimal tenths of a degree when toggling minutes to decimal button as with the LHA & GHA read outs.

I will make yet another donation  my fourth for your time and effort. Thank you

**Comment by gzotti** [comment]
Please use the Location panel and set your timezone to UTC before you call the script. I have not seen it in action, though. 

If with "navigation mode" you mean "nav stars displayed", this auto-switch to UTC may become an option, but not exclusive behaviour. The casual user may be interested in displaying the nav stars, but else wants to keep his preferred time settings.

**Comment by johnbellora** [comment]
Hello Georg,
Yes I think you are right. I tried it but under a few circumstances I had bad figures but it might be on my end.
Any chance to get the location window to show decimals of a degree got the GPS coordinates when toggled just like the LHA mod you did for me?

Best Regards
John.


-----Original Message-----

**Comment by alex-w** [comment]
v0.20.4 will following an option "Use decimal degrees" in Location dialog too

**Comment by johnbellora** [comment]
Thank you sir!


-----Original Message-----
