### ISSUE TITLE
Missing Pixel Width and Height in Ocular Plugin

### ISSUE THREAD

**Issue by skorpiokp** [Stellarium/stellarium#1420]
This is my first time doing this, so I hope I filled this out correctly. I'm trying to enter my sensor info for my camera in the ocular plugin and it's not giving me the option for pixel width and height. I have uninstalled and reinstalled the program, getting the same issue. 
I'm expecting this window to appear:
![image](https://user-images.githubusercontent.com/76421336/102745096-4f6a0380-4329-11eb-893f-96a2bb133dc3.png)

But I'm getting this window instead: 
![image](https://user-images.githubusercontent.com/76421336/102745135-5db81f80-4329-11eb-8e2f-35d662cbf375.png)

Reproduce problem
1) Click Configuration Window
2) Click Plugins
3) Scroll to Ocular and click configure
4) Click Sensor and Add, look for _Pixel Width_ and _Pixel Height_, not there.

* Stellarium version: 0.20.3
* Operating system: Windows 10 Pro, Surface Book 2
* Graphics Card: Intel® HD Graphics 620 integrated GPU and NVIDIA® GeForce® GTX 1050 discrete GPU w/2GB GDDR5 graphics memory

**Comment by alex-w** [comment]
Pixel width and height was not used real and we removed both parameters from the GUI

**Comment by axd1967** [comment]
@skorpiokp  check if you really have 0.20.3 - use F1 > About? this was removed in https://github.com/Stellarium/stellarium/commit/898495d596c99e400eae56462334c05971fcecb9 ; if you DO have 0.20.3, something is wrong.
