### ISSUE TITLE
Bug Exoplanetes 

### ISSUE THREAD

**Issue by Zetssuu** [Stellarium/stellarium#1421]
Bonjour, je suppose que cet affichage n'est pas normal ?
Je voulais le signaler car je ne pense pas que les exoplanètes s'amusent a faire une belle figure géométrique comme ça.  
![image](https://user-images.githubusercontent.com/76463921/102848982-6d616200-4416-11eb-9e13-d26689cc0f4e.png)

**Comment by alex-w** [comment]
No, this is not a bug! See Kepler space telescope mission for details.
