### ISSUE TITLE
calendar plugin collides with the bottom bar

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1422]
From @Atque , to not forget:

If many plugins are loaded, the calendar information collides with the bottom bar and makes the text unreadable. See this screenshot:

![info_collide](https://user-images.githubusercontent.com/37028368/102883146-cb5e6b80-444f-11eb-9e62-b94c4949af2a.PNG)

Is there any setting to lift it up, so it is completely above the bottom bar?

_Originally posted by @Atque in https://github.com/Stellarium/stellarium/issues/1343#issuecomment-749490794_

**Comment by gzotti** [comment]
From me, to not forget.
>Not in this first version. Even on FullHD screens there is also already the problem that the main object info may collide with the left menu bar if all info bits are requested. To mitigate these issues, historians or other users who need the calendars are able to e.g. disable Exoplanets, quasars, satellites plugins, or deactivate night view, galactic grid or even the quit button.
