### ISSUE TITLE
Newfoundland Time Zone

### ISSUE THREAD

**Issue by dave-gillingham** [Stellarium/stellarium#1423]
The province of Newfoundland, on the east coast of Canada, has its own unique time zone (GMT -3:30). Please add this time zone in an upcoming release.

**Comment by gzotti** [comment]
UTC-3:30 (which already exists BTW) is a timezone without daylight saving rules. Presumably Newfoundland is in the existing timezone "America/St_Johns"?

**Comment by dave-gillingham** [comment]
The time zone does adhere to daylight savings time.

**Comment by gzotti** [comment]
If your timezone uses DST you must NOT use "UTC+/-something". Is "America/St_Johns" right for you?

**Comment by dave-gillingham** [comment]
"America/St_Johns" is the correct timezone.

**Comment by gzotti** [comment]
OK, then please use it. I can close this as solved.
