### ISSUE TITLE
some thoughts about rewrite/communicate...

### ISSUE THREAD

**Issue by silas1037** [Stellarium/stellarium#1426]
The greate stellarium was written by cpp, and I also found some earlier rewritten version —— like Stellarium for Java.

The following are just some ideas...

1. Is that possible/easy to rewrite / port it  to other language like python? 

Rewrite: Translating a OOJ to OOJ seems to be easier more, but simpler language's code will be shorter... 

2. Although the cpp-base program success at running speed, to share it calculation data or communication between different programs also values.

Functions to communicate with diff language by interface: handle a call from other programs, returning what they wants like astro calculation results. Well, remote-control can work for it.

---

On some website I also saw the headless mode of none-gui stellarium in docker, maybe port code to a dynamic lib is possible..

**Comment by gzotti** [comment]
Please see the permanent success of Stellarium for Java for an answer.

**Comment by silas1037** [comment]
> Please see the permanent success of Stellarium for Java for an answer.

I don't understand the words.

**Comment by alex-w** [comment]
Short answer: you should start new project for resolving your ideas (some dynamic library and GUI as a plugin or standalone application for that library), becasue this will be simpler that rewritting 80% of planetarium to obtaining dynamic library with some API.
