### ISSUE TITLE
show comet locations regardless of magnitude

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1427]
Someone thought s/he saw a comet at a given location, so I wanted to check this after loading ALL known comets.

Unfortunately, comets are filtered and the user has to zoom in to find a comet (the find feature is useless in this use case). The user needs an option to override the magnitude and show all comets regardless of their actual brightness, similar to how satellites can be shown even when they would be invisible.

A related issue is that comet orbits can be shown, but without the location of the comet.

**Comment by gzotti** [comment]
Stellarium is not a tool to check for comet discoveries.

**Comment by Ruediger3** [comment]
Hi axd1967,

I can recommend ASTAP. There is a built in function to solve image and autocratically detected and identify comets and asteroids automatically. With that we identified Asteroid "Bettina" in one image a few days ago. 
See here: https://www.astrobin.com/forum/c/group-forums/astrophotography-germany/asteroid-lokalisiert/
or here https://pixinsight.com/forum/index.php?threads/comet.15762/#post-95364

For your use case Stellarium is the wrong tool. 

Cheers and Happy X-Mas.
Rüdiger

**Comment by axd1967** [comment]
No, it is not the idea to do plate recognition or look for new comets, discover comets, or use the result of stacking. 

The user that reported a comet is not experienced enough and most probably mistook a nebula for a comet, in case one might wonder.

Nevertheless, this brought up a new use case: as a user, I want to see all loaded comets.

**I just want to have an idea of where are the comets that Stellarium has in memory.** Currently, Stellarium artificially filters away those comets that would be too faint to see. This is a handy filter, but should be user-selected rather than imposed.

Stellarium is sufficient and very well capable of doing what this issue needs: to visualise all comets that the user has loaded; it is the responsability of the user to load "enough" comets.

Again: as a user, I simply want to make the comets visible that the application has loaded. I don't care if not all comets have been loaded.

Again: this behaviour is comparable to the satellite plugin, where the user can visualise all sats that have been loaded (which does not guarantee that all sats are shown, yes, I'm aware of this too).

I know that I might not see ALL comets (even then), but that is **no problem**.

**Again: show all comets loaded in memory, regardless of their magnitude.**

I don't care if some comets exist that Stellarium is not aware of, or the user has not downloaded.

Just to avoid any discussion: I just want to see what comets Stellarium is aware of, without having to zoom in, search, or find via the comet dialog. Please let me know if this is not clear?

**Comment by gzotti** [comment]
1) ff621a11df8f037b533424b0d829cfc6ed0a9962

2) comets beyond orbit_good are discarded because their positions are too bad to be displayed. This is our decision, and no, we have no interest to have an option to "show comets on wrong positions just because we could".

**Comment by Ruediger3** [comment]
No: The, the idea was not to recover new comets.
No: The the user did not mistook it. BTW, how can you mistake a comet whith nebula?
No: The user is experienced
No: It was not for a stack of subs

Sorry if I missed your use case, just wanted to help.

**Comment by axd1967** [comment]
> No: The the user did not mistook it. BTW, how can you mistake a comet whith nebula?

:-) Messier wanted to get rid of those pesky smudges that looked like comets :-)

**Comment by gzotti** [comment]
> 
> 
> > No: The the user did not mistook it. BTW, how can you mistake a comet whith nebula?
> 
> :-) Messier wanted to get rid of those pesky smudges that looked like comets :-)

Because he did NOT have a list of known immovable objects. Today we have his, Herschel's, Dreyer's, ...

**Comment by Ruediger3** [comment]
> > No: The the user did not mistook it. BTW, how can you mistake a comet whith nebula?
> 
> :-) Messier wanted to get rid of those pesky smudges that looked like comets :-)

Yes, but not our days, where you have huge catalogues covering all objects in range for amateurs and not using the bottom of a glass bottle as a telescope. ;)

**Comment by axd1967** [comment]
> > :-) Messier wanted to get rid of those pesky smudges that looked like comets :-)
> 
> Yes, but not our days, where you have huge catalogues covering all objects in range for amateurs and not using the bottom of a glass bottle as a telescope. ;)

well, I know at least one noob amateur (and no, it's not me) who thought s/he saw a comet (with a low power bino!). a quick look at [SBWOBS](https://ssd.jpl.nasa.gov/sbwobs.cgi) for the most obvious / visible comets quickly excluded the possibility. but opened this issue...

**Comment by axd1967** [comment]
> ff621a11df8f037b533424b0d829cfc6ed0a9962)

Sure! But it should be a user decision to deal with a slow application: the user should understand the implication of showing all such objects. The default setting could be "off" (or even a config-file-only setting). And the user who does have powerful hardware should not be penalised because other users are not able to run the software - that's why we use config settings, to please more users.

But currently, the user has **no** option at all.

Agreed, when the option would be made available, user _might_ start complaining about speed. But not everyone needs to display ALL objects all the time. And again: users are to be warned of the implication, after that they are on their own.

As a quick test, I hacked around those sections of code (ff621a11df8f037b533424b0d829cfc6ed0a9962) and downloaded all comets from https://www.minorplanetcenter.net/iau/MPCORB/CometEls.txt which now gives me 900+ objects:

```
...
Updated successfully "407ppanstarrsfuls"
Updated successfully "408pnovichonokgerke"
Updated successfully "409ploneoshill"
Updated successfully "1i`oumuamua"
Updated successfully "2iborisov"
Loading Solar System data (1: planets and moons) ...
Loading from : "/home/alex/projects/stellarium/builds/current/share/stellarium/data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "./data/ssystem_minor.ini"
SolarSystem has  1042 entries.
Loaded 959 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15670 / 15672 items of planetary surface nomenclature

```

And also disabled magnitude filters and enabled DSO:

![image](https://user-images.githubusercontent.com/3529789/103152200-e3065e80-4785-11eb-8b45-c0f3ba8abffb.png)


As far as I can see, there is not much of a performance issue; but I can perfectly understand that older PC will suffer (especially those that still run low resolution displays). That's why a user setting will bring together both worlds.

> 2. comets beyond orbit_good are discarded because their positions are too bad to be displayed. This is our decision, and no, we have no interest to have an option to "show comets on wrong positions just because we could".

This sounds perfectly reasonable, I'm not interested either.

I see the `orbit_good` flag. Take the example of C/2020 M3: the orbit of M3 is currently well known even if it needs regular updates, its position is "quite" acceptable (currently `orbit_good = 1000`).

M3 is visible when zoomed in, but the user needs to use the search dialog to show its position it when zoomed out. Why? If performance is an issue, then a user setting is the answer.

![image](https://user-images.githubusercontent.com/3529789/103152186-d7b33300-4785-11eb-96e5-6858930b61d1.png)


So for me, this would be a quick means to check for a possible comet (or not)

And agreed, we DON'T want to see ALL comets as a default!

**Comment by axd1967** [comment]
In case the user would opt to ignore all magnitudes, the icon from #1332 could be used to plot comet positions.

**Comment by axd1967** [comment]
Interesting related comment:

https://github.com/Stellarium/stellarium/blob/01834bb2ab5a1f23381bd3547a4b2ecdf3d031dd/src/core/modules/Comet.cpp#L415-L418
