### ISSUE TITLE
Ability to build an observation plan/list

### ISSUE THREAD

**Issue by stefanoklett** [Stellarium/stellarium#1431]
It would be nice to be able to easily create an observation list.

You select an object at a specific time and add it to an observation list containing the object's coordinates and time.

Clearly, partially, this already works with bookmarks, but it is limited to a list and does not contain the date of observation.
This system could easily be integrated into automatic observation systems (like ACP Observatory COntrol Software).

Best regards
Stefano

**Comment by gzotti** [comment]
Duplicate. #976, #869, ...
It would be even nicer if somebody who has the time to observe and gain insights what such a thingy should be able to do actually made it. It cannot be so difficult, right?  :-)
