### ISSUE TITLE
Should be possible compile the version for Windows 10 ARM64 version?

### ISSUE THREAD

**Issue by Corsair-63** [Stellarium/stellarium#1436]
Stellarium runs in windows 10 ARM64 (Surface pro X and another hardware at this time) under emulation of x86, it means that doesn't run natively in the system and could be some loose of functionality either to take advantage of processor and memory. 

should be possible offer this suite as default with this Windows 10 ARM64 compiled version?

_x86 versions of software is becoming more rare and sometimes deprecated in order to squeeze all the benefits and advantages of new processor and OS version, so could be a good start to port also marvellous Stellarium to have such feature of running "at home" with these processor that looks like that are pushing hard to make their proper room, mostly used in tablet, that are really useful for the star sighting in landscapes and at sea.

**Comment by gzotti** [comment]
Does it run in x86 emulation mode or not? What does not work? 

X86 compatible hardware will be with us for many more years, even if sales may go down. There is a small computer or even SBC market still for x86. Win32 builds and Mac builds are downloaded in about equal numbers.
Don't forget that Stellarium had WinXP builds years after WinXP had been declared dead. And it has still seen thousands of downloads, even if only about 1% of regular Win32 builds. 

Is Windows 10 ARM64 the same as Windows UWP? Then at least Qt5 supports it. You can always build Stellarium from source.

**Comment by alex-w** [comment]
Important note - tablets (e.g. Surface Pro X) is not primary target for desktop edition of Stellarium

**Comment by alex-w** [comment]
> Does it run in x86 emulation mode or not? What does not work?
> 
> X86 compatible hardware will be with us for many more years, even if sales may go down. There is a small computer or even SBC market still for x86. Win32 builds and Mac builds are downloaded in about equal numbers.
> Don't forget that Stellarium had WinXP builds years after WinXP had been declared dead. And it has still seen thousands of downloads, even if only about 1% of regular Win32 builds.
> 
> Is Windows 10 ARM64 the same as Windows UWP? Then at least Qt5 supports it. You can always build Stellarium from source.

AppVeyor is not support Qt for Windows UWP and we cannot prepare signed binaries for this platform.

**Comment by Corsair-63** [comment]
Thanks for your quick answer, understood.

I'm seaman and I use the tablet as desktop computer when at work. I cannot travel with neither desktop nor big laptop, I have to minimize my luggage. 😉 (I learnt after long time  being travelling with big laptops)

I know that it works under emulation on _x86 I haven't test in deep, I did it with my previous one Surface 4 that was wintel x64 based and I installed x64 version running smoothly but the new one running under emulation is really slow, It's a pity not having it working natively.

From my point of view _x86 should be deprecated long time ago, from my poor knowledge this version at this time is not making any benefit for the software development that should be based in the close future as x64 and ARM64 (that's what computing gurus say, not me) 

AFAIK as per Microsoft itself UWP app must run natively under Windows ARM64, but I'm not computing engineer.

**Comment by Corsair-63** [comment]
And first of all I have to say that I'm really happy to test and run this program since long time ago, because is really useful on board in order to have a clear picture of the stars that could be sightseeing in order to get the astronomical position, making the observation job really easy.

**Comment by gzotti** [comment]
Is the title of this issue valid then? Should it not rather be "I want to download installable version for ARM64 Windows UWP"? 

I assume everybody could follow our instructions (maybe with a little help from Google) and compile Stellarium on his own ARM64 UWP with the Qt libraries for UWP, if that is possible without unknown obstacles.  Only somebody with such hardware has the interest to build and test it. We have no such hardware and no "testing department for new/rare hardware" or whatever you seem to assume.

**Comment by axd1967** [comment]
> I assume everybody could follow our instructions (maybe with a little help from Google) and compile Stellarium on his own ARM64 UWP with the Qt libraries for UWP, if that is possible without unknown obstacles. Only somebody with such hardware has the interest to build and test it. We have no such hardware and no "testing department for new/rare hardware" or whatever you seem to assume.

@Corsair-63 could be a good tester of the build procedures :-) ideally, anyone should be able to build Stellarium, assuming the instructions are clear enough; if not, the instructions should be expanded accordingly. (https://github.com/Stellarium/stellarium/blob/master/BUILDING.md)

**Comment by ultrapre** [comment]
It may not to build it for UWP easily like Desktop because the kit for uwp lacks modules like script, serialport and printsupport. Maybe you need to pay efforts to fix it like #194 . My suggestion is to build from a lite version like [stellarium-mobile](https://github.com/ultrapre/Stellarium-mobile).

**Comment by gzotti** [comment]
You can build a version without scripting support. Serial: likely just drop Telescope plugin and external GPS device? Print: not currently required I think. But probably the disabling `#define`s need to be tested/fixed.

**Comment by ultrapre** [comment]
QtPrintSupport is imported by qcustomplot.h, not like others two could be disabled by what like ENABLE_GPS.

**Comment by Corsair-63** [comment]
I could try to build a version for windows 10 ARM64, but I have no clue of using Visual studio 2019, already installed, and how to get the option to compile for ARM64, I had to install the x86 version in my Surface X.

also QT is asking me for an account to install the library, ??

for sure that I'll burst my Tablet ;-)

**Comment by gzotti** [comment]
Downloading Qt requires an account, yes. But it's free for open-source projects. If QtScript (deprecated) is not at all available for UWP, you must disable ENABLE_SCRIPTING. We have not tested (I think) disabling some of the ENABLE_* config options, though. If printing support really is  a problem, we will have to find some way to circumvent, maybe at cost of having to disable the entire AstroCalc module for this build. However, currently UWP is officially not supported, and we can only watch from afar.

**Comment by gzotti** [comment]
Stellarium no longer depends on qcustomplot or QtPrintSupport. (#2447)

**Comment by alex-w** [comment]
This is a good task for the community to participate in the contribution into Stellarium. Who wants to help us?

**Comment by alex-w** [comment]
Good news: https://github.com/msys2/MINGW-packages/pull/18653

**Comment by hmartinez82** [comment]
I already got CalcMySky building for MSYS2 even for Windows on ARM (see unit tests passing at https://github.com/msys2/MINGW-packages/pull/18697)  >
I'm going to add the libindiclient package now, but I need to know now, if Stellarium will work with the latest indiclient? I saw that CPM is using a fairly version of INDI.

**Comment by hmartinez82** [comment]
We decided to stop pursuing a solution for this with MSYS2 / MinGW 64 and went with Visual Studio instead. It was of absolutely great help that the AppVeyor runners images already had Qt 6 compiled for Windows on ARM

It is now possible to build AppVeyor for Windows on ARM. You need Qt 6 compiled for x64 and for ARM64 and CMake. The x64 build of Qt is needed for running the compile time tools and Qt must be compiled to use SChannel as its SSL QtNetwork backend. OpenSSL is not required.

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
