### ISSUE TITLE
Is there any way to get a CI build binaries?

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#1437]
I'd like to be able to test Stellarium's revisions as they are pushed to git. It's easy to do the build on Linux, but I'd like to also test Windows versions. Is there any easy way to get the Windows binaries of a non-released revision of Stellarium?

I've noticed that there is an AppVeyor CI script that runs and apparently works, but only publishes artifacts for the `release` branch. Is there any reason not to let it publish artifacts for every build?

**Comment by alex-w** [comment]
Just add string “[publish]” into commit message to get an artifact

**Comment by 10110111** [comment]
This works, thanks.
