### ISSUE TITLE
Cannot reassign directory that holds screen saves

### ISSUE THREAD

**Issue by beamtuner** [Stellarium/stellarium#144]
### Expected Behaviour
Should remember and use the directory chosen for screen grabs.

### Actual Behaviour
If you choose a directory different than the default screenshot save diectory, it does not save screenshots to chosen directory.  It ignores the choice and continues using the old default directory.

### Steps to reproduce
1. In the Configuration window, select the Tools tab.
2. In the Screenshots pane, choose a new directory.
3. Switch to the Main tab.
4. Select Save Settings.
5. Close the Configuration window.
6. Select ctrl-S to perform a screen save.
7. The screen save is placed in the original default Stellarium directory of Pictures library, rather than in the directory you chose in step 2.
8. Close out program.
9. Restart program.
10. Type ctrl-S to perform a screen save.
11. The screen save is placed again in the original directory, and not in the one chosen in step 2.
12. In the Configuration window, select the Tools tab.
13. Observe in the Screenshots pane that the program has forgotten the directory you chose in step 2, and is instead using the original default directory.
14. No error messages are issued during any of the above steps.

### System
* Stellarium version: stellarium-0.18.0-win64.exe
* Operating system: Windows 10 Pro
* Graphics Card: NVidia Geforce GTX 1060 6GB Geforce Game-ready driver version 390.77

### Logfile 
2018-05-02T01:16:09
Operating System: Windows 10
Product Name: Windows 10 (10.0)
Compiled using MSVC++ 14.0 (Visual Studio 2015)
Qt runtime version: 5.9.4
Qt compilation version: 5.9.4
Addressing mode: 64-bit
Total physical memory: 16287 MB
Available physical memory: 10159 MB
Physical memory in use: 37%
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Processor speed: 3600 MHz
Processor name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
C:\Program Files\Stellarium\stellarium.exe 
 -------------------------------------------------------
[ This is Stellarium 0.18.0 - http://www.stellarium.org ]
[ Copyright (C) 2000-2018 Fabien Chereau et al.         ]
 -------------------------------------------------------
Writing log file to: "C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\batti\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.6.0 NVIDIA 390.77"
Current Format:  QSurfaceFormat(version 4.6, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
StelMainView::init
Detected: OpenGL "4.6"
Driver version string: "4.6.0 NVIDIA 390.77"
GL vendor is "NVIDIA Corporation"
GL renderer is "GeForce GTX 1060 6GB/PCIe/SSE2"
GL Shading Language version is "4.60 NVIDIA"
GLSL Version Number detected:  4.6
GLSL version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\batti\\AppData\\Local\\stellarium\\stellarium\\cache"
StelLocation::createFromLine(): TimeZone name for  "Bloomington"  not found. Translating "system_default"  to  "system_default"
Sky language is  "en_US"
Couldn't load translations for language  "en_US" in section "stellarium-planetary-features"
Empty translation file for language  "en_US" in section "stellarium-planetary-features"
Planetary features language is  "en_US"
Application language is  "en_US"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
Loaded 77 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\batti\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
Loaded 102 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15466 / 15471 items of planetary surface nomenclature
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_7.cat: 0_0v0_7; 4979"
"Loading .\\stars\\default\\stars_1_0v0_7.cat: 1_0v0_7; 21806"
"Loading .\\stars\\default\\stars_2_0v0_7.cat: 2_0v0_7; 150850"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
"Loading C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_4_1v0_2.cat: 4_1v0_4; 1692779"
"Loading C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_5_2v0_1.cat: 5_2v0_1; 7083058"
"Loading C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_6_2v0_1.cat: 6_2v0_1; 24670782"
"Loading C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_7_2v0_1.cat: 7_2v0_1; 50733321"
"Loading C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_8_2v0_1.cat: 8_2v0_1; 92304337"
Finished loading star catalogue data, max_geodesic_level:  8
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4506 / 4506 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6916 / 6916 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.4 (standard edition)"
Loaded 90415 DSO records
Loading DSO outline data ...
Loaded 63 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 848 / 848 common star names
Loading DSO name data ...
Loaded 1012 / 1029 DSO name records successfully
WARNING - No position data for 17 objects: "PGC 621, PGC 2345, PGC 2906, PGC 2907, PGC 14098, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Loaded 54 / 54 asterism records successfully for culture "western"
Loaded 44 / 44 asterism names
stel.OpenGLArray: Vertex Array Objects are supported
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "EquationOfTime"
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "FOV"
Loaded plugin "MeteorShowers"
MeteorShowersMgr: Loading catalog file: "C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Observability"
Loaded plugin "Oculars"
Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
Oculars::validateIniFile ocular.ini exists at:  "C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateIniFile found existing ini file version  3.1
Loaded plugin "Satellites"
[Satellites] loading catalog file: "C:\\Users\\batti\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Loaded plugin "TelescopeControl"
[TelescopeControl] Only embedded telescope servers are available.
[TelescopeControl] Adding device model: "Meade AutoStar compatible" "Any telescope or telescope mount compatible with Meade's AutoStar controller." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Meade LX200 (compatible)" "Any telescope or telescope mount compatible with Meade LX200." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Meade ETX70 (#494 Autostar, #506 CCS)" "Meade's ETX70 with the #494 Autostar controller and the #506 Connector Cable Set." "TelescopeServerLx200" 1500000
[TelescopeControl] Adding device model: "Losmandy G-11" "Losmandy's G-11 telescope mount." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Wildcard Innovations Argo Navis (Meade mode)" "Wildcard Innovations' Argo Navis DTC in Meade LX200 emulation mode." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Celestron NexStar (compatible)" "Any telescope or telescope mount compatible with Celestron NexStar." "TelescopeServerNexStar" 500000
[TelescopeControl] Adding device model: "Sky-Watcher SynScan (version 3 or later)" "Any Sky-Watcher mount that uses version 3 or later of the SynScan hand controller." "TelescopeServerNexStar" 500000
[TelescopeControl] Adding device model: "Sky-Watcher SynScan AZ GOTO" "The Sky-Watcher SynScan AZ GOTO mount used in a number of telescope models." "TelescopeServerNexStar" 500000
[TelescopeControl] Loaded successfully 1 telescopes.
Initializing planets GL shaders... 
  OpenType support missing for "Verdana", script 11
  OpenType support missing for "MS Shell Dlg 2", script 11
  OpenType support missing for "Arial", script 11
  OpenType support missing for "MS UI Gothic", script 11
  OpenType support missing for "SimSun", script 11
  OpenType support missing for "Verdana", script 12
  OpenType support missing for "MS Shell Dlg 2", script 12
  OpenType support missing for "Arial", script 12
  OpenType support missing for "MS UI Gothic", script 12
  OpenType support missing for "SimSun", script 12
  OpenType support missing for "Verdana", script 13
  OpenType support missing for "MS Shell Dlg 2", script 13
  OpenType support missing for "Arial", script 13
  OpenType support missing for "MS UI Gothic", script 13
  OpenType support missing for "SimSun", script 13
  OpenType support missing for "Verdana", script 14
  OpenType support missing for "MS Shell Dlg 2", script 14
  OpenType support missing for "Arial", script 14
  OpenType support missing for "MS UI Gothic", script 14
  OpenType support missing for "SimSun", script 14
  OpenType support missing for "Verdana", script 16
  OpenType support missing for "MS Shell Dlg 2", script 16
  OpenType support missing for "Arial", script 16
  OpenType support missing for "MS UI Gothic", script 16
  OpenType support missing for "SimSun", script 16
  OpenType support missing for "Verdana", script 17
  OpenType support missing for "MS Shell Dlg 2", script 17
  OpenType support missing for "Arial", script 17
  OpenType support missing for "MS UI Gothic", script 17
  OpenType support missing for "SimSun", script 17
  OpenType support missing for "Verdana", script 18
  OpenType support missing for "MS Shell Dlg 2", script 18
  OpenType support missing for "Arial", script 18
  OpenType support missing for "MS UI Gothic", script 18
  OpenType support missing for "SimSun", script 18
  OpenType support missing for "Verdana", script 19
  OpenType support missing for "MS Shell Dlg 2", script 19
  OpenType support missing for "Arial", script 19
  OpenType support missing for "MS UI Gothic", script 19
  OpenType support missing for "SimSun", script 19
  OpenType support missing for "Verdana", script 20
  OpenType support missing for "MS Shell Dlg 2", script 20
  OpenType support missing for "Arial", script 20
  OpenType support missing for "MS UI Gothic", script 20
  OpenType support missing for "SimSun", script 20
  OpenType support missing for "Verdana", script 32
  OpenType support missing for "MS Shell Dlg 2", script 32
  OpenType support missing for "Arial", script 32
  OpenType support missing for "MS UI Gothic", script 32
  OpenType support missing for "SimSun", script 32
  OpenType support missing for "Verdana", script 10
  OpenType support missing for "MS Shell Dlg 2", script 10
  OpenType support missing for "Arial", script 10
  OpenType support missing for "MS UI Gothic", script 10
  OpenType support missing for "SimSun", script 10

**Comment by alex-w** [comment]
Please check latest beta

**Comment by beamtuner** [comment]
ok, I'll give it a try.

**Comment by beamtuner** [comment]
The beta, stellarium-0.90.0.15924-win64.exe, seems to be working correctly. Tnx.

**Comment by gzotti** [comment]
This was also reported in https://bugs.launchpad.net/stellarium/+bug/1764084
