### ISSUE TITLE
Update build instructions to the latest versions of Visual Studio and Qt

### ISSUE THREAD

**Issue by Thomas1664** [Stellarium/stellarium#1443]
### Expected Behaviour
Show instructions for building on Windows with the latest versions of Visual Studio and Qt.

### Actual Behaviour
`BUILDING.md` uses Visual Studio 2017 and Qt 5.9 in the Windows section

### Steps to reproduce
See `BUILDING.md`

**Comment by gzotti** [comment]
Please try to build with MSVC2019, Qt5.15.2, record exactly what behaves differently, and suggest a PR which in detail explains the relevant differences.
