### ISSUE TITLE
Grid coordinate labels off screen

### ISSUE THREAD

**Issue by RickWayne** [Stellarium/stellarium#1445]
### Expected Behaviour
Labels for grid systems should be readable

### Actual Behaviour
Most labels only  partly onscreen (screenshot)

### Steps to reproduce
Open program, press Z key to show azimuth grid (equatorial shows same behavior)

### System
* Stellarium version: 0.18.2
* Operating system: Mac OS 11.1
* Graphics Card: Radeon Pro 560X 4 GB
* Screen type (if applicable): MacBook Pro 15" 2018

<img width="851" alt="Screen Shot 2020-12-28 at 12 18 10 PM" src="https://user-images.githubusercontent.com/5933823/103235575-2557a900-4908-11eb-856c-3c45619d10fc.png">

**Comment by alex-w** [comment]
Please check v0.20.4 and attach log.txt from Stellarium

**Comment by alex-w** [comment]
Damn! Your macOS is 11.1 nd you cannot check v0.20.4 :-/
