### ISSUE TITLE
DisplayPort 1.2 DaisyChain Monitors Block Startup 

### ISSUE THREAD

**Issue by hansardj** [Stellarium/stellarium#1448]
[
### Expected Behaviour
Stellarium Startup Completes when it is intitiated.

### Actual Behaviour
Describe or maybe attach a screenshot?
Stellarium Startup Splash Screen appears yet no updates flash in the lower left corner of the splash screen related to the loading of the modules.  A few seconds after the Splash Screen appears it closes without any feedback.  

### Steps to reproduce
My system has 5 monitors where two are displays that are daisy chained using DisplayPort 1.2 Daisy Chain feature.  I determined by disabling the 2 daisy chanined monitors that Stellarium would start up.  After it started up I then reenabled the 2 disabled monitors and then took the Stellarium window and spread it over the monitors without issue.  

### System
* Stellarium version: stellarium-0.20.4-win64.exe
* Operating system: Windows 10 19042.685
* Graphics Card: <Manufacturer NVIDIA, Model (NVIDIA Quadro T2000, 27.21.14.5256>
* Screen type (if applicable): 5 HP HC270 monitors in Portrait mode (Flipped and Unflipped), 2560x1440, 100% scaling

### Logfile 
2020-12-29T16:49:11
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 15.9 (Visual Studio 2017)
Qt runtime version: 5.12.6
Qt compilation version: 5.12.6
Addressing mode: 64-bit
Total physical memory: 32469 MB
Available physical memory: 24786 MB
Physical memory in use: 23%
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Processor speed: 2304 MHz
Processor name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
C:\Program Files\Stellarium\stellarium.exe 
 -----------------------------------------------------
[ This is Stellarium 0.20.4 - https://stellarium.org/ ]
[ Copyright (C) 2000-2020 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "C:\\Users\\Admin\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\Admin\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file  "C:\\Users\\Admin\\AppData\\Roaming\\Stellarium\\config.ini"  does not exist. Copying the default file.
Config file is:  "C:\\Users\\Admin\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)

###LOG FILE ENDS

**Comment by alex-w** [comment]
Please try run Stellarium in ANGLE mode

**Comment by gzotti** [comment]
I have used an NVidia NVS system with 5 monitors (to develop), then 5 projectors (for the museum) without issues. This is almost certainly nothing we can solve, but a particularity of your setup. I also don't complain about my flakey Thunderbolt3 connection here. Please seek advice from Qt, Microsoft, NVidia, monitor or even cable vendors.

**Comment by alex-w** [comment]
@hansardj please respond. Else we will close this issue.

**Comment by hansardj** [comment]
Using Stellarium in ANGLE mode resolved the problem.  Thanks for the follow up prompt.
