### ISSUE TITLE
Satellite Plugin feature request

### ISSUE THREAD

**Issue by beamtuner** [Stellarium/stellarium#145]
Would like an option allowing display of only satellites currently visible.

**Comment by gzotti** [comment]
What do you mean? Activate "Realistic Mode..." in the satellite config panel, and see dots of varying brightness zip around.

**Comment by beamtuner** [comment]
The dots can be very hard to see, unless labels are turned on, at which point the labels can really clutter the view.
Would like an option that displays only the visible little graphic satellites.

**Comment by alexandre137** [comment]
hi i m using stellarium web

**Comment by alexandre137** [comment]
i need of help my request is valid
