### ISSUE TITLE
Update Stellarium Telescope position after finding object

### ISSUE THREAD

**Issue by kazziekat** [Stellarium/stellarium#1452]
The Problem:  
     There is no way to have Stellarium update/sync a telescopes current position.  I select Jupiter in Stellarium and press ctrl + 1 to slew the telescope to it's position.  However, because things aren't always perfect, the actual telescope position is off and needs manually adjusted to actually show Jupiter in the telescope.  This now creates the problem in that the scope position in Stellarium is now off of Jupiter.  This difference between Stellarium and the real world makes it very hard to actually find objects throughout the night.  

The Solution:
     Have a hotkey combo to tell Stellarium where the telescope is actually positioned.
1.  Select object in Stellarium
2. Slew to object (ctrl + 1)
3. Manually adjust telescope position onto real object in the sky via eqmod (scope position is now off in Stellarium)
4. Press ctrl + 3 (or whatever hotkey combo) to tell Stellarium the scope is now actually on the target (Stellarium is now synced and shows scope position on the target). 

Alternatives:
     Finding another program to replace Stellarium :(

Additional context:
     I understand that the old StellariumScope did have this feature, but stellariumScope complains about using itself with the latest versions of Stellarium...such an important feature shouldn't have been lost in the transition to telescope control directly within Stellarium.  Please add this feature as it will help save lots of people lots of time and frustration...and make Stellarium even better than it already is :)

I have no idea how it works, but isn't it just a matter of having Stellarium set new coordinates for the telescope position indicator?

Thanks,
kazziekat

**Comment by alex-w** [comment]
The SYNC feature was implemented 2 years ago and it can be called through button or hotkey

**Comment by kazziekat** [comment]
@alex-w    Oh ok, Great! Which button or hotkey? lol

So after some more research I saw many others don't know how to sync the reticle in Stellarium either...

ctrl + shift + (number of telescope)
ie.  ctrl + shift + 1

thanks 🤪
