### ISSUE TITLE
sun analemma

### ISSUE THREAD

**Issue by LivioE** [Stellarium/stellarium#1454]
Hi everybody. Happy new year to all.
In the previous 20.3 the simulation of sun analemma was possible. With the same setting, in 20.4 is not possibile. I use in both version the 'astronomical calculation' window, ephemeris sub menu, and set: SUN, date interval.
In 20.3 I see immediately the analemma as typical figure, in 20.4 the marks (sun position at same hour and different date) are distribuited along ecliptic.   Why ?

**Comment by gzotti** [comment]
Don't forget to activate horizontal coordinates to see the analemma in horizontal coordinates.

**Comment by gzotti** [comment]
@LivioE does that answer your question?

**Comment by LivioE** [comment]
Thanks very much. Yes it's all in order
