### ISSUE TITLE
Filter the current view by magnitude

### ISSUE THREAD

**Issue by salarmehr-cbs** [Stellarium/stellarium#1458]
I believe it would be dramatically useful to be able to manually filter the celestial object by their magnitude. Maybe a slide controller or a text box to enter the value manually.

**Comment by gzotti** [comment]
Why?

**Comment by salarmehr-cbs** [comment]
@gzotti why what? If you mean how it can be useful, it helps you to set the visible object in the sky according to visibility or clarity of the sky in your area. The visible items on the app are the visible ones in the sky.

**Comment by alex-w** [comment]
Partially these filters were added 15 years ago, partially - 7 years ago - why you just do not use it?

**Comment by salarmehr-cbs** [comment]
@alex-w could you advise how can I access them? I could not find any filtering mechanism.

**Comment by gzotti** [comment]
This program's aim is to give a realistic impression how the sky looks to the naked eye and through a telescope. You therefore cannot display e.g. just mag5 stars. If you artificially want more stars than you can see, play with the star scale settings. If you want to clip stars at mag3, do so in the stars settings.  If you want to visualize the effects of light pollution, change the Bortle scale value in the program menu. If you want more DSO than useful, activate all catalogs and increase the position of the DSO marker slider. 

Give an example what you want to filter and how the display would change from the way the program currently works.

**Comment by axd1967** [comment]
@salarmehr-cbs 

have you tried F4:
![image](https://user-images.githubusercontent.com/3529789/103531534-d7075480-4e89-11eb-85a0-6c8d78180775.png)
![image](https://user-images.githubusercontent.com/3529789/103531551-e1c1e980-4e89-11eb-855b-2e6a254f9b5c.png)
![image](https://user-images.githubusercontent.com/3529789/103531573-ed151500-4e89-11eb-8640-e496414f4544.png)

for naked eye, you could select magnitude 6.

but finally: are you talking about the desktop or the web version?

**Comment by salarmehr-cbs** [comment]
@axd1967 I talk about both platforms. (the feature can be added to desktop one first)

Those options do not provide the feature that I'm referring too. We need a simple slider similar to the below one so set the minimum magnitude and while you are changing it will automatically be applied to the current view. Once you reach a value that matches to the current naked eye view of the sky you leave the slider. Now visible objects will be quickly identified and located without seeing invisible objects on the app. 

![image](https://user-images.githubusercontent.com/63023315/103735150-93574b00-5041-11eb-944f-f1bf2e6e3c3d.png)

**Comment by gzotti** [comment]
Visibility is a mix of many factors: eye sight, dark adaptation, natural sky brightness, star brightness, light pollution, ... Average conditions and a pretty good mix of those file-tuning elements already exist.

You say the magnitude limitation fields are not what you are able to use, but you want to use a slider for magnitude limitation? 
I. e. no functional change, you just want a different GUI control element? Consider that sliders take a lot more screen space and are usually not as finely tunable as the numerical spinners.

**Comment by axd1967** [comment]
> @axd1967 I talk about both platforms. (the feature can be added to desktop one first)
> 
> Those options do not provide the feature that I'm referring too. We need a simple slider similar to the below one so set the minimum magnitude and while you are changing it will automatically be applied to the current view. Once you reach a value that matches to the current naked eye view of the sky you leave the slider. Now visible objects will be quickly identified and located without seeing invisible objects on the app.
> 
> I believe this is really quick to implement and has no downside. The slider can become active by a new toggle button on the bottom bar and while it's inactive, we can consider the current functionality wich is auto.
> 
> ![image](https://user-images.githubusercontent.com/63023315/103735150-93574b00-5041-11eb-944f-f1bf2e6e3c3d.png)

that is already possible, even if you need a little bit more effort. 
watch:

https://user-images.githubusercontent.com/3529789/103764123-2f219080-501b-11eb-8521-6b2e028a17b1.mp4

what you indeed want is what @gzotti describes. 

I sometimes need such a feature in order to match what I see with what Stlr shows; for that, I play with Bortle and magnification settings (via the mouse wheel). The question is whether this use case justifies adding a **redundant** control. How often will you do this?

**Comment by salarmehr-cbs** [comment]
![image](https://user-images.githubusercontent.com/63023315/104282325-fb56d700-5502-11eb-803a-d7576a8cf01c.png)
![image](https://user-images.githubusercontent.com/63023315/104282348-0578d580-5503-11eb-8407-7418be6f3833.png)
![image](https://user-images.githubusercontent.com/63023315/104282396-175a7880-5503-11eb-9ae4-7830668117b4.png)

Android version of SkyPortal has neatly implemented this feature. Exactly the way that I was describing earlier.

**Comment by alex-w** [comment]
As I said before - this feature already implemented many years ago - why you just do not use it?

**Comment by salarmehr-cbs** [comment]
Thanks. I'm just suggesting an improvement in the UI/UX. If possible. 
Also is it possible to assign a shortcut for this feature currently? so without and UI change, I can use my keyboard to achieve the same?

**Comment by alex-w** [comment]
> Thanks. I'm just suggesting an improvement in the UI/UX. If possible.

I see no seriously improvements by using slider for this feature.

> Also is it possible to assign a shortcut for this feature currently? so without and UI change, I can use my keyboard to achieve the same?

The shortcuts are implemented already too - just assign wanted keys and use it.

**Comment by gzotti** [comment]
There are enough fine-tuning settings already available, even if the star scale settings do not directly indicate a mag limit. The default mag limit is auto-determined and works pretty well, and you can override it with the star scale settings.  

I'd call this a case of https://github.com/Stellarium/stellarium/wiki/FAQ#why-dont-you-implement

**Comment by axd1967** [comment]
@salarmehr-cbs 

there are indeed shortcuts (F7) that you can assign, that will solve your issue:

![image](https://user-images.githubusercontent.com/3529789/104300543-ebb99d00-54c6-11eb-9d3a-94f6f9082fbc.png)

**Comment by salarmehr** [comment]
@axd1967 many thanks for sharing it. I assigned the shortcut and it works like a charm. (I assigned page up/page down for this purpose).
