### ISSUE TITLE
Main display feature request

### ISSUE THREAD

**Issue by beamtuner** [Stellarium/stellarium#146]
Would like a switchable option allowing selecting,  centering view, slewing scope, and tracking for any chosen blank spot in the sky, to allow framing an image properly in a sensor when taking pictures containing multiple objects. Could toggle option off to restore normal object selection behavior. 
In other words, when active, feature would allow treating any chosen spot in the sky as if it were a "virtual object" for purposes of the "center on object" and "slew to object function". Toggling the "virtual object" button off would restore normal behavior.

**Comment by gzotti** [comment]
Put a marker (Shift-click) anywhere, "Find" it [F3]. Or slew telescope via hand controller.

**Comment by beamtuner** [comment]
Quoting Georg Zotti <notifications@github.com>:

> Put a marker (Shift-click) anywhere, "Find" it [F3]. Or slew 
> telescope via hand controller.
Shift-click does not put a marker "anywhere". 
It puts a marker on a nearby object, which is not what i want to do. 
I already know how to mark objects.
You cannot put a marker on a blank part of the sky.
"Find it" F3 finds objects. I am not trying to find objects,
I'm sorry that my feature request isn't clear.
I don't know how to make it more clear, but since I have failed to get my meaning across, you can consider the request withdrawn.
If I have to stand out in the cold with my hand controller to slew my scope to where I want to drive it, when the software could easily be modified to do so instead, I see no reason to continue the discussion.
Thank you for your time.
Have a nice day.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Stellarium_stellarium_issues_146-23issuecomment-2D385885117&d=DwICaQ&c=nE__W8dFE-shTxStwXtp0A&r=fvY8okovU0pTuI4h47uW6A&m=-AZB7aVc17LXGr-ZmF_9SeUDgC42IQmMevhkUgSPaRI&s=ZXLUOGLQTsXfqWha9czJRMQY2oJEhlrtKBGF56BXeOs&e=

  

-- 
Gene

beamtuner@att.net  Live  - Keep all precepts
battin@msu.edu     Learn - Practice all good Dharma
...                Love  - Save the many beings

**Comment by gzotti** [comment]
No need to be miffed. Lacking further information, I describe V0.18.0 on Windows. 

The Help panel and Appendix A.1 list:
```
Add custom marker                        | Shift & left click
Delete marker closest to mouse cursor    | Shift & right click
Delete all custom markers                | Shift & Alt & right click
```
This works perfectly on all computers in my reach. "Marker 1" etc. can then be selected (mouse click), found in the F3 Search panel, centered, slewed to, whatever. Primary feature request solved. 

It is great that you know that the software can "easily" be modified. This is a community project. We do accept pull requests (code contributions) for useful changes when they work on all platforms. Have a nice day.

**Comment by beamtuner** [comment]
Quoting Georg Zotti <notifications@github.com>:

> No need to be miffed. Lacking further information, I describe V0.18.0 
> on Windows.
>
> The Help panel and Appendix A.1 list:
> ```
> Add custom marker                        | Shift & left click
> Delete marker closest to mouse cursor    | Shift & right click
> Delete all custom markers                | Shift & Alt & right click
> ```
> This works perfectly on all computers in my reach. "Marker 1" etc. 
> can then be selected (mouse click), found in the F3 Search panel, 
> centered, slewed to, whatever. Primary feature request solved.
>
> It is great that you know that the software can "easily" be modified. 
> This is a community project. We do accept pull requests (code 
> contributions) for useful changes when they work on all platforms. 
> Have a nice day.

Sorry for my temper.

For some reason, when I tried the shift-click method, I was not getting the custom marker, just a marker on a nearby object. A reboot cured this, though I have no idea how or why.
Thanks for your patience. The efforts you guys put into making this software so usable
and sophisticated are really appreciated.

-- 
Gene

beamtuner@att.net  Live  - Keep all precepts
battin@msu.edu     Learn - Practice all good Dharma
...                Love  - Save the many beings
