### ISSUE TITLE
Skybox.ssc default folder and GridLinesMgr issue

### ISSUE THREAD

**Issue by TheRoam** [Stellarium/stellarium#1461]
### Expected Behaviour
Skybox.ssc should hide your gridlines and then move around taking a screenshot of the six faces composing a cube needed to model a skybox.

It should save six image files in the default folder, plus a .txt data file,

### Actual Behaviour
When your gridlines are disabled by default, the script just doesnt start running and does nothing (my guess: it's supposed to hide them automatically, but they do not exist, therefore [undefined] error).

core.getEnv also produces an error when it cannot find the default folder path (maybe because I'm not running on Windows).

### Steps to reproduce

0.Use Linux Ubuntu or similar (Mint in my case)
1.Start Stellarium
2.(if not done already) Hide gridlines
3.Go to Configuration and click "Save View" and "Save Configuration"
4.Restart Stellarium
5.Go to Scripts and run "skybox". Nothing should happen.
6.Open the log file and check for GridLinesMgr error: GridLinesMgr.getFlagCurrentVerticalLine() result is [undefined]
7.If uncommented (as it is not needed if you hide them manually), there is an error finding the output folders, so I also set them manually in the script.

### System
* Stellarium version: Bug happened on 0.20 flatpak, then retested on 0.18 desktop version so I could manually edit the script.
* Operating system: Linux Mint 19
* Graphics Card: not applicable
* Screen type (if applicable): not applicable

### Logfile 
#Edited Attached log file and working script with local routes.
[1-log_current-script.txt](https://github.com/Stellarium/stellarium/files/5777644/1-log_current-script.txt)
[2-script_skybox_core-getEnv.txt](https://github.com/Stellarium/stellarium/files/5777648/2-script_skybox_core-getEnv.txt)
[2-log_core-getEnv-tweak.txt](https://github.com/Stellarium/stellarium/files/5777649/2-log_core-getEnv-tweak.txt)
[3-script_skybox_GridLinesMgr-tweak.txt](https://github.com/Stellarium/stellarium/files/5777651/3-script_skybox_GridLinesMgr-tweak.txt)
[3-log_GridLinesMgr-tweak.txt](https://github.com/Stellarium/stellarium/files/5777652/3-log_GridLinesMgr-tweak.txt)

Edited: posted logs were not very clear so I attach new ones showing individual issues.

**Comment by gzotti** [comment]
The script should preserve gridlines if the user has them active. However, the current vertical line does not make sense in the skybox and is therefore switched off.  I never disable the GridlineMgr, so never ran into this issue.

**Comment by TheRoam** [comment]
Ok, I see. I'm not a programmer so probably misunderstood the code. Maybe the script could do a few more pre-checks to cover these cases. Thanks for looking into it and keep up the good work!

**Comment by TheRoam** [comment]
Edited attached logs and scripts for clarity

**Comment by gzotti** [comment]
@TheRoam Out of curiosity: what program are you using on Mint that utilizes such skybox?

**Comment by TheRoam** [comment]
im running Unity3D. I was looking for a cool looking night skybox (as realistic as possible) and Stellarium's one is perfect as it's customizable.

**Comment by gzotti** [comment]
Indeed. That's the point with this work, see also https://github.com/Stellarium/stellarium-unity and https://doi.org/10.14434/sdh.v4i1.31041. There is a stupid typo in the script. Just change spelling to `GridLinesMgr`. Now investigating the envvars problem...

**Comment by gzotti** [comment]
Seems I have trouble running stellarium on a more Linuxy system after my WSL update to Ubuntu 20.04 a few days ago. 
`
stellarium: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory`

The library exists in /usr/lib/x86_64-linux-gnu/ like the rest of the Qt libs. `ldd /usr/bin/stellarium` finds all the other libs, just libQt5Core.so.5 points to nowhere. Any idea what to try now? `sudo ldconfig /usr/lib/x86_64-linux-gnu`  did not help.

**Comment by TheRoam** [comment]
did you update Stellarium or Qt? I would reinstall Stellarium from the official Ubuntu repo and it should spot any missing dependencies and ask you to install them as well. It might no be the most up to date Stellarium version, but it should be a working version for your Linux specific distro and will have the correct dependencies.

I dont have native Ubuntu, so my guess would be:
-first have the repo up to date:
_sudo apt-get update
sudo apt-get upgrade_
-see what stellarium version you have in the repo
_sudo apt-cache search stellarium
(you should see one of these options: [https://packages.ubuntu.com/search?keywords=stellarium&searchon=names&suite=all&section=all])_
-install stellarium
_sudo apt-get install stellarium_

if you didnt get a message to update dependencies in the process of repo update and stellarium install, I would reinstall Qt as well, just in case, which for Ubuntu might be:
_sudo apt-get install qt5-default_

**Comment by gzotti** [comment]
I had it running on WSL/Ubuntu 18.04 LTS. A few days ago I did a do-release-upgrade. This usually works nicely, just not this time. I just added again our repo and try installing again, just I have a terrible line. Will take a while...

**Comment by gzotti** [comment]
Did not help :-(

```
$ stellarium
stellarium: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

$ ldd /usr/bin/stellarium
        linux-vdso.so.1 (0x00007ffffd6ac000)
        libQt5PrintSupport.so.5 => /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 (0x00007f9f8dcd0000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9f8dcb0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9f8dc8d000)
        libQt5MultimediaWidgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5MultimediaWidgets.so.5 (0x00007f9f8dc60000)
        libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f9f8d5c0000)
        libQt5Multimedia.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so.5 (0x00007f9f8d490000)
        libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f9f8cea0000)
        libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f9f8ccd0000)
        libQt5Script.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Script.so.5 (0x00007f9f8ca20000)
        libQt5Positioning.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Positioning.so.5 (0x00007f9f8c980000)
        libQt5SerialPort.so.5 => /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so.5 (0x00007f9f8c960000)
        libQt5Core.so.5 => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9f8c760000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9f8c611000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9f8c5f0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9f8c3f0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9f8f08f000)
        libQt5Core.so.5 => not found
        ...

$ ls -l /usr/lib/x86_64-linux-gnu/libQt5Core.*
-rw-r--r-- 1 root root    1240 Apr  9  2020 /usr/lib/x86_64-linux-gnu/libQt5Core.prl
lrwxrwxrwx 1 root root      20 Apr  9  2020 /usr/lib/x86_64-linux-gnu/libQt5Core.so -> libQt5Core.so.5.12.8
lrwxrwxrwx 1 root root      20 Apr  9  2020 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 -> libQt5Core.so.5.12.8
lrwxrwxrwx 1 root root      20 Apr  9  2020 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12 -> libQt5Core.so.5.12.8
-rw-r--r-- 1 root root 5519624 Apr  9  2020 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8

$ cat /etc/ld.so.conf.d/x86_64-linux-gnu.conf
# Multiarch support
/usr/local/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu

$ ldconfig  -p | grep libQt5Core.so.5
        libQt5Core.so.5 (libc6,x86-64, OS ABI: Linux 3.17.0) => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
$ ldconfig  -p | grep libQt5OpenGL.so.5
        libQt5OpenGL.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5
$ ldconfig  -p | grep libQt5SerialPort.so.5
        libQt5SerialPort.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so.5
$ ldconfig  -p | grep libQt5Gui.so.5
        libQt5Gui.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5

$ uname -a
Linux XXXXX 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

```
Frustrating. The libraries are all there. Only libQt5Core.so has the "OS ABI: Linux 3.17.0" Does that refer to an old kernel version? 

Will try to check the issue on my dual-boot now...

**Comment by gzotti** [comment]
The script needed a few little changes. See the beginning. On Linux you must also set a config variable, see log.txt when the data file is not where you expect it to be.

**Comment by gzotti** [comment]
https://stackoverflow.com/questions/63627955/cant-load-shared-library-libqt5core-so-5 has the solution to the library problem under WSL1.

**Comment by TheRoam** [comment]
I just did a fresh install of the weekly snap and the new script works great! cheers!
