### ISSUE TITLE
Corona enlarged when the Moon is?

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1464]
I don't know if this is on purpose, but the corona texture is not enlarged when the Moon is. That means, if the Moon is x 4 in size, the corona of the Sun is hidden behind the Moon.

BTW: The word "corona" feels weird to use in this context these days.  :(

**Comment by gzotti** [comment]
Also the Sun is hidden behind the oversized Moon. Of course, for eclipse simulation, use a correctly-sized moon. 

On your other remark, last April I had pointed out Corona Borealis as the "constellation of the year 2020"... The name just occurs in many "crowned" contexts.

**Comment by Atque** [comment]
@gzotti I thought it might be intentional. It was just a heads-up in case it was unknown to you devs. Closing this, since it is not a bug.

It would really fit the year... It's a nice word, used even in currencies (Swedish _krona_, Czech _koruna_ etc.).
