### ISSUE TITLE
Are there any plans to switch to OpenGL Core profile?

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#1465]
While working on the integration of ShowMySky atmosphere renderer into Stellarium, I've come across the fact that Stellarium requests OpenGL 2.1 from `QSurfaceFormat`, which means that, even if it uses GL 3.1+ features, it remains in the compatibility profile. This makes it impossible to actually use ShowMySky with Stellarium on e.g. Intel hardware on Linux, since the driver there, based on Mesa, doesn't support GL 3.1+ compatibility profile.

From my experiments here, at least two places need some rework to support Core profile:

* `StelTexture`, which uses `GL_LUMINANCE_ALPHA` format that's no longer supported by GL Core (this can be worked around by always using `GL_RGBA` for such textures)
* `StelPainter`/`StelOpenGLArray`, which use vertex attributes in the old way, by passing RAM pointers to `glVertexAttribPointer` instead of offsets in actual GPU-side buffers.
* Maybe something else, I've not been able to work around the incompatible vertex attribute usage.

My question thus is, are there any plans to switch Stellarium to GL Core profile? Is there any work in progress to make it forward-compatible?

**Comment by gzotti** [comment]
If you know what to do, I think you are welcome to develop a PR for this and other OpenGL optimisations. Just make sure all components keep working on all platforms :-) I cannot say what generation of computers will fall out of use then? My oldest (Geforce 8xxx) has OpenGL 3.3. What about OpenGL ES2 devices, Windows PCs with necessity to run via ANGLE? 
However, in (hopefully) a few days a large branch will be integrated (#502). Although it does not introduce many changes w.r.t. OpenGL, I have restructured a few places. Maybe wait for completion of that.

**Comment by 10110111** [comment]
> Just make sure all components keep working on all platforms :-)

I'll need some help with this :) I can check on multiple machines with x86/x86_64 Linux, but not much more than that.

> What about OpenGL ES2 devices, Windows PCs with necessity to run via ANGLE?

I'm not even sure what Windows PCs need ANGLE. Major GPU manufacturers seem to have been supplying OpenGL drivers, so I supposed pure OpenGL should be OK for virtually all Windows systems.

As for GLES devices, which are these? Raspberry Pi? I suppose Stellarium doesn't target Android/iOS.

**Comment by gzotti** [comment]
> > Just make sure all components keep working on all platforms :-)
> 
> I'll need some help with this :) I can check on multiple machines with x86/x86_64 Linux, but not much more than that.
> 
> > What about OpenGL ES2 devices, Windows PCs with necessity to run via ANGLE?
> 
> I'm not even sure what Windows PCs need ANGLE. Major GPU manufacturers seem to have been supplying OpenGL drivers, so I supposed pure OpenGL should be OK for virtually all Windows systems.

There are many older PCs without Geforce cards, Intel Core-i 2xxx or so, which have bad OpenGL support but work with DirectX9. 

See https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/windows/openglblacklists/default.json

Check for entries "disable_opengl" and without "disable_angle". All these systems still work with ANGLE.
I have 1-2 such devices to test (Windows).

Of course, also the world keeps turning, and Qt6 brings entirely new challenges. Somebody with good OpenGL (and other GPU tech like Vulkan?) skills could really help in the upgrading process, and ultimately we could decide to drop a few older systems from support by Qt6-based versions which would still have to be supported for a while in the Qt5-based builds.  You cannot imagine how many people demanded upgrades in the Qt4-based 0.12 series on XP systems of yesteryear when Qt5-based 0.15 was already out. (Thank @alex-w for this support!)

The question may be, is there a way to support both, with just minor runtime (command-line or autodetect) switches? Or (less comfortable, but we could probably live with it) compile time switches/#defines? We may also need some maintenance documentation. 

> As for GLES devices, which are these? I suppose Stellarium doesn't target Android/iOS. Raspberry Pi? Anything else?

As far as I can understand, ANGLE implements OpenGL ES2. Indeed, the "native" GL ES2 device which should remain a valid target is Raspberry Pi 3/4. I see that RPi4 now has GLES3.1 (https://developer-tech.com/news/2020/feb/03/raspberry-pi-4-opengl-es-conformant-vulkan-incoming/) I can accept Raspberry 3 without the new sky model (for tech reasons), but not without Stellarium. Another GLES2 target to try are some Odroid SBCs. Basically wherever Qt5 is fully supported Stellarium was running. 

The two of us don't build for Android, but some other people have done so (see a few related issues/PRs here), and it seems with a large enough screen their build works. However, a real Android version should probably build an entirely new GUI/menu structure better suited to typical screen sizes and input paradigms found with Android devices. I know nothing about iOS, but expect the same applies.

**Comment by 10110111** [comment]
OK, at least there needs to be some compatibility update to the codebase, even if `StelMainView` doesn't request GL3.3 Core. In particular, we need to get rid of `GL_LUMINANCE_ALPHA` in some way, and switch to using VAO instead of client-state-based vertex uploads. These both seem to be GLES2-compatible.

BTW, are there any binaries available to try on the Raspberry?

**Comment by gzotti** [comment]
I think if you have Ubuntu on RPi, at least some 0.18.* version is in the default Ubuntu repository. Not sure about packages in RaspberryOS. Admittedly, I usually just build from sources.

**Comment by 10110111** [comment]
> Admittedly, I usually just build from sources.

On the Pi itself? Or do you have a cross-build config?

**Comment by gzotti** [comment]
Just on the Pi. Use a 32GB SDcard and follow Linux instructions. On a Pi4 with 4GB, you don't even need a larger swapfile.

**Comment by 10110111** [comment]
OK, I'll see what I can do.
