### ISSUE TITLE
bug de interface

### ISSUE THREAD

**Issue by fabiosky2021** [Stellarium/stellarium#1467]
Minha linguagem Português do Brasil traduz essa mensagem para você melhor entender.
queria relata um bug de interface  no Windows 7 ultimaste quanto no windows 10 a barras de navegação não esta aparecendo https://docplayer.com.br/docs-images/65/53486112/images/157-0.jpg elas simplesmente sumiram mesmo ja desentalei vai vezes e nada de voltarem me ajuda a corrigir isso a verão 20

**Comment by gzotti** [comment]
Presumably another case of:

https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#menu-invisible-windows
