### ISSUE TITLE
constellation problem

### ISSUE THREAD

**Issue by snoitaleR** [Stellarium/stellarium#1474]
WIN10X64.19041.572
STELLARIUMX64.0.20.4.0
When the "config.ini" file is automatically created, the "sky_culture" = "western" parameter in the [localization] section is set in lowercase letters, so the constellation control keys do not work.

**Comment by alex-w** [comment]
Please more details

**Comment by snoitaleR** [comment]
After selecting the "Western" culture through the "Star Knowledge" tab, the "WESTERN" value is added to the "sky_culture" parameter in capital letters, after which the [B], [V], [C] and [R] keys work.

**Comment by gzotti** [comment]
Cannot confirm.

I deleted config.ini, started version 0.20.4 on Win10 20H2 x64. Western skyculture was active, and BCVR buttons worked. 
There is no "Star Knowledge" tab in the desktop version, the tab is labeled "Starlore". 
Selecting another starlore and storing configuration stores the other skyculture directory name. Going back to "Western" and storing settings stores "western" (in lowercase letters) as it should. 
I don't see where the key actions would be linked to skyculture names? They trigger display of whatever constellations/borders/art/... are available in the currently selected skyculture.
Do you have your own private copy of a "WESTERN" (capitalized directory name) sky culture?

**Comment by snoitaleR** [comment]
Yes, all folders are written in capital letters. Unfortunately, I don't know why.

**Comment by gzotti** [comment]
Google for: windows directories written in capitals. 

I don't think this is our problem.

**Comment by snoitaleR** [comment]
I agree. I will reinstall the program.

**Comment by alex-w** [comment]
Cannot confirm too.

**Comment by alex-w** [comment]
Cannot confirm too.

**Comment by alex-w** [comment]
@snoitaleR any news?
