### ISSUE TITLE
I cant open the program.

### ISSUE THREAD

**Issue by readsandwiches** [Stellarium/stellarium#1475]
### Expected Behaviour
Click the program in the start menu> it opens.
### Actual Behaviour
Click the program in the start menu> the Stellarium open screen opens up> nothing happens. 
Describe or maybe attach a screenshot?
![image](https://user-images.githubusercontent.com/51712333/105613335-be96a580-5d76-11eb-9564-3d0ed30d08d7.png)

### Steps to reproduce
open the program with Microsoft surface pro 3 with windows 10 which is compatible (3D graphics card which supports OpenGL 3.0 and GLSL 1.3 or OpenGL ES 2.0)
### System
* Stellarium version: <0.20.3>
* Operating system: <Windows, 10>
* Graphics Card: <Manufacturer intel, Model HD, 4400),>

### Logfile 
cannot find it (will update when I find it)

**Comment by gzotti** [comment]
What exactly happens if "nothing" happens? The splash screen appears. And then? Some error, warning, silent disappearance, or do you kill the process after 2 minutes?
Is this a first-time installation, or have you used Stellarium in previous versions? Have you updated (or did Windows Update update) the Intel graphics drivers? Have you tried ANGLE mode? 

The logfile is where the User Guide (chapter 5) says it is. It could contain some relevant info.

**Comment by readsandwiches** [comment]
silent disappearance, I have installed v 0.20.3 and updated it to 0.20.4 and it opened first, then it closed and I cannot open it anymore. I have tried angle mode

**Comment by readsandwiches** [comment]
Update: found log
[log.txt](https://github.com/Stellarium/stellarium/files/5861348/log.txt)

**Comment by gzotti** [comment]
According to the last lines therein, you have a misconfigured ocular. 
In your $USERDIR/modules/Oculars/ocular.ini, search for afov=0 and replace by some positive number that means apparent field of view. Zero is a meaningless value here. I cannot say if this is the reason for a silent abort, though.

$USERDIR is where you found log.txt

**Comment by readsandwiches** [comment]
so how do I fix it

**Comment by gzotti** [comment]
> search for afov=0 and replace by some positive number

**Comment by readsandwiches** [comment]
where

**Comment by gzotti** [comment]
Can you see my previous answer?

**Comment by readsandwiches** [comment]
oh yeah misread

**Comment by readsandwiches** [comment]
done

**Comment by readsandwiches** [comment]
OHMAHGAHD thanks
