### ISSUE TITLE
Help: how can I delete custom markers?

### ISSUE THREAD

**Issue by salarmehr** [Stellarium/stellarium#1476]
Shif+click creates a green marker:

![image](https://user-images.githubusercontent.com/2582036/105618917-1b5e9280-5e41-11eb-8ecc-67702332faa5.png)

How can I delete one or all of them?

**Comment by alex-w** [comment]
In Stellarium User Guide or F1 (Help) window you may find:
Shift + Alt + Right click — Delete all custom markers
Shift + Right click — Delete marker closest to mouse cursor
