### ISSUE TITLE
Is Stellarium compatible with Chromebook?

### ISSUE THREAD

**Issue by tksteed** [Stellarium/stellarium#1480]

**Comment by gzotti** [comment]
What kinds of programs can you install on a Chromebook?

**Comment by tksteed** [comment]
Honestly, I am not sure.  I am an educator and use Stellarium for my Online course.  I love the program.  I have a student this semester who cannot download it.  She is using a Chromebook.  That is pretty much all I know.  She is not local to where our campus is so I cannot ask her to just come to campus.  Any help is appreciated.


   [cid:b29dfed6-9772-4412-a8d8-f23c67b21e11]
   Karen Steed
   UAHT Math and Science Instructor,
   karen.steed@uaht.edu
   870-722-8272
[cid:fcc2a37e-a424-4a1e-b0ae-97c6c2475839]



________________________________

**Comment by gzotti** [comment]
Google finds information about the topic "install programs on Chromebook". It may depend on the model what you can do with it.  She should ask someone in her neighborhood for assistance. I have never seen such a thing. 

Depending on course content, you/she may consider using Stellarium web. (https://stellarium-web.org/)
It has similar appearance but other data and functionalities.

**Comment by tksteed** [comment]
Thank you.  I did make that suggestion to her. I thank you for your time.


   [cid:2af3c33a-b5e7-4acb-b366-8640650ceb49]
   Karen Steed
   UAHT Math and Science Instructor,
   karen.steed@uaht.edu
   870-722-8272
[cid:d645d18d-f842-4363-93e5-d87e9396c129]



________________________________

**Comment by alex-w** [comment]
As far as I know Chromebooks use Android as operating system and use can use at least 2 version of Stellarium (Stellarium Mobile and Stellarium Mobile Plus) for Android and one web edition of Stellarium.

**Comment by tksteed** [comment]
Thank you.  I have tried using only the web version, but it will not allow me to change location or time (or at least I don't see how to) and this is necessary for my labs.

Stellarium is a really great product and I am thankful for it.


   [cid:4e9e0284-e076-4054-96dc-746c925aa7cc]
   Karen Steed
   UAHT Math and Science Instructor,
   karen.steed@uaht.edu
   870-722-8272
[cid:82843386-c278-45fd-bcfa-79a1993b5933]



________________________________
