### ISSUE TITLE
Antisolar point for other planets

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1481]
The antisolar point feature is very nice, but I think it could be applied to other planets. It would be a point exactly 180 degrees from the sun, seen from planet center.

It would help a lot when searching for Jupiter oppositions from Mars etc.

**Comment by alex-w** [comment]
Note: antisolar point and opposition longitude are calculated in ecliptic coordinate system, which is not applicable outside of the Earth.

**Comment by Atque** [comment]
@alex-w Hm, I see. That makes it more complicated. Couldn't the point just be added by placing it exactly 180 degrees from the Sun center at all times?

**Comment by gzotti** [comment]
The antisolar point from a planet should be simple: it's at the heliocentric coordinates of the planet.

**Comment by Atque** [comment]
@gzotti Interesting. Would it be possible to calculate each planet's ecliptic pole (90 degrees from the antisolar point), and even an ecliptic for the planet?

**Comment by gzotti** [comment]
That's less easy. (Else I would have done it :-) 90 degrees away, sure. But in which direction? If you develop (or find) an algorithm to show a "planet ecliptic" in terms of ICRF, please forward it.

**Comment by Atque** [comment]
@gzotti Wouldn't it simply be in the direction of the Sun? And the ecliptic would be a great circle 90 degrees from the poles? Maybe I'm oversimplifying it...

**Comment by gzotti** [comment]
You can draw a circle 90° away from the antisolar point. You can draw another circle 90° away from the sun and try to intersect them. Hey, wait, they are identical by definition, right? 
3 points define a circle. Maybe the planet's motion vector can be used? It points tangentially along the orbit, so a circle 90° around this, intersecting with a 90° circle around the sun, would define the "ecliptic poles". This might define a sort of "current ecliptic circle" (just an idea). But where do you place the zero mark? How do you e.g. find the intersection of this circle with the planet's equator to define "spring equinox"? It's not on my shortlist of tasks, but you can do the math and we code it then. It's not something a typical user will ever see or need. Maybe I add such "planet ecliptic", but without partitions and labeled grid.

**Comment by alex-w** [comment]
I've switch calculation of anti solar point in ecliptic (J2000) frame ;)

**Comment by Atque** [comment]
@gzotti Ok, it's way more complicated than I had thought. I can't provide you with data or calculations. When I want to see the "ecliptic" of a planet (the true ecliptic), then I just use the ephemeris tool, so there is a workaround.

@alex-w Thank you for the fast solution. I can't build and test right now, but wouldn't using J2000 frame mean that the antisolar point will be off when using dates far in the past or future?

**Comment by gzotti** [comment]
about J2000 frame: No problem, that should be the correct solution.  Just try and see.

Yes, the ephemeris tool for the sun should give an "ecliptic line" as well...
