### ISSUE TITLE
Cannot screen share Stellarium on Zoom recording

### ISSUE THREAD

**Issue by Ethdhelwen** [Stellarium/stellarium#1484]
### Expected Behaviour
I wanted to record myself using Zoom showing some constellations to my school class and record it. We use this to do remote learning lessons.

### Actual Behaviour
The video recorded, but all that was shown on the screen was the initial picture of a field with the Sun up. It didn't move as I moved around the sky. Is this normal. Thank you for your advice.

### Steps to reproduce
Use Zoom.
Load up Stellarium.
Watch recording back.

### System
* Stellarium version: stellarium 0.20.4-win64
* Operating system: Windows 10 64
* Graphics Card: Nvidea GTX 960
* Screen type (if applicable): BENq GL2250

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
I’ve checked recording Stellarium demo within zoom and... it works as expected - without problem.

**Comment by gzotti** [comment]
I have given (and seen) several Zoom talks using Stellarium with my NVid**i**a Geforce GTX960M on Win10/x64 and have never seen a problem.  Did you install and update your NVid**i**a Geforce drivers properly?

**Comment by Ethdhelwen** [comment]
Hi Georg! Yes, I happened to do that last week. I've just tried another recording programme with the same result - this time I managed to see 15 minutes of the opening image, and 30 seconds from somewhere randomly within the recording. Odd that it's possible to record films/Youtube videos as they play, but not this. I'm not technical enough to know why, I'm afraid.

Hi Alex, I don't think that I understand the purpose of your comment. I don't believe that it will resolve my issue to know whether it worked just fine for you, without a little more detail (possible settings etc). But thanks for your interesting slice of your life! 🙂

________________________________

**Comment by Ethdhelwen** [comment]
Ah, some luck! Although the alt-S screenshot and folder doesn't seem to work for me, I am able to print screen and save screenshots in paint. I can make a mock-up of what I did and play the sound track commentary over the photos! Lesson saved! 🙂 Well, I'd be interested to hear if any settings come to mind for videos. Or maybe just time for a new more modern graphics card! And to think, I was counting myself amongst the fortunate that Cyberpunk 2077 manages to run on my PC! 🙂 At least finding out about Stellarium has inspired me to go outside and stargaze again after many years (due to cataracts/monocular vision turning the real sky into a hazy blur!) Thanks to you both and the Stellarium team, and I'll recommend it to my pupils this week to get into astronomy!

________________________________

**Comment by gzotti** [comment]
Alt-S switches star labels. Ctrl-S saves screenshots by default. You should be able to at least record videos with the recorder built into the Windows+G game bar and play those recordings via Zoom. And you don't need a better graphics card for Stellarium. What's Cyberpunk 2077? Talk about your "slice of your life"...

Given that Zoom works for both developers on different operating systems and one is similar to yours, we don't think this is our problem to solve.

**Comment by alex-w** [comment]
Just for protocol: I've checked recording the video of Stellarium's show within Zoom on 2 platforms: Windows 10 and macOS 11.  Both cases work as expected.

**Comment by Ethdhelwen** [comment]
Thanks Alex! Sadly, I've just checked again using Zoom, and it isn't working as expected. I am using graphics card driver 461.40, if that helps.

________________________________

**Comment by Ethdhelwen** [comment]
Hi Georg! Yes, Ctrl + S also doesn't work as expected, I'm afraid. No screenshots appear. Game bar, no luck. Zoom as described before still. Recording with teams does the same. I have an old screen capture programme called WM Capture 8, no luck. All of them do seem to record when I try a film on Amazon and recording footage from several games. As I've said, I don't know if there is a technical difference between the way these different kinds of screen footage are generated and recorded that might explain this quirk.

Having read to the end of your response, I'm not entirely sure that I understand your intended tone in your final two sentences, Georg. I don't believe that I have blamed you personally for having technical difficulties with recording Stellarium. I simply reported an issue in the forum which you have provided, wondered if there was a solution, and thanked the team, even though we are all stumped. It is great that other people are not having this issue with similar (but not identical) hardware, but I'm not sure that this warrants the conclusion that the problem doesn't exist for me. Nor does it seem a likely conclusion that, out of all the identical build generic shop-bought PCs in the world, mine alone is uniquely dysfunctional. Nor do I think that it warrants some passive-aggressive mockery of my gaming choices! 🙂 If the cause is unknown to you, a simple, "I'm sorry, we're at a loss on this one!" would suffice. No personal responsibility or blame lays upon you. Once again, thanks for trying to look into this issue for me. Have a great day, Georg!

________________________________

**Comment by gzotti** [comment]
You started mocking about Alexander's comment. You should be strong enough to accept being cited back.

Driver versions may be relevant indeed. It works (for me) with 457.30, maybe they ruined something now.

**Comment by Ethdhelwen** [comment]
Hi Georg! I'm afraid you must have misinterpreted something in translation. No mockery of Alex was either given or intended. I am concerned - for you - by the tone in which your responses are going, as they become increasingly abusive. As to whether I can 'take it' (an odd manner in which to conduct yourself as a project manager/creator on your own forums - well done, by the way, on what is a fantastic learning tool!), I would assume that the smiley emoji in my previous comment would indicate to you that I found your unwarranted abusive insults to be amusing, in that they were quite unexpected but reveal more about your character than they do the person to whom they are directed. I'm a teacher: very little surprises me! 🙂

Thank you for looking into the driver, Georg. Perhaps, as a suggestion for future forum users and your public image, all it might take in future is for you to respond with such useful questions, sticking entirely to technical issues?

Thanks again to you all.

________________________________

**Comment by gzotti** [comment]
If expressing that this is not our bug to solve feels insulting to you, I will better shut up now. :-X

**Comment by Ethdhelwen** [comment]
Hi Georg!

On the contrary, it would be perfectly acceptable to express that this bug is not an issue particular to Stellarium, but that is it more likely an issue to do with hardware or recording software used... as previously stated in my last comment, when I questioned the quality of my own graphics card: another statement to which you bizarrely took personal offence, as if it reflected badly upon Stellarium. Quite to the contrary.  I'm neither annoyed that I have experienced this issue, nor have I in any way implied that it is the 'fault' of your programme. I simply asked you if you knew what might be happening, without any way of knowing that the creators themselves would respond and take it as a personal insult to their work, which I have repeatedly praised. I have asked an identical question elsewhere, and those who responded managed to do so and offer several opinions without any emotional connotation.

What would feel insulting is insulting people for other aspects of their lives on a technical forum, then using your position as project owners and moderators to continue to mock and abuse other users. If you had simply stuck to the former rather than the latter from the outset, you would not now find yourself resorting to attempts at barbed witticisms as put-downs, with no useful purpose but to insult others. You now seem to have interpreted the quite reasonable expectation that users might have not to be mocked when asking for technical advice as some form of cancelling culture, claiming that I am somehow preventing you from communicating. Precisely how you imagine that I would be able to do that is another question for you to ponder.

________________________________

**Comment by alex-w** [comment]
@Ethdhelwen please attach log.txt from Stellarium.

**Comment by axd1967** [comment]
@Ethdhelwen the first thing that I would suggest is to disable "full screen" mode (F11) and see if this still happens in "windowed" mode.

also, can you specify the version of Zoom?

@Ethdhelwen @alex-w @gzotti 
_please_ understand that conflicts regularly pop up because of what mostly look like "lost in translation" issues. I've also had my share of fallout from this attitude, the only thing I can suggest is to _please_ assume that most, if not all, of the users here have good intentions, and even if there is a perception of negative attitudes, you have to stay cool; understand that users are sometimes irritated, sometimes trip into issues that they cause themselves, sometimes are not able to fully express issues, etc... remember that you are managing a project that you can be proud about; remember that being a helpdesk means you _will_ be exposed to difficult "human" issues. an objective reader should notice that  @Ethdhelwen 's initial posts try to be courteous, so there is no reason to spiral into verbal violence.

@alex-w could not reproduce the behaviour, which makes it difficult to analyse what's going on, so we can only hope that some other user also has this issue. it is understandable that this doesn't help @Ethdhelwen - even more, it is frustrating (for both sides, think of it!) to see that an issue cannot be reproduced; sometimes, it IS an end user error (I call it "finger trouble"); often, other circumstances that are beyond the control of the developer have an impact, etc.

**Comment by alex-w** [comment]
Any feedback please
