### ISSUE TITLE
20.4 does not allow windows tab to be utilized

### ISSUE THREAD

**Issue by euplanetarium** [Stellarium/stellarium#1485]
20.4 does not allow windows tab to be utilized to access other applications on computer.  it always worked with previous versions

**Comment by gzotti** [comment]
Works for me. Please indicate your graphics system, including driver version.

**Comment by euplanetarium** [comment]
version    10.0.18362.1110
IDE ATA/ATAPI controllers

**Comment by gzotti** [comment]
IDE ATA/ATAPI concerns your CD/DVD/HDD drives, not the graphics system. The version number may be Intel, but we are talking about graphics: NVidia Geforce, AMD Radeon, or Intel Core-i processor graphics? I am very sure we cannot do anything, anyhow, as such operating system particulars are beyond our influence. Maybe seek advice with Microsoft that "some program" suddenly does not work anymore with windows-tab on your system.   On mine it works as expected in full-screen and windowed mode, OpenGL and ANGLE modes.

**Comment by euplanetarium** [comment]
Thank you.

**Comment by alex-w** [comment]
Please share log.txt and try Windowed mode (F11)

**Comment by gzotti** [comment]
@euplanetarium we will close this on March 20 if you don't further describe your issue.

**Comment by euplanetarium** [comment]
I still can't use my "windows" button to open other apps while Stellarium is 20.4 is on!  Are others having same problem?
I did NOT have it with previous version on this computer!


David Hurd | Professor and Planetarium Director
Geosciences Department
________________________________

      EDINBORO UNIVERSITY

________________________________
169 Cooper Hall | Edinboro, PA 16444
814.732.2493 | ***@***.******@***.***>
http://www.edinboro.edu/planetarium

________________________________

**Comment by gzotti** [comment]
I can Alt-Tab, Windows-Tab, press Windows key to call the start menu, etc. 
Without logfile or your information, we don't know whether you are running OpenGL or ANGLE mode. Have you tried running ANGLE mode? This helps with some computers.

**Comment by euplanetarium** [comment]
Finally got it by hitting f11.  Thanks for your help


David Hurd | Professor and Planetarium Director
Geosciences Department
________________________________

      EDINBORO UNIVERSITY

________________________________
169 Cooper Hall | Edinboro, PA 16444
814.732.2493 | ***@***.******@***.***>
http://www.edinboro.edu/planetarium

________________________________
