### ISSUE TITLE
Zodiacal light practically invisible with the slightest light pollution

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1489]
I'm not quite sure if this is really a bug (I've seen the comments in the code, and it seems intentional).

The zodiacal light is almost completely invisible if the light pollution is set to 2 or above. However, in reality, a Bortle 2 site would show a great deal of zodiacal light. I've seen it from a Bortle 4 area, quite impressive.

However, if one sets the extinction coefficient to 0.0, then the zodiacal light is displayed more realistically. Visible until about Bortle 4. Compare these two screenshots with light pollution set at 2:

With extinction = 0.2:
![ext02](https://user-images.githubusercontent.com/37028368/106623176-a0018d00-6574-11eb-9b65-cdb035098ec8.png)

With extinction = 0.0:
![ext00](https://user-images.githubusercontent.com/37028368/106623187-a3951400-6574-11eb-81b6-7013a0908897.png)

I find it unrealistic.

**Comment by gzotti** [comment]
Not a bug, just a need for further tweaking.

Indeed LP (Bortle index) is the primary ZL killer. The primary question is how accurate the Bortle scale and also its implementation in Stellarium really are. I know an expert on light pollution who is not really happy with it and how Stellarium uses it. However, there is a mix of: eye adaptation; screen brightness; screen environment brightness; observer expectation and experience, and certainly more factors. 

I hardly get to observe it, but implemented it after a visit in a pristine-sky location in Namibia's highlands (no LP, low extinction). I never saw it so bright again. I would have to return there (want to, at some time...) to improve the visual balancing. You can tweak the values in code and suggest a better match. The extinction should be kept at reasonable levels (definitely >0.10) in the process.
If all fails, you can set ZL brighter, just as you can set the Milky Way brighter. 

I want to give the sky brightness module a thorough review later this year.

**Comment by Atque** [comment]
@gzotti I could play around with the values a bit to see if I can find something more useful. If I do, I might create a PR.

**Comment by axd1967** [comment]
See also https://github.com/Stellarium/stellarium/discussions/1504
