### ISSUE TITLE
Got a crash when removing a telescope

### ISSUE THREAD

**Issue by wadouk** [Stellarium/stellarium#1490]
### Expected Behaviour
Deleting a telescope entry in ocular window

### Actual Behaviour
Crash when pressing the delete button

### Steps to reproduce
Launch stellarium
Editing occulars
click on tab telescope
Select the first one
Click delete
Stellarium crash

### System
* Stellarium version: 0.20.4-2 from pacman & downgrade by compiling from sources 0.20.4, 0.20.3, 0.20.2 (no occular button)
* Operating system: Linux laptop 5.9.12-arch1-1-oled (Linux manjaro with a specific kernel for oled)
* Graphics Card: `mhwd -l -d` 
Display controller nVidia Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q]
Display controller Intel Corporation UHD Graphics 630 (Mobile)
Some driver for both : video-linux 
Version : 2018.05.04 
Info : Standard open source drivers
(Dell XPS 7590)

* Screen type (if applicable): Dual screen : Laptop 15" 1920x1080 (Secondary) & Dell 24" 1920x1200 (Primary)

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/5918371/log.txt)

### Other comments
When launching from command line : got a message `Segmentation fault (core dumped)`
Same with one screen
Core dump file : https://heloworldDOTme/upload/core.stellarium.1000.ff42b0f1238e48c2966d9fde5f9c7cad.9889.1612342349000000.zst (replace DOT with a dot)

**Comment by gzotti** [comment]
There was a problem with deleting the last entries in the lists, but I thought this was solved in 0.20.3 or .4. Did you observe this with 0.20.4 or with your builds of earlier sources?

**Comment by wadouk** [comment]
The last, the first, the middle entry whatever.
It's the same with pre-built 0.20.4 or built from sources (0.20.4 too) or 0.20.3
Can't test before (.2) because there is no bar with occular button.

Could be about the files that store the data, a format problem ? If I clean $HOME/.stellarium it will be recreated ?
Will try to downgrade to 0.20.0.

**Comment by gzotti** [comment]
Do NOT downgrade! The problem was SOLVED, not added, before 0.20.4. 
BTW, there has always been an oculars toolbar since 2010 or so. You can configure it away, though. 

Not sure if the config file changed. If you have no valuable data collection of all your equipment, just delete ~/.stellarium/modules/Oculars

Did you remove the "currently used" instrument, or just any in the list?

I cannot do more this week, but it helps to identify the problem.

**Comment by alex-w** [comment]
Please attach your ocular.ini file

**Comment by wadouk** [comment]
removed ~/.stellarium, rolled back to 0.20.0 and it's OK, succeed to edit the occular list, not tried until the last one to see the other bug.
the button bar with occular access doesn't display but remove the ~/.stellarium (from 0.20.4) fixed that.

**Comment by wadouk** [comment]
renamed .ini to .txt for github
[ocular.txt](https://github.com/Stellarium/stellarium/files/5919403/ocular.txt)

**Comment by alex-w** [comment]
> renamed .ini to .txt for github
> [ocular.txt](https://github.com/Stellarium/stellarium/files/5919403/ocular.txt)

But this is standard file. I cannot reproduce the issue.

**Comment by wadouk** [comment]
Oups, that's true, I could had mentioned this before, a fresh install already do it.
I just tried with a "normal" kernel and it's the same (Linux laptop 5.9.16-1-MANJARO).

**Comment by alex-w** [comment]
The issue is gone probably... Is it correct?

**Comment by wadouk** [comment]
Nop, The same with master 628488710

**Comment by alex-w** [comment]
Please share your latest oculars.ini file

**Comment by wadouk** [comment]
The same as before, don´t touched, don´t edited
[ocular.txt](https://github.com/Stellarium/stellarium/files/6316511/ocular.txt)

**Comment by alex-w** [comment]
Please describe steps for reproduce the issue (detailed step-by-step instructions).

**Comment by wadouk** [comment]
A video will be better that long explanation

https://user-images.githubusercontent.com/787448/114846148-afa31a80-9ddc-11eb-9326-9302fcd1ec1a.mp4

- Open stellarium
- Go in ocular
- select one
- click delete
- core dump

**Comment by alex-w** [comment]
I see no askConfirmation() window. Could you disable lines in OcularsDialog.cpp file where have askConfirmation() and check it again? Or, better, try change &StelMainView::getInstance() to Q_NULLPTR in StelDialog:: askConfirmation() method.

P.S. Poke to @axd1967

**Comment by wadouk** [comment]
Seems I have only fetched and not pull (see splash screen), investigating and give you new info

**Comment by wadouk** [comment]
The same, same method in StelDialog
![image](https://user-images.githubusercontent.com/787448/114883568-569bac80-9e05-11eb-88ff-436ab235878d.png)

**Comment by alex-w** [comment]
Could you try windowed mode?

**Comment by wadouk** [comment]
with this diff it´s OK

```
@@ -152,16 +152,16 @@ void OcularDialog::deleteSelectedTelescope()
        if (telescopeTableModel->rowCount() == 1)
        {
                qDebug() << "Cannot delete the last entry.";
-               QMessageBox::warning(&StelMainView::getInstance(), q_("Warning!"), q_("Cannot delete the last telescope."), QMessageBox::Ok);
+        QMessageBox::warning(Q_NULLPTR, q_("Warning!"), q_("Cannot delete the last telescope."), QMessageBox::Ok);
                return;
        }
 
-       if (askConfirmation())
-       {
+//     if (askConfirmation())
+//     {
                telescopeTableModel->removeRows(ui->telescopeListView->currentIndex().row(), 1);
                ui->telescopeListView->setCurrentIndex(telescopeTableModel->index(0, 1));
                plugin->updateLists();
-       }
+//     }


```

**Comment by wadouk** [comment]
I rollback the line with `&StelMainView::getInstance()` and still working.
The problem seems in `askConfirmation()`

Don´t understand the "windowed mode"

**Comment by wadouk** [comment]
Failing too with

```cpp

bool StelDialog::askConfirmation()
{
    return (QMessageBox::warning(Q_NULLPTR, q_("Attention!"), q_("Are you sure? This will delete your customized data."), QMessageBox::Yes | QMessageBox::No, QMessageBox::No) == QMessageBox::Yes);
}


```

**Comment by alex-w** [comment]
Press F11 - switch to windowed mode

**Comment by alex-w** [comment]
WTF?!? Please try moved askConfirmation() into section "protected slots" in StelDialog.hpp file

**Comment by wadouk** [comment]
trying 

```diff
@@ -193,8 +193,6 @@ protected:
        //! to the required datatype, the application will crash
        void connectColorButton(QToolButton* button, QString propertyName, QString iniName, QString moduleName="");
 
-       bool askConfirmation();
-
        //! The main dialog
        QWidget* dialog;
        class CustomProxy* proxy;
@@ -214,6 +212,8 @@ protected slots:
        //! connect from StelApp to handle font and font size changes.
        void handleFontChanged();
 
+    bool askConfirmation();
+
 private slots:
        void updateNightModeProperty();
 };

```

**Comment by wadouk** [comment]
Failing the same

**Comment by alex-w** [comment]
I see in the log:
> GL renderer is "Mesa Intel(R) UHD Graphics 630 (CFL GT2)"

Could you try run Stellarium on Nvidia GPU?

**Comment by wadouk** [comment]
Any doc on how to do that ?

**Comment by alex-w** [comment]
Probably `DRI_PRIME=1 stellarium` in console

**Comment by wadouk** [comment]
the same, but logs still talking on intel not nvidia. looking for my distro.

**Comment by alex-w** [comment]
Maybe it can help: https://forums.linuxmint.com/viewtopic.php?t=326816

**Comment by wadouk** [comment]
seems succeed to change the GPU
but running the one in the disto failing the same

trying to make the same with master

`__GLX_VENDOR_LIBRARY_NAME=nvidia __NV_PRIME_RENDER_OFFLOAD=1 stellarium`

```log
OpenGL supported version:  "4.6.0 NVIDIA 460.67"
Current Format:  QSurfaceFormat(version 4.6, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 0, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CompatibilityProfile)
StelMainView::init
Detected: OpenGL "4.6"
Driver version string: "4.6.0 NVIDIA 460.67"
GL vendor is "NVIDIA Corporation"
GL renderer is "GeForce GTX 1650/PCIe/SSE2"
```

**Comment by wadouk** [comment]
The same on master

```
This is Stellarium 0.21.0-6284887 
...
Driver version string: "4.6.0 NVIDIA 460.67"
GL vendor is "NVIDIA Corporation"
GL renderer is "GeForce GTX 1650/PCIe/SSE2"
GL Shading Language version is "4.60 NVIDIA"
GLSL Version Number detected:  4.6
```

**Comment by wadouk** [comment]
maybe be "helloworld" program that I could execute to check if QT doesn´t fail itself on my distro ?

**Comment by alex-w** [comment]
> maybe be "helloworld" program that I could execute to check if QT doesn´t fail itself on my distro ?

You can try build demo for "warning window" from Qt examples (https://doc.qt.io/qt-5/qmessagebox.html)

**Comment by wadouk** [comment]
If I make something full on my own, i will not have the same test case as the one is failing. 
So much actions could defer from the ones are done in stellarium.

**Comment by Leia286** [comment]
It was a one off for me. See alex-w One Off Oculars Plugin Crash #1822 . I was not running ANGLE mode. I was running normal mode.

**Comment by MaraJadeLives** [comment]
I had the same issue on Windows, see #1822. I don't remember which scope I was deleting.

**Comment by wadouk** [comment]
Hi,

I taken little time to make a little hello with the line that fail and without surprise it works in qt creator

Will think it's something different between build time and execution time, otherwise it will not build.

Will go deep in cmake in my case ?
What is the build tool used in stellarium ?

![image](https://user-images.githubusercontent.com/787448/163969813-7446c3bb-841c-41e2-b119-b3e6c7d17aad.png)


```cpp
#include <QApplication>
#include <QtWidgets>

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    bool t = QMessageBox::warning(Q_NULLPTR, "Attention!", "Are you sure? This will delete your customized data.", QMessageBox::Yes | QMessageBox::No, QMessageBox::No) == QMessageBox::Yes;
    printf("hello %d", t);
    return app.exec();
}

```

**Comment by wadouk** [comment]
Test this morning on 1.0-2 build on manjaro and it's working fine !
