### ISSUE TITLE
Positional error of  Sirius 'B' ?  (Alpha CMa B) - designated  * alf CMa B   (A Custom Object) in Stellarium

### ISSUE THREAD

**Issue by PaulJRead** [Stellarium/stellarium#1491]
This is an issue that may be already covered under Proper Motions elsewhere...  but my main concern is that this relatively well known star (Sirius B) does not appear to be included in Stellarium's star catalogs and is instead, designated a "Custom Object" !!

The orbit of Sirius B around the Main Star is well documented elsewhere. However, in Stellarium the movement and hence the current position relative to the main star, is incorrect (VERY incorrect),  rendering Stellarium an unreliable reference source for locating this hard-to-see dim star.  Several local astronomers have expressed general distrust in Stellarium specifically because of this issue.

**Comment by gzotti** [comment]
It is well known that Stellarium does not model the revolution of binary stars around a common centre of gravity. Whether well-known or not does not matter. Appendix F in the User Guide deals with known shortcomings. 

Is Sirius B contained in the Hipparcos catalog? Or was the satellite's telescope blinded by Sirius A?

This is an open-source project. Everybody is cordially invited to improve the star catalog.

**Comment by PaulJRead** [comment]
I was not aware that the HIP catalog was Stellarium's sole source of star data, but if that is so, then perhaps using Stellarium Web would offer a better solution since Sirius B is present and correctly designated there with several catalog references: HD 48915B 
 BD-16 1591B    GJ 244B     Gaia DR2 2947050466531873024     AGC 1BC.  Unfortunately however, the motion issue remains in Stellarium Web as well.

The request for an answer came to me from several members of the Leicester Astronomical Society who, having the use of their own modern, powerful imaging equipment, had tried to use Stellarium to identify feint stars in close proximity to Sirius A while also searching for Sirius B knowing it's approximate current relative position and distance from Sirius A.    Personally, I am a huge fan of Stellarium and grateful for the work that the small team has done over recent years in continuing to develop the software to the latest versions.  Sometimes it is hard to accept that it cannot (always) be the perfect tool for everyone  :)

**Comment by gzotti** [comment]
For such highly specific identification tasks probably ALADIN is better. "Stellarium is a free open source planetarium for your computer. It shows a realistic sky in 3D, just like what you see with the naked eye, binoculars or a telescope." Make that "small telescope". 

As I have learned myself several years ago the fastest way to have a solution for some issue one really wants to see is to do it yourself (or find somebody who knows what to do). If I had equipment to see Sirius B and still more time to develop, I might be inclined to do it. But I don't have the requirements.  

Further reading: https://github.com/Stellarium/stellarium/wiki/FAQ#why-dont-you-implement

**Comment by PaulJRead** [comment]
Thank you for your time Georg, both in responding to this thread and more so in giving your time to the Stellarium project.  If I were competent I would happily give of my own time to help with development, but since I am not, I can best serve Stellarium by continuing to "sing it's praises" and "spread the word".  I can add to that, that I will also endeavour to press home the 'self-help' philosophy when issues are raised locally!  Thank you once again to you and the other team members for all the work that goes into Stellarium - it is very much appreciated.
