### ISSUE TITLE
Stellarium does not start

### ISSUE THREAD

**Issue by MearsMan** [Stellarium/stellarium#1496]
For the last two years I used Stellarium on my laptop (Win10, 16GByte RAM, GeForce MX230) without any problems, but since today Stellarium does not start...I see the startup logo with the version number (0.20.4) but then the App dissapears.
Yes, the latest drivers are installed and all other programms work as usual.

**Comment by MearsMan** [comment]
I use a Dell Inspiron 5593 with an intel i7 with 16GByte RAM. Windows 10 Pro (20H2). GeForce MX230 with 4GByte

The logfile:
2021-02-13T09:40:47
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 15.9 (Visual Studio 2017)
Qt runtime version: 5.12.6
Qt compilation version: 5.12.6
Addressing mode: 64-bit
Total physical memory: 16151 MB
Available physical memory: 11995 MB
Physical memory in use: 25%
Processor speed: 1498 MHz
Processor name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Processor speed: 1498 MHz
Processor name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Processor speed: 1498 MHz
Processor name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Processor speed: 1498 MHz
Processor name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Processor speed: 1498 MHz
Processor name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Processor speed: 1498 MHz
Processor name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Processor speed: 1498 MHz
Processor name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Processor speed: 1498 MHz
Processor name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
C:\Program Files\Stellarium\stellarium.exe 
 -----------------------------------------------------
[ This is Stellarium 0.20.4 - https://stellarium.org/ ]
[ Copyright (C) 2000-2020 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "C:\\Users\\olafm\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\olafm\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\olafm\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)

**Comment by alex-w** [comment]
Please try run Stellarium in ANGLE mode.

**Comment by MearsMan** [comment]
Now, it is running. Thank you very much, but first I used the previous version...same desktop link as the past two years. Then it did not work anymore. I installed 0.20.4 and tried all the different startup-modes.
Anyway thank you ,-)
