### ISSUE TITLE
bug or feature? bookmark circle detaches from label

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1498]
When highlighting bookmarks and then advancing time, the bookmark circle stays behind while the label moves with the object.

![image](https://user-images.githubusercontent.com/3529789/107858640-58f97e80-6e35-11eb-8e2c-ab877df56835.png)
![image](https://user-images.githubusercontent.com/3529789/107858651-6adb2180-6e35-11eb-99ad-8a656f8cb313.png)

I think this is a bug, but should not be treated like a bug, but like an interesting feature; this should be clearly documented in code to avoid removing this "feature" by mistake?

**Comment by alex-w** [comment]
This is not a bug!

**Comment by axd1967** [comment]
I think this is open to discussion, but for me, it can remain as is.
