### ISSUE TITLE
Playing videos in 0.18.0 Script

### ISSUE THREAD

**Issue by MRSPlanetarium** [Stellarium/stellarium#150]
### Doesn't show the video; however, the soundtrack plays.

Log file has the line 'StelVideoMgr::playVideo( "true" ): no such video' however the video is in the path AND the soundtrack is played.

Occasionally get the error DirectShowPlayerService::doRender: Unresolved error code 0x80040266 () showing in the log file; however, not everytime

### Steps to reproduce
Originally occurs in a script touring the solar system so I've cut down to just the video playing portion as in the attached test scripts.

[VideoTest.txt](https://github.com/Stellarium/stellarium/files/1983535/VideoTest.txt)
[VideoTest2.txt](https://github.com/Stellarium/stellarium/files/1983536/VideoTest2.txt)

Tried videos from different sources and changing the video format from MP4 to WMV still only get the sound track. 

It's almost like the video is playing in the background

### System
* Stellarium version: 0.18.0
* Operating system: Windows 7 Enterprise
* Graphics Card: Intel

### Logfile 

[log.txt](https://github.com/Stellarium/stellarium/files/1983510/log.txt)

**Comment by gzotti** [comment]
Yes I know, https://bugs.launchpad.net/stellarium/+bug/1735186

The video player is a rather fragile piece. It may make a difference playing on OpenGL or ANGLE modes, and of course this depends on graphics hardware and drivers.

**Comment by MRSPlanetarium** [comment]
Sorry missed that one. Strangly it did work with version 16.
I'll find a work around
