### ISSUE TITLE
3D Sceneries: Full shadows during lunar eclipses

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1506]
A small problem with the shadowing of 3D sceneries: During a total lunar eclipse, the shadowing and illumination of the 3D landscape is the same as if the Moon were not eclipsed. See screenshot below:

![stellarium-069](https://user-images.githubusercontent.com/37028368/108043005-d80ed280-7040-11eb-9ee1-0a0cadc62d38.png)

**Comment by gzotti** [comment]
Oops. I guess that used to be the case also before the latest changes. 
Sure, needs a fix.

**Comment by Atque** [comment]
> I guess that used to be the case also before the latest changes.

Yes, this is an old issue that I have seen for a few years. I think it is from the time when old-style landscapes and the sky were illuminated by lunar eclipses (before 2015?).
