### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by t4saha** [Stellarium/stellarium#1511]
### Expected Behaviour
Strings are translated

### Actual Behaviour
Strings are in English

In Roman Calendar, followings are not available for translation

`    QStringList events={"Kalendae", "Nones", "Ides"};`
`    QStringList eventsShort={"Kal.", "Non.", "Id."};`
`    .....`
`   list << "pridie";`

### Steps to reproduce
Activate Calendar Plugin

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Ubuntu 20.4>
* Graphics Card: <(Integrated Intel)>

### Logfile 
N.A.

**Comment by gzotti** [comment]
These are not meant for translation. Romans talked Latin. Do you think trans*literation* (into other character sets)  is necessary?

**Comment by t4saha** [comment]
Yes I mean transliteration mostly. I understand that the names of day and months etc are proper names but these are available in translation portal for other calenders. It's nice to have transliteration too. Ex. Th sounds like থ or ঠ or দ in Bengali.
