### ISSUE TITLE
HiPS: Mellinger survey off at galactic poles

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1515]
Perhaps this is outside of Stellarium's dev team's reach, but I think it is worth mentioning.

The Mellinger survey, the prettiest of them all IMO, is off at the galactic poles. Look at the screenshot below:
![stellarium-070](https://user-images.githubusercontent.com/37028368/108558496-4500c180-72fa-11eb-94e2-55fb00cd11f4.png)

Not how the stars Al Dafirah and 14/16 Comae Berenicis are off about half a degree from the HiPS images.

It is possible this is present for more surveys, but I have only seen it in the Mellinger survey so far.

**Comment by gzotti** [comment]
Yes, this is out of our reach. I was given another all-sky, but sadly have not yet managed to get that straight :-(

**Comment by Atque** [comment]
> Yes, this is out of our reach. 

I thought so. Then it's no use keeping this open.

> I was given another all-sky, but sadly have not yet managed to get that straight :-(

Nick Risinger's panorama, I presume?

**Comment by gzotti** [comment]
No, one made in Austria.

**Comment by Atque** [comment]
I see. I hope you can get it to work, because I love these optical surveys (Mellinger, DSS color etc). :)
