### ISSUE TITLE
Calculate Neptune conjunctions

### ISSUE THREAD

**Issue by nicopop75** [Stellarium/stellarium#1520]
Hello, when I want to search for celestial phenomena involving Neptune the software slow down totally,  does not calculate any phenomenon (stars conjunctions, conjunctions with galaxies, other planets and moons),  and crashes, even if I run the search for a very short period, for example one or two days. I only encountered this problem only with Neptune planet.

Stellarium version 0.20.4     Operatyng System Windows 8.1   3.6 GHz RAM 4 GB

Thank you

**Comment by alex-w** [comment]
I cannot reproduce the issue.

**Comment by alex-w** [comment]
Please share log.txt after crash.

**Comment by nicopop75** [comment]
Here attached the required file.
Thanks.

[last run log.txt](https://github.com/Stellarium/stellarium/files/6018144/last.run.log.txt)

**Comment by alex-w** [comment]
Could you share your config.ini file also?

**Comment by nicopop75** [comment]
[config.txt](https://github.com/Stellarium/stellarium/files/6106065/config.txt)

**Comment by nicopop75** [comment]
Good morning, here attached the config.ini file.
Thank you

**Comment by alex-w** [comment]
I cannot reproduce the issue still - could you share crash dump and your steps to reproduce?

**Comment by nicopop75** [comment]
Fig.1 I search for  Neptune phenomena ony for one day.  Fig. 2 The software after five minutes crashes. Fig,3 After a long wait I am forced to interrupt the software abruptly.    Fig 4 I repeat the research for one month. Fig.5 This time, after five minutes the research is successful.
I have also noticed that researching for conjunctions Jupiter- Europa only for one day (2021.03.17)  the software misses one conjuction (fig.6), Instead if I search for Jupiter -Europa conjunctions for one month, on 2021.03.17 the software calculates the conjunction (fig.7) 
!
[log.txt](https://github.com/Stellarium/stellarium/files/6159071/log.txt)
[IMAGINE 1 I ONLY SEARCH FOR ONE DAY](https://user-images.githubusercontent.com/79394885/111522032-20153800-875a-11eb-8ddb-c8e1f1117818.png)
![IMAGINE 2 RESEARCH AFTER FIVE MINUTE THE SOFTWARE CRASHES](https://user-images.githubusercontent.com/79394885/111522069-2b686380-875a-11eb-9d40-6b5b563768f4.png)
![IMAGINE 3 I AM FORCED TO INTERRUPT THE SOFTWARE ABRUPTLY](https://user-images.githubusercontent.com/79394885/111522088-302d1780-875a-11eb-8e97-b806d17b4113.png)
![IMAGINE 4 THE SAME RESEARCH BUT FOR ONE MONTH](https://user-images.githubusercontent.com/79394885/111522099-33c09e80-875a-11eb-8059-4bbbdf390d78.png)
![IMAGINE 5 THIS TIME AFTER FIVE MINUTES THE SEARCH IS SUCCESSFUL](https://user-images.githubusercontent.com/79394885/111522108-36bb8f00-875a-11eb-8b63-2f3a51f15252.png)
![IMAGINE 6 RESEARCH PHENOMENA JUPITER ONLY FOR ONE DAY - MISSES THE JUPITER-EUROPA CONJUNCTION](https://user-images.githubusercontent.com/79394885/111522118-391de900-875a-11eb-99d3-bd3565291149.png)
![IMAGINE 7 IF I SEARCH FOR ONE WEEK THERE'S A SECOND CONJUNCTIONS ON 03 17 BETEWEEN JUPITER AND EUROPA](https://user-images.githubusercontent.com/79394885/111522128-3b804300-875a-11eb-8891-06b62c0c0ebb.png)

**Comment by alex-w** [comment]
OK, the issue in calculation of aphelion and perihelion
