### ISSUE TITLE
master: satellite dialog is unnecessarly wide and cannot be resized horizontally

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1525]
### Expected Behaviour

![image](https://user-images.githubusercontent.com/3529789/108912524-0a17ca00-7629-11eb-877d-fd9815e195c3.png)

### Actual Behaviour

![image](https://user-images.githubusercontent.com/3529789/108912556-13a13200-7629-11eb-81c9-e5159a4317b7.png)

The "groups" pane content seems to no longer wrap around.

### System
* Stellarium version: Stellarium 0.20.4-817beea [master]
* Operating system: KUbuntu 20.04

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

[log.txt](https://github.com/Stellarium/stellarium/files/6031987/log.txt)

**Comment by axd1967** [comment]
update: after some manipulations (possibly hiding/showing sats), this seems to have disappeared, so this might be difficult to reproduce.

it is possible that simply closing and restarting removes this issue.

**Comment by alex-w** [comment]
I cannot reproduce the issue
