### ISSUE TITLE
Abell catalog

### ISSUE THREAD

**Issue by Ishtar66** [Stellarium/stellarium#1526]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by Ishtar66** [comment]
Your Abell catalo is inaccurate and or non existent. A simple query for Abell 12 which is located near mu Orionis doesn't show it and returns a reply as "galaxy cluster". Looking at the magnified image around mu Orionis doesn't show the planetary nebula

**Comment by gzotti** [comment]
See https://github.com/Stellarium/stellarium/issues/1486, https://github.com/Stellarium/stellarium/issues/1473

**Comment by Ishtar66** [comment]
Never mind I found it

Dan Kahraman
