### ISSUE TITLE
sat plugin: magnitude filter

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1527]
**Is your feature request related to a problem? Please describe.**
The increasing amount of sats warrants a filter to reduce to eg visual sats

![image](https://user-images.githubusercontent.com/3529789/109171523-27ac7700-7782-11eb-9969-f2cd6209d4f4.png)

**Describe the solution you'd like**
A magnitude low cut filter that hides sats below a given mag

**Describe alternatives you've considered**
The `visual` category - but it is not very clear what exactly is determined as "visual"

![image](https://user-images.githubusercontent.com/3529789/109171666-49a5f980-7782-11eb-83d5-df6e130c0856.png)

**Additional context**
It is probable that the sat magnitudes are not 100% correct, yet this feature should allow a user to make a rough selection (eg remove m10+ sats).

EDIT ADDED
 The idea is to be able to have Stellarium represent the sky as an observer would see it: the cutoff magnitude would be chosen by the observer, depending on equipment (eg mag 6 by default, for a visual observer; other magnitudes will depend on the instrument in use.)

**Comment by axd1967** [comment]
I understand and agree.

But if it is deemed OK for future development, it should not be closed (I'm not sure about the Done) as it won't be found by future developers.

When I look at the [won't fix](https://github.com/Stellarium/stellarium/issues?q=is%3Aclosed+label%3A%22won%27t+fix%22) list, I see mostly issues that are out of scope, strange, etc....

This should instead be moved to the [wishlist](https://github.com/Stellarium/stellarium/issues?q=is%3Aissue+is%3Aopen+label%3Awishlist), as this is a sound issue that is not too difficult to develop.

An example of an issue that does end up in the wishlist and is FAR more evolved and far-fetched than this issue is https://github.com/Stellarium/stellarium/issues/463 ...

**Comment by alex-w** [comment]
> I understand and agree.
> 
> But if it is deemed OK for future development, it should not be closed (I'm not sure about the Done) as it won't be found by future developers.
> 
> When I look at the [won't fix](https://github.com/Stellarium/stellarium/issues?q=is%3Aclosed+label%3A%22won%27t+fix%22) list, I see mostly issues that are out of scope, strange, etc....

But your proposal is strange. You are using mode "Show satellites as markers", who ignore magnitude and it purpose for demonstration all satellites, who have "displayed" option enabled. Of course you may hide all invisible artificial satellites by marking the same named option. In realistic mode you will see only satellites who will be visible depended by magnitude and zooming level. So, what is your final goal for filled request? I see no serious reasons for "breaking" the demo mode.

> This should instead be moved to the [wishlist](https://github.com/Stellarium/stellarium/issues?q=is%3Aissue+is%3Aopen+label%3Awishlist), as this is a sound issue that is not too difficult to develop.

If you do not see difficulties then this is not mean that difficulties are not exist. ;)

**Comment by axd1967** [comment]
#wishlist

**Comment by axd1967** [comment]
marked as duplicate of #2060, but that issue has **not** been closed. 

this issue is a clean, sound suggestion and should be moved to the wishlist rather than be closed. 

this is an example of closing an issue just because it was me that opened it; I cannot find another explanation why this issue would have been closed. there exist several good issues that I opened and were closed without a good explanation (but with lots of bickering). in this way, several good ideas are drowned.

@xalioth

**Comment by alex-w** [comment]
this issue was closed because you wanted to ruined demonstration mode without any appropriate reasons

**Comment by axd1967** [comment]
> this issue was closed because you wanted to ruined demonstration mode without any appropriate reasons

???

**Comment by axd1967** [comment]
I've amended the description to make more clear what the idea is.

Note that this could be further extended (as a separate issue) to the Ocular plugin, with an option that filters away sats that cannot be seen with the currently selected ocular combination.

**Comment by gzotti** [comment]
I have described elsewhere that some confusion around limits in the Oculars were in the process of being fixed, when another developer made a short reappearance to take that over. Unfortunately this attempt did not proceed, and the old problems remain.
