### ISSUE TITLE
cannot select Leo

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1528]
### Expected Behaviour
Select constellation Leo via Search > Object

### Actual Behaviour

Leo does not appear in the list.

![image](https://user-images.githubusercontent.com/3529789/109282908-727bcc80-781e-11eb-9496-4022f10f1387.png)

It does appear via Constellation search:

![image](https://user-images.githubusercontent.com/3529789/109283143-b40c7780-781e-11eb-80db-c387e1a85c8e.png)

### Workaround
Select via Search > Lists > Constellations

### System
* Stellarium version: Stellarium 0.20.4-817beea [master]

* Operating system: KUbuntu 20.04
### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by axd1967** [comment]
This might be a subtle bug in the Search dialog, because I now have it for the Dutch "Tweelingen" (Gemini); cannot yet specify a test procedure to reproduce this, it seems to depend on a sequence of actions.

**Comment by alex-w** [comment]
I can confirm the issue, but this is not exactly a bug, because Stellarium hasn't priority (or search context for main search tool) for different types of objects and the list of names with substring "leo" is long.

**Comment by gzotti** [comment]
Hmm, sure, leo is very short. But if the given search string matches *exactly* it should really be found if other objects of the same category (e.g. cancer) are also found.

**Comment by axd1967** [comment]
Rings a bell, I think this is a duplicate.
Maybe a solution could allow to include spaces in the search string? That way, `Leonard` etc are discarded and `Leo *` remains.

**Comment by alex-w** [comment]
> Hmm, sure, leo is very short. But if the given search string matches _exactly_ it should really be found if other objects of the same category (e.g. cancer) are also found.

This is interesting idea!
