### ISSUE TITLE
Mistake in naming of NGC 2194?

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1530]
According to https://britastro.org/journal_item/25644,
> ... those of you who use Stellarium 0.20 as a planetarium programme will note a rare mistake. NGC 2194 is not the Intergalactic Wanderer, which is NGC 2419 in Lynx.

https://en.wikipedia.org/wiki/NGC_2194 -> remove "Wanderer"?
https://github.com/Stellarium/stellarium/blob/5c900c69318c5fed625724086b60ae0e26153175/nebulae/default/names.dat#L264

https://en.wikipedia.org/wiki/NGC_2419 is OK
https://github.com/Stellarium/stellarium/blob/5c900c69318c5fed625724086b60ae0e26153175/nebulae/default/names.dat#L311

Maybe it should be "Herschel 74"?
https://www.go-astronomy.com/herschel.php?Her=74

**Comment by alex-w** [comment]
Please read the book “Observing and Cataloguing Nebulae and Star Clusters: From Herschel to Dreyer's New General Catalogue” by Wolfgang Steinicke, Cambridge University Press, 2010. ISBN 978-0521192675

**Comment by gzotti** [comment]
If Steinicke made an error, we don't have to reproduce it.
