### ISSUE TITLE
No daylight Saving V20.2 and 20.4

### ISSUE THREAD

**Issue by BrianWMi** [Stellarium/stellarium#1531]
Sky was expected to advance or revert by 1 hour when passing through dates for daylight saving in UK as per previous versions.

No change  seen in sky position of objects.

Step through day by day before and after March 28th

### System
* Stellarium version: <Name of downloaded installable file?>20.4    File is Stellarium - 0.20.4-win64
* Operating system: <Name, version number>  Win 10    version 20H2
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
What timezone are you using?

**Comment by BrianWMi** [comment]
Europe/London

**Comment by gzotti** [comment]
And did you enable Daylight Saving Time in the Location panel?
When you scroll the days in the date panel, you will see time jumping, not the sky.

**Comment by BrianWMi** [comment]
Ah ok. Yes I can see that the time jumps now instead of previous versions
where the sky jumped.

Thank you very much for that.
