### ISSUE TITLE
calibration / synchronization

### ISSUE THREAD

**Issue by sylvainnaudin** [Stellarium/stellarium#1532]
Bonjour :)
i am sorry for my bad english, im french.
Already a big thank you for your beautiful, practical and fluid software.

So my problem is a telescope synchronization problem.
I pilot without problem with EQMOD, but before this last update 0.20.4 I did ctrl + 3 to reposition the telescope cursor on the desired target after having recentered this one in the field of the camera and therefore calibrated the mount with stellarium . But today it doesn't work anymore. CTRL + 3 no longer works. I tried to do it with the sync button in the window which was used to pilot the telescope but nothing happened. I changed the keyboard shortcuts but it had no effect. I tried with synscan without success and I even tried with another PC, without success. today to my great regret I am sailing with a chart of the sky because it works for them.
Thank you for your time and I hope to find a solution with you.
cordially
Naudin Sylvain

### Expected Behaviour
no reaction, calibration is not done
### Actual Behaviour
ctrl+3 
### Steps to reproduce
refocus a targeted object in the field of the camera and calibrate the mount with stellarium.
### System
* Stellarium version: 0.20.4
* Operating system: windows + EQMOD
* Graphics Card: all computer

**Comment by alex-w** [comment]
Are you using StellariumScope?

**Comment by sylvainnaudin** [comment]
Bonjour 
oui j'utilise stellarium scope

**Comment by alex-w** [comment]
StellariumScope is 3rd-party software and I don’t know why it not work properly. Why you doesn‘t use ASCOM or direct connection to the mount? Which version of Stellarium was installed before?

**Comment by sylvainnaudin** [comment]
Du coup j'ai essayer avec ASCOM et ca fonctionne merci beaucoup ! j'y avait tout simplement pas penser et je maitrise encore mal le domaine et tout les logiciels. 
Je suis vraiment content de la vitesse a la quel vous m'avez répondue et je ne manquerai pas de faire une donation quand les finances iront mieux. 
Merci pour tout :)

**Comment by sylvainnaudin** [comment]
en faite il y a des bugs avec ASCOM, le suivis s'arrête régulièrement spontanément, la sync bug le curseur travers l'écran sans contrôle et tout a l'heur j'étais comme en simulation parceque tout étais en mouvement sur le pc et le télescope bouger pas d'un poil. du coup pour répondre a votre question j'avais surement la dernière mise a jour avant la 0.20.4 .

**Comment by gzotti** [comment]
(Google Translate:) So I tried with ASCOM and it works thank you very much! I just didn't think about it and I still don't have a good grasp of the domain and all the software. I'm really happy with the speed with which you answered me and I'll be sure to donate when the finances get better. Thank you for everything :)
