### ISSUE TITLE
History for searched objects 

### ISSUE THREAD

**Issue by Astro-Yogi** [Stellarium/stellarium#1533]
Problem : 
When you like to search for objects, you searcherd for before, you have to enter the object-name again every time.

Solution:
When you select the search-window, you could have two buttons ("Last" / "Next") to select again the last searched objects. 

Alternatives:
No idea.

Additional context:
It would make the handling more comfortable, when i enter  only "4468" in the search-field, stellarium would find  "NGC4468".

**Comment by gzotti** [comment]
last searched items has been added a while ago.
There are too many catalogs to say one needs no name to search for a number.
