### ISSUE TITLE
oculars - compass rose: vertical flip also flips horizontally

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1535]
### Actual Behaviour
 normal:
![image](https://user-images.githubusercontent.com/3529789/110140770-bbaabe00-7dd4-11eb-87a7-28cc105a2b62.png)

horizontal flip only (OK):
![image](https://user-images.githubusercontent.com/3529789/110140882-dc731380-7dd4-11eb-8d30-aff66fa011c7.png)

 vertical flip only: NOT OK: (actually this is a 180 rotation):
![image](https://user-images.githubusercontent.com/3529789/110140994-fa407880-7dd4-11eb-8e20-4e98bf033a59.png)

### Steps to reproduce

1. activate oculars
2. select an ocular/telescope combination, eg Plossl 40mm/C11 f/10
3. check that compass rose is active
3. check in the ocular/telescope properties that the combination does not flip the image
2. enable horizontal flip (CTRL+Shift+H) -> observe  that E/W are flipped
3. disable horizontal flip -> observe that N up, S down, E left, W right
3. enable horizontal flip (CTRL+Shift+V)

**Bug:** NS are flipped, but EW are also flipped.

### System
* Stellarium version: Stellarium 0.20.4-817beea [master]
* Operating system: KUbuntu 20.04
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

**Comment by treaves** [comment]
It's always a bad idea to confuse intent in a PR; there should be a PR to fix this issue that is separate from the PR to refactor/redesign the implementation of the plugin.

**Comment by treaves** [comment]
Thanks.  I'd like to start getting back involved.  Just randomly looked at this.  It is good to see code improvement from @gzotti  - I just threw out the comment.

**Comment by alex-w** [comment]
> Thanks. I'd like to start getting back involved. Just randomly looked at this. It is good to see code improvement from @gzotti - I just threw out the comment.

Well, I am and Georg has made many changes in Oculars plugin in the past few years :) Are you interested in adding improvements into your plugin or whole planetarium?

**Comment by gzotti** [comment]
Hi! I thought 2-3 weeks ago I could fix that other one (#1509). However, I finally became aware of the meanwhile problematic entanglement of mode switching with side effects (with possible minor bugs outside my usual application area) and wanted to make mode switching more transparent. Then this "yet another of these little ocular issues" issue came along, and I just thought "while we're at it...". Unfortunately, real life started to interfere at the same time (surveys), and I am unsure if this all comes in time for 0.21. I'd much more like to implement a few more calendars. If you want to make a different PR instead of #1521, or take over this one (I admit, it's definitely unfinished, but some progress is visible) I can stop my work on this immediately.

**Comment by treaves** [comment]
I’m actively working on the Oculars code.  Just wanted to give Georg a heads-up that I’d not forgotten.

**Comment by gzotti** [comment]
Have you seen #1521? I am stuck with real-world issues ATM. The mode switching is in progress, but unfinished and still in chaos. If you find it all nonsense, you are free to change it to a better and clearer solution. However, we need these 2-3 sets of temporary settings for various visibility issues (flip state, line drawing, visibility of constellation artwork, milky way saturation, star sizes, mag limits etc. etc., tons of user-requested fine-tuning of the last 8 years): Main app, Ocular mode, CCD mode may have different settings. Now probably also finder mode (similar to ocular view mode).

**Comment by treaves** [comment]
I'm beginning to look at this.  @alex-w  or @gzotti one of you need to get my project permissions added.

I know what the bug here is, and I'll fix this before going to the the entire display state cleanup.  But even the default here is wrongs E & W are flipped. This should not be the case.  @alex-w why was the original PNG created this way?  I'm just trying to understand before I get started.

**Comment by alex-w** [comment]
I tried sumulate the view through eyepiece - not real flipping the cardinals. But (!) I've prepared only one version of mirroring the cardinal names to improve readability and this is problem - the number of textures should be 4 - 1 for normal view and 3 for various mirrored views. :(

**Comment by axd1967** [comment]
thanks!
I'm busy reviewing the changes and will create issues where needed.

observations for now:

1. something smelly happening with the display of the ocular on-screen control panel (OCP):
![image](https://user-images.githubusercontent.com/3529789/119228519-9d22ac00-bb13-11eb-8abb-5dbfd2d29663.png)
also, the font changing has some issue, and it looks like the font size is not remembered
![image](https://user-images.githubusercontent.com/3529789/119228551-cfcca480-bb13-11eb-95cd-c1e147ec6328.png)
also, there is some state issue: toggling the OCP seems to move it in different font sizes, probably issues that are all related.

2. (still busy testing, I will add comments here and signal when the validation has completed)

**Comment by axd1967** [comment]
Meanwhile, it might be an idea to add a new swimlane in the projects: "to validate" (or similar).

![image](https://user-images.githubusercontent.com/3529789/119229383-1ae8b680-bb18-11eb-8276-a80f7bd28048.png)

From the Validation lane, an issue can either go to "Merged" and "Done" or otherwise "To rework" (or similar) - as this will require more work than just push back to "To Do" .

**Comment by axd1967** [comment]
(Unrelated to this issue: I've noticed across some releases that "Enable mouse navigation" had to be reset in order to make the mouse work.)

**Comment by treaves** [comment]
Alex, why did you reopen this issue?

**Comment by Atque** [comment]
@axd1967 I can't seem to reproduce your issues, except for the inability to toggle flip buttons when oculars are activated.

**Comment by alex-w** [comment]
@axd1967 please do clean building the Stellarium

**Comment by axd1967** [comment]
re-ran from an empty build directory, just to make sure. here is the build script I usually use:

```shell
PROJECT=/home/alex/projects/stellarium/src/stellarium

ENABLE=""

ENABLE=$ENABLE" -DENABLE_GPS=0"
ENABLE=$ENABLE" -DENABLE_LIBGPS=0"
ENABLE=$ENABLE" -DENABLE_MEDIA=0"
# see also src/stellarium/BUILDING.md
ENABLE=$ENABLE" -DUSE_PLUGIN_TELESCOPECONTROL=0"
#ENABLE=$ENABLE" -DUSE_PLUGIN_SUPERNOVAE=0"
ENABLE=$ENABLE" -DUSE_PLUGIN_QUASARS=0"
ENABLE=$ENABLE" -DUSE_PLUGIN_PULSARS=0"
ENABLE=$ENABLE" -DUSE_PLUGIN_EXOPLANETS=0"
#ENABLE=$ENABLE" -DUSE_PLUGIN_ARCHAEOLINES=0"
#ENABLE=$ENABLE" -DUSE_PLUGIN_NOVAE=0"
#ENABLE=$ENABLE" -DUSE_PLUGIN_REMOTECONTROL=0"
#ENABLE=$ENABLE" -DUSE_PLUGIN_REMOTESYNC=0"


OPTIONS=""
OPTIONS=$OPTIONS" -DCMAKE_INSTALL_PREFIX=$PWD/ "
OPTIONS=$OPTIONS" -Wfatal-errors"
#OPTIONS=$OPTIONS" "$ENABLE

cmake clean
cmake $OPTIONS $ENABLE -DCMAKE_BUILD_TYPE="RelWithDebInfo" $PROJECT
make clean #translations translations-stellarium translations-stellarium-skycultures
make -j6 install 2>&1 | tee build.log 
```

still the same issues.

I also tried running from a fresh (empty) `user-dir`.

**Comment by axd1967** [comment]
I will try a `git bisect`. stay tooned.

**Comment by axd1967** [comment]
cd262d8 contains the problem.

**Comment by Atque** [comment]
@axd1967 Can you do a step-by-step description to trigger the bugs/crashes?

**Comment by Atque** [comment]
Hmm, all right, I can reproduce the issue where fonts behave strangely. When scrolling through fonts, the panel at the upper right becomes weird. See the screenshot below:
![stellarium-095](https://user-images.githubusercontent.com/37028368/119251224-d60b6100-bba5-11eb-8654-a8bc8659a5bc.png)

Furthermore, the compass markings are inverted; in the sky, west is to the right, and east to the left, when viewing from the northern hemisphere.

**Comment by alex-w** [comment]
@axd1967 please fill separate bug report for GUI artifacts

**Comment by alex-w** [comment]
> Furthermore, the compass markings are inverted; in the sky, west is to the right, and east to the left, when viewing from the northern hemisphere.

It’s depends by flipping/mount setting for telescope

**Comment by Atque** [comment]
> It’s depends by flipping/mount setting for telescope

It still seems inverted. Compare these two screenshots of the Moon through oculars:
![stellarium-096](https://user-images.githubusercontent.com/37028368/119251672-0c49e000-bba8-11eb-8b36-d64178b5e7f7.png)
![stellarium-097](https://user-images.githubusercontent.com/37028368/119251674-0f44d080-bba8-11eb-9a88-d4c2c84c0f28.png)

While the compass rose is indeed inverted, it is still incorrect. The illuminated part of the Moon is to the west, not east.

**Comment by alex-w** [comment]
Confirmed!

**Comment by axd1967** [comment]
I guess we can continue the discussion in #1685 , thanks everybody. _(and thank `git bisect` :-) - I really love Git, in case someone didn't notice ;-) )_

**Comment by axd1967** [comment]
plugin setting issue dealt with in #1683

**Comment by treaves** [comment]
Okay, I see what is going on now.

@alex-w when you finally aded me to the project, you didn't give me same role as you by mistake.  Once that's corrected I'll get to this (and the property defect that resulted from the cleanup).
