### ISSUE TITLE
Stellarium fails to start on raspberry pi OS armhf

### ISSUE THREAD

**Issue by mgrouch** [Stellarium/stellarium#1540]
libEGL warning: DRI2: failed to authenticate
 -----------------------------------------------------
[ This is Stellarium 0.18.3 - https://stellarium.org/ ]
[ Copyright (C) 2000-2019 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "/home/user/.stellarium/log.txt"
File search paths:
  0 .  "/home/user/.stellarium"
  1 .  "/usr/share/stellarium"
Config file  "/home/user/.stellarium/config.ini"  does not exist. Copying the default file.
Config file is:  "/home/user/.stellarium/config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
Unable to find an X11 visual which matches EGL config 11
Segmentation fault

There is no such issue on arm64 version.

**Comment by alex-w** [comment]
Please check https://github.com/Stellarium/stellarium/wiki/Raspberry-Pi

**Comment by mgrouch** [comment]
Which part is relevant? I do not know what to look for

thanks

**Comment by gzotti** [comment]
> For the current Raspbian ("Buster", 2019), just
> 
>     activate the "OpenGL Driver" in raspi-config, Advanced options, Full KMS.
>     follow the building instructions for Linux.

**Comment by mgrouch** [comment]
It is activated. FakeKMS. There is no FullKMS option.
I'm not building stellarium I'm installing it using apt from debian repo.

Thanks

**Comment by gzotti** [comment]
I have seen that you have installed the 2018 version. Therefore, if that does not run, follow the build instructions for Linux. We are not responsible for outdated versions in the Debian repo. We don't know more than we have written in the page given above.

**Comment by mgrouch** [comment]
Is there some PPA where I can get more recent Debian armhf package?
Thanks

**Comment by alex-w** [comment]
@mgrouch please check https://launchpad.net/~stellarium

**Comment by mgrouch** [comment]
Thanks
