### ISSUE TITLE
Min port setting of INDI made some mount can not work

### ISSUE THREAD

**Issue by sennin32** [Stellarium/stellarium#1543]
### Expected Behaviour
Connect mount(Vixen SXW) like Kstars(Mac) with INDI

### Actual Behaviour
The min port was set to 1024.
That makes mounts like VIxen which use HTTP protocol can not work.

### Steps to reproduce
The ip was changed immediately after typing 
So I did some basic search and tried to figure it out.
After spending some time on testing. 
I believe the issue cause by interface layer.
And I got lucky to find which part of the program cause this issue.
[INDI UI config](https://github.com/Stellarium/stellarium/blob/da46a111638fbc3a963cd3a73956f7890267b963/plugins/TelescopeControl/src/INDI/TelescopeClientINDIWidget.ui)
Min of port was set to 1024 on line 77.
Is anyone can correct it and maybe release it in next release?

### System
* Stellarium version: 0.20.4
* Operating system: Mac 10.13.6, But I believe the issue happens on Windows too
* Graphics Card:  It does not related to GPU
* Screen type (if applicable): Build-in screen with Macbook air 2012, but it does not related to the issue either

**Comment by alex-w** [comment]
Why you need port 80 to connect to INDI server?

**Comment by sennin32** [comment]
> Why you need port 80 to connect to INDI server?

Cause vixen starbook one use HTTP protocol.
INDI driver for it also use that as the solution.
Not as stable and popular as other modern solutions, I guess that's why it disappears.

**Comment by alex-w** [comment]
Stellarium is INDI-client, who can connect to INDI-server, which control devices through drivers. So, INDI-server control Vixen via HTTP protocol. Why INDI-client should use HTTP protocol for connection to INDI-server?

**Comment by sennin32** [comment]
> Stellarium is INDI-client, who can connect to INDI-server, which control devices through drivers. So, INDI-server control Vixen via HTTP protocol. Why INDI-client should use HTTP protocol for connection to INDI-server?

Got it!!!
I thought it is the same as Kstar that shows the port and ip of connection with mounts.
Then connect to the mount directly by launch INDI itself.

I tested again today and it connect normally!
Thank you.

**Comment by alex-w** [comment]
So, is the “problem” solved?

**Comment by sennin32** [comment]
> So, is the “problem” solved?

Yes, exactly.
I can use kstar's build-in INDI function to setup parameters of mount and connect with Stellarium now.
It works fine.
