### ISSUE TITLE
calendars do not completely follow language changes

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1545]
### Expected Behaviour
Calendar language tracks language changes

### Actual Behaviour

![image](https://user-images.githubusercontent.com/3529789/111014420-d4523f80-83a3-11eb-8d4d-6a288b860dc5.png)

### Steps to reproduce

1. enable calendar plugin (Alt+K?)
2. change program language (F2 > Main)
bug: language is not changed in calendar

## workaround
change the setting, save, and restart.

### System
* Stellarium version: Stellarium 0.20.4-f5740f7 [master]
* Operating system: KUbuntu 20.04
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

**Comment by gzotti** [comment]
Yes, I know.
