### ISSUE TITLE
Extend or remove 100 000 years date limit

### ISSUE THREAD

**Issue by gotgutgit** [Stellarium/stellarium#1546]
Please let the user choose dates **beyond 100 000 years** in the past or in the future. I'd like to model constellation changes based on currently known proper motion data for major stars. Maybe add a warning about accuracy or a checkbox somewhere in the configuration to remove this limit.

**Comment by gzotti** [comment]
Unfortunately the proper motion data are not good enough to warrant this. Even 100.000 years are too much IMHO, rather stay within 40.000. (See Appendix F in the User Guide.) There are some online programs which already show stars from Gaia which should be much better suited for that purpose.

**Comment by gotgutgit** [comment]
> There are some online programs which already show stars from Gaia which should be much better suited for that purpose.

@gzotti Could you please point me at some of these programs? Actually, the best one I could find so far is Stellarium. :)
And will Stellarium include data from Gaia & Hipparcos which were used in making of this 450 000 years video? https://www.space.com/37148-orion-constellation-changes-over-450000-years.html

**Comment by gzotti** [comment]
Currently I cannot find more than Google, it's not my field of immediate interest. 
As much as I'd like to have a better star catalog myself, somebody would have to actually develop it. Stellarium's development is based on voluntary work by currently 2 people who are more than busy with their own focal tasks.
