### ISSUE TITLE
0.20.4: Windows MESA mode broken

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#1551]
### Expected Behaviour
Calling MESA option on startup runs OpenGL processed on the CPU

### Actual Behaviour
The program is running with high CPU load without a visible window. 

### Steps to reproduce
run with MESA option from start menu

Version 0.20.3 works fine.

### System
* Stellarium version: 0.20.4-win64.exe
* Operating system: Windows 10 20H2
* Graphics Card: (Geforce,) but the point is circumventing missing GPU by emulated graphics. 

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/6152824/log.txt)

I consider this less critical than the ANGLE issue #1549, as more users likely run ANGLE. Still pretty annoying.

**Comment by alex-w** [comment]
@gzotti please check the current master

**Comment by gzotti** [comment]
No, the shader fix #1549 was independent from this issue. It must have crept in between 0.20.3 and 0.20.4.

**Comment by alex-w** [comment]
Hmmm... what about use library from https://github.com/Stellarium/stellarium-data/releases/tag/qt-5.6 ?

**Comment by gzotti** [comment]
No, these are for ANGLE. I'm talking about opengl32sw.dll, the CPU-only solution for ~pre-20009 multicore methusalems without proper GPU. Not sure how many are running this, at 5fps or so... (still better than nothing, in some applications, though).

I try to identify the time of incidence. (now "after October 21, 2020".)

**Comment by gzotti** [comment]
Ah, here. The multisampling ff4a38b9d1a57637741e7c47fbf858c231686bd0. 
This broke Spout and Mesa. That means, calling with Mesa must disable multisampling just like spout does.
