### ISSUE TITLE
Multisampling is broken on Linux

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#1553]
Linux never has `ENABLE_SPOUT` defined, while current check for the `qApp` property compares the property value to `"none"`, while actual value is absent (gets converted to `""`). This results in multisampling being always disabled on Linux (actually, on everything `!WIN32`).

**Comment by 10110111** [comment]
This change would fix it, but I'm not sure if it's the best approach.

```diff
diff --git a/src/CLIProcessor.cpp b/src/CLIProcessor.cpp
index 99dc9ac3e2..50dc64031d 100644
--- a/src/CLIProcessor.cpp
+++ b/src/CLIProcessor.cpp
@@ -303,6 +303,8 @@ void CLIProcessor::parseCLIArgsPostConfig(const QStringList& argList, QSettings*
         qApp->setProperty("spout", "none");
     if (!spoutName.isEmpty())
         qApp->setProperty("spoutName", spoutName);
+#else
+    qApp->setProperty("spout", "none");
 #endif
 }
 
```

**Comment by gzotti** [comment]
Ah, right...

**Comment by gzotti** [comment]
Thanks. This is one of maybe 3 ways to do it, and reasonably simple.
