### ISSUE TITLE
Arctic and antarctic lines

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1555]
In older starmaps and star globes, there is often markings for arctic and antarctic circles in the sky. They correspond to the zenith passage of said circles on Earth.

It might be useful to add them to the archaeolines plugin.

**Comment by gzotti** [comment]
Also new globes should have them. But I don't really see their application in the sky. Can you give a use example?

**Comment by Atque** [comment]
@gzotti I don't really see a use either, other than "might be interesting", and help recreate old star globes, in case you happen to find one.

**Comment by axd1967** [comment]
star globes are a good future idea for Stellarium. they can be simulated with orthographic projection + H flip

![image](https://user-images.githubusercontent.com/3529789/111814446-bff9cf80-88da-11eb-8e98-6b9837750422.png)

by enabling the arctic lines, the user can see why those are the limits of sun rays
in this image, the Sun almost reaches the winter solstice and the Arctic line almost disappears out of sight.

![image](https://user-images.githubusercontent.com/3529789/111814934-5d550380-88db-11eb-9f5b-f0953e76429d.png)

**Comment by Atque** [comment]
@axd1967 Yes, this is how I also simulate star globes. Horizontal flip + orthographic projection + constellation art gives a good representation of how a 400+ year old star globe would appear. Arctic and antarctic lines would be a neat addition. It is of course possible to add them manually by custom declination, but this is not accurate enough, and it doesn't follow the Earth's axial orientation change.

**Comment by gzotti** [comment]
Alright, my globe (19th ct.) has such line...
