### ISSUE TITLE
cardinal points' showing in diff langs

### ISSUE THREAD

**Issue by silas1037** [Stellarium/stellarium#1558]
cardinal points' translation in few langs have lost, which is different from before.

eg.SC

![image](https://user-images.githubusercontent.com/36977717/111874954-3b8a7800-89d2-11eb-9182-287b45a2f40f.png)

**Comment by alex-w** [comment]
See https://github.com/Stellarium/stellarium/blob/master/po/stellarium/zh_CN.po#L520 - the translation is not lost

**Comment by silas1037** [comment]
Okay, it is just a delay of translation.

**Comment by silas1037** [comment]
@alex-w  Could some like "NNE" with 3 letters be hiden in some langs (eg. SC) ? Because they are unusal in some langs.

**Comment by alex-w** [comment]
Not right now, maybe later

**Comment by gzotti** [comment]
You could translate to an empty string (?) But is the equivalent of ENE too much info, or what is the problem?

**Comment by gzotti** [comment]
If that really is an issue, we should have another multi-value switch: Cardinal/Intercardinal/Secondary Intercardinal.

**Comment by alex-w** [comment]
> If that really is an issue, we should have another multi-value switch: Cardinal/Intercardinal/Secondary Intercardinal.

This is in my TODO list

**Comment by adrienbibibi** [comment]
In the French version, the south-south-west direction is displayed as "SSE" instead of "SSO"
Version 0.21.0

**Comment by alex-w** [comment]
> In the French version, the south-south-west direction is displayed as "SSE" instead of "SSO"
> Version 0.21.0

According to Transifex it's correct: https://www.transifex.com/stellarium/stellarium/translate/#fr/stellarium/311706047?q=text%3ASSE

**Comment by alex-w** [comment]
> @alex-w Could some like "NNE" with 3 letters be hiden in some langs (eg. SC) ? Because there are no such usage in some langs.

Yes, you can hide 3 letters directions now.

P.S. How many directions with labels you see on Chinese compass?

**Comment by silas1037** [comment]
> P.S. How many directions with labels you see on Chinese compass?

Surely 8.
3 letters directions only appears in geology because these words were imported from English.

**Comment by silas1037** [comment]
> P.S. How many directions with labels you see on Chinese compass?

Surely 8.
3 letters directions only appears in geology because these words were imported from English.

**Comment by alex-w** [comment]
> > P.S. How many directions with labels you see on Chinese compass?
> 
> Surely 8.
> 3 letters directions only appear in geology because these words were imported from English. When attempting to descript them, we use angles instead.

Ha! Probably you can create an implementation of Chinese compass as a plugin :)

I've found this drawings:
![-](https://user-images.githubusercontent.com/88731/120681686-d3720b00-c4c5-11eb-93d0-6bbbe37ccb52.jpg)
![60-601689_drawing-chinese-compass-polynesian-arrow-circle-tattoo-design](https://user-images.githubusercontent.com/88731/120681738-e2f15400-c4c5-11eb-82e1-567e440ed37c.png)

So, Chinese compass has 8 "cardinals" and 24 "ordinals". This is really fun, but I guess other versions of compasses are exists (I just didn't know about before as class).

**Comment by silas1037** [comment]
> So, Chinese compass has 8 "cardinals" and 24 "ordinals". This is really fun, but I guess other versions of compasses are exists (I just didn't know about before as class).

Some multi-layer compass may have tens of circles like below.
https://chaobaoxiaokun.github.io/compass/

![image](https://user-images.githubusercontent.com/36977717/120742185-0bf70080-c529-11eb-9bcc-c82080aecb60.png)

> Ha! Probably you can create an implementation of Chinese compass as a plugin :)

I am willing to, but most importantly they seem to be used in geomantic omen rather than about astronomy so that it's hard for me to connect them with astronomy application, well maybe just because I know less.

(common usage: Put it with some angle in rules (mostly relative to house), and explain what's the meaning of pairs of words pointed by the pointer.)

P.S. Mainly elements connected to astro is the twenty-eight lunar mansions.

Maybe we could listen to what @sunshuwei says.

**Comment by freemanli** [comment]
It comes from Feng shui (Chinese: 風水, https://en.wikipedia.org/wiki/Feng_shui ) and is used specially for building. I don't think it has any application to stellarium.

**Comment by alex-w** [comment]
OK! In any way the visibility of intercardinal and secondary intercardinal points (8-wind compass rose and 16-wind compass rose respectively) are switchable now and users can configure visibility of labels by own preference. I hope we will not adding a  32-wind compass rose for sailors. :)
