### ISSUE TITLE
Apparent inaccuracies in star almanacs / ephemerides in the past (i.e.  γ Dra in 1871-02-28)

### ISSUE THREAD

**Issue by baryluk** [Stellarium/stellarium#1559]
### Expected Behaviour
Accurate predictions.

### Actual Behaviour

![Screenshot at 2021-03-20 21-38-22](https://user-images.githubusercontent.com/110322/111886345-f744ab00-89c4-11eb-9def-88716ecab3cd.png)

This is a simulated view of  γ Draconis, from Royal Observatory, Greenwich, at night 1871-02-28  (as you can see it is actually morning of the next day).

I advanced the time so the  γ Draconis is exactly at local Zenith. I made it as close as possible. (it in fact should be slightly closer, the error is of about 1 arc minute here).

The problem:

"On a supposed alteration in the amount of Astronomical Aberration of Light, produced by the passage of the Light through a considerable thickness of Refracting Medium." By George Biddell Airy, C.B., Astronomer Royal. Received November 17, 1871, published in Proceedings of the Royal society of London. VOL20 (1871-1872). pages 35 to 39.

https://royalsocietypublishing.org/doi/pdf/10.1098/rspl.1871.0011

https://gallica.bnf.fr/ark:/12148/bpt6k56114d/f79.item

one can find that on the night of 28th February of 1871, Airy, measured the Zenith Distance of  γ Draconis to be 83.3“.

The location (51° 28' 34.0“ latitude, ~0°00' longitude) of observation was slightly south to Transit Circle instrument, compared than used in Stellarium, but that will change only by few seconds.

The Stellarium, suggests that it was 7:19 in the morning. A physical impossibility. (for the reference a astronomical twilight  was at 04:55 local time).

So I strongly suggest an issue with Sterllarium or data it is using.

### System
* Stellarium version: 0.20.4-3 from Debian testing.

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
On aberration: https://github.com/Stellarium/stellarium/issues/1272

Have you cross checked your physical impossibility with other software? Or with a planisphere?

**Comment by baryluk** [comment]
> On aberration: #1272
> 
> Have you cross checked your physical impossibility with other software? Or with a planisphere?

Good question.

I tested with https://skyandtelescope.org/interactive-sky-chart/ , and the results are same as Stellarium. 7:19.  I also used the https://in-the-sky.org/skymap.php , and the result is close to Sterllarium, with closest Zenith approach of about 6' (hard to really judge), and time of 7:23. Close enough (probably minor variations in calculation accuracies, proper motions of stars, or equation of time).

Maybe I am reading the original Airy's paper wrong somehow.

**Comment by gzotti** [comment]
Bright stars can be observed in daylight, esp. when you know where to look and the object is in focus. Try it.

**Comment by baryluk** [comment]
I was going to write to archives of Royal Greenwich Observatory, about possibly finding the notes of Airy or his other observers, but I did found semi-raw observations and data reductions in this publication of RGO from 1871: "Greenwich Observations in Astronomy, Magnetism and Meteorology made at the Royal Observatory, Series 2, vol. 33, pp.E59-E61"

"Observations of γ Draconis with the Water-Telescope; and Reduction of the Observations, 1871" by Airy, G. B.

http://articles.adsabs.harvard.edu//full/1873GOAMM..33E..59A/0000630.000.html

For example observation of 1871-02-28 was taken between 19:00 and 20:00. So, not at 7:19 in the morning.
Similarly the one on 1871-03-01 was taken at 19:xx.

There are some other days were observations were takes as early as 17:00 (in the spring), and as latest as 7:30 in the morning (in the autumn).

Interestingly, this is about 12 hours difference comparing the notes and the Stellarium. A 12 hours difference, is a time when γ Draconis, would cross the anti-meridian too, but on the opposite side of the Polaris. For example on 1871-02-28 19:21 is the time when γ Draconis crosses N meridian according to Stellarium, but it is then just 13° above the horizon, where it would be affected a lot by the refraction, and of course the telescope used wasn't even designed to do such measurements - the Airy's Water Telescope could only measure very close to Zenith.

**Comment by baryluk** [comment]
@gzotti I just confirmed by other paper that the observation was not done in daylight, it was at ~19:30, at JD ≈ 2404487.30.

**Comment by baryluk** [comment]
Cartes du Ciel / SkyChar 4.3.4350 and KStars 3.4.3 shows the same results as Stellarium. That makes it unlikely that the all are wrong.

I believe the issue is that before 1925, the GMT in astronomical observation was actually set with 0 at noon, not midnight. It is now refered as GMAT

That explains everything. ~19:15 GAMT, is 7:15 counting from midnight.

My bad.

**Comment by gzotti** [comment]
If you study the papers and conclude it was 12 hours off, OK. But I wonder, if this was a zenith telescope and you want to observe the minuscule effects of aberration, observing the star at inferior culmination (15° high) is as bad as you can get. If a zenith passage (or something in the vicinity) was observed with a zenith telescope, the original time would fit considerably better. IMHO it's the only solution.  But I have no time now to investigate this further.
