### ISSUE TITLE
Stellarium 0.21.0RC1 labels for umbra and penumbra missing

### ISSUE THREAD

**Issue by kajaji** [Stellarium/stellarium#1560]
### Expected Behaviour
labels of Umbra/Penumbra circles to be shown
### Actual Behaviour
No Labels on the circles

### Steps to reproduce
In View Makings tab select to show umbra and penumbra.
Circles displayed without labels
### System
* Stellarium version: 0.21.0RC1
* Operating system: Windows 10
* Graphics Card: NVidia Geforce
* Screen type : 3840x2160, HighDPI, 75% scaling

**Comment by gzotti** [comment]
Funny, indeed.

**Comment by alex-w** [comment]
Why 0.21.1? Just add a special case near line 836 in GridLinesMgr.cpp file.

**Comment by gzotti** [comment]
Just zero time before 0.21.0. But go ahead.

**Comment by alex-w** [comment]
@gzotti When you introduced the circles of shadows then where would you expect to see labels for their circles?

**Comment by gzotti** [comment]
The labels for the great circle lines usually appear when the screen border intersects them. Usually the (pen)umbra circles are small enough to fit fully in the screen. If somebody requires to see the labels we can add them even to the fully visible circles. But is this not ugly screen clutter when we want to observe eclipses? So, back to "display only when they intersect the screen border". TBH, probably I just filled in the label text for completeness but I never missed the labels here.

**Comment by alex-w** [comment]
Hmm... probably 0.21.1 is good target for this issue, because it requires discussion to the limits for visibility and placement of labels.

**Comment by gzotti** [comment]
Now after looking at the code again: These circles are not even small circles but an off-axis (by observer parallax) line loop, so the screen intersect callback cannot be used here. I recommend not showing labels for the obvious. Or where shall they go and not disturb?
