### ISSUE TITLE
Exclude outdated comet data in ephemeris computations

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#1564]
### Expected Behaviour
Don't include comets beyond their valid time range in ephemeris computations

### Actual Behaviour
Found during trial around #1563: When searching for phenomena around Jupiter's moons in 2021, I can find conjunctions with comets with orbital data from the 1960s or so. 

### Steps to reproduce

Load 1000 comets data file. 
Use AstroCalc/Phenomena to search for phenomena around Jupiter's moons, e.g. June to September 2021.

### System
* Stellarium version: 0.21.0-RC1
* Operating system: Windows (irrelevant)
* Graphics Card: (irrelevant)

**Comment by axd1967** [comment]
An additional option could be to add a button in the MSSO dialog to select objects with an outdated data.
An additional option could be a parameter that specifies when an object is outdated (in days).

![image](https://user-images.githubusercontent.com/3529789/112136791-ba003900-8bcf-11eb-92b2-a573d995b91a.png)

**Comment by gzotti** [comment]
> An additional option could be to add a button in the MSSO dialog to select objects with an outdated data.

Different issue in a separate plugin

And an application-based issue. Some users care for recreating past events and objects, some would remove Hale-Bopp as "outdated". So selecting objects for deletion may require more criteria, like max brightness or so. 

> An additional option could be a parameter that specifies when an object is outdated (in days).

Different (related) issue in that separate plugin

**Comment by alex-w** [comment]
I think we should add 2 additional parameters for solar system bodies (probably goodOrbitDays and timeOfPericenter) from orbital data to handling the state of the valid visibility of SSO through method isObjectDateValid() without parameters, because current JDE we may obtain from core.

@gzotti ?

**Comment by alex-w** [comment]
I see that we has a call the method objectDateValid(JDE) from Orbits class within Comet class to handle compute the data and orbit. So, it should be extended to use for compute positions and orbits of minor bodies.
