### ISSUE TITLE
Include IAU list of approved names for stars

### ISSUE THREAD

**Issue by jscheidtmann** [Stellarium/stellarium#1565]
The IAU has a list of approved star names here:
https://www.iau.org/public/themes/naming_stars/

It seems that in the latest version of Stellarium (0.20.4), this list is not included. E.g. Phecda (gamma UMa) does not yield a result when searching by name. 

This is an issue, as some mounts suggest stars of alignment by name. Sometimes names are not known and then cannot be found in Stellarium. 

Please include the list of IAU names (ideally with alternative spellings) to allow for searches of these stars.

**Comment by alex-w** [comment]
Phecda already in the list: https://github.com/Stellarium/stellarium/blob/0f12e9b2a8ec89543be803c0ff1676ef3546d133/skycultures/western/star_names.fab#L971 (it was included a long time ago)

**Comment by gzotti** [comment]
Strange. I just pressed F3, typed Phecda, and pressed Enter.

Obviously, the IAU list is a must, but as far as I can say, it is already included.

**Comment by gzotti** [comment]
@jscheidtmann does your mount include Wurren? Or Tianguan?

**Comment by alex-w** [comment]
Rey’s SC hasn’t Phecda and we wouldn’t add then into this SC

**Comment by gzotti** [comment]
Ah, that's why. Yes, the Rey SC is an immutable thing. Users are free to copy files around when they know what they are doing... 

BTW the IAU list has been created to *stop* spelling variants. Even if they propose unhistoric spellings.

**Comment by jscheidtmann** [comment]
You're not using Stellarium in stand-alone / off-line mode. 

1) my search dialog displays "simbad search successful", but only for the full name (translated from German)
2) my expectation is that a partial search for "phec" is successful, similar to "plu", which shows "pluto" (among other matches)

**Comment by jscheidtmann** [comment]
Sorry for being imprecise. 

In addition, when clicking on the search results, the information window displays "User defined object":
![stellarium](https://user-images.githubusercontent.com/19821951/112213468-679a3900-8c1e-11eb-9717-a03462aef50f.png)

instead, when I restart Stellarium and click on the star:
![stellarium2](https://user-images.githubusercontent.com/19821951/112213891-df686380-8c1e-11eb-8154-b02f273640d7.png)

Furthermore, I would expect the IAU star names to be present in that information.

**Comment by gzotti** [comment]
If you are using the default "Western" skyculture, it is enough to type "Phe" to get a shortlist including *Phe*cda, Al*phe*cca, Muli*phe*n and others. If you are using other skycultures, for example Western (H. A. Rey), you only see the star names included in that skyculture. If that skyculture does not include Phecda, you don't find it.

**Comment by jscheidtmann** [comment]
Ah, got it. Hmm, leaves me wondering: Shouldn't the IAU names be available in all skycultures? I can understand that there are specific names as per tradition in a skyculture but shouldn't the IAU names be handled as a catalogue? You also display HIP numbers, for example see second screenshot ...

**Comment by gzotti** [comment]
Absolutely not. The default "Western" has the collection of all literature. We intend to let users select the sources in the future. But the particular other skycultures show their respective names, and the concept of authentic representation of skycultures does not allow names not included in the respective source. You can show the star designations "&alpha; CMi" etc. as star label instead of the proper name with the respective switch. 

If you want to break authenticity on your own computer, copy the star_names.fab file from Western to your favourite skyculture directory. Or better, make a private adaptation. See chapter 9 in the User Guide.
