### ISSUE TITLE
Notification for scientists

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1568]
Our "main" article for Stellarium has been published: https://journal.equinoxpub.com/JSA/article/view/17822

We can add notification for scientists into the Help/About window of planetarium for citing this article in their scientific works (who is used Stellarium of course) + added new one item in the FAQ.

@gzotti is it OK?

**Comment by gzotti** [comment]
Yes, please do that. Also add a link on stellarium.org and tweet a bit. I hope the paper (open-access!) will be useful to all!

**Comment by kajaji** [comment]
This link:
DOI: https://doi.org/10.1558/jsa.17822
is broken.

The link is in the The Journal of Skyscape Archaeology page pointed to by:
"Our "main" article for Stellarium has been published: https://journal.equinoxpub.com/JSA/article/view/17822 "

**Comment by gzotti** [comment]
@kajaji I just told Alexander. The publisher should have sorted this out by Monday, latest...

**Comment by gzotti** [comment]
@kajaji  DOI has been fixed.
