### ISSUE TITLE
Suggestion for some features

### ISSUE THREAD

**Issue by i-grow-carrots** [Stellarium/stellarium#157]
1. Air mass data for a specific astronomical object. Also, the ability to ask "When will X be above airmass Y?"

2. Links from astronomical data readouts to online databases: hyperlinked data. 

3. The ability to select exact time steps (not just increasing them by a certain factor).

**Comment by gzotti** [comment]
1a could be added to the extinction info. 1b requires significant work. Is this for more than a handful of users? (see https://answers.launchpad.net/stellarium/+faq/2913)
2 there is a blueprint "Link to Wikipedia". Volunteers?
3 See the Guide, Appendix A.5 or Help [F1]/Date and Time.

**Comment by i-grow-carrots** [comment]
1b. I know there are people who would want airmass calculation functionality. I can't guarantee it's for more than a handful... but I suspect it could be. 

3. Yes, the Guide is well-written. I should have been clearer, though. I am proposing that the speed of the clock itself can be set with precise time steps. Perhaps I'm missing something still.

**Comment by gzotti** [comment]
1a: There are a few models, but I have implemented a good one already, which is used for extinction computation. RefractionExtinction: Extinction::airmass() (currently private, but this could be changed.)

3: The time panel should not become too large with many more extra buttons, we have discussed this several times. Probably we cannot cater for all needs/users. You could always stop time, write a handful of scripts that advances/goes back by whatever time units you want, and assign those to hotkeys. Also have a look into the RemoteControl web interface, there is a page with time step buttons.

**Comment by alex-w** [comment]
@gzotti 1a - OK, it's good solution, but... what about real use cases to using airmass within Stellarium?

**Comment by gzotti** [comment]
What do you mean? It's core of extinction!

**Comment by alex-w** [comment]
Sorry for my bad phrase. I just want to know real uses cases, which requires show airmass for users (except serious astrophotography).

**Comment by gzotti** [comment]
Ah, OK. Yes, I also am unsure who would really want to know such expert details. I learned the hard way (under Namib's crystal skies) that astrophotography around 20° or so is (literally!) pointless even when the object looks great. (30min exposure on color slide, manually fine-guided. The guide star was perfect, the rest of the frame streaked out by changing refraction...)  

Note that the airmass curve is also given in the Guide (Fig. 17.5). This links altitude and airmass.   Insights or rules of thumb about airmass/altitude could of course be added to the Guide.  @i-grow-carrots ?

**Comment by i-grow-carrots** [comment]
@gzotti  @alex-w   I think the software is great how it is. Very inspirational and useful for a lot of people. I remembered that an astronomy student wanted more explicit airmass data, so I passed along the idea. Naturally, a project like this one can't implement everything that everyone wants. I get that.
