### ISSUE TITLE
Proportional hint 'outline' shown in ocular view

### ISSUE THREAD

**Issue by elgjc3** [Stellarium/stellarium#1572]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by elgjc3** [comment]
Under the DSO options when I have the proporitonal hint selected the 'border' appears in the occular view.  Deselecting the proportional hint the border isn't present in the ocular view.

Example:  NGC 6738
Ocular 15mm, 60deg aFOV
Scope D=130mm, FL=650mm

Object has the yellow dots shown when the proportional hint is selected

**Comment by alex-w** [comment]
And, what is the problem?

**Comment by elgjc3** [comment]
Hi Alex,

In the general sky view the proportional hints works well and is useful for me as a visual observer so I can judge the relative size of targets against one another and see those that might be easier to find based on size.

Once I switch to the ocular view, when a single target selected, the relative size of that object becomes, in my view, less important and much more of a personal preference as to how the object is framed based on the insturment and EP combination.  The scaled overlay now obscures a detailed view which isn't helpful when I am comparing what I see in the EP vs what I think I should be looking at from Stellarium.  In the screen shot examples above of M4 the central detail isn't visible.

It would be better if the overlay was hidden in by default when switching to the occular view.

Thank you.
