### ISSUE TITLE
StarMgr Only getting 648 stars

### ISSUE THREAD

**Issue by moudimash99** [Stellarium/stellarium#1574]
when running this api call
"http://localhost:8090/api/objects/listobjectsbytype?type=StarMgr"
I am getting only 648 stars
instead of all the possible stars I have loaded. I have even added 2 more catalogue files but the number is still the same. I currently believe it's more a problem from me than the program, I just wanted to understand what I was doing wrong, and how to access all the star names in the program

### System
* Stellarium version: 0.20.3
* Operating system: Windows 10

**Comment by moudimash99** [comment]
i was using the remote-control plug-in

**Comment by alex-w** [comment]
This method should give a list of all stars with the proper names. Did you used standard western skyculture?

**Comment by moudimash99** [comment]
Greetings thanks alot for taking from your time to respond to my question it really means alot.
I have not changed any setting for the skyculture so i assume i am using it right now
As described in the below image the number of results is only 648
![image](https://user-images.githubusercontent.com/29631946/112906063-345f1a80-90f4-11eb-80f4-da898703da70.png)
which is somehow less than when i call StarMgr:2
i figured i was doing something wrong but I didnt quite understand why that was happening

![image](https://user-images.githubusercontent.com/29631946/112906155-5fe20500-90f4-11eb-9b00-6ba77c3a49e8.png)

**Comment by alex-w** [comment]
This is interesting, I'll look at it problem tonight.

@gzotti any comments, please.

**Comment by gzotti** [comment]
`curl -G   http://localhost:8090/api/objects/listobjecttypes | python -m json.tool`

provides insight:

```
...
 {
        "key": "StarMgr",
        "name": "Stars",
        "name_i18n": "Stars"
    },
    {
        "key": "StarMgr:0",
        "name": "Interesting double stars",
        "name_i18n": "Interesting double stars"
    },
    {
        "key": "StarMgr:1",
        "name": "Interesting variable stars",
        "name_i18n": "Interesting variable stars"
    },
    {
        "key": "StarMgr:2",
        "name": "Bright double stars",
        "name_i18n": "Bright double stars"
    },
    {
        "key": "StarMgr:3",
        "name": "Bright variable stars",
        "name_i18n": "Bright variable stars"
    },
    {
        "key": "StarMgr:4",
        "name": "Bright stars with high proper motion",
        "name_i18n": "Bright stars with high proper motion"
    },
...
```

>600 stars looks like "named stars" indeed. 

You cannot get a list of "all stars" by this API.

**Comment by moudimash99** [comment]
ouhh thats a bit weird  but why does StarMgr 2 list more stars than Star Mgr? shouldnt it be more specific?
I have used that api call you have referenced as by direction tool @gzotti 
Is there a way to get a list of all stars? I was attempting to get that list through the c++ code but I wasnt sure how to be able to call StarMgr And StellApp

**Comment by gzotti** [comment]
I already wrote:

>You cannot get a list of "all stars" by this API.

When you attempt to get the stars with C++: What are you attempting to do? The star catalog formats are described in the User Guide. The details of this API are probably visible in the code only. Also for us.

**Comment by gzotti** [comment]
Please no changes which break compatibility. You may introduce "StarMgr:5" or some other free key. But again, getting "all [millions of] stars" is not possible.

**Comment by moudimash99** [comment]
Ouhh okay I get it so starMgr only gets with proper names . Although @alex-w u hit the nail on the head I’m looking for how to get starmgr::listAllObjects() . The reason is that I’m working on a small project that utilizes all seen stars with a magnitude less than 10 (about 300k)

though sorry to ask but would it be more accurate that calling StarMgr would return list of all stars in stellarium vs it being a specific type of stars?

**Comment by gzotti** [comment]
From the sources of StarMgr:

```
//! @note Loading stars with the common names only.
	virtual QStringList listAllObjects(bool inEnglish) const;	

```
I repeat, another time:

>But again, getting "all [millions of] stars" is not possible.

Depending on whether you want to talk to Stellarium via the HTTP interface, or you want to modify Stellarium with C++, you will also have to familiarize yourself with the code of e.g. Star and StarWrapper classes.

**Comment by moudimash99** [comment]
@gzotti and @alex-w im so thankful for taking so much of your time , I deeply appreciate it. So to confirm the starmgr::listAllObjects() only lists stars with common names not stars with names like VY210 or stuff and there’s no way to get those names?

**Comment by alex-w** [comment]
@moudimash99 see StarMgr::getHipparcosStars() method

**Comment by alex-w** [comment]
Why do you need Stellarium itself? If you need in your project some star catalog only (I mean from Stellarium), then you need to download the star catalog and use it (for example you may download catalogs from the VizieR website). If you try to extend the Stellarium, then you need follow the BUILDING.md instructions.
