### ISSUE TITLE
POD error

### ISSUE THREAD

**Issue by dmacks** [Stellarium/stellarium#1579]
Building stellarium on my OS X 10.13 fails:
```
[ 39%] Generating stellarium.1
[ 39%] Building CXX object plugins/TelescopeControl/src/CMakeFiles/TelescopeControl-static.dir/gui/moc_SlewDialog.cxx.o
/sw/build.build/stellarium-mac-0.11.0-4/stellarium-0.11.0/build/unix/doc/stellarium.pod around line 182: Non-ASCII character seen before =encoding in 'Chéreau,'. Assuming UTF-8
POD document had syntax errors at /usr/bin/pod2man5.18 line 72.
make[2]: *** [doc/CMakeFiles/ManPages.dir/build.make:77: doc/stellarium.1] Error 255
```
Making it an unaccented "e" instead of with the accent aigu clears the error.

**Comment by gzotti** [comment]
Does "stellarium-0.11.0" refer to the version from around the year 2010?

**Comment by gzotti** [comment]
Seriously, 2010 has been a while ago. This site is about the current version only. (Currently version 0.21.0)

**Comment by dmacks** [comment]
Wow, that is a really old version. Sorry for trying to fight old stuff. I was trying to use fink's package, whose specific maintainer seems to have abandoned it. Will NMU a new version and go from there.
