### ISSUE TITLE
Tangled preprocessor tokens in StelFileMgr.hpp

### ISSUE THREAD

**Issue by dmacks** [Stellarium/stellarium#1580]
Building on OS X 10.13 using compiler: Apple LLVM version 10.0.0 (clang-1000.11.45.5) throws a ton of warnings of:
```
/sw/build.build/stellarium-x11-0.11.0-5/stellarium-0.11.0/src/core/StelFileMgr.hpp:20:9: warning: '_STELFILEMGR_HPP' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
#ifndef _STELFILEMGR_HPP
        ^~~~~~~~~~~~~~~~
/sw/build.build/stellarium-x11-0.11.0-5/stellarium-0.11.0/src/core/StelFileMgr.hpp:21:9: note: '_STELFILEMGR_HPP_' is defined here; did you mean '_STELFILEMGR_HPP'?
#define _STELFILEMGR_HPP_
        ^~~~~~~~~~~~~~~~~
        _STELFILEMGR_HPP
2 warnings generated.
```
This code is unchanged in the past decade, so maybe compilers have become better at detecting "legal but probably wrong" code? The construct is:
```
#ifndef _STELFILEMGR_HPP
#define _STELFILEMGR_HPP_
[header code]
#endif // _STELFILEMGR_HPP_
```
notice how the token in the ifndef doesn't match what is then defined and commented in the matched endif.

**Comment by gzotti** [comment]
Please do not report syntax issues from yesteryear here. The code has changed significantly in the past decade. One problem more recent compilers dislike is the underscore. Now it reads

```
#ifndef STELFILEMGR_HPP
#define STELFILEMGR_HPP

```

You will also need to find Qt4 libraries to compile this historical code.

**Comment by dmacks** [comment]
Wow, that is a really old version. Sorry for trying to fight old stuff.
