### ISSUE TITLE
Hercules constellation issue?

### ISSUE THREAD

**Issue by blakesphere** [Stellarium/stellarium#1599]
Hello.

Just found a weird error in Stellarium. I tried using the Search box to locate a constellation. Works fine, in general. Earlier I had found Virgo, Leo, Ursa Major, etc. If you search for "Hercules" you get dropped at the star Pollux! Huh?!

I also tried browsing the constellation list in the Search box. 

Same issue!

* Stellarium version: 0.21.0 (32-bit)
* Operating system: Win 10 

Had another expert user test it on their system.

Rolled back to Stellarium 0.18.0. Same error! If you do Search, Lists, Constellations, and choose Hercules, you end up on a star in Gemini.

regards,
Blake

**Comment by alex-w** [comment]
The second name of beta Gemini is Hercules, so, this is not an error, but I'll add context for it.

**Comment by blakesphere** [comment]
hi Alex. Can you quote your source for Hercules as the Geminorium star name, please? Thanks, Blake.

**Comment by alex-w** [comment]
Sources of the names for HIP 37826:
- Kunitzsch, P.; Smart T. (2006). "A Dictionary of Modern star Names: A Short Guide to 254 Star Names and Their Derivations" (2nd rev. ed.). Cambridge, MA: Sky Pub. ISBN 978-1-931559-44-7
- Allen, R. H. (1963). "Star Names: Their Lore and Meaning" (rep. ed.). New York, NY: Dover Publications Inc. ISBN 0-486-21079-0
- [IAU Catalog of Star Names (IAU-CSN)](http://www.pas.rochester.edu/~emamajek/WGSN/IAU-CSN.txt)
- Jack W. Rhoads (1971). "[Technical Memorandum 33-507-A Reduced Star Catalog Containing 537 Named Stars](http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19720005197_1972005197.pdf)", Jet Propulsion Laboratory, California Institute of Technology; November 15, 1971
- [IAU Naming Stars](https://www.iau.org/public/themes/naming_stars/)
- [Bright Star Catalogue, 5th Revised Ed.](http://vizier.u-strasbg.fr/viz-bin/VizieR?-source=V/50) (Hoffleit+, 1991)
- Josef Klepesta, Antonin Rukl (1977). "Constellations: A concise guide in colour". ISBN 0600008932

**Comment by gzotti** [comment]
Hercules/Apollo are listed in the BSC and Allen, the latter mentions them as being in use until Flamsteed's times. Today these names are totally out of use. We have plans to let users exclude unwanted sources from the star names, when data are complete and somebody finds time to tackle a few major tasks around skycultures.
