### ISSUE TITLE
Migrating Translations

### ISSUE THREAD

**Issue by gunchleoc** [Stellarium/stellarium#16]
As discussed on the mailing list, it would be good to get the translations off Launchpad too and host them somewhere else, where the translators might get the following goodies:

* Fuzzy matches from the translation memory. This way, small changes won't completely kill the string for those who are not translating offline
* Support for additional file formats for the sky culture and landscape etc. translations

The 2 options I like best personally are:

# Pootle

* This tool is free as in freedom, and Stellarium will have full control over everything
* Translators can switch on other translations to guide them, e.g. a Bulgarian translator could display both the English source strings and the Russian translation at the same time
* Glossary function
* You will have to run your own Django

I have never run a Pootle server, but they do have a [step-by-step guide](http://docs.translatehouse.org/projects/pootle/en/stable-2.8.x/server/index.html) on how to do it. Pushing and pulling translations can be fully automated.

http://pootle.translatehouse.org/

# Transifex

* Non-free, but free-to-use for FLOSS projects
* Displaying other languages is blocked, unless you're a member of the other language's translation team too
* Glossary, social features and issue tracker
* You won't need to take care of the hosting

You can push and pull translations with the [Transifex client](https://docs.transifex.com/client/introduction).

http://transifex.com/

**Comment by xalioth** [comment]
I just had a look at both, and also tried POEditor.com

The main issue with Pootle is that it's annoying to maintain, (or have someone maintain) a server for us.
POEditor is a bit awkward because it doesn't really have the concept of template .pot file, i.e. all files must be a translation for a language

My personal conclusion is that the easiest would be to use Transifex, as it's quite github-friendly with the configuration stored directly in a file. It's also used by many major open source projects, so I guess it will be more familiar for translators.

**Comment by xalioth** [comment]
@alex-w should we go for it and create a Stellarium transifex project ?

**Comment by cardinot** [comment]
@xalioth @alex-w 
If we decide for Transifex, FYI, I have an account for Stellarium which I've created a few time ago when I was testing the service. I'll add you there as maintainers anyway.
https://www.transifex.com/stellarium/stellarium/

**Comment by xalioth** [comment]
OK, if we want to start we need to add .tx directory etc..

see here: https://docs.transifex.com/integrations/github

**Comment by alex-w** [comment]
No objection at the moment.

**Comment by xalioth** [comment]
@cardinot You also need to add a "ressource" for the stellarium website: https://github.com/Stellarium/stellarium.github.io/tree/master/po

Also, I don't know if it's possible, but ideally we would like to have the translations output directly in .json files in https://github.com/Stellarium/stellarium.github.io/tree/master/_data/i18n

without going through the .po format

**Comment by gunchleoc** [comment]
That was fast, thank you all!

Now, how about adding [landscapes](https://github.com/Stellarium/stellarium/blob/master/landscapes/garching/description.en.utf8), [Scenery3D](https://github.com/Stellarium/stellarium/blob/master/scenery3d/Sterngarten/description.en.utf8) and [Sky Culture Descriptions](https://github.com/Stellarium/stellarium/blob/master/skycultures/arabic/description.en.utf8) too?

That's a lot of files though, so maybe we need some change in the format first?

**Comment by gunchleoc** [comment]
Another point, this project should use Transifex' glossary goodies now to help with terminology consistency.

I once used a temporary project on Transifex to create a glossary for Stellarium - maybe you can upload it to get a list of terms that translators can work off of?

[Stellarium.zip](https://github.com/Stellarium/stellarium/files/1513556/Stellarium.zip)

The upload function is at: https://www.transifex.com/stellarium/settings/glossary/

I also have a [python script](https://bazaar.launchpad.net/~widelands-dev/widelands/trunk/view/head:/utils/generate_glossary.py) that you can use to autotranslate glossary entries for everybody after that upload is done - you'll need to fetch a copy of he glossary off Transifex to prefill the source terms and language list.

The script will take a Transifex glossary csv file and then walk a directory of gettext po files to run poterminology on them. All generated entries will have a warning in the note for the translation that they have been autogenerated, so that translators can decide if the term still needs attention.

**Comment by alex-w** [comment]
The glossary should in the UTF-8 encoding

**Comment by gunchleoc** [comment]
I downloaded it from Transifex, copied my data over in LibreOffice and then saved... now who was the joker who encoded it as Windows? Here's the corrected glossary file:

[Stellarium-utf8.zip](https://github.com/Stellarium/stellarium/files/1513946/Stellarium-utf8.zip)

**Comment by alex-w** [comment]
Apparently Transifix change file format: https://docs.transifex.com/setup/glossary/uploading-an-existing-glossary

**Comment by gunchleoc** [comment]
Added a comment column - that should hopefully do it.

[Stellarium-utf8.zip](https://github.com/Stellarium/stellarium/files/1513998/Stellarium-utf8.zip)

**Comment by leonardcj** [comment]
As a long time FLOSS Translation Team Coordinator for SugarLabs (but only a recent visitor to Stellarium), I'm a huge Pootle fan and consider the Translate House Team as valued colleagues and friends, but I do understand the appeal of having Transifex run a server for you.  If you wanted to explore Pootle, I'd try to help.  My own instance is a bit long in the tooth or I'd offer to host.

**Comment by gunchleoc** [comment]
Does closing this bug mean that you don't want to upload the glossary?

**Comment by alex-w** [comment]
The glossary has been uploaded a week ago.

**Comment by gunchleoc** [comment]
Have you [linked it to the project](https://docs.transifex.com/setup/glossary/associating-a-project-to-a-glossary)? All I see is an [empty glossary](https://www.transifex.com/stellarium/stellarium/glossary/en/?filter=&count=25).

**Comment by alex-w** [comment]
Please check it again

**Comment by gunchleoc** [comment]
It's fixed, thanks a lot! :)
