### ISSUE TITLE
DSO outlines sometimes cause spurious lines

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#160]
### Expected Behaviour
No lines zipping through screen when moving the scene
### Actual Behaviour
![stellarium-004](https://user-images.githubusercontent.com/18099873/40266527-32fdc752-5b4d-11e8-9096-6db815a81095.png)

### Steps to reproduce
 - Activate "Use outlines for big deep-sky objects"
 - Switch on all classes which are rendered with the outlines for maximum chance.
 - Move around slowly with FoV around 60..75°. Occasionally a green or red line may flash across the screen. In rare cases you can "catch" it like here. A small movement will make it go away. Also switching off "outlines" identifies those as culprit.

### System
* Stellarium version: (Seen on master on 2018-05-19)
* Operating system: WIndows 10 (but should not matter)
* Graphics Card: NVidia GeForce 960M (but should not matter)

### Logfile 
Does not help here.

I assume some clipping or projection artifact. (Stereographic used here, not found [but not hunted for excessively] with others.)

**Comment by gzotti** [comment]
Did not fix :-(
![stellarium-009](https://user-images.githubusercontent.com/18099873/40269401-440cc062-5b7e-11e8-8e91-23121a2d62fa.png)

It seems this here is caused by one of the nebulas in Orion, just opposite. Maybe the DSO can be culled away when it's in the opposite view direction? If I move slightly, there are 3 lines shooting like laser beams from the bottom-left corner.

**Comment by alex-w** [comment]
It's strange, I cannot reprodice it anymore. :-/

**Comment by alex-w** [comment]
OK, I may reproduce it again in very specific cases - seems we have a small bug in StelPainter when intersections and clips are calculated. A possible precission or rounding errors?

**Comment by gzotti** [comment]
It has possibly been solved by some work of @guillaumechereau. Guillaume, can you remember if your line fix is related?
