### ISSUE TITLE
WDS Struve Appendix catalogue errors?

### ISSUE THREAD

**Issue by blakesphere** [Stellarium/stellarium#1604]
Just spotted a little catalogue error in Stellarium. 

ν (nu) 2 Draconis aka 25 Dra aka Kuma. It is in the Washington Double Star database as Struve Appendix item number 35 or STFA 35 or ΣA35. Stellarium shows it as Σ35. The "A" is missing.

Full WDS identifier with discoverer code is: 17322+5511 STFA 35

Found another! δ (delta) Cephei. Should ΣA58 in Stellarium not Σ 58.

And iota Boo. Missing the "A" on Σ 26.

Also tested Psi 1 Aqr. Shows as Σ 12 when it should be Σ B 12. Official WDS code is 23159-0905 STFB 12.

Looks like this is a general issue with the Appendix items.

Sometimes, Struve's additional items are shown with Roman numeral.
Σ I (STFA) aka appendix 1
Σ II (STFB) aka appendix 2

Stellarium version:  0.21.0

regards,
Blake

**Comment by alex-w** [comment]
We used Wil Tirions atlas as a source of designations and probably it have a mistakes. Could you review all STF, STFA and STFB stars?

**Comment by blakesphere** [comment]
I've been doing spot checks and everyone I have found exhibits this error. I found about a dozen so far.

HD 21700	BD+27 514	SAO 75964	HIP 16386	STFA 7    in Taurus
Mintaka	Delta Ori, 34 Ori	SAO 132220	HIP 25930	STFA 14	
Tau Leo	84 Leo	SAO 118875	HIP 55945	STFA 19	
32 Com	HR 4884	SAO 100309	HIP 62807	STFA 23	
Iota Boo	21 Boo	SAO 29071	HIP 69713	STFA 26
Delta Boo	49 Boo	SAO 64589	HIP 74666	STFA 27
Alkalurops	Mu 1 Boo, 51 Boo	SAO 64686	HIP 75411	STFA 28
Kuma	Nu 2 Dra, 25 Dra	SAO 30450	HIP 85829	STFA 35
Sheliak	Beta Lyr, 10 Lyr	SAO 67451	HIP 92420	STFA 39
Delta Cep	27 Cep	SAO 34508	HIP 110991	STFA 58
Dabih	Beta Cap, 9 Cap	SAO 163481	HIP 100345	STFA 52
3 Peg	HR 8265	SAO 126940	HIP 106783	STFA 56
56 And	HR 557	SAO 55107	HIP 9021	STFA 4
ψ1	 	Aqr	aka STFB 12
1	Peg	aka STFB 11

Understood you used Tirion for the source. That's not official.

Ultimately for double star data, the official source of the Washington Double Star database should be used. 

It is currently hosted at Georgia State University. The WDS is owned by the US Naval Office.
http://www.astro.gsu.edu/wds/

There's also an interface provided by Stelle Doppie, which uses the WDS, by Luke.
https://www.stelledoppie.it/index2.php?section=1

Blake

**Comment by alex-w** [comment]
The WDS is not available directly from Russia (probably Georgia State University staff fear that Russian will steal secret data about double stars or this is just an example of censorship).

**Comment by blakesphere** [comment]
That sucks. 

I can scrap the current lists if you want. There are 4 files. Total of about 150 000 pairs.

If you want me to do that, where would i put the files?

Blake

**Comment by alex-w** [comment]
The second link is available.
.

**Comment by blakesphere** [comment]
Awesome! Very good.

All working except...
Mintaka Delta Ori, 34 Ori SAO 132220 HIP 25930 STFA 14

**Comment by alex-w** [comment]
> All working except...
> Mintaka Delta Ori, 34 Ori SAO 132220 HIP 25930 STFA 14

It's fixed later: https://github.com/Stellarium/stellarium/commit/6c62c65da14e87928c0ca3bcaf0ffa15f5f50934#diff-038643314c4891a78028d67805e2b496b2d7559c80ea944c36f0369ebb112addR5286
