### ISSUE TITLE
libstelMain.so is not installed by make install

### ISSUE THREAD

**Issue by badshah400** [Stellarium/stellarium#161]
The shared library libstelMain.so generated by `make` is not installed when `make install` is run. As a result, running stellarium (v0.18) fails with the error:
```
stellarium: error while loading shared libraries: libstelMain.so: cannot open shared object file: No such file or directory
```

For openSUSE's RPM packages (and ditto for Fedora, I noticed) we manually copy it to the system lib dir, but this should typically be done by the `make install` script.

### Expected Behaviour
Stellarium installed by invoking `make install` (after building it using `cmake` and then `make`, of course) should run without complaints.

### Actual Behaviour
The stellarium binary complains of missing shared library libstelMain.so unless said library is manually copied from the build dir to a valid library path (e.g. `/usr/lib64/`)

### Steps to reproduce
* Build according to directions
* Invoke `make install` to install binary, shared application files, etc.
* Run `stellarium` from the command line.

### System
* Stellarium version: 0.18.0
* Operating system: openSUSE Tumbleweed (Linux 4.16.9)
* Graphics Card: Nvidia

### Logfile 
Not relevant

**Comment by alex-w** [comment]
How you get libstelMain.so?

Please show diff for your building rules between latest and previous versions.

**Comment by badshah400** [comment]
Have a look at changes to the spec file here:
https://build.opensuse.org/request/show/610431

The only changes to build rules are
```
 %build
-%cmake -DENABLE_SOUND=1
+export QT_HASH_SEED=0
+%cmake -DUSE_PLUGIN_TELESCOPECONTROL=OFF
```

The fully expanded `%cmake` macro is:
```
/usr/bin/cmake /home/abuild/rpmbuild/BUILD/stellarium-0.18.0/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DCMAKE_MODULE_LINKER_FLAGS=-Wl,--as-needed '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/share/cmake/Modules -DUSE_PLUGIN_TELESCOPECONTROL=OFF
```

**Comment by alex-w** [comment]
I think better path for Source0 should be:
`Source0:        https://github.com/Stellarium/stellarium/archive/v%{version}/stellarium-%{version}.tar.gz`

Plus I see `-DBUILD_SHARED_LIBS:BOOL=ON` in `%cmake` macro, but we use shared library for Windows/MinGW packages only. Please try define `%cmake -DBUILD_SHARED_LIBS=0` in the spec file.

**Comment by badshah400** [comment]
Thanks for both suggestions. Turning off shared libs fixes the problem. So, it is discouraged to have shared libs enabled for our RPM pkgs then?

**Comment by gzotti** [comment]
@badshah400 did that solve your issue?

**Comment by peti** [comment]
Fixed for openSUSE in https://build.opensuse.org/request/show/622840.

**Comment by gzotti** [comment]
What is the problem with the Telescope plugin?

**Comment by badshah400** [comment]
@gzotti That plugin doesn't build -- at least not without hacky modifications to the cmake file -- when libStel is built as shared library, but now that we have switched to using static lib, we can enable that back:
https://build.opensuse.org/request/show/623560

Thanks for pointing this out.

**Comment by peti** [comment]
I believe this ticket can be closed.

**Comment by gzotti** [comment]
Good!
