### ISSUE TITLE
Sudden change of the sun location between year 1582&1583.

### ISSUE THREAD

**Issue by hamed59** [Stellarium/stellarium#1622]
Hi guys,

I just found a bug in the Stellarium software. The position of the sun is changing between years 1582 and 1583 whereas it should be stable on it's spot. If this bug exists it will have an effect on the other calculations. Has a similar bug been reported earlier?

**Comment by alex-w** [comment]
This is not a bug!

Please read about differences between Julian and Gregorian calendars and date of introduction the last one.

**Comment by gzotti** [comment]
Please learn about the Gregorian calendar reform. Read at least Appendix F.8 of the Stellarium User Guide.

**Comment by hamed59** [comment]
Believe my comments are not understood clearly. It's not about the difference between Julian and Gregorian calendars. Set the date on 1582 and change the year to 1583. Between year 1582 and 1583 the sun suddenly changes position. Even if the calendars change the position of the sun should not change

**Comment by hamed59** [comment]
Thanks a lot Alex.
