### ISSUE TITLE
Sudden change of the sun location between year 1582&1583

### ISSUE THREAD

**Issue by hamed59** [Stellarium/stellarium#1623]
Believe my comments are not understood clearly. It's not about the difference between Julian and Gregorian calendars. Set the date on 1582 and change the year to 1583. Between year 1582 and 1583 the sun suddenly changes position. Even if the calendars change the position of the sun should not change

**Comment by alex-w** [comment]
> Set the date on 1582 

You are set the date in Julian calendar 

> and change the year to 1583. 

You are set the date in Gregorian calendar

> Between year 1582 and 1583 the sun suddenly changes position. Even if the calendars change the position of the sun should not change

The position of the Sun is not changed, but you set artificial difference in few days between dates. Seriously, please learn about Gregorian calendar reform.

**Comment by alex-w** [comment]
Duplicate of #1622
