### ISSUE TITLE
Stellarium for visually impaired

### ISSUE THREAD

**Issue by RichardJAdams** [Stellarium/stellarium#1624]
**I am having a real problem starting with Stellarium due toi the colour combinations on menus etc. Is it possible to view menus with black/white background/text colour combination. I have had a look at the manual but can't find anything that looks useful. Aside from being centrally blind in one eye, the other has difficulty seeing anything with low contrast between background and foreground..I do nt see well in dim or very bright lighting

**Comment by alex-w** [comment]
No, it’s impossible.

**Comment by gzotti** [comment]
It may be easier to develop a variant of the RemoteControl web based GUI with different colours. Just exchange ~1000 lines of CSS... However, not all parts of the program can be operated in this interface.

**Comment by axd1967** [comment]
> No, it’s impossible.

I'm not sure about that.

It should be possible with Qt themes, as this is a fundamental feature of Qt.
If I'm not mistaken, Qt could even allow the end user to modify the _runtime theme_ without programmatic efforts.

https://doc.qt.io/qt-5/topics-ui.html
https://doc.qt.io/qt-5/qtquick-usecase-styling.html
https://forum.kde.org/viewtopic.php?f=17&t=136316
https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications
https://stackoverflow.com/questions/21078950/set-application-theme-in-qt
https://stackoverflow.com/questions/6740333/can-i-run-a-qt-application-with-a-specific-theme
https://askubuntu.com/questions/909075/how-to-customize-the-colors-of-qt-applications-in-ubuntu-16-10
https://www.reddit.com/r/kde/comments/7khhfd/setting_colorscheme_on_a_perapplication_basis/

(By the way, this is an example of an issue in ergonomy: see also #678 )

**Comment by axd1967** [comment]
@alex-w  please stop these games. see https://github.com/Stellarium/stellarium/issues/1627#issuecomment-830668047

**Comment by alex-w** [comment]
> @alex-w please stop these games. see [#1627 (comment)](https://github.com/Stellarium/stellarium/issues/1627#issuecomment-830668047)

Stellarium doesn't support themes, but you're writing that this is wrong, so, probably you'we implemented theme support for planetarium and you have the code for this feature. If you have nothing, then why are you misleading others?

**Comment by treaves** [comment]
@RichardJAdams does the night mode work for you?

The issue with stylesheets is that almost the entire GUI of Stellarium is OpenGL.  It's not widgets.  Any widget is theme able, and the css that Stellarium uses is data/gui/normalStyle.css Feel free to play with that to see what impact it has.

If we could get more developers interested, it's time to redesign the GUI - maybe move to QML.  But we have neither the skills nor the time for that.

**Comment by gzotti** [comment]
One minor problem is that some CSS bits are hardcoded in the program. Somebody would have to go through all and analyze the existing CSS which is far from simple. I have put in a few hours playing with loadable css, but soon concluded it must be somebody else's problem. My first idea, build a new RemoteControl GUI with your favorite CSS, still may be the simplest.
 
There is a GUI define somewhere which allows building a GUIless program. It could be extended to build an alternative GUI. So yes, somebody else could design something entirely new.  It may allow better touch screen interaction and help in the display size zoo as well. 

Somebody, are you here? Somebody, do you hear?

**Comment by alex-w** [comment]
Please check details for adding user CSS in Stellarium User Guide - https://github.com/Stellarium/stellarium-data/releases/download/guide/guide.pdf
