### ISSUE TITLE
Cannot toggle full screen mode on GNOME 40

### ISSUE THREAD

**Issue by paolostivanin** [Stellarium/stellarium#1625]
### Expected Behaviour
Full screen mode (F11) can be toggled on GNOME 40.x

### Actual Behaviour
After the update to GNOME 40.x, when toggling full screen mode with F11 (going from full screen to resizable window) the windows disappear. The process is still running in background, but the window cannot be found. I have to kill the process using `kill -9 ...`.

### Steps to reproduce
* install openSUSE Tumbleweed with GNOME 40.x
* install Stellarium 0.21.0
* Stellarium starts in full screen mode. Press F11 and watch the window disappear, but with `ps aux` we can see that the process is still alive in background.

### System
* Stellarium version: 0.21.0
* Operating system: openSUSE Tumbleweed
* Graphics Card: nVidia Quadro P600
* Screen type (if applicable): 1920x1080
* X11 (not using Wayland)

### Logfile 
[log.zip](https://github.com/Stellarium/stellarium/files/6397161/log.zip)

**Comment by gzotti** [comment]
Are other programs which use Qt5 and OpenGL running OK under GNOME 40.x? Have you reported this to GNOME?

**Comment by paolostivanin** [comment]
I tried `ksudoku` and `calibre` (they both use qt5+opengl) and they work fine.
If you know of any other software I could try, please let me know :)

BTW, no, I didn't report this to GNOME because I'm not sure whether it's a GNOME bug or not.

**Comment by alex-w** [comment]
First, Gnome use F11 to toggle fullscreen mode for gnome; second, F11 is well-known issue in gnome-shell. Please change F11 shortcut in the Gnome and try it again.

**Comment by paolostivanin** [comment]
The issue remains even when using the dedicated Stellarium button on the bottom bar

**Comment by chuchingkai** [comment]
It seems the window is minimized, press the fullscreen hotkey(F11) can bring back the disappeared window.

**Comment by yifanjiang** [comment]
The workaround is to set default "fullscreen" as "false" in /etc/.stellarium/config.ini. Then using F11 to switch back and forth.

**Comment by yifanjiang** [comment]
The workaround is to set default "fullscreen" as "false" in $HOME/.stellarium/config.ini. Then using F11 to switch back and forth.

**Comment by paolostivanin** [comment]
Thanks Yifan, the workaround works perfectly. I'll close this since the issue seems to be QT5 and/or GNOME related then.
