### ISSUE TITLE
sat plugin: connect sources to groups

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1636]
**Is your feature request related to a problem? Please describe.**

- The `stations` group seems to contain only one entry: ISS/Zarya; I expect CSS to be added to that group.
https://celestrak.com/NORAD/elements/stations.txt

**Describe the solution you'd like**
- as a user, I want to specify to which group(s) a source is to be linked (zero, one or more - this can be implemented in several phases).
- this should apply to **newly added** sats only, so that a sat that has been assigned (or maybe later reassigned manually) to a group remains in that group even if the linking changes or is removed.
- extension to the use case: include a button to update (add/remove) the group assignment of all sats of a selected source (a kind of batch operation)

**Describe alternatives you've considered**
## Workaround
Manually assign groups to specific sats - ie repeat this for each sat.

**Additional context**
![image](https://user-images.githubusercontent.com/3529789/116781275-2cdbba00-aa82-11eb-9650-0235b4e89fe4.png)

**Comment by alex-w** [comment]
Please do it yourself.

**Comment by axd1967** [comment]
good input. 

the user is free to (un)link a source to one or more groups, there is no need to automatically do that (ie derive the group  by somehow analysing the source name; this would lead to potential name clashes and possibly unreadable or meaningless names). I've updated the description as that was not clear.

(being able to assign to multiple groups might become obsolete when groups themselve can contain subgroups - in other words, a hierarchy of groups could be a possibility, although I do believe in **cyclic** (!!) directed graphs as an even more powerful means to organise sats.)

**Comment by alex-w** [comment]
Please do it yourself, again!

**Comment by axd1967** [comment]
> Please do it yourself, again!

@alex-w - ONCE MORE - please STOP this kind of comments. this is not helping anyone. it's not because I can write C++ that I have to indulge this kind of comments.

@Atque @gzotti @treaves

**Comment by alex-w** [comment]
Hello @axd1967! Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
