### ISSUE TITLE
meteor showers: include ANT (anthelion source)

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1637]
**Is your feature request related to a problem? Please describe.**
The ANT (Anthelion source) is often referred to as a broad, weak source of meteors (usually fewer than five per hour) located on the ecliptic some 15° east of the ASP.

**Describe the solution you'd like**
Option to toggle ANT display

**Additional context**

Regularly referred to in
- https://www.imo.net/members/imo_showers/working_shower_list
- https://meteorflux.org/rt#ANT
- http://adsabs.harvard.edu/full/2004JIMO...32...81L
- https://www.oxfordreference.com/view/10.1093/oi/authority.20110803095416116

**Comment by alex-w** [comment]
Note: the ANT hasn't peak date and the code of plugin should be changed to support this special case (computation the location of the radiant and displaying information about the meteor shower).
