### ISSUE TITLE
Feature request: identify Greek letters?

### ISSUE THREAD

**Issue by CarpeCimex** [Stellarium/stellarium#164]
I don't recognize many of the Greek letters Stellarium uses to identify stars, at least in the font being used.  Could you put the name in parens after the letter (e.g. "ρ (rho)") or provide a little lookup table window for them?

This is such a tiny nit though, in a stunning piece of software.  I am so delighted with Stellarium and grateful for all the developers' work!

**Comment by gzotti** [comment]
Astronomers are somehow expected to know Greek letters since 1603...

**Comment by alex-w** [comment]
Hint: press F3 and see tooltips

**Comment by CarpeCimex** [comment]
@gzotti - Well, we use a lot of them in electronic engineering too.  I can recognize most of them, but the font used in Stellarium throws me.
@alex-w - Thanks, that does it!  The tooltips didn't show up for me at first, but after F11 they did.  This is certainly workable.
