### ISSUE TITLE
Almagest sky culture is missing Russian translation of the description

### ISSUE THREAD

**Issue by abalkin** [Stellarium/stellarium#1645]
### Expected Behaviour

Expect sky culture description to be displayed in  Russian when Russian is selected as the program language.

### Actual Behaviour

![image](https://user-images.githubusercontent.com/535197/117516777-00370f00-af68-11eb-80ab-85414b647670.png)

### Steps to reproduce

1.  Press F2 to show the Configuration form and set Program Language to Русский. 
2. Press F4 to show the View (Вид) form and select the Starlore (Знания о звёздах) tab.
3. Select the second item on the left: Almagest (Альмагест).

### System
* Stellarium version: 0.21.0-df56370
* Operating system: Darwin 19.6.0 x86_64
* Graphics Card: Radeon Pro Vega 56

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/6444725/log.txt)

### Comment

The translation is available at [transifex](https://www.transifex.com/stellarium/stellarium/viewstrings/#ru/stellarium-skycultures-descriptions/319068811) and in the [po/stellarium-skycultures-descriptions/ru.po](https://github.com/Stellarium/stellarium/blob/0893f76aaca3c678d5728b7a23635758036bcd4b/po/stellarium-skycultures-descriptions/ru.po#L353) file but Stellarium is apparently looking for the `skycultures/almagest/description.ru.utf8` file which is missing.

**Comment by alex-w** [comment]
The translation is not complete yet ;)

**Comment by abalkin** [comment]
I actually started translating `skycultures/almagest/description.en.utf8`, but then discovered the .po file and the transifex section.  What can I do to help completing the translation?  Is there a forum where Russian translations are discussed?
