### ISSUE TITLE
Almagest sky culture is incomplete and inaccurate

### ISSUE THREAD

**Issue by abalkin** [Stellarium/stellarium#1646]
### Expected Behaviour
Almagest includes a very small (by modern standards) catalogue of stars (1022 stars assigned to 48 constellations).   It is expected that Ptolemy's descriptions for all 1022 stars be shown when Almagest culture is selected.

### Actual Behaviour
![image](https://user-images.githubusercontent.com/535197/117520248-46469f80-af75-11eb-87b4-aedec9223ea3.png)

### Steps to reproduce
Select Almagest sky culture and enable Labels and Markers in the View (F4) dialogue  with the slider brought all the way to the right.

### System
* Stellarium version: 0.21.0-df56370

### Inaccuracy

Coma Berenices (Com) is listed among Almagest constellations  as "πλόκαμος (Plokamos, in Leo)", but it is not one of the 48 Almagest  constellations.

**Comment by abalkin** [comment]
I have found a more recent collection of digitized versions of Ptolemy's catalog in [Ptolemy's Star Catalog](http://pbarbier.com/ptolemy/ptolemy.html) by Pierre Barbier.  The content there is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License which makes it usable as long as proper credit ifs given in the culture description.

**Comment by sushoff** [comment]
Concerning the **Inaccuracy** of Coma 
 
You are right, it is not a constellation but it is as one of the named asterisms within the constellation of Leo - similiar to the Pleiades in Taurus which are also labeled. I was/am not sure how to deal with it in the display: I mean, the stars have to be included, are listed in the star cat. and labeled as "Lock". 

In my scientific work, I draw polygones (convex hulls) around all stars of one constellation. This would make it clear but does not look as beautiful as the stick figures drawn by my students. O:-)

**Comment by alex-w** [comment]
> Concerning the **Inaccuracy** of Coma
> 
> You are right, it is not a constellation but it is as one of the named asterisms within the constellation of Leo - similiar to the Pleiades in Taurus which are also labeled. I was/am not sure how to deal with it in the display: the stars have to be included because they are listed in the star cat. and labeled as "Lock". That is why, we put "[in Leo]" behind it in order to designate them as part of the constellation of Leo.

But it can be defined as asterism

**Comment by sushoff** [comment]
yes, (I think it is), that's for the label 
but then, the stars do not appear connected to Leo and they should appear "somehow highlighted" (connected with lines)

**Comment by alex-w** [comment]
> yes, (I think it is), that's for the label
> but then, the stars do not appear connected to Leo and they should appear "somehow highlighted" (connected with lines)

Why? Please try show asterisms in Western skyculture.

**Comment by sushoff** [comment]
oh, the Alm. asterism file seems to be missing 
I know, I defined one ~2 yr ago - but possibly did not upload it (because I considered it redundant) - I will do so, THANK YOU for pointing me to the issue.

More interesting is the question on star catalogues that we discussed with Georg a while ago: 
It would be great if there was an option to highlight "the stars in the historical catalogue". 
**Example Story:** if the user selects "Almagest", then all stars that are listed in the cat. appear encircled in blue. 
In this case, we want to give the user the opportunity to select the identification (Grasshoff or Knobel or van Gent...) but anyway, this would solve the above-mentioned problem because then, the stars of the Lock would be encircled and it would be clear that they belong to the cat.

**Comment by alex-w** [comment]
> **Example Story:** if the user selects "Almagest", then all stars that are listed in the cat. appear encircled in blue.
> In this case, we want to give the user the opportunity to select the identification (Grasshoff or Knobel or van Gent...) but anyway, this would solve the above-mentioned problem because then, the stars of the Lock would be encircled and it would be clear that they belong to the cat.

This feature is not implemented yet.

**Comment by gzotti** [comment]
Yes, we have discussed this years ago: "User star lists". There are many ways to understand such feature, be it personal observing lists (now going into bookmarks), or special plugins like NavStars. However, a way to define lists in terms of HIP AND/OR coordinates (equatorial or ecliptical, with epoch, and shown with (optionally labelled) ring markers (like NavStars, but at the given catalog coordinates) and link lines to tentative HIP identifications is still a wish for the future. This could then be applied to all historical catalogs from Almagest, Sufi, various medieval Astrolabe star lists, Ulugh Beg, Tycho, ...

Such user star lists would be a feature (plugin) technically independent from the sky cultures, but could of course be displayed at the same time.

**Comment by sushoff** [comment]
so how do we solve this now? 
- [ ] I will search the files and upload the asterism-definition 
- [ ] I suggest for the moment it is sufficient that the Lock is designated as "Lock in Leo" 

Not so urgent but considered
- [ ] in principle it should not be difficult to define convex hulls summarizing all stars of a constellation and use the extant "geodetic line"-feature to connect them 
- [ ] and integrate the star list feature (?)

**Comment by gzotti** [comment]
For here and now, it should be sufficient to 
- add the asterism files to the almagest skyculture. This likely includes just Coma and Antinous. (or also Pleiades?)

Quite ambitious (overkill?) may be setting constellation borders in forms of your convex hulls. Technically, I don't know what "lies between" those constellations? Maybe define seamless borders instead (see older atlases like Bode, but note the difficult curved borders...). Make sure the "in-between formless(?) stars" listed in the Almagest are enclosed in those regions.

Star list feature: As said, future plugin (@alex-w when did we first discuss that? 2016 or so?). But please remain available :-)

**Comment by sushoff** [comment]
Bode dates ~1600 years later!
The convex hulls were made to show that there are gaps in between - they are not borders, borders never existed (no need).

**Comment by sushoff** [comment]
> * This likely includes just Coma and Antinous. (or also Pleiades?)

I will add Antinous, good idea... 

included were Hyades, Pleiades, Coma ... (it's on my list)

**Comment by gzotti** [comment]
I know Bode is much later, it's just my idea of "borders in historical maps". I don't know if Ptolemy had a concept of strict borders. I rather don't think so. (Some stars overlap.) The other question is of technical nature, whether Stellarium's border definition can be applied to "polygons with gaps". If the answer to one of the questions is "not really", then I think convex hull borders may not be required. Else, a sky partition is required that encloses each star in Ptolemy's list and identifies its association to its constellation. In some cases, convex hulls may then overlap, which causes ambiguities (e.g. Oph&neighbours?), so this is not really good IMHO. A partition scheme shaped like Delporte's may create a complete sky partition without gaps or overlaps, but it's likewise "out of its time". (There will be some "unmapped southern region".). 

Short: I think no borders required.

**Comment by sushoff** [comment]
as I said: No, Ptolemy did not have the concept of strict borders. That is why, I made convex hulls to summarize the coordinates-per-headline (equaling the stars-per-constellation). 

oh, sorry, I misunderstood that you meant the "border"-definition in Stellarium. I didn't check that. I was thinking of just defining something (mathematically) and I think, mathematically, it could be be different because I drew the lines in the hulls as geodetic lines and the IAU-borders are parallel to RA/DEC-lines - and DEC-circles are not great circles :-( 
Ok, then, you are right, this would be a bigger issue. 
However, there is the "angle measurement tool" that allows to draw geodetic lines. 

The convex hulls are the best possible way to display it because 
 * the ambiguity is intentional, some stars shall belong to more than one constellation
 * the gaps and ambiguities become obvious this way 
 * stick figures only connect the parts of a constellation figure, e.g. the hand with the arm ... but Ptolemy frequently lists "stars outside the constellation figure", most prominent case: Arktouros (the Guard) which does not belong to the stick figure of Boötes but does belong to the constellation

**Comment by abalkin** [comment]
Thanks all to your responses.  I would like to focus this issue on expanding the star_names.fab file in the Almagest sky culture.  I am not sure stick figures were something that astronomers in Ptolemy's Alexandria would draw.  I think those came from eastern sources.  (Happy to be proven wrong.). The problem with the convex hulls is that they clearly intersect and we probably want constellations to be defined as non-intersecting regions.

**Comment by gzotti** [comment]
The technical implementation of borders (which are only needed to resolve ambiguities in correlating stars to constellations) in Stellarium do not allow overlaps. So, either a border style that splits the sky in non-overlapping regions, or no border definition. 

Yes, the point about Arcturus is funny. All (?) 20th-century stick figure atlases include Arcturus as "obvious" component within the figure. Good to point out Ptolemy sees it differently...

**Comment by abalkin** [comment]
@gzotti > (Some stars overlap.)

Looking at Ernie Wright's rendering of Toomer, I see 3 overlaps:

1.  {Aur 11} = {Tau 21} = [112 bet Tau]
2.  {Boo 9} = {Her 29} = [52 nu1 Boo]
3.  {Aqr 42} = {PsA 1} = [24 alp PsA]

In all three cases, the descriptions confirm that the overlap is intentional.  Thus {Aur 11} is described as "The star on the right ankle, which is [applied in] common to the horn [of Taurus, 400 Tau 21]" and {Tau 21} in turn is described as "The star on the tip of the northern horn, which is the same as the one on the right foot of Auriga [230 Aur 11]".  Similarly, {Her 29} is described as "The star on the end of the right leg is the same as the one on the tip of the staff [of Bootes, 96 Boo 9]" and {PsA 1} as "The star in the mouth, which is the same as the beginning of the water [670 Aqr 42]".

While I see how these ambiguities can make it difficult to define constellation boundaries, we can easily come up with combined descriptions such as "The star in the mouth, which is the same as the beginning of the water" and put that in the star_names.fab file.

The only technical difficulty that I see is that long descriptions may easily overlap and/or run out of screen if they are displayed for too many stars, but this can be addressed after completing  the star_names.fab file.

@sushoff >  It would be great to have the possibility to choose the model (the set of identifications: by Toomer/ Grasshoff/ Knobel...). 

I disagree.  I think it is more important to provide one complete set of Ptolomeyan descriptions than to confuse users with multiple closely related cultures.

**Comment by abalkin** [comment]
> Yes, the point about Arcturus is funny. All (?) 20th-century stick figure atlases include Arcturus as "obvious" component within the figure. Good to point out Ptolemy sees it differently...

@gzotti - I think the western culture shows Arturus closer to Ptolemey's description, "The star between the thighs, called 'Arcturus', reddish"

![image](https://user-images.githubusercontent.com/535197/117554738-85cdc400-b027-11eb-9b5a-b695599170a9.png)



than does "Almagest" culture:

![image](https://user-images.githubusercontent.com/535197/117554653-0b9d3f80-b027-11eb-9bc1-2498d167ff93.png)

**Comment by gzotti** [comment]
Hm? Why? The "Western" stick figure includes it (as is common in 20th century atlases), the "Almagest" stick figure does not.

**Comment by abalkin** [comment]
I pushed a python script in gh-1647 to generate new star_names.fab together with the generated file.

I used the existing `stars/default/cross-id.dat` to translate from HR to HIP numbers and got the following errors:

```
$ python3.9 make_star_names.py > star_names.fab
No HIP number found for HR 8417 (17 xi Cep)
No HIP number found for HR 5506 (36 eps Boo)
No HIP number found for HR 5478 (30 zet Boo)
No HIP number found for HR 7417 (6 bet1 Cyg)
No HIP number found for HR 7751 (32 Cyg)
No HIP number found for HR 0 (NGC 869/884)
No HIP number found for HR 854 (18 tau Per)
No HIP number found for HR 6733 (69 tau Oph)
No HIP number found for HR 8131 (8 alp Equ)
No HIP number found for HR 888 (48 eps Ari)
No HIP number found for HR 2891 (66 alp Gem)
No HIP number found for HR 0 (GC 2632 M44)
No HIP number found for HR 5978 (xi Sco)
No HIP number found for HR 7776 (9 bet Cap)
No HIP number found for HR 8817 (89 Aqr)
No HIP number found for HR 0 (NGC 5139)
No HIP number found for HR 5605 (pi Lup)
```

Three errors for HR 0 are expected - the are three nebulae that should probably be translated manually.

The rest may indicate mistakes in the `cross-id.dat` – I did not have time to look closer.

**Comment by sushoff** [comment]
> @sushoff > It would be great to have the possibility to choose the model (the set of identifications: by Toomer/ Grasshoff/ Knobel...).
> 
> I disagree. I think it is more important to provide one complete set of Ptolomeyan descriptions than to confuse users with multiple closely related cultures.

No! Most of the standard users won't be interested in these details and will probably never change the sky culture. THose who do, are highly likely interested in these details because they are either historians (of science) or philologists or archaeologists or any other type of researcher.

**Comment by gzotti** [comment]
> I am not sure what your "why?" is asking. 

I am talking of the stick figures only. All 20th century stick figures I know (also the Rey style, although very different) show Bootes in prominent position within the stick figure. You said the default "Western" SC was closer to Ptolemy than the "Almagest" SC, which I cannot follow.

As said, we still need the "custom star lists" plugin mentioned above for "scientific" users. This topic is beyond skycultures, although may overlap as in this case. Else we need 3 Almagest SCs: Almagest/Toomer, Almagest/Knobel, Almagest/Manitius. But this is overkill for the casual user. And there are dozens of historical atlases/catalogs... For this one, the documentation should clarify source materials and probable diverging interpretations.

**Comment by abalkin** [comment]
> You said the default "Western" SC was closer to Ptolemy than the "Almagest" SC, which I cannot follow.

@gzotti  -You may be right.  On the second look neither Western nor Almagest stick figures matches the description "between the thighs".  The Western figure places Arcturus too high (between the hips rather than thighs) while current Almagest figure has it below knees, almost between the heels.

**Comment by abalkin** [comment]
> It would be great to have the possibility to choose the model (the set of identifications: by Toomer/ Grasshoff/ Knobel...). 

The main difference between these sources is the language of translation, so I think it is best to use them to provide i18n strings.  Unfortunately there are still ambiguities in identification.  In almstars files there are 54 (5%)  differences in Almagest to HR mappings between Toomer and Knobel and 114 (10%)  between Knobel and Manitius.  In those cases, I don't think there is any value in preserving multiple mappings.  We should take a mapping that we believe is best and treat the remaining sources purely as alternative translations of Ptolemey's descriptions.

On the other hand, I don't know neither German (Manitius) nor Latin ( Knobel), so I will only be able to contribute translations that I can generate by exact match.

Alternatively, we can assume that the order of descriptions is the same in all translations and generate translations without using identification info.

**Comment by abalkin** [comment]
@sushoff , @alex-w - please take a look at my latest commit in #1647 (1874eb6bece990532bde7030160056c9f067e344).  It makes Almagest more consistent with al-Sufi culture and solves the problem with displaying long descriptions.

![image](https://user-images.githubusercontent.com/535197/117983433-f107e680-b304-11eb-8b35-d5521da4432c.png)

Note that unlike what is done in al-Sufi, I use space rather than underscore to form short star names.  To my taste it looks better because `_` in names feels like a programming artifact rather than a user–friendly name.

**Comment by sushoff** [comment]
I don't have a clear opinion yet. What I don't like of the designators "UMi n" with n Natural Number is its similarity to Chinese star names - which we do not at all want to imply. In China (and its derivatives in Japan, Korea, Vietnam), most stars only have a number and not a name - so such a designator is wanted and there is no alternative. In the other cultures, this is not the case and we do not want to imply it. That makes me sceptical concerning this particular performance of the idea of abbreviations although the idea as such is, of course, good.

**Comment by abalkin** [comment]
@sushoff - I am not sure what you concern about Chinese culture is.  Here is how Polaris and it's vicinity displayed in Stellarium when Chinese culture is chosen:

![image](https://user-images.githubusercontent.com/535197/117989442-527e8400-b30a-11eb-8869-d69f36b317e2.png)

**Comment by sushoff** [comment]
> @sushoff - I am not sure what you concern about Chinese culture is. Here is how Polaris and its vicinity displayed in Stellarium when Chinese culture is chosen:
> 
> ![image](https://user-images.githubusercontent.com/535197/117989442-527e8400-b30a-11eb-8869-d69f36b317e2.png)

nothing - I only worry on possible misinterpretations of your abbreviations by the user

**Comment by sushoff** [comment]
@alex-w Why are all the Con_n labels in the translation tasks? that's not necessary - the label based on the IAU-names is already international and there is no need for translation. Could you please remove it!?

**Comment by gzotti** [comment]
@sushoff that's a technical requirement. Star names are translatable, but we cannot currently identify IAU abbreviations. We discussed "untranslatable names", but somebody wanted to allow transliteration. For German, I can just quick-copy these labels.

**Comment by gzotti** [comment]
Seeing the current list of "unreviewed" entries I wonder how many obvious and completely useless misspellings of star names should we include? We don't need "all possible lists" but "qualified lists". Can we just delete entries like Scalovin (recte: Svalocin), Rotanen (recte: Rotanev), Asellus Secondus (recte: A. Secundus)? And why are there Italian spellings of the usual names in the Western star names (Sirio, Polare, Procione, ...)? These are completely useless. Italian translators will apply them to Sirius/Polaris/Procyon etc.

**Comment by sushoff** [comment]
I thought exactly the same!

**Comment by alex-w** [comment]
OK, done
