### ISSUE TITLE
Stellarium 0.18 64bit on WIn-10 missing menus!

### ISSUE THREAD

**Issue by aqking** [Stellarium/stellarium#165]
I just upgraded from S-0.16 to S-0.18 and now when moving cursor to bottom or theLHS, the menu items are not displayed.
They are there, as a "title" pos up to let me know what the item is. 
And when I click on the item, it seems to open the window, but it is hidden behind the main screen.
This appear to be some Z-axis problem.
And it happens both in full screen, and when F11 is pressed.

**Comment by alex-w** [comment]
Please show log from Stellarium

**Comment by gzotti** [comment]
Read the FAQ and run ANGLE mode or install OpenGL drivers.

**Comment by gzotti** [comment]
@aqking did that solve your issue?

**Comment by aqking** [comment]
Yes- I finally figured how to do the  -a option.
Will look for Intel's OpenGL eventually.
Thanx.
