### ISSUE TITLE
Version 0.21.0 won't read my version 0.20.1 telescopes.json file

### ISSUE THREAD

**Issue by dlwmacgregor** [Stellarium/stellarium#1651]
-->

### Expected Behaviour
Telescopes Plug-in file should open. Created with v0.20.1.

### Actual Behaviour
Blank telescopes window opens - no entries.

### System
* Stellarium version: <Name of downloaded installable file?> 0.21.0
* Operating system: <Name, version number> Windows 10 v2004 OS Build 19041.928
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by axd1967** [comment]
@dlwmacgregor it's very important that you attach your v0.20.1 telescope.json file , otherwise we can't help.

**Comment by dlwmacgregor** [comment]
I apologize.
I've never submitted a bug report before and I tried to follow the instruction as closely as possible.

Please find the attached telescope.json file I have been using since May 2020 when I first got my Celestron Nexstar SE8.
Updates from 0.20.1 to 0.20.4 have worked without problems.
0.21.0 is the problem wrt the telescopes.json file.

Regards

Doug
Ottawa Canada


----- Original Message -----
From: alex ***@***.***>
Reply-To: Stellarium/stellarium ***@***.***>
To: Stellarium/stellarium ***@***.***>
Cc: dlwmacgregor ***@***.***>, Mention ***@***.***>
Sent: 5/8/2021 3:55:42 PM
Subject: Re: [Stellarium/stellarium] Version 0.21.0 won't 
read my version 0.20.1 telescopes.json file (#1651)



@dlwmacgregor 
it's very important that you attach your v0.20.1 telescope.json file , otherwise we can't 
help.

**Comment by alex-w** [comment]
Version of plugin was changed in release 0.21.0 - you may open telescope.json file in text editor and edit the version.

**Comment by dlwmacgregor** [comment]
Just to be clear, you are saying that if I open the telescopes.json file with, say, Notepad++ and change the version number at the bottom of the file from the current 0.4.0 to the new version (?) the current version of Stellarium will see it?
Why is this necessary.
Respectfully, couldn't the latest version somehow read the old version and make the change? I've never had to manually change config files when upgrading other apps.
Thanks.

**Comment by alex-w** [comment]
Telescope Control plugin has version 0.4.1 in the latest release of planetarium.

**Comment by dlwmacgregor** [comment]
[log.txt](https://github.com/Stellarium/stellarium/files/6446591/log.txt)

**Comment by dlwmacgregor** [comment]
OK.
I reinstalled 0.21.0 after editing the telescopes.json file. I  changed the version at the bottom of the file to 0.4.1.
My telescope entries not show up as normal.
Many thanks.
Was this an oversight?
[log.txt](https://github.com/Stellarium/stellarium/files/6446601/log.txt)

**Comment by axd1967** [comment]
Editing the JSON file is seldom a good idea, especially by a user. Stellarium is supposed to automatically upgrade the file if needed, so if this went wrong, then this is an issue that needs to be corrected.

(By the way, you didn't attach the `telescope.json` file, but the log file).

Here also, a remark similar to https://github.com/Stellarium/stellarium/issues/1022#issuecomment-687677480: whenever Stellarium needs to (automatically) upgrade a config file, the previous version of the file should always be kept by adding a date/time stamp in the file name (and optionally by adding some kind of comment or rather a dummy JSON field that indicates that the file has been replaced by a new version). this will create a set of previous versions of a config file that are always available when necessary. Normally only a few of those files should remain around, it is up to the user to clean up old files from time to time. A **workaround** is for the user to regularly make backups of the Stellarium config directory (Git is a good way for this).

**Comment by dlwmacgregor** [comment]
Alex.

I have no wish to edit any config or other such files. 
It's complicated enough for me to try and understand all the complexities of this new - or should I say rediscovered hobby.
Even being a retired programmer/network administrator, I have my hands full figuring out the telescope, various software, first exposure to the Raspberry Pi and it's 
software.
I'm surprised I have managed to get this far in only a few months. But I'm 
learning and eager to do so.

Stellarium is a fabulous application and 
it's people like you who make it all possible.

I like the idea of making backup copies of the Stellarium Config folder(s) and will now do this as a rule for all updates.

I tried using Git last summer for the drivers for the (at that time) newly released SVBony SV305 camera.
I spent 5 weeks trying to compile all the various files but never could get a viable driver so I just downloaded AstroDMX instead with the driver included.

A man's 
got to know his limitations. I just wanted to get on with it and not get bogged 
down in the weeds.

I greatly appreciate your help in this and 
I've learned in the process.
Thanks again.

Cheers

Doug
Ottawa




----- Original Message -----
From: alex ***@***.***>
Reply-To: Stellarium/stellarium ***@***.***>
To: Stellarium/stellarium ***@***.***>
Cc: dlwmacgregor ***@***.***>, Mention ***@***.***>
Sent: 5/8/2021 7:02:44 PM
Subject: Re: [Stellarium/stellarium] Version 0.21.0 won't 
read my version 0.20.1 telescopes.json file (#1651)



Editing the JSON file is seldom a good idea, especially by a user. Stellarium 
is supposed to automatically upgrade the file if needed, so if this went wrong, 
then this is an issue that needs to be corrected.
(By the way, you didn't attach the telescope.json file, but the log file).
Here also, a remark similar to #1022 (comment): whenever Stellarium needs to (automatically) upgrade a config file, the previous version of the file should always be kept by adding a date/time stamp in the file name (and optionally by adding some kind of comment or rather a dummy JSON field that indicates that the file has been replaced by a new version). this will create a set of previous versions of a config file that are always available when necessary. Normally only a few of those files should remain around, it is up to the user to clean up old files from time to time. A workaround is for the user to regularly make backups of the Stellarium config directory (Git is a good way for this).

**Comment by dlwmacgregor** [comment]
btw I attached the telkescope.json file to my first reply to you via e-mail and 
I just did it again.

Doug







----- Original Message -----
From: alex ***@***.***>
Reply-To: Stellarium/stellarium 
***@***.***>
To: Stellarium/stellarium ***@***.***>
Cc: dlwmacgregor ***@***.***>, Mention ***@***.***>
Sent: 5/8/2021 7:02:44 PM
Subject: Re: [Stellarium/stellarium] Version 0.21.0 
won't read my version 0.20.1 telescopes.json file (#1651)



Editing the JSON file is seldom a good idea, especially by a user. Stellarium is supposed to automatically upgrade the file if needed, so if this went wrong, then this is an issue that needs to be corrected.
(By the way, you didn't 
attach the telescope.json file, but the log file).
Here also, a remark similar to #1022 (comment): whenever Stellarium needs to 
(automatically) upgrade a config file, the previous version of the file should 
always be kept by adding a date/time stamp in the file name (and optionally by 
adding some kind of comment or rather a dummy JSON field that indicates that 
the file has been replaced by a new version). this will create a set of 
previous versions of a config file that are always available when necessary. 
Normally only a few of those files should remain around, it is up to the user 
to clean up old files from time to time. A workaround is for the user to 
regularly make backups of the Stellarium config directory (Git is a good way 
for this).

**Comment by axd1967** [comment]
hello @dlwmacgregor the issue is closed, that is fine, but I would like to help you a bit here.

Just for getting used to the GitHub interface: you might maybe not be aware that reacting via email is not always ideal ; in fact you should be reacting via this link:  https://github.com/Stellarium/stellarium/issues/1651#

![image](https://user-images.githubusercontent.com/3529789/117574102-cedf5000-b0db-11eb-9c53-a409de0c57f7.png)


that will allow you to attach a file in the issue. you will also discover that your `telescope.ini` file is not to be seen anywhere in the issue, take a look.

just as an example, I attached such a file in this comment. you will discover that `.json` files are rejected by GitHub, so you should first copy it somewhere and add `.txt` to the filename.

[telescopes.json.txt](https://github.com/Stellarium/stellarium/files/6447607/telescopes.json.txt)

(welcome to GitHub :-) )

-alex-

**Comment by dlwmacgregor** [comment]
Thanks Alex. I was not aware of that.
Good tip about .json files.
I am attaching the current telescopes.json file here as a .txt file.
I did attach a screen grab of it earlier.
Did you want a copy of my telescope.ini file?
[telescopes.txt](https://github.com/Stellarium/stellarium/files/6447640/telescopes.txt)

**Comment by axd1967** [comment]
> Thanks Alex. I was not aware of that.
> Good tip about .json files.
> I am attaching the current telescopes.json file here as a .txt file.
> I did attach a screen grab of it earlier.
> Did you want a copy of my telescope.ini file?
> [telescopes.json.txt](https://github.com/Stellarium/stellarium/files/6447643/telescopes.json.txt)

Good! Now we can see it.

I see what you mean by screen grab - avoid that when sharing text files, it's not easy to work with by the developers.

The issue has been dealt with,  as you can see, it shows "Closed":

![image](https://user-images.githubusercontent.com/3529789/117574957-03eda180-b0e0-11eb-8a20-39cf543b1f8c.png)

**Comment by dlwmacgregor** [comment]
OK. Understood.
I'll get the hang of it.

**Comment by dlwmacgregor** [comment]
You are welcome.
Thanks for the support and a great app.

**Comment by dlwmacgregor** [comment]
Thanks!
Looks good.
