### ISSUE TITLE
Non-extincion affected star labels

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1652]
I'm not sure if this is a bug or a feature.

Star labels are affected by extinction. This means that Sirius close to the horizon might not show a label, while a 3rd magnitude star at zenith might do. I think this is undesirable. Planets show labels regardless of extincion. It would be better if stars also did, in my opinion.

**Comment by alex-w** [comment]
Well, all celestial objects in the Stellarium use magnitude with extinction to compute visibility labels, so, I changed behavior for Solar system bodies as identical to all others.

@gzotti?

**Comment by gzotti** [comment]
No matter what, all objects should behave equal in this respect. Thanks @Atque for noticing. 
@alex-w Your commit either solved a bug and we can close this, or do you want to let it flagged as dissenting "opinion" that all object labels should depend on non-extinction magnitude? IMHO it can be closed.
