### ISSUE TITLE
Need version 0.9.1 of Stellarium

### ISSUE THREAD

**Issue by Hondoe1950** [Stellarium/stellarium#1653]
Hi! I have a program that links to Stellarium 0.9.1 and won't work with any subsequent versions.

Does anyone have a copy of this version that I can have?

I would really appreciate it.

**Comment by gzotti** [comment]
Errm, why not use the search engine of your preference?

**Comment by Hondoe1950** [comment]
> Errm, why not use the search engine of your preference?

I have used Google and spent over 40 minutes trying to find version 0.9.1 to no avail. Every link eventually pointed me to the current version
