### ISSUE TITLE
Stars missing from cross-id.dat file

### ISSUE THREAD

**Issue by abalkin** [Stellarium/stellarium#1657]
While working on issue #1646, I discovered that the following stars cannot be found in the `cross-id.dat` file by their HD numbers:

```
No HIP number found for HR 8417 (17 xi Cep)
No HIP number found for HR 5506 (36 eps Boo)
No HIP number found for HR 5478 (30 zet Boo)
No HIP number found for HR 7417 (6 bet1 Cyg)
No HIP number found for HR 7751 (32 Cyg)
No HIP number found for HR 854 (18 tau Per)
No HIP number found for HR 6733 (69 tau Oph)
No HIP number found for HR 8131 (8 alp Equ)
No HIP number found for HR 888 (48 eps Ari)
No HIP number found for HR 2891 (66 alp Gem)
No HIP number found for HR 5978 (xi Sco)
No HIP number found for HR 7776 (9 bet Cap)
No HIP number found for HR 8817 (89 Aqr)
No HIP number found for HR 5605 (pi Lup)
``` 
### System
* Stellarium version: 0.21.0-3cfc10f

**Comment by abalkin** [comment]
Apparently, there are many more BSC stars that are missing from the `cross-id.dat` file.  According to my count, there are 9006 unique entries in the HR column of the file:

```
$ tail -n +2 cross-id.dat| cut -f 5 | egrep -v '^$' | sort | uniq | wc -l
    9006
```

(The total number of entries is 9040 and the duplicates may or may not indicate mistakes - possibly some double stars have two HIP numbers fro one HR.)

According to [BSC ReadMe](http://cdsarc.u-strasbg.fr/ftp/V/50/ReadMe), there are 9110 objects in BSC,  of  which  9096 are stars:

```
   The  BSC  contains  9110  objects,  of  which  9096 are stars (14
    objects catalogued in the original compilation of 1908 are  novae
    or  extragalactic objects that have been retained to preserve the
    numbering, but most of their data are omitted), while the remarks
    section is slightly larger than the main catalog. 
```

This suggests that there  are 9096 - 9006 = 90 "bright" stars missing from  the `cross-id.dat` file.  (I say "maybe" for the unlikely case that a BSC star is legitimately missing from the Hipparcos Catalogue.

**Comment by alex-w** [comment]
In the cross-id.dat file 9021 stars has HR identifier now. Probably HR designations for many double stars are missing :(

**Comment by abalkin** [comment]
> In the cross-id.dat file 9021 stars has HR identifier now. 

Confirmed.  I can now process almstars cat1 catalogue with no warnings.   On the other hand, I don't think manually maintaining this file is a good use on anyone's time.  There must be an at least semi-automatic way to generate cross-catalogue id translations from publicly available databases.

**Comment by alex-w** [comment]
Right now:
```
$ tail -n +2 cross-id.dat| cut -f 5 | egrep -v '^$' | sort | uniq | wc -l
9072
```
