### ISSUE TITLE
Set the time?

### ISSUE THREAD

**Issue by MichaelKauper** [Stellarium/stellarium#166]
I cannot set the time with the time/date window.   We can set the date but not the time.  Windows 10, ASUS Republic of Gaming laptop.

Everything else works well.  Several people have looked at it with me.  None of us can set the time in Stellarium 0.18.0.  HELP!

Before reporting an issue around graphics artifacts like missing menu buttons, strange colors, Moon not rendered, or similar, 
*please make absolutely sure* you are running the latest graphics drivers for your graphics card. 
95% of graphics problems are solved this way.

Before reporting an issue, please *absolutely make sure* to check the closed issues 
(https://github.com/Stellarium/stellarium/issues?q=is%3Aissue+is%3Aclosed) 
whether it has been reported and solved/closed already! Don't report in this case.

Also look into the wiki (https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version 
and https://github.com/Stellarium/stellarium/wiki/FAQ) 
and check if you are attempting to report a known issue. Don't report in this case.

Also look into the User Guide before reporting unexpected but correct behaviour. Don't report in this case.

If you want to report a feature wish, delete these template lines above and below, and fill in. 

If you want to report a bug, please make sure to update and verify the bug still exists in the current version. 
In this case please also check current beta builds from http://stellarium.org
If bug still persists, delete text above down to and including this line and fill in:

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Why do you think the questionnaire contains a point "Steps to reproduce?" It works on 10 systems in my reach.

What have you tried so far? Have you read the Guide, section 4.1?

**Comment by gzotti** [comment]
@MichaelKauper any answer?

**Comment by gzotti** [comment]
Closing after a month of silence.
