### ISSUE TITLE
separate color for bright nova plugin

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1667]
**Is your feature request related to a problem? Please describe.**

I was happily surprised to discover the recent V1405 Cas (= Nova Cas 2021) in Stellarium and was puzzled as to what had imported this object; it looks like it is the "Bright Nova" plugin. So I wondered what more fresh data did this plugin dynamically add to Stellarium.

![image](https://user-images.githubusercontent.com/3529789/118269422-01fc5780-b4bf-11eb-801f-53c6d62bb4f8.png)

**Describe the solution you'd like**
Some way to easily find such objects

- add a color option in the plugin dialog, to highlight all objects  (symbol and/or label)?
- add a filter in the View > DSO page? (eg a separate pane "Plugins" , checkbox "Bright Nova "?)
- maybe add the plugin's objects as a category in WUT?

Additionally, 
- the plugin should explain from where the updates come (eg in the About, or in the User Guide (v 0.21), page 131)

**Describe alternatives you've considered**

**Additional context**
(https://www.astronomerstelegram.org/?read=14622)

**Comment by alex-w** [comment]
> * add a color option in the plugin dialog, to highlight all objects  (symbol and/or label)?

Not a highlighting, but the list of bright novae can be found in the Search Tool and About tab (including date of maximum brightness).

> * add a filter in the View > DSO page? (eg a separate pane "Plugins" , checkbox "Bright Nova "?)

Already implemented many years ago - to disable showing novae just disable plugin 'bright novae"

> * maybe add the plugin's objects as a category in WUT?

Already implemented 

> * the plugin should explain from where the updates come (eg in the About, or in the User Guide (v 0.21), page 131)

Various sources

**Comment by axd1967** [comment]
thanks.

> > * add a color option in the plugin dialog, to highlight all objects  (symbol and/or label)?
> 
> Not a highlighting, but the list of bright novae can be found in the Search Tool and About tab (including date of maximum brightness).

OK! but this is a difficult workaround.

also, notice that other objects can be colored:
![image](https://user-images.githubusercontent.com/3529789/118359659-c7f58900-b584-11eb-8977-b5383ad2150e.png)

> 
> > * add a filter in the View > DSO page? (eg a separate pane "Plugins" , checkbox "Bright Nova "?)
> 
> Already implemented many years ago - to disable showing novae just disable plugin 'bright novae"
(note: I want to see ONLY novae)

yes, but it is difficult to use: 
1. one has to disable all other objects, which is rather tedious:
![image](https://user-images.githubusercontent.com/3529789/118361276-f5ddcc00-b58a-11eb-8a28-28e2ddc31325.png)

2. the objects are still not visible at large scale, even when magnitude and angular limits have been disabled:


compare ...

![image](https://user-images.githubusercontent.com/3529789/118361167-5b7d8880-b58a-11eb-8f48-11cd9300438d.png)

... to the result of normal DSO display/filtering:

![image](https://user-images.githubusercontent.com/3529789/118361200-836cec00-b58a-11eb-9cd7-666ca69fa56e.png)


> > * maybe add the plugin's objects as a category in WUT?
> 
> Already implemented

correct, sorry
![image](https://user-images.githubusercontent.com/3529789/118359719-1571f600-b585-11eb-93ba-1f0a967bcce7.png)

> > * the plugin should explain from where the updates come (eg in the About, or in the User Guide (v 0.21), page 131)
> 
> Various sources

so it seems the data comes from https://stellarium.org/json/novae.json

https://github.com/Stellarium/stellarium/blob/581b2660490f4d78afee9f3564182c9608b3c849/plugins/Novae/src/Novae.cpp#L542-L551

_(DRY: the URL should be moved into a constant)_

It looks like this is a manual process? Is it possible to document how (and how often) this data is updated?

**Comment by axd1967** [comment]
> We have a reason not to do it at the moment, but maybe in future we will back to this proposal or someone can implement it and propose pull request with solution! Some reasons for it in the FAQ:
> https://github.com/Stellarium/stellarium/wiki/FAQ#Why_dont_you_implement

we can partially agree here. 

because as this is not unfeasible or unrealistic, please consider attaching the label "wishlist" then? so future devs can easily find it back?

thanks.

**Comment by alex-w** [comment]
> > Not a highlighting, but the list of bright novae can be found in the Search Tool and About tab (including date of maximum brightness).
> 
> OK! but this is a difficult workaround.
> 
> also, notice that other objects can be colored:
> ![image](https://user-images.githubusercontent.com/3529789/118359659-c7f58900-b584-11eb-8977-b5383ad2150e.png)

Seriously, do you do not see difference between star and galaxy or nebula? We won't replace stars by markers.

**Comment by axd1967** [comment]
> Seriously, do you do not see difference between star and galaxy or nebula? We won't replace stars by markers.

I miss a way to discover the contributions of the plugin in a _graphical_ way, similar to the markers used for DSO objects.

but a reasonable workaround is `WUT > Bright nova stars`.
