### ISSUE TITLE
Crash when any device added into Oculars plugin

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1673]
### Expected Behaviour
Adding the devices (eyepieces, lenses, telescopes, CCDs) into list of devices

### Actual Behaviour
When user press button "Add" in the Oculars plugin the planetarium is crashes.

### Steps to reproduce
1. Open Oculars plugin config dialog
2. Open any tab for devices (eyepice, lens, CCD, telescope)
3. Press "Add" button

### System
* Stellarium version: 0.21.0-b0c26ce
* Operating system: Ubuntu Linux 20.04
* Graphics Card: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2, driver 460
* Screen type (if applicable): 1920x1080

**Comment by treaves** [comment]
This should be fixed in the latest PR; this is an odd case, as I think the actual defect is in the Qt meta system.  For some reason the constructors of the model objects were not found.  I updated the code and got it to work.  But I'm not happy with it.
