### ISSUE TITLE
The atmosphere is turned on by default on the Galilean satellites

### ISSUE THREAD

**Issue by Ironman65** [Stellarium/stellarium#1676]
I noticed when you go to the surfaces of the four Galilean satellites Io, Europa, Ganymede and Callisto the atmosphere is turn on by default. Which I guess should be turned off by default. OS WINDOWS 10 32 bit.

**Comment by alex-w** [comment]
All Galilean satellites has atmosphere, but too thin of course (pressure at surface lesser 1 Pa).
