### ISSUE TITLE
oculars: switching out of ocular mode loses tracking

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1680]
### Expected Behaviour
Tracking is maintained irrespective of ocular mode

### Actual Behaviour
Tracking lost when leaving ocular mode

### Steps to reproduce

1. select an object
2. track the object (SPACEBAR)
2. activate ocular mode  (ctrl-O)
3. observe that ocular mode keeps tracking the object
4. leave ocular mode (ctrl-O)

bug: tracking is lost, even though object is still selected

### System
* Stellarium version: 0.21.0
* Operating system: KUbuntu 18

**Comment by alex-w** [comment]
This is standard behavior for this plugin

**Comment by axd1967** [comment]
> This is standard behavior for this plugin

Sure! But if we follow that logic, all plugins already have a standard behaviour and therefore need no more improvement...

**Comment by axd1967** [comment]
fixed, thank you!
