### ISSUE TITLE
Oculars: artefacts in the GUI where font size is changed

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1685]
Hmm, all right, I can reproduce the issue where fonts behave strangely. When scrolling through fonts, the panel at the upper right becomes weird. See the screenshot below:
![stellarium-095](https://user-images.githubusercontent.com/37028368/119251224-d60b6100-bba5-11eb-8654-a8bc8659a5bc.png)

Furthermore, the compass markings are inverted; in the sky, west is to the right, and east to the left, when viewing from the northern hemisphere.

_Originally posted by @Atque in https://github.com/Stellarium/stellarium/issues/1535#issuecomment-846515393_

**Comment by alex-w** [comment]
The bug is related to code, which was moved into branch https://github.com/Stellarium/stellarium/tree/oculars-ng

The bug report is closed at the moment due to the reason above.

**Comment by axd1967** [comment]
fixed, thank you!
