### ISSUE TITLE
Dead links in Stellarium user guide

### ISSUE THREAD

**Issue by abalkin** [Stellarium/stellarium#1694]
I came across a few dead links in User Gude version 0.20.4:

* Page 301, Fn. 3 - http://ad.usno.navy.mil/wds/
* Page 137, Fn. 17 - http://lasp.colorado.edu/~bagenal/3720/CLASS6/6EquilibriumTemp.html
* Page 95, Fn. 14 - https://github.com/Stellarium/stellarium-data/adding-nebula-images

**Comment by gzotti** [comment]
Thanks!

**Comment by axd1967** [comment]
Yes :-) Those are http/https issues; I had begun to run over all the links and check them; there are several 404, some (permanent) redirects etc. Some of these originate in files that are not fully under Stellarium control

[result.txt](https://github.com/Stellarium/stellarium/files/6556303/result.txt)

**Comment by gzotti** [comment]
I had the impression last year that USNO links were banned for non-US access. I still cannot connect. Not sure how that evolves.

**Comment by axd1967** [comment]
I can confirm that they are working on their website. _Maybe_ external access might be denied, but I doubt it.
