### ISSUE TITLE
Screen goes black for a while

### ISSUE THREAD

**Issue by hermmensch** [Stellarium/stellarium#1712]
[Screen goes black for a while.docx](https://github.com/Stellarium/stellarium/files/6585363/Screen.goes.black.for.a.while.docx)

**Comment by alex-w** [comment]
I see Intel® HD Graphics 630 in the file and it happens in full screen mode. Please try use ANGLE mode.

**Comment by hermmensch** [comment]
Stellarium started in ANGEL mode. Problem solved. Thanks
