### ISSUE TITLE
Stellarium v0.20.2, v0.20.3, v0.20.4 and v0.21.0 not working in Windows 10

### ISSUE THREAD

**Issue by phileefan** [Stellarium/stellarium#1715]
When trying to install versions v0.20.2, v0.20.3, v0.20.4 and v0.21.0 on my Acer Windows 10 laptop, they do not open. There is an icon in the taskbar but nothing will open. Plus my entire desktop is locked up, not allowing me to do anything. Once I hit the Windows key it then allows me to close out the instance of Stellarium and unlocks my desktop. 

I can open v0.20.1 and all versions before this one. I don't know if this matters or not but the screenshot below comes up when installing v0.20.1 and all versions before BUT does not come up in versions v0.20.2, v0.20.3, v0.20.4 and v0.21.0. Also below is the log file from v0.21.0 install attempt. Hopefully this helps. Thanks........

![Stellarium 0 20 1 Install](https://user-images.githubusercontent.com/85319129/120793352-ca545e80-c504-11eb-8988-262adac9c85f.jpg)

[Stellarium 0.21.0 log.txt](https://github.com/Stellarium/stellarium/files/6598065/Stellarium.0.21.0.log.txt)

**Comment by alex-w** [comment]
Please try ANGLE mode.

**Comment by phileefan** [comment]
alex-w,

Thank you very much, that did the trick! I checked my other Windows 10 machine with the same updates and this is not an issue. What do you believe is casing this? Just curious..................

**Comment by gzotti** [comment]
If we only knew... Ask Nvidia. Our MFAQ deals with graphics issues. I am just surprised your Geforce also acts like this.

**Comment by phileefan** [comment]
Understood! Again thank you very much.....

**Comment by alex-w** [comment]
> If we only knew... Ask Nvidia. Our MFAQ deals with graphics issues. I am just surprised your Geforce also acts like this.

v0.20.1 is based on Qt 5.9, v0.20.2 is based on Qt 5.12 - so, probably between those versions of the framework has changes in graphical subsystem or OpenGL support layer.

**Comment by alex-w** [comment]
@phileefan please check Stellarium 0.21.0-63d10a0-win64 and 0.21.0-63d10a0-qt5.9-win64: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by phileefan** [comment]
alex-w,

Thanks for the update. I used the v0.21.0 Angle Mode last evening/this morning with no issues. I will try out 0.21.0-63d10a0-win64.exe on my next outing. Should I be using this update in Angle Mode also?????

**Comment by alex-w** [comment]
Please check both versions in both modes.

**Comment by phileefan** [comment]
alex-w,

Same result with both win64 versions, only working in Angle mode.

**Comment by alex-w** [comment]
> Same result with both win64 versions, only working in Angle mode.

Bad news :(

**Comment by gzotti** [comment]
This is a driver or configuration issue, like tens of similar reports. Nothing we can really solve. My PC with Geforce delivers a working counter-example. Use ANGLE. This is the solution working in all reported cases.

**Comment by phileefan** [comment]
gzotti,

No worries, I'm using Angle mode. This is the 1st issue I've ever had like this. Feel free to send me updates as you come out with them and I'll try them out!
