### ISSUE TITLE
A nameless star near α Lyrae with wrong apparent magnitude data

### ISSUE THREAD

**Issue by miku39393** [Stellarium/stellarium#1724]
### Expected Behaviour
This star at 18h36m57.59s +38d54m09.3s(J2000.0),near the α Lyrae.
I have searched in DSS,WISE and 2MASS data base.Found the apparent magnitude of this star is about +15.

(In WISE,the cyan ring show the star) 
![图片](https://user-images.githubusercontent.com/85461933/120943052-29151480-c75f-11eb-82ab-c9a6a02bd4c0.png)

(Invisible in my photograph,the red ring show the place of the star.)
![图片](https://user-images.githubusercontent.com/85461933/120943203-fa4b6e00-c75f-11eb-9073-d3796d6926d8.png)

### Actual Behaviour
In Stellarium,the apparent magnitude of this star is +8.10，not suitable with reality.
![图片](https://user-images.githubusercontent.com/85461933/120943648-ccb3f400-c762-11eb-8341-3a8e74876e72.png)

### Steps to reproduce
Input 18h36m57.59s +38d54m09.3s(J2000.0) in Stellarium can find this star.

### System
* Stellarium version: <Stellarium 0.20.1>
* Operating system: <Windows 10 Professional 20H2>
* Graphics Card: <NVIDIA GeForce GTX1060 461.72>

**Comment by gzotti** [comment]
There are probably tens of similar data errors around bright stars. Compare with DSS to see why.
However I cannot find enough similarities between your photo and the screenshot to "connect the dots". Either we have 15 more data errors, or your screenshot is off. ;-)
