### ISSUE TITLE
GetObjectInfo issue with Custom Objects 

### ISSUE THREAD

**Issue by cbellang** [Stellarium/stellarium#1725]
Hello, 

I noticed a bug concerning the use of the GetObjectInfo function when searching for "custom objects" (such as "V* W Hydra" or "* chi Cyg", ...). Indeed, the first time you run the script that contains this function after opening stellarium, this function returns nothing. You have to point to the object by hand with the "search" tool of the interface, then run the script again (without closing Stellarium) so that the function returns something. 
Is there a solution to this problem?

**Comment by alex-w** [comment]
Where is the problem?

Hint: https://stellarium.org/doc/0.21/classCustomObjectMgr.html

**Comment by cbellang** [comment]
I do 

info = core.getObjectInfo("V* W Hydra"); 

to get its altitude and azimuth. I then observe the behavior I described (the function returns nothing, unless a manual search has been done before). Maybe this is not the right function to perform this action?

**Comment by gzotti** [comment]
These custom objects are temporary. After program start, they don't exist. Only when you search for them, we look up at SIMBAD, and a new temporary custom object is created. This is of course deleted on exit.

**Comment by cbellang** [comment]
Ah ok ! 
Is there a way to record it (I have a list), and avoid the manual research ?

**Comment by alex-w** [comment]
> Ah ok !
> Is there a way to record it (I have a list), and avoid the manual research ?

Please add the custom objects before search...
