### ISSUE TITLE
Stellarium 0.21.0 Froze on Windows 10

### ISSUE THREAD

**Issue by surfinash** [Stellarium/stellarium#1728]
### Actual Behaviour

Installed v0.21.0 on May 23rd. Worked fine till yesterday. Froze on startup this morning. Froze the entire NUC. Had to kill through task manager. Nothing seems to be helping. All drivers/etc are up to date. This is a windows 10 pro NUC bought brand new last year.

Uninstalled, deleted the folder, restarted the computer, reinstalled - no difference. Still froze the entire PC.

### Start the PC. Double click on Stellarium. Watch it load, and freeze as it loads the scripts. 

Update: After several reinstalls - stellarium 0.21.0 was launched, but froze again in a minute. 

Looking at the error, I am going to delete satellites.json and try again.

[log.txt](https://github.com/Stellarium/stellarium/files/6620238/log.txt)

### System
* Stellarium version: 0.21.0 (also tried 0.20.4)
* Operating system: Windows 10 Pro
* Graphics Card: Intel HD Graphics 5500, Driver version 20.10.15.5058>
* Screen type (if applicable): Remote desktop 1080p

### Logfile 
Attached.

**Comment by surfinash** [comment]
Stuck at [Novae] update. Seems to be having issues connecting and downloading. 

[Novae] Download error: While trying to access "https://stellarium.org/json/novae.json" the following error occured: "Unknown error"

Here's the log:

---

[New Log.txt](https://github.com/Stellarium/stellarium/files/6620293/New.Log.txt)

**Comment by alex-w** [comment]
Please disable “Bright Novae” plugin in config.ini and try it again

**Comment by alex-w** [comment]
And please share the current novae.json file

**Comment by surfinash** [comment]
Thanks Alex. Here is the Novae.json.

+++
[novae.json.txt](https://github.com/Stellarium/stellarium/files/6620331/novae.json.txt)

**Comment by surfinash** [comment]
"Please disable “Bright Novae” plugin in config.ini and try it again"

>> Tried that. Did not help. Still seeing the hang. Bad part - the entire system becomes unresponsive. When I try to kill with CTRL+ALT+DEL - it launches the UI, and hangs again in about 20 sec.

**Comment by alex-w** [comment]
Please try to disable all plugins and check it again.

**Comment by surfinash** [comment]
BTW - didn't see "Bright Novae" in the plugins list. It was just "Novae" under [plugins_load_at_startup].

**Comment by alex-w** [comment]
> BTW - didn't see "Bright Novae" in the plugins list. It was just "Novae" under [plugins_load_at_startup].

This is correct point

**Comment by surfinash** [comment]
>> Please try to disable all plugins and check it again.

Copy that.

**Comment by surfinash** [comment]
Disabling all plugins did not work. 

Here is a link to the log file.

[https://drive.google.com/file/d/1oTUFYymBrZQ6a6dFveE_GYXIApl2a5Er/view?usp=sharing](url)

**Comment by alex-w** [comment]
Stop! Do you really use Remote Desktop connection?

**Comment by surfinash** [comment]
Yes.

**Comment by surfinash** [comment]
My macbook pro > nuc (win10 Pro) on my telescope. Remote Desktop into the PC.

**Comment by alex-w** [comment]
Remote Desktop Client cannot correct run OpenGL applications in fullscreen mode. Please use ANGLE mode or windowed mode for OpenGL.

**Comment by surfinash** [comment]
How do I turn the ANGLE mode? or Windowed mode?

**Comment by surfinash** [comment]
Is it in Config.ini?

**Comment by alex-w** [comment]
> Is it in Config.ini?

To set windowed mode - yes (hint: fullscreen)

**Comment by alex-w** [comment]
To ANGLE mode: Start -> Programs -> Stellarium -> Stellarium (ANGLE mode)

**Comment by surfinash** [comment]
>> To set windowed mode - yes (hint: fullscreen)

Is that under the "Video" section? Ok - let me try.

**Comment by surfinash** [comment]
WORKED!! Fabulous. Thank you.

**Comment by alex-w** [comment]
Did you tried ANGLE mode also?
