### ISSUE TITLE
Oculars: ignoring 'Binocular' setting in Eyepieces tab, showing wrong UI texts

### ISSUE THREAD

**Issue by joberreiter** [Stellarium/stellarium#1738]
When the first entry of the eyepieces tab is of 'Binocular' type, the Oculars plugin shows wrong UI texts.

### Expected Behaviour
On opening the settings dialog within Oculars and selecting the eyepieces tab, I would expect this for binoculars:
![snap0195](https://user-images.githubusercontent.com/13220647/121772453-b8fafa00-cb75-11eb-9915-7f8d2513e7b2.png)

### Actual Behaviour
On opening the settings dialog within Oculars and selecting the eyepieces tab, there is:
![snap0194](https://user-images.githubusercontent.com/13220647/121772452-b8626380-cb75-11eb-9ba7-b7bad043c2c6.png)

### Steps to reproduce
* Activate Oculars (Ctrl-O)
* Click on the settings icon to bring up the settings dialog
* At the eyepieces tab, at the first entry, check the 'Binocular' setting. If there is no entry, create it (values don't matter), and check the 'binocular' type.
* Close and restart Stellarium (not sure if that is necessary!)
* Activate Oculars (Ctrl-O)
* Click on the settings icon to bring up the settings dialog
* Click on the 'Eyepieces' tab to show the eyepieces list

### System
* Stellarium version: stellarium-0.21.0-win64.exe
* Operating system: MS Windows 7 SP1 (= v6.1) , 64bit, language german, region "de-de"
* Graphics Card: NVIDIA GeForce GTX 760, driver 466.11-desktop-win8-win7-64bit-international-whql.exe
* Screen type (if applicable): 2x 23" 16:10 @ 3360x1050px (32:10)

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/6641993/log.txt)

**Comment by alex-w** [comment]
I cannot reproduce the issue

**Comment by alex-w** [comment]
Please share your oculars.ini file

**Comment by joberreiter** [comment]
Of course:
[ocular.ini.txt](https://github.com/Stellarium/stellarium/files/6642037/ocular.ini.txt)

I have to rename it, because github is configured not to allow to upload *.ini files.

**Comment by joberreiter** [comment]
May it be that the sequence of the ini-file entries starting with "<number>\" does matter?
Like:
```
0\name=Oly 8x42 EXPS1
0\afov=6.5
0\efl=8
0\fieldstop=42
0\permanentCrosshair=false
0\reticlePath=
1\name=Nikon Aculon 10-22x50 @ 10
1\afov=36.7
1\efl=10
1\fieldstop=50
1\permanentCrosshair=false
1\reticlePath=
0\binoculars=true
1\binoculars=true
```
And if the numbered lines are not perfectly sorted (by number), the read out of the ini-entries fails (and the settings get their default values)?

Maybe it is then related to #1684 ?

**Comment by gzotti** [comment]
The Oculars plugin currently undergoes a major revision. Hopefully this will be then solved.
