### ISSUE TITLE
Ctl+t to hide side and bottom bars also hides Calendars display from the screen

### ISSUE THREAD

**Issue by kajaji** [Stellarium/stellarium#1747]
Minor issue.
### Expected Behaviour
Ctrl+t Shouldn't affect the display of Calendars

**Comment by alex-w** [comment]
Ctrl+T is hide GUI and information panel at top left corner, so, this is not a bug.

**Comment by gzotti** [comment]
Indeed Ctrl+T is the shortcut to remove all Sky GUI elements from the screen. This behaviour is on purpose.
