### ISSUE TITLE
Ability to change saturation of the Milky Way texture

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#175]
This is a feature request: It would be highly desirable to be able to change the saturation of the Milky Way texture directly in the program. The current texture used (in my opinion) shows too much color to be realistic.

**Comment by gzotti** [comment]
More urgent things first. Or please provide a pull request with your solution. Else I may consider it for Stellarium 3.0 or so....

**Comment by guillaumechereau** [comment]
I made a quick test using the rgb -> hsv functions from: http://lolengine.net/blog/2013/07/27/rgb-to-hsv-in-glsl.

The rest of the code of the shader is relatively trivial.  Here is a screenshot of the milky way with 50% saturation:

![image](https://user-images.githubusercontent.com/107679/43594383-a9541fc4-96ac-11e8-9138-46a2ebe185cf.png)

**Comment by alex-w** [comment]
Very nice!

**Comment by gzotti** [comment]
Excellent, thanks! This is also the first move towards solving https://bugs.launchpad.net/stellarium/+bug/800837

**Comment by guillaumechereau** [comment]
I pushed a branch for the code:
https://github.com/Stellarium/stellarium/tree/milkyway-saturation-effect

The new config value is:
astro/milky_way_saturation_effect, from -1 (totally unsaturated) to +1 (full saturation).  Default to 0 (no effect applied).

**Comment by guillaumechereau** [comment]
The proposed UI:
![untitled](https://user-images.githubusercontent.com/107679/43675273-da07d5f8-9813-11e8-8a33-2aef292bc56d.png)

This has the disadvantage of changing the translation string, so I am not sure if that a good idea.  I can also do it with two separate lines.

**Comment by gzotti** [comment]
One line is preferrable, and well, sometimes strings have to be updated. However, I find it's more intuitive to have saturation 1=default, and 0=totally unsaturated. Oversaturation=2 maybe OK, but nobody asked for that. or just have 0..1 for "unsaturated".."default". Opinions?

**Comment by guillaumechereau** [comment]
Yes maybe 0 to 1 is better, specially if we never need to increase the
saturation. I think I’ll make this change.

**Comment by guillaumechereau** [comment]
I pushed the change.

**Comment by gzotti** [comment]
I just remote-controlled curl -d 'id=MilkyWay.saturationEffect&value=2' http://localhost:8090/api/stelproperty/set

Quite psychedelic. Maybe oversaturation could remain a scriptable option (for artists?), just the GUI for most users can be restricted.

**Comment by guillaumechereau** [comment]
Maybe yes.  By the way I changed the name of the property to simply 'saturation' in my last commit.  Also a value of 2 now means: double the saturation value instead of max it out.

**Comment by gzotti** [comment]
I had tried this before your latest commit. Linking the GUI to the property of course means we cannot leave the value to scripting. Not sure, maybe allow 0..5 or 0..3, with the current 1 (leave as-is) as default? A base color tint can also be configured, in total this is very flexible and should leave few desires.

Hehe, I think I would have changed the property name, this is much clearer.

**Comment by alex-w** [comment]
I think saturation for GUI is OK now.

**Comment by alex-w** [comment]
The branch has been merged into master

**Comment by gzotti** [comment]
OK, we can tweak the UI later if needed, even 10 as upper limit still makes a difference. Thanks! 
Now that LP wishlist entry could be implemented (in the next few months or so), but it needs a proper "de-saturizing" taking area magnitude, aperture and magnification into account, some objects definitely can have a color hue.
