### ISSUE TITLE
Satellites with high drag do not show up

### ISSUE THREAD

**Issue by JAY-Githb** [Stellarium/stellarium#1757]
With Starlinks before, and some Oneweb satellites now,  some do not show. And normally clicking on a sat name in the Config window will go to that satellite.  With these satellites, nothing happens.

LOG FILE:
2021-06-18T13:47:54
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 15.9 (Visual Studio 2017)
Qt runtime version: 5.12.6
Qt compilation version: 5.12.6
Addressing mode: 64-bit
Total physical memory: 7092 MB
Available physical memory: 1990 MB
Physical memory in use: 71%
Processor speed: 3094 MHz
Processor name: AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G  
C:\Program Files\Stellarium\stellarium.exe 
[ This is Stellarium 0.21.0 - https://stellarium.org/ 

Satellite has invalid orbit: "0 FALCON 9 DEB" "48701"
Satellite has invalid orbit: "0 ONEWEB-0195" "48240"
Satellite has invalid orbit: "0 ONEWEB-0196" "48218"
Satellite has invalid orbit: "0 ONEWEB-0211" "48767"
Satellite has invalid orbit: "0 ONEWEB-0214" "48788"
Satellite has invalid orbit: "0 ONEWEB-0215" "48800"
Satellite has invalid orbit: "0 ONEWEB-0216" "48801"
Satellite has invalid orbit: "0 ONEWEB-0217" "48245"
Satellite has invalid orbit: "0 ONEWEB-0218" "48214"
Satellite has invalid orbit: "0 ONEWEB-0219" "48223"

LAT; N 40° 19' 
LONG; W 74° 26'
ELEV;  52 m

Some Predictions that don't appear.
  40.330  74.445  170.   JAY RESPLER Monroe       2000 
***  2021 June 20  Sun morning  *** Times are AM EDT (UT -4)
 H  M  S Tim Azi El C Dir  Mag Dys F  Hgt Shd  Rng  EW Phs  R A   Dec
48223 _ONEWEB-219    21-31P 
 2 55 45   9 274 79 C  93  5.7   0 9  427 138  435 1.9  64 1855  40.0
48214 _ONEWEB-218    21-31E
 2 57  2   9 274 77 C  93  5.7    0 9  428 139  439 1.9  64 1843  39.8
48240 _ONEWEB-195    21-31AG 
 3  9  3    9 276 60 C  93  6.2    0 9  481 199  545 1.4  60 1732  36.9

Using these TLE

ONEWEB-218             
1 48214U 21031E   21170.91668981 -.00000081  00000-0 -20567+0 0  9990
2 48214  87.6291 294.8920 0013389  60.9345 179.2334 14.61367870  1754

ONEWEB-219           
1 48223U 21031P   21170.91668981 -.00953836  00000-0 -20354+0 0  9994
2 48223  87.6329 294.8942 0012905  61.7167 182.5022 14.61821333  1754

ONEWEB-195             
1 48240U 21031AG  21170.91668981 -.00936047  00000-0 -34055+0 0  9991
2 48240  87.4690 294.8976 0009439  71.0533 159.7464 14.36345280  1769

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
@JAY-Githb could you check latest RC also?

**Comment by JAY-Githb** [comment]
Sorry, what is RC?

**Comment by alex-w** [comment]
> Sorry, what is RC?

Release candidate: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by alex-w** [comment]
I cannot reproduce the issue. Please check version 0.21.1

**Comment by JAY-Githb** [comment]
I did check it on version 0.21.1 and it is working!
Thank you.

Jay
