### ISSUE TITLE
Losing the bottom quarter of words on the main screen, but not in any of the menus

### ISSUE THREAD

**Issue by jgroub** [Stellarium/stellarium#176]
I just downloaded version 18 to a very old 2008 eMachines PC desktop (remember them?). On the main screen, the labels (and the info in the strip at bottom, and the info on whatever object you click on, in the top left corner) are all pixellated and difficult to read - it's like the bottom quarter of all of the words/numbers in the labels has been sliced off. Strangely, this doesn't happen in any of the menus on the left side - they all look just fine, normal, easily-readable letters. 

Although the frame rate is very slow, about 7-8 frames per second, I've run Stellarium on a PC laptop (that's now dying) with frame rates that low and never encountered this problem. I'm not running anything else on this machine other than all the usual startup junk. 

I'm wondering if this is maybe a Windows problem or a monitor problem. It's running Windows Vista. 

As for the monitor, it's described by windows as a generic 19-inch monitor, at 1440x900 resolution. I tried dropping the resolution down to 1360x768 and 1280x1024, but that didn't help this problem, and it made everything else look worse. 

Is there any setting within Stellarium where I can fix this? If not, what version would be best to run on a 2008 machine? Can you provide me with a link to that earlier version?

**Comment by gzotti** [comment]
Your monitor quite likely works. 

Vista is not officially supported by Stellarium, and has been declared dead by Microsoft. 
Stellarium is working great on two 2008 PCs in my reach. Just that "2008 PC" means nothing without hardware specification.  I don't remember eMachines. You may have seen a warning on first start that something about OpenGL is missing or may not work properly on your computer. Did you?

Please see canonical answers here.

https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version

If this does not help, show logfile. (And read the FAQ and other wiki articles about what logfile...)

**Comment by jgroub** [comment]
Yes, I did see that Open GL warning.  What does that mean?  What should I do?

**Comment by gzotti** [comment]
Follow the next line.

**Comment by gzotti** [comment]
@jgroub did that help?

**Comment by jgroub** [comment]
No, because I don't know what a log file is.  Waaaaaay above my computing paygrade.  Don't know what one is, where it would be, what I should be looking for even if I ever found it.
________________________________

**Comment by gzotti** [comment]
Its location is described in the Guide which you find linked in the Program menu, group Stellarium. There should also be a link named "Last run log" or so. This would be it. 

Else, Vista is not supported, and PCs from 2008 should likely use some Stellarium version from the 0.12 series unless equipped with advanced hardware of 2008 which might just be capable. This information will be seen in the logfile.
