### ISSUE TITLE
Bug in a 15.x version

### ISSUE THREAD

**Issue by Leia286** [Stellarium/stellarium#1774]
I used a 15.x version on a Windows 10 Dell laptop, several years back.
Processer: intel i5
The Irdium flares calc caused the program to crash. Thanks for fixing by this point (version 20.2 or 19.3).

**Comment by alex-w** [comment]
Why don’t you use newest version of Stellarium?

**Comment by gzotti** [comment]
There are no more Iridium flares. If some old data crash some outdated version, sorry, but who cares ? Please update.

**Comment by Leia286** [comment]
I just updated yesterday to 21.1, and haven't checked it out yet.
