### ISSUE TITLE
Satellites plug in.

### ISSUE THREAD

**Issue by JAY-Githb** [Stellarium/stellarium#1785]
I often want to know  what type of orbit a particular satellite is in.
The only way to know now is to click on the satellite in the Configuration window and then go to that satellite.  That wipes out the current sky view.
It would be helpful if perigee/apogee and period  could be added to the Satellites tab in the Satellites Configuration window.
Along with Name and Catalog number, that information  could be added above or below the fields for Standard mag and RCS. 
To make space, one line can be removed from the Description field.
Only  perigee/apogee and period are needed.  Inclination is already shown in the TLE at the bottom of the window.

Thanks for your consideration.
Jay Respler

**Comment by axd1967** [comment]
- Inclination is also an important piece of information as it gives an idea how far north/south a satellite _could_ be seen.
- current altitude could also be added.
- the current classification done by Stellarium (LEO/HEO etc) is also an interesting piece of information

**Comment by JAY-Githb** [comment]
Inclination is already shown in the TLE at the bottom of the window. No need to duplicate that information.
Current altitude is constantly changing.  You get that variable information by going to the satellite. What I'm suggesting is simply a description of the satellite orbit: perigee, apogee, period in hours and minutes, and just total minutes.

If perigee/apogee are shown, LEO/HEO are self evident. No need for additional description.  If wanted however, set that as a Class the way Geostationary is now. 
BTW, Geostationary would more accurately be described as Geosynchronous since many of them do move. 

Jay Respler

**Comment by alex-w** [comment]
> If perigee/apogee are shown, LEO/HEO are self evident. No need for additional description. If wanted however, set that as a Class the way Geostationary is now.
> BTW, Geostationary would more accurately be described as Geosynchronous since many of them do move.

Just read the Help window - I hope info about classes in the plugin will be helpful

**Comment by JAY-Githb** [comment]
Hello Alex. 
In case it was not clear, my comment was not to you. It was directed to axd1967 who asked for certain things. 
I was explaining how he could get what he wants right now without needing to make any changes in the program. 

You're doing a fine job. 

Jay Respler 
***@***.*** 
Monroe Township, New Jersey

**Comment by JAY-Githb** [comment]
Perfect!
I also  appreciate the very fast work you did in making this improvement.
Thank you.

-
Jay Respler
***@***.***
Monroe Township, New Jersey

**Comment by JAY-Githb** [comment]
I did check the latest version.  Still works well .
Thank you again.
