### ISSUE TITLE
Moon's elongation from Sun, on the plane of the ecliptic

### ISSUE THREAD

**Issue by kishorekumar62** [Stellarium/stellarium#1786]
**Is your feature request related to a problem? Please describe.**
I am trying to use Stellarium to teach the concept of new moon and full moon. By definition, at new moon, Moon's elongation from the Sun, on the plane of the ecliptic, is zero degrees. Stellarium does show Moon's elongation, but not on the plane of the ecliptic. Hence, during new moon, the elongation remains non-zero.

**Describe the solution you'd like**
My request is, pls include Moon's elongation from the Sun, on the plane of the ecliptic.

**Describe alternatives you've considered**
I had to use http://time.unitarium.com/moon/where.html to illustrate the time of a new moon (2021-04-12T02:33:16GMT). Stellarium shows elongation of 4+degrees at that time. I would prefer to use Stellarium simply cause I can create an animation using scripting, and animations are great for teaching.

**Additional context**
Here are two screenshots to illustrate what I have said above, one from unitarium.com and the other from Stellarium:

![image](https://user-images.githubusercontent.com/20681412/124376776-42f63880-dcc6-11eb-9b27-63d3a65b95ba.png)

![image](https://user-images.githubusercontent.com/20681412/124376725-032f5100-dcc6-11eb-9fd3-4a48cc1aebb9.png)

**Comment by gzotti** [comment]
Is there a special name for this "difference between Solar and Lunar ecliptical longitude"? Such a label name would be terrible. And I know somebody will complain about string #29...

**Comment by kishorekumar62** [comment]
I thought that was "elongation". I suspect I am wrong.

JPL Horizons has something called "S-O-T angle":

![image](https://user-images.githubusercontent.com/20681412/124382786-cc1d6780-dce6-11eb-9c44-5ee6f2483238.png)

The final Note in the above screenshot is the crux of my issue. I am requesting for S-O-T angle in a specific direction, i.e. along the ecliptic.

**Comment by kishorekumar62** [comment]
Elsewhere I have seen your recommendation to use the O/C longitude line. That definitely does help a lot, to show the conjunction and opposition visually. In addition, if I can show 0 Deg and 180 Deg also, that would be perfect.

**Comment by gzotti** [comment]
There are graphical representations of elongation which may only show elongation in longitude, and maybe this was the definition or usual practice centuries ago. But nowadays it's the angular distance including latitudinal offset.

**Comment by kishorekumar62** [comment]
Thank you very much! Apologies for the greatly delayed acknowledgement. I am now trying to locate the dates of upcoming Supermoons. This feature will be perfect for that.
