### ISSUE TITLE
Proper motion values as displayed vs that in the catalog.

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1787]
### Discussed in https://github.com/Stellarium/stellarium/discussions/1778

<div type='discussions-op-text'>

<sup>Originally posted by **BikramAjay** July  1, 2021</sup>
Why the proper motion values as displayed in the catalog and by Stellarium are different? 

H11 :       41.73          Trigonometric parallax (mas)
H12 :      121.23          mu_alpha* (mas/yr)
H13 :      -22.01          mu_delta (mas/yr)

https://hipparcos-tools.cosmos.esa.int/cgi-bin/HIPcatalogueSearch.pl?hipId=65378%20A&hdId=&tyc1=&tyc2=&tyc3=

![Screenshot 2021-07-01 045243](https://user-images.githubusercontent.com/86772525/124097885-03132500-da2a-11eb-8c4c-34c2c514976f.jpg)
</div>

**Comment by Atque** [comment]
There are some problems with proper motions in Stellarium's catalogs. See this picture for a comparasion between Cartes du Ciel and Stellarium (Cassiopeia seen at 10,000 BC):

![cdc_vs_stellarium](https://user-images.githubusercontent.com/37028368/124567103-f59fd580-de43-11eb-94c0-098d3f7c6d2d.png)

Cartes du Ciel is generally seen as more accurate when it comes to proper motion displayal (although not perfect). Other planetaria, such as SkySafari and Starry Night, agree with CdC.

**Comment by gzotti** [comment]
Please see Appendix F.2 in the User Guide. If the catalog was created with a buggy coder/decoder, this could probably be fixed, however this was apparently created about 2006/07, and the developer unfortunately left the project soon after.

**Comment by Atque** [comment]
> Please see Appendix F.2 in the User Guide. If the catalog was created with a buggy coder/decoder, this could probably be fixed, however this was apparently created about 2006/07, and the developer unfortunately left the project soon after.

It is really unfortunate. Stellarium needs a new star catalog (I know what you're going to say, but I am not the one with knowledge to implement this). When the full Gaia release is ready (2024 or so), we have radial velocities for a billion stars available.

**Comment by gzotti** [comment]
Yes. However Gaia needs to be mixed with Hipparcos, as it is missing the brightest stars. Maybe this catalog will already provide the mix, though. We will see in 2024. Before that, there is lots to do elsewhere.

**Comment by alex-w** [comment]
Proper motion in our star catalog are encoded and, of course, we shouldn't just display it, because these values will have wrong data. :(

**Comment by Atque** [comment]
@alex-w I see the values given in _hip_pm.dat_ correspond to the values given in Cartes du Ciel, however the graphical displaying of proper motion is still not fixed. I guess the values in this file has nothing to do with the actual positions of the stars?

**Comment by alex-w** [comment]
> @alex-w I see the values given in _hip_pm.dat_ correspond to the values given in Cartes du Ciel, however the graphical displaying of proper motion is still not fixed. I guess the values in this file has nothing to do with the actual positions of the stars?

The original report has info about wrong values of displayed proper motion data and this was correct notification, because proper motion in our *.cat files are encoded to inner format and we shouldn't just display it without decoding. I fixed displayed data only as was reported.

Your comment is related to different "problem" and you compared flat 2D movement (Stellarium) and 3D movement (CdC as far I know). Of course 2D and 3D models will give different results. This is well-known problem of Stellarium and our catalogs don't have third component (velocity) for proper motion data. It can be solved by full refactoring our star catalogs (include changing the data format) - who will do it? ;)

Probably we should postpone this really big task up to full release a Gaia data to obtain more data and accurate data.

**Comment by Atque** [comment]
Okay, so the task is bigger than I had though. It might be wise to wait, but keep in mind that the Gaia release won't contain stars brighter than about +3 mag., meaning we still need Hipparcos data.
