### ISSUE TITLE
If the names of the stars are written in Latin language, it should be called Capella no Kapella, I think...

### ISSUE THREAD

**Issue by Robiop15** [Stellarium/stellarium#179]
Než nahlásíte problém kolem grafických artefaktů, jako jsou chybějící tlačítka nabídky, podivné barvy, měsíc nevykreslený nebo podobný,* Ujistěte se, že jste si naprosto jisti, že používáte nejnovější grafické ovladače grafické karty.95% grafických problémů je řešeno tímto způsobem.Před podáním hlášení o problému prosím * naprosto ujistěte *, že chcete zkontrolovat uzavřené problémy(https://github.com/Stellarium/stellarium/issues?q=is%3Aissue+is%3Aclosed)ať již byla hlášena a vyřešena / uzavřena! V tomto případě nehláste.
Also look into the wiki (https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version 
and https://github.com/Stellarium/stellarium/wiki/FAQ) 
and check if you are attempting to report a known issue. Don't report in this case.

Also look into the User Guide before reporting unexpected but correct behaviour. Don't report in this case.

If you want to report a feature wish, delete these template lines above and below, and fill in. 

If you want to report a bug, please make sure to update and verify the bug still exists in the current version. 
In this case please also check current beta builds from http://stellarium.org
If bug still persists, delete text above down to and including this line and fill in:

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
I just tried and see Capella. 
Latviešu valoda is not latine
