### ISSUE TITLE
update Asteroids crash software

### ISSUE THREAD

**Issue by AndreaMatthey** [Stellarium/stellarium#180]
Before reporting an issue around graphics artifacts like missing menu buttons, strange colors, Moon not rendered, or similar, 
*please make absolutely sure* you are running the latest graphics drivers for your graphics card. 
95% of graphics problems are solved this way.

Before reporting an issue, please *absolutely make sure* to check the closed issues 
(https://github.com/Stellarium/stellarium/issues?q=is%3Aissue+is%3Aclosed) 
whether it has been reported and solved/closed already! Don't report in this case.

Also look into the wiki (https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version 
and https://github.com/Stellarium/stellarium/wiki/FAQ) 
and check if you are attempting to report a known issue. Don't report in this case.

Also look into the User Guide before reporting unexpected but correct behaviour. Don't report in this case.

If you want to report a feature wish, delete these template lines above and below, and fill in. 

If you want to report a bug, please make sure to update and verify the bug still exists in the current version. 
In this case please also check current beta builds from http://stellarium.org
If bug still persists, delete text above down to and including this line and fill in:

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by AndreaMatthey** [comment]
when I try to update database of asteroids, the software crash

**Comment by alex-w** [comment]
Please attach log.txt

**Comment by AndreaMatthey** [comment]
where I can find this log file?
While I try to update dabase from
Minor Planet Center, Planetarium just close, disappears.
Trying other
database of asteroids, I see in the taskbas: Planetarium not respose

Il
07.06.2018 17:14 Alexander Wolf ha scritto: 

> Please attach log.txt 
>

> --
> You are receiving this because you authored the thread.
> Reply
to this email directly, view it on GitHub [1], or mute the thread
[2].

--

Andrea Mattei   


Con Mobile Open 6 GB hai 6 Giga, 600 minuti e 300 SMS per il tuo smartphone a 9€ al mese per sempre. Passa ora a Tiscali Mobile, il nostro mese è vero! http://tisca.li/Open6GB0318

**Comment by alex-w** [comment]
> where I can find this log file?

:'( Quote from part, who you ignored:

> If possible, attach the logfile log.txt from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
@AndreaMatthey any logfile or other news? Else we will close this in a few days.

**Comment by AndreaMatthey** [comment]
Can you tell me how I can get logfile??????

I can say just this: i try to update asteroi database.. and stellarium go in crask.

I have try it on 3 different computers: windows 10 pro 32 bit with 4 Gb RAM

 

Same crash

 

 

 

Da: Georg Zotti [mailto:notifications@github.com] 
Inviato: domenica 8 luglio 2018 20:47
A: Stellarium/stellarium
Cc: AndreaMatthey; Mention
Oggetto: Re: [Stellarium/stellarium] update Asteroids crash software (#180)

 

@AndreaMatthey <https://github.com/AndreaMatthey>  any logfile or other news? Else we will close this in a few days.

**Comment by gzotti** [comment]
Let me repeat a third time:

>>  log.txt from your user data directory. Look into the Guide for its location.

**Comment by AndreaMatthey** [comment]
I just disabled my windows firewall and tried to update the database,
but I had the exact same problem.
In essence, the stellarium closes and
disappears without highlighting any errors, simply closing the
application.

This time I have try to update this
one:
https://www.minorplanetcenter.net/iau/ECS/MPCAT/mpn.txt

Il
09.07.2018 04:24 Alexander Wolf ha scritto: 

> Andrea, are you using
firewall? 
> 
> --
> You are receiving this because you were
mentioned.
> Reply to this email directly, view it on GitHub [1], or
mute the thread [2].

--

Andrea Mattei   


Con MyOpen 10 GB hai 10 Giga, 1000 minuti e 100 SMS al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 10€ di credito omaggio! Attiva ora al costo di 10€ !
SCOPRI DI PIU’ http://tisca.li/myopen10GB

**Comment by gzotti** [comment]
Have you downloaded this file manually? Most likely, a 100MB file with 523000 asteroids is too much to offer into a selection list, so we should remove this URL.

You can load elements from 
https://www.minorplanetcenter.net/iau/Ephemerides/Bright/2018/Soft00Bright.txt

**Comment by AndreaMatthey** [comment]
yes, of course I have tried also this mode……. but same problem
I
start to think that only 4 Gb of memory RAM is not enought. 
NOw I have
tried with more small database
like:

https://www.minorplanetcenter.net/iau/MPCORB/Unusual.txt

You not
have problems?

Il 09.07.2018 11:53 Georg Zotti ha scritto: 

> Have you
downloaded this file manually? Most likely, a 100MB file with 523000
asteroids is too much to offer into a selection list, so we should
remove this URL. 
> 
> You can load elements from
>
https://www.minorplanetcenter.net/iau/Ephemerides/Bright/2018/Soft00Bright.txt
[1] 
> 
> --
> You are receiving this because you were mentioned.
>
Reply to this email directly, view it on GitHub [2], or mute the thread
[3].

--

Andrea Mattei   


Con MyOpen 10 GB hai 10 Giga, 1000 minuti e 100 SMS al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 10€ di credito omaggio! Attiva ora al costo di 10€ !
SCOPRI DI PIU’ http://tisca.li/myopen10GB

**Comment by gzotti** [comment]
I see a crash with the 523000 object list mpn.txt, but am somewhat not too surprised. The crash occurs after downloading the 100MB file (progress bar completed), so during conversion and feeding the selection list. I simply assume that building a list in the GUI has its practical limits of usability, probably at a few thousand objects, and technical limits which express themselves as crash. Presumably this worked years ago when the list was a fraction of its current size. But there is no point in loading 500.000 objects, Stellarium will become much too slow to be useful. If you are interested in particular objects like "(444444) 2006 CL67" (likely not in the MPC short list for 2018), you will have to create an entry manually, sorry for that inconvenience.   

I see no crash with the lists of observable objects or the "unusual" list because these are short enough.

**Comment by alex-w** [comment]
I see no crash and I see all objects from mpn.txt file within Stellarium. On linux of course.

**Comment by gzotti** [comment]
Admittedly I did not see a crash, but actively killed the working process after a few minutes of unresponsiveness, which is the average user's indication of "frozen/crashed". How does the 500.000 object list behave in the GUI?

**Comment by alex-w** [comment]
Of course slow, but acceptable for this number of elements.

**Comment by AndreaMatthey** [comment]
Can you suggest me the way for insert only asteroids not over 18 mag.
?
Otherwise I will try to cut TXT file and reduce at 80.000 / 100.000
objects …
thanks a lot.

Andrea

Il 09.07.2018 12:56 Georg Zotti ha
scritto: 

> I see a crash with the 523000 object list mpn.txt, but am
somewhat not too surprised. The crash occurs after downloading the 100MB
file (progress bar completed), so during conversion and feeding the
selection list. I simply assume that building a list in the GUI has its
practical limits of usability, probably at a few thousand objects, and
technical limits which express themselves as crash. Presumably this
worked years ago when the list was a fraction of its current size. But
there is no point in loading 500.000 objects, Stellarium will become
much too slow to be useful. If you are interested in particular objects
like "(444444) 2006 CL67" (likely not in the MPC short list for 2018),
you will have to create an entry manually, sorry for that inconvenience.

> 
> I see no crash with the lists of observable objects or the
"unusual" list because these are short enough. 
> 
> --
> You are
receiving this because you were mentioned.
> Reply to this email
directly, view it on GitHub [1], or mute the thread [2].

--

Andrea
Mattei   


Con MyOpen 10 GB hai 10 Giga, 1000 minuti e 100 SMS al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 10€ di credito omaggio! Attiva ora al costo di 10€ !
SCOPRI DI PIU’ http://tisca.li/myopen10GB

**Comment by gzotti** [comment]
Right. With a bit more patience it loads also on Windows. (64bit version) I think I had seen a temporary memory consumption of more than a GB, so this might fail on a 32bit system.

**Comment by gzotti** [comment]
@AndreaMatthey 100.000 objects? We recommend using a few hundred objects at most.

**Comment by AndreaMatthey** [comment]
My need arises from the fact that I go to the mountains with my
equipment and load everything necessary on my notebook.
Among my
activities there is also that of researching NEO objects, so, almost in
real time I would like to check if in a star field there is some
asteroid or comet known.

I use Stellarium for control my Teloscope
Mount and search object. I have in easy mode, without any problem, to
update many other stellar catalogs, now on Stellarium I can see stars
around 17 magnitude.
I prefer Stellarium and not other planetarium like
Kstars and et.cetera.
Where is the different from giant stellar catalogs
and asteroidal?

Thanks for all.
Best regard

Andrea

Il 09.07.2018
14:41 Georg Zotti ha scritto: 

> @AndreaMatthey [1] 100.000 objects? We
recommend using a few hundred objects at most. 
> 
> --
> You are
receiving this because you were mentioned.
> Reply to this email
directly, view it on GitHub [2], or mute the thread [3].

--

Andrea
Mattei   


Con MyOpen hai Giga, SMS e i minuti che vuoi da 3€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 10€ di credito omaggio!
SCOPRI DI PIU’ http://tisca.li/myopen

**Comment by gzotti** [comment]
Asteroid positions have to be computed from orbital elements, iteratively solving Kepler's equation and doing other longish math to finally derive at a topocentric position. Star positions on the other hand are constant 3D vectors on the unit sphere, all that is done is proper motion, a simple 3D vector addition.

It might in principle be possible to move asteroid computation to the GPU, therefore applying parallelisation of computations, however no developer has until now attempted to touch this topic for real. I would very much like to have this, so that we could visualize the asteroid belt with 250.000 (or as we saw yesterday, 523.584 from mpn.txt) moving 1-pixel dots. I have once done a similar thing (CPU-based, and limited to 10.000 which slowed down a fast desktop computer of around 2002), and it really looked quite impressive.

If you upgrade to a 64bit system, you might avoid the crash scenario and be able to import many more asteroids. However, probably nobody has ever attempted to load all (or even half) of mpn.txt. The problem for you is that you likely really need lots of objects, so even the first 5000 objects (a number which will certainly slow down Stellarium significantly) will not be enough. And of course, you need to update the orbital elements on a weekly basis!

There are dedicated NEO websites which you could consult prior to your mountain expeditions.

**Comment by AndreaMatthey** [comment]
many years ago I used a Guide 8 of Project Pluto, based on MS-DOS
interface, there Always I was able to load all asteroids, but graphical
interface was not so good.
You know Project Pluto Guide?

Il 10.07.2018
11:52 Georg Zotti ha scritto: 

> Asteroid positions have to be computed
from orbital elements, iteratively solving Kepler's equation and doing
other longish math to finally derive at a topocentric position. Star
positions on the other hand are constant 3D vectors on the unit sphere,
all that is done is proper motion, a simple 3D vector addition. 
> 
> It
might in principle be possible to move asteroid computation to the GPU,
therefore applying parallelisation of computations, however no developer
has until now attempted to touch this topic for real. I would very much
like to have this, so that we could visualize the asteroid belt with
250.000 (or as we saw yesterday, 523.584 from mpn.txt) moving 1-pixel
dots. I have once done a similar thing (CPU-based, and limited to 10.000
which slowed down a fast desktop computer of around 2002), and it really
looked quite impressive. 
> 
> If you upgrade to a 64bit system, you
might avoid the crash scenario and be able to import many more
asteroids. However, probably nobody has ever attempted to load all (or
even half) of mpn.txt. The problem for you is that you likely really
need lots of objects, so even the first 5000 objects (a number which
will certainly slow down Stellarium significantly) will not be enough.
And of course, you need to update the orbital elements on a weekly
basis! 
> 
> There are dedicated NEO websites which you could consult
prior to your mountain expeditions. 
> 
> --
> You are receiving this
because you were mentioned.
> Reply to this email directly, view it on
GitHub [1], or mute the thread [2].

--

Andrea Mattei  



Con MyOpen hai Giga, SMS e i minuti che vuoi da 3€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 10€ di credito omaggio!
SCOPRI DI PIU’ http://tisca.li/myopen

**Comment by AndreaMatthey** [comment]
many years ago I used a Guide 8 of Project Pluto, based on MS-DOS
interface, there always I was able to load all asteroids, but graphical
interface was not so good.
You know Project Pluto Guide?

 



Con MyOpen hai Giga, SMS e i minuti che vuoi da 3€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 10€ di credito omaggio!
SCOPRI DI PIU’ http://tisca.li/myopen

**Comment by alex-w** [comment]
I've removed link to https://www.minorplanetcenter.net/iau/ECS/MPCAT/mpn.txt from bookmarks, but this is not resolved memory issue on large lists of objects.

As possible solution I may write a script, who will download this list every week and splitting it on chunks - 10000 asteroids per chunk for example - and publish the data on some stellarium.org host.

@gzotti Is it acceptable?

**Comment by AndreaMatthey** [comment]
I think yes,
thank a lot fo all
Andrea

Il 24.07.2018 06:56 Alexander
Wolf ha scritto: 

> I've removed link to
https://www.minorplanetcenter.net/iau/ECS/MPCAT/mpn.txt [1] from
bookmarks, but this is not resolved memory issue on large lists of
objects. 
> 
> As possible solution I may write a script, who will
download this list every week and splitting it on chunks - 10000
asteroids per chunk for example - and publish the data on some
stellarium.org host. 
> 
> @gzotti [2] Is it acceptable? 
> 
> --
> You
are receiving this because you were mentioned.
> Reply to this email
directly, view it on GitHub [3], or mute the thread [4].

--

Andrea
Mattei   


Con MyOpen hai Giga, SMS e i minuti che vuoi da 3€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 10€ di credito omaggio!
SCOPRI DI PIU’ http://tisca.li/myopen

**Comment by gzotti** [comment]
Actually, having the bookmark URL somewhere is valuable, and the import seems to work when we have enough memory, i.e. on 64-bit systems. Maybe remove on 32-bit builds only? Or test for free memory before attempting to load? Or handle some unexpected result?

I have found a remark in Planet.cpp about speed-up with running the 10.000 NEOs by removing too dim objects. Of course, this throws away objects of, say, mag24 which could occult a star. (Note that I don't expect Stellarium accurate enough for such sub-arcsecond issues!)

When I tried importing the big list, I finally got the list parsed into the GUI, but did not attempt importing "all" objects. @alex-w did you import? What was the effect on framerate?

**Comment by alex-w** [comment]
I've tried import all data from mpn.txt file on the 64-bit linux:
1) The import required over 2GB memory
2) The import process required a lot of time
3) FPS after import is very low (lesser 1 FPS)

So, I've splitted this huge file on chunks (10000 minor planets per file; 53 files at all) and insert links into SSE bookmarks. 

I'll update data of these files every week (script+cron).
