### ISSUE TITLE
Stellarium ubuntu - Satellite plugin - satellite data not loaded unless first a satellite is selected in the plugin configuration

### ISSUE THREAD

**Issue by agathokles** [Stellarium/stellarium#1803]
Ubuntu 20.04.2 LTS
core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Linux 5.4.0-73-generic
x86_64

Stellarium 0.19.3 (package 0.19.3-1build1)
But also tried Stellarium-0.21.1-x86_64.AppImage with same results.

-----------------------

Searching (in Search window) for any satellite returns no result.
Satellites plugin is set to load at startup.

If one then goes to Configuration window: Plug-ins: configure: Satellites 
and then selects or searches for and then selects a satellite, e.g. ISS (Zarya), then for the rest of the program session searching (in Search window) for satellites works, i.e. there are results.
If Stellarium is then closed and restarted we're back to square one, i.e. no satellite results (in Search window).

**Comment by alex-w** [comment]
You need to enable plugin also

**Comment by axd1967** [comment]
I've also had this bug a few times: for some reason, sats are not found. I think it is mostly when sats hints are disabled (Ctrl+Z), so check that first. 

(A small but irritating side issue is that there is no indication anywhere that sat hints are on/off, a small issue that requires to add a checkbox in the plugin dialog.) (for_wishlist)

Be aware that the Search dialog remembers search terms (#1050) , even if they might not result in a hit; so a search term in that dialog does not guarantee that the object can be found.

**Comment by alex-w** [comment]
> The plugin is active according to the OP.

According to the OP the plugin is loaded, but not activated.

> (A small but irritating side issue is that there is no indication anywhere that sat hints are on/off, a small issue that requires to add a checkbox in the plugin dialog.) (for_wishlist)

Seriously?

**Comment by axd1967** [comment]
@alex-w I'm sorry you take this the wrong way.

**Comment by agathokles** [comment]
Yes if sateliite hints are enabled then the search for satellites works (and stops working when hints disabled); btw searching for a satllite inside the plugin configuration automatically enables these hints.
But I don't understand why this should be the case.
It seems counterintuitive to me.
Imo a result should be returned regardless of hints being enabled or not.
In fact satellites hints clutter the sky/screen; one shouldn't have to have to get the sky view cluttered just to locate and select a single satellite.
Perhaps I should open this a feature request?!?!

PS There is an indicator of satellite hints being enabled or not; the respective icon on the horizontal menu gets highlighted. But it's very easily forgetable and imo in any case irrelevant.

**Comment by gzotti** [comment]
The state of the button in the button bar (main switch for general satellite visibility) is not irrelevant but is the designed indicator you ask for. If switching on satellites is needed to be able to find a satellite in the search dialog, somebody must have made just this decision. But we will never make all users happy.

**Comment by agathokles** [comment]
What I meant by irrelevant is irrelevant with respect to the problem, imo at least, with search results; not irrelevant in general.
Could someone please simply explain why search results for satellites are only shown when satellite hints are enabled?!?!?

**Comment by gzotti** [comment]
Because it may be that you are only interested in satellite results when you have switched them on? In an astronomy program, natural sky objects are just much more important that those tin boxes. If I search for some natural object, I don't want to be distracted by a satellite (or even series) of the same name. Presumably the developer of this plugin had similar concerns. 

Does a successful query really depend on the satellite hints (icons vs "realistic mode"), or rather on state of the main Satellite switch? (I don't use the plugin in these months and won't enable it now.)

**Comment by agathokles** [comment]
1. Your answer seems like a very special preference to me; much more of an option, not the expected, not a consistent and intuitive behaviour; at least imo.
2. Afaict realistic mode is selected when "Show artificial satellites as markers" is unticked and icon mode when ticked; but it's irrelevant with respect to search results; afaict, in either case no artificial satellite results are shown when satellite hints are disabled.

**Comment by gzotti** [comment]
re 1. Time to get used to programs' idiosyncrasies...

re 2. If the Satellite plugin's main switch governs also finding satellites, this can easily be remembered.

**Comment by agathokles** [comment]
I have been using Stellarium for years and yet a few days ago when I needed the azimuth of ISS's rising from the horizon I couldn't for the life of me find it using the desktop version of the program; I resorted to the web version which gave me the info just fine.
The point is not to find a way around the program idiosyncrasies; I already have since found both a way around this idiosyncracy and the program itself to do what I wanted to do.
The point is that imo this idiosyncrasy shouldn't exist in the first place.

**Comment by alex-w** [comment]
This is seems like absurde: you disabled compute position of satellites, but want to see their positions on the sky.

**Comment by alex-w** [comment]
> @alex-w I'm sorry you take this the wrong way.
> 
> There is NO indication that sat hints are enabled, other than by looking whether one can see any satellite. This is a particular issue that appears when one filters on a small amount of satellites; the **workaround** is then to search for the desired satellite, and when it is found you can see that hints have been activated. (Unless the satellite already pops up, which is a trivial indication that the feature is active.)
> 
> The solution is simple: to add the checkbox that is related to `Ctrl-Z`, as it is an ergonomic indication that the feature is active.

I'm very angry! A big button on the bottom bar, which indicate the ON/OFF state for satellites probably "too small" for you to see it. As many times before you professionaly "don't see" obvious solution and propose weird and unintuitive "solution".

**Comment by alex-w** [comment]
> 1. Your answer seems like a very special preference to me; much more of an option, not the expected, not a consistent and intuitive behaviour; at least imo.

When you deactiveted satellites (disable showing the hints of satellites) then you diabled compuration the placement (current coordinates) of the satellites. Let's imagine that you may search satellites by their names in Search tool always - with and without visible hints. What we should to select in the sky if coordinates (the placement of satellite) is unknown - whole sky or nothing? The solution is very simple: no satellites - no search.

> 2. Afaict realistic mode is selected when ...:Satellites plugin: configure: Settings: "Show artificial satellites as markers" is unticked and icon mode when ticked; but it's irrelevant with respect to search results; afaict, in either case no artificial satellite results are shown when satellite hints are disabled.

When satellite hints are disabled you have a state: no satellites. What we should "search" here?

**Comment by alex-w** [comment]
> I have been using Stellarium for years and yet a few days ago when I needed the azimuth of ISS's rising from the local horizon etc. I couldn't for the life of me find it using the desktop version of the program; I resorted to the web version of Stellarium which gave me the info just fine.

This is a "facepalm" state for me: web edition of Stellarium always compute position of satellites and all included satellites of course can be found; in the desktop edition of Stellarium you have an inactivated of computation the position of satellites (this is equal to "no satellites" state) and of course these satellites cannot be found in search tool.

**Comment by agathokles** [comment]
This is a facepalm state for me too; per the other behaviour of Stellarium I don't have POSITIONS of satellites disactivated; I have HINTS thereof disactivated.
Just like disactivating hints of stars and planets still returns search results about them.

**Comment by alex-w** [comment]
> This is a facepalm state for me too; per the otherwise behaviour of Stellarium I don't have POSITIONS of satellites disactivated; I have HINTS thereof disactivated.
> Just like disactivating hints of stars and planets still returns search results about them.

As I said before twice: you disactivated computation positions of satellites

**Comment by gzotti** [comment]
Switching off the satellites with the button in the main button bar disables the CPU intensive computations for satellites. We are not going to change this.

**Comment by agathokles** [comment]
The icon reads [Ctrl+Z] Satellite hints not Satellite positions.
I now know it actually disactivates positions not hints.
You're not going to change that. OK fine.
But that's not expected or intuitive behaviour, please don't act as if it were, please don't facepalm me.

**Comment by alex-w** [comment]
> The icon reads [Ctrl+Z] Satellite hints, not Satellite positions.

Probably your copy of Stellarium has other implementation of satellite with other behavior. Our copy of Stellarium toggle via Ctrl+Z computation positions of satellites and displayed hints of satellites in computed coordinates.

> I now know it actually disactivates positions not hints.
> You're not going to change that. OK fine.
> But that's not expected or intuitive behaviour, please don't act as if it were, please don't facepalm me.

The plugin Satellites has this behavior over 10 years already. I don't know why you expected something else.

**Comment by agathokles** [comment]
No my copy has the same behaviour otherwise I wouldn't have opened this.
It just READS (floating text displayed above the toolbar, left side, when mouse cursor above respective toolbar icon), as I'm guessing yours also does, HINTS, not actual POSITIONS.
The plugin may have a consistent behaviour for 10 years -I have no reason to doubt that- but its behaviour is inconsistent with the rest of the program's, as I've simply explained.
Anyway, this isn't going anywhere, thank you.

**Comment by axd1967** [comment]
1. I totally agree with @agathokles  that _intuitively_ search should return results whether hints are set or not. but @gzotti argument is stronger, because disabling hints allows to filter the search results (in a not-so-obvious way, agreed; and disabling computation as @alex-w points out is indeed also a strong argument)
2. indeed there is the indicator, thanks! I never saw it, because my task bar is always sunken. there is no reason to be angry for that; we are all polite.
3. but **the confusion around hints and positions is relevant** - it likely indicates a small ergonomical issue for_wishlist
3. it's not because somebody made a decision about something that it cannot be changed... idiosyncracies are not rules carved in stone... and sometimes they present very bad ergonomical issues (especially on Stellarium, but at least we are working on it)
5. (and get used to facepalms flying around here... I understand your frustration. )
