### ISSUE TITLE
satellite plugin: ISS dot "disappears" behind Moon

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1804]
### Actual Behaviour

![image](https://user-images.githubusercontent.com/3529789/126066841-20c361ed-8919-4b5f-925f-1278d3842e02.png)

![image](https://user-images.githubusercontent.com/3529789/126066852-73054174-ceb2-46f6-8f26-a919a0f86969.png)

### System
* Stellarium version: 0.21.1
* Operating system: 
* Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-77-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
@axd1967 please see screenshot 2

**Comment by axd1967** [comment]
@gzotti @Atque @treaves I please help me. I find the behaviour of @alex-w extremely abusive.

for_wishlist

**Comment by alex-w** [comment]
> @gzotti @Atque @treaves I please help me. I find the behaviour of @alex-w extremely abusive.

Really? Alex, please see your screenshot and read your report:
> ISS dot "disappears" behind Moon

P.S.  I've marked ISS especially for you on your screenshot
![stellarium-iss](https://user-images.githubusercontent.com/88731/126121652-58acff15-a666-432a-ae39-491e8de36494.jpg)

Now please explain where I was "extremely abusive"

**Comment by gzotti** [comment]
Absolutely what we intended to have when somebody asked to show a transiting black object in front of the Lunar disk.

**Comment by axd1967** [comment]
(The abuse is that I have eyes and can see the label, yet you point it out to me as if I'm blind.)

OK, found the code here:
https://github.com/Stellarium/stellarium/blob/9af5e2eeacc35cd2959533110eb97e016122546e/plugins/Satellites/src/Satellite.cpp#L933-L935

The related issue is https://github.com/Stellarium/stellarium/issues/1186 and was implemented in https://github.com/Stellarium/stellarium/compare/f5af8d9c2a7d21f25690a6406ba0decc860ea41b...6eca0ffd88759489510d097a3a31fea9cbf2ad13

This is the **intention** of the current code:
![image](https://user-images.githubusercontent.com/3529789/126318756-1d81b9b2-43a0-4532-90d9-3e989cc4128d.png)


The issue is that the ISS still reflects sunlight and will be seen in the darker portions of the Moon disc.

![image](https://user-images.githubusercontent.com/3529789/126311611-dfa6ffd1-e4cb-42ba-8cff-85e8a1aa97fa.png)


The solution for the Moon is certainly far from trivial. My feeling is that for the "realistic" (non-marker, or "dot") mode there should be a modulation of the intensity as a function of  `rcMag`, position on the disc and Moon phase angle (possibly also related to dynamic eye adaption, not sure). In case of a full Moon, the result would be a black (or `transitSatelliteColor`?) transiting satellite.


As can be seen here...

![image](https://user-images.githubusercontent.com/3529789/126319119-58544673-09ed-410d-b744-61c0c5b4002f.png)


Source: https://www.flickr.com/photos/148143189@N03/42277921554

![image](https://user-images.githubusercontent.com/3529789/126318928-a77a0e21-fa1b-41d5-b993-6fb0dfcfaf00.png)

Source: https://www.cnet.com/news/this-is-a-real-view-of-the-iss-transiting-the-moon/

![image](https://user-images.githubusercontent.com/3529789/126319203-2f10c706-e892-4e5a-8527-3cc334aea334.png)

Source: https://www.universetoday.com/132963/see-space-station-fly-front-moon/

**Comment by gzotti** [comment]
Just that the title of your issue is wrong. Nothing disappears *behind* the moon, the icon is visible in plain sight. 

Simply send a PR which fixes this issue: Replace the bright dot in closeup with a 3D model (of course make sure it's correctly oriented!), fix visual balance with a proper mix of Lunar surface brightness and ISS brightness, ... 

Or just try to observe it for real!

**Comment by Atque** [comment]
Maybe the ISS texture could be bright when illuminated, and dark when not? Wouldn't that be fairly easy to implement?

**Comment by gzotti** [comment]
That may be possible. And while we are at it, do that for all space stations...
But this plugin is still not my focus.

**Comment by alex-w** [comment]
The color of hint for satellites, which crossing of the satellite of the Moon or the Sun is defined in the GUI. This is was feature request from users, which active uses Satellites plugin for observing ISS. But in any way this fact is not related to the report.

**Comment by axd1967** [comment]
as if I thought the ISS would disappear behind the Moon... please. I routinely observe the ISS and am driving a group around it (https://www.facebook.com/groups/iss.be) ...

(And nobody asks for a 3D model.)

I still object to closing issues that do contain a bug, This way, issues disappear from the radar of developers who might want to tackle them.

**Comment by axd1967** [comment]
for_wishlist

**Comment by alex-w** [comment]
> as if I thought the ISS would disappear behind the Moon... please. I routinely observe the ISS and am driving a group around it (https://www.facebook.com/groups/iss.be) ...

This is the highest form of hypocrisy and extremely abusive behavior!!!

YOU are wrote "ISS dot "disappears" behind Moon" twice and few times me and Georg mark that this is wrong! Do you don't understand what exactly meaning word "behind"? From your sentence and screenshots we see that this is definitely not a bug, but you ignore it and accuse me in insult!

> (And nobody asks for a 3D model.)

YOU ask it!

> I still object to closing issues that do contain a bug, This way, issues disappear from the radar of developers who might want to tackle them.

You selected black color for satellites (for hints of satellites) which crosses of the Moon and no, selecting any color do not put ISS behind the Moon as you report!

**Comment by axd1967** [comment]
I see what you mean, so I will change the colour to better explain the issue.

in "dot" mode, the dot is replaced by a marker when n front of the lunar disc:

![image](https://user-images.githubusercontent.com/3529789/126521269-da935a19-6114-439e-ae9d-b2233718ef26.png)

But in "dot" mode I expect to see the same **dot**, not a **marker**.

(this is extremely abusive again... really, is there a need for such violence? @Atque @treaves @gzotti )

**Comment by alex-w** [comment]
You reported **satellite plugin: ISS dot "disappears" behind Moon** and attached 2 screenshots where anybody can see that you are wrong. I've marked this report as "invalid", because this is not a bug and this is a truth. But now I see that hearing a truth is extremely abusive for you.

Since this moment I will ignore all your reports, comment or pull requests because I cannot work with blind fanatic and very aggressive and abusive person.

**Comment by axd1967** [comment]
@gzotti @Atque @treaves please help me.

**Comment by gzotti** [comment]
What had to be said has been said, and then some more. We have understood that we cannot fulfill your expectations. The current behaviour has been implemented at users' request, and some ultra-minuscule details around it still can be improved, yes, indeed. When we can find some time slot. At our own scale of importance. But the title of your report is still misleading and wrong.  

Just don't post comments on all topics so frequently, and please stop commenting on closed issues or suggesting tags. Else I will close&lock discussions to all closed issues. We do have daytime occupations.

**Comment by axd1967** [comment]
@xalioth @gzotti @Atque @treaves please help me.


this is simply outrageous. @alex-w is being rude and aggressive towards **many** users. 

the real problem is usually a language issue, but the result is often a misunderstanding, leading to conflicts.

Here is a list of places where this behaviour emerges:



https://github.com/Stellarium/stellarium/issues/678
https://github.com/Stellarium/stellarium/issues/1527
https://github.com/Stellarium/stellarium/issues/1484#issuecomment-768223531
https://github.com/Stellarium/stellarium/issues/1636#issuecomment-830666936
https://github.com/Stellarium/stellarium/issues/1624#issuecomment-828634086
https://github.com/Stellarium/stellarium/issues/1160#issuecomment-884271246
https://github.com/Stellarium/stellarium/issues/1803#issuecomment-882052124
https://github.com/Stellarium/stellarium/issues/105#issuecomment-366437098
https://github.com/Stellarium/stellarium/issues/1680#issuecomment-846639219
https://github.com/Stellarium/stellarium/issues/1682#issuecomment-846510913
https://github.com/Stellarium/stellarium/issues/1805#issuecomment-882066883
https://github.com/Stellarium/stellarium/issues/1791#issuecomment-877383439
https://github.com/Stellarium/stellarium/issues/958#issuecomment-666271675
https://github.com/Stellarium/stellarium/issues/1682#issuecomment-872156430
https://github.com/Stellarium/stellarium/issues/1196#issuecomment-674079483
https://github.com/Stellarium/stellarium/blob/1e617e49918ab2e5e5fad318dd1ab4024eb1e41c/src/gui/BookmarksDialog.cpp#L263
https://github.com/Stellarium/stellarium/issues/1180#issuecomment-665409374
https://github.com/Stellarium/stellarium/pull/1326#issuecomment-710090775
https://github.com/Stellarium/stellarium/issues/1249#issuecomment-872040142
https://github.com/Stellarium/stellarium/issues/1247#issuecomment-689345130
https://github.com/Stellarium/stellarium/issues/970#issuecomment-584756879
https://github.com/Stellarium/stellarium/issues/678#issuecomment-523026361
https://github.com/Stellarium/stellarium/pull/1447#issuecomment-803452879
https://github.com/Stellarium/stellarium/issues/1527#issuecomment-786389580
https://github.com/Stellarium/stellarium/issues/1534#issuecomment-791988627
https://github.com/Stellarium/stellarium/issues/1627#issuecomment-830668934

**Comment by axd1967** [comment]
And there was no need to close this issue, as it does highlight a problem; it doesn't matter how small or large it is. 

The usual action is to send such issues to the backlog, but NOT to close them unless they are NOT an issue.
