### ISSUE TITLE
Spiky Moon's halo

### ISSUE THREAD

**Issue by t4saha** [Stellarium/stellarium#1805]
### Actual Behaviour
Moons halo is also spiky.

### How to reproduce
tick the spiky star check box

### System
* Stellarium version: master
* Operating system: Ubuntu 20.04
* Graphics Card: Integrated
* Screen type (if applicable): 1368x768

**Comment by alex-w** [comment]
Why you need spiky halo for the Moon?

**Comment by gzotti** [comment]
No, this would look ridiculous, sorry.

**Comment by t4saha** [comment]
No, I don't want spiky moon halo. currently the moon's halo turns spiky when spiky star option is checked.

**Comment by t4saha** [comment]
![spiky moon bug](https://user-images.githubusercontent.com/34002960/126071997-eee27aff-595c-406f-8976-c07c5d895f63.png)

**Comment by gzotti** [comment]
Oops...

**Comment by Atque** [comment]
A larger Moon halo would perhaps be desirable.

**Comment by axd1967** [comment]
> A larger Moon halo would perhaps be desirable, but only from terrestrial locations.

Or maybe from locations that have an atmosphere...

**Comment by Atque** [comment]
> Or maybe from locations that have an atmosphere...

The Moon would be too faint from such locations for it to have a separate halo texture.

**Comment by alex-w** [comment]
The issue can be reproduce for all solar system objects :(

**Comment by gzotti** [comment]
For naked-eye view of planets the spikes are OK. Just the moon as seen from earth (or if you really want, for all "large" moons as seen from their planet) should probably show non-spikes. It's non-crucial cosmetics, though.

**Comment by alex-w** [comment]
I've added fix for whole Solar system bodies

**Comment by gzotti** [comment]
If you want to tweak something even more: After harmonizing the planet and star disk sizes (somebody had complained), Jupiter's Moons appear distractingly large. A relative scale of 0.5 looks better for closeups then. Tweak here, break there...

**Comment by Atque** [comment]
> If you want to tweak something even more: After harmonizing the planet and star disk sizes (somebody had complained), Jupiter's Moons appear distractingly large. A relative scale of 0.5 looks better for closeups then. Tweak here, break there...

Are you talking about my PR #1361? The Jovian moons are bright as seen from Jupiter, so I don't see the problem here.

**Comment by alex-w** [comment]
please check the master

**Comment by gzotti** [comment]
@Atque probably this one, yes. IMHO the current view of Jupiter seen from Earth does not look like Jupiter looks like in most (except maybe the poorest quality) instruments. The moons are too big IMHO, even if the scaling with the stars may be better harmonized. Maybe the size of the Jovian moons should take into account the glare effect of Jupiter itself to make them smaller again, or something?

**Comment by Atque** [comment]
> IMHO the current view of Jupiter seen from Earth does not look like Jupiter looks like in most (except maybe the poorest quality) instruments.

This could be said about any star. Stellarium is very pretty, no doubt, but the stars do not look like stars do when you view them IRL, be it through a telescope or with the naked eye. Stellarium shows stars as blobs with different sizes, while in reality they are pinpoints of very bright light. I would like to see star/planet halos drawn with a shader (such as in Celestia) instead of a texture. I looked into it a few months ago, but as I almost completely lack experience in programming, I ended up only studying Celestia's code. I'm not sure how hard it would be to implement or if it would hit performance, but it would help giving a more realistic view. 

> Maybe the size of the Jovian moons should take into account the glare effect of Jupiter itself to make them smaller again, or something?

That could help in this particular case, but this means that stars of 6-7th magnitude would look brighter than the 4-5th magnitude of the Galilean moons.

**Comment by gzotti** [comment]
A shader program will not make your screen brighter in singular pixels. We must live with 8bit screens and blurry scaled blobs for some more time. It is just this very particular example of a Jupiter where you start to see some details on its disk with a small instruments. In these views, the Gal. Moons appear much smaller than they do now. I think we had the same debate already around 2015 or so. Time for a third scaling wheel?

**Comment by Atque** [comment]
@gzotti Not perfectly, but it would probably look better, at least with sufficient tweaking options. Celestia has none though.

A third scaling wheel might be a good feature. I always found the two scaling options too limiting. Either the bright stars are too bright (Sirius is too obvious), or all stars are too small.
