### ISSUE TITLE
Online Query Plug-in Button

### ISSUE THREAD

**Issue by t4saha** [Stellarium/stellarium#1806]
### Expected Behaviour
IDK, may be open preferred website from the list (Wikipedia, AAVSO ....)
### Actual Behaviour
Clicking the online query plug-in button at the bottom bar does nothing whether i select any object or not, also there is no tool tip.
### Steps to reproduce
Just click online query plug-in bottom bar button
### System
* Stellarium version: 0.21.1
* Operating system: Ubuntu 20.04
* Graphics Card: Integrated
* Screen type (if applicable): 1368x768

**Comment by gzotti** [comment]
Yes, I have seen it. Something strange has occurred after the merge and disabled that button's functionality. For now, please call the plugin dialog and click "configure".

**Comment by t4saha** [comment]
In the latest Qt6 build closing the online query dialog doesn't disables the bottom toolbar button.

**Comment by gzotti** [comment]
Yes, this is also in V0.22.2.

**Comment by gzotti** [comment]
Fixed in https://github.com/Stellarium/stellarium/commit/027be418bede16f51b295874f0bdcc0ef3350562
