### ISSUE TITLE
Expand Dat/Time dialog to include a tab for UTC time.

### ISSUE THREAD

**Issue by AlanKilgore** [Stellarium/stellarium#1809]
I am a member of the astronomical occultation community.  I use Stellarium to plan my expeditions. One of the features I use is to set the date/time to the time of the event and then search and display the starfield. Our prediction software generates events in UT time, not local time. Instead of having to do mental math, we would like the ability to use the date/time spinners the same way it works for local time.

I suggest adding another tab to the Date/Time dialog and call it Coordinated Universal Time or UTC for a shorter label. The date/time spinners would work the same way except they would change the clock time to be whatever UTC time was selected.

**Comment by alex-w** [comment]
Why don't you just use the UTC time zone in the planetarium?
