### ISSUE TITLE
Windows 10 LTSB latest updates freezes Stellarium x64

### ISSUE THREAD

**Issue by zirneklitis** [Stellarium/stellarium#182]
### Expected Behaviour
The application Stellarium should launch

### Actual Behaviour
Freezes in never-ending state of waiting. Nothing happens – no splash screens or other messages. Even no log file is created (with or without  `--dump-opengl-details`  or `--verbose` options). Just sitting in the memory (see attached screenshot).

![2018-06-08 06_03_58-task manager](https://user-images.githubusercontent.com/3538610/41137108-f1ffccb0-6ac8-11e8-8f78-b4f1268a0e05.png)

At the same time Stellarium x64 can be launched **with administrator privileges** and it **_works as expected_**.

You can launch the **32-bit version** on the the system and it **_works as expected_**.

### Steps to reproduce
Just try to launch the application.

### System
* Stellarium version: stellarium-0.16.1-win64.exe; stellarium-0.18.0-win64.exe; stellarium-0.90.0.15997-win64.exe
* Operating system: Windows 10 Enterprise LTSB, 1607, 14393-2248
  This mess was caused by some of the last two weeks updates.
* Graphics Card: NVIDIA Quadro K620; NVIDIA  23.21.13.8816

### Logfile 
No log file is created.

**Comment by alex-w** [comment]
Please try remove Stellarium directory from the profile (e.g. C:\Users\<LOGIN>\AppData\Roaming\Stellarium) and check it again.

**Comment by zirneklitis** [comment]
Thank You but it does not help :-(

**Comment by gzotti** [comment]
Why are you are running Windows version 1607? Would updating to 1709 or 1803 be an option? One notebook with 1607 (home edition) refused to work without an update.

**Comment by zirneklitis** [comment]
Sorry, You missed four letters – **LTSB** (**L**ong **T**erm **S**upport **B**uild) – more easy manageable Windows version. No upgrades, no metro applications. Only updates. It sticks with version 1607. Not long ago Stellarium works as expected with this Windows version. Most likely 3-D acceleration support has been broken/changed. At least _VirtulBox_ complains about that.

**Comment by alex-w** [comment]
If Stellarium works with administrator privileges and didn't work with user privileges - it's obviously local problem. Could you check drivers for graphics card?

**Comment by gzotti** [comment]
@zirneklitis from your description this is a VirtualBox issue or something else not in our reach. Did you solve it?

**Comment by zirneklitis** [comment]
Sorry, summertime. Some points: 1. It's not a VirtualBox issue, as it was just another example for non-functional piece of software after Windows 10 LTSB updates. 2. As I have to find quick solution, the 64-bit Stellarium was replaced with the 32-bit Stellarium. 3. It looks like a issue only for Windows 10 LTSB users.
