### ISSUE TITLE
Stellarium Crashed when Cliking on Configaration window button

### ISSUE THREAD

**Issue by t4saha** [Stellarium/stellarium#1821]
Stellarium Crashed when Clicking on Configuration button or pressing F2. After some digging I find it is some how relates to the online query plugin. To Open Configuration Dialog window either I have to disable the plugin or click the plugin button on the bottom toolbar first. Latest weekly snapshot (0.21.1-c6cd4e8) don't have this problem.

### Expected Behavior
Configuration dialogs opens

### Actual Behavior
Stellarium Crashed

### Steps to reproduce
Open Stellarium > Enable Online Query Plugin > Exit > Restart Stellarium > Click Configuration Button on side toolbar.

### System
* Stellarium version: latest master
* Operating system: Ubuntu 20.04

**Comment by alex-w** [comment]
Probably related to #1806
