### ISSUE TITLE
One Off Oculars Plugin crash

### ISSUE THREAD

**Issue by Leia286** [Stellarium/stellarium#1822]
### Expected Behaviour
No crash.
### Actual Behaviour
I was deleting a telescope from Oculars plugin. I clicked yes, delete, and the program went into a not-responding mode and crashed. It didn't have the 'Windows says this program isn't responding' mode that I'm used to seeing Stellarium crashes have.
### Steps to reproduce
Couldn't redo it when I reopened Stellarium. Deleted some more scopes, no problems. I think this might be a one off
### System
* Stellarium version: 21.1
* Operating system: Windows 10 64 bit
* Computer: Inspiron 5000 series 

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
Screenshots from redo attempt
![Screenshot (325)](https://user-images.githubusercontent.com/85947805/127666465-4589be89-6e19-4e2c-8c38-80f787e2fd9e.png)
![Screenshot (320)](https://user-images.githubusercontent.com/85947805/127666472-42931635-013a-4a70-94cd-acc5aecedef2.png)
Thank you to all the developers who work on Stellarium!

**Comment by alex-w** [comment]
Could you check report #1490?
