### ISSUE TITLE
CR 36 (Collinder 36) at wrong location

### ISSUE THREAD

**Issue by offermannu** [Stellarium/stellarium#1827]
### Expected Behaviour
Find Cr 36 at 3h11m +63°15' (see https://in-the-sky.org/data/object.php?id=Collinder_36)

### Actual Behaviour
Stellarium shows Cr 36 at 3h11m48.01 +11°48'

### Steps to reproduce
[F3] and search for Cr 36

### System
* Stellarium version: 0.21.1

**Comment by alex-w** [comment]
Note: Cr 36 = Tr 3

**Comment by offermannu** [comment]
Looks good :-)
Thank you!
