### ISSUE TITLE
Perseids

### ISSUE THREAD

**Issue by MayumiYamanaka** [Stellarium/stellarium#1828]
Hello, you say according to the program that the Perseids reach their maximum on August 13 in France. However, according to the AFA (the French Astronomy Association), it will be August 6, 7, 8. So, who is right ? Thanks.
![SNAG-03-08-2021 15 38 33](https://user-images.githubusercontent.com/88386685/128025376-e6238036-679b-4367-8867-0243c472e88e.jpg)

**Comment by axd1967** [comment]
Some preliminary remarks:
- https://www.afastronomie.fr/ and https://www.afastronomie.fr/les-nuits-des-etoiles
- https://www.imo.net/resources/calendar/
- currently, Stellarium fetches the data from this location:
https://github.com/Stellarium/stellarium/blob/d5d8d667a1893d08e8abee9aea6b8bc7f34ac105/plugins/MeteorShowers/src/MeteorShowersMgr.cpp#L173



I suspect that the "Nuits des etoiles" is the driving event, which is set on a **weekend**.

_

> "Les changements des dates d'une année à l'autre s'expliquent par le fait que les organisateurs cherchent le meilleur compromis entre la visibilité des étoiles filantes de l'essaim des Perséides (maximum de fréquence d'observation aux alentours de la période du 9 au 14 août) et des autres astres, il faut donc en particulier éviter les périodes de pleine lune qui gênerait la vision des étoiles faibles et de la Voie lactée. Comme chaque fois que cela est possible, c'est le fin croissant qui précède le premier quartier qui est privilégié."

_

https://fr.wikipedia.org/wiki/Nuits_des_%C3%A9toiles


(@gzotti @alex-w do we have a comprehensive list of data that is updated by Stellarium.org? is there documentation on how this list is kept up-to-date? where it takes its data from? Does the JSON data include a freshness indicator?

https://stellarium.org/json/novae.json
https://stellarium.org/json/pulsars.json
https://stellarium.org/json/quasars.json
https://stellarium.org/json/showers.json
https://stellarium.org/json/supernovae.json

**Comment by MayumiYamanaka** [comment]
I believe you are right. The "Night of the stars" is more like a weekend than the day when there will be a maximum of meteors. Thanks

**Comment by gzotti** [comment]
The sky has no weekends. August 12/13 has been the best-known date, annually, globally. 
I cannot comment on implementation details of the plugin, but the sources are public.

**Comment by MayumiYamanaka** [comment]
It makes sense, I understand now. Thanks
