### ISSUE TITLE
Strange representation of the "Great Rift"

### ISSUE THREAD

**Issue by offermannu** [Stellarium/stellarium#1830]
### Expected Behaviour
True outline of the Great Rift

### Actual Behaviour
<img width="1920" alt="Bildschirmfoto 2021-08-06 um 20 23 19" src="https://user-images.githubusercontent.com/4171341/128555452-ec0fbe87-85e7-4927-9b3e-b8a933f84663.png">
A strange graphics artifact that doesn't change size when zooming in and out (see screenshot).

### Steps to reproduce

1. Open search window [F3] and switch to the "List" tab
2. Select "Regions og the sky" in the drop drown list box
3. Select "Great Rift" in the result pane

### System
* Stellarium version: 0.21.1
* Operating system: macos 11.4
* Graphics Card: Radeon Pro 560X 4 GB
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/6947377/log.txt)

**Comment by gzotti** [comment]
The "strange graphical artifact" is called "icon" and is used if there is no geometrical outline available.

**Comment by offermannu** [comment]
@gzotti - ah ok I see ;-)
