### ISSUE TITLE
Starlore!

### ISSUE THREAD

**Issue by peachpriestess** [Stellarium/stellarium#1840]
Hello,
I was using your program and looking at the star-lore from different cultures, is there a way to include their original names in that particular language even if it's still written in English script?? I find it a little confusing to read star names which aren't really their names in that language but are 
instead the translation of that name in English. So would it be possible to create a feature where we can have both like "original name (translation)"  still written in English script???
Thanks!

**Comment by alex-w** [comment]
Hint:

![stellarium-001](https://user-images.githubusercontent.com/88731/130211368-681786f4-2fa6-456a-8cf6-21bdd2a019a1.jpg)

**Comment by peachpriestess** [comment]
> Hint:
> 
> ![stellarium-001](https://user-images.githubusercontent.com/88731/130211368-681786f4-2fa6-456a-8cf6-21bdd2a019a1.jpg)

Oh wow!! I never saw that option 😅 Thank you for the help! I'll try it when I get the chance 😌
