### ISSUE TITLE
When you glude your mouse to the left or bottom edge of the stallarium screen, the Buttons pop out, is there a way to make them stay permanently 

### ISSUE THREAD

**Issue by amaxlegend** [Stellarium/stellarium#1851]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gzotti** [comment]
When the menu slides out, a triangle becomes visible in the bottom left corner. Click it to lock the button bar. It will turn into a square to mark the menu as locked.

**Comment by amaxlegend** [comment]
many thanks
