### ISSUE TITLE
Please make time controls more granular or configurable

### ISSUE THREAD

**Issue by void4** [Stellarium/stellarium#1853]
I'm always frustrated when I want to fast forward and have clicked the fast forward button 5 times. Time passes much too fast then, there should be a step between the 4th and the 5th option.

Please introduce an intermediate fast forward speed or make them configurable in the settings.

**Comment by alex-w** [comment]
Please see https://stellarium.org/doc/0.21/classStelMainScriptAPI.html#a09505d989b398ee0c96f047647826af4

You may define any time rate (for example you may write a small script and assign hotkey for call of them).

**Comment by alex-w** [comment]
By default buttons in the GUI connected to actions with hotkeys K and L and their have multiplicator 10.  But Stellarium has actions with hotkeys Shift+K and Shift+L, which have multiplicator 2. Please use hotkeys to slowly increasing/decreasing the time rate.

**Comment by axd1967** [comment]
(Shift+J/Shift+L for finer grained rate, and K for normal rate)

@void4 have a look at F7, search for "time" (you can type that in the search box towards the bottom of the dialog)

but it sounds like a bad habit to be nervous and trigger those key combinations too fast. and did you know that you can use CTRL+mouse to advance too?

**Comment by void4** [comment]
I didn't know these hotkeys and options existed :D

(Also I noticed my mouse double clicks sometimes... I have to get a new one)

Thanks y'all!
