### ISSUE TITLE
Current year in Czech translation of meteor showers search dialog is not displayed

### ISSUE THREAD

**Issue by margre8** [Stellarium/stellarium#1854]
### Expected Behaviour
Complete current date is displayed in meteor shower search dialog.
### Actual Behaviour
In the place of year is displayed `rrrr`
![Snímek z 2021-08-30 22-06-39](https://user-images.githubusercontent.com/40942201/131399698-3102cb73-6245-45a7-912f-935e3c2513a5.png)

### Steps to reproduce
Set Czech translation and start meteor shower search dialog.
I found out this issue can by solved by replacing `msgstr dd/MM/rrrr` by `msgstr dd/MM/yyyy` in the `/po/Stellarium/cs.po` file.

> #: plugins/MeteorShowers/src/ui_MSSearchDialog.h:193
#: plugins/MeteorShowers/src/ui_MSSearchDialog.h:195
msgid "dd/MM/yyyy"
msgstr "dd/MM/rrrr"

### System:
* Stellarium version: 0.21.1

**Comment by gzotti** [comment]
Somebody apparently translated a formatting string. 8-O Umm, @alex-w why is the formatting string translatable?

**Comment by alex-w** [comment]
> why is the formatting string translatable?

It was not marked as "no translatable"
