### ISSUE TITLE
focus of search dialog not always active

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1874]
It happens too often that ctrl-F opens the search dialog, but for some reason the focus is not always in the search textedit, and as a result the user is activating commands. eg intention is to search for "moon", but the focus is wrong and Stellarium inteprets "moon"  as s series of individual commands "m" "o" "o "n".

_Originally posted by @formtapez in https://github.com/Stellarium/stellarium/issues/1834#issuecomment-913113876_

**Comment by gzotti** [comment]
whenever I press Ctrl-F the cursor is blinking on the enter line. Does this depend on OS?

**Comment by axd1967** [comment]
Ubuntu 20 does not show that behaviour

![image](https://user-images.githubusercontent.com/3529789/134358142-8221d5b7-ed6d-4d85-a62a-14253f6d61d1.png)

**Comment by gzotti** [comment]
Hmm, I just could reproduce it. When focus was on a list entry when I closed the dialog, on next call it is still there. But maybe user handling (pressing Ctrl-F to call the dialog to screen) wants to always activate the entry line.

I will try to call the dialog, and if the first page is visible, then force-focus the entry line.

**Comment by formtapez** [comment]
It happens on Windows (Stellarium 0.21.1 x64) when you select a search result via mouse leftclick from the result-list. Then the next search dialog has the wrong focus. When using cursorkeys+enter to select a result, the issue does not happen.
