### ISSUE TITLE
B 287 (Barnard 287) is not bookmarkable

### ISSUE THREAD

**Issue by offermannu** [Stellarium/stellarium#1884]
### Expected Behaviour
Barnard 287 appears in the bookmark list, a click on it will goto B 287 in Scorpius (close to M7).

### Actual Behaviour
Stellarium selects double star B 287 in Libra.
It is not possible to add Barnard 287 to the bookmarks.

### Steps to reproduce
Goto Barnard 287, add to bookmarks and click on it.

### System
* Stellarium version: 0.21.1
* Operating system: macos 11.4
* Graphics Card: -
* Screen type (if applicable): -

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Stellarium has 2 objects with the same designation - how should we guess which one should be selected?

**Comment by offermannu** [comment]
Stellarium could always add "Barnard xyz" instead of "B xyz" to the bookmarks for example. This is the way how you find it via the search field.
In case of objects which have multiple IDs Stellarium should avoid adding the ambiguous label (which doesn't help in case of Barnard 287 of course).
Another solution would be to add "dec" and "ra" to the bookmarks for ambiguous IDs and take them into account during selection.

**Comment by gzotti** [comment]
The strange thing is, while adding this to the list it is added as "Nebula" in Scorpio. As soon as the list is closed, it shows up as "Star" in Libra. This is clearly a bug.

The new list interaction is also strange: when I press "edit list", the selected object is unselected.

**Comment by gzotti** [comment]
If you search for object "Barnard 287" you can store it into the new bookmark list as object of type CustomObject (i.e. a SIMBAD result). This is a temporary workaround.

**Comment by offermannu** [comment]
"New bookmark list"? I don't know this?

**Comment by gzotti** [comment]
Ah, sorry. The bookmark feature is about to change for the next release. I was testing with this. Still, maybe storing "Barnard 287" works.

**Comment by offermannu** [comment]
Ah - ok I see :-) Already looking forward to it!

I tried to export/edit/import bookmarks.json and change the entry to 
`"name": "Barnard 287"` but this doesn't work unless you add `ra`and `dec`.

**Comment by alex-w** [comment]
OK, I think I know how to fix this and all similar issues in the Observing lists feature, but I need some experiments and probably the fix will be available in version 0.21.3 or later.

**Comment by axd1967** [comment]
please don't confirm that the bookmark feature will change in the next release. 
see #1816

**Comment by gzotti** [comment]
Although this comment is off-topic, accept that this ship has sailed. Given no army of testers who then exactly know what to change in code we have no choice than releasing this as-is, just like a popular operating system's version 8.0 was more of a public alpha test. At least this solution seems to have some new advantages, although it lacks important previous functionality.  I expect about 4-15 reports related to various bookmark problems in 0.21.2. You (and I) will have to live with it for at least three months. And hopefully we see progress by @Jocelyn1109 by November.

**Comment by Jocelyn1109** [comment]
Hi all currently  I am concentrating on fixing the first bugs that have been found and others that I have discovered. Then I will work on the new ones. I hope everything will be corrected for November.

Jocelyn

**Comment by axd1967** [comment]
We dan continue the discussion here but allow me to suggest to stop that discussion and add comments to #976.

**Comment by alex-w** [comment]
@Jocelyn1109  To search objects by it's object type we reimplemented functions [`findAndSelect`](https://github.com/Stellarium/stellarium/blob/0d911462bb95317724e33922a1a21231c8f72d38/src/core/StelObjectMgr.hpp#L82) and [`searchByName`](https://github.com/Stellarium/stellarium/blob/0d911462bb95317724e33922a1a21231c8f72d38/src/core/StelObjectMgr.hpp#L135v)
