### ISSUE TITLE
Wrong location of Ceres

### ISSUE THREAD

**Issue by AldenStarling** [Stellarium/stellarium#1890]
When comparing real photos and another app, I noticed that Ceres, currently near Aldebaran, is in the wrong location. Pallas also seems to follow the same localization error. Please check.

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Please use the Solar System Editor plugin about twice a year to update orbital elements.

**Comment by axd1967** [comment]
Related: #1880 #1564 #1598

**Comment by Atque** [comment]
I can't understand why every release does not contain fresh orbital data for all the large asteroids.

**Comment by gzotti** [comment]
We may be too busy developing to actually go out and observe... There are always more ideas than time for what can be added. I have learned to be aware of the fact I have to update those elements on a regular basis, maybe other people have not. But: if SB installs a new version and keeps the old data, the elements will not be updated. (And no, forcing an update of selected ssystem data is not what we aim at.) I have no overview how many users observe asteroids. Yes, this could come on a pre-release checklist.  @alex-w ?

**Comment by alex-w** [comment]
> I can't understand why every release does not contain fresh orbital data for all the large asteroids.

We may update elements of orbits every week but it will not help for users, who have installed Stellarium already. And we thinking that enforce deletion the user data is very bad idea. We cannot predict how many asteroids or comets will observe user and their type to guessing the frequency of updating the elements and source of these elements. If user won’t manage user data then we cannot help here. Just as a note to the report - no any technical info was given and we may only guessing the reality of problem and their source. Probably this is result of outdated data, but what is in real?

**Comment by alex-w** [comment]
I think this report should be marked as incomplete, because it has no useful info and in other words is may be shorted as “I have problem - please fix it”. First, where is technical info about Stellarium? Second, where is real photo (date and time is critical info here also)? Which software was used for comparison? Was the Stellarium fresh installed or not?

@AldenStarling please give technical details

**Comment by gzotti** [comment]
This is an FAQ problem. Update elements. Period.

**Comment by AldenStarling** [comment]
The app I used for comparison was Sky Safari for the iphone. Equipment Canon 80D+300mm F4 lens. I photographed Ceres on 9-15-2021, but the location was different in the Stellarium. I photographed again today 16-09-2021 and I could see that the SkySafari app data was correct and the Stellarium was still in the wrong position. I didn't know that it was necessary to update the Stellarium data manually, for me at the start of the program everything was automatically updated. sorry.

**Comment by AldenStarling** [comment]
![Ceres](https://user-images.githubusercontent.com/90830742/133644524-bcd9bf5d-602e-481b-9a1e-a1acecf3826d.jpg)
After updating Ceres in the solar system editor the location was correct. I thought it was a Stellarium program error, I apologize to the developers

**Comment by gzotti** [comment]
No need to apologize. Good you now know. Happy observing!
