### ISSUE TITLE
Almagest "filmroll" no longer rendered?

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1895]
In  122fe98  I had  this:

![image](https://user-images.githubusercontent.com/3529789/133976154-3942db47-7535-4764-b837-6bcf250f4ed1.png)

but in fd88ef7f9b (on the release branch) I get this:

![image](https://user-images.githubusercontent.com/3529789/133975918-c1e8daf2-05ff-4197-a5f6-4314fb3ce9ca.png)

**Comment by gzotti** [comment]
Cannot reproduce with current master.

**Comment by axd1967** [comment]
still an issue with eea67d12339c2d151f9ff63b9dcb85c392bd31b0 ...

the "filmroll" is simply `corvus_s.png`, a PNG https://github.com/Stellarium/stellarium/blob/9a6ccc7c56c5185c4a9068c74f4c9c98c705a1df/skycultures/greek_almagest/corvus_s.png.
 
found it: for some reason, some description*.utf8 contain an error (German, Japanese and Dutch):

https://github.com/Stellarium/stellarium/blob/9a6ccc7c56c5185c4a9068c74f4c9c98c705a1df/skycultures/greek_almagest/description.nl.utf8#L55

**Comment by gzotti** [comment]
Ah, indeed. Translation mess.
