### ISSUE TITLE
Telescope reticule not slewing to target object - points.json file missing

### ISSUE THREAD

**Issue by GernotSchreider** [Stellarium/stellarium#1896]
### Expected Behaviour
when connected to a telescope Stellarium should display the position of the telescope as reticule and update this when slewing to a new target

### Actual Behaviour
Describe or maybe attach a screenshot?
Stellarium 0.21 does only show an initial (?) position of the telescope reticule and does not update the position when slewing to a new target
<img width="241" alt="Mount_not_tracking_inStellarium" src="https://user-images.githubusercontent.com/68224336/133980533-a064ea7a-fa6c-461f-a037-cbb70f0a5469.png">

### Steps to reproduce
connect to a telescope via ASCOM 6.4 SP1 and observe
However when connected to the virtual telescope the reticule is moving to the correct position

### System
* Stellarium version: 0.21.1
* Operating system: Win 10
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
The logfile shows an error related to this issue
Loaded plugin "TelescopeControl"
[TelescopeControl] Only embedded telescope servers are available.
[TelescopeControl] Adding device model: "Meade AutoStar compatible" "Any telescope or telescope mount compatible with Meade's AutoStar controller." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Meade LX200 (compatible)" "Any telescope or telescope mount compatible with Meade LX200." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Meade ETX70 (#494 Autostar, #506 CCS)" "Meade's ETX70 with the #494 Autostar controller and the #506 Connector Cable Set." "TelescopeServerLx200" 1500000
[TelescopeControl] Adding device model: "Losmandy G-11" "Losmandy's G-11 telescope mount." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Wildcard Innovations Argo Navis (Meade mode)" "Wildcard Innovations' Argo Navis DTC in Meade LX200 emulation mode." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Celestron NexStar (compatible)" "Any telescope or telescope mount compatible with Celestron NexStar." "TelescopeServerNexStar" 500000
[TelescopeControl] Adding device model: "Sky-Watcher SynScan (version 3 or later)" "Any Sky-Watcher mount that uses version 3 or later of the SynScan hand controller." "TelescopeServerNexStar" 500000
[TelescopeControl] Adding device model: "Sky-Watcher SynScan AZ GOTO" "The Sky-Watcher SynScan AZ GOTO mount used in a number of telescope models." "TelescopeServerNexStar" 500000
[TelescopeControl] loadTelescopes(): Deleted node unrecogised as slot: "version"
[TelescopeControl] Loaded successfully 2 telescopes.
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.
Initializing planets GL shaders... 
>>>>>> relevant error in logfile missing points.json file
**SlewDialog::loadPointsFromFile(): No points loaded. File is missing: "C:\\Users\\gerno\\AppData\\Roaming\\Stellarium\\modules\\TelescopeControl\\points.json"**
<<<<<<<
connectionType: 7  initString: "ASCOM POTH Hub:ASCOM:J2000:POTH.Telescope:true"
Creating telescope "ASCOM POTH Hub:ASCOM:J2000:POTH.Telescope:true" ; name/type/equinox/params: "ASCOM POTH Hub" "ASCOM" J2000 "POTH.Telescope:true"
TelescopeClientASCOM::TelescopeClientASCOM with telescope name  "ASCOM POTH Hub"  and ascomDeviceId  "POTH.Telescope"
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by GernotSchreider** [comment]
Just wanted to give this update
After upgrading to ASCOM 6.5 SP1 and new ASCOM driver the behaviour is correct.
So unfortunately I cannot tell which upgrade fixed the bug in Ascom 6.4

**Comment by gzotti** [comment]
Thank you. Every such feedback counts and can help tracing down issues with the instrument zoo out there! But please test thoroughly, I have read reports that it works for while and then fails. Can you please also disclose your telescope info? I don't use ASCOM. Is this POTH something that is currently in wide use?

**Comment by luzpaz** [comment]
@GernotSchreider any progress ?

**Comment by GernotSchreider** [comment]
@luzpaz 
Thank you for coming back to me.
In fact I do not use POTH anymore, I upgraded to DeviceHub in ASCOM as the new standard to connect multiple devices. 
So far, I did not have these issues any more.

**Comment by gzotti** [comment]
OK, solution is then using ASCOM6.5 and DeviceHub. Thank you!
