### ISSUE TITLE
Catalan translation errors

### ISSUE THREAD

**Issue by leonardcj** [Stellarium/stellarium#19]
I noticed two relatively minor errors in your Catalan translation.  The correct terms are below.  Marian  was incorrect as Mairan and Pleiades is missing the accent on the e.

Nebulosa de Marian

Plèiades

**Comment by alex-w** [comment]
The Pleiades is accepted, but why Marian? In all sources, which I've seen for M43, their name is Mairan's Nebula or de Mairan's Nebula.

**Comment by leonardcj** [comment]
You are right about de Mairan's Nebula, my mistake or rather a develoer's mistake I need to correct now.

**Comment by alex-w** [comment]
@leonardcj maybe you want to help us translate Stellarium to Catalan language?

Hint: https://www.transifex.com/stellarium/stellarium/dashboard/

**Comment by leonardcj** [comment]
Actually, I restate my objection :-)

From your PO  ca.po skycultures

#: nebulae/default/names.dat:122
msgid "de Mairan's Nebula"
msgstr "Nebulosa de Marian"

I just described the error wrong.

**Comment by alex-w** [comment]
It's was wrong of course, but I've fixed it in the translations :)

**Comment by leonardcj** [comment]
alex I'm not a Catalan-speaker, but I am the Translation Team Coordinator for Sugar Labs and I've got a very good Catalan localizer.  My confidence in asserting the errors in your PO came after I merged you POs with the one for our little StarChart activity and compared differences.  It is also  based on the i18n enhancements I made to insert wiki links into the code (and POT file) that allows interwiki look up.  see  https://github.com/sugarlabs/starchart/blob/master/po/StarChart.pot and the embedded translation comments linking to the relevant pages.  I would be happy to collaborate on developing similar links for your program, but I'm pretty busy and I'm starting to think wikidata links may be better than regular wiki links.  Reach me at cjl@sugarlabs.org and we can discuss the concept.

**Comment by alex-w** [comment]
Thanks for the info! In one side the link on the wiki may be helpful, in other side some astronomical background is required for translators of astronomical software, because some special terms has other translation in common software.

**Comment by leonardcj** [comment]
It is all in how you view it.  Consider the wiki link as a means of acquiring some that specialized background and you expand beyond the educated stargazer into a way of creating more of them.  You could even leverage it as a way of encouraging more wiki articles to be created in other languages and providing a deeper dive into the celestial objects you display.

**Comment by leonardcj** [comment]
How better to point out the special meaning of certain terms than linking to an article explaining it?  I don't advocate a link for every entry, just proper nouns (e.g. object names) and terms like Longitude, Latitude, etc that are concepts with wiki pages.

**Comment by leonardcj** [comment]
I see you have a long list of country names, basically an embedded copy of ISO-3166-1.  I can absolutely help you with that in pretty much all languages.  I am leveraging wikidata retrieval e.g .see here for Afghanistan in many languages http://tinyurl.com/yb6lmmky  and CLDR Unicode locales (which also contain ISO-3166-1 to a great extent) and the Debian Alioth iso0codes translation project to identify canonical and conflicting translations of those country names.  I can add a check of your country names and flag possible corrections and additions.

**Comment by alex-w** [comment]
Could you make a patch for countries list please?

**Comment by leonardcj** [comment]
Sure, a pull request against the PO file is acceptable?  Someone else will take care of synching back to Transfex?

**Comment by leonardcj** [comment]
Or were you suggesting a translator comment to the wiki page embedded in code to appear in POT after regeneration?  Such as I use in https://translate.sugarlabs.org/templates/CLDR_regions/translate/CLDR_regions.pot#filter=incomplete

**Comment by alex-w** [comment]
The pull request may be acceptable. Technically src/translations_countries.h generated by script and I may just add links to wikipedia within script as comments.

**Comment by leonardcj** [comment]
Is this sufficient?  .xlsx format because github would not accept .csv
Coulmns
1) sequential integers for ordering
2) List of countries (in order found in src/translations_countries.h) with code markup from file
3) Corresponding wikilinks, note pre-pended #: is PO file comment mark, not needed in other contexts. 

[countries.xlsx](https://github.com/Stellarium/stellarium/files/1524012/countries.xlsx)

**Comment by leonardcj** [comment]
I'm not against trying to properly format this as a patch, it's just that you might be able to do it more easily with higher confidence.  If you could do that, I'll take care of going through each language PO file to look for opportunities to pick up new translations.  If I do that would you like the new entries default marked as "fuzzy" for human review, although I would just take them as I have very high confidence in them, some people (like me) have strong feelings about machine translation, but I make an exception for the country names in the manner I am deriving them.

**Comment by leonardcj** [comment]
Shall we start this in a new open issue?   This has gone far afield from Catalan typos and orthography.

**Comment by leonardcj** [comment]
Information transferred and discussion continued in https://github.com/Stellarium/stellarium/issues/22
