### ISSUE TITLE
Vertical stripes in atmosphere when rendering fog

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#190]
When I pan around with e.g. _Ocean_ landscape, I see some blurred vertical stripes instead of normal fog texture. This pattern is even more visible, even statically, if you use wider FOV. Here's an example:

![screenshot](https://user-images.githubusercontent.com/6376882/41252587-15c34d34-6dad-11e8-9a07-f13e318fa594.jpg)

Here's a higher-constrast view of the image above:

![high-contrast version of the screenshot](https://user-images.githubusercontent.com/6376882/41252610-2c009cdc-6dad-11e8-99a8-a9a82a7963cb.jpg)

I've been able to improve the image by increasing by an order of magnitude the value 64 passed to `StelPainter::sCylinder` in `LandscapeOldStyle::drawFog` method (namely, I replaced 64 with 764). Not sure how acceptable that is as a solution, but at least this is a pointer to the source of the problem.

**Comment by gzotti** [comment]
Yes, this is related to how the fog layer is rendered onto rather large triangles. If you look closely, you will find a similar pattern in the blue skydome (play with landscape/atmosphereybin<>44 to see off-default behaviour). 
The fog layer is not a very important thing, and is usually not looked at with contrast enhancement. There is also a particularly structured fog texture in the ocean landscape directory.

**Comment by 10110111** [comment]
> is usually not looked at with contrast enhancement

Well, I also didn't look too — until I got tired of this artefact while I was panning around. I enhanced contrast and increased FOV only to report the issue.

**Comment by am17107** [comment]
hello how i can create a file of stellarium on github I'll build it myself

**Comment by am17107** [comment]
@10110111 hello ruslan i can implement the atmosphere on stellarium web the i think the github implement

**Comment by alex-w** [comment]
Please review this issue again due to changes in the code for the atmosphere
