### ISSUE TITLE
Missing stars in Stellarium

### ISSUE THREAD

**Issue by siegbert7** [Stellarium/stellarium#1907]
Comparing my pictures from the sky with Stellarium, sometimes I can see a stars clearly on my pictures, but not in Stellarium. 

For the first I thought, it's a hotpixel on my sensors or a satelite or something else. But I found it on many pictures. So I decided to check an example in simbad (simbad.u-strasbg.fr), whether there is a star or not. 

Yes, there is a star and it's name is "TYC 1309-1609-1". You can use this link to see it in simbad (https://simbad.u-strasbg.fr/simbad/sim-id?Ident=%40795762&Name=TYC%201309-1609-1&submit=submit).

I have made a splitscreen, see attachment. On the left you can see Stellarium and in the green circle the star is missing. On the right you can see a screenshot of simbad with the stars.
![Fehlender Stern](https://user-images.githubusercontent.com/48695821/134401197-ecd7e1b1-49ea-4031-8064-2dc4d01c7394.jpg)

This is one example. Most of the stars are shown in Stellarium, but sometimes a star is missing.

### Expected Behaviour
showing star "TYC 1309-1609-1"

### Actual Behaviour
Stellarium doesn't show this star with 11,5 mag

### Steps to reproduce
Just open Stellarium a the right position of the sky, see attachment.

### System
* Stellarium version: 0.21.1
* Operating system: windows 10, 21H1
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
Not available.

**Comment by gzotti** [comment]
For a quick look for more stars, you can always switch on the DSS layer.

**Comment by siegbert7** [comment]
> 
> 
> For a quick look for more stars, you can always switch on the DSS layer.

Thanks for your hint. I have checked DSS with "TYC 1309-1609-1" and they also know this star and show it at the same position. But I think they have just asked Simbad, see attachment below.

But this is not my point. My point is, that Stellarium seams to forget some single stars which definitly exist and should be shown. If have loaded the star catalogs up to number 8 (16.5 mag), so this star with 11.5 mag should be displayed. And it is only one example for missing stars.

May be it is a problem of the programm itself or a problem of one of the cataloges or somethings else.

![DSS](https://user-images.githubusercontent.com/48695821/134533501-cad7a1a2-747a-4cc7-bbb0-79d71a56caea.JPG)

**Comment by JAY-Githb** [comment]
I have also found mag 9 stars missing. I click DSS to show them.
