### ISSUE TITLE
Make STELLARIUM_USE_CPP11 always on?

### ISSUE THREAD

**Issue by gongminmin** [Stellarium/stellarium#192]
Although there is an STELLARIUM_USE_CPP11 flag to turn on and off C++11 features, Planet::drawSurvey is using lambda from C++11. Doesn't that imply C++11 should always on, and remove STELLARIUM_USE_CPP11?

Furthermore, since most compilers are fully support C++11 or even14, are you interesting in take those features? For example, auto iter = ...begin() is much more elegant than std::vector<T>::iterator iter = ...begin().

If you are fine with it, I can work on this and send out some pull requests.

**Comment by alex-w** [comment]
C++11 required by Qt 5.7, but minimal version of Qt for building Stellarium is 5.4. De facto we using Qt 5.6 for building binary packages for Mac OS X and Linux and Qt 5.9 for Windows (both version from the TLS branches). I think we may switch to persistent using C++11 standard for compilation of Stellarium now.
