### ISSUE TITLE
Stellarium very slow when visiting other planets after having used AstroCalc graphs

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1920]
This was found in the latest public beta (RC2) on Windows 10 64-bit:

If you start on Earth, and graph any object of choice, and then close down the AstroCalc tab and visit another planet, Stellarium will freeze and then (often) crash.

1. Start Stellarium. Select the Sun and draw a graph for it.
2. Close down AstroCalc tab.
3. Select to view from Neptune.
4. Stellarium freezes (clearly calculating a new graph) and sometimes crashes.

All right, so this only happens if the Sun is still selected when visiting Neptune. I believe the #1852 would fix this, but it doesn't.

**Comment by gzotti** [comment]
I have also seen short freezes, but no crash. But I also assume some graph gets replotted in the background.

**Comment by axd1967** [comment]
Where can we find RC1?

**Comment by Atque** [comment]
@axd1967 Here:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

I'm sorry, this was RC2 appearantly.

**Comment by axd1967** [comment]
thx - I was constantly looking at that page, the "RCx" was buried in the page while I expected a tag. it is in fact the `release` branch, currently 85064710a9.

**Comment by gzotti** [comment]
@alex-w please check whether this little change in AstroCalcDialog::updateXVsTimeGraphs() is correct or there is still something missing. I think the displayed graph after re-showing the dialog is the right one.

**Comment by gzotti** [comment]
Too bad. Indeed going to Neptune is currently dangerous! Reopening the AC dialog crashed for me.

**Comment by Atque** [comment]
@gzotti Some kind of "cancel" that can be clicked even during the plotting process would be nice, and maybe some kind of progress bar, as explained in #375.

**Comment by gzotti** [comment]
Probably the Monthy Elevation graph should be limited to earthly observers? The fast rotating gas planets appear to cause issues.

**Comment by gzotti** [comment]
I think this problem really has been solved. There are other problems when observing from the outer planets, but they have been there also in 0.21.1. E.g. #1925 is related, and definitely causes delays.
