### ISSUE TITLE
Graph scaling wrong when observing from another planet

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#1925]
### Expected Behaviour

The AstroCalc Graphs/Graph tag has a "duration" field to select the range of dates for the X axis. Setting e.g. to 5 should show the development of the selected quantity over the next 5 (presumably earth) years.

### Actual Behaviour
Describe or maybe attach a screenshot?
![stellarium-009](https://user-images.githubusercontent.com/18099873/134806479-804f6592-cf62-4e81-be73-f0d282a96ea3.png)

Observe from Uranus, select Jupiter as target. Draw e.g. Distance vs. Time and Magnitude vs. Time. 
Set duration to 5 years (I had come from Earth and some older settings for Mars before.)
It seems the graph has a timeline for 12 years? Drawing takes a few minutes (!) 
Setting to 1 year and redrawing provides an empty graph which also looks like several years wide. 

### System
* Stellarium version: master (0.21.1-da6168c74c5, post 0.21.2-RC2)
* Operating system: Win10 (irrelevant)

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Also in 0.21.1. Methinks the culprit is in AstroCalcDialog::prepareXVsTimeAxesAndGraph():

int dYear = (static_cast<int>(core->getCurrentPlanet()->getSiderealPeriod()*graphsDuration) + 1) * 86400;

Looks like an unfortunate mix between sidereal period (orbit vis period for the planets!) observer location and duration of earth's rotation (?) The date scale labeled with calendar dates should probably be always counted in earth years, at least until colonies in orbit around the outer planets become reality... ;-) @alex-w ?

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
