### ISSUE TITLE
Stellarium now requires Qt >= 5.12.0 to build

### ISSUE THREAD

**Issue by arjendekorte** [Stellarium/stellarium#1927]
QPalette::PlaceholderText was added in Qt 5.12, so this seems to be the minimum required value to build. This is not reflected in the documentation `BUILDING.md` which still mentions Qt 5.7 as minimum. See the below errors when building against Qt < 5.12

```
[  215s] /home/abuild/rpmbuild/BUILD/stellarium-0.21.2/build/plugins/OnlineQueries/src/ui_onlineQueriesDialog.h:106:54: error: 'PlaceholderText' is not a member of 'QPalette'
[  215s]          palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush1);
[  215s]                                                       ^~~~~~~~~~~~~~~
[  215s] /home/abuild/rpmbuild/BUILD/stellarium-0.21.2/build/plugins/OnlineQueries/src/ui_onlineQueriesDialog.h:111:56: error: 'PlaceholderText' is not a member of 'QPalette'
[  215s]          palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
[  215s]                                                         ^~~~~~~~~~~~~~~
[  215s] /home/abuild/rpmbuild/BUILD/stellarium-0.21.2/build/plugins/OnlineQueries/src/ui_onlineQueriesDialog.h:116:56: error: 'PlaceholderText' is not a member of 'QPalette'
[  215s]          palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush3);
[  215s]                                                         ^~~~~~~~~~~~~~~
```

**Comment by alex-w** [comment]
This is my fault and we may produce the next version with fix.

@gzotti ?

**Comment by gzotti** [comment]
It is time to upgrade to Qt5.12, if not 5.15.2!

**Comment by alex-w** [comment]
> It is time to upgrade to Qt5.12, if not 5.15.2!

Ubuntu 18.04 has extended LTS support and we prepared packages for it (and used coverity scan at ubuntu-18.04), but she has Qt 5.9 in the repository

**Comment by gzotti** [comment]
OK, then we move on to 5.9+ and may develop new features with QT_VERSION tests. Just that I don't know what's "too new for old Qt" in the UI files. Or is there some compatibility setting in the QtCreator/UI designer?

**Comment by alex-w** [comment]
No compatibility setting in the QtCreator/UI designer for UI elements (but we may use specific Qt version for whole project). In any way minimal Qt is 5.9 now + I've added patches to resolve this issue.

**Comment by arjendekorte** [comment]
> It is time to upgrade to Qt5.12, if not 5.15.2!

This issue is just about the BUILDING.md file not listing the correct minimum Qt version needed. As long as this is correct, I'm fine with whatever version is needed.

The problem is just if we don't set the minimum version correctly, OBS will start building, waste resources only to fail exactly at the same point. That is wasteful.

**Comment by Alzimzim** [comment]
Plugins OnlineQueries requires Qt >= 5.12.0 https://doc.qt.io/qt-5/qpalette.html#placeholderText
Qt < 5.12.0 error build (error: 'PlaceholderText' is not a member of 'QPalette')

**Comment by alex-w** [comment]
> Plugins OnlineQueries requires Qt >= 5.12.0 https://doc.qt.io/qt-5/qpalette.html#placeholderText
> Qt < 5.12.0 error build (error: 'PlaceholderText' is not a member of 'QPalette')

The fix is available in `master`
