### ISSUE TITLE
Pluto rotates in the wrong direction

### ISSUE THREAD

**Issue by Ironman65** [Stellarium/stellarium#1928]
Pluto is rotating from East to West. It should rotate West to East. This happening in the latest version of Stellarium 21.2 32 bit

**Comment by alex-w** [comment]
The issue may be related to commit 89761d8a35eeb8bda3e143ebafb52ebb95fdd03c or this is result of some typo in refactoring code of SolarSystem/Planet classes

**Comment by Atque** [comment]
Doesn't Pluto, like Venus, have such a large axial tilt that it appears to rotate backwards?

**Comment by gzotti** [comment]
The WGCCRE2015 report says for the axis orientation in J2000.0 coordinates:

> (134340) Pluto α0 = 132◦.993
> δ0 = −6◦.163
> W = 302◦.695 + 56◦.3625225d(m)
> 
> (134340) Pluto : I Charon α0 = 132◦.993
> δ0 = −6◦.163
> W = 122◦.695 + 56◦.3625225d(n)
> 
> (m) The 0◦ meridian for Pluto is defined as the mean sub-Charon meridian
> (n) The 0◦ meridian for Charon is defined as the mean sub-Pluto meridian

From which we have, in our ssystem_major.ini for Pluto:

> rot_pole_ra=132.993
> rot_pole_de=-6.163
> rot_pole_w0=302.695
> rot_pole_w1=56.3625225
> 

and for Charon:

> rot_pole_ra=132.993
> rot_pole_de=-6.163
> rot_pole_w0=122.695
> rot_pole_w1=56.3625225

The rotation would in earlier decades have been described as "backward", but the WGCCRE definitions for minor bodies was changed to allow for axes with large precession, please see the WGCCRE reports. IMHO all is good.
