### ISSUE TITLE
Load of starlore fails

### ISSUE THREAD

**Issue by margre8** [Stellarium/stellarium#1930]
### Expected Behaviour
Starlore menu shows all starlores correctly.

### Actual Behaviour
Starlore menu shows incomplete list and this incomplete list is different after every Stellarium startup.

![stellarium-042](https://user-images.githubusercontent.com/40942201/135037694-f0746d96-f0d0-4985-85c5-051e8750fdfc.png)

![stellarium-044](https://user-images.githubusercontent.com/40942201/135038774-7e3d1248-8f32-4d07-8cae-33e4fb38bfb9.png)

### Steps to reproduce
Start Stellarium and go to view/starlore
I found out starlore window shows informations correctly when I start Stellarium for first time or when I delete .stellarium folder before startup, starlore is broken after second startup.

### System
* Stellarium 0.21.2 my own build from source code (install destination /usr)
* Operating system: Ubuntu 20.04.3 (64-bit)

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/7241822/log.txt)

**Comment by gzotti** [comment]
Cannot confirm with the regular installer. Something wrong in the build config?

**Comment by margre8** [comment]
I built it with `cmake -DCMAKE_INSTALL_PREFIX=/usr ../..` and installed it with `sudo make install`.
I am attaching build config log: [BuildConfig.txt](https://github.com/Stellarium/stellarium/files/7242361/BuildConfig.txt)
I didn't notice any problem with build.

**Comment by alex-w** [comment]
@margre8 could you check permissions for `/usr/stellarium` directory?

**Comment by margre8** [comment]
@alex-w `/usr/share/stellarium` has root permissions in my computer.

**Comment by margre8** [comment]
I found out this problem disappears when I run stellarium manually from `build/src/` folder.

**Comment by margre8** [comment]
I have same problem with AppImage version.

**Comment by gzotti** [comment]
@margre8 your logfile indicates a problem with the Seleucid skyculture. I don't see a problem there, but can you move that directory away for a test? If moving the Seleucid SC directory away helps, the problem must lie there.

**Comment by margre8** [comment]
@gzotti Thank you for your tip but it doesn't work also I found out the error with `info.ini` is not for Seleucid only, but it changes on every stellarium startup (now the warning was for almagest).

**Comment by gzotti** [comment]
Bad. Maybe try to move them away one-by-one as they are listed in the logfile. We have had a few updates. Not sure if that broke things in your specific case.

**Comment by alex-w** [comment]
Please remove Stellarium package, which was installed from repository

**Comment by margre8** [comment]
@alex-w If you mean package installed via `apt-get install`, I did not install any version of Stellarium from ubuntu repository.

**Comment by margre8** [comment]
@gzotti Thank you, your suggestion of deletion of directories with errors works. I have deleted: `russian_siberian` `seleucid ` `mulapin` and `almagest `. Now sky culture menu seems OK.

**Comment by margre8** [comment]
It seems the problem was in uninstalling `stellarium v0.21.1`, because `sudo make uninstall` did not remove directories of changed sky cultures that is why skylore window in `stellarium v0.21.2` was broken.

**Comment by alex-w** [comment]
Did you followed instructions from BUILDING.md file?

**Comment by margre8** [comment]
@alex-w Yes I did.
* Before build of new version I unstalled the old version via `sudo make uninstall`
* `mkdir -p build/unix` and used `cmake -DCMAKE_INSTALL_PREFIX=/usr ../..`
* `make` and `sudo make install`

I think the only problem was from switching from version `0.21.1` to `0.21.2`
After deletion of unused directories in `/usr/share/stellarium/skycultures` starlore menu works without any problem

**Comment by alex-w** [comment]
Is the problem solved?

P.S. I use directory `/opt` for the myself builded stellarium and I never have problem with sky cultures, but I didn't check command `make uninstall`

**Comment by margre8** [comment]
@alex-w Yes, the problem is solved. Thank you for your help.
