### ISSUE TITLE
0.21.2: observing lists core dump

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1932]
test procedure:

1. open obs lists
2. create new list
3. type name
4. select a star
5. add object
6. do not close any dialog
6. immediately export list (indeed, in the object list creation mode)
7. then import the list

bug: core dump.

and this crash could have been prevented, it was predicted [here](https://github.com/Stellarium/stellarium/pull/1816#issuecomment-890382301). 

extensive discussion here: #976 

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-86-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

**Comment by offermannu** [comment]
I can confirm that the problem also exists on macOS 11.4

**Comment by Jocelyn1109** [comment]
Perfect and great details. I will investigate.

**Comment by Menno5** [comment]
@Jocelyn1109 If I can help in any way with every day use testing or what ever, I would be glad to do so.

**Comment by sapper4484** [comment]
i can also confirm that the upgrade does not import existing lists.  OR they don't show up.  To test I tried an import then an export and then a import.  On import nothing shows, on export the files has the entries, on import it abends
