### ISSUE TITLE
Search of Atlas right hand error

### ISSUE THREAD

**Issue by margre8** [Stellarium/stellarium#1934]
### Expected Behaviour
Search of the right hand of atlas statue shows right hand

### Actual Behaviour
Search of the right hand of atlas statue ends by crash of the program

### Steps to reproduce
* select farnese greek sky culture
* search for the right hand of atlas statue

### System
* Stellarium version: v0.21.2
* Operating system: Ubuntu 20.04.3

**Comment by gzotti** [comment]
I cannot confirm a crash, technically, but right hand of atlas and the "special feature" pattern are not labeled, and the main view turns black when when searching for them.
