### ISSUE TITLE
All B.C. dates are wrong by 1 year! Need to be 1 year higher number B.C.

### ISSUE THREAD

**Issue by ragriffin** [Stellarium/stellarium#1937]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
And why don't you read the User Guide first?

**Comment by ragriffin** [comment]
Stellarium is wrong by one year when the year is B.C. (i.e. Before Christ). There is no such thing as the year 0.  Going forwards the year moves directly from 1 B.C. to 1 A.D. (Anno Domini).  It is the first year before Christ and then the first year after Christ.  

I was checking the solar eclipse at Nineveh (Mosul in Iraq) that actually happened on 15th June 763 B.C. at 10:42 a.m. This date of the eclipse is famous around the internet as the date used to date Assyrian records so that we know the exact dating of events in Assyria and Babylon.  It is mentioned in the Assyrian Eponym records (a list of events each year).  It is simply known as the Assyrian Eclipse.  I found that Stellarium put the date of the eclipse as 15th June 762 B.C.  It should be in the year 763 B.C. 
 Therefore Stellarium is wrong by exactly one year. I assume that Stellarium is also wrong for all dates that are before Christ (i.e. B.C. dates) by one year.

I expect that this will be very easy to fix.  I am surprised that no one picked up this basic fault before me.

**Comment by sunshuwei** [comment]
Haven't you heard of "Astronomical year numbering"?

**Comment by gzotti** [comment]
No one, except for  #72, #89, #922, #1544, ...
