### ISSUE TITLE
Bookmarks can not be added/imported into Observing List

### ISSUE THREAD

**Issue by Menno5** [Stellarium/stellarium#1944]
### Expected Behaviour
With upgrading from 0.21.1 to 0.21.2, Bookmarks should have converted into the Observing List or the import function of the Observing List should import Bookmarks (bookmarks.json). If I understand correctly, this is mentioned in #976 

### Actual Behaviour
After the upgrade the Observing List is empty and Bookmarks (from own system but also downloads from sites) can not be imported. Either nothing is happening or Stellarium is crashing (crash is Stellarium suddenly closing and log.txt has no data of the crash. See log below)

### Steps to reproduce
See above.

### System
* Stellarium version: 0.21.2
* Operating system: Windows 10 Pro 64bit 20H2 (19042.1237)
* Graphics Card: Graphics Card: MSI RTX 2080 ti Gaming x Trio

### Log file
[log.txt](https://github.com/Stellarium/stellarium/files/7263850/log.txt)
.

**Comment by axd1967** [comment]
similar to #1932

**Comment by Menno5** [comment]
........
> 
> As you can see, now the legacy bookmarks are loaded into observing list.
> 
> 
> Thanks ;

Looks good this! Thanks for following this up.
Question: is there going to be a setting for the localized name of an object? For example, vdB 141 is way less recognizable (and placeable in the sky) than the localized name Ghost Nebula.

**Comment by axd1967** [comment]
> Question: is there going to be a setting for the localized name of an object? For example, vdB 141 is way less recognizable (and placeable in the sky) than the localized name Ghost Nebula.

(see also #1811)
