### ISSUE TITLE
Artifacts in constellations artwork

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1945]
### Expected Behaviour

Rendering artwork in sky cultures without artifacts and clipping

### Actual Behaviour

Rendering artwork in sky cultures in some time has clipping and artifacts, see right side on the screenshot.
![stellarium-014](https://user-images.githubusercontent.com/88731/135720648-897161da-c162-40fa-93a3-3f6344505df3.jpg)

### Steps to reproduce
1. Run Stellarium
2. Enable displaying artwork (R)
3. Move the sky 

### System
* Stellarium version: master
* Operating system: Ubuntu 20.04.3 LTS
* Graphics Card: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] 
* Screen type (if applicable): 1920x1080

**Comment by alex-w** [comment]
I can reproduce issue in version 0.21.2 too

**Comment by alex-w** [comment]
Version 0.21.1 doesn't have this issue, so, this is a regress :(

**Comment by alex-w** [comment]
The source of issue is commit 9232fba331928e96aa7829108c4af6b48398712b :-(

**Comment by alex-w** [comment]
Probably method `Constellation::drawArt` is not needed, because I don't see where is called.

The next problem - artwork is aberrated and not aberrated in same time, WTF?

**Comment by alex-w** [comment]
@gzotti I see aberration is applied only for constellations artwork and nothing else - is this really need for constellation artwork?

**Comment by gzotti** [comment]
Aberration is applied to constellation artwork, like to (almost) everything else. Sure, why not? Sorry, I currently cannot reproduce this. What projection and FoV?

**Comment by alex-w** [comment]
Standard stereographic projection and all FOV

**Comment by gzotti** [comment]
Finally I can reproduce it in Ubuntu, but not Windows. Driver problem? Will investigate (also your PR) next week.

**Comment by alex-w** [comment]
No issue on Mac

**Comment by gzotti** [comment]
Technically this is not the cleanest solution.  I don't understand why the same code works on the other platforms but not on Linux. The result now is that the uncritical constellation artwork does not follow aberration shift (~20"). This would have been more relevant if the aberration exaggeration could have been increased much more than it turned out to be possible.
