### ISSUE TITLE
Time range extension with DE431 not works.

### ISSUE THREAD

**Issue by BC4300** [Stellarium/stellarium#1949]
(First of all: it’s a fantastic program, I use it almost daily – thank you very much!)

I use the 0.21.2 version of Stellarium.
Wanted to extend the accurate time range, so according to the instructions of the manual I downloaded  from JPL (via Filezilla)  the DE431 and DE441 folders.
First I made a folder named ephem in the C/ Program files/Stellarium folder,
https://drive.google.com/file/d/1SAH4ES6ZC89LsW_MbtTB17V2qXbtESYD/view?usp=sharing
 than I copied from the downloaded DE431 folder the lnxm13000p17000.431 file to the ephem folder.
In the Configutation  Windows I enable the DE431, and try to use it.
At lat. 47,4983° for dec. 21. 4300 BC,  Stell. shows the sunset at az. 238, which is impossible.
https://drive.google.com/file/d/1fMdj20UqEYJJtXHSTF_OYtPzYP7CG9dl/view?usp=sharing
Equally for sept. 21. 4300 BC sunrise at az. 70, sunset at az. 289., etc.
https://drive.google.com/file/d/1aDAwsjtAXXcnYS0gJ-YWZTFWN5sdIu-o/view?usp=sharing
https://drive.google.com/file/d/1M_CLjL77quP3764URPjW8ueqJhmOfnmg/view?usp=sharing

Than I downloaded the DE430 and DE440 folders, and copied the files with the 441 
 to the ephem folder.
https://drive.google.com/file/d/1EKs460xuKEU_7TuWO-qIUwNKwDCr3DdG/view?usp=sharing

I try to enable all of them, than alternately one by one with the DE431 – the errors stayed the same.
https://drive.google.com/file/d/1CbnAx4MjIcG1wc6H011DWzIp5aBbppBk/view?usp=sharing
(I copied the DE431 to Cartes du Ciel and interestingly, exactly the same errors occurred: sept. 21. 4300 BC sunrise at az. 70, sunset at az. 289., etc.)
I use a Dell Inspiron 3593, 8GB, OS 64b Win10 Home (20H2)
What could be the problem?
Thank you in advance:
BC4300

**Comment by alex-w** [comment]
Important note: year -4300 != 4300BC (Hint: astronomical year numbering)

**Comment by alex-w** [comment]
>At lat. 47,4983° for dec. 21. 4300 BC, Stell. shows the sunset at az. 238, which is impossible.

Why it's impossible?

**Comment by gzotti** [comment]
Do you think December 21 4300BC should have been winter solstice, and September 21 autumn equinox? Please read Appendix F.8 and then chapter 13.11 of the User Guide.

**Comment by BC4300** [comment]
Thank you – I see now (I hope.) 
I think you refer to this from the manual: _„ If you want to show summer solstice in the year -2500, you will notice it is not on June 21st. This is not an error of Stellarium – the Gregorian reform had a reason! In prehistoric times, it may be more useful to work with solar ecliptic longitudes. For example, summer solstice is when the Sun is at λ = 90.”_
So if I set the program to eg. 4300BC, and by the date/time window  I get the Sun to λ = 90 position (or working simply with the Archeolines plugin, I  get the Sun to the Summer Solstice line), I will see what happened on the sky on the summer solstice of 4300BC ?  (positions of the heavenly bodies before sunrise, etc.)

**Comment by BC4300** [comment]
Super. Thank you.
