### ISSUE TITLE
Unwanted trails in mars retrograde motion script

### ISSUE THREAD

**Issue by YvesAD** [Stellarium/stellarium#1950]
I'm running a modified "MarsRetrograde_DN.ssc" script, but the behavior described below is also present with the script downloaded from the Stellarium site.
 
### Expected Behaviour
See only the trail of Mars retrograde motion
### Actual Behaviour
Lot of trails appears too (moon and asteroids ? (some can be selected,
[log.txt](https://github.com/Stellarium/stellarium/files/7273263/log.txt)
![stellarium-006](https://user-images.githubusercontent.com/4289117/135752785-e7662f62-e8b3-442c-bd53-d81df7497ca1.png)
 i.e. "bianca" some not)

### Steps to reproduce
Activation/deactivation of the asteroids/planets trails in the configuration menu and/or the corresponding plugins do not affect the unwanted behavior.

### System
* Stellarium version: 0.27.2 from PPA
* Operating system: Ubuntu 18.04.6
* Graphics Card: Intel UHD Graphics 620 (WHL GT2)
* Screen type (if applicable): built-in (laptop asus zenbook) 1920x1080 120Hz
### Logfile 
attached + screenshot

**Comment by alex-w** [comment]
Please change the settings for trails in the GUI (see screenshot) or through scripting engine: https://stellarium.org/doc/0.21/classSolarSystem.html#a659a973460dfbef071a14ac71630c1c9 and https://stellarium.org/doc/0.21/classSolarSystem.html#a7786f98a84ab0d5e14c627ac0508349f
![stellarium-001](https://user-images.githubusercontent.com/88731/135754042-95ad97d6-d049-4d71-8dc1-978d0319aa21.jpg)

**Comment by YvesAD** [comment]
Thanks for your answer.
1) I tried the same config in the GUI (and tried it again now) but the unwanted trails continued to appear.
2) I can suppress the unwanted trails by modifying the script : 
    at line num 37 in "MarsRetrograde_DN.ssc"
    I wrote
SolarSystem.setFlagTrails(false);
SolarSystem.setNumberIsolatedTrails(1);
SolarSystem.setFlagTrails(true);

   instead of "SolarSystem.setFlagTrails(true);"

Didn't work on any stellarium script for the last 3 years. I was a little bit rusted.

**Comment by alex-w** [comment]
Both my links are important!
