### ISSUE TITLE
Invisibe labels of stars

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1951]
Original question: https://answers.launchpad.net/stellarium/+question/698950

### Expected Behaviour
All labels of star are visible when "Labels and marks" in section Stars in far right position

### Actual Behaviour
Not all stars have visible labels on any zoom level when "Labels and marks" in section Stars in far right position

**Comment by gzotti** [comment]
I think stars with only HIP/SAO/HD numbers don't get a sky label by intention. Else the sky will be flooded with just too many labels.

**Comment by alex-w** [comment]
@gzotti yes, you're right! But see screenshot - label of UZ PsA should be visible.

![stellarium-000](https://user-images.githubusercontent.com/88731/135820542-46b9652e-9aa9-48ca-9684-bcc5a37778b4.jpg)

Probably adding new config option to toggle the including of HIP designations onto screen may be good here for some people.

**Comment by gzotti** [comment]
Probably variable stars (or also WDS) are interesting enough to "deserve" a screen label. But for the HIP/SAO/HD only, yes, an extra option would be useful, and maybe even a fov limitation. Text labels are pretty slow, don't flood your screen with thousands of overlapping labels.

**Comment by alex-w** [comment]
I think I will refactor subsystem for scientific designations of stars (customization screen labels of stars)
