### ISSUE TITLE
Shortcut to center on current telescope position

### ISSUE THREAD

**Issue by MasterPIC** [Stellarium/stellarium#1956]
Hi,
what about adding a shortcut to center Stellarium chart on current telescope coordinates?

Thanks
Armando

**Comment by MasterPIC** [comment]
Hi,
I may be wrong but by giving a look at the source code I see no shortcut is associated to centeringScreenActionId.

**Comment by gzotti** [comment]
This is because you can configure it in the program menu, but don't have to. Stellarium probably has more configurable actions that a regular keyboard has keys, so it's up to the user to configure what he needs.

**Comment by alex-w** [comment]
> Hi, I may be wrong but by giving a look at the source code I see no shortcut is associated to centeringScreenActionId
> 
> plugins/TelescopeControl/src/TelescopeControl.cpp - line 198

Please press F7 and assign shortcut ;)

**Comment by MasterPIC** [comment]
Hi Alexander,
I just tested it and I can confirm the centering by shortcut works flawlessly.
But I see goto center and goto selected object seems not working. I tried to set different shortcuts too but they seem not working. I'm using ASCOM .Net simulator.

Thanks again
Armando
