### ISSUE TITLE
Pixel size in sensor config doesn't matter

### ISSUE THREAD

**Issue by vladtcvs** [Stellarium/stellarium#1977]
Sensor config has 3 parameters:

1) sensor size in mm
2) resolution in px
3) pixel size in um

Obviously, only 2 of them independent.

### Expected Behaviour

I enter sensor resolution and pixel size and stellarium calculates sensor size. Or i enter resolution and sensor size and stellarium calculates pixel size

### Actual Behaviour

I need to enter all 3 values - sensor size, pixel size and resolution. And it looks that pixel size doesn't matter at all

### System
* Stellarium version: 0.19.3
* Operating system: Ubuntu 20

![image](https://user-images.githubusercontent.com/3390973/138505058-8156efc7-7e03-441e-8474-efeb7fc8236c.png)

**Comment by axd1967** [comment]
(@vladtcvs in case you wonder, the solution is to upgrade Stellarium to the most recent version.)
