### ISSUE TITLE
refraction settings not remembered

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2018]
### Actual Behaviour
![image](https://user-images.githubusercontent.com/3529789/140811180-4df61455-f9e9-4974-8abc-25b62879268a.png)

### Steps to reproduce

1. open F4>refraction settings
2. observe that they are nonstandard (?)
3. click "Std atmosphere"
4. save settings (F2)
5. exit & restart

This is an important issue for users needing a higher precision.

### System
* Stellarium version: 0.21.2
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Is is stored. However, when you have pressure/temp settings in your landscape.ini, those are loaded on loading a landscape. For critical uses these values should be checked before use.

**Comment by axd1967** [comment]
confused...

- I see: in `config.ini` there is `pressure_mbar` (and temperature)
- code browsing reveals existence of `landscape/pressure_mbar` as well as `location/atmospheric_pressure` ...) 
- values from pressure dialog are updated in `config.ini` *when saving the settings*

Maybe the status line should include the current pressure/temp setting next to the location info? Or some other way to indicate what pressure is being used.

Fact is that changing pressure, then closing and restarting Stellarium requires the user to re-check the pressure; there is something smelly here, one would expect this value to be "somehow" remembered. 

In fact we are dealing with several pressure values:

In random order of precedence:

1. value in `config.ini`
1. pressure specified in landscape
1. pressure from current location (which can be initially set from landscape altitude)
1. pressure computed from altitude of landscape 
1. user overridden value

Food for thought.

**Comment by axd1967** [comment]
Rest assured, I'm aware of the complications, _and they already exist, seen the amount of existing pressure variables_. And I'm just trying to improve things. And I've never used sarcasm as far as I know, as it won't help.

**Comment by alex-w** [comment]
Question: how many landscapes has atmospheric pressure settings? Answer: one. 

Maybe 2-3 user contributed landscapes has settings for pressure also (from the official list of user contributed landscapes).

Probably you have an own landscape with atmospheric settings and now you ask us why Stellarium use your settings?
