### ISSUE TITLE
altitude of Sun's lower limb

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2019]
### Expected Behaviour

Ho does not correspond to altitude as reported by Pointer Coordinates tool.

### Actual Behaviour

- location: S 19° 56' 42.00" W 29° 45' 32.00" 0m (! Southern hemisphere)
- time: 2021-11-08 19:31:41Z
- target: Sun
- refraction settings: std atm

lower limb as reported by Pointer Coord: (lower right of screenshot): **alt = 8d01m01s**

as reported by the nav plugin : lower limb is higher than Sun center; plus, the values seem strange; the offsets seem to be 1/2 SD rather than 1 SD?

Sun
Magnitude: -26.76 (reduced to -25.43 by 6.70 Airmasses)
RA/Dec (J2000.0):
14h55m22.54s/
-16°42'50.0"

Az./Alt.:
+255°01'02.4"/
**+8°16'51.9"**
(apparent)

Ho:
**+8°24.9'**
(lower limb)
Hc:
+8°10.5'

Rise:
7h14m
Transit:
13h43m
Set:
20h12m

Distance: 0.991 AU (148.202 M km)
Light time: 0h08m14.3s Apparent diameter: +0°32'16.51"
Diameter: 1391400.0 km

![image](https://user-images.githubusercontent.com/3529789/140811633-3e9969c6-b117-4864-ae23-ac2a96ac2541.png)

### System
* Stellarium version: 0.21.2
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by axd1967** [comment]
@A-j-K could you have a peek at this?

**Comment by A-j-K** [comment]
> @A-j-K could you have a peek at this?

I'll try and look later this week. I have a new computer that means I'll need to rebuild my dev env :(

**Comment by axd1967** [comment]
Here is another example: a positive Ho while the apparent alt is negative

![image](https://user-images.githubusercontent.com/3529789/140813992-21523fb4-72dc-48c4-98ad-7400efea5406.png)

**Comment by A-j-K** [comment]
Pretty sure I already know what the problem is and I'm guessing you do too ;)  Just installing VS, will checkout shortly

**Comment by A-j-K** [comment]
@axd1967 please see https://github.com/Stellarium/stellarium/pull/2021
