### ISSUE TITLE
Revised Julian calendar

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2028]
According to WP page [Revised Julian calendar](https://en.wikipedia.org/wiki/Revised_Julian_calendar) (see adoption section also)  adding this calendar into Calendars plugin may be helpful. The algorithm of calendal calculations and accuracy info are exist in WP.

**Comment by gzotti** [comment]
ACK. Yes, whenever I get again to continue with this plugin. Thanks for the pointer!
