### ISSUE TITLE
I don't understand...

### ISSUE THREAD

**Issue by nicksave-code** [Stellarium/stellarium#2034]
![WhatsApp Image 2021-11-12 at 21 25 19](https://user-images.githubusercontent.com/43389593/141602425-a25df11f-28c9-4156-b37a-fe51abae8a14.jpeg)

**Comment by gzotti** [comment]
Although this is the place to report issues in Stellarium, not stellarium-web, this is trivial to identify as mirror reflection in the underlying photographic survey.
