### ISSUE TITLE
Simulation of Martian polar ice caps

### ISSUE THREAD

**Issue by worachate001** [Stellarium/stellarium#2040]
There is no polar ice caps displayed on Mars 

The program can calculate direction of the axis relative to the Sun, so it can predict seasonal events and changing polar ice on Mars.
As far as I know, the extent of polar ice caps change according to the season. There must be a way to predict the lowest latitude covered by ice (on both poles).

I'm wondering if we can draw something on Mars surface or changing texture of Mars on the fly to simulate the extent of polar ice caps?

Below is an example of what Stellarium should be able to do (I did it by changing the texture of Mars to a new one with simulated ice on it).

![mars-ice-cap](https://user-images.githubusercontent.com/41257965/141769169-d661a1e5-15c5-408a-9a85-d049e2a6809d.png)

**Comment by gzotti** [comment]
Currently there is no way to modify a planet texture while running the program. This could be changed, though.
The other problem is identifying a model that could be implemented. It is not switching between two textures but either have a series (~5?) or even allow modification of the texture. The same is true for seasonal changes on Earth seen from the Moon, sun spots, or motion in Jupiter's belts - the planets just look like glass marbles.  Contributions welcome.

**Comment by worachate001** [comment]
Time variations of Mars' gravitational field and seasonal changes in the masses of the polar ice caps
https://dspace.mit.edu/handle/1721.1/74244

Look at Fig.10, this may be useful in the future.

![marspolarcaps](https://user-images.githubusercontent.com/41257965/150623182-6dd137df-1baf-45dc-b730-68c8e516570f.png)

**Comment by gzotti** [comment]
That's a start, thanks. Meanwhile we can exchange textures during runtime. Now somebody just find a way to patch the standard Mars texture with white zones, triggered by some evaluation and change of Ls. I think a constant "latitude overlay" should be acceptable.

**Comment by worachate001** [comment]
We can change the texture of any planets now, right? But I still have to figure out how to do it. It would be awesome if we have this feature before Mars opposition in December 2022.

**Comment by gzotti** [comment]
The planet texture would have to be kept as QImage, a picture rectangle. Then a copy is made, and based on Ls the upper and lower regions of it must be painted white. Then this texture is applied to Mars. Probably this should be done by a new class that closely communicates with SolarSystem.

**Comment by alex-w** [comment]
Some time ago I'm added scriptable methods for replacing textures of the planet on-the-fly: https://github.com/Stellarium/stellarium/blob/2c2f701464f7da4e4eba37470f7f7c560c296756/src/core/modules/SolarSystem.cpp#L348

**Comment by gzotti** [comment]
Actually, it may even be simpler to do that in the planet fragment shader. It's just "set to white if texture coordinate is larger than yS" (or smaller than yN). Maybe with a small transition zone.

**Comment by gzotti** [comment]
Look into #2220!
