### ISSUE TITLE
Adding references in constellation names file results in parse error

### ISSUE THREAD

**Issue by kajaji** [Stellarium/stellarium#2055]
In building records in _constellation_names.eng.fab_ and adding references like:
0100 "الفرقدان" _("The two oryx calves") 1,2,3,4
I get this message in the _log.txt_ file:
**ERROR - cannot parse record at line 1 in constellation names file "C:\\Users\\kaaaj\\AppData\\Roaming\\Stellarium\\skycultures\\arabic\\constellation_names.eng.fab" : "0100 \"الفرقدان\" _(\"The two oryx calves\") 1,2,3,4\n"**
while I beleive I follow the specs in the user guide.

Adding similar references in the _star_names.fab_ passes without issues.

Is the issue here?
https://github.com/Stellarium/stellarium/blob/51874c862a07f1b36c9f16dedff9fb537456d855/src/core/modules/ConstellationMgr.cpp#L822

**Comment by gzotti** [comment]
Indeed. It seems commas are currently not allowed in the regular expression. These constellation comments are not yet in use, but are important assets in the future. Please hold back a few weeks until this is available in a beta. It should certainly be possible in 0.21.3.
