### ISSUE TITLE
Impossible to show ephemeris of Pluto

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#2062]
It appears that it is impossible to show an ephemeris of Pluto. I believe it is related to the "orbit_good" problem, but this is strange since Pluto is included in the DE440/DE441 ephemerides, meaning fairly accurate positions over many millennia.

**Comment by alex-w** [comment]
The [fix](https://github.com/Stellarium/stellarium/commit/45fb7037b3dd398552921f68399055da2686bb21) for Pluto is not in the current beta yet.

**Comment by gzotti** [comment]
Yes, I have discovered Pluto was excluded somehow and fixed it a few weeks ago. 

Pluto has always been an special case. Without DE*, the built-in algorithm for Pluto is valid (provides usable positions) only for 1885-2099. However, for the user there is no way to update elements, so it's not useful to show an update warning. 

There is IMHO no more to do now. Can we close this as done?
