### ISSUE TITLE
Segmentation fault (core dumped) on FreeBSD on Raspberry Pi 4

### ISSUE THREAD

**Issue by Pavel-II** [Stellarium/stellarium#2069]
### Expected Behaviour
Start stellarium 
### Actual Behaviour
Fail start with error
Segmentation fault (core dumped)

run: gdb ./stellarium
`...
[New LWP 100459 of process 6742]
LandscapeMgr: initialized Cache for 100 MB.

Thread 1 received signal SIGSEGV, Segmentation fault.
Invalid permissions for mapped object.
0x000000004ec167b8 in ?? () from /usr/local/llvm12/lib/libLLVM-12.so
`
### Steps to reproduce

[buildlog.txt](https://github.com/Stellarium/stellarium/files/7613769/buildlog.txt)
[home_stlrm_.stellarium_log.txt](https://github.com/Stellarium/stellarium/files/7613770/home_stlrm_.stellarium_log.txt)
[runlog.txt](https://github.com/Stellarium/stellarium/files/7613771/runlog.txt)

### System
* Stellarium version: build from src Stellarium 0.21.2-dd006bc [master] 
* Operating system: FreeBSD 13.0-STABLE
* Graphics Card: Raspberry Pi 4 B: Broadcom VideoCore VI 500 MHz
* Screen type (if applicable): Dell Inc 20" 1680x1050

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Stellarium runs on Raspberry Pi 4 with Raspberry OS (Raspbian). If you can solve the problem with FreeBSD (unsupported), we can accept a patch.

**Comment by alex-w** [comment]
@Pavel-II интересно FreeBSD/arm64 использует OpenGL или OpenGL ES?

**Comment by koobs** [comment]
@Pavel-II 

1) Does the `astro/stallarium` FreeBSD Ports/Package [1] (currently 0.22) build, link and run on your aarch64 machine? 

2) Also, if you haven't already, make sure `stable/13` is up to date on the latest revision (please mention your `uname -a` version too), rebuild/update if it is not and test reproduction of the issue again.

3) If you're running a non-GENERIC kernel, include your kernel configuration
4) If `/etc/sysctl.conf` is not empty, include its contents
5) If /etc/make.conf is not empty, include its contents

[1] https://www.freshports.org/astro/stellarium

**Comment by alex-w** [comment]
This is a good task for the community to participate in the contribution into Stellarium. Who wants to help us?

**Comment by gzotti** [comment]
@Pavel-II please respond. Else we will close this issue.

**Comment by MikaelUrankar** [comment]
No segfault for me with stellarium-0.22.2 on an honeycomb / AMD Radeon RX 550 hardware, FreeBSD -CURRENT.
