### ISSUE TITLE
User Guide for 0.12 LTS

### ISSUE THREAD

**Issue by Symbian9** [Stellarium/stellarium#207]
### Expected Behaviour

Add *User Guide* for latest release of `0.12` branch (`v0.12.4` and later) on GitHub.

### Actual Behaviour

Currently latest version of `0.12` branch is `v0.12.9` hosted fully on GitHub, but it's release has no attached PDF of *User Guide*:

- https://github.com/Stellarium/stellarium/tree/0.12
- https://github.com/Stellarium/stellarium/releases/tag/v0.12.9

Latest *User Guide* for `0.12` branch exists only for `v0.12.3` and it still hosted only on SourceForge:

- https://sourceforge.net/projects/stellarium/files/Stellarium-user-guide/

In same time sources and PDF's of *User Guide* for Stellarium `0.16` and later now added to each release on GitHub:

- https://github.com/Stellarium/stellarium/tree/master/guide
- https://github.com/Stellarium/stellarium/releases/download/v0.16.0/stellarium_user_guide-0.16.0-1.pdf
- https://github.com/Stellarium/stellarium/releases/download/v0.16.1/stellarium_user_guide-0.16.1-1.pdf
- https://github.com/Stellarium/stellarium/releases/download/v0.17.0/stellarium_user_guide-0.17.0-1.pdf
- https://github.com/Stellarium/stellarium/releases/download/v0.18.0/stellarium_user_guide-0.18.0-1.pdf

### System

- Stellarium version: v0.12.4..v0.12.9

### Reference

- http://stellarium.sourceforge.net/wiki/index.php/Category:User%27s_Guide
- http://stellarium.sourceforge.net/wiki/index.php/Stellarium_User_Guide
  - http://barry.sarcasmogerdes.com/stellarium/stellarium_user_guide-new.pdf
- https://launchpad.net/stellarium/0.12
- http://stellarium.org/doc/0.12/

**Comment by gzotti** [comment]
There is no user guide repository in the 0.12 sources, it was a different project and thus the separate download. 
There is also no user guide at all in 0.13 and 0.14 series.
There will be no update to the old user guide for the 0.12 series. Unless you write it.

**Comment by Symbian9** [comment]
> There will be no update to the old user guide for the 0.12 series. Unless you write it.

I want write it using as base PDF of *User Guide for Stellarium 0.12.4* by *Barry Gerdes*, but link is dead

- http://barry.sarcasmogerdes.com/stellarium/stellarium_user_guide-new.pdf

Also I want use latest updates on wiki, but look like all sub-pages unavailable now.

- http://stellarium.sourceforge.net/wiki/index.php/Stellarium_User_Guide

Are there backup of wiki version of User Guide?

**Comment by gzotti** [comment]
As you can read in the dedication in the User Guide for V0.15, not only the link is dead.
What is the point in this mission? Version 0.12 was superseded four years ago, and 1000x more people have downloaded the current version than 0.12.9. The old users guide reasonably well describes 0.12.

**Comment by Symbian9** [comment]
> What is the point in this mission?

I want write manual for "Stellarium-android" 1.24.x (extended fork of last open sources of "Stellarium Mobile" from Noctua Software, that  based on 'desktop' Stellarium 0.12)

- https://github.com/chengxinlun/Stellarium-android/
  - https://github.com/chengxinlun/Stellarium-android/releases/tag/1.24.4

I interested in Stellarium 0.12 for desktop with Linux (many people can't use Stellarium 0.13 due to increased hardware requirements), and in "Stellarium-android" for mobile with Android.

P.S.: I'm in touch with developer of "Stellarium-android", and he already implement few my feature request, as result "Stellarium-android" 1.24.x can use config files from Stellarium 0.12.x

- https://github.com/chengxinlun/Stellarium-android/issues/2

**Comment by Symbian9** [comment]
> As you can read in the dedication in the User Guide for V0.15, not only the link is dead

Yes, I know about *Barry Gerdes*... R.I.P.

Anyway, I just found archived PDF of *"User Guide for Stellarium 0.12.4 by Barry Gerdes"*

![User Guide for Stellarium 0.12.4](http://i.imgur.com/OFq36Fq.png)

**Comment by gzotti** [comment]
OK, did not know about this fork. We collected the bits and pieces of the HTML/wiki manual and created a new one for 0.15. I have never seen the old sources for the 0.12 PDF. AFAIK it has been written in LyX, a LaTeX WYSIWIG environment. 

So, it seems you can either take the current guide (maybe sources from V0.15) and delete what is not in 0.12, or copy-paste text from that 0.12.4 guide.

**Comment by Symbian9** [comment]
> So, it seems you can either take the current guide (maybe sources from V0.15) and delete what is not in 0.12, or copy-paste text from that 0.12.4 guide.

Yeah, I also think about that ;-)

Also, is there page where described additional changes from `v0.12.4` to `0.12.9`?

**Comment by Symbian9** [comment]
> OK, did not know about this fork.

@gzotti, this year I twitted it for `@StellariumDev`... Twice... :-/

- http://twitter.com/app4soft/status/957628342597046273
- http://twitter.com/app4soft/status/965731918712049667

**Comment by gzotti** [comment]
At least 0.12.9 includes a Change log (see Windows start menu).

**Comment by gzotti** [comment]
Well, I don't tweet...

**Comment by Symbian9** [comment]
> see Windows start menu

As I [said](https://github.com/Stellarium/stellarium/issues/207#issuecomment-399224380) above, I'm Linux user.

In `ChangeLog` on GitHub there no any info about `v0.12.5` .. `v0.12.9`

- https://github.com/Stellarium/stellarium/blob/master/ChangeLog

**Comment by gzotti** [comment]
Sure, because 0.13 succeeded 0.12.4. But also your Linux package for 0.12.9 should contain a Changelogs file. Or check the individual release sites like https://launchpad.net/stellarium/+milestone/0.12.9.
