### ISSUE TITLE
Abell 6 coordinates are wrong

### ISSUE THREAD

**Issue by seymoreStars** [Stellarium/stellarium#2071]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Are they? What do you expect to find, and where? 
Note that Stellarium includes Abell's ACO catalog of galaxy clusters, not the planetary nebulae.

**Comment by seymoreStars** [comment]
My mistake, I was searching for Abell-6 planetary nebula. I guess there is an Abell-6 galaxy cluster also?

Steve

________________________________

**Comment by gzotti** [comment]
Yes. As said our "Abell" is Abell's ACO catalog.
