### ISSUE TITLE
Further issues with orbit_epoch...

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#2082]
There appear to be further issues with the _orbit_epoch_. When importing from sources through the Solar System Editor, we learn that comet C/2021 A1 (Leonard) has an obsolete orbit as of 2021, which is highly unlikely, since the comet was discovered this very year. This unfortunately means that the comet won't appear in the sky unless the user manually adds a proper epoch to the comet.

Looking at what is actually imported through the MPC database, we learn that the parameter _orbit_epoch_ is completely omitted.

**Comment by gzotti** [comment]
I have solved this a few days ago. The SSE plugin did not feed the epoch. Please build from sources, or wait for the next beta.

**Comment by Atque** [comment]
Thank you @gzotti, I have not been following the project too keenly lately. This issue can be closed.

**Comment by Pharnaces** [comment]
I just loaded the most recent Stellarium version (1.1).  I am still having problems with the epoch in a comet orbit.  I put in an orbit with epoch J2000.0 (2451545.0) and get the same exact orbit if I put in the orbit epoch as a date thousands of years old
