### ISSUE TITLE
ocular view: mouse dragging should be just as effective

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2086]
When enabling Ocular view, the mouse becomes restricted to object selection followed by a jump to the selected object; the user can only move the view via cursor keys.

Instead, normal mouse dragging should be possible.

**Comment by alex-w** [comment]
Mouse navigation disabled in eyepiece mode by design to avoid set the wrong FOV

**Comment by axd1967** [comment]
How can a wrong FOV be set by mouse?

**Comment by axd1967** [comment]
just found, related: #1317
there is no objective reason given there, other than "by design", "has been implemented on purpose in 2010,  Just get used to it." -> this is not how software evolves

https://user-images.githubusercontent.com/3529789/144810760-c1f6f6db-189a-4e44-a218-397dce1acae6.mp4

**Comment by axd1967** [comment]
If the problem is a "wrong FOV" by "mouse", then the problem is rather "wrong FOV by scrollwheel"; this is a matter of not touching the scrollwheel, not by artificially restricting the user.

**Comment by axd1967** [comment]
As the conversation is locked as "too heated" in #1317, I'll state my use case here:

While searching for C/2021 A1, I needed to fine-move the ocular view in order to perform a star hopping. The cursors did not provide a sufficiently fluid way to do this.

I don't know what the impact would be for tablet users such as @astro-martin , but desktop users should not find this a problem.

**Comment by alex-w** [comment]
> just found, related: #1317 there is no objective reason given there, other than "by design", "has been implemented on purpose in 2010, Just get used to it." -> this is not how software evolves

Alex, sorry, but you do not known how software evolves in principle, because you are ignore physical laws and objective reality by no objective reason. As proof for working the tool A you are share example for how works the tool B. Other example in this issue: you are ask how zooming by mouse may caused the changing of FOV. Sorry, but this is elementary knowledge and elementary logic.

**Comment by axd1967** [comment]
@alex-w **please stop insulting me in public**. you are here **publicly** (and repeatingly, _ad nauseam_, for reasons that you cannot provide despite me repeatingly asking for them) accusing me of

- being a professional software engineer, not knowing how software evolves
- ignoring physical laws
- ignoring "objective reality" (whatever that means)
- lack of elementary knowledge 
- lack of elementary logic

you are always starting this kind of war, I'm so tired of it because I always try to stay nice, but I will **not** accept being ridiculed.

my arguments are always and everywhere (because **this is a recurring theme** in our discussions) the same: as long as there are no theoretical or mathematical limits, there is no reason to impose restrictions to the user. it is the responsibility of the user to correctly interpret the behaviour; it is the responsibillity of the developer to protect the user from actions that could lead to problems.

@xalioth @gzotti @Atque @treaves @Jocelyn1109 please help me here.

**Comment by alex-w** [comment]
@axd1967 has been banned due permanent insulting behaviour
