### ISSUE TITLE
stellarium-0.21.2-12d6720 "4%" in info string

### ISSUE THREAD

**Issue by kajaji** [Stellarium/stellarium#2095]
### Actual Behaviour
a "4%" string appears in the info at the end of "Solar Az./Alt: ..." string. Also for "Lunar Az./Alt: ...".
This "4%" disappears when the option for formatting output is selected.

### Steps to reproduce
Select any star or planet with info for "solar and lunar positions" box 
![trbug2](https://user-images.githubusercontent.com/34771982/145726488-a74b6cfc-6b1c-4792-860d-7b2cce1e80da.JPG)
checked
### System
* Stellarium version: <stellarium-0.21.2-12d6720>
* Operating system: <Windows 10>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Oops, thanks!
