### ISSUE TITLE
Two obsolete skycultures included in stellarium-0.21.2-12d6720

### ISSUE THREAD

**Issue by kajaji** [Stellarium/stellarium#2096]
### Actual Behaviour
Almagest and Arabic Moon stations skycultures were included in the package of latest beta stellarium-0.21.2-12d6720.

Almagest is obsoleted by _Greek (Almagest)_ and Arabic Moon stations is obsoleted by _Arabic Lunar stations_.

### Steps to reproduce
Starlore tab, skycultures list

skycultures folder of Stellarium.
### System
* Stellarium version: <stellarium-0.21.2-12d6720>

**Comment by alex-w** [comment]
Did you have installed version 0.21.2-12d6720 as upgrade to previously installed Stellarium?

**Comment by kajaji** [comment]
Yes.
Sorry my mistake.
I did reinstall with a new folder. No issue.
Thanks
