### ISSUE TITLE
Date Time window does not scale for UHD display in Windows 10

### ISSUE THREAD

**Issue by mkkroeger** [Stellarium/stellarium#210]
HP Spectre x360 15 running Windows 10 Home
Display Resolution 3840 X 2160 (Recommended), Scaling 250% (Recommended)
Stellarium 0.18.0 64 bit
Most everything seems to look and work OK (at least so far). However, the Date Time window does not scale properly and I can only see the top date part of the window. I cannot see the bottom time part and I cannot rescale the window (or I do not know how to rescale it)
I have attached a screenshot
![screenshot](https://user-images.githubusercontent.com/40503359/41798463-c09f13c8-763b-11e8-907d-a9f7d40a01c2.jpg)
![image](https://user-images.githubusercontent.com/40503359/41798481-cda5ab18-763b-11e8-8ca6-82e7410612c6.png)

Other applications work OK and I do not want to change resolution. This happens with either the Intel or NVidia graphics.

Thanks

**Comment by gzotti** [comment]
Sure, we have 4k problems. No, some users have 4k problems. No developer has a 4k Windows system to do anything about it, though. Patches welcome. 
However, your screenshot looks normal and complete.

**Comment by mkkroeger** [comment]
Thank you for the quick response. Yes, everything seems normal and complete
except I cannot adjust the time. I guess a scalable window would be nice.
Thanks again

**Comment by mkkroeger** [comment]
Wait, I rebooted again and now it's working. I can change the time

**Comment by mkkroeger** [comment]
After installing the latest version, 0.18.3, this problem has returned. Fiddling with scaling does not help or makes everything worse. Rebooting does not help either. The window again looks as in the screen capture above. Everything else appears OK. A scrollbar on the date/time window would help.

**Comment by mkkroeger** [comment]
I forgot to add, no other settings have been adjusted between the previous issue and now. Using either the the Intel or NVidia graphics (up-to-date drivers) results in the same appearance. Thanks in advance.

**Comment by gzotti** [comment]
Your screenshot shows both date and time. What is the problem?

**Comment by mkkroeger** [comment]
That was an earlier picture. But, never mind, my fiddling with scaling and
rebooting fixed this again. 4K displays seem a lot finickier. Thanks for
your quick response.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
