### ISSUE TITLE
ocular plugin

### ISSUE THREAD

**Issue by Thierry45** [Stellarium/stellarium#211]
Before reporting an issue around graphics artifacts like missing menu buttons, strange colors, Moon not rendered, or similar, 
*please make absolutely sure* you are running the latest graphics drivers for your graphics card. 
95% of graphics problems are solved this way.

Before reporting an issue, please *absolutely make sure* to check the closed issues 
(https://github.com/Stellarium/stellarium/issues?q=is%3Aissue+is%3Aclosed) 
whether it has been reported and solved/closed already! Don't report in this case.

Also look into the wiki (https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version 
and https://github.com/Stellarium/stellarium/wiki/FAQ) 
and check if you are attempting to report a known issue. Don't report in this case.

Also look into the User Guide before reporting unexpected but correct behaviour. Don't report in this case.

If you want to report a feature wish, delete these template lines above and below, and fill in. 

If you want to report a bug, please make sure to update and verify the bug still exists in the current version. 
In this case please also check current beta builds from http://stellarium.org
If bug still persists, delete text above down to and including this line and fill in:

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by Thierry45** [comment]
when I change the ocular the wiew does not change nor the FOV. Magnification changes (x20, x40, x112 for the 3 oculars I have described) but not the view. I am running v0.18.0 64 bits on Windows 10 family 64 bits

**Comment by alex-w** [comment]
Are you have disable option "Scale image circle" in the Oculars plugin?

**Comment by Thierry45** [comment]
Hello Alexander

 

It can be in the  “able” or “disable” position and it does not change the result

Example:

I simulated a 80/480 telescope with 3 different oculars: 28 mm, 14 mm, 5 mm

 

Below 28 mm



 

Below 14 mm



 

Below 5 mm



 

Below is the ocular plugin setting dialog box for general with the circle scale change abled. If I disable it, I have excalty the same images…



 

Ocular tab



 

Telescope tab



 

Thanks for your help!

 

Regards,

 

Thierry

 

De : Alexander Wolf <notifications@github.com> 
Envoyé : samedi 30 juin 2018 08:16
À : Stellarium/stellarium <stellarium@noreply.github.com>
Cc : Thierry45 <thierry@beauvilain.fr>; Author <author@noreply.github.com>
Objet : Re: [Stellarium/stellarium] ocular plugin (#211)

 

Are you have disable option "Scale image circle" in the Oculars plugin?

**Comment by gzotti** [comment]
Please update and re-check.

**Comment by alex-w** [comment]
The problem was found and fixed, the fix will be available in release 0.19.3

**Comment by axd1967** [comment]
@alex-w does this commit solve following issue : https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#oculars-plugin-sensor-size-or-ocular-magnification-scaling-seems-way-off-v0183 ?

**Comment by alex-w** [comment]
Yes, it should solve described problem.
