### ISSUE TITLE
Stellarium 0.12.1 With Issue With shadow Ambient

### ISSUE THREAD

**Issue by cork124** [Stellarium/stellarium#2112]
To see what I mean, set the time to 2021-12-20, 13:19:36 (PM) (location on earth is irrelevant), Look at the values in the infostring; the LANDSCAPE on nstellarium 0.12.1 not simulates a shadow ambient  the photos here to you  
![photo-hotel](https://user-images.githubusercontent.com/90666924/146816066-db01b833-acb9-4805-bf48-4fc4de12bc19.jpg)
![image](https://user-images.githubusercontent.com/90666924/146816802-6194bd24-be98-4f86-b077-8905c3e573b7.png)

**Comment by alex-w** [comment]
Please use 3D sceneries to modelling the shadows. The landscapes are just photographies.

**Comment by gzotti** [comment]
And this is our special person with special requirements from Brazil.
