### ISSUE TITLE
Screenshot setup doesn't work. Can't set the directory for screenshot

### ISSUE THREAD

**Issue by JMcPeak3373** [Stellarium/stellarium#2129]
__When I go into settings and try to set the directory for screenshot, STELLARIUM will freeze for about 10 seconds, then crash and exit out. I am running the latest version (Stellarium 0.21.3). I am using the following:

Operating system;
Kernel: 5.11.0-402110311031-generic x86_64 bits: 64 compiler: N/A Desktop: Gnome 3.36.9 
           wm: xfwm4 dm: GDM3, LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 

Hardware;
Type: Laptop System: Dell product: Precision M6800 v: 00 serial: <filter> Chassis: 
           type: 9 serial: <filter> 
Topology: Quad Core model: Intel Core i7-4810MQ bits: 64 type: MT MCP arch: Haswell 
           rev: 3 L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 44701 
           Speed: 3734 MHz min/max: 800/3800 MHz Core speeds (MHz): 1: 3596 2: 3666 3: 3637 
           4: 3592 5: 3688 6: 3681 7: 3630 8: 3594 
Graphics:  Device-1: Intel 4th Gen Core Processor Integrated Graphics vendor: Dell driver: i915 
           v: kernel bus ID: 00:02.0 chip ID: 8086:0416 
           Device-2: NVIDIA GK104GLM [Quadro K4100M] vendor: Dell driver: nvidia v: 450.156.00 
           bus ID: 01:00.0 chip ID: 10de:11b7 
           Display: x11 server: X.Org 1.20.13 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa tty: N/A 
           OpenGL: renderer: Quadro K4100M/PCIe/SSE2 v: 4.6.0 NVIDIA 450.156.00 direct render: Yes

**Comment by alex-w** [comment]
Please check https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#Crash_of_Stellarium_on_Linux_Mint_when_opening_or_saving_files

**Comment by JMcPeak3373** [comment]
So it's not a file opening or saving issue. It only happens when I try to set the screen shot directory in the TOOLS. I've been able to use my desktop screen capture to capture the stellarium screen without an issue. It used to work fine about 4 or 5 versions back. Here is a screenshot of the dialog that is causing issues
![Screenshot_2021-12-25_10-09-29](https://user-images.githubusercontent.com/32822412/147389127-d266bc4a-5a55-4dcb-9559-e8cf253c8bf6.png)
.

**Comment by alex-w** [comment]
28 Sep 2020 you reported about same problem and we don’t catch any feedback after report. The file dialog for opening file, saving file or choosing directory is same file dialog. Just check the instructions from FAQ, because this is well-known problem for Mint.

**Comment by gzotti** [comment]
There is something weird also on Ubuntu Mate (20.04LTS). I dual-boot this on my tiny Atom netbook. (Minimal usable system. It's far more efficient than the phone-home-prone w10).  
It seems calling any system dialog (select screenshot dir, select a color) opens an extra window, but this window is not filled with the ui, it just shows a copy of the underlying graphics. No crash, but we just cannot select dirs or colors. I followed the FAQ entry, no change.

**Comment by alex-w** [comment]
@gzotti could you try `export QT_QPA_PLATFORM=wayland && Stellarium` and `export QT_QPA_PLATFORM=xcb && Stellarium`?

**Comment by JMcPeak3373** [comment]
> @gzotti could you try `export QT_QPA_PLATFORM=wayland && stellarium` and `export QT_QPA_PLATFORM=xcb && stellarium`?
> 
> Or (it's better) `stellarium -platformtheme xcb` (and `stellarium -platform xcb`)

Hello,

   Before I had a chance to read your message in my E-mail, I saw there was an UPDATE to STELLARIUM and I installed it, and now everything works again. I was able to set my saving directory and save a screen shot of the current sky I Hi_res without issue. I appreciate your assistance.

**Comment by gzotti** [comment]
> @gzotti could you try `export QT_QPA_PLATFORM=wayland && stellarium` and `export QT_QPA_PLATFORM=xcb && stellarium`?

This system has no wayland plugin. xcb works.

> Or (it's better) `stellarium -platformtheme xcb` (and `stellarium -platform xcb`)

These also work. However, setting environment variables has to be done once only.

**Comment by alex-w** [comment]
> These also work. However, setting environment variables has to be done once only.

Yes, but setting environment variables touches all applications, not only stellarium. I can add extra shortcut in the GUI.

**Comment by gzotti** [comment]
I safely assume that these settings apply to all Qt5 based applications on that respective system.
