### ISSUE TITLE
Shortkey for enable / disable survey

### ISSUE THREAD

**Issue by tammojan** [Stellarium/stellarium#213]
Is it possible to toggle showing the latest used survey with some shortkey? I.e. when I press H, a hydrogen sky appears, and when I press H again, I'm back to 'normal' stellarium without any survey.

**Comment by gzotti** [comment]
The Guide answers this on page 16, and you can assign your own hotkeys (section 4.7.1).

**Comment by alex-w** [comment]
Default shortcut for toggle HiPS is Ctrl+Alt+D, but you may change it in Shortcut Editor (Details in Stellarium User Guide).

**Comment by tammojan** [comment]
Apparently my mileage varies, the shortkey does not work. Using it with Stellarium 0.18.1, macos, US International keyboard layout.
