### ISSUE TITLE
Stellarium v0.21.3 AppImage doesn't work

### ISSUE THREAD

**Issue by ivan-hc** [Stellarium/stellarium#2130]
I can't run the program, here you are some error messages while launching the new version (on Debian Testing/Unstable):
#### without libqt5webengine5 
       /tmp/.mount_stella6GPElI//usr/bin/stellarium: error while loading shared libraries: libQt5WebEngineWidgets.so.5: cannot open shared object file: No such file or directory

#### with libqt5webengine5 
        /tmp/.mount_stellaTE5coM//usr/bin/stellarium: /tmp/.mount_stellaTE5coM//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5)
        /tmp/.mount_stellaTE5coM//usr/bin/stellarium: /tmp/.mount_stellaTE5coM//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5Quick.so.5)
        /tmp/.mount_stellaTE5coM//usr/bin/stellarium: /tmp/.mount_stellaTE5coM//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5)
        /tmp/.mount_stellaTE5coM//usr/bin/stellarium: /tmp/.mount_stellaTE5coM//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5WebChannel.so.5)
        /tmp/.mount_stellaTE5coM//usr/bin/stellarium: /tmp/.mount_stellaTE5coM//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5Qml.so.5)
        /tmp/.mount_stellaTE5coM//usr/bin/stellarium: /tmp/.mount_stellaTE5coM//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5QmlModels.so.5)

**Comment by alex-w** [comment]
Where is you taken an AppImage?

**Comment by ivan-hc** [comment]
From https://github.com/Stellarium/stellarium/releases/latest

Exactly https://github.com/Stellarium/stellarium/releases/download/v0.21.3/Stellarium-0.21.3-x86_64.AppImage

**Comment by alex-w** [comment]
Done: https://github.com/Stellarium/stellarium/releases/download/v0.21.3/Stellarium-0.21.3.1-x86_64.AppImage
