### ISSUE TITLE
testing stellarium-0.21.3-1.fc35.x86_64 -   Fedora 35

### ISSUE THREAD

**Issue by tuxedotje** [Stellarium/stellarium#2133]
Errors at start up in Terminal. 

QSocketNotifier: Can only be used with threads started with QThread
Empty translation file for language  "en_US" in section "stellarium-scripts"
StelCore: Invalid timezone name: ""  -- not setting timezone.
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Satellite has invalid orbit: "NO-84" "40654"
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.

**Comment by gzotti** [comment]
> Errors at start up in Terminal.
> 
> QSocketNotifier: Can only be used with threads started with QThread 

not sure

> Empty translation file for language "en_US" in section "stellarium-scripts" 

harmless

> StelCore: Invalid timezone name: "" -- not setting timezone. 

You may want to set some time zone

> qt.gui.icc: Unsupported ICC profile class 70727472 
> QPngHandler: Failed to parse ICC profile 

Some textures are technically problematic. I have fixed this problem and message for the default set on Windows, but cannot say what the PNG library on your OS can do or not do. It should be harmless if the image is sRGB. https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile


>Error in Asterism "TA6" : can't find star with coordinates 2.14697 / 8.55097 
>ERROR reading asterism lines record at line 88 for culture "western" 
>WARNING - asterism abbreviation "TA6" not found when loading asterism names 

**confirmed**

> qt.qpa.wayland: Wayland does not support QWindow::requestActivate() 

Sounds like a Qt implementation issue on Wayland.

> Oculars::validateAndLoadIniFile() found existing ini file version 3.1 

status message, confirms everything is OK.

> Satellite has invalid orbit: "NO-84" "40654" 

reports bad data has been identified for this satellite, and according measures have been taken to deal with it. 

> Dubious result: Landscape "Guereins" not calibrated. Opacity test represents mathematical horizon only.

Informs that technically this default landscape is old and was never properly calibrated. User Guide chapter 7 explains what this means.
