### ISSUE TITLE
No timezone for Nuuk (Godthåb), Greenland

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#2140]
The Greenland capital of Nuuk (Godthåb) seems to have no timezone, instead using the system standard. The problem appears to be that Nuuk is using _America/Nuuk,_ which is now called _America/Godthab_.

**Comment by gzotti** [comment]
Needs an entry in StelLocationMgr.cpp L471. Thanks for the replacement name!

**Comment by alex-w** [comment]
I see no problems in Stellarium 0.21.3 Qt 5.12/macOS 12.1

@Atque please share OS info

**Comment by alex-w** [comment]
> Needs an entry in StelLocationMgr.cpp L471. Thanks for the replacement name!

The entry America/Godthab was added in StelLocationMgr.cpp L463

**Comment by Atque** [comment]
@alex-w Windows 10 64-bit.
