### ISSUE TITLE
Loading problem with Solar System Editor

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2146]
### Discussed in https://github.com/Stellarium/stellarium/discussions/2143

<div type='discussions-op-text'>

<sup>Originally posted by **stephanpls** January  2, 2022</sup>
In the Solar System Editor, tab Configuration file, I encounter these problems:

1. If I try the 'Import and replace the Solar System minor objects to file..' function, I see that the destination file (...Users\AppData\Roaming\Stellarium\data\ssystem_minor.ini) indeed only contains the data I wanted to add. However, Stellarium ignores this data so it is not found with Search (F3) nor in the Location window (F6).

2. If I try the 'Import and add Solar System minor objects from file..' function, I see in the destination file that the data I wanted to add is not added at all.

However, if I add my data manually to the destination file (with Notepad) Stellarium reads it and is working with it as expected. </div>

**Comment by gzotti** [comment]
This file is encoded as UTF16-BOM. The plugin can process only ASCII or UTF-8.

**Comment by alex-w** [comment]
Well, we should check the encoding of opening files and add warning when encoding is unexpected.
