### ISSUE TITLE
Latest stellarium is not installable on raspberry pi OS buster

### ISSUE THREAD

**Issue by mgrouch** [Stellarium/stellarium#2149]
Latest stellarium is not installable on raspberry pi OS buster.

It requires libqtwebengine5, but libqtwebengine5 is not installable via apt.

And previous version of stellarium for bionic disappeared from launchpad.net

I can't find stellarium_0.21.2-upstream1~ubuntu18.04.1_armhf.deb

I think it's a bad practice to delete something that was released. What if someone needs to downgrade?

Thanks

**Comment by alex-w** [comment]
Please check version 0.21.3-upstream3

**Comment by gzotti** [comment]
You must build Stellarium yourself on the Raspberry platform.

**Comment by mgrouch** [comment]
@alex-w 

version 0.21.3-upstream3 installs fine. Thanks
