### ISSUE TITLE
Cannot be built with most recent compilers

### ISSUE THREAD

**Issue by data-man** [Stellarium/stellarium#2157]
### Expected Behaviour
Successful building
### Actual Behaviour
```
.../stellarium/src/external/libindi/libs/indibase/basedevice.cpp: In member function ‘std::string INDI::BaseDevice::messageQueue(int) const’:
.../stellarium/src/external/libindi/libs/indibase/basedevice.cpp:1237:16: error: use of deleted function ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::nullptr_t) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::nullptr_t = std::nullptr_t]’
 1237 |         return nullptr;
      |                ^~~~~~~
In file included from /usr/include/c++/12/string:53,
                 from /.../stellarium/src/external/libindi/libs/indibase/basedevice.h:24,
                 from /.../stellarium/src/external/libindi/libs/indibase/basedevice.cpp:19:
/usr/include/c++/12/bits/basic_string.h:732:7: note: declared here
  732 |       basic_string(nullptr_t) = delete;
```

### Steps to reproduce
* Install gcc-12 or clang-14
* Use CMake as usual
### System
* Stellarium version: https://github.com/Stellarium/stellarium/commit/1236856cff26e667b6b5251935ccbacaeb43ba38
* Operating system: Devuan GNU/Linux 5 (daedalus/ceres) x86_64

**Comment by gzotti** [comment]
Can you build the current INDI distribution with this compiler? If not, please report the issue to the INDI project. I also see many warnings in the INDI sources when compiled with not the very latest compilers.

**Comment by alex-w** [comment]
This plugin (Telescope Control) should be fully rewritten a long time ago. Of course with refactoring the architect and drivers/clients.

**Comment by data-man** [comment]
> Can you build the current INDI distribution with this compiler? 

Sure. INDI library (the latest commit) from https://github.com/indilib/indi compiled without errors.

**Comment by data-man** [comment]
Without `TelescopeControl` plugin all is ok.

**Comment by gzotti** [comment]
@alex-w What is the problem with INDI again? Are there no installable packages that we could depend upon (I see libindi/libindi-dev etc. in Ubuntu), or are there changes in our version in "external"?

**Comment by alex-w** [comment]
The standard library has incompatible changes with our INDI code - e.g. removing some methods which used in our copy. Plus modern INDI has some new external dependencies, which duplicated our code by the fact.

**Comment by gzotti** [comment]
I see these options:
- Use libindi/libindi-dev packages (with their own dependencies) and work around the removal of "some methods" in our code. Not sure how to install those libraries/dev packages on Windows. (Is INDI supported by Windows-based astro software? Sorry, I don't know this code area well.)
- Update our old copy in external/indiclient by a more recent one that can be compiled with most recent compilers, and add those removed functions. This is the far worse option, as it will have to be done every few years. Document these changes!!
 
I cannot say how many users are affected by this. It compiles with MSVS2019, and I have not tried whatever is on Ubuntu 20.4 LTS on WSL.

**Comment by alex-w** [comment]
@data-man Please check the master

**Comment by data-man** [comment]
Fixed, thank you!
