### ISSUE TITLE
New Sky Culture "Andes Septentrionales"

### ISSUE THREAD

**Issue by TaytaAlejandro** [Stellarium/stellarium#216]
Greetings.
After many years we have decoded the four main Andean constellations and are ready to be published, I would greatly appreciate your help.

My regards.

[andes_septentrionales.zip](https://github.com/Stellarium/stellarium/files/2202065/andes_septentrionales.zip)

**Comment by alex-w** [comment]
Thank you very much!

But all translatable data in the culture on Spanish and this is big problem for translators. Could you update constellation_names.eng.fab and prepare description.en.utf8? I see problem with orientation of "El Sapo" also - could you check it too?

**Comment by alex-w** [comment]
Any news for it?

**Comment by alex-w** [comment]
OK, thanks!

**Comment by TaytaAlejandro** [comment]
Greetings.

Dear Alexander, our knowledge in programming has become a great limitation,
so our delay, we appreciate your help and understanding.

We enclose a first version of the "Millenary Astronomy in the Northern
Andes", with the hope of improving it and completing it over time.

The alignment of the frog constellation is correct.

Big hugs.

I enclose the contents of the "Andes_Septentrionales folder.

Andrés Alejandro Ayala Quinatoa
*Tratos Comunicaciones*
         EVOLUCIONEMOS JUNTOS
0998122333 - 0991376650 - +593 (2) 2570 394

**Comment by alex-w** [comment]
Hi!

Apparently your attachment was removed by Github. Could you attach new version through web interface?

Thanks!

**Comment by alex-w** [comment]
Replaced by https://github.com/Stellarium/stellarium/issues/267

**Comment by TaytaAlejandro** [comment]
Best regards.

On September 15, the celebrations for the female new year in the Northern
Andes begin. We would be really happy to be able to recommend colleges and
universities Stellarium download to understand the start and movement of
the solar cycle.

Would there be any chance to get to this date friends?

Thanks for all your great work.
