### ISSUE TITLE
Bug in the latest Mac OS version for negative or BC years.

### ISSUE THREAD

**Issue by Cmathiaz** [Stellarium/stellarium#2165]
I am using the latest Mac OS version (0.21.3) of Stellarium. There seems to be a bug when we set negative or BC dates. For example, 22 March 4000BC should be a vernal equinox point, and the rising sun should be very close to the east at 6 AM. See the first screenshot attached. The precession is not correctly incorporated in the Mac OS version, though the first point of Aries is shown at the correct location. This problem is not present in the iOS version, which works correctly. See the second screenshot attached. I have not checked the Windows version yet. Please check. Thanks.

<img width="1280" alt="mac os version" src="https://user-images.githubusercontent.com/96643980/149051225-00b3d639-1019-4569-9603-9d8af6e624f3.png">
   
![iOS version](https://user-images.githubusercontent.com/96643980/149052325-dbabfe22-6cbe-4791-bee0-511aefcd821a.PNG)

**Comment by Atque** [comment]
Have you taken into account that the Julian calendar is quite inaccurate over millennia? I get the vernal equinox of -4000 at 22 of April in the Windows version.

**Comment by Cmathiaz** [comment]
I thought the dates are in the Gregorian system. In the Gregorian calendar system (year = 365.2425 days), the vernal equinox should come close to March 21. The exact tropical year is 365.2422 days. The calendar has been created and adjusted in the past so that the equinoxes occur on the same days every year. The small 1-day shift comes due to this slight accumulated difference. Anyway, why is there a lot of difference between the iOS and MacOS versions? I will check with the Windows version. The year 1AD gives the correct result.

**Comment by Cmathiaz** [comment]
Julian 22 April 4000BC is Gregorian 21 March 4000BC! I didn't realise that the dates should be in the Julian calendar. The Windows version also gives the vernal equinox on the same correct date 22 April 4000BC.  Sorry for the confusion. Is the calendar system in the iOS version different?

**Comment by alex-w** [comment]
iOS version uses Gregorial calendar always - desktop edition (and macOS version) switches between Gregorial and Julian calendars by historical and scientifical reasons.

P.S. See tooltip hint on your first screenshot

**Comment by Cmathiaz** [comment]
Thanks a lot. Sorry about the confusion.

**Comment by gzotti** [comment]
The calendrical dates used in the desktop version and its accuracies are described in the User Guide. The smartphone and web versions may not be well suited for prehistorical simulation.
