### ISSUE TITLE
Rechange

### ISSUE THREAD

**Issue by InternetWanderer505** [Stellarium/stellarium#2167]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by InternetWanderer505** [comment]
The thing is, about the old way the "solar system observer" was working. The further distance allowed us to see better the structure of the solar system, also, if we could see the planets from up, then we could see the structure of the moon systemtoo better, iknow that not all the planets would be seen from up from that point, but still this is the solar system OBSERVER.
thanks for reading.

**Comment by InternetWanderer505** [comment]
i think i explained the problembetter,but nevermind

**Comment by gzotti** [comment]
As said there, press Alt-End to increase distance. If time allows, other handling of the observers will further improve.
