### ISSUE TITLE
Blink screen on linux

### ISSUE THREAD

**Issue by wadouk** [Stellarium/stellarium#2168]
### Expected Behaviour
Launch and be usable

### Actual Behaviour
Blinking and unusable
https://user-images.githubusercontent.com/787448/149374008-db3c05d4-d025-4e04-9a23-0a329250c73c.mp4

### Steps to reproduce
Just launch stellarium

### System
* Stellarium version: `0.21.1` `0.21.3` or `965210dbd`
* Operating system: `Linux laptop 5.10.89-1-MANJARO #1 SMP PREEMPT Wed Dec 29 18:09:17 UTC 2021 x86_64 GNU/Linux`
* Graphics Card: `Dual : UHD Graphics 630 & GeForce 1650 Mobile`
* Screen type (if applicable): 1920x1080
* Laptop PC : Dell XPS 15 7590 - Core i7

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/7864476/log.txt)

Any advice welcome

Thinks it was OK in November but since the last python upgrade (3.8) at the beginning of the month it was like that
Don't think it's a version dependent problem because was OK before.

**Comment by gzotti** [comment]
Duplicate of #2166, Intel GPU driver problem? Can you force running on the Geforce?

**Comment by wadouk** [comment]
Try the same with [this method](https://github.com/Stellarium/stellarium/issues/1490#issuecomment-820509252) and I only get a small fail window

![image](https://user-images.githubusercontent.com/787448/149380772-63811865-b35a-4d0b-b020-9c18df2a7fd0.png)

[This option](https://github.com/Stellarium/stellarium/issues/1490#issuecomment-820501667) doesn't change anything (blinking)

will re-dig in the graphic card configuration on archlinux

**Comment by alex-w** [comment]
@wadouk could you check solutions from #2127 and #2077?

**Comment by wadouk** [comment]
Doesn't able to check it quickly, seems the same of both. Will see all later. Thanks

**Comment by sincorchetes** [comment]
Hello

Same problem with Fedora Linux Workstation 35 Wayland + GNOME + nouveau
```
stellarium-0.21.3-1.fc35.x86_64
libwayland-client-1.19.0-2.fc35.x86_64
libwayland-server-1.19.0-2.fc35.x86_64
libwayland-egl-1.19.0-2.fc35.x86_64
libwayland-cursor-1.19.0-2.fc35.x86_64
qt5-qtwayland-5.15.2-15.fc35.x86_64
xorg-x11-server-Xwayland-21.1.4-1.fc35.x86_64
kf5-kwayland-5.89.0-1.fc35.x86_64
gnome-session-wayland-session-41.3-1.fc35.x86_64
egl-wayland-1.1.9-3.fc35.x86_64
kernel-5.15.13-200.fc35.x86_64
mesa-libgbm-21.3.3-1.fc35.x86_64
mesa-libglapi-21.3.3-1.fc35.x86_64
mesa-libEGL-21.3.3-1.fc35.x86_64
mesa-filesystem-21.3.3-1.fc35.x86_64
mesa-dri-drivers-21.3.3-1.fc35.x86_64
mesa-libGL-21.3.3-1.fc35.x86_64
mesa-libxatracker-21.3.3-1.fc35.x86_64
mesa-vulkan-drivers-21.3.3-1.fc35.x86_64
mesa-libGLU-9.0.1-5.fc35.x86_64
```
https://user-images.githubusercontent.com/31448043/149550944-79a89d14-f6f8-4a99-8e4a-d432ef27f916.mp4

**Comment by wadouk** [comment]
I Found [something](https://wiki.archlinux.org/title/intel_graphics#AccelMethod) ! 

Create a file `/etc/X11/xorg.conf.d/20-intel.conf`

```
Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"
  Option "AccelMethod" "uxa"
EndSection
```

One day I Will have the courage to install a driver on linux

**Comment by sincorchetes** [comment]
That's not a Stellarium error:

It's not Xorg problem @wadouk , but thanks! Could you confirm there the MESA version is used?

It's a MESA problem, you can still read from here: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5731

**Comment by sincorchetes** [comment]
RPMs available that fixing this problem for Fedora 35.

https://koji.fedoraproject.org/koji/taskinfo?taskID=81298037

**Comment by wadouk** [comment]
Well after some days, the `AccelMethod uxa` is not great, there is : 
 - some lags/low FPS in video 
 - usual work seem slow
 -  not good coming back from energy saving state. 

But yes doesn't seem to be a stellarium or xorg problem but something in the driver level ?

Version of mesa `21.3.2`
Screen of "Add/Remove Software"
![image](https://user-images.githubusercontent.com/787448/150174496-4f6111bb-e813-42c3-9d52-9114ea0b3e52.png)

**Comment by sincorchetes** [comment]
That's a MESA problem.
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5731

Intel uses MESA to get a driver for xorg/wayland.

**Comment by wadouk** [comment]
And seems the next version is good https://gitlab.freedesktop.org/mesa/mesa/-/issues/5731#note_1207753

**Comment by wadouk** [comment]
Updating mesa to 21.3.4 this morning, a little more usable but still blinking.

**Comment by wadouk** [comment]
21.3.5 of mesa this morning and it's great !
