### ISSUE TITLE
Ocular aFoV does not change FoV shown

### ISSUE THREAD

**Issue by gebi** [Stellarium/stellarium#2173]
### Expected Behaviour

i'm not sure how to report this, but it always felt the FoV (field of view) in stellarium ocular view was way off compared to my real telescopes.
The Ocular aFoV also changes the FoV one can see through the ocular, eg. like this
![explore scientific showcase of aFoV for oculars](https://user-images.githubusercontent.com/659/149565555-fb63a78a-488a-45d1-be54-33ace7bb8114.png)

### Actual Behaviour
In stellarium ocular view the real FoV does not change with different ocular aFoV, the image is only zoomed and the displayed FoV changes, but the piece of the sky shown does not change.

21mm 100deg
![21mm 100deg](https://user-images.githubusercontent.com/659/149566261-cbdec238-fba8-45b7-929f-d78613fea49b.png)

vs 21mm 50deg
![21mm 50deg](https://user-images.githubusercontent.com/659/149566303-4d7232b9-1201-4dd5-9646-6f2a9e7c7b38.png)

What's also strange is, that the FOV display at the bottom shows 3.32grad for the 50deg ocular which is wrong, it's only 0.84deg (the 1.66deg shown for the 100deg ocular are correctly calculated but IMHO only half of the view seen in a real telescope is shown)

### Steps to reproduce

create 2 oculars, with eg 21mm focal length and 36.2mm fieldstop
1. 100deg aFoV
2. 50deg aFoV

go to the orion nebular, activate ocular view and change between the 2 oculars to compare the views
look at the stars to see the part of the sky shown.

(i've used a 10" dobson with 1250mm focal length and 250mm diameter, but it happens on every telescope here)
(i've checked both the issues and changelog from 0.20.4 onwards to the latest version for changes that would fix this behaivour and have not found anything, thus this report).

### System
* Stellarium version: 0.20.4-3
* Operating system: debian
* Graphics Card: integrated intel
* Screen type (if applicable): 32" 4k

### Kudos

many thx for this awesome piece of software :smile: !!

**Comment by alex-w** [comment]
@gebi could you share the source of first image?

**Comment by gebi** [comment]
@alex-w sure, i've searched a bit for some representative image, and i think i found the image initially there https://www.bresser.de/Astronomie/Zubehoer/Okulare/EXPLORE-SCIENTIFIC-100-Ar-Okular-25mm-2.html

other tools 
- [https://astronomy.tools/calculators](https://astronomy.tools/calculators/field_of_view/?fov[]=400|209|||1||&fov[]=400|36|||1||&messier=42) i've already prepared a similar FoV example as in the issue above
- [telescopius.com telescope simulator](https://telescopius.com/deep-sky/object/2901/orion-nebula/m-42/diffuse-nebula) has a nice "compare with other FoV" option in eye piece config)

**Comment by gebi** [comment]
@alex-w sry if your question was what's SHOWN in the first image: it's **M43 / orion nebular** (though i would not have recognized it, plate solver astrometry.net found it :)

[EXPLORE-SCIENTIFIC-100-Ar-Okular-25mm-2 on nova.astrometry.net](https://nova.astrometry.net/user_images/5780259#annotated)

**Comment by gzotti** [comment]
@gebi please compare your case to the explanations and example illustrated in Figure 16.17 of the User Guide.

**Comment by gebi** [comment]
@gzotti they look about right and i just checked the newly released 0.22.0 and it seems to fixed there as well, thx :)!

**Comment by gzotti** [comment]
This just means it works as intended. 
The FoV shown in the bottom edge is not the FoV of the ocular circle but of the screen (vertical FoV).

**Comment by gebi** [comment]
i'm not sure what you are talking about...
but if you look at the initial report against `Stellarium version: 0.20.4-3` the behaviour was different, and indeed wrong (as already confirmed).

to recap: because in stellarium 0.20 the image section did not change but it was just zoomed out, which is clearly wrong for aFOV

it seems the behaviour changed, thus fixing this bug in stellarium version 0.22.0
which is awesome but not a bug is just wrong.
