### ISSUE TITLE
Gravity labels for the horizon

### ISSUE THREAD

**Issue by PLANETARAS** [Stellarium/stellarium#2174]
Stellarium 0.21.2 - It would be useful to have gravity labels also on the gradation of the horizon

**Comment by gzotti** [comment]
Yes, the horizon markers don't have gravity labels. And the gravity labels of the horizon line are outside the horizon on a part of the sky, like the cardinal marks.  All three should be repaired.

**Comment by alex-w** [comment]
Apparently I don't understand this report - where is the problem?

**Comment by gzotti** [comment]
Look at them: They are useful in planetaria with vertical fisheye projection and make the labels readable in the projected alt-azimuthal frame. Center view in the zenith, fov~200°. Switch on horizon line with labels, Cardinal points and Compass Marks. 

- Observe that the numbers for compass marks are not rotated to be "gravity labels". 
- Observe that Cardinal markers at the bottom of the screen are "inside" (above) the horizon circle, those at the upper edge are also above the horizon circle, but this means outside the horizon circle, and they won't be shown on the projected planetarium's sky. 
- The labels of the horizon circle show the inverse behaviour: "inside" in the upper part of the screen, below and thus "outside" at the screen bottom.
- Observe ecliptic with labels: some labels are quite far away from their actual points, and are not parallel to the ecliptic, some even intersect. This is mere cosmetic, but still can be improved.

This is no big problem for regular screen use, but I see the problem in the context of planetaria with 180° cutoff horizons.

**Comment by alex-w** [comment]
@gzotti please check the master branch - I’ve added couple fixes for gravity labels (HiDPI and compass marks issues)

**Comment by gzotti** [comment]
Actually the compass marks are almost like the horizon Line from GridlineMgr, just that the numbers are above the horizon. I will add a special line there (no line drawn, but ticks and numbers; proper label orientation is solved there) and remove the SpecialMarkerMgr CompassMarks. For the Cardinals, we have to repeat the same logic to keep the labels within the horizon circle.

**Comment by alex-w** [comment]
> Actually the compass marks are almost like the horizon Line from GridlineMgr, just that the numbers are above the horizon. I will add a special line there (no line drawn, but ticks and numbers; proper label orientation is solved there) and remove the SpecialMarkerMgr CompassMarks. For the Cardinals, we have to repeat the same logic to keep the labels within the horizon circle.

But that line will be invisible when landscape is visible

**Comment by gzotti** [comment]
Aargh, yes. Must check whether it's possible to juggle the priorities.

**Comment by gzotti** [comment]
Bah, indeed that's the killer. OK, more copy&paste...
