### ISSUE TITLE
Location from network problem

### ISSUE THREAD

**Issue by advius** [Stellarium/stellarium#218]
Greetings.
I have a long-term problem with location from network, this log say:

Failure getting IP-based location: 
	 "Error transferring http://freegeoip.net/json/ - server replied: Forbidden"

**Comment by gzotti** [comment]
Ouch. Follow the URL (just click) to see our problem.

**Comment by advius** [comment]
So I look to API.
Thanks for you answer.

**Comment by ZhenyuHe** [comment]
Hi!
I'm now using the latest version 0.21.2 on MacBook.
When I try to "Get location from network", it returns the location with 'N 0° 0' 0.00", E 0° 0' 0.00", 0m'.

The log file says: **Got location ", ,  (0, 0; )" for IP "103.166.247.125"**. However, this IP is not mine. And I was wondering how to solve it.
Thanks!

**Comment by gzotti** [comment]
If this service does not work in your location (or country?), you must switch off the checkbox and set your coordinates manually.

**Comment by ZhenyuHe** [comment]
I see. Thanks for you answer.
