### ISSUE TITLE
i18n enhancement - addition of wikilinks as translator's comments

### ISSUE THREAD

**Issue by leonardcj** [Stellarium/stellarium#22]
Started in https://github.com/Stellarium/stellarium/issues/19

 leonardcj commented 10 hours ago •
@alex-w I'm not a Catalan-speaker, but I am the Translation Team Coordinator for Sugar Labs and I've got a very good Catalan localizer. My confidence in asserting the errors in your PO came after I merged you POs with the one for our little StarChart activity and compared differences. It is also based on the i18n enhancements I made to insert wiki links into the code (and POT file) that allows interwiki look up. see https://github.com/sugarlabs/starchart/blob/master/po/StarChart.pot and the embedded translation comments linking to the relevant pages. I would be happy to collaborate on developing similar links for your program, but I'm pretty busy and I'm starting to think wikidata links may be better than regular wiki links. Reach me at cjl@sugarlabs.org and we can discuss the concept.

@alex-w
Member
alex-w commented 10 hours ago
Thanks for the info! In one side the link on the wiki may be helpful, in other side some astronomical background is required for translators of astronomical software, because some special terms has other translation in common software.

@leonardcj
leonardcj commented 2 hours ago
It is all in how you view it. Consider the wiki link as a means of acquiring some that specialized background and you expand beyond the educated stargazer into a way of creating more of them. You could even leverage it as a way of encouraging more wiki articles to be created in other languages and providing a deeper dive into the celestial objects you display.

How better to point out the special meaning of certain terms than linking to an article explaining it? I don't advocate a link for every entry, just proper nouns (e.g. object names) and terms like Longitude, Latitude, etc that are concepts with wiki pages.

I see you have a long list of country names, basically an embedded copy of ISO-3166-1. I can absolutely help you with that in pretty much all languages. I am leveraging wikidata retrieval e.g .see here for Afghanistan in many languages http://tinyurl.com/yb6lmmky and CLDR Unicode locales (which also contain ISO-3166-1 to a great extent) and the Debian Alioth iso0codes translation project to identify canonical and conflicting translations of those country names. I can add a check of your country names and flag possible corrections and additions.

@alex-w
Member
alex-w commented 2 hours ago
Could you make a patch for countries list please?

@leonardcj
leonardcj commented an hour ago
Sure, a pull request against the PO file is acceptable? Someone else will take care of synching back to Transfex?

Or were you suggesting a translator comment to the wiki page embedded in code to appear in POT after regeneration? Such as I use in https://translate.sugarlabs.org/templates/CLDR_regions/translate/CLDR_regions.pot#filter=incomplete

@alex-w
Member
alex-w commented an hour ago
The pull request may be acceptable. Technically src/translations_countries.h generated by script and I may just add links to wikipedia within script as comments.

@leonardcj
leonardcj commented 15 minutes ago •
Is this sufficient? .xlsx format because github would not accept .csv
Columns

1    sequential integers for ordering
2    List of countries (in order found in src/translations_countries.h) with code markup from file
 3   Corresponding wikilinks, note pre-pended #: is PO file comment mark, not needed in other contexts.

What is your script's input? I can easily add a column for two-letter ISO-3166-1 code if that would help.

I noticed you are missing a few obscure locations (e.g. Diego Garcia), do you want that list?

@leonardcj
leonardcj commented 11 minutes ago
I'm not against trying to properly format this as a patch, it's just that you might be able to do it more easily with higher confidence. If you could do that, I'll take care of going through each language PO file to look for opportunities to pick up new translations. If I do that would you like the new entries default marked as "fuzzy" for human review, although I would just take them as I have very high confidence in them, some people (like me) have strong feelings about machine translation, but I make an exception for the country names in the manner I am deriving them.

@leonardcj
leonardcj commented 4 minutes ago

Shall we start this in a new open issue? This has gone far afield from Catalan typos and orthography.

**Comment by leonardcj** [comment]
[countries.xlsx](https://github.com/Stellarium/stellarium/files/1524035/countries.xlsx)

**Comment by alex-w** [comment]
> I can easily add a column for two-letter ISO-3166-1 code if that would help.

This is will be very helpful

**Comment by leonardcj** [comment]
[countries.xlsx](https://github.com/Stellarium/stellarium/files/1524604/countries.xlsx)

Enhanced spreadsheet, includes some unlisted countries on separate tab.
