### ISSUE TITLE
Stellarium crashes when selecting Surveys on MacOS 12.1

### ISSUE THREAD

**Issue by mbgroen** [Stellarium/stellarium#2215]
### Expected Behaviour
Being able to select a Survey under "Sky and viewing options"

### Actual Behaviour
Stellarium crashes and needs to be "force stopped" when selecting the "Surveys" tab under "Sky and viewing options" from the left side bar.

### Steps to reproduce
Select the "Surveys" tab under "Sky and viewing options" from the left side bar.

### Systems 
* Stellarium version: 0.21.3 (both Mac mini 6.1 and MacBook Pro 12.1)
* Operating system: MacOS 12.1 (both Mac mini 6.1 and MacBook Pro 12.1)
* Graphics Card: Intel HD Graphics 4000 (Mac mini 6.1) and Intel Iris Graphics 6100 (MacBook Pro 12.1)
* Screen type (if applicable): Mac mini: 2560x1080 / MacBook Pro 2560x1600 (Retina)

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/7949611/log.txt)

**Comment by alex-w** [comment]
I cannot reproduce the issue on my Mac. The fetching the list may be slow (it depends by internet speed), but it works.

**Comment by Atque** [comment]
@alex-w It is extremely slow (almost unusable) on the MacBook Pro 2021 compared to Windows. Is it because Stellarium runs with Rosetta?

**Comment by alex-w** [comment]
The first start (a frozen start) need around 1 minute to fetch and show all lists for me. All other starts uses cache and need around 0-1 seconds to create a list. 

macOS 12.1

**Comment by Atque** [comment]
@alex-w I mean displaying the actual survey. Stellarium becomes very slow (FPS < 1) until all tiles have loaded.

**Comment by mbgroen** [comment]
Eventhough MacOS reports the App as "Not responding" when you try to force quit the application, like said by alex-w it is just very slow. After I waited about a minute while the app was unresponsive, it showed the list and functions as expected.
Thanks for your help.
