### ISSUE TITLE
Galactic coordinate system uses wrong range

### ISSUE THREAD

**Issue by stx-chris** [Stellarium/stellarium#2219]
### Expected Behaviour
Galactic longitude ranging from 0° to 360° according to definition [The New I.A.U. System of Galactic Coordinates (1958 Revision) ](https://academic.oup.com/mnras/article/121/2/123/2604025)

### Actual Behaviour
Galactic longitude ranging from -180° to +180°

### Steps to reproduce
- Display "Galactic Grid"

### System
* Stellarium version: 0.21.3
* Operating system: macOS 12.2

**Comment by alex-w** [comment]
Seems supergalactic coordinates have same problem.

**Comment by stx-chris** [comment]
Tried today's snapshot version (0.21.3-d800cdd). The grid view has been fixed, many thanks for the quick fix! But the coordinates delivered by `core.getSelectedObjectInfo()` still show negative longitudes.

**Comment by alex-w** [comment]
> Tried today's snapshot version (0.21.3-d800cdd). The grid view has been fixed, many thanks for the quick fix! But the coordinates delivered by `core.getSelectedObjectInfo()` still show negative longitudes.

Oops... I forget about mapping the data for scripting engine. The fix will be available in next snapshot.
