### ISSUE TITLE
Exported skybox doesn't stitch together in Unity

### ISSUE THREAD

**Issue by Ghostbird** [Stellarium/stellarium#2223]
### Expected Behaviour
Skybox export yields six images that can be imported into Unity as (clamped edge) textures and mapped seamlessly onto the six faces of a Skybox/6 sided material.

### Actual Behaviour
If I map west to front (+Z), east to back (-Z), top to up (+Y), bottom to down (-Y) these all form a seamless whole. However there's no way to map the north and south images. In fact, if I map north to left (+X) and south to right (-X) they seem to be in the right place, but contain partially the same view as the east and west tiles. Which should not be possible given that the script sets a 90° FOV in Stellarium.

### Steps to reproduce
- Open Sellarium
- Press <kbd>Ctrl</kbd><kbd>D</kbd> then <kbd>B</kbd>

### System
* Stellarium version: 0.20.4 (Debian packaged)
* Operating system: Debian 11
* Graphics Card: GeForce GTX 960 with driver version 460.91.03
* Screen type: ASUS PB287Q, 3840x2160 pixels (620.93 x 341.28 mm)

### Logfile 
No relevant logging

## Solution

I found out why this happens, and it's perfectly sensible. To create a cube, you must stitch together four squares. However the skybox script doesn't do anything to facilitate this.
It turns out that I had to go to *Settings*(<kbd>F2</kbd>)»*Tools*, and at the bottom of the window, I could set overrides for the screenshot size. This was even better, since I now could generate screenshots of higher resolutions than my actual screen size.

## Conclusion

This isn't an issue that _must_ be fixed, but a bit more help for the clueless end-user would be nice. I opted to still report this, since I couldn't find this documented anywhere, and this issue can at least serve as documentation.

**Comment by gzotti** [comment]
The StreamingSkybox.cs does that cropping. Alternatively, configure a square custom size as you have found out.
