### ISSUE TITLE
Lunar halo flickers when panning or zooming

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2240]
I'm using Stellarium v0.21.3-221-g98ef806dca. When I get the Moon in the viewport and pan around, so that the Moon moves, its halo flickers. This is especially easy to reproduce when full Moon is at the top of the screen or even above the screen (in this case the atmosphere flickers). This can also be reproduced by simply zooming without any panning.

Below are some screenshots, where I centered view on the Moon and simply scrolled the mouse wheel to change zoom levels. The first three show how the halo exists, then doesn't, then does again. The subsequent two screenshots show how the halo breaks down into stripes. All this with default config, running on GNU/Linux with GeForce GTX 750Ti with `nvidia` binary driver.

![Screenshot - 060222 - 00:34:02](https://user-images.githubusercontent.com/6376882/152659957-61a24dae-8c7b-4026-9023-fd6c34f683ef.png)
![Screenshot - 060222 - 00:34:04](https://user-images.githubusercontent.com/6376882/152659959-e9c45566-32af-4b25-afb2-debb923f4fcd.png)
![Screenshot - 060222 - 00:34:10](https://user-images.githubusercontent.com/6376882/152659960-c211a387-7c2f-4116-a417-85b72be3794c.png)
![Screenshot - 060222 - 00:34:13](https://user-images.githubusercontent.com/6376882/152659962-f2185f27-e4b7-4a0c-abec-b81b126c9cf9.png)
![Screenshot - 060222 - 00:34:16](https://user-images.githubusercontent.com/6376882/152659963-7f16357e-d1a5-40b2-84c7-a897c6a62165.png)

**Comment by alex-w** [comment]
I can confirm issue on macOS too
