### ISSUE TITLE
Decimal degrees can't be entered in the Location dialog

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2247]
I have "Use decimal degrees" option enabled, so in the Location dialog the spinboxes are in decimal degrees. But if I try to enter actual coordinates into these spinboxes, these values are not applied. Subsequent step up/down action on the corresponding spinbox just increments/decrements the old value.

I have a local fix which I'll supply soon. This bug is orthogonal to #2239.

**Comment by gzotti** [comment]
It may be that the "new" QRegularExpression is slightly different from the older QRegExp. But I think @alex-w has fixed this issue in the AngleSpinBox already. Do you see the issue in master or 0.21.3?

**Comment by 10110111** [comment]
No, it doesn't work. The problem is here (below is my fix):
```diff
diff --git a/src/gui/AngleSpinBox.cpp b/src/gui/AngleSpinBox.cpp
index a53d3519a1..195f64b1f0 100644
--- a/src/gui/AngleSpinBox.cpp
+++ b/src/gui/AngleSpinBox.cpp
@@ -241,7 +241,7 @@ double AngleSpinBox::stringToDouble(QString input, QValidator::State* state, Pre
           QRegularExpression::CaseInsensitiveOption);
     QRegularExpression hmsRx("^\\s*(\\d+)\\s*h(\\s*(\\d+(\\.\\d*)?)\\s*[m'](\\s*(\\d+(\\.\\d*)?)\\s*[s\"]\\s*)?)?$",
           QRegularExpression::CaseInsensitiveOption);
-    QRegularExpression decRx("^(\\d+(\\.\\d*)?)(\\s*[\\x00b0]\\s*)?$");
+    QRegularExpression decRx("^(\\d+(\\.\\d*)?)\\s*\u00b0\\s*?$");
     QRegularExpression badRx("[^hdms0-9 °'\"\\.]", QRegularExpression::CaseInsensitiveOption);
     QRegularExpressionMatch dmsMatch=dmsRx.match(input);
     QRegularExpressionMatch hmsMatch=hmsRx.match(input);
```

**Comment by alex-w** [comment]
OK, please add PR

**Comment by worachate001** [comment]
It looks like this issue still exist in the latest master.

I tried to change from
QRegularExpression decRx(u8"^(\\d+(\\.\\d*)?)\\s*\u00b0\\s*?$");
back to
QRegularExpression decRx(u8"^(\\d+(\\.\\d*)?)(\\s*[\\x00b0]\\s*)?$");
seems to fix it.

**Comment by 10110111** [comment]
@worachate001

What OS do you use? For me on GNU/Linux the result is opposite to yours.

**Comment by worachate001** [comment]
Windows 10 and Ubuntu 20.04. They have the same behavior.

**Comment by gzotti** [comment]
U00b0 is simply the degree character "°", or not? Is there any reason not to write this into the regular expression?

**Comment by 10110111** [comment]
@gzotti

It's not 7-bit ASCII, so may show differently on different platforms, also depending on what platform you type it on.

`\u00b0` is the cross-platform way of representation of the corresponding UTF-8 sequence (in addition to the `u8` suffix for the literal). I'm quite puzzled why `QRegularExpression` doesn't accept it on some systems. The only idea is that Qt version matters.

@worachate001

What Qt version do you have?

**Comment by 10110111** [comment]
@worachate001 

Also, could you try wrapping the original literal in `QString::fromUtf8()`? I wonder if `QRegularExpression` took the literals via `QString::toLocal8bit()` in the older Qt versions, which would explain the observations.

**Comment by gzotti** [comment]
As far as I know git is configured to store everything in UTF8, or not? 
At least .git/config has [gui] encoding=utf-8.  But I am not sure why this is given in the gui section only. (I am no git expert.)

But we are using "°" in many places without issues. So 7bit ASCII should be a matter of the past.

**Comment by 10110111** [comment]
> As far as I know git is configured to store everything in UTF8, or not?
> At least .git/config has [gui] encoding=utf-8.

Git doesn't recode any file you push. This config setting only affects things like `git diff` and the like, i.e. for presentation, rather than storage.

> So 7bit ASCII should be a matter of the past.

Unfortunately, no. I recently came across a problem that a literal of `u8"°"`, typed on a Linux machine (thus saved in UTF-8) showed as "Â°" when compiled by MSVC. This was in ShowMySky GUI. I had to explicitly code it as `u8"\u00b0"` to get the intended results on GNU/Linux and Windows platforms.

**Comment by 10110111** [comment]
> But we are using "°" in many places without issues.

This might be due to one bug compensating another bug as long as all the bugs are consistent. Not a good idea to leave it as is, because it requires one to think to introduce some other bugs into new code just to make sure the existing ones are compensated. It's better to fix them.

**Comment by worachate001** [comment]
Windows 10 : Qt 5.12.12
Ubuntu 20.04 : Qt 5.9.7

I hope I understand it right, tried these in Ubuntu...

QRegularExpression decRx(QString::fromUtf8(u8"^(\\d+(\\.\\d*)?)(\\s*\u00b0\\s*)?$"));  <-- it doesn't work

QRegularExpression decRx(QString::fromUtf8(u8"^(\\d+(\\.\\d*)?)(\\s*\x00b0\\s*)?$"));  <-- it works
QRegularExpression decRx("^(\\d+(\\.\\d*)?)(\\s*°s*)?$");  <-- it works

**Comment by 10110111** [comment]
Could you print a debug message like the following (putting it right next to `decRx` creation point):
```cpp
    {
        constexpr char test[]=u8"\u00b0";
        qDebug() << "u8:" << hex << +uint8_t(test[0]) << +uint8_t(test[1]);
    }
    {
        constexpr char test[]=u8"\x00b0";
        qDebug() << "u8x:" << hex << +uint8_t(test[0]) << +uint8_t(test[1]);
    }
    {
        constexpr char test[]="°";
        qDebug() << "char:" << hex << +uint8_t(test[0]) << +uint8_t(test[1]);
    }
```
and then post these lines here? This will let us see what's going on.
On my GNU/Linux system with Qt 5.15.2 I get the following:
```
u8: c2 b0
u8x: b0 0
char: c2 b0
```
The `u8x` one is the bad version (with `\x00b0`) that shouldn't happen.

**Comment by 10110111** [comment]
> Ubuntu 20.04 : Qt 5.9.7

I wonder how you got such an old Qt on Ubuntu 20.04. The official repos provide Qt 5.12.8, see e.g. [here](https://packages.ubuntu.com/focal-updates/libqt5gui5).

**Comment by worachate001** [comment]
I got these, apparently the same with you.

u8: c2 b0
u8x: b0 0
char: c2 b0

**Comment by worachate001** [comment]
> > Ubuntu 20.04 : Qt 5.9.7
> 
> I wonder how you got such an old Qt on Ubuntu 20.04. The official repos provide Qt 5.12.8, see e.g. [here](https://packages.ubuntu.com/focal-updates/libqt5gui5).

You're right. It's actually Qt 5.12.8. I got a wrong one from Anaconda.

**Comment by 10110111** [comment]
Actually, I now see the difference that must be the culprit. For some weird reason my new version doesn't include the parentheses. Could you try with `u8"^(\\d+(\\.\\d*)?)(\\s*\u00b0\\s*)?$"` in the regex?

**Comment by worachate001** [comment]
> Actually, I now see the difference that must be the culprit. For some weird reason my new version doesn't include the parentheses. Could you try with `u8"^(\\d+(\\.\\d*)?)(\\s*\u00b0\\s*)?$"` in the regex?

Yes, it works. I was wondering why the parentheses were removed and tried to put them back.
