### ISSUE TITLE
Text User Interface: light pollution 

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2248]
After switching from Bortle scale one node (Light pollution) in the Text User Interface plugin is broken due slot/signal is deprecated.

**Comment by 10110111** [comment]
Any details on how to reproduce?

**Comment by alex-w** [comment]
1) Enable the plugin
2) Restart Stellarium 
3) See logs or just try change light pollution via TUI

**Comment by 10110111** [comment]
Hmm, I wonder how this should work now. We can of course go the same way as in `LandscapeMgr::increaseLightPollution()`: getting current Bortle scale index, incrementing it and then choosing a luminance for the new index, calling `SkyDrawer::setLightPollutionLuminance()` with it.

But this seems too coarse. Any ideas?
