### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by bigyin362** [Stellarium/stellarium#225]
Before reporting an issue around graphics artifacts like missing menu buttons, strange colors, Moon not rendered, or similar, 
*please make absolutely sure* you are running the latest graphics drivers for your graphics card. 
95% of graphics problems are solved this way.

Before reporting an issue, please *absolutely make sure* to check the closed issues 
(https://github.com/Stellarium/stellarium/issues?q=is%3Aissue+is%3Aclosed) 
whether it has been reported and solved/closed already! Don't report in this case.

Also look into the wiki (https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version 
and https://github.com/Stellarium/stellarium/wiki/FAQ) 
and check if you are attempting to report a known issue. Don't report in this case.

Also look into the User Guide before reporting unexpected but correct behaviour. Don't report in this case.

If you want to report a feature wish, delete these template lines above and below, and fill in. 

If you want to report a bug, please make sure to update and verify the bug still exists in the current version. 
In this case please also check current beta builds from http://stellarium.org
If bug still persists, delete text above down to and including this line and fill in:

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by bigyin362** [comment]
I had Ver 0.13.x on Win 7.  It stopped working.  I deleted it and downloaded Ver 0.18.1 and it's still the same.  I get a "wait" blue circle at the top and bottom of the screen (but not in the middle and there's a greyed out box bottom right labelled 0%.
Thanks

**Comment by gzotti** [comment]
Do you think that #224 is not your problem?

**Comment by bigyin362** [comment]
Having looked at other posts, I've searched for log.txt and config.ini and I can't find either anywhere on my C: drive ?

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/FAQ#i-dont-read-documentation-where-is-that-configini-file-you-are-always-pointing-to
