### ISSUE TITLE
Issue downloading Stellarium to MacOS 11.6

### ISSUE THREAD

**Issue by belray04** [Stellarium/stellarium#2250]
I tried to download Stellarium Mac OS X 10.12 on my Macbook with macOS 11.6 but keep getting an immediate "Stellarium quit unexpectedly" and fails to successfully download. I have attached a screenshot of the pop-up. I don't know how to check which graphics card I have but I'm using a MacBook Air 13. Hopefully someone can help. 
<img width="703" alt="Screen Shot 2022-02-02 at 4 27 57 PM" src="https://user-images.githubusercontent.com/99233943/152915783-e0947561-ba2c-4963-9d40-13746d366e5c.png">

**Comment by alex-w** [comment]
I cannot confirm the issue. Please try delete all Stellarium-related directories and try install it again.

**Comment by belray04** [comment]
I have just tried this and got the exact same outcome. Thank you though

**Comment by alex-w** [comment]
Did you have fresh install of Stellarium or not?

**Comment by belray04** [comment]
> Did you have fresh install of Stellarium or not?

I had never downloaded Stellarium before this. I got this pop up every single time I've tried to download it.

**Comment by alex-w** [comment]
Would you check and share checksum for downloaded file?

**Comment by chrisx8** [comment]
I just tried to run Stellarium `v0.21.3`, download from GitHub release, on a MacBook Pro (14-inch, 2021) with M1 Pro and MacOS 12.3.

It looks like it might be some issue with Apple's Rosetta 2 translation tool on an M1-based Mac. Are you able to update macOS and try again?

**Comment by alex-w** [comment]
Did you tried to remove `/Library/Application Support/Stellarium` directory?

**Comment by gzotti** [comment]
@belray we need information from you. If you don't respond, we will close this issue after June 23.

**Comment by belray04** [comment]
I apologize for the lack of responses. I needed to download this software
for a course but I ended up getting by just fine with the web version of
Stellarium. Thank you for all the help
