### ISSUE TITLE
Stellarium dumps core on Arch Linux right after start

### ISSUE THREAD

**Issue by s5k6** [Stellarium/stellarium#226]
### Expected Behaviour

Do not die after start

### Actual Behaviour

AShortly after start, stellarium terminates.  I have retried with the ~/.stellarium directory removed, so it's not about my personal setup.

I've attached  `.stellarium/log.txt`.

### Steps to reproduce

Just launch

### System

    $ stellarium --version
    Stellarium 0.18.1

* Operating system: Up-to-date ArchLinux (Tue 2018-Jul-24 18:57:13 CEST)

* Graphics Card: GeForce GTX 1060 6GB

### Logfile 

    2018-07-24T18:50:15
    Operating System: Linux version 4.17.8-1-ARCH (builduser@heftig-21239) (gcc version 8.1.1 20180531 (GCC)) #1 SMP PREEMPT Wed Jul 18 09:56:24 UTC 2018
    Product Name: Arch Linux
    Compiled using GCC 8.1.1
    Qt runtime version: 5.11.1
    Qt compilation version: 5.11.1
    Addressing mode: 64-bit
    MemTotal:        8069272 kB
    MemFree:          135136 kB
    MemAvailable:    6537564 kB
    SwapTotal:             0 kB
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 1962.853
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 1861.760
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 2129.801
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 1809.915
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 2214.804
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 2044.929
    01:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1) (prog-if 00 [VGA controller])
    Kernel driver in use: nvidia
    Kernel modules: nouveau, nvidia_drm, nvidia
    stellarium 
     -------------------------------------------------------
    [ This is Stellarium 0.18.1 - http://www.stellarium.org ]
    [ Copyright (C) 2000-2018 Fabien Chereau et al.         ]
     -------------------------------------------------------
    Writing log file to: "/home/sk/.stellarium/log.txt"
    File search paths:
      0 .  "/home/sk/.stellarium"
      1 .  "/usr/share/stellarium"
    Config file  "/home/sk/.stellarium/config.ini"  does not exist. Copying the default file.
    Config file is:  "/home/sk/.stellarium/config.ini"
    Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
    Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
    StelGLWidget constructor
    StelGraphicsScene constructor
    initializeGL
    OpenGL supported version:  "4.6.0 NVIDIA 396.24"
    Current Format:  QSurfaceFormat(version 4.6, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
    StelMainView::init
    Detected: OpenGL "4.6"
    Driver version string: "4.6.0 NVIDIA 396.24"
    GL vendor is "NVIDIA Corporation"
    GL renderer is "GeForce GTX 1060 6GB/PCIe/SSE2"
    GL Shading Language version is "4.60 NVIDIA"
    GLSL Version Number detected:  4.6
    GLSL version is fine, we should not see a graphics problem.
    Cache directory is:  "/home/sk/.cache/stellarium/stellarium"
    Sky language is  "en_US"
    Planetary features language is  "en_US"
    Application language is  "en_US"
    Loading Solar System data (1: planets and moons) ...
    Loading from : "/usr/share/stellarium/data/ssystem_major.ini"
    Loaded 77 Solar System bodies
    Loading Solar System data (2: minor bodies)...
    Loading from : "/usr/share/stellarium/data/ssystem_minor.ini"
    Loaded 102 Solar System bodies
    File ssystem_minor.ini is loaded successfully...
    Loading nomenclature for Solar system bodies ...
    Loaded 15505 / 15510 items of planetary surface nomenclature
    Could not find the starsConfig.json file: will copy the default one.
    Creating directory  "/home/sk/.stellarium/stars/default"
    Creates file  "/home/sk/.stellarium/stars/default/starsConfig.json"
    Loading star data ...
    "Loading /usr/share/stellarium/stars/default/stars_0_0v0_7.cat: 0_0v0_7; 4979"
    "Loading /usr/share/stellarium/stars/default/stars_1_0v0_7.cat: 1_0v0_7; 21806"
    "Loading /usr/share/stellarium/stars/default/stars_2_0v0_7.cat: 2_0v0_7; 150850"
    "Loading /usr/share/stellarium/stars/default/stars_3_1v0_4.cat: 3_1v0_4; 425807"
    Finished loading star catalogue data, max_geodesic_level:  3
    Loading scientific star names from "/usr/share/stellarium/stars/default/name.fab"
    Loaded 4506 / 4506 scientific star names
    Loading variable stars from "/usr/share/stellarium/stars/default/gcvs_hip_part.dat"
    Loaded 6916 / 6916 variable stars
    Loading double stars from "/usr/share/stellarium/stars/default/wds_hip_part.dat"
    Loaded 16412 / 16412 double stars
    Loading cross-identification data from "/usr/share/stellarium/stars/default/cross-id.dat"
    Loaded 108338 / 108338 cross-identification data records for stars
    navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    Loading DSO data ...
    [...] "Stellarium DSO Catalog, version 3.5 (standard edition)"
    Loaded 90415 DSO records
    Loading DSO outline data ...
    Loaded 63 DSO outline records successfully
    LandscapeMgr: initialized Cache for 100 MB.
    Loading star names from "/usr/share/stellarium/skycultures/western/star_names.fab"
    Loaded 860 / 860 common star names
    Loading DSO name data ...
    Loaded 1012 / 1029 DSO name records successfully
    WARNING - No position data for 17 objects: "PGC 621, PGC 2345, PGC 2906, PGC 2907, PGC 14098, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
    Loaded 88 / 88 constellation records successfully for culture "western"
    Loaded 85 / 85 constellation art records successfully for culture "western"
    Loaded 88 / 88 constellation names
    Loading constellation boundary data ... 
    Loaded 782 constellation boundary segments
    Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
    ERROR reading asterism lines record at line  63 for culture "western"
    Loaded 53 / 54 asterism records successfully for culture "western"
    WARNING - asterism abbreviation "TA6" not found when loading asterism names
    Loaded 43 / 44 asterism names
    stel.OpenGLArray: Vertex Array Objects are supported
    Initializing basic GL shaders... 
    Creating GUI ...
    Loaded plugin "Exoplanets"
    Creating directory  "/home/sk/.stellarium/modules/Exoplanets"
    [Exoplanets] No Exoplanets section exists in main config file - creating with defaults
    [Exoplanets] exoplanets.json does not exist - copying default catalog to  "/home/sk/.stellarium/modules/Exoplanets/exoplanets.json"
    [Exoplanets] Default exoplanets.json to  "/home/sk/.stellarium/modules/Exoplanets/exoplanets.json"
    [Exoplanets] loading catalog file: "/home/sk/.stellarium/modules/Exoplanets/exoplanets.json"
    Loaded plugin "FOV"
    FOV: no fov section exists in main config file - creating with defaults
    Loaded plugin "MeteorShowers"
    Creating directory  "/home/sk/.stellarium/modules/MeteorShowers"
    MeteorShowersMgr: Loading catalog file: "/home/sk/.stellarium/modules/MeteorShowers/showers.json"
    MeteorShowersMgr: Trying to restore the default catalog to "/home/sk/.stellarium/modules/MeteorShowers/showers.json"
    MeteorShowersMgr: The default catalog was copied!
    MeteorShowersMgr: Starting to update the catalog...
    Loaded plugin "Novae"
    Creating directory  "/home/sk/.stellarium/modules/Novae"
    [Novae] no Novae section exists in main config file - creating with defaults
    [Novae] novae.json does not exist - copying default file to "/home/sk/.stellarium/modules/Novae/novae.json"
    [Novae] copied default novae.json to "/home/sk/.stellarium/modules/Novae/novae.json"
    [Novae] loading catalog file: "/home/sk/.stellarium/modules/Novae/novae.json"
    Loaded plugin "Oculars"
    Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
    Creating directory  "/home/sk/.stellarium/modules/Oculars"
    Oculars::validateIniFile copied default_ocular.ini to  "/home/sk/.stellarium/modules/Oculars/ocular.ini"
    Loaded plugin "Satellites"
    Creating directory  "/home/sk/.stellarium/modules/Satellites"
    [Satellites] satellites.json does not exist - copying default file to  "/home/sk/.stellarium/modules/Satellites/satellites.json"
    [Satellites] copied default satellites.json to  "/home/sk/.stellarium/modules/Satellites/satellites.json"
    [Satellites] copied default qs.mag to  "/home/sk/.stellarium/modules/Satellites/qs.mag"
    [Satellites] loading catalog file: "/home/sk/.stellarium/modules/Satellites/satellites.json"
    Satellite has invalid orbit: "MOLNIYA 3-3" "08425"
    Satellite has invalid orbit: "IRIDIUM 6" "24794"
    Satellite has invalid orbit: "IRIDIUM 19" "24965"
    Satellite has invalid orbit: "IRIDIUM 34" "24969"
    Satellite has invalid orbit: "IRIDIUM 43" "25039"
    Satellite has invalid orbit: "IRIDIUM 40" "25041"
    Satellite has invalid orbit: "GRACE-1" "27391"
    Satellite has invalid orbit: "GRACE-2" "27392"
    Satellite has invalid orbit: "ORS 1" "37728"
    Satellite has invalid orbit: "TIANGONG 1" "37820"
    Satellite has invalid orbit: "EAGLE 2" "39436"
    Satellite has invalid orbit: "AGGIESAT 4" "41313"
    Satellite has invalid orbit: "FLOCK 2E'-1" "41479"
    Satellite has invalid orbit: "FLOCK 2E'-2" "41481"
    Satellite has invalid orbit: "FLOCK 2E-2" "41484"
    Satellite has invalid orbit: "FLOCK 2E-4" "41487"
    Satellite has invalid orbit: "FLOCK 2E-6" "41563"
    Satellite has invalid orbit: "FLOCK 2E'-8" "41569"
    Satellite has invalid orbit: "FLOCK 2E-9" "41571"
    Satellite has invalid orbit: "FLOCK 2E-12" "41573"
    Satellite has invalid orbit: "FLOCK 2E-11" "41574"
    Satellite has invalid orbit: "FLOCK 2E'-9" "41575"
    Satellite has invalid orbit: "FLOCK 2E'-10" "41576"
    Satellite has invalid orbit: "FLOCK 2E'-12" "41578"
    Satellite has invalid orbit: "FLOCK 2E'-13" "41761"
    Satellite has invalid orbit: "STARS-C" "41895"
    Satellite has invalid orbit: "OSNSAT" "41939"
    Satellite has invalid orbit: "LEMUR-2-TRUTNA" "42067"
    Satellite has invalid orbit: "Columbia" "42702"
    Satellite has invalid orbit: "ISS DEB (ROSA)" "42813"
    Satellite has invalid orbit: "DRAGON CRS-13 DEB" "43061"
    Satellite has invalid orbit: "DRAGON CRS-13 DEB" "43062"
    Satellite has invalid orbit: "SL-4 R/B" "43064"
    Loaded plugin "SolarSystemEditor"
    Trying to copy ssystem_minor.ini to "/home/sk/.stellarium/data/ssystem_minor.ini"
    MeteorShowersMgr: Loading catalog file: "/home/sk/.stellarium/modules/MeteorShowers/showers.json_new.json"
    MeteorShowersMgr: The current catalog is not compatible!
    Failure getting IP-based location: 
             "Error transferring http://freegeoip.net/json/ - server replied: Forbidden"
    [Exoplanets] Starting update...
    [Novae] starting update...

**Comment by alex-w** [comment]
Open ~/.stellarium/config.ini and change all instances of http://stellarium... to https://www.stellarium...

**Comment by s5k6** [comment]
Thank you very much!  I've done as you said, using:

    $ sed -Ei 's#http://stellarium#https://www.stellarium#p' ~/.stellarium/config.ini

It seems to be running as expected now.
