### ISSUE TITLE
Are values of 0 and 13 for month spinbox in DateTime dialog useful?

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2272]
If you try to type a date like `2017-08-21` into the DateTime dialog (pressing <kbd>Tab</kbd> instead of typing <kbd>-</kbd>), you'll find that on typing `0` in the month field so as to get `08` the value suddenly changes to `12`, which makes you select all and re-type it without the `0`.

After some investigation I found that the ui file, `dateTimeDialogGui.ui`, has strange limits set for this spinbox: 0 to 13. This is just as the natural limits of 1 to 12, but with a margin of 1. I wonder, what is the use of these insensible values?

One use I suppose is to allow scrolling through the years like December to next January or January to previous December — with mouse wheel or Up/Down arrow keys. But is this the only use? Is the _typing_ behavior described above actually intended?

If the typing behavior is unintended, I might come up with a better scroll-through implementation, to improve the typing UX.

**Comment by gzotti** [comment]
I think this is only to allow correct wheel scrolling, which is however more important than typing.  I don't know if anybody ever cared for strange effects when entering seemingly wrong numbers like 0. You can change it, but don't break the scrolling!
