### ISSUE TITLE
APT/Stellarium interoperability issue?

### ISSUE THREAD

**Issue by spneuman** [Stellarium/stellarium#2275]
### Actual Behaviour

I am not sure this is a bug but, to my recollection, previous versions of Stellarium allowed me to click on an object and have APT import the object info from Stellarium. In my most recent current version, this no longer works; I need to Search for the object in Stellarium, and only then would APT import the info. Upon contacting APT, they told me it must be a Stellarium, not an APT issue. Please advise.

Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by spneuman** [comment]
How will I know that my issue has been addressed or discussed?

**Comment by gzotti** [comment]
> How will I know that my issue has been addressed or discussed? 

It would help if you filled in more of the provided issue template. Give a short title and extensive description, your program versions etc. Do not answer to the email but visit the github website and edit the original report, fill in the missing parts. 

I have currently no equipment for using APT, so cannot really help. It may have to do with you not having configured or activated the RemoteControl plugin.

**Comment by alex-w** [comment]
Which version of APT and Stellarium?

**Comment by spneuman** [comment]
Stellarium 0.21.3 and APT 3.94 on Windows 10 platform

**Comment by alex-w** [comment]
> Stellarium 0.21.3 and APT 3.94 on Windows 10 platform

Quote from APT website:
> the current APT version is [v3.90](https://www.astrophotography.app/usersguide/what_is_new_.htm)

Where you got version 3.94 of APT?

**Comment by gzotti** [comment]
Email attachments do not work. As said before, please visit the Github website and type into the browser dialog.

**Comment by spneuman** [comment]
Done; hope this worked.

**Comment by spneuman** [comment]
Regarding APT version, here is a screen shot showing version 3.94
![image](https://user-images.githubusercontent.com/99762712/154716128-7d80ea30-198a-4e39-8a75-4b44733a8bc0.png)

**Comment by spneuman** [comment]
Stellarium version  0.21.3-win64
Device name	DESKTOP-UAIJ1CD
Processor	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
Installed RAM	8.00 GB (7.81 GB usable)
Device ID	D8AD810F-0170-47A1-B287-F09D49BD420E
Product ID	00325-96323-21200-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points
Edition	Windows 10 Home
Version	20H2
Installed on	‎3/‎9/‎2021
OS build	19042.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0
Edition	Windows 10 Home
Version	20H2
Installed on	‎3/‎9/‎2021
OS build	19042.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by spneuman** [comment]
Intel UHD Graphics 620 Adapter
Generic PnP Monitor

**Comment by spneuman** [comment]
I have just uploaded all the hardware info I could think of as well as a screen shot of APT showing version 3.94, APT log and Stellarium log.

 

Please let me know if there is anything else you may need.

 

I greatly appreciate your time and effort in addressing this issue.

 

Shlomo Neuman

**Comment by alex-w** [comment]
Did you configured Stellarium as described in APT User's Guide?

**Comment by spneuman** [comment]
Well, here is an interesting situation. I went back to the APT download page, downloaded APT 3.90 (which, on that page, is said to be the most recent full version) and everything is back to normal. I will contact APT to clarify this; in the meantime, I thank you for your efforts and good offices.

**Comment by spneuman** [comment]
Returning to Issue #2275, the trick is to double click on a Stellarium object, which allows transferring its location to APT. Single click does not do it. You may want to make this clear in the Stellarium Users' Guide.

**Comment by gzotti** [comment]
APT is not a part of Stellarium. Such details would have to go into APT's User Guide.

**Comment by spneuman** [comment]
Actually, double clicking centers a star in Stellarium; does your Users’ Guide talk about it?
