### ISSUE TITLE
cannot search and add a comet in 21.3

### ISSUE THREAD

**Issue by blakesphere** [Stellarium/stellarium#2281]
Tried using Stellarium 0.21.3 on Windows 10 (and a Mac).

Solar System Editor
Import Orbital Elements
Online Search

Not working. Tried C/2021 O3 and C/2021 A1. No go.

The progress bar at the bottom-right of the screen briefly flashes and shows 0%.

Older version 0.21.1 even old 0.18.0 work as expected.

At first I thought the MPC service was *down* but it works in the older versions.

regards,
Blake

**Comment by alex-w** [comment]
Please try remove older verson before installing v0.21.3

**Comment by blakesphere** [comment]
I'm collecting data. 

I'll pull the log file.

Put one datum is that this was on a completely fresh install.

**Comment by blakesphere** [comment]
Oh, another thing. If I try Online search, after it fails, I cannot use the Lists tab. It's all locked out. A restart of Stellarium presents the Lists tab normally and in fact a comet can be found by this means. So the 2 takeaways:

The failure of the Online search breaks the normal function in the Import data window.

Users can still add comets but not by using the Online search tab.

**Comment by blakesphere** [comment]
Thank you, team! Working again in 0.22.0. Appreciate it!

**Comment by blakesphere** [comment]
Tested on Windows 10 (32 bit).
