### ISSUE TITLE
Crash at startup with this fault:  Unable to find module called "Calendars"

### ISSUE THREAD

**Issue by seescho** [Stellarium/stellarium#2287]
I went back in history and found, that the fault is introduced with this commit from Feb 16, 2022:  Calendars: Astro functions #2229

The crash only happens, if the Calendars-Plugin is disabled for loading at startup. If I enable it for loading at startup via config.ini, no more crash.

My OS: openSUSE Tumbleweed (up to date)
Reproducible: always

**Comment by gzotti** [comment]
Uh, I think I have found it. Stupid...

**Comment by gzotti** [comment]
@seescho thanks for notifying!

**Comment by seescho** [comment]
Works fine now. Thanks for fixing it.
