### ISSUE TITLE
Stellarium 0.18.1 crashes on Windows 10 and Ubuntu 18.04

### ISSUE THREAD

**Issue by iphorde** [Stellarium/stellarium#229]
Stellarium 0.18.1 crashes after running for a few a few seconds on both Ubuntu 18.04 and Windows 10. There is no error log, no message, it just exits. You can be doing anything.

**Comment by Vlaifius** [comment]
Сигнатура проблемы Windows 8:
  Имя события проблемы:	BEX64
  Имя приложения:	stellarium.exe
  Версия приложения:	0.18.1.0
  Отметка времени приложения:	5b3895d7
  Имя модуля с ошибкой:	ucrtbase.DLL
  Версия модуля с ошибкой:	10.0.10240.16384
  Отметка времени модуля с ошибкой:	559f3851
  Смещение исключения:	0000000000065a4e
  Код исключения:	c0000409
  Данные исключения:	0000000000000007
  Версия ОС:	6.3.9600.2.0.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	5d3f
  Дополнительные сведения 2:	5d3f978649fe64047b55c516b1459dc3
  Дополнительные сведения 3:	04e0
  Дополнительные сведения 4:	04e0e685dd9ba96a37b3497f292bed60
