### ISSUE TITLE
Crashed while using - display unusable after reinstall to fix.

### ISSUE THREAD

**Issue by Rigmaker** [Stellarium/stellarium#2297]
Was using Stellarium when the pgm froze and failed to recover.   I rebooted my pc and started it up again - this time the screen came up and displayed as shown in the screen snip. 
![Stellarium Screenshot 2022-02-23 111432](https://user-images.githubusercontent.com/60071690/155363007-66ec6094-192d-472c-ad01-6378bfd39a81.png)

I have uninstalled the pgm including all config files, Registry settings and personal config settings, re-booted and installed again... Same thing.  In the log file I see some note near the top regarding a profile with a different version in a Warning... but don't understand that note.
[log.txt](https://github.com/Stellarium/stellarium.github.io/files/8126097/log.txt)

I have also used Revo Uninstaller to completely wipe all configuration/pgm/user and registration entries for the software, but nothing changes.  

Any help would be appreciated.

**Comment by gzotti** [comment]
We have had several reports of this kind. This is a bug in Intel's graphics drivers, we cannot help here.
