### ISSUE TITLE
Phoebe position iincorrect

### ISSUE THREAD

**Issue by kwbeverage** [Stellarium/stellarium#230]
### Expected Behaviour
Correct position shown for Phoebe
### Actual Behaviour
For a given time Phoebe is shown in an incorrect location.  Checked results against ephemerides acquired from the MPC Natural Satellites Ephemeris Service and Saturn Viewer 2.9 website.   See screen capture and text file for comparison.

### Steps to reproduce
Installed current version (0.18.1) which shows the same position as previous install (0.17.0).
### System
* Stellarium version: stellarium-0.18.1-win64
* Operating system: Windows 10, version 1803
* Graphics Card: NVidia GEFORCE GTX 950m
### Logfile 
No logfile available

Attachments:
![stellarium-014](https://user-images.githubusercontent.com/41690099/43207671-cf8caeea-8fe5-11e8-9e39-210011a667ff.png)

[phoebe_data.txt](https://github.com/Stellarium/stellarium/files/2228279/phoebe_data.txt)

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/FAQ#some-moons-are-in-another-position-than-they-should-be

Stellarium is not finished. You are cordially invited to help.

**Comment by alex-w** [comment]
Phoebe has simple elliptic orbit at the moment and of course this solution is not accurate. We need to implement [PH12](ftp://ftp.imcce.fr/pub/ephem/satel/ph12/README.txt) and [HTC 2.0](ftp://ftp.imcce.fr/pub/ephem/satel/htc20/ReadMe.txt) for Saturnian moons.

**Comment by piellepi** [comment]
hi!
I'm using version 1.1 of stellarium but Phoebe's position is still greatly incorrect.
instead in stellarium web the position seems correct and comparable to the one generated by IMCCE software

this is the position in PC version
![febe pc](https://user-images.githubusercontent.com/98280503/207552320-cf64de1e-91d9-4684-9716-7cae65ffc41c.png)

this is in the web version
![febe web](https://user-images.githubusercontent.com/98280503/207552475-a5d542a3-9c3e-4bd1-9da7-a933eb0502cd.png)

and this is the position from IMCCE
![febe imcce](https://user-images.githubusercontent.com/98280503/207552938-b37692ae-8a5e-4b04-bc2d-4f6b20006599.png)

thanks
Pierluigi Panunzi

**Comment by gzotti** [comment]
Yes, and therefore this issue is still open.

**Comment by worachate001** [comment]
I'm investigating the cause of error and found that orbital elements of the satellite are wrong for the epoch. I will correct it soon and try to check (and correct them if needed) others before the release of version 23.2.

**Comment by gzotti** [comment]
@alex-w mentioned PH12, so this (or even better) would be preferred over Kepler elements.

**Comment by worachate001** [comment]
I read that PH12 ephemeris is available for only the years 1875-2022. The alternative method that I'm thinking about is using mean orbital elements that include rate of changes (in longitude of ascending node, etc.) , derived from hundred years of elements. But it would be original work.

**Comment by gzotti** [comment]
OK, yes, PH12 is no solution then. Note that the current way to describe moon orbits is relative to the planet equator, which is not what is usually found in the literature. I don't know the origin of this model. If you make variable orbits like this, you must also change the KeplerOrbit class.
