### ISSUE TITLE
can't see nor search an asteroid - 1999 vf22

### ISSUE THREAD

**Issue by Yossi1M** [Stellarium/stellarium#2306]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
See User Guide ch.12.7 and/or  https://github.com/Stellarium/stellarium/wiki/FAQ#adding-a-comet-to-stellarium-with-the-solar-system-editor-plug-in

The process for minor planets is similar.
