### ISSUE TITLE
Stellarium ver 21.3 - Asteoid noot seen nor choosable.

### ISSUE THREAD

**Issue by Yossi1M** [Stellarium/stellarium#2312]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Formally this is incomplete. But if you want to add an asteroid, look into the User Guide chapter 12.7 or the FAQ.

**Comment by Yossi1M** [comment]
Hi, thank you for your response.

However, I tried to follow your advise but after a few hours of trying to add Asetroid  1999-VF22 I gave up. I didn't succeed.

I really believe that bodies that are of an enormous interest like the above mentioned Asteroid  and the JWST should be include in the lists that Stallerium provides.

10x

Yossi
