### ISSUE TITLE
Month time key

### ISSUE THREAD

**Issue by Domainedeletoile** [Stellarium/stellarium#232]
Hi,

Is it possible to have shorts keys to manage time by month ? It will be easier to show how the sky changes wihin the year.

Thnak you.

Alexandre PIGUET

**Comment by Domainedeletoile** [comment]
Yes, I didn't think about it.

Thank you !

Alexandre

Merci, Cordialement,

*Alexandre PIGUET*

Porteur du Projet du Domaine de l’Etoile

http://domainedeletoile.fr, Inscrivez-vous sur mon *Blog* pour suivre
l’aventure…

Et suivez moi sur *FaceBook* à https://www.facebook.com/domainedeletoile/

Tel : 06-60-13-62-89

alexandre.piguet@domainedeletoile.fr



2018-07-27 9:29 GMT+02:00 Georg Zotti <notifications@github.com>:

**Comment by alex-w** [comment]
I've added support to add/subtract calendric months also

**Comment by Domainedeletoile** [comment]
Super, where can I find this support ?

Le ven. 27 juil. 2018 à 10:56, Alexander Wolf <notifications@github.com> a
écrit :

**Comment by alex-w** [comment]
In next version for calendric month...
