### ISSUE TITLE
Meteor displaying

### ISSUE THREAD

**Issue by Domainedeletoile** [Stellarium/stellarium#233]
Hi,

The Meteor are always dispayed at the start-up. Even if you disable it (ctrl+shift+M) and save, it appears again after the next start-up. Could you please solve it ?

Thank you

Alexandre PIGUET

**Comment by gzotti** [comment]
Minutes ago, I called the Meteor plugin's configure panel and disabled "Enable plugin at startup". 
On next start, it was switched off.

**Comment by Domainedeletoile** [comment]
Ah OK, I have to pass by the plugin. I am going to try.

Thank you again.

Merci, Cordialement,

*Alexandre PIGUET*

Porteur du Projet du Domaine de l’Etoile

http://domainedeletoile.fr, Inscrivez-vous sur mon *Blog* pour suivre
l’aventure…

Et suivez moi sur *FaceBook* à https://www.facebook.com/domainedeletoile/

Tel : 06-60-13-62-89

alexandre.piguet@domainedeletoile.fr



2018-07-27 9:32 GMT+02:00 Georg Zotti <notifications@github.com>:
