### ISSUE TITLE
Red lines

### ISSUE THREAD

**Issue by advius** [Stellarium/stellarium#235]
Greetings,
when updating mesa to version 18.0.5-0 ubuntu0.16.04.1 lines change colour to read and they flashing.
![stellarium-010](https://user-images.githubusercontent.com/40942201/43368515-715ba9bc-935e-11e8-8fdc-6601829e9663.png).

My OS is Linux mint 18.3 cinnamon 64-bit.
My Stellarium is 0.18.1 Appimage.

Thank you for answer.

**Comment by alex-w** [comment]
Please attach ~/.stellarium/log.txt

**Comment by advius** [comment]
OK 
I attach a logfile:
[log.txt](https://github.com/Stellarium/stellarium/files/2239051/log.txt)


This  problem is manifested too if I run Stellarium on Ubuntu Bionic and Fedora 28 workstation on live cd.

**Comment by gzotti** [comment]
GLSL Version Number detected:  1.2
This is not enough: we need GLSL1.30 or later.

Sorry, your hardware is too old.

**Comment by advius** [comment]
Thank you for answer.
Please have you a some tip for fix it with my hardware?
Thank you.

**Comment by gzotti** [comment]
There is most likely no fix with this 10 year old hardware to run version 0.18.
Too old hardware can be replaced by new hardware. 
Else, you can still use version 0.12.

For 5 years, this has been in the FAQ: https://github.com/Stellarium/stellarium/wiki/FAQ#opengl-issues

**Comment by advius** [comment]
Thank you very much for answers.
