### ISSUE TITLE
API mode Documentation

### ISSUE THREAD

**Issue by Remi1945** [Stellarium/stellarium#2358]
I am trying to use stellarium with the api mode but the documentation is very poor and I very often receive **unsupported operation** message when I try to do something.
So please make a better documentation with exemples

**Comment by alex-w** [comment]
API documentation on the stellarium.org website reflected to the latest stable version of Stellarium. Did you tried use the latest one? Plus all methods are case sensitive - please check it too.

**Comment by Remi1945** [comment]
I think I had the latest documentation an yes I am aware of case sensitive problem.
For example I am trying to set the location with the api through a navigator but it's not working

**Comment by alex-w** [comment]
According to discussion #2359 - you used wrong HTTP method ;)
