### ISSUE TITLE
Stellarium dumps core on Arch Linux right after start

### ISSUE THREAD

**Issue by s5k6** [Stellarium/stellarium#236]
**Note:** This is not  #226, nor #227 

### Actual Behaviour

Stellarium crashes right after start on Arch Linux.  I have applied the fix mentioned in #226 / #227, that did not help.

### Steps to reproduce

This seems to be related to my settings, after deleting `~/.stellarium` it seems to run fine.  So maybe you cannot reproduce this.

I have applied #226, and then it wa working.  I have not used stellarium during the last two days.  Now the same version crashes.  No updates in between.

Obviously, I don't want to loose my settings.  So if there's no fix, whichfiles do I need to copy from the (backed up) old settings folder?

### System

    $ stellarium --version
    Stellarium 0.18.1

  * Operating system: Up-to-date ArchLinux (Tue 2018-Jul-24 18:57:13 CEST)

  * Graphics Card: GeForce GTX 1060 6GB

### Logfile

    2018-07-29T20:08:57
    Operating System: Linux version 4.17.10-1-ARCH (builduser@heftig-13013) (gcc version 8.1.1 20180531 (GCC)) #1 SMP PREEMPT Wed Jul 25 11:23:00 UTC 2018
    Product Name: Arch Linux
    Compiled using GCC 8.1.1
    Qt runtime version: 5.11.1
    Qt compilation version: 5.11.1
    Addressing mode: 64-bit
    MemTotal:        8069276 kB
    MemFree:         4712964 kB
    MemAvailable:    6984612 kB
    SwapTotal:             0 kB
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 2589.206
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 1695.613
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 1863.388
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 1579.509
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 1418.833
    model name	: AMD FX(tm)-6300 Six-Core Processor
    cpu MHz		: 1498.892
    01:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1) (prog-if 00 [VGA controller])
    Kernel driver in use: nvidia
    Kernel modules: nouveau, nvidia_drm, nvidia
    stellarium 
     -------------------------------------------------------
    [ This is Stellarium 0.18.1 - http://www.stellarium.org ]
    [ Copyright (C) 2000-2018 Fabien Chereau et al.         ]
     -------------------------------------------------------
    Writing log file to: "/home/sk/.stellarium/log.txt"
    File search paths:
      0 .  "/home/sk/.stellarium"
      1 .  "/usr/share/stellarium"
    Config file is:  "/home/sk/.stellarium/config.ini"
    Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
    Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
    StelGLWidget constructor
    StelGraphicsScene constructor
    initializeGL
    OpenGL supported version:  "4.6.0 NVIDIA 396.45"
    Current Format:  QSurfaceFormat(version 4.6, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
    StelMainView::init
    Detected: OpenGL "4.6"
    Driver version string: "4.6.0 NVIDIA 396.45"
    GL vendor is "NVIDIA Corporation"
    GL renderer is "GeForce GTX 1060 6GB/PCIe/SSE2"
    GL Shading Language version is "4.60 NVIDIA"
    GLSL Version Number detected:  4.6
    GLSL version is fine, we should not see a graphics problem.
    Cache directory is:  "/home/sk/.cache/stellarium/stellarium"
    StelLocation::createFromLine(): TimeZone name for  ""  not found. Translating "system_default"  to  "system_default"
    StelLocation::createFromLine(): TimeZone name for  "hütte"  not found. Translating "system_default"  to  "system_default"Sky language is  "en_US"
    Planetary features language is  "en_US"
    Application language is  "en_US"
    Loading Solar System data (1: planets and moons) ...
    Loading from : "/usr/share/stellarium/data/ssystem_major.ini"
    Loaded 77 Solar System bodies
    Loading Solar System data (2: minor bodies)...
    Loading from : "/home/sk/.stellarium/data/ssystem_minor.ini"
    Loaded 101 Solar System bodies
    File ssystem_minor.ini is loaded successfully...
    Loading nomenclature for Solar system bodies ...
    Loaded 15505 / 15510 items of planetary surface nomenclature
    Loading star data ...
    "Loading /usr/share/stellarium/stars/default/stars_0_0v0_7.cat: 0_0v0_7; 4979"
    "Loading /usr/share/stellarium/stars/default/stars_1_0v0_7.cat: 1_0v0_7; 21806"
    "Loading /usr/share/stellarium/stars/default/stars_2_0v0_7.cat: 2_0v0_7; 150850"
    "Loading /usr/share/stellarium/stars/default/stars_3_1v0_4.cat: 3_1v0_4; 425807"
    "Loading /home/sk/.stellarium/stars/default/stars_4_1v0_2.cat: 4_1v0_4; 1692779"
    "Loading /home/sk/.stellarium/stars/default/stars_5_2v0_1.cat: 5_2v0_1; 7083058"
    "Loading /home/sk/.stellarium/stars/default/stars_6_2v0_1.cat: 6_2v0_1; 24670782"
    "Loading /home/sk/.stellarium/stars/default/stars_7_2v0_1.cat: 7_2v0_1; 50733321"
    "Loading /home/sk/.stellarium/stars/default/stars_8_2v0_1.cat: 8_2v0_1; 92304337"
    Finished loading star catalogue data, max_geodesic_level:  8
    Loading scientific star names from "/usr/share/stellarium/stars/default/name.fab"
    Loaded 4506 / 4506 scientific star names
    Loading variable stars from "/usr/share/stellarium/stars/default/gcvs_hip_part.dat"
    Loaded 6916 / 6916 variable stars
    Loading double stars from "/usr/share/stellarium/stars/default/wds_hip_part.dat"
    Loaded 16412 / 16412 double stars
    Loading cross-identification data from "/usr/share/stellarium/stars/default/cross-id.dat"
    Loaded 108338 / 108338 cross-identification data records for stars
    navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    Loading DSO data ...
    [...] "Stellarium DSO Catalog, version 3.5 (standard edition)"
    Loaded 90415 DSO records
    Loading DSO outline data ...
    Loaded 63 DSO outline records successfully
    LandscapeMgr: initialized Cache for 100 MB.
    Loading star names from "/usr/share/stellarium/skycultures/western/star_names.fab"
    Loaded 860 / 860 common star names
    Loading DSO name data ...
    Loaded 1012 / 1029 DSO name records successfully
    WARNING - No position data for 17 objects: "PGC 621, PGC 2345, PGC 2906, PGC 2907, PGC 14098, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
    Loaded 88 / 88 constellation records successfully for culture "western"
    Loaded 85 / 85 constellation art records successfully for culture "western"
    Loaded 88 / 88 constellation names
    Loading constellation boundary data ... 
    Loaded 782 constellation boundary segments
    Loaded 54 / 54 asterism records successfully for culture "western"
    Loaded 44 / 44 asterism names
    stel.OpenGLArray: Vertex Array Objects are supported
    Initializing basic GL shaders... 
    Creating GUI ...
    Loaded plugin "Exoplanets"
    [Exoplanets] File format is wrong! Error: illegal value
    [Exoplanets] Default exoplanets.json to  "/home/sk/.stellarium/modules/Exoplanets/exoplanets.json"
    [Exoplanets] loading catalog file: "/home/sk/.stellarium/modules/Exoplanets/exoplanets.json"
    Loaded plugin "MeteorShowers"
    MeteorShowersMgr: Loading catalog file: "/home/sk/.stellarium/modules/MeteorShowers/showers.json"
    Loaded plugin "Novae"
    [Novae] version of the catalog: 1
    [Novae] loading catalog file: "/home/sk/.stellarium/modules/Novae/novae.json"
    Loaded plugin "Oculars"
    Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
    Oculars::validateIniFile ocular.ini exists at:  "/home/sk/.stellarium/modules/Oculars/ocular.ini" . Checking version...
    Oculars::validateIniFile found existing ini file version  3.1
    Loaded plugin "Satellites"
    [Satellites] loading catalog file: "/home/sk/.stellarium/modules/Satellites/satellites.json"
    Loaded plugin "SolarSystemEditor"
    Using the ssystem_minor.ini file that already exists in the user directory...
    [Exoplanets] Starting update...
    [Satellites] starting Internet update...

**Comment by alex-w** [comment]
Just hypothesis: could you disable Satellites plugin in the config.ini and check it again?

**Comment by gzotti** [comment]
After some server reconfiguration to https, there was a temporary problem. I am still using the old URLs (http://stellarium.org) with V0.18.1 and never had a problem. I understand from #224 the current best solution should be https://stellarium.org).

**Comment by s5k6** [comment]
Ok, I've changed as follows

    $ diff tmp/config.ini .stellarium/config.ini 
    403c403
    < Satellites                             = true
    ---
    > Satellites                             = false

and Stellarium has not crashed yet.  It pretty much looks like being the problem.

**Comment by alex-w** [comment]
It's an interesting. @s5k6 could you check all files in ~/.stellaruim/modules/Satellites and show section [Satellites] from config.ini?

**Comment by s5k6** [comment]
> could you check all files in ~/.stellaruim/modules/Satellites

Check for what?  Here they are:

    $ l .stellarium/modules/Satellites/
    total 2.8M
    -rw-r--r-- 1 sk users 290k Mar 28 13:04 qs.mag
    -rw------- 1 sk users 982k Jul 24 19:11 satellites.json
    -rw------- 1 sk users 981k Jul 24 18:44 satellites.json.old
    -rw------- 1 sk users 5.8k Jul 24 19:11 tle0.txt
    -rw------- 1 sk users 7.8k Jul 24 19:11 tle10.txt
    -rw------- 1 sk users  10k Jul 24 19:11 tle11.txt
    -rw------- 1 sk users 1.7k Jul 24 19:11 tle12.txt
    -rw------- 1 sk users 5.3k Jul 24 19:11 tle13.txt
    -rw------- 1 sk users  25k Jul 24 19:11 tle14.txt
    -rw------- 1 sk users  12k Jul 24 19:11 tle15.txt
    -rw------- 1 sk users 5.6k Jul 24 19:11 tle16.txt
    -rw------- 1 sk users 1.1k Jul 24 19:11 tle17.txt
    -rw------- 1 sk users 7.3k Jul 24 19:11 tle18.txt
    -rw------- 1 sk users  76k Jul 24 19:11 tle19.txt
    -rw------- 1 sk users  12k Jul 24 19:11 tle1.txt
    -rw------- 1 sk users 6.6k Jul 24 19:11 tle20.txt
    -rw------- 1 sk users  10k Jul 24 19:11 tle21.txt
    -rw------- 1 sk users  15k Jul 24 19:11 tle22.txt
    -rw------- 1 sk users 3.7k Jul 24 19:11 tle23.txt
    -rw------- 1 sk users 2.9k Jul 24 19:11 tle24.txt
    -rw------- 1 sk users 4.2k Jul 24 19:11 tle25.txt
    -rw------- 1 sk users  69k Jul 24 19:11 tle26.txt
    -rw------- 1 sk users 4.8k Jul 24 19:11 tle27.txt
    -rw------- 1 sk users 2.7k Jul 24 19:11 tle28.txt
    -rw------- 1 sk users 3.1k Jul 24 19:11 tle29.txt
    -rw------- 1 sk users 3.7k Jul 24 19:11 tle2.txt
    -rw------- 1 sk users 5.3k Jul 24 19:11 tle30.txt
    -rw------- 1 sk users  840 Jul 24 19:11 tle31.txt
    -rw------- 1 sk users 1.1k Jul 24 19:11 tle32.txt
    -rw------- 1 sk users  26k Jul 24 19:11 tle33.txt
    -rw------- 1 sk users 1.6k Jul 24 19:11 tle34.txt
    -rw------- 1 sk users  336 Jul 24 19:11 tle35.txt
    -rw------- 1 sk users  24k Jul 24 19:11 tle36.txt
    -rw------- 1 sk users 2.7k Jul 24 19:11 tle3.txt
    -rw------- 1 sk users  11k Jul 24 19:11 tle4.txt
    -rw------- 1 sk users  25k Jul 24 19:11 tle5.txt
    -rw------- 1 sk users 5.3k Jul 24 19:11 tle6.txt
    -rw------- 1 sk users 3.7k Jul 24 19:11 tle7.txt
    -rw------- 1 sk users  12k Jul 24 19:11 tle8.txt
    -rw------- 1 sk users  11k Jul 24 19:11 tle9.txt

> and show section [Satellites] from config.ini?

Yep:

    [Satellites]
    auto_add_enabled                       = true
    auto_remove_enabled                    = true
    hint_color                             = 0.0,0.4,0.6
    hint_font_size                         = 10
    invisible_satellite_color              = 0.2,0.2,0.2
    last_update                            = 2018-07-24T19:11:32
    orbit_fade_segments                    = 5
    orbit_line_flag                        = false
    orbit_line_segments                    = 90
    orbit_segment_duration                 = 20
    realistic_mode_enabled                 = true
    show_satellite_hints                   = true
    show_satellite_labels                  = false
    tle_sources/1/add_new                  = true
    tle_sources/1/url                      = http://www.celestrak.com/NORAD/elements/visual.txt
    tle_sources/10/url                     = http://www.celestrak.com/NORAD/elements/geo.txt
    tle_sources/11/add_new                 = true
    tle_sources/11/url                     = http://www.celestrak.com/NORAD/elements/stations.txt
    tle_sources/12/url                     = http://www.celestrak.com/NORAD/elements/weather.txt
    tle_sources/13/url                     = http://www.celestrak.com/NORAD/elements/resource.txt
    tle_sources/14/url                     = http://www.celestrak.com/NORAD/elements/sarsat.txt
    tle_sources/15/url                     = http://www.celestrak.com/NORAD/elements/dmc.txt
    tle_sources/16/url                     = http://www.celestrak.com/NORAD/elements/tdrss.txt
    tle_sources/17/url                     = http://www.celestrak.com/NORAD/elements/argos.txt
    tle_sources/18/url                     = http://www.celestrak.com/NORAD/elements/intelsat.txt
    tle_sources/19/url                     = http://www.celestrak.com/NORAD/elements/gorizont.txt
    tle_sources/2/url                      = http://www.celestrak.com/NORAD/elements/tle-new.txt
    tle_sources/20/url                     = http://www.celestrak.com/NORAD/elements/raduga.txt
    tle_sources/21/url                     = http://www.celestrak.com/NORAD/elements/molniya.txt
    tle_sources/22/url                     = http://www.celestrak.com/NORAD/elements/orbcomm.txt
    tle_sources/23/url                     = http://www.celestrak.com/NORAD/elements/globalstar.txt
    tle_sources/24/url                     = http://www.celestrak.com/NORAD/elements/x-comm.txt
    tle_sources/25/url                     = http://www.celestrak.com/NORAD/elements/other-comm.txt
    tle_sources/26/add_new                 = true
    tle_sources/26/url                     = http://www.celestrak.com/NORAD/elements/glo-ops.txt
    tle_sources/27/url                     = http://www.celestrak.com/NORAD/elements/beidou.txt
    tle_sources/28/url                     = http://www.celestrak.com/NORAD/elements/sbas.txt
    tle_sources/29/url                     = http://www.celestrak.com/NORAD/elements/nnss.txt
    tle_sources/3/add_new                  = true
    tle_sources/3/url                      = http://www.celestrak.com/NORAD/elements/science.txt
    tle_sources/30/url                     = http://www.celestrak.com/NORAD/elements/engineering.txt
    tle_sources/31/url                     = http://www.celestrak.com/NORAD/elements/education.txt
    tle_sources/32/url                     = http://www.celestrak.com/NORAD/elements/geodetic.txt
    tle_sources/33/url                     = http://www.celestrak.com/NORAD/elements/radar.txt
    tle_sources/34/url                     = http://www.celestrak.com/NORAD/elements/cubesat.txt
    tle_sources/35/url                     = http://www.celestrak.com/NORAD/elements/other.txt
    tle_sources/36/url                     = https://www.amsat.org/amsat/ftp/keps/current/nasabare.txt
    tle_sources/37/add_new                 = true
    tle_sources/37/url                     = https://www.prismnet.com/~mmccants/tles/classfd.zip
    tle_sources/4/url                      = http://www.celestrak.com/NORAD/elements/noaa.txt
    tle_sources/5/url                      = http://www.celestrak.com/NORAD/elements/goes.txt
    tle_sources/6/add_new                  = true
    tle_sources/6/url                      = http://www.celestrak.com/NORAD/elements/amateur.txt
    tle_sources/7/add_new                  = true
    tle_sources/7/url                      = http://www.celestrak.com/NORAD/elements/gps-ops.txt
    tle_sources/8/add_new                  = true
    tle_sources/8/url                      = http://www.celestrak.com/NORAD/elements/galileo.txt
    tle_sources/9/add_new                  = true
    tle_sources/9/url                      = http://www.celestrak.com/NORAD/elements/iridium.txt
    tle_sources/size                       = 37
    update_frequency_hours                 = 72
    updates_enabled                        = true

**Comment by s5k6** [comment]
Okay, this is becoming a little bit more complicated, I might have
promised a bit too much about “backed up `~/.stellarium`”.

In between the bug disappeared, but I can reproduce it again now.

Since Stellarium stores quite some data in `~/.stellarium` that I'd
rather consider “cache”, I've decided to exclude some of that stuff
from my backups.  To this end, there's a `/usr/local/nobackup/$USER/`
for each user, which is excluded from backup, and a symlink
`.nobackup` to there in each home.  Data heavy directories from all
kinds of applications should be moved there.  So, my
`~/.stellarium/modules/Satellites` resolves as follows:

    $ namei ~/.stellarium/modules/Satellites
    f: /home/sk/.stellarium/modules/Satellites
     d /
     d home
     d sk
     d .stellarium
     l modules -> /home/sk/.nobackup/stellarium/modules/
       d /
       d home
       d sk
       l .nobackup -> /usr/local/nobackup/sk/
         d /
         d usr
         d local
         d nobackup
         d sk
       d stellarium
       d modules
     d Satellites

Now, if I just delete `~/.stellarium`, everything's fine.

When I restored my original `~/.stellarium`, Stellarium crashed, until
I've disabled `Satellites` in my `.stellarium/config.ini`, as written
in a previous post.  I assume that, after this step, something got
written into `~/.stellarium/{modules,stars}`, because these are the
(only) two directories symlinked from `~/.nobackup`, *and* I've failed
to reproduce the bug by restoring my original (faulty) `~/.stellarium`
since then.

But I can reproduce the bug easily by resorting my original (faulty)
`~/.stellarium`, *and then* delete `~/.stellarium/{modules,stars}`.
So I've just attached the archived `~/.stellarium` which should cause
the crash:

[.stellarium.zip](https://github.com/Stellarium/stellarium/files/2241042/default.stellarium.zip) — only 25kB

Can you reproduce this?

**Comment by alex-w** [comment]
@s5k6 yes, I understand now why Stellarium crashes.

It's same problem as before, but after changes settings of server we have redirect www.stellarium.org -> stellarium.org 

Dammit. Could you change string https://www.stellarium to https://stellarium in config.ini and check it again?

P.S. Seems we should release version 0.18.2 ASAP.

**Comment by s5k6** [comment]
$ sed -Ei 's#https://www.stellarium#https://stellarium#g' config.ini 

Yep, that seems to do the trick on the `.stellarium.zip` i've posted above.  (Sorry for including the whole path in the zip file...)
