### ISSUE TITLE
Remote Control no longer loading

### ISSUE THREAD

**Issue by ImmersiveTheatres** [Stellarium/stellarium#2362]
I use Stellarium 0.19.1 almost daily on a MacBook Pro, as part of my mobile planetarium shows. I've received fantastic help from this forum in the past - and even had new functionality suggestions approved, like allowing stars to twinkle with the atmosphere off, etc.

Recently - out of the blue - the Remote Control has stopped loading for me (or, more accurately, it fails to load 90% of the time).

http://localhost:8090 no longer works. All I get is: "Please wait, loading"

I have tried changing the port to 8070, 8080, 8090; but it makes no difference. I have tried different browsers, but it makes no difference.
 
 I am running Mac OS X Catalina ver. 10.15.7
 
 Has anyone else experienced this? 
 
 I've researched the web thoroughly, but cannot find a solution.
 
 Can someone perhaps help me?
 
 Thank you

**Comment by alex-w** [comment]
Please attach log from Stellarium

**Comment by ImmersiveTheatres** [comment]
I've just looked for the Stellarium log in Stellarium.app -> Package Contents -> Contents ... and I can't see it anywhere. Can you point to it for me please?

Also, I cannot access the Stellarium toolbars because:

(a) they have been disabled (so they don't project on the planetarium dome)

(b) I cannot find OS X keyboard toolbar shortcuts anywhere on the Web (surely these must exist somewhere? All I can find is Windows and Linux keyboard toolbar shortcuts)

Your help with these challenges would be greatly appreciated.

Thank you

**Comment by gzotti** [comment]
User Guide, chapter 5.
User Guide, elsewhere. Mostly when Ctrl+key is written for Linux and Windows, Mac users call the same thing Command+key.

**Comment by ImmersiveTheatres** [comment]
> 
[log.txt](https://github.com/Stellarium/stellarium/files/8357813/log.txt)

**Comment by ImmersiveTheatres** [comment]
> User Guide, chapter 5. User Guide, elsewhere. Mostly when Ctrl+key is written for Linux and Windows, Mac users call the same thing Command+key.

Great thank you. I found the log.txt file and attached it above.

**Comment by alex-w** [comment]
Please try connecting to localhost:8090 via firefox (any non-default browser)

**Comment by ImmersiveTheatres** [comment]
I've tried with Firefox and Safari - the same problem 😐

**Comment by gzotti** [comment]
Do you have some particular firewall settings that would disallow connection?
