### ISSUE TITLE
Unlabeled gas cloud

### ISSUE THREAD

**Issue by JohnK625** [Stellarium/stellarium#2366]
If the bug still persists, give your issue a clear, short title, delete text above down to and including this line and fill in:
-->**Just below and to the right of NGC 2505 is what appears to be a supernova gas cloud which does not show a label.**

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Do you mean PK 164+31.1? Activate display of PK catalog objects. "Below and to the right" are not quite appropriate. Give equatorial coordinates if it is another object.

**Comment by JohnK625** [comment]
I figured it out - It's the "Headphone Nebula".

If "Limit Magnitude" is checked, the label does not display - if it's
un-checked, the label and info will display.

Thanks for your time with this!

John
======================================

**Comment by gzotti** [comment]
Half a year ago you said all is resolved. Your headphone nebula, PK 164+31.1, is marked with a symbol and labeled if you have activated the PK catalog, disabled limit magnitude (or set to include its magnitude) and moved the "labels" and "hints" sliders far enough to the right to include such dim objects.
![stellarium-024](https://user-images.githubusercontent.com/18099873/195065238-d4f6a688-eff1-4541-8f8a-380244537f22.jpg)
