### ISSUE TITLE
USE MORE ACCURATED 3D MODELS FUNCTION  DOESN'T WORK WITH 0.22 VERSION

### ISSUE THREAD

**Issue by nicopop75** [Stellarium/stellarium#2367]
Hello, 
I've  installed version 0.22 of Stellarium. I've encountered the following problem: activating the  mode' 3D images , the images are white, (see images  here attached): 

With the previous version 0.21.3 I did not encounter this problem. 

I'm using Stellarium on the following pc: WINDOWS 8.1 3.6 GH ram 4 GB. 
Graphics card:  INTEL HD GRAPHICS 4400
Stellarium versions 0.22

Thank you very much for your attention.

![(243) IDA](https://user-images.githubusercontent.com/79394885/160294806-2ed26649-0c24-42a0-94ef-195ec8926966.png)
![AMALTHEA](https://user-images.githubusercontent.com/79394885/160294808-f2928c99-f8b3-47a2-bf20-897ac9e6291e.png)
![IMAGE 1](https://user-images.githubusercontent.com/79394885/160294809-0588f456-6734-479f-a0da-8f896c5c7462.png)
![VESTA](https://user-images.githubusercontent.com/79394885/160294811-3d36bfe8-181a-4e1f-99c8-60c0224e50e6.png)

**Comment by nicopop75** [comment]
[log.txt](https://github.com/Stellarium/stellarium/files/8358224/log.txt)
[config.txt](https://github.com/Stellarium/stellarium/files/8358231/config.txt)

**Comment by alex-w** [comment]
OK, this bug was introduced when Martian polar caps was visualized: https://github.com/Stellarium/stellarium/commit/c787c1e3e1bd33d3a3d312f398dc67931cd64112

@gzotti could you check it?

**Comment by gzotti** [comment]
I had feared it...

**Comment by alex-w** [comment]
@gzotti please check my patch

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
