### ISSUE TITLE
Some missing French translations

### ISSUE THREAD

**Issue by jester38** [Stellarium/stellarium#237]
I am new here, so Hello to all !

I use the French version of Stellarium and I would like to report some English terms that are not, or inaccurately, trans lated in French. They are located in the informations when clicking on a planet. Please, look at the attached screenshot.
These are :
- rise
- set
- orbital velocity
- equatorial rotation velocity
- equatorial diameter
About the French translation "illuminé :" I would have expected "illuminé à : " But as the object may have a male or female gender, maybe, then I suggest "illumination", "éclairement"...

Regards.
![english terms](https://user-images.githubusercontent.com/24970385/43370753-d5d6c964-9384-11e8-86ae-acf4be2ecc63.jpg)

**Comment by gzotti** [comment]
Translation is a community effort. You can help!

https://www.transifex.com/stellarium/stellarium/dashboard/

**Comment by alex-w** [comment]
I've sent notification to French translators team.

**Comment by martignoni** [comment]
These are now translated.
