### ISSUE TITLE
Visual Magnitudes for Some DSOs widely different than typical catalogue values

### ISSUE THREAD

**Issue by clavecinist** [Stellarium/stellarium#2375]
Some DSOs - including prominent Messier objects, display visual magnitudes much fainter than reported in other resources. For example, M88 and M91 are both reported as fainter than 13th magnitude, which would have put them out of reach of Messier and Mechain themselves! I am not sure how pervasive the problem is, but it is mildly disturbing that bright objects are being kept off the charts until I zoom in a lot because their catalogued visual magnitudes are wrong/too faint.

**Comment by alex-w** [comment]
We use magnitudes for DSO from standard scientific catalogues and databases, such SIMBAD.

**Comment by clavecinist** [comment]
I can appreciate using SIMBAD data, etc, but when the SIMBAD data and reality are so far apart as with M88 and M91, there is a problem for the people who are trying to use it and don't know better that their scopes may or may not be able to see those objects. Is there no recourse for objects with glaringly wrong magnitudes to be reported and corrected?

**Comment by alex-w** [comment]
> I can appreciate using SIMBAD data, etc, but when the SIMBAD data and reality are so far apart as with M88 and M91, there is a problem for the people who are trying to use it and don't know better that their scopes may or may not be able to see those objects. 

Sorry, but do you really think that scientific catalogs and databases use random values for magnitudes, which are not related to reality? Magnitudes for M88 and M91 are coming from "[A catalogue of quasars and active nuclei: 13th edition](http://simbad.cds.unistra.fr/simbad/sim-ref?bibcode=2010A%26A...518A..10V)" which contains photometry data for more that 100000 galaxies. And these data was obtained from the photometer. Can these data contains errors? Maybe.

The next question: which values for you are typical for these objects? The original Messier catalog has no magnitudes.

> Is there no recourse for objects with glaringly wrong magnitudes to be reported and corrected?

We can put any values for magnitudes, but... which values are correct?

**Comment by clavecinist** [comment]
Man, look I think overall the values in Stellarium are fine. But for these
particular objects the program lists values of 13.18 (M88) and 13.57 (M91).
Stephen J. O'Meara lists these objects as  9.6 and 10.2 respectively in his
Messier Objects Deep Sky Companion. That is a huge difference. I have a 4.5
inch telescope, and I have observed these galaxies successfully many times.
Galaxies in the mag 13 range are way too faint to be seen in my scope, even
if I was observing with ideal dark sky conditions. It takes a large scope
to observe that. The data here are so flat out wrong from the perspective
of a visual (not photometric) observer that it was concerning, which is why
I reported it. While V band magnitudes often correlate with overall visual
brightness, these objects are clearly example where there is a problem.

As an end user, this problem means I cannot always reliably create charts
for our monthly 'What's Up' feature at the local astronomy club meetings
for our beginner visual observers. RASC is instructing people on the use of
Stellarium due to it's wonderful features and free pricetag. I don't know
how pervasive the problem is just yet or if these particular galaxies are
outliers, so I will have to evaluate whether I need to find an alternative
software for this task over time if this isn't going to be fixed. I
understand this is probably a big, complicated ask.

I leave it to you to decide what is right for Stellarium.

**Comment by gzotti** [comment]
I can imagine that a catalog of quasars and AGN lists the "core magnitude", and not the integrated magnitude of the extended disk. However I agree with OP that these Messier objects are commonly listed as much brighter. Probably some other catalog, e.g. Revised NGC, should be used for more common objects, and the QSO/AGN catalog only for smaller/fainter objects that are not listed in the NGC.

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest

**Comment by stx-chris** [comment]
We spotted a similar thing for `88 Tau`, for instance. Most sources (incl. SIMBAD, Hipparcos, Cartes du ciel) give `4.25` as the value of apparent magnitude. Stellarium gives `6.60`, which we cannot explain.

**Comment by gzotti** [comment]
My Stellarium shows mag 4.40 for d Tau=88 Tau=HIP21402A.

**Comment by stx-chris** [comment]
Hi @gzotti thanks for your quick feedback. My Stellarium instance (latest release) associates `88 Tau` with `HIP 21402 C` instead of `A`, which is why the wrong magnitude might be shown. SIMBAD query returns only `HIP 21402`. I cannot even find `HIP 21402 A` in Stellarium. How did you get your listing?

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/62717406/169687838-e64c71d2-8190-4aba-91c0-2804eb8cde47.png">

**Comment by gzotti** [comment]
I searched for 88 Tau. This was not found in the list of internal objects, so a SIMBAD query was fired. This caused a Custom Object marker to appear labeled "*88 Tau". I clicked on the star next to it which happened to be d Tau, listed as mag 4.40. This is in version 0.22.1.

**Comment by stx-chris** [comment]
I understand; this must be a bug then. When I execute your steps and manually click on the brightest star, labeled "d Tau", I also arrive at the correct star `HIP 21402 A` with the right magnitude (see new screenshot). It is just that if one searches for it by its names `d Tau`, `88 Tau`, `HIP 21402`, Stellarium shows the wrong star `HIP 21402 C`.

Does anybody have an explanation for this behavior? 

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/62717406/169689919-4672b7d3-85cb-4f89-9fda-a14c1bd07bf9.png">

**Comment by gzotti** [comment]
Ah, yes. Searching for "d Tau" instead of "88 Tau" finds the internal entry immediately (without SIMBAD) but leads to the HIP C component. Cannot say why.

**Comment by stx-chris** [comment]
@gzotti Can I ask you to reopen this issue or do you want me to reopen a new bug report? Thx

**Comment by gzotti** [comment]
It is a star, no DSO, so the issue is not a problem with DSO magnitudes. @alex-w ?
