### ISSUE TITLE
Stellarium 22 Missing libQt5Charts.so.5

### ISSUE THREAD

**Issue by RLWagner** [Stellarium/stellarium#2378]
When trying to run either snap or appimage version I get an error "./stellarium: error while loading shared libraries: libQt5Charts.so.5: cannot open shared object file: No such file or directory"  Should this not be included in the package?

**Comment by ckuethe** [comment]
Reproducible on Ubuntu 21.10:

```
/tmp/.mount_StellajeQYpr//usr/bin/stellarium: /tmp/.mount_StellajeQYpr//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5Charts.so.5)
```

**Comment by ckuethe** [comment]
Thanks. Unfortunately this doesn't work on my machine:

```
ckuethe@thorium:/tmp$ /usr/bin/unzip Stellarium-edge-x86_64.zip 
Archive:  Stellarium-edge-x86_64.zip
  inflating: Stellarium-edge-x86_64.AppImage  
ckuethe@thorium:/tmp$ chmod +x Stellarium-edge-x86_64.AppImage 
ckuethe@thorium:/tmp$ ./Stellarium-edge-x86_64.AppImage 
/tmp/.mount_Stellabp8dyw//usr/bin/stellarium: /tmp/.mount_Stellabp8dyw//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /lib/x86_64-linux-gnu/libQt5Charts.so.5)
```

**Comment by alex-w** [comment]
@ckuethe @RLWagner please check https://github.com/Stellarium/stellarium/suites/5929078993/artifacts/202797190

**Comment by ckuethe** [comment]
Awesome. That latest one works. It picked up my custom terrain and connected to my telescope.

Thanks!

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest

**Comment by ckuethe** [comment]
Yep, that works.
