### ISSUE TITLE
Mistranslations to Spanish in object names: NGC4147 and NGC3532

### ISSUE THREAD

**Issue by theradioboy** [Stellarium/stellarium#2380]
I've seen a couple of objects with mistranslated names in Spanish.

NGC4147, "Kick the can", is mentioned in "The Secret Deep", a book by Stephen James O'Meara as named after a Twilight Zone episode in which a group of elders from a nursing home rejuvenate after playing the "Kick the can" game, as this would relate to the blue stragglers found in the core region of the cluster. The translation to Spanish as it is now in Stellarium reads "Patear el Can". In Spanish, "Can" means, simply put, "dog", so the name becomes really weird: "to kick the dog". 
A better translation would be "Patear la lata" o "Bote pateado". The issue with the second translation (which would literally be "kicked can") is that "bote" can mean a "can" in the original sense, but also means "boat". "Lata" might or not have additional meanings in different countries, but it probably is the best bet. Another option is "patear el tarro", but that will probably be equivalent only in a few regions. However, besides "Kick the can" being probably a bit non-standard, the name loses its context a lot more when considering that, as far as I know, the game is not that famous in the Spanish-speaking community, the series is not as famous everywhere in the Spanish-speaking regions, the corresponding chapter of the series is quite old, and hence a lot of context and cultural references are needed to understand the point of the name, which I think it's already somewhat difficult in English.

The second issue happens with C91 (NGC 3532), the "Wishing well cluster". The main translation to Spanish reads "Cúmulo Deseando bien", which would be like saying "Wishing [someone] well cluster". The correct translation would then be "Cúmulo Pozo de los Deseos" if one means a vertical shaft in the ground made to obtain water, in which one asks for a wish.

**Comment by gzotti** [comment]
Translation is an art...
Yes, there are some objects whose funny names need background research. (I would exclude some references from my installation as soon as we make this possible.) Thanks for these examples. I have never watched Twilight Zone, so I would never understand this name completely, but kicking something around is probably one of the oldest games. (Soccer is the regulated variant very visible in the Spanish world :) Not sure if it makes sense to name this cluster after localized versions of "kick-something-around". 

Indeed the only sense of wishing well is the "vertical shaft with water on the bottom" kind of well, not the adverb to "good".

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
