### ISSUE TITLE
Trouble with selection priority of nomenclature items 

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#239]
### Expected Behaviour
Zoom to see Jupiter and its large moons. The moons are still tiny on screen. Click to select Io.

### Actual Behaviour
If Io is deep enough in Jupiter's shadow, some named feature on Io gets selected.

This is useless. At this scale of a few pixels, the only meaningful hit should be Io. Even more so as I have disabled display of planetary nomenclature. 

Probably we should first select the celestial body, and only then become "hot" for named features on this previously selected body? And with some extra penalty if named features are disabled. 

### Steps to reproduce
e.g. 2018-08-03 19:43:15 UT. Io is partly shadowed by Jupiter. 

### System
* Stellarium version: master.16154

### Logfile 
Irrelevant here.

**Comment by alex-w** [comment]
This behavior is useful for the Moon during lunar eclipse

**Comment by gzotti** [comment]
Hmm, when the Moon is large enough to see detail, it may be useful. When the Moon (or Io etc.) is 5px wide, it does not make sense, really. You cannot discern Plato from Clavius. And indeed, during Friday's Lunar eclipse, named features are selected when the FoV was smaller than about 4.25 degrees, so the moon was tens of pixels in diameter and showed enough structural detail. 

I think the first hit should always select the whole body, and only if that object is displayed in significant size, selection could go deeper and hit some named crater or so.
