### ISSUE TITLE
Location Setting problem

### ISSUE THREAD

**Issue by Martythorn** [Stellarium/stellarium#2392]
Trying without success to create a new location on Stellarium 0.21.3, Windows 10 fully patched, latest drivers
I Entered this 

![Location 1](https://user-images.githubusercontent.com/103525965/163016473-bf8117ce-b16e-49de-aec9-c4ef5d38430c.jpg)

When I retrieved the location I get this 
![Location 2](https://user-images.githubusercontent.com/103525965/163017739-52aebccf-b863-49ab-a9fa-9d2c1e0d1231.jpg)
This was the previous location

**Comment by alex-w** [comment]
The issue was fixed in version 0.22.0

**Comment by Martythorn** [comment]
Thanks for the speedy response

**Comment by Martythorn** [comment]
Many thanks
