### ISSUE TITLE
Stellarium on MacOS (not connecting to Meade telescope)

### ISSUE THREAD

**Issue by peilematthew** [Stellarium/stellarium#2393]
Trying to connect Meade LX90 to stellarium running on MAC OS

Can not sync or slew Mount

I have succesfully controlled this Meade Lx90 mount with Stellarium on Windows

* Latest version of Stellarium
* MacOS Monterey
*

**Comment by alex-w** [comment]
Did you install the driver for USB-To-RS232 device?

**Comment by gzotti** [comment]
@peilematthew we need information from you. If you don't respond, we will close this around June 23.

**Comment by gzotti** [comment]
Closed by non-response
