### ISSUE TITLE
Astronomical Calculations tool extremelly slow

### ISSUE THREAD

**Issue by EnMazinger** [Stellarium/stellarium#2398]
Dear all,
I searched the forums and I did not found my issue.
I have a desktop computer with Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz with 12GBRAM memory, running Stellarium 0.22.0. The performance of the program is good when accelerating time speed. I can see animation of the sky quite smoothly even with increased time steps like months or years. I get around 6.5FPS speed. Zooming in/out and finding objects is also ok. The issue comes when I select the window for astronomical calculations. In this window everything goes really slowly. Updates take time, short period ephemerides calculation takes long time. It is like I was using a completely separate calculation engine, and this engine is broken.
I own another laptop computer with slower Intel i5 processor. In this computer everything goes quick and smooth as one could expect. 
The issue on my i7 computer has been around in previous versions of Stellarium with no sign of improvement as newer versions are being installed.
Anyone has an idea on how to fix it?
Thank for your time and support.

**Comment by alex-w** [comment]
Please attach log.txt file from Stellarium, where works on problematic PC

**Comment by EnMazinger** [comment]
2022-04-14T07:01:32
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 15.9 (Visual Studio 2017)
Qt runtime version: 5.12.6
Qt compilation version: 5.12.6
Addressing mode: 64-bit
Total physical memory: 12223 MB
Available physical memory: 7502 MB
Physical memory in use: 38%
Processor speed: 3408 MHz
Processor name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Processor speed: 3408 MHz
Processor name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Processor speed: 3408 MHz
Processor name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Processor speed: 3408 MHz
Processor name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Processor speed: 3408 MHz
Processor name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Processor speed: 3408 MHz
Processor name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Processor speed: 3408 MHz
Processor name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Processor speed: 3408 MHz
Processor name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
F:\Aplicacions\Stellarium\stellarium.exe 
 -----------------------------------------------------
[ This is Stellarium 0.22.0 - https://stellarium.org/ ]
[ Copyright ? 2000-2022 Stellarium Developers         ]
 -----------------------------------------------------
Writing log file to: "C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.6.0 NVIDIA 431.07"
Current Format:  QSurfaceFormat(version 4.6, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::sRGBColorSpace, profile  QSurfaceFormat::CompatibilityProfile)
StelMainView::init
Detected: OpenGL "4.6"
Driver version string: "4.6.0 NVIDIA 431.07"
GL vendor is "NVIDIA Corporation"
GL renderer is "GeForce GTX 745/PCIe/SSE2"
GL Shading Language version is "4.60 NVIDIA"
GLSL Version Number detected:  4.6
GLSL version is fine, we should not see a graphics problem.
Sky language is  "ca_ES"
Planetary features language is  "ca_ES"
Application language is  "ca_ES"
Scripts language is  "ca_ES"
Cache directory is:  "C:\\Users\\Jordi\\AppData\\Local\\stellarium\\stellarium\\cache"
Loaded 252 countries
Loaded 193 regions
StelLocation::createFromLine(): TimeZone name for  "caldes de montbui"  not found. Translating ""  to  "UTC"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
SolarSystem has  24735 entries.
Loaded 24652 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15781 / 15783 items of planetary surface nomenclature
WARNING - These planets to assign nomenclature items were not found: "Dactyl"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
"Loading C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_4_1v0_2.cat: 4_1v0_4; 1692779"
"Loading C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_5_2v0_1.cat: 5_2v0_1; 7083058"
"Loading C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_6_2v0_1.cat: 6_2v0_1; 24670782"
"Loading C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_7_2v0_1.cat: 7_2v0_1; 50733321"
"Loading C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_8_2v0_1.cat: 8_2v0_1; 92304337"
Finished loading star catalogue data, max_geodesic_level:  8
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4941 / 4941 scientific star names
Loading scientific star extra names from ".\\stars\\default\\extra_name.fab"
Loaded 26200 / 26200 scientific star extra names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 22992 / 22992 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108378 / 108378 cross-identification data records for stars
Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
Loading proper motion data from ".\\stars\\default\\hip_pm.dat"
Loaded 117955 / 117955 proper motion data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.14 (standard edition)"
Loaded 94668 DSO records
Loading DSO outline data ...
Loaded 95 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 1099 / 1099 common star names
Loading DSO name data ...
Loaded 1174 / 1197 DSO name records successfully
WARNING - No position data for 23 objects: "PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1000714, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Loaded 84 / 84 asterism records successfully for culture "western"
Loaded 74 / 74 asterism names
stel.OpenGLArray: Vertex Array Objects are supported
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Observability"
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at:  "C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Loaded plugin "OnlineQueries"
Loaded plugin "Quasars"
[Quasars] Version of the format of the catalog: 1
[Quasars] Loading catalog file: "C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\modules\\Quasars\\quasars.json"
Loaded plugin "RemoteControl"
RemoteControl using QtWebApp version 1.6.4-stellarium
StaticFileController: docroot=F:/Aplicacions/Stellarium/webroot, encoding=UTF-8, maxAge=60
StaticFileController: cache timeout=60000, size=1048576
Loaded plugin "Satellites"
[Satellites] loading catalogue file: "C:\\Users\\Jordi\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "1998-067SX" "49278"
Satellite has invalid orbit: "ELECTRON KICK STAGE R/B" "52199"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Loaded plugin "TelescopeControl"
[TelescopeControl] Only embedded telescope servers are available.
[TelescopeControl] Adding device model: "Meade AutoStar compatible" "Any telescope or telescope mount compatible with Meade's AutoStar controller." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Meade LX200 (compatible)" "Any telescope or telescope mount compatible with Meade LX200." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Meade ETX70 (#494 Autostar, #506 CCS)" "Meade's ETX70 with the #494 Autostar controller and the #506 Connector Cable Set." "TelescopeServerLx200" 1500000
[TelescopeControl] Adding device model: "Losmandy G-11" "Losmandy's G-11 telescope mount." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Wildcard Innovations Argo Navis (Meade mode)" "Wildcard Innovations' Argo Navis DTC in Meade LX200 emulation mode." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Celestron NexStar (compatible)" "Any telescope or telescope mount compatible with Celestron NexStar." "TelescopeServerNexStar" 500000
[TelescopeControl] Adding device model: "Sky-Watcher SynScan (version 3 or later)" "Any Sky-Watcher mount that uses version 3 or later of the SynScan hand controller." "TelescopeServerNexStar" 500000
[TelescopeControl] Adding device model: "Sky-Watcher SynScan AZ GOTO" "The Sky-Watcher SynScan AZ GOTO mount used in a number of telescope models." "TelescopeServerNexStar" 500000
[TelescopeControl] loadTelescopes(): Deleted node unrecogised as slot: "version"
[TelescopeControl] Loaded successfully 1 telescopes.
Unable to find module called "Calendars"

**Comment by worachate001** [comment]
Having a very large number of objects in 'C:\Users\Jordi\AppData\Roaming\Stellarium/data/ssystem_minor.ini' can slow down the program. I would like to suggest trying to delete this file (rename or create a backup of the file before deleting it) and start the program again. Add only objects that you really want should help.

**Comment by EnMazinger** [comment]
Wooow !!
Very impressive right now.
My ssystem_minor.ini file was 17MB big. I renamed it as system_minor.ino just to make sure the program does not find it. Now the astronomical calculations work really fast again.
Thank you for the help! From now on, I will check that this file does not get big.

**Comment by alex-w** [comment]
This is important questions: please describe how you used AstroCalc/Ephemeris tool, for which objects?

**Comment by EnMazinger** [comment]
Nothing special in particular, sometimes I want to track the minor body track on the sky along the days. Sometime I want to sort by filter a given set of objects like Caldwell. Sometimes I want to find phenomena between asteroid and planets in a given time period. 
Stellarium is such a magnificent piece of software !

**Comment by gzotti** [comment]
There is nothing we can do about it apart from finding a way to push the asteroid computations into GPGPU programs or other ways of parallelization. For now I close this.
