### ISSUE TITLE
Deletion of class GPSLookupHelper by pointer to incomplete type

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#240]
While compiling current Stellarium on Ubuntu amd64 with g++ 5.4.1 I get the following warnings:
```
/home/ruslan/packages/stellarium/src/core/StelLocationMgr.cpp: In destructor ‘virtual StelLocationMgr::~StelLocationMgr()’:
/home/ruslan/packages/stellarium/src/core/StelLocationMgr.cpp:458:10: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
   delete nmeaHelper;
          ^
/home/ruslan/packages/stellarium/src/core/StelLocationMgr.cpp:458:10: warning: invalid use of incomplete type ‘class GPSLookupHelper’
In file included from /home/ruslan/packages/stellarium/src/core/StelLocationMgr.cpp:19:0:
/home/ruslan/packages/stellarium/src/core/StelLocationMgr.hpp:32:7: note: forward declaration of ‘class GPSLookupHelper’
 class GPSLookupHelper;
       ^
/home/ruslan/packages/stellarium/src/core/StelLocationMgr.cpp:458:10: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
   delete nmeaHelper;
          ^
/home/ruslan/packages/stellarium/src/core/StelLocationMgr.cpp:463:10: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
   delete libGpsHelper;
          ^
/home/ruslan/packages/stellarium/src/core/StelLocationMgr.cpp:463:10: warning: invalid use of incomplete type ‘class GPSLookupHelper’
In file included from /home/ruslan/packages/stellarium/src/core/StelLocationMgr.cpp:19:0:
/home/ruslan/packages/stellarium/src/core/StelLocationMgr.hpp:32:7: note: forward declaration of ‘class GPSLookupHelper’
 class GPSLookupHelper;
       ^
/home/ruslan/packages/stellarium/src/core/StelLocationMgr.cpp:463:10: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
   delete libGpsHelper;
          ^
```
Technically, deletion through a pointer to incomplete type is undefined behavior. I've come across a crash lately, on another machine, with terminal saying something about GPS. I don't remember the details (this crash never reproduced since), but it might be related to these warnings.

**Comment by 10110111** [comment]
Oh, right. I indeed have `ENABLE_GPS:BOOL=0`. But shouldn't then both pointers simply be `#ifdef`-excluded sinilarly to `StelLocationMgr::locationFromGPS()`, along with the code in the destructor? At least for cleanliness, but also to silence these scary warnings.

**Comment by gzotti** [comment]
Yes. Just that I never saw those warnings. Ah yes, I never compiled this version without GPS.... Will fix that.

It would be interesting to find out what caused the crash. Re-plugging GPS devices to other USB ports in the "right" moment may confuse the program under rare conditions, but regular use should not fail.

**Comment by 10110111** [comment]
The interesting fact about that system where I got the crash is that the library was not found at the CMake stage, so GPS is actually unsupported there. But in any case, I also don't have any devices plugged in too. Might be that this has been fixed by one of the updates since then, so don't worry about this crash until I make a formal issue report :) .

**Comment by gzotti** [comment]
Hm, you need libGPS and/or QPositioning for that as described in https://github.com/Stellarium/stellarium/wiki/Linux-build-dependencies#linux-users. Else... no GPS.
