### ISSUE TITLE
Abbreviation of Canes Venatici (CVn)

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#2400]
Both CVn and Cvn exist in skyculture texts, maybe it is better to fix all them to CVn.

**Comment by ultrapre** [comment]
Triangulum Australe (TrA) also show same problem.

**Comment by alex-w** [comment]
Where is you found it?

**Comment by ultrapre** [comment]
On *.fab in the skyculture's sub-folder.

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
