### ISSUE TITLE
0.22.1: Segfault if star catalogues (v2.0) added to existing installation

### ISSUE THREAD

**Issue by Kangie** [Stellarium/stellarium#2404]
While packaging 0.22.1 for Gentoo (gentoo/gentoo#25054) I noticed that if I enable the `stars` USE flag (which simply downloads  the stars catalogue v2.0 files from stellarium-data & installs to `/usr/share/stellarium/stars/default`) after initialising the application without it that the application segfaults immediately after importing/loading the data for the first time.

All subsequent launches behave as expected, and if the initial launch detects these files it does not segfault.

### Expected Behaviour

Stellarium should launch successfully when star catalogue `.cat` files are added.

### Actual Behaviour

```
. . .
Loading nomenclature for Solar system bodies ...
Loaded 15781 / 15783 items of planetary surface nomenclature
WARNING - These planets to assign nomenclature items were not found: "Dactyl"
Loading star data ...
"Loading /usr/share/stellarium/stars/default/stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading /usr/share/stellarium/stars/default/stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading /usr/share/stellarium/stars/default/stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading /usr/share/stellarium/stars/default/stars_3_1v0_4.cat: 3_1v0_4; 425807"
Found file  "/usr/share/stellarium/stars/default/stars_4_1v0_2.cat" , checking md5sum..
MD5 sum correct!
"Loading /usr/share/stellarium/stars/default/stars_4_1v0_2.cat: 4_1v0_4; 1692779"
Found file  "/usr/share/stellarium/stars/default/stars_5_2v0_1.cat" , checking md5sum..
MD5 sum correct!
[1]    1741584 segmentation fault (core dumped)  stellarium --verbose
```

### Steps to reproduce

1. Install stellarium with `USE=-stars`
2. Launch the application
3. Install with `USE=stars`
4. Launch the application

I assume that this behaviour can be replicated by installing a binary distribution, launching it without the catalogue files, adding the catalogue files, then launching the app again.

### System
* Stellarium version: 0.22.1 - Gentoo
* Operating system: Gentoo, ~amd64
* Graphics Card: Nvidia

**Comment by Kangie** [comment]
See the linked PR for additional info / troubleshooting.

**Comment by DarthGandalf** [comment]
Same happens if stars were available on previous runs, but then got removed. Then the first run after the removal also segfaults

**Comment by alex-w** [comment]
I cannot reproduce it on my linux-box (Ubuntu Linux 20.04.1)
