### ISSUE TITLE
Opacity-Mag conflict in Dark nebula catalog

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#2408]
Like B157 and B223, using Opacity in VMag, but they are Molecular Cloud, making their show as magnitude, whose labels show so bright.

**Comment by gzotti** [comment]
Dark clouds have a problem in that the usual magnitude does not apply. However, also not just mag loss, but probably contrast with the surrounding area would be a useful datum to display and sort by. Feel invited to develop a useful scheme!

**Comment by alex-w** [comment]
Not all molecular clouds are dark…
