### ISSUE TITLE
Bug: The Eridanus-Taurus/Cetus constellation border is desync.

### ISSUE THREAD

**Issue by GammaMicroscopii** [Stellarium/stellarium#241]
Stellarium version: confirmed for 0.18.0 and 0.18.1
Sky culture: Western
Show constellation borders: active
Show "IAU constellation" field of objects: active

Tou can see that the visual constellation border between Eridanus and Taurus/Cetus doesn't match the constellation shown in the IAU constellation information field. There is a chunk of sky that, as the borders, is shared by Taurus and Cetus, but if you select an object in there, it shows "Eri" as the IAU constellation.

That chunk is the rectangle between the opposite corners +0º 24' 13" / 3h 41min 25s and -1º 13'16" / 2h 45min 21s (J2000, equatorial coordinates).

**Comment by alex-w** [comment]
Apparently it's not borders problem - it's problem of rounding error in getIAUConstellation() data.

**Comment by gzotti** [comment]
No. Have a look in 1875 coordinates. A small box south of 10 Tau was apparently omitted in the fast-identification list ADC VI/42. I hope I can work out the right format of that catalog now.

**Comment by gzotti** [comment]
Strange, the lines are present, problem must be elsewhere. Continuing...

**Comment by gzotti** [comment]
Bah, a very stupid parsing error. Makes a lot of similar problems in the Southern hemisphere.
