### ISSUE TITLE
Strange glare of 47 Tuc

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#2420]
I find a strange glare just at west of 47 Tuc as below:

![QAI_ GTYZEWAO7Q %WD7$%9](https://user-images.githubusercontent.com/32613953/165110134-fa72a3af-675c-49da-ad56-b2dac916b5f1.jpg)

![ICJVJCLX8ZW_HBID533@X 0](https://user-images.githubusercontent.com/32613953/165110059-93dda023-8533-426c-ba60-4fa54c5037c8.jpg)

Sunshuwei points out it is the problem caused by Milkyway background (textures\milkyway.png), which may be due to field curvature at high latitudes?

![E`6% IO$X7@J6VML3{GF9{G](https://user-images.githubusercontent.com/32613953/165110402-22e08a2a-467a-4b43-b8a4-8f2466649f54.png)

**Comment by gzotti** [comment]
Indeed. Not so long ago sb deleted most of these "echoes", but apparently not this one.

**Comment by gzotti** [comment]
Uh, not so fast. My thumbs-up was a thank to Atque. Probably this smudge should also be edited away, and then maybe some more so far unseen.

**Comment by Atque** [comment]
Hm, I was about to say that I would prefer it be left, but now I see that 47 Tucana is visible even with large FOV's. The whole point of leaving the DSO's untouched was to visualize the naked eye DSO's, which would otherwise be lost unless the user zooms in to a certain FOV. However, the "fuzziness" of 47 Tuc is lost if edited away. I'm not sure.

**Comment by gzotti** [comment]
The echo is roughly 20' away from the visible 47 Tuc which is created in the right position from the star catalog. I wonder how this happened in the first place, but it's clearly ugly and misplaced. If anything, a brightening could be placed manually where it belongs, under 47 Tuc.

**Comment by Atque** [comment]
I might give it a shot.
