### ISSUE TITLE
Catalog Filter: logic feature request

### ISSUE THREAD

**Issue by silas1037** [Stellarium/stellarium#2425]
![image](https://user-images.githubusercontent.com/36977717/166141806-ad65c4b2-ea54-41dd-9190-9dff86842b19.png)

- [x] add checkbox to "select all" and "select none"
reason: we can switch quickly without selecting one by one.

- [ ] add optical checkbox, logic: "and (&)" among catalogs
reason: make it only show objects in all catalogs selected (such as Arp and NGC).

**Comment by alex-w** [comment]
For the second option: 1) this is problematic to implementation and 2) I see no reason to implement it, because e.g. when all catalogs selected then user will see no DSO objects

**Comment by silas1037** [comment]
Well, I read the code about using "flag or" logic to depend objects showing, which is difficult for the second to achive.

**Comment by silas1037** [comment]
If v4 catalog is on progress, I hope more it will be more extensible, such as loading multiple catalog files, or to display only the celestial objects above based on a user's custom list.
