### ISSUE TITLE
observing list with non-designation object

### ISSUE THREAD

**Issue by silas1037** [Stellarium/stellarium#2426]
![image](https://user-images.githubusercontent.com/36977717/166147348-7d19e3b5-f06c-4bf1-9fb1-6eb423135641.png)

By adding Calabash Nebula to list, it cannot work.

It cannot save objects with coordinate but without catalog-id to list. 
I suggest making it can identify coordinate-only object, so that users can make plan with objects not in software catalog.
I know the observing list is developing, maybe it is not in plan. Thanks!

**Comment by ultrapre** [comment]
> @silas1037 Hi, more details please to reproduce the problem. Thanks. :)
> 
> Jocelyn

You can add a random and weak star without labels into list, it will temporaly show position in list, but it cannot be used to locate again.

**Comment by Jocelyn1109** [comment]
Hi @ultrapre ,
As I understand you add this object (Calabash Nebula) into ObservingList and the object name is not a name but coordinates ?

Jocelyn

**Comment by silas1037** [comment]
> Hi @ultrapre , As I understand you add this object (Calabash Nebula) into ObservingList and the object name is not a name but coordinates ?
> 
> Jocelyn

Yes.

**Comment by ultrapre** [comment]
> Hi @ultrapre , As I understand you add this object (Calabash Nebula) into ObservingList and the object name is not a name but coordinates ?
> 
> Jocelyn

Yes.

**Comment by Jocelyn1109** [comment]
@silas1037 ok thanks for your reply. I will see this particular case :)

Jocelyn

**Comment by Jocelyn1109** [comment]
Hi @gzotti, What should we do in the case that the object has no name or if the name is not correct (for example only on character) like one the picture 
Currently in the code when the name of the object is empty we do (like on current bookmark):

`if (objectName.isEmpty()) {`
   `objectName = QString("%1, %2").arg(objectRaStr, objectDecStr);`
   `objectNameI18n = q_("Unnamed object");`
   `fov = GETSTELMODULE(StelMovementMgr)->getCurrentFov();`
`}`

I did the test with: Calabash Nebula

![bad_name](https://user-images.githubusercontent.com/43777557/170021984-598a9560-fea2-462e-a527-2b10ebbe4fae.png)
?

**Comment by gzotti** [comment]
I wonder how object name can be empty? StelObject::getEnglishName() should deliver this, and StelObject::getNameI18n() should deliver its translated name. For unnamed stars, yes, a coordinate-based "name" can be formed, but I would not use englishName for this and then use "unnamed object" in the translated string.

**Comment by Jocelyn1109** [comment]
@gzotti  I updated the post with a possible solution.
