### ISSUE TITLE
Downloading meteor showers

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2428]
In version 3.0 of Meteor Showers plugin we have a broken signal/slot in download manager for updates of meteor showers data. As a result we have a invalid status in the GUI and warnings in the log.

To get a warning in the log you can open GUI of the plugin and please press "Update..." button to get the issue in the GUI.

**Comment by worachate001** [comment]
My investigation so far:
1. In Ubuntu, the update process goes well (despite the error about signal).
2. I switched to Windows 10 and got this error:
"qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed"
It also happens to other plugins.
3. I installed OpenSSL v1.1.1n in Windows 10. The qt.network.ssl error goes away and the update succeed.
4. I tried reusing some codes from another plugin to fix the signal bug, it seems to work well.

Still testing and learning...
