### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Stellarium/stellarium#243]
I would like to point out that identifiers like “[`_STELMAINGRAPHICSVIEW_HPP_`](https://github.com/Stellarium/stellarium/blob/f7acb15cc34337a1b9cc36b604e85366ccfbfc69/src/StelMainView.hpp#L20 "Update candidate")” and “[`_VECMATH_H_`](https://github.com/Stellarium/stellarium/blob/f7bcbd26bc39d9da77eb5c80a8ec9ad3213376df/src/core/VecMath.hpp#L24 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by alex-w** [comment]
Thanks for report!

**Comment by elfring** [comment]
Are there [any further update candidates left over](https://github.com/Stellarium/stellarium/blob/c1f2ed17b8195b970fbf2f638d2040bb9cbe554f/src/core/RefractionExtinction.hpp#L23 "Update candidate")?

**Comment by gzotti** [comment]
Possibly. In which way is _REFRACTIONEXTINCTION_HPP_ in a file RefractionExtinction.hpp violating the naming convention of the C++ language standard?

Please help with pull requests, not by teaching. Some of the code has worked for a decade or more.

**Comment by alex-w** [comment]
It's fixed already (see warnings in QtCreator with clang model)

**Comment by alex-w** [comment]
> How do you think about to avoid that this software depends on undefined behaviour?

@elfring are you meant something concrete or all 200+ cases for C 11 Standard? In any case please fill separate bug report for UB.

**Comment by alex-w** [comment]
Ah, sorry, @elfring - you are right!

**Comment by elfring** [comment]
Thanks for [your renaming of affected include guards](https://github.com/Stellarium/stellarium/commit/c4c3552dbd67c6e50f4c035402eb3fc82fcd4354 "Update headers").

I propose to [take another look](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") at [remaining update candidates](https://github.com/Stellarium/stellarium/blob/dd849ef98f18165d961597b05b965f07f3b85022/plugins/LogBook/src/gui/TargetsDialog.hpp#L19 "Update candidate").

**Comment by alex-w** [comment]
LogBook is outdated plugin (who has been never finished yet) and he is not compiled by default. I think he will be not compile in principle due old code. This plugin should be re-written or removed.

**Comment by elfring** [comment]
Thanks for such background information.

Will any implementation details be still adjusted for plugins like “Satellites” and “Scenery3d”?
