### ISSUE TITLE
Telescope Control works only if I run Stellarium 0.21.1

### ISSUE THREAD

**Issue by ArnoldBrody** [Stellarium/stellarium#2434]
I have three versions of Stellarium (0.21.1, 0.21.2 and 0.22.0) installed on my ASUS VivoBook 17 running Windows 11 
     Processor	Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz   1.10 GHz
     Installed RAM	8.00 GB (7.83 GB usable)
     System type	64-bit operating system, x64-based processor

I tried controlling the AVX with Stel 0.22.0. I had to change COM3 to COM4 and then it was able to  connect. Or so it said. But I never saw my telescope's indicator in Stellarium when viewing the same area my scope was pointing to. If I did a search for the name of my telescope connection (Arnies AVX) or asked to slew to a star, the program crashed.

I launched Stel 0.21.2. It connected to my AVX on start-up. But still no indicator on the screen. If I try to slew the scope to a target, Stel crashes.

I launched Stel 0.21.1. It connected to my AVX on start-up and worked perfectly. The indicator appears, I can search for my telescope connection, and I can slew to targets (quite accurately). 

Please let me know if more information is needed. Thank you.

**Comment by gzotti** [comment]
Not that I could fix this, but it could help if you can disclose the protocol "Arnies AVX" is using. Is that a LX200 compatible?

**Comment by ArnoldBrody** [comment]
Here are the configuration settings for my telescope connection (in case
this answers your question).

For Stellarium Versions 0.21.1, 0.21.2, 0.22.0 (all the same)

*Telescopes Controlled*
# 1, Type = Local, Stellarium, Name = Arnies AXV

Configuration of Arnies AVX

*Telescope controlled by:* Stellarium, directly through a serial port

*Telescope Properties*
Name: Arnies AVX
Connection delay: 0.50s
Coordinate system: Equinox of the date (JNow)
(checked) Start/connect at startup

*Device settings*
Serial port: COM4
Device model: Celestron NexStar (compatible)

*User interface settings*
(not checked) Use field of view indicators

*Options tab*
*GUI*
(checked all three) Show Telescope labels, Show telescope reticles, Show
field of view indicators

*About tab*
*Telescope Control plug-in *Version 0.4.2

**Comment by alex-w** [comment]
Could you try windowed mode?

**Comment by aargeebee** [comment]
I just purchased a Avus laptop (same one as ArnoldBrody) just to control a telescope in the field, and have spent 2 days tearing hair out trying to get Stellarium to recognise my Dob8 Goto. I have had Stellarium 0.21.2 on an Avus Desktop PC for a few months and it works perfectly. Same hardware connected to new Avus laptop simply wont work on latest Stellarium. I installed Stellarium 0.21.1. into laptop and scope was connected on first try.. Very happy I saw this report by Arnold..  Why this bug should exist is beyond me !!

**Comment by gzotti** [comment]
Have you seen the other issue reports about the TelescopeControl plugin? Have you tried the Qt5-based build of V1.2 already? If not, or if this still does not work, please attach the Logfile which we are always requesting. Somebody out there with a GOTO telescope and the same problem may hopefully eventually look into it.

**Comment by aargeebee** [comment]
I just found the qt5 v1.2  and the scope was recognised by it and works fine... so I guess that would indicate something to do with qt6..  
Q.. why are previous versions not available on the Stellarium website? Had to go looking for it on the web.

**Comment by aargeebee** [comment]
.... downloaded from SourceForge

**Comment by gzotti** [comment]
![2023-01-06 09_36_27-Stellarium Astronomy Software – Mozilla Firefox](https://user-images.githubusercontent.com/18099873/210964385-10d44408-4897-4393-924d-3cb3107d6f95.jpg)

**Comment by gzotti** [comment]
Several Qt6/TelescopeControl issues have been solved before 23.3. We tentatively close this as member of a large group of related issue reports for now. In case of re-occurrence of this issue in V23.3, please create a new report with very clear description of circumstances.
