### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Stellarium/stellarium#244]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
* [HttpListener::close](https://github.com/Stellarium/stellarium/blob/af21ce2b47c622ad503224cd31db2bb8e7c6b77e/plugins/RemoteControl/src/qtwebapp/httpserver/httplistener.cpp#L51 "HttpListener::close function")
* [NMEALookupHelper](https://github.com/Stellarium/stellarium/blob/9908ac3389af9b768ee53d7ec60c0407fd6defd5/src/core/StelLocationMgr.cpp#L294 "Destructor for NMEALookupHelper")
* [SyncServer](https://github.com/Stellarium/stellarium/blob/35f499813e430e91f571a4347b26fd6bfbbd6784/plugins/RemoteSync/src/SyncServer.cpp#L48 "Destructor for SyncServer")

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by gzotti** [comment]
QtCreator provides many hints, including clang-tidy. We are already listening to its suggestions as we develop further, thank you.
