### ISSUE TITLE
missing stars in Windows' version vs WEB-version

### ISSUE THREAD

**Issue by andypl1** [Stellarium/stellarium#2441]
Hi, I noticed missing stars in Virgo when I run a Windows' version of Stellarium 0.22.1. In the same area in web-version, these stars are visible. I loaded all available catalogs into Stellarium. Atmosphere visualization is off. Much fainter stars are visible but not the ones indicated on my picture. Does web-version use a different catalog of stars? Can it be loaded into Windows' version?

![Stellarium difference prog vs web](https://user-images.githubusercontent.com/49583268/167678465-80aec20d-3329-43b2-a494-4731765e490a.JPG)

**Comment by gzotti** [comment]
The star catalogs are different, and no, the web stars cannot be loaded into the desktop edition as these are entirely different programs. Switch on the DSS view to display more background stars.

**Comment by andypl1** [comment]
Thanks for the info. It's a pity that such stars are missing in catalogs. However it is good that they are at least visible in DSS-mode.

BTW. The tip for DSS-button shows 'TOAST' instead of a button to press (such as 'D' for DSO). What does it mean in this case?

**Comment by gzotti** [comment]
Tessellated Octahedral Adaptive Subdivision Transform. More on this is available at the URL given in the User Guide, section 10.4. There is no hotkey preconfigured, but you can add your own. See User Guide, section 4.8.

**Comment by andypl1** [comment]
Thanks a lot for all the info
