### ISSUE TITLE
Stellarium doesn't start/load

### ISSUE THREAD

**Issue by BlackApron** [Stellarium/stellarium#2446]
### Discussed in https://github.com/Stellarium/stellarium/discussions/2445

<div type='discussions-op-text'>

<sup>Originally posted by **BlackApron** May 16, 2022</sup>
Hi... I had to reinstall my computer. It is the same computer that previously ran Stellarium without issues. But after reinstalling win10 and installing Stellarium 0.22.1, it just doesn't start. ANGLE, MESA, all versions show the same messages in the log:

QOpenGLFramebufferObject: An undefined error has occurred:  1285
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.

I don't know what else to try.  Stellarium shows the splash screen but then it just shows a black window that closes a few seconds after.

Any suggestions?

Thanks!</div>

**Comment by alex-w** [comment]
Please install drivers for graphics card

**Comment by BlackApron** [comment]
Drivers are all up to date. Other programs such  as TheSkyX and StarryNight 8 work ok.

![Display Driver](https://user-images.githubusercontent.com/22322561/168672692-69f4e702-eb84-4b66-ac5f-eb9c6e5942a7.jpg)

**Comment by alex-w** [comment]
Please attach log.txt file from Stellarium

**Comment by BlackApron** [comment]
[log.txt](https://github.com/Stellarium/stellarium/files/8758019/log.txt)

**Comment by alex-w** [comment]
Could you try re-install Stellarium (uninstall current version and install it again) - looks like you have mixed versions of libraries?

**Comment by BlackApron** [comment]
Hi,
   I've uninstalled it and reinstalled it several times trying with both the 32 and 64 versions without luck.

When you say "mixed versions" of libraries, Do you mean OpenGL versions?

Any way you know to manually delete OpenGL?

Thanks!
________________________________

**Comment by alex-w** [comment]
Please share log from Stellarium when it works in ANGLE mode

**Comment by BlackApron** [comment]
Hi Alexander,
    It doesn’t work in ANGLE mode either… here is the log…

**Comment by alex-w** [comment]
Thank you very much for the log - ANGLE mode is broken

**Comment by BlackApron** [comment]
Just in case this might be useful, here is the log for Stellarium with OpenGL diagnostics…



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by gzotti** [comment]
To be more exact, the way ANGLE is called is broken. 
Can you try to set an environment variable: QT_OPENGL=angle
before launching Stellarium? This seems to help.

**Comment by BlackApron** [comment]
That actually worked!!!

Thanks so much!

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by gzotti** [comment]
I consider this solved.

**Comment by BlackApron** [comment]
Thank you… it works perfectly well now…



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
