### ISSUE TITLE
The menus are unreadable and it doesn't keep my location.

### ISSUE THREAD

**Issue by NeonBlueWS** [Stellarium/stellarium#2448]
You've made Stellarium unusable. The menus are gray on gray and I can barely read them. Also, it won't keep my location. It keeps reverting to Southern Europe. I'm using the current version for Windows x64. 

It used to be a great program but now it sucks.

**Comment by gzotti** [comment]
Interesting. The colors and principal mode of operation have not changed since I think 2008. For your other issues we indeed have setting menus, F1 for help, and even a User Guide.

**Comment by alex-w** [comment]
Please attach the log.txt file

**Comment by alex-w** [comment]
Maybe related to #2471

**Comment by ner00** [comment]
This is only my personal experience, but since I've not updated in quite a while until today, my experience is that the menus are exactly the same as before and so is the location, it is still saved and loaded from `%APPDATA%\Stellarium\config.ini`

Specifically:
```
[init_location]
landscape_name                         = guereins
last_location                          = 35.6789, -5.4321
location                               = My Location, My Country
```

**Comment by gzotti** [comment]
If @NeonBlueWS does not provide more information by filling in the questions from the issue template and sending the logfile as requested or just reading enough of the User Guide to help himself into proper use, this will be closed after June 23.

**Comment by claudiohase** [comment]
Dear Sir,
Texts with shadows are unreadables !!!  Remove its.  Menus will be good to read !!!

**Comment by claudiohase** [comment]
I use a SAMSUNG 4k TV as display........
![20220617_213854](https://user-images.githubusercontent.com/90158638/174415669-3f732e06-f3a0-4ff1-878f-539d244d6ccb.jpg)
The shadows (or gray bottom, is possible too)  are BAD !!!!!!

**Comment by gzotti** [comment]
There are no shadows unless your TV creates them. No PC monitor shows them, but my cheap TV also oversharpens. Play with your TV settings.

**Comment by gzotti** [comment]
timeout
