### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [Stellarium/stellarium#245]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream") ⇒ [SqueezeHip](https://github.com/Stellarium/stellarium/blob/585dcacdf71372de845b81420e1b9d1b80369263/util/MakeCombinedCatalogue.C#L946)
- [fread](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fread.html "Binary input") ⇒ [main](https://github.com/Stellarium/stellarium/blob/585dcacdf71372de845b81420e1b9d1b80369263/util/ParseNomad.C#L151)

**Comment by alex-w** [comment]
The code from utils directory is used the one-two times per year and it is for advanced users.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by gzotti** [comment]
You are cordially invited to help improving via pull requests. But indeed, some auxiliary programs are usually not for public use and "as good as necessary".

**Comment by gzotti** [comment]
Are you trying to sell a course?
