### ISSUE TITLE
Your Website SSL Maintenence

### ISSUE THREAD

**Issue by AdamRj-765** [Stellarium/stellarium#2453]
Hi, 
While on your site looking for a download of your application, I noticed that your site's SSL certificate is either not installed or expired. I know that these certificates can get expensive, but I can help you to keep it up to date for a very competitive price. 
Please contact me at omnisolutions001.adam@mailgw.com if you would like to schedule a free consultation on how my company can provide this Web Service. Our site is also listed here: https://omni-solutions-tech.com

**Comment by xalioth** [comment]
No ads here

**Comment by AdamRj-765** [comment]
It's not an ad. Its a professional curtesy, one to inform you of your very lax and dangerous web administration skills, and two to offer services that are not offered publicly -therefore its not an Ad. Its an freelancer estimate.
