### ISSUE TITLE
Some phenomena are not found in AstroCalc

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#2459]
There appears to be a problem with the Phenomena tools in AstroCalc. For example, we know that the opposition of Jupiter in 2022 occurs on September 26, but searching for this using "Jupiter" and "Planets and Sun" respectively, nothing is returned. I don't know if this is a MacOS-only issue, as I cannot currently test on a Windows computer. Please see the screenshot below. Using these, and pressing "Calculate phenomena", nothing happens.

<img width="1114" alt="Skärmavbild 2022-05-23 kl  22 47 58" src="https://user-images.githubusercontent.com/37028368/169903799-77ec5282-e645-4737-bd40-4d61a727e73a.png">

Latest public beta (but this has not worked for a few months I believe), MacBook Pro M1, Monterey 12.4.

**Comment by alex-w** [comment]
Cannot confirm issue on Windows, I'll check it on macOS tonight

**Comment by alex-w** [comment]
I cannot confirm the issue on macOS with current master

**Comment by Atque** [comment]
This is the config.ini that I'm using, but I get the same problem when using a fresh install and config. Uploading the log.txt as well.
[log.txt](https://github.com/Stellarium/stellarium/files/8764731/log.txt)

[config.ini.zip](https://github.com/Stellarium/stellarium/files/8764730/config.ini.zip)

**Comment by alex-w** [comment]
With your config:
![stellarium-003](https://user-images.githubusercontent.com/88731/170094000-326732f9-83ce-4de8-94f9-1a590e4727d6.jpg)

**Comment by alex-w** [comment]
> Weird. I still see no results when clicking the button.

I can reproduce the issue now (master & v0.22.1; arm64 + qt 5.15.3)!
 
> Are you running the native build?

Seems like the issue related to changes in Qt 5.15

**Comment by alex-w** [comment]
I can confirm the issue with Qt 5.15.2 on Linux, so, this is regress in Qt 5.15 :(

**Comment by alex-w** [comment]
No, this is our problem

**Comment by gzotti** [comment]
Just saw it. Qt5.14 forced a change in the date handling (AstroCalc.cpp : L4758). Looked trivial, but maybe this broke something.

**Comment by alex-w** [comment]
> Just saw it. Qt5.14 forced a change in the date handling (AstroCalc.cpp : L4758). Looked trivial, but maybe this broke something.

@gzotti, you missed to use QDateTime() for Qt 5.14+!

In any way I changed the handling data and fixed similar issue for AstroCalc/RTS tool (at least I see same result for Qt 5.12 & Qt 5.15 on my macOS)

**Comment by gzotti** [comment]
No, the QDateTime() is already the argument. I miswrote the end date coming from the wrong UI element, so it searched only for a single day. *-(

**Comment by alex-w** [comment]
> No, the QDateTime() is already the argument. I miswrote the end date coming from the wrong UI element, so it searched only for a single day. *-(

Why? QDateEdit->date() should give QDate() only
