### ISSUE TITLE
testRadToHMSStr fails on x86

### ISSUE THREAD

**Issue by DarthGandalf** [Stellarium/stellarium#2460]
### Expected Behaviour

Unit tests should pass

### Actual Behaviour

Unit test fails:

```
FAIL!  : TestConversions::testRadToHMSStr() 'expectedHMS==hms' returned FALSE. (2.74889 radians = 10h30m00.01s (expected 10h30m00.00s))
   Loc: [/var/tmp/portage/sci-astronomy/stellarium-0.22.1/work/stellarium-0.22.1/src/tests/testConversions.cpp(942)]
```

### Steps to reproduce
1. use 32 bit x86 system
2. cmake; make; ctest

### System
* Stellarium version: 0.22.1
* Operating system: Gentoo Linux
* Graphics Card: irrelevant
* Screen type (if applicable): irrelevant

### Logfile 
[build.log](https://github.com/Stellarium/stellarium/files/8758450/build.log)

https://bugs.gentoo.org/847064

**Comment by gzotti** [comment]
Uh, where do I find a 32bit x86 today?

**Comment by DarthGandalf** [comment]
32 bit software can be run on 64 bit (x86_64) CPU as well

You can e.g. download "32 bit" from https://www.debian.org/distrib/ or "x86" from https://www.gentoo.org/downloads/ and run it on a VM with a usual x86_64 virtual CPU (or even physical machine)

**Comment by gzotti** [comment]
Sure I can setup an x86 VM and start compiling. Or maybe you can fix this issue please and send a PR? May be faster.

**Comment by DarthGandalf** [comment]
@alex-w that fixed the test, thanks!

@gzotti

> Or maybe you can fix this issue please and send a PR?

My best idea was to randomly replace `double` with `long double`, which is probably not a good solution, even if it would work

**Comment by DarthGandalf** [comment]
Looks like this broke amd64:

```
FAIL!  : TestConversions::testRadToHMSStr() 'expectedHMS==hms' returned FALSE. (0.08727 radians = 0h20m-0.0s (expected 0h20m00.0s))                                                                                                                                               
   Loc: [/mnt/portagetmp/portage/sci-astronomy/stellarium-0.22.1-r1/work/stellarium-0.22.1/src/tests/testConversions.cpp(938)]
```

**Comment by alex-w** [comment]
This is weird, but I see where we can get negative zero.
