### ISSUE TITLE
Broken interface with `QT_QPA_PLATFORMTHEME=qt5ct`

### ISSUE THREAD

**Issue by Firgen** [Stellarium/stellarium#2470]
### Expected Behaviour

Interface is usable

### Actual Behaviour

Some windows (sky and viewing options, configuration, astronomical calculations, oculars) are ridiculously wide and thus unusable.
![screenshot_20220518_200246](https://user-images.githubusercontent.com/29487700/170829270-3ad0cb5c-10ab-489e-a266-7ddbd4abb8c7.png)
![screenshot_20220518_200253](https://user-images.githubusercontent.com/29487700/170829271-a0fae97d-245e-484a-9281-4dca113ffb73.png)
![screenshot_20220518_200301](https://user-images.githubusercontent.com/29487700/170829273-c2f50b08-421f-4443-b9c9-da47b43a2f98.png)

### Steps to reproduce

Apparently something in my user configuration causes this so I'm not even sure if I can create this issue. When I try a different user everything is fine.

I have `QT_QPA_PLATFORMTHEME=qt5ct`. When I unset it, the behavior changes but it's still broken (The windows are slightly less wide and sky and viewing options don't even open).

### System
* Stellarium version: 0.22.1
* Operating system: Fedora 35, Fedora 36, Void Linux
* Graphics Card: <AMD, RX580, mesa 22.0.3-1>
* Screen type (if applicable): 1920x1080, no scaling

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/8791294/log.txt)

**Comment by alex-w** [comment]
Try reset the settings: `rm ~/.stellarium/config.ini`

**Comment by Firgen** [comment]
> Try reset the settings: rm ~/.stellarium/config.ini

That doesn't work.

> Wayland environment?

Both X and wayland.

**Comment by alex-w** [comment]
Please try uninstall Stellarium from repository and check our AppImage.

**Comment by Firgen** [comment]
Well, I actually wanted to open another issue about that. The AppImage segfaults and doesn't run.

**Comment by alex-w** [comment]
Well, probably I cannot help you, because attached log has limited info and looks like you have a big problem for HDD (I not see in the log version of Stellarium, initialization process, version of OpenGL, etc.). See [typical log](https://github.com/Stellarium/stellarium/files/8791347/log-6.txt) from Stellarium on linux.

**Comment by Firgen** [comment]
I narrowed it down to `QT_QPA_PLATFORMTHEME=qt5ct`. The reason it only changed the behavior is because something was already broken in .stellarium somehow. I deleted `$HOME/.stellarium` and set `QT_QPA_PLATFORMTHEME=` and it works fine.

**Comment by alex-w** [comment]
Could you please share latest log?

**Comment by Firgen** [comment]
[log.txt](https://github.com/Stellarium/stellarium/files/8800532/log.txt)

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by gzotti** [comment]
> Well, probably I cannot help you, because attached log has limited info and looks like you have a big problem for HDD (I not see in the log version of Stellarium, initialization process, version of OpenGL, etc.). See [typical log](https://github.com/Stellarium/stellarium/files/8791347/log-6.txt) from Stellarium on linux.

I have seen such incomplete log on a CentOS system. Some QT related envvar influences the amount of debug messages, but I cannot find the docs for this now.

@Firgen if Stellarium runs with some other setting of QT_QPA_PLATFORMTHEME, this is the solution. Just write a wrapper script which sets this variable to a working flavour and then calls stellarium.

**Comment by Firgen** [comment]
> @Firgen if Stellarium runs with some other setting of QT_QPA_PLATFORMTHEME, this is the solution. Just write a wrapper script which sets this variable to a working flavour and then calls stellarium.

Yes, that works as a workaround but I don't think it's a solution.

**Comment by gzotti** [comment]
You are cordially invited to find a solution that suits you better, then.

**Comment by Firgen** [comment]
> Please check the fresh version (development snapshot) of Stellarium: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

This AppImage actually runs and it doesn't have this issue. It also gives me a proper log.

**Comment by alex-w** [comment]
AppImage used Qt 5.12

**Comment by 10110111** [comment]
> This AppImage actually runs and it doesn't have this issue

AppImage uses its own copy of Qt, which doesn't include `libqt5ct.so`. This effectively disables qt5ct.

On my system trying Stellarium with qt5ct only makes fonts in some internal dialogs' widgets larger than without qt5ct. All this despite there being no such font size set in `qt5ct` GUI.

The problems might be due to a bug in qt5ct, not necessarily in Stellarium. You might want to try commenting out some settings being applied in qt5ct source, `qt5ctplatformtheme.cpp` file to find out what exactly breaks Stellarium for you.

**Comment by Firgen** [comment]
Sorry for staying silent, I was doing other stuff and I kinda forgot about this.

I am using the workaround to disable qt5ct for Stellarium and it works and trying to debug qt5ct is not really worth my time. I think we can close this issue.
