### ISSUE TITLE
Would like an easy way to go to the zenith, south down

### ISSUE THREAD

**Issue by mcovington** [Stellarium/stellarium#2474]
I would like an easy way to put the zenith at the center of the screen, south down.  Going to horizontal coordinates az. 180, alt. 90, will do it.  I would like to have an easier way, such as typing "zenith" or "up" into the Find box.

With orthographic projection, this makes Stellarium into a convenient whole-sky planisphere.

**Comment by gzotti** [comment]
A 1-line script will do:

StelMovementMgr.lookZenith(true);

Assign this to a shortkey. 

Errm, this is already available. Shift-Z.

**Comment by mcovington** [comment]
Further comment.  Pressing Shift-Z *usually* aims at the zenith with south down, but occasionally some other direction is down.  Why is that?  When it happens, I move the map a little at random and press Shift-Z again, and I get what I want, the view aimed at the zenith with south at the bottom of the screen.

**Comment by gzotti** [comment]
You can press Shift-S, Shift-Z to first ensure looking south, then up.
