### ISSUE TITLE
Observing list seems to think everything is a nebula

### ISSUE THREAD

**Issue by ckuethe** [Stellarium/stellarium#2475]
### Expected Behaviour
Observing list correctly displays object type, eg. nebula, star, galaxy, globular cluster, ...

### Actual Behaviour
Observing list shows all objects as nebulas
![Screenshot_2022-05-31_19-30-54](https://user-images.githubusercontent.com/1131751/171316649-bd394afc-d83e-4924-b97f-3ea0b7b805f3.png)

### Steps to reproduce
Created a list, added some objects that aren't nebulae

### System
* Stellarium version: Stellarium-0.22.1-x86_64.AppImage
* Operating system: Xubuntu 22.04
* Graphics Card: Intel TigerLake-LP GT2 [Iris Xe Graphics], Mesa Intel(R) Xe Graphics (TGL GT2) (0x9a49), 4.6 (Core Profile) Mesa 22.0.1
* Screen type (if applicable): 1920x1080, 96dpi, 24bpp

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by Jocelyn1109** [comment]
Hi @ckuethe and thank you for this message.
Actually it is not directly a problem with OObservingList because the object type returned by Stellarium for Abell 2151, for example, is Nebula.

@alex-w @gzotti is it normal ?

![nebula](https://user-images.githubusercontent.com/43777557/171397647-21ca2da5-0e52-44bd-816a-6318b58364da.png)

Jocelyn

**Comment by alex-w** [comment]
> Hi @ckuethe and thank you for this message. Actually it is not directly a problem with OObservingList because the object type returned by Stellarium for Abell 2151, for example, is Nebula.
> 
> @alex-w @gzotti is it normal ?

Yes, it is normal currently. I’ll add special method for getting the correct object type tomorrow (this feature in TODO list)

**Comment by alex-w** [comment]
The new method `getObjectType()` return object's type. It should be English lowercase name of the type of the object (as a type string in infobox).

Typical usage: `QString objType = selectedObject[0]->getObjectType();`

The method `getType();` return the name of object' class by the fact.

**Comment by Jocelyn1109** [comment]
Hi @alex-w, as you can see on the picture everything is working properly with your new method getObjectType().
I did the test with Sun, Vesta (asteroid) and all other items in this ticket that appeared as Nebula (see first post).

Jocelyn

![object-type](https://user-images.githubusercontent.com/43777557/171614744-120bec22-051f-44df-b26a-7fe2f6efd5ba.png)

**Comment by alex-w** [comment]
Hello @ckuethe!

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by ckuethe** [comment]
So a small nit - the observing list needs to be recreated or objects need to be re-added to an existing list pick up the new object type, but aside from that it works.

![Screenshot_2022-09-22_12-08-51](https://user-images.githubusercontent.com/1131751/191831342-69893dcc-5fca-4a44-a75d-a889bd1fa346.png)

**Comment by Jocelyn1109** [comment]
@ckuethe you can create a new list and import the old into it

**Comment by Jocelyn1109** [comment]
@ckuethe I will give you more details tomorow morning when I will be in front of my computer  😀

**Comment by ckuethe** [comment]
No worries, I got my observing list the way I wanted it. I'm just point out that my old list didn't just magically upgrade the object type. Once I recreated it, the object types were all correct.

**Comment by Jocelyn1109** [comment]
Hi @ckuethe ,
Here is the information regarding the import of old lists in the "observing lists":

- when switching to the new version of Stellarium with "observing lists" the legacy bookmarks.json will be automatically imported into the observation lists with the name "bookmarks list",
- if you want to import another "observing list" the best way is to create a new list and to import  it into it.
-  if you want to import another "bookmarks.json" do the same.

These features have been tested by me (the developer) and should work, but they still need further testing.
Do not hesitate to come back to me for any questions or problems.

Jocelyn
