### ISSUE TITLE
Stellarium 0.18.1 freezeup

### ISSUE THREAD

**Issue by Teamonger** [Stellarium/stellarium#248]
Under Configuration, Tools, I'm trying to change my Screenshot Directory.  When I click on the folder button to browse, everything freezes and I have to Ctl-Alt-Delete to Task Manager to end the task.  Stellarium 0.16 was fine.  I'm on Windows 7 machine.

Any ideas?

**Comment by alex-w** [comment]
Could you check it in windowed mode also?

**Comment by Teamonger** [comment]
Seems to work in windowed mode.  Thanks Alex, that was quick!

**Comment by alex-w** [comment]
Please attach log from Stellarium

**Comment by Teamonger** [comment]
Okay, how do I get that?

**Comment by alex-w** [comment]
"Start -> Programs -> Stellarium -> Latest run log" or F1 within Stellarium

**Comment by Teamonger** [comment]
Here it is
[log.txt](https://github.com/Stellarium/stellarium/files/2260578/log.txt)

**Comment by alex-w** [comment]
Thanks!

**Comment by gzotti** [comment]
Sometimes system dialogs hide behind the full-screen window. The color panel (grid lines and ArchaeoLines GUI) does not show on older Geforce (seen on M580GTX) in OpenGL mode, but works in ANGLE mode. And it works on a Geforce 960M.

Please try if ANGLE mode helps.

**Comment by gzotti** [comment]
@Teamonger,  I cannot reproduce the issue on my own Intel HD4600 desktop system. However, I have a later driver:  OpenGL 4.3.0 - Build 20.19.15.4835

Please can you 
1) test whether running Angle mode solves the problem with your current graphics driver. Just start with the "Stellarium (ANGLE mode)" link in your start menu, go into full screen and open the file dialog. 
2) update your graphics driver (from  Intel.com) and see if this solves the issue in OpenGL Fullscreen mode.

**Comment by Teamonger** [comment]
Yes, I did try ANGLE mode.  That seems to clear up the problems, let's me use Alt-tab to exit Full Screen mode to other apps.  I'm a bit leery about updating the driver... had a bad experience doing that some time ago.  So I'll stick with ANGLE for now.  Thanks for your help!
