### ISSUE TITLE
Problem with saving configuration

### ISSUE THREAD

**Issue by FranciscoBorg28** [Stellarium/stellarium#2481]
hello, I have windows 11, and in the stellarium last version, I modify landscape, and other options. Then I give it to save configuration, but later when I start it again, the configuration is not saved.
Where is the problem?
best regards

**Comment by gzotti** [comment]
How do you detect that configuration has not been saved?

- Default Landscape has to be saved in its panel
- Location can be configured separately
- Auto-location from IP at startup will always set a different default location until you switch it off
- And probably a few more options.

**Comment by gzotti** [comment]
Please see section 6.2.2 of the User Guide and what feels like 5 years of FAQ editing here in the wiki.
