### ISSUE TITLE
Clicking object in Observing List makes my location all zeroes

### ISSUE THREAD

**Issue by Menno5** [Stellarium/stellarium#2486]
I don't know if this already has been reported?
When I double click an object in the Observing Lists, it goes to that object but my location is changed to **N 0° 0' 0.00" E 0° 0' 0.00"** ?

I did test and it looks like it has to do with my location.
If I use a standard location from the dropdown list (Amsterdam, The Netherlands), the observing list works as intended. I stay in my location.
If I use a location that I did add myself with coordinates, when clicked the Observing List location is loaded but my location is set to all zeroes. It seems it doesn't like the System Default time zone?
Below a screenshot of the settings I use (minus the specific coordinates)

### System
* Stellarium version: Stellarium-0.22.1-win64
* Operating system: Windows 10 Pro 21H2 64bit
* Graphics Card: MSI RTX 2080ti Gaming X Trio

### Logfile 
[log.zip](https://github.com/Stellarium/stellarium/files/8881283/log.zip)

![time](https://user-images.githubusercontent.com/56191878/173134004-57c34eb1-8c91-49bf-a77c-560f6bb18c31.jpg)

**Comment by Menno5** [comment]
More info: I did find that ticking the _Use custom time zone_ and then choosing _System default_ in the dropdown menu, solves this problem. But when not ticked, although Stellarium shows the local time on the bottom, it is not used in the saved lists.

**Comment by Jocelyn1109** [comment]
@Menno5 ok thanks, I will see :)
