### ISSUE TITLE
Unable to download Stellarium because of bandwith, asks for username and password

### ISSUE THREAD

**Issue by Mahinavai** [Stellarium/stellarium#2488]

**Comment by alex-w** [comment]
Please try https://47tuc.ru/stellarium/Stellarium-0.22.1-x86_64.zip

**Comment by Mahinavai** [comment]
> Please try https://47tuc.ru/stellarium/Stellarium-0.22.1-x86_64.zip
> 
> MD5: 8b4c25bfc98d841a07d5dcd73a94b7ff

Dearest Alex, that worked!!! Today is my birthday and you just made my day! All of us hear thank you once and again!

**Comment by gzotti** [comment]
Don't forget the User Guide PDF from https://stellarium.org. A lot has changed since 2012, esp. features and accuracy for cultural astronomy! 
See also  https://doi.org/10.1558/jsa.17822

**Comment by alex-w** [comment]
Stellarium 0.22.1 User Guide: https://47tuc.ru/stellarium/stellarium_user_guide-0.22.1-1.pdf

**Comment by Mahinavai** [comment]
I spoke too soon…  I downloaded Stellarium from the supplied link, and all seems normal, no errors downloading, etc...The file weighs 602.3 mb and my computer is a mid-2015 Macbook Pro, with Intel Core i7 (64-bit), running Monterey 12.0.1. It has a AMD Radeon R9 M370X graphics card which supports  OpenGL 4.3. These are all more than the app requires, so I don´t know why  a pop-up dialog box springs up when I try to open the app, simply informing me that it can´t open it. No other explanation, error code, nor anything else. Maybe it downloaded with an error? Any idea on what might be causing this?

**Comment by gzotti** [comment]
The same-named package on https://github.com/Stellarium/stellarium/releases has 344MB. Something must have gone wrong with the download.

**Comment by Mahinavai** [comment]
> I spoke too soon… I downloaded Stellarium from the supplied link, and all seems normal, no errors downloading, etc...The file weighs 602.3 mb and my computer is a mid-2015 Macbook Pro, with Intel Core i7 (64-bit), running Monterey 12.0.1. It has a AMD Radeon R9 M370X graphics card which supports OpenGL 4.3. These are all more than the app requires, so I don´t know why a pop-up dialog box springs up when I try to open the app, simply informing me that it can´t open it. No other explanation, error code, nor anything else. Maybe it downloaded with an error? Any idea on what might be causing this?

UPDATE / FIX: I deleted all copies of Stellarium (the new one) with an uninstaller. Then extracted the zip file directly to the Applications folder with Administrator Privileges using Pacifist. No other decompressor app did the trick, but this worked!
