### ISSUE TITLE
Small black window instead of Stellarium UI

### ISSUE THREAD

**Issue by UgnilJoZ** [Stellarium/stellarium#2493]
### Expected Behaviour
After the loading screen, the main window of Stellarium should open.

### Actual Behaviour
After the loading screen, a small black window appears:
![grafik](https://user-images.githubusercontent.com/7910828/174806792-f2dc2939-0e98-4574-abc6-2d046e835da9.png)
It closes as soon a key is pressed.

### Steps to reproduce
Open the program.

### System
* Stellarium version:
  * Flatpak "org.stellarium.Stellarium" 0.21.3 (stable)
  * [Stellarium-0.22.1-95a6881-x86_64.AppImage](https://github.com/Stellarium/stellarium-data/releases/download/weekly-snapshot/Stellarium-0.22.1-95a6881-x86_64.AppImage) weekly snapshot
* Operating system: Arch Linux with kernel 5.18.5-arch1-1
* Graphics Card: NVidia GeForce GTX 1050 Ti (rev a1), driver 515.48.07-11
* Screen type:
  * 4096x2160 @ 59.94 Hz and 200% scaling
  * 1280x1024 @ 60.02 Hz
* Display Session: Gnome 42.2 Wayland session

<details>
<summary><h3>Logfile using Flatpak</h3></summary>
<pre><code>2022-06-21T15:09:15
Operating System: KDE Flatpak runtime
Compiled using GCC 11.2.0
Qt runtime version: 5.15.5
Qt compilation version: 5.15.3
Addressing mode: 64-bit
MemTotal:       32792420 kB
MemFree:        25089756 kB
MemAvailable:   29282072 kB
SwapTotal:      33554428 kB
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 3755.954
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2370.871
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 3700.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 3700.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 3700.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
2d:00.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1) (prog-if 00 [VGA controller])
Kernel driver in use: nvidia
stellarium 
 -----------------------------------------------------
[ This is Stellarium 0.21.3 - https://stellarium.org/ ]
[ Copyright (C) 2000-2021 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "/home/joz/.stellarium/log.txt"
File search paths:
  0 .  "/home/joz/.stellarium"
  1 .  "/app/share/stellarium"
Config file is:  "/home/joz/.stellarium/config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
StelGLWidget constructor
StelGraphicsScene constructor
QOpenGLWidget: Failed to make context current
QPainter::begin: Paint device returned engine == 0, type: 1
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::worldTransform: Painter not active
QPainter::save: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::setWorldTransform: Painter not active
QPainter::end: Painter not active, aborted</code></pre>
</details>

<details>
<summary><h3>Terminal output using Flatpak</h3></summary>
<pre><code>$ flatpak run org.stellarium.Stellarium
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
Qt: Session management error: None of the authentication protocols specified are supported
 -----------------------------------------------------
[ This is Stellarium 0.21.3 - https://stellarium.org/ ]
[ Copyright (C) 2000-2021 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "/home/joz/.stellarium/log.txt"
File search paths:
  0 .  "/home/joz/.stellarium"
  1 .  "/app/share/stellarium"
Config file is:  "/home/joz/.stellarium/config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
StelGLWidget constructor
StelGraphicsScene constructor
QOpenGLWidget: Failed to make context current
QPainter::begin: Paint device returned engine == 0, type: 1
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::worldTransform: Painter not active
QPainter::save: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::setWorldTransform: Painter not active
QPainter::end: Painter not active, aborted</code>
</pre>
</details>

<details>
<summary><h3>Logfile using AppImage</h3></summary>
<pre><code>2022-06-22T17:24:26
Operating System: Arch Linux
Compiled using GCC 9.4.0
Qt runtime version: 5.12.8
Qt compilation version: 5.12.8
Addressing mode: 64-bit
MemTotal:       32792420 kB
MemFree:        16408876 kB
MemAvailable:   27443512 kB
SwapTotal:      33554428 kB
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 3516.174
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 3700.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 3700.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2200.000
model name	: AMD Ryzen 5 5600X 6-Core Processor
cpu MHz		: 2800.000
2d:00.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1) (prog-if 00 [VGA controller])
Kernel driver in use: nvidia
Kernel modules: nouveau, nvidia_drm, nvidia
/tmp/.mount_StellaV1rEsz/usr/bin/stellarium 
 -----------------------------------------------------------------------
[ This is Stellarium 0.22.1-95a6881 [release] - https://stellarium.org/ ]
[ Copyright (C) 2000-2022 Stellarium Developers                         ]
 -----------------------------------------------------------------------
Writing log file to: "/home/joz/.stellarium/log.txt"
File search paths:
  0 .  "/home/joz/.stellarium"
  1 .  "/tmp/.mount_StellaV1rEsz/usr/bin/../share/stellarium"
Config file is:  "/home/joz/.stellarium/config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
StelGLWidget constructor
StelGraphicsScene constructor
QOpenGLWidget: Failed to make context current
QPainter::begin: Paint device returned engine == 0, type: 1
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::worldTransform: Painter not active
QPainter::save: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::setWorldTransform: Painter not active
QPainter::end: Painter not active, aborted</code></pre>
</details>

<details>
<summary><h3>Terminal output using AppImage</h3></summary>
<h4>With empty QT_QPA_PLATFORM</h4>
<pre><code>$ './Stellarium-0.22.1-95a6881-x86_64.AppImage'
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
WARNING StelFileMgr::StelFileMgr: could not find install location: "/usr/share/stellarium"  (we checked for  "/usr/share/stellarium/data/ssystem_major.ini" ).
Maybe this is AppImage or something similar? Let's check relative path...
 -----------------------------------------------------------------------
[ This is Stellarium 0.22.1-95a6881 [release] - https://stellarium.org/ ]
[ Copyright (C) 2000-2022 Stellarium Developers                         ]
 -----------------------------------------------------------------------
Writing log file to: "/home/joz/.stellarium/log.txt"
File search paths:
  0 .  "/home/joz/.stellarium"
  1 .  "/tmp/.mount_StellaV1rEsz/usr/bin/../share/stellarium"
Config file is:  "/home/joz/.stellarium/config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
StelGLWidget constructor
StelGraphicsScene constructor
QOpenGLWidget: Failed to make context current
QPainter::begin: Paint device returned engine == 0, type: 1
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::worldTransform: Painter not active
QPainter::save: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::setWorldTransform: Painter not active
QPainter::end: Painter not active, aborted
Speicherzugriffsfehler (Speicherabzug geschrieben)</code></pre>
Last line "memory access error (memory dump written)" appears as soon as I press a button. The program ends subsequently.

<h4>With QT_QPA_PLATFORM=wayland</h4>
<pre><code>$ QT_QPA_PLATFORM=wayland './Stellarium-0.22.1-95a6881-x86_64.AppImage'
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Abgebrochen (Speicherabzug geschrieben)</code></pre>
No window is displayed and program ends immediately.
</details>

**Comment by alex-w** [comment]
Where is the log from an AppImage? 

P.S. I see the wayland plugin is missed in your Qt

**Comment by UgnilJoZ** [comment]
> P.S. I see the wayland plugin is missed in your Qt

I have `qt5-wayland-5.15.5+kde+r38-1` and `qt6-wayland-6.3.1-1` installed (I assume these packages contain the platform plugin) and other Qt applications do work, also with `QT_QPA_PLATFORM=wayland`.

But Stellarium does not open if I try to enforce wayland:
```
$ flatpak override --user --env=QT_QPA_PLATFORM=wayland org.stellarium.Stellarium
$ flatpak run org.stellarium.Stellarium
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

[Program ends without displaying something]
```

Although, `eglfs` platform gives me a *fullscreen* black window, and normal sounding terminal output. So there, the program loads normally and only the actual graphics are missing.

**Comment by alex-w** [comment]
Please check v0.22.1

**Comment by alex-w** [comment]
Please try test stellarium from AUR

**Comment by UgnilJoZ** [comment]
Hey, thank you for the effort. I think I am too dumb to find the AppImage, is [this](https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot) the right release?

**Comment by alex-w** [comment]
No, we're removed the AppImage packages

**Comment by UgnilJoZ** [comment]
It does indeed work (with the `QT_QPA_PLATFORM=wayland` env variable)!
Thank you!
