### ISSUE TITLE
strange/unexpected star movement

### ISSUE THREAD

**Issue by izengineer** [Stellarium/stellarium#2501]
Hello, I was traveling in time with Stellarium and noticed something strange at two different times.

During the 1582-1583 and 1847-1848 year transitions, I detected about 6-7 degrees of rotation(equatorial grid) in the sky. 

For example, the star Arcturus in 1847(Date :1847-7-7, Time : 00-00-00), Az./Alt. : 274/26 degrees and exactly one year later; in 1848(Date : 1848-7-7, Time : 00-00-00) Az./Alt. : 267/34 degrees. 

Likewise, on 1582(Date :1582-7-7, Time : 00-00-00) Az./Alt. : 283/17 degrees and exactly one year later; in 1583(Date :1583, Time : 00-00-00) Az./Alt. : 277/24 degrees.

I went back 2022 years from today and I have not seen a different rotational movement like this. I'm using the app on windows 10 and I downloaded the latest stellarium version just to be sure.

Is there a problem with the software or is there an orbital movement of the earth or sun specific to these two dates?

good work,
Ilhan

**Comment by gzotti** [comment]
1582: Gregorian calendar reform.
1848: First use of time zones.

More info: Stellarium User Guide.
