### ISSUE TITLE
Earth's shadow

### ISSUE THREAD

**Issue by johnbellora** [Stellarium/stellarium#2503]
Hello Alex & George,

I would like to request to please add earth's shadow in proper arc degrees diameter. This is wonderfully useful and educational to watch each full moon and see how far the shadow misses the earth and to watch the movement pattern as the earth shadow zips by the moon every month. The planetarium software Aciqra has this feature, and it is unique and great. It only sees proper that the great Stellarium would have this great feature. It actually looks like a black planet in it's proper diameter

Best regards

John Bellora

**Comment by alex-w** [comment]
Hello @johnbellora! Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by johnbellora** [comment]
Hello George
are you able to view the shadow or a ring  which represents the tru diamere of the shadow of the if it was hitting the moon when it is not covering part of the mood? This is what I am after. 
John


-----Original Message-----

**Comment by alex-w** [comment]
> Hello George are you able to view the shadow or a ring  which represents the tru diamere of the shadow of the if it was hitting the moon when it is not covering part of the mood? This is what I am after.  John

Yes, see the screenshot (Earth umbra & Earth penumbra)
![view_dialog_markings_tab](https://user-images.githubusercontent.com/88731/179154421-3666c0b3-63b1-47b3-b738-0cfce18ec49d.png)

**Comment by johnbellora** [comment]
Hello George
I apologize i did not articulate properly the feature i would like. When the earth's shadow is not touching the moon, it will always be  visible  against the back ground indicated by a circle of the proper diameter  it would be if it ere crossing the moon. I have seen this feature in other programs and it is fascinating to see when we have a full moos, how far off the shadow is from eclipsing the moon that month.
The current option you listed below appears only to show the earth's shadow only when clipping or covering the moon. i would like to see at anytime where the earth's shadow is.
Best Regards
John Bellora


-----Original Message-----

**Comment by alex-w** [comment]
Earth umbra & Earth penumbra options in Markings tab will show circles of umbra & penumbra at Moon's distance.

**Comment by johnbellora** [comment]
that would be great. Maybe i am doing something wrond. I marked both. Can you send me a screen shot? i cannot see it. Please see below an example of another program.It is hard to see but there is a black circle.
John




-----Original Message-----

**Comment by alex-w** [comment]
> that would be great. Maybe i am doing something wrond. I marked both. Can you send me a screen shot? i cannot see it. Please see below an example of another program.It is hard to see but there is a black circle. John

Please check the web page of the issue to see the screenshots: https://github.com/Stellarium/stellarium/issues/2503

**Comment by johnbellora** [comment]
I apologize , i followed you link but i do not see a sky visualization, only a visualization of the checked boxes in the menu. Is the Earths shadoed labels?
John


-----Original Message-----

**Comment by alex-w** [comment]
Please see the visualization:
![stellarium-031](https://user-images.githubusercontent.com/88731/179173507-9be41951-e34d-44b9-8738-f70bbfc7a51f.jpeg)

**Comment by johnbellora** [comment]
Beautiful and perfect. How do I turn it on?
John


-----Original Message-----

**Comment by alex-w** [comment]
> Beautiful and perfect. How do I turn it on? John

Just mark 2 checkboxes in Markings tab (and save the settings via F2 -> "Save settings" if you want to see the umbra & penumbra always)

**Comment by alex-w** [comment]
Could you show screenshot of Markings tab and log.txt from Stellarium (please via web page)?

**Comment by gzotti** [comment]
One caveat: The rings are displayed only if the Moon itself is not scaled!

**Comment by johnbellora** [comment]
AHHHHHHHH.
Thank you


-----Original Message-----

**Comment by johnbellora** [comment]
hello,

as you can see both programs are from San Diego at the same UTC time. The Aciqra program shows the Earth's shadow( hard to see) as well as labeled. The Stellarium does not.
This is what i am hoping for. I am using 22.2

John




-----Original Message-----

**Comment by alex-w** [comment]
Github rejected attachments when message for issues sent by email and we do not see anything. Please use web interface to share the images/photos/files.
