### ISSUE TITLE
Earth shadow at sat altitude issues

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2510]
### Expected Behaviour
See #1246 and #2360

### Actual Behaviour

Umbra should start where satellites become reported as "not sunlit".

![image](https://user-images.githubusercontent.com/3529789/177860532-a51a5ce8-75b6-4059-b0a8-89fbe66551eb.png)

![image](https://user-images.githubusercontent.com/3529789/177865369-bca043d3-9e54-4657-80fc-893f228e0d07.png)

Also, "Show umbra at distance" (which makes one wonder whether distance to the observer is intended) should probably read "Show umbra at **altitude**".

Also, it is odd that the umbra sticks above the horizon when the Sun is visible (or e.g. rising/setting). The umbra should be visible above the horizon during the night only, and should touch the horizon at sunrise/sunset (notwithstanding refraction issues).

![image](https://user-images.githubusercontent.com/3529789/177865601-8f55f6fa-1a40-4edd-9a76-7161e4ac28d9.png)

![image](https://user-images.githubusercontent.com/3529789/177861172-eb0ef015-a4b8-485e-9391-3411a1955cec.png)

It could be (but I haven't checked it) that the umbra should always be near/touch the ASP at any moment.

For geo sats the feature seems to work:
![image](https://user-images.githubusercontent.com/3529789/177866103-63ed5bac-3391-4dfa-8223-e339c66f301d.png)

The CU locus seems to converge to the Earth at Moon umbra, which is as expected.

![image](https://user-images.githubusercontent.com/3529789/177864884-84439f45-ef5b-4ac1-97a8-3cebdb1f6e07.png)

### System
* Stellarium version: <Name of downloaded installable file?> 9275de93251f2e9e6032afdf889332b9c66a248c
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-120-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by axd1967** [comment]
Projection is stereographic, but that shouldn't matter? It looks like the drawing logic does take projection into account: e.g. fisheye gives this:

![image](https://user-images.githubusercontent.com/3529789/179370113-0fb811a2-ff49-46d2-a85f-5d29e164e60c.png)


The image shows the ISS about to enter the Earth shadow (red, marked "3") in a few seconds. That is where the Earth shadow should start. According to the current implementation, the ISS should enter the Earth shadow at "2", which clearly conflicts with the calculations of the satellite tool.

**Comment by alex-w** [comment]
Please remember about the trigonometry and projections (or sines/cosines in triangles)...

**Comment by Atque** [comment]
@alex-w Wouldn't the shadow markings fit anyway?

**Comment by alex-w** [comment]
> @alex-w Wouldn't the shadow markings fit anyway?

See the placement of satellite at points A and B on the drawing:
![IMG_2694_1](https://user-images.githubusercontent.com/88731/179458037-ccae4ad0-f1ea-4f3c-9b3d-776479a05c38.jpg)

We render the umbra's circle at altitude H and we do not compute projection the placement of satellite to axis for shadow cone.

**Comment by gzotti** [comment]
I started investigating this yesterday. The circle should be drawn not at distance  "earth_radius+H" but at "(earth_radius+H)*cos(earth_radius+H, antisolar_direction)" where "earth_radius+H" is of course the (geocentric) satellite position.

**Comment by Atque** [comment]
I don't see the point in showing the shadow, if it does not reflect the border between visible and invisible.

**Comment by gzotti** [comment]
In the drawing, when the satellite is at B, the shadow circle likewise must go through B. This can be achieved with the above change.
