### ISSUE TITLE
quadrature mark

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2511]
**Is your feature request related to a problem? Please describe.**
A way to see where quadrature happens (see also #789)

**Describe the solution you'd like**
Ideas:
- a new line "quadrature line" (actually a cone centered on the Sun)
- a quadrature mark on the ecliptic

**Describe alternatives you've considered**
Search for elongation at 90/270 or use astrocalc

**Additional context**

**Comment by axd1967** [comment]
quadrature of the Moon...

![image](https://github.com/Stellarium/stellarium/assets/3529789/46de11c1-e1f7-46a0-ba45-035be011d26a)

**Comment by axd1967** [comment]
interestingly...
need to check this, but I would assume that the average terminator runs along the quadrature mark.

![image](https://github.com/Stellarium/stellarium/assets/3529789/cb692a61-b705-4166-a199-9753636e3fa3)

**Comment by gzotti** [comment]
Quadrature means 90° away from the sun. Use pen and paper to draw a triangle Moon-Earth-Sun with right angle at earth. Now see the angle at the moon. The sunlight does not come from the side, parallel to the earth-sun line. Therefore terminator does not run along quadrature circle.

**Comment by axd1967** [comment]
correct - it should be a small angle.
