### ISSUE TITLE
Toggling Cardinals in Spheric Mirror Mode

### ISSUE THREAD

**Issue by mjwroe** [Stellarium/stellarium#252]
### Expected Behaviour
In spheric mirror mode, the cardinals should toggle as normal

### Actual Behaviour
In spheric mirror mode, turning the cardinals off causes issues but only either atmosphere or ground are turned on. The issue appears differently for combinations on ground on/off and atmosphere on/off and differently again from full screen to partial screen.

![atmos_off_ground_on](https://user-images.githubusercontent.com/41952218/43965762-079174c2-9cb8-11e8-90c2-fa10ffe75788.png)
![atmos_on_ground_off_fullscreen](https://user-images.githubusercontent.com/41952218/43965763-07b09974-9cb8-11e8-8cd6-e816c4ab09ea.png)
![atmos_on_ground_off_partial_screen](https://user-images.githubusercontent.com/41952218/43965764-07cc0e2a-9cb8-11e8-9efb-3f97d6151814.png)

### Steps to reproduce
As above

### System
* Stellarium version: 0.18.1
* Operating system: Windows 10 Enterprise, version 1703
* Graphics Card: Intel HD, WDDM 2.0, version 20.19.15.4835

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

[log.txt](https://github.com/Stellarium/stellarium/files/2278414/log.txt)

**Comment by gzotti** [comment]
Looks like https://bugs.launchpad.net/stellarium/+bug/1777320. 

Can you quit Stellarium, rename your config.ini (to force a reset) and restart Stellarium?

**Comment by mjwroe** [comment]
Alas, I get the same behaviour (although no Moon texture).
I also saw the issues with 0.18.0 where the whole sky went white under spheric distortion, but 0.18.1 fixed that for me just fine.

**Comment by gzotti** [comment]
Must confirm now (build 16219). With Spherical Mirror distortion, when Cardinals switched off, ground and atmosphere must be both on or off, having only one gives these weird errors.

**Comment by guillaumechereau** [comment]
I confirm too on ubuntu. I will have a look.

**Comment by guillaumechereau** [comment]
I found a fix, but I am not sure if I should commit it, because I don't understand the reason why it works.

Basically, it works if we add those lines at the end of the LandscapeMgr::draw method:

    const StelProjectorP prj = core->getProjection(StelCore::FrameAltAz, StelCore::RefractionOff);
    QOpenGLPaintDevice device;
    device.setSize(QSize(prj->getViewportWidth(), prj->getViewportHeight()));
    QPainter painter(&device);

But I am not sure why... I just found out that the problem occurs unless we call StelPainter::drawText, that eventually use those lines.

I guess some internal states of OpenGL get set when we create a QPainter, even if we don't use it after.  It's not very clear.

**Comment by gzotti** [comment]
Very odd. It happens only in the spheric mirror warping mode, though. Maybe the internal texture numbers are messed up in this case, and these StelPainter lines somehow re-initialize them?

**Comment by psjshep** [comment]
A colleague of mine is using Spherical Mirror Distortion in his inflatable dome...  we would appreciate anything you can do to sort this issue out.
Thanks
Phil

**Comment by gzotti** [comment]
Looks good, thanks. Even if there is some "magic" in this solution, I think this can be closed.

**Comment by mjwroe** [comment]
Thank you folks!

**Comment by alex-w** [comment]
Please check the latest beta - 0.18.2.6 (0.90.0.16289)

**Comment by psjshep** [comment]
Will do thanks.... I will report back...
