### ISSUE TITLE
Add additional names to observing list

### ISSUE THREAD

**Issue by ckuethe** [Stellarium/stellarium#2525]
**Is your feature request related to a problem? Please describe.**

I can't always remember what an object is named from its catalog number, or what its number is based on the name. Unfortunately I couldn't find a way to add additional names to the observing list.

**Describe the solution you'd like**

Add an additional column for names if the user wants to see them.

**Describe alternatives you've considered**

Tried moving the column dividers, right clicking all around the observing list to see if this was already enabled.

**Additional context**

Additional names for the Pelican Nebula
![Screenshot_2022-07-20_10-27-13](https://user-images.githubusercontent.com/1131751/180045220-24870886-b296-42ba-90d4-6e9710140afe.png)

Only one catalog name visible in the observing list.
![Screenshot_2022-07-20_10-14-20](https://user-images.githubusercontent.com/1131751/180043312-58ace5c0-5930-4610-bbac-686279448fa9.png)

**Comment by Jocelyn1109** [comment]
@alex-w Ok :)

**Comment by alex-w** [comment]
> @alex-w Ok :)

Probably this is user notes to the OL or just 2 columns - "designation" + "common name"

**Comment by Jocelyn1109** [comment]
@alex-w @ckuethe  like that ?

![column-name](https://user-images.githubusercontent.com/43777557/180192708-adcd2001-902c-4e35-b623-ac852fafbcbc.png)

**Comment by ckuethe** [comment]
Wonderful!

**Comment by Jocelyn1109** [comment]
@alex-w  @ckuethe I added the object name too in the creation dialog. It's better and clearer.

Jocelyn
