### ISSUE TITLE
no buttons

### ISSUE THREAD

**Issue by rklobstr** [Stellarium/stellarium#253]
### Actual Behaviour :  no buttons appear.  when hovering around where they should be,, button name  appear in white letters.  these are inactive & just names, not buttons.  f keys don't respond.

what i see is a ground view of a field in paris.  i'm in the US.

### System
* Stellarium version: <0.18.1>
* Operating system: <w10>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>  dunno.  computer was made in 2017 so it should be fine.

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/FAQ#menu-invisible-windows
