### ISSUE TITLE
BUGS

### ISSUE THREAD

**Issue by Zeissao** [Stellarium/stellarium#2540]
# v0.22.2

**Comment by alex-w** [comment]
![stellarium-011](https://user-images.githubusercontent.com/88731/181878796-a89230b6-41e5-4dd2-a25f-6201b60dfd40.jpg)

**Comment by alex-w** [comment]
What is "the Bing input method"?

**Comment by Zeissao** [comment]
Bing input method is a text input tool developed by microsoft.
Sorry, i just remembered that i'm using win10 built-in input method instead of bing input method, i made a mistake.
This video shows my problems. As you can see, when i'm typing Chinese pinyin, there's a **_box_** containing candidate characters that correspond to Chinese pinyin appears, so the input content can be previewed in real time before i put them into the search box.
But, the **_box_** will not appear if stellarium runs in fullscreen mode, so i don't know which Chinese character the Chinese pinyin I entered corresponds to. I didn't meet this problem in previous versions.
And i can search for tianhe in Chinese 天和 directly in the past, but as you can see, when i put 天和 in the search box, there's nothing appears.
In the video, when i'm typing "tian", "TIANHE" appears, but when i clicked on it,  it just changed its position in the list, the main interface didn't found tianhe for me. 

https://user-images.githubusercontent.com/97239715/181904767-4cb01088-fcc9-40e6-9abd-6b21dded2190.mp4

I've tried reinstalling stellarium and deleting all related files but that didn't work. Puzzled.

**Comment by alex-w** [comment]
Please check third tab in Satellites plugin: celestrak.com moved to celestrak.org

![Uploading stellarium-012.jpg…]()

**Comment by Zeissao** [comment]
AWESOME! The problem has been solved, thanks very much!
By the way, is it normal that stellarium shows that "The satellite is sunlit and the observer is in the dark", but no magnitude information is shown？It seems that this situation only appears to tianhe...
![stellarium-20220730-192042735](https://user-images.githubusercontent.com/97239715/181908681-fea81c2c-4286-4655-9428-53166a20ce65.png)

**Comment by alex-w** [comment]
No standard magnitude or RCS values exists - no visual magnitude

**Comment by Zeissao** [comment]
Got it, thank you!
