### ISSUE TITLE
Crash when language is changed [scripting disabled]

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2544]
### Expected Behaviour
Changed language of GUI after selection of language in dropdown list of languages

### Actual Behaviour
Crash after selection of language in dropdown list of languages

### Steps to reproduce
1. Run Stellarium. 
2. Open Configuration dialog (F2).
3. Select the language of main program

### System
* Stellarium version: 1.22.2-3d47d9a (universal)
* Operating system: macOS 12.5
* Graphics Card: irrelevant
* Screen type (if applicable): irrelevant

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
@gzotti @worachate001 please check the crash on Windows and linux also...

**Comment by gzotti** [comment]
Changing from startup in German. Poof! 

But I have a hint from log.txt:

Application language is  "et"
Couldn't load translations for language  "et" in section "stellarium-scripts"
Empty translation file for language  "et" in section "stellarium-scripts"
Scripts language is  "et"


This Qt6 build is necessarily still without scripting!

However, changing sky culture language also crashes:

Sky language is  "et"
Planetary features language is  "et"

Also changing to English (en) crashes. :-(

**Comment by alex-w** [comment]
These hints you may see with Qt5 too when translation is not exist, but without crashes. I guess this is unrelated to the problem.

**Comment by gzotti** [comment]
I thought this was a Qt6 issue. Now a Qt5.15 debug build also crashed!

**Comment by gzotti** [comment]
I found what happens: 
With scripting disabled, the last page in the config dialog is removed. 
When changing language, the ui->retranslateUi() call wants to translate everything. But it does not find the last tab. Nullptr->crash.
I can hopefully find a better way to hide, not delete, the script tab. Or keep an empty script dialog.

This should be a minimal nuisance when scripting is reactivated again also in Qt6.
