### ISSUE TITLE
SSO magnitude limit check-box not working - crashes Stellarium

### ISSUE THREAD

**Issue by ArnoldBrody** [Stellarium/stellarium#2546]
Hello.
On the Sky and viewing options window > SSO tab, when I try to click the checkbox for "Limit magnitude" the program freezes and crashes. This happened in version 0.22.2. I have a number of earlier versions and they all crash when I try to select Limit magnitude.
Kindly advise if there is a fix or work-around.
Thank you,
Arnold
[log.txt](https://github.com/Stellarium/stellarium.github.io/files/9243990/log.txt)

**Comment by alex-w** [comment]
I cannot reproduce the issue on macOS.

Please share steps to reproduce.

**Comment by worachate001** [comment]
@ArnoldBrody  Having a large numbers of objects in this file C:\\Users\\arnbr\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini may be the cause. You may try to delete this file or make a backup by renaming or moving it to a backup folder and let the program create a new one. Only add objects that you really need should help.

**Comment by alex-w** [comment]
@ArnoldBrody please share your `ssystem_minor.ini` file

**Comment by aedas** [comment]
Cannot reproduce the issue with Windows 10 (on MacBook Pro) either

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by gzotti** [comment]
@ArnoldBrody if you don't provide your `ssystem_minor.ini` we cannot proceed and will close this.
