### ISSUE TITLE
Stellarium 0.15.2 crashed in Windows

### ISSUE THREAD

**Issue by narkobuck** [Stellarium/stellarium#255]
I normally use 0.15.2 on my Windows 10 laptop but just for planning, never for connection to the mounts.

This morning I was checking out the locations in the program and how clicking each location in random would change the sky view. At the end of it all, I wanted to get back to where I am physically, and there was an option .. something like "get location from network" (I think), so I clicked it since I was connected to the internet, and the program paused for a while then closed itself.

Restarting the program just made it close again in 4 - 5 seconds. After i uninstalled and reinstalled the program, the same thing is still happening. No error messages at all.

I went into the default_config.ini file, went to [init_location] and Location = Auto 

Could this be creating the problem?

Thanks

Roger

**Comment by gzotti** [comment]
Yes. 

The IP lookup service was stopped from this address, and version 0.15 series is not robust enough to handle this properly. Please update, or fill in a place name like "Paris, France", then set your location manually.
