### ISSUE TITLE
Здравейте, в BG превода на 0.18.1 са разменени СЗ и СИ, ЮЗ и ЮИ ...Благодаря за програмата!

### ISSUE THREAD

**Issue by PhilipApostolov** [Stellarium/stellarium#256]
READ THIS AND FILL IN THIS TEMPLATE!

Before reporting an issue around graphics artifacts like missing menu buttons, strange colors, Moon not rendered, or similar, 
*please make absolutely sure* you are running the latest graphics drivers for your graphics card. 
95% of graphics problems are solved this way.

Before reporting an issue, please *absolutely make sure* to check the recent open and also closed issues 
(https://github.com/Stellarium/stellarium/issues?q=is%3Aissue+is%3Aclosed) 
whether it has been reported and solved/closed already! Don't report a new issue in this case, you may join the discussion.

Also look into the wiki https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version 
and FAQ https://github.com/Stellarium/stellarium/wiki/FAQ 
and check if you are attempting to report a known issue. Don't report in this case.

Also look into the User Guide before reporting unexpected but correct behaviour. Don't report in this case.

If you miss translations, please help us with your language and join our translators at Transifex: https://www.transifex.com/stellarium/stellarium/dashboard/

If you want to report a feature wish, delete these template lines above and below, and fill in. 

If you want to report a bug, please make sure to update and verify the bug still exists in the current version. 
In this case please also check current beta builds from http://stellarium.org

If the bug still persists, give your issue a clear, short title, delete text above down to and including this line and fill in:

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Проверете версията 0.18.2RC2

**Comment by PhilipApostolov** [comment]
Не я намирам.

**Comment by alex-w** [comment]
https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by alex-w** [comment]
Проверете версията 0.18.2 - https://stellarium.org

**Comment by Iskandor** [comment]
Hello, we have similar problem in Slovak localization, there is southwest instead of northwest and vice-versa. Our version is 0.18.2.
All the best

**Comment by gzotti** [comment]
Please read the carefully ignored template above!

If you miss translations, please help us with your language and join our translators at Transifex: https://www.transifex.com/stellarium/stellarium/dashboard/

**Comment by alex-w** [comment]
I've checked Bulgarian language - it's OK for 0.18.2. Fixed in Slovak language.
