### ISSUE TITLE
Odd sound

### ISSUE THREAD

**Issue by MaryAlice51** [Stellarium/stellarium#2560]
### Actual Behaviour
Describe:
There is an odd sound, barely audible but no less annoying. Happens regardless of what Location I use, whether Earth, Moon, Mars, Jupiter. 
It's a kind of a hiss, and occasionally, there is the sound of crickets. 
I like to keep the Stellarium open and running in it's own window, but, the sound is annoying, even when I'm not using that window.
In fact the sound continues even when I quit Stellarium but leave the Icon on the Dock

### System
* Stellarium version: <0.22.2>
* Operating system: <macOS Monterey  12.5>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>  I don't know
* Screen type (if applicable): Resolution, HighDPI, scaling Built in Retina 2880 x 1800
### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
By default Stellarium has no sounds, but you wrote “there is the sound of crickets”. Few years ago I’ve published script for playing the sound of crickets at startup the program and maybe you have it. Please check `startup.ssc` script.

**Comment by MaryAlice51** [comment]
Thank you,
where do I find startup . scc script

**Comment by MaryAlice51** [comment]
It's getting late here, I will try to follow any instructions, tomorrow
Thank you

**Comment by gzotti** [comment]
This is noise from the internal electronics of your computer, similar to the sound of auxiliary pumps (air condition, servo steering, ...) in your car when the main engine is running. Maybe you have not heard it in other applications when they don't need the graphics card. Stellarium has not really to do with it other than actually "using" that hardware.

**Comment by MaryAlice51** [comment]
I see. I use all manner of graphics on my Mac, I watch videos, I do Photoshop, I watch Live TV…it’s a long list of things I do on my Computer.
I get no, none, zero, back ground humming, and crickets chirping, while running, using, anything else on my MacBook.

Last evening I got this reply:

Member 
alex-w <https://github.com/alex-w> commented 11 hours ago <https://github.com/Stellarium/stellarium/issues/2560#issuecomment-1207340914>
By default Stellarium has no sounds, but you wrote “there is the sound of crickets”. Few years ago I’ve published script for playing the sound of crickets at startup the program and maybe you have it. Please check startup.ssc script.
I replied to Alex-w that it was late, I’ll look into it tomorrow…which is today now. 
Maybe you can tell me, where can I find startup . ssc script?
Thank you

**Comment by gzotti** [comment]
Watching TV, photoshopping, etc. may not require the 3D graphics hardware. Modern videogaming would use it. Try that with sound switched off. Or switch sound off generally to notice that this "barely noticeable but no less annoying" sound is not emitted from the loudspeaker. I hear some hissing occasionally, but also not every day.

The location of startup.ssc is the scripts subdirectory of the user directory described in the User Guide, section 5.1.2. However, I am 99.999999% sure you are not hearing a sound file.

**Comment by MaryAlice51** [comment]
I see
I also use SkySafari6 Pro by Simulation Curriculum  which, I'm guessing, uses the same, or very similar, 3D graphics as Stellarium?  I get no hissing, humming, nor crickets chirping with that.
Even when I turn Sound Off, I can hear the sound, from the computer speakers. Even after I deleted Stellarium, the sound continued. Only after using a Shredder, on Stellarium,  on ClearMyMacX did the sounds stop.
I really enjoyed Stellarium, for a number of years. It's easy to use, the graphics are great, I like everything about Stellarium. I would love to keep using it. 
But I cannot, so long as  that pervasive background sound continues.
Thank you for your input.

**Comment by gzotti** [comment]
I don't know the commercial programs. If you hear the sound even with speakers switched off or when Stellarium does not run, how would the existence of the program files on your filesystem cause sound emission? 

Random bits of further information:

https://forums.tomshardware.com/threads/hissing-sound-coming-from-my-pc.3689625/
https://www.reddit.com/r/buildapc/comments/6d731o/hissing_noise_coming_from_computer/

There is nothing to fix for us.

**Comment by MaryAlice51** [comment]
Closed? Rather than do further investigation? Here's a reminder of a response I got:
[alex-w](https://github.com/alex-w) commented [14 hours ago](https://github.com/Stellarium/stellarium/issues/2560#issuecomment-1207340914)
By default Stellarium has no sounds, but you wrote “there is the sound of crickets”. Few years ago I’ve published script for playing the sound of crickets at startup the program and maybe you have it. Please check startup.ssc script.

Alex published a script playing the sound of crickets at start up
 I REPEAT I DO NOT get that swishing humming sound, nor crickets chirping, while running ANY OTHER PROGRAM. Forgive me for shouting, but sometimes shouting is necessary.

Don't want to investigate further, to fix it? That's your choice
I regret that I cannot, will not use Stellarium, which is sad because it is, otherwise, a very good program

**Comment by alex-w** [comment]
@MaryAlice51 could you record and share the odd sound?

**Comment by MaryAlice51** [comment]
Record an Internal, not External sound? I don’t know, I’ll look into that.
Meanwhile I deleted Stellarium, again, to eliminate the sound.
Meanwhile, go back in the replies to the person who said he put a Crickets Sound Effects in a Script, somewhere, on Stellarium.
Maybe he should write a Script to eliminate it, or, at least make it optional, and produce an updated Stellarium
Thank you for your reply

**Comment by MaryAlice51** [comment]
Thank you
Where do I find startup. scc  script?

**Comment by alex-w** [comment]
On the Mac `startup.ssc` is located within `Stellarium.app` (`Stellarium.app/Contents/Resources/scripts/startup.ssc`) by default, but users can save own scripts into `~/Libraries/Application Support/Stellarium/scripts` directory. If you did not managed anything related to Stellarium's scripts on your mac, then you have standard scripts only - without media files.
