### ISSUE TITLE
keyboard shortcut not being saved 

### ISSUE THREAD

**Issue by sushi-valou** [Stellarium/stellarium#2571]
Hi !
I've been encountering a somehow annoying issue regarding the keyboard shortcuts. Whenever I select ";" as a shortcut for an action, Stellarium doesn't save it after closing the software. For example, if you apply ";" to adding a solar day, you will see that the keyboard shortcut is no longer there after closing Stellarium. 

### Expected Behaviour
The keyboard shortcut should be applied after pressing the button "apply" and stay saved even though you close the software. 

### Actual Behaviour
The keyboard shortcut is no longer applied to the given action after reopening Stellarium. 

### Steps to reproduce
--> Apply a keyboard shortcut to any action with ";"
--> Close Stellarium (Ctrl+Q)
--> Go back on Stellarium
--> Look at the action to which you gave the keyboard shortcut, it should no longer be here. 

### System
* Stellarium version: v0.22.2 - Windows 64 bit
* Operating system: Windows 10
* Graphics Card: irrelevant
* Screen type (if applicable): irrelevant

**Comment by alex-w** [comment]
";" is assigned already for meridian line

**Comment by sushi-valou** [comment]
I am aware of this, but I have another shortcut for the meridian line. I've changed almost every default shortcut to arrange it in a way where I can memorize them easier. ";" seems to be the only button that has this issue.

**Comment by alex-w** [comment]
@sushi-valou please share config.ini file from Stellarium

**Comment by sushi-valou** [comment]
Could you please tell me where can I find this information ? Also I'm on Windows 10, sorry for the error. Thank you very much

**Comment by alex-w** [comment]
Please check About dialog within planetarium - it has the full path to config.ini file. You may found it in the Stellarium User Guide or in startup menu group.

**Comment by sushi-valou** [comment]
I made some research and yet I struggle to understand where I can manage to find the config.ini file. Is there a relevant paragraph in the user guide can tell me step by step how to get there ? I apologize for taking quite a lot of time to help you save this problem.

**Comment by gzotti** [comment]
Chapter 5.

**Comment by sushi-valou** [comment]
After doing a lot of researches I finally found it ! I hope that this is what you were looking for and that hopefully you will be able to understand what's happening with this ";"  Thank you so much. 
[config.ini Stellarium.txt](https://github.com/Stellarium/stellarium/files/9387768/config.ini.Stellarium.txt)

**Comment by sushi-valou** [comment]
> Chapter 5.

I indeed searched o*in the user guide and I was able to find the file afterwards.
