### ISSUE TITLE
Angular distance in AstroCalc/PC tool

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2578]
### Expected Behaviour
Angular distance axis have values in degrees

### Actual Behaviour
In some cases angular distance axis has no values. See screenshots.

Good:
![stellarium-013](https://user-images.githubusercontent.com/88731/184878500-7b2e4fbd-5bce-4431-946d-e39a58fdd060.jpg)

Bad:
![stellarium-014](https://user-images.githubusercontent.com/88731/184878585-3ab69424-b6c4-4e5a-9ae3-08114e2edd94.jpg)

### Steps to reproduce
1. Run Stellarium2. 
2. Open AstroCalc/PC/Graphs tool3. 
3. Select Jupiter - Saturn planets (or any planets with wide distances)4.

**Comment by alex-w** [comment]
Probably issue is happened when angular distance is over 90 degrees

**Comment by gzotti** [comment]
The QtChart avoids overlapping text.  When you scale the window to be higher, do the numbers appear?

**Comment by gzotti** [comment]
Yes, just scale the window:
![image](https://user-images.githubusercontent.com/18099873/184885028-6dd66cfe-b88a-42ed-8f0a-49ea0896457b.png)
