### ISSUE TITLE
Flathub's latest version doesn't load the saved config.

### ISSUE THREAD

**Issue by BaraVaq** [Stellarium/stellarium#258]
Hello, 

### Expected Behaviour

Stellarium loads  the saved config. 

### Actual Behaviour

Always as if it were the first start. 

### Steps to reproduce

Explore then click save both view and settings. Close the application and open it again. 

### System
* Stellarium version: Flathub's 0.18.1
* Operating system: Debian 8,9; Ubuntu 18.04  

Best wishes, 
BaraVaq

**Comment by gzotti** [comment]
Seems to be a Flathub problem outside our reach.

**Comment by alex-w** [comment]
Please check updated flatpak

**Comment by BaraVaq** [comment]
Thank you for the changes. Everything works well now.
