### ISSUE TITLE
Phase angle vs Time in AstroCalc/Graphs tool

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2582]
### Expected Behaviour
Right axle for function "Phase angle vs Time" have values in degrees

### Actual Behaviour
Right axle for function "Phase angle vs Time" have no values when phase angle is over 90 degrees. See screenshots.

Good:
![stellarium-015](https://user-images.githubusercontent.com/88731/184882590-ff77ba66-7b50-4c54-bbdf-a0008deca04f.jpg)

Bad:
![stellarium-016](https://user-images.githubusercontent.com/88731/184882642-bbf7ae41-b29a-4de5-a69d-6d44f6692f88.jpg)

**Comment by gzotti** [comment]
Same as #2578

**Comment by gzotti** [comment]
It's the same issue with a QChart axis labeled too densely. Increase window height slightly, and all numbers appear. If this is really too annoying, I can try to reduce partitions of the vertical axis.

**Comment by alex-w** [comment]
Did you set the number of partitions “manually”?

**Comment by gzotti** [comment]
AstroCalcChart::setYrangeR(). But please adjust carefully.
