### ISSUE TITLE
Preset Sensor/Telescope/Lenses within Ocular changes after Sync and Show in Astro Photography Tool software

### ISSUE THREAD

**Issue by jmesseroff** [Stellarium/stellarium#2585]
### Expected Behaviour
After plate solving in APT software and clicking Sync, then Show, it sends a message the info was sent to Stellarium.  However, the preset Sensor/Telescope/Lenses in OCULAR changes to a different sensor/telescope/lens.  When I manually reselect the correct sensor/telescope/lens defined FOV rectangle moves slightly off the actual location of the plate solved coordinates.

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Stellarium 0.22.2>
* Operating system: <Windows 11 Home>
* Graphics Card: <Intel(R) UHD Graphics, Driver 30.0.101.1692  Date 4/11/22>
* Screen type (if applicable): Resolution, HighDPI, scaling
* Generic PnP Monitor, Scaling 100%, Display Resolution 1366x768

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/9365738/log.txt)

![Stellarium Setup ASI 071camera Tak 180 Scope](https://user-images.githubusercontent.com/111460077/185227363-a461dfa7-e166-4b9d-9b35-69a84da31bd3.jpg)
![Sync-Show changes scope-camera +location](https://user-images.githubusercontent.com/111460077/185227474-f978cc99-a792-426f-8b62-9b98cfc66f7b.jpg)
![APT Image Plate Solved](https://user-images.githubusercontent.com/111460077/185227491-290cb705-7a8b-4d4d-bde5-d06cfd7812a7.jpg)

**Comment by alex-w** [comment]
Please check APT user guide and settings within APT for Stellarium

**Comment by jmesseroff** [comment]
Thanks Alexander,

You were correct. I reinstalled APT on a new laptop and one of the settings populated incorrectly.  I have since fixed this setting and things are working correctly. 

Thanks,

Jay
