### ISSUE TITLE
Directions markers are tilted relative to the horizon line

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2603]
### Expected Behaviour
When using perspective projection, the horizon is straight, so the direction markers should be vertical.

### Actual Behaviour
The direction markers become tilted relative to the horizon when camera looks up or down — so that the horizon is not in the center. See the screenshot below.
![Screenshot - 250822 - 19:51:09](https://user-images.githubusercontent.com/6376882/186724724-3ec94f53-fb2b-4468-9bbc-388097251090.png)

### Steps to reproduce
1. Launch Stellarium
2. Set projection to _Perspective_
3. Orient the camera so that the horizon is close to the top or bottom of the screen
4. Look at the direction markers — S, SW, W, etc., notice how they become tilted when coming to the right or left edge of the screen.

### System
* Stellarium version: 20bd99ad733b00416b25d5b38d3c104be4d0f119
* Operating system: Linux From Scratch
* Graphics Card: Nvidia GeForce 750Ti, with `nvidia` proprietary driver
* Screen type (if applicable): 1920×1080, 102 DPI

**Comment by gzotti** [comment]
Please add azimuthal grid to understand that this is not a bug but very much intended.

**Comment by 10110111** [comment]
> Please add azimuthal grid to understand that this is not a bug but very much intended.

Well this is very non-obvious. Maybe they should be straight when the azimuthal grid is not displayed? Otherwise these letters really seem "drunken".

**Comment by gzotti** [comment]
The labels are always tilted parallel to the vertical lines. ("Vertical" as in "great-circle arcs joining in the respective pole, zenith, etc.") This is an intended program feature, and earlier versions had various issues in other modes, esp. in spherical mirror mode. The perspective projection is just ugly when FOV is large.
