### ISSUE TITLE
Can't parse `constellation_names.eng.fab` file

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2606]
The problem found in the attached log to the bug report #2605

### Expected Behaviour
Correct reading the constellation names info

### Actual Behaviour
Stellarium can't parse `constellation_names.eng.fab` file in Indian sky culture

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
The problem are the special characters in the abbreviated name. The regular expression does not allow them currently. (it seems character class w only has ASCII?) 

2 solutions possible:
- allow non-ascii characters in the abbreviation key
- remove non-ascii characters and require pure ascii keys

**Comment by gzotti** [comment]
Extended RE to recRx("(*UCP)^\\s*(\\.?\\w+)\\s+\"(.*)\"\\s+_[(]\"(.*)\"[)]\\s*([\\,\\d\\s]*)\\n");

According to https://pcre.org/original/doc/html/pcrepattern.html, the (*UCP) extends \w to Unicode. Now all lines are valid, except for line 113, which has a R_with_ring_below that appears to be a combined character. 

@alex-w shall I replace \w by the "any" character (.)? Or should we enforce non-diacritic keys for the sake of programmability?

**Comment by alex-w** [comment]
I fear using “all” characters will give problem later :(

**Comment by alex-w** [comment]
> allow non-ascii characters in the abbreviation key

this is better solution IMHO

**Comment by gzotti** [comment]
Errm, this is contradictory. You mean, "remove non-ascii characters and require pure ascii keys"? This requires only editing the constellation_names.eng.fab plus a docfix in the SUG.

**Comment by alex-w** [comment]
> Errm, this is contradictory. You mean, "remove non-ascii characters and require pure ascii keys"? This requires only editing the constellation_names.eng.fab plus a docfix in the SUG.

No, I mean “allow non-ascii characters in the abbreviation key”. I fear using (.) in some cases will cause wrong results.

**Comment by gzotti** [comment]
But this is the point! Currently we allow \w which excludes Unicode with diacritics. This makes life easier for the program. When you want to *allow non-ascii characters*, using (*UCP) extends \w to mean \p{N}|\p{L}|_, which excludes the R_with_ring. 
This requirement of allowing non-ASCII keys means using "." or at least \p{L}|\p{N}|\p{P}|_.

**Comment by gzotti** [comment]
Tried recRx("(*UCP)^\\s*(\\.?(\\p{N}|\\p{L}|\\p{P}|_)+)\\s+\"(.*)\"\\s+_[(]\"(.*)\"[)]\\s*([\\,\\d\\s]*)\\n");
The R_with_ring_below (line 113) is still excluded. 

Tried recRx("^\\s*(\\.?.+)\\s+\"(.*)\"\\s+_[(]\"(.*)\"[)]\\s*([\\,\\d\\s]*)\\n");
"Any character" Works, but we are unsure if that opens a can of worms.

Tried recRx("^\\s*(\\.?\\S+)\\s+\"(.*)\"\\s+_[(]\"(.*)\"[)]\\s*([\\,\\d\\s]*)\\n");
"Non-whitespace": Also works.

What to use? What is the danger of "." over "\S"?

**Comment by alex-w** [comment]
Probably the latest one looks better here
