### ISSUE TITLE
No Milky Way in ANGLE mode

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#261]
### Original discussion
https://groups.google.com/forum/#!msg/stellarium/w0g1ZYMs5G4/imeNOPL1DQAJ

### Expected Behaviour
Milky Way visible
### Actual Behaviour
In ANGLE mode (OpenGL ES), shader compilation breaks, and the Milky Way is not rendered.

### Steps to reproduce

Call Stellarium in ANGLE mode, or run it on a blacklisted system like Core-i[357]-2xxx generation which is forced to ANGLE mode. 

### System
* Stellarium version: 0.18.2 
* Operating system: Windows 7, 10
* Graphics Card: Intel Core i7-2xxx and (forced) GeForce 960M.

### Logfile 
See original discussion above.

Shader compilation fails, logfile contains more detailed diagnosis.

**Comment by guillaumechereau** [comment]
Possibly a bug from the new saturation Shader.  Maybe ANGLE doesn't support the 'v.xxx' syntax?

**Comment by guillaumechereau** [comment]
OK, after closer inspection, at least on problem was from the lake of precision specification in the shader, since this is required for OpenGL ES2.  I push a fix.

**Comment by gzotti** [comment]
OK, this seems to have fixed the Milky Way, at least with DirectX9 and DirectX11 on NVidia 960M. Thanks!

**Comment by alex-w** [comment]
Please check version 0.90.0.16237 (0.18.2.2)

**Comment by gzotti** [comment]
Yes, fixed. Thanks!
