### ISSUE TITLE
Short Up vector flicker after turning to object

### ISSUE THREAD

**Issue by worachate001** [Stellarium/stellarium#2614]
### Expected Behaviour
No flicker.

### Actual Behaviour
Screen flickers.

### Steps to reproduce
1. Open search window to search for any object.
2. Screen flickers when centering at the object.

It also happens with other operations that use the same behavior (double click an item in AstroCalc, for example). The issue just come up very recently.

### System
* Stellarium version: 22.3 (latest master)
* Operating system: Windows 10, Linux Mint 21
* Graphics Card: NVIDIA GeForce RTX 2060 SUPER
* Screen type (if applicable): -

**Comment by alex-w** [comment]
@worachate001 could you record the video?

**Comment by worachate001** [comment]
Here it is ...
https://user-images.githubusercontent.com/41257965/187824867-7150695a-3204-4c6a-90e2-4b79fc826cfb.mp4

**Comment by worachate001** [comment]
If you have trouble with above link, you can try this - https://youtu.be/RYIcII-LME8

**Comment by alex-w** [comment]
The bug was introduced in commit 4e2ee7d87f54c7282d5c3e74a77cba5b08c8cae0

@gzotti could you review it again?

**Comment by gzotti** [comment]
Sigh... sure :-(

**Comment by worachate001** [comment]
Also, one more weird thing happens when you double click an object. Orientation of the sky changes in unexpected way (use wide angle view to see the change).

**Comment by gzotti** [comment]
Bah, right. This is what I hate about the StelMovementMgr. This class has become way too complicated to comprehend what's going on...
