### ISSUE TITLE
Erratic behavior with right click in Angle Measure plugin with snap option

### ISSUE THREAD

**Issue by worachate001** [Stellarium/stellarium#2630]
This looks like unintentional to me. Please correct me if I'm wrong.

### Expected Behaviour
Starting point fixed when selecting end point with right click.

### Actual Behaviour
Starting point *sometimes* change to previously selected end point.

### Steps to reproduce
1. Enable Angle Measure plugin and 'Allow snap to selected object'
2. Right click several times to different points to test it.

### System
* Stellarium version: latest master
* Operating system: Linux Mint 21

**Comment by alex-w** [comment]
@uwes-ufo please check it

**Comment by alex-w** [comment]
I think the new behaviour should be at least described in Stellarium User Guide

**Comment by uwes-ufo** [comment]
The end point is always the last edited point, the start point is the penultimate one.

**Comment by alex-w** [comment]
@uwes-ufo plugins/AngleMeasure/src/AngleMeasure.cpp:400 has code `if (erase || release && !picked)` - please add brases to get a strong logic comparison

**Comment by uwes-ufo** [comment]
> Starting point sometimes change to previously selected end point.

This depends on the position of the mouse pointer in relation to the two line ends. The end of the line that is closer to the mouse pointer is moved and defined as the new end point.

**Comment by uwes-ufo** [comment]
> plugins/AngleMeasure/src/AngleMeasure.cpp:400 has code `if (erase || release && !picked)` - please add brases to get a strong logic comparison

please read this line as `if (erase || (release && !picked))`

**Comment by alex-w** [comment]
From description of PR:
> You can pan the screen and left-click to select an object as usual, and a right-click will snap the end of the protractor line (closest to the mouse pointer) to the selected object. Double-click with the right mouse button to pick up the end of the line. Another double click with the right mouse button removes the angle measuring line.

@worachate001 is it resolves the issue or you found something else?

**Comment by gzotti** [comment]
I am especially missing an update of the function description in the User Guide.

**Comment by worachate001** [comment]
Maybe I'm still confused or misunderstood. Please take a look at my recorded video here - https://youtu.be/eyOwZrc5Z3E

I'm trying to measure angular distance between Jupiter and many of its moons. I want starting point stay at Jupiter but at the end, it's not.

1. I began with selecting Jupiter, and right-click.
2. Select one of moon and right-click.
3. Select another moon and right-click.
4. I want to repeat the same process with other moons.
5. At the end, starting point switched to Io.

What happened here, what's wrong with my method?

Anyway, it's not a big issue (we have another option). It feels like there is inconsistent behavior?

**Comment by uwes-ufo** [comment]
> What happened here, what's wrong with my method?

After selecting Europe, please right click near the top right end of the line (near Io) that you want to move. Otherwise the lower left end of the line will be moved as shown in your video.

The end of the line that is closest to the mouse pointer when you right-click is moved.

**Comment by worachate001** [comment]
@uwes-ufo Thanks for explanation, I think I get it now. It's somewhat unexpected method (when I click Europa but have to move mouse pointer back near Io for the best result), we need to clearly explain it in the User Guide. We may close this issue, I guess.

**Comment by alex-w** [comment]
> @uwes-ufo Thanks for explanation, I think I get it now. It's somewhat unexpected method (when I click Europa but have to move mouse pointer back near Io for the best result), we need to clearly explain it in the User Guide. We may close this issue, I guess.

@uwes-ufo please prepare explanation of new behavior for the User Guide - as pull request or comment for this issue.

**Comment by uwes-ufo** [comment]
> please prepare explanation of new behavior for the User Guide - as pull request or comment for this issue.

- The left mouse button is not used for angle measurement, so you can pan the screen and left-click to select an object as usual.
- To draw the angle dimension line, you can drag with the right mouse button.
- A right click moves the end of the angle line that is closest to the mouse pointer.
- If an object is selected, right-clicking will snap the end of the protractor line (closest to the mouse pointer) to the selected object.
- Double-click the right mouse button to capture the end of the line. Another double click with the right mouse button removes the angle measuring line.
