### ISSUE TITLE
Stellarium won't start with Dell Dsiplaylink 3100 attached

### ISSUE THREAD

**Issue by myorangedragon** [Stellarium/stellarium#2638]
### Expected Behaviour
Run Stellarium and a window should appear

### Actual Behaviour
No window appears but Stellarium app is taking around 17.5% CPU usage, This continues until I end task.

### Steps to reproduce
With Dell DisplayLink 3100 attached all attempts to run Stellarium result in the same problem (I have tried every one of the possible startup variants (MESA etc). However, if the Displaylink USB is unplugged, it runs fine on my laptop's built in display. If, when Stellarium is running, I plug in the Displaylink USB, then Stellarium continues to run and I can move the Stellarium window to any of the 3 monitors that my Displaylink has attached and it will continue to work OK. If I then close the window and try to run a new instance of Stellarium, the problem is back again. Note I have tried running stellarium from the windows menu bar on all 4 screens I have attached (laptop and 3 displaylink screens) and it fails on all of them (including the laptop's own screen which works ok if the Displaylink is unplugged).
I have also tried turning off the 4k screen so there are just the 2 1920x1280 screens and this also fails.
I have also tried turning off the 4k and one of the smaller screens and it also fails.

### System
* Stellarium version: stellarium-0.22.2-win64
* Operating system: Windows 10 latest auto update: 21H2
* Graphics Card: Dell Displaylink 3100: Latest drivers dated Aug 2022 (DisplayLink-Dock-Driver_5DF5P_WIN_10.2.7042.0_A02)
    On Laptop Intel Graphics 3000: Version 9.17.10.4459 Date 5/19/2016 (Latest available)
* Screen type (if applicable): On Displaylink 3100: 2x Dell 1920x1280 and one Samsung 4K
         On Laptop: 1920x1280 built in screen.
### Logfile 
There is no log.txt file created when the problem occurs.

**Comment by gzotti** [comment]
There must be a logfile created. We had a bug report earlier when the window was created off-screen at negative coordinates. Such would be written in the logfile. Other than that, I don't know what a Dell DisplayLink 3100 is and why this device misbehaves.

**Comment by myorangedragon** [comment]
Hi Gzotti,   Thanks for the quick reply.
I have just run an explorer search on "log.txt" on my C drive. The only file with that name is an adobe elements data file and it's contents are very adobe specific.
I have also tried running Stellarium, letting it eat CPU cycles at 17.5% and then running a search for log.txt on my users directory and also the "Program Files" directory - still just the adobe log.txt file.
FYI a Dell Displaylink 3100 is a USB3.0 docking station for older Dell laptops - it provides one 4K Displayport output and 3x 1920x1280 HDMI outputs plus some more USBs and Audio outputs. Being slightly old now, they are type A USB3.0 connectors rather than the Type C connectors that most such things use these days.
Also I can report that when it runs correctly (with the DisplayLink disconnected) then it quickly goes to around 4%  CPU usage (this figure is from memory - but for sure it was a lot less than 17.5%). I am running a Quad Core i7 with SSDs.

**Comment by gzotti** [comment]
The canonical path to the user directory which includes log.txt is described in the User Guide, chapter 5.

**Comment by gzotti** [comment]
Any news? Else we close this at end of September.

**Comment by gzotti** [comment]
It's long overdue to close this.
