### ISSUE TITLE
Ocular Plugin "Scale image circle" value not saved

### ISSUE THREAD

**Issue by Austin-RR** [Stellarium/stellarium#264]
**SUMMMARY**

Stellarium will not remember the setting value for the "Scale image circle" option in the Oculars plugin.  The Stellarium GUI appears to not update the ocular.ini file for this option.  The option can only be set through a manual edit of the ocular.ini file.  This bug appears in all versions from 0.17.0 through the current version of 0.18.2.

**DETAIL**

When opening the Ocular plugin settings and setting a value for the "Scale image circle" option, the value first appears to have been successfully changed.  The image circle does in fact follow whatever value has been set for this option.  However, once Stellarium is closed and started again, it becomes apparent that the value has never been saved to the ocular.ini file.

**HOW TO REPRODUCE**

Using "stellarium-0.18.2-win64.exe" on Windows 7 (x64):

1. Ensure Stellarium will start with a clean startup.
(%APPDATA%\Stellarium should be deleted prior to starting Stellarium.)
2. Start Stellarium.
3. Open the Oculars settings window.
4. Under the "General" tab, notice the "Scale image circle" option is selected (it has a checkmark).
5. Deselect the "Scale image circle" option (remove the checkmark).
6. Shutdown Stellarium.
7. Start Stellarium.
8. Open the Oculars settings window.
9. The "Scale image circle" option is STILL selected when it should not be selected.

**OTHER INFO**

The "Scale image circle" option is listed as the "use_max_exit_circle" parameter in the ocular.ini file of the Ocular plugin.  Manually editing this parameter in the ocular.ini file will successfully allow the desired setting to always appear at every startup.  However, any change made through the GUI will never be remembered.

A quick check of all the other settings in the "General" tab appear to show that all their setting changes get written to the ocular.ini file just fine.  This bug appears to only affect the "Scale image circle" option.

Using the "Save settings" feature within the "Configuration" window does not help.  The Ocular settings do not need to be saved with this "Save settings" feature, but it was tested anyway.

**VERSION TESTS**

Tested older Stellarium versions (all Win-x64 versions) and found that this bug first appeared in 0.17.0.

0.16.1 - No Bug
0.17.0 - Bug exists
0.18.0 - Bug exists
0.18.1 - Bug exists
0.18.2 - Bug exists

Note that my personal preference for this "Scale image circle" option is to change its value from its default value of enabled to the disabled value.  I believe I have never noticed this bug before probably because at the release of every version, I tend to create a new custom configuration for the entire %APPDATA%\Stellarium directory by copying/pasting some information from the previous configuration files.  Therefore, I was always able to get this option to behave they way I intended for it to behave because I manually set the value in the ocular.ini file.

**Comment by alex-w** [comment]
Thank you very much for detailed bug report!
