### ISSUE TITLE
Satellites Plugin new clear search button continues to filter results

### ISSUE THREAD

**Issue by Austin-RR** [Stellarium/stellarium#265]
**SUMMARY**

When using the new (new to 0.18.2) clear button that has been added to the Satellites Plugin for searching satellites, it appears the results will still get filtered despite the search terms getting cleared strictly by using the new clear button.

**HOW TO REPRODUCE**

Using "stellarium-0.18.2-win64.exe" on Windows 7 (x64):

1. Ensure Stellarium will start with a clean startup. (%APPDATA%\Stellarium should be deleted prior to starting Stellarium.)
2. Start Stellarium.
3. [ALT+Z] to bring up the Satellites plugin settings and go to the "Satellites" tab.
4. From the drop-down menu, select "all" if not already selected.
5. All available satellites should be listed.
6. In the search box, type "iss" (without quotes).
7. Possibly 3 satellites should only be listed: "AISSAT 1", "ISS (ZARYA)" and "SWISSCUBE". (This is the correct behaviour.)
- From my testing, these are the only satellites I have that include "iss" in its name.
- Note that there may be some variations for you depending on what list of satellites are made available at the time of doing these steps.
8. From the drop-down menu, select "scientific".
9. Only "ISS (ZARYA)" should be listed. (This is the correct behaviour.)
10. Use the new clear button to clear the search box.
11. From the drop-down menu, once again select "all".
12. Only "AISSAT 1", "ISS (ZARYA)" and "SWISSCUBE" appear in the list. (This is NOT the correct behaviour. All satellites should appear.)
13. From the drop-down menu, once again select "scientific".
14. Only "ISS (ZARYA)" appears in the list. (This is NOT the correct behaviour. All scientific satellites should appear.)

**MORE INFO**

It can be seen that every list is still being filtered with the "iss" search term despite the search box being cleared by the new clear button.

Closing the Satellites Configuration window and opening it up again does not help the issue.

The search box can be truly be cleared by manually clearing it with the delete or backspace key.  If the clear button has already been used, then simply type anything in the search box and then clear it with the delete or backspace key - which is the method that has always been used before.

**Comment by alex-w** [comment]
Thank you very much for detailed bug report!
