### ISSUE TITLE
ISS as shown in Stellarium happens approx 20 mins before it actually happens in the sky

### ISSUE THREAD

**Issue by MintakaLite** [Stellarium/stellarium#2654]
<!--

I have been using Stellarium very happily for many years with no problems to speak of. 
However over the last couple of months when checking the path of Zarya (ISS), the times of visibility and transit/ close pass of the Moon or Sun, Stellarium is out but approximately 18mins in terms of timing. Also transits not showing in Stellarium when 'predictions' are shown in other software.

The other software/websites I use is Heavens-Above, Satflare and Luminos Pro app on my iPhone. 

Lat 53 deg, 28 min, 8.7 sec North.
Long 1 deg, 4 min, 31.67 sec West.
20m above sea-level
From several sources like GPS, Ordinance Survey maaps

When I go outside and look for the ISS, the timing as suggested by Stellarium is not correct, but is correct with the other software/websites.

Other than Windows updates and software updates, nothing else has changed on my PC.

Latest stellarium-0.22.2-win64

PC details

Device Specifications

Device name	Astro-2
Processor	Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz   3.20 GHz
Installed RAM	12.0 GB (11.9 GB usable)
Device ID	6EE63446-C026-4D2E-A0B6-BF5A5C106FB5
Product ID	00330-80000-00000-AA334
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Graphics Nvidia GeForce 405

Windows Specifications

Windows 10
Edition	Windows 10 Pro
Version	21H2
Installed on	‎22/‎10/‎2020
OS build	19044.1949
Experience	Windows Feature Experience Pack 120.2212.4180.0

My PC 
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Update satellite elements.

**Comment by JAY-Githb** [comment]
How old are your TLEs?
ISS occasionally changes orbit so you should use the latest TLE.
Predictions work fine for me.

Jay

**Comment by alex-w** [comment]
Please check the sources of TLE - celestrak changed the domain couple months ago.

**Comment by MintakaLite** [comment]
Hi, thanks for your replies.
Satellites Plug In loads at start-up and is configured to update every hour. So that should not have been the problem.
I tried looking at how to find, download and import TLE data from another website. 
Not done that yet, but I will continue the hunt.

However, spurred on by the replies, I looked again in the satellite plug-in. 
I removed ISS(Zarya) from the list, then saved settings, re-started Stellarium and added ISS back in. 
Success, trusty old Stellarium is now back showing ISS back in its proper place.
Hoping to image a transit of the sun on 30th of September, clouds and orbital boosts permitting.

Thank you

**Comment by JAY-Githb** [comment]
To get TLE from another site:
Download the TLE to your computer.. Update from that file.
or
Put that site in your Source list. You can then update directly from that site.

**Comment by axd1967** [comment]
Same issue indeed.

The TLE epoch as shown on 2022-09-21 said "October 4" (!!!):

![image](https://user-images.githubusercontent.com/3529789/191586192-5fe7d871-0b7f-4ca4-92d2-864b086d505e.png)



## Workaround
As proposed in https://github.com/Stellarium/stellarium/issues/2654#issuecomment-1250093957, delete the ISS and then use the '+' button to add it again. TLE epoch is now September 15.

![image](https://user-images.githubusercontent.com/3529789/191586415-f7baccc6-2d72-45db-9d99-05b09fd75d98.png)


Nevertheless, I do not understand why this has happened; the TLE are supposed to be updated and fetched on a regular basis (I do it at least once a day).
So for me this smells like a bug somewhere.

**Comment by JAY-Githb** [comment]
Could be an error in the TLE.  Can't tell since that's not shown.
Post again showing line 1 as well as line 2.
Where do you get the TLE?

Jay

**Comment by axd1967** [comment]
aha - looks like the problem comes from adding these on top of the default sources:

https://celestrak.org/NORAD/elements/supplemental/sup-gp.php?FILE=iss&FORMAT=tle

Stellarium should issue a warning when it detects such a situation?
