### ISSUE TITLE
Black image created when custom size screenshot is enabled

### ISSUE THREAD

**Issue by worachate001** [Stellarium/stellarium#2655]
### Expected Behaviour
Normal screenshot.

### Actual Behaviour
Black image (white if invert colors is enabled).

It seems to related with Qt6 (Qt5-based build is working properly).

### Steps to reproduce
1. Enable any custom size (F2 > Tools > Screenshots)
2. Ctrl+S to take screenshot

### System
* Stellarium version: 1.22.2-0fd7b3d (latest beta)
* Operating system: Manjaro Linux 22.0.0 / Windows 10
* Graphics Card: NVIDIA GeForce RTX 2060 SUPER

**Comment by worachate001** [comment]
Update: I tried switching from ShowMySky to Preetham. It works again. So it's probably not about Qt6.

**Comment by gzotti** [comment]
No problem here with W10/Geforce 960M. Also tried --single-buffer: works.

**Comment by gzotti** [comment]
Oops, yes, custom size does not work with ShowMySize. In this case, the screenshot is composed into an extra buffer. @10110111 ?

**Comment by 10110111** [comment]
Yes, I can reproduce. Will have a look.

**Comment by 10110111** [comment]
@worachate001 please check that if you replace `ShowMySky.dll` in the Stellarium folder with the one from [here](https://ci.appveyor.com/project/10110111/calcmysky/builds/44811034) (click the necessary platform and get the artifact from there), this problem gets fixed.

**Comment by worachate001** [comment]
@10110111 In Manjaro with ShowMySky from your repo, the bug has been fixed. By the way, the new atmospheric model is beautiful and looks realistic. Thank you for your hard work.
