### ISSUE TITLE
Weird flicker when centering an object

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#2665]
There appears to be a weird flicker when centering objects. I can create this with Windows 64-bit and MacOS. It appears the whole screen is mirrored, and then, very quickly (a frame or so), return to normal. Small problem, but very noticeable when you see it.

Steps to reproduce:
1. Select any object.
2. Press `Space` (or whatever button you have mapped to center an object)
3. Once the object is centered, the flicker happens.

This is ugly and not worthy of being in the 1.0 release.

**Comment by alex-w** [comment]
Duplicate of #2614

**Comment by alex-w** [comment]
This issue is fixed now, but not published yet. The fix will available for testing in next 2-3 days.

**Comment by Atque** [comment]
Oops, my bad. Let's close this.
