### ISSUE TITLE
New Sky Culture "Andes Septentrionales"

### ISSUE THREAD

**Issue by TaytaAlejandro** [Stellarium/stellarium#267]
Greetings.
After many years we have decoded the four main Andean constellations and are ready to be published, I would greatly appreciate your help.

My regards.

[andes_septentrionales.zip](https://github.com/Stellarium/stellarium/files/2330852/andes_septentrionales.zip)

**Comment by alex-w** [comment]
Seems in this skyculture the Molestina Triangle, Antonio Quinatoa Cross and South Cross are asterisms - is it correct?

The figure of Antonio Quinatoa Cross looks like rhombus - is it correct?

**Comment by TaytaAlejandro** [comment]
Yes.

Regards.

**Comment by alex-w** [comment]
The new sky culture will be available for testing in next weekly build.

**Comment by TaytaAlejandro** [comment]
We are deeply grateful.

Our best wishes to you.

Thanks.
