### ISSUE TITLE
Rearrengement of checkboxes

### ISSUE THREAD

**Issue by t4saha** [Stellarium/stellarium#2671]
### Expected Behavior
Tool tip shows the actual purpose

### Actual Behavior
It shows "label Partition"

### Steps to reproduce
Open View Dialog > Marking Tab > Hover pointer on the text
![view](https://user-images.githubusercontent.com/34002960/191189656-9f55981b-ca71-4e3e-aa4b-a3af84f116e3.png)

### System
* Stellarium version: 1.22.2-68985d0 based on Qt6 [snap]
* Operating system: Ubuntu 22.01
* Graphics Card: N.A.
* Screen type (if applicable): Normal

**Comment by gzotti** [comment]
Note: There are 3 checkboxes with only one permanently visible label, but 3 tooltips. Line, separations (partitions) and "label partitions". For space reasons, the label of the "label partitions" checkbox should present the line name, but the tooltip of course says "label partitions".
