### ISSUE TITLE
Mouse cursor dissappears when using Display pointer trails in Windows 10, 11

### ISSUE THREAD

**Issue by Rvemplar** [Stellarium/stellarium#2675]
Mouse cursor dissappears when using Display pointer trails in Windows 11

### Expected Behaviour
Mouse will show with display pointer trails.
### Actual Behaviour
Mouse arrow will disappear and become invisible, but mouse will still function although no arrow is present
### Steps to reproduce
Enabling of the display pointer trails (max setting) and then starting up stellarium 

### Systems

* Stellarium version: <stellarium-0.22.2-win64>
* Operating system: Edition	Windows 11 Pro
Version	21H2
Installed on	‎8/‎9/‎2022
OS build	22000.978
Experience	Windows Feature Experience Pack 1000.22000.978.0

* Graphics Card: <Nvidia Geforce RTX 3060 ver 31.0.15.1694>
* Screen type (if applicable): Acer Nitro XV282K KVbmiipruzx 28" 4K UHD (3840 x 2160) 144Hz Gaming Monitor

Processor	AMD Ryzen 9 5900X 12-Core Processor               3.70 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/9608454/log.txt)
------------------------------------------------
This issue is also present in Windows 10
Stellarium version: <stellarium-0.22.2-win64>
* Operating system: Edition	Windows 10 Pro
Version	21H2
Installed on	‎5/‎29/‎2020
OS build	19044.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0

* Graphics Card: <Nvidia Geforce GTX 970 ver 31.0.15.1694>
* Screen type (if applicable): ACER Nitro 25XV2Q

Processor	Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.40 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by gzotti** [comment]
One of the oldest FAQ. Mouse pointer disappears when using mouse trail. We cannot do anything about it.

**Comment by impeeza** [comment]
Sorry to necrobump this issue but for future release, I do use the attached Scripts to run stellarium, first turns off the mouse pointer trails and then turn on again once you close stellarium!

[StellariumNoMouseTrails.zip](https://github.com/user-attachments/files/18497408/StellariumNoMouseTrails.zip)
