### ISSUE TITLE
Astronomical calculations dialog is too small for Eclipses tab

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2678]
The Eclipses tab has two tables one under another, and this makes the space too tight for them, see the screenshot below. Would it better to increase the height of the dialog?

Both _View_ and _Configuration_ dialogs are higher, so I think it shouldn't be a problem in principle.

![Screenshot - 220922 - 16:52:18](https://user-images.githubusercontent.com/6376882/191766269-bf114168-ae14-40ec-966d-772ce96ae193.png)

**Comment by 10110111** [comment]
Oh... invisible resizing border that doesn't exist on the top... that's unexpected...

Anyway, maybe the defaults are worth changing?

**Comment by gzotti** [comment]
I think it's good to allow squeezing to such small window, i.e. keep default window sizes small. (Think of netbooks!)  The window size and location is stored for next use, so it's a one-time operation to adapt to your screen size. 

Yes, the top edge is not available for resizing.

**Comment by 10110111** [comment]
How is this invisible resizing frame implemented? I've found the `BarFrame` class that implements the title bar, and it doesn't get single mouse clicks at the very top several pixels, although it does get double clicks there. But still I'm puzzled what is responsible for the invisible resizing frame.

**Comment by gzotti** [comment]
I am afraid this is code from our ancestors, made in Qt4 times. Have you checked the CSS in data/gui?

**Comment by 10110111** [comment]
I've disabled the CSS and the invisible frame is still there.

**Comment by 10110111** [comment]
Oh, I've found it: `CustomProxy` redefines `paintWindowFrame` method to do nothing, hence the transparency.
