### ISSUE TITLE
0.22.2-992d4a7-win64: opening Observing Lists deselects object

### ISSUE THREAD

**Issue by Menno5** [Stellarium/stellarium#2680]
Is the same as [https://github.com/Stellarium/stellarium/issues/1941](url) which is closed but issue is still there. Using the Weekly Snapshot stellarium-1.22.2-992d4a7-win64

I select an object (say M81) but as soon as I open the Observing List, the object gets deselected.
When I select M81 again and then use Edit List, M81 is deselected again.

Expected: M81 stays selected when Opening and/or Editing the Observing List.

**Comment by gzotti** [comment]
This needs a little rework. I am trying my best.

**Comment by Jocelyn1109** [comment]
@gzotti I work on it and I found the problem.

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
