### ISSUE TITLE
No 'Go' button in Search Window Position tab

### ISSUE THREAD

**Issue by Pierreledoc** [Stellarium/stellarium#2681]
### Expected Behaviour
In the Search Window, Position tab, I can enter the Long and Lat but I can see no way to navigate to this position.
The User guide merely states 'The Position tab (Fig. 4.20) provides a convenient way to enter a set of coordinates'
I expect there should be a 'Go' button to trigger the navigation?
### Actual Behaviour
If I hit the scroll arrows on the Lat Long entries the content resets and the sky display slews to the reset value.

### System
* Stellarium version: 0.21.2
* Operating system: Win 10 build 19043.2006
* Graphics Card: Lenovo 320s laptop
* Screen type (if applicable): R
-->

**Comment by gzotti** [comment]
What have you tried so far? Use the mouse wheel to change values, enter coordinates directly and press enter? Which other interaction can be done with the coordinates fields that would not move to these coordinates?

**Comment by 10110111** [comment]
While pressing <kbd>Return</kbd> or <kbd>Tab</kbd> will indeed apply the value typed, a typical inexperienced user won't know to do it. An _Apply_ button would indeed improve UX.

**Comment by gzotti** [comment]
Click in the coordinate line. E.g., [4h 1I7m 23.50s]

Note the location of the cursor, here shown as I.

Now scroll the mouse wheel. The 17 will change. 

Alternatively press up or down arrow. The value changes.

Alternatively press the arrows. Value changes. 

Alternatively mark 17 and type numbers, then press Enter. Value changes. 

Double-click field to highlight all, type `1h23m45.6s`, press Enter. Value changes.

We don't need another button.

**Comment by 10110111** [comment]
I'm not sure where you found the time control, this issue is, as I understand, about the Latitude and Longitude fields that are just spinboxes, see the screenshot:

![Screenshot - 230922 - 17:10:06](https://user-images.githubusercontent.com/6376882/191980210-fc46dfa8-a179-46bc-a875-bba40311ff83.png)

Here, if we type the coordinates, it's obvious to a techie that either pressing <kbd>Return</kbd> or moving focus to another widget will result in a value change signal.

The OP, apparently, isn't as experienced, and the UI, which doesn't rotate the camera "as you type", thus seems to ignore what has been typed (but not "entered"). Thus it's a reasonable question: "how to make it happen?"

> We don't need another button

Yes, "we", the developers, don't. But the users might. The issue is in UX, not in technical sufficiency of the UI.

**Comment by Pierreledoc** [comment]
I can change the values - using any of the techniques listed by gzotti - but that doesn't navigate me to the desired position. The camera position does change as I type, but based on incomplete coordinates. It doesn't change after every keystroke - and will not change following the last entry +Enter or +Tab

Does 45 years in IT count as 'experienced' ? :-)

**Comment by gzotti** [comment]
I used RA/Dec coordinates and don't have decimal degrees interface, therefore the hours/minutes/seconds.

I cannot reproduce the problem on Windows 10 with current master, sorry. It just works. You can enter 67.75 [ENTER] even in DMS mode to set 67° 45' etc. However you must highlight the field contents via double-click before entering the new value.

**Comment by Pierreledoc** [comment]
OK - I got it to work!

Change degrees, minutes, seconds, decimal seconds individually on Lat and Long boxes then tab to exit the Long box - camera slews on focus change from Lat to Long then on tab from Long. There's probably another combination that works but I just need the one! This worked using Ecliptic J2000, I haven't tried the other coordinate types. FYI double-clicking on the degrees value picks up the degree symbol - I think this is a flaw.

Thanks all for your help!

This is a TERRIBLE interface - you need a BUTTON for sure :-)

**Comment by Pierreledoc** [comment]
Thanks for your help gzotti !

**Comment by gzotti** [comment]
Now people will start to ask questions what's the difference between that button or simply pressing ENTER...

**Comment by 10110111** [comment]
If both work as expected, they won't. It's a pretty common UI idiom, see e.g. the KDE file manager:

![a](https://user-images.githubusercontent.com/6376882/193027403-a2a64eff-ce20-4f64-9d34-7c3793e606ca.png)

The only strangeness in the implementation here is that the button is _under_ the items to apply, and it's so large.

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest

**Comment by Pierreledoc** [comment]
Thanks Alex!PierreledocOn 1 Oct 2022 13:31, "Alexander V. Wolf" ***@***.***> wrote:
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
