### ISSUE TITLE
Console for use Stellarium in dome planetarium

### ISSUE THREAD

**Issue by EGPlanetarium** [Stellarium/stellarium#2686]
Please need a console for use Stellarium in dome fisheye Planetarium!

**Comment by gzotti** [comment]
1) The Text User Interface has been the classical non-intrusive planetarium interface.
2) There is the RemoteControl plugin which does most things of the regular GUI and could possibly be expanded for your needs.
3) Else, there are some third-party developments I have seen particular for planetaria. Google helps.

**Comment by gzotti** [comment]
@EGPlanetarium any comments? Else we will close this.

**Comment by EGPlanetarium** [comment]
No comments.
Close It, thank you.
EG Planetarium

Il mar 11 ott 2022, 12:09 Georg Zotti ***@***.***> ha scritto:
