### ISSUE TITLE
Unable to download star catalogs with version 0.18.2 of Stellarium for Windows

### ISSUE THREAD

**Issue by jester38** [Stellarium/stellarium#269]
Hello,

I tried to move from version 0.18.1 to 0.18.2 of Stellarium on two computers running Windows 7 Pro 32-bit.
During the installation process, I have left the check boxes as they are concerning the cleaning of a previous installation. I started Stellarium and tried to load additional star catalogs, but the progress counter stays at %0 and disappears after a while with no additional catalog loaded.
I then switched back to version 0.18.1 and was able to download star catalogs.
Note that I did the A,B,A,B test several times on both computers with the same result.
I have even tried to delete the Stellarium folder C:\users\MyName\AppData\Roaming\Stellarium before installing version 0.18.2 for an even cleaner installation, but it did not help.
So, for now, I stay with version 0.18.1...

Regards.

**Comment by jpd23** [comment]
Hi,
I could not find the release 0.18.2.3.
My solution has been to upload the file **stars_4_1v0_2.cat** 
from https://sourceforge.net/projects/stellarium/files/Extra-data-files/stars4/
and store it in C:\Program Files\Stellarium\stars\default .
It works.
Jean-Pierre

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by jpd23** [comment]
Thank you gzotti.
Sorry, I notice I've written upload instead of download in my previous message.
The beta release is described as "unsafe" by Windows Defender, so I didn't install it yesterday.
Anyway, "when it works, don't fix it", so I keep my solution. 
Regards.
Jean-Pierre

**Comment by gzotti** [comment]
Defender does not like us, also the releases. We would need some registration or certificate. 
https://github.com/Stellarium/stellarium/wiki/FAQ#unsigned-installer-dangerous-to-download-malware

**Comment by gzotti** [comment]
Please see #260. I can no longer reproduce this.

**Comment by gzotti** [comment]
Just tried beta/x64. Works.

**Comment by gzotti** [comment]
@CF20852 I gave a workshop in a "free/open" WiFi area (i.e., no password). One participant with MS Surface could not download star catalogs. Later he wrote it worked at home. Probably this is a network settings issue, not in our control.

**Comment by CF20852** [comment]
Works fine for me in the 32-bit version, but I wasn’t able to get it to work in the 64-bit version.  Tried both versions of OpenSSL.
