### ISSUE TITLE
Wrong size of the map in Location dialog, wrong position of the marker when hiDPI scaling is on

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2693]
### Steps to reproduce

1. Set `QT_SCREEN_SCALE_FACTORS=1.5` environment variable
2. Run Stellarium
3. Open _Location_ dialog

### Behavior observed

1. The map is too small
2. The cursor is far from the place where it should be (even if the map were enlarged)
3. Clicking the map places the marker not under mouse cursor

### Screenshot
![Screenshot - 260922 - 21:15:58](https://user-images.githubusercontent.com/6376882/192351249-65729dc8-63c6-4fed-b40d-69549d5ef4b4.png)

### System
* Stellarium version: v0.22.2-426-g3575721b9b
* Operating system: Linux From Scratch, Qt 6.3.1

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
