### ISSUE TITLE
Is it intended that Oculars panel buttons have no hover effect?

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2698]
The panels at the bottom-left side of the window contain buttons that "glow" when mouse cursor is above them. But the top-right panel, corresponding to _Oculars_ plugin, has buttons that seem disabled by reaction to mouse cursor: they don't glow on hover (although clicking them works fine).

Is it intended, or should it be fixed?

**Comment by alex-w** [comment]
It’s intended behavior

**Comment by gzotti** [comment]
I think it just was not implemented. No hurry, not for 1.0!

**Comment by 10110111** [comment]
Actually, it seems to be a bug. `pxmapGlow` is definitely loaded in `Oculars::init()`, but somehow it becomes null at the point of rendering in `StelButton::updateIcon()`.

I'll take care of this.

**Comment by gzotti** [comment]
If you have fixed it already, we can add it to 1.0 of course. I meant it should not be seen as relevant or urgent for 1.0.

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
