### ISSUE TITLE
cant downlaod additional catalogue up to 15 mag.

### ISSUE THREAD

**Issue by JoeClipphead** [Stellarium/stellarium#270]
Hello,
Windows 10 Pro 64 bit(1803)
Stellarium 18.2 64 bit

I cant download additional catalogues from (i dont know) to the stellarium application.
If i click on the button "Load  catalogue 5 (to 9) nothing happens.

https://1drv.ms/u/s!An3Mko8hoMpG5uUKkzH3ErvK7zbB_g

Pleas help me immidiatly because i have a presentation with 50+ kids during a science week.
And thes kids want to know all, REALLY ALL from the beginnung of astronomy to black holes and hubble.
And the churches have a lot of money to buy a lot of hardware.

And witch stars above 10 mag are worth to observe with a stara-analyser to make next steps in spectroscopy. At the end the will have there own spectralatlas with stars at the end of visibility of a new spectroscope.  so i need these 5-9 caralogues.

Thank you and sorry for my poor english
Rainer

Rainer@Borchmann.de
http://spektroskopie.vdsastro.de/startseite.html

**Comment by iMacSoldier** [comment]
download manually from https://sourceforge.net/projects/stellarium/files/Extra-data-files/
and copy in C:\Users\YOUR ACCOUNT\AppData\Roaming\Stellarium\stars\default

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#openssl-problems-in-the-logfile-missing-hips-surveys-cannot-download-additional-star-catalogs-windows
