### ISSUE TITLE
Missing constellation art in Babylonian Seleucid

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#2704]
I'm not quite sure if this is a bug, or intented use.

The skyculture Babylonian Seleucid has a few image files containing constellation art. However, since the `babylonian_seleucid/CMakeLists.txt` does not contain any patterns for image file extentions, they won't install. Is this intended? If not, maybe this should be fixed before 1.0.

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
