### ISSUE TITLE
Support OpenGL 3.3 Core Profile

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#2707]
This is mostly a demand caused by Apple's lack of supporting an OpenGL 3.3 Compatibility Profile.

The ShowMySky feature which provides the wonderful twilight colors requires OpenGL 3.3. Most computers' OpenGL subsystems nowadays deliver 4.* Compatibility Profiles. Apple traditionally axes compatibility features and as far as we can see provides only OpenGL Core profiles. 

Stellarium still uses some OpenGL functions which are no longer available in a 3.3 Core profile. 

I don't have an Apple computer, so I personally don't care for and cannot develop this, but there are certainly Apple developers out there who are able and willing to do that.

**Describe the solution you'd like**

* Initialisation on Apple computers shall deliver an OpenGL 3 3 core profile at start if possible (easy)
* Stellarium must run completely without graphical errors caused by attempting to run OpenGL functions which have been removed from the 3.3 Core profile. 

On other platforms, existing functionality must not change. OpenGL 2.1 and OpenGL ES 2.0 systems must continue to work. Where OpenGL 3.3 functions are not available, there is no ShowMySky, that's OK.
 
**Describe alternatives you've considered**

Currently there is no ShowMySky on Apple computers.

**Additional context**
Stellarium's ShowMySky is awesome. It would be nice to have this also on the Apple platform!

**Comment by 10110111** [comment]
I'm trying to understand the existing Stellarium code regarding choosing OpenGL context, and it looks like a mess. Questions:

1. Why do we have a separate code path for Qt6?
2. Why do we override the default format in `StelMainView::getDesiredGLFormat()`?
3. What is the point of `--compat33`? Which exactly systems need it?
4. Why is 3.3-compat requested on macOS (which doesn't provide it anyway), while 2.1 on all others including Windows and Linux?

**Comment by gzotti** [comment]
> I'm trying to understand the existing Stellarium code regarding choosing OpenGL context, and it looks like a mess. 

Indeed, here is lots of legacy code. For me it starts with analyzing the way our window is constructed, compared to Qt docs/examples. This may stem from whatever pre-Qt4 developments were used 15 years ago.  The Context trouble was a long story starting IIRC around Qt5.2...5.4, when we had version 0.13.*, we needed 3 different packages for genuine OpenGL, ANGLE and MESA versions. Starting with V0.14.0 we had dynamic OpenGL binding, i.e. one package with command-line switches. The common denominator according to Qt was OpenGL 2.1 OR OpenGL ES2.0. However, "something" beyond 2.1 (but included in all tested GLES2.0 systems) was apparently required in the planet shader, and I never fully understood what it was. Some GPUs (mosty Intels...) were allegedly "2.1", but had graphics bugs.  So I added all this diagnostic debug output and methods. At some later point Qt added blacklists to ban bad GPUs or switch them to ANGLE automatically. 

We asked users to send in logfiles from working and non-working systems to find out more, but response was ... meager. 

One developer from the first team who worked on a Mac complained about all this "nonsense output" and wondered what else we would expect if we request an OpenGL 2.1 context, the output would of course be just that, and why confirm with debugs. This is indeed what Apple does, and I just commented output away from MAC builds. On the Windows platforms (and also Linux), the returned context can be any compatible higher version. Most of the time this means some higher (3.3, 4.0...4.6)  Compatibility profile, and everything works. And the very same graphics code, old-fashioned OpenGL calls and *unversioned* shaders, work on OpenGL ES2.0 systems like Linux SBCs (RaspberryPi, Odroid with Mali GPU), with just a few features missing (e.g. line width). In this respect, ANGLE is also an OpenGL ES2.0 system, and indeed it was not possible with the official Qt5 libraries on Windows to have the decision about OpenGL or GLES at compile time. Meanwhile even Mesa on some Linux systems provides OpenGL or GLES. 

> Questions:
> 
>     1. Why do we have a separate code path for Qt6?

Too blind to find it again. Where was that?
 
>     2. Why do we override the default format in `StelMainView::getDesiredGLFormat()`?

Phew, too long ago. Just try what is the difference? It was just that something (planet moon shadows?) did not work with the minimum. 
 
>     3. What is the point of `--compat33`? Which exactly systems need it?

I think I did that while we developed the Scenery3D plugin as we exceeded 2.1 features. At some point I learned that Macs can in fact provide more than OpenGL 2.1 when "properly" asked. The next level was (according to some Apple dev docs) V3.3 Core profile. They did not write anything about Compatibility profile. Never ever having access to a Mac, I just attempted to provide here a switch which could have been tested on a Mac, but maybe never was. 

With Qt6, graphics becomes diverse again. On Windows, DirectX is preferred, Mac likes Metal, and Vulkan is also supported. Qt docs tell you more about what we *should* do in the future: use Qt's functions, not OpenGL directly. Now, that's a huge lot of code to change... 

I did some experiments earlier this year with manually requesting a 3.2 Core profile from my Geforce. The result looks genuinely weird. I think with "Core" what you get is much stricter, and well, some OpenGL functions are missing and do nothing. But I am not enough OpenGL expert and had no time to have investigated further. Mac developers may be more motivated...

>     4. Why is 3.3-compat requested on macOS (which doesn't provide it anyway), while 2.1 on all others including Windows and Linux?

This was that attempt. The hope was that this "whatever it was" that was above 2.1 and caused some bug reports from Macs would be provided in 3.3 Compat if only we could get Macs to provide it. If Apple does not provide that Compatibility profile, 2.1 is all you get.

**Comment by 10110111** [comment]
> > 1. Why do we have a separate code path for Qt6?
> Too blind to find it again. Where was that?

The Qt6-specific is [here](https://github.com/Stellarium/stellarium/blob/master/src/main.cpp#L188), the general code that overrides it is [here](https://github.com/Stellarium/stellarium/blob/master/src/StelMainView.cpp#L737).

**Comment by gzotti** [comment]
Ah yes. The TODOs imply that I wanted to continue checks on GLES systems "later". My Odroids did not play well, though. The C1 did not like its Ubuntu20 image, and the XU3 also has yet no Ubuntu22. The Raspi4/Ubuntu 22 Mate has Qt6. but I did not check these particularities more thoroughly yet. Unlikely I find enough time until late November. 

The important point here is that QSurfaceFormat::setDefaultFormat(fmt); must be called before the first format is requested, so I pushed this part to this earlier place.

**Comment by 10110111** [comment]
> The important point here is that QSurfaceFormat::setDefaultFormat(fmt); must be called before the first format is requested, so I pushed this part to this earlier place.

What exactly happens if this isn't done?

**Comment by gzotti** [comment]
I think (but please try) it just emits a Qt-internal warning and ignores what it is requested. But this is "TODO" terrain to actually find out the real consequences on all platforms (!). Earlier this year we had the first occurrences of the --angle-mode etc flags being ignored. These changes were maybe related to attempts to fixing these. But as it seems, even if it worked for one release, the command-line switches (and extra start menu links) are again broken.

**Comment by 10110111** [comment]
I'm now converting all client-state-based rendering into VAO & VBO use, as is required for Core profile. Now I'm looking at `Planet::drawSurvey`, and I wonder how I can test that it works.

From the comment I see it's somehow related to HiPS. But some googling didn't tell me what exactly it is. I enabled HiPS in the bottom panel, but didn't notice any change in the sky. How can I check that HiPS is rendered? What should I look for?

**Comment by gzotti** [comment]
The usual HiPS are all-sky surveys from professional institutions. The planet HiPS are hi-res textures hosted on stellarium.org. To see them, go into the HiPS setup (F4/Surveys) and choose Solar System, then select e.g. Mars in the sky and zoom in. You see a somewhat blurry texture. Now enable the survey for Mars: it gets much sharper.

**Comment by gzotti** [comment]
Thank you @10110111 for implementing this!
