### ISSUE TITLE
Stellariumscope website went dark. ASCOM Telescope support soon?

### ISSUE THREAD

**Issue by dts350z** [Stellarium/stellarium#271]
I see the website for Stellariumscope is down. I realize that is not part of this project but just wanted to point out that the need for ASCOM telescope support would be very important if Stellariumscope is no longer being developed or made available.

http://welshdragoncomputing.ca/x/index.php/home/stellariumscope/download-stellariumscope

**Comment by gzotti** [comment]
I think we could accept a working patch if somebody with an ASCOM-only telescope would be so kind to develop it. (But I do not decide about the TelescopeControl plugin.)

**Comment by gzotti** [comment]
Just to note, the website is accessible again.

**Comment by gzotti** [comment]
We only need one entry mentioning the wish for direct ASCOM support. Be it #406.
