### ISSUE TITLE
Icon button for Online Queries is the same as Show Coordinates For Mouse Pointer

### ISSUE THREAD

**Issue by Keatah** [Stellarium/stellarium#2710]
Two buttons have the same icon. One of them matches it's function, the "Show coordinates of the mouse pointer". Makes sense, a pointer and crosshair..

The other, "Show window for Online Queries" isn't a good fit. Seems like it should have a different design or something.

Win10
stellarium-1.22.3-win64.exe
If you need more info I will provide it.

![stellarium-002](https://user-images.githubusercontent.com/7831115/193429184-4bcfe309-063c-4476-b512-36fdb48b863c.png)

**Comment by gzotti** [comment]
Yes I also have seen it. But too late.

**Comment by 10110111** [comment]
It used to look like this:

![bt_OnlineQueries_Off](https://user-images.githubusercontent.com/6376882/193429337-b872ef94-cbb7-4660-9911-eed3c729c45e.png)

The SVG sources, though, don't have the question mark, that's why the regenerated icon lost it.

I wonder though, why it even looked like a pointer touching a coordinate grid, even if with a question mark. Does such an icon make sense?

**Comment by gzotti** [comment]
I admit I am bad with icon design. The crossmark with mouse arrow implies a target, and the question mark a query. In total "what's here". 
I am open for better designs that read "look for online information about that thing here at the mouse cursor"

**Comment by 10110111** [comment]
> I admit I am bad with icon design.

That's OK, me too :D

> In total "what's here".

This sounds convincing enough. I suppose then, I'll just edit the SVG icon to add a question mark, and regenerate the PNGs.

What font did you use for the question mark?

**Comment by gzotti** [comment]
OMG. Whatever I found in Photoshop. This was just something quick... Maybe also @martinber can suggest something better?

**Comment by 10110111** [comment]
Does this look acceptable as a fix?

![a](https://user-images.githubusercontent.com/6376882/193432453-d44f4225-2596-4bd9-8871-90cd6a9a622c.png)

**Comment by martinber** [comment]
I would go fo something like a ["help cursor" icon](https://www.google.com/search?tbm=isch&q=help+cursor+icon&tbs=imgo%3A1)

![image](https://user-images.githubusercontent.com/6921727/193442519-08803290-6606-4ba5-939d-534fae117fe1.png)

For consistency I used the same question mark font as the help window already present. I don't want to use the same crosshair because it would be too similar to "show coordinates of mouse pointer". I will try now to think how to represent a target better

**Comment by gzotti** [comment]
Yes, that's also OK. Is there any standardized icon element to put "web" into the interpretation?

**Comment by 10110111** [comment]
> I will try now to think how to represent a target better

OK, for now I've pushed what I had in [a comment above](https://github.com/Stellarium/stellarium/issues/2710#issuecomment-1264511481). Leaving this issue open for the time when we have a final alternative icon.

**Comment by martinber** [comment]
Which one do you think is more clear?

![image](https://user-images.githubusercontent.com/6921727/193467074-8b340875-a7a1-4bb6-9cec-577d7fecdc18.png)

![image](https://user-images.githubusercontent.com/6921727/193467089-21937263-54d0-451a-92d3-d262f581d518.png)

**Comment by alex-w** [comment]
Left bottom

**Comment by 10110111** [comment]
IMO, the clearest one that shows the intent is the star+pointer+questionMark.

Maybe the star could be replaced with a Saturn-like planet, because the star seems too overloaded a concept, especially a five-pointed one.

**Comment by gzotti** [comment]
I agree, left bottom. It can be read as "search worldwide". Right center is what I had in my mind earlier today, "what does the www say about this". But it's characters, so left bottom is better. 
Replacing the star by Saturn is not good IMHO as it implies "planet". So far almost all addressed sites (except Wikipedia) look for stars.

**Comment by 10110111** [comment]
OK, the bottom-left one reflects the plugin name, Online Queries, without any hint at mouse-pointing, so maybe it's the best then.

**Comment by martinber** [comment]
Tried some more and I think both top ones are good enough. The only problem with the top-left is that it is similar to equatorial and azimuth grids 

![image](https://user-images.githubusercontent.com/6921727/193467578-8c31419b-ef18-4a1b-bfee-37a62a972205.png)

**Comment by Keatah** [comment]
Love all the active development happening here.
