### ISSUE TITLE
cannot add new mount to telescope-extension

### ISSUE THREAD

**Issue by schwiha** [Stellarium/stellarium#2713]
### Expected Behaviour
Adding a new telescope (mount) to stellarium telescope plugin can be finished by clicking "OK" (previously made configuration is stored - telescope configuration window is closed). 

### Actual Behaviour
"OK" can be clicked but has no function - config is not stored and dialog can only be exited by cancel (or "X" in upper corner)

### Steps to reproduce
Fresh installation of: Windows, .net 3.5, ASCOM 6.6, iOptron / or EQMOD for Skywatcher (both same result regarding "actual behavior"), stellarium 1.22.3

actual steps:
open configuration window [F2] -> goto TAB "Plugins" -> choose "Telescope control" -> tic load at startup and restart stellarium
open configuration window [F2] -> goto TAB "Plugins" -> choose "Telescope control" -> configure -> add new telescope (list of telescopes is empty = new installation) -> choose your config (simulation or ASCOM had been tried) -> press "OK" (but this has no function and no effect - window is still open, config not saved)

Same steps tested after deinstallation of stellarium 1.22.3 win64 and reinstall of version 0.22.2 win64 and everything works as expected - new telescope (mount) is recognized and can be slewed with stellarium 0.22.2

### System
* Stellarium version: 1.22.3 win64
* Operating system: Windows 10

**Comment by gzotti** [comment]
Can you please also test with V1.0 alternative package 0.22.3?

Or @alex-w do you see already what happened? Obsolete signal again?

**Comment by alex-w** [comment]
No, but this is looks like bug. The log may help us.

**Comment by schwiha** [comment]
I have added config.ini (renamed to .txt for being able to upload) and log.txt (is there a possibility to increase the log level?)
[log.txt](https://github.com/Stellarium/stellarium/files/9693064/log.txt)
[config.txt](https://github.com/Stellarium/stellarium/files/9693066/config.txt)

**Comment by schwiha** [comment]
Same behavior for 0.22.3 (alias 1.0) (added log file log.txt as log_22_3.txt)
[log_22_3.txt](https://github.com/Stellarium/stellarium/files/9693097/log_22_3.txt)

**Comment by gzotti** [comment]
Thanks. Yes, a last-minute correction went wrong. :-(

**Comment by gzotti** [comment]
I hope this fixed it. (Cannot test!!)

**Comment by itsgps** [comment]
Heeeloooo All - we came across this problem only last night and upon downloading Latest version.  Has it been updated since?
Issue we initially found with one User was Not able to Add a Scope.  We found that one way to get around that was I shared my telescopes.json file.  That worked as we both have EQMod for mounts (EQ6 for me and HEQ5 for him.)

However subsequently although Stellarium would open as soon as you clicked on Telescope Control Stellarium would crash either quickly or a Slow CTRL+ALT+DEL Death.

I didn't seem to have those problems my end, and tonight when setting up I have found the Exact same problems, and realised I had Upgraded to the same version he had, and now My same config crashing.  I uninstalled that version and found a Version I had in the Downloads folder from 2021.  Installed - everything back to 100% working.

So - Presumably the whole Telescope Control Plugin itself was somewhat faulty - Version 0.42 I think it shows - has that Now been updated? or Stellarium itself?
Working version here is 0.21.1 - Broken version appeared to be 1.22.3-win64

**Comment by gzotti** [comment]
If you can build Stellarium yourself, you may be the first to test if the assumed fix worked.

**Comment by itsgps** [comment]
Will get onto it and see how I go. Just got to prep my IDE, it's been a while...!

**Comment by gzotti** [comment]
Does not work yet. Needs larger update.

**Comment by SteveStuff** [comment]
I also have the same issue with the plugin for "Remote Control" plugin.  
I configure what I want for "Remote Control" plugin but when I select "OK" to save this config. for this plugin, nothing is saved

**Comment by gzotti** [comment]
Cannot confirm either. At least "Enable Server" and "Enable automatically on startup" and allow CORS are stored and work. What else did you try?

**Comment by charlesbarros** [comment]
I can confirm that it's working in the last weekly snapshot.

**Comment by stooge75** [comment]
Still had same issue last night

**Comment by avteam53** [comment]
Downloaded current release version 1.22.3 tonight and it still has the same problem.   The  "OK" button doesn't do anything.  Only the Cancel button or the x at the top close it and the only thing saved is the ASCOM Settings section.

**Comment by gzotti** [comment]
If you download the version with the problem again, you of course will see the problem again. "Weekly snapshot" is the message here.

**Comment by stooge75** [comment]
What exactly is a weekly snapshot

**Comment by itsgps** [comment]
@stooge75 
The link is here
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

This is referenced in the "Building Stellarium" page here:

https://github.com/Stellarium/stellarium/blob/master/BUILDING.md

**Comment by itsgps** [comment]
Gzoti - Sorry I haven't had any chance for Builds or testing...At this point in time in Victoria (Aus) we haven't had anything other than Mass flooding for weeks - so not a priority...But going away this weekend - might test Snapshot.

**Comment by gzotti** [comment]
Uh, sorry to read. This gives "down under" a new meaning, right? :-o

**Comment by avteam53** [comment]
Thanks Gzoti.  I downloaded the Snapshot and it appears to be working correctly.

**Comment by stooge75** [comment]
[log.txt](https://github.com/Stellarium/stellarium/files/9904144/log.txt)
im still crashing

**Comment by alex-w** [comment]
> [log.txt](https://github.com/Stellarium/stellarium/files/9904144/log.txt) im still crashing

Sorry - you can add the mount, but it crashes at connect?

**Comment by stooge75** [comment]
Sorry Alex my keyboard batteries are failing. The telescope control thing is fixed but it now crashes just after I open stellarium. How do I add a log?

**Comment by stooge75** [comment]
I get a runtime error subscript out of range,when I try to click on configuration spanner on the left,it clicks on the eqmod that suddenly appears then it crashes. Sometimes it just freezes and I have to use task manager to end it.

**Comment by alex-w** [comment]
> Sorry Alex my keyboard batteries are failing. The telescope control thing is fixed but it now crashes just after I open stellarium. How do I add a log?

Via webinterface for example. Do you use Stellarium + ASCOM/eq6 only or something else in addinition?

**Comment by stooge75** [comment]
In general you mean? Yes APT or Nina and phd2. Or do you mean just before it crashes just now? No nothing else started,just eqmod/ascom and stellarium

**Comment by alex-w** [comment]
> I get a runtime error subscript out of range,when I try to click on configuration spanner on the left,it clicks on the eqmod that suddenly appears then it crashes. Sometimes it just freezes and I have to use task manager to end it.

Please fill the separate bug report with detailed explanation of problem (with steps to reproduce) and logs. If you are using some additional software via ASCOM please add note about it too.

**Comment by alex-w** [comment]
> In general you mean? Yes APT or Nina and phd2. Or do you mean just before it crashes just now? No nothing else started,just eqmod/ascom and stellarium

Mmmm... Stellarium is crashes when you using ASCOM for the mount only (other software are not started)?

**Comment by stooge75** [comment]
Not crashing when I use ascom. You asked what else I’m using. I just said I use eqmod/ASCOM obviously because stellarium starts them when it opens.
Just after stellarium opens,and I goto click on spanner on left,it crashes after saying runtime error subscript out of range.
I looked at the last log and at the very end it says 
Telescope control) loaded successfully 1 telescopes 
Dubious result: landscape “Guereins “ not calibrated. Opacity test represents mathematical horizon only.
Initialising planets GL shaders….
