### ISSUE TITLE
Window Resizing WIN 11

### ISSUE THREAD

**Issue by pjglad** [Stellarium/stellarium#2715]
Stellarium 1.0 does not remember resizing window on WIN 11. When I relaunch it does not remember window resize. However, it remembers window resizing on MacOS.

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Please share log from Stellarium

**Comment by pjglad** [comment]
2022-10-02T11:20:25

Operating System: Windows 11 Version 2009

Compiled using MSVC++ 16.10, 16.11 (Visual Studio 2019)

Qt runtime version: 6.3.1

Qt compilation version: 6.3.1

Addressing mode: 64-bit

Total physical memory: 16183 MB

Available physical memory: 9681 MB

Physical memory in use: 40%

Processor speed: 2803 MHz

Processor name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

Processor speed: 2803 MHz

Processor name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

Processor speed: 2803 MHz

Processor name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

Processor speed: 2803 MHz

Processor name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

Processor speed: 2803 MHz

Processor name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

Processor speed: 2803 MHz

Processor name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

Processor speed: 2803 MHz

Processor name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

Processor speed: 2803 MHz

Processor name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

C:\Program Files\Stellarium\stellarium.exe -platform windows:altgr 

 ------------------------------------------------------------

[ This is Stellarium 1.0 (v1.22.3) - https://stellarium.org/ ]

[ Copyright (C) 2000-2022 Stellarium Developers ]

 ------------------------------------------------------------

Writing log file to: "C:\\Users\\pjglad\\AppData\\Roaming\\Stellarium\\log.txt"

File search paths:

 0 . "C:\\Users\\pjglad\\AppData\\Roaming\\Stellarium"

 1 . "."

Config file is: "C:\\Users\\pjglad\\AppData\\Roaming\\Stellarium\\config.ini"

Default surface format: QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QColorSpace(), profile QSurfaceFormat::NoProfile)

Desired surface format: QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QColorSpace(), profile QSurfaceFormat::NoProfile)

setDefaultFormat

Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.

StelGLWidget constructor

StelGraphicsScene constructor

initializeGL

OpenGL supported version: "4.6.0 - Build 30.0.100.9836"

Current Format: QSurfaceFormat(version 4.6, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QColorSpace(), profile QSurfaceFormat::CompatibilityProfile)

StelMainView::init

Detected: OpenGL "4.6"

Driver version string: "4.6.0 - Build 30.0.100.9836"

GL vendor is "Intel"

GL renderer is "Intel(R) Iris(R) Xe Graphics"

GL Shading Language version is "4.60 - Build 30.0.100.9836"

GLSL Version Number detected: 4.6

GLSL version is fine, we should not see a graphics problem.

Detected a high resolution device! Device pixel ratio: 1.5

Sky language is "en_US"

Planetary features language is "en_US"

Application language is "en_US"

Scripts language is "en_US"

Cache directory is: "C:\\Users\\pjglad\\AppData\\Local\\stellarium\\stellarium\\cache"

Loaded 252 countries

Loaded 193 regions

Loading Solar System data (1: planets and moons) ...

Loading from : "./data/ssystem_major.ini"

SolarSystem has 83 entries.

Loaded 83 Solar System bodies

Loading Solar System data (2: minor bodies)...

Loading from : "C:\\Users\\pjglad\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"

SolarSystem has 190 entries.

Loaded 107 Solar System bodies

File ssystem_minor.ini is loaded successfully...

Loading nomenclature for Solar system bodies ...

Loaded 15833 / 15835 items of planetary surface nomenclature

WARNING - These planets to assign nomenclature items were not found: "Dactyl"

Loading star data ...

"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"

"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"

"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"

"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"

Finished loading star catalogue data, max_geodesic_level: 3

Loading scientific star names from ".\\stars\\default\\name.fab"

Loaded 4942 / 4942 scientific star names

Loading scientific star extra names from ".\\stars\\default\\extra_name.fab"

Loaded 26200 / 26200 scientific star extra names

Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"

Loaded 6862 / 6862 variable stars

Loading double stars from ".\\stars\\default\\wds_hip_part.dat"

Loaded 22992 / 22992 double stars

Loading cross-identification data from ".\\stars\\default\\cross-id.dat"

Loaded 108378 / 108378 cross-identification data records for stars

Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"

Loaded 117703 / 117703 parallax error data records for stars

Loading proper motion data from ".\\stars\\default\\hip_pm.dat"

Loaded 117955 / 117955 proper motion data records for stars

navigation/preset_sky_time is a double - treating as jday: "2451514.25001"

Loading DSO data ...

[...] "Stellarium DSO Catalog, version 3.17 (standard edition)"

Loaded 94663 DSO records

Loading DSO outline data ...

Loaded 98 DSO outline records successfully

LandscapeMgr: initialized Cache for 100 MB.

Loading star names from ".\\skycultures\\western\\star_names.fab"

Loaded 1102 / 1102 common star names

Loading DSO name data ...

Loaded 1212 / 1236 DSO name records successfully

WARNING - No position data for 24 objects: "NGC 4173, PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1000714, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124"

Loaded 88 / 88 constellation records successfully for culture "western"

Loaded 85 / 85 constellation art records successfully for culture "western"

Loaded 88 / 88 constellation names

Loading constellation boundary data ... 

Loaded 782 constellation boundary segments

Error in Asterism "TA6" : can't find star with coordinates 2.14697 / 8.55097

ERROR reading asterism lines record at line 88 for culture "western"

Loaded 83 / 84 asterism records successfully for culture "western"

WARNING - asterism abbreviation "TA6" not found when loading asterism names

Loaded 73 / 74 asterism names

stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs

stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)

Initializing basic GL shaders... 

Creating GUI ...

Loaded plugin "Exoplanets"

[Exoplanets] Version of the format of the catalog: 1

[Exoplanets] loading catalog file: "C:\\Users\\pjglad\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"

Loaded plugin "MeteorShowers"

[MeteorShowersMgr] Loading catalog file: "C:\\Users\\pjglad\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\MeteorShowers.json"

[MeteorShowersMgr] Version of the format of the catalog: 2

Loaded plugin "Novae"

[Novae] version of the catalog: 1

[Novae] loading catalog file: "C:\\Users\\pjglad\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"

Loaded plugin "Oculars"

Oculars::validateAndLoadIniFile() ocular.ini exists at: "C:\\Users\\pjglad\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...

Oculars::validateAndLoadIniFile() found existing ini file version 3.1

Loaded plugin "Satellites"

[Satellites] loading catalogue file: "C:\\Users\\pjglad\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"

Satellite has invalid orbit: "BINAR-1" "49272"

Loaded plugin "SolarSystemEditor"

Using the ssystem_minor.ini file that already exists in the user directory...

qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile

 OpenType support missing for "Verdana", script 11

 OpenType support missing for "Arial", script 11

 OpenType support missing for "MS UI Gothic", script 11

 OpenType support missing for "SimSun", script 11

 OpenType support missing for "Segoe UI Emoji", script 11

 OpenType support missing for "Segoe UI Symbol", script 11





    On Sunday, October 2, 2022 at 11:12:54 AM PDT, Alexander V. Wolf ***@***.***> wrote:  
 
 


Please share log from Stellarium

**Comment by Menno5** [comment]
On Windows 10 21H2 it also does not remember.
Steps to reproduce: open Stellarium, change the window size, close Stellarium, open Stellarium again, Window is now again screen filling but the maximize window button in the upper right corner is not engaged.
[log.zip](https://github.com/Stellarium/stellarium/files/9696205/log.zip)

**Comment by gzotti** [comment]
Have you stored your configuration after the window resize?

**Comment by gzotti** [comment]
Yes. I'd prefer to have immediate storage of settings too, but I am not alone...

**Comment by Menno5** [comment]
This was not my bug report, I just did test it. It's closed but I don't know if the OP has the same since he's on Win 11 and I am on Win 10?

**Comment by gzotti** [comment]
Ah yes, sorry. @pjglad please test if storing configuration solves this.

**Comment by pjglad** [comment]
Problem resolved. Thanks!!
