### ISSUE TITLE
LDN and SN objects cannot be selected by mouse click

### ISSUE THREAD

**Issue by wetzelmd** [Stellarium/stellarium#2716]
V 1.0 on Mac M1 silicon, latest MacOS release (Monterey 12.6):

I cannot select LDN objects on the screen with a mouse click.  Same problem seems to occur for SN objects as well.

Mark Wetzel

**Comment by alex-w** [comment]
Hi!

пн, 3 окт. 2022 г. в 11:13, wetzelmd ***@***.***>:

> V 1.0 on Mac M1 silicon, latest MacOS release (Monterey 12.6):
>
> I cannot select LDN objects on the screen with a mouse click. Same problem
> seems to occur for SN objects as well.
>
Did you enable the magnitude limit option in the DSO tab?

-- 
With best regards, Alexander

**Comment by gzotti** [comment]
Of course the respective catalogs must be enabled too.

**Comment by alex-w** [comment]
I cannot reproduce the issue

**Comment by wetzelmd** [comment]
Yes, catalogs are enabled. Previous version works without issues.

Mark

**Comment by wetzelmd** [comment]
Alexander,

Thank you for your prompt reply.

I will check DSO mag limit later.  It has always been enabled with limit set to 17.5.  No issues with 0.22 versions.

Mark

**Comment by alex-w** [comment]
Hello @wetzelmd!

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by alex-w** [comment]
Probably related to #2701

**Comment by wetzelmd** [comment]
Thank you for looking into this.  On my M1 MacBook Pro, latest MacOS, LDN’s can now be set;ected.  However, many Sharpless, PK, PN and some NGC object, and all SNR and LBN object I tested cannot be selected.

Mark
