### ISSUE TITLE
Solar disk lacks limb darkening

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2719]
### Expected Behaviour

Zooming into the Sun should show a solar disk that has smooth reduction of brightness from the center to the rim. Here's a photo of the Sun I took in real life through a solar filter:

![sun-photo](https://user-images.githubusercontent.com/6376882/193814480-116bb4ae-68da-441f-8e42-c82e2421ed9b.png)

The [theoretical brightness profile](https://en.wikipedia.org/wiki/Limb_darkening#Calculation_of_limb_darkening) is obviously not flat:

![brightness](https://user-images.githubusercontent.com/6376882/193817407-4404930b-edd4-4f2d-99d6-3118289a5d7d.png)

### Actual Behaviour

The solar disk is flat (if we disregard the grain texture and the irrelevant "halo" texture), and there's a strange bright rim. Here's a screenshot:

![sun](https://user-images.githubusercontent.com/6376882/193815128-df520d7e-965f-4b0e-9d4c-9f2dfab3c8dc.png)

If we take the RGB profile from the screenshot (~150px away from the center to avoid the "halo"), we'll see this:

![profile](https://user-images.githubusercontent.com/6376882/193815629-3656c98c-548b-427e-920b-09939441881a.png)

Both the bright rim and the flat interior are obvious here.

### Steps to reproduce

1. Select the Sun
2. Center on selected object <kbd>Space</kbd>
3. Disable atmosphere <kbd>A</kbd>
4. Zoom in so that the solar disk fills almost the whole screen.

### System
* Stellarium version: v1.0-13-g6bffbc7c0a
* Operating system: Ubuntu, Windows
* Graphics Card: NVIDIA GeForce GTX 750Ti

**Comment by gzotti** [comment]
Indeed, limb darkening should be easy to add with normal vector consideration. The bright rim may even be an artifact of the corona texture painted after the sun (?) and a slight mismatch. In this case, of course invert drawing order. About Solar Corona, there is another issue about it not being affected by refraction. This would need a different approach to map the Corona into the sky.

**Comment by 10110111** [comment]
> The bright rim may even be an artifact of the corona texture painted after the sun (?)

Yes, it appears to be. I noticed that we do have an option `landscape/early_solar_halo`, which defaults to `false` and influences the corona too. Why? When is it useful? I think it should be true unconditionally.

**Comment by gzotti** [comment]
Cannot say. There were some changes in 2015/16 when I prepared using Stellarium in an exhibition. "false" should then be the old behaviour. Some effects look different, and I was probably not convinced if it was really better in all settings. E.g., check halo with a rising sun.

**Comment by 10110111** [comment]
> E.g., check halo with a rising sun.

Didn't notice any bad effects. What should be wrong?

**Comment by 10110111** [comment]
BTW, the corona is currently controlled by `viewing/flag_draw_sun_halo`. But the halo is supposed to be an optical effect of the observer, not an astrophysical or atmospheric effect. Should the corona really be affected by this option?

**Comment by gzotti** [comment]
I don't think so. But I always have both on. Cannot say when this was probably joined. Somebody wanted the Corona (which was originally only visible during TSE) whenever atmosphere was off. Maybe this influenced the latest changes here.

**Comment by 10110111** [comment]
OK, I think I'll move the corona drawing out and place it before the sphere, which is the only sensible order to use.
