### ISSUE TITLE
Main toolbar missing on load

### ISSUE THREAD

**Issue by Pierreledoc** [Stellarium/stellarium#2721]
### Expected Behaviour
On loading the program the main toolbar top line with date and time etc should be visible. Mousing over the bottom of the screen should display the main toolbar controls.
### Actual Behaviour
On loading the program the main toolbar top line is missing and mousing over the bottom of the screen has no effect. The side toolbar works as before when mousing over the bottom left corner. Pressing the maximize button causes the main toolbar to display and function normally. Pressing restore down causes the main toolbar to disappear. However, reducing the screen size in this state causes the main toolbar to re-appear, after which toggling between maximized and reduced modes retains the toolbar display.

### System
* Stellarium version: <stellarium-1.22.3-win64.exe>
* Operating system: <Windows 10 Home Build 19043.2006>
* Graphics Card: <Lenovo 320S laptop native>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by Pierreledoc** [comment]
Adding screen resolution - 1920x1080

**Comment by 10110111** [comment]
> However, reducing the screen size in this state causes the main toolbar to re-appear

Does it appear suddenly, or does it look as if the toolbar is ejected from the bottom?

> Screen type (if applicable): Resolution, HighDPI, scaling
> Adding screen resolution - 1920x1080

What about high-DPI scaling? Your laptop screen has 165 DPI, do you use any scaling?

**Comment by Pierreledoc** [comment]
Not easy to answer your question as the 'reduced' display is at the full screen size so I can't grab a corner. I can only grab the screen title bar to reduce, at which time the tool bar is there, but I can't tell if it popped up or slid up.
No special scaling - standard setting.
Boy, you guys are quick :-)

**Comment by 10110111** [comment]
To clarify, does Stellarium start in a windowed mode? Do you see the Windows taskbar in this mode? This all sounds as if the window is higher than the screen, which is why the bottom part of it is not visible.

**Comment by alex-w** [comment]
Please share log from Stellarium

**Comment by Pierreledoc** [comment]
It starts up full screen with Windows taskbar at the bottom. Maximize/Restore Down button shows 'Maximize'.

**Comment by Pierreledoc** [comment]
This log is just initial start-up

2022-10-04T18:29:09
Operating System: Windows 10 Version 2009
Compiled using MSVC++ 16.10, 16.11 (Visual Studio 2019)
Qt runtime version: 6.3.1
Qt compilation version: 6.3.1
Addressing mode: 64-bit
Total physical memory: 8058 MB
Available physical memory: 4118 MB
Physical memory in use: 48%
Processor speed: 2904 MHz
Processor name: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Processor speed: 2904 MHz
Processor name: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Processor speed: 2904 MHz
Processor name: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Processor speed: 2904 MHz
Processor name: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
C:\Program Files\Stellarium\stellarium.exe -platform windows:altgr 
 ------------------------------------------------------------
[ This is Stellarium 1.0 (v1.22.3) - https://stellarium.org/ ]
[ Copyright (C) 2000-2022 Stellarium Developers              ]
 ------------------------------------------------------------
Writing log file to: "C:\\Users\\prjdo\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\prjdo\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\prjdo\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
setDefaultFormat
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.5.0 - Build 23.20.16.4973"
Current Format:  QSurfaceFormat(version 4.5, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::CompatibilityProfile)
StelMainView::init
Detected: OpenGL "4.5"
Driver version string: "4.5.0 - Build 23.20.16.4973"
GL vendor is "Intel"
GL renderer is "Intel(R) HD Graphics 620"
GL Shading Language version is "4.50 - Build 23.20.16.4973"
GLSL Version Number detected:  4.5
GLSL version is fine, we should not see a graphics problem.
Detected a high resolution device! Device pixel ratio: 1.25
Sky language is  "en_GB"
Planetary features language is  "en_GB"
Application language is  "en_GB"
Scripts language is  "en_GB"
Cache directory is:  "C:\\Users\\prjdo\\AppData\\Local\\stellarium\\stellarium\\cache"
Loaded 252 countries
Loaded 193 regions
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\prjdo\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
SolarSystem has  190 entries.
Loaded 107 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15833 / 15835 items of planetary surface nomenclature
WARNING - These planets to assign nomenclature items were not found: "Dactyl"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4942 / 4942 scientific star names
Loading scientific star extra names from ".\\stars\\default\\extra_name.fab"
Loaded 26200 / 26200 scientific star extra names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 22992 / 22992 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108378 / 108378 cross-identification data records for stars
Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
Loading proper motion data from ".\\stars\\default\\hip_pm.dat"
Loaded 117955 / 117955 proper motion data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.17 (standard edition)"
Loaded 94663 DSO records
Loading DSO outline data ...
Loaded 98 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 1102 / 1102 common star names
Loading DSO name data ...
Loaded 1212 / 1236 DSO name records successfully
WARNING - No position data for 24 objects: "NGC 4173, PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1000714, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "western"
Loaded 83 / 84 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 73 / 74 asterism names
stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\prjdo\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\prjdo\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\MeteorShowers.json"
[MeteorShowersMgr] Version of the format of the catalog: 2
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\prjdo\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at:  "C:\\Users\\prjdo\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Loaded plugin "Satellites"
[Satellites] loading catalogue file: "C:\\Users\\prjdo\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Loaded plugin "TelescopeControl"
[TelescopeControl] Only embedded telescope servers are available.
[TelescopeControl] Adding device model: "Meade AutoStar compatible" "Any telescope or telescope mount compatible with Meade's AutoStar controller." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Meade LX200 (compatible)" "Any telescope or telescope mount compatible with Meade LX200." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Meade ETX70 (#494 Autostar, #506 CCS)" "Meade's ETX70 with the #494 Autostar controller and the #506 Connector Cable Set." "TelescopeServerLx200" 1500000
[TelescopeControl] Adding device model: "Losmandy G-11" "Losmandy's G-11 telescope mount." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Wildcard Innovations Argo Navis (Meade mode)" "Wildcard Innovations' Argo Navis DTC in Meade LX200 emulation mode." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Celestron NexStar (compatible)" "Any telescope or telescope mount compatible with Celestron NexStar." "TelescopeServerNexStar" 500000
[TelescopeControl] Adding device model: "Sky-Watcher SynScan (version 3 or later)" "Any Sky-Watcher mount that uses version 3 or later of the SynScan hand controller." "TelescopeServerNexStar" 500000
[TelescopeControl] Adding device model: "Sky-Watcher SynScan AZ GOTO" "The Sky-Watcher SynScan AZ GOTO mount used in a number of telescope models." "TelescopeServerNexStar" 500000
[TelescopeControl] loadTelescopes(): Deleted node unrecogised as slot: "version"
[TelescopeControl] Loaded successfully 1 telescopes.
  OpenType support missing for "Verdana", script 11
  OpenType support missing for "Arial", script 11
  OpenType support missing for "MS UI Gothic", script 11
  OpenType support missing for "SimSun", script 11
  OpenType support missing for "Segoe UI Emoji", script 11
  OpenType support missing for "Segoe UI Symbol", script 11

**Comment by 10110111** [comment]
So this is not actually fullscreen mode. You have a window that covers the full screen. Fullscreen mode is if you press <kbd>F11</kbd>.

Anyway, to fix the problem with the oversized window, you can reduce its size it by dragging from the top edge, and then in the _Configuration_ dialog press _Save settings_ button.

**Comment by Pierreledoc** [comment]
That works ... thanks!
But I assume it should open full screen by default?

**Comment by 10110111** [comment]
Switch to full screen via <kbd>F11</kbd> and save settings.
On my machines already starts fullscreen by default. Apparently, you had previously saved settings in the windowed mode.

**Comment by Pierreledoc** [comment]
OK - thanks again!
