### ISSUE TITLE
Build issue with 1.0

### ISSUE THREAD

**Issue by limburgher** [Stellarium/stellarium#2730]
### Expected Behaviour
Stellarium 1.0 compiles on Fedfora Rawhide (38)

I'm the package maintainer for Fedora.

### Actual Behaviour

Build fails, see attached log

### Steps to reproduce
From RPM Spec:
BuildRequires:  make
BuildRequires:  desktop-file-utils
BuildRequires:  mesa-libGLU-devel
BuildRequires:  ImageMagick
BuildRequires:  cmake
BuildRequires:  qt6-qtbase-devel
BuildRequires:  qt6-qtdeclarative-devel
BuildRequires:  qt6-qtlocation-devel
BuildRequires:  qt6-qttools-devel
BuildRequires:  qt6-qtserialport-devel
BuildRequires:  qt6-qtmultimedia-devel
BuildRequires:  qt6-qtcharts-devel
BuildRequires:  qt6-qtbase-private-devel
BuildRequires:  gettext-devel
BuildRequires:  boost-devel
BuildRequires:  glib2-devel
BuildRequires:  perl-podlators
BuildRequires:  libappstream-glib
BuildRequires:  CalcMySky-devel
BuildRequires:  libindi-devel
BuildRequires:  QXlsx-devel
BuildRequires:  libnova-devel

export CFLAGS="$RPM_OPT_FLAGS -fPIC"
export CXXFLAGS="$RPM_OPT_FLAGS -fPIC"
%{cmake} -DCMAKE_BUILD_TYPE=Release -DQT6_LIBS=%{_libdir}/qt6 -DCPM_USE_LOCAL_PACKAGES=yes
make VERBOSE=1 %{?_smp_mflags}

### System
* Stellarium version: 1.0 source tarball
* Operating system: Fedora Linux x86_64
* Graphics Card: N/A
* Screen type (if applicable): N/A

### Logfile 
[build.log](https://github.com/Stellarium/stellarium/files/9735938/build.log)

**Comment by alex-w** [comment]
Please apply this patch https://github.com/qtexcel/QXlsx/commit/8e83402db866ae7a67582da28aa68c83545f13c8

**Comment by limburgher** [comment]
Worked like a charm, thank you!
