### ISSUE TITLE
Moon 16k texture

### ISSUE THREAD

**Issue by OAStubby** [Stellarium/stellarium#2731]
[http://www.skytechx.eu/download/?file=moon16k.png](url)

With version 1.22.3 the Moon is transparent, with version 0.22.3 is rendered correctly.

System
* Stellarium version: 1.22.3/0.22.3
* Operating system: Windows 10 Enterprise LTSC 2021
* Graphics Card: Intel UHD 750 - Driver 30.0.101.1273
* Screen type (if applicable): 1920x1080

**Comment by alex-w** [comment]
Please share log from version 1.22.3

**Comment by OAStubby** [comment]
Log and screenshot for version 1.23.2
[log.txt](https://github.com/Stellarium/stellarium/files/9736419/log.txt)
![stellarium-001](https://user-images.githubusercontent.com/37912680/194626758-448e8a64-b6ff-4666-9a48-40121fd51a83.png)

**Comment by gzotti** [comment]
From the logfile:

`qt.gui.imageio: QImageIOHandler: Rejecting image as it exceeds the current allocation limit of 128 megabytes
`
This image is just too large...

**Comment by gzotti** [comment]
To render hi-res lunar surface, enable it in the HiPS surveys.

**Comment by 10110111** [comment]
To increase allocation limit you can set `QT_IMAGEIO_MAXALLOC` environment variable to a number of megabytes (default in Qt6 is 128). Qt5 seems to not have such a limit.

**Comment by OAStubby** [comment]
@10110111 Thanks for the suggestion, it works perfectly.
