### ISSUE TITLE
Installing Win64 v1.22.3 on Windows 10 Pro 21H2 fails: Incompatible Windows version (because must run as admin)

### ISSUE THREAD

**Issue by LigH-de** [Stellarium/stellarium#2735]
### Expected Behaviour

Stellarium installs.

### Actual Behaviour

> This program does not support the version of Windows your computer is running.

### Steps to reproduce

Run setup as normal user.

### System
* Stellarium version: stellarium-1.22.3-win64.exe
* Operating system: Windows 10 Pro 21H2
* Graphics Card: Nvidia 1660 Super (v517.48)
* Screen type (if applicable): 1920x1200x32bpp

### Logfile 
 n/a

Apparently the installation continues when I run the installer **as Administrator**; you should possibly mention this requirement in a very prominent location on your website, or try to display a more specific error message in the installer.

**Comment by 10110111** [comment]
> This program does not support the version of Windows your computer is running.

This is a very strange error in such circumstances. I suppose it's a bug in the installer, which apparently detects OS version wrongly when run as a normal user.

**Comment by gzotti** [comment]
Practically every installer since WinXP requires admin privileges before it starts unpacking and writing files. The program itself, once installed, does not need admin privileges. This is perfectly normal behaviour.

**Comment by 10110111** [comment]
While the inability to install without admin privileges is normal, the error message is misleading.

**Comment by LigH-de** [comment]
Many installers are able to request an escalation when they need administrative rights.

**Comment by alex-w** [comment]
I can add `PrivilegesRequired = admin` in [setup] section of installer, but I can’t test the behavior

**Comment by gzotti** [comment]
The installer behaves completely normal on the ~5 Win10 systems in my reach. If run as user, there is the "<Ding>... this needs admin privileges to install ..." (sorry, different words of course). You don't have to "run as admin" from the beginning. 

If you really see the message "This program does not support the version of Windows your computer is running." the error is something else. I would have expected about 10.000 complaints so far (including my own) if this was regular occurrence.

**Comment by alex-w** [comment]
Paranoic settings of UAC?

**Comment by LigH-de** [comment]
Would be easier to discover if I was able to let the installer write a verbose protocol, but that may require a debug build of the installer.

I am not aware of any overly protective options in my system (rather the opposite, Defender can be quite annoying in cases of bundled installers I can handle myself). Most other installers simply work or request an escalation.

**Comment by alex-w** [comment]
I've tried install Windows 10 into VirtualBox today and checked working Stellarium installer here - no problem, all work as expected.

**Comment by LigH-de** [comment]
If you don't see an easy way to discover the reason, it's just me, so feel free to close as "won't fix". I would be curious, though, if a debug build of an installer might tell more.

**Comment by gzotti** [comment]
I tend to see this as singular problem then which is out of our hands. The installer is industry-grade standard software used by many other programs, we are just users here.
