### ISSUE TITLE
massive translations by illegal translator banned from the team followed by massive review

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2738]
Closely related: https://github.com/Stellarium/stellarium/discussions/1999

I'm coordinator of the Dutch team and have been trying to keep a high quality of the Dutch translations. My approach is to  get the translators together via virtual meeting so that we can produce high quality translations. It appears that some translators would not agree to such an approach, and prefer to operate on their own, producing incorrect translations. Some translators would then prefer to leave the team rather than sit together.

For example, I have removed one very prolific user "HerrMensch" from the team because (1) this user does not want to cooperate inside the team, and (2) (s)he applies massive and often wrong translations, (3) I cannot reach this user.

Example of unexpected and very recent translations:
- "Distinctive area of broken terrain." as "Onderscheidend gebied van gebroken terrein.", a literal but incorrect translation that  should read "Gebied bestaande uit gehavend terrein."

Another user "pahles" that did not want to work in a team context recently performed incorrect translations, e.g.

- "albedo feature" is incorrectly translated as "albedo-functie"
- "Radial-patterned feature." as "Radial-patterned feature." (which looks like a machine translation)

Other users submitted incorrect translations that were incorrectly flagged as "reviewed":
- "Chain of craters." as "Kraterrij." but should/could be "kraterketen"

Today I noticed that 

1. user "HerrMensch" has performed a massive - probably machine driven - translation. Transifex says "via Translation memory"
2. ALL strings have been reviewed by someone unknown to me (I'm the only active reviewer)

Please explain what is happening here:

1. how is it possible that such a user can operate and cannot be stopped
2. how come that all translations have been reviewed
3. it is flabbergasting that translators can be given translation powers and cannot be stopped. This is unacceptable, because the reputation of individual translators that try to deliver good translations is stained by the actions of a few lone wolves

thank you.

**Comment by axd1967** [comment]
I have also had to reject a translator that refused to contact me. It is unacceptable that a random user can start translating without demonstrating a sound mastery of the Dutch language,

**Comment by alex-w** [comment]
A few days ago we moved to new tool for integration Transifex/GitHub and new tool added new slugs for resources. Of course new resources as automatic filled from old resources and these "_new_" translations got status _not reviewed_. For ability to restore possible errored translations I've create a separate branch - [transifex-archive](https://github.com/Stellarium/stellarium/tree/transifex-archive/po). A few resources (e.g., German) was restored by me from this branch. Esp. for Dutch language I restored the translations (_planetary-features_) from `po` file and I'm marked them as reviewed as it was before. Sorry for that.

So, you may update all Dutch resources to "the release state" via uploading `*.po` files from latest release. And of course you can reject my massive yesterday's reviewing.

Please write to me if you will catch problems for rejection the reviewed status of translations or uploading `*.po` files.

**Comment by pahles** [comment]
> Another user "pahles" that did not want to work in a team context recently performed incorrect translations, e.g.
> 
> * "albedo feature" is incorrectly translated as "albedo-functie"
> * "Radial-patterned feature." as "Radial-patterned feature." (which looks like a machine translation)

For some reason @axd1967 always drags my name into this translation drama. I haven't made a translation for Stellarium for several years now, so how I have 'recently' performed translations is a mystery to my. I have indicated I don't want to cooperate with the translation efforts in the way @axd1967 has in his mind. The reason is of no ones concern. I would appreciate is @axd1967 would keep my name out of this discussion (as I have requested more than a year ago).

**Comment by axd1967** [comment]
@pahles  in that case, someone else is using your account.


![image](https://user-images.githubusercontent.com/3529789/194828523-e6387843-1ad2-41d6-9c86-293690381992.png)

**Comment by gzotti** [comment]
Is it possible that "5 days ago" this whole big change happened, and Transifex just re-recorded this date?

**Comment by axd1967** [comment]
or - Transifex is wrongly crediting @pahles via some Transifex mechanism

**Comment by pahles** [comment]
Again, I have not translated anything with Transifex 5 days ago, I was 'removed' from the Translators in June this year:

<img width="688" alt="Screenshot 2022-10-10 at 11 05 40" src="https://user-images.githubusercontent.com/3521661/194832218-4ab8372a-9db7-4c3b-8c25-f6911e090ff6.png">

My account on Transifex is not being used by someone else.

> Is it possible that "5 days ago" this whole big change happened, and Transifex just re-recorded this date?

This most likely is the case.

**Comment by alex-w** [comment]
Well, this may be strange, but please answer the question "Which date will be set for a resource, which was created 5 days ago?" to better understanding what is happened after creating new slugs for translations.

**Comment by gzotti** [comment]
I have the impression that also everything has been approved now. I had a few strings yet not approved where I wanted to think about a better English phrase. Unfortunately also approved_before etc filters don't work as expected, so it seems the translated-on and reviewed-on data are just not available. Nuisance, but we will have to live with it.

**Comment by axd1967** [comment]
> ... please answer the question "Which date will be set for a resource, which was created 5 days ago?"

I'm sorry @alex-w , I don't understand your question. Can you please rephrase it?

**Comment by axd1967** [comment]
Strictly speaking this is not a Stellarium issue, but it might be good to have this reported to Transifex as well as monitored here by other translators.

What I will do is mark all strings as unreviewed for now. As far as I remember, most strings were in the unreviewed state before this incident.
