### ISSUE TITLE
qt6: TestJavaScripting::testColor() fails

### ISSUE THREAD

**Issue by DarthGandalf** [Stellarium/stellarium#2739]
### Expected Behaviour

Unit tests pass

### Actual Behaviour
TestJavaScripting::testColor() fails
Describe or maybe attach a screenshot?

```
PASS   : TestJavaScripting::testV3f()
Script:
var f1 = new Color(0.5, 0.4, 0.3);
f1.getR().toFixed(1)+','+f1.getG().toFixed(1)+','+f1.getB().toFixed(1)

Script:
var f3 = new Color('#00ffff');
f3.toRGBString()

QWARN  : TestJavaScripting::testColor() "Could not convert argument 0 at"
QWARN  : TestJavaScripting::testColor() 	 "%entry@:1"
QWARN  : TestJavaScripting::testColor() Passing incomatible arguments to signals is not supported.
FAIL!  : TestJavaScripting::testColor() 'result == expect' returned FALSE. (var f3 = new Color('#00ffff');
f3.toRGBString()
=[r:1, g:1, b:1])
   Loc: [/mnt/portagetmp/portage/sci-astronomy/stellarium-1.0/work/stellarium-1.0/src/tests/testJavaScripting.cpp(254)]
PASS   : TestJavaScripting::cleanupTestCase()
Totals: 4 passed, 1 failed, 0 skipped, 0 blacklisted, 3ms
```

### System
* Stellarium version: 1.0
* Operating system: Gentoo Linux with Qt 6.4.0
* Graphics Card: 
* Screen type (if applicable): 

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

[LastTest.log](https://github.com/Stellarium/stellarium/files/9742161/LastTest.log)

**Comment by DarthGandalf** [comment]
Testing it further... It fails with qt5 too, if I use `-DENABLE_SCRIPT_QML=yes`. But in this case the test fails even more
[LastTest.log](https://github.com/Stellarium/stellarium/files/9742187/LastTest.log)

The test passes with `-DENABLE_SCRIPT_QML=no`, but this option is not available with qt6

**Comment by gzotti** [comment]
-DENABLE_SCRIPT_QML should be false for Qt5. True with Qt5 is currently unsupported. This is one of the key differences between Qt5 and Qt6 versions. 
But yes, this is a new issue I also found yesterday, it's new with Qt6.4.

**Comment by tofilwiktor** [comment]
I'm not so good with Qt/C++, so I'm likely wrong but the entire `Color` class in `V3d.hpp` is defined within an `#ifdef ENABLE_SCRIPT_QML` block, so shouldn't this test only run when ENABLE_SCRIPT_QML is defined? Instead the `testColor()` function is outside such a block. I'm unable to test this at the moment because Stellarium doesn't properly compile with Qt6.4 on Arch-based Linux distributions (see: #2709).

**Comment by gzotti** [comment]
Does current master still not compile on Arch? I moved to 6.4 on the day of your report, solved a mini issue and never had a problem since.

**Comment by tofilwiktor** [comment]
Oh, you made me realize, I downloaded the source code from releases instead of just cloning, then complained about an older issue persisting 🤦. I think I'm just too tired right now. I'll clone and try compiling again.

**Comment by tofilwiktor** [comment]
After some testing and reading about QML I realized that the bug is actually caused by passing `hexColor` by reference in the Color constructor because QML apparently doesn't support reference signal parameters. Removing that seems to fix the issue.

**Comment by gzotti** [comment]
Ah, thanks. Did not check yet.
