### ISSUE TITLE
INDI Telescope Control

### ISSUE THREAD

**Issue by Amanda-M-UK** [Stellarium/stellarium#2750]
Hi,

Is it possible to change the host (IP address) for the telescope control plugin? It seems to be hard-coded for localhost and I cannot find any options to change this. I need to connect to an INDI server running on a different machine. 

Anybody know how to do this?

**Comment by alex-w** [comment]
It's not hardcoded

**Comment by gzotti** [comment]
Maybe you are experiencing #2713 ?

**Comment by Amanda-M-UK** [comment]
I've found the control to change the IP and port now. Missed it, sorry for the report.
