### ISSUE TITLE
Oculars: Indicate max exposure time for moving objects to avoid trailing

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#2752]
**Is your feature request related to a problem? Please describe.**

Suggested via PM by Andrea Mattei:

> When I select an asteroid, I can see some values in the info, including the proper motion expressed in seconds of arc.
> So, if I have set my scale for my CCD, might it be useful to read the exposure time to use to prevent the asteroid from being moved?
> 
> 
> For example, I have selected Asteroid (1420) Radcliffe. I can read 15" /hour how Proper Motion. My CCD scale is 1.1105"/px
> So, my calc is: 
> 1.1105 / (15/3600) = 266 sec (max time of exposure)
> 
> 
> Selecting (65803) Didymos:
> Proper Motion is: 5' 14" = 314 arc second for hour (at 15 october 2022)
> then: (1.1105 / (314/3600)) = 12.7 sec (max time of exposure)
> 

**Describe the solution you'd like**

If a solar system object is tracked in sensor view, add information of maximum exposure time to avoid a movement of more than 1 pixel width. The info can go as ExtraInfoString or as add-on to the sensor frame. 

**Describe alternatives you've considered**
Currently it needs some brain to estimate this time.

**Additional context**
It can be assumed the telescope is tracking at sidereal rate.

**Comment by AndreaMatthey** [comment]
hi Georg.
Some news #2752 ?

**Comment by alex-w** [comment]
@AndreaMatthey not yet, sorry

**Comment by gzotti** [comment]
Please don't hold your breath. I have no time before December, at least.

**Comment by alex-w** [comment]
@AndreaMatthey please share parameters for your CCD and telescope

**Comment by AndreaMatthey** [comment]
ATIK 383L+ 
Sensor Type: KAF-8300 17.6mm x 13.52m
Horizontal Resolution: 3354 pixels
Vertical Resolution: 2529 pixels
Pixel Size: 5.40µm x 5.40µm
RC 10" Focal Lenght: 2000 mm

**Comment by alex-w** [comment]
> ATIK 383L+
> Sensor Type: KAF-8300 17.6mm x 13.52mm
> Horizontal Resolution: 3354 pixels
> Vertical Resolution: 2529 pixels
> Pixel Size: 5.40µm x 5.40µm
> RC 10" Focal Lenght: 2000 mm

Binning 2x2?

**Comment by alex-w** [comment]
@AndreaMatthey could you share installed version of Stellarium (within Stellarium: F1 -> About)?

**Comment by AndreaMatthey** [comment]
Stellarium 1.0
Versione 1.22.3
Based on Qt 6.3.1

Yes, normally I use Bin 2

**Comment by AndreaMatthey** [comment]
Great. Just tested. I think that it work.
