### ISSUE TITLE
Color settings of windows backgrounds and fonts

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#2763]
**Is your feature request related to a problem? Please describe.**
I am using Stellarium 1.0 in Kubuntu 22.04 with dark theme and LG 34GK950F monitor. When I open settings it is hard to read texts in setting windowses, because the font is black and background is dark grey.

**Describe the solution**
Please, add text color settings to Stellarium.eeeeeeeeeeeeeeeeee

**Comment by alex-w** [comment]
Related to #1624

**Comment by gzotti** [comment]
I have played with this a good while ago. Shall I finally upload my branch?

**Comment by alex-w** [comment]
> I have played with this a good while ago. Shall I finally upload my branch?

Did you meant adding support themes?

**Comment by gzotti** [comment]
I want to allow loading .css files. Either per CLI or even as scripting command. Just rebased and compiling to see what I had done 2 years ago...

**Comment by gzotti** [comment]
Not that I advocate these settings, just to show an awful user scheme:

![stellarium-045](https://user-images.githubusercontent.com/18099873/197403094-be90bcdb-bae7-42bf-9835-39ddf346dab6.jpg)

**Comment by gzotti** [comment]
@ilkant now you can create your own theme. The description of #2772 contains  "daylight" style files which you can use for a start. Usage will be described in the User Guide in V1.1.

**Comment by alex-w** [comment]
Please check details for adding user CSS in Stellarium User Guide - https://github.com/Stellarium/stellarium-data/releases/download/guide/guide.pdf

**Comment by ilkant** [comment]
I use Linux Kubuntu 22.04 and Stellarium 1.1 Release Canidate 3 as
AppImage. I put daylight.css to my homefolder. No difference to default
style and colors.

I have before looked /usr/share/stellarium/webroot and there is one css
file. But for example not in ~/.stellarium/ folder. In
/usr/share/stellarium it would perhaps affect to all users of this machine.
But Iam only one, who uses.

la 29. lokak. 2022 klo 10.08 Alexander V. Wolf ***@***.***)
kirjoitti:

**Comment by ilkant** [comment]
I copied daylight.css to ~/.stellarium/ folder and started Stellarium
1.1 RC3 with /home/user/apps/Stellarium-1.1-RC3-x86_64.AppImage
--gui-css daylight

It works! Thank you. And you might write some lines to user guide how
to do this in Linux. I think that same works with apt or such
installed stellarium too. Nice that an AppImage works with
daylight.css.

su 30. lokak. 2022 klo 22.05 Ilpo Kantonen ***@***.***) kirjoitti:
