### ISSUE TITLE
Date/time dialog date delimiter differs between ui and cpp files

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2766]
The `.ui` file of the _Date and Time_ dialog looks as follows:

![Screenshot - 221022 - 19:51:48](https://user-images.githubusercontent.com/6376882/197352630-93500f98-4c25-4dab-8447-c292b9bb01bb.png)

And then the slash is replaced in `DateTimeDialog.cpp`:
```
	// Use ISO 8601 to date formatting
	// See details: https://bugs.launchpad.net/stellarium/+bug/1655630
	QString delimiter = QChar(0x2012);
	ui->dateDelimiterLabel1->setText(delimiter);
	ui->dateDelimiterLabel2->setText(delimiter);
```

Why? Is it just a mistake, or is there a deep reason to avoid setting the correct character from the beginning?

**Comment by gzotti** [comment]
I can only guess. Replacing the characters may have been faster in the day this change was made. But yes, looks weird. @alex-w ?

**Comment by alex-w** [comment]
Ouch... @10110111 you may freely replace delimiter in the GUI and remove code for it from CPP file, because Qt5 and Qt6 has better support unicode than Qt4 (don't forget mark delimiters as untranslatable strings)

**Comment by 10110111** [comment]
OK, done.
