### ISSUE TITLE
Missing file after update 

### ISSUE THREAD

**Issue by stooge75** [Stellarium/stellarium#2767]
Telescope_control.json missing from files
Just updated to version 1 and when i ask it to add my mount in telescope control/configure,the chooser appears and I click heq5/6 then ok.
Nothing happens it won’t add my mount.
I’m led to believe it’s because of a missing telescope_control.json file as that’s the only thing different from the updated version and the old version on my other laptop

**Comment by alex-w** [comment]
Duplicate of #2713

**Comment by stooge75** [comment]
So what’s the recommended fix?

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
