### ISSUE TITLE
Search result from Simbad not plotted on right spot (missing aberration)

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#2769]
Discovered in https://groups.google.com/d/msgid/stellarium/6323ea53-5515-4949-859b-dd00f7d19438n%40googlegroups.com

### Expected Behaviour

When an object search is forwarded to Simbad, the artificial object that is created should be plotted with aberrated position. 

### Actual Behaviour

The returned object is plotted on current coordinates, but without aberration. 

### Steps to reproduce

Search "alf Psc", check result: marker not on the star. Then switch off aberration correction to see marker on top of the star. 

### System
* Stellarium version: 1.0
* Operating system: Win10 (irrelevant)
* Graphics Card: irrelevant

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Victim of underdocumentation of CustomObject. I was aware of the manually set markers (which are drawn without aberration), but was not aware that this class is used for Simbad results.

**Comment by alex-w** [comment]
> Victim of underdocumentation of CustomObject. I was aware of the manually set markers (which are drawn without aberration), but was not aware that this class is used for Simbad results.

Markers are markers, custom objects are custom objects and this is different entities

**Comment by gzotti** [comment]
But both are handled in this CustomObject class, right? This is really confusing also when the constructor argument isVisible governs the isMarker instance variable.

**Comment by alex-w** [comment]
> But both are handled in this CustomObject class, right? 

No.

**Comment by gzotti** [comment]
Yes, these are also those things that users understand as "Marker" because they are plotted as "Marker X" on screen. I have to check again what the MarkerMgr class does. Ah, something with scripting.
