### ISSUE TITLE
Outer ring of Uranus has a gap

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2775]
Maybe I don't know something about the rings of Uranus, but it seems quite strange that the outer ring as rendered by Stellarium has a gap that rotates as time passes. See the screenshot:

![Screenshot - 231022 - 23:37:00](https://user-images.githubusercontent.com/6376882/197417046-55604e37-7ac5-431d-9dcd-8df5c8eef9f2.png)

I have long seen this behavior in Stellarium, only now report it. It reproduces on Intel UHD Graphics 620, NVIDIA GeForce GTX 750Ti, NVIDIA ION etc., so I suppose it's a problem in Stellarium itself—or in my knowledge about Uranus.

**Comment by gzotti** [comment]
I think the rings are somehow described as incomplete. Must check again.

**Comment by alex-w** [comment]
This is correct view, because outer ring of Uranus is not full circle

**Comment by 10110111** [comment]
> This is correct view, because outer ring of Uranus is not full circle

Any reference to support this?

**Comment by gzotti** [comment]
I am no longer sure. Yes, I remember having read about ringlets and incomplete arcs,  by gravity interaction with moons.  See https://en.wikipedia.org/wiki/Rings_of_Uranus and references therein.
The &epsilon; ring is described as shepherded by Cordelia and Ophelia. Our model does not do that. Maybe somebody should check the distribution of non-empty pixels in the Uranus ring texture again. 
What surprises me however is that the texture is just a 2-px wide line. This is enough to paint a textured circle, but indeed, that the outermost circle is not closed is weird.

**Comment by 10110111** [comment]
The only part that talks about incomplete arc is this:

> The ε ring seems to consist of a number of narrow and optically dense ringlets, some of which may have incomplete arcs.

So the _ringlets_, not the whole ring, and _may_ have incomplete arcs, not do have. This in no way makes the whole ring have abrupt start and end.

Finally, just look at the image from Hubble as posted by the JPL [here](https://www.jpl.nasa.gov/images/pia01282-hubble-observes-the-planet-uranus), and for comparison the Stellarium render of this configuration (Aug 14 1994).

![](https://d2pn8kiwq2w21t.cloudfront.net/original_images/jpegPIA01282.jpg)

![Screenshot - 241022 - 01:07:53](https://user-images.githubusercontent.com/6376882/197420441-8ae27c00-e086-44fd-b25c-beacc3863b79.png)

**Comment by 10110111** [comment]
Oh, actually it's all messed up. The brightest ring in the Hubble's photo is the ε ring, and it's inside the orbit of Ophelia. What Stellarium shows as a very bright and incomplete outermost ring seems to be the μ ring. But this one should be so faint as to be invisible, just as the ν ring (and anything beyond the ε ring).

**Comment by gzotti** [comment]
Yes, Uranus' rings should be redone. They look rather symbolic now.

**Comment by 10110111** [comment]
The mesh generator has an off-by-one mistake in generation of indices, taking `slices` as stack stride instead of `slices+1`. The resulting mesh, if we choose `slices=5` and `stacks=2`, looks like this:

![Screenshot_2023-01-07_18-47-44](https://user-images.githubusercontent.com/6376882/211151540-b98e2c59-d080-44e2-9c8b-a6c3559cde7e.png)

When fixed, it will look like this:

![Screenshot_2023-01-07_18-48-37](https://user-images.githubusercontent.com/6376882/211151558-598539d6-7886-4e9f-a0a0-c8b735eaf0bf.png)
