### ISSUE TITLE
ShowMySky is not working in Stellarium 1.1 RC2 on Linux

### ISSUE THREAD

**Issue by worachate001** [Stellarium/stellarium#2779]
Testing Stellarium-1.1-RC2-x86_64.AppImage.

### Expected Behaviour
ShowMySky works.

### Actual Behaviour
Failed to load ShowMySky library: Cannot load library ShowMySky-Qt5: (ShowMySky-Qt5: cannot open shared object file: No such file or directory)

### Steps to reproduce
Run the AppImage and enable ShowMySky.

### System
* Stellarium version: 1.1 RC2
* Operating system: Manjaro Linux 22.0

**Comment by alex-w** [comment]
The fix in PR #2761

**Comment by worachate001** [comment]
Thanks @alex-w. I have been busy and missing things.
