### ISSUE TITLE
False stars in database

### ISSUE THREAD

**Issue by vladtcvs** [Stellarium/stellarium#2786]
### Expected Behaviour
![m33-2](https://user-images.githubusercontent.com/3390973/198835000-41378678-e4dc-4e23-a958-a63d27684d5b.png)

### Actual Behaviour
![m33-stellarium](https://user-images.githubusercontent.com/3390973/198834872-3df218ee-d1ec-4d9c-9989-5287a02c43c7.png)

There is some unnamed star with 7.45 magnitude in Stellarium in the center of M33. But there is no such star in reality.

### System
* Stellarium version: 0.22.2

**Comment by gzotti** [comment]
Just another false entry...

**Comment by vladtcvs** [comment]
Also I think, that there are no such bright unnamed stars at all. So if there are such stars in DB, all of them should be reviewed

**Comment by Atque** [comment]
Maybe it’s time to update the star catalog? For historical research, proper motions need to be solved. There are open-source projects with both 3D corrected Hipparchus catalog and Gaia releases.
