### ISSUE TITLE
Compilation issue / ShowMySky & Qt6

### ISSUE THREAD

**Issue by arnaudlecam** [Stellarium/stellarium#2791]
### Expected Behaviour
CMake should find ShowMySkyConfig.cmake and showmysky-config.cmake
### Actual Behaviour
ShowMySkyConfig.cmake and showmysky-config.cmake are not founded by CMake.
### Steps to reproduce
Compiling stellarium with ShowMySky support enabled
### System
* Stellarium version: stellarium-1.0-2
* Operating system: Linux-6.0.2-arch1-1 (x86_64)
### Temporary solutions
1) Desabling ShowMyCalc support
2) Creating symbolic links
<pre><code>ln -s /usr/lib/ShowMySky-Qt6/cmake/ShowMySky-Qt6Config.cmake /usr/lib/ShowMySky-Qt6/cmake/ShowMySkyConfig.cmake
ln -s /usr/lib/ShowMySky-Qt6/cmake/ShowMySky-Qt6Config-none.cmake /usr/lib/ShowMySky-Qt6/cmake/showmysky-config.cmake</code></pre>

**Comment by 10110111** [comment]
Use CalcMySky-v0.1.0 with Stellarium v1.0. Newer version of CalcMySky has changed naming of the ShowMySky library, and this is supported by current Stellarium `master`.

**Comment by arnaudlecam** [comment]
ok, I'll send a link to Arch's maintainer : thank you !

**Comment by carlosal1015** [comment]
Thank you @arnaudlecam
