### ISSUE TITLE
Freezing Stellarium when scripts are running

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2792]
### Expected Behaviour

Stellarium run the scripts

### Actual Behaviour

Qt6-based Stellarium freezing when scripts are running. 

The list of problematic scripts:
- earth_2.ssc
- earth_3.ssc
- earth_4.ssc
- earth_5.ssc
- earth_6.ssc
- earth_7.ssc

### System
* Stellarium version: 1.0 (v1.22.3)
* Operating system: macOS 13.0

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
In 1.1-RC3 only `earth_3.ssc` script causes freezing Stellarium

**Comment by gzotti** [comment]
As much as we know so far: tight busy-loops require addition of a short wait.
