### ISSUE TITLE
log.txt Timezone for some places in Europe not found

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#2796]
### Expected Behaviour
No warning lines at log.txt file.

### Actual Behaviour
Only some warning message lines at log.txt file.

### System
* Stellarium version: <Stellarium-1.1-RC3-x86_64.AppImage?>
* Operating system: <Kubuntu, 22.04>

### Logfile 
File log.txt has following lines:
dLoaded 249 countries
QFSFileEngine::open: No file name specified
StelLocationMgr::loadCitiesBin(): TimeZone for  "Berehove"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Khust"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Mukacheve"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Svalyava"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Uzhhorod"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Vynohradiv"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): Summary of unknown TimeZones:
"Europe/Uzhgorod"
Please report these timezone names (this logfile) to the Stellarium developers.

**Comment by ilkant** [comment]
Berehove, Khust, Mukacheve, Svalyava, Uzhhorod, Vynohradiv and Uzhgorod are in Ukraine. I got timezones from english Wikipedia. How to place them to data?

Place              Normal               Summer
Berehove       UTC+2 (EET)     (DST) UTC+3 (EEST)
Khust             UTC+1 (CET)     (DST) UTC+2 (CEST)
Mukacheve   UTC+1 (CET)     (DST) UTC+2 (CEST)
Svalyava       UTC+1 (CET)     (DST) UTC+2 (CEST)
Uzhhorod      UTC+2 (EET)     (DST) UTC+3 (EEST)
Vynohradiv    UTC+1 (CET)     (DST) UTC+2 (CEST)
Uzhgorod      UTC+2 (EET)     (DST) UTC+3 (EEST)

**Comment by gzotti** [comment]
It seems these timezones recently were removed from the IANA timezones database. I will add them to our replacement mechanism. They are then automatically set to Kyiv.

**Comment by gzotti** [comment]
Actually this is only obsolete timezone Ushgorod, and has been fixed last week.

**Comment by gzotti** [comment]
For the record: Fixed in 327a66c3e43545cfce77a238cf33fcf25ac71245

**Comment by ilkant** [comment]
I fetched 28th November 2022 from GitHub Stellarium source code and compiled on my computer. Now version is: Stellarium 1.1 Version 1.22.4-94821fc [master] Based on Qt 6.3.1.

There are still 

Loaded 252 countries
Loaded 193 regions
StelLocationMgr::loadCitiesBin(): TimeZone for  "Berehove"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Khust"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Mukachevo"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Rakhiv"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Svalyava"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Thunder Bay"  not found:  "America/Thunder_Bay"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Uzhgorod"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Vynohradiv"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): Summary of unknown TimeZones:
"Europe/Uzhgorod"
"America/Thunder_Bay"

**Comment by gzotti** [comment]
Thanks for the note. I cannot check currently due to hardware problems.
