### ISSUE TITLE
Stellarium 1.1 core dumped Kubuntu 22.04

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#2799]
### Expected Behaviour
Normal Stellarium screen.

### Actual Behaviour
No graphics screen appears before Stellariums stops and core dumped.

### System
* Stellarium version: <Stellarium-1.1-x86_64.AppImage>
* Operating system: <Kubuntu, 22.04>
* Graphics Card: <MSI GeForce GT 1030 2GH LF OC>
* Screen type (if applicable): 3440 x 1440 LG Electronics 34GK950F

### Logfile 
This is output to konsole when started application. Stellarium 1.1 RC3 AppImage worked ok. Stellarium 0.20.4 installed from Kubuntu repository.

$ Stellarium-1.1-x86_64.AppImage 
 ------------------------------------------------------------
[ This is Stellarium 1.1 (v0.22.4) - https://stellarium.org/ ]
[ Copyright (C) 2000-2022 Stellarium Developers              ]
 ------------------------------------------------------------
Writing log file to: "/home/ilpo/.stellarium/log.txt"
File search paths:
  0 .  "/home/ilpo/.stellarium"
  1 .  "/usr/share/stellarium"
Config file is:  "/home/ilpo/.stellarium/config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
OpenGL module type: 0
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
Can't open ISO639 codes file  "/usr/share/stellarium/data/languages.tab"
Default surface format:  QSurfaceFormat(version 3.3, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CoreProfile)
OpenGL module type: 0
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.3 (Core Profile) Mesa 22.0.5"
Current Format:  QSurfaceFormat(version 4.3, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 0, stencilBufferSize 0, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CoreProfile)
StelMainView::init
Luminance textures are not supported
Detected: OpenGL "4.3"
Driver version string: "4.3 (Core Profile) Mesa 22.0.5"
GL vendor is "nouveau"
GL renderer is "NV138"
GL Shading Language version is "4.30"
MESA Version Number detected:  22
Mesa version is fine, we should not see a graphics problem.
GLSL Version Number detected:  4.3
GLSL version is fine, we should not see a graphics problem.
stel.OpenGLArray: Vertex Array Objects are supported
Sky language is  "fi_FI"
Planetary features language is  "fi_FI"
Application language is  "fi_FI"
Scripts language is  "fi_FI"
Cache directory is:  "/home/ilpo/.cache/stellarium/stellarium"
Loaded 249 countries
QFSFileEngine::open: No file name specified
StelLocationMgr::loadCitiesBin(): TimeZone for  "Berehove"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Khust"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Mukacheve"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Svalyava"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Uzhhorod"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Vynohradiv"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): Summary of unknown TimeZones:
"Europe/Uzhgorod"
Please report these timezone names (this logfile) to the Stellarium developers.
Loading Solar System data (1: planets and moons) ...
Loading from : "/usr/share/stellarium/data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "/home/ilpo/.stellarium/data/ssystem_minor.ini"
SolarSystem has  190 entries.
Loaded 107 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15670 / 15672 items of planetary surface nomenclature
WARNING - These planets to assign nomenclature items were not found: "Dactyl"
Loading star data ...
"Loading /usr/share/stellarium/stars/default/stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading /usr/share/stellarium/stars/default/stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading /usr/share/stellarium/stars/default/stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading /usr/share/stellarium/stars/default/stars_3_1v0_4.cat: 3_1v0_4; 425807"
"Loading /home/ilpo/.stellarium/stars/default/stars_4_1v0_2.cat: 4_1v0_4; 1692779"
"Loading /home/ilpo/.stellarium/stars/default/stars_5_2v0_1.cat: 5_2v0_1; 7083058"
"Loading /home/ilpo/.stellarium/stars/default/stars_6_2v0_1.cat: 6_2v0_1; 24670782"
"Loading /home/ilpo/.stellarium/stars/default/stars_7_2v0_1.cat: 7_2v0_1; 50733321"
"Loading /home/ilpo/.stellarium/stars/default/stars_8_2v0_1.cat: 8_2v0_1; 92304337"
Finished loading star catalogue data, max_geodesic_level:  8
Loading scientific star names from "/usr/share/stellarium/stars/default/name.fab"
Loaded 6489 / 6489 scientific star names
WARNING: could not load scientific star extra names file: stars/default/extra_name.fab
Loading variable stars from "/usr/share/stellarium/stars/default/gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from "/usr/share/stellarium/stars/default/wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from "/usr/share/stellarium/stars/default/cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
Loading parallax errors data from "/usr/share/stellarium/stars/default/hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
WARNING: could not load proper motion data file: stars/default/hip_pm.dat
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
QMetaProperty::read: Unable to handle unregistered datatype 'DitheringMode' for property 'StelCore::ditheringMode'
StelProperty StelCore.ditheringMode can not be read. Missing READ or need to register MetaType?
Keskeytetty (luotiin core-tiedosto)
$ 

Keskeytetty =

And last lines from log.txt4:
WARNING: could not load proper motion data file: stars/default/hip_pm.dat
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
QMetaProperty::read: Unable to handle unregistered datatype 'DitheringMode' for property 'StelCore::ditheringMode'
StelProperty StelCore.ditheringMode can not be read. Missing READ or need to register MetaType?
$

**Comment by 10110111** [comment]
Please try the following patch:
```diff
diff --git a/src/core/Dithering.hpp b/src/core/Dithering.hpp
index efd3bb08c0..de4d60ff99 100644
--- a/src/core/Dithering.hpp
+++ b/src/core/Dithering.hpp
@@ -42,4 +42,6 @@ Vec3f calcRGBMaxValue(DitheringMode mode);
 
 QString makeDitheringShader();
 
+Q_DECLARE_METATYPE(DitheringMode)
+
 #endif
```
