### ISSUE TITLE
Hawaiian Starlines - Missing star names

### ISSUE THREAD

**Issue by papakilohoku** [Stellarium/stellarium#2808]
### Expected Behaviour
There are missing star names and labels for some of the stars and celestial bodies in a number of "starlines." They were included previous versions It appears that they were deleted in the latest upgrade into 1.0 and subsequent 1.1.
### Actual Behaviour
Describe or maybe attach a screenshot?
[https://drive.google.com/file/d/1CfPEm0PwwqU_x1V-lLyVxz7TGqq9IkND/view?usp=sharing](https://drive.google.com/file/d/1CfPEm0PwwqU_x1V-lLyVxz7TGqq9IkND/view?usp=sharing
)
### Steps to reproduce
The stars that were loaded in previous versions are missing. If there was a way to update these items, please advise and we will be working on updating them on our side to submit to you. Please advise when possible. 

### System
* Stellarium version: <1.1>
* Operating system: <MacOS 12.6>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
<img width="1024" alt="Kallupe_o_kawelo" src="https://user-images.githubusercontent.com/43593012/199342619-10c3d8e9-d806-43e4-8796-fe3366ea801e.png">

**Comment by gzotti** [comment]
Can you please indicate which earlier version had included names for these stars? The last change seems to have happened more than 1 year ago.

**Comment by papakilohoku** [comment]
I am unsure. I believe that they were there in the version that was utilized around this time last year (I use it as a teaching tool in my course). I did not notice that it was missing until this current version of 1.0 and 1.1. 

Is there a way that I could load older versions to check?

**Comment by alex-w** [comment]
See history of changes in SC: https://github.com/Stellarium/stellarium/commits/master/skycultures/hawaiian_starlines

**Comment by papakilohoku** [comment]
Copy that. I think that the last change made the stars disappear as it is in the same local area as the one change mentioned in the history.

**Comment by gzotti** [comment]
> Copy that. I think that the last change made the stars disappear as it is in the same local area as the one change mentioned in the history. 

The only change to the star name file done after first inclusion was #1931. Here, a false duplicate was removed. 
Is it possible you have a private skyculture of the same name installed which "overwrites" the built-in?

**Comment by papakilohoku** [comment]
I do not think so as the other students in my class do not see the other names either. Do you see those stars and names on your end?

**Comment by gzotti** [comment]
No, we have never seen them. This is what I am trying to say. We never have received names for those stars in the hawaiian_starlines SC.

**Comment by papakilohoku** [comment]
Interesting, as the screen shots that we were using were from a previous version of stellarium. Iʻll try to get up to speed and make those corrections

**Comment by papakilohoku** [comment]
It also is shown on the iphone app version when you (or whoever made the apple app version) copied the information. We will work with that. 

Is there a quick primer of how to make those additions available on the github? Would you be able to point me in to the proper direction? Thank you.

**Comment by alex-w** [comment]
@papakilohoku could you share `config.ini` file?

**Comment by papakilohoku** [comment]
The original submission was from 2017. Not sure if we still have the file. We will look for it as best as we can. Are there any other ways to access the config.ini file from previous versions?

**Comment by gzotti** [comment]
what has config.ini to do with that?
