### ISSUE TITLE
Objects at high zoom wobble — but only when atmosphere is on

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2809]
To reproduce, try the following steps:

1. Launch Stellarium
2. Make sure atmosphere is off
3. Go to Thebe (or, if your max zoom setting is too small, try Callisto)
4. Zoom in to see the ball, notice how clean and stable it is
5. Turn atmosphere on...

The screenshots of Thebe, as an extreme example:

* No atmosphere:

![Screenshot - 021122 - 00:57:45](https://user-images.githubusercontent.com/6376882/199351794-acdb2f9f-0d63-4c21-8068-4153c2ac6cd4.png)

* Atmosphere on (this is just one screenshot of a continuously wobbling image):

![Screenshot - 021122 - 00:57:37](https://user-images.githubusercontent.com/6376882/199351932-4967e936-0412-471b-a171-9cead987f64b.png)

I would suppose a problem with precision of projection, but given that without atmosphere everything is OK, the problem apparently is elsewhere.

**Comment by 10110111** [comment]
I've found the problem: it's in the `float`-coarsening of the geometric angle of elevation in `Refraction::innerRefractionForward` that breaks things. I've tried removing all this coarsening from this method, so that calculations are all done in `double`, and now nothing wobbles.

**Comment by gzotti** [comment]
Thanks @10110111, that was the one case of float/double issue I mentioned I was intending to track down.
