### ISSUE TITLE
I just loaded the most recent Stellarium version (1.1).  I am still having problems with the epoch in a comet orbit.  I put in an orbit with epoch J2000.0 (2451545.0) and get the same exact orbit if I put in the orbit epoch as a date thousands of years old

### ISSUE THREAD

**Issue by Pharnaces** [Stellarium/stellarium#2810]
I just loaded the most recent Stellarium version (1.1).  I am still having problems with the epoch in a comet orbit.  I put in an orbit with epoch J2000.0 (2451545.0) and get the same exact orbit if I put in the orbit epoch as a date thousands of years old

_Originally posted by @Pharnaces in https://github.com/Stellarium/stellarium/issues/2082#issuecomment-1299379073_

**Comment by gzotti** [comment]
All orbital elements relate to equinox J2000.0 but to the epoch of their elements. The orbit element epoch is the time for the given mean longitude.

**Comment by Pharnaces** [comment]
OK, thanks, that was not clear to me that J2000.0 is the default.  Is there any way to set the orbital elements to another epoch than J2000.0?

**Comment by Pharnaces** [comment]
I mean to another ecliptic coordinate system than J2000.0

**Comment by gzotti** [comment]
Not yet, and changing that has currently low priority, sorry. But we accept working solutions developed by other users!

**Comment by Pharnaces** [comment]
I'm not in any hurry.  Thanks!
