### ISSUE TITLE
Updated finnish translations to next version of Stellarium

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#2814]
**Is your feature request related to a problem? Please describe.**
I have translated Stellarium texts to finnish language in Transifex. I want them to be available in the next version of Stellarium. Is this possible? How often are updated translations included in distribution? I use AppImage myself, so I hope for changes to that as well.

The same thing can be done to all other languages too, if there are updates.

**Describe the solution you'd like**
Take current translations from Transifex when you make new version of Stellarium. Also to AppImages.

**Comment by alex-w** [comment]
Many texts are not transtaled to finnish language - https://www.transifex.com/stellarium/stellarium/translate/#/fi

Transifex automatic added translations into Stellarium when progress for resource is reaches 100%

**Comment by ilkant** [comment]
Yep: 8% -> 20% translated. I'm new to astronomy, so I'm careful with terms.

**Comment by ilkant** [comment]
It works. I see finnish texts. Thanks!
