### ISSUE TITLE
ObserveList load

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#2815]
**Describe the solution you'd like**
I want ObservingList loading to Stellarium. It loads list from users computer disk.

**Additional context**
When user can load ObservingList from disk, he or she can edit fields. Now field Date, Place (location), and Landscape couln't be able to edit. Furher user can get lists from other people and load them to own Stellarium.

**Comment by alex-w** [comment]
Did you tried import lists?

**Comment by ilkant** [comment]
I don't know how to import. There are not such feature in GUI and neither in Users Guide.

**Comment by gzotti** [comment]
Import was problematic but was fixed in #3207. Editing fields in the lists in GUI is not planned.
