### ISSUE TITLE
无法下载，需要授权

### ISSUE THREAD

**Issue by weitaifu** [Stellarium/stellarium#2817]
无法下载，需要授权。
无论怎么设置Microsoft edge的SmartScreen，也不论怎么设置Windows10的阻止可能不需要的应用。都无法下载。在Windows7中也无法下载。

**Comment by alex-w** [comment]
@sunshuwei please check this issue

**Comment by gzotti** [comment]
Google Translate:

> Unable to download, authorization required.
> 
> No matter how you set up Microsoft edge's SmartScreen, and no matter how you set up Windows 10 to block potentially unwanted apps. Neither can be downloaded. Can't download in Windows7 either.
> 

Try downloading with a different browser. There are ways to accept warnings and continue.
