### ISSUE TITLE
Stellarium 1.1: No images of deep sky objects M57 or M31

### ISSUE THREAD

**Issue by zeklh** [Stellarium/stellarium#2819]
When I zoom in no image of a deep sky object is shown. The button deep-sky-objects is activated.

My system: Windows 10 Home, Version 21H2

Regards
Hans

**Comment by 10110111** [comment]
Do you see them at any zoom level? Also, please post the log.

**Comment by alex-w** [comment]
Please try press I

**Comment by zeklh** [comment]
No image at any zoom level, but after pressing 'I' it works.

Here is the log.
[log.txt](https://github.com/Stellarium/stellarium/files/9927941/log.txt)

**Comment by alex-w** [comment]
> No image at any zoom level, but after pressing 'I' it works.

But this is not a bug - you just have disabled showing textures by some reasons.

**Comment by zeklh** [comment]
Sorry my mistake. I oversaw the button for deep sky images.
