### ISSUE TITLE
Crash on Qt 6 if media is enabled

### ISSUE THREAD

**Issue by DarthGandalf** [Stellarium/stellarium#2828]
### Expected Behaviour
Stellarium runs

### Actual Behaviour
Crash on startup. I found the minimal example and reported it at https://bugreports.qt.io/browse/QTBUG-108221

I don't know how actionable this bug is for you, mostly heads-up. As a workaround, for now I have disabled in Gentoo package the ability to select Qt 6 and media support at the same time.

### Steps to reproduce
1. Compile with `-DENABLE_QT6=yes -DENABLE_MEDIA=yes`
2. Run

### System
* Stellarium version: 1.1
* Operating system: Gentoo Linux
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by 10110111** [comment]
Ah, I did come across this, but that was because I don't have pulseaudio installed, while ALSA backend seems to be abandoned and disabled in Qt (I tried to enable it, but it doesn't compile).

**Comment by DarthGandalf** [comment]
Mm, I also don't have pulseaudio.

**Comment by alex-w** [comment]
I mark it as low importance because this issue in the Qt and we cannot resolve it within Stellarium - qtmultimedia module shouldn't be crash when backend had issue or didn't supported.

**Comment by alex-w** [comment]
Maybe we should mark it as "won't fix"

**Comment by DarthGandalf** [comment]
Sure
