### ISSUE TITLE
Flag Cardinal Points in script stopped working 

### ISSUE THREAD

**Issue by qam1** [Stellarium/stellarium#2834]
The Script commands

LandscapeMgr.getFlagCardinalsPoints();
LandscapeMgr.setFlagCardinalsPoints();

Don't work anymore.

They were working in version 0.21 but for some reason they stopped working in 0.22 and still don't work in versions 1.0 & 1.1

Pressing Q still toggles them off and on

**Comment by gzotti** [comment]
We changed the name to getFlagCardinalPoints().

**Comment by qam1** [comment]
Ok thanks
