### ISSUE TITLE
Bad performance for boundaries

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2836]
### Expected Behaviour
Good performance to rendering boundaries of constellations

### Actual Behaviour
Bad performance to rendering boundaries of constellations - after enabling displaying boundaries FPS dramatic decreases in 4 times

### Steps to reproduce
1. Run Stellarium
2. Enable boundaries (`B`)

### System
* Stellarium version: master
* Operating system: macOS 13.0 M1

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/9974143/log.txt)

**Comment by 10110111** [comment]
Does this also happen with `--opengl-compat` option?

**Comment by Atque** [comment]
Also to some degree present on Windows. Especially noticeable at wide FOV.

**Comment by alex-w** [comment]
@10110111 any ideas where is the source of issue?

**Comment by 10110111** [comment]
Apparently, the geometric shader works slowly. But it's so basic, that I don't know how it could be optimized.
A solution of this issue would be to redo `StelPainter::drawFromArray()` for all line-based primitives, so that it created polygons on the CPU instead of the geometric shader. Not nice technically, and quite a bit of work.

**Comment by alex-w** [comment]
Today we tested 1.2RC2 on Intel Mac and the issue is not reproducible, so, apparently this is problem specific for arm-macs (at least for M1).

**Comment by gzotti** [comment]
I can confirm the boundaries are "expensive" also on Win11, dropping from 60 to 52 fps in wide-angle view. But also gridlines, GUI dialogs  and InfoText displays are (and always have been) costly. I have not tested previous versions on this notebook, though. A drop to 1/4 would be bad, indeed. Is that only boundaries, or also the gridlines?

**Comment by unpacklo** [comment]
The core issue is the CPU cost here in drawing lines:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/3121968/212389574-d6fdecc9-359f-46c9-913f-27bd921c4bd3.png">

We should not be creating a new QOpenGLPaintDevice in `StelPainter::drawText`. The destruction of QOpenGLPaintDevice is 11% of the total CPU time. I've spent some time before in this code in an attempt to optimize a few months ago but I simply don't have enough knowledge about how Qt's OpenGL API and how Stellarium works to be able to meaningfully contribute at this time.

**Comment by unpacklo** [comment]
I finally managed to build stellarium on my macos and I can confirm that simply making the variable static makes my frame rate go from about 7 FPS to about 20 FPS (from about 143 ms per frame to about 50 ms per frame) for about a 2.8x speedup. Totally worth doing, but given that the CPU time associated with the destructor only takes up 10%, there must be some sort of GPU pipeline flush or sync that occurs with the construction/destruction of the QOpenGLPaintDevice that causes a much larger performance problem on the GPU side. I'll try to dig more but simply making that var static has a really big boost.

**Comment by 10110111** [comment]
> I finally managed to build stellarium on my macos and I can confirm that simply making the variable static makes my frame rate go from about 7 FPS to about 20 FPS

This is not related to boundaries, right? Because I don't see any text associated with them.

**Comment by alex-w** [comment]
@unpacklo thank you for investigating the problem. Could you send us pull request with patch?

**Comment by unpacklo** [comment]
> > I finally managed to build stellarium on my macos and I can confirm that simply making the variable static makes my frame rate go from about 7 FPS to about 20 FPS
> 
> This is not related to boundaries, right? Because I don't see any text associated with them.

@10110111 ah sorry, I was confused with another issue. I don't see the problem with boundaries at the moment, but I am seeing big performance problems on my Intel MacBook Pro (2019).

> @unpacklo thank you for investigating the problem. Could you send us pull request with patch?

@alex-w Yes, I intend to open a PR once I've figured out why making it static improves performance so much.

**Comment by krstnrogers** [comment]
Very slow and lags on version 1.2 when enabling the "show boundaries" option. Macbook air running MacOS Ventura 13.2.

**Comment by alex-w** [comment]
This is weird. macOS 13.2.1, current master + Qt5 - no penalty of performance when boundaries are enabled. Current master + Qt6 - the issue is here.

**Comment by gzotti** [comment]
We can so much need a profiling expert to point out bottlenecks!

**Comment by 10110111** [comment]
One major difference between Qt5 and Qt6 is that in Qt5 only integral scaling factors are supported (any fraction is rounded), while Qt6 supports fractional factors. You might be observing no slowdown with e.g. 100% effective (i.e. from Qt's PoV) pixel ratio, while a slowdown appears with higher pixel ratio.

**Comment by alex-w** [comment]
> One major difference between Qt5 and Qt6 is that in Qt5 only integral scaling factors are supported (any fraction is rounded), while Qt6 supports fractional factors. You might be observing no slowdown with e.g. 100% effective (i.e. from Qt's PoV) pixel ratio, while a slowdown appears with higher pixel ratio.

But why Qt6-based packages doesn't have the issue on Mac's with Intel CPU?

**Comment by 10110111** [comment]
If the issue only appears on non-Intel, this may just mean that Intel have been capable of making GPUs that run geometry shaders with sensible performance.

Just to check, what pixel ratio do you have on the machines where this slowdown happens? I'm interested in both Qt5 and Qt6 perspectives. Also, was the line width setting changed from the default on these machines?

**Comment by alex-w** [comment]
Device pixel ratio is 2

**Comment by 10110111** [comment]
In both cases?

**Comment by alex-w** [comment]
> In both cases?

Yep
