### ISSUE TITLE
Scaling for stars 

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#2840]
When running Stellarium on a high-DPI monitor, stars tend to look very small. Of course this is solvable by increasing the relative scale, but it would look better if the stars also scaled, so that relative scale = 1 and absolute scale = 1 looks about the same no matter what monitor is used.

**Comment by gzotti** [comment]
Yes, one of the things you may only see on a HiDPI monitor, which devs seem not to have... :-)

**Comment by alex-w** [comment]
Version 0.12.4:
![stellarium-000](https://user-images.githubusercontent.com/88731/201756408-90336465-09c7-4479-95e7-39e92196a7b6.png)

Version 1.1:
![stellarium-002](https://user-images.githubusercontent.com/88731/201756523-e806679c-f0a5-4937-b4e1-5cf695774f03.jpg)

Both screenshots taken in macOS 13 at MBP with Retina display. @Atque do you want to see sky in version 1.1 as it look in version 0.12.4?

**Comment by Atque** [comment]
@alex-w Yes, that's what I mean. However, this needs to be re-implemented carefully, as older versions of Stellarium showed the faintest stars with a high contrast to the sky. You can see this in your two screenshots; the modern Stellarium barely shows the faintest stars, while the legacy version shows them pretty clearly (which of course is scientifically incorrect).

**Comment by gzotti** [comment]
There are several factors: HiDPI, new skylight model with its modified sky brightness values, new tonemapping options. These all really need careful re-balancing.

**Comment by alex-w** [comment]
a first attempt - branch: visualisation/draw-point-source

![stellarium-003](https://user-images.githubusercontent.com/88731/201837942-ee93dcc7-be57-45bb-b164-2ce826f1f363.jpg)

**Comment by Atque** [comment]
That looks good. We seem to keep the faint stars barely visible, which I personally think is very important. No surprises when playing with relative/absolute scales?

**Comment by alex-w** [comment]
> That looks good. We seem to keep the faint stars barely visible, which I personally think is very important. No surprises when playing with relative/absolute scales?

See the changes - it's just application the scale of resolution

**Comment by alex-w** [comment]
![stellarium-004](https://user-images.githubusercontent.com/88731/201854540-6db42de3-06cd-408e-952e-22bf3d262463.jpg)
