### ISSUE TITLE
Planet halo jumps around at large enough zoom, while planet is stationary

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2844]
### Steps to reproduce

1. Select a "small" object like Helene
2. Zoom into it so that the halo just starts to fade out but hasn't faded (for Helene FoV is 9.08e-05°, adjust the minimum in the config if needed)
3. Watch the halo without the atmosphere, notice fast jumps around the planet
4. With the atmosphere the jumps are occasional (speed up time to increase the frequency), but the position is almost never correct

Related to #2809, but apparently the problem is not in the projector.

Example screenshot:

![Screenshot - 121122 - 21:56:25](https://user-images.githubusercontent.com/6376882/201490384-c432e225-9f1f-4399-8d3a-c34085691292.png)

### System
* Stellarium version: v1.1-60-g318104f86d
* Operating system: Linux From Scratch
* Graphics Card: GeForce GTX 750Ti

**Comment by gzotti** [comment]
I think we have enabled magnification of SSO given such dancing artifacts which indicate end of numerical stability. Standard min_fov does not allow such views. But maybe there is still a solution.

**Comment by 10110111** [comment]
Yes, indeed the solution exists, and I have it locally. The problem is once again `float` vs `double` in computations on the CPU.

**Comment by gzotti** [comment]
I think I have fixed the jittering sphere position some time ago, but overlooked the halo. And IIRC some years ago I asked whether we should simply move to double everywhere in position calcs, but was advised not to do it. Maybe now it's the time to do that.

**Comment by alex-w** [comment]
I think we can move computations to `double`, because in future we’ll have 64bit only packages

**Comment by gzotti** [comment]
There is still a penalty for GL_DOUBLE, so we use it only for -- again -- positional calculations. On GLES, there is no GL_DOUBLE, so I added a #define that forces it back to GL_FLOAT. Not nice, but it fulfills its purpose. 
@10110111 can you merge your halo position solution? Or does it show new issues? Then maybe all projection functions using single precision float types should be investigated (we have f->f, f->d, d->f and d->d; mark the f types deprecated and let gcc show them?). It may still be enough for landscapes, Milky Way, Zodiacal light, DSO images, skylight, i.e. whereever projection is confined to the unit sphere.

**Comment by 10110111** [comment]
> can you merge your halo position solution? Or does it show new issues?

It didn't find any new issues, but the way it had to be done I don't like: some places need additional `toVec3d()` calls, which could better be done by having the original vector in double. OTOH, we can do the full conversion to double later, and push this fix now. The commit itself is 753739fadf854c257181ed3f4ee2d1eb237c0cc1 in my fork.

**Comment by 10110111** [comment]
> P.S. what about OpenGL code?

OpenGL with double is infeasible in this decade. At least on NVIDIA GeForce series computations in double are an order or two of magnitude slower than in float. Quadro series are better in this regard, but few "normal" users have them.

I had a serious performance improvement when I found a way to get rid of double precision computations in CalcMySky eclipse simulation.

**Comment by gzotti** [comment]
Yes, Quadro requirement is certainly not an option for us.
