### ISSUE TITLE
landscapes should be adressable by ID

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2845]
**Is your feature request related to a problem? Please describe.**
I use following script as another way to switch between landscapes

```javascript
// vim: set ft=javascript :
//
// Name: Landscape - custom
// Author: AD
// License: Public Domain
// Version: 0.3
// Shortcut: Alt+L,9
// Description: KISS easy way to assign a custom landscape to a shortcut key 
//

// just (un)comment the desired landscape name...

//landscape_name = "0 - parking Gz (0.1a)";

//landscape_name = "1 - Bourgoyen";
//landscape_name = "1 - Campus Schoonmeersen Zuid v3";
//landscape_name = "1 - De Sterre-spits v0.1";
//landscape_name = "1 - Stationsbuurt Zuid";
//landscape_name = "1 - UGent Campus Sterre";
//landscape_name = "1 - Vredesmonument";
//landscape_name = "1 - Watersport";
//landscape_name = "1 - Zieklien";
//landscape_name = "1 - parking station";
landscape_name = "1 - Vrijdagmarkt";

//landscape_name = "Autosnelwegen";
//landscape_name = "Claudine - Vinalmont";

//landscape_name = "u/Eva Gent - Gezondheidstraat Window Horizon";
//landscape_name = "Gent - Blaarmeersen toren";
//landscape_name = "u/Els Gent - Drongensestnweg Zero Horizon";
//landscape_name = "u/Gent - Edwin v1.0";
//landscape_name = "u/ma Gent - Europalaan window";
//landscape_name = "u/Tim's Schipperskaai";
//landscape_name = "1 - varia";

//landscape_name = "Urumqi Zero Horizon";
//landscape_name = "hw/L'escala";

//landscape_name = "u/Ruth - Lovendegem";
//landscape_name = "u/Ruth hwt/Le Mas - 2";

var fade_time = 0.0;

LandscapeMgr.setCurrentLandscapeName(landscape_name, changeLocationDuration = fade_time);
```

The problem is that there is only one way to refer to a landscape: its title.
Whenever I want to change the title for whatever reason, I need to also change the script.

See also https://stellarium.org/doc/0.21/classLandscapeMgr.html

**Describe the solution you'd like**

Add a "ID" field that the user can choose to fill in as desired. Easiest and most flexible is an LANDSCAPE_ID field such as "23123123241" or "2022-10-10-ls1" or "STELLARIUM-DEFAULT-001" or whatever, that can be referred to from scripts, shared with less risk of name clashing... This allows the user to play with the landscape name as desired, and invoke the landscape via a new method, e.g. `LandscapeMgr.setCurrentLandscapeID(landscape_id, ...);`. Don't use complicated methods to ensure true unicity (such as the approach used for Observing Lists): the essence is that a user can easily decide on an own scheme (that could indeed use some kind of universal ID; but imposing that approach makes things complicated for some users).

A non-trivial extension of this use case would allow the user to rename all landscapes (including those included with Stellarium) so that the user can arrange the list of landscape names at will, include landscapes that are versioned on GitHub etc.

(And while on this issue, please make the vertical splitter movable so that the names can be read more easily.)

(Another extension is to allow the user to arrange landscape structures in folders rather than impose a single depth folder. This would make sharing landscapes more easy.)

**Describe alternatives you've considered**

Don't change the titles.

**Additional context**

**Comment by alex-w** [comment]
Landscape_ID and LandscapeMgr.setCurrentLandscapeID() was invented over 10 years ago

**Comment by gzotti** [comment]
Just don't rename landscapes then, we will not introduce a third naming scheme for you. I have over 250 and can still manage. It only takes some more time at startup. What I can agree is to make the splitter movable (and remember its position) for landscapes, skycultures and surveys in the same way, if I knew how.

**Comment by axd1967** [comment]
IIRC the splitter can be made movable via the UI editor, see 02a69ac128ee0f5faf5f84256eedcbc9480fa3fd.

Some other developer could deal with the ID issue ->  [for_wishlist](https://github.com/Stellarium/stellarium/search?q=for_wishlist&type=issues).

Please, can we skip the personal note ("for **you**")? there is no need to make this personal. We are all contributing in a positive, constructive way to this project, each in their way.
