### ISSUE TITLE
Satellites plugin rounds observer elevation to 1000 meters

### ISSUE THREAD

**Issue by rkinnett** [Stellarium/stellarium#2848]
The Satellites plugin appears to round the user's location elevation setting to the nearest 1000 meters which is very coarse.  For low-Earth orbiting satellites at mid-elevation, this yields roughly 0.1 deg pointing error.

To reproduce, pause Stellarium, select a fast-moving LEO satellite, then change site elevation gradually between 0 to 999m and observe no change in satellite position, then increment to 1000m and observe discrete jump of roughly 0.1 deg, then no change between 1000 and 1999m and another jump at 2000m, etc.

Please consider rounding to nearest 1m or 10m or 100m instead of 1000m.

This will improve usefulness of Stellarium for planning observations of satellite transits of celestial objects, although it is understood that there are other limitations on satellite position accuracy.

**Comment by gzotti** [comment]
Thanks for noting this!

**Comment by rkinnett** [comment]
Thanks for quick resolution!

**Comment by rkinnett** [comment]
Confirmed working in Stellarium v1.2.  Thanks!
