### ISSUE TITLE
Slow down auto centering in planetarium mode

### ISSUE THREAD

**Issue by MartinLewicki** [Stellarium/stellarium#2850]
When in a planetarium dome, clicking on an object the centering is far too quick. It sometimes disturbs the audience as it suddenly whips around faster than the eye can follow!

Request a custom setting or key function so that the object gently moves to the center - and even begin slow zooming while moving to the center.  It must be slow enough to accommodate a dome experience.

Martin

**Comment by alex-w** [comment]
Please try run script `StelMovementMgr.setAutoMoveDuration(5);` and check the movement again

**Comment by alex-w** [comment]
> Thank you Alex. It works nicely, especially at "10" for our dome. Is there also a similar setting to slowly zoom out to the default view via the "\"' key? 

No

> Also, given we use Stellarium in our dome this feature should be autoloaded at program launch rather than having to manually activate via F2-Scripts or script console every time? How can we do this and any other script we wish to autoload on launch? Martin

See `startup.ssc` script

**Comment by alex-w** [comment]
@MartinLewicki Is the issues resolved for you?

**Comment by MartinLewicki** [comment]
Yes. the script works nicely on the dome thank you. If we could get it to
similarly zoom out at a defined rate to full view to complete the acton.

Martin

Martin Lewicki
Adelaide Planetarium | Lecturer & Astronomy Educator
UniSA STEM | University of South Australia
Mawson Lakes
GPO Box 2471, Adelaide
South Australia 5001
Ph: +618 8302 3027
email ***@***.***
web: www.unisa.edu.au/planetarium/
