### ISSUE TITLE
Jupiter

### ISSUE THREAD

**Issue by Maxipac** [Stellarium/stellarium#2870]
Bonjour,
J'ai remarqué que la position de la tache rouge et des satellites de Jupiter ne correspondait pas à la réalité. Il semblerait que Stellarium montre une position en avance sur le temps réel. Pourtant le fuseau horaire et le site d'observation sont corrects.
Si j'utilise carte du ciel, tout est correct.
Merci de votre aide.
Patrick

Hello,
I noticed that the position of the red spot and the satellites of Jupiter did not correspond to reality. It looks like Stellarium is showing a position ahead of real time. However, the time zone and the observation site are correct.
If I use sky chart, everything is correct.
Thank you for your help.
patrick

**Comment by alex-w** [comment]
Please attach `config.ini` from Stellarium

**Comment by Maxipac** [comment]
[config.zip](https://github.com/Stellarium/stellarium/files/10086692/config.zip)

Voici mon fichier config.ini et merci pour votre réactivité.

Here is my config.ini file and thank you for your responsiveness.

**Comment by alex-w** [comment]
You have disabled option "Simulate light speed" and you see expected result of it.

**Comment by gzotti** [comment]
Also read about `GRS Details...` in the User Guide, page 32.

**Comment by Maxipac** [comment]
Merci beaucoup à tous. Vous avez trouvé le problème qui maintenant est résolu.
Je ne comprends pas pourquoi l'option " Simuler la vitesse de la lumière " était décochée et je ne connaissais pas sa fonction. Je vais informer mon ami qui a aussi le même problème.
Encore merci à vous pour votre aide rapide.
Patrick

Thank you very much to all. You have found the problem which is now solved.
I don't understand why the "Simulate speed of light" option was unchecked and I didn't know its function. I will inform my friend who also has the same problem.
Thank you again for your quick help.
Patrick
