### ISSUE TITLE
Stellarium Version 1.1 on macOS extremly slow display when moving 

### ISSUE THREAD

**Issue by vrmex** [Stellarium/stellarium#2872]
### Expected Behaviour
Fast smooth display while moving

### Actual Behaviour
Extremely slow display when moving 

### System
* Stellarium version: <Stellarium-1.1.1-macOS.zip>
* Operating system: <macOS Ventura Version 13.0.1 (22A400) INTEL MACBOOK PRO>
* Graphics Card: <AMD Radeon Pro 5500M 4 GB; Intel UHD Graphics 630 1536 MB>
* Screen type <16-inch (3072 × 1920)>

### Logfile 
none

**Comment by Atque** [comment]
Is this with the touchpad?

**Comment by gzotti** [comment]
#2778

**Comment by vrmex** [comment]
> 

Yes, this is with the Intel MacBook Pro 16" touchpad; basically Stellarium 1.1 as is right now it is totally useless.

**Comment by Atque** [comment]
If possible, try using a mouse and see if that works.
