### ISSUE TITLE
Please more DSLR focal lenses

### ISSUE THREAD

**Issue by deepsouthSA** [Stellarium/stellarium#2884]
Hello Stellarium Team
First of all a HUUUUUGE thank you for all the work you have and still putting into this project!
At the moment I can only find one focal length (135mm) in your telescope list. Could you please add some more commonly used focal lenses for DSLR users to this list:  200/ 300/400/600? Please!!

**Comment by gzotti** [comment]
Thanks, but no. Others have complained about the "useless collection which they have to delete, wasting their precious time". It is a matter of minutes to add and configure your own lens.

**Comment by deepsouthSA** [comment]
Thanks for your reply George, really appreciated!
Could you point me to a site/ tutorial explaining the process please
Always clear skys

**Comment by gzotti** [comment]
Have you seen the User Guide?
Actually, the user interface shows buttons labeled "Add", "Delete", and the right side shows detail settings. Can you figure out what to press?

**Comment by gzotti** [comment]
Question answered.
