### ISSUE TITLE
Connection between Arduino and Stellarium

### ISSUE THREAD

**Issue by Ferra04** [Stellarium/stellarium#2886]
### Expected Behaviour
connecting arduino with stellarium using meade lx200 protocol in order to get cordinates in real time for a camera mount.
### Actual Behaviour
i try to estabilish a connection but when i choose the right COM port i cant turn on the connection 
![image](https://user-images.githubusercontent.com/119624494/205143114-b9989077-bd7e-43f0-b9cc-4bdae1a6108e.png)
![image](https://user-images.githubusercontent.com/119624494/205143321-011cc7ce-dbd2-4e0f-bebe-74de9c6a88ec.png)
### Steps to reproduce
i followed this guide https://epsilonphoto.weebly.com/il-primo-sketch.html

### System
* Stellarium version: <Stellarium 1.1>
* Operating system: <Windows, 11>
* Graphics Card: <Manufacturer (Nvidia), Model (GTX1660 Ti),Latest>
* Screen type (if applicable):1920x1080, HighDPI, scaling

**Comment by gzotti** [comment]
Let me guess: https://epsilonphoto.weebly.com/il-primo-sketch.html  knows more than we do.

**Comment by Ferra04** [comment]
i can't hundestand why can't i use this.
