### ISSUE TITLE
Cannot install v1.1 on Mac OS 10.5.7

### ISSUE THREAD

**Issue by phomer60** [Stellarium/stellarium#2890]
### Expected Behaviour
Able to be installed. 10.15.7 was last updated in July 2022 and is the latest version I can install. If there is nothing that can be done about this then how do I reinstall the previous version?
### Actual Behaviour
Complains about not being compatible.

### Steps to reproduce
Attempt to install it.
### System
* Stellarium version: <v1.1>
* Operating system: <Mac OS, 10.15.7>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Stellarium 1.1 requires macOS 11.0+, because it Qt6-based only bundle. We can provide Qt5-based bundle, but it will show black screen.

**Comment by gzotti** [comment]
Our website states 10.5 as minimum requirement. What about the x64-only Qt5-based version without ShowMySky?

**Comment by alex-w** [comment]
> Our website states 10.5 as minimum requirement. What about the x64-only Qt5-based version without ShowMySky?

It's not related to ShowMySky, it's related to OpenGL 3.3 Core profile

**Comment by 10110111** [comment]
> It's not related to ShowMySky, it's related to OpenGL 3.3 Core profile

Does it work in `--opengl-compat` mode?

**Comment by alex-w** [comment]
> Does it work in `--opengl-compat` mode?

Yes, of course

**Comment by gzotti** [comment]
Sure, but SMS needs 3.3core. So, the 1.0 behaviour (OpenGL2.1, no SMS) is surely better for 10.5 than just a black screen.

**Comment by phomer60** [comment]
I extracted the file below and it still shows as not compatible.

https://github.com/Stellarium/stellarium-data/releases/download/weekly-snapshot/Stellarium-1.1-c47a4d8-macOS.zip

Paul

**Comment by alex-w** [comment]
From the description:
**Stellarium-1.1-c47a4d8-x86_64.zip** | Stellarium 1.1-c47a4d8 (1.1+) for macOS (x86_64; macOS 10.15+) based on Qt 5.12.12 (AppleClang 11.0.0) with media support.

**Comment by phomer60** [comment]
Alex,

I am not sure what you are asking, is there a different version that is compatible?

Paul

**Comment by phomer60** [comment]
Alex,

An icon for iIncompatible code is shown in Mac OS as a circle with a cross bar and that is what I got when i extracted the file.

Paul

**Comment by alex-w** [comment]
@phomer60 please open URL https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot and check **Packages notes** section
