### ISSUE TITLE
Pixelating bottom panel icons on screenshots

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2899]
### Expected Behaviour
Smooth bottom panel icons on the screenshots

### Actual Behaviour
On HiDPI devices screenshots has pixelized bottom panel icons when it taken by Stellarium itself. See bottom panel on screenshots below.

Screenshot from Stellarium (72 DPI):
![stellarium-003](https://user-images.githubusercontent.com/88731/206483566-81eb5983-eeec-45c6-82c7-a84f421c332b.png)

Screenshot from Stellarium (144 DPI):
![stellarium-004](https://user-images.githubusercontent.com/88731/206485215-2379a8f5-2496-4179-9b74-01dbaa8d37ba.png)

Screenshot from Stellarium (300 DPI):
![stellarium-005](https://user-images.githubusercontent.com/88731/206486489-56f2190a-c7b8-47da-b9ad-986f2e4108c5.png)

Screenshot from macOS:
![Снимок 08 12 2022 в 22 04](https://user-images.githubusercontent.com/88731/206483892-7ab9c44f-54eb-4e5f-b0ed-47da42ee26e5.jpeg)

### System
* Stellarium version: master
* Operating system: macOS 13.0.1 on MacBook Pro
* Screen type (if applicable): 2880x1800

**Comment by 10110111** [comment]
Also reproduces on GNU/Linux/X11 with Qt scaling factor 1.5.
