### ISSUE TITLE
remotecontrol i18n enhancements

### ISSUE THREAD

**Issue by leonardcj** [Stellarium/stellarium#29]
If I understood how your HTML was converted into POT (intltool?), I might try a pull request, but hopefully the attached file is adequate for action.

I'd like to propose i18n enhancement of the stellarium-remotecontrol.pot file by adding these wiki-links as translator comments in the HTML in such a way that they are parsed into the POT file.

[stellarium-remotecontrol_i18n_enhancements.txt](https://github.com/Stellarium/stellarium/files/1545250/stellarium-remotecontrol_i18n_enhancements.txt)

**Comment by gzotti** [comment]
While I still don't see necessity to add a link to a "Capella" entry on WP to translate "Capella", we could at least decide what to do with this here, won'tfix or accept. @alex-w ? Would this require an HTML comment next to each occurrence of tr()? Given that practically all strings have been translated in the main program, I see this as useless ballast.
