### ISSUE TITLE
Satellite TLE downloading ?

### ISSUE THREAD

**Issue by Frank57** [Stellarium/stellarium#2900]
Hello, I have been enjoying this program a lot and now have the PC version and will gladly help support it as well but have one question. May have been posted already but didn't come across anything. When in the program, I try to do an update to the TLE list but it just hangs there stating to wait, but no movement on the progress bar at the bottom, right side of the program. Left it like that for some time and nothing., Is this part working? the current ones are from June 2022 within the program and want to update to the latest ones. Frank

**Comment by alex-w** [comment]
The domain of Celestrak is changed and you should update sources of TLE by hands or press button to restore sources list in the GUI of the Satellite plugin.

**Comment by Frank57** [comment]
Ok, got it. I went back and read thru the user guide and see something about the restore button and thought that was if you made a lot of changes and messed it up but did that per your info and now I see all the sources again and everything is updating. Have a few satellites of interest I like to watch but not to clear out all the ones out there, geez, so many of them and those starlink ones are everywhere up there. But love the program itself for the star and planet info, Great program. Need to get a better PC now as I think I'm at the bare minimum for requirements as I lock up now and then. Keep up the great work. Told a friend about this program and he checked it out and loves it too. Nice, simple but lots of features. Thank you  Frank
