### ISSUE TITLE
Tamil Language translation of the content are Incorrect in stellarium App please replace correct name in the app

### ISSUE THREAD

**Issue by Sivaraja1982** [Stellarium/stellarium#2906]
Language  issue: Tamil names of stars and planets are incorrect pls rectify.

**Comment by gzotti** [comment]
Translation is done via Transifex. Please help yourself! (https://github.com/Stellarium/stellarium/wiki#translation)

**Comment by alex-w** [comment]
> Language issue: Tamil names of stars and planets are incorrect pls rectify.

Is it incorrect rendering or incorrect wording?

**Comment by gzotti** [comment]
@Sivaraja1982 have you added the translations? Or are there other problems? Else we will close this after Jan 15.
