### ISSUE TITLE
Landscape is displaying magenta

### ISSUE THREAD

**Issue by Wellco** [Stellarium/stellarium#2910]
### Expected Behaviour
Landscape should display correctly. I have two custom landscapes, One displays correctly but the other does not. I have checked the bit depth, size, colour space and so on but cannot find any differences. One image was created a few months ago and edited using a potentially different workflow, it displays fine. However the one today is just a magenta screen.

There must be an issue with the file, but I cannot find it

### Actual Behaviour
Describe or maybe attach a screenshot?

![Screenshot 2022-12-12 at 15 14 42](https://user-images.githubusercontent.com/5941720/207081961-60321cd9-50d1-482b-9686-47996

Here is my PNG file
![2THEWILLOWBACKGRDNeee](https://user-images.githubusercontent.com/5941720/207083788-f4d33bdc-3466-4741-867a-0d32547eb05a.png)
9ec7b79.png)

### Steps to reproduce
Configure a new landscape as per instructions, then use it in your session

### System
* Stellarium version: stellarium-1.1.1-qt6-win64
* Operating system: Windows 11 with all the updates applied
* Graphics Card: Intel HD Graphics
* Screen type (if applicable): I am using RDP as it's a headless PC, but one custom landscape is fine but the other not. 

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Please attach log.txt and screenshot. Would you check 1.2RC1?

**Comment by Wellco** [comment]
![Screenshot 2022-12-12 at 15 14 42](https://user-images.githubusercontent.com/5941720/207086344-f1c72ffd-8a33-475c-bed3-8b346e580f53.png)

Screen shot..

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by Wellco** [comment]
I found the Log.txt file and it said the PNG could not be found. So I went back and looked in the landscape.ini and realised that was a typo. I corrected this and now the file displays as it should.

**Comment by 10110111** [comment]
I think just displaying magenta is not very user friendly. Maybe we should create a texture with "texture not found" text instead (maybe on magenta background, just in case fonts are broken too)?

**Comment by gzotti** [comment]
I think we just had "crash" before. Magenta ("something is wrong") plus explanation in SUG 7.4 seemed better to me. If you want, please e.g. add a screen message.
