### ISSUE TITLE
Solar System Observer is located 1AU from the Sun regardless of how it's configured

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2911]
### Expected Behaviour

In `ssystem_major.ini`, we have the following line for `[solar_system_observer]`:
```
orbit_SemiMajorAxis=30
```

The expected effect is that the distance to the Sun is 30 AU, or at least that the distance changes when this value is changed.

### Actual Behaviour

In practice, the distance to the Sun is stuck at 1 AU no matter what value I configure for the observer's semi-major axis. In fact, all the observers appear to be at 1 AU from their parent.

### Steps to reproduce

1. Run Stellarium
2. Change location to Solar System Observer
3. Locate the Sun
4. Check _Distance_ item in the info panel, notice it's 1 AU
5. Zoom in to see the full Sun, notice that it fills the screen when FoV is ~0.5°, which confirms that it's 1 AU away.
6. Edit `ssystem_major.ini` to increase `orbit_SemiMajorAxis` of the observer 100×
7. Repeat the observation, note that the distance remains the same.

### System
* Stellarium version: v1.1-477-g581cad6fd3
* Operating system: Ubuntu 20.04

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/10215523/log.txt)

**Comment by gzotti** [comment]
This is stuck in a transition. Actually, the SSO was in an extremely wide orbit (configured with that entry)  without motion. I introduced a "gimbal orbit" that operates with certain key combinations (look into StelMovementMgr), but the chain of transformations to make it really useful is unfinished.

**Comment by gzotti** [comment]
What would be a good basis: Re-create StelMovementMgr, probably based on quaternions, with all possible "mount" frames. Basic operation should not change, but after that, the gimbal should be either in planet frame or in J2000 frame (switchable), and we could finally "officially" use ecliptical maps etc.

To recreate the old behaviour, change Orbit.hpp line 16.
