### ISSUE TITLE
Building configuration problem with ShowMySky

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#2913]
Since integration of ShowMySky, I cannot build it without manual intervention or just excluding it. 

### Expected Behaviour

Build successfully with MSVC2019+QtCreator 

### Actual Behaviour

Part of build log:

> [30/568 6.0/sec] Generating check version update
> FAILED: _deps/showmysky-qt6-build/check version update D:/StelDev/GIT/build-stellarium-Desktop_Qt_6_4_1_MSVC2019_64bit-Release/_deps/showmysky-qt6-build/check version update 
> cmd.exe /C "cd /D D:\StelDev\GIT\build-stellarium-Desktop_Qt_6_4_1_MSVC2019_64bit-Release\_deps\showmysky-qt6-build && true"
> Der Befehl "true" ist entweder falsch geschrieben oder
> konnte nicht gefunden werden.
> (Command "true" either misspelled or cannot be found)

### Steps to reproduce

Checkout from github, open project in QtCreator, run cmake and try to build. 

I cannot find where this command "... && true" is created, is this part of CPM? And what is the actual purpose of adding "... && true"? It is true when the first part is true and false when the first part is false, so IMHO it's not needed.

### System
* Stellarium version: master on 2022-12-14 
* Operating system: Windows 10 or 11
* Graphics Card: irrelevant

**Comment by 10110111** [comment]
I think I know where this `true` comes from: [here](https://github.com/10110111/CalcMySky/blob/master/CMakeLists.txt#L114). Now, I suppose the CI works fine because it uses PowerShell as the default shell on Windows. What can we use in place of `true` on `cmd.exe`?

**Comment by 10110111** [comment]
Try replacing `true` with `echo`.

**Comment by gzotti** [comment]
Yes, `echo.` works, finally! (with a point immediately after - no whitespace!)

**Comment by gzotti** [comment]
Works!

**Comment by 10110111** [comment]
I pushed the fix to CalcMySky. Won't bump the dependencies in Stellarium's CMakeLists, because 1) it's not required for the CI, 2) it's better to refer to a release rather than to a point of 3 commits after the release. If anyone needs this fix, they can install latest CalcMySky separately from CPM.

**Comment by gzotti** [comment]
OK for me personally if some new version from CMS will come in the next few months. For all self-builders on Windows, we would however need the above instruction in BUILDING.md: "After running cmake, edit _deps... in your building directory..."

**Comment by 10110111** [comment]
> For all self-builders on Windows, we would however need the above instruction

Well, this is uglier than just referencing a commit id. Feel free to do what you think is best. I still wonder why you get this error while CI doesn't.

Does PowerShell process `echo.` command as a no-op?

**Comment by 10110111** [comment]
Actually, I'll just push it. Done in ad4a4f24e8661613086c3414c5f1aa37114a780b.
