### ISSUE TITLE
Windows 7 and Stellarium

### ISSUE THREAD

**Issue by SonjaHemphill** [Stellarium/stellarium#2915]
### Expected Behaviour
Stellarium boots and runs at several frames a second or better.
### Actual Behaviour
With these drivers (Driver version string: "2.1.0 - Build 8.15.10.2869"), the program runs at roughly 10-13 FPS for a few seconds before crashing. It has GLSL version 1.2

With some older drivers, and in ANGLE mode, it'd run, but 2-3 FPS was very good (normally, IIRC in the 0.something-2 FPS range). 

### System
* Stellarium version: 0.22.2 (I'm running an older system, and your new version says Windows 10+)
* Operating system: Windows 7, SP1
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): PnP monitor 
* CPU:   Intel(R) Core(TM)2 Duo CPU     P9400  @ 2.40GHz
* System: Dell Latitude E4300
### Logfile 
2022-12-14T08:30:05
Operating System: Windows 7 SP 1 (6.1)
Compiled using MSVC++ 15.9 (Visual Studio 2017)
Qt runtime version: 5.12.6
Qt compilation version: 5.12.6
Addressing mode: 64-bit
Total physical memory: 4047 MB
Available physical memory: 1709 MB
Physical memory in use: 57%
Processor speed: 2394 MHz
Processor name: Intel(R) Core(TM)2 Duo CPU     P9400  @ 2.40GHz
Processor speed: 2394 MHz
Processor name: Intel(R) Core(TM)2 Duo CPU     P9400  @ 2.40GHz
C:\Program Files\Stellarium\stellarium.exe --mesa-mode -platform windows:altgr 
 -----------------------------------------------------
[ This is Stellarium 0.22.2 - https://stellarium.org/ ]
[ Copyright (C) 2000-2022 Stellarium Developers       ]
 -----------------------------------------------------
Writing log file to: "C:\\Users\\Alexandra.Fujioka\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\Alexandra.Fujioka\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\Alexandra.Fujioka\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "2.1.0 - Build 8.15.10.2869"
Current Format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
StelMainView::init
Detected: OpenGL "2.1"
Driver version string: "2.1.0 - Build 8.15.10.2869"
GL vendor is "Intel"
GL renderer is "Mobile Intel(R) 4 Series Express Chipset Family"
GL Shading Language version is "1.20  - Intel Build 8.15.10.2869"
GLSL Version Number detected:  1.2
This is not enough: we need GLSL1.30 or later.
You should update graphics drivers, graphics hardware, or use the --mesa-mode option.
Else, please try to use an older version like 0.12.9, and try there with --safe-mode
Config option main/ignore_opengl_warning found, continuing. Expect problems.
Sky language is  "en_US"
Planetary features language is  "en_US"
Application language is  "en_US"
Scripts language is  "en_US"
Max texture size: 4096
Cache directory is:  "C:\\Users\\Alexandra.Fujioka\\AppData\\Local\\stellarium\\stellarium\\cache"
Loaded 252 countries
Loaded 193 regions
StelLocationMgr::loadCitiesBin(): TimeZone for  "Anak"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Anbyon-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Anju"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Aoji"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Ayang-ni"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Chaeryong-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Changyon"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Chongjin"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Chongju"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Chunghwa"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Haeju"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Hamhung"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Hoeryong"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Hoeyang"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Hongwon"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Hukkyo-ri"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Hungnam"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Hwangju-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Hyesan"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Hyesan-dong"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Iwon-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Kaesong"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Kangdong-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Kanggye"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Kapsan-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Kilju"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Kosan"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Kowon-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Kujang-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Kusong"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Kyongsong"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Manp'o"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Musan-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Namp'o"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Namyang"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Ongjin"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Onsong"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "P'yongsong"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Pyongyang"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Rajin"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Ranam"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Sakchu-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Samho-rodongjagu"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Sariwon"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Sil-li"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Sinanju"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Sinmak"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Sinuiju"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Sonbong"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Songnim-ni"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Sunan"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Sunch'on"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Sungho 1-tong"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "T'ongch'on-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Uiju"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Wonsan"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Yonan-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Yonggwang-up"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Yuktae-dong"  not found:  "Asia/Pyongyang"
StelLocationMgr::loadCitiesBin(): Summary of unknown TimeZones:
"Asia/Pyongyang"
Please report these timezone names (this logfile) to the Stellarium developers.
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\Alexandra.Fujioka\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
SolarSystem has  190 entries.
Loaded 107 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15824 / 15826 items of planetary surface nomenclature
WARNING - These planets to assign nomenclature items were not found: "Dactyl"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
"Loading C:\\Users\\Alexandra.Fujioka\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_4_1v0_2.cat: 4_1v0_4; 1692779"
"Loading C:\\Users\\Alexandra.Fujioka\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_5_2v0_1.cat: 5_2v0_1; 7083058"
"Loading C:\\Users\\Alexandra.Fujioka\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_6_2v0_1.cat: 6_2v0_1; 24670782"
Finished loading star catalogue data, max_geodesic_level:  6
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4942 / 4942 scientific star names
Loading scientific star extra names from ".\\stars\\default\\extra_name.fab"
Loaded 26200 / 26200 scientific star extra names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 22992 / 22992 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108378 / 108378 cross-identification data records for stars
Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
Loading proper motion data from ".\\stars\\default\\hip_pm.dat"
Loaded 117955 / 117955 proper motion data records for stars
StelCore: Invalid timezone name: ""  -- not setting timezone.
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.16 (standard edition)"
Loaded 94663 DSO records
Loading DSO outline data ...
Loaded 98 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Got location "Sitka, Alaska, United States (57.0514, -135.317; America/Sitka)" for IP "209.165.147.1"
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 1099 / 1099 common star names
Loading DSO name data ...
Loaded 1212 / 1236 DSO name records successfully
WARNING - No position data for 24 objects: "NGC 4173, PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1000714, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Loaded 84 / 84 asterism records successfully for culture "western"
Loaded 74 / 74 asterism names
stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...
QOpenGLFramebufferObject: Unsupported framebuffer format.
QOpenGLFramebufferObject: Unsupported framebuffer format.
QOpenGLFramebufferObject: Unsupported framebuffer format.
QOpenGLFramebufferObject: Unsupported framebuffer format.
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\Alexandra.Fujioka\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\Alexandra.Fujioka\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\MeteorShowers.json"
[MeteorShowersMgr] Version of the format of the catalog: 2
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\Alexandra.Fujioka\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Observability"
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at:  "C:\\Users\\Alexandra.Fujioka\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
QOpenGLFramebufferObject: Unsupported framebuffer format.
QOpenGLFramebufferObject: Unsupported framebuffer format.
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.

**Comment by SonjaHemphill** [comment]
Try this link for a screenshot.
https://pdfhost.io/v/tXE1c06EK_Untitled_document

**Comment by SonjaHemphill** [comment]
Also there's this annoying overlay thing... Am trying another link for a screenshot.
https://pdfhost.io/v/rPc1783iS_Untitled_document

**Comment by gzotti** [comment]
You have confirmed a dialog that warned you of upcoming problems. Since then, these lines are written to the logfile:

> Detected: OpenGL "2.1"
> Driver version string: "2.1.0 - Build 8.15.10.2869"
> GL vendor is "Intel"
> GL renderer is "Mobile Intel(R) 4 Series Express Chipset Family"
> GL Shading Language version is "1.20 - Intel Build 8.15.10.2869"
> GLSL Version Number detected: 1.2
> This is not enough: we need GLSL1.30 or later.
> You should update graphics drivers, graphics hardware, or use the --mesa-mode option.
> Else, please try to use an older version like 0.12.9, and try there with --safe-mode
> Config option main/ignore_opengl_warning found, continuing. Expect problems.

The Intel graphics of yesteryear was not capable of running Stellarium, and in some earlier versions the ANGLE/MESA links did not work. Please follow instructions to set 2 environment variables. https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#forcing-graphics-mode-windows
