### ISSUE TITLE
Wrong phase angle of waning moon

### ISSUE THREAD

**Issue by SMi1984DE** [Stellarium/stellarium#2916]
### Expected Behaviour

The lunar phase angle should be 72 degrees + 180 degrees (waning moon) = 252 degrees, in this example, not 72 degrees, because the phase angle should represent the different phases of the moon (and it's movement arround the earth/a full circumnavigation) from 0 degrees (=New Moon) over 90 degrees (first quarter), 180 degrees (=Full Moon), 270 degrees (last quarter) (back to) to 360 degrees/0 degrees (New Moon).

Otherwise the phase angle will never reach a value above 180 degrees. So it's only nessecary to add a value of 180 degrees after Full Moon, if the "phase angle" is beeing calculated with help of the "moon phase" value "P" in percentage.

(for example: The moon has 50% illumination at two times. At first quarter (waxing moon) = 50% and at last quarter (waning moon) = 50% as well. The calculation of the phase angle (f) with help of the common formula below only considers the phase from waxing moon.

`f = cos-1 [ 2P / 100 - 1]`

see also
http://castor2.ca/16_Calc/01_Moon/03_Phase/index.html
and
https://www.projectglobalawakening.com/moon-phases/

### Actual Behaviour
phase angle is +72 degrees

![phase_angle](https://user-images.githubusercontent.com/120596291/207688507-b304cdde-2d62-4b91-bbb2-f884dda34892.jpg)

### Steps to reproduce
n/a

### System
* Stellarium version: 1.1.1-macOS (Stellarium.app Version 0.22.4-8cc1565
* Operating system: macOS Big Sur (Version 11.7.1)
* Graphics Card: AMD Radeon R9 M290X 2GB
* Screen type (if applicable): iMac Retina 5k, 27")

### Logfile 
n/a

**Comment by SMi1984DE** [comment]
btw. Stellarium is a great planetarium software. I like it very much. It's easy to use and has a lot of functions and informations. I think, you spend a lot of time for developing. ;) Thank you... 👍  👍 👍 👍 👍 👍

**Comment by gzotti** [comment]
The phase angle is the angle Sun-object-observer and is 0...180°. Your idea implies that "phase angle" for the Moon must be defined differently than for planets. Can you give a reference? Or do you just mean elongation? 
And yes, we spend a lot of time, maybe too much. And then some.

**Comment by SMi1984DE** [comment]
Okay, I understand the difference and it's not easy to find an explicit (or one-to-one) reference for this value "moon phase angle". I'm going to look for an explicit one in the next days.

Obviously both variants for the same term are existing and it's more a question of the personal view, I think. But in fact it's the same result. 😵‍💫 Only with other values. ;o) Maybe it's simply an other definition for the same thing - on one side, when the moon-earth-system (and moon's orbital movement arround the earth) is the reference (full orbit = 360 degrees or 2*pi) and on the other side, when the angle between moon, sun and earth is dispositive (angle = max 180 degrees).

But in last version it's not very clear, where the postition of moon is, when the angle is 90 degrees for example. Is it waning or waxing moon? You can say one angle is positive and the other is negative, but which one is positive and which one is negative? Negative, when moon is moving towards the sun? Or maybe on waning moon? Then you need the moon-earth system from the first definition as reference again. Or is the difference between postive and negative angles (or angle deviations) a result of the ecliptic (are there negative values at the moment)? Will the angle reach 180 degrees only on solar eclipse? Then I will never find out for example (with help of this value), at which time we have "New Moon", except on solar eclipse (or when the angle is suddenly increasing after decreasing before/I have to catch exactly this moment, but when it's possiblie for me (or my computer) to search for "0 degrees", it's quite more easier). The same is valid for "First Quarter", "Last Quarter", etc. With this value (for example 90 degrees), I will never be certain if there is really "First Quarter", "Last Quarter", etc., when the angle has a positive proportion by default, from the inclination of the ecliptic.

With a range between 0 and 360 it's easier to find out, if moon is waning or waxing AND it's easier to find out, if there is (exactly) "Full Moon" (180 degrees) or (exactly) "Last Quarter" (270 degrees) and on "Last Quarter" it's easy to know, that the angle between sun-earth-moon is (nearly) 90 degrees. ;) *) Otherwise I have to look for the inclination of moon's ecliptic and the ecliptic of the sun, to get the difference, if I need this value (the angle I get as additional amount by default in first definition). But as I wrote at the beginning, it's more a question of the viewers perspective. Maybee it's more important for astronomers to get this type of "moon phase angle", descriped in first definition. I would work with the "angular distance" for this purpose, which represents this behavior from the first definition in a better way in my eyes, so you can use the second definition for the "moon phase angle". ;o)

Okay, as I wrote at the beginning, I'm going to look for a scientific one-to-one reference. The actual version is not wrong for certain, but maybe the other one is the better one (for me). ;o) Stellarium, in any case, is a very great software. Thank you for investing your time...


<img width="730" alt="moonearthsun" src="https://user-images.githubusercontent.com/120596291/208249014-fec8e051-3c03-42c0-9d59-704e497be7e1.png">

**Comment by gzotti** [comment]
You just need to read the Elongation value for what you mean: 0/360=New Moon; 90=First quarter; 180=Full Moon; 270=Last Quarter.

**Comment by SMi1984DE** [comment]
> You just need to read the Elongation value for what you mean: 0/360=New Moon; 90=First quarter; 180=Full Moon; 270=Last Quarter.

The elongation is the same like the your definition of the "moon phase angle" (360° - "moon phase angle" = "elongation") and will never reach 360 degrees as well. :/ The elongation and the "first definition" of the "moon phase angle" are the same values in the meaning. A reverse value from 360 degrees. You can retrace it, when you search for an elongation with a value of 270 degrees. This is not "Firtst Quarter" or "Last Quarter" etc. and you never reach 0/360 degrees as well...

**Comment by gzotti** [comment]
OK, sometimes you need to do some mental gymnastics, but with the right data.  Just one line below that you can read "Elongation (&Delta;&lambda;<sub>s</sub>)". Now find out what E or W mean.
