### ISSUE TITLE
I see trees and houses on Moon

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#2921]
### Expected Behaviour
Expected to see Moon landscape. Craters and so on. Or other planet landscape where you be.

### Actual Behaviour
I see trees and houses on ground. Just landscape of Europe "Guereins".

### Steps to reproduce
1. Start Stellarium
2.  Set location to Moon and Serenity sea or so on.
3. Set Atmosphere off if it is on

### System
* Stellarium version: <Stellarium-1.1-c47a4d8-x86_64.AppImage>
* Operating system: <Kubuntu 22.10>
* Graphics Card: <MSI GeForce GT 1030 2GH LF OC>
* Screen type (if applicable): 3440x1440 LG 34GK950F

### Logfile 
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.
(I remember that it writes to log this line too when I am at Tellus.)

**Comment by alex-w** [comment]
Does you have enabled “Auto select landscapes” option?

![image](https://user-images.githubusercontent.com/88731/208440018-a7c47c8e-d165-4793-a3c6-2748d17b05d4.png)

**Comment by ilkant** [comment]
I checked the AUto select landscapes. The trees wre there still. And then I shut the Stellarium down and started again. The trees are still on Moon.

And a wish. The save settings could be visible on all tabs Main, Information, Extras, Time, Tools. So when I change Tools settings I have not to go first to Main tab and then save settings.

**Comment by gzotti** [comment]
You must check Auto select landscapes (and Save Settings to keep this behaviour), then switch to the Moon. 

We (developers) disagree on the necessity to explicitly press "Save Settings". IMO we could even remove it, or reduce to a few very critical things. For now we keep this centralized requirement, but some secondary choices like colors are stored immediately.

**Comment by ilkant** [comment]
Seems to work now. Thanks!
