### ISSUE TITLE
Black screen with spout sender 

### ISSUE THREAD

**Issue by jatolimon** [Stellarium/stellarium#2922]
### Expected Behaviour
Spout sender working

### Actual Behaviour
Spout demo receiver just show a black screen. It detects stellarium and show resolution, but no image at all. 

### Steps to reproduce
Run stellarium with spout sender. Run other software with spout receiver. 

### System
* Stellarium version: tried the last 3 ones and the last beta

* Operating system: tried on 2 different pc's with win 10 and 11

* Graphics Card: nvidia 2070 supper and 3060ti.

* Screen type (if applicable): 4k monitor and 4k screen

**Comment by jatolimon** [comment]
Solved changing resolution to 1920x1080 while both programs where working. Changed back to 4k resolution and still works.

**Comment by jatolimon** [comment]
Is there a way of sending more resolution through spout than than the one of the stellarium window?

**Comment by gzotti** [comment]
No, this is not possible.

**Comment by gzotti** [comment]
I saw an issue with a new installation of Win11, Geforce3070Ti with Optimus gaphics. Spout initially launched on the Intel side of graphics, resulting in a black Spout window despite it recognizing the stellarium sender. Use NVidia control panel to force SpoutReceiver running on the Geforce as well. This hint goes into the FAQ or even SUG for 23.1.
