### ISSUE TITLE
Telescop control : cannot open serial device 

### ISSUE THREAD

**Issue by Tristian68** [Stellarium/stellarium#2934]
### Expected Behaviour:
I have a NexStar compatible telescop controler which can conect at Stelarium throught Bluetooth on my celularphone an works prety well. I  expect to do the same on Stelarium 1.1 or 1.2  on Windows 10  ( the controler was working ok with somme old version of stelarium on a Lenovo YOGA Laptop Windows 10)

### Actual Behaviour
I get in the log file: "ERROR creating TelescopeClientDirectNexStar: cannot open serial device "COM5"
TelescopeClient::create(): Unable to create a telescope client." 

I can tell you that if I connect on COM 5 with Putty and send some comands to the controler i receive good answers ( so the BT connection via COM 5 is working).

### System
* Stellarium version: <stellarium-1.2-qt6-win64?>
* Operating system: <Windows 10 Version 22H2>
*Laptop ASUS ExpertBook 

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/10300576/log.txt)

**Comment by gzotti** [comment]
We just had a similar report (#2924) about COM port issues. Can you try the Qt5-based build (available tomorrow)?

**Comment by Tristian68** [comment]
Thank You, The Qt5 is working fine and now I can conect the Telescope controler via BT with Stelarium 1.2.


    On Sunday, December 25, 2022 at 10:40:37 PM GMT+2, Georg Zotti ***@***.***> wrote:  
 
 


We just had a similar report (#2924) about COM port issues. Can you try the Qt5-based build (available tomorrow)?

**Comment by faggio79** [comment]
Hello everybody. I'm experiencing the same identical issue with an Orion (Skywatcher) Synscan V5 hand controller. Until i used stellarium version 0.xx everything was working fine. Since 1.0 version i get always "stopped" status and cannot control my mount. Currently i'm using version 1.2.5 qt6, but the plugin still not working.

Thanks a lot for opening this issue!

**Comment by gzotti** [comment]
If you see the other reports on this, please conclude that trying Qt5-based 1.2 (0.22.5) is your best option currently.

**Comment by achellet** [comment]
> 

Thank you for the advice . It's ok Qt5-based 1.2 (0.22.5)
I'm ok to test any Qt6 version.

Thanks a lot

**Comment by rbk1rbk** [comment]
I can also confirm, that win 32 bit Qt5 version works, win 64bit version doesn't.
Building stellarium from source is beyond my skills. Checking the `SerialPort.cpp` I would expect some of these messages in the log, but I don't see any; only the message from `Lx200Connection::Lx200Connection` functions. Maybe it helps.

**Comment by gzotti** [comment]
Yes, sure, please go ahead. I have no hardware and no time these months to deal with this, unfortunately. It needs motivation like an own non-working instrument to fix that :-)

**Comment by Tristian68** [comment]
Hello,I installed the stellarium-23.2-a69d242-patch-qt6-win64 over the stellarium-23.2-qt6-win64 and I can confirm that the connection with an Nexstar compatible GoTo over a serial connection ( even bluetooth) is working wery well.The PC was an ASUS ExpertBook I5 and Windows 11Pro 64bit
All the best,Tristian


    On Wednesday, July 5, 2023 at 06:18:07 PM GMT+3, github-actions[bot] ***@***.***> wrote:  
 
 


Hello @Tristian68!

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
