### ISSUE TITLE
astronomical calc: show current object

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2937]
**Is your feature request related to a problem? Please describe.**
I've calculated the path of a comet, but I can't see it unless it is selected.
Related: #1427

**Describe the solution you'd like**
Add an option in the astrocalc dialog to highlight the object(s) that has/have been selected (irrespective of actual magnitude/visibility), so that it is visible even without selection.

![image](https://user-images.githubusercontent.com/3529789/209571892-500229bc-fe9b-45fc-92dc-a83b4a8fe1ee.png)

**Describe alternatives you've considered**
select the object.

**Additional context**

**Comment by alex-w** [comment]
Apparently I don’t understand the request for selection without selecting, but did you tried select any line in table?

**Comment by axd1967** [comment]
Selecting a line inside the table does highlight a position along the computed path (as in #1200), and double-clicking jumps to that direction in time, but that's not what I want.

The problem with that approach is that I lose the overview of the sky; I want to be able to see how (e.g.) a comet moves relative to other objects (as I can do with e.g. planets relative to DSO), but I cannot do so without a focus on that object, because often the object is too .

The idea is (1) to see a symbol (similar to a planet marker, if possible a bit larger) regardless of the computed magnitude (2) that corresponds to the **currently** selected time (rather than the time of a computed row in the astrocal dialog).

A solution could be to show a special marker(s) that corresponds to the position of the objects (there could be 2) in the astrocal dialog, computed for the **current time** (regardless of the computed rows in the astrocal dialog). A checkbox in the astrocal dialog could implement this: "show as marker" or something. The marker could be large enough so that it shows up on top of astrocalc plots.

Note that the marker(s) could be drawn  _without any astrocal data_  (because their positions must be recomputed anyway).

## Workaround
Disable the SSO magnitude limit to show the comet position regardless of its actual brightness. It might also be necessary to also disable the atmosphere and/or increase the amount of labels/markers. This still poses a problem in that too much information is present in the display:

![image](https://user-images.githubusercontent.com/3529789/209580398-cbfb3b32-7568-4c60-bc5d-8e8bbb5471f7.png)
