### ISSUE TITLE
Maybe Wrong Exoplanets

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#2938]
### Expected Behaviour
Not such exoplanets pile. Maybe a bug?

### Actual Behaviour
![image](https://user-images.githubusercontent.com/18149564/209583810-9ee2b9b2-f626-4d04-b73c-b7f44befb993.png)

### System
* Stellarium version: <Stellarium 1.2 compiled from source-code>
* Operating system: <Kubuntu, 22.10>
* Graphics Card: <NVIDIA GeForce GT 1030/PCIe/SSE2 3.3.0 NVIDIA 515.86.01>
* Screen type (if applicable): 3440x1440 LG 34GK950F

### Logfile 
[Exoplanets] loading catalog file: "/home/user/.stellarium/modules/Exoplanets/exoplanets.json"

**Comment by gzotti** [comment]
Of course there is. Kepler. All is OK.
