### ISSUE TITLE
cannot filter shortcut dialog

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2939]
### Actual Behaviour
![image](https://user-images.githubusercontent.com/3529789/209586124-12a4d540-ffd7-41bb-9259-8e3d08f066ca.png)

### System
* Stellarium version: 

Stellarium 1.2+
Version 0.22.5-239b713 [master]
Based on Qt 5.12.8

* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
What you may expect works for me (V1.2-qt6, Win11)

**Comment by alex-w** [comment]
Cannot reproduce with Qt6, but it exist with Qt5
