### ISSUE TITLE
Copy+paste to object info

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#2942]
**Describe the solution you'd like**
When I click with mouse an object in the sky, it displays top left corner an information of that object. I want topy+paste for example Azimuth value (or all) to clipboard. So, I could be able to copy the information to some other application. For example to text processing application. Now Stellarium doesn't have such feature.

**Comment by alex-w** [comment]
Stellarium can do it. Please read Stellarium User Guide or list of shortcuts within planetarium (F1 or F7)
