### ISSUE TITLE
astrocalc silently drops outdated orbits and connects

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2943]
### Expected Behaviour

1. continue the calculations despite elements outdated but color the output rows e.g. red to indicate to the user that the data might not be reliable
2. left text block: help the user: show **how much days** the orbital elements are outdated (rather than just issue the warning); show the validity period rather than just a warning.

### Actual Behaviour
Bug: two objects get connected by a line, probably because (7) Iris elements are no longer valid

![image](https://user-images.githubusercontent.com/3529789/209802304-94c84a56-8a7d-4111-84c7-0881a2940306.png)

Maybe: 
https://github.com/Stellarium/stellarium/blob/647b3f2e6f4583bd890604a5facfbae8dbcea1a4/src/gui/AstroCalcDialog.cpp#L1906-L1909

btw - magic const:
https://github.com/Stellarium/stellarium/blob/647b3f2e6f4583bd890604a5facfbae8dbcea1a4/src/core/modules/SolarSystem.cpp#L1544

Probably `StelCore::JD_HOUR` ? used in 5 places.

### Steps to reproduce

1. set time to 2023-04-21 (i.e. today+5m-7d, but probably irrelevant)
3. open astrocal dialog
4. select (136199) Eris and (7) Iris
5. set from: 2023-03-28 1135 to: 2023-05-30 1135 step: 1 solar day

Suspected to be related to #2000 
## Workaround
 suggested workaround of #2000 (updating `orbit_good`) helps, 

except  that the warning in the info text block still appears, probably due to a difference between
https://github.com/Stellarium/stellarium/blob/647b3f2e6f4583bd890604a5facfbae8dbcea1a4/src/core/modules/Planet.cpp#L4842-L4857
and the definition/use of `orbit_good`.

### System
* Stellarium 1.2+
Versie 0.22.5-239b713 [master]
Gebaseerd op Qt 5.12.8

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-135-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

**Comment by gzotti** [comment]
At what time elements are outdated depends on too many factors, esp. on your expectation of accuracy. This is an estimate, and no hard limit can be given. Do you understand "estimate", "best effort" etc? You can still compute results outside our recommendation, but expect GIGO results, hence the warning. For best results, use elements with epoch only days away from observation. 

Re `StelCore::JD_HOUR`: ACK.

**Comment by axd1967** [comment]
> Do you understand "estimate", "best effort" etc?
15 years.

**Comment by alex-w** [comment]
@axd1967 please check 23.2RC2 - we added flag to ignore valid range for orbits
