### ISSUE TITLE
astrocal: skip unlabeled markers

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2951]
When ticking "Skip draw the unlabelled markers also" and unticking "dates", markers are still plotted.

### Expected Behaviour

Without dates, markers should only be plotted every N steps if the "skip" checkbox is set. 
(Please ignore the displaying of dates in the screenshot)

![image](https://user-images.githubusercontent.com/3529789/209949532-9288b367-03ea-4cc3-9267-f6a355aa93bd.png)

### Actual Behaviour

When date plotting is disabled, all steps are plotted regardless of the "skip" checkbox.

![image](https://user-images.githubusercontent.com/3529789/209949498-2f319f49-7e76-4d98-bfe8-3c2d8596cb78.png)

### System
* Stellarium 1.2+
Version 0.22.5-239b713 [master]
Based on Qt 5.12.8
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-135-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
> Without dates, markers should only be plotted every N steps if the "skip" checkbox is set.

Why expected it? With the selected options markers shouldn't plotted.
