### ISSUE TITLE
Text of coordinates is clipped at the top of the screen

### ISSUE THREAD

**Issue by siegbert7** [Stellarium/stellarium#2955]
Text of coordinates is clipped at the top of the screen

### Expected Behaviour
Full text readable on the screen

### Actual Behaviour
For screenshot see attachment

### Steps to reproduce
Start Stellarium, turn on "Equatorial Grid", look at the top of the window

### System
* Stellarium version: Stellarium 1.22.5
* Operating system: windows 10
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
![Stellarium Text Clipped](https://user-images.githubusercontent.com/48695821/210103435-cc7b3254-a418-49cc-9f4a-fb164ff8aa60.png)

**Comment by alex-w** [comment]
Please share log from Stellarium

**Comment by gzotti** [comment]
OP means the minuscule cut of a few pixels that has been there forever. A truly tiny thing that needs a little adjustment.

**Comment by alex-w** [comment]
> OP means the minuscule cut of a few pixels that has been there forever. A truly tiny thing that needs a little adjustment.

I fear the issue related to HiDPI.

**Comment by 10110111** [comment]
> I fear the issue related to HiDPI.

No, I easily reproduce it on Ubuntu with 100% scale factor.

**Comment by siegbert7** [comment]
Thanks. It's good now !

Siegbert
________________________________
Von: github-actions[bot] ***@***.***>
Gesendet: Montag, 27. März 2023 08:48
An: Stellarium/stellarium ***@***.***>
Cc: siegbert7 ***@***.***>; Mention ***@***.***>
Betreff: Re: [Stellarium/stellarium] Text of coordinates is clipped at the top of the screen (Issue #2955)


Hello @siegbert7<https://github.com/siegbert7>!

Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest
