### ISSUE TITLE
search window: include current position

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2960]
**Is your feature request related to a problem? Please describe.**
(1) I sometimes want to plot computed positions in my viewport. However, when I activate the Position tab of the Search Window, it starts up with coordinates 0,0. Thus, when I want to go back to my previous viewport, I need to enter the center coordinates of the viewport before I can start my actual task.

(2) The workaround is to look up the current coordinates. Sometimes I need to enter positions in a different coordinate system, but switching between coordinate systems resets the currently stored values.

**Describe the solution you'd like**
(10 Include a button "Go to current position". The dialog is then pre-filled with the coordinates of the center of the viewport.

(2) Recompute the coordinates when switching between coordinate systems, so that the search center does not jump.

**Describe alternatives you've considered**
Find the current coordinates, then slew to the desired position by filling those in the dialog.

**Additional context**
![image](https://user-images.githubusercontent.com/3529789/210157532-bc0f9524-e157-4ee8-aeb4-d58c124e6f73.png)

**Comment by gzotti** [comment]
When using azimuth from south, azimuth is wrong! Maybe connect the AzimuthFromSouthChanged signal. 

... aww, just missed the merge...
