### ISSUE TITLE
Stellarium 1.0+ no longer installs on Windows 11 arm64

### ISSUE THREAD

**Issue by tjzepf** [Stellarium/stellarium#2962]
### Expected Behaviour

Prior to Stellarium 1.0, the software would install and operate fine on a Windows arm64 installation running on a M1 Mac under Parallels.

### Actual Behaviour

The install fails with "This program can only be installed on versions of Windows designed for the following processor architectures: x64"

### System
* Stellarium version: stellarium-1.2-qt6-win64.exe
* Operating system: Windows 11 21H2 (arm64)
* Graphics Card: M1 (Parallels Emulation)
* Screen type (if applicable): N/A

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by tjzepf** [comment]
![Screenshot 2023-01-01 at 8 50 36 AM](https://user-images.githubusercontent.com/7686213/210176950-90351aa7-21b6-4a00-9af9-c368b1532063.png)

**Comment by gzotti** [comment]
While I don't understand why anyone would want to run an emulation while there is a native version for macOS on ARM, you could try to run the Qt5-based Windows version in the emulator. Or just use the native version.

**Comment by 10110111** [comment]
> you could try to run the Qt5-based Windows version

This doesn't make any principal difference: the error is about instruction set architecture, which obviously isn't compatible, regardless of the libraries used.

So, the only sensible solution is to use the native macOS version. If one really needs to run Stellarium in a Windows virtual machine, the VM should emulate an x86_64 CPU (x64, if we use Microsoft's terminology).

**Comment by tjzepf** [comment]
Windows arm64 has a quite robust emulation for x64 binaries. Stellarium 0.22.2 runs flawlessly under this emulation. As for why not run native on MacOS, this is the use case:

I am an astrophotographer, and give demonstrations of image acquisition on my Mac using simulated astrophotography hardware. Most of this software only runs under Windows (sigh), so I need to operate in a Windows environment. Running Stellarium with the Telescope Control plugin is nice to have as it helps visualize where the telescope is pointing.

I realize this is not a mainstream use case, but there is a nascent but growing collection of hardware that can run Windows 11 on ARM. As the software (at least used to) run fine under emulation, this seems like a simple modification to the architecture check during install.

**Comment by gzotti** [comment]
@10110111 I am also aware that the architecture of our qt5 build should also just be x64, however, if previous (only qt5-based) versions worked, so may the new qt5-based build. There is no arm64 Windows build of Stellarium so far. How many arm64-Windows systems are out there? I think they are coming, but only as tech previews. (?)

@tjzepf With your specifying TelescopeControl plugin, my recommendation gets stronger. We have a handful of reports that indicate the TelescopePlugin in the Qt6 builds has some problem. Please try the qt5-based build.

**Comment by tjzepf** [comment]
@gzotti , yes the qt5 version installs fine. Oddly, though, the Telescope Control plugin does not list ASCOM as a choice for telescope control. Neither does it list ASCOM for the 0.22.2 version either.

**Comment by gzotti** [comment]
You need to install ASCOM drivers before using that. Please see the User Guide, I don't use this part of the program.

**Comment by alex-w** [comment]
> @gzotti Do we not provide a Windows arm64 build?

No. Qt 6.4 has a technical preview for support Windows/arm64, but without important libraries.

**Comment by alex-w** [comment]
We can allow installation win64 application into arm64 environment, but... I fear this is bad idea.

**Comment by timthorn** [comment]
> We can allow installation win64 application into arm64 environment, but... I fear this is bad idea.

Is your concern that things will break? As @tjzepf says, x64 emulation on Arm in Windows 11 is quite robust, though in previous versions only x32 emulation existed (later Insider builds of Windows 10 did have x64 emulation but it's only in Windows 11 that it is officially supported).

Happy to test a drop on a Lenovo Thinkpad X13s and my son's Microsoft Surface Pro 9, if that would help.

**Comment by alex-w** [comment]
@tjzepf @timthorn please check this snapshot - https://ci.appveyor.com/api/buildjobs/8oyl7cth94hhq67b/artifacts/stellarium-23.0-843567a-qt6-win64.exe

**Comment by timthorn** [comment]
Thanks @alex-w. The CI system's limit for downloads of that file has been hit so I'm unable to get the binary today, but I'll keep trying over the next few days.

**Comment by timthorn** [comment]
Thanks again @alex-w. The build looks to work for me. Performance isn't great (out of the box, 2-3FPS in MESA mode and 5-6FPS with acceleration, but turning satellites and ground off gets to a very usable ~15FPS).

Although you say that important libraries are missing, could building with Arm64EC help? I think that's meant to allow you to mix x86 and Arm code in the same process. More here: https://learn.microsoft.com/en-us/windows/arm/arm64ec

**Comment by alex-w** [comment]
> Thanks again @alex-w. The build looks to work for me. Performance isn't great out of the box (2-3FPS in MESA mode and 5-6FPS with acceleration) but turning satellites and ground off gets to a very usable ~15FPS.

OK, the original issue is fixed

> Although you say that important libraries are missing, could building with Arm64EC help? I think that's meant to allow you to mix x86 and Arm code in the same process. More here: https://learn.microsoft.com/en-us/windows/arm/arm64ec

Some important Qt modules are not ported to Windows/arm64 architecture, so, we'll wait the full support ARM64 by framework.

**Comment by timthorn** [comment]
Thanks @alex-w.

> Some important Qt modules are not ported to Windows/arm64 architecture, so, we'll wait the full support ARM64 by framework.

My point was that because ArmEC allows interworking of x86 and native Arm code which will deliver some speedup, you might not need to wait for all the modules to be ported. Of course, if you want to do a single piece of work to target full native, I understand - and in any case greatly appreciate you enabling the installer to work on Windows on Arm.

On Qt, is it just Qt Webengine that you need but are missing?

**Comment by alex-w** [comment]
> On Qt, is it just Qt Webengine that you need but are missing?

Nope. Serial ports missing too.

**Comment by hmartinez82** [comment]
I've got it compiling and launching natively for ARM64. Albeit using MSYS2 as the dev environment and Clang as the compiler https://github.com/msys2/MINGW-packages/pull/18653

**Comment by alex-w** [comment]
> I've got it compiling and launching natively for ARM64. Albeit using MSYS2 as the dev environment and Clang as the compiler [msys2/MINGW-packages#18653](https://github.com/msys2/MINGW-packages/pull/18653) and without the Telescope plugin, ShowMySky or QtWebEngine

`-DENABLE_MEDIA=Off` should be enough to disable media support

**Comment by hmartinez82** [comment]
I don't think that Media support was the issue The issue was that MSYS2 already has a Qt version that has the fix for https://bugreports.qt.io/browse/QTBUG-105984, I'm going of course to upstream the fix here sometime soon (which is to compare Qt 6.4.0 or less than 6.4.1). I have a bunch of questions regarding the dependencies needed for Telescope and ShowMySky too.

**Comment by 1963m** [comment]
Tengo instalado el Stellarium 0.22.0 en Windows 11 y el problema es que a la hora de control de telescopio este solo se mueve en dirección suroeste mientas si apunto a un objeto dirección sureste el telescopio no gira,otro problema es que cuanto el telescopio hace un giro largo el nombre del telescopio y la diana desaparece

**Comment by gzotti** [comment]
@1963m You are commenting in an unrelated and closed issue thread, and in a language at least most of the developers have to use a translator. In addition, you don't say what kind of telescope you have. And you are using an outdated version. As visible in numerous other places here, there are unsolved issues with telescope support in 1.0+/Qt6. We will not investigate new spurious problems reported in 0.22 in an unrelated issue thread when they cannot be reproduced in 23.3.

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
