### ISSUE TITLE
Large Magellanic cloud missing

### ISSUE THREAD

**Issue by johnbellora** [Stellarium/stellarium#2963]
The Large Magellanic cloud is conspicuously missing Every southern hemisphere photo clearly shows both small and large Magellanic clouds clearly visible. Please add it. The Small Magellanic cloud looks great Please add with a close as possible coordinate to the brightest spot.

Best regards
![image](https://user-images.githubusercontent.com/63178816/210204665-0af47248-ab81-4eae-83af-924d0de829c8.png)
![image](https://user-images.githubusercontent.com/63178816/210204814-7f77e45c-8fc1-47a7-b037-47a2673c5a75.png)

John Bellora
858-776-2189

**Comment by 10110111** [comment]
Please show steps to reproduce. I have both of them visible and selectable.

**Comment by Atque** [comment]
They are visible, but are somewhat dim (which corresponds to their appearance in nature). Try increasing the brightness of the Milky Way, as they are in the same texture. Zooming in enough will show the DSO textures.

**Comment by johnbellora** [comment]
Thank you my mistake

John

**Comment by johnbellora** [comment]
Thank you, My mistake

**Comment by johnbellora** [comment]
Thank you, My mistake.
John


-----Original Message-----
