### ISSUE TITLE
Guide Chapter 4

### ISSUE THREAD

**Issue by hdquemada** [Stellarium/stellarium#2984]
Not a bug per se, but I noticed the users guide chapter 4 doesn't match what I see in the version 1.2 (linux) of Stellarium I have installed on my laptop. I'm happy to propose re-writes to match that version, which will require more than just a few minor fixes. But I didn't want to do so without checking if it's OK with the developers.  If I have permission, I'll work on it.

**Comment by gzotti** [comment]
There is continuous development. Actually the Guide should grow together with the program. Did we forget updating something? Is anything unclear? Sure, please go ahead.

**Comment by gzotti** [comment]
@hdquemada did you write something?

**Comment by gzotti** [comment]
IIRC, we have discussed or even accepted some improvements in the past year. We can probably consider this solved, or expect a new PR on further updates.
