### ISSUE TITLE
Character Error in Korean Installer

### ISSUE THREAD

**Issue by ysjbserver** [Stellarium/stellarium#2988]
### Expected Behaviour
When installing Stellarium, some Korean text appears as rather 'strange'. I tried to find original texts of these messages, but since they are too corrupted, I can't find them.

### Actual Behaviour
![캡처](https://user-images.githubusercontent.com/37777205/211912813-104a792f-3591-43c1-9806-c38c595e0794.PNG)

![2](https://user-images.githubusercontent.com/37777205/211912809-d12c7608-822c-43ef-9d1a-8f835c63a69e.PNG)

And when creating links for desktop, links were not generated. I think the links' names were also corrupted.

![3](https://user-images.githubusercontent.com/37777205/211913656-239bf7e4-6367-495e-8c45-b53d48ccdb7e.PNG)

This warning message is repeated about 8 times, with slightly different link addresses. Warning message and error code itself doesn't change.

### Steps to reproduce
Select "Korean" (or whatever the corrupt text thing is) in Installer. I only tested with Windows because that's the one I only have, but I doubt it'll be different.

### System
* Stellarium version: 1.2 (Latest)
* Operating system: Windows 10
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

Since this happens in installer, I don't think there is any log generated, but if I'm wrong, let me know and I'll find it.

**Comment by gzotti** [comment]
We developers do not understand the Korean text, this is part of the installation program. Somebody would have to translate what is shown here to give us at least a chance to understand what is happening here.

**Comment by 10110111** [comment]
At the very least the "?ъ", "??" in the Korean text, and "￦" instead of "\" or "/" in the installation path are definitely wrong.

**Comment by 10110111** [comment]
Some questions to the reporter:

1. Is the system language of your OS Korean?
2. Was this problem present in Stellarium 1.1 installer?
3. Is this problem also present in Stellarium itself after installation?

**Comment by ysjbserver** [comment]
1. Yes it is. If you need I can change it to English and try installing in Korean.
2. I just tried and it was present. I tried going back and at 0.21 it was still present. I think it's a very old problem.
3. No, it only appears in the installer. As far as I know, there isn't any error text in the main program.

And just to be clear, '￦' is used in Korean as substitute for '\'. ('￦' is not error) It's stupid, but it is standard in Korean fonts. Everything else is font error.

**Comment by ysjbserver** [comment]
For some context:

- First picture is the very first window, selecting installation language.
- Second picture is about creating desktop shortcut. Making shortcut message itself isn't corrupted, but 2 lines below that are showing as corrupted.
- Third is final stage of installing, when creating desktop shortcuts.
