### ISSUE TITLE
moon culmination data problem

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2990]
Hello, With the astronomical calculations (F10 of the Stellarium interface) I asked to see the culminations of the moon over a given period. I then downloaded the data to excel. The problem is the following: the culmination times and the corresponding information given (height az; observer/moon distance, magnitude) are not always correct. There are in particular duplicates (two culminations for a single day and (then or before in the spreadsheet, everything is shifted. Is this a handling error on my part? a bug in the application? Thank you for your answer !

_Originally posted by @ibaneoudo in https://github.com/Stellarium/stellarium/discussions/2961_

**Comment by gzotti** [comment]
All you can do is sort and shift the tables and add "---" where else there would be a duplicate entry. There are worse issues. Or are there really still wrong results now?

**Comment by alex-w** [comment]
> All you can do is sort and shift the tables and add "---" where else there would be a duplicate entry. There are worse issues. Or are there really still wrong results now?

Yes, I see doubles and wrong results and this is bad.

**Comment by iban1967-dev** [comment]
#2961: what's next?
Good morning,
The problem I was able to expose in #2961 found its solution in version stellarium-23.0-29d18ac-qt6-win64.exe
I registered on the forum to expose this problem and I thank you for having implemented a solution. Indeed, we now have the culmination and sunset sunrises on the date indicated on the clock. It is perfectly simple and clear.
I would just like to make a small remark. The issue I mentioned moved from thread to thread (#2990...) and eventually I wasn't even in the thread anymore. I find it a pity. In any case, this does not encourage the reporting of this type of information. I thank Alex for taking the time to understand the problem and escalate it. Thanks to whoever handled it. I do not thank gzotti for having hastened to classify this information without follow-up.
