### ISSUE TITLE
Remote Control plugin: Lists

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2995]
### Expected Behaviour
Find and select objects from Search/Lists tool

### Actual Behaviour
Any objects from Search/Lists tool cannot be selected

### Steps to reproduce
1. Run Stellarium and enable RC plugin
2. Open WUI of RC plugin in tablet browser
3. Try use Lists 

### System
* Stellarium version: 1.2 & 1.2+

**Comment by alex-w** [comment]
The issue is exists at least since version 0.19.3 :(

**Comment by gzotti** [comment]
Ah, yes. Something must have changed in the interface which no longer maps to RC code.

**Comment by alex-w** [comment]
It works in desktop browsers with double clicks :-/

**Comment by gzotti** [comment]
Is this then rather an Android browser problem? I seem to have no trouble with desktop Firefox.
