### ISSUE TITLE
German (only?)  translation 

### ISSUE THREAD

**Issue by dd1uw** [Stellarium/stellarium#2996]
stellarium 1.2. : observatory Hof in Germany found some to German untranslated terms in display of the constellations. Example Gemini (should be Zwillinge) or Leo (löwe). We use stellarium for kids who are confused by this. We'd appreciate to have as far as possible german texts. 
I recognized the localization in the de.qm files under ...\translations. I can change the knwn terms to german locally. We propose that the German translator can check the translations for the next Stellarium release. Thanks in advance.
Best regards 
Uwe (dd1uw)

**Comment by gzotti** [comment]
Wir haben 41 deutsche Übersetzer... Da ist vor 3 Monaten irgendwas verrutscht.
