### ISSUE TITLE
Missing star at position 7h 37m 35.s773 -14° 25' 8".11

### ISSUE THREAD

**Issue by hrnts2000** [Stellarium/stellarium#2998]
### Steps to reproduce 
In the region of the open cluster messier 47 (NGC 2422) in the Puppis constellation, at the following location (red box):

RA 7h 37m 35s.773 
Dec -14° 25' 8".11 

Through consultation of the SIMBAD catalog I noticed the absence of a star.
A SIMBAD query performed using the above coordinates gives the probable position of a star listed as Cl* NGC 2422 PMS 1052 (magnitude in red 12.262). The star was used to calculate the Messier 47 mass function, described in the article "Luminosity and Mass Function of the Galactic open cluster NGC 2422", Astronomy and Astrophysics, volume 404, 927-937 (2003/6-4).
See atach for further information.

![screenshot  2023-01-17 22 06](https://user-images.githubusercontent.com/122935944/213017958-9ce912cc-b323-4258-8a0d-efea92115f6b.jpg)

### System
* Stellarium version: v.1.2 
* Operating system: MacOS Monterey 12.1
* Graphics Card: Intel Iris Plus Graphics 655 1536 MB 
* Screen type Retina: Resolution 2560x1600 

Best regards.

Renato Polloni

**Comment by gzotti** [comment]
Many stars are missing, sure. Is the star included in the source catalogs documented in the Appendix of the User Guide? You can always cross-check for and find uncataloged (non-plotted) stars using the DSS layer.

**Comment by gzotti** [comment]
I can see the stars in the red box, though. Although I cannot select the upper of the two brighter ones. Some stars have this. 
![stellarium-065](https://user-images.githubusercontent.com/18099873/222996082-f56a4941-2e84-4974-a91c-9321817b887b.jpg)

However, by coordinates I could identify your star in the DSS layer. Yes, it's not in the star catalog.  Just to give you an idea about completeness of sky/catalog coverage or where stars brighter than the nominal catalog limit may be missing.  
![stellarium-069](https://user-images.githubusercontent.com/18099873/222995280-097dcaff-d34d-428a-a06a-54999c71fa3d.jpg)

**Comment by hrnts2000** [comment]
Thanks for your replay and informations.

> Il giorno 6 mar 2023, alle ore 01:57, Georg Zotti ***@***.***> ha scritto:
> 
> However, by coordinates I could identify your star in the DSS layer. Yes, it's not in the star catalog. Just to give you an idea about completeness of sky/catalog coverage or where stars brighter than the nominal catalog limit may be missing.
