### ISSUE TITLE
I18n request - slightly odd - Asteroid (2758) Cordelia

### ISSUE THREAD

**Issue by leonardcj** [Stellarium/stellarium#30]
I am linking translations.fab to wiki pages to help localizers.  For some reason there is no en.wikipedia.org article for Asteroid (2758) Cordelia although such an article exists in many other European language wikis.  It would be a great if such an article could be created by an astronomy-minded community member in en.wikipedia.org.

I think there is a redirect at https://en.wikipedia.org/wiki/2758_Cordelia that sends you to
https://en.wikipedia.org/wiki/List_of_minor_planets:_2001%E2%80%933000#758 when the linkage should really be the other way around, a link from the index to the main article for Asteroid (2758) Cordelia.

**Comment by gzotti** [comment]
I think you should raise this issue at Wikipedia because the article is missing _there_. For translators it should be enough to note that 2758 Cordelia is an asteroid. The translation for "Cordelia" will likely be "Cordelia", maybe requiring transliteration.

**Comment by leonardcj** [comment]
@gzotti @alex-w There is no Wikipedia entity to raise it with, only wikipedians, people with an interest in topics and sharing information on them, I thought there might be someone interested in astronomy and sharing astronomical information looking at these requests.  Your reply was rude and it is short sighted to simply close this request as you did when someone with a broader viewpoint or more open mind might respond to it.  Is this how you welcome new members to your community, people who are only trying to improve the software and expand the scope of it's audience?  If so, then my time is probably better spent elsewhere.

**Comment by gzotti** [comment]
We cannot do anything about a missing WP article. And yes, honestly, I don't think links to WP articles about single asteroids are required to translate asteroid names, which is the sole purpose of Transifex in this context. Links for difficult concepts like equation of time, sidereal time or stellar parallax may be useful, though.

**Comment by leonardcj** [comment]
I'm sorry, but it is just silly to say you cannot do anything about a missing WP article, ANYONE can create a WP article, I just thought it should be someone who knows something about astronomy.  Are there seriously no members of your community that edit WP?  Is it that important to close the issue that you couldn't leave it visible as an enhancement request?  If you haven't noticed my recent activity, between pull #31 and pull #45, I've added over 1,000 i18n enhancements, more if you include those in issue #6 some of which are exactly of the type you suggest is most useful.  Please re-open this issue.

**Comment by gzotti** [comment]
Did I comment negatively about #31 or #46? #6 is about a pink-sky issue for Quadro cards, likely no i18n problem. 
If ANYONE can create WP articles, this includes you. Whoever did the existing ones must have overlooked Cordelia. I am pretty sure that our team did not write hundreds of WP asteroid pages. Therefore here is not the right place to request a WP page for Cordelia. BTW, tens of thousands of asteroids don't have detailed pages. Why not request a page for 2755 Avicenna?
I have edited a few other WP pages, but I still don't see the value of WP links to asteroids for the sake of helping translators find a better translation term for their _names_.
Reopened issue. But don't expect further comments on this topic from my side.

**Comment by leonardcj** [comment]
Thank you for re-opening.  For the record, I was referring to issue 6 not pull 6, see attachment there.  When I better master your i18n process, I'll close that one myself.  I've re-established my Wikipedia account and when I have developed enough street-cred to be able to create pages without too much fuss, I will take care of this issue myself as well.  It won't be a particularly informative wiki page, but it will complete the set, I'll look for  a suitable astronomy affinity group to improve it.  In addition, I will be providing wiki redirect pages for the handful of Hipparcos ID references that do not already re-direct properly.  A minor flaw with #45 I discovered that I will correct by making the broken links work as re-directs, no revision of the pull should be required.

**Comment by daggerstab** [comment]
Looking at the [history](https://en.wikipedia.org/w/index.php?title=2758_Cordelia&action=history) of that wiki page, there used to be a single-sentence article and it was turned into a redirect because it didn't contain any information that wasn't already in the minor planet list articles. So in order to recreate it, it there has to be something that makes the article non-trivial (e.g. has the asteroid been the subject of a journal article? Is it a NEA or special in some other way? Has it been considered for exploration, or mining, or something?) The only thing I found after a brief Googling is that the asteroid shares a name with one of the moons of Uranus.

**Comment by alex-w** [comment]
I will close this issue because it is not our primary target - anybody may buy the books with asteroid naming info and make articles in wikipedia.
