### ISSUE TITLE
Objects Lists not working

### ISSUE THREAD

**Issue by Dequinzr** [Stellarium/stellarium#3000]
1) When adding objects to the my default list, they disappear when I restart Stellarium. I can add nothing to the list.
![Add object list](https://user-images.githubusercontent.com/122984332/213240481-b3572b8a-68bf-49f6-9e22-c418b19eeb0c.jpg)

2) when creating a new list (json format) and add objects in it, nothing remains in the list when I restart Stellarium. But when exporting the list before closing Stellarium, I can find the .json generated.

3) when trying to import the json generated, Stellarium crashes.
![variable json](https://user-images.githubusercontent.com/122984332/213240812-5f5450a7-d463-4894-8563-2995111d40ff.jpg)

### Expected Behaviour
Normal behaviour should be Stellarium to keep objects added when restarting it and be able to import a json file

### Actual Behaviour
Describe or maybe attach a screenshot?
Stellarium stop working when importing .json
I have added a screenshot of variable.json

### System
* Stellarium version: <Name of downloaded installable file?> 0.22.1
* Operating system: <Name, version number> Windows 10 with all updates appli

* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?> Graphic HD Intel 
* Screen type (if applicable): Resolution, HighDPI, scaling 
![Ecran](https://user-images.githubusercontent.com/122984332/213243551-ac990fad-b658-4118-8bec-f47bfabb1d38.jpg)
ed

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by Dequinzr** [comment]
I am using Stellarium since a few months to pilot my Dobson Skywatcher 254mm Goto telescope in combination with Synscan Pro using Wifi connection (integrated in my Dobson). I can now point to any variable star I am following and I am really delighted with the result. Moreover, I have downloaded all available stars, comet and asteroids database via Stellarium plugins to plan occultations i am following with an AZO camera. I thank you for all this work and thank you in advance for your help with objects lists. It is important for me to prepare my observation program by filling the observation lists.

**Comment by gzotti** [comment]
I can only suggest one thing: UPDATE to the latest version...
If you are using a GOTO telescope, make sure to use a Qt5-based build available from stellarium.org following the "all releases" link.

**Comment by Dequinzr** [comment]
I am sorry but it has nothing to do withe the telescope. I have no problem to guide it with Stellarium. The only thing that is not working is the fact that object lists is not working properly as the list does not hold the object entries when rebooting Stellarium and when importing an object list (variables.json in this case) Stellarium stop working. 

I am using version 0.22.1 which is following your list the latest version. Isnt it ?

**Comment by Dequinzr** [comment]
Sorry again, I just see there is a version 1.2 of Stellarium. I have installed it and the problem is solved.
Thank's a lot

**Comment by gzotti** [comment]
I was suggesting to use a Qt5-based build of V1.2 to drive a GOTO telescope because while your issue has been solved in 1.0 and later, the TelescopeControl plugin seems broken at least for a handful of users with Qt6-based builds.

**Comment by Dequinzr** [comment]
Many thank's for this information I did not understood at first read. I will test 1.2 QT6 and if not working, I will downgrade to QT5
If you may be interested, please find a document I have written to guide my dobson skywaycher goto with wifi integrated.
You may use it freely (if interested) and share it to public. It took me many hours of search and tests to achieve this fully working configuration without any wire (pure wifi) contrary to the different tutorials I have follow which are using Ascom driver and Com to USB wire.
[Guider Skywatcher avec un software V2 (Robert et Benoit).pdf](https://github.com/Stellarium/stellarium/files/10456998/Guider.Skywatcher.avec.un.software.V2.Robert.et.Benoit.pdf)

**Comment by gzotti** [comment]
Thank you for your guide. We need such hands-on guides that reflect the 2020s. I hope to find time to add this into the guide (with proper credits), but we will have to translate it.

**Comment by Dequinzr** [comment]
Hi Georg,

I will translate it to you, and send it back no problem

regards,

Robert Dequinze
***@***.***
Mob: +32 (0)475 81 84 07



Le jeu. 19 janv. 2023 à 14:40, Georg Zotti ***@***.***> a
écrit :

**Comment by Dequinzr** [comment]
Hi Georg,
Please find the document translated in English. I have adapt it to improve readability and comprehension.
Use it freely as you want hoping it will help Skywatcher observers.
[Guiding Skywatcher with a software V3 (Robert and Benoit).pdf](https://github.com/Stellarium/stellarium/files/10459971/Guiding.Skywatcher.with.a.software.V3.Robert.and.Benoit.pdf)

**Comment by Dequinzr** [comment]
Hi Georg,
1) I have tested guiding my telescope with Synscan Pro and Stellarium 1.2 QT6 using full wi-fi protocol (without any cable) and it is working fine. No break, no problem. The detailed config is described in my document.

2) Could you please send me the link to my document when you will publish it ?
Thank's

**Comment by gzotti** [comment]
Thanks for the translation and testing. It's the first positive confirmation that a Qt6-based build works at least for some instruments...


I just wonder, @alex-w shall we integrate this into the SUG or rather host it as-is on stellarium.org? It is a very detailed decription of using one instrument family. 

For proper integration I would need the figures non-embedded. 

If we decide to host it as original work: There are a few typos plus a formulation that should be changed: Fig.6 "hardly advised" means "not at all advised". Better: "strongly advised".
