### ISSUE TITLE
Satellites not showing on sky map

### ISSUE THREAD

**Issue by JAY-Githb** [Stellarium/stellarium#3004]
There have been several Starlinks that don't plot,  These 2 also won't show a plot.
As with Starlinks, these have high values in  line 1, columns 36-43. 
Seems there's a filter that doesn't allow rapidly changing orbits to appear on the map.
Can this limitation be removed?

CZ-2C R/B____________________column 36------43
1 53131U 22082D   23016.56019124  .00028223  00000-0  67515-3 0  9991
2 53131  97.3563  29.8636 0046177  69.3426 291.2762 15.40296072 28372
SL-4 R/B
1 54382U 22163B   23016.56217940  .00206184  12997-4  91844-3 0  9994
2 54382  67.1293 237.5809 0417086  48.9105 314.7279 15.15323762  7048

Version 1.2

**Comment by gzotti** [comment]
Maybe R/B means Rocket Booster and thus is no proper Starlink satellite?

**Comment by alex-w** [comment]
@gzotti R/B is rocket buster and this is just an example to reproduce the issues. I didn’t check it though yet.

**Comment by gzotti** [comment]
Yes, but Jay pointed out that "these two" don't plot. Exactly those are boosters, no proper Starlink satellites, from which I suspect they are just filtered away.

**Comment by JAY-Githb** [comment]
Hi.
There are many Starlinks that don't plot. I can give examples of those too.  I just mentioned these 2 to show that it is not just Starlinks that don't show up. Starlinks don't show when they are raising their orbit and have a large rate of change, These  2 also have a large drag. That is the common factor in all objects that don't plot so I suspect something there is the issue.

**Comment by JAY-Githb** [comment]
Examples:
Here are Starlinks in the same pass.
This group did not plot. When clicking on the name in the Satellites Configuration window, nothing happened.
STARLINK-5444 4-37
1 54768U 22175L   23016.89971637 -.00000799  00000-0 -12817-5 0  9990
2 54768  53.2139 157.2546 0001233 121.1753 238.9389 15.73186353  6633
STARLINK-5447 4-37
1 54779U 22175X   23017.08946103  .00007666  00000-0  59041-4 0  9991
2 54779  53.2155 156.3081 0001528  93.8557 266.2638 15.73178944  4503
STARLINK-5439 4-37
1 54783U 22175AB  23017.08914589  .00025694  00000-0  18694-3 0  9998
2 54783  53.2140 156.3090 0001264  49.0728 311.0401 15.73198423  4503
STARLINK-5438 4-37
1 54786U 22175AE  23016.64370413 -.00003155  00000-0 -18078-4 0  9991
2 54786  53.2149 158.5013 0001175  64.1529 295.9613 15.73193283  6597
4503STARLINK-5433
1 54793U 22175AM  23016.57746963  .00065911  00000-0  47035-3 0  9998
2 54793  53.2176 158.8017 0001193  74.2589 285.8562 15.73200390  6588


These Starlinks Do plot. When clicking on the name in the Satellites Configuration window, the view goes right to them on the sky map.

STARLINK-5452 4-37
1 54772U 22175Q   23016.64528559 -.00001903  00000-0 -91505-5 0  9998
2 54772  53.2155 158.5129 0000993  71.2984 288.8144 15.73193842  6599
STARLINK-5443 4-37
1 54781U 22175Z   23017.08935877 -.00004328  00000-0 -26458-4 0  9990
2 54781  53.2143 156.3084 0001229  95.8321 264.2839 15.73180337  4505
STARLINK-5415 4-37
1 54796U 22175AQ  23016.64265499 -.00006470  00000-0 -41736-4 0  9999
2 54796  53.2143 158.4974 0001337  61.2870 298.8284 15.73187809  6597
STARLINK-5421 4-37
1 54799U 22175AT  23016.64059050 -.00001126  00000-0 -36103-5 0  9992
2 54799  53.2167 158.4837 0001268  94.2127 265.9038 15.73199587  6596
STARLINK-5428 4-37
1 54800U 22175AU  23016.76929270 -.00002009  00000-0 -99113-5 0  9999
2 54800  53.2157 157.8633 0000904 104.6595 255.4525 15.73194031  6613
STARLINK-5422 4-37
1 54804U 22175AY  23016.64191784 -.00003891  00000-0 -23332-4 0  9990
2 54804  53.2141 158.4929 0001059  82.4086 277.7054 15.73192140  6595
STARLINK-5417 4-37
1 54805U 22175AZ  23016.64202616 -.00001243  00000-0 -44436-5 0  9996
2 54805  53.2150 158.4939 0001035  76.5789 283.5347 15.73192859  6592
STARLINK-5414 4-37
1 54809U 22175BD  23016.64160254 -.00005646  00000-0 -35854-4 0  9995
2 54809  53.2142 158.4910 0001430  49.5792 310.5352 15.73189272  6591
STARLINK-5408 4-37
1 54810U 22175BE  23016.64139201 -.00004148  00000-0 -25147-4 0  9995
2 54810  53.2155 158.4905 0001598  28.5275 331.5833 15.73197456  6599
STARLINK-5424 4-37
1 54811U 22175BF  23016.64128818 -.00002751  00000-0 -15190-4 0  9993
2 54811  53.2150 158.4866 0001422  52.0841 308.0308 15.73194008  6594

**Comment by JAY-Githb** [comment]
Here is the start of that pass:

  40.3   74.4       2000  
 2023 Jan  16  Mon morning  *** Times are AM UT-5 ***  1748  625

 H  M  S Tim Azi El C Dir  Mag Dys F  Hgt Shd  Rng  EW Phs  R A   Dec
54799 STARLINK-5421 22-175AT 
 6  2 55     327 38 C  91  5.2   1 8  222  43  347 2.1  43  8 9  64.5

**Comment by alex-w** [comment]
@JAY-Githb I'm really sorry, but previously I didn't have a time to check the behaviour of the plugin for these satellites and now the data is tool old. Can you revised the issue for your current data?

P.S. Should I publish the beta to tests?

**Comment by alex-w** [comment]
Oops... @JAY-Githb did you meant the limits for filters in the GUI?
