### ISSUE TITLE
astrocalc: include button "Now"

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3012]
**Is your feature request related to a problem? Please describe.**
The first date/time field defines the time of the calculation series.
When first opening the astrocal dialog, the current time is filled in; but closing and reopening the astrocal no longer changes that field during the session (because the dialog remains in memory).
Sometimes I want to compute a run for a different date, and then I painfully need to modify the time field.

**Describe the solution you'd like**
Add a button that inserts the currently active date/time in the field.

**Describe alternatives you've considered**
(Restart Stellarium...)

**Additional context**

**Comment by alex-w** [comment]
I don’t understand what’s the problem? If you want to set some time then you should set it - any “magic” button can’t guess what you want. Why “now” button can help here?

P.S. Astronomical calculations is not an astronomical calendar!

**Comment by alex-w** [comment]
@axd1967 we need feedback

**Comment by 10110111** [comment]
Well it seems rather obvious: there are a few date fields in the AstroCalc dialog, like e.g. beginning date for ephemeris, and it'd be useful to have an easy way to insert current time into them, without entering it manually.

**Comment by axd1967** [comment]
thank you.
