### ISSUE TITLE
rectangular FOV wrong for other than very small angles

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3015]
### Expected Behaviour

The angle measurement tool should measure the exact sizes that have been set in the rectangle FOV.

Unless I'm mistaken, this is a known issue.

### Actual Behaviour

The rectangular FOV does not take projection into account. 
(Exception: in cylindrical projection, the vertical dimension is respected)

![image](https://user-images.githubusercontent.com/3529789/213930407-83bc892a-48c4-4668-a088-56de3b815211.png)

**Comment by gzotti** [comment]
it's a rectangle drawn with IIRC the screen center scale. Using such a big square must lead to errors. We should probably limit this field to 5°.

**Comment by axd1967** [comment]
> it's a rectangle drawn with IIRC the screen center scale. Using such a big square must lead to errors. We should probably limit this field to 5°.

No. Because

1. Stellarium should correctly display angularly defined topocentric rectangles of any size (yes, indeed, also of 180x180!)
2. artificially limiting the user where there is no fundamental issue is not a good idea ([needless limits](https://github.com/Stellarium/stellarium/issues?q=is%3Aissue%20needless%20limit))
3. 7-10 degrees is a typical binocular FOV

Note that this can also serve as a solution for #2882

**Comment by gzotti** [comment]
I knew you would say this. 
Some limits must be defined to avoid errors. As always, you are free to develop a PR that overcomes this trivial simplification that is not so trivial to solve. `(All-1)` seem to be able to live with a quick estimate. 
To simulate instruments, use the Oculars plugin which was designed for this. (It also just shows a rectangle, but with info.)
Please send a link to a bino with rectangular fov.

**Comment by axd1967** [comment]
I'm aware this is not an easy issue. This is a good issue for an advanced developer, so please don't close it otherwise it will slip under the radar of keen developers.

And it's not because "all-1" can live with it, that it can't be mentioned. It is often precisely that single voice that might point out a problem. Remember "[the Emperor has no clothes](https://en.wikipedia.org/wiki/The_Emperor%27s_New_Clothes)"?

I don't want to simulate instruments; see #2882 for a very real use case.

Remember: if Stellarium claims to be accurate, this is part of the deal...

And Georg, can we drop the silly remarks on rectangular FOV of bino's? It is hurting, you want to make me look stupid. You should know better by now... because it should be obvious that I'm referring to the rectangle that spans the FOV of a bino. Let's engage some brains before entering the room, please!

**Comment by alex-w** [comment]
The #2882 has bad description and this is very untypical use case, at least I don’t know people who want see the sky through tonnel. For correct solving #2882 you need to introduce the new type of landscape.

**Comment by gzotti** [comment]
The button next to the rectangular fov controls a circular fov. Now who engages brains? You can surely report 600 more tiny issues, from which we must still sort out those worth solving. This is a waste of our time. Thanks, we are still busy.

**Comment by alex-w** [comment]
@10110111 would you look at this issue? Probably the solution will be similar to your solution for Oculars plugin.

**Comment by 10110111** [comment]
What should this rectangle actually represent? Possible interpretations:

* the field of view of a rectilinear lens whose central horizontal and vertical FoV is specified by the settings;
* a quadrilateral with the sides having the specified FoV (this is more in line with the screenshot in the OP);
* something else?

What is the use case of this marking?

**Comment by axd1967** [comment]
the FOV box should follow the same mathematical behaviour as the angular tool. No lenses involved here, that belongs in the Oculars module.

**Comment by 10110111** [comment]
You see, it's a vague description: there's no such spherical rectangle that would have all "horizontal" great arcs equal and all vertical great arcs equal. The best one can hope for is that the sides have the required FoV, or a pair of central lines, or something else, but not all the lines of the same orientation. So I ask once again: what is the use case?

**Comment by alex-w** [comment]
By the fact, this tool was added as very simple visualizer for rectangular FoV of some optical setup with CCD, where we have known only value of filed of view and neither other.

**Comment by axd1967** [comment]
the primary issue is the discrepancy between angular tool and RFOV. The angular tool seems to define the correct limits of the rectangle.

Here the bug is visible for a 90x20 RFOV in stereographic projection

- the angular tool correctly reports 90d between N and E
- the RFOV tool (red) seems to cut off short (so the demanded 90 FOV is not actually met)

![image](https://github.com/Stellarium/stellarium/assets/3529789/aad9b1da-3d83-466f-88bb-17b6dc5879d8)


use case: see #2882. (which is NOT to define yet another landscape). (plus: Stellarium should be accurate.)

btw - it makes no sense to limit circular FOV (CFOV) to 28 while limiting rectangular FOV (RFOV) to 180x180.

**Comment by alex-w** [comment]
> use case: see #2882. (which is NOT to define yet another landscape). (plus: Stellarium should be accurate.)

This use case is not use case by the fact, because it is not related to rectangular FOV of optical setup with CCD.

> btw - it makes no sense to limit circular FOV (CFOV) to 28 while limiting rectangular FOV (RFOV) to 180x180.

As we said before, these limits have objective reasons.

**Comment by gzotti** [comment]
What's the point of a 180° rectangle then? Limit to ~20° to avoid the obvious distortion-caused error to keep the "simple" solution, or copy/adapt "sensor" code from recent work by @10110111 .

**Comment by 10110111** [comment]
I have an adaptation of the sensor code, but we need to make the decision whether it's OK to use the same kind of rectangle (judging by what @alex-w says, it's OK). It won't have the same angular sizes on the borders as it does in the middle between the borders (and it can't in principle).

**Comment by axd1967** [comment]
V25.3:

<img width="1147" height="781" alt="Image" src="https://github.com/user-attachments/assets/e9cd3163-afd6-4828-b9a5-d8eabe42de1e" />


RFOV = 120x90; stereoscopic projection.

Angles measured between markers:

1. 7-8: 90d (OK)
2. 9-10: 120d (OK)
3. 12-13: 102d ?
4. 13-14: 52d?


I think this is what is desired:

<img width="1117" height="918" alt="Image" src="https://github.com/user-attachments/assets/e7f301d6-5748-4734-a38a-38f7ec2033c1" />

**Comment by 10110111** [comment]
The current behavior reflects the actual geometry of perspective
projection. You'll get the correct FoV when measuring through the center of
the frame. What you're talking about would not be a perspective lens
footprint.

You can check this by making a photo with a wide-angle rectilinear lens and
trying to fit in into Stellarium (Lens Distortion Estimator plugin may help
to place and orient the image).

**Comment by 10110111** [comment]
Actually, you can check even easier: just switch the projection to
perspective and note that the corners of the footprint are at the same
locations with respect to the azimuthal grid as they were. And the
footprint is rectangular as it should be.
