### ISSUE TITLE
Latest release, has an incorrect windows registry version and file properties in the windows installer

### ISSUE THREAD

**Issue by PierreCsn** [Stellarium/stellarium#3018]
The latest release appear in windows registry as version 0.22.5 and in the properties of the installer aswell.

we currently package the app for automatic deployment for our customers, can we exepect a correction on your side, or should be correct our packaging to handle the improper installer ?

**Comment by gzotti** [comment]
Version 0.22.5 is the internal number of Qt5-based V1.2 as laid out in the User Guide. Are you talking about any other build?

**Comment by PierreCsn** [comment]
hmm seems like we have been using the improper version before for our packaging and only noticed now. nvm closing the issue
