### ISSUE TITLE
Is it possible to see only the 48 constellations of  Ptolemy?

### ISSUE THREAD

**Issue by decoomanj** [Stellarium/stellarium#3021]
**Is your feature request related to a problem? Please describe.**
When doing archeo-astronomy, the constellations which are not listed by Ptolemy can sometimes clutter images.

**Describe the solution you'd like**
Display of constellations by Ptolemy only.

**Describe alternatives you've considered**
Removing them from screenshots -> as good as impossible.

**Comment by Atque** [comment]
There is a sky culture “Greek Almagest” which contains the Ptolemaic constellations.

**Comment by decoomanj** [comment]
Ah, correct, but apart from the Farnese variant, there are no constellation images in there? Or am I missing something?

**Comment by gzotti** [comment]
The Greek (Almagest) has no artwork included. 
There is also the Greek (Leiden Aratea) variant.

**Comment by gzotti** [comment]
And BTW it is very easy to create a private copy of the default ("Modern") sky culture and delete what you want.

**Comment by decoomanj** [comment]
Thanks for the hints. I'll try this out!
