### ISSUE TITLE
Stellarium crashes when synced to APT and GSS

### ISSUE THREAD

**Issue by NotTheChief** [Stellarium/stellarium#3034]
### Expected Behavior

The expected behavior is for the selected target to be tracked by Stellarium while I am doing a shooting session.

### Actual Behavior

Stellarium crashes, shuts down, and has to be restarted every few seconds once I have Stellarium, APT, and GSS synced to a target. Stellarium does not stay open long enough for me to be able to observe if there is accurate tracking on the selected object - Becklin's Star area during the winter months.

### Steps to reproduce

Reproduction is easy! I just restart Stellarium, find the SkyWatcher symbol on the Stellarium screen, sync to the target, wait a few seconds, and watch it crash (shut down) which is happening all the time. 

### System
* Stellarium version: stellarium-1.1.1-qt6-win64
* Operating system: Windows 10 PRO, Version 22H2
* Graphics Card: I do not know. The graphics card is part of the Intel NUC that I am using.
* I am using an Intel NUC10I5FNK with 32GB ram with Remote Desktop Connection to run my SkyWatcher HEQ-5 PRO and all software: APT (4.10), GSS (1.0.4.6), and Stellarium (1.22.4).

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#problems-with-telescopecontrol-plugin
