### ISSUE TITLE
Reddish color of umbra during total lunar eclipse is almost vanish

### ISSUE THREAD

**Issue by worachate001** [Stellarium/stellarium#3035]
### Expected Behaviour
Reddish Moon during total lunar eclipse.

### Actual Behaviour
![moon-tle](https://user-images.githubusercontent.com/41257965/215922896-0f47da8b-4e9d-4c5e-a727-eeb38a986068.png)

### Steps to reproduce
Search for total lunar eclipse and jump to the time of greatest eclipse.

### System
* Stellarium version: Latest master
* Operating system: Manjaro 22.0.1
* Graphics Card: NVIDIA Geforce RTX 2060 SUPER

**Comment by Atque** [comment]
Introduced by #3002. The Moon now also looks too bright in the daylight sky.

![stellarium-156](https://user-images.githubusercontent.com/37028368/215964497-d5ed1b64-81c1-4a4f-b4c7-9c10b5857d80.png)

I guess some balancing is needed.
