### ISSUE TITLE
Scripting URLs in User Guild v1.2 need updating.

### ISSUE THREAD

**Issue by bryonelliott** [Stellarium/stellarium#3037]
### Expected Behaviour
In Chapter "17. Scripting", reference URLs should match the versions of software being used. 

### Actual Behaviour
Footnote 1 is for the Qt5 Scripting Engine, which is fine since it's mentioned in the text.  But there should be an additional footnote for the Qt6 QJSEngine, "https://doc.qt.io/qt-6/qtjavascript.html", which is mentioned in the last paragraph of 17.1, and is the version of the JavaScript engine used by the version of Stellarium that this document is for.

Footnote 3 (https://www.stellarium.org/doc/22.x/scripting.html) in 17.1 leads to a "404 Page Not Found" error.  The URL should be "https://stellarium.org/doc/1.x/scripting.htmlhttps://stellarium.org/doc/1.x/scripting.html"

### Steps to reproduce
Click on the footnote URLs in chapter 17.

### System
* Stellarium version: 1.2
* Operating system: Windows 11, Version 10.0.22621 Build 22621
* Graphics Card: NVIDIA GeForce RTX 2080 Super, Driver Version	31.0.15.2824
* Screen type (if applicable): Resolution, HighDPI, scaling: 1920x1080, 100% scaling.

### Logfile 
N/A

**Comment by gzotti** [comment]
Footnote on Qt6 added. The URL in footnote 3 is created by automatisms, but was victim to the version/series number changes and will hopefully be correct with the next version.
