### ISSUE TITLE
error: void INDIConnection::newDevice(INDI::BaseDevice*) marked override, but does not override

### ISSUE THREAD

**Issue by carlosal1015** [Stellarium/stellarium#3038]
### Expected Behaviour

stellarium must compile with [this instruction](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=stellarium#n25).

### Actual Behaviour

It does not, and throws an error.

```console
364/986] Building CXX object plugins/TelescopeControl/src/INDI/CMakeFiles/TelescopeControl_INDI.dir/TelescopeControl_INDI_autogen/mocs_compilation.cpp.o
FAILED: plugins/TelescopeControl/src/INDI/CMakeFiles/TelescopeControl_INDI.dir/TelescopeControl_INDI_autogen/mocs_compilation.cpp.o 
/usr/sbin/g++ -DCOPYRIGHT_YEARS=\"2000-2023\" -DDEBUG3 -DDEBUG4 -DDEBUG5 -DENABLE_GPS -DENABLE_LIBGPS -DENABLE_MEDIA -DENABLE_NLS -DENABLE_SCRIPTING -DENABLE_SCRIPT_CONSOLE -DENABLE_SCRIPT_QML -DENABLE_SHOWMYSKY -DINSTALL_DATADIR=\"/usr/share/stellarium\" -DPACKAGE_VERSION=\"1.22.5\" -DQT_CORE_LIB -DQT_DLL -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DSTELLARIUM_COPYRIGHT="\"Copyright (C) 2000-2023 Stellarium Developers\"" -DSTELLARIUM_DEV_URL=\"https://github.com/Stellarium/stellarium\" -DSTELLARIUM_MAJOR=1 -DSTELLARIUM_MINOR=22 -DSTELLARIUM_PATCH=5 -DSTELLARIUM_PUBLIC_VERSION=\"1.2\" -DSTELLARIUM_RELEASE_BUILD -DSTELLARIUM_SOURCE_DIR=\"/tmp/makepkg/stellarium/src/stellarium-1.2\" -DSTELLARIUM_URL=\"https://stellarium.org/\" -DTELESCOPE_CONTROL_CONFIG_VERSION=\"0.4.1\" -DTELESCOPE_CONTROL_PLUGIN_LICENSE="\"GNU GPLv2 or later\"" -DTELESCOPE_CONTROL_PLUGIN_VERSION=\"0.4.2\" -D_REENTRANT -D_USE_MATH_DEFINES -I/tmp/makepkg/stellarium/src/build/plugins/TelescopeControl/src/INDI -I/tmp/makepkg/stellarium/src/stellarium-1.2/plugins/TelescopeControl/src/INDI -I/tmp/makepkg/stellarium/src/build/plugins/TelescopeControl/src/INDI/TelescopeControl_INDI_autogen/include -I/tmp/makepkg/stellarium/src/build -I/tmp/makepkg/stellarium/src/stellarium-1.2/src -I/tmp/makepkg/stellarium/src/stellarium-1.2/src/core -I/tmp/makepkg/stellarium/src/stellarium-1.2/src/core/modules -I/tmp/makepkg/stellarium/src/stellarium-1.2/src/core/planetsephems -I/tmp/makepkg/stellarium/src/stellarium-1.2/src/gui -I/tmp/makepkg/stellarium/src/stellarium-1.2/src/scripting -I/tmp/makepkg/stellarium/src/build/src -I/tmp/makepkg/stellarium/src/stellarium-1.2/plugins/TelescopeControl/src -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtNetwork -isystem /usr/include/qt6/QtGui -isystem /usr/include/qt6/QtWidgets -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-result -fPIC -std=c++17 -MD -MT plugins/TelescopeControl/src/INDI/CMakeFiles/TelescopeControl_INDI.dir/TelescopeControl_INDI_autogen/mocs_compilation.cpp.o -MF plugins/TelescopeControl/src/INDI/CMakeFiles/TelescopeControl_INDI.dir/TelescopeControl_INDI_autogen/mocs_compilation.cpp.o.d -o plugins/TelescopeControl/src/INDI/CMakeFiles/TelescopeControl_INDI.dir/TelescopeControl_INDI_autogen/mocs_compilation.cpp.o -c /tmp/makepkg/stellarium/src/build/plugins/TelescopeControl/src/INDI/TelescopeControl_INDI_autogen/mocs_compilation.cpp
In file included from /tmp/makepkg/stellarium/src/build/plugins/TelescopeControl/src/INDI/TelescopeControl_INDI_autogen/EWIEGA46WW/moc_INDIConnection.cpp:10,
                 from /tmp/makepkg/stellarium/src/build/plugins/TelescopeControl/src/INDI/TelescopeControl_INDI_autogen/mocs_compilation.cpp:2:
/tmp/makepkg/stellarium/src/build/plugins/TelescopeControl/src/INDI/TelescopeControl_INDI_autogen/EWIEGA46WW/../../../../../../../stellarium-1.2/plugins/TelescopeControl/src/INDI/INDIConnection.hpp:72:14: error: ‘void INDIConnection::newDevice(INDI::BaseDevice*)’ marked ‘override’, but does not override
   72 |         void newDevice(INDI::BaseDevice *dp) override;
      |              ^~~~~~~~~
```

### System
* Stellarium version: From the source, version 1.2.
* Operating system: Arch Linux
* Graphics Card: No Apply

### Logfile 

[stellariumlog.txt](https://github.com/Stellarium/stellarium/files/10557873/stellariumlog.txt)

**Comment by alex-w** [comment]
related to PR #2891

**Comment by paolostivanin** [comment]
That PR, unfortunately, doesn't fix the issue. With INDI 2.0.0 released few days ago, the INDI library was refactored and redesigned.
[THIS](https://github.com/indilib/indi/commit/4a15b8ea4b5b4616aa85dc02bdc385cc93819985) is the commit that introduced the changes.
In order to compile Stellarium against INDI 2.0.0, the code in Stellarium itself must be updated to this new format.

**Comment by paolostivanin** [comment]
e.g.

```
virtual void newDevice(INDI::BaseDevice *dp); // deprecated
virtual void newDevice(INDI::BaseDevice baseDevice);
```

**Comment by GaVenga** [comment]
fixed it by softlinking: /usr/lib/libindiclient.so.2.0.0 → /usr/lib/libindiclient.so.1
(sudo ln -s /usr/lib/libindiclient.so.2.0.0 /usr/lib/libindiclient.so.1)
Only do this when downgraded library is needed!
(Example: actual Version is "2" - needed version is "1" - not actual "3" to needed "4")

**Comment by paolostivanin** [comment]
I highly suggest *not* to do that. That's a recipe for disaster!
If a software requires INDI 1, and you create a symlink to INDI 2, that software is for sure gonna crash. Same thing the other way around.
There's a reason packagers and developers use soversion for shared libraries 😊

**Comment by GaVenga** [comment]
I highly suggest not to do that. ==> seems you never programmed libraries....
Libraries are backward compatible... Jumptables are constant, data can be upgraded
If not - THEN you are right.-

**Comment by 10110111** [comment]
> Libraries are backward compatible

The change of the soversion tells that its developer disagrees with this. The fact that some part of the API or even ABI retains backwards compatibility by accident doesn't let the users rely on this generally.

Of course, if you can prove that the subset of the API & ABI that you use retained the compatibility in the switch between the exact versions in question, then you can indeed do this hack.

**Comment by pnoumenon** [comment]
> I highly suggest not to do that. ==> seems you never programmed libraries.... Libraries are backward compatible... Jumptables are constant, data can be upgraded If not - THEN you are right.- To link from a lower subversion to a higher is shurely master of disaster, as the jumptable to the new function does not exist..

People keep telling me how Arch keeps breaking despite me not ever having had my system break in almost 10 years of using it. I'm starting to understand why it's breaking for those people now.

That aside, I'm also experiencing this problem, and I'm just going to use the AppImage until Stellarium gets updated to fix this.

**Comment by rokezu** [comment]
Was looking for updates about this library upgrade, and I second the comments by @paolostivanin and @10110111 that whoever stumbles upon this thread, DO NOT soft link library version to circumvent the dependency requirement, the proper way to go is to wait for Stellarium devs to refactor the code for the new API of libindi and keep using the older version in some other way.

And going with @pnoumenon, another way to keep an old version is to tell pacman to IgnorePkg libindi so to keep the 1.9.9-1 version required by Stellarium, pacman will warn about this every time, and in my case only Stellarium uses libindi.  And a quick anecdote, as a fellow decade-plus Arch user, they do have broken my system plenty of times, most recently as in it was working late night, then come morning grub stopped booting/working even after following their steps, haha (long history short, they just packaged an in-development git version with plenty of new features and bugs being worked on and call it a day - to avoid dealing with security advisories and patching of the stable release!).  I just keep a bunch of PCs nearby to browse around things like that, it is nice to learn stuff by moving fast and breaking things, but I'm getting old and probably will switch to Debian or Fedora soon. Just get off my rolling lawn.

**Comment by pnoumenon** [comment]
> come morning grub stopped booting/working even after following their steps, haha (long history short, they just packaged an in-development git version with plenty of new features and bugs being worked on and call it a day - to avoid dealing with security advisories and patching of the stable release!)

Yeah, GRUB seems to break a lot of people's systems; I wouldn't touch it with a 10-foot pole personally (no offense to whoever develops it these days, I'm sure it has a rich history and was once quite useful).

**Comment by alex-w** [comment]
The fix is in master already
