### ISSUE TITLE
Unknown data response in Stellarium mobile telescope control

### ISSUE THREAD

**Issue by urbanze** [Stellarium/stellarium#3042]
Hello guys, I developed my entire system (hardware, software, etc) to control my DIY GoTo telescope and use Stellarium (computer) over TCP to move on stars. I decoded the proprietary protocol used by Stellarium TCP and works so fine.

However, I tried to use Stellarium Mobile over network (WiFi/TCP) and my code is receiving [0x4b, 0x61] and [0x23, 0x23]. When I look at the log, Stellarium mobile is trying to recognize protocol sending this bytes and probably waiting some response.

1. I can't find any information about the response that I need to return over TCP. Someone can give me instructions about this sync? (In this case, I will use lx200 instead NexStar).
2. Stellarium Mobile don't have the same proprietary protocol as computer TCP?

**Comment by urbanze** [comment]
Alright, I already can decode and learn about sync process to use Stellarium mobile to my custom GoTo Telescope.

I used [0x23, 0x06] packet sent from Stellarium to start sync process from my app, sending 'A' over TCP. After this, Stellarium send many common commands like #GR, GD...

**Comment by xalioth** [comment]
Hi, yes we use the 0x06 (ACK) caracter to recognize a LX200 protocol. Once you support this one everything else should be more usual! Let me know if you need more assistance.

**Comment by urbanze** [comment]
> Hi, yes we use the 0x06 (ACK) caracter to recognize a LX200 protocol. Once you support this one everything else should be more usual! Let me know if you need more assistance.

Thanks! Can you explain the difference between [0x23, 0x23] and [0x23, 0x06] sent by Stellarium at sync moment?
