### ISSUE TITLE
Unable to build Stellarium in Fedora 37 (error in ShowMySky)

### ISSUE THREAD

**Issue by worachate001** [Stellarium/stellarium#3044]
### Expected Behaviour
Success build of Stellarium.

### Actual Behaviour
I'm trying Nobara Linux (a modified version of Fedora 37). Everything went well until this error: 

```
[ 82%] Linking CXX shared library libShowMySky-Qt6.so
/usr/bin/ld: ../libcommon.a(EclipsedDoubleScatteringPrecomputer.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [_deps/showmysky-qt6-build/ShowMySky/CMakeFiles/ShowMySky.dir/build.make:153: _deps/showmysky-qt6-build/ShowMySky/libShowMySky-Qt6.so.15.0.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:3095: _deps/showmysky-qt6-build/ShowMySky/CMakeFiles/ShowMySky.dir/all] Error 2
```

I'm not sure there is something wrong in my system or a bug in ShowMySky. I have to disable ShowMySky to successfully build the program. It would be fantastic if it can be fixed so I can enjoy the beauty of ShowMySky again.

### System
* Stellarium version: Latest master
* Operating system: Nobara 37 (Fedora 37)

**Comment by 10110111** [comment]
Try configuring cmake with `-DCMAKE_CXX_FLAGS=-fPIC`.

**Comment by worachate001** [comment]
Problem solved. Thank you!
