### ISSUE TITLE
stellarium glitches out when any input is given

### ISSUE THREAD

**Issue by GNz-11** [Stellarium/stellarium#3046]
### Expected Behaviour
run smoothly without screen going blank 

### Actual Behaviour
Describe or maybe attach a screenshot?
I have an external monitor attached to my laptop. I've set my external monitor as the primary display, so Stellarium opens on that screen. On my internal monitor, I have other applications like Edge and Discord running. Whenever I use the other applications on my internal monitor, the screen of Stellarium goes blank for a couple of seconds and then reappears. When I go to use Stellarium after using other applications, it does the same thing again. And it does the same thing for every input (like clicking or entering any characters with my keyboard). This issue makes Stellarium unusable. I don't know whether this is a screen related issue. I've been trying to make Stellarium open on my internal monitor but haven't been successful in doing so. It ran smoothly without any issues on my old Windows 7 PC with the same monitor, which I am currently using as my external display.

### Steps to reproduce
If you have two displays, use one for Stellarium and the other for any other application. Use the application on the other display, and after using that application, try to use Stellarium.

### System
* Stellarium version: stellarium-1.2-qt6-win64
* Operating system: windows 11
* Graphics Card: Intel UHD version 31.0.101.2115
* Screen type (if applicable): (external) LED, 1600x900 resolution, 100% scaling (recommended by windows)

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/10611453/log.txt)

**Comment by 10110111** [comment]
Try passing `--single-buffer` option to Stellarium (either from command line, or by editing its shortcut).
