### ISSUE TITLE
Stellarium takes all CPU and laptop crashes

### ISSUE THREAD

**Issue by skou99** [Stellarium/stellarium#3047]
I checked my graphics driver for AMD Radeon Vega 8, which is upto date. Is there anything else I need to check out ?
Thanks

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/FAQ#reporting-a-crash

I don't understand how you can avoid filling in the issue template.

**Comment by skou99** [comment]
thanks for  your comment, however I was wondering if anyone happened to know that this driver is supported, as, if it's not then it isn't worth putting in a crash report

**Comment by 10110111** [comment]
> I was wondering if anyone happened to know that this driver is supported

Stellarium doesn't support or unsupport any drivers, it just uses whatever the system provides. If that works, then fine. Your GPU seems to be relatively recent (2018), which should be OK. But in any case, a complete crash report is useful to diagnose a crash, it should never be omitted from an issue about a crash.

**Comment by gzotti** [comment]
Without further feedback we will close this after March 26.

**Comment by skou99** [comment]
Hi I cleared down some extra space over time and rebooted and this fixed it
