### ISSUE TITLE
DSS Sky Survey Hybrid Loading Scheme

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#3049]
Is there a solution to load local and online DSS images? For example, if the DSS level in the configuration file is lv10 and the decompressed image downloaded to the local is lv6, then it can be obtained online when the local miss occurs, which can save a large number of images without consuming local space, and also ensure the use of DSS by some users with poor network.

**Comment by gzotti** [comment]
There is no hybrid solution. However you can just skip downloading level 11, level 10 should be good enough for most purposes.

**Comment by ultrapre** [comment]
I mean when the target is not hit locally, use network search

**Comment by gzotti** [comment]
And I say again you have to decide to use either network access or do a local install. All options are described in the User Guide.
