### ISSUE TITLE
Plug-in File 'ocular.ini' locks during boot-up

### ISSUE THREAD

**Issue by Snomike** [Stellarium/stellarium#3055]
<!--
Stellarium has been running fine up until now. During boot up Setllarium pauses on the 'Ocular Plug-In'  message and doesn't finish boot up. I find on my Windows 11 PC C:\Users\<my name>\AppData\Roaming\Stellarium\modules\Oculars a file created during boot-up named 'ocular.ini.lock just under the normal file 'ocular.ini'. 
I have to go into Task Manager to end the Stellarium boot-up. When I erase the 'ocular.ini.lock' file, it is created again on the next Stellarium boot-up attempt.
Any idea what is causing Stellarium boot-ups to do this?

**Comment by Snomike** [comment]
My initial description didn't record, first time I've submitted an issue. 
The issue is, up until now, Stellarium has worked just fine. Now, when Stellarium tries to boot-up it gets stuck when it's loading Ocular Plug-in.  It doesn't finish its boot. In Explorer on my Windows 11 PC, in C:\Users\<my name>\AppData\Roaming\Stellarium\modules\Oculars under the normal file 'ocular.ini' a  new file is created called 'ocular.ini.lock' and I have to go to Task Manager to end the task of Stellarium trying to boot-up. If I erase the file 'ocular.ini.lock' and reboot Stellarium, the 'ocular.ini.lock' file is created again and Stellarium is stuck.
How is this happening?

**Comment by Snomike** [comment]
I was finally able to get in to Stellarium and in Configuration, Plug-Ins, Ocular and unchecked 'Load at Startup' and now it boots up just fine. What do I need to do to purge the Ocular file and or configuration and load in a new one? Apparently what I had in got corrupted somehow. I remember trying to add a telescope and camera sensor last week and that is what must have corrupted it.

**Comment by gzotti** [comment]
A ".lock" file prevents other programs from accessing a file simultaneously. 
Quit Stellarium, delete the ocular.ini file which you have found, and restart Stellarium. A default ocular.ini is recreated.

**Comment by Snomike** [comment]
gzotti, thank you. I deleted the ocular.ini file and on start-up it did recreate another ocular.ini file. Problem is, when I configure Oculars to Load at start-up, the next time I start-up Stellarium, the ocular.ini.lock file is created and Stellarium hangs up again and won't finish booting up. I essentially can't run the Ocular plug-in. As long as I don't have Oculars 'Load at startup' box checked I can run Stellarium. When I check the box, the program hangs at start-up. I don't know what is causing this to happen.

**Comment by gzotti** [comment]
Weird. Cannot reproduce the problem. At this point I cannot even say where the lock file is needed.

**Comment by alex-w** [comment]
please check permissions for file system

**Comment by gzotti** [comment]
@Snomike Any updates?
