### ISSUE TITLE
CPU - 10 of 12 Maxed

### ISSUE THREAD

**Issue by 520kaymann** [Stellarium/stellarium#3070]
### Discussed in https://github.com/Stellarium/stellarium/discussions/3069

<div type='discussions-op-text'>

<sup>Originally posted by **520kaymann** February 22, 2023</sup>
Using Stellarium Version 1.22.5 Completely love the program.

Issue: CPU Core 10 of 12 is full throttle (98-100%) 100% of the time. Overall CPU usage is 14%

Question: 1) does Stellarium support multicore load spreading? 2) does Stellarium support GPU offloading?

If either is yes how do I enable it?

Again FANTASTIC program.

Randall</div>

**Comment by gzotti** [comment]
The issue report template asks for your platform and other details. I still don't know how to avoid the template.

Yes, there are a few threads running in parallel. 
If you are running Software OpenGL (MESA on Windows), the CPU has to take over.

**Comment by 10110111** [comment]
> The issue report template asks for your platform and other details. I still don't know how to avoid the template.

It's sort of obvious: this issue was originally created as a discussion, which doesn't present this template.

**Comment by 520kaymann** [comment]
I will fill out the template where is it?

**Comment by 10110111** [comment]
If you click _New issue_ → _Bug report_, you should get the template in the input field.

**Comment by 520kaymann** [comment]
Found it:

### Expected Behaviour
Processes spread our over all cores or even distributed to GPU

### Actual Behaviour
Core 10 of my 12 cores is maxed out 100% of the time Stellarium is running

### Steps to reproduce
1) Reduced max fps to 40
2) Starting with zero plugins enabled

### System
* Stellarium version: 1.22.5
* Operating system: Windows 10 22H2
* Graphics Card: NVidia GeForce RTX 2060
* Screen type: MSI Optix MAG 341CQ 3440x1440 Scaling 100% FPS as reported by Stellarium 17

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/10806930/log.txt)

**Comment by 10110111** [comment]
The symptoms don't look normal given what we know. Does the Task Manager confirm that the whole CPU usage is by `Stellarium.exe`, rather than any other process?

> Reduced max fps to 40

Does the problem reproduce without this?

**Comment by 520kaymann** [comment]
As soon as I Kill Stellarium Core 10 goes to nearly nothing...

**Comment by 520kaymann** [comment]
Stellarium.exe takes up 8% of total CPU when the next highest is Desktop Window Manager takes up only 0.4% of total CPU use. Power Usage by Stellarium is in the red at Very High.

**Comment by 520kaymann** [comment]
Memory Usage is a very reasonable 534.3 MB

**Comment by 520kaymann** [comment]
GPU 3D is approximately 80% dropping to zero after killing Stellarium

**Comment by 520kaymann** [comment]
BTW Not sure how this helped but on Cloudy Nights they indicated setting the min_fps lower would help and I set it to 6fps and core 10 dropped usage to approximately 50%

**Comment by 10110111** [comment]
> CPU Core 10 of 12

Do you mean that 10 cores out of 12 are used? Or did you really mean that just one core that has id 10? If the latter, then it's completely normal. If it's 10 cores that are maxed out, then not.

**Comment by 520kaymann** [comment]
Core id #10 any way to spread the wealth?

**Comment by 10110111** [comment]
Spreading is the prerogative of the OS. Applications have no business in this normally.

**Comment by gzotti** [comment]
(As also mentioned on CN.) The discussed fps settings are intents, not guaranteed settings. Stellarium was designed and is still developed as graphically pleasing simulator, but it also *can* guide telescopes. As such, max_fps=10.000 basically means "as fast as the system allows" and is mostly applied while you are changing the scene, zooming, panning, etc. And yes, the main graphics thread will hog one of your cores (selected by the OS), leaving some other cores for a few side-threads and other tasks on your system. (It is far from trivial to identify subtasks that could be offloaded to another thread.)  min_fps is the fps intent for "idle" updates (while you are not interacting with the software). It makes sense to lower the rates to 5/15 or even lower when running on limited hardware or via remote desktop or just to conserve energy. If your system's max achievable fps is only 17, the default min_fps=18 (which should limit today's systems which regularly show 60fps) still maxes out the system.

**Comment by gzotti** [comment]
Version 23.1 now has GUI settings available to reduce frame rate. Can we close this?

**Comment by 520kaymann** [comment]
stellarium-23.1-qt6-win64.exe installs as 32 bit program? and still maxes out the one CPU core. Where can I please get the true 64 bit exe

**Comment by gzotti** [comment]
As noted, reported and fixed elsewhere for future releases, the default install location is wrong. The program is 64bit. Omit "(x86)" from the proposed install path. 
The "max out one core" will not solved by this. The main thread runs on one core, and the operating system takes care of assigning cores, see above.

**Comment by 520kaymann** [comment]
Thank you:
1) Task Manager properly identifies Stellarium as 64 bit - Thank you.
2) Control Panel - Add Remove Programs  Names it 32 bit - but it is actually 64 bit so no biggie.
3) 1.2 freezes on removal, task manager proccess kill and it is gone from Add Remove

The Bottom Line: The GUI is fantastic for live frame rate adjustments - I can slow it to a crawl if I want for everyday backdrop stuff and speed it up for other uses if need be. In other words you all nailed this one down perfectly!
