### ISSUE TITLE
Wrong position and classification of Abell 81 = IC1454 (data base error)

### ISSUE THREAD

**Issue by energiebrand** [Stellarium/stellarium#3078]
### Expected Behaviour

The object should be found at the correct position and classified as a Planetary Nebula.

### Actual Behaviour

Searching for Abel81 (= IC1454 (Planetary nebula)) ends in a wrong position.
The object there is classified as a Galaxie cluster (but Abel81 is a Planetary Nebula).

### Steps to reproduce

Search for Abell81 and check position and name.
Then search for IC1454 and do the same.

### System
Stellarium 1.2 / Version 1.22.5 / Qt 6.4.0
Windows 10

![Abel81_correct_IC1454](https://user-images.githubusercontent.com/60507600/221839798-af4b7041-3312-4a40-aa11-b3fc0bdec28a.jpg)
![Abel81_wrong](https://user-images.githubusercontent.com/60507600/221839804-3ca44b5d-083b-4e4f-9db1-b5a4e2280679.jpg)

**Comment by alex-w** [comment]
@energiebrand please check the full name of used Abell catalog

**Comment by energiebrand** [comment]
Thanks a lot! I wasn`t aware that there are different catalogues for Galaxie Clusters and Planetary Nebulae...
