### ISSUE TITLE
Default user-dir is created even if it's overriden via arguments. (linux)

### ISSUE THREAD

**Issue by tdukv** [Stellarium/stellarium#3079]
### Expected Behaviour
The -u and -c options should make the program not look into the default location.

### Actual Behaviour
An empty ~/.stellarium/ directory is created, before continuing with the overriden locations.

### Steps to reproduce
1. Move ~/.stellarium/ somewhere else
2. Use -u option to point to the new location
3. The old default is created as an empty dir

### System
* Stellarium version: Stellarium 1.2 (v0.22.5)
* Operating system: Void Linux
* Graphics Card: N/A
* Screen type (if applicable): N/A

### Logfile 
```
$ stellarium -u ~/.local/share/stellarium/ -c ~/.config/stellarium/config.ini
User config directory does not exist:  "/home/<user>/.stellarium"
Creating directory  "/home/<user>/.stellarium"
 ------------------------------------------------------------
[ This is Stellarium 1.2 (v0.22.5) - https://stellarium.org/ ]
[ Copyright (C) 2000-2023 Stellarium Developers              ]
 ------------------------------------------------------------
Writing log file to: "/home/<user>/.local/share/stellarium//log.txt"
File search paths:
  0 .  "/home/<user>/.local/share/stellarium/"
  1 .  "/usr/share/stellarium"
Config file is:  "/home/<user>/.config/stellarium/config.ini"
```

**Comment by alex-w** [comment]
A workaround: please define environment variable `STEL_USERDIR` before run Stellarium
