### ISSUE TITLE
Milky Way invisible when scene is flipped

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3085]
The Milky Way seems to vanish when using the flip scene buttons. However, enabling flipping the scene both horizontally and vertically does not hide it.

I can reproduce this in the master on Windows, and on the stable 1.2 on Mac.

**Comment by gzotti** [comment]
Zodiacal Light has the same problem!

**Comment by gzotti** [comment]
@10110111 please can you look into this?

**Comment by 10110111** [comment]
The problem originates in `StelProjector::needGlFrontFaceCW()`. If I stub it with `return true`, things work again. Not sure whether it breaks anything.

**Comment by 10110111** [comment]
Actually, culling makes no sense in the full-screen-quad approach used in ZL and MW. I'll just remove the corresponding GL calls.
