### ISSUE TITLE
sat plugin: nadir sat reported as not sunlit while local night

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3098]
### Expected Behaviour
Sats that are below the horizon during local nighttime should (mostly) be reported as being sunlit.

### Actual Behaviour
![image](https://user-images.githubusercontent.com/3529789/224823384-022a4744-22a0-4eb9-80a9-9e8915819d19.png)

It looks like all sats below the local horizon are reported as "not sunlit" (pink="invisible")
![image](https://user-images.githubusercontent.com/3529789/224824173-94626063-f7c7-4c15-92e4-3933115a4d39.png)

### Steps to reproduce

1. advance to local nighttime (sun well below horizon)
2. select a sat that is about to dive towards the western horizon
3. track it so that the info block (left side of screen) appears
4. advance time so that the sat is well below the horizon - at this point, it should (probably) be locally lit

Bug: sat is reported as "not sunlit".

### System
* Stellarium version: 23.0.72-bdee5b6 [master]

**Comment by gzotti** [comment]
Satellites can be _invisible_ either because they are in shadow, or because they are below the horizon.

**Comment by axd1967** [comment]
> Satellites can be _invisible_ either because they are in shadow, or because they are below the horizon.

Yes, but they can be invisible AND still **sunlit**.

**Comment by gzotti** [comment]
Just that the developer of this plugin has decided to mark _invisible_, not shadowed objects in a different color. These are the satellites actually irrelevant to the observer.

**Comment by gzotti** [comment]
OK, the text message is wrong. Should be just "invisible".
