### ISSUE TITLE
sat plugin: umbra at "distance" (should be "altitude") does not correspond to selected sat's umbra

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3100]
### Actual Behaviour

![image](https://user-images.githubusercontent.com/3529789/224827010-a052b213-4e01-4c12-8c67-e92ba67238ba.png)
![image](https://user-images.githubusercontent.com/3529789/224827042-4813a9ec-f3ca-48ba-8185-a5c70e536ec8.png)

### Additionally

- wordings 
- [ ] phrasing: "_show umbra at **distance**_"  should be "_show umbra at **altitude**_" (as noted in https://github.com/Stellarium/stellarium/issues/2510#issue-1298098454)
- [ ] phrasing: "show Earth's umbra" should be "show umbra" or "show umbra for selected sat"  (idem penumbra) because there is only one "Earth umbra", but each sat has its umbra (depending on altitude)
- [ ] what is meant by "C.U."? -> make it "CU" or "Centre of Umbra"

### System
* Stellarium version: 23.0.72-bdee5b6 [master]

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
This "umbra at fixed distance/altitude" thingy currently seems anyhow not to do the things users would expect, at least not for LEO. We should disable the button and option at least for now. @alex-w ? 
C.U. is Center of Umbra, like for Earth's shadow for the Moon.

**Comment by alex-w** [comment]
> This "umbra at fixed distance/altitude" thingy currently seems anyhow not to do the things users would expect, at least not for LEO. We should disable the button and option at least for now. @alex-w ?
> C.U. is Center of Umbra, like for Earth's shadow for the Moon.

Ok

**Comment by axd1967** [comment]
This issue is still open, nevertheless I'd like to add a snippet of observations:

The current ISS marathon is a nice example of what's happening:

![image](https://github.com/Stellarium/stellarium/assets/3529789/11aac95f-0097-4174-9c18-05c2ffbaeb3b)


The ISS orbit is momentarily interrupted (yellow segment, ends in Leo), but the Earth shadow (drawn red) does not match what Stellarium predicts.

Interestingly, Heavens Above does not predict the temporary passage in darkness:

(https://heavens-above.com/passdetails.aspx?&satid=25544&mjd=60078.0378598858&type=A)
![image](https://github.com/Stellarium/stellarium/assets/3529789/e18b787f-13ff-4fe0-8384-59b8de5bd626)

http://www.satflare.com/track.asp?q=25544#TOP does:
![image](https://github.com/Stellarium/stellarium/assets/3529789/80878281-8592-48c3-b575-511912a6e8a4)

tracksat.space:

![image](https://github.com/Stellarium/stellarium/assets/3529789/86a8752b-dd02-4982-8817-e3074b5750c3)

**Comment by axd1967** [comment]
looking good.
it should be "umbra" rather than "Earth umbra", because it is dependent on the selected satellite or altitude.

I see no reason to make the selected versus virtual sat altitude settings mutually exclusive: two are related to the selected sat, the third is related to the selected altitude value.

![image](https://github.com/Stellarium/stellarium/assets/3529789/df8cafd3-3473-4c83-a027-3bee9bd0ce4d)
(Ideally, radio boxes should be employed to convey this desire.)

thx
