### ISSUE TITLE
Finkbeiner Ha survey missing - Mellinger colour survey comes and goes

### ISSUE THREAD

**Issue by phaseforth** [Stellarium/stellarium#3103]
The Finkbeiner all sky Ha survey has been missing for a few weeks.  (Note It is still available as an online selection in Aladin lite.)
The Mellinger colour survey has been missing for a while but appears to be back as I write this.

I use both extensively for creating my  ultra-widefield mosaics.

**Comment by gzotti** [comment]
The availability of these external resources is out of our hands.
