### ISSUE TITLE
Online query shows information about previous object

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#3104]
### Expected Behaviour
Online query would show information about current focused object.

### Actual Behaviour
Stellarium shows information about previous focused object.

### Steps to reproduce
1 Mark some object (clicking with mouse)
2 Open online query window
3 Choose Wikipedia or biblicalastronomy or other (maybe)
4 Then close online query window
5 Choose another object (clicking with mouse)
6 Open online query window

There are the previous object information. Not the current new object information. This is not a big problem. You can push again the button of information. But if there has been some time after previous object you perhaps doesn't remember that you have changed focus to another object.

### System
* Stellarium version: 23.0.71-0711842 [tarball]
* Operating system: Kubuntu 22.10

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/10986022/log.txt)

**Comment by alex-w** [comment]
Cannot confirm the issue

**Comment by gzotti** [comment]
If you just open the window without re-querying, this is expected. Press "Wikipedia" etc. again.
