### ISSUE TITLE
"SSL Handshake Failed" Errors Encountered When Updating Some Plugins

### ISSUE THREAD

**Issue by coctree52** [Stellarium/stellarium#3123]
### Expected Behaviour
Automatically downloading the latest files for plugins like "Exoplanets," "Pulsars," etc. to update the data.
### Actual Behaviour
Errors occurred and data were not updated. For plugins of exoplanets, pulsars, quasars, and meteor showers, the latest files couldn't be downloaded due to "SSL Handshake Failed". However, the satellites could be successfully updated.
### System
* Stellarium version: <0.22.5>
* Operating system: <Windows 7>
* Graphics Card: 
* Screen type (if applicable): 

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/11064472/log.txt)

**Comment by alex-w** [comment]
@coctree52 please upgrade to version 23.1
