### ISSUE TITLE
Eridanus' asterism seems to me wrong

### ISSUE THREAD

**Issue by Stellarhum** [Stellarium/stellarium#3126]
### Expected Behaviour
The Eridanus' asterism should pass through δ (Rana), π, γ (Zaurak), ο1 (Beid), and ν.
At least, that's what I see on Carte du Ciel, Skytech X and some other paper guides and maps (as Pocket Sky Atlas).

### Actual Behaviour
The Eridanus' asterism passes only through δ (Rana) and ν, and skips π, γ (Zaurak), and ο1 (Beid).

### Steps to reproduce
Display asterisms, and look at the Eridanus's asterism.

### System
* Stellarium version: stellarium-1.2-qt6-win64
* Operating system: Windows 10 Home
* Graphics Card: not relevant
* Screen type (if applicable): not relevant

### Logfile 
not relevant

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#constellation-lines-do-not-match-those-in-my-atlas

**Comment by Stellarhum** [comment]
Well, there isn't _de jure_ standard, but there is a _de facto_ standard.
I thought the features were there to satisfy the user. I don't understand what is the purpose of this one.

**Comment by gzotti** [comment]
What you see is the *de facto standard* Stellarium skyculture. You can easily switch to Sky&Telescope's figures or even design your own.
