### ISSUE TITLE
error: ‘class ShowMySky::AtmosphereRenderer’ has no member named ‘setViewDirShaders’

### ISSUE THREAD

**Issue by carlosal1015** [Stellarium/stellarium#3133]
### Expected Behaviour

Compiles fine as previous version stellarium 1.2 if [`calcmysky`](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=calcmysky) is installed.

### Actual Behaviour

The compilation process fail and throws and error during compilation time. See the full log below.

```
/tmp/makepkg/stellarium/src/stellarium-23.1/src/core/modules/AtmosphereShowMySky.cpp: In member function ‘virtual void AtmosphereShowMySky::computeColor(StelCore*, double, const Planet&, const Planet&, const Planet*, const StelLocation&, float, float, float, bool)’:
/tmp/makepkg/stellarium/src/stellarium-23.1/src/core/modules/AtmosphereShowMySky.cpp:703:36: error: ‘class ShowMySky::AtmosphereRenderer’ has no member named ‘setViewDirShaders’
  703 |                         renderer_->setViewDirShaders(shaderSources.first, shaderSources.second,
      |                                    ^~~~~~~~~~~~~~~~
```

### Steps to reproduce

```
$ curl -LO https://github.com/Stellarium/stellarium/releases/download/v23.1/stellarium-23.1.tar.gz
$ tar -xvf stellarium-23.1.tar.gz
$ cmake -S stellarium-23.1 -B build -DENABLE_SHOWMYSKY=ON
```

### System
* Stellarium version: 23.1
* CalcMySky version: 0.2.1
* Operating system:  Arch Linux Rolling Release
* Graphics Card: No apply
* Screen type (if applicable): No apply

### Logfile 

- [CMakeCache.txt](https://github.com/Stellarium/stellarium/files/11080306/CMakeCache.txt)
- [log.txt](https://github.com/Stellarium/stellarium/files/11080374/log.txt)

**Comment by alex-w** [comment]
This is may be important - the master and version 23.1 uses [this](https://github.com/10110111/CalcMySky/archive/0fb93ef8e602c463f167f7727d4d80382033caca.tar.gz) version of library.

**Comment by alex-w** [comment]
Related to [#13](https://github.com/10110111/CalcMySky/issues/13)

**Comment by 10110111** [comment]
Done: [v0.3.0](https://github.com/10110111/CalcMySky/releases/tag/v0.3.0).

**Comment by alex-w** [comment]
@10110111 please fix cmake in master also

**Comment by 10110111** [comment]
Done
