### ISSUE TITLE
stellarium version 23.1 did not start after installation on Ubuntu 22.04.2

### ISSUE THREAD

**Issue by tflyer-rgb** [Stellarium/stellarium#3134]
Expected behavior
Program starts without a problem

Actual behaviour

Starting Stellarium 23.1 with the following command stellarium produce the console output below.

Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Setting QT_QPA_PLATFORM=wayland did not help. The AppImage file Stellarium-23.1-qt5-x86_64.AppImage run as expected.

Steps to reproduce
Try to start stellarium-23.1 om Ubuntu 22.04.2
The installation with the following command

sudo apt-get install  stellarium-qt6

run without any problem, see attached Stellarium_23.1_Installation.txt

Operating system: Ubuntu 22.04.02
Graphics card: intel iRISx
Screen type: Notebook  resolution 1920 x 1080
[Stellarium_23.1_Installation.txt](https://github.com/Stellarium/stellarium/files/11081335/Stellarium_23.1_Installation.txt)
[Stellarium_23.1_Installation.txt](https://github.com/Stellarium/stellarium/files/11081341/Stellarium_23.1_Installation.txt)

**Comment by alex-w** [comment]
Please try install `qt6-wayland` package

**Comment by alex-w** [comment]
Ok, please install `qt6-qpa-plugins` package

**Comment by tflyer-rgb** [comment]
Thanks reinstalling libssl3 and installing qt6-qpa-plugins fix all the described problem.

**Comment by alex-w** [comment]
The new version should be coming today from our PPA

**Comment by alex-w** [comment]
@tflyer-rgb please run `sudo apt update && sudo apt upgrade`

**Comment by tflyer-rgb** [comment]
Up to now there are no upgrade after sudo apt update && sudo apt upgrade

apt serach stellarium show only a new 23.1 version without qt6

apt search stellarium
Sortierung… Fertig
Volltextsuche… Fertig
stellarium/jammy 23.1.0-upstream1.1~ubuntu22.04.1 amd64
  real-time photo-realistic sky generator

stellarium-data/jammy,jammy 23.1.0-upstream1.1~ubuntu22.04.1 all
  Stellarium data files

stellarium-qt6/jammy,now 23.1.0-upstream1.0~ubuntu22.04.1 amd64  [installiert]
  real-time photo-realistic sky generator

stellarium-qt6-data/jammy,jammy,now 23.1.0-upstream1.0~ubuntu22.04.1 all  [Installiert,automatisch]
  Stellarium data files

I just take a look at milestone 23.2 it says due by June25. For me 23.1 works fine with the additional installed packages. Thanks for this great piece of software.
