### ISSUE TITLE
AstroCalc - planet diameter wrong

### ISSUE THREAD

**Issue by doctee** [Stellarium/stellarium#3135]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by doctee** [comment]
In AstroCalc (curves - angular diameter vs. time) the angular diameter of Uranus, Neptune (and more?) is calculated wrong. For example, the Uranus diameter is calculated to 12-14" what is higher than expected.

**Comment by alex-w** [comment]
Why you think that data is wrong? This tool includes rings size into account.

**Comment by Atque** [comment]
> 

Ring size for Saturn might make sense, but not for Uranus or Neptune.
