### ISSUE TITLE
On big zoom mouse clicks are off

### ISSUE THREAD

**Issue by DarthGandalf** [Stellarium/stellarium#3136]
### Expected Behaviour
When I click on a star, it's selected

### Actual Behaviour
Some stars click fine, but some are not. To select the left star I need to click on empty space (pun intended) to the left of it
https://youtu.be/L5-CGJaUoNk

I tried to disable "atmosphere visualization", without it sky moves somewhat (I see the same stars in different place on screen), but it still misclicks

### Steps to reproduce
* Open Stellarium
* Zoom by *a lot*
* Try to click on stars

### System
* Stellarium version: 23.1
* Operating system: Gentoo linux amd64
* Graphics Card: Gigabyte Radeon RX 6700XT, x11-drivers/xf86-video-amdgpu-22.0.0:0
* Screen type (if applicable): Resolution 1920x1080, no scaling

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/11094530/log.txt)

**Comment by 10110111** [comment]
> Zoom by _a lot_

How much exactly? What does the FoV field show?

**Comment by gzotti** [comment]
It has to do with aberration correction. But also with aberration disabled, I find I cannot click on some stars.

**Comment by DarthGandalf** [comment]
> How much exactly? What does the FoV field show?

At 0.29° it's noticeable, at 0.0332° it's almost unusable

**Comment by alex-w** [comment]
Probably related to #365 also
