### ISSUE TITLE
r23.1  incorrect default installation folder

### ISSUE THREAD

**Issue by PaulJRead** [Stellarium/stellarium#3137]
Hi,   the Win64-bit installation is defaulting to the 32-bit  Program Files (x86) folder.   If not noticed and corrected by the user, this results in the update being equivalent to a clean install with apparent loss of all user variables including backgrounds etc.
Previous updates for Win64 platform have always defaulted to the correct Program Files folder.

**Comment by alex-w** [comment]
Duplicate of #3130
