### ISSUE TITLE
Bending grid below horizon

### ISSUE THREAD

**Issue by siegbert7** [Stellarium/stellarium#3139]
### Expected Behaviour
Normal Gridlines without curves

### Actual Behaviour
Bending grid, see attachemnt

### Steps to reproduce
Start Stellarium, turn on the grid, turn off the horizon, look at the grid.
Not a real problem, but looks strange.
The problem also exists in former versions

### System
* Stellarium version: 23.1 <stella
![BendGrid](https://user-images.githubusercontent.com/48695821/228594533-1980ff7a-80d0-421b-ba88-48b848c4980e.png)
rium-23.1-qt6-win64.exe>
* Operating system: <Windows 10 Home, 22H2>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by 10110111** [comment]
It's due to atmospheric refraction. Disable atmosphere, and this distortion will disappear.

**Comment by Atque** [comment]
It is also possible to set the atmospheric pressure to 0, to get rid of this effect. But that is unscientific.

**Comment by siegbert7** [comment]
> It's due to atmospheric refraction...

Sure ? If so, I would have expeected a more steady bending, not right and left in a small area. But may be.

**Comment by 10110111** [comment]
> not right and left in a small area

It's not left and right, but up and down. Notice how the bending is localized near the horizon. Or turn on the orbit for, say, the Moon, and see that the bent line describes precisely how the Moon moves with time. Of course, the part below the horizon is not physical, it's just to make the lines continuous when the ground is not displayed.
