### ISSUE TITLE
Option "Start Stellarium with stopped clock"

### ISSUE THREAD

**Issue by siegbert7** [Stellarium/stellarium#3140]
**Is your feature request related to a problem? Please describe.**
Zooming deep into the sky, you can see the stars moving across your screen. At the first time, this is fascinating. 

But after a while, the stars you want to examine, leave the screen. Time is moving ! Not a real problem, you can stop the clock and afterwards set the time.

When looking deep into the sky more than one time, every time you start Stellarium again, you have to stop the clock again. If you want to see a fixed time after starting, you can set this time as an option, see attachment. Ok. But after starting Stellarium you have to hurry up to stop the clock and correct the time a few seconds. Time is running ! 

**Describe the solution you'd like**
Sometimes I wished to have an option where I can say, that Stellarium starts with the clock stopped. See picture.

**Describe alternatives you've considered**
Stopping the clock every time I started the programm manually.

**Additional context**
![Stop Clock](https://user-images.githubusercontent.com/48695821/228606696-174e7529-d409-43f6-8697-e4edde6ae93b.jpg)

**Comment by alex-w** [comment]
A quick solution: add command `core.setTimeRate(0);` into `startup.ssc` script
