### ISSUE TITLE
Zooming sometimes leads to a hang for a second or two

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#3148]
### Steps to reproduce
1. Make sure that initial zoom level is on the order of 80°
2. Launch Stellarium during the night (or disable atmosphere after launching)
3. Scroll deeply at once to zoom quickly into about 10°

### Expected Behaviour
Smooth video, maybe with some loading messages but without stuttering.

### Actual Behavior
A progress bar appears in the bottom-left corner, first partially out of the frame, waits about a second, then on a subsequent frame it's completely visible and says "Loading 'Nebulae'" for another second, then the progress indicated increases, and soon after this the video resumes.

### System
* Stellarium version: 3a96310b84bf1b2e9de4f00c8b075ce0c148baf1
* Operating system: Ubuntu 20.04
* Graphics Card: Intel UHD Graphics 620
* Screen type (if applicable): FullHD

### Logfile
[log.txt](https://github.com/Stellarium/stellarium/files/11124605/log.txt)

### Config file
[config.ini.gz](https://github.com/Stellarium/stellarium/files/11124632/config.ini.gz)

**Comment by 10110111** [comment]
The call to `loaderThreadPool->setMaxThreadCount()` in `StelTextureMgr::StelTextureMgr` appears to be the reason of this problem. Apparently, 8 threads on my machine take too much CPU time and bandwidth, so that the animation stops working for some time. Replacing the `QThread::idealThreadCount()` with `4` removes all lags here, so that the progress bar shows growing percentage while the animation, albeit less smooth, still continues, making the app usable.

**Comment by 10110111** [comment]
My CPU is Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz, which has 4 cores and 2 threads/core.

> Or maybe, (my idealThreadCount is now 20), make it min(16, idealThreadCount()/2) ?

I'm not so sure how this will behave on other CPUs, including very high-end machines. Will reducing the number of threads slow down loading noticeably?

**Comment by gzotti** [comment]
I am "guilty" for 984951b3c04c25deed630679ec23bf81a794fe85 where I raised this number from 4 to 16, given the current generation of CPUs. I had expected a little speedup by loading more in parallel if possible, which was however almost unnoticed. The short stall was there before and after, and I did not notice a difference there, but yes, the loading bar vanished faster. Now, if actually starting the threads cause the stall and starting more threads causes longer stall, we should revert to fewer threads. 

What is your result for idealThreadCount()? On your HT CPU I expect 8, but it can also be 4. Maybe it should even become idealThreadCount/2-1.

**Comment by 10110111** [comment]
> What is your result for idealThreadCount()?

It's 8, as per the number of the logical CPUs.

> Maybe it should even become idealThreadCount/2-1.

I think this -1 is extraneous, but if you do this, don't forget to clamp below :) In fact, even if you only divide, the clamp is necessary.

Whether you should do such a change, you can check on a Raspberry or something similarly slow.

**Comment by gzotti** [comment]
Not quite, as this is only for x86_64... but I have i5-4750 and i7-2xxx to test.
The "-1" is to keep the main thread out of the count. On your CPU it would result in 3, i.e., main thread has one core, and three more for the others, and therefore thread count from Stellarium alone would not exceed physical core count. (Other processes may still utilize the HT'ed cores)

**Comment by 10110111** [comment]
I expect this to be a problem with I/O rather than actual CPU resources, so the use of the core count should only be considered as an estimate. On my machine 4 as the size of the thread pool works acceptably fast.

**Comment by gzotti** [comment]
Yes, I/O may be the actual issue. My current dev system loads from NVME, which is why I may not see much delay... The others have SATA SSDs. My 2014/15 netbook is my last system with a spinning HDD, as it is CPU limited (2-core, 1GHz) and did in no way gain speed when I tried an SSD. But it would also only launch 2 threads. And it's so dead slow that developing/test building is a real pain. (Install regular updates: 1/day including unavoidable post-update M$ telemetry tests. Compile: tens of minutes. Stellarium then runs pretty well, though (with OpenGL 4(.2/3?)), and was able to control my little mount when I last had time to use it. )

**Comment by alex-w** [comment]
The macro Q_PROCESSOR_X86_64 is working for all x64 processors, include arm64

**Comment by gzotti** [comment]
That's surprising, given the "X86" in the name.

**Comment by alex-w** [comment]
> That's surprising, given the "X86" in the name.

Defined if the application is compiled for 64-bit x86 processors. This includes all AMD64, Intel 64, and other x86_64/x64 processors. The [Q_PROCESSOR_X86](https://doc.qt.io/QT-6/qtprocessordetection.html#Q_PROCESSOR_X86) macro is also defined when Q_PROCESSOR_X86_64 is defined.

**Comment by gzotti** [comment]
Yes, but ARM is very much "The non-x86 CPU (tm)"...

**Comment by alex-w** [comment]
> Yes, but ARM is very much "The non-x86 CPU (tm)"...

Sorry, I fixed typo

**Comment by gzotti** [comment]
Is a macOS/arm64 build a "fat binary" which runs on Apple systems with either (legacy) Intel x86_64 (Core-i) or the new Apple arm64 CPUs?

**Comment by gzotti** [comment]
I tried on the i7-2xxx on Ubuntu 22.04.2. The ~1/2 s stall is there, regardless of using 4 or 8 threads. It's a one-time event visible on first zoom-in. 
If we assume that actual I/O activity causes the stall, the update reduces loading to 3 threads on 8-core systems, or 9 threads on 20-core systems which usually come with faster NVME SSDs. I hope this is OK.
