### ISSUE TITLE
Software bug? EndeavourOS Arch Linux

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#3150]
### Discussed in https://github.com/Stellarium/stellarium/discussions/3149

<div type='discussions-op-text'>

<sup>Originally posted by **rcec52** April  1, 2023</sup>
I'm having issues with the latest version of Stellarium 23.1 . The graphical landscape display is messed up. I'm using a Nvidia GeForce 1060 video card in an older computer. Previous versions worked fine. All of my software is up to date and I'm using the latest kernel from my OS. I've downloaded and installed files from the AUR arch repository, I also download the appimage from this site and installed the necessary software to launch and install this version on this computer. I still have the same issue with the graphical landscape display. It is messed up. Any idea's what can be causing this? I haven't a clue. 

![Screenshot from 2023-03-31 19-53-37](https://user-images.githubusercontent.com/129566671/229260337-09d1f0c4-f909-4aec-b971-19dfa601d6c0.png)
</div>

**Comment by alex-w** [comment]
@rcec52 please attach log.txt

**Comment by alex-w** [comment]
@rcec52 please share link or attach landscape also

**Comment by 10110111** [comment]
> Nvidia GeForce 1060

What driver are you using? `nvidia`, `nouveau`?...

**Comment by ilkant** [comment]
I had similair screen when I used open Nvidia source graphics drivers on my Linux Kubuntu system. When I replaced tähem to Nvidias closed drivers, problem disappeared.

**Comment by gzotti** [comment]
@rcec52 does using NVidia's closed-source driver solve your problem? We will close this after September 22 if this remains unanswered.
