### ISSUE TITLE
Input of new sensors does not change view when selected

### ISSUE THREAD

**Issue by pooky2483** [Stellarium/stellarium#3153]
-->

### Expected Behaviour
wireframe view size should change to represent new sensor size
### Actual Behaviour
sensor size stays the same as previously newly entered sensor
See screenshots labelled 'Preset'. Note 'Preset Sensor' is a default one
![New Preset 01](https://user-images.githubusercontent.com/3163682/229309238-7012397a-5994-43f4-8374-cd66be57d827.png)
![New Preset 02](https://user-images.githubusercontent.com/3163682/229309239-40e6328d-6d77-401c-b800-ebcfba7b9ff6.png)
![New Preset 03](https://user-images.githubusercontent.com/3163682/229309240-de015557-4baa-4869-87aa-f6d24fa5d3dc.png)
![New Preset 04](https://user-images.githubusercontent.com/3163682/229309241-32821dfa-ae75-485a-bc0e-7ebd1270ad54.png)
![New Preset 05](https://user-images.githubusercontent.com/3163682/229309242-ad514138-500c-47cd-b558-27d3239dfb5d.png)
![Preset Sensor ](https://user-images.githubusercontent.com/3163682/229309243-7b82d88c-3f6f-40aa-ae54-84e38c96444e.png)

### Steps to reproduce
Enter new sensor data
Sensor Name       Res X  Res Y  Chip Width Chip Height
ASI183MC PRO1 5496  3672  13.2            8.8
ASI183MC PRO2 3840  2160  13.2            8.8
ASI183MC PRO3 1920  1080  13.2            8.8
ASI183MC PRO4 1280  720    13.2            8.8
ASI183MC PRO5 640    480    13.2            8.8
ASI183MC PRO6 320    240    13.2            8.8
### System
* Stellarium version: 32.2.0
* Operating system: Windows 10 10.0.19044
* Graphics Card: NVIDIA GeForce RTX 2070 SUPER 31.0.15.1694
* Screen type: ASUS VG2799 1920 x 1080 8-bit

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/11130356/log.txt)

**Comment by gzotti** [comment]
What is the problem? All your sensor are equal sized, and the default sensor is Full-frame SLR size. Or do you expect that the Moon stays as large as in the other frames, and the red sensor box would shrink? The developer has decided for this solution.

**Comment by gzotti** [comment]
The relevant data are sensor size (visualized by the red box) and pixel count (not visualized). Pixel size is regarded as trivial derivative found by a division of chip size by pixel count. 

You have given ResX and ResY values which mean that the chip size is divided by that many pixels. If you want instead to express that you only take (e.g. PRO6) a sub-frame of 320x240 with the same-sized pixels like for the full PRO1 out of a 5496x3672 frame, you simply multiply pixel size by pixel count to reach the actually used chip size.

**Comment by alex-w** [comment]
@pooky2483 please shoot couple images of the Moon with different resolution settings on real hardware and show the results.

**Comment by gzotti** [comment]
We have provided the relevant information.
