### ISSUE TITLE
Fix-Text mode no longer works

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#3154]
The command-line option `--fix-text` (`-t`) used to be useful to overcome issues with bad font rendering on some weaker systems line Raspberry 2/3 in 2016.

### Expected Behaviour

Render fonts to pixmaps which get then properly displayed

### Actual Behaviour

I see mangled rectangles with random characters or pixel noise in the scene. The menu texts are displayed somewhat mangled with off geometry, this can be a part missed in #3125.

Describe or maybe attach a screenshot?

### Steps to reproduce

Run with CLI option `-t` . See scene

### System
* Stellarium version: 23.1+
* Operating system: Windows 11
* Graphics Card: Geforce M3070Ti
* Screen type (if applicable): likely irrelevant

**Comment by 10110111** [comment]
The text now renders, though in some places it's skewed (dunno if it used to be like this before the main breakage), and in all places it's ugly.

**Comment by gzotti** [comment]
Thanks!
Originally (2016? Or has this then been a revival of 2012/13 work? I cannot remember.) it looked practically like the normal screen text, sans antialiasing. Too much has changed since it became actually unnecessary for the Pi (2018?). The aim of this is to have at least basic functionality on terribly broken systems. Fortunately I have none any longer... Not sure if rotated text came later? It was certainly added in more places, so maybe this introduces unwanted skews now.

**Comment by gzotti** [comment]
Hmm, the skew in the Arcturus label is weird. This is never rotated. The horizon labels are rotated in some projections. 
Yes, menu looks like before (no antialiasing, but readable). What about the screen text when selecting an object?

**Comment by 10110111** [comment]
The skew was introduced because of blind following a static analyzer in afe4a846a00044234727bd178c9a33df8ed9257b. I'll revert the breaking chunk.

**Comment by 10110111** [comment]
Pushed. This is the fixed look:

![stellarium-007](https://user-images.githubusercontent.com/6376882/235255222-e01a4355-565e-4586-8cb3-e83b4758cad0.png)

**Comment by gzotti** [comment]
Excellent! :-)
