### ISSUE TITLE
cannot filter sat dialog

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3158]
### Actual Behaviour
(similar to #2939 )

### Steps to reproduce

1. open sat dialog
2. select a category from the dropdown, eg comm sats
3. filter for "starlink"
4. observe that other names still appear

### System
* Stellarium version: Version 23.1.89-af1279f [master] Based on Qt 5.12.8
* Operating system: ubuntu 20.04

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
I cannot reproduce the issue
