### ISSUE TITLE
Ability to Import and Mark Objects List from the Minor Planet Center Objects by Properties

### ISSUE THREAD

**Issue by lf0k0nle** [Stellarium/stellarium#3162]
As far as I can tell, the only way to mark customized MPC solar system objects is to import them into the Solar System Editor as an MPC list from the limited selection of hard-coded MPC bookmarks, and then search for them individually and add them one by one to a custom observing list and then highlight them. The first problem is that this method can be tedious for hundreds of objects in order to look at object distributions on the celestial sphere. This is important in looking for observational biases in relation to discovering objects relative to the galactic plane. The second problem is that none of the hard-coded Stellarium bookmarks links to the objects I'm interested in, namely detached trans-Neptunian objects. They can be only be accessed at https://minorplanetcenter.net/db_search page at the bottom where the very customizable search for "objects by properties" lies. Unfortunately, this outputs a list of orbit parameters that is in different and incompatible format from the hard-coded Stellarium bookmarks links in the solar system editor or the import list format of the import observing list dialog box.

**Comment by gzotti** [comment]
If you are one of the few users who are interested in the distribution of detached transneptunian objects w.r.t. the Galactic Plane, you may be in the position to convert these data to the required format (see User Guide) with some other script of yours. Or even add this feature/interface to the SSO editor plugin.

**Comment by lf0k0nle** [comment]
You're welcome!  I should add the these detached, extreme trans-Neptunian objects (ETNOs) are very important to astronomers looking for the hypothetical Planet Nine. As the Rubin observatory's Legacy Survey of Space and Time comes online next year, astronomers expect this population of detached ETNOs to increase dramatically in the Minor Planet Center database, so I think there will be a growing public interest in these objects. For more info see planetninearchives.com

**Comment by gzotti** [comment]
When you manage to filter the data into a list format compatible to MPC's usual asteroid or comet files, you can import those MPC data files after downloading and textfile editing. This works now. Waiting for new filtering buttons to appear can turn into a long wait.

**Comment by lf0k0nle** [comment]
Been there, done that.

**Comment by gzotti** [comment]
If you did not ask to import only particular objects by filtering by properties from a larger list on import, can we close this? Or what exactly should be the outcome of this feature request? What should change in Stellarium?

**Comment by lf0k0nle** [comment]
Yes, sorry for the misunderstanding.

**Comment by gzotti** [comment]
OK
