### ISSUE TITLE
Observing list export/import path

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#3165]
**Is your feature request related to a problem? Please describe.**
When I export or import observing list, it uses users home directory (in Linux system). I want to use for example ~/Documents/Stellarium/observinglists/ directory to export and import lists. Or that directory can be for example ~/.stellarium/observinglists/ .

**Describe the solution you'd like**
Stellarium can have path to importing and exporting observing lists. It can be in config.ini file as a setting. Or setting in tools dialog like screenshot directory setting.

**Comment by gzotti** [comment]
For 23.3 after string freeze this is only a manual entry in config.ini.

```
[main]
observinglists_dir = path_to_whereever
```
 GUI changes may be added later.
