### ISSUE TITLE
Location on map not updated when selecting solar eclipses

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3171]
When searching for all solar eclipses, double-clicking on an eclipse in the list takes you to the location and time of the maximum eclipse ("Greatest eclipse's point"). Looking at the map in the Location dialog, the arrow will have moved and the coordinates will have changed correspondingly. However, this only works with the first eclipse you select. Selecing another one will not update the map, although the location will have been changed to that of the maximum eclipse. It appears some update to the Locations dialog is not done.

A work-around is to select a location from the list of locations, and then select the desired solar eclipse.

I can reproduce this in the current master, Qt 6.4.0, Windows 10 64-bit.

**Comment by gzotti** [comment]
Ah yes. This is setting another "location of greatest magnitude" with the same name, which we had optimized away... :-/

**Comment by 10110111** [comment]
> I wonder why switching locations takes so much time

If altitude changes, ShowMySky has to reload new texture slices. Not good, I know, but I don't currently know of a good way to fix this (except by loading the whole 4D texture at once, which might be bad for large sky models).

**Comment by gzotti** [comment]
Ah, thanks. Hmm, when switching from one "location of max eclipse" to the next, altitude should stay the same. And the wait time is also with active Preetham model. Would that still load SMS textures before continuing? (There are no log messages of any kind.) I think such long switching times should cause feedback by either loading bar or at least "wait" cursor. Often double click does apparently nothing, then I wait 5-10 seconds or more before I try again.

**Comment by 10110111** [comment]
> And the wait time is also with active Preetham model

Then this is not the (only) reason.

**Comment by 10110111** [comment]
Actually, the delay might be related to #3148.

**Comment by gzotti** [comment]
Loading DSO textures during totality? I don't think so. But maybe new #3173. Something around loading location. Maybe there is some circular Qt messaging going off?

**Comment by gzotti** [comment]
This is without Satellites plugin even built.
