### ISSUE TITLE
Clicking on map to change location gets increasingly slower from click to click

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#3173]
### Expected Behaviour

Click on the map in LocationPanel sets new location within a short reaction time with every click

### Actual Behaviour

Clicking 3-6 times to set various random locations takes longer and longer to set new location

### System
* Stellarium version: 23.1
* Operating system: Win11
* Graphics Card: Geforce (likely irrelevant)

### Logfile 
Nothing suspicious

**Comment by 10110111** [comment]
Does it happen with Qt 5?

**Comment by gzotti** [comment]
Unfortunately, yes. At least 5.15.2.

**Comment by alex-w** [comment]
I can't reproduce the issue in macOS

P.S. When I/O is happened then choosing the location is a bit slowly of course

**Comment by gzotti** [comment]
But it should not become slower and slower. Why does the 5th click already take several seconds (~twice the time of the 4th click) to compute coordinates from the map (or do something else in the background)? There is no landscape to load, what sort of heavy IO would be triggered?

**Comment by alex-w** [comment]
> But it should not become slower and slower.

Not in the macOS

**Comment by alex-w** [comment]
Stop! This is really slow when atmosphere is disabled!

**Comment by gzotti** [comment]
I have atmosphere on. But something unexpected must be going on here. 
Is there a way (debug command) to let Qt write out triggered signal connections ?

**Comment by alex-w** [comment]
Georg, please try follow:
* Run Stellarium
* Disable atmosphere
* Open Location dialog
* Disable showing stars (S)
* Enable showing stars (S)
* Random click on the map

What happening on your side?

**Comment by alex-w** [comment]
Hmm... Setting time zones in `setLocationFromMap` may be removed, because it set in `setFieldsFromLocation` and the last one is called within `setLocationFromMap`

**Comment by gzotti** [comment]
Maybe. But what happens here that slows it down? I had to set this to return to default location/landscape. 
Why are there in StelCore::moveObserverTo() two emits which send locations?

**Comment by alex-w** [comment]
I can't reproduce the issue in Stellarium 23.1/Win10 O_o

**Comment by alex-w** [comment]
OK, I've remarked line 199, builded the planetarium and run it.

* Open Location dialog
* Random clicks on the map without slowings
* Select the Venus and Ctrl+G
* Of course the map is not changed, but when I click on the map I see in the log:
```
"Can't create StelObserver on planet SpaceShip because it is unknown. Use Earth as default."
"Can't move from planet SpaceShip to planet Earth because it is unknown"
```

OK, other experiment. Revert commenting line 199 and disable code for `mapWidget ` in `setLocationUIvisible` - everithing fast!

What is happened here? A cycle: mapWidget (emit positionChanged) -> LocationDialog (setLocationFromMap - > moveObserverTo) -> StelCore (emit targetLocationChanged) -> LocationDialog (updateFromProgram -> setLocationUIvisible) -> mapWidget (emit positionChanged)

**Comment by gzotti** [comment]
I see for this use case it is OK now. But it may have not cleared the original problem. But #3171 is then still not good. I don't know why the loading of best place takes so long, even with Preetham atmosphere. Maybe a similar loop. So, we'd better review the connected actions...

**Comment by alex-w** [comment]
@gzotti please check master

**Comment by gzotti** [comment]
Selecting a contact time from the lower box works. However, should selecting the main line in the upper dialog not also set best location? This occasionally works, but more than often does nothing. 
I just made sure to load the zero landscape (2c6a603f76b44). Whatever landscape you currently have, you will almost certainly be taken elsewhere...

**Comment by gzotti** [comment]
This was not a good fix. Select SolarSystemObserver and click into the image. The solution in #3180 seems to work.
