### ISSUE TITLE
Different historical time zones on MacOS?

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3177]
I was amusing myself with recreating the flag of Brazil, which shows the southern sky as seen from Rio de Janeiro at 08:30 on November 15, 1889. Selecting Rio de Janeiro and entering the time, I noticed that the time zone was set to the very curious UTC-03:06. It seems to fit with the time zone used in São Paulo in 1889, and I guess it was used nationwide.

See the screenshot below. Note how the time zone is set to the peculiar UTC-03:06.

![stellarium-009](https://user-images.githubusercontent.com/37028368/231871866-4d4ecc76-24ea-47bc-a1cf-0df4b1d8ad8a.png)

However, I can't replicate this on Windows. Is there a reason why this only shows on the MacOS? Bug?

**Comment by gzotti** [comment]
Qt relies on timezone data available from the operating system. While Unixoids use tzdata with highly interesting historical results, Windows does not provide such free luxury. 

https://doc.qt.io/qt-6/qtimezone.html

**Comment by Atque** [comment]
That solves the mystery. Bummer for Windows users then!
