### ISSUE TITLE
[linux][wayland] high load on GPU

### ISSUE THREAD

**Issue by lilydjwg** [Stellarium/stellarium#3178]
### Expected Behaviour
low load on GPU, smooth display (as before).

### Actual Behaviour
100% GPU load, loud fan, laggy display, 15-17fps (this is lower than Minecraft!).

### Steps to reproduce
Just start it.

### System
* Stellarium version: 23.1 (Qt 6.5)
* Operating system:  Arch Linux latest
* Graphics Card: Intel Corporation HD Graphics 630 (Wayfire, wlroots)
* Screen type (if applicable): 3840x2160, 2x

### Logfile 

[log.txt](https://github.com/Stellarium/stellarium/files/11232285/log.txt)

**Comment by oldherl** [comment]
I am experiencing the same amount of slowness, also on Wayland on Linux.
The first seconds were stuck at 0.28fps, then it resumes to about 15 to 45 fps and always changing in between. This is still very laggy and different from before.

Operating System: Arch Linux
Stellarium version: 23.1 (Qt 6.5)
Graphics Card: AMD Ryzen 7 6800H with Radeon Graphics
Desktop Environment: KDE (KWin) on Wayland
Screen type (if applicable): 3840x2160, 2x

Logfile with "stellarium -d":
[log.txt](https://github.com/Stellarium/stellarium/files/11232346/log.txt)

**Comment by ilkant** [comment]
You can try top-command in Linux console and see which process consumes processor time and resource.

I have i5-10400F processor and 32 GB memory. Top says that Stellarium uses 46,5 % of processor resources. That is biggest. Other are about 2 %. But fan doesn't make noise. Iam wondering if that depends Ryzen-processor...?

**Comment by oldherl** [comment]
>  Iam wondering if that depends Ryzen-processor...?
No, @lilydjwg was not using Ryzen processor.

**Comment by lilydjwg** [comment]
On Sat, Apr 15, 2023 at 05:21:32AM -0700, Ilpo Kantonen wrote:
> You can try top-command in Linux console and see which process consumes processor time and resource.
> 
> I have i5-10400F processor and 32 GB memory. Top says that Stellarium uses 46,5 % of processor resources. That is biggest. Other are about 2 %. But fan doesn't make noise.

CPU usage is not a lot, but GPU is full. intel_gpu_top shows stellarium is using all of it.

This is an integrated GPU so it's inside the CPU package and the fan cares about it.

-- 
Best regards,
lilydjwg

**Comment by 10110111** [comment]
How much CPU us used depends on what is turned on. If you have this problem right after starting Stellarium, without need to toggle anything, please share your `config.ini`.

**Comment by lilydjwg** [comment]
It's the one generated at startup: [config.ini.txt](https://github.com/Stellarium/stellarium/files/11239941/config.ini.txt)

**Comment by 10110111** [comment]
Ah didn't notice it's all about the GPU!

**Comment by alex-w** [comment]
@lilydjwg please check version 24.3 - it has some refactoring in rendering stuff

**Comment by lilydjwg** [comment]
Much better! I'm using a 1080p screen now, but it can almost stay at 60fps when idle, using 50% CPU and 30% GPU.
