### ISSUE TITLE
Stellarium 1.2.4  not saving settings

### ISSUE THREAD

**Issue by ciocartila** [Stellarium/stellarium#3189]
### Actual Behaviour
After I set my location from the configuration window and check save as default location ,I go to "save settings" and then restart Stellarium.But after I restart it keeps going back to Guereins so it doesn't save anything regarding the location.

### System
* Stellarium version: 1.2.4
* Operating system: <windows 10>
* Graphics Card: <Nvidia driver 531>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Do you have "retrieve location from network" activated? This should bring you to a location nearby. If that fails, it goes to Paris with landscape Guereins. 

Where do you read "version 1.2.4"? This should not exist.

**Comment by ciocartila** [comment]
Sorry.It's version 1.2.25.I checked "retrieve location form network" and that seemed to do the trick.But if i change the elevation it goes back to Guereins on the next restart.So I guess I'll have to leave the elevation as "zero"

**Comment by alex-w** [comment]
> .But after I restart it keeps going back to Guereins so it doesn't save anything regarding the location.

Stellarium database is not have location Guereins, but planetarium has landscape Guereins. Do you have enabled option "Position from landscape" from View (press F4)/Landscape dialog?

>Sorry.It's version 1.2.25.

Please show screenshot Help (press F1)/About window

**Comment by ciocartila** [comment]
It's version 1.22.5. I misspelled.Yes it's enabled .So I unchecked it and now everything is ok.I could even change the elevation,save settings,restart and the location is ok now.Thanks for the input.I wouldn't have guessed that at all.I noticed that this problem appeared since I updated to this version recently.I'm glad the issue has been resolved.
