### ISSUE TITLE
Unable to find ISS(Zarya) lately

### ISSUE THREAD

**Issue by MohdAaquibKhan** [Stellarium/stellarium#3191]
In the past I used to accurately locate and look at ISS Zarya, but recently I dont find it at all, is there a different pack I have to download for it. I know how to locate using search and have been doing it since long time. It doesnt work only for ISS and that too recently
![image](https://user-images.githubusercontent.com/106028987/233454611-eb0106c7-6449-4232-a450-9d400fcfb42f.png)

**Comment by alex-w** [comment]
Please check list of satellites in the Satellites plugin

**Comment by MohdAaquibKhan** [comment]
> Please check list of satellites in the Satellites plugin

Thanks, it works
