### ISSUE TITLE
Location Incorrect

### ISSUE THREAD

**Issue by MyNameIsDale** [Stellarium/stellarium#3196]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by MyNameIsDale** [comment]
Although new to Stellarium, to this point it has not been useful because of incorrect location (coordinates set from Google Earth) and horizon much too high.

**Comment by gzotti** [comment]
When you are new to a program, consider reading the introductory pages of the available documentation.

**Comment by MyNameIsDale** [comment]
Hello:

Thank you for the response.
Unfortunately, the suggestion(s) did not solve my problem.
Although I've double-checked my coordinates several times, the 
Stellarium's night sky is considerably off from the visible sky in my 
location. I am using my computer's time which is correctly set to our 
current Atlantic DST and my location is about 30 m above sea level 
(according to Google Earth).
Many very visible night sky objects are not visible in Stellarium (below 
the horizon).
As a work around, I've tried increasing my elevation by 10 times, yet 
the problem remains.
Also, Stellarium's sky is skewed north. For example, Venus shows in 
Stellarium as being located in the WNW, rather than in the SE sky 
shortly after sunset.

The manual is not helpful in dealing with this problem.

Thank you,

Dale Mullen

Dale Mullen
302 Lakeside Road
Hebron, N.S.
B5A 5K4
Canada


------ Original Message ------
From "Georg Zotti" ***@***.***>
To "Stellarium/stellarium" ***@***.***>
Cc "MyNameIsDale" ***@***.***>; "Author" 
***@***.***>
Date 2023-04-23 5:18:46 AM
Subject Re: [Stellarium/stellarium] Location Incorrect (Issue #3196)

**Comment by 10110111** [comment]
You should really be more specific about the exact point of your location as reported by Google Earth, and show the _Location_ dialog. From the description you gave it just looks like you made a mistake when using the Google Earth's output to input to Stellarium. E.g. confused latitude and longitude, entered in the wrong format like decimal degrees vs degree-minute-second, etc.

Without the details we have to resort to our crystal balls to diagnose your issue.

**Comment by MyNameIsDale** [comment]
Thank  you for your response.

The exact settings put into Stellarium are:
43 55 13.16 N
66 06 29.67 W
Elevation 30m

Time is set to my computer's system clock

Is there a problem with the format above.

Thanks,

Dale

Dale Mullen
302 Lakeside Road
Hebron, N.S.
B5A 5K4
Canada


------ Original Message ------
From "Ruslan Kabatsayev" ***@***.***>
To "Stellarium/stellarium" ***@***.***>
Cc "MyNameIsDale" ***@***.***>; "Author" 
***@***.***>
Date 2023-04-27 2:49:33 PM
Subject Re: [Stellarium/stellarium] Location Incorrect (Issue #3196)

**Comment by MyNameIsDale** [comment]
Yes.
Seemingly, I had no quick way to show the degree symbol in my Email 
program, so I left out the signs.
You typed the locations correctly.

Dale Mullen
302 Lakeside Road
Hebron, N.S.
B5A 5K4
Canada


------ Original Message ------
From "Ruslan Kabatsayev" ***@***.***>
To "Stellarium/stellarium" ***@***.***>
Cc "MyNameIsDale" ***@***.***>; "Author" 
***@***.***>
Date 2023-04-27 3:23:07 PM
Subject Re: [Stellarium/stellarium] Location Incorrect (Issue #3196)

**Comment by 10110111** [comment]
To make things unambiguous, could you give the link to the location at Google Maps, and a screenshot of the _Location_ dialog in Stellarium?

**Comment by gzotti** [comment]
When I select e.g. Yarmouth, North America, time zone is set to America/New_York  which resolves to UTC-4:00. After sunset, Venus is of course in the WNW. It cannot be opposite the sun in SE.

Uh, I just saw it's the wrong Yarmouth (Cape Cod). Selecting Halifax as representant of any location in N.S. sets timezone America/Halifax which resolves to UTC-3:00. 

Changing elevation does not change your horizon elevation as described elsewhere. (https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#when-i-raise-the-altitude-of-my-location-why-does-the-landscape-not-move-down)

**Comment by 10110111** [comment]
Your asterix-censored URL didn't work for me. Anyway, from your signature I found that your coordinates are OK: at least they are consistent with Hebron, N.S.

What makes me wonder is this:

> For example, Venus shows in Stellarium as being located in the WNW, rather than in the SE sky shortly after sunset.

Why do you expect Venus to be in south-east shortly after sunset? Given that the Sun sets near the west, Venus should also be roughly in the west.

**Comment by MyNameIsDale** [comment]
Hummm....

"Your asterix-censored URL didn't work for me."

Don't understand why that is occurring. Just now, I double-clicked on 
the link I emailed and it took me to a location right over my house.

Hopefully, if we get a clear evening (doesn't happen often in this 
area), I'll try to get out to do a recheck tonight.

Obviously, as you can easily tell, I'm not an astronomer although I'm 
familiar with a few stars, some of the constellations and planets. After 
being away from observations for a while, I became intrigued with Sirius 
when it made a spectacular showing earlier this spring.
All my "sky" applications were out of date so when looking for a 
replacement, I happened on Stellarium. It was disappointing not to be 
able to see Sirius in the program and found its location far below the 
horizon, while at the same time looking at the star, well above the 
actual horizon.

Polaris seemed OK (application and visual agreed) but the others didn't 
"seem" to be in the right place when viewed in Stellarium.

However, at this point my problem is why objects which are clearly 
visible to the naked eye are showing up in Stellarium as being below the 
horizon.

Local times are based on Atlantic Time (DST).

Thanks again,

Dale

.................................

------ Original Message ------
From "Ruslan Kabatsayev" ***@***.***>
To "Stellarium/stellarium" ***@***.***>
Cc "MyNameIsDale" ***@***.***>; "Author" 
***@***.***>
Date 2023-04-27 4:55:44 PM
Subject Re: [Stellarium/stellarium] Location Incorrect (Issue #3196)

**Comment by gzotti** [comment]
Probably the translation from email to github filters away that this weird incomplete string should be a clickable URL. Typing in the forum instead of sending emails to the forum may help. 

Sirius was in your southeast after sunset about three months ago. Meanwhile it's in your southwest early evening sky.

Seriously, show a screenshot of your location panel.

**Comment by MyNameIsDale** [comment]
Hello:

As shown above in this thread, the panel is:


Thanks for the help,

Dale


------ Original Message ------
From "Georg Zotti" ***@***.***>
To "Stellarium/stellarium" ***@***.***>
Cc "MyNameIsDale" ***@***.***>; "Author" 
***@***.***>
Date 2023-04-27 5:36:18 PM
Subject Re: [Stellarium/stellarium] Location Incorrect (Issue #3196)

**Comment by 10110111** [comment]
> As shown above in this thread, the panel is:

No image is present. You really need to either switch email client, or use GitHub web interface. In fact, I think GitHub might be unable to show attached images from email.

**Comment by MyNameIsDale** [comment]
Will this work?
![Current Location](https://user-images.githubusercontent.com/131567995/234988880-a7517a9a-858d-4f47-8f31-5c78aec61d0f.jpg)

**Comment by gzotti** [comment]
Yes. Now let us assume your PC clock is set correctly, time zone (trimmed off right side in this panel) is set correctly, then all should be OK. If not, identify unambiguously three stars, measure their altitudes and provide identification, UTC time and altitudes. Then let an astro navigator identify your location.

**Comment by MyNameIsDale** [comment]
My PC clock is right on (date and time - Atlantic daylight savings time).
I'm not sure just how to follow your suggestions to identify my current location. As it's already clouding over (very frequent in our area), I may not be able to do anything until a clear night.
At that point I'll attempt to do as you suggested, if I can figure out the process.
Thanks,
Dale

**Comment by MyNameIsDale** [comment]
However, at this time (7:55 pm locally), the sun is still above the horizon. However, Stellarium suggests that it's below the horizon as it doesn't show in the application at all???
This is my problem...

**Comment by gzotti** [comment]
If I place myself to Halifax, time is UTC-3:00. Sun is about to set. What is Atlantic Daylight savings time translated to UTC&pm;offset?
![stellarium-073](https://user-images.githubusercontent.com/18099873/235009541-5bcbf055-7e8d-435b-abfd-c7f05e6fde8e.jpg)

Advance time in steps of hours to see if you have a wrong timezone. Where in Your Stellarium sky is the sun? "Below the horizon" means just wrong, but does not help enough. Show a screenshot with horizontal coordinate grid on, sun or stars visible, time and location shown on the lower status line, and location panel. Yes, the thingy with the earth map! In its entirety.

**Comment by MyNameIsDale** [comment]
![Stellarium WSW Sky at 8-29 PM Atlantic Time](https://user-images.githubusercontent.com/131567995/235012178-b4c0f214-9b64-4dd8-9bf8-a0a021c51988.jpg)

**Comment by MyNameIsDale** [comment]
Atlantic Daylight Time is 3 hours behind Universal Time Coordinated. 1:30 pm in ADT is 4:30 pm in UTC. ADT to UTC call time. Best time for a conference call or a meeting is between 8am-3pm in ADT which corresponds to 11am-6pm in UTC. 1:30 pm Atlantic Daylight …

**Comment by gzotti** [comment]
So, what's wrong with the image now? I see the sun may have set behind the 5° elevated horizon, and twilight illuminates the scene. To see a zero-altitude flat horizon, load the zero-altitude "Zero Horizon" landscape. Apart from that, I cannot read coordinates of either the sun or a star (as requested). I also cannot see the location panel (as requested). For me, all looks OK now.

**Comment by MyNameIsDale** [comment]
April 28, 2023

I thought I had included everything you requested in the screen shot.
The exact co-ordinates of my locations were visible in the screen shot, 
in the lower left corner.
Neither the sun nor the stars were visible when you requested (cloudy 
west horizon and bright sky). However, if you would explain exactly how 
to get and send you the information you need, then I will try again to 
provide the information.
As explained, not many of our evenings are clear for star 
viewing/gazing.
I had planned on using Venus as a guide to what is visible but when I 
retired for the day at 11:00 pm, Venus was still well above the horizon 
(~20-30 degrees) although Stellarium suggested that Venus should only be 
a few degrees above the horizon.
Obviously I've missed a significant part somewhere in the settings. It's 
been a number of years since I've used a computer-based star locater but 
this is a problem not previously experienced.

Thanks again,
Dale

------ Original Message ------
From "Georg Zotti" ***@***.***>
To "Stellarium/stellarium" ***@***.***>
Cc "MyNameIsDale" ***@***.***>; "Author" 
***@***.***>
Date 2023-04-27 9:17:59 PM
Subject Re: [Stellarium/stellarium] Location Incorrect (Issue #3196)

**Comment by 10110111** [comment]
How do you make sure that what you identify as Venus is actually Venus? In the SE part of the sky that you mentioned previously there's Arcturus, which is also relatively bright, and quite high. Is it possible that you misidentified the bright point?

**Comment by MyNameIsDale** [comment]
April 28, 2023

What I'm referring to as Venus was visible about 20-30 degrees above the 
horizon in the WNW sky at 11:00 pm (Atlantic Time). With the haze at 
that time, only a few stars/planets were visible although the moon was 
visible high overhead.
I was trying to find something bright, close to the west horizon, so 
that I could make a direct comparison.

Thanks,
Dale

------ Original Message ------
From "Ruslan Kabatsayev" ***@***.***>
To "Stellarium/stellarium" ***@***.***>
Cc "MyNameIsDale" ***@***.***>; "Author" 
***@***.***>
Date 2023-04-28 9:31:53 AM
Subject Re: [Stellarium/stellarium] Location Incorrect (Issue #3196)

**Comment by gzotti** [comment]
Venus was 10° high in WNW at that time, or 20° high one hour earlier, as shown in Stellarium for your location and timezone UTC-03:00. How do you perform measurements?

**Comment by 10110111** [comment]
To make sure that Stellarium computes it sensibly, try [TimeAndDate](https://www.timeanddate.com/astronomy/night/canada/halifax). It also shows that at 11pm Venus at about 8° altitude in Halifax.

**Comment by MyNameIsDale** [comment]
April 28, 2023

They are just approximate estimations. Using directly overhead to the 
horizon as 90 degrees, anything midway between these two points is 
considered ~45 degrees. A planet or star midway between the horizon and 
45 degrees, i've been classing as 20-30 degrees above the horizon.
Granted, these angles are not precise but accurate enough to help others 
find an approximate location in the sky.

Dale

------ Original Message ------
From "Ruslan Kabatsayev" ***@***.***>
To "Stellarium/stellarium" ***@***.***>
Cc "MyNameIsDale" ***@***.***>; "Author" 
***@***.***>
Date 2023-04-28 10:49:02 AM
Subject Re: [Stellarium/stellarium] Location Incorrect (Issue #3196)

**Comment by MyNameIsDale** [comment]
Thank you. I will try TimeAndDate as you've suggested on our next clear 
evening.

Dale
------ Original Message ------
From "Ruslan Kabatsayev" ***@***.***>
To "Stellarium/stellarium" ***@***.***>
Cc "MyNameIsDale" ***@***.***>; "Author" 
***@***.***>
Date 2023-04-28 10:49:02 AM
Subject Re: [Stellarium/stellarium] Location Incorrect (Issue #3196)

**Comment by 10110111** [comment]
> am not in any way an astronomer

I'm also not an astronomer ;)

> I'm working with a 32" screen so when a screen shot is required, it needs to be very specific as to exactly what part is needed

The whole Stellarium window is generally implied (or at least the sub-window that is requested; in my comment high above it was the _Location_ dialog, not a tiny rectangle inside it). 32" doesn't make it any harder, on Windows you get a screenshot of the active window into clipboard by just pressing <kbd>Alt</kbd>+<kbd>PrtScr</kbd>. Then you can paste it into MSPaint or any other image editor.

> and how to bring that specific information up on the screen.

The user is expected to be able to learn how to use the GUI of a new program. Stellarium is rather intuitive in this regard (compared e.g. to 3D editors), but even if you don't find it intuitive, just read the User Guide, e.g. chapter 3 has an introduction.

**Comment by MyNameIsDale** [comment]
At this very moment (8:19 pm Atlantic Time), the full sun is visible 
above the horizon. However, Stellarium claims that the sun is below the 
horizon!
This is the problem for which so far, I can find no correction.
This of course is the original problem that I posed in this thread.

Dale



------ Original Message ------
From "Ruslan Kabatsayev" ***@***.***>
To "Stellarium/stellarium" ***@***.***>
Cc "MyNameIsDale" ***@***.***>; "Author" 
***@***.***>
Date 2023-04-28 7:11:13 PM
Subject Re: [Stellarium/stellarium] Location Incorrect (Issue #3196)

**Comment by MyNameIsDale** [comment]
Just after the sun was completely below the horizon (8:28 pm Atlantic Time) from my location, this was the display on Stellarium. Is this what you needed?

![Stellarium's View at 8-28 pm Atlantic Time](https://user-images.githubusercontent.com/131567995/235269754-759e883d-6472-4cf0-b896-aa14c184beb1.jpg)

**Comment by gzotti** [comment]
What does it take?
- Press G to hide the Landscape.
- Click on the Sun to show textual information.
- Read Altitude value.

Is this altitude value smaller than zero?

Or is the sun only hidden by the ELEVATED HORIZON decoration which you can easily replace? 

A meaningful screenshot with object, info text and location panel looks like this:

![stellarium-074](https://user-images.githubusercontent.com/18099873/235269551-968b3688-d48d-4892-9da8-6c7724470a43.jpg)

**Comment by MyNameIsDale** [comment]
This is Stellarium's display at 8:39 pm (Atlantic Time).
![Stellarium Window at 8-39 pm April 28, 2023](https://user-images.githubusercontent.com/131567995/235270918-4d64946a-0998-49f5-9484-6a79c117f1dc.jpg)

**Comment by gzotti** [comment]
Everything is OK then. As suggested to you last week, 

> When you are new to a program, consider reading the introductory pages of the available documentation.

If you think the default landscape horizon displayed by Stellarium must match the horizon line of your backyard, you are expecting too much. As suggested yesterday, 

> To see a zero-altitude flat horizon, load the zero-altitude "Zero Horizon" landscape. 

We give targeted advice, but only so much. But we expect that you follow this advice.  We developers can then utilize our spare time better, i.e., for development.
