### ISSUE TITLE
Search result from previous session don't work

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#3199]
### Expected Behaviour
Search dialog remembers last session of Stellarium searched object below search input field. When clicked with mouse, Stellarium should go to that sky object.

### Actual Behaviour
If I search F3 some object for example HD 52071 and found that. Then I quit Stellarium. When I start next session with Stellarium, F3 search dialog has the HD 52071 under input. So it remembers that from previous Stellarium session. But when I click it with mouse Stellarium doesn't go to that object on screen. I have to type it again to input field and push search button. Then it finds that object on screen.

This is minor bug/feature. But I think that Stellarium might work better, if search result from previous session works like search result in this session . Or no results from previous session to new session.

### Steps to reproduce
1. Start Stellarium.
2. Find some sky object with F3.
3. Then quit Stellarium.
4. Start again Stellarium.
5. Go to search dialog (F3)
6. Click the previous sessions search result below input field. Nothing happens.

### System
* Stellarium version: <23.1+ (23.1.113-38dbf6a compiled on my computer yesterday)>
* Operating system: <Kubuntu 22.10>
* Graphics Card: <Manufacturer (MSI GeForce GT 1030 2GH LF OC, Nvidia drivers>
* Screen type (if applicable): LG 34GK950F 3440x1440

**Comment by alex-w** [comment]
HD 52071 is not in Stellarium database, you find it via SIMBAD

**Comment by ilkant** [comment]
Here is original message, where I found that. When I searched on Stellarium, I founded it. But not that orange object. :)

https://www.reddit.com/r/Stellarium/comments/12uaqxi/whats_that_orange_thing_the_big_star_is_called_hd/

**Comment by alex-w** [comment]
Orange object may be asteroid :)
