### ISSUE TITLE
Steins versus Šteins

### ISSUE THREAD

**Issue by leonardcj** [Stellarium/stellarium#32]
In skycultures/translations.fab, why do you insist on 

.# TRANSLATORS: Asteroid (2867) Steins
.# TRANSLATORS: https://en.wikipedia.org/wiki/2867_%C5%A0teins
._("Steins","minor planet")

instead of the correctly accented spelling with the diacritic mark on the Š?

.# TRANSLATORS: Asteroid (2867) Šteins
.# TRANSLATORS: https://en.wikipedia.org/wiki/2867_%C5%A0teins
._("Šteins","minor planet")

Is just because you use MPC as your canonical reference for spelling?

It seems a mark of disrespect to Kārlis Šteins not to spell his name correctly.
https://en.wikipedia.org/wiki/K%C4%81rlis_%C5%A0teins

Just curious.

**Comment by alex-w** [comment]
No problem, you may use Šteins as name, but you will never seen and never find this asteroid on Minor Planet Center website with this name, because MPC uses ASCII encoding for files with orbital elements.

**Comment by leonardcj** [comment]
@alex-w  Okay, I suspected it was an ASCII versus UTF-8 issue at heart, I just wasn't sure whose problem it was.  It is a pity, and only one of the reasons that I am an advocate of UTF-8 everywhere.  Would adding the properly accented name after the more easily discovered one be an acceptable option that covers both issues?  I meant no disrespect to you or the astronomy community, only expressing the passion of an i18n/L10n advocate.

**Comment by alex-w** [comment]
We use data from MPC for minor planets and comets and you may use MPC search tool for quick validating acceptable names with diacritic chars. Of course we may use correct spelling in comments for translators.

**Comment by alex-w** [comment]
When MPC will switch to UTF-8 for orbital elements files, then we switch to usage diacritic chars in names.

**Comment by leonardcj** [comment]
Fair enough.
