### ISSUE TITLE
TimeZone for  "Yellowknife"  not found

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#3200]
### Expected Behaviour
No log error lines from that.

### Actual Behaviour
[log.txt](https://github.com/Stellarium/stellarium/files/11315726/log.txt)

StelLocationMgr::loadCitiesBin(): TimeZone for  "Yellowknife"  not found:  "America/Yellowknife"
StelLocationMgr::loadCitiesBin(): Summary of unknown TimeZones:
"America/Yellowknife"
Please report these timezone names (this logfile) to the Stellarium developers.

### Steps to reproduce
1. Start Stellarium

### System
* Stellarium version: <Stellarium 23.1+ 23.1.113-38dbf6a [master]>
* Operating system: <Kubuntu 22.10>
* Graphics Card: <MSI GeForce GT 1030/PCIe/SSE2 2GH LF OC, OpenGL 3.3, driver 3.3.0 NVIDIA 515.105.01>
* Screen type LG 34GK950F 3440x1440

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Thanks for reporting!
