### ISSUE TITLE
Which version do I download

### ISSUE THREAD

**Issue by Suehohenthaner** [Stellarium/stellarium#3203]
macos 10.14+; x86_64  or
macos 10.14+;arm64
 I have a desktop Macbook pro with 3 quad core Intel core i5. I just purchased a MacBook air laptop Apple M2. Both use Ventura. I see the _86 is a larger file size. Not sure what I need. Can you help?

**Comment by gzotti** [comment]
An Intel Core i5 is not an ARM. You will need one for each.
