### ISSUE TITLE
Importing observe list doesn't replace default observe list

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#3206]
### Expected Behaviour
When you import observe list from computer disk and allow it to overwrite default list, it replaces it.

### Actual Behaviour
Imported observe list doesn't replace default list. So you cant see at all imported observe list.

I think that there is other similair behaviors. So may be vice to draw finite automata and design what should be done each case. Default list can be saved default name json and then replaces. So this does not forget default observations.

Imported list might appear to observe window top to drop-down menu. Now it doesn't appear.

### Steps to reproduce
1. Create new observe list
2. Export it to pisces.json (or what you want)
3. Quit Stellarium
4. Start Stellarium
5. Import pisces.json observe list to Stellarium
6. Allow pisces.json to overwrite default list
7. BUG Stellarium does not overwrite default list. So you cant see pisces.json observations at all.

### System
* Stellarium version: <Stellarium 23.1+ 23.1.113-38dbf6a [master]>
* Operating system: <Kubuntu 23.04>
* Graphics Card: <MSI GeForce GT 1030/PCIe/SSE2 2GH LF OC, OpenGL 3.3, driver 3.3.0 NVIDIA 515.105.01>
* Screen type LG 34GK950F 3440x1440

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/11328131/log.txt)

**Comment by gzotti** [comment]
Seems exported list is malformatted.

**Comment by gzotti** [comment]
The point was not anything around default list, but a newly-imported list was not available in the list selection.

**Comment by ilkant** [comment]
Well done! Now you can save and download lists. Another comment is that it would be good if this announcement could be localized for different languages.
![image](https://github.com/Stellarium/stellarium/assets/18149564/43692f43-3d8e-49a8-b188-d87176ac6b98)
