### ISSUE TITLE
Astro calc ceslestial positions major planets distances to Earth too

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#3216]
**Is your feature request related to a problem? Please describe.**
I am quite beginner on astronomy. I think that it would be nice if Astronomic calculator could have distances to Earth too. Now there are distances to Sun.

**Describe the solution you'd like**
Mathematical calculations of distances between planet and Earth. Adding them to data column and export to xlsx and csv.

**Comment by alex-w** [comment]
The distance from Earth for this tool is meaningless, because it is a virtual solar system model.

**Comment by gzotti** [comment]
I would not say so. In the positions tab we already give earth-centered (even location dependent) transit time and elevation and elongation, so, adding distance should be possible. Just the code gets longer and longer... 

When touching this segment, may I also suggest using arcseconds for planet angular sizes.

**Comment by alex-w** [comment]
> I would not say so. In the positions tab we already give earth-centered (even location dependent) transit time and elevation and elongation, so, adding distance should be possible. Just the code gets longer and longer...
> 
> When touching this segment, may I also suggest using arcseconds for planet angular sizes.

Georg, please see the screenshot:
![stellarium-042](https://user-images.githubusercontent.com/88731/236165582-1d268daa-c639-43e7-98ea-46daf8a1419b.jpeg)

Why you think that this tool need distance from Earth?

**Comment by alex-w** [comment]
> So, OK, no large change required, but maybe arcseconds for apparent planet (all SSO) diameters.

All calculations in Positions/Major Planets are heliocentric and angular diameters for SSO is meaningless here too. Or you meant the first subtab?

**Comment by gzotti** [comment]
First subtab of course, like the rest of my misunderstanding.
