### ISSUE TITLE
SATELLITES  plugin- SEARCH.  23.1

### ISSUE THREAD

**Issue by JAY-Githb** [Stellarium/stellarium#3221]
Did I forget what to do already?
In SATELLITES CONFIGURATION
When I type into the Search box, nothing happens.

Also SETTINGS OF CUSTOM FILTER doesn't seem to do anything.

Thanks for refreshing my memory.
Jay

**Comment by alex-w** [comment]
Probably duplicate of #3158 - please check the report

**Comment by alex-w** [comment]
Hello @JAY-Githb 

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by JAY-Githb** [comment]
Hello.
I downloaded  this version.  SEARCH is now working correctly.
Stellarium 23.1+
Version 23.1.122-7b59b0c [HEAD]
Based on Qt 5.12.6

Thank you!

**Comment by alex-w** [comment]
Duplicate of #3158
