### ISSUE TITLE
With core.setObserverLocation you can change your observer location to another object. That is to say, an object that Stellarium knows, such as Jupiter or 1 Ceres.

### ISSUE THREAD

**Issue by HalleySTW** [Stellarium/stellarium#3222]
With core.setObserverLocation you can change your observer location to another object. That is to say, an object that Stellarium knows, such as Jupiter or 1 Ceres.
My goal is to "put myself" on a spacecraft, let's say BepiColombo, the Mercury explorer, and look back to the Earth-Moon system. 

But Stellarium does not know BepiColombo, and not many, if any, other spacecraft. Sure, I could put its Kepler elements in ssystem_minor.ini, but that's quite laborious every time with changing trajectories.

At ssd.jpl.nasa.gov/horizons I can download the trajectories of many spacecraft in RA, Dec and distance, as seen from the Earth. Right from the beginning of their  trajectory (launch), so you have the whole history in one file. 

I would like to use those RA, Dec and distance as input for something like core.setObserverLocation. Is such an option available?

_Originally posted by @stephanpls in https://github.com/Stellarium/stellarium/discussions/2108_

**Comment by gzotti** [comment]
Using RA/Dec as seem from earth will not help if you want to ride the spacecraft, though. A "TrajectoryOrbit" subclass of Orbit has to be implemented which can deal with a precomputed trajectory. 

We already have a wishlist entry for spacecraft trajectories. If time allows or some institutional grant can be provided...

**Comment by stephanpls** [comment]
Georg,

 

Where was I mentioned? Yes, in the past I contributed some stuff involving spacecraft, but other hobbies and work took me a little away from astronomy and Stellarium. Hobbies come, go and come back in waves, you know!

 

Cheers,

 

Stefan

**Comment by gzotti** [comment]
@stephanpls I did not write the original issue. @HalleySTW opened it, mentioned you and immediately closed this issue. Regardless, as we core developers get all issue entries, I just commented what would have to be done for it, and that it is a duplicate (without taking the time to find the actual issue entry). Case closed for me.
