### ISSUE TITLE
Comet not shown longer than year after date of Stellarium launch

### ISSUE THREAD

**Issue by imaginer21** [Stellarium/stellarium#3229]
I have a question - when I add a comet in the list by solar system editor, the comet is shown only a year after the current date, then it disappears. Is there a way to set the visibility of a comet further than only a year after date of using Stellarium? (f.e. I see comet C/2023 A3 now and can be seen until Apr 30, 2024, then it is not shown).

**Comment by alex-w** [comment]
I guess the orbital elements for comet C/2023 A3 are outdated already and it should be updated by Solar System Editor plugin.

In any was please see Stellarium User Guide, section D.2.2

**Comment by imaginer21** [comment]
Thank you. How do I update the elements? I only update with the SS editor, but this doesnt work.

**Comment by alex-w** [comment]
> Thank you. How do I update the elements? I only update with the SS editor, but this doesnt work.

It should works. What about version of your copy of Stellarium?

**Comment by imaginer21** [comment]
Last one, 23.1... using MPC but also Gideon van Buitenen database, but the problem remains. Once I get over 16/5/24, the image of the comet dissapears. In only shows it position, but no comet in the target.

**Comment by imaginer21** [comment]
Well, no text info appears. The comet only disappears. I tried to set different value to orbit_good parameter as well, but it didn't work. So you see the comet in your Stellarium after 16/5/2023 (I mean image of it)? What parameters do you have?

**Comment by imaginer21** [comment]
![obrazek](https://github.com/Stellarium/stellarium/assets/133754118/6e4ed7a4-807b-400f-8081-2607cbcfa63a)
![obrazek](https://github.com/Stellarium/stellarium/assets/133754118/38d04b60-2702-439f-afc1-3fd92ff61692)

[c2023a3(tsuchinshanatlas)]
absolute_magnitude             = 4.7
albedo                         = 0.1
coord_func                     = comet_orbit
dust_brightnessfactor          = 1.5
dust_lengthfactor              = 0.4
dust_widthfactor               = 1.5
name                           = C/2023 A3 (Tsuchinshan-ATLAS)
orbit_ArgOfPericenter          = 308.488
orbit_AscendingNode            = 21.5574
orbit_Eccentricity             = 1.00018
orbit_Epoch                    = 2460066.5
orbit_Inclination              = 139.1182
orbit_PericenterDistance       = 0.391273
orbit_TimeAtPericenter         = 2460581.1733
orbit_good                     = 1000
radius                         = 5
ref                            = MPEC 2023-HD1
slope_parameter                = 4
type                           = comet

In ssystem_minor (C/Users/user/AppData/Roaming/Stellarium/Data

but there is anothe ssystem_minor in c:\Program Files (x86)\Stellarium\data\

Now which one is working for this?

**Comment by gzotti** [comment]
Second image, last line in the text block.

The minor objects file is taken from the users' data directory because users are allowed to edit it. Never edit a file in C:\Program Files [(x86)]\Stellarium.

Now, change orbit_good=0 and the test is no longer performed. The comet will be plotted where the elements place it.

**Comment by imaginer21** [comment]
Sorry, orbit_good=0 is set now (in the AppData/Roaming folder), but no change. Comet disappears on May 1, 2024 :/

**Comment by imaginer21** [comment]
Working, thanks!
