### ISSUE TITLE
Obtain ecliptic obliquity in a script

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#3233]
### Discussed in https://github.com/Stellarium/stellarium/discussions/3231

<div type='discussions-op-text'>

<sup>Originally posted by **kishorekumar62** May 17, 2023</sup>
I am writing script and would like to obtain the ecliptic obliquity of date. I am unable to find the scripting API call that can give me this value. Can someone help?

Thanks in advance.
</div>

We could add this to the infoMap of the Sun.

**Comment by Yarolond** [comment]
I'm trying to calculate the coordinates of planets relative to the ecliptic. But I can't do this. Could someone please help me with this calculation?

**Comment by alex-w** [comment]
> I'm trying to calculate the coordinates of planets relative to the ecliptic. But I can't do this. Could someone please help me with this calculation?

https://stellarium.org/doc/23.0/classStelMainScriptAPI.html#aebaa4b5ef785df2227317844e95279d7
