### ISSUE TITLE
32 compass rose marks are slightly off-centered

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3235]
I noticed that the 32 compass rose marks are slightly off, see the screenshot below.

![stellarium-202](https://github.com/Stellarium/stellarium/assets/37028368/232128b5-a53b-4147-b8fa-97852e9c823e)

Notice how the SbW is slightly closer to the SSW than to the S. It should be centered in between them.

**Comment by gzotti** [comment]
I think I also see a distortion at SWbS and SWbW. Some of the vectors should also be normalized or built with sin/cos.

**Comment by ilkant** [comment]
BTW, how to install 32 compass rose marks to Stellarium? I didn't find that setting and plugin.

**Comment by gzotti** [comment]
> BTW, how to install 32 compass rose marks to Stellarium? I didn't find that setting and plugin. (But I have translated them.)

F4/Markings, left column, towards bottom.
