### ISSUE TITLE
Search doesn't draw square to object on screen

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#3238]
### Expected Behaviour
Search F3 goes to found object and draws a square around the object. So, it is easy to find on screen.

### Actual Behaviour
If the search object is for example Centauri A or Hanburger galaxy in deep space, Stellarium doesn't draw a square around the object. So, it can be hard to find it on screen. And if you use center the focus to object and you zoom in, square appears. And if you zoom out the square disappears.

### Steps to reproduce
1 Find (F3) NGC 5128
2 Stellarium doen't show square where it is

### System
* Stellarium version: <Stellarium 23.1.144-a6d653b [master]>
* Operating system: <Kubuntu 23.04>
* Graphics Card: <MSI GeForce GT 1030/PCIe/SSE2 2GH LF OC, OpenGL 3.3, driver 3.3.0 NVIDIA 515.105.01>
* Screen type LG 34GK950F 3440x1440

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/11552661/log.txt)

**Comment by gzotti** [comment]
When you search something, it will be centered on screen and marked with an animated rectangle with round corners or rotating circle with spikes (for stars). I think this is enough eye support. Or does this not appear on your screen?
![image](https://github.com/Stellarium/stellarium/assets/18099873/bd9ff18f-f3de-46b3-865b-d92038e98316)

**Comment by ilkant** [comment]
It doesn't appear on screen when searchin NGC 5128. Earlier Stellarium versions have worked ok, but this version 23.1.144 doesn't. And maybe this happens only deep sky objects. I can use center to object and then zoom in and again center to object. But it's not so easy to do that when you don't see the retangle.

**Comment by 10110111** [comment]
> But it's not so easy to do that when you don't see the retangle.

Why is it not easy? You can press <kbd>Space</kbd> or corresponding button in the bottom toolbar without even having the object in the frame.

**Comment by ilkant** [comment]
OK. That helps. But some previous Stellarium versions drew retangle to found object.

**Comment by gzotti** [comment]
I just rebuilt to make sure I have the same state of master. It just works as usual. I don't find how to switch off the auto-centering.

**Comment by alex-w** [comment]
I cannot reproduce the issue in master

**Comment by gzotti** [comment]
Any update on this?

**Comment by alex-w** [comment]
@ilkant please share config.ini file
