### ISSUE TITLE
Silent uninstallation not completely possible

### ISSUE THREAD

**Issue by LenzWinkler** [Stellarium/stellarium#3241]
### Expected Behaviour
The [INNO setup](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline) parameter '/SUPPRESSMSGBOXES' combined with '/SILENT' or '/VERYSILENT' should actually disable all message boxes.

### Actual Behaviour
In fact, the following message box is not suppressed:
![image](https://github.com/Stellarium/stellarium/assets/72972073/912baf37-013c-4bb9-923a-8bbc02b1c374)

Using '/SAVEINF=uninstall.iss' and '/LOG' I tried to find out if I can specify the answer 'Yes' or 'No' as a task or a component, but no answer file is created at all.

Possible reason: Any task message box displayed by [Code] support function `MsgBox` is not suppressible with '/SUPPRESSMSGBOXES'.

Perhaps you could predefine a default response or otherwise make it possible for the silent or unattended uninstall to go through completely automatically.

### Steps to reproduce
1. Install
2. Uninstalling via command line:  
* `"C:\Program Files\Stellarium\unins000.exe" /SILENT /SUPPRESSMSGBOXES`
* `"C:\Program Files\Stellarium\unins000.exe" /SILENT /SUPPRESSMSGBOXES /LOG`

### System
* Stellarium version: 0.20.2 and 23.1
* Operating system: Windows 10 22H2
* Graphics Card: VM (Microsoft Hyper-V-Video)

### Logfile 
Uninstaller log from `%TMP%`: 
[Uninstall Log 2023-05-24 #001.txt](https://github.com/Stellarium/stellarium/files/11557390/Uninstall.Log.2023-05-24.001.txt)

**Comment by gzotti** [comment]
I find this option so dangerous that I would just remove it. (I will not test it.)

**Comment by alex-w** [comment]
`MsgBox` in the [code] block is suppressible and default behavior for it is `No`

**Comment by LenzWinkler** [comment]
> `MsgBox` in the [code] block is suppressible and default behavior for it is `No`

OK, thanks Alex! But which CMD parameter then suppresses the said message box?

[Inno](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline) writes to '/SUPPRESSMSGBOXES':

> 5 message boxes are not suppressible:
[...]
Any [...] message box displayed by [Code] support function [...] `MsgBox`.

**Comment by alex-w** [comment]
I tried run `"C:\Program Files\Stellarium\unins000.exe" /SILENT /SUPPRESSMSGBOXES /LOG` - Stellarium removed successfully with one dialog with progress bar. What exactly you are expected to see?

**Comment by alex-w** [comment]
This is may be strange, but runnig `"C:\Program Files\Stellarium\unins000.exe" /VERYSILENT /SUPPRESSMSGBOXES` just quietly deleting Stellarium - without extra dialogs.

**Comment by LenzWinkler** [comment]
Sorry about that, you are absolutely right. I've now tried it again on a fresh VM:

- Version **23.1** with `"C:\Program Files (x86)\Stellarium\unins000.exe" /VERYSILENT /SUPPRESSMSGBOXES` runs **without** message box.
- Version **0.20.2** with `"C:\Program Files\Stellarium\unins000.exe" /VERYSILENT /SUPPRESSMSGBOXES` however not yet.

Unfortunately I have to update several classroom PCs from 0.20.2 to 23.1. I now do it this way, that I remove the old version directly on file and registry level with delete commands. From the new versions on, I can remove the software regularly via the uninstaller.

Thank you very much

**Comment by 10110111** [comment]
Could the difference be because of initial conditions of having or not having custom user configuration?

**Comment by alex-w** [comment]
Ability the silent uninstalling was added since version v0.20.4

**Comment by alex-w** [comment]
> This needs to go into the Guide. Which command-line options exist and are useful for such unattended installations/uninstallations?

It's not for regular users, but https://documentation.help/Inno-Setup/topic_setupcmdline.htm

**Comment by HorNet505** [comment]
there is a workround.
On a test client I ran an uninstallation using the parameter:
     /LOG:"%Windir"\Logs\Application_removal.log
In this log are all the steps visible to uninstall the app via command line.
You can basically take the log and replace "rd" "delete" whatsoever and have your uninstall script.
