### ISSUE TITLE
Charon moves opposite direction to the other Pluto moons

### ISSUE THREAD

**Issue by Ajaja** [Stellarium/stellarium#3242]
Charon moves the opposite orbit way around Pluto. 
Positions of Nix, Hydra, Kerberos and Styx  are far away from real too (I did some checks using Horizons here https://gist.github.com/Ajaja/02f67dc19d567f771f260d2939ba9ec8 ) but al least they move in right direction.

### System
* Stellarium version: 23.1

**Comment by gzotti** [comment]
Can you provide better orbital elements? In any case, Pluto and Charon have bound rotation.
For the others: sure. Just use updated elements. Where can we find them?

**Comment by gzotti** [comment]
Fine. Where do we find elements?

**Comment by Ajaja** [comment]
On Horizons System, as I said. For any epoch.
For example:
https://ssd.jpl.nasa.gov/api/horizons.api?format=text&MAKE_EPHEM=YES&COMMAND=901&EPHEM_TYPE=ELEMENTS&CENTER=%27500@999%27&START_TIME=%272023-05-25%27&STOP_TIME=%272023-05-26%27&STEP_SIZE=%271%20DAYS%27&REF_SYSTEM=%27ICRF%27&REF_PLANE=%27BODY%27

Previously I made a mistake in a sign in https://gist.github.com/Ajaja/02f67dc19d567f771f260d2939ba9ec8 
Now I fixed it.  Looks like after all Charon moves  in right direction, but all other Pluto moons move in Stellarium in wrong direction.

**Comment by Ajaja** [comment]
It's easy to get elements for any specific date: https://gist.github.com/Ajaja/b438bf50a2c21d4496f67c30c20c8871
Maybe, a better approach would be to calculate average elements for some reasonable period. 
Anyway, Kepler orbits won't be working well for long periods with Pluto-Charon system, especially for small moons, but at least correct ones for some epoch will fix direction of orbital movement.

**Comment by gzotti** [comment]
You can work out changes required in ssystem_major.ini and send a pull request. Indeed, elements in Horizon show a change, so any static solution is temporary only. If there is a model published for the non-Keplerian solution of Pluto's moons, we could also implement that. However, it is a problem that rarely causes me headaches. Most people have difficulties observing Pluto, let alone Charon, or even the smaller pebbles. For now we could just invert the motion of the smaller ones as qualitative fix.
