### ISSUE TITLE
Incorrect ocular rectangle for a photo lens

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#3249]
### Expected Behaviour

When choosing focal length of the lens and the sensor corresponding to my camera, and choosing perspective projection (which is what most non-fisheye lenses try to simulate), the red rectangle that's turned on by the _Image sensor frame_ button should be roughly the same as the rectangle of the photo I'd take with my camera, up to distortions of the lens.

### Actual Behaviour

* A change of projection doesn't change the shape of the rectangle, this is already suspicious.
* Aspect ratio of the red rectangle differs a lot from aspect ratio of my photos.
* Angle per pixel figures in the bottom-right part of the rectangle are different for X and Y direction, which doesn't make sense with my usual isotropic camera sensor.

### Steps to reproduce

* Make a photo with an APS-C camera like Canon 80D and e.g. a 10mm lens.
* Try to position the red frame in Stellarium so that the stars in the photo are situated similarly to the stars in Stellarium.
* Notice the discrepancy that can't be fixed by panning around.
* Note that the camera has square pixels (which you can check by taking a picture of a square) and a resolution of 6000×4000 implying aspect ratio of 1.5, but the rectangle in Stellarium has aspect ratio ~1.3.

### System
* Stellarium version: 23.1.126-17cbd6b
* Operating system: Ubuntu 20.04
* Graphics Card: Intel UHD Graphics 620

**Comment by alex-w** [comment]
Please share photos

**Comment by gzotti** [comment]
A rectangular box certainly cannot represent the distorted field of view of a 10mm lens. This is for aiming and getting a rough guide, and works well for long focal widths. For overlaying wide-angle shots, somebody has to rewrite that part. 
The different angle per pixel looks weird. Have you configured sensor dimensions and pixel count correctly? (Maybe sensor dimensions from data sheets have been rounded?)

**Comment by 10110111** [comment]
> A rectangular box certainly cannot represent the distorted field of view of a 10mm lens.

If we assume that the lens is an ideal perspective lens (we don't simulate actual objectives, so this is a sensible approximation), then a rectangular box in perspective projection is perfectly capable of representing the field of view of this lens.

> The different angle per pixel looks weird. Have you configured sensor dimensions and pixel count correctly?

I took the stock EOS 80D, whose parameters seem correct. The problem with this part appears to be that the calculation takes the whole FoV of the lens and divides it by the number of pixels, which is bound to be wrong due to non-uniform angular resolution in different parts of the frame (the center being the densest). If I compute just the resolution of the pixels from the center, it's isotropic.

**Comment by 10110111** [comment]
> Please share a photo and a screenshot

Here's my attempt at matching the photo and the Stellarium render. I made vertical sizes of the frame equal, and put Sirius at the same spot on the screen.

Photo (taken at 20.427°S, 57.36°E)
![photo](https://github.com/Stellarium/stellarium/assets/6376882/2aae2bb1-64ea-4431-8437-7213122a9dc6)

Screenshot
![screenshot](https://github.com/Stellarium/stellarium/assets/6376882/eeb0c60f-44e7-498e-b6b1-0380a54f071c)

**Comment by axd1967** [comment]
related to #3015?
