### ISSUE TITLE
changing location re-enables atmosphere 23.1.141-c98b3c9

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3250]
### Expected Behaviour
When disabling atmosphere and moving around, atmosphere should remain off

### Actual Behaviour
Atmosphere is re-activated

### Steps to reproduce

1. disable atmosphere (A)
2. open location dialog (F6)
3. move location

Bug: atmosphere is enabled

### System
* Stellarium version: 23.1.141-c98b3c9

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-148-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
I guess the option for automatic enabling the environment is enabled in settings, so, in this case this is not a bug

**Comment by axd1967** [comment]
> I guess the option for automatic enabling the environment is enabled in settings, so, in this case this is not a bug

Which setting would that be?

![image](https://github.com/Stellarium/stellarium/assets/3529789/0a3fdd07-a439-49c3-9d06-9529096ada70)
![image](https://github.com/Stellarium/stellarium/assets/3529789/80fb0a21-f47c-4520-9f38-f05e76171f87)

**Comment by axd1967** [comment]
Aha, this one

![image](https://github.com/Stellarium/stellarium/assets/3529789/eb7feba1-34dd-4629-b1d8-b93169fa0e03)

**Comment by gzotti** [comment]
#3180
