### ISSUE TITLE
Angle Measure plugin

### ISSUE THREAD

**Issue by classeschair** [Stellarium/stellarium#3253]
I recall that on first using angle measure it read in decimal degrees. Then I needed to use D-M-S units so selected that option. Now I can't get back! Can't break the D-M-S hold on angles. I see this has been mentioned by a few others but no answer to the problem appears anywhere.

There ought be a second option to select decimal degrees.

**Comment by alex-w** [comment]
Please check settings of the plugin

**Comment by gzotti** [comment]
I don't know who mentioned this before, please always add a link to such statements. The decimal degrees vs. deg/min/sec is in the F2 configuration window, tab Tools. 

In the plugin's settings, the dms switch only changes labeling between degree/minute/second symbol and "d"/"m"/"s". @alex-w I don't know if that is at all useful, or if the intention of this switch should rather be decimal degrees vs. DMS (with degree/minute/second symbol).

**Comment by alex-w** [comment]
> I don't know who mentioned this before, please always add a link to such statements. The decimal degrees vs. deg/min/sec is in the F2 configuration window, tab Tools.

This is correct statement, thanks!

> In the plugin's settings, the dms switch only changes labeling between degree/minute/second symbol and "d"/"m"/"s". @alex-w I don't know if that is at all useful, or if the intention of this switch should rather be decimal degrees vs. DMS (with degree/minute/second symbol).

The correct statement for the plugin settings and my mistake in my answer. Enabling decimal degrees switch whole planetarium to use decimal degree and this is correct behaviour IMHO.

**Comment by classeschair** [comment]
There's nothing to check. DMS is not selected. Nothing else to check. David
    On Thursday, June 1, 2023 at 01:41:56 AM EDT, Alexander V. Wolf ***@***.***> wrote:  
 
 


Please check settings of the plugin

**Comment by gzotti** [comment]
Do you actually see the plugin settings? And are you running V23.1 or any earlier version?

**Comment by gzotti** [comment]
To repeat myself
>The decimal degrees vs. deg/min/sec is in the F2 configuration window, tab Tools.

**Comment by gzotti** [comment]
Question solved.
