### ISSUE TITLE
Rotating sensor frames only rotates the labels

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3258]
Using the latest master `78ae8c5`, it appears that rotating the sensor frame does not work anymore, but only rotates the surrounding labels. See the screenshot below.

![stellarium-223](https://github.com/Stellarium/stellarium/assets/37028368/7f67759b-40d9-401c-9743-9442f94b1858)

Probably introduced by #3254.

**Comment by gzotti** [comment]
Yes I just discovered that a minute ago!

**Comment by gzotti** [comment]
Not yet in all modes! Switch main program to equatorial mode and move around.

**Comment by 10110111** [comment]
Erm... how should it actually look? Is the text orientation correct now in equatorial mode, or the frame?

**Comment by gzotti** [comment]
![stellarium-084](https://github.com/Stellarium/stellarium/assets/18099873/ba741d9a-1b3e-4207-b866-12675c147a33)
Frame is OK, text is bad.

**Comment by 10110111** [comment]
OK, the text should now always match the orientation of the rectangle, so this issue should be considered fixed.

What makes me wonder though, is that when "Equatorial mount" checkbox is checked, and the view is in equatorial mode, the frame is still aligned to the horizon. You say it's OK, but IMO it's wrong.

**Comment by gzotti** [comment]
Uh, that's indeed wrong. The principal axes of the sensor frame should be governed by the telescope's mount setting, not by the application's mount mode. Consider this as new bug.
