### ISSUE TITLE
Default list of comets

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#3261]
When I worked for partially fix an issue #3224 (see PR #3230) I got an important idea - we should revised the default list of comets: 
* The number of comets should be reduced (probably 10-15 comets at well - most bright and/or most famous and maybe expected be bright in near future)
* Historical data should contains correct designation and correct orbital elements (for observable epoch!) - to avoid mix with modern data the name should contains an asterix.
* The modern comets probably should be revised per every release

**Comment by gzotti** [comment]
On the historical (1000 comets) file: These data have a known source, so orbital elements at their epoch should be OK. I am not sure, as this was years ago, I may not have recorded the epoch, as our elements did not have this entry at that time. It is usually close enough to perihelion to assume perihelion date as epoch. We have seen earlier that it is not useful to update elements of historical comets with elements for the current epoch! 

Please do not add asterix to the names. Yes, the name should be correct with all possible styles. The file ends around year 2000, so this would just add a a star to all comets before 2000. 

+1 for revising the default list. If interesting comets have been announced, we should consider fetching data for current/upcoming comets. Comets which were dimmer than mag10 or so can probably be removed a year after perihel. "Cleanup" functions could also be added to the SSeditor, if users never look back, all past elements could be removed.

**Comment by alex-w** [comment]
See also #1241

**Comment by alex-w** [comment]
Probably we should add few very bright comets (naked eye visible - a "great comets") and some historically important comets, like comet Halley. Is it ok?

Second part - comets, which expected to be bright in near future (0.5-1 year) - but what is limit of brightness?

**Comment by gzotti** [comment]
You could copy (not move!) entries for Halley 1910 (if still useful?) & 1986, Hyakutake, Hale-Bopp from the 1000comets file. Whatever was important (brighter than mag6?) after 2000 (McNaught 2006, one in 2013, 2021, Holmes ~2017?) may be nice. Comet experts will have their own preferences and add more. Always use epoch close to perihel. 

If we add elements for future comets, we must say somewhere that they are tentative, subject to changes, and any serious magnitude/visibility prognosis many months in advance is next to impossible, so users must seek additional info and update elements when the comet approaches and they go serious about observing. Do you know a website which could be configured for access via OnlineQuery?

**Comment by gzotti** [comment]
Interesting list. However, for most users I think we need not go back so far, and only include real eyecatchers, e.g. mag3 and brighter. The SSO list should not be longer than necessary unless users decide on it. Maybe add another loadable list `brightest_comets_since_1935.ini`.

**Comment by alex-w** [comment]
> Interesting list. However, for most users I think we need not go back so far, and only include real eyecatchers, e.g. mag3 and brighter. The SSO list should not be longer than necessary unless users decide on it. Maybe add another loadable list `brightest_comets_since_1935.ini`.

Probably adding data from lists [THE BRIGHT-COMET CHRONICLES](http://www.icq.eps.harvard.edu/bortle.html) and [Brightest comets seen since 1935](http://www.icq.eps.harvard.edu/brightest.html) into one list `bright_comets.ini` may be good another loadable list.

**Comment by alex-w** [comment]
Other good source to fix designations in our data: [COMET NAMES AND DESIGNATIONS](http://www.icq.eps.harvard.edu/names1.html)
