### ISSUE TITLE
Calendars plugin: Could you add a Yi October solar calendar？

### ISSUE THREAD

**Issue by Joshua19770704** [Stellarium/stellarium#3263]
Could you add a Yi October solar calendar, a set of calendars used for more than 10,000 years, which is very accurate and has had a significant impact on ancient Chinese civilization and astronomical calendars?

**Comment by alex-w** [comment]
@Joshua19770704 do you have description of the calendar or algorithms?

**Comment by gzotti** [comment]
And also scientific references to support the claim of use of a single calendar system over 10.000 years. Where was it used, why is it no longer used if it is so accurate?

**Comment by gzotti** [comment]
If @Joshua19770704 does not provide information about this calendar, we can close this. The topic can be opened again when usable algorithms can be provided.
