### ISSUE TITLE
Infostring "Solar A/a" and "Lunar A/a" missing for many object types

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3273]
I find the infostrings `Solar A/a` and `Lunar A/a` very useful, especially the former. However, many objects do not have them displayed, such as satellites and quasars. I suspect the reason is that these are plugins added long before said infostrings were addad to the main program.

**Comment by gzotti** [comment]
These should be part of StelObject info to show everywhere.

**Comment by alex-w** [comment]
This issue related to #3138 also
