### ISSUE TITLE
renaming a landscape makes it unreachable

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3287]
### Actual Behaviour
Describe or maybe attach a screenshot?

### Steps to reproduce

1. rename a landscape (`name` field) in associated `landscape.ini`
2. without closing, try to load that landscape 

Bugs:

1. landscape name is not updated in the list
2. clicking on the old name does nothing (obviously)

## Solution

1. #2845 
2. https://doc.qt.io/qt-6/qfilesystemwatcher.html ( :warning: watch failure -> logfile  )

## Workaround
Restart

### System
* Stellarium version: <Name of downloaded installable file?>  795febf92bca62822538a5b90b501e656e402cbf

* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by 10110111** [comment]
Solution 3: Add a refresh button

**Comment by gzotti** [comment]
Renaming a landscape without closing the program is such a rare activity that we have no plans for that.
Likewise, renaming/editing a skyculture, renaming/reconfiguring DSO images/names, ...
