### ISSUE TITLE
Not available to download stellarium-23.2-qt5-win64.exe

### ISSUE THREAD

**Issue by Corsair-63** [Stellarium/stellarium#3297]
Stellarium carries me to download page and in versions shown the description of:

stellarium-23.2-qt5-win64.exe

but not available in the list of downloadable files, maybe to early for being completely filled the list or forgotten that version.

**Comment by 10110111** [comment]
@alex-w We get such complaints on each release. Maybe the releases should only be published when all files have been downloaded?

**Comment by gzotti** [comment]
You are too early. It should be available tomorrow.

**Comment by Corsair-63** [comment]
Not making any complaint, just giving some info about, I also shown that release was today, that's why I already wrote ".. to early for ..."

but what you write is a really good point, wait for the release until all version are built and uploaded.

and of course thanks a lot for the answer and the marvellous software.

**Comment by alex-w** [comment]
Done, see the website or releases section
