### ISSUE TITLE
Ugly artefacts in the Leiden Aratea skyculture

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3299]
There are some ugly artefacts in the Leiden Aratea skyculture, probably becaues the backgrounds of the constellation art are not perfectly black. See the screenshot below.

![stellarium-237](https://github.com/Stellarium/stellarium/assets/37028368/fbeeaba3-1662-4a10-a9d9-7ebf40ee6a99)

**Comment by gzotti** [comment]
@sushoff can you please have a look into that? Some "blacks" seem to be 5/5/5.
