### ISSUE TITLE
wrong coordinates

### ISSUE THREAD

**Issue by tajicoji** [Stellarium/stellarium#3309]
### Expected Behavior
correct coordinates

### Actual Behavior
I think the coordinates are off.
This is a Capella, but on J2000 it is   (RA) 05h 16m _**41.35871**,  (DEC) +45° 59' _**52.7693**''. 
But Stellarium shows                         (RA) 05h 16m _**39.89**_,      (DEC) +45° 59' _**38.0**.

### Steps to reproduce
should be displayed

### System
* Stellarium version: stellarium-23.2-a69d242-qt6-win64
* Operating system: Windows 11
* Graphics Card: Inter(R) UHD Graphics

**Comment by alex-w** [comment]
Which is source of your reference coordinates?

**Comment by tajicoji** [comment]
I posted information from Wikipedia, but the database used by APT is the same value as Wiki.
![capella](https://github.com/Stellarium/stellarium/assets/84647917/50df2cb3-0871-4c24-892d-b29965d01a9d)

**Comment by alex-w** [comment]
http://simbad.u-strasbg.fr/simbad/sim-basic?Ident=Capella&submit=SIMBAD+search

**Comment by tajicoji** [comment]
> I'm afraid this issue is related to a bug in proper behavior

what do you mean?
Isn't the coordinate displayed when you select a fixed star etc. the value of the database?

The link destination coordinates are the same as the wiki.
"ICRS coordinates (ep=J2000) : 05 16 41.35871 +45 59 52.7693 (optical) [ 4.75 2.47 90 ] A 2007A&A...474..653V"

**Comment by gzotti** [comment]
J2000 coordinates are catalog values. Coordinates of date include proper motion, precession, nutation, aberration and refraction.

**Comment by tajicoji** [comment]
> J2000 coordinates are catalog values. Date coordinates include proper motion, precession, nutation, aberrations, and refraction.

Hmm. . . That may be true, but I don't think it's desirable for the coordinate values of the targets linked with the shooting software to be different.
It's good to enjoy it alone without connecting to a mount, but I don't think it's good if the coordinates are different for each software.
So if you connect Stellarium to the mount and move from APT to Capella, Stellarium's scope will stop at some distance from Capella. Of course, Stellarium's goto is similar.

**Comment by tajicoji** [comment]
そもそも、ステラリウムには"J2000”と表示した座標を出力しています。J2000のカタログ値以外を表示するのはおかしいのではないですか？

**Comment by tajicoji** [comment]
In the first place, the coordinates displayed as "J2000" are output to Stellarium. Isn't it strange to display values other than the J2000 catalog value?

**Comment by tajicoji** [comment]
Since J2000 is a catalog, coordinates marked as J2000 must display catalog values.
Values that change with the date and time are displayed as "on date".

**Comment by gzotti** [comment]
No, it is not strange that we have the options to show both J2000 AND coordinates of date. This is on purpose because J2000 coordinates are the wrong ones if you operate a correctly aligned mechanical telescope in 2023. 

Does your mount work in J2000 coordinates or in coordinates of date?
Are the respective settings for the telescope in APT and the telescope control plugin correct?

**Comment by gzotti** [comment]
Summary: Our J2000 coordinates include aberration correction for technical reasons. Other sources give mean position. This may cause a positional mismatch of up to 20.4". If in doubt, switch off aberration correction.

**Comment by tajicoji** [comment]
Thank you！
Unchecking the tool's geocentric coordinates and nutation gave the values from the J2000 catalog.

**Comment by tajicoji** [comment]
I checked a new snapshot and it did not resolve this issue.
"stellarium-23.2-f5706e5-qt5-win64" works fine, but remote control from APT fails.
APT error message
2023/07/15 20:46:56 (UT 2023/07/15 11:46:56) Problem connecting to OpErr Stellarium (5)
2023/07/15 20:46:56 (UT 2023/07/15 11:46:56) OpErr Character set is iso-8859-1, utf-8, utf-16, utf-16le, or utf-16be There must be extracted.

"stellarium-23.2-f5706e5-qt6-win64" crashed. However, remote control from APT succeeds.
