### ISSUE TITLE
A few notes

### ISSUE THREAD

**Issue by Orio1961** [Stellarium/stellarium#3310]
I would like to draw your attention to several issues...
1. I would like to increase the number of catalogs from 9 to 12-15, especially GAIA 2.3 catalogs, as well as such catalogs as TIC, NOMAD, USNO-B1.0, UCAC and other large and important catalogs.
2. And one more important note, when viewing data about a star, I do not see the name of the object itself, but only its characteristics.
3. It would be very nice to make it so that when viewing data about an object, you could also go to 
Centre de Données astronomiques de Strasbourg. Strasbourg astronomical Data Center.
With great respect and reverence for you and your work. Thank you.

**Comment by gzotti** [comment]
re 1: Sure, me too. Please do it. 
re 2: catalog number are not stored for the smaller stars for reasons of efficiency.
re 3: F3/SIMBAD, "Query SIMBAD about selected object". User Guide 4.5.2.

**Comment by Orio1961** [comment]
> re 1: Sure, me too. Please do it. re 2: catalog number are not stored for the smaller stars for reasons of efficiency. re 3: F3/SIMBAD, "Query SIMBAD about selected object". User Guide 4.5.2.

Thanks for the answer, but I would like the information to be displayed for weak objects only when you click on them, i.e. there was a name and all the characteristics (only when you select an object) and one more nuance, how to copy the text about the selected object?

**Comment by alex-w** [comment]
`Ctrl+C`

**Comment by Orio1961** [comment]
> `Ctrl+C`

Thank you very much...
