### ISSUE TITLE
I would like to draw your attention to several issues...

### ISSUE THREAD

**Issue by Orio1961** [Stellarium/stellarium#3311]
- [ ] 1. I would like to increase the number of catalogs from 9 to 12-15, especially GAIA 2.3 catalogs, 
as well as such catalogs as TIC, NOMAD, USNO-B1.0, UCAC and other large and important catalogs.
- [ ] 2. And one more important note, when viewing data about a star, I do not see the name of the 
object itself, but only its characteristics.
- [ ] 3. It would be very nice to make it so that when viewing data about an object, you could also go to 
Centre de Données astronomiques de Strasbourg. Strasbourg astronomical Data Center.
With great respect and reverence for you and your work. Thank you.

**Comment by alex-w** [comment]
3. - Please check second tab in Search tool

**Comment by gzotti** [comment]
See my answers in the earlier #3310

**Comment by gzotti** [comment]
I see no need to keep this open. Whoever creates the next star catalog will surely again use currently available catalogs without this reminder. The other questions have been answered.
