### ISSUE TITLE
Telescopic asterisms are broken

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#3315]
### Expected Behaviour
Render telescopic asterisms

### Actual Behaviour
Telescopic asterisms cannot be created due problem for finding reference stars

### System
* Stellarium version: 23.2
* Operating system: macOS 13.4.1

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/11969593/log.txt)

**Comment by alex-w** [comment]
I can't reproduce the issue on Windows :-/

**Comment by Atque** [comment]
I can, but only sometimes. Having run Stellarium for a while, changing sky cultures etc., the problem shows.

Here's how I can reproduce on Windows 64-bit (Qt6):
1. Start with Modern sky culture
2. Show asterisms
3. Change sky culture to a few others
4. Return to Modern. Now the telescopic asterisms won't show.

This is an old problem, 2 or 3 years at least. I have meant to report it, but I have found no consistent way of reproducing it until now.

**Comment by gzotti** [comment]
I agree it's old and intermittent. There were occasional lines in the logfile about "cannot load TA6" or such, but not always.

**Comment by alex-w** [comment]
I see the effect with arm64 binaries only :(

**Comment by alex-w** [comment]
@Atque I guess your Windows machine is a HiDPI-device - is it correct?

**Comment by Atque** [comment]
> @Atque I guess your Windows machine is a HiDPI-device - is it correct?

2560x1440 @ 25", don't know if that qualifies as HiDPI?

**Comment by hmartinez82** [comment]
@Atque In Windows:
- Right click in the desktop anywhere in the wall paper
- Select Display Settings
- Scroll down to Scale & Input
If Scale is any number above 100% then you hare doing some form of High DPI. For instance,  I have it as 200% in my main desktop and in my personal Windows on ARM laptop.

**Comment by Atque** [comment]
@hmartinez82 Okay, it says "125% (recommended)", so yeah, then I have an HiDPI monitor.

**Comment by 10110111** [comment]
I reproduce the problem as described in #3552, and here's what I found with the following test:
```diff
diff --git a/src/core/modules/Asterism.cpp b/src/core/modules/Asterism.cpp
index 52c480d0f2..3c9eafb0cf 100644
--- a/src/core/modules/Asterism.cpp
+++ b/src/core/modules/Asterism.cpp
@@ -114,6 +114,15 @@ bool Asterism::read(const QString& record, StarMgr *starMgr)
                     qWarning() << "Error in asterism" << abbreviation << "- can't find star with coordinates" << RA << "/" << DE;
                     return false;
                 }
+                if (RA == 3.6803 && DE == 89.1048)
+                { // XXX: debug
+                    const auto pos = s->getJ2000EquatorialPos(core);
+                    StelUtils::rectToSphe(&RA, &DE, pos);
+                    RA *= 12/M_PI;
+                    DE *= 180/M_PI;
+                    qDebug() << "Found a problematic star, actual RA:" << RA << ", DE:" << DE << ", vmag:" << s->getVMagnitude(core);
+                    qDebug().noquote() << "Info: -----------------------------------\n" << s->getInfoString(core);
+                }
                 break;
             }
         }
```
In my case I consistently get some stars missing, one of them is at `RA == 3.6803 && DE == 89.1048` as the patch above tries to catch. I've caught it, and here's the relevant output (reformatted for readability):
```html
Found a problematic star, actual RA: 3.67637 , DE: 89.1101 , vmag: 8.05
Info: -----------------------------------
<font color=#fefeff>
<h2>HIP 17195 - HD 14369 - SAO 460</h2>
Type: <b>star</b><br />
Magnitude: <b>8.05</b><br/>
Absolute Magnitude: 3.22<br />
Color Index (B-V): <b>0.41</b><br />
RA/Dec (J2000.0):     3h40m34.94s/+89°06'36.3"<br/>
RA/Dec (on date):    21h08m23.29s/+54°44'26.1"<br/>
HA/Dec:     6h12m15.14s/+54°44'26.1"  <br/>
Az./Alt.: +322°37'02.9"/-18°17'31.5"  <br/>
Gal. long./lat.: +123°36'02.8"/+26°28'05.9"<br/>
Supergal. long./lat.: +25°45'31.6"/+15°07'10.0"<br/>
Ecl. long./lat. (J2000.0): +88°45'29.0"/+65°49'31.5"<br/>
Ecl. long./lat. (on date): +355°09'52.9"/+64°53'20.7"<br/>
Ecliptic obliquity (on date): +23°26'18.0"<br/>
Mean Sidereal Time: 3h20m38.8s<br/>
Apparent Sidereal Time: 3h20m38.4s<br/>
Rise: 11h59m<br/>
Transit: 15h51m<br/>
Set: 19h44m<br/>
IAU Constellation: UMi<br/>
Distance: 301.44±0.81 ly<br />
Proper motion: 59.92 mas/yr towards 239.2°<br />
Proper motions by axes: -51.45 -30.71 (mas/yr)<br />
Parallax: 10.820±0.029 mas<br />
Spectral Type: F0<br />
Solar Az./Alt.: +196°46'45"/-46°44'13"<br/>
Lunar Az./Alt.: +59°54'12"/+6°02'40"
</font>
```
This same star, found via <kbd>F3</kbd> as `HIP17195`, has the same vmag (which confirms it's the correct star), but a very different position and even J2000 RA/dec:

![stellarium-011](https://github.com/Stellarium/stellarium/assets/6376882/688a363d-a20c-41ff-b466-2b2b50f27e34)

Why could it have moved?

**Comment by alex-w** [comment]
Aberration?

**Comment by alex-w** [comment]
Stop! Decimal degrees and decimal hours are different of course

**Comment by gzotti** [comment]
I did not study this code. Aberration causes upto 20 arcsec of positional change. Is the search radius large enough?

**Comment by 10110111** [comment]
> Aberration?

Indeed, disabling aberration avoids the errors.

**Comment by 10110111** [comment]
Interestingly, the docs for `StarMgr::searchAround` (in the `.cpp` file only) say that it ignores aberration:
```cpp
// Return a QList containing the stars located
// inside the limFov circle around position vv (in J2000 frame without aberration)
QList<StelObjectP > StarMgr::searchAround(const Vec3d& vv, double limFov, const StelCore* core) const
```
But what I observe is that aberration does affect the position being checked.
