### ISSUE TITLE
problems with data update

### ISSUE THREAD

**Issue by nicopop75** [Stellarium/stellarium#3321]
Hello, I would like to report that with the new version 23.2 I can no longer download the updated data of comets, meteor showers, pulsars and quasars.
The download only works with satellites and Van Buitenen comets, but not with MPC files.
Once the update has been launched, I allow up to half an hour to pass, but the progress bar remains stationary at zero.

Also in the surveys function I can download the deep sky data but not the solar system data.

I am using a Windows 8.1 PC with an Intel 3.6 gh processor.
I enclose the config.ini and last run log files

Has the update procedure changed ? Has anyone else experienced these problems ? Or are there problems on the sites ?

Thank you for your attention.

[log.txt](https://github.com/Stellarium/stellarium/files/11995065/log.txt)
![comet update from MPC 2](https://github.com/Stellarium/stellarium/assets/79394885/d5473577-5d35-4702-a418-e208f99cfd86)
![comet update from MPC](https://github.com/Stellarium/stellarium/assets/79394885/ab5235a2-5f3a-4117-938d-99c24813de89)
![Deep sky surveys](https://github.com/Stellarium/stellarium/assets/79394885/6fdd43d4-fa78-4f7a-a8f0-eb4092e2ffbe)
![exoplantes update](https://github.com/Stellarium/stellarium/assets/79394885/39617f18-7721-47fe-b2f1-5a738cc56e57)
![meteor showers update](https://github.com/Stellarium/stellarium/assets/79394885/54aba719-3a71-49a5-834c-75e9b814de92)
![Quasars update](https://github.com/Stellarium/stellarium/assets/79394885/79c42009-f60b-4bd1-9e5d-8ce8e9b615e8)
![Solar system surveys](https://github.com/Stellarium/stellarium/assets/79394885/c9121fa0-34df-490f-8ea2-37308ae4fa77)

**Comment by alex-w** [comment]
Please show listing files from C:\Program Files\Stellarium\

**Comment by nicopop75** [comment]
here attached you will find the list of files contained in the c/programs/stellarium folder and also the c/programs/stellarium/data folder



![PROGRAM STELLARIUM FILES 1](https://github.com/Stellarium/stellarium/assets/79394885/30a3f065-3f59-40b9-a12e-8964b7d13a22)
![PROGRAM STELLARIUM FILES 2](https://github.com/Stellarium/stellarium/assets/79394885/d817bcbf-6e2a-4cde-94a5-7df67dd40cff)
![PROGRAM STELLARIUM FILES 3](https://github.com/Stellarium/stellarium/assets/79394885/de1c9b01-86a2-4cdb-8c40-3a65a1452768)
![PROGRAMS STELLARIUM DATA FILES](https://github.com/Stellarium/stellarium/assets/79394885/57eda55e-0c65-4b59-b582-12fb61b3b964)

**Comment by 10110111** [comment]
The log contains the following suspicious lines:

```
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
[Exoplanets] Download error: While trying to access "https://www.stellarium.org/json/exoplanets.json" the following error occurred: "TLS initialization failed"
[Exoplanets] Already updating...  will not start again until current update is complete.
[Exoplanets] Already updating...  will not start again until current update is complete.
[Exoplanets] Already updating...  will not start again until current update is complete.
```

Not sure why TLS initialization could fail.

**Comment by 10110111** [comment]
Also, the log has a strange chain of 177 zero characters in this part:
```
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.
<177 times '\0'>[Exoplanets] Already updating...  will not start again until current update is complete.
```
This may hint at memory corruption.

**Comment by alex-w** [comment]
> Not sure why TLS initialization could fail.

OpenSSL 3 can be too new for Windows 8.

**Comment by alex-w** [comment]
> On my Ubuntu 20.04 machine Exoplanets update successfully, but Satellites emit another error

celestrak.org is outdated now… please reset the default list of TLE sources

**Comment by alex-w** [comment]
Please replace `libssl-3-x64.dll` and `libcrypto-3-x64.dll` files by files from attached archive and try update the data again

[OpenSSL.zip](https://github.com/Stellarium/stellarium/files/11997919/OpenSSL.zip)

**Comment by nicopop75** [comment]
Great! It's working now.
Thank you very much
What was the problem?

**Comment by gzotti** [comment]
Running an obsolete OS like Windows 8.* is a problem...
