### ISSUE TITLE
HIPS Survey Deep Sky List in Qt5 version

### ISSUE THREAD

**Issue by Hide4576** [Stellarium/stellarium#3326]
I'm using the Qt5-based version because I use TelescopeControl, but the Qt5-based V23.2 seems to have the following problem:

"DSS Colored", "DSS Blue", "DSS NIR", and "DSS Red" are not displayed in the HIPS Surveys - Deep Sky list.

No problem with Qt6 based V23.2.

**Comment by gzotti** [comment]
This is rather weird. The code is the same. However, availability of the HiPS is mostly out of our hands. Maybe just wait a minute longer to let them load?

**Comment by Hide4576** [comment]
In my environment, no matter how many minutes or hours I wait, the situation does not change.
Is it happening only in my environment?
I would appreciate it if you could check it in your environment.

My environment is

Windows 11 Pro 64bit
stellarium-23.2-qt5-win64.exe

**Comment by Hide4576** [comment]
I attach a screenshot

![screenshot 2023-07-14 221238](https://github.com/Stellarium/stellarium/assets/139552154/c58bad6f-5860-4e3f-98d9-0425ff5a283f)

**Comment by gzotti** [comment]
OK, confirmed. However I cannot explain this atm. If it's only about wanting to see DSS, you can use the older DSS Toast survey.

**Comment by alex-w** [comment]
Please check this hook: https://github.com/Stellarium/stellarium/issues/3321#issuecomment-1628186500

**Comment by Hide4576** [comment]
After replacing the two files in #3321 and running V23.2 again, the problem was resolved.
I was able to download DSS Colored etc. successfully.

Thank you.

**Comment by Hide4576** [comment]
I have confirmed.
The problem has been fixed in "stellarium-23.2-f5706e5-qt5-win64.exe".
Thank you for your quick response.
