### ISSUE TITLE
Several functions can only be executed by keyboard shortcuts

### ISSUE THREAD

**Issue by freebrowser1** [Stellarium/stellarium#3332]
**Is your feature request related to a problem? Please describe.**
The F1 function shows all keyboard shortcuts, so the user should memorize all these shortcuts or at least look up the function in the table and press the key combination. Even clicking on a shortcut does not perform the action. It appears an old MSDOS or WordPerfect user interface.

**Describe the solution you'd like**
* At least that clicking on a shortcut displayed results in performing that action.
* Yet better is a menu where the user can easily select an option.

**Additional context**
<img width="490" alt="Screenshot 2023-07-20 at 21 14 15" src="https://github.com/Stellarium/stellarium/assets/26625141/c5ef6cae-dadf-47f4-8dff-3fe66c8b2668">

**Comment by 10110111** [comment]
You've shown a screenshot where most of the actions are either mouse-cursor-dependent, so that your request is inapplicable to them, or already available from the GUI (e.g. time scrolling is doable via the Time dialog).

It'd be better if you listed the exact items that you need and suggested a GUI representation for them. On my side, I only miss a checkbox for showing/hiding DSO images (the shortcut is <kbd>i</kbd>), similarly to how it exists for e.g. the Milky Way.

**Comment by gzotti** [comment]
Yes, it takes a few minutes to learn the most important buttons in a piece of software that has evolved over many years. It may also help to read the intro chapter of the User Guide which we have written for you. 

@10110111 you can enable the bottom bar button for that in the F2 Configuration/Extras/Nebula Background.

**Comment by freebrowser1** [comment]
> Yes, it takes a few minutes to learn the most important buttons in a piece of software that has evolved over many years. It may also help to read the intro chapter of the User Guide which we have written for you.
> 
> @10110111 you can enable the bottom bar button for that in the F2 Configuration/Extras/Nebula Background.
Well, some functions as 'step hour' or 'step minute' are only accessible by keyboard shortcuts which one has to learn.
So it would be very useful to allow showing buttons for such functions in the bottom bar as well.

**Comment by gzotti** [comment]
Open the time window and press the arrows above or below the displayed hour or minute, respectively. Or scroll your mouse wheel.

**Comment by freebrowser1** [comment]
> Open the time window and press the arrows above or below the displayed hour or minute, respectively. Or scroll your mouse wheel.
That works indeed, but other shortcuts, e.g. one saros earlier / later and many others cannot be handled by this and cannot be added as buttons as well.

**Comment by gzotti** [comment]
If you are interested in these more advanced time functions, enjoy the flexibility to configure and memorize your own hotkeys. Many users don't need them, some need a small subset, therefore there are no defaults, and no wasted screen real estate for all of 91 buttons that would trigger actions related to time.

**Comment by freebrowser1** [comment]
> If you are interested in these more advanced time functions, enjoy the flexibility to configure and memorize your own hotkeys. Many users don't need them, some need a small subset, therefore there are no defaults, and no wasted screen real estate for all of 91 buttons that would trigger actions related to time.

Even in the rare case anyone uses all 91 buttons, the screen real estate is not wasted because it auto hides.
Moreover, I tried some keyboard shortcuts which don't work at all, e.g. (linux) F11 shows a popup with text of another app and F9 hides the Stellatium app, so keyboard shortcuts are not useful for so many controls. 
Hence many apps don't use this MSDOS era of keyboard shortcuts and use a menu bar what every modern OS /app  has (and even Stellarium has, but not for all options.

**Comment by 10110111** [comment]
> (linux) F11 shows a popup with text of another app and F9 hides the Stellatium app

The fact that your DE is poorly configured doesn't make it a fault of Stellarium.

> Hence many apps don't use this MSDOS era of keyboard shortcuts

Lacking keyboard shortcuts is not an advantage.

Anyway, if you make a PR that would implement addition of some buttons, this would be reviewed and possibly merged. Just make sure not to clutter the default layout, and to make it possible to only add a selected set of buttons, rather than them all.

**Comment by freebrowser1** [comment]
> 
> The fact that your DE is poorly configured doesn't make it a fault of Stellarium.
>
DE ? What is DE ? 
> Lacking keyboard shortcuts is not an advantage.
>
I am not advocating disabling keyboard shortcuts, but advocating making it more user friendly.

> Anyway, if you make a PR that would implement addition of some buttons, this would be reviewed and possibly merged. Just make sure not to clutter the default layout, and to make it possible to only add a selected set of buttons, rather than them all.

In this case, limit the number of buttons to prevent cluttering, but let the user determine which buttons are shown.

Well, the simplest option is to make all options in the F1 screen clickable, that means when the user clicks on the keyboard shortcut in the F1 screen (when it is not a mouse action), the option is executed. That makes it much more user friendly without the need to memorize complex keyboard shortcuts.
