### ISSUE TITLE
Black on dark gray in user interface is barely readable

### ISSUE THREAD

**Issue by freebrowser1** [Stellarium/stellarium#3333]
Using the 'settings' and other menus (F1 help) show black text on dark gray background. This is barely readable.

### Expected Behaviour
More contrast between fore- and background (e.g. white on dark gray or black on light gray) or even user customizable colors.
<img width="490" alt="Screenshot 2023-07-20 at 21 14 15a" src="https://github.com/Stellarium/stellarium/assets/26625141/a11503c5-b53a-42e3-8341-eed98661858d">

### Actual Behaviour
<img width="490" alt="Screenshot 2023-07-20 at 21 14 15" src="https://github.com/Stellarium/stellarium/assets/26625141/7d8d4a44-7253-467c-a651-b361723c7894">

### Steps to reproduce
Use any of the left menus (Sky viewing options, Settings, Help. Astronomical Calculations).

### System
* Stellarium version: 0.23.2, but all versions back to 0.16 or even earlier.
* Operating system: macOS, Linux, Windows
* Graphics Card: depends on computer used
* Screen type: Macbook Pro M1 builtin 14" display (1440x900), but any other rather similar.

### Logfile 
N/A

**Comment by gzotti** [comment]
User Guide, 6.2.3, is for you. Please study the User Guide before raising issues.

**Comment by freebrowser1** [comment]
Exactly, but the documentation does not tell where `normalHtml.css` is located and how it should be edited. And not everyone is familiar with CSS.
But the default style should be at least more readable.

**Comment by gzotti** [comment]
The Guide reads:
>You can find the CSS files in Stellarium’s Github site[footnote 9].
And footnote 9 has: 
>https://github.com/Stellarium/stellarium/blob/stellarium-stable/data/gui/normalStyle.css and https://github.com/Stellarium/stellarium/blob/stellarium-stable/data/gui/normalHtml.css

The list of system recommendations (https://stellarium.org) includes:
>Moderately dark environment (deep shadow or indoors)

While most users are happy with this appearance which has been configured more than a decade ago, there will always be somebody who dislikes something. We understand that and provide these hooks for personal adjustments by power users like you. But the three of us will likely not develop an interactive style editor. Contributions welcome.

**Comment by freebrowser1** [comment]
You are right, but the documentation does not tell which CSS rule affects the background and text color in the dialogs in normalStyle.css. The other normalHtml.css has only a few lines and does not determine colors (color and background-color).
Which CSS styles should I change ?

**Comment by gzotti** [comment]
In low screen brightness, low contrast is usually less of an issue. Else we would have changed the defaults years ago. 

The original designer of this style has left the project. The file is not documented, and there is no style description/documentation I am aware of. Feel free to experiment, document for non-CSS experts, and contribute your results.
