### ISSUE TITLE
Vec3f script error

### ISSUE THREAD

**Issue by kajaji** [Stellarium/stellarium#3337]
Setting colors in scripts does not work. My scripts are old and didn't have issues as I remember, but running them under version 1.1 produces an error. The current scripting documentation matches my code.
### Expected Behaviour
Set color as documented in http://stellarium.org/doc/head/scripting.html

### Actual Behaviour
A script error:
script error: 'Reference'  @ line 1: ReferenceError: Vec3f is not defined

### Steps to reproduce
Use any set color like:
ConstellationMgr.setLinesColor(Vec3f(1.0,0.0,0.0));
### System
* Stellarium version: 1.1
* Operating system: Windows 11

**Comment by 10110111** [comment]
Does it still happen with the latest version of Stellarium?

**Comment by kajaji** [comment]
Yes. Tested on V 23.2

**Comment by gzotti** [comment]
Please read the section 17.5.2 about Vec3f in the User Guide.

**Comment by kajaji** [comment]
Thanks.
It's working using the sample code in the guide.
