### ISSUE TITLE
Stellarium is lagging

### ISSUE THREAD

**Issue by krzysztof832** [Stellarium/stellarium#3339]
hello all,
I am new here and not sure if it is the right place to ask for help
I just installed the newest version of Stellarium 23.2 and it is lagging. 
it is frozen for long time. processor utilization shows from 20 to 50 %.I also installed it at another laptop and it works very well. so it looks like this is problem of my laptop.
could you please advice how to check it? maybe some additional soft / drivers are missing?
My laptop is quite strong. Intel I7 .
Working on Windows 10.
thank you and regards

**Comment by 10110111** [comment]
You need to make sure that you have the correct OpenGL drivers for your GPU. I don't know whether Intel GPUs have OpenGL drivers in Windows by default, so you should double check. Stellarium log could help.

**Comment by ilkant** [comment]
krzysztof832, please attach log.txt to your message. Or tell how much your laptop has memory, exact processor model, etc.

**Comment by krzysztof832** [comment]
Hello Ilpo,
I can describe my problem more precisely already. so Stellarium is
installed on the laptop connected to my rig.I am controlling it via
TeamViewer. Stellarium itself works well on the laptop. no problems, the
lag occurs on my MAC which steers my rig. If I am connected from another
Windows machine all works fine. only MAC has delay and freezes the screen.
I reported it to TeamViewer desk help but got no real advice or solution.
is this known problem ? I will send log.txt but can you tell me how to find
it?
I am using Mac mini M1 , OS Ventura, RAM 16GB, hard disc still more than
100GB memory
very best regards,Krzysztof

wt., 25 lip 2023 o 02:00 Ilpo Kantonen ***@***.***>
napisał(a):

**Comment by gzotti** [comment]
So, please tell us, is this a "Stellarium" problem? Or rather a "TeamViewer on Mac" problem?

**Comment by krzysztof832** [comment]
to be honest I do not know. If Stellarium is not working, connection is
good. as soon as Stellrium is working it starts to lag.
I do not know how to detect where there is a problem. If I am
connecting via Windows machines all works fine.
It can be Stellarium on Mac or Teamviewer on Mac. i am a bit lost here

wt., 25 lip 2023 o 13:03 Georg Zotti ***@***.***> napisał(a):

**Comment by krzysztof832** [comment]
it's rather Stellarium on Mac. because in other cases connection is ok,
when Stellarium is off.

wt., 25 lip 2023 o 13:13 Krzysztof ***@***.***> napisał(a):

**Comment by ilkant** [comment]
You can find log.txt with Stellarium User Guide page 61 and chapter 5.3. The Logfile. Previous chapter 5.2 describes directory structure too. But I think that your situation is not issue of Stellarium.

file:///home/ilpo/Lataukset/stellarium_user_guide-23.1-1.pdf

**Comment by gzotti** [comment]
Prehistoric.  The current version of the User Guide can be found on your own harddisk...

**Comment by gzotti** [comment]
We probably cannot do anything at this point. If we don't receive more info, we will close this at end of September.
