### ISSUE TITLE
Discrepancy in the definition of "Prism/CCD distance"

### ISSUE THREAD

**Issue by SusanSSB** [Stellarium/stellarium#3346]
I am looking for a clarification of the definition of "Prism/CCD distance". I am using Stellarium Version 1.1. On page 216 of the Stellarium 1.1 User Manual, it states, "Prism/CCD distance – distance between **center** of prism/CCD of Off-Axis Guider and optical
axis of telescope in mm.". However in the Oculars window, under the Sensors tab, when you roll your cursor over "Prism/CCD distance", the pop-up description of the "Prism/CCD distance" states this to be "the distance from the center of the Imaging Sensor to the **bottom** of the Prism". This is a discrepancy. Which is correct? Please advise.

This should be corrected so the definition in the User Manual is the same as in the pop-up description of the "Prism/CCD distance" under the Sensors tab of the Oculars window. Thanks in advance.

**Comment by gzotti** [comment]
We have discussed that last week...

https://groups.google.com/g/stellarium/c/1n3ZL8aw1AA

**Comment by 10110111** [comment]
When I changed the code, I used the User Guide as the spec (and wasn't even aware of the tooltip that appears to contradict the Guide). So the Guide reflects the actual behavior.

**Comment by SusanSSB** [comment]
So, what does this mean, "So the Guide reflects the actual behavior"?... What should the "Prism/CCD distance" be? Please clarify.

**Comment by 10110111** [comment]
This means that what the Guide says is true:

> Prism/CCD distance – distance between center of prism/CCD of Off-Axis Guider and optical axis of telescope in mm.

**Comment by SusanSSB** [comment]
Okay, thank you very much for the clarification… I am still puzzled, though. When I enter the same combination of telescope, imaging camera, OAG and guide camera specs in both SkySafari Pro and Stellarium, the resulting view in Stellarium, of the relative positions of the imaging camera and guide camera, looks very different from the view in Sky Safari Pro. Sky Safari Pro uses a “Sensor Offset” which is defined exactly the same as the “Prism/CCD distance” in Stellarium, i.e., the distance between the center of prism/CCD of the Off-Axis Guider and optical axis of telescope in mm. I am puzzled by the fact that I get different results in Stellarium that I do in Sky Safari Pro… 

 

Kind regards,

 

Susan

**Comment by 10110111** [comment]
Well, without screenshots and numerical information I don't know what difference you see or anything. Can only guess that the other app includes lens distortions that Stellarium doesn't simulate.
