### ISSUE TITLE
ShowMySky library no longer found

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#3352]
I had though this was solved by cmake/CPM magic: SMS not found on Windows. I had my SMS library from January. Is there a new version? Please add instructions to BUILDING.md.

### Expected Behaviour

ShowMySky found

### Actual Behaviour

ShowMySky not found

Describe or maybe attach a screenshot?

### Steps to reproduce

Build master on Windows and run from within QtCreator

### System
* Stellarium version: master (seen on 2023-08-04)
* Operating system: Windows 11
* Graphics Card: irrelevant

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

```
Creating scene FBO with size 3440x1440
Initializing planets GL shaders... 
Loaded 52 / 52 references
Atmosphere runs with statically reduced resolution: 4
ERROR: Failed to initialize ShowMySky atmosphere model: Failed to load ShowMySky library: Cannot load library ShowMySky-Qt6: Das angegebene Modul wurde nicht gefunden.
WARNING: Falling back to the Preetham's model
```

**Comment by 10110111** [comment]
Last update to this was in 4466cfefdc0b2c71514e0a4b5b903f89112ccc9d, so the latest release should be fetched by CPM. I think CI build would fail if it didn't work, no?

Also, when was the last time(revision) you had it work as expected?

**Comment by gzotti** [comment]
The CI runs on Linux only, right? And would usually do make install before testing? (And does it do runtime test?) 
I don't remember when I last used it in master, June, July? I often concentrate on other things. SMS is a great showoff, though. 
Now, what does CPM do on Windows? Where does the SMS library go? The exe in `<build>/src/stellarium.exe` does not find it.

**Comment by 10110111** [comment]
AppVeyor runs Windows builds too. The loading is simply `QLibrary::load()`. If the library is not near the EXE, its path must be present in `PATH` environment variable. You can configure it locally in your QtCreator project configuration (the section where you can pass things to CMake).

**Comment by gzotti** [comment]
OK. I finally found the library and added this info to BUILDING.md.
