### ISSUE TITLE
NomenclatureItems: Goto crashes

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#3355]
It seems that moving to a selected feature leads to a crash in 23.2. It worked in 1.1. 

### Expected Behaviour

Select some crater. Ctrl-G should move us there

### Actual Behaviour

Ctrl-G causes a crash

### Steps to reproduce

Select a crater. Press Ctrl-G

### System
* Stellarium version: 23.2 and master (2023-08-06)
* Operating system: Windows 11
* Graphics Card: irrelevant

### Logfile 
Nothing useful.

**Comment by alex-w** [comment]
Please check v23.1 - I fear this issue related to latest changes in locations

**Comment by gzotti** [comment]
Yes, I have the same thoughts
