### ISSUE TITLE
No cross-marking for antipoints (antapex, SCP, SEP etc)

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3356]
We seem to have lost the cross-marking for the antapex point. It is present for the apex point, see the screenshot below:

![stellarium-246](https://github.com/Stellarium/stellarium/assets/37028368/b45de473-97a0-4fac-a657-37e345197da3)

Windows 10, 64-bit
Latest master (https://github.com/Stellarium/stellarium/commit/5d3ef9799c015313717cc03b8825604c2bfa23f0) built with Qt 6.4.2

Edit: Okay, it's the same for all anti-points (SCP, SEP, SGP etc).

**Comment by 10110111** [comment]
I mentioned this in #3343, but that PR shouldn't be related to the breakage.

**Comment by gzotti** [comment]
It is, though :-(

**Comment by 10110111** [comment]
What do you mean? Reversion of that commit removes the problem?

**Comment by gzotti** [comment]
I checked out the commit before that, and it has the south pole crosses. 
Maybe it's something with bf culling (some reversed normal), but I did not check the code closely.
