### ISSUE TITLE
make window size adjustable

### ISSUE THREAD

**Issue by hsdk123** [Stellarium/stellarium#3361]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

- make the window size adjustable by touching the outside of the window
- also allow to ex. save the size and have stellarium open to that size on next startup

**Describe alternatives you've considered**

- stellarium currently only has fullscreen vs window mode

**Additional context**

**Comment by gzotti** [comment]
The window size is of course configurable like most windows. Drag the window to the size of your liking, then press "Store settings" in the config dialog to store settings.

**Comment by hsdk123** [comment]
> The window size is of course configurable like most windows. Drag the window to the size of your liking, then press "Store settings" in the config dialog to store settings.

Thank you, where is 'Store settings'?

**Comment by 10110111** [comment]
In the _Configuration_ dialog that you can open by <kbd>F2</kbd> or from the left-side panel.

**Comment by gzotti** [comment]
> > The window size is of course configurable like most windows. Drag the window to the size of your liking, then press "Store settings" in the config dialog to store settings.
> 
> Thank you, where is 'Store settings'?

I deeply apologize. The button is labeled "Save settings" in English.

**Comment by hsdk123** [comment]
Thank you very much, works!
