### ISSUE TITLE
Telescope configuration won't connect telescope through virtual port

### ISSUE THREAD

**Issue by jacko116** [Stellarium/stellarium#3367]
Hello,

I have updated to 23.2 and tried to connect Stellarium through a virtual serial com port created by Nexremote. Unfortunately, this version of Stellarium does not connect to the virtual serial com port. Troubleshooted thinking there was a problem with Nexremote, but after of a few hours of troubleshooting decided to rollback to Stellarium version 0.22.2 and the connection worked perfectly. There is something in the 23.2 version that doesn't Stellarium connect to the Virtual Port. I have not tried earlier releases before 23.2 so I can't tell you in which release the problem starts to occur (somewhere between 0.22.2 - 23.2)

Regards,

Giacomo

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Hello @jacko116 

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by gzotti** [comment]
Published in http://stellarium.org/release/2023/07/02/stellarium-23.2.html

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
