### ISSUE TITLE
Add a minimum/maximum elevation mask

### ISSUE THREAD

**Issue by vpicouet** [Stellarium/stellarium#3372]
Hello,
it would be interesting to be able to put a mask (maybe slightly transparent) to show what is the accessible sky of one telescope.
For instance, working on a balloon experiment we can only access 40-60 elevation (see picture)
![Capture d’écran, le 2023-08-16 à 15 18 38](https://github.com/Stellarium/stellarium/assets/37241971/353257a1-cdec-42c8-926a-1b9d6103f196)

I tried to modify the landscapes/zero_horizon file to put the 40deg limit, which worked, but I did not manage to add the higher limit.
![Capture d’écran, le 2023-08-16 à 15 20 33](https://github.com/Stellarium/stellarium/assets/37241971/eb2879ad-8be2-463a-86b4-f88256f74aff)

I tried to it the same way as in Iobserve software:

```
#    Trivial    zero-line    horizon    for    Stellarium
#    avoid    spurious    vertical    lines/triangles    by    small    offset    from    north/south!
#    The    cardinal    directions    are    marked    by    low    spikes    for    technical    reasons.        
#    Note    that    we    should    start    the    horizon    line    at    90    degrees    -    this    indicates    a    polygon    bug!

90 40
91 40
...
357 40
358 40
360 40
0 40
1 40
...
89 40
89 60
88 60
87 60
86 60
...
0 60
359 60
...
94 60
93 60
92 60
91 60
```

But this did not apply an upper limit.
Am I doing it right or should I use some modified version of the ocular view or even some other settings?
Or is there an easier way to do it?
Also, is there a possibility to have this mask/landscape slightly transparent in order to be able to know when target will get observable.

Thanks a lot for the help!

**Comment by gzotti** [comment]
The polygonal landscape is simple and allows only one cover: the ground. There are no extra windows possible. If you can live with it, it may be possible to connect the regions with a thin stem. Or, use a spherical landscape. 

To switch on transparency, activate the transparency checkbox (available since 23.2+).

**Comment by vpicouet** [comment]
Thanks for the info!
I am on 23.2 but can not see the transparency checkbox
![Capture d’écran, le 2023-08-16 à 16 20 28](https://github.com/Stellarium/stellarium/assets/37241971/5bff4852-f455-4235-88fc-7eecaa6769d3)

**Comment by gzotti** [comment]
Oops, my fault. The option was added in the night after release. Try a beta.

**Comment by gzotti** [comment]
Solutions exist. We can close this.
