### ISSUE TITLE
Telescope Control broken

### ISSUE THREAD

**Issue by mene99** [Stellarium/stellarium#3380]
The plug in stopped working for Celestron Telescopes in the latest version.

I tried the 23.1 and it was able to connect via COM.

the new version 23.2 does not. Click on START after adding a telescope but nothing happen.

Please fix it!

**Comment by alex-w** [comment]
Hello @mene99 

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by gzotti** [comment]
We are aware of issues around the TC plugin, however it requires somebody with the relevant hardware and some programming skills (and the will to invest a weekend or two to get it to work) to track down these issues. The release Notes include our recommendations.

Do you see issues with the Qt5-based release 23.3?

**Comment by mene99** [comment]
> Hello @mene99
> 
> Please check the fresh version (development snapshot) of Stellarium: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

Yes, the newest snapshot work on Q6

**Comment by gzotti** [comment]
So we can consider this a duplicate and close?

**Comment by mene99** [comment]
just one last questions, what is the difference between Qt5 and At6?

**Comment by gzotti** [comment]
Qt is a programming framework (think of "toolbox") which provides basic programming functionalities for all major platforms. 

Qt6 is the successor of Qt5, just like Windows 10 is the successor to Windows 7 (considering Win8 a bad joke). 

Just as Windows 10 will reach end-of-life in October 2025, Qt5 will also be left to die at some date in the future. Until then, preferrably earlier, developers should have moved on to base their works on Qt6, and leave Qt5-based versions behind.

**Comment by mene99** [comment]
Thank you!

**Comment by mene99** [comment]
> > Now I wonder what changed in TC from 23.1 to 23.2 that broke something even more
> 
> 23.1 should also not have worked unless the Qt5 version was in use. The fix came after 23.2 (which was released on July 2):
> 
> ```
> commit 3940ea9d63cd75aa6bdfb630904f09da96ff0879
> Author: Georg Zotti <Georg.Zotti@univie.ac.at>
> Date:   Tue Jul 4 23:05:58 2023 +0200
> 
>     TelescopeControl: Fix connection to a renamed signal
> 
> commit 2a77c0ee2b6e3864cb9df95e72e2f6dc7dc8d1a5
> Author: Andy Kirkham <1134086+A-j-K@users.noreply.github.com>
> Date:   Tue Jul 4 15:23:01 2023 +0100
> 
>     Ensure Unicode strings are converted when compiling  with Unicode enabled (#3301)
>     
>     TelescopeControl: handle Unicode correctly (Fix #2934)
>     - also remove QT6 conditional compile, use QString across Qt5/6 for Windows
> ```

indeed it was the Qt5 for 23.1

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by mene99** [comment]
Thank you , so i will wait for the next version to come and go with Qt6!

Cheers

**Comment by mabuimo** [comment]
I don't think this bug is fixed with version 23.3. I must use Stellarium 19.3 to move a SW AZ GOTO mount.

**Comment by gzotti** [comment]
Also 23.3-qt5-win32 or 23.3-qt5-win64 use Qt5. But I have no idea what a SW AZ GOTO mount is and what kind of connection it uses.

**Comment by mabuimo** [comment]
Hi gzotti, it is a [Sky-Watcher AZ GOTO ](https://skywatcher.com/product/az-gt/). The connection is achieved using an RJ12 (6-pin)  to RS-242 (serial) cable.

**Comment by gzotti** [comment]
I don't mean connector, but what protocol connection. But this one seems directly supported (SUG 16.2.5). Still, it should work at least with a Qt5-based 23.3, as well or better than with 0.19.3. If it does not, please open a new bug report with exact description of the problem, i.e. under which circumstances something unexpected happens. "Does not work with my telescope" is clearly not enough. Is there a crash, is other software involved, does it appear to connect and nothing happens, ... the usual issue template should guide you through the report process.  We usually cannot deal with such reports directly when we don't have this hardware. It takes others of you with that hardware to stumble upon these problems and solve it.
