### ISSUE TITLE
ISS... Why does the ISS show up 20 minutes before your Satellite ISS tracker actually shows it on Stellarium on my computer screen?

### ISSUE THREAD

**Issue by garysunfist** [Stellarium/stellarium#3384]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by garysunfist** [comment]
This has been going on for several months now.

**Comment by gzotti** [comment]
Duplicate of #2654
