### ISSUE TITLE
cannot find STARLINK-30295

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3388]
### Expected Behaviour

after resetting and updating sources, this sat does not appear in Stellarium (already several days now):
https://heavens-above.com/satinfo.aspx?satid=70295

probably unrelated (because starlinks ARE updated via other source) but the default source list also contains a erratic source:
[Satellites] FAILED to download "https://celestrak.org/NORAD/elements/supplemental/starlink.txt" Error: "Error transferring https://celestrak.org/NORAD/elements/supplemental/starlink.txt - server replied: Not Found"

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version:  23.2.247-d70c06a [master]
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

[log.txt](https://github.com/Stellarium/stellarium/files/12512779/log.txt)

**Comment by alex-w** [comment]
This is not Stellarium bug. I’ve updated link to supplemental TLE data, but if you’re not loaded  data for some satellite, the you can’t find it in Stellarium.
