### ISSUE TITLE
Scripting API, what is a substitution for StelSkyDrawer.setBortleScaleIndex?

### ISSUE THREAD

**Issue by andrey-nakin** [Stellarium/stellarium#3390]
Hello!

`StelSkyDrawer` no longer has `setBortleScaleIndex` method in Scripting API.

What can be used as a substitution for it?

**Comment by 10110111** [comment]
Looking at the code I can't confirm that there's no such method. How did you conclude this?

**Comment by alex-w** [comment]
See http://stellarium.org/doc/23.0/classStelSkyDrawer.html#a4e4405fbd4a1a36c4d8b89d5de4abf50

**Comment by 10110111** [comment]
@alex-w 

> The limit is valid only at a given zoom level (around 60 deg)

What is this about? Is the text misplaced?

**Comment by alex-w** [comment]
From the description: Set the parameters so that the stars disappear at about the naked-eye limiting magnitude corresponding to the given zenith luminance at moonless night.

**Comment by andrey-nakin** [comment]
@alex-w thank you!

Is there an easy way to convert bortle scale to a magnitude/arcmin^2?

**Comment by alex-w** [comment]
@andrey-nakin please see https://en.wikipedia.org/wiki/Bortle_scale

**Comment by 10110111** [comment]
> From the description

Either my browser is broken, or the Doxygen output is:

![Screenshot_2023-09-05_16-03-45](https://github.com/Stellarium/stellarium/assets/6376882/ed73cd7b-4d81-4140-af17-b4384ce79363)

**Comment by alex-w** [comment]
> > From the description
> 
> Either my browser is broken, or the Doxygen output is:
> 
> ![Screenshot_2023-09-05_16-03-45](https://user-images.githubusercontent.com/6376882/265691494-ed73cd7b-4d81-4140-af17-b4384ce79363.png)
 
This part you will see when link “more” pressing in the list of scriptable methods above.

**Comment by 10110111** [comment]
> This part you will see when link “more” is pressing in the list of scriptable methods above.

Well, this is a bad layout, because I got to this part by mere following your link. The `@brief` should also be there in the full section. If the layout can't be changed, then the approach to filling the `@brief` and the full parts in the sources should be changed.
