### ISSUE TITLE
Return code -6 when running script in Stellarium

### ISSUE THREAD

**Issue by andrey-nakin** [Stellarium/stellarium#3391]
Stellarium fails with error -6 when running my script.
Here are the last lines of Stellarium console log:

```
...
getPauseScript() is deprecated and will no longer be available in future versions of Stellarium.
Unloaded plugin "SolarSystemEditor"
Unloaded plugin "Satellites"
Unloaded plugin "Oculars"
Unloaded plugin "Novae"
Unloaded plugin "MeteorShowers"
Unloaded plugin "Exoplanets"
Downloaded 0 files (0 kbytes) in a session of 1492.97 sec (average of 0 kB/s + 0 files from cache (0 kB)).
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.
malloc(): unsorted double linked list corrupted
Stellarium return code -6
```

**Comment by gzotti** [comment]
I see you are using the deprecated pauseScript() call. After that, at some later point, you exit Stellarium, and during exiting, there is this malloc error. 
Does your script initialize the exit from Stellarium?

Do we have to guess all this? https://github.com/Stellarium/stellarium/wiki/FAQ#reporting-a-crash

**Comment by alex-w** [comment]
@andrey-nakin any feedback please

**Comment by andrey-nakin** [comment]
@alex-w sorry for the delay. I'm trying to reproduce the issue and I can't. I can provide a bit more info about the circumstances the error occurred in.

- The app is working in Linux Mint.
- The script a quite big, about 200k.
- The script makes a lot of screeshots and writes them to the disk.
- The script is working for tens of minutes.
- The error occurs in a random manner: the same script may cause it and may finish with zero code.

I'll provide more info when I am able to reproduce the bug.

**Comment by alex-w** [comment]
Hi @andrey-nakin 

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by andrey-nakin** [comment]
Hi @alex-w 

Tried it several times with no errors. Will notify if the issue reappears.

Thanks a lot
