### ISSUE TITLE
Error when downloading stars

### ISSUE THREAD

**Issue by worachate001** [Stellarium/stellarium#3395]
### Expected Behaviour
No error.

### Actual Behaviour
It may be a minor issue that occurs when adding more stars.

This error comes up, but the process is a success.

`qt.core.qobject.connect: QObject::connect: No such signal QNetworkReplyHttpImpl::error(QNetworkReply::NetworkError)`

### Steps to reproduce
F2 > Extras > Star catalog updates

### System
* Stellarium version: master
* Operating system: Manjaro 23.0

**Comment by alex-w** [comment]
Please share a log

**Comment by worachate001** [comment]
[log.txt](https://github.com/Stellarium/stellarium/files/12546372/log.txt)

**Comment by alex-w** [comment]
Thanks! Please try update TLE - I fear it will not work (changes in Qt 6.5.2?)

**Comment by worachate001** [comment]
> Thanks! Please try update TLE - I fear it will not work (changes in Qt 6.5.2?)

It seems to work with this log file. 
[log.txt](https://github.com/Stellarium/stellarium/files/12546598/log.txt)
