### ISSUE TITLE
Some warnings before 23.3 release. No errors.

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#3401]
### Actual Behaviour
It works ok, therse are only warnings.

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/12563766/log.txt)

Here is a list log.txt warnings that you can improve Stellarium. No errors, only watnings. Two notes. I have added daylight.css to get Stellarium not so dark. The missing dayliht Html.css can be my vault or that is Stellarium. Don't know. I have bought last spring an EQ-3 pro, which is goto. And I think that I try to connect it to Stellarium in this autumn. Not tried yet. Lines beginning x## are comments, not errors or warnings.

x## Stellarium 23.2+ (v23.2.251-4671a1d [master]

INFO: Cannot find these planetary objects to assign nomenclature items: "Dactyl, Dimorphos"

WARNING - No position data for 9 objects: PGC 59117, PGC 73957, PGC 100170, PGC 100170, PGC 119230, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124

x## Loading style file: /home/user/.stellarium/daylight.css
Cannot find daylight Html.css. Loading default HTML style.

x## This occurs after setting telescope plugin on.
[TelescopeControl] loadTelescopes(): No telescopes loaded. File is missing: "/home/user/.stellarium/modules/TelescopeControl/telescopes.json"

x## Creating scene FBO with size 3049x1363
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile

**Comment by 10110111** [comment]
> x##

You can format code (or similar text) blocks using triple backticks, like here:
````
```
### some header
more code
### something else
```
````

**Comment by gzotti** [comment]
> ### Actual Behaviour
> 
> It works ok, therse are only warnings.
> ### Logfile
> 
> [log.txt](https://github.com/Stellarium/stellarium/files/12563766/log.txt)
> 
> Here is a list log.txt warnings that you can improve Stellarium. No errors, only watnings. Two notes. I have added daylight.css to get Stellarium not so dark. The missing dayliht Html.css can be my vault or that is Stellarium. Don't know. I have bought last spring an EQ-3 pro, which is goto. And I think that I try to connect it to Stellarium in this autumn. Not tried yet. Lines beginning x## are comments, not errors or warnings.
> 
> x## Stellarium 23.2+ (v23.2.251-4671a1d [master]
> 
> INFO: Cannot find these planetary objects to assign nomenclature items: "Dactyl, Dimorphos"

Normal. We have names for surface features, but not the actual moons,.

> WARNING - No position data for 9 objects: PGC 59117, PGC 73957, PGC 100170, PGC 100170, PGC 119230, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124

Deplorable, but mostly harmless.
 
> x## Loading style file: /home/user/.stellarium/daylight.css Cannot find daylight Html.css. Loading default HTML style.

As long as you don't provide also a HTML CSS, you will see this warning,
 
> x## This occurs after setting telescope plugin on. [TelescopeControl] loadTelescopes(): No telescopes loaded. File is missing: "/home/user/.stellarium/modules/TelescopeControl/telescopes.json"

Configure your telescope to create this file. 
 
> x## Creating scene FBO with size 3049x1363 qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile

PNG lib issue. Should be harmless.

**Comment by alex-w** [comment]
> Deplorable, but mostly harmless.

These objects in extended edition of DSO catalog ;)

**Comment by ilkant** [comment]
> As long as you don't provide also a HTML CSS, you will see this warning,

The error message does not give a clear message as to what the deficiency is. Is the file html.css missing Html.css or daylight_html.css or is the content of the file daylight.css incorrect? It contains many Qt-related specifications.

At least the html.css files did not remove the error message.

**Comment by gzotti** [comment]
You have followed instructions in section 6.2.3 of the User Guide to activate your own CSS. A few lines later in the same section you can read what to do about HTML style.
