### ISSUE TITLE
splash doesn't stop when starting stellarium from a script

### ISSUE THREAD

**Issue by ostfriese4** [Stellarium/stellarium#3407]
Hello,
If I start stellarium from a script (here analemma.ssc) the splash screen  disappears only after tehe script is done. I use Stellarium 23.2.0 on ubuntu 22.04.3 LTS.
![screenshot](https://github.com/Stellarium/stellarium/assets/144824657/eba2c7f3-efca-471e-8b94-df6960371996)
[log.txt](https://github.com/Stellarium/stellarium/files/12588504/log.txt)

**Comment by alex-w** [comment]
The few last lines in the log are surprising to me :(

**Comment by gzotti** [comment]
Probably the unknown properties are unrelated. The plugin is just not loaded.

I see no issue on Windows. Script runs, then the regular startup scene (current evening) is shown.

**Comment by ilkant** [comment]
Log.txt line 15: QProcess: Destroyed while process ("lspci") is still running.

I have Linux too and this writes graphics card specifications. Maybe your grpahics card or processor integrated graphics are not standard. Your processor seems not to be very fast. Maybe this causes QProcess interrupt. These are my thoughts to problem.

**Comment by alex-w** [comment]
> Log.txt line 15: QProcess: Destroyed while process ("lspci") is still running.
> 
> I have Linux too and this writes graphics card specifications. Maybe your grpahics card or processor integrated graphics are not standard. Your processor seems not to be very fast. Maybe this causes QProcess interrupt. These are my thoughts to problem.

This is a separate problem. I think we need to rewrite the part of logger which get the hardware information (a cross-platform of course or, at least, using standard API in specific platforms - no QProcess!).
