### ISSUE TITLE
problem with updating to v23.2

### ISSUE THREAD

**Issue by mahdi-h** [Stellarium/stellarium#3410]
when I update stellarium to v23.2 it doesn't work and shows the error "entry point not found" while v22.0 still works properly

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/FAQ#reporting-a-crash

**Comment by ilkant** [comment]
Try to find more info with Google search with keywords: entry point not found. You get many answers and links to softwares.

**Comment by alex-w** [comment]
the error "entry point not found" say that probably this is not our problem (antivirus or corrupted file system)
