### ISSUE TITLE
Black square in Planetary Nebula marker

### ISSUE THREAD

**Issue by Menno5** [Stellarium/stellarium#3420]
Minor bug but still ;)

The marker for the planetary nebula has a black square in it. See screenshot below.
When the _Use proportional hints_ is active it's especially noticeable.

Stellarium Version 23.2.264-13f21ff (weekly snapshot, qt6)
Windows 11 Pro 22H2 22621.2283
MSI RTX2080ti Gaming X Trio
Nvidia driver: 537.13

![PN](https://github.com/Stellarium/stellarium/assets/56191878/656efd6b-b728-4efe-98e7-29aafbac3955)

**Comment by gzotti** [comment]
OMG, this explains the previous GL_ONE,GL_ONE...

**Comment by 10110111** [comment]
How come it's still texture-based?..

**Comment by 10110111** [comment]
And, BTW, I don't reproduce...

**Comment by gzotti** [comment]
Planetary nebulae (usually just a tiny icon) and "regions" (amorphous cloud) still use icon textures.
