### ISSUE TITLE
23.3 Quitting Unexpectedly

### ISSUE THREAD

**Issue by kantn8r** [Stellarium/stellarium#3430]
Expected Behaviour - Stellarium to run continuously without quitting unexpectedly 

Actual Behaviour - Twice during a 2 hour session last night Stellarium quit unexpectedly. Luckily Stellarium quitting did not compromise my astronomy session running GeminiTelescope.net, PHD2 and SharpCap.

Steps to reproduce - I believe the cause each time was when I switched between SharpCap and Stellarium and attempted to move the pointer in Stellarium.

System
* Stellarium version: <Stellarium-23.3-qt6-win64.exe>
* Operating system: <Window 10 - w/ latest updates><HP Pavilion 15 Laptop PC 15-eg0073cl>
* Graphics Card: <Intel Iris X Graphics>
* Screen type: <15.6" diagonal, FHD (1920 x 1080)>

Logfile  - attached
[log_Stellarium_09252023.txt](https://github.com/Stellarium/stellarium/files/12729893/log_Stellarium_09252023.txt)

**Comment by gzotti** [comment]
Reconfirms tentatively closed #2821.
