### ISSUE TITLE
Stellarium Not Opening

### ISSUE THREAD

**Issue by JackPaxton123** [Stellarium/stellarium#3431]
I have to do an Astronomy assignment with Stellarium but it says it quit unexpectedly.

------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: B5751692-089D-4C2D-8D90-62062B387B7A
CrashReporter Key:   87E0EE5D-FE1B-88EC-4C4B-DF7212D4DED3
Hardware Model:      MacBookAir10,1
Process:             stellarium [8518]
Path:                /Users/USER/Desktop/Stellarium.app/Contents/MacOS/stellarium
Identifier:          org.stellarium.Stellarium
Version:             23.2.0 (23.2.0)
Code Type:           X86-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           org.stellarium.Stellarium [114072]

Date/Time:           2023-09-26 20:14:20.7824 -0500
Launch Time:         2023-09-26 20:14:20.7244 -0500
OS Version:          macOS 13.3 (22E252)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: ROSETTA 0 
rosetta error: Attachment of code signature supplement failed: 1 
/var/db/*/stellarium.aot

Triggered by Thread:  0

Thread 0 Crashed:
0   runtime                       	    0x7ff7ffdbf5a4 0x7ff7ffdbb000 + 17828

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000022   x1: 0x0000000000000000   x2: 0x00007ff7ffdecb11   x3: 0x0000000000000800
    x4: 0x00007ff7ffde740e   x5: 0x0000000000000000   x6: 0x000000000000002c   x7: 0x0000000000000000
    x8: 0x00007ff7ffdf6000   x9: 0x0000000000000000  x10: 0x00000000fffffed4  x11: 0x00007ff7ffdf6993
   x12: 0x0000000000000078  x13: 0x3263303531393532  x14: 0x00007ff7ffdde980  x15: 0x00007ff7ffdf68b4
   x16: 0x0000000000000209  x17: 0x000000030a2d2487  x18: 0x000000030a2d306b  x19: 0x00007ff7ffdecb11
   x20: 0x00007ff7ffdecb11  x21: 0x0000000103bcf000  x22: 0x0000000000000004  x23: 0x0000000103bcf000
   x24: 0x0000000000000003  x25: 0x0000000000000001  x26: 0x00000000012e4000  x27: 0x0000000204074000
   x28: 0x000000030a2db950   fp: 0x000000030a2d2540   lr: 0x00007ff7ffdd8c14
    sp: 0x000000030a2d2520   pc: 0x00007ff7ffdbf5a4 cpsr: 0x40001000
   far: 0x00007ff7ffdd8cb0  esr: 0x56000080  Address size fault

Binary Images:
       0x203fcc000 -        0x204067fff dyld (*) <afa3518c-143e-3060-bbe8-624d4ca41063> /usr/lib/dyld
    0x7ff7ffdbb000 -     0x7ff7ffdeafff runtime (*) <baf9136b-e1ff-3661-ad17-0f4ca7ce58f9> /usr/libexec/rosetta/runtime

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"stellarium","timestamp":"2023-09-26 20:14:20.00 -0500","app_version":"23.2.0","slice_uuid":"223e835a-4dc1-3598-ac95-8f674bf34bb7","build_version":"23.2.0","platform":0,"bundleID":"org.stellarium.Stellarium","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.3 (22E252)","roots_installed":0,"name":"stellarium","incident_id":"B5751692-089D-4C2D-8D90-62062B387B7A"}
{
  "uptime" : 2200000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "coalitionID" : 114072,
  "osVersion" : {
    "train" : "macOS 13.3",
    "build" : "22E252",
    "releaseType" : "User"
  },
  "captureTime" : "2023-09-26 20:14:20.7824 -0500",
  "incident" : "B5751692-089D-4C2D-8D90-62062B387B7A",
  "pid" : 8518,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-09-26 20:14:20.7244 -0500",
  "procStartAbsTime" : 52888869227728,
  "procExitAbsTime" : 52888869772441,
  "procName" : "stellarium",
  "procPath" : "\/Users\/USER\/Desktop\/Stellarium.app\/Contents\/MacOS\/stellarium",
  "bundleInfo" : {"CFBundleShortVersionString":"23.2.0","CFBundleVersion":"23.2.0","CFBundleIdentifier":"org.stellarium.Stellarium"},
  "storeInfo" : {"deviceIdentifierForVendor":"E174927B-7347-590C-83A2-AA0FC199495F","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.stellarium.Stellarium",
  "crashReporterKey" : "87E0EE5D-FE1B-88EC-4C4B-DF7212D4DED3",
  "throttleTimeout" : 2147483647,
  "codeSigningID" : "org.stellarium.Stellarium",
  "codeSigningTeamID" : "3WW8XR23DF",
  "codeSigningFlags" : 570490881,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 1672,
  "sleepWakeUUID" : "F0CD0240-F5E8-4868-8A48-3D87DAD24D46",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":518,"code":0,"namespace":"ROSETTA","details":["rosetta error: Attachment of code signature supplement failed: 1 \n\/var\/db\/*\/stellarium.aot"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":19674664,"threadState":{"x":[{"value":34},{"value":0},{"value":140703126440721},{"value":2048},{"value":140703126418446},{"value":0},{"value":44},{"value":0},{"value":140703126478848},{"value":0},{"value":4294966996},{"value":140703126481299,"symbolLocation":235,"symbol":"__crashreporter_info__"},{"value":120},{"value":3630798729607984434},{"value":140703126382976},{"value":140703126481076,"symbolLocation":12,"symbol":"__crashreporter_info__"},{"value":521},{"value":13055632519},{"value":13055635563},{"value":140703126440721},{"value":140703126440721},{"value":4357681152},{"value":4},{"value":4357681152},{"value":3},{"value":1},{"value":19808256},{"value":8657518592,"symbolLocation":0,"symbol":"dyld_all_image_infos"},{"value":13055670608}],"flavor":"ARM_THREAD_STATE64","lr":{"value":140703126359060},"cpsr":{"value":1073745920},"fp":{"value":13055632704},"sp":{"value":13055632672},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":140703126255012,"matchesCrashFrame":1},"far":{"value":140703126359216}},"frames":[{"imageOffset":17828,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8656830464,
    "size" : 638976,
    "uuid" : "afa3518c-143e-3060-bbe8-624d4ca41063",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703126237184,
    "size" : 196608,
    "uuid" : "baf9136b-e1ff-3661-ad17-0f4ca7ce58f9",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=1168K resident=0K(0%) swapped_out_or_unallocated=1168K(100%)\nWritable regions: Total=43.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=43.1M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                       15.8M        6 \nVM_ALLOCATE (reserved)            19.2M        2         reserved VM address space (unallocated)\n__DATA                              80K        3 \n__DATA_CONST                        32K        1 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                         368K        4 \n__TEXT                             816K        2 \nmapped file                        6.8G       33 \n===========                     =======  ======= \nTOTAL                              6.9G       54 \nTOTAL, minus reserved VM space     6.9G       54 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "355439a21e1f573b268f6c8465bb0364c2e0a7c0",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000062
    },
    {
      "rolloutId" : "645c2d2f9e69a025b0a37e29",
      "factorPackIds" : {

      },
      "deploymentId" : 240000002
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "3a3cf641-8471-4e4e-9ad4-81d0ede970fd",
      "experimentId" : "64a84dae90d82611a0bd7d3d",
      "deploymentId" : 400000010
    },
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    }
  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: MacBookAir10,1, BootROM 8422.100.650, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Jan 12 2023 05:52:26 version 18.20.383.14.7.8.149 FWID 01-1469d19d
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by alex-w** [comment]
I can't reproduce the crash

**Comment by hn-88** [comment]
Hi @alex-w 

@JackPaxton123  seems to be running a  X86-64 version on a  MacBookAir10,1 which has an Apple M1 chip. Is that the correct version for that chipset?

**Comment by alex-w** [comment]
> Hi @alex-w
> 
> @JackPaxton123 seems to be running a X86-64 version on a MacBookAir10,1 which has an Apple M1 chip. Is that the correct version for that chipset?

x86_64 bundles should be running via Rosetta 2 on arm64 chips, so, it should be work (and it works on my MBP M1 on macOS 13.6/14.0)

**Comment by alex-w** [comment]
Seems like this is not our bug: https://coder-studio.ru/q-2408777/dotnet-watch-run-vydayet-oshibku-rosetta-ne-udalos-prikrepit-dopolneniye-podpisi-koda-1-posle-sokhraneniya

**Comment by 10110111** [comment]
@alex-w Just in case, your previous link was a machine translation of [this thread](https://stackoverflow.com/q/73971248/673852).

**Comment by alex-w** [comment]
@JackPaxton123 please check latest stable release or 23.4RC1 - https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
