### ISSUE TITLE
Screenshot 16-bit rendering

### ISSUE THREAD

**Issue by MadeByIToncek** [Stellarium/stellarium#3439]
**Is your feature request related to a problem? Please describe.**
-
I use Stellarium for video production [I know, not the oficial use case but whatever]. I've found out that stellarium screenshots are only 8bit, which can cause banding [see image]. This can sometimes get a bit annoying, as it can get quite obvious around dark colors. 16-bit screenshots would solve this.
![0x0](https://github.com/Stellarium/stellarium/assets/47974277/ab853dd3-54f5-4a0a-87cc-bc0035109ae3)

**Describe the solution you'd like**
-
Small dropdown, next to screenshots settings, allowing to toggle between 8-bit and 16-bit color mode.

**Describe alternatives you've considered**

**Additional context**

**Comment by 10110111** [comment]
Stellarium doesn't support deep-color rendering yet. But you can simply enable dithering in configuration, and this will solve the banding problem.

**Comment by 10110111** [comment]
If your screen is not capable of or not set up for 10-bit rendering, then 10/10/10 dithering will be useless. Even if you have set it up for this color depth but experience banding, try using 8/8/8, and if it still doesn't help, then this might be a problem in Stellarium.

**Comment by MadeByIToncek** [comment]
Thanks, switching to 8/8/8 helped ...

Here's the comparison (heavily brightened dawn)
![none](https://github.com/Stellarium/stellarium/assets/47974277/c7ea4957-6c0d-4438-816d-3f4609a5c8ea)
