### ISSUE TITLE
Weird graphics glitches when using cylindrical projection

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3440]
Using the latest master (https://github.com/Stellarium/stellarium/commit/cdd531be636b3dda94ec6919049bc264953fad86), zooming in on the Moon while using cylindrical projection causes some ugly artifacts, see the screenshot below.

![stellarium-268](https://github.com/Stellarium/stellarium/assets/37028368/70b4c575-cf7d-469b-9593-6a8469b0e0f2)

Probably introduced by #3438.

**Comment by 10110111** [comment]
Hmm, indeed, the approach used is broken.
