### ISSUE TITLE
AstroCalc: Crash when clicking calculate ephemeris button

### ISSUE THREAD

**Issue by worachate001** [Stellarium/stellarium#3441]
Something just break ephemeris calculation. 

### Expected Behaviour
No crash.

### Actual Behaviour
Crash when clicking calculate ephemeris button.

This error appears when running with gdb:
```
ASSERT: "dateTime.timeSpec()==Qt::UTC" in file /home/worachate/stellarium/src/core/StelUtils.hpp, line 521

Thread 1 "stellarium" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, 
    no_tid=no_tid@entry=0) at pthread_kill.c:44
Downloading source file /usr/src/debug/glibc-2.37-5.fc38.x86_64/nptl/pthread_kill.c
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
Missing separate debuginfos, use: dnf debuginfo-install xorg-x11-drv-nvidia-libs-535.113.01-1.fc38.x86_64
```

### Steps to reproduce
1. [F10]
2. Ephemeris
3. Select a celestial body
4. Calculate ephemeris

### System
* Stellarium version: 23.3+ (latest master)
* Operating system: Fedora Linux 38 (Workstation Edition)

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
@worachate001 please check the master

**Comment by worachate001** [comment]
> @worachate001 please check the master

@alex-w no more crash, thanks.
