### ISSUE TITLE
Wrong character in Meade LX200 comand

### ISSUE THREAD

**Issue by labrat0638** [Stellarium/stellarium#3451]
I checked serial port communication in telescope control plugin. Since I made and build own GOTO implementation (on Arduino) it worked flawlessly in Stellarium with Meade LX200 protocol. Until problems with Qt6 versions. Now it mainly fixed, congratulations. But now I noticed Arduino does not react properly on sent by Stellarium target coordinates. I sniffed USB communication with program Device Monitoring Studio. Now Stellarium uses weird character instead `[*]` in this command: `:SdsDD*MM:SS#`. (Look into attachments)

### Expected Behaviour

![Comand in old version](https://github.com/Stellarium/stellarium/assets/147339096/2fec7c8c-81eb-439b-9f0c-5427e4104549)

This is implementation according to known to me MEADE LX200 protocol documentation. ( I older versions like: 0.20.2)

### Actual Behaviour

![Comand in new version](https://github.com/Stellarium/stellarium/assets/147339096/17163baf-0498-4918-b009-f5b0dbabdb74)

This is implementation with not expected sign (in Stellarium 23.3)

### System
* Stellarium version: stellarium-23.3-qt6-win64

* Operating system: Windows 10

**Comment by alex-w** [comment]
Please attach your LX200 protocol documentation

**Comment by 10110111** [comment]
Here is [the source](https://github.com/Stellarium/stellarium/blob/master/plugins/TelescopeControl/src/Lx200/Lx200Command.cpp#L176) of this character in Stellarium's output:
```cpp
	p[-6] = '\xDF'; // = 223, degree symbol. This is always printed as asterisk in the specs, very confusing.
```

**Comment by labrat0638** [comment]
[TelescopeProtocol_2010-10.pdf](https://github.com/Stellarium/stellarium/files/12841429/TelescopeProtocol_2010-10.pdf)
page: 13

[command-protocol-v2.13.2.pdf](https://github.com/Stellarium/stellarium/files/12841431/command-protocol-v2.13.2.pdf)
page: 27

**Comment by 10110111** [comment]
[Here](https://www.astro.louisville.edu/software/xmtel/archive/xmtel-indi-6.0/xmtel-6.0l/support/lx200/CommandSet.html#LX200CmdSetGrammar) we can also find the discussion of `°` sign denoted by `*` in the manuals:

> the degree symbol (ASCII 223 '°' [0xdf]) non-terminal is used as the separator character in degrees and minutes. This character is shown as an asterisk (ASCII 0x2a '*') in the manual for both the 16-inch and smaller telescopes and is followed by a note in the manual describing the ASCII value of the character.

**Comment by 10110111** [comment]
Finally, your second document discusses the meaning of the asterisk in _Commands_ section on page 2 of 46.

**Comment by labrat0638** [comment]
So, this mean the older versions of Stellarium had wrong implementation.

**Comment by gzotti** [comment]
Groundhog day? Years ago I found a mismatch between code and specs, tried to repair according to the specs. Users complained this broke the program. We reverted, and all users were happy again.  Now a problem appears in some Arduino implementation. Is the program currently working with genuine LX200 systems?

**Comment by labrat0638** [comment]
> Groundhog day? Years ago I found a mismatch between code and specs, tried to repair according to the specs. Users complained this broke the program. We reverted, and all users were happy again. Now a problem appears in some Arduino implementation. Is the program currently working with genuine LX200 systems?

Exactly, I can easily adapt my Arduino project to current Stellarium implementation, but owners of Meade Telescopes not so much.

**Comment by gzotti** [comment]
Can we close this?

**Comment by gzotti** [comment]
We can presumably close this as resolved. The "unexpected" character 223 is actually required.
