### ISSUE TITLE
Multi screen display

### ISSUE THREAD

**Issue by EdAddis** [Stellarium/stellarium#3453]
I have a two-monitor setup, with the main one on the left hand side.  Stellarium always opens on the right one, which I use for supplementary programs that I'm not working on.  There doesn't appear to be any way of running the program in a non-maximised way and hence of dragging it over to my main screen.  I found a way to move it from the keyboard but, unlike other programs, it doesn't open by default on the screen where it was last closed.  Can you please let me know how to control which screen it opens on?

**Comment by gzotti** [comment]
You can at least exit fullscreen, drag it over and go into fullscreen again. IIRC it should always open on the first screen. Whether this is your main screen depends on OS settings.

**Comment by EdAddis** [comment]
I can't find any way to exit full screen

**Comment by 10110111** [comment]
<kbd>F11</kbd>

**Comment by 10110111** [comment]
> IIRC it should always open on the first screen.

Which screen to open on is a setting, which should be saved when you click _Save settings_ while having the window on the desired screen.

**Comment by EdAddis** [comment]
Thanks F11 works OK, but there is no handle to drag the screen!

**Comment by EdAddis** [comment]
> > IIRC it should always open on the first screen.
> 
> Which screen to open on is a setting, which should be saved when you click _Save settings_ while having the window on the desired screen.

On a setting in Stellarium?  Where?

**Comment by gzotti** [comment]
> Thanks F11 works OK, but there is no handle to drag the screen!

Which OS are you using that does have borderless/handle-less windows? On leaving fullscreen on MS Windows the window may have its content area on top-left edge. The mouse still moves the window down to show the top edge.

**Comment by 10110111** [comment]
> On a setting in Stellarium? Where?

Press <kbd>F2</kbd> and you'll get the _Configuration_ dialog.

**Comment by EdAddis** [comment]
> > > IIRC it should always open on the first screen.
> > 
> > 
> > Which screen to open on is a setting, which should be saved when you click _Save settings_ while having the window on the desired screen.
> 
> On a setting in Stellarium? Where?

Certainly can't see that in Configuration.  As I said in the OP, closing the programme whilst on a different monitor doesn't seem to affect which one it opens on.

**Comment by EdAddis** [comment]
> > Thanks F11 works OK, but there is no handle to drag the screen!
> 
> Which OS are you using that does have borderless/handle-less windows? On leaving fullscreen on MS Windows the window may have its content area on top-left edge. The mouse still moves the window down to show the top edge.

Thanks - the handle was off screen at the top for some reason!

**Comment by EdAddis** [comment]
> > On a setting in Stellarium? Where?
> 
> Press F2 and you'll get the _Configuration_ dialog.

Thanks.  Still can't find anything there for this problem.

**Comment by 10110111** [comment]
> Still can't find anything there for this problem.

Which problem exactly? To save the size and position of your window click _Save settings_. Did you try this?

**Comment by EdAddis** [comment]
It's OK, I have a fix now anyway.  My secondary screen was set as the main one, so I've just changed that and the program is now opening on the other one, as required.
Many thanks for your help.
Ed

    On Monday, 9 October 2023 at 22:36:11 BST, Ruslan Kabatsayev ***@***.***> wrote:  
 
 



Still can't find anything there for this problem.


Which problem exactly? To save the size and position of your window click Save settings. Did you try this?
