### ISSUE TITLE
Display planet nomenclature information

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#3455]
Stellarium can display named features on planet surfaces (NomenclatureItem). The names can be translated, which is necessary only for few languages. Translators see the explanation who the commemorated person (or terrestrial landscape, mythical river, ...)  was. Users don't see that.

**Describe the solution you'd like**
Add an optional line to the NomenclatureItem InfoString that provides translatable information about the feature name. This has about the same add-on value as discoverer names for DSO. 

**Describe alternatives you've considered**
None so far. (Looking up in Transifex or the pot file is no real solution.)

**Additional context**

The current format is `(SSO); information` . This format can be translated as-is. For display, the part `(SSO);` can be omitted. However, how would RtoL languages (e.g. arab) have to be formatted?

**Comment by alex-w** [comment]
I can add this feature by half hour, but this is bad idea, because it will add over 15000 new translatable strings

**Comment by gzotti** [comment]
I know the number is huge, and it may be a bad idea to just simply add the strings for all. However, it is IMHO interesting side info. 
Maybe we should think of add-on translation/info packages for in-program installation? (Like downloadable star catalogs. Also the extra DSO catalog could be transformed into an in-program download.)
I think exactly the translations for the planet nomenclature offers itself as add-on download. If not installed, only the English names would be shown. This may be enough for most users. Those interested in translated names and/or their explanation could install the translated package. And probably nomenclatureItem  "name translation" can be limited to languages "where necessary" (e.g. where it includes transliteration). Many European languages likely just copy all the ("internationally approved") names 1:1.
