### ISSUE TITLE
Sudden change of the Milky Way position between 1582 and 1583

### ISSUE THREAD

**Issue by NataliaSanchezSteiner** [Stellarium/stellarium#3464]
### Expected Behaviour
As years pass, the Milky Way as observed over the local eastern horizon (Bogotá, Colombia) should be seen moving very slowly towards the south. 
### Actual Behaviour
However, if you check its position (check the galactic equator line) in the year 1582 compared to the one in the year 1583, it has a huge leap of around 20° on azimuth. This leap does not happen years before 1582 nor after 1583. It happens just when moving from 1582 to 1583. Naturally, this leap applies not only to the MW but to all stars.
Screenshots:
![image](https://github.com/Stellarium/stellarium/assets/148076261/dd9e129c-e7a7-4c33-93c7-8d620eea1e6b)
![image](https://github.com/Stellarium/stellarium/assets/148076261/d4bcf4f3-df8a-465c-9685-ac818fad353b)

### Steps to reproduce
1. Set date 16th June 1582, 19:30. Location: Bogotá, Colombia
2. Enable the galactic equator line
3. Set view towards the east
4. Change the year from 1582 to 1583 
5. See the unexpected leap of the Galactic equator line

### System
* Stellarium version: 23.3.0
* Operating system: Windows 10
* Graphics Card: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.70 GHz

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
2023-10-16T15:02:45
Operating System: Windows 10 Version 22H2
Compiled using MSVC++ 16.10, 16.11 (Visual Studio 2019)
Qt runtime version: 6.5.2
Qt compilation version: 6.5.2
Addressing mode: 64-bit
Total physical memory: 12204 MB
Available physical memory: 3575 MB
Physical memory in use: 70%
Processor speed: 2712 MHz
Processor name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Processor speed: 2712 MHz
Processor name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Processor speed: 2712 MHz
Processor name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Processor speed: 2712 MHz
Processor name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
C:\Program Files\Stellarium\stellarium.exe 
 -------------------------------------------------------------
[ This is Stellarium 23.3 (v23.3.0) - https://stellarium.org/ ]
[ Copyright (C) 2000-2023 Stellarium Developers               ]
 -------------------------------------------------------------
Writing log file to: C:\Users\nats_\AppData\Roaming\Stellarium\log.txt
File search paths:
 [0]: C:\Users\nats_\AppData\Roaming\Stellarium
 [1]: .
Attempting to use an existing older config file.
Cleared cache and updated config.ini...
Config file: C:\Users\nats_\AppData\Roaming\Stellarium\config.ini
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
OpenGL module type: desktop OpenGL
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
Default surface format:  QSurfaceFormat(version 3.3, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::CoreProfile)
OpenGL module type: desktop OpenGL
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL(windowWidth = 1366, windowHeight = 705)
OpenGL supported version:  "3.3.0 - Build 25.20.100.6518"
Current Format:  QSurfaceFormat(version 3.3, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::CoreProfile)
Initialization StelMainView
Luminance textures are not supported
Maximum texture anisotropy: 16
Maximum 2D texture size: 16384
Detected: OpenGL 3.3
Driver version string: 3.3.0 - Build 25.20.100.6518
GL vendor: Intel
GL renderer: Intel(R) HD Graphics 620
GL Shading Language version: 3.30 - Build 25.20.100.6518
GLSL Version Number detected: 3.3
GLSL version is fine, we should not see a graphics problem.
stel.OpenGLArray: Vertex Array Objects are supported
Sky language: en_GB
Empty translation file for language  "en_GB" in section "stellarium-planetary-features"
Planetary features language: en_GB
Application language: en_GB
Scripts language: en_GB
Cache directory: C:\Users\nats_\AppData\Local\stellarium\stellarium\cache
Loaded 252 countries
Loaded 193 regions
Loading Solar System data (1: planets and moons) ...
Loading from: ./data/ssystem_major.ini
Solar System has 83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies) ...
Loading from: C:\Users\nats_\AppData\Roaming\Stellarium/data/ssystem_minor.ini
Minor body  "1I/2017 U1 (`Oumuamua)" has incomplete data (missing iau_designation or minor_planet_number) in "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1I_Oumuamua"
Minor body  "2002 AA29" has incomplete data (missing iau_designation or minor_planet_number) in "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2002aa29"
Minor body  "2003 YN107" has incomplete data (missing iau_designation or minor_planet_number) in "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2003yn107"
Minor body  "2006 RH120" has incomplete data (missing iau_designation or minor_planet_number) in "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2006rh120"
Minor body  "2010 TK7" has incomplete data (missing iau_designation or minor_planet_number) in "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2010tk7"
Minor body  "2013 LX28" has incomplete data (missing iau_designation or minor_planet_number) in "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2013lx28"
Comet  "P/2013 CU129 (PANSTARRS)" has no IAU designation, no perihelion code, no discovery code and seems not a numbered comet in section  "p2013cu129%28panstarrs%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "p2013cu129%28panstarrs%29"
Comet  "P/2010 V1 (Ikeya-Murakami)" has no IAU designation, no perihelion code, no discovery code and seems not a numbered comet in section  "p2010v1%28ikeyamurakami%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "p2010v1%28ikeyamurakami%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2016u1%28neowise%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2014w2%28panstarrs%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2014r1%28borisov%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2014q3%28borisov%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2014q2%28lovejoy%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2013v5%28oukaimeden%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2013us10%28catalina%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2013a1%28sidingspring%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2012x1%28linear%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2012k1%28panstarrs%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2012f3%28panstarrs%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "c2011kp36%28spacewatch%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "TeslaRoadster"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "P_Halley_2061"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "C_1996B2%28Hyakutake%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "C_1995O1%28Hale-Bopp%29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "9ptempel"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "99942apophis"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "951gaspra"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "90482orcus"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "90377sedna"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "88phowell"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "81pwild"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "7pponswinnecke"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "71pclark"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "6pd%27arrest"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "67pchuryumovgerasimenko"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "66pdutoit"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "64pswiftgehrels"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "62ptsuchinshan"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "556372002ux25"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "53pvanbiesbroeck"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "5261eureka"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "51pharrington"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "50000quaoar"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "4vesta"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "48pjohnson"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "4692192016hq3"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "45phondamrkospajdusakova"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "43pwolfharrington"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "433eros"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "41ptuttlegiacobinikresak"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "4196242010so16"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "3juno"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "38628huya"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "37pforbes"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "3753cruithne"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "367943duende"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "3574392004bl86"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "32pcomassola"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "3200phaethon"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "3119992007ns2"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "3072612002ms4"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2pencke"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2pallas"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "29pschwassmannwachmann"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2867steins"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2778102006fv35"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "253mathilde"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "25143itokawa"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "24pschaumasse"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "243ida"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "230plinear"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "22pkopff"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2297622007uk126"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2250882007or10"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "21pgiacobinizinner"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "21lutetia"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "218plinear"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "218bianca"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "213pvanness"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2089962003az84"
minor body  "2013 LX28" has no IAU code in section  "2013lx28"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2013lx28"
minor body  "2010 TK7" has no IAU code in section  "2010tk7"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2010tk7"
minor body  "2006 RH120" has no IAU code in section  "2006rh120"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2006rh120"
minor body  "2003 YN107" has no IAU code in section  "2003yn107"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2003yn107"
minor body  "2002 AA29" has no IAU code in section  "2002aa29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "2002aa29"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "20000varuna"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1phalley"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1ceres"
Comet  "1I/2017 U1 (`Oumuamua)" has no IAU designation, no perihelion code, no discovery code and seems not a numbered comet in section  "1I_Oumuamua"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1I_Oumuamua"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "19pborrelly"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1866sisyphus"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1864daedalus"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "185ppetriew"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1810epimetheus"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1809prometheus"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "174567varda"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1642072004gu9"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "15pfinlay"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1566icarus"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "144pkushida"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "141pmachholz"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "136472makemake"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "136199eris"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "136108haumea"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1215141999uj7"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "120347salacia"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "116pwild"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "10ptempel"
Old-fashioned entry "comet_orbit" found. Please delete line from  "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini" section "1014291998vf31"
Solar System has 186 entries.
Loaded 103 Solar System bodies
File ssystem_minor.ini is loaded successfully...
qt.gui.imageio: libpng warning: iCCP: profile 'ICC profile': 'RGB ': RGB color space not permitted on grayscale PNG
Loading nomenclature for Solar system bodies ...
Loaded 15883 / 15939 items of planetary surface nomenclature
INFO: Cannot find these planetary objects to assign nomenclature items: "Bennu, Dactyl, Dimorphos, Ryugu"
Loading star data ...
Loading star catalog: .\stars\default\stars_0_0v0_8.cat - 0_0v0_8; 4979 entries
Loading star catalog: .\stars\default\stars_1_0v0_8.cat - 1_0v0_8; 21806 entries
Loading star catalog: .\stars\default\stars_2_0v0_8.cat - 2_0v0_8; 150826 entries
Loading star catalog: .\stars\default\stars_3_1v0_4.cat - 3_1v0_4; 425807 entries
Finished loading star catalogue data, max_geodesic_level: 3
Loading scientific star names from .\stars\default\name.fab
Loaded 4942 / 4942 scientific star names
Loading scientific star extra names from .\stars\default\extra_name.fab
Loaded 26200 / 26200 scientific star extra names
Loading variable stars from .\stars\default\gcvs_hip_part.dat
Loaded 6862 / 6862 variable stars
Loading double stars from .\stars\default\wds_hip_part.dat
Loaded 22992 / 22992 double stars
Loading cross-identification data from .\stars\default\cross-id.dat
qt.gui.imageio: libpng warning: iCCP: profile 'icc': 'GRAY': Gray color space not permitted on RGB PNG
Loaded 108378 / 108378 cross-identification data records for stars
Loading parallax errors data from .\stars\default\hip_plx_err.dat
Loaded 117703 / 117703 parallax error data records for stars
Loading proper motion data from .\stars\default\hip_pm.dat
Loaded 117955 / 117955 proper motion data records for stars
navigation/preset_sky_time is a double - treating as jday: 2451514.25001
Loading DSO data ...
[...] Stellarium DSO Catalog, version 3.20 (standard edition)
Loaded 94660 DSO records
Loading DSO outline data ...
Loaded 98 DSO outline records successfully
Loading DSO discovery data ...
Loaded 183 / 183 DSO discovery records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from .\skycultures\modern\star_names.fab
Loaded 1104 / 1104 common star names
Loading DSO name data ...
Loaded 1318 / 1343 DSO name records successfully
WARNING - No position data for 25 objects: PGC 2798, PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1000714, PGC 1436754, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124
Loaded 88 / 88 constellation records successfully for culture "modern"
Loaded 85 / 85 constellation art records successfully for culture "modern"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in asterism "TA6" - can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "modern"
Loaded 83 / 84 asterism records successfully for culture "modern"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 73 / 74 asterism names
Initializing basic GL shaders... 
Creating GUI ...
Loading style file: :/graphicGui/normalStyle.css
Loaded plugin "ArchaeoLines"
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: C:\Users\nats_\AppData\Roaming\Stellarium\modules\Exoplanets\exoplanets.json
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: C:\Users\nats_\AppData\Roaming\Stellarium\modules\MeteorShowers\MeteorShowers.json
[MeteorShowersMgr] Trying to restore the default catalog to "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\MeteorShowers.json"
[MeteorShowersMgr] The default catalog was copied!
[MeteorShowersMgr] Version of the format of the catalog: 2
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] Loading catalog file: C:\Users\nats_\AppData\Roaming\Stellarium\modules\Novae\novae.json
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at: C:\Users\nats_\AppData\Roaming\Stellarium\modules\Oculars\ocular.ini . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version 3.1
Loaded plugin "Satellites"
setFlagUmbraAtFixedDistance() currently not possible
[Satellites] loading catalogue file: "C:\\Users\\nats_\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
SSE: Comet cross-index data: Overwriting entry for "453P"
Creating scene FBO with size 1366x705
[Novae] Updating novae catalog...
[Novae] Updating novae catalog is complete...
Initializing planets GL shaders... 
Loaded 54 / 54 references
[MeteorShowersMgr] Updating meteor showers catalog...
[MeteorShowersMgr] Updating Meteor Showers catalog is complete...
  OpenType support missing for "Verdana", script 11
  OpenType support missing for "Tahoma", script 11
  OpenType support missing for "Arial", script 11
  OpenType support missing for "MS UI Gothic", script 11
  OpenType support missing for "SimSun", script 11

**Comment by alex-w** [comment]
Please read about difference between Julian and Gregorian calendars and when latest one was introduced.

**Comment by alex-w** [comment]
See #2501 and #1622 + Stellarium User Guide

**Comment by NataliaSanchezSteiner** [comment]
Hi, thank you for the comments. I suspected it had to do with the change to the Gregorian calendar. However, I don't know what to trust. I mean, should I trust that the MW and the stars are in the correct position with regard to the local horizon before 1582? Or should I enable something in the software to see it properly? And what about their positions after 1583?

**Comment by gzotti** [comment]
What you see is correct. Before 1582-10-15 all dates are in Julian calendar, on and after that date in Gregorian. Of course, if checked on a fixed date of each year, 10 days seem to be missing. This causes a leap of about 40 minutes in Sidereal time.
