### ISSUE TITLE
Custom horizon

### ISSUE THREAD

**Issue by port-hacking** [Stellarium/stellarium#3465]
Hi,
 
I have been having lots of difficulties loading a custom horizon into Stellarium.
 
I can get my png to load but I cannot get my horizon line to load. The file is called "horizon.txt" as per the script. I have tried it with and without headings, but the format is otherwise correct. It doesn't seem to matter if I have 360 or 10 points. I have used the horizon files from other peoples' examples and I can get these to load without a problem.

Do you have any suggestions?
 
Thanks,
 
Scott
 
Here is the script:
[landscape]
name = [removed for this post]
author = Scott
description = Driveway divet
type = spherical
maptex = [removed for this post].png
angle_rotatez = -230.00

polygonal_horizon_list = horizon.txt
polygonal_angle_rotatez=0.0000001
polygonal_horizon_list_mode = azDeg_altDeg

horizon_line_color = 0.25, 0.25, 0.25
minimal_brightness - 0.15

[location]
planet = Earth
latitude = [removed for this post]
longitude = [removed for this post]
altitude = 1042
atmospheric_extinction_coefficient = 0.27
atmospheric_temperature = 10.0
atmospheric_pressure = 1013.0
light_pollution = 3

**Comment by gzotti** [comment]
I see a misspelled "minimal_brightness" entry line. (no equal sign !)
Else, if it works with a different horizon.txt, the culprit is the one you are having, and we don't see it. I can easily say, mine work.

**Comment by gzotti** [comment]
I close this out of inactivity.
