### ISSUE TITLE
Hydra constellation broken in certain cultures

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3477]
The constellation of Hydra is broken when using two sky cultures; Modern (IAU) and Modern (Sky & Telescope). This is only visible when the constellation is selected using the constellation isolator. See the screenshot below.

![stellarium-271](https://github.com/Stellarium/stellarium/assets/37028368/aedcef21-30bd-45c0-8ad6-c6a0363cb3fe)

The reason it is broken is because the line between α and β Crateris is shared with Crater.

**Comment by gzotti** [comment]
Please check https://www.iau.org/static/public/constellations/gif/HYA.gif

What do you see?
