### ISSUE TITLE
Too long star names unreadable

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3479]
Very long star names, such as the al-Sufi designation of Aldebaran, are displayed in one row and thus extend beyond the screenspace. See the screenshot below, where the font is set to 12 (which is a bit too small for my screen).

![stellarium-278](https://github.com/Stellarium/stellarium/assets/37028368/31919ca6-8bc8-42ec-a94b-d5662b6c27f2)

Some kind of break to divide into several rows might be needed.

**Comment by gzotti** [comment]
It may be useful to write these descriptions (which are translations of Ptolemy's locative annotations) only into the description.en.utf8 file.
