### ISSUE TITLE
stellarium: symbol lookup error: /lib/x86_64-linux-gnu/libQt6Multimedia.so.6: undefined symbol: eglCreateImage

### ISSUE THREAD

**Issue by rpremuz** [Stellarium/stellarium#3482]
On Ubuntu 22.04 LTS I installed stellarium from ppa:stellarium/stellarium-releases

```
$ dpkg -l | grep stellarium
ii  stellarium       23.3.0-upstream1.0~ubuntu22.04.1  amd64  real-time photo-realistic sky generator
ii  stellarium-data  23.3.0-upstream1.0~ubuntu22.04.1  all    Stellarium data files
```

When I start stellarium I get the following error and the application terminates:
```
$ stellarium --verbose
stellarium: symbol lookup error: /lib/x86_64-linux-gnu/libQt6Multimedia.so.6: undefined symbol: eglCreateImage
```
Additional info:
```
$ inxi -G
Graphics:
  Device-1: NVIDIA GT218 [GeForce 210] driver: nvidia v: 340.108
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    gpu: nvidia resolution: 1920x1200~60Hz
  OpenGL: renderer: GeForce 210/PCIe/SSE2 v: 3.3.0 NVIDIA 340.108

$ dpkg -l | grep libqt6multimedia6
ii  libqt6multimedia6:amd64  6.2.4-1  amd64  Qt 6 Multimedia library
```

**Comment by alex-w** [comment]
I can't reproduce the issue in Ubunu 22.04.

**Comment by alex-w** [comment]
@rpremuz did you have installed qt framework from standard repo or PPA?

**Comment by rpremuz** [comment]
```
$ dpkg -l | grep 'libqt[56]core'
ii  libqt5core5a:amd64  5.15.3+dfsg-2ubuntu0.2  amd64  Qt 5 core module
ii  libqt6core6:amd64   6.2.4+dfsg-2ubuntu1.1   amd64  Qt 6 core module
```

`apt policy` says that the packages come from standard repositories for jammy.

**Comment by alex-w** [comment]
My system:
```
$ dpkg -l | grep stellarium
ii  stellarium          23.3.0-upstream1.0~ubuntu22.04.1    amd64  real-time photo-realistic sky generator
ii  stellarium-data     23.3.0-upstream1.0~ubuntu22.04.1    all    Stellarium data files
$ dpkg -l | grep libqt6multimedia6
ii  libqt6multimedia6:amd64      6.2.4-1                    amd64  Qt 6 Multimedia library
$ dpkg -l | grep 'libqt[56]core' 
ii  libqt5core5a:amd64           5.15.3+dfsg-2ubuntu0.2     amd64  Qt 5 core module
ii  libqt6core6:amd64            6.2.4+dfsg-2ubuntu1.1      amd64  Qt 6 core module
```
Graphics:
```
$ inxi -G
Graphics:
  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 535.129.03
  Device-2: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia
    resolution: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
    v: 4.6.0 NVIDIA 535.129.03
```
I have no described issue.

**Comment by alex-w** [comment]
According to line:
`stellarium: symbol lookup error: /lib/x86_64-linux-gnu/libQt6Multimedia.so.6: undefined symbol: eglCreateImage`
the issue in Qt6.

Please try install `qt6-qpa-plugins` package

**Comment by 10110111** [comment]
> undefined symbol: eglCreateImage
> OpenGL: renderer: GeForce 210/PCIe/SSE2 v: 3.3.0 NVIDIA 340.108

In the old times of 2009 when GeForce 210 was released, EGL was not well-supported by anything on X11. I suspect that your Qt6 was built with EGL as the OpenGL window system API, which is not suitable for your GPU driver. You may need a custom build of Qt6, or you can try the Qt5 version of Stellarium (not sure if it's provided in the PPA; if not, you'll have to build it).

**Comment by alex-w** [comment]
> or you can try the Qt5 version of Stellarium (not sure if it's provided in the PPA; if not, you'll have to build it).

We do not provide Qt5-based Stellarium for Ubuntu 22.04 via PPA. Of course, I can prepare `stellarium-qt5` package

**Comment by rpremuz** [comment]
Thank you @alex-w and @10110111 for your replies.

For me it is to much effort to create custom builds of the packages.

I'll use the web version of Stellarium (https://stellarium-web.org) on that machine.
