### ISSUE TITLE
Set time in information shows previous set time

### ISSUE THREAD

**Issue by pgriffin17** [Stellarium/stellarium#3484]
### Expected Behaviour
The set time should show the next set time if an object is above the horizon, not the previous set time on that same day. For example, if the moon rises at 16h48m on 10-24-2023, it should show the next set time, even if that set time is early in the morning the next day, 10-25-2023 at 3h26m.

### Actual Behaviour
The Moon set time is listed as 2h08m on 10-24-2023 at my location once the moon is above the horizon. This correctly updates to the next Moon set time when the time advances past midnight onto the 25th, but before that, it states the previous set time for the 24th (2h08m) as shown below.

![image](https://github.com/Stellarium/stellarium/assets/31374077/ddbc6b57-b13c-4a1c-9d6c-87e3a6c5c565)

### Steps to reproduce
Click on object above the horizon in the evening on any given day, watch the set time change on either side of midnight.

### System
* Stellarium version: stellarium-23.3-qt6-win64.exe
* Operating system: Windows 10 Home 22H2
* Graphics Card: NVIDIA RTX 3060Ti
* Screen type (if applicable): 1920x1080

**Comment by gzotti** [comment]
We have decided otherwise, trying to show rise/set of the current calendar day. This is common practice.
