### ISSUE TITLE
Is weekly snapshot not done weekly?

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#3491]
The latest [weekly snapshot](https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot) reflects the state of 70e4f4dc6e1f5b279b62265cc748dda6f7b9aed3, which is more than two weeks old. Is "weekly" a misnomer, or are there reasons for the delay?

**Comment by gzotti** [comment]
I had seen the same in summer. It used to be weekly, indeed. Maybe the simplicity of the CI build activation (at least for Win) took away the immediate need for this? But then there should be automatic links to something like the latest or 5 latest build artifacts (?). OTOH those don't describe what's new. I see it was downloaded about 50 times in those 2 weeks which is not really much, while still taking time to create/manage. It should be recreated after any significant progress (which may not warrant weekly action).

**Comment by 10110111** [comment]
> Maybe the simplicity of the CI build activation (at least for Win) took away the immediate need for this?

They are still needed when we want to avoid hitting AppVeyor's download limit. In particular, we could download "patches" from AppVeyor which would be applied on top of the last weekly snapshot. This would make it easier to have the latest assets while getting the executable from the patch.

**Comment by alex-w** [comment]
Reasons of delay is technical - I had no internet up to today (I've changed the home location)

**Comment by gzotti** [comment]
Ah, download limit, right!

**Comment by 10110111** [comment]
OK, the questions is answered, thanks.
