### ISSUE TITLE
Old-fashioned comet orbit entries in ssystem_minor.ini

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#3495]
### Expected Behaviour

No old-fashioned orbits to comets.

### Actual Behaviour
There are about 130 old-fashioned comet orbits in ssystem_minor.ini. 

### Steps to reproduce
1. Start Stellarium and look log.txt.

### System
* Stellarium version: <Stellarium 23.3+ (Version 23.3.310-a9db483 [master]>
* Operating system: <Kubuntu 23.10>
* Graphics Card: <MSI GeForce GT 1030/PCIe/SSE2 2GH LF OC, OpenGL 3.3, driver 3.3.0 NVIDIA 525.147.05>
* Screen type LG 34GK950F 3440x1440

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/13262104/log.txt)

**Comment by alex-w** [comment]
This is correct messages because you're using ssystem_minor.ini from previous versions. Please try reset the file or update orbital elements for minor bodies and comets.

**Comment by ilkant** [comment]
I downloaded ssystem_minor.ini to ~/.stellarium/data/ dorectory. Now it works and no old-fashioned lines in log.txt. Thanks. The original ssystem_minor.ini file was from January 2023. I have done several git pull commands in this year and compiled Stellarium on my computer. Pull commands have not updated that ini file. Maybe, because it's on user home directory and not /opt/stellarium directory. You can close this bugreport now.
