### ISSUE TITLE
Oculars have separate star scale settings?

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3498]
Appearantly, the Oculars plugin and its different functionalities override the star settings. If I set absolute/relative scale to 1.5/0.5, the Oculars plugin will keep the 1.0/1.0. It would make more sense if the Oculars plugin had not separate star settings.

**Comment by alex-w** [comment]
See options:
![stellarium-002](https://github.com/Stellarium/stellarium/assets/88731/237be156-00e6-487e-866a-44152add59be)

Please disable "Auto-limit stellar magnitude" if you do not want this behavior.

**Comment by alex-w** [comment]
Did you see it for Eyepiece or Sensor mode?

**Comment by Atque** [comment]
I see it in both modes.

**Comment by alex-w** [comment]
Please describe steps to reproduce the issue

**Comment by Atque** [comment]
It's not an issue, it's a feature. However, I find it a nuisance.

1. Change the absolute and relative scales of stars to e.g. 1.5 and 0.5 respectively.
2. Open Oculars (eyepiece or sensor). The stars will have different values now (1.00/1.00 by default).

What I wish for, is that the absolute and relative scales aren't stored separately when using Oculars. I get that some users want to use very small stellar disks to simulate the view through an eyepiece, but I would like to see that as a separate option then. ("Use main program's option for stars" or something.)

**Comment by gzotti** [comment]
The Oculars plugin has separate settings, very much for a reason. The current state works. Setting star scales is usually a one-time effort of user preferences.  We will not go back here! Rather (if not done) even have separate sets for eyepiece and sensor. Often photos have smaller stars than the user would expect, and it may be difficult to orient on a photo.
