### ISSUE TITLE
Ability to edit satellites info e.g. colors and comments via plugin's UI

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#350]
_Original report by José Durazo:_ https://bugs.launchpad.net/stellarium/+bug/925909

Stellarium's satellite plugin it's pretty famous for tracking satellites. I would really like if satellite's info can be edited from plugin's window instead "satellites.json". It can help to keep satellites by color category and with complementary info.

**Comment by gzotti** [comment]
Seems #380 provides a solution!
