### ISSUE TITLE
Stellarium desktop and stellarium android app not showing the same information for the same time entered

### ISSUE THREAD

**Issue by mmmgaa** [Stellarium/stellarium#3501]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by 10110111** [comment]
You haven't specified what information differs and which side is wrong. But anyway, these are two completely unrelated projects, so one shouldn't expect them to work in the same way.

**Comment by gzotti** [comment]
@mmmgaa We will close this after Dec. 15 if you don't follow up.

**Comment by mmmgaa** [comment]
Why do I need to follow up 🤔
I asked you the question !!!!!
Surely you're supposed to follow up with me !

Regards

Mark
