### ISSUE TITLE
Parallactic angle displayed also for stars

### ISSUE THREAD

**Issue by jwoillez** [Stellarium/stellarium#3509]
**Is your feature request related to a problem? Please describe.**
The Parallactic Angle calculation info is not displayed when the selected target is a star.

**Describe the solution you'd like**
But it is for any other kind of object.

**Describe alternatives you've considered**
It would make sense to also display it for stars.

**Additional context**
I would remove the test for not star on that line: https://github.com/Stellarium/stellarium/blob/d1454bd8e29cd8a2be1645520935ad1c805ed9da/src/core/StelObject.cpp#L923

**Comment by gzotti** [comment]
Why "would it make sense"? We are omitting it deliberately as useless bit of information in context of stars because a rotated pinpoint dot looks still like a pinpoint dot.

**Comment by jwoillez** [comment]
My feedback is just on why it is shown for a planet but not for a star.
The parallactic angle is a coordinate-like angle like alt,az,ra,dec that is not related to the morphology of the target. It only depends on where the target is in space and time, as observed from a location on earth. It has as much (or as less) meaning for a star as for e.g. a planet.

**Comment by gzotti** [comment]
What is your practical application for knowing the parallactic angle of a star? Give at least one use case. Else this is as useful as providing trivial math lessons like '2+2=4' in the already overcrowded information screen area.

**Comment by jwoillez** [comment]
In my case it was to verify the calculation of the parallactic angle at various sky locations for an instrumentation project for astronomy. Probably not a use case that interests a large enough fraction of the users.

It could be useful for someone who pairs Stellarium to an actual AltAz telescope, and wonders where the direction of North is with respect to the zenith/up direction on the eyepiece/detector. But showing the equatorial and azimuth grids fulfils the same purpose as displaying the parallactic angle between the two.

**Comment by gzotti** [comment]
You can set a a marker. Its P.A. is displayed.
