### ISSUE TITLE
Landscape Hijacked to an AD

### ISSUE THREAD

**Issue by RodSutter** [Stellarium/stellarium#3511]
I was trying to download a new landscape, I had just downloaded the newest version of Stellarium, when i went to your website for landscapes. I went to South America and tried to download the "[ESO's Very Large Telescope in the Atacama Desert, Chile](http://www.essl.de/wp/wp-content/uploads/2008/03/paranal.zip) when you click on it, it takes you to a  betting website.
Thanks, Rod Sutter

**Comment by gzotti** [comment]
A pity. This is an external link which apparently must be declared dead. Thanks for notifying us.

**Comment by alex-w** [comment]
The landscape was removed from our website
