### ISSUE TITLE
Creating Langscapes in Version 23.3

### ISSUE THREAD

**Issue by rcec52** [Stellarium/stellarium#3512]
I'm using EndeavourOS Linux (Arch derivative). I created a Landscape that was for an early version of Stellarium . I believe it was for version 19. It was stitched using Hugin into a panorama which was installed with a simple *.ini file. It works in the present version 23.3 with no issues. I created a new panorama and it will not display  what so ever. The software indicates that it was 'successfully installed' but the screen comes up  horizon less  without  the panorama horizon in the view port. The old zip file still works and comes up. I'm at my wits end trying to figure out what's going on. 

Any Help would be appreciated, 
Rich ;)

**Comment by alex-w** [comment]
Without log from Stellarium we can be guessing for source of this issue only. Please check the real file names and names in landscape.ini for your landscape.

**Comment by axd1967** [comment]
Same issue here with two landscapes that used to work on 0.22
polygons work, but panoramic picture does not appear.

## Workaround
**when toggling transparency on and then off, the panorama is shown.** 
this must be repeated when switching landscapes.

[log.txt](https://github.com/Stellarium/stellarium/files/13902988/log.txt)

`git bisect` tells that this bug appears in 5e14e82a79

**Comment by alex-w** [comment]
@axd1967 please share an example of landscape

**Comment by axd1967** [comment]
> @axd1967 please share an example of landscape

[landscape.ini.txt](https://github.com/Stellarium/stellarium/files/13905240/landscape.ini.txt)

[gazetteer.en.utf8.txt](https://github.com/Stellarium/stellarium/files/13905241/gazetteer.en.utf8.txt)

[horizon.txt](https://github.com/Stellarium/stellarium/files/13905242/horizon.txt)
![pano-low](https://github.com/Stellarium/stellarium/assets/3529789/efb44df3-0eb4-4596-a98e-6b42c7c28c9d)


note: when marking this landscape as "default", after a restart the landscape appears normally:
![image](https://github.com/Stellarium/stellarium/assets/3529789/15f3a2dd-b0ca-4850-93e2-acafec5b3160)


however, when switching to another , similarly configured landscape , that one doesn't appear unless toggling transparency.

when then re-selecting the original landscape, once again the workaround needs to be applied.

**Comment by alex-w** [comment]
I can't reproduce the issue

**Comment by alex-w** [comment]
Hello @axd1967 and @rcec52!

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
