### ISSUE TITLE
Saturn Missing From Charts Created with both Stellarium Versions 1.1 and 23.3

### ISSUE THREAD

**Issue by SusanSSB** [Stellarium/stellarium#3513]
Today, I have used both versions 1.1 and then 23.3 (both Windows 64bit) of Stellarium to create all-sky star charts representing the night sky for Nov. 21st 2023 at 8:00PM EST and discovered that Saturn is not showing up on either version of the chart. All the other planets that should be showing are there, but not Saturn. I am using these charts for public outreach activities, one scheduled for next Tuesday evening Nov. 21st, so it is important to me to provide accurate information.

I first created this chart with Stellarium Version 1.1 (Window 64bit) and, when I saw that Saturn was missing, I thought updating to the newest version, 23.3 (Window 64bit) would fix the problem. But it did not. I have enclosed two screen shots of the charts from Stellarium 23.3, showing where Saturn should be but no image is displayed on the chart (see below). One screenshot shows the full All Sky chart indicating the location where Saturn should be showing, and the other screenshot shows the same chart zoomed in. I have also included the Log file (see below).

I checked to see if this was a previously reported known issue, but got no hits. I get Intel updates regularly so as far as I know my graphics drivers are up to date.

Don't hesitate to let me know If you need more information. I will be happy to supply other information as long as I know where to get it. :-) I look forward to your feedback. Thank you.

### Actual Behaviour (Screenshots)
Screenshot 1, showing the all-sky chart representing the night sky for Nov. 21st 2023 at 8:00PM EST, but no Saturn image shows on the chart where it is supposed to be located.
![All Sky_ No Saturn](https://github.com/Stellarium/stellarium/assets/140850696/962d4ef3-e090-4ff4-bdb9-9f16d12945fe)

Screenshot 2, showing the all-sky chart representing the night sky for Nov. 21st 2023 at 8:00PM EST, zoomed in, but no Saturn image shows on the chart where it is supposed to be located.
![Zoomed Sky_No Saturn](https://github.com/Stellarium/stellarium/assets/140850696/084b1660-efc5-44a4-a242-10327e66f3a0)

### System
* Stellarium version: <stellarium-23.3-qt6-win64>
* Operating system: <Windows 11 Pro, Version 22H2, OS Build 22621.2715>
* Computer: Thinkpad TPX390 Yoga
* Processor: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz   2.11 GHz; 16GB RAM
* Graphics Card: <Intel(R) UHD Graphics 620; Driver Date: 2021-12-23, Driver version: 30.0.101.1218>

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/13397318/log.txt)

**Comment by gzotti** [comment]
Cannot reproduce that. The logfile may contain info about shader problems.
Test MESA mode for (slow but hopefully working) graphics. If problem persists, try Qt5-based version and ANGLE mode.

**Comment by SusanSSB** [comment]
I tried the MESA Mode and the problem still persists. I am sorry, I don't understand what you mean by the Qt5-based. Please explain. Thank you.

**Comment by gzotti** [comment]
Go to stellarium.org and see the link (further down) "all releases". Here you can find a stellarium 23.3 64bit Qt5-based. However, your logfile does not show a shader error. Is Saturn the only missing planet? Or is Uranus also missing (close to Jupiter)?

**Comment by 10110111** [comment]
Does Saturn not appear even if you zoom closely (to about 0.03° FoV)?

**Comment by SusanSSB** [comment]
gzotti, Uranus is missing, too... :-(

Neither Saturn nor Uranus show, even when zoomed in to a maximum of FOV of 0.00139 degrees.

I even uninstalled the software, did a reboot, reinstalled the stellarium 23.3 64bit Qt6-based software and it is still missing these two planets. :-( (sigh)

I will uninstall stellarium 23.3 64bit Qt6-based version, reboot my computer and then install the stellarium 23.3 64bit Qt5-based software (I finally found it on the website). I will let you know what I find... Stay tuned.

**Comment by gzotti** [comment]
No need to reboot. Just that both Saturn and Uranus have rings, so this is a first hint where to look for issues. I have not seen issues on that for years, though.

**Comment by SusanSSB** [comment]
I installed the stellarium 23.3 64bit Qt5-based version and tried it. The problem with the missing Saturn and Uranus seems to have been resolved, but another issue has arisen. 

I have tried all the modes and only one mode, Angle Mode; 75% Scale, works correctly, using the settings retained in the User config.ini file (see following screenshot).
![AngleMode75%](https://github.com/Stellarium/stellarium/assets/140850696/5d3d6f2d-e583-473f-99e6-6e2697390df5)

Mesa Mode opens a black window (see following screenshot).
![Mesa Mode](https://github.com/Stellarium/stellarium/assets/140850696/44bbaa4a-a4e9-4add-aa31-37d3346f2961)

Angle Mode (and all the others) opens Stellarium ignoring the settings in the config.ini file and instead uses the original "default" settings (see following screenshot). The default settings are less than desirable. This view was created with Angle  Mode.
![AngleMode(user config not used)](https://github.com/Stellarium/stellarium/assets/140850696/3770d47c-cb30-400c-a270-069c7957009c)

...And this view was created with Angle Direct 3D 11 Mode (whatever that means)
![Angle Direct3D11Mode](https://github.com/Stellarium/stellarium/assets/140850696/0aec85d0-7209-4b0b-b6db-6809ba283caa)

Here is the log file...
[log.txt](https://github.com/Stellarium/stellarium/files/13398652/log.txt)

I spent a lot of time customizing the settings in Stellarium (i.e., colors, line thickness, font size, etc.) to get just the right look, Now, I don't know what I am going to do.  I am considering to go back and try the stellarium-1.1.1-qt5-win64 version... The version I had tried before was the 1.1.1-qt6-win64 version... I need to get the presentation done...

Let me know if you require further information.

**Comment by SusanSSB** [comment]
Okay, this gets stranger and stranger... I installed Stellarium and reinstalled version stellarium-23.2-qt5-win64. When I start Stellarium in Angle mode, with a date of 2023-11-17 and time 21:0:39, Saturn is present as demonstrated in the following screenshot.
![Saturn Visible](https://github.com/Stellarium/stellarium/assets/140850696/46624e3a-88aa-4cad-a42a-913f4e4580e3)

Now if I change the date to 2023-11-19, Saturn disappears, as demonstrated  in the following screenshot. 
![Saturn Disappeared](https://github.com/Stellarium/stellarium/assets/140850696/bda36321-edda-42ad-b002-04a5efc03771)

Now that shouldn't happen. Here is the last log file. 
[log.txt](https://github.com/Stellarium/stellarium/files/13398797/log.txt)

I hope you can tell me what is going on .... Thank you.

**Comment by gzotti** [comment]
I just saw you were using 23.2. Not sure if it makes a difference, can you upgrade to 23.3/Qt5? 
The last log was also "normal" OpenGL mode, not ANGLE mode. 
Other than that, I can only confirm this is weird.

**Comment by SusanSSB** [comment]
Georg, thank you for your assistance with this issue. I did try version 23.3/Qt5 and it was doing the same thing, so I uninstalled it and then installed 23.2/Qt5 to see if it did the same thing (I figured, "What the heck"). Now I am wondering if there is something "corrupted" in my config.ini file. I am thinking of deleting the config.ini file and starting up Stellarium to create a new one with default settings. But before I do that, are there any precautions I should take so I don't inadvertently lose, for example, the informations in my data, landscapes, modules or stars folders? Or should I be, first, looking at the config.ini file to see if there is anything anomalous going on? I don't have a strong background in computer "coding" and the like (but I am an engineer), so any advice/guidance would be appreciated. I saved the latest version of my config.ini file as a text file,so I could enclose it as a file attachment (see below). Could you please have a look at it to see if there is anything weird about it?
[config_ini_2023_11_22.txt](https://github.com/Stellarium/stellarium/files/13442901/config_ini_2023_11_22.txt)

**Comment by 10110111** [comment]
I can reproduce the problem with your config file, and if I disable SSO magnitude limit, Saturn re-appears.

**Comment by SusanSSB** [comment]
Thank you, Ruslan! That helps me big time, but I feel a little foolish ;-)... It just goes to show how much more I still have to learn about Stellarium (sigh)... I went into the Sky and viewing options window, and in the SSO tab, unselected, "Limit magnitude" and  adjusted the "Labels and Markers" slider a bit and, voila, the planets were all showing up on the chart.

I still have to figure out why:

1. when I open Stellarium using the Mesa Mode option, it opens as a totally blank,  **BLACK** window; and 
2. when the Angle Mode Option is used, Stellarium opens but **without** using the customized format settings (i.e., colors, line thickness, font size, etc.) retained in the user config.ini file; it instead uses, what I presume, are the Stellarium "default" settings, as I pointed out in one of my previous messages (see https://github.com/Stellarium/stellarium/issues/3513#issuecomment-1817318943).

**Comment by 10110111** [comment]
> when I open Stellarium using the Mesa Mode option, it opens as a totally blank, BLACK window

This is a good question, especially since Mesa is used as a fail-safe mode, but I don't have Windows to test.

> when the Angle Mode Option is used, Stellarium opens but without using the customized format settings (i.e., colors, line thickness, font size, etc.) retained in the user config.ini file

You can check which file is being used in each run via _Help_ (<kbd>F1</kbd>) → _Config_. From your description these might be different for some reason (and when judging this, beware of WoW64 paths redirection).

**Comment by SusanSSB** [comment]
I just ran Stellarium first using, "Angle Mode; scale 75%" and then "Angle Mode", and checked _Help > Config_ for each run. They both use the same config file path, "C:\\Users\\susan\\AppData\\Roaming\\Stellarium\\config.ini". I looked at the log files for each run and noticed the following, "_Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing._" Could this be relevant to the issues I am having? When I customized the format settings (i.e., colors, line thickness, font size, etc.), I was using much earlier version of Stellarium, either V0.22.2 or V1.1... Your feedback is appreciated.

**Comment by 10110111** [comment]
> "Angle Mode; scale 75%" and then "Angle Mode"

These should only differ in font sizes and line thicknesses, because the scale applies to them. The colors should be the same. Also, the effect of scaling will be different between Qt5- and Qt6-based versions due to the differences in behavior of Qt.

> "Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing."

This is generally harmless.

**Comment by gzotti** [comment]
As far as I remember ANGLE does not support line thickness, so this would be normal. Color should work.

I think we have targeted black MESA window in 23.3 or just days after release, so current beta should not be affected.

@10110111 The message about default format may be harmless, however we might want to fix the cause for this sometime. Where (very early) can format setting take place to suppress this warning?

However, if the actual problem was a too bright user-defined planet magnitude limit, this is solved, right?

**Comment by SusanSSB** [comment]
Yes, the problem with the "disappearing" planets has been resolved. I realize the problem I was having was largely "self-inflicted" (sigh). Thank you for all your help.
