### ISSUE TITLE
Artificial satellites 

### ISSUE THREAD

**Issue by ShineOnUCrazyDiamond** [Stellarium/stellarium#3517]
Good morning,
my question is: are the speed data and position of artificial satellites in live? Is it the same on mobile and on computer? Can we observe the real artificial satellite trajectory?
Thank you for your attention,
Have a good day.

ps: je suis pas contre une réponse en français 😅

**Comment by alex-w** [comment]
Yes, when TLE are actual

**Comment by gzotti** [comment]
We can only discuss the Desktop version here. When satellite elements are up-to-date, positions should be accurate.

**Comment by ShineOnUCrazyDiamond** [comment]
However, in the data credits there is no mention of satellite data, which makes me ask the question, how can they know in reality and in advance the trajectory of the satellites?

**Comment by gzotti** [comment]
who are "they"?

**Comment by ShineOnUCrazyDiamond** [comment]
Well, sorry for my English and my lack of knowledge in application creation. I suppose I meant the people who enter the data into the application, the engineers? are you this engineers? or a user like me who gives his opinion?Thank uLe 21 nov. 2023 à 15:52, Georg Zotti ***@***.***> a écrit :﻿
who are "they"?

**Comment by ShineOnUCrazyDiamond** [comment]
Ok, thank u very muchBonne soirée Le 21 nov. 2023 à 18:09, Ruslan Kabatsayev ***@***.***> a écrit :﻿

are the speed data and position of artificial satellites in live?

They are not streamed from anywhere, instead they are extrapolated from predefined parameters that are updated from the web once in a while (see Artificial Satellites settings).

Is it the same on mobile and on computer?

The applications are unrelated, so we can't tell exactly.

Can we observe the real artificial satellite trajectory?

I don't think so.

are you this engineers? or a user like me who gives his opinion?

So far everyone who replied to you was an engineer.

**Comment by gzotti** [comment]
The plugin documentation in the desktop program provides author information. The original authors are no longer involved, but we try our best to keep it running. And the Stellarium User Guide also answers many questions.

**Comment by gzotti** [comment]
I consider this answered.
