### ISSUE TITLE
Belt of Venus and Earth's shadow

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#352]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1106773

This is feature request from old bug tracker.

Just after sunset in the east or just before sunrise in the west, you should see a segment of the Earth's shadow on the horizon below a pinkish band of light known as the "Belt of Venus."

http://en.wikipedia.org/wiki/Belt_of_Venus

Can you make this visible in Stellarium?

**Comment by alex-w** [comment]
A paper has appeared: https://www.usna.edu/Users/oceano/raylee/papers/RLee_AO_BOV_paper_2015.pdf

**Comment by gzotti** [comment]
#624 will hopefully solve this. The preview is amazing!

**Comment by adrian16724** [comment]
hello gzotti

**Comment by adrian16724** [comment]
i ii make it work myself

**Comment by adrian16724** [comment]
how do i create a file on github for stellarium i m working myself

**Comment by gzotti** [comment]
Follow the information in the wiki, and follow information about git usage widely available elsewhere. 

In case you are the one who has shown up under other identities at least twice already: We will lock also this conversation if we can foresee the same style of messages.

**Comment by adrian16724** [comment]
> Follow the information in the wiki, and follow information about git usage widely available elsewhere.
> 
> In case you are the one who has shown up under other identities at least twice already: We will lock also this conversation if we can foresee the same style of messages.

redirect me to wiki please friend

**Comment by adrian16724** [comment]
hello georg good afternoon

**Comment by alex-w** [comment]
Please review this issue again due to changes in the code for the atmosphere

**Comment by gzotti** [comment]
Indeed solved by #624.
