### ISSUE TITLE
Mars equinox sun rise position moves along the Zodiac from 2021 CE between Sagittarius and Scorpio to between Scorpio and Libra in 14000 CE

### ISSUE THREAD

**Issue by isenberg** [Stellarium/stellarium#3528]
### Expected Behaviour
With the current standard model implemented in Stellarium without precession of the Mars rotational axis, no movement of the sun rise location during equinox morning against the background stars is expected.

### Actual Behaviour
Visible sun rise location against the background at equinox on Mars, sun rises exactly at 90°:
2021-02-07 Sagittarius / Scorpio (matches actual real observation, https://ops-alaska.com/time/gangale_mst/VernalEquinox.htm)
5000-05-26 Scorpio
14000-04-28 Scorpio / Libra

### Steps to reproduce
Install Stellarium release, set location to Perseverance, Mars, change dates to list above and adjust time to see the sun on the horizon.

### System
* Stellarium version: 23.3
* Operating system: macOS

**Comment by gzotti** [comment]
Why do you think Mars should not show precessional motion?

**Comment by isenberg** [comment]
I was actual working right now to add some experimental precession to Mars and saw all those notes in the code that only to  Earth precession transformation is applied in Stellarium. That's the reason for my bug report as it looks unexpected from reading the code. 

Or is the Mars axis precession read from the SPICE file and just some additional precession calculation for Earth is special there? Then my bug report is invalid.

**Comment by isenberg** [comment]
setting to invalid as my observation on the tested dates matches the 179_600 Earth-years cycle of Mars: https://en.wikipedia.org/wiki/Astronomy_on_Mars#Long-term_variations

That means the Mars axial wobble is apparently read from the ephemerides.

**Comment by isenberg** [comment]
invalid bug

**Comment by gzotti** [comment]
Please read section F.6 of the User Guide for clarity.
