### ISSUE TITLE
F-Droid version

### ISSUE THREAD

**Issue by GuiSousa135** [Stellarium/stellarium#3540]
**A Stellarium F-Droid version**

**Comment by gzotti** [comment]
Look into #194. The three core developers have no time to create a small-screen compatible new GUI just for fun. This here is a desktop project with (preferentially) keyboard/mouse control. If you want a full *droid version, you must become active yourself.

**Comment by rugk** [comment]
Hmm AFAIK a mobile version exists (now?)?

https://www.stellarium-labs.com/stellarium-mobile-plus/

So I guess I make a new issue.
