### ISSUE TITLE
Plugin for Wikipedia

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#355]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1274458

Copy from here: https://sourceforge.net/p/stellarium/discussion/278769/thread/bb37f777/

Hi guys

I'm new in the world of astronomy but learned about stellarium a few years ago. I can probably point out nothing in the sky so for me stellarium is more of an educational and learning tool rather than a sky map tool.

So from that educational/selfhelp angle I was wondering:
 - Is it possible to have a wikipedia plugin, so that when you click on a star/object you dont only get the sinbad numbers but can also read what wiki says about it. Of course it wont have entries for even a tiny fraction of the stars out there but I'm thinking that it can become a powerful tool if you combine it with scripting and taking people for various tours.

**Comment by gzotti** [comment]
It is moderately easy to just open a wikipedia page in the system's webbrowser on the name of the selected object. However, there is no guarantee that an article exists. It also appears unsuited to present or further process the result in the application, so the call to the external webbrowser seems best.
