### ISSUE TITLE
Some stars belong to more than one constellation, is that ok?

### ISSUE THREAD

**Issue by PurrProof** [Stellarium/stellarium#3555]
Stars with ids 677, 31685, 39429, 25428 belong to more than 1 constellation.

I checked file
https://github.com/Stellarium/stellarium/blob/master/skycultures/modern/constellationship.fab, and also the version from modern_st dir.

**Comment by gzotti** [comment]
Stars can only belong to one IAU constellation (defined as region in the sky). However, the historical figures were originally overlapping, and yes, some stars may be part of more than one figure.
