### ISSUE TITLE
Orientation of Jupiter, Uranus and Venus may be incorrect or displaying az/alt wrong

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#357]
_Original report by Steve:_ https://bugs.launchpad.net/stellarium/+bug/1637417

If you look at this webpage
http://aa.quae.nl/en/reken/zonpositie.html
There is a table under section "15. Comparison with planetary programs" (In middle of the page)which shows comparisons for the azimuth and h altitudes between diff programs.
I went through both tables and noticed Venus, Uranus and Jupiter for stellarium 0.15 varied largly from results of what other programs were showing which generally matched each other by about a degree or 180deg which was predictable.
I verified that stelarium .15 showed the results the table showed.

I also noticed when comparing Jupiter Az/alt from version.14.2 Stellarium and .15 stellarium the results were different for az/alt which seemed odd given that other planets matched between version .14.2 and .15
So it could be just a az/alt info display error or something more serious.

**Comment by gzotti** [comment]
The table is matched pretty close now, sub-degree differences hopefully only come from refined models. 
For Jupiter, rotation rate is a bit difficult. We can easily stick to system II, but this would bring the GRS out of sync with reality, so we adjust the rotation artificially.
