### ISSUE TITLE
Fault to render on secondary Hdpi (4K) monitor

### ISSUE THREAD

**Issue by Franco-64** [Stellarium/stellarium#3573]
Hi, after a fresh installation and a change of some line in [video] section of config.ini, Stellarium opens correctly in the secondary 4K display, at full screen. But the planetary image occupies only a section of the screen (see image). It seems also that the selection of sky objects in misaligned with what I see in monitor (I can click and have some results in the black area), as the app sees "internally" as the visualization was in full screen. No change after i pressed F11 twice.

This is my video section of config.ini:

[video]
dithering_mode = color888
fullscreen = false
maximum_fps = 10000
minimum_fps = 18
screen_h = 2160
screen_number = 1
screen_w = 3840
screen_x = 0
screen_y = 0
tm_display_adaptation_luminance = 50
viewport_effect = none

### Expected Behaviour
Rendering full screen

### Actual Behaviour
<img width="1919" alt="stellarium" src="https://github.com/Stellarium/stellarium/assets/154953541/87d32738-9cb8-4745-87f8-6d1308b19dc7">

### Steps to reproduce
After a fresh installation of latest stable version (stellarium-23.4-qt5-win64.exe)

### System
* Stellarium version: stellarium-23.4-qt5-win64.exe
* Operating system: Windows 11 Version 22H2
* Graphics Card: Intel Iris Plus, OpenGL 4.6
* Screen type: Philips PHL276E8V at 3840x2160

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/13776231/log.txt)

**Comment by 10110111** [comment]
Does this still happen if you disable HiDPI scaling?

**Comment by Franco-64** [comment]
It depends. I use 200% scaling on 4K monitor for best viewing of menu and windows, and the behavior is uncorrect as described. If I use 150% or less, is OK. With a scale of 175% or more, the issue reappers.

Issue is present in both case: if I launch the app after rescaling, and i I rescale when Stellarium is open.

**Comment by 10110111** [comment]
Does this happen in previous versions of Stellarium, like 23.2 and 23.3?
