### ISSUE TITLE
Many Missing Stars With All Catalogs Installed

### ISSUE THREAD

**Issue by atcz** [Stellarium/stellarium#3575]
### Expected Behaviour
With all star catalogs installed, there should be no missing stars in the magnitude 9-13 range.

### Actual Behaviour
Many stars are missing from the Stellarium display when compared to the DSS colored display (Ctrl+Alt+D).  I found 5 missing stars in the vicinity of M10, and there are many more in this area.  I also found more around M107.

This is the Stellarium display with the missing star locations marked, HIP 82905 is at the bottom right:
![MissingStars](https://github.com/Stellarium/stellarium/assets/86995996/1e24fe9d-098e-4252-a862-723d0c94b398)

Here is with DSS colored turned on:
![MissingStarsDSS](https://github.com/Stellarium/stellarium/assets/86995996/f89fb7f4-6a14-4162-8d34-c93485363985)

This is the data for the missing stars:
-1 
At coords (J2000.0) 16:55:58.5393377640 -04:06:35.657424252:
Object: AKARI-IRC-V1 J1655585-040635 (Long-Period Variable Candidate)
Distance from query: 47.20 arcsec
Other Identifiers:
 - AKARI-IRC-V1 J1655585-040635                       
 - Cl* NGC 6254    CGW      72                        
 - IRAS 16533-0401                                    
 - 2MASS J16555855-0406355                            
 - TIC 157963127                                      
 - Gaia DR3 4365631984908750336                       
 - Gaia DR2 4365631984908750336                       
Information from catalog: Gaia
Gaia DR2 
Magnitude G: 9.309
Colour index B-V: 1.79
Magnitude BP: 11.552
Magnitude RP: 7.980
Visual magnitude: 9.68

-2
At coords (J2000.0) 16:56:01.1270029224 -04:13:40.643294196:
Object: Cl* NGC 6254    CGW      73 (Long-Period Variable Candidate)
Distance from query: 23.43 arcsec
Other Identifiers:
 - Cl* NGC 6254    CGW      73                        
 - 2MASS J16560112-0413406                            
 - TIC 157963238                                      
 - Gaia DR3 4365625868875307648                       
 - Gaia DR2 4365625868875307648                       
Information from catalog: Gaia
Gaia DR2 
Magnitude G: 11.094
Colour index B-V: 1.42
Magnitude BP: 12.749
Magnitude RP: 9.906
Visual magnitude: 11.4

-3
At coords (J2000.0) 16:55:05.4628980672 -04:10:58.570162644:
Object: UCAC4 430-066293 (Star)
Distance from query: 12.62 arcsec
Other Identifiers:
 - UCAC4 430-066293                                   
 - AP J16550546-0410585                               
 - DENIS J165505.4-041058                             
 - 2MASS J16550546-0410585                            
 - RAVE J165505.5-041059                              
 - TIC 157900425                                      
 - USNO-B1.0 0858-00297800                            
 - Gaia DR3 4377545876286912896                       
 - Gaia DR2 4377545876286912896                       
Information from catalog: Gaia
Gaia DR2 
Magnitude G: 11.348
Colour index B-V: 1.2
Magnitude BP: 11.955
Magnitude RP: 10.565
Visual magnitude: 11.71

-4
At coords (J2000.0) 16:55:11.1816127282 -04:12:57.210475528:
Object: UCAC4 429-065370 (Star)
Distance from query: 19.19 arcsec
Other Identifiers:
 - UCAC4 429-065370                                   
 - AP J16551117-0412572                               
 - 2MASS J16551117-0412572                            
 - TIC 157900450                                      
 - Gaia DR3 4365535949433713024                       
Information from catalog: Gaia
Gaia DR2 
Magnitude G: 12.157
Colour index B-V: 1.26
Magnitude BP: 12.832
Magnitude RP: 11.378
Visual magnitude: 12.55

-5
At coords (J2000.0) 16:55:30.9168274224 -04:15:40.735742184:
Object: Cl* NGC 6254    CGW      38 (Star)
Distance from query: 55.23 arcsec
Other Identifiers:
 - Cl* NGC 6254    CGW      38                        
 - 2MASS J16553091-0415407                            
 - TIC 157903632                                      
 - Gaia DR3 4365534712483091840                       
 - Gaia DR2 4365534712483091840                       
Information from catalog: Gaia
Gaia DR2 
Magnitude G: 12.912
Colour index B-V: 0.7
Magnitude BP: 13.261
Magnitude RP: 12.390
Visual magnitude: 13.07

### Steps to reproduce
Select DSS colored in "Surveys" and compare the display with the HPS button selected and de-selected.

### System
* Stellarium version: stellarium-23.3-qt5-win64.exe 
* Operating system: Windows 10 Pro 22H2
* Graphics Card: Nvidia RTX 3070 verion 545.84
* Screen type (if applicable): N/A

**Comment by gzotti** [comment]
Catalogs tend to be incomplete. Therefore there is the DSS layer in the first place...
