### ISSUE TITLE
Incorrect coordinates of Phoenix Dwarf Galaxy in Stellarium

### ISSUE THREAD

**Issue by Minusman666** [Stellarium/stellarium#3576]
Hello everyone, it seems that the coordinates of Phoenix Dwarf Galaxy are wrong in Stellarium. If you select Phoenix Dwarf Galaxy under F3 Search, a rather empty area of the Phoenix constellation is displayed (see screenshot).
![Screenshot (141)](https://github.com/Stellarium/stellarium/assets/114421887/9f141229-b879-4f28-bab4-01ff3c058e0d)
The next screenshot shows the correct coordinates.
![Screenshot (142)](https://github.com/Stellarium/stellarium/assets/114421887/0d351778-dd06-450a-9c3c-515d1103a976)

With kind regards.

### System
* Stellarium version: v23.04.0
* Operating system: Windows 11 Version 23H2
* Graphics Card: NVIDIA GeForce GTX 1070/PCIe/SSE2  Driver: NVIDIA 546.33
* Screen type Acer S277HK: Resolution, 3840 x 2160 60Hz Scaling: 150%

**Comment by gzotti** [comment]
Ideed a typo. If you want, follow instructions in User Guide 8.1. Copy C:\Program Files\Stellarium\nebulae\default\catalog.txt into USER_DIR/nebulae/default.  
Edit the line 79 starting with numbered entry 29. Change first data value from 7 to 27 as shown.

> 29	**2**7.7750 	-44.4447	13.08	13.2	AGx	dI/dGsp ...


Create empty file catalog.pack in the same dir, run Stellarium once, then gzip it.
