### ISSUE TITLE
Provide a "dim slider"

### ISSUE THREAD

**Issue by sjvudp** [Stellarium/stellarium#3577]
**Is your feature request related to a problem? Please describe.**
In early evening there was mainly one bright object (Jupiter) visible, and a few others.
Opening Stellarium showed quite a lot of objects, most of them not being visible (due to lack of darkness).
**Describe the solution you'd like**
If there were a slider to dim (i.e.: "hide") the lesser-bright stars, one could try to match more easily what actually can be seen.

**Describe alternatives you've considered**
Trying to match real view and Stellarium screen visually.

**Additional context**
Here is a "gained up" version of the photo showing the situation:

![IMG20231230172338-SGU](https://github.com/Stellarium/stellarium/assets/6734808/46ced094-6c02-49ec-b289-2af3eb1fe199)

See also https://astronomy.stackexchange.com/q/55643/48933

**Comment by gzotti** [comment]
Generally Stellarium tries to simulate glare and brightening up of the sky. If that still is not enough, just turn up light pollution to get a three-star sky.

**Comment by sjvudp** [comment]
> Generally Stellarium tries to simulate glare and brightening up of the sky. If that still is not enough, just turn up light pollution to get a three-star sky.

Honestly I wasn't aware of those, but when checking it seems those are only available in the "Stellarium Plus" version. I almost think one should get bad viewing conditions for free ;-)

**Comment by gzotti** [comment]
Stellarium Plus is a smartphone app. This site discusses the desktop version only.

**Comment by sjvudp** [comment]
> Stellarium Plus is a smartphone app. This site discusses the desktop version only.

Oops, I did not know, sorry. Maybe add a note to the site README.

**Comment by xalioth** [comment]
Hi, actually there is already such a feature in Stellarium Mobile, it's in the advanced settings: a brightness slider allows to do just what you request. hope it helps!
