### ISSUE TITLE
How to select single stars in M29?

### ISSUE THREAD

**Issue by Dilbflo** [Stellarium/stellarium#3580]
Hi all.
I am following a course of the Open University about Astronomy. They use Stellarium as main software planetarium. At a certain point they ask to analyze the magnitude of the main stars in M29. I am able to find M29, but when I click on the single stars I can't pick nothing, as if there is only an image and not the single stars. I am missing something?
(I use Stellarium 23.4 with Windows 10).
Thanks.

**Comment by gzotti** [comment]
It may help to switch off DSO symbols, DSO images and aberration.

**Comment by 10110111** [comment]
Try adding extra star catalogs from _Configuration_ → _Extras_ → _Star catalog updates_. By default, when no extra catalogs are enabled, there are indeed only a few stars clickable in M29, all the others being only in the DSO image.

**Comment by Dilbflo** [comment]
Thanks all. With your suggestions and a bit of trial and error I was able to select single stars in M29. I am quite new to Stellarium, so the orientation among the various layers, catalogs and visualization options is not easy at first.
![Stellarium M29 Star](https://github.com/Stellarium/stellarium/assets/98282897/1eb439b0-ab6f-4834-9ccc-4593b6919102)

**Comment by Dilbflo** [comment]
Thanks all. With your suggestions and a bit of trial and error I was able to select single stars in M29. I am quite new to Stellarium, so the orientation among the various layers, catalogs and visualization options is not easy at first.

![Stellarium M29 Star](https://github.com/Stellarium/stellarium/assets/98282897/4bb86553-65dd-48ea-ae0c-9450b570d368)
