### ISSUE TITLE
import issue [observing lists]

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3586]
### Actual Behaviour
Describe or maybe attach a screenshot?

### Steps to reproduce

1. open observing lists dialog
2. open import dialog
3. make sure to filter for *.json
4. import attached JSON file [2024-ssb.json](https://github.com/Stellarium/stellarium/files/13888446/2024-ssb.json)
5. **BUG: observe that some comets are not imported**

### System
* Stellarium version: Version 24.4.8-0de39da [master] Based on Qt 5.12.8
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-169-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/13888493/log.txt)

**Comment by alex-w** [comment]
Please attach your `ssystem_minor.ini` file, because in my environment the 3 lines are missing, but this is OK - no objects, no import.

**Comment by axd1967** [comment]
[ssystem_minor.ini.txt](https://github.com/Stellarium/stellarium/files/13888949/ssystem_minor.ini.txt)

that could explain it, even if it's conceptually not OK. in such a case, **at least a warning should be issued** for the missing objects. the user should be able to import the missing objects, even if this is a drag.

## WORKAROUND
Before importing a bookmark file, ensure all objects have prior been imported via the SSB editor. This is not workable for large files, but OTOH it is a temporary issue.

**Comment by gzotti** [comment]
It is only a bug if objects existing in ssystem_minor.ini are not found. Else it is expected that imported lists have been exported from a fully compatible program. 

The message in the logfile could be expanded to echo the inconvertible passage. Else, I disagree yet another time about having to automatically import missing objects via SSE plugin first. This only makes things more complicated. If an object is not found, a popup window could be shown. OTOH, if you create a bookmark file with 2000 asteroids, then delete the ssystem_minor.ini and try to import the bookmark file, you will have to acknowledge 2000 "object not found: XY" popups. Not what I want. The only change could be
 
* echo the bad section to logfile to know which object gives trouble. Avoid same error message at two even closely related places in code. 
* Show generalized popup warning "There were errors. See logfile".

**Comment by alex-w** [comment]
> It is only a bug if objects existing in ssystem_minor.ini are not found. Else it is expected that imported lists have been exported from a fully compatible program.

Please try use attached files - I can confirm the issue in linux

**Comment by gzotti** [comment]
The problem is that a legacy bookmarks file is being loaded. We have extended the bookmarks feature into observing lists, but did not remove the code to load 2020-style bookmarks before going 1.0. Actually, after loading, for a last time after upgrading from 0.20 or so, some old bookmarks should be imported as first observing list, and users would never go back to the old format. In a perfect world, users would load only real obslists after 2021, and we could remove that compatibility code which may indeed be broken for some reason.

**Comment by gzotti** [comment]
OMG, that was really messed up. We have list names and OLUD. Duplicate names broke the entire list system. I hope this is OK now.
