### ISSUE TITLE
odd canceling workflow [observing lists]

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3587]
### Expected Behaviour

When canceling an action, no error message should be issued.

### Actual Behaviour
Error message given although the user didn't do anything wrong.

### Steps to reproduce

1. delete a  list; click NO
10. BUG: odd error message "you cannot delete the default or last list". this indicates oddities in the user action canceling logic. Why can't "the last list" be deleted? 
11. similarly, when canceling an export action, Stellarium says "Error: Cannot export"; this is unnecessary and confusing.

### System

* Stellarium version:  Version 24.4.8-0de39da [master] Based on Qt 5.12.8

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
1: ACK
2: The last list and the default list cannot be deleted because there must be at least one list, and the default list is delete-protected. No bug, this is intentional.
3: ACK.
