### ISSUE TITLE
Can't load satellites

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#3588]
### Expected Behaviour
Stellarium loads all satellites.

### Actual Behaviour
log.txt contains this and 21 other similair lines to other satellites.

[Satellites] FAILED to download "http://www.celestrak.org/NORAD/elements/noaa.txt" Error: "Error transferring http://www.celestrak.org/NORAD/elements/noaa.txt - server replied: Not Found"

I tried to get data with browser and the address below worked.

https://celestrak.org/NORAD/elements/gp.php?GROUP=noaa&FORMAT=tle

So, I think that Celestrak has changed their system.

### Steps to reproduce
1. Start Stellarium

### System
* Stellarium version: <Stellarium 24.0+ (Version 24.0.10-c422498 [master]>
* Operating system: <Kubuntu 23.10>
* Graphics Card: <MSI GeForce GT 1030/PCIe/SSE2 2GH LF OC, OpenGL 3.3, driver 3.3.0 NVIDIA 525.147.05>
* Screen type LG 34GK950F 3440x1440

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/13894125/log.txt)

**Comment by alex-w** [comment]
By the fact the fix is included in last 2 versions already - please try use “reset” button in Sources tab of plugin

**Comment by ilkant** [comment]
Thanks!
