### ISSUE TITLE
Stellarium 23.4.0 Qt6.5.3 Win64 freezes after opening

### ISSUE THREAD

**Issue by Regulus-mj94** [Stellarium/stellarium#3590]
After installing the latest version (23.4.0 Qt6.5.3 Win64) yesterday, Stellarium freezes after opening.
I can only see that the fps is about 0.02! CPU usage has also increase to 50%. By running the MESA mode, things get better a bit and the fps rise to 5.
Uninstalling and reinstalling made no difference.
The previous version that was installed on my PC was 23.2 Qt6 and it ran without any issue.

![Screenshot 2024-01-13 182343](https://github.com/Stellarium/stellarium/assets/84971633/ed2a0db6-fcd6-48fd-bf96-feb48f8180e3)

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/13928780/log.txt)

**Comment by gzotti** [comment]
Uninstalling and reinstalling rarely makes a difference. 
You are running an officially unsupported Win11 on a 3rd-gen Core i5 with a pretty old Geforce card. Make sure you have the latest drivers from NVidia. This can make a difference.

**Comment by 10110111** [comment]
Try using `--opengl-compat` command-line option for Stellarium.

**Comment by Regulus-mj94** [comment]
> Uninstalling and reinstalling rarely makes a difference. You are running an officially unsupported Win11 on a 3rd-gen Core i5 with a pretty old Geforce card. Make sure you have the latest drivers from NVidia. This can make a difference.

I have the latest driver.
Can testing beta versions help identify the problem?

**Comment by Regulus-mj94** [comment]
> Try using `--opengl-compat` command-line option for Stellarium.

how should I try this?

**Comment by 10110111** [comment]
> Can testing beta versions help identify the problem?

Beta versions of the driver? I think your GPU is no longer supported by NVIDIA (on any OS of any version), so you'll most likely not find any beta driver.

> how should I try this?

You can edit your Stellarium shortcut, adding the option to the command line field (separating it by a space from others if any).

**Comment by Regulus-mj94** [comment]
> 
> Beta versions of the driver? I think your GPU is no longer supported by NVIDIA (on any OS of any version), so you'll most likely not find any beta driver.

I thought Stellarium had a beta or weekly release.
 
> You can edit your Stellarium shortcut, adding the option to the command line field (separating it by a space from others if any).

I still couldn't figure out.
Should I open  cmd and call the program shortcut and enter this command? 🤷‍♂️

**Comment by 10110111** [comment]
> I still couldn't figure out.

https://www.digitalcitizen.life/shortcut-arguments-parameters-windows/

**Comment by Regulus-mj94** [comment]
>
> https://www.digitalcitizen.life/shortcut-arguments-parameters-windows/

Running with --opengl-compat didn't make difference.
then i tried combo of --mesa-mode --dump-opengl-details and this is the log file:
[log.txt](https://github.com/Stellarium/stellarium/files/13932991/log.txt)


I found that by turning landscape and atmosphere off, fps rise to around 27. (5 fps in MESA mode when both turned on)

**Comment by 10110111** [comment]
> I found that by turning landscape and atmosphere off, fps rise to around 27.

What was the frame rate in 23.2? Does the problem also happen in 23.3?
What changes if you enable atmosphere or landscape but not both?

**Comment by Regulus-mj94** [comment]
> What was the frame rate in 23.2? Does the problem also happen in 23.3? What changes if you enable atmosphere or landscape but not both?

I don't remember the exact number, but it worked smoothly without freezing or lagging.
I will reinstall 23.2 tomorrow and check the fps. I'll also get a logfile from it to compare with 23.4.
>What changes if you enable atmosphere or landscape but not both?

Lanscape On + Atmosphere On = 5 fps
Landscape Off + Atmosphere On = 24 fps
Landscape On + Atmosphere Off = 9 fps
Landscape Off + Atmosphere Off = 30 fps

**Comment by gzotti** [comment]
@10110111 did you see the shader warning in the very first logfile? Is that something in either the smoothed-out (fragment shader filled) landscape, or the new transparency?
@Regulus-mj94 please also attach the logfiles in the further tests.

**Comment by 10110111** [comment]
> did you see the shader warning in the very first logfile?

It's wrong, the variable is written to in all if-else branches.

@Regulus-mj94 Please post the log when using `--opengl-compat`.

**Comment by 10110111** [comment]
Also, does the performance improve if you switch landscape to e.g. Mars or Grossmugl?

**Comment by Regulus-mj94** [comment]
Here are the logfiles of runing stellarium in different conditions:
### 23.4 + --opengl-compat:
[log 23.4 --opengl-compat.txt](https://github.com/Stellarium/stellarium/files/13940428/log.23.4.--opengl-compat.txt)

### 23.2 normal:
[log 23.2 normal.txt](https://github.com/Stellarium/stellarium/files/13940425/log.23.2.normal.txt)

### 23.2 + --opengl-compat:
[log 23.2 --opengl-compat.txt](https://github.com/Stellarium/stellarium/files/13940431/log.23.2.--opengl-compat.txt)

I also tested switching different landscapes in 23.4 (MESA) and 23.2 (Normal, MESA, opengl). In 23.4 without switching landscape and atmosphere off, landscapes Garching, Guéreins, Hurricane and Ocean run at 5 fps while others run at 15 fps. In 23.2 (normal mode) every terrestrial landscapes run at 20 fps and other planets landscapes run at 30 fps. (except Sun that run at 20 fps)

**Comment by 10110111** [comment]
OK, this makes sense. I think I'll add a new switch to force low-graphics mode even when OpenGL 3.3 Compatibility profile is available. With it you'll lose dithering and ShowMySky atmosphere, but gain performance.

**Comment by Regulus-mj94** [comment]
> OK, this makes sense. I think I'll add a new switch to force low-graphics mode even when OpenGL 3.3 Compatibility profile is available. With it you'll lose dithering and ShowMySky atmosphere, but gain performance.

What caused the performance to drop from 23.2 to 23.4?
Is it due to using a newer version of opengl in 23.4 (which my graphics card doesn't support)?
ShowMySky was slow on 23.2 on my PC but at least it worked, am I missing it completely with your solution?
And, when will this change be implemented?

**Comment by 10110111** [comment]
> What caused the performance to drop from 23.2 to 23.4?

There were some changes in the way the scene (and landscapes in particular) is rendered that made it more demanding on the GPU while removing some visual artifacts.

> Is it due to using a newer version of opengl in 23.4 (which my graphics card doesn't support)?

No, the required version is still 3.3, and your GPU does support it. But the support from your GPU is apparently quite poor, so you get low performance.

> ShowMySky was slow on 23.2 on my PC but at least it worked, am I missing it completely with your solution?

Yes, we can't achieve progress if we try to support all the graphics features on hardware that's not capable enough or too slow. The fix will be optional, so you'll have a choice to keep status quo (maybe switching to another landscape to make things work faster).

> And, when will this change be implemented?

When I get some free time for this.

**Comment by 10110111** [comment]
So, it appears that this doesn't force-disable ShowMySky, so you can have it regardless of low graphics mode, provided you have OpenGL 3.3 support. Dithering will, however, still be turned off in this case.

**Comment by Regulus-mj94** [comment]
I installed the latest weekly snapshot.
Where is the force low graphics option? How should I enable it?
