### ISSUE TITLE
Is there any tutorial on compiling to android platform and iOS platform?

### ISSUE THREAD

**Issue by frank-1992** [Stellarium/stellarium#3598]
I want to integrate this star map into a mobile application, but I don’t know how to do it?
can you give me some suggestions?

**Comment by alex-w** [comment]
This is the repository for desktop edition of Stellarium

**Comment by frank-1992** [comment]
Is there any repository for mobile?



At 2024-01-17 14:16:10, "Alexander V. Wolf" ***@***.***> wrote:

This is the repository for desktop edition of Stellarium

**Comment by alex-w** [comment]
> Is there any repository for mobile? 

Unofficial: https://github.com/chengxinlun/Stellarium-android and https://github.com/ultrapre/Stellarium-mobile
