### ISSUE TITLE
Rise/Transit/Set info gets wrong after switching location if the object was selected

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#3602]
### Steps to reproduce

1. Disable "Use custom time zone" in Location dialog so that the TZ switches automatically
2. Switch location to Novoaltaysk
3. Select the Sun
4. Check that rise/transit/set times are sensible (sunrise about 9:26, sunset about 17:44 on January 21)
5. Keeping the Sun selected, switch location to Saint Petersburg
6. Look at rise/transit/set of the Sun

### Expected Behaviour

Transit is somewhere around 13:00.

### Actual Behaviour

* Times are shifted so that transit is given around the actual rise time, and set is reported near the actual noon.
* Clearing the selection and selecting the Sun doesn't help.
* Selecting another object, e.g. LMC, and then back again the Sun fixes the times reported.

![Screenshot_2024-01-20_20-30-25](https://github.com/Stellarium/stellarium/assets/6376882/a13ed395-494a-423e-ae7e-9e1a9522a0eb)

### System
* Stellarium version: v23.4-48-gd05e0e82dc
* Operating system: Ubuntu 20.04
* Graphics Card: Intel UHD Graphics 620

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/14000428/log.txt)

**Comment by 10110111** [comment]
The problem still reproduces with the original reproduction steps.

**Comment by alex-w** [comment]
> Did you reproduce it before your change?

Yes, of course
