### ISSUE TITLE
Remote Control Plugin - Objects Info

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#3605]
### Discussed in https://github.com/Stellarium/stellarium/discussions/3604

<div type='discussions-op-text'>

<sup>Originally posted by **Xio1996** January 22, 2024</sup>
Hi Everyone,

I am using the Remote Control Plugin (/api/objects/info?format=map) to return data on the selected object in Stellarium. The object is then added to an AstroPlanner plan. I'm having trouble getting the objects size/orientation information returned.

As an example I selected NGC 6740 (galaxy) and requested the data in JSON format. The size information for the major axis is returned in several formats.

    "size": 0.0003470296231767495,
    "size-dd": 0.019883332774043083,
    "size-deg": "0.01988°",
    "size-dms": "+0°01'11.58\"",

However, Stellarium displays not only the major axis but also the minor axis and orientation angle. I know that if I call the 'info' command on the Remote Control Plugin, without a format parameter, then I will get back the displayed html code. 

Size: +0Â°01'11.58" x +0Â°00'41.52"<br />Orientation angle: 40Â°

Is it possible to get this information (if available) in the JSON/map format? 

Many thanks for your help.

Pete</div>

**Comment by Xio1996** [comment]
Thank you.

**Comment by Xio1996** [comment]
@gzotti Thank you for adding the functionality, exactly what I needed.
