### ISSUE TITLE
SIGSEV on Startup (Flatpak)

### ISSUE THREAD

**Issue by Xarius86** [Stellarium/stellarium#3607]
### Expected Behaviour
Stellarium launches.

### Actual Behaviour
Stellarium shows splash screen and eventually crashes.

### System
* Stellarium version: Flatpak from Flathub.` (Stellarium	org.stellarium.Stellarium	23.4	stable	system)`
* Operating system: Fedora Silverblue 39
* Graphics Card: Intel

### Logfile 
Log attached.
[log.txt](https://github.com/Stellarium/stellarium/files/14013949/log.txt)

**Comment by alex-w** [comment]
@Xarius86 could you check suggestions from #3429?

**Comment by Xarius86** [comment]
I just checked this a few moments ago.

There were some library updates from Flatpak and some rpm-ostree updates since I last tried to run it...so, I'm not sure what update fixed it, but it's working now.

**Comment by alex-w** [comment]
Good news, thanks!
