### ISSUE TITLE
Force low graphics mode option in stellarium-24.0-81f3739-qt6-win64

### ISSUE THREAD

**Issue by Regulus-mj94** [Stellarium/stellarium#3611]
I installed the latest weekly snapshot which has a fix for my previous [issue](https://github.com/Stellarium/stellarium/issues/3590).
Where is the force low graphics option? How should I enable it?

**Comment by 10110111** [comment]
Pass `--low-graphics` or `-L` option to the Stellarium executable. On Windows you can do this by editing the shortcut.

**Comment by Regulus-mj94** [comment]
I tested it now.
Everything works smooth and lag-free, even a bit smoother than 23.2!
Even ShowMySky run with better fps.
Not sure what I missed using this low graphics mode. I can't see any diffrence.
Anyway, thank you for this quick fix. If I find any bugs in further use, I will report.

**Comment by Regulus-mj94** [comment]
Is there a way it can be activated in config file so that it will be applied automatically to the new versions after the update?

**Comment by gzotti** [comment]
No plans currently, but you can configure the environment variable STEL_ARGS, see User Guide chapter 6.2.2. We must not forget documenting this option in the list in Chapter 6.

**Comment by 10110111** [comment]
Added to the list in the SUG.
