### ISSUE TITLE
cannot select θ1 Ori B which is the B star in the orion trapezium

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#362]
_Original report by Richard Bruckner:_ https://bugs.launchpad.net/stellarium/+bug/1195285

cannot select ?1 Ori B which is the B star in the orion trapezium

the other 3 stars in the trapezium are easily selected by clicking on them at any zoom level

win 7 64 bit 0.12.2 dev7

**Comment by roncli** [comment]
I had a different experience where all I could select was D, regardless which star I clicked on in the trapezium.  This is in 1.2.4.
