### ISSUE TITLE
General Oculars usage questions

### ISSUE THREAD

**Issue by FredOzzie** [Stellarium/stellarium#3624]
### Discussed in https://github.com/Stellarium/stellarium/discussions/1398

<div type='discussions-op-text'>

<sup>Originally posted by **alex-w** December  9, 2020</sup>
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.</div>

**Comment by FredOzzie** [comment]
Hi All,
I've been using Stellarium for 3-4 years and I really like it.  But I have a couple suggestions/requests.
1.  As I search for new DSO's, I notice interesting objects like a red nebula near the star 12 Mon.  But clicking around in the area does not bring up any catalog no. for this object.  How to find out what it is?
2. I often use the telescope or camera "tool" views (icons @ upper R of screen.  It would be REALLY helpful if the cardinal points were added to the display.
3. For camera view, why is there an entry for telescope (unless there is a way to add an afocal system)?  If so, how to do this?  For example, with an 80x eyepiece & 4mm smartphone lens, hw to enter FOV?
4. For telescope/camera views, would be very helpful to have an easy way to rotate the FOV (via a clickable handle) rather than the awkward wrench icon, then Sensors, then guess at rotation angle, then close wrench & see if the rotation is correct.
5. When these tool views are open, would be handy to be able to shrink the display of info. in UR corner so that the sky view is not covered.

Thanks for Stellarium & for this forum.
Fred

**Comment by alex-w** [comment]
1. Search Tool/SIMBAD
2. Oculars plugin doesn’t hide the cardinal points. Probably you meant something else.
3. I don’t understand problem. Telescope is equal objective in DLSR.
4. GUI in top right corner (digits with degrees) or shortcuts.
5. Can be configured in Configuration/Markings dialog and in Oculars plugin.

**Comment by gzotti** [comment]
1 Yes, activate more DSO catalogs. The nebula is the famous Rosetta. 
2 I suggest you activate the coordinate grid of your preference.
3 A camera needs a telescope. Think of a "real" camera on a "real" telephoto lens. Note that afocal smartphone lens photography is not considered worth modelling. 
4 You can rotate the sensor frame by 1/5/15 degrees in the upper right menu panel. The actual view does not rotate and is either equatorial or azimuthal.

**Comment by FredOzzie** [comment]
Thanks for the answers.  I do know the Rosetta, NGC 2244, and now I see the ID on the screen but earlier I saw no markings.  And other times, I've seen nebulosity & tried clocking all over the area but got no identification

re: cardinal points, I'd like to see them in the ocular view.    Hopefully my screenshot is visible showing the FOV of my 8x50 right-angle, correct view finder scope. I think up is E but it would be nice if it were identified.
![Finder view](https://github.com/Stellarium/stellarium/assets/158761373/3c99f533-09b1-45ec-b468-c59e082f913d)

**Comment by alex-w** [comment]
> re: cardinal points, I'd like to see them in the ocular view. Hopefully my screenshot is visible showing the FOV of my 8x50 right-angle, correct view finder scope. I think up is E but it would be nice if it were identified.

What is the problem?
![stellarium-001](https://github.com/Stellarium/stellarium/assets/88731/3c88866f-a70e-49b2-9f27-68f27553e569)

> And it would be REALLY nice if I could rotate this view with my mouse. For example if I plan a camera shot of the Milky Way in Cygnus, I'd like to align the view along the axis of Cygnus to see what fits in the FOV without guessing at a rotation angle in the wrench icon/Sensors view.

It's already implemented
![stellarium-003](https://github.com/Stellarium/stellarium/assets/88731/d115a348-d4f5-4a8f-94da-d85b692dfab4)

**Comment by FredOzzie** [comment]
@alex-w: 
"What is the problem?"  Thanks for your message.  How did you make that image and how can I do it?
"It's already implemented" How to do this?  Looks really nice.

**Comment by alex-w** [comment]
> @alex-w: "What is the problem?" Thanks for your message. How did you make that image and how can I do it? 

What is you see here (Ocular view section - Show compass rose)?
![oculars_gui_general](https://github.com/Stellarium/stellarium/assets/88731/17907dc3-302b-4c53-9eaa-43db1d75b6ac)

> “It's already implemented" How to do this? Looks really nice.

Looks like a joke… We’re answered for it twice - please see GUI panel in top right corner on my screenshot.

In any way answers for all questions/suggestion was gives in Stellarium User Guide already.

**Comment by FredOzzie** [comment]
Now I see it.  Thanks for your help.

--- Fred
