### ISSUE TITLE
Old compatible version needed

### ISSUE THREAD

**Issue by BrunoGrubenmann** [Stellarium/stellarium#3629]
Hi,
I installed Stellarium 23.4 under MacOS 12.6 (Monterey). This version cannot be installed on my older MAC under Catalina 10.15.7, which cannot be updated further.
Could I find somewhere an older Stellarium-Version compatible with Catalina?
With many thanks and best Regards.
Bruno Grubenmann

I was requested by Stellarium Labs to send you an issue on github

**Comment by alex-w** [comment]
Please check https://github.com/Stellarium/stellarium/releases/download/v23.3/Stellarium-23.3-qt5-x86_64.zip

General answer for search any old version of Stellarium: links "all releases" or "archive" at stellarium.org
