### ISSUE TITLE
wrong position angle & dist for 61 Cygni binary

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#363]
_Original report by Robert Toop:_ https://bugs.launchpad.net/stellarium/+bug/1299412

The position angle for 61 Cyg A to B appears to be 90 degrees; should be 152 degrees.
The separation appears to be 48 arcsec; should be 31.5 arcsec.
Good news is that cranking back the clock in Stellarium 0.12.4 shows proper motion that matches 1916 & 1948 photos in "Burnham's Celestial Handbook."

I love this program, but until now I assumed ALL star positions were based on Hipparchos satellite. Is there a problem with close doubles in general?

**Comment by gzotti** [comment]
The InfoString data say PA(2018)=267°, angular separation 121''. Separation is more like 30'', and PA should be 154° by now.  Now 61 Cyg is one of the revolving binaries. Can these values be actually computed "live"? 

In addition, I am afraid something is wrong with that star's PM. See it with e.g. ZTF or 2MASS HiPS in background, the dates don't fit. @henrysky , @alex-w ?

**Comment by henrysky** [comment]
@gzotti I have fixed (d326ee9) 61 Cygni parameters (once pointed out by Atque but the same mistake happen again when transferring the code from in-line to a separate data file).

Position angle and separation should be able to be computed live. I will take a look tonight
