### ISSUE TITLE
Location Latitude & Longitude will not save

### ISSUE THREAD

**Issue by 520kaymann** [Stellarium/stellarium#3633]
### Expected Behavior

Enter latitude, longitude, elevation, Name of location, Then add to list and location should be listed as entered.

### Actual Behavior
Upon entering name of location the latitude and longitude change back to previous values.

### Steps to reproduce
Add any new location and will get the above results.
### System
* Stellarium version: 23.4.0 based on Qt 6.5.3
* Operating system: Windows 10 latest build and fully up to date
* Graphics Card: NVidia, Model RTX 2060, 31.0.15.5123 (2024-01-18)

**Comment by gzotti** [comment]
I just added a new location and can switch between existing and the new one. 
You probably cannot overwrite existing locations, else I cannot reproduce your problem.

**Comment by gzotti** [comment]
If your landscape contains location data and you load it with [x] Use location from Landscape activated, sure.

**Comment by 520kaymann** [comment]
My landscape is auto loaded at startup can I remove the lat and lon from the custom landscape file with no ill effect?

**Comment by gzotti** [comment]
The usual idea is that a landscape fits best to its location. If the landscape.ini does not include its location, or if the flag to load location from landscape is not set (this may be the better way out here), loading a landscape does not change location.

**Comment by 520kaymann** [comment]
I deleted Latitude, Longitude, and Elevation values from the Custom landscape ini and all works great. Yes, my landscape outline is down there but I can easily ignore it when not in the backyard. Thank you for your time and consideration! Values now stick!
