### ISSUE TITLE
Issue with Astronomical Calculations: Ephemeris Showing Unrealistic Magnitude for Uranus

### ISSUE THREAD

**Issue by Yogurt84** [Stellarium/stellarium#3634]
### Expected Behaviour
"Astronomical calculations" (Ephemeris) estimates the magnitude of Uranus within a rage of [5.38, 6.03].
This range was sorced from Wikipedia.

### Actual Behaviour
"Astronomical calculations" (Ephemeris) sometimes predict a magnitude of Uranus greater than 10.
 - 10.10 at 2030-02-18 01:52:02
 - 10.90 at 2069-02-18 01:49:23 

### Steps to reproduce
1) Open "Astronomical calculations" window
2) Open "Ephemeris" tab
3) Select Uranus in "Celestial body" option
4) From: 2024.02.18 12:57:03 To: 2074.03.18 12:57:03  // Perhaps time setting is critical.
5) Time step: 1 sidereal year
6) Select "magnitudes" checkbox
7) Click "Calculate ephemeris"

### System
* Stellarium version: stellarium-23.4-qt6-win64.exe
* Operating system: Windows10 Version 22H2 OS build 19045.4046
* Graphics Card: NVidia, GeForce GTX 960, 537.13
* Screen type (if applicable): 

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/14321147/log.txt)

**Comment by alex-w** [comment]
Ephemeris tool in "Astronomical calculations" dialog show magnitudes with air mass correction (refraction and extintion effects), so, magnitude of Uranus near horizon will be dimmer than in some height. Of course when Uranus under horizon you will see probably "strange" magnitudes (depends on selected algorithm for refraction/extintion under horizon). To avoid these effects, just disable an atmosphere and compute the ephemeris again.

**Comment by gzotti** [comment]
I just added a note to the Guide on that.

**Comment by alex-w** [comment]
@gzotti adding tooltip for magnitudes when atmosphere on maybe helpful also

**Comment by gzotti** [comment]
Ideed. But it's not only atmosphere. If s.o. compares with almanac, we apply topocentric correction, aberration etc. _if so set_. I will try to find a short formulation.
