### ISSUE TITLE
Color index for some stars is wrong

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#364]
_Original report by Nick Fedoseev:_ https://bugs.launchpad.net/stellarium/+bug/1405467

Color index for some stars is wrong, they usually look too red.
Actual index of the selected star at the picture is about ~1.5, while 3.50 is shown.

Perhaps, this can be useful: such extreme index value corresponds to integer value of 127 before conversion (maximum allowed for the field in the data structure)

**Comment by gzotti** [comment]
(fixed in original discussion? -- No!)
That one star is no longer shown. But there is one suspicious nearby

mag: 13.45
Color index (B-V): 3.41
RA/Decl (J2000.0):3h45m49.61s/+24°25'35.8"

B-V>3 is very suspicious, generally, so this may even be a code/catalog design bug!

**Comment by alex-w** [comment]
Some additional info: https://stargazerslounge.com/topic/337028-stellarium-v0191/ and https://stargazerslounge.com/topic/336251-accuracy-of-color-index-in-stellarium/
