### ISSUE TITLE
Allow sub-arcminute lower limit for angular size

### ISSUE THREAD

**Issue by oleraj** [Stellarium/stellarium#3647]
**Is your feature request related to a problem? Please describe.**
When I try to use the "Limit angular size (arcmin)" feature on the "Sky and Viewing Options" window -> DSO tab, I can set a reasonable maximum target size, but the fact that the lowest minimum is 1 arcminute means that I won't be able to see nebular targets smaller than 1 arcminute such as NGC 2346 / Butterfly Nebula, which is 54 arcseconds -- just shy of 1 arcminute.

**Describe the solution you'd like**
I would like to be able set a lower angular size limit of 0 and also allow 10th decimal values between 0 and 1, i.e., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9.

**Describe alternatives you've considered**
I tried setting this to zero my manually typing 0 but when I click out of the field it switches back to 1, confirming the fact that 1 arcminute is the lowest allowed minimum value. For me the only alternative I've found to be able to see labels for targets below 1 arcminute is to turn off the "Limit angular size" feature.  The disadvantage of that is I can't use the feature.

**Additional context**
Let me know if any additional details would be helpful. Thanks!

**Comment by gzotti** [comment]
Just an idea: we may develop a QDoubleSpinbox subclass that changes step width (increment) at decadic breaks, dependent on current value: 0.01, 0.02, ... 0.09, 0.1, 0.2, ... 0.9, 1.0, 2.0, ... 9.0, 10.0, 20.0, .... This still would allow manual input of something like 543.21 if needed, but would IMO be comfortable when all we want to set here rapidly by mousewheeling is the order of magnitude.

**Comment by alex-w** [comment]
> Just an idea: we may develop a QDoubleSpinbox subclass that changes step width (increment) at decadic breaks, dependent on current value: 0.01, 0.02, ... 0.09, 0.1, 0.2, ... 0.9, 1.0, 2.0, ... 9.0, 10.0, 20.0, .... This still would allow manual input of something like 543.21 if needed, but would IMO be comfortable when all we want to set here rapidly by mousewheeling is the order of magnitude.

Or use our DMS spinbox... I'll play with our current DMS form - maybe it will be more expectable for users

**Comment by 10110111** [comment]
> we may develop a QDoubleSpinbox subclass that changes step width (increment) at decadic breaks

We already have `LogarithmicSpinBox`.

**Comment by gzotti** [comment]
IMHO setting size in arcminutes is OK. If the LogarithmicSpinBox does the trick already (have not tried), all the better. The class files are missing our usual project header with author/GPL2 license though.
