### ISSUE TITLE
Wrong results "Search window \ Position \ Go to position"

### ISSUE THREAD

**Issue by agentu007** [Stellarium/stellarium#3648]
### Expected Behaviour
I set "Vertical viewport offset" to : -15%. 
![Offset](https://github.com/Stellarium/stellarium/assets/31736286/5c7ce9d5-649d-423c-b8ed-207362300b87)
I entered Jupiter's coordinates in "Search window \ Position" and expected the target to be centered on the planet.
![GoTo Stellarium](https://github.com/Stellarium/stellarium/assets/31736286/49b8a414-e46a-4ea0-90a2-39edac237b41)

I checked the same command with offset 0% and I got the good result.

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/14438459/log.txt)

**Comment by gzotti** [comment]
This has been developed on purpose.

**Comment by agentu007** [comment]
I think I was misunderstood. Please read again what I complained about.

I try to rephrase:
I entered the coordinates of a point in a fixed reference system, and I expected to be led to that point. This is how orientation works on any map.
The fact that you look at the map from different angles (the equivalent of the viewport function) should not influence the identification of the chosen point.

I continue to believe that changing the offset of the viewport is not allowed to influence the chosen point.
I consider this behavior a bug. 
But if you thought the software in this way, then I will adapt.

Thank you.

**Comment by gzotti** [comment]
Yes, we had a reason to implement this behaviour in this very way. You may prefer to disagree. OK. We cannot cater all expectations.

**Comment by agentu007** [comment]
Thank you.
