### ISSUE TITLE
Extremely slow on linux with nvidia-drivers-340.108

### ISSUE THREAD

**Issue by dennisnez** [Stellarium/stellarium#3649]
under 0.01 fps, 100% cpu, not usable.
glxinfo says i do have direct rendering and glxgears shows reliable 60fps.

There's nothing too bad in the log file, except maybe:
EXT_gpu_shader4 MISSING!
TessellationControl Shader: NO
TessellationEvaluation Shader: NO
Compute Shader: NO

Stellarium 24.4
Kernel driver in use: nvidia
OpenGL supported version:  "3.3.0 NVIDIA 340.108"
GL renderer: Quadro NVS 320M/PCIe/SSE2
GLSL Version Number detected: 3.3
GLSL version is fine, we should not see a graphics problem.

Does stellarium come with some kind of basic graphics capability tests to see what might be causing the bottleneck, or some settings I can try to fiddle with? Is "--low-graphics" supposed to be in 24.4?

**Comment by 10110111** [comment]
> glxinfo says i do have direct rendering and glxgears shows reliable 60fps.

`glxgears` is not a benchmark, it's so easy for the computer that I get 245 FPS with software rendering there.

> There's nothing too bad in the log file, except maybe

Please attach the full log file.

> Does stellarium come with some kind of basic graphics capability tests to see what might be causing the bottleneck

No, there's no such functionality.

> Is "--low-graphics" supposed to be in 24.4?

I'm not sure the version number you see is reliable, since 24.4 is only going to be released in December 2024. Did you build Stellarium yourself? If you take current `master` or the latest weekly build, this option will be available.

@alex-w The way the version string is generated in CMakeLists appears to be faulty, since even if we build a version from a previous year, it'll get tagged with current year.

**Comment by alex-w** [comment]
> @alex-w The way the version string is generated in CMakeLists appears to be faulty, since even if we build a version from a previous year, it'll get tagged with current year.

I fixed this issue in master already

**Comment by gzotti** [comment]
> EXT_gpu_shader4 MISSING!

I think I remember this was a welcome extension many years ago, but maybe it has been integrated into higher versions of OpenGL, as I see this message also on my system. Should not harm, just someone _might_ want to go over these tests one day and adapt to the 2020s.

**Comment by dennisnez** [comment]
> Please attach the full log file.

Attached
[stellarium.log](https://github.com/Stellarium/stellarium/files/14448940/stellarium.log)

> Did you build Stellarium yourself?

Yep, gentoo

**Comment by gzotti** [comment]
Is this with default data files? With this CPU I hope you have not loaded too many minor planets/comets. Or do the kernel modules nouveau and nvidia* fight each other?

**Comment by 10110111** [comment]
We've seen a case when a GPU from ~2007 was formally compatible with OpenGL 3.3, but too slow to be useful in high-graphics mode. Apparently, you are using one of such GPUs, so you'll have to use low-graphics mode. You need to use either the latest weekly build, or build from current git `master` to get the option to force it (it was added in d05e0e82dca728619c2713c95757f1e551927e01).

**Comment by gzotti** [comment]
I have no "feeling" for the Quadro cards. I had a Geforce 9800M GTX (G92) which worked well (for its age), and an 8600/8800 (?) desktop card which also worked as bare minimum cards as of ~2018 (I gave them away meanwhile). Not clear what critical bit is missing here. Yes, low-graphics should work.

**Comment by alex-w** [comment]
@dennisnez please try build master and check it with `--low-graphics` CLI option

**Comment by dennisnez** [comment]
> @dennisnez please try build master and check it with `--low-graphics` CLI option

Yes --low-graphics seems to work here, providing a respectable 17fps. Thank you!

**Comment by gzotti** [comment]
Added a FAQ entry.
