### ISSUE TITLE
Fog image does not cover the full view

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#368]
_Original report by Nick Fedoseev:_ https://bugs.launchpad.net/stellarium/+bug/15322277

Happens on old_style landscapes with big FOVs if landscape uses fog image.
See attached picture.

**Comment by gzotti** [comment]
https://bugs.launchpad.net/stellarium/+bug/1532227 (correct URL) is a duplicate (actually the original report for) #191.
