### ISSUE TITLE
Option to disable stars for satellite-only view

### ISSUE THREAD

**Issue by adamjameschristensen** [Stellarium/stellarium#3685]
I propose implementing a new option to completely disable the display of stars in Stellarium. This would create a "Satellite Mode" where only artificial satellites are visible on a black background.

Currently, Stellarium offers the ability to hide star labels (Alt + S) and configure satellite data sources. While these features are helpful, they don't address the issue of a cluttered view due to the vast number of stars. Disabling stars entirely would provide a cleaner and more focused environment for observing and tracking satellites.

Disabling stars would be particularly beneficial for:

Casual stargazers: Quickly identifying and tracking potential visible satellites during nighttime observations. With stars present, especially in dense regions of the sky, faint satellites can be easily missed.

Satellite research: Providing a clearer view of satellite traffic, especially for users studying the growing number of satellites orbiting Earth. A "Satellite Mode" would facilitate research on orbital paths and potential light pollution concerns.

Thank you for considering this feature request. Disabling stars would significantly enhance the usability of Stellarium for both casual satellite observers and researchers focusing on the increasing number of artificial satellites in orbit.

**Comment by alex-w** [comment]
Just press S
