### ISSUE TITLE
Cannot compile with XLSX

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#3686]
### Expected Behaviour
Activating ENABLE_XLSX in CMake configuration leads to successful compilation

### Actual Behaviour
Compilation fails with 126 errors.
![grafik](https://github.com/Stellarium/stellarium/assets/18099873/6ec4f1c5-b271-4ac0-9ded-2ccd6463ead2)

Maybe just some headers missing? I cannot say when I had disabled this, so unsure when significant changes were made. Sorry, no time currently to go hunting after this. 
There are also warnings (C4821) about missing Unicode signatures (BOM).

### Steps to reproduce
Setup QtCreator, MSVC2019, Qt6.5.3, configure as above.

### System
* Stellarium version: master (6c869cc1b7d365c4926534d5094a7d51313a0acc)
* Operating system: Windows 11
* Qt version 6.5.3/MSVC2019
* Graphics Card: irrelevant

### Note
I hope CI works for 24.1, so I target 24.2 here.

**Comment by 10110111** [comment]
What does `xlsxcellformula.h` contain? In which encoding? Normally it contains the definition of `class CellFormula` and should be in ASCII with UNIX line endings. It builds perfectly for me on Linux/GCC.

**Comment by alex-w** [comment]
I cannot reproduce the issue in Windows 10/MSVC2019/Qt 6.5.3

**Comment by alex-w** [comment]
@gzotti could you cleanup the building tree and check it again?

**Comment by gzotti** [comment]
OK, after full cleanout (my attempts before only ran cmake, sorry I am short in time these weeks.) it seems we are back at the "usual" INDI warnings which should go away iff anybody steps up to INDI2.... 

```
[120/1068 7.5/sec] Building CXX object src\external\CMakeFiles\indiclient.dir\__\__\_deps\indiclient-src\libs\indibase\indiproperty.cpp.obj
[121/1068 7.5/sec] Building C object src\external\CMakeFiles\indiclient.dir\__\__\_deps\indiclient-src\libs\indicom.c.obj
D:\StelDev\GIT\build-stellarium-Desktop_Qt_6_5_3_MSVC2019_64bit-Release\_deps\indiclient-src\libs\indicom.h(45): warning C4005: "_USE_MATH_DEFINES": Makro-Neudefinition
Befehlszeile(1): note: Siehe vorherige Definition von "_USE_MATH_DEFINES"
[122/1068 7.5/sec] Building CXX object _deps\qxlsxqt6-build\CMakeFiles\QXlsx.dir\source\xlsxdocument.cpp.obj
[123/1068 7.5/sec] Building CXX object src\external\CMakeFiles\indiclient.dir\__\__\_deps\indiclient-src\libs\indibase\basedevice.cpp.obj
D:\StelDev\GIT\build-stellarium-Desktop_Qt_6_5_3_MSVC2019_64bit-Release\_deps\indiclient-src\libs\indicom.h(45): warning C4005: "_USE_MATH_DEFINES": Makro-Neudefinition
D:\StelDev\GIT\build-stellarium-Desktop_Qt_6_5_3_MSVC2019_64bit-Release\_deps\indiclient-src\libs\indibase\basedevice.cpp: note: Siehe vorherige Definition von "_USE_MATH_DEFINES"
[124/1068 7.5/sec] Linking CXX static library _deps\qxlsxqt6-build\QXlsxQt6.lib
[125/1068 7.1/sec] Building CXX object src\external\CMakeFiles\indiclient.dir\__\__\_deps\indiclient-src\libs\indibase\baseclient.cpp.obj


```
