### ISSUE TITLE
Wrongly display of Right Ascension 12h in Equatorial System (RA-dec)

### ISSUE THREAD

**Issue by Peter-JY** [Stellarium/stellarium#3688]
### Expected Behaviour

Display 0h and 12h circle properly

### Actual Behaviour

![image](https://github.com/Stellarium/stellarium/assets/63086083/e7602569-723b-468d-9df8-0e2e1efd1b84)
![image](https://github.com/Stellarium/stellarium/assets/63086083/d960adf2-69ad-4503-a1ec-906352c7a08b)
![image](https://github.com/Stellarium/stellarium/assets/63086083/b58d9990-dd78-481f-86ed-274a8ada154a)

### Steps to reproduce

Not know exactly how to reproduce that. I just opened it, chose the Moon, press ctrl+M and E.

### System
* Stellarium version: 23.3.0
* Operating system: Windows 10 19045.3930
* Graphics Card: AMD Vega 8 Graphics in Ryzen 5 3500U; Driver version 26.20.11030.22001
* Screen type (if applicable): Resolution 2160*1440, scaling 150%, full screen mode

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/14745720/log.txt)

**Comment by gzotti** [comment]
Cannot reproduce with 23.4 or 24.1. Please update.

**Comment by Peter-JY** [comment]
I'm sorry to say that after updating to 24.1, this issue still occurs. : (

**Comment by gzotti** [comment]
... and now I saw it. Not always though! May depend on the sub-second of program start (???) Some bad optimisation?

**Comment by alex-w** [comment]
> ... and now I saw it. Not always though! May depend on the sub-second of program start (???) No, time-dragging shows it blinks from one location (time) to the next... Just the 12h line, no other.

a rounding issue probably?

**Comment by gzotti** [comment]
Some decision has to do with rounding, sure. But from ~12h&pm;(few seconds) to displaying 0h is an error.

**Comment by gzotti** [comment]
GridlinesMgr.cpp:334: 

Is there anything that breaks elsewhere when removing all of the extra cases and tests, just replace with 
`textAngle = d->raAngle;`
before the `if (d->frameType==StelCore::FrameFixedEquatorial)`.

Why did we need all the (possible) bloat before? Is there similar simplification possible in the other grid systems?

**Comment by alex-w** [comment]
As far as I remember, this bloat was needed to avoid other cases for rounding issues. Probably this code should be revived for all grids.
