### ISSUE TITLE
24.1: Problem in OBJ number parser

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#3689]
We have massively sped up the OBJ loading for 24.1 by some more manual parsing. I tried a couple of my large scenes, but not the simple ones. It seems we have overlooked "something". :-(

### Expected Behaviour
All scenes load without issues

### Actual Behaviour
Some scenes report a problem in the lower-left corner, refer to the logfile for details, and just won't load. 

### Steps to reproduce
Try loading built-in Sterngarten scenery.

### System
* Stellarium version: 24.1
* Operating system: Windows 10
* Graphics Card: Geforce 2070 (irrelevant)

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

Relevant fragment:
```
stel.plugin.scenery3d: Loading ground from "C:/Program Files/Stellarium_24.1/scenery3d/Sterngarten/Sterngarten_Wien_innerArea_ground.obj"
stel.OBJ: Loading "C:/Program Files/Stellarium_24.1/scenery3d/Sterngarten/Sterngarten_Wien_innerArea_ground.obj"
stel.OBJ: Opened file in 0 ms
stel.OBJ: 7 materials loaded from MTL file "Sterngarten_Wien_innerArea_ground.mtl"
stel.OBJ: Error parsing Vec2: { "vt" "-588.189" "-1.07797e-046" }
stel.OBJ: Critical error on OBJ line 918 , cannot load OBJ data:  "vt -588.189 -1.07797e-046"
stel.plugin.scenery3d: Failed to load ground model "C:/Program Files/Stellarium_24.1/scenery3d/Sterngarten/Sterngarten_Wien_innerArea_ground.obj"

```

I thought it choked over the exponential number, but this is by far not the first, not the first negative, and I don't really see a reason not to continue here. Or does it want to parse "vt" as first element into e Vec2? Why here, why not earlier? 

Strange: I found a similar error in 23.4 in another of my older models (probably all affected are Sketchup exports, but not all Sketchup exports are affected...), so the issue may have crept in earlier. Note the difference: QList(...), not {...}:

```
stel.OBJ: Error parsing Vec3: QList("vn", "-0.707106781187", "1.23018458829e-47", "0.707106781187")
stel.OBJ: Critical error on OBJ line 913 , cannot load OBJ data:  "vn -0.707106781187 1.23018458829e-47 0.707106781187"
stel.plugin.scenery3d: Failed to load OBJ file "D:/Stellarium/scenery3d/NNN/NNN1.obj"

```

I see the exponent, e-046 or e-47. Maybe this fails to parse into a single-precision float? Could of course just be rounded to zero.

**Comment by alex-w** [comment]
I can confirm the problem in linux :(

**Comment by alex-w** [comment]
> I see the exponent, e-046 or e-47. Maybe this fails to parse into a single-precision float? Could of course just be rounded to zero.

I've replaced numbers like `-1.07797e-046` to `0` and it works now

**Comment by gzotti** [comment]
Yes, this fixes the one model. But I have more, so it's something to fix in the parser. If required, we must parse to double, round to single. The OBJ format has no restrictions concerning numerical domain. Of course, also exporters could round before writing, but that's up to their devs.

**Comment by 10110111** [comment]
Wow, this is actually surprising. I'd never think that underflow would result in a parsing error. And I'm afraid that if we change the parsing to `double`, this might become slower. Maybe we should retry with a double version of `from_chars` if the `float` one fails (but surely, benchmark the direct `double` solution first).

**Comment by 10110111** [comment]
A relevant article about this defect in C++: [link](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2827r0.html).

**Comment by gzotti** [comment]
Yes, I also never have seen this before. Some parsing function could have extra parameters to actively demand failure, but usually IMHO a simple, silent round to zero would be enough. Sure, there might be cases with other follow-up issues then...  
Yes, keep parsing float and switch to double only for error sounds like a good strategy. A single such number can break an otherwise fine  35 million vertex file.
