### ISSUE TITLE
cannot delete comet 12P/Pons-Brooks via SSO editor

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3693]
### Expected Behaviour

(My) comet catalog contains two instances of this comet:

"12P/Pons-Brooks"
"12P/Pons-Brooks (2024)"

### Actual Behaviour
Cannot delete the first instance

### Steps to reproduce

1. Go F4 > SSO > Solar System Editor > Solar System
2. look for 12P/Pons-Brooks (not the "(2024) version
![image](https://github.com/Stellarium/stellarium/assets/3529789/80d382dc-1f26-4b3b-b5ab-7c4898e09915)

4. click "Remove"
5. quit Stellarium
6. open Stellarium

BUG: removed comet reappears.

### System
* Stellarium version: 
Stellarium 24.4+
Version 24.4.8-0de39da [master]
Based on Qt 5.12.8

* Operating system:
* Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-174-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

## Workaround
Manually remove the object from `ssystem_minor.ini`.

**Comment by gzotti** [comment]
The first entry is of outdated format. Maybe some parser cannot identify it. Yes, just delete it manually. Like all ssystem_minor.ini files before 23.2 (?) have an entry "comet_orbit" about which current versions complain. Ignore the complaint and use the file with older versions, or use different files. 

Is that outdated entry included in 24.1?

**Comment by axd1967** [comment]
Note: this is technically not a bug, yet a user annoyance, because both comet orbit data versions _nearly_ overlap, making it difficult to read their labels.

![image](https://github.com/Stellarium/stellarium/assets/3529789/3907b27d-3358-4652-8905-3d751d04ce28)

Data files that use older formats should come with upgrade routines to deal with this kind of issues. 
The software pattern is e.g. use a switch case that progresses through all older versions, successively rewriting / upgrading the format until the latest format is reached.

> Is that outdated entry included in 24.1?

I removed the entry, can't tell, sorry.

**Comment by gzotti** [comment]
If the new version would just modify the file, it would not be usable with older versions which may be installed. At some point new functionality like format changes which allow better distinction between multiple apparitions of periodical comets creates little annoyances for a little handful of users. I cannot say what caused the non-deletion.

**Comment by alex-w** [comment]
> Version 24.4.8-0de39da [master]

You're using the actual version for the first two weeks of January, but the code in the plugin was changed already - please check the latest master
