### ISSUE TITLE
Planet Orbit Lines do not show

### ISSUE THREAD

**Issue by akagumo** [Stellarium/stellarium#3695]
### Expected Behaviour
in SSO menu, checking show orbits, orbit lines should show

### Actual Behaviour
in SSO menu, checking show orbits, no lines show

### Steps to reproduce
in SSO menu, check show orbits on

### System
* Stellarium version: 24.1
* Operating system: macOS 13.6.5
* Graphics Card: Intel Mac with AMD 580 graphics
* Screen type (if applicable): 

I searched and could not find any info on this issue.  a YT video shows, jut check on show orbit lines and it works, but not for me.

**Comment by gzotti** [comment]
Works well on Windows.
![grafik](https://github.com/Stellarium/stellarium/assets/18099873/c389d701-4974-4560-8544-502517cb565a)

**Comment by akagumo** [comment]
well doesn't work for me on Mac.  am I missing something or is it a bug in Mac version?
<img width="1688" alt="Screenshot 2024-03-27 at 5 04 22 PM" src="https://github.com/Stellarium/stellarium/assets/26473499/e5631f47-86ed-4938-ad8e-fcf33636a831">

**Comment by alex-w** [comment]
@akagumo please select any planet or disable option "Only orbits for selected objects..."

**Comment by akagumo** [comment]
thanks alex-w, thought I tried that. I guess I didn't. works now.
