### ISSUE TITLE
Lunar Rise - Transit - Set (RTS) Tables Format change request

### ISSUE THREAD

**Issue by jerrydsp** [Stellarium/stellarium#3703]
I use the RTS feature in the Astronomical calculations suite of programs
to generate a table of Lunar RTS values. I use these values to plan my
astro-photography evenings at remote dark sites in South Australia.

Each row gives the Moon Rise, Transit and Set times (RTS) for a particular day.

Is it possible to order the Rise, Transit and Set times such that they
are in time order ? i.e. Each line starts with a Moon Rise (day #1) followed
by the next Transit time and Set time even if they are on different days.

I am currently extracting the relevant lines and re-ordering to suit my purposes
Here is an example of how I re-order the data:

[Moon_RTS_plan_04_05.txt](https://github.com/Stellarium/stellarium/files/14833524/Moon_RTS_plan_04_05.txt)

**Comment by gzotti** [comment]
We (attempt to) provide RTS for the current calendar date as provided by our favourite almanachs. This would mean that occasionally one event may not occur on a date. Your use case is just what other people have complained about, that we don't provide the setting minute on that current calendar day. It's a matter of taste, but we cannot (easily) serve both flavours without going through many nasty code details. For almanach creation, there are lots of other tools around.
