### ISSUE TITLE
Only 2 steps in date stepper

### ISSUE THREAD

**Issue by StarFlea** [Stellarium/stellarium#3707]
Hello folks!

The following (reproducible) problem:
1. The moon is selected and centered.
2. Date/Time settings are opened
3. If the date is changed via the stepper, it always makes 2 jumps instead of one, e.g. from 2024 to 2022...

![3](https://github.com/Stellarium/stellarium/assets/118836358/43b5a4de-c974-4f1b-abb5-3660db6e9d68)

Only the year, month and day are affected, but not the time.
Apparently the phenomenon only occurs when the moon is selected. It works perfectly with the sun...

Version: 24.1 Qt5
Windows 10
All graphics drivers are up to date

Greetings!
Star Flea

**Comment by 10110111** [comment]
I don't reproduce. Works as expected when

* rotating the mouse wheel while hovering over the number,
* clicking arrow buttons,
* pressing arrow keys when the control is in focus.

**Comment by StarFlea** [comment]
OK, i checked it...

- Mouse wheel: works fine!
- Arrow keys: works fine!
- **Arrow buttons: dont work!**

It takes a second or two before it automatically jumps to the overnext date, but I can't prevent this jump! I restarted Stellarium several times but no effect..
Please check, if can reproduce it, when you pause the simulation.  Did you select and center the moon? Only then does this behavior seem to occur...

Here are my time configurations:
![Unbenannt](https://github.com/Stellarium/stellarium/assets/118836358/cf9126e3-693f-4411-825f-4aa3c4a14aa5)

**Comment by StarFlea** [comment]
OK, i found the reason:

If i deactivate in "Displayed fileds" the checkbox "Risings, Transits, and Settings" (RTS) the problem disappears! ;-)

**Comment by 10110111** [comment]
Tried with pausing an unpausing, the Moon being selected and centered all this time. Still no repro.

> It takes a second or two before it automatically jumps to the overnext date, but I can't prevent this jump!

Can you describe in detail what you observe? Maybe the date does change but the control is not redrawn?

> If i deactivate in "Displayed fields" the checkbox "Risings, Transits, and Settings" (RTS) the problem disappears!

This is even stranger. I also had this checkbox enabled all this time, and couldn't reproduce.

**Comment by StarFlea** [comment]
Ok, i try to describe:

1. Start Stellarium
2. Ensure, RTS is enabled
3. Set date to 2025 - 4 - 4 / 20:15:00
4. Select moon and center it
5. Klick to the up-arrow in year: date jumps to 2024-04-04 (in settings and simulation) and a second later it jumps on its own to 2025-04-04 (in settings and simulation)

**Comment by gzotti** [comment]
I also cannot reproduce this. Pressing the up arrow button advances to 2026-04-04. 
May depend on configured plugins or other settings as well.

**Comment by StarFlea** [comment]
Strange, the behavior still occurs for me...
Did you pause the simulation and select and center the moon? Is RTS enabled?

**Comment by gzotti** [comment]
Yes, I think I followed to the point. Maybe I had time 20:15:47 but tell me this matters! Or did I select the Moon before setting date? Does this make a difference?

**Comment by StarFlea** [comment]
No, the date doesn't matter.

I just tried selecting the moon first (without centering) with the current date (2024-05-11). Now, the double jump takes place in the month and not in the year...

The only thing that seems to matter is whether RTS is activated and the moon is selected.

I'm using a Qt5 version. Can this make a difference?

**Comment by StarFlea** [comment]
The day is now also affected by the double jump.

Interestingly, the time remains unaffected.

**Comment by gzotti** [comment]
Still no "luck" for me. Also with 24.1/Qt5.

**Comment by gzotti** [comment]
Wild guess: Some issue around timezone and the actual changes in whether the Moon has transit shortly before/after midnight. Is the jump on any date, or by chance just today and that 2025-4-4? Of course, if the up arrow works, the button should work the same way.

**Comment by StarFlea** [comment]
The date doesn't seem to matter! I just tried it with today's date. It also doesn't seem to matter whether the moon has already crossed the meridian or not.
Only the date field is affected, but not the time field! Here, the year, month or day are skipped using the up arrow, but also with the down arrow.
Using the up and down keys on the keyboard works fine!

**Comment by StarFlea** [comment]
It doesn't matter whether the simulation is running or paused...

**Comment by StarFlea** [comment]
Here are my settings...
![Information](https://github.com/Stellarium/stellarium/assets/118836358/ddb5a80a-8ed6-4a0a-87d8-9cd38f363d40)

**Comment by gzotti** [comment]
Can you try a reset: rename config.ini to start "like new". Maybe there is some setting involved that we never think of.

**Comment by StarFlea** [comment]
I recreaded the config.ini: no effect! :-(

**Comment by alex-w** [comment]
@StarFlea would you check 24.3RC1?

**Comment by StarFlea** [comment]
Hi Alex,

The problem seems to have been resolved now, at least I can't reproduce it anymore!
Has something changed? Now I'm curious!

**Comment by alex-w** [comment]
This is a good question.
