### ISSUE TITLE
[Windows] No working CLI output

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#3710]
### Expected Behaviour
Seeing the list of options when stellarium running with parameter `--help` in CLI

### Actual Behaviour
Not seeing the list of options when stellarium running with parameter `--help` (or version number when `--version` is used) in CLI

### System
* Stellarium version: 24.1
* Operating system: Windows 10
* Graphics Card: agnostic

**Comment by 10110111** [comment]
Well, this may be a hard problem. Given that Stellarium is a GUI app, you may need to get a console for this (with `AttachConsole` or, if it fails, `AllocConsole`).

**Comment by 10110111** [comment]
Additinally, I'm not sure if this will work well with e.g. GitBash console, which is not the normal Windows (CSRSS/ConHost-based) console.

**Comment by alex-w** [comment]
It was working before, but when we broke it?

**Comment by 10110111** [comment]
No idea. Try git-bisect, if you know which version worked.

**Comment by alex-w** [comment]
> No idea. Try git-bisect, if you know which version worked.

It was many years ago, so, git-bisect not helping here…

**Comment by alex-w** [comment]
It was broken since 0.10.0 (migration to Qt4) :(

**Comment by gzotti** [comment]
Strange, I see the options for Stellarium 24.1 with --help on W11. It just needs another press of Enter to return to prompt.
