### ISSUE TITLE
Github hides your repository after a millisec display

### ISSUE THREAD

**Issue by AncientZygote** [Stellarium/stellarium#3713]
If I visit [https://github.com/Stellarium/stellarium/](Stellarium) Github shows me the repository for a few millseconds then hides the content. 

If I visit [https://github.com/Stellarium/stellarium/tree/master/src/core/planetsephems](Stellarium tree) it shows the cpp files, but gives me html garbage when download any of them (it does not offer the expected download all as zip).

I have noticed this odd malfunction on my own repositories as well and assumed it was Microsoft improving Github again.

This behavior occurs with browsers:
Version 80.0.3987.163 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
Firefox 68.70esr
Chrome Version 66.0.3359.181 (Official Build) (64-bit)

Where can I obtain your code other than github?
Thanks.

**Comment by 10110111** [comment]
Your browsers are awfully outdated. Many websites will misbehave with them. Apparently, GitHub is not an exception.

If you want to just get the code, you have a couple of options:

 * Get the sources from https://stellarium.org by clicking the "Linux source" link at the top (the name "Linux" is misleading here, the source is common for all OSes supported).
 * use the standard Git client to clone the repo:
```
git clone https://github.com/Stellarium/stellarium.git
```

**Comment by AncientZygote** [comment]
Thanks. Point taken (re my "ancient" 5-year old browsers). I appreciate your pointing me to the site where I indeed found the code (as well as info pointing me at Ubuntu version targets).
