### ISSUE TITLE
Screen flickering 

### ISSUE THREAD

**Issue by patrickmattie** [Stellarium/stellarium#3718]
Hi,

I have a brand new Lenovo ThinkBook G4  and downloaded Stellarium on it, but when starting it up the screen starts to flicker. It stops after 2 seconds or so, but when i press any of the F1, F2, etc. short cut buttons or the buttons in the left side of Stellarium it starts to flicker again. It only flickers once or twice after pressing the buttons and then never again with those buttons. It sometimes also flickers when dragging the screen. I have updated my laptop to the newest software and redownloaded stellarium multiple times to no avail. Is there something i can do to fix this? This never happend with my last laptop.

I saw something about ANGLE mode, but have no idea how to do that.

Thanks in regards,
Patrick

System
* Stellarium version: 24.1
* Operating system: Windows 11
* Graphics Card: AMD Ryzen 7-5825U

**Comment by alex-w** [comment]
Please try Qt5-based version of Stellarium

**Comment by patrickmattie** [comment]
How do i try the Qt-5 based version? I dont think i have installed drivers for the graphics card, I just installed Stellarium, Ascom and EQ-mod. Sorry i'm kinda new to this.

**Comment by gzotti** [comment]
It is the version under the download button marked "Windows 7+" on stellarium.org. Please also look into our FAQ.

**Comment by gzotti** [comment]
1-2 flickers when opening windows may have to be tolerated on Intel-only systems.  Permanent flicker would be worrisome. If we don't receive more info, we will close this soon.

**Comment by gzotti** [comment]
We can only hope the Qt5-based version works.

**Comment by palhu** [comment]
I have a lenovo chromebook model ip slim 3 chrome 14m868 and in linux crostini I had a flickering stellarium window , very annoying flashing rapidly from full screen to small screen , if you has synaptic installed , just launch it typing on penguin terminal  sudo -E synaptic , then search mesa and mark on the box to install the lib...mesa wich are related to mesa and were unboxed or not installed ,click mark all upgrades then click apply, reinstall stellarium , and that worked for me. Linux in crostini is in trixie, there is no icon to lunch synaptic , you just install synaptic on penguin terminal " sudo apt install synaptic " and to launch it type " sudo -E synaptic " .  By lib...mesa I mean the packages related to mesa but not the dev (developing) packages which are not necessary if you are not a linux developer. Good luck.
