### ISSUE TITLE
5 sec-Annular solar Eclipse 1966-05-20: Sky too dark

### ISSUE THREAD

**Issue by MrRG2024** [Stellarium/stellarium#3720]
Hello,

I find a bug:
- stellarium 24.1
-> Astronomical.calculations
-> All Solar Eclipses
-> year 1966 
-> table of solar eclipses
-> click 1966-05-20 to go to greatest eclipse point
->> sky is darker then by an total eclipse

best regards
Ralf

**Comment by alex-w** [comment]
Please attach screenshots for annular and total eclipses

**Comment by MrRG2024** [comment]
it's only for 1sec very dark and several seconds dark. Time must be stopped.
![eclipse_1966_t_a](https://github.com/Stellarium/stellarium/assets/167628050/221917d9-8c90-48fc-8fc2-b7624415fac0)

**Comment by gzotti** [comment]
Strange: diameter moon:sun is 0.999, but eclipse magnitude=1.000, which allows such darkness. It would be interesting to see actual footage of such an almost-total annular.

**Comment by worachate001** [comment]
> Strange: diameter moon:sun is 0.999, but eclipse magnitude=1.000, which allows such darkness. It would be interesting to see actual footage of such an almost-total annular.

These two values are not the same because they use different method for calculations. Stellarium's solar radius (695,700 km) is smaller than solar radius in traditional eclipse calculations (696,000 km). We should use the same value, but it may not enough to fix the main issue.

**Comment by gzotti** [comment]
Good point. What is the source of "our" solar radius @alex-w @xalioth ? Changing that to 696000 (still used in the 2013 Supplement) creates a razor-sharp annular eclipse (again with magnitude 1.000 (looks to be correctly rounded) /obscuration 99.91%. I can also see strange artifacts in ShowMySky on the best spot within a few seconds of annularity when the Lunar shadow races through the zenith, (@10110111 Mode 3 only, no big deal, though.)

And I should probably add another brightness tweak to reduce earthshine during annular solar eclipses.

**Comment by 10110111** [comment]
> Mode 3 only, no big deal, though

Mode 3 should be the best in quality. If it suffers from a problem that doesn't exist in lower levels, it's bad.

From my side, I can't even reproduce the dark scene as described by the OP.

**Comment by gzotti** [comment]
![stellarium-104](https://github.com/Stellarium/stellarium/assets/18099873/a511756e-c6b6-45af-bb6f-303c5f8d0e54)

This ring is visible over 3 seconds or so. 

It may be somewhat too dark in 1966, although this is really a border case. Must have looked like circumferential Baileys Beads seconds from totality. (Are there photos of this one? An interesting study is https://books.googleusercontent.com/books/content?req=AKW5QaevTc-nNaVSLdrU1AJxQzsO2dH61dCU6tEF2hYFIpKpOhxhq9-Mq6z0L2cQnYBKXpfgxTgsVT9Czt_ZghIFFAmSM3X87THB1ZnQ0gs113X-6LbhFzyb9UpdDR6prldG2lw4aa6m-7zx-rkzbBpGRbLCPRQok_sZT7LLldia9bsxiskmhhiq4SwyYFhEEuuT6uB-t39e-c0qgHgXrtCLee70jj40JEOp8T8zSyY-5ZkGae217wMV0WSLDeANABvQLZ7UV2SR0SSXITZC83pytc_xCI9PgQ)  For a wider annual eclipse like 2005, sky brightness seems OK. It "is" slightly dark like minutes before a totality.

**Comment by alex-w** [comment]
We have `#define SUN_RADIUS 696000.` in `StelUtils.hpp` file, but we have other value in `ssystem_major.ini` file. I've changed radius value in the ini file, and probably this issue has been added by me, when I updated properties of Solar system bodies from IAU and NASA handbooks.

**Comment by alex-w** [comment]
@gzotti @worachate001 please check the master

**Comment by worachate001** [comment]
Thanks @alex-w. I would like to note that I couldn't reproduce the very dark sky posted by @MrRG2024. The sky during annularity seems a bit too dark, but not very dark like that. It might be related to GPU or graphic mode?

**Comment by Atque** [comment]
> ![stellarium-104](https://private-user-images.githubusercontent.com/18099873/325383889-a511756e-c6b6-45af-bb6f-303c5f8d0e54.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjMyNzAsIm5iZiI6MTcxNDAyMjk3MCwicGF0aCI6Ii8xODA5OTg3My8zMjUzODM4ODktYTUxMTc1NmUtYzZiNi00NWFmLWJiNmYtMzAzYzVmOGQwZTU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA1MjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxODkzMzZlMzg0NDk1YmY4ODkxZTE3ZmM2YmZlMjQ0YjcxMjFkYzBhODFhNDA3ZDJmYWU2NmMyYmZlODI0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4v0BrrUr1PoO42DP3LA3HtFP5_jPVJvmNpWHfxUUPIU)
> 
> This ring is visible over 3 seconds or so.

Do you use the default textures, those contained in the default installation? I've found that using higher resolution textures solves many otherwise visible artifacts.

**Comment by MrRG2024** [comment]
Here are all near total eclipses from 1960-2040 as a panel.
Plus 2 just so total ones.
1967-11-02 totally without duration
1986-10-03 Hybrid with duration 0 seconds
(Before I saw that all you had to do was click on the eclipse in the table, I had manually set the location of the greatest eclipse in most of them.)
![near_total_1960-2040](https://github.com/Stellarium/stellarium/assets/167628050/4dc6da98-7633-4503-a89c-f1b422e284b7)

**Comment by MrRG2024** [comment]
@worachate001:
you must stop the running time
It's only for the 1 second so dark

**Comment by gzotti** [comment]
> > This ring is visible over 3 seconds or so.
> 
> Do you use the default textures, those contained in the default installation? I've found that using higher resolution textures solves many otherwise visible artifacts.

Yes, and with `flag_atmosphere_dynamic_resolution = true` and `atmosphere_resolution_reduction = 4`. I'd still like to know more about the model to be described in the User Guide before playing with parameters again.

**Comment by gzotti** [comment]
Your 1966-05-20 looks like atmosphere is switched off entirely. If not, it's really a bug. For the others, this looks like the classical Preetham skylight, so the ring-like artifact I mentioned above is another issue.

**Comment by MrRG2024** [comment]
with and without atmosphere:
![19660520_with-without-atmosphere](https://github.com/Stellarium/stellarium/assets/167628050/5afa7c3d-fb7c-48b7-9399-a1caf275b5ee)

**Comment by MrRG2024** [comment]
+-1 second:
![19660520_+-1sec](https://github.com/Stellarium/stellarium/assets/167628050/9e81da92-40ff-4fcd-b3f0-ae9bd9d625bb)

**Comment by gzotti** [comment]
Do you have "Dynamic eye adaption" switched off? This might explain the too many stars. I cannot reproduce the amount of darkness either, but this may indeed lie in sub-second time differences. 
Ah yes, now I could. Go back 10s, then play real-time. Preetham model is too dark, stars flare up for a moment. ShowMySky is much better. 

--> The solution for me is "use the more modern sky model, it models solar eclipse brightness much better than the old model".

**Comment by gzotti** [comment]
Not sure if there is progress. 
- Nobody is assigned
- The Preetham sky has this darkness problem in exceptional cases.
- The ShowMySky is better and would be the obvious recommendation, but has this strange ring visible over a few seconds as the shadow axis sweeps over the observer. @10110111 did you follow into this?

**Comment by 10110111** [comment]
> @10110111 did you follow into this?

No, haven't found time for this yet.

**Comment by gzotti** [comment]
I think we can declare this solved.
