### ISSUE TITLE
Stellarium waiting several seconds on 'Audio' at startup

### ISSUE THREAD

**Issue by freebrowser1** [Stellarium/stellarium#3725]
When starting Stellarium it shows a splash screen showing what is loading and then it starts Stellarium normally.
The issue is that in the splash screen I see 'Initializing audio...' which takes several seconds. But In don't have audio (and why does a planetarium app need sound ?) so this is completely useless.
### Expected Behaviour
No audio loading.

### Actual Behaviour
Loading Audio at startup takes several seconds.

### Steps to reproduce
Start Stellarium on Ubuntu without sound drivers.
<img width="597" alt="Screenshot 2024-04-27 at 11 01 19" src="https://github.com/Stellarium/stellarium/assets/26625141/1e019bb9-43f5-4e53-9986-ed7cbc153496">

### System
* Stellarium version: 24.1 installed with apt package manager in Ubuntu.
* Operating system: Ubuntu 22.04.4
* Graphics Card: ? (it is not a graphics issue)
* Screen type (if applicable): 1366x768 (it happens at any resolution)
* 
### Logfile 
`stellarium 2>&1 | tee err2` results in attached file.
[err2.log](https://github.com/Stellarium/stellarium/files/15137696/err2.log)

**Comment by alex-w** [comment]
Is it from our PPA?

**Comment by freebrowser1** [comment]
> Is it from our PPA?

Yes, after installing Ubuntu and Stellarium with `apt install stellarium` I got Stellarium 20.1 and then I did
`sudo add-apt-repository ppa:stellarium/stellarium-releases` and reinstalled with `apt install stellarium` and then I got the latest 24.1 version.

**Comment by 10110111** [comment]
> and why does a planetarium app need sound ?

I also thought this first of all. From the code it looks like it's only used in the scripting engine, to make it possible for scripts to emit sounds.

**Comment by gzotti** [comment]
Yes, audio is required by the scripting engine, so this is required. Just like you have an audio system in a physical planetarium.
Is the actual audio initialisation taking so long, or is the next relevant message just late?  
If we want to be greedy with CPU cycles, add yet another config option to disable multimedia modules, and message handling in the scripting engine for the case that the Multimedia part has not been initalized.

**Comment by alex-w** [comment]
Please check the fresh beta version of Stellarium:
https://code.launchpad.net/~stellarium/+archive/ubuntu/stellarium-beta

**Comment by gzotti** [comment]
@alex-w I strongly believe that disabling media support in the install files on all platforms will make more users unhappy than delaying startup by a few seconds on some systems.  A viable solution would be an option (config.ini or command line) to switch off media support, which would prevent loading/initializing of the demanding (?) infrastructure. This may solve or prevent OP's case found in the logfile: 

> (stellarium:4919): GStreamer-CRITICAL **: 10:53:33.002: gst_element_message_full_with_details: assertion 'GST_IS_ELEMENT (element)' failed

Or maybe @freebrowser1 's Gstreamer is just broken, which takes a few seconds to recover after (or before?) this message.

**Comment by alex-w** [comment]
@gzotti media support is disabled by default now. In any way our official packages for  windows and macos provide media support. The media support in linux packages is not important and this task in hands of maintainers.

**Comment by 10110111** [comment]
> The media support in linux packages is not important

Why? Do Linux users not use scripting?..

**Comment by gzotti** [comment]
I just wonder, can you still even buy a system without sound support? No AC97, no Intel sound chip on board? I remember my last add-on sound card was in the 1990s. Or is this OP's system deliberately configured without sound support? (Kernel module deliberately disabled?) In the latter case, Stellarium worked as could have been expected: trying to initialize sound subsystem, and giving up after some time, emitting an error message, and starting. If single users want no sound and know how to disable the Kernel module, they also know or can easily find out how to build the program without multimedia support on their systems without the rest of Linux users suffering. And if we are complaisant, we add another runtime option. But don't disable a feature that works well on the vast majority of systems.

**Comment by alex-w** [comment]
> Why? Do Linux users not use scripting?..

Media support is important for real planetariums, and who heard about linux there? Windows - definitely yes, sometimes macOS, but not linux.

**Comment by 10110111** [comment]
> I just wonder, can you still even buy a system without sound support?

Not sure about buy, but I've just recently was on a VirtualBox-powered Windows without any emulated sound card (I guess I could have enabled it before trying, but the MS-supplied image has it disabled by default). When running under Dr. Memory the initialization of sound was way too long, so I had to comment out this in the sources to see some progress.

> In the latter case, Stellarium worked as could have been expected: trying to initialize sound subsystem, and giving up after some time

This "after some time" is the keyword: there shouldn't be any time to wait if there's no sound device in the system.

**Comment by gzotti** [comment]
Ah, VMs. Did not think of those. But what is "too long"? 10 seconds, or several minutes? 
Thanks for default-activating again. If anybody wants to really fix the issue in a "fully compliant" way, that command line (or config.ini) option is still the way to go I think. 
BTW, I know one mobile planetarium (inflatable dome, visiting schools) which IIRC runs Stellarium on Linux. Why not?

**Comment by 10110111** [comment]
> But what is "too long"? 10 seconds, or several minutes?

Well, under Dr. Memory it took many hours until I decided to take action. But well, this is quite an unusual scenario, I suppose Dr. Memory works as Valgrind, software-emulating each instruction, which, in addition to being under virtualization, does take its toll on performance.

**Comment by gzotti** [comment]
I think I have solved this in #3779. At least this disables sound on Windows. @freebrowser1 can you test this (build and run with --no-audio)?

**Comment by freebrowser1** [comment]
I updated to 24.2 on Linux (arm64) and the sound issue is gone.

**Comment by gzotti** [comment]
Interesting. The change has not been merged yet. :-)

**Comment by alex-w** [comment]
> Interesting. The change has not been merged yet. :-)

Media support is disabled for packages in our PPA

**Comment by freebrowser1** [comment]
I tried it out on Ubuntu and it works, but the pesky 'initializing audio' still exists. Can this be disabled ?

**Comment by alex-w** [comment]
> I tried it out on Ubuntu and it works, but the pesky 'initializing audio' still exists. Can this be disabled ?

No, you need to rebuild Stellarium with `-DENABLE_MEDIA=Off` option to disable multimedia (audio + video) support.

**Comment by gzotti** [comment]
I can hardly remember. I added an option --no-audio, or allowed setting config.ini[audio]enabled=false. Does that work to disable a split second message that tells us how far we get and should not cause a headache?

**Comment by freebrowser1** [comment]
> > I tried it out on Ubuntu and it works, but the pesky 'initializing audio' still exists. Can this be disabled ?
> 
> No, you need to rebuild Stellarium with `-DENABLE_MEDIA=Off` option to disable multimedia (audio + video) support.
Rebuild is not needed, on the Ubuntu 24.3 version the audio is indeed gone when enabling this config.ini setting.
