### ISSUE TITLE
Invalid update information in AppImage

### ISSUE THREAD

**Issue by probonopd** [Stellarium/stellarium#3726]
### Expected Behaviour

The Stellarium AppImage either contains valid or no [update information](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information)

### Actual Behaviour

The Stellarium AppImage contains defective (invalid) update information

### Steps to reproduce

The Stellarium AppImage contains the string "None" as update information. The string "None" is not valid update information. Hence, the AppImage is not a valid AppImage.

```
@probonopd ➜ /workspaces/go-appimage (master) $ objdump -x ./stellarium-24.1-qt5-x86_64.AppImage | grep upd
 27 .upd_info     00000400  0000000000000000  0000000000000000  0002c38f  2**0
@probonopd ➜ /workspaces/go-appimage (master) $ dd if=./stellarium-24.1-qt5-x86_64.AppImage skip=181135 bs=1 count=1024 | xxd
00000000: 4e6f 6e65 0000 0000 0000 0000 0000 0000  None............
```

The "None" should not be there.

Most likely it is caused by

* https://github.com/Stellarium/stellarium/blob/76434348dbf619431f521e4e8a2363b1a273ab95/util/appimage/stellarium-appimage-qt5.yml#L85
* https://github.com/Stellarium/stellarium/blob/76434348dbf619431f521e4e8a2363b1a273ab95/util/appimage/stellarium-appimage-qt6.yml#L96

### System
* Stellarium version: `stellarium-24.1-qt5-x86_64.AppImage`
* Operating system: Linux (any)

### References
* https://github.com/probonopd/go-appimage/issues/276
* https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information

**Comment by alex-w** [comment]
> The Stellarium AppImage contains the string "None" as update information. 

yes, as it described in documentation and in examples, so, why isn’t valid now?

**Comment by alex-w** [comment]
Hello @probonopd!

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by probonopd** [comment]
Looks good now, as you can see like this:

```
wget https://github.com/Stellarium/stellarium-data/releases/download/weekly-snapshot/Stellarium-24.1-15ee028-qt5-x86_64.AppImage
dd if=./Stellarium-24.1-15ee028-qt5-x86_64.AppImage skip=181135 bs=1 count=1024 | xxd
```

All zero bytes, so no update information.

Of course it would be even better if it had _valid_ update information, but at least it no longer has _invalid_ update information.

Thanks!
