### ISSUE TITLE
hiding nav stars does not restore previous settings [navstar plugin]

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3728]
### Expected Behaviour

When toggling the nav stars, previous settings should be restored

### Actual Behaviour
After showing and then hiding the navigational stars, star labels are not restored

### Steps to reproduce

1. hide nav stars
2. enable "Labels and Markers" in View>Sky settings
![image](https://github.com/Stellarium/stellarium/assets/3529789/be3d1f09-5e48-4785-ab50-ab5f983df3c3)

3. enable nav stars
4. hide nav stars

bug: setting in step 2 remains cleared

it is possible that other settings are not restored either.

### System
* Stellarium 24.4+
Version 24.4.8-0de39da [master]
Based on Qt 5.12.8
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-176-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
I cannot reproduce the report in master
