### ISSUE TITLE
Artifacts on very short total eclipses (ShowMySky)

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3729]
This was briefly mentioned but not properly reported in #3720.

Very precise total solar eclipses, such as the 3rd October 1986 eclipse, show a strange dark and pixelated halo around the Sun, using `eclipse simulation quality = 3.` See the screenshot below:

![stellarium-285](https://github.com/Stellarium/stellarium/assets/37028368/b560ae63-11d6-4276-b148-5f2c55a6dfbe)

Strangely enough, it does not appear on my MacBook, despite the same settings (`flag_atmosphere_dynamic_resolution = true` and `atmosphere_resolution_reduction = 4`, otherwise mode 3 is almost unusable).

System: Windows 10 64-bit
GPU: AMD Radeon RX 5700 XT (driver 24.4.1)

**Comment by gzotti** [comment]
Indeed, for this eclipse it looks even worse.

**Comment by 10110111** [comment]
I don't reproduce on Linux/Intel.

@gzotti Are you also on an AMD GPU?

@Atque does this happen in Mesa mode?

**Comment by gzotti** [comment]
No, W11 Optimus notebook with Geforce RTX 3070Ti. Driver version 546.01. 
Go to central location/time, one minute back, run simulation. This ring passes through the sky. OK, I can live with it, but of course technically there should be a way around to really please the spectators.

**Comment by Atque** [comment]
> I don't reproduce on Linux/Intel.
> 
> @gzotti Are you also on an AMD GPU?
> 
> @Atque does this happen in Mesa mode (may be very slow, but I'm interested just in the fact of artifacts presence)?

Mesa mode looks like this (weird lines across the screen, and the artifact still present):
![mesamode](https://github.com/Stellarium/stellarium/assets/37028368/e29da413-0a4b-4cbb-9bc5-690cf5cabcc9)

**Comment by 10110111** [comment]
OK, I've noticed something much more subtle on Intel, see the screenshot below. Looks like the roughly same ellipse(s), but apparently, while your systems generate NaNs at some of the broken pixels, mine just yields some very imprecise numbers. But at least I can reproduce the presence of some artifacts.

![Screenshot_2024-04-28_00-44-03](https://github.com/Stellarium/stellarium/assets/6376882/137fa59b-f71f-4005-a704-90eb3168d5a7)

**Comment by Atque** [comment]
Interesting. On MacOS, there appears to be no errors whatsoever:
![stellarium-012](https://github.com/Stellarium/stellarium/assets/37028368/127ed032-205f-4de6-9ee7-0ad9f7a0303a)

**Comment by 10110111** [comment]
Does the patch in [eclipse-artifacts-fix](https://github.com/Stellarium/stellarium/tree/eclipse-artifacts-fix) branch fix this for you? I no longer have the artifacts on Intel UHD Graphics 620 with this.

**Comment by 10110111** [comment]
> Does the patch in [eclipse-artifacts-fix](https://github.com/Stellarium/stellarium/tree/eclipse-artifacts-fix) branch fix this for you?

Note that this is applied to the default ShowMySky atmosphere, so you should be using it for testing, not some custom one. Or you can patch your custom model.

**Comment by Atque** [comment]
> Does the patch in [eclipse-artifacts-fix](https://github.com/Stellarium/stellarium/tree/eclipse-artifacts-fix) branch fix this for you? I no longer have the artifacts on Intel UHD Graphics 620 with this.

Yes, that appears to work for me as well. Great work!

@gzotti?

**Comment by gzotti** [comment]
I tried compiling last night. Some process appears to block my stellarium build (compiler cannot overwrite an "open" file stellarium.exe while "still in use"). But process explorer, OpenedFilesView and whatever other tools I tried don't see why stellarium.exe should be open. Zombies on Windows?  Seems I must finally restart my system, but another longish process is still running. Hopefully in late afternoon (6hrs).

**Comment by Atque** [comment]
You can simply paste the `.frag` files in `atmosphere\default`,  no building needed.

**Comment by 10110111** [comment]
> compiler cannot overwrite an "open" file stellarium.exe while "still in use"

You might be able to rename it... Also, there are tools like Unlocker that made it possible to release files from being "in use", so you may have some success with this.

**Comment by 10110111** [comment]
> You can simply paste the .frag files in `atmosphere\default`, no building needed

Or indeed, you can just direct Stellarium to the source path to find the updated atmosphere, without any copy-pasting anything.

**Comment by alex-w** [comment]
The patch is perfect for me

**Comment by gzotti** [comment]
OK. There is still some now more noisy ring artifact visible at this one eclipse, sweeping through the screen from right to left in just a few seconds. I could not detect a problem for 2017 or 2024. 
![stellarium-027](https://github.com/Stellarium/stellarium/assets/18099873/60c5dc93-b118-4751-b573-0261bb461678)

So, certainly an improvement worth applying, but it's not fully solved yet.

**Comment by 10110111** [comment]
> There is still some now more noisy ring artifact visible at this one eclipse

Are you on NVIDIA?

**Comment by Atque** [comment]
> There is still some now more noisy ring artifact visible at this one eclipse, sweeping through the screen from right to left in just a few seconds.

I can't detect this on AMD.

**Comment by gzotti** [comment]
Yes, Geforce RTX 3070Ti Laptop GPU, drivers 546.01, Win11home 23H2. One second later:
![stellarium-032](https://github.com/Stellarium/stellarium/assets/18099873/914438f9-8919-4911-8516-468c7d9fe11b)

Annular 2005/10 is also OK, but this was long. The problem seems to be around the area of the shadow cone tip. I could check a very short annular. Suggestions?

**Comment by 10110111** [comment]
So yes, the look is of exactly the same kind as what I had on Intel before the fix. NVIDIA is infamous for its very aggressive optimizer, which in particular assumes that the arithmetic is associative while it's not—due to rounding. And the expression here is sensitive to the order of additions & subtractions, which is why things break.

Apparently, I'll have to hide the difference somehow to inhibit this optimization.

**Comment by 10110111** [comment]
I've push 634db3d960a417f62e4b632c12a5db43c2cb2f89, please try it. If it doesn't help, I'll have to make an uglier hack.

**Comment by gzotti** [comment]
Yes, that solved it, thanks!
