### ISSUE TITLE
Click to select a star at high zoom gets the wrong star

### ISSUE THREAD

**Issue by GrandfatherJ** [Stellarium/stellarium#3733]
Issue noticed at high zoom with FOV < 0.4 and all star catalogues loaded.

### Expected Behaviour
Click on a star to select it and view its details.

### Actual Behaviour
A nearby star is selected instead of the star clicked on.

### Steps to reproduce
1/ With star catalogues loaded so that stars to 16th mag centre on Mimosa in the Southern Cross and zoom so that the FOV is 0.2 degrees or less. To the left of Mimosa is a 11.45 mag white star. 
2/ Click on the star. 
3/ Notice that the 15.5th mag star nearby is selected instead

The correct star can be selected by clicking on the opposite side of the correct star about the same distance as the incorrectly selected star is.

![image](https://github.com/Stellarium/stellarium/assets/64131943/88513c3a-db36-42b1-8f1f-8e534217aba4)

### System
* Stellarium version: stellarium-24.1-qt6-win64.exe
* Operating system: Windows 11 Home, 23H2
* Graphics Card: NVidia, RTX4070, 31.0.15.3210
* Screen type (if applicable): 2560x1600 Lenovo DisplayHDR

### Log file
[log.txt](https://github.com/Stellarium/stellarium/files/15206016/log.txt)

**Comment by Atque** [comment]
I can reproduce this but only with aberration enabled.

**Comment by GrandfatherJ** [comment]
It may be related to catalogue search order. In my playing around faint stars seem to be preferred. In the image below I clicked on the bright star below and slightly left of the selected star. The issue doesn't happen with any of the other bright stars in the screen shot.

![image](https://github.com/Stellarium/stellarium/assets/64131943/a5c9ae36-7417-4443-b003-815d84780b10)

Note that aberration is enabled by default. I guess with the default catalogue only this may not happen at all, or there are so few close bright stars it's not much of a problem. Complete pain when it does happen though!

**Comment by gzotti** [comment]
Yes, the anti-aberration of the clicked point may need some improvement. However, even with A. disabled, sometimes some stars just don't like to be clicked, so there may even be more to fix. Combine this with the need to re-investigate the catalog algorithms altogether for slight misbehaviour.  For now you describe what to do: click a bit to the other side.

**Comment by GeoffClements** [comment]
Just installed Stellarium to support my physics degree and came across this issue.

I'm running version 24.02 as a flatpak on a KDE Neon machine (Ubuntu 22.04 lts).

If I install version 0.20.4 from the Ubuntu repos then this version does not have the problem.

**Comment by GrandfatherJ** [comment]
Just had a play and looks good.

Cheers,
Peter

**Comment by StarFlea** [comment]
The problem does not seem to have been completely resolved with the new RC. In about 50% of all cases (in the constellation described above) the wrong star is marked. Unfortunately, I cannot reproduce why exactly...

**Comment by 10110111** [comment]
This is likely due to #3136 (in short, turn off aberration, and you'll be able to select the stars you want, then turn it on to restore their correct positions).

**Comment by StarFlea** [comment]
If I turn off the aberration, I get a significant improvement, but the effect is not completely gone.
In about 5% of all cases, I now get an incorrect star selection...

**Comment by gzotti** [comment]
This may be what I had described earlier as "it feels like some stars don't want to be selected". We had to add two corrections for anti-refraction and anti-aberration. If both atmosphere and aberration are switched off, it is as good as it gets "natively". maybe then some vector proximity search fails? E.g. not sure if all star vectors are totally normalized after the Zone math (?)
