### ISSUE TITLE
Satellites visualization is chaotic on macOS

### ISSUE THREAD

**Issue by brunophilipe** [Stellarium/stellarium#3738]
### Expected Behaviour
Satellites are not moving at relativistic speeds, app is smooth

### Actual Behaviour
Satellites move in unrealistic speeds, affecting frame rate to the point app is almost unusable. Disabling satellites fixes the frame rate (90FPS+)

### Steps to reproduce
Launch stellarium
Enable satellites
(If important: Location is set to Vancouver, Canada)

### System
* Stellarium version: 24.1.0
* Operating system: macOS 14.4.1 (23E224)
* Graphics Card: Apple M1 Max, 32 GB
* Screen type (if applicable): 4K 1920x1080 Scaled 2x (3840x2160)

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/15271893/log.txt)
[Screen Recording on YouTube](https://www.youtube.com/watch?v=dvbFglg39fM)

**Comment by Atque** [comment]
Can't reproduce on my Mac. Are your TLE's up to date?

**Comment by gzotti** [comment]
Yes, clear indication of outdated TLE.
