### ISSUE TITLE
screen flicker

### ISSUE THREAD

**Issue by clxisclx** [Stellarium/stellarium#3743]
I use Stellarium-24.1-qt6-macOS.zip and my laptop is Apple M1 and 12.6 version.
When I click this button multiple times in a row, the screen starts flashing non-stop.
![moon](https://github.com/Stellarium/stellarium/assets/70900785/d01a41f9-2fb2-4541-9d33-3ecf4fad04cd)

**Comment by alex-w** [comment]
Well, you're enabled a big time rate - hundreds or thousands days per minute - so, of course, you will see very fast-forward for time and of course the screen will be "flicker". What exactly you expected to see when the time rate is big?
