### ISSUE TITLE
org.kde.Platform branch 6.5 has reached EOL

### ISSUE THREAD

**Issue by TheTechnician27** [Stellarium/stellarium#3749]
### Expected Behaviour
Stellarium should ideally use a new version if one of its dependencies is EOL.

### Actual Behaviour
While updating via Flatpak on Arch-based KDE:
```
Info: runtime org.kde.Platform branch 6.5 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   org.stellarium.Stellarium
```

### Steps to reproduce
Install Stellarium through Flatpak and attempt to run `flatpak update`.

### System
* Stellarium version: 24.1 (latest Flatpak)
* Operating system: Manjaro, KDE 6
* Graphics Card: NVidia GTX 1070, driver version 550.78

I imagine this is already known about, but as I did not see an issue for it when searching, I wanted to formally document it.

**Comment by gzotti** [comment]
The flatpak is not configured/packed/released by us. Please contact the maintainer.

**Comment by alex-w** [comment]
Correct place to report issues for flatpak - https://github.com/flathub/org.stellarium.Stellarium/issues
