### ISSUE TITLE
 strange grid array of hundreds exo-planets in the sky

### ISSUE THREAD

**Issue by johnbellora** [Stellarium/stellarium#3754]
When i turned on exo planets and looked around the sky, there was an obvious bug which showed many hundreds of exo planets in a grid.
![Stellarium bug](https://github.com/Stellarium/stellarium/assets/63178816/4450ae36-976d-41d4-b3fc-a454e0973567)

**Comment by johnbellora** [comment]
1.)When i turned on exo planets and looked around the sky, there was an obvious bug which showed many hundreds of exo planets in a grid.

2.) Also The NGC104 does not register when clicking on it for more information. Completely ignores it. It is just off the Small Magellanic cloud.

3.) Also the CTRL-ALT- SHIFT-J command to jump 1 sidereal year  does not appear to work either

**Comment by alex-w** [comment]
> When i turned on exo planets and looked around the sky, there was an obvious bug which showed many hundreds of exo planets in a grid. 

This is correct view, see [Kepler space telescope](https://en.wikipedia.org/wiki/Kepler_space_telescope#Field_of_view) mission for details

**Comment by johnbellora** [comment]
wow! How strange but very cool. Please address the #2 & #3 potential bugs listed in my 2nd communication.
Best Regards
John Bellora
    On Wednesday, May 29, 2024 at 09:30:25 PM GMT-8, Alexander V. Wolf ***@***.***> wrote:   

 



When i turned on exo planets and looked around the sky, there was an obvious bug which showed many hundreds of exo planets in a grid.


This is correct view, see Kepler space telescope mission for details

**Comment by johnbellora** [comment]
Please address the 2nd and third items
Thanks
John Bellora
    On Wednesday, May 29, 2024 at 09:47:41 PM GMT-8, Alexander V. Wolf ***@***.***> wrote:   

 


Closed #3754 as completed.

**Comment by alex-w** [comment]
> 1.)When i turned on exo planets and looked around the sky, there was an obvious bug which showed many hundreds of exo planets in a grid.

This is correct view, see [Kepler space telescope](https://en.wikipedia.org/wiki/Kepler_space_telescope#Field_of_view) mission for details

> 2.) Also The NGC104 does not register when clicking on it for more information. Completely ignores it. It is just off the Small Magellanic cloud.

Probably, DSO markers are not enabled to display - please try press D and check it again.

> 3.) Also the CTRL-ALT- SHIFT-J command to jump 1 sidereal year does not appear to work either

But we're using Ctrl+Alt+Shift+] (and Ctrl+Alt+Shift+[) commands by default to jump 1 sidereal year - please press F1 to check active shortcuts.

**Comment by johnbellora** [comment]
thank you. I sent a few more request.  Maybe i missed those options.
    On Wednesday, May 29, 2024 at 10:10:12 PM GMT-8, Alexander V. Wolf ***@***.***> wrote:   

 



1.)When i turned on exo planets and looked around the sky, there was an obvious bug which showed many hundreds of exo planets in a grid.


This is correct view, see Kepler space telescope mission for details


2.) Also The NGC104 does not register when clicking on it for more information. Completely ignores it. It is just off the Small Magellanic cloud.


Probably, DSO markers are not enabled to display - please try press D and check it again.


3.) Also the CTRL-ALT- SHIFT-J command to jump 1 sidereal year does not appear to work either


But we're using Ctrl+Alt+Shift+] (and Ctrl+Alt+Shift+[) commands by default to jump 1 sidereal year - please press F1 to check active shortcuts.
