### ISSUE TITLE
three separate bugs

### ISSUE THREAD

**Issue by johnbellora** [Stellarium/stellarium#3755]
1.)When i turned on exo planets and looked around the sky, there was an obvious bug which showed many hundreds of exo planets in a grid.

2.) Also The NGC104 does not register when clicking on it for more information. Completely ignores it. It is just off the Small Magellanic cloud.

3.) Also the CTRL-ALT- SHIFT-J command to jump 1 sidereal year does not appear to work either

Best Regards

John Bellora

**Comment by alex-w** [comment]
> 1.)When i turned on exo planets and looked around the sky, there was an obvious bug which showed many hundreds of exo planets in a grid.

This is correct view, see [Kepler space telescope](https://en.wikipedia.org/wiki/Kepler_space_telescope#Field_of_view) mission for details

> 2.) Also The NGC104 does not register when clicking on it for more information. Completely ignores it. It is just off the Small Magellanic cloud.

Probably, DSO markers are not enabled to display - please try press D and check it again.

> 3.) Also the CTRL-ALT- SHIFT-J command to jump 1 sidereal year does not appear to work either

But we're using Ctrl+Alt+Shift+] (and Ctrl+Alt+Shift+[) commands by default to jump 1 sidereal year - please press F1 to check active shortcuts.
