### ISSUE TITLE
request a few keyboard functions.

### ISSUE THREAD

**Issue by johnbellora** [Stellarium/stellarium#3756]
Please forgive me if any of these already exist.

I would like to add

1.) A single keyboard key that jumps a single calendar year to the same date, not +365 days  
2.) A SHIFT-same key to jump backwards in time 1 calendar year, not - 365 days

Best Regards

John Bellora

**Comment by alex-w** [comment]
Please press F7 and assign or change assigned shortcuts

**Comment by gzotti** [comment]
We can presumably close this as solved.
