### ISSUE TITLE
Plugin Scenery3d - windows 11 - Qt 6.7.1 - APIENTRYP

### ISSUE THREAD

**Issue by uwes-ufo** [Stellarium/stellarium#3763]
https://github.com/Stellarium/stellarium/blob/45afd56ec2c258b3d58572c9b2ca58127c4a3a9d/plugins/Scenery3d/src/GLFuncs.hpp#L37

Somehow APIENTRYP is not defined.
As a cheap workaround I added:

```diff 
 #include <QOpenGLContext>
 #include <QOpenGLFunctions_1_0>
 
+#if defined(_WIN32)
+#include <qt_windows.h>
+#endif
+
 #if !QT_CONFIG(opengles2)
 //! Defines some OpenGL functions not resolved through StelOpenGL (which only contains base OpenGL ES2 functions)
```

But honestly I don't have enough background knowledge to provide a real solution.

**Comment by gzotti** [comment]
I don't understand. Does compilation suddenly fail on your system? I think Qt6.7.1 is the latest release, right? Maybe a Qt issue then? Or is including qt_windows.h a new requirement with Qt6.7?

**Comment by uwes-ufo** [comment]
Yes, compilation fails with Qt 6.7.x, but Qt 6.6.x works.

**Comment by 10110111** [comment]
What if you replace `APIENTRYP` with `QOPENGLF_APIENTRYP`?

**Comment by gzotti** [comment]
OK, then the first guard is also test on Qt version>=6.7  before this inclusion. Then we should see why this file is now required, i.e., what changed in Qt , and whether Qt has released some statement about it.

**Comment by 10110111** [comment]
Or maybe, instead of replacing this with a Qt-specific macro, just try including `<qopengl.h>`.

**Comment by uwes-ufo** [comment]
QOPENGLF_APIENTRYP works! 
Thank you!

**Comment by alex-w** [comment]
> QOPENGLF_APIENTRYP works! Thank you!
> 
> (no luck with <qopengl.h>)

What about QOPENGLF_APIENTRYP with Qt 6.6?

**Comment by gzotti** [comment]
I would still enclose this by a Qt version test. Or confirm it's OK with Qt5.12 as well.

**Comment by 10110111** [comment]
We can just push it into a branch and let the CI sort it out.

**Comment by uwes-ufo** [comment]
At least it passed some tests.
[uwes-ufo/stellarium](https://github.com/uwes-ufo/stellarium/commit/c82b349a6f72eff62a057ec2ce0b13ac0bcd7e46)

**Comment by 10110111** [comment]
> At least it passed some tests.
> uwes-ufo/stellarium

I don't find AppVeyor ones there... You may have to connect an AppVeyor account to make them work. Or I can push it myself if you fail.

**Comment by uwes-ufo** [comment]
Yes, please do another test because my fork is a bit different.

**Comment by 10110111** [comment]
Let's see if [this build](https://ci.appveyor.com/project/10110111/stellarium/builds/49960947) works out, and on success I'll push this commit to `master`.
