### ISSUE TITLE
24.1 version hangs up when connected to telescope while changing to other windows or apps

### ISSUE THREAD

**Issue by JavierIbarraP** [Stellarium/stellarium#3767]
Hello support team,

### Expected Behaviour
Be able to change to another window or  app while connected to telescop

### Actual Behaviour
I'm experiencing hangs up if I have Stellarium connected to the telescope LX200GPS, both with the generic and specific ASCOM drivers, if I change to another window or application for a while. It only happens when connected. If I disconnect I can change windows or apps without a problem.

### Steps to reproduce
Just connect to telescope and change to another window or app for a while. When you return to Stellarium, if it has not hanged up already, it hangs after few seconds

### System
* Stellarium version: 24.1
* Operating system: Windows 11
* Graphics Card: NVIDIA geforce MX130, WDDM 3.1
* Screen type (if applicable): 1920X1080, 150%

### Logfile 
I don't have the log.txt file as was overwritten with the last opening just this morning.

**Comment by GernotSchreider** [comment]
I have the same problem. I can connect to the mount (Avalon Linear) and do slew to a target. After that changing window to camera control app and back and Stellarium crashes.
I have uploaded the log file for inspection.
[log.txt](https://github.com/user-attachments/files/15748202/log.txt)
I had similar issues with previous versions but now it happens every time.

**Comment by 10110111** [comment]
May be related to (or the same issue as) #2874.

**Comment by gzotti** [comment]
Yes, we can safely assume duplicate. Known problem, unsolved. Use the Qt5-based build of 24.1.

**Comment by ElonVampire** [comment]
收到！

**Comment by JavierIbarraP** [comment]
Ok, following the suggestion of gzotti I installed Qt5-based build of 24.1
I will test it as soon as I get clear skies.
Regards

Javier
