### ISSUE TITLE
c/2021 s3 panstarr?

### ISSUE THREAD

**Issue by brenella** [Stellarium/stellarium#3776]
I was searching for c/2021 s3 panstarrs. Couldn't find it. Is it the same as c/2022 s3 panstarrs? 
![Screenshot 2024-06-21 113850](https://github.com/Stellarium/stellarium/assets/173489350/04d9e71e-75dc-459b-86ef-c3a1cf11fc03)
![Screenshot 2024-06-21 113840](https://github.com/Stellarium/stellarium/assets/173489350/8d220e54-a5d6-437b-89f5-f51af77d280f)

### System
* Stellarium version: 24.1
* Operating system: Windows 11 pro, 64bit
* Graphics Card: Nvidia
* Screen type (if applicable): 4K

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
No. You may have to add data with the Solar System Editor plugin. See User Guide.

**Comment by brenella** [comment]
> No. You may have to add data with the Solar System Editor plugin. See User Guide.

Thank you for your help. Issue resolved.
