### ISSUE TITLE
Wrong JSON data RA & RAJ2000 - RemoteControl plugin HTTP API ObjectService (/api/objects/)

### ISSUE THREAD

**Issue by steyefong** [Stellarium/stellarium#378]
The API returns a strange negative RAJ2000 and RA degrees in decimal. 
### Expected Behaviour
Example:
"ra":"337.6692083","raJ2000":"337.4105833"
### Actual Behaviour
Example:
"ra":"-22.330828267516114","raJ2000":"-22.589419982557157"
### Steps to reproduce
Example:
http://localhost:8090/api/objects/info?format=json&name=ngc7293
### System
* Stellarium version: 0.18.2
* Operating system: Windows 10, 64-bit
[log.txt](https://github.com/Stellarium/stellarium/files/2407585/log.txt)

* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
The result is delivered as fast as possible. If you need it, just apply the obvious "mod 360" in your client application.

**Comment by steyefong** [comment]
Thanks for the reply. I would then suggest to mention this in the API document.
