### ISSUE TITLE
DSO(Open star cluster) info bug

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3783]
### Expected Behaviour
"Morphological description" not include unnecessary string

### Actual Behaviour
"Morphological description" include unnecessary string "/&gt;"

### Steps to reproduce
Show Configuration window.
Select "All available" in "Selected object information".

Select one Open star cluster (or star cluster)in sky. (example: "Cr89" or "NGC2175")
![20240627_2](https://github.com/Stellarium/stellarium/assets/173982253/947d08bf-3135-4ed8-8d68-fa88af92d23e)

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

I traced source.

src/core/StelUtils.cpp
line 1343
     QStringList data = s.split(" ");

These star cluster's information are some lines.
This information include "&lt;br /&gt;".

I estimate that   if "s" include "&lt;br /&gt;", it separate "&lt;br" and "/&gt;".

thank you.

**Comment by alex-w** [comment]
Hmm... I can't reproduce the issue.

**Comment by 3domennotry** [comment]
Dear alex-w
Thank you for reply and assist.

I retry.
However, this bug is not occured.

Sorry, I don't know what the reproduction are.

Please forget this bug.

sorry and thank you.
