### ISSUE TITLE
Stellarium slow when graphs tab in AstroCalc has been opened

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#379]
### Expected Behaviour
Stellarium runs as normal.

### Actual Behaviour
Stellarium running slower than usual when scrolling through dates in the time window (F5) if an object is selected. FPS drops to about 20. If no object is selected, time runs as usual when scrolling.

### Steps to reproduce
1. Start Stellarium.
2. Open AstroCalc (press F10).
3. Choose Graphs tab.
4. Stellarium now runs considerably slower when scrolling through days in the time window, if an object is selected.

Note that in earlier versions, this only happened when the graphs tab was left open. I guess this has  something to do with the merging of the Alt. vs. time/monthly elevation/graphs tabs. It seems Astrocalc computes the graph every day, even though the window is closed.

### System
* Stellarium version: stellarium-0.90.0.16263-win64.exe (latest public beta build released on 16 september)
* Operating system: Windows 10 64-bit
* Graphics Card: GeForce GTX 1070.

**Comment by alex-w** [comment]
Please check the latest beta - 0.18.2.6 (0.90.0.16289)

**Comment by Atque** [comment]
@alex-w, it seems to work perfect now. Many thanks for the solution!
