### ISSUE TITLE
Navigational Pugin strange toolTip message

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3796]
### Actual Behaviour
  "Place of the string with coordinates of the mouse pointer" is shown.

### Steps to reproduce

1. Start Navigational Pugin.
2. Show Navigational Pugin Configuration window.
3. Move mouse cursor on String "Current set:".
![20240704_2](https://github.com/Stellarium/stellarium/assets/173982253/b39887d4-8ae5-4268-86ab-3b50dfa79596)

However, it maybe not bug.

I am Japanese.
In Japanese Language, the toolTip message is strange.

However, I don't know how it should be in English.

(Sorry, I can not speak English very well.)

thank you.

**Comment by gzotti** [comment]
Copy/paste error...

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed.
Thank you very much.

**Comment by alex-w** [comment]
Thanks for good feedback!
