### ISSUE TITLE
Observing list strange toolTip message

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3797]
### Actual Behaviour
  "Highlight all the objects of the selected list" or "Clear all the highlight objects" is shown.

### Steps to reproduce

1. Show Observing list window.
2. Change editor mode or creation mode
3. Move mouse cursor on Button "Add object" or "Remove object".
![20240704_3-1](https://github.com/Stellarium/stellarium/assets/173982253/a03274f3-fe16-4df5-b63f-5fa32def4bff)
![20240704_3-2](https://github.com/Stellarium/stellarium/assets/173982253/19b174a7-7164-4bab-ac27-1723deb9c400)

"Highlight all the objects of the selected list" is shown when Move mouse cursor on Button "Add object".

"Clear all the highlight objects" is shown when Move mouse cursor on Button "Remove object".

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
* Operating system: Win7 32bit

...By the way, I feel that toolTip messages is blink in this window.
Maybe it's just my imagination.

(Sorry, I can not speak English very well.)

thank you.

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed.
Thank you very much.

**Comment by alex-w** [comment]
Thanks for good feedback!
