### ISSUE TITLE
Exoplanets Plugin is not shown in native language.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3798]
### Expected Behaviour
  Detection method is shown in native language.

### Actual Behaviour
  Detection method is shown in English.

### Steps to reproduce

1. Start Exoplanets Plugin.
2. Show Exoplanets Plugin Configuration window.
3. Show Table.

![20240706_1-1](https://github.com/Stellarium/stellarium/assets/173982253/9dabc247-d224-4415-9840-ab7b2f202b07)
![20240706_1-2](https://github.com/Stellarium/stellarium/assets/173982253/9aff42bb-45bd-4c3f-b79b-d0d429641e81)

Please, look at most right column (D.M).

If detection method by 1 way, method is shown in native language.

If detection method are by 2 or more way, method is shown in English instead of native language.

example
EN:"Radial Velocity"
ES:"Velocidad Radial"
FR:"Vitesse radiale"

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed.
Thank you very much.

**Comment by alex-w** [comment]
Thanks for good feedback!
