### ISSUE TITLE
Astronomical calculation window: Another object selected.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3799]
### Expected Behaviour
  Dark nebulae B34 is selected in sky.

### Actual Behaviour
  Star B34 is selected in sky.

### Steps to reproduce

1. Show Astronomical calculation window.
2. Show WUT.
3. Select a category.
   Select "Dark nebulae".
4. Select object "B34", and double click.

![20240706_2-1](https://github.com/Stellarium/stellarium/assets/173982253/a6216a55-2967-4f99-aeee-5acc9cf031fa)

Dark nebulae B34 in AUR.
Star B34 in FOR.
These object have no relation.

By the way,
When input "B34" in Search window, Dark nebulae B34 is only selected.

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed.
Thank you very much.

**Comment by alex-w** [comment]
Thanks for good feedback!
