### ISSUE TITLE
Astronomical calculations(Phenomena) strange toolTip message

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3801]
### Expected Behaviour
Valid range: +0&deg; 00' 00"..+20&deg; 00' 00"
is shown.

### Actual Behaviour
Valid range: -0&deg; 01' 00"..+0&deg; 01' 00"
is shown.

### Steps to reproduce

1-1. Show Astronomical calculations window.
1-2. Show Phenomena
1-3. Move mouse cursor on the InputBox.

Valid range: -0&deg; 01' 00"..+0&deg; 01' 00"
is shown.
![20240707_1-1](https://github.com/Stellarium/stellarium/assets/173982253/d682290c-31c9-43d8-a56e-1c1ccc608e7d)

Strangely...

2-1. Change "Program language" to other language in Configuration window.
2-2. Change "Program language" to English in Configuration window.
2-3. Show Astronomical calculations window.
2-4. Show Phenomena
2-5. Move mouse cursor on the InputBox.

Valid range: +0&deg; 00' 00"..+20&deg; 00' 00"
is shown.
(it's right.)
![20240707_1-2](https://github.com/Stellarium/stellarium/assets/173982253/8babda14-9c4f-45f0-a6b4-25b31d81f793)

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed.
Thank you very much.

**Comment by alex-w** [comment]
Thanks for good feedback!
