### ISSUE TITLE
(modern IAU) Constellation line different IAU web site's one.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3806]
### Expected Behaviour
Constellation line dose not through "&sigma; And".

### Actual Behaviour
Constellation line through "&sigma; And".

### Steps to reproduce

1. Show "Sky and viewing options" window.
2. Show "Sky Culture".
3. Select "Modern(IAU)".
4. Show constellation lines.
![stellarium-001](https://github.com/Stellarium/stellarium/assets/173982253/fa8cd71a-9003-4c6d-bcf6-1241d044866d)

Constellation line through "&sigma; And".

However, Constellation line dose not through "&sigma; And" in IAU WEB Site.
https://www.iau.org/static/public/constellations/gif/AND.gif

/Stellarium/skycultures/modern_iau/constellationship.fab

And 20 677 3092 3092 5447 5447 9640 113726 116631 116631 116805 116805 116584 116584 116805 116805 116631 116631 1473 1473 2912 2912 3092 3092 2912 2912 5447 5447 4436 4436 3881 3881 5434 5434 7607 3092 3031 3031 3693 3693 4463

This bug can fixed follows.
2 lines(116631 to 1473 , 1473 to  2912) changed 1 line(116631 to 2912)

And 19 677 3092 3092 5447 5447 9640 113726 116631 116631 116805 116805 116584 116584 116805 116805 116631 116631 2912 2912 3092 3092 2912 2912 5447 5447 4436 4436 3881 3881 5434 5434 7607 3092 3031 3031 3693 3693 4463

By the way, there are 3 duplicate lines.

...3 duplicate lines deleted.

And 16 677 3092 3092 5447 5447 9640 113726 116631 116631 116805 116805 116584 116631 2912 2912 3092 2912 5447 5447 4436 4436 3881 3881 5434 5434 7607 3092 3031 3031 3693 3693 4463

There are some duplicate lines in other constellations.

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by alex-w** [comment]
@3domennotry thanks for fix: https://github.com/Stellarium/stellarium/commit/4eac64d78ec9e3288b3eab95256cd61fffb0dd17

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed in stellarium-24.2-623f996-qt5-win64.exe.

(I have both environments win7 32bit and win7 64bit.
The file "constellationship.fab" not included in stellarium-24.2-623f996-patch-qt5-win32.exe.
And 32bit win7 Full packages(stellarium-24.2-623f996-qt5-win32.exe) is not release.)

Thank you very much.
