### ISSUE TITLE
Time in HH:mm:ss format

### ISSUE THREAD

**Issue by jalil1408** [Stellarium/stellarium#381]
How can I show Rise, Set and Transit times as HH:mm:ss?

**Comment by gzotti** [comment]
You cannot. While seconds could be given for transit, they make no sense with unpredictable atmospheric conditions during rise and set.

**Comment by jalil1408** [comment]
I suggest to add these options **Configuration** window:

**Time Format** : HH:mm | HH:mm:ss | ...
**Date Format** : dd/MM/yyyy | day dd month yyyy | ...
**Coordinates Format** : DMS | DecimalDegrees
