### ISSUE TITLE
TextUserInterface PlugIn display bug

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3813]
### Actual Behaviour
HTML tag shown.

### Steps to reproduce

1. Start TextUserInterface Pugin.
2. Set "Toggle TUI object info" in Keyboard Shortcuts window.
![20240714_1-1](https://github.com/user-attachments/assets/14784460-a548-429c-9a45-b7c3b85d26ef)

3. Select Moon or Sun or Planet.
![20240714_1-2](https://github.com/user-attachments/assets/490d3f2e-89fa-4f0d-8fe3-7e8c3dc6c4f6)
![20240714_1-3](https://github.com/user-attachments/assets/e12b5eef-894c-44e5-9058-69842eb77f02)

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by alex-w** [comment]
@3domennotry please share your `config.ini` file

**Comment by 3domennotry** [comment]
thank you for reply
[config.zip](https://github.com/user-attachments/files/16229683/config.zip)

**Comment by 3domennotry** [comment]
Sorry.
I write mistake "System".
The correct is stellarium-24.2-98544be-patch-qt5-win32.exe +  Stellarium version: stellarium-24.2-qt5-win32.exe.

**Comment by alex-w** [comment]
@gzotti, please check this bug. It was introduced in commit 8e409308062f82cb9d225d0ce9b56f80ac57e032, and I'm not sure that I correct understand how it should work.

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed.
Thank you very much.
