### ISSUE TITLE
EQmod in stellarium

### ISSUE THREAD

**Issue by patrickmattie** [Stellarium/stellarium#3814]
Hi,

My stellarium is working now, but I'm having issues with the 3 aligment points. Whenever im done setting everything up and I start the first alignment, EQmod slews not even close to the star I want it too. My coördinates are correct, but whenever I look at the EQmod coördinates the longitude is in east and west and the lattitude is in north and south (see images). The coördinates in stellarium are the other way around. Is this something I can fix or is this standard and i need to use other coördinates? If there is anything else i need to do please tell me, thanks.

![image](https://github.com/user-attachments/assets/84d3731b-fd27-4db8-9123-497090b16151)
![image](https://github.com/user-attachments/assets/fc8f8925-e940-4f82-bc49-f45c9a274c92) --> O is east

**Comment by 10110111** [comment]
> Lengte is longitude en breedte is latitude, but I don’t think it matters

It's actually the only thing that matters here. You've now confirmed that Stellarium's labels are correct, while in EQMOD they are wrong. And indeed, if you look into EQMOD's user guide, you'll see a screenshot in the *Initial Setup* section that shows Latitude (in English) above Longitude.

So just switch places of your numbers to match the corrected labels and, ideally, also report the wrong translation to EQMOD.

**Comment by patrickmattie** [comment]
So it will fix it when it’s in English? Or can I just switch the coordinates of what I have now?

**Comment by 10110111** [comment]
You can just swap the coordinates assuming the labels are swapped. The labels themselves don't affect functionality, they are just text for the user (and a misleading one).

**Comment by patrickmattie** [comment]
I will do that thank you!
