### ISSUE TITLE
Oculars plugin Limit magnitude is not autochanged Solar system body.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3817]
### Expected Behaviour
Limits magnitude is automatically changed in "SSO".

### Actual Behaviour
Limits magnitude is not automatically changed in "SSO".

### Steps to reproduce
It maybe not bug.

1. Start Oculars Plugin.
2. Checked "Auto-limit stellar magnitude" in Oculars Plugin config window.
![20240719_1-1](https://github.com/user-attachments/assets/7421e81b-0298-4d3c-ae26-1f76b5a658fa)

3. Checked "Limit magnitude" and input number 6.5 in "Sky" in "Sky and viewing options window".
![20240719_1-2](https://github.com/user-attachments/assets/b7f54905-8437-449b-88a5-a98eb22b2096)

4. Checked "Limit magnitude" and input number 6.5 in "DSO" in "Sky and viewing options window".
![20240719_1-3](https://github.com/user-attachments/assets/d3615537-ff35-4101-80c2-4daa7fc445e1)

5. Checked "Limit magnitude" and input number 6.5 in "SSO" in "Sky and viewing options window".
![20240719_1-4](https://github.com/user-attachments/assets/66486bfe-6424-4bde-9e3d-d7c5e73d55ab)

6. Select celestial object.
7. Ocular view.

Limit magnitude is automatically changed in "Sky".
![20240719_1-5](https://github.com/user-attachments/assets/bf9107b7-7f26-46c2-815c-644698501e31)

Limit magnitude is automatically changed in "DSO".
![20240719_1-6](https://github.com/user-attachments/assets/2ee28f33-97a2-4082-956f-730c0552ee3b)

However, limit magnitude is not automatically changed in "SSO".
![20240719_1-7](https://github.com/user-attachments/assets/1848a96c-7d1d-45e2-b5d0-1acb0b015235)

By the way, my telescope's(11.4 cm) limit magnitude is about 12.1 by Official Catalog in Vixen.
However, result is 13.55 by Oculars Plugin.
![20240719_1-8](https://github.com/user-attachments/assets/1f37bdd7-75bc-429c-a43d-b01fce954800)

Which is correct?

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
  + stellarium-24.2-98544be-patch-qt5-win32.exe
  + stellarium-24.2-623f996-patch-qt5-win32.exe

* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by gzotti** [comment]
Just not implemented yet, but should be simple copy-pastes from the other cases. Note that the limiting magnitude formulae for stellar objects (point source) are different from extended objects. 

It's funny you ask whether our data are better or worse than the manufacturer's claims. Whether manufacturer's claims or our models taken from the literature are more accurate can best be checked by observing limiting cases.

**Comment by 3domennotry** [comment]
Thank you for reply and always thank you.
Sorry I didn't write enough.

In Japan, usually, Telescope's limit magnitude formula is follow:

result = 6.0 + 2.5 * LOG(（D / 7.0）^2 )

6.0 : limit magnitude by naked eye in dark sky
7.0 : eye's diameter in dark sky
D: telescopes's diameter

Therefore, 114mm Telescope's limit magnitude is about 12.05
(Rounded off in Vixen catalog, 12.1)


/plugins/Oculars/src/Oculars.cpp
line 3279

Oculars plugin's formula is follow:
result = 4.5 + 4.4 * LOG(D)
D: telescopes's diameter
(article http://adsabs.harvard.edu/abs/1997JBAA..107...82N)

Therefore, 114mm Telescope's limit magnitude is about 13.55

Which formula is correct?
The results are similar to the formula usually used in Japan.

Unfortunately, it cannot be verified completly.
Because, There are terrible light pollution in Japan.

In dark sky area( 50 km away from my home town), I can found 4.5 mag stars by naked eye.
And about 10.5 magnitude stars can be found by this telescope.

From experience...
3.5 mag by naked eye, 9.5 mag by telescope.
4.0 mag by naked eye, 10.0 mag by telescope.
4.5 mag by naked eye, 10.5 mag by telescope.

Maybe, If I can found 6.5 mag stars by naked eye, I can found 12.5 mag stars by telescope

This is my personal opinion.
It would be great if these formulas could be selected.

thank you.

**Comment by alex-w** [comment]
> In Japan, usually, Telescope's limit magnitude formula is follow:
> 
> result = 6.0 + 2.5 * LOG(（D / 7.0）^2 )
> 
> 6.0 : limit magnitude by naked eye in dark sky 7.0 : eye's diameter in dark sky D: telescopes's diameter
> 
> Therefore, 114mm Telescope's limit magnitude is about 12.05 (Rounded off in Vixen catalog, 12.1)

What is the source of formula? 

> 
> /plugins/Oculars/src/Oculars.cpp line 3279
> 
> Oculars plugin's formula is follow: result = 4.5 + 4.4 * LOG(D) D: telescopes's diameter (article http://adsabs.harvard.edu/abs/1997JBAA..107...82N)
> 
> Therefore, 114mm Telescope's limit magnitude is about 13.55
> 
> Which formula is correct? The results are similar to the formula usually used in Japan.

As far as I know, all formulae for limiting magnitudes where you can see only aperture of telescope based an experience, and it may have variance for location/weather conditions.

**Comment by 3domennotry** [comment]
dear alex-w

https://www.stargaze.co.jp/engwhat.html
https://www.stargaze.co.jp/order3/SpecReading.html

According to this website:
{
formula 1.
"m = N + 5 log D"
N:8.8
D: telescope diameter (inch)

formula 2.
"m = N + 5 log (D1/D0) "
N: 6.0
D0:7.0
D1: telescope diameter (mm)

These formula's result is similar.

For dealers,
Most of the calculations are based on these formulas.

However, Over the years, the constants have changed.
}

Sorry, I do not know formula 1.

"6.0 + 5 log (D1 / 7.0) "
"6.0 + 2.5 * LOG(（D / 7.0）^2 )".
These formula's result is same.

thank you.

**Comment by 10110111** [comment]
> Which formula is correct?

There's not a single definition for this. E.g. [1] reads:

> Most of these proposed criteria are of the form:
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*m&nbsp;=&nbsp;N&nbsp;+&nbsp;5*&nbsp;log(*D*),&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1)
> where *m* is the limiting magnitude for a telescope with aperture *D* (in inches) and *N* is some normalization constant. <...> Any such formula will produce a value which is correct to within one or two magnitudes; however, for most applications this accuracy is too poor. This class of formulae is hopelessly naive because many effects are not included, of which magnification and sky brightness effects are most important.

Note that first, the constant 5 is for *D* specified in inches. And then that, as the text says, the formula itself is rather imprecise.

I didn't check whether the Oculars plugin's formula is correct though, just posted this bit FWIW.

### References

1: Schaefer, B. E.. ["Telescopic limiting magnitudes"](http://adsbit.harvard.edu/cgi-bin/nph-iarticle_query?bibcode=1990PASP..102..212S&db_key=AST&page_ind=0&plate_select=NO&data_type=GIF&type=SCREEN_GIF). Astronomical Society of the Pacific, Publications (ISSN 0004-6280), vol. 102, Feb. 1990, p. 212-229.

**Comment by gzotti** [comment]
We could allow selection of various models, plus addition of a "fudge factor" for empirical corrections by the single user. Is it worth the effort? Is the fudge addition just a constant or an arbitrary polynomial (or log?) function of the model's result? Who would ever develop and verify such model?  IIRC Schaefer had effects of diameter, obstruction, sharp vision, age, and a few more included. (I am off my main environment, so don't have it with me. ) All these models are for guidance, but you will gain experience only by own observation.

**Comment by 3domennotry** [comment]
OK. I never check the "Auto-limit stellar magnitude" checkbox on the Oculars settings page.
Instead, I created a script to do so.

Disappointingly...
I can't turn off the useless display in the upper right corner.
![stellarium-002](https://github.com/user-attachments/assets/cdf1844d-a89a-4f95-8cb4-e907f440c4ff)

The script cannot run automatically when switching to the eyepiece.

I envy those who do not feel uncomfortable with the current formula.
I have no expensive telescope, no good eye, no excellent sky, nothing to match this formula.

I can not speak English very well.
If I have been rude, I apologize.

thank you.

**Comment by gzotti** [comment]
Ah, we don't even use Schaefer's model yet. Suggestion: 2.5 options with another RadioButton. 

* m=[C]+[W]*log(D). Take D from telescope data, use DoubleSpinBoxes for C and W in GUI, add reset button to fill C and W from North's paper. Note that log(x^2)=2*log(x), or log(a/b)=log(a)-log(b), so the Japanese formula (or similar ones) can be met with different constants C, W. Details can go into the User Guide. 
* Implement Schaefer's model from sky brightness/light pollution, telescope data (obstruction!), magnification, experience, age, ...

**Comment by 3domennotry** [comment]
Disappointingly, I don't use it.

m=[C]+[W]log(D)
I want to get the same result as this formula "m = 6.0 + 5 * log (114 / 7)".

D is automatically specified, 114 (my telescope)
I can specified C and W.
C = 6.0.
W = 5 / (log(114) / log(114/7)) = 2.945704587

If I used another telescope(60mm),
W = 5 / (log(60) / log(60/7)) = 2.62366098

Every time I need a different value.


By the way, I forget binocular.

For binoculars, a different formula is used.
The results of this formula are even more amazing.

According to this formula, we found 12.41 mag star by 5.0cm binocular in dark sky.

Light pollution affects this formula.
If light pollution is max, we found 5.31 mag star by 5.0cm binocular.

I don't believe that is possible.

https://global.vixen.co.jp/en/product/38068_8/
In Japan, nobody calls them binoculars. I call "bino-telescope".
This "bino-telescope" has 126mm diameter and limiting magnitude is 12.3 .

Already, I solved this problem. I used my script.

However,
If you are willing to spend your valuable time, I suggest follow:
The magnitude can be entered directly each telescope( and binocular).


By the way, I made another discussions "about finder".
https://github.com/Stellarium/stellarium/discussions/3822

This discussion may possibly be relevant.

Thank you.

**Comment by gzotti** [comment]
we will not add limiting mag data to the instruments, but implement models from qualified sources. My last note was what we (developers) could probably implement by end of the year. Whenever anybody steals his own time instead of going out observing. 

A 126mm bino refractor is not what we mean when specifying "binoculars". Just configure that as regular telescope. "Binoculars" in the ordinary sense are things like 8x40, 10x50, 12x60, handheld with neck strap. Try to use the 126mm without a tripod...

**Comment by alex-w** [comment]
binoculars or bino-telescopes has other formula for limiting magnitudes

**Comment by 3domennotry** [comment]
I have confirmed that this bug( limit magnitude is not automatically changed in "SSO" ) has been fixed.
Thank you very much.

I think it is good that the discussion ("Telescope's limit magnitude formula") is also closed.
