### ISSUE TITLE
Ecliptic line position is wrong

### ISSUE THREAD

**Issue by Feb991** [Stellarium/stellarium#3820]
The ecliptic line position is wrong.

For example, it shows the path of the Sun like on the equinox on the current date (21/07/2024). See figure 1.

Moreover, its position changes while modifing the time on the same date. In figure 2 I've just changed the time and the ecliptic changed.

![Figure 1](https://github.com/user-attachments/assets/2df2fb87-8338-48a2-81fe-02ae9ba3a844)
![figure 2](https://github.com/user-attachments/assets/4c797909-f1c9-450e-9152-414837ed9efa)

**Comment by 10110111** [comment]
Looks correct. The ecliptic is not the geocentric trajectory of the Sun, it's the plane of the Earth's orbit around the Sun. In Stellarium it's depicted by (I think) an in-plane line at 1 AU from the observer. Of course, if the observer rotates with the Earth, the line will also shift with respect to the azimuth/altitude grid, just as the Sun and the stars do.

**Comment by gzotti** [comment]
The ecliptic line is very correct. Please read an astronomical introductory book.
