### ISSUE TITLE
I want to ask for access so that I can be allowed to create a JavaScript version of Stellarium which is almost the same as Stellarium desktop

### ISSUE THREAD

**Issue by testori1972** [Stellarium/stellarium#3824]
because Stellarium is open-source so it can be distributed to the web version of Stellarium

**Comment by 10110111** [comment]
Why do you need access if you can just make your own fork?

**Comment by gzotti** [comment]
Please, not another port for reasons of 'yet another programming language'! Remember the fate of Stellarium for Java. (Sun Java!) Created when Stellarium was still small enough, development was apparently given up shortly after completion, around 2010 (?) Features of 0.8.2 or so. Their website is too broken to find any downloads. (https://stellarium4java.org/)

Actually there is already Stellarium for web, the current JavaScript/C/WebAssembly version. 

Why not put your energy and creativity in improving the desktop version? Our JavaScript scripting functionality can probably be improved, e.g, by re-introducing a pause() function. Or tackle any of 250+ open issues. Fix the TelescopePlugin problems and earn a noticeable bonus.

**Comment by gzotti** [comment]
Superseded by #3834
