### ISSUE TITLE
I am creating Stellarium-Web for NPM

### ISSUE THREAD

**Issue by testori1972** [Stellarium/stellarium#3834]
EDIT (GZ): This used to be the title:
so because I just installed the eslint package to check for errors, and I managed to copy delta t, sidereal time, planet pluto, etc., we used other people's vendor data such as stellarium mobile, astronomy-engine, etc. to make it more accurate because the cpp programming language is complicated

and I copied from Stellarium C++ and other vendor data such as astronomy-engine, stellarium-mobile to the new JavaScript version of the Stellarium repository, because it is open-source so it can be distributed to other repositories with different programming languages ​​such as JavaScript, even though the WASM version is didn't help and had to use webgl which made the device very slow url: https://github.com/testori1972/Stellarium-Web

**Comment by 10110111** [comment]
So what's the issue here?

**Comment by gzotti** [comment]
Can you give a clear 1-line (<10 words) title to the issue, and formulate what you want to say in the issue text? Does the issue concern us and our repository? Or is it something to be discussed under Discussion?

Do you think it is wise to call your new repository Stellarium-Web, given the fact that Stellarium-Web is the name of a well-known existing, successfully working project that has not been invented by you? What exactly will be the benefit of your development? Why would anybody want to use your Stellarium-Web next to the working Stellarium-Web? Is this just to confuse people? Would you make a picture editor and call it PhotoShop?

If you take things from Stellarium and just port them to another language, you must adhere to the same license: GPL. You cannot switch to MIT. And you cannot simply overwrite a copyright note when you are just changing programming language, but the algorithm (including function names) can still be seen from the previous version. This is plagiarism.

**Comment by testori1972** [comment]
The old version of Stellarium Web uses WebGL which causes the cellphone to be slow, and I want to publish this to npm with the latest version. If you want to use WebGL, you can customize it yourself

**Comment by gzotti** [comment]
If you want to start a desktop planetarium project to run in a web browser based on Node.js, just start a new project with a proper new name. Don't confuse people with re-using the existing name Stellarium-Web. 

When you don't edit and change the issue title to something clearer, I will do it in a few minutes. 

And actually this is nothing to be discussed as _issue_ in the repository of the C++ version when it does not directly have to do with the actual desktop C++ version (like a bug report, feature wish, ...).
