### ISSUE TITLE
double_stars.ssc : RA and Dec are shift.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3835]
### Actual Behaviour
RA and Dec are shift.

For example: &theta; Orionis is not shown(out of screen).

### Steps to reproduce

1. Start Script double_stars.ssc.

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
  + stellarium-24.2-98544be-patch-qt5-win32.exe
  + stellarium-24.2-623f996-patch-qt5-win32.exe

* Operating system: Win7 32bit

In this script, current RA and DEC were used.
(I think that maybe it is middle position.)

line28 to 47
e.g.		  ["03h46m45.16s", "+24d35m44.5s",

line74
		core.moveToRaDec(doublestar[j][0], doublestar[j][1]);

current RA and DEC shifts day by day.

This is my personal opinion.

1. 
current RA and DEC are not use.
J2000.0 RA and DEC are use.

2.
Return to the date and time of those coordinates.
(Not sure if this is possible with scripts.)

3.
Calculate middle position.

This is sample.

&theta; Ori:
center of four &theta;1 Ori might be better than brightest &theta;1 Ori C.
As same as Mizar, etc...

&epsilon; Lyr :
I created a calculation method for the "double-double" mode.
However,
HIP 91919 A and HIP 91919 B have the same value(RA, Dec).
HIP 91926 C and HIP 91926 D have the same value(RA, Dec).

(Sorry, I can not speak English very well.)

thank you.

**Comment by 3domennotry** [comment]
sample is.
[20240801_1-1.txt](https://github.com/user-attachments/files/16448255/20240801_1-1.txt)

**Comment by gzotti** [comment]
It seems some coords (at least RA for theta Ori) are wrong. And using J2000 coordinates may be not enough when magnification is high, given shifts by proper motion, nutation and aberration. Maybe it is better to actually search for those stars by name. Or switch off nutation and aberration. And yes, use `moveToRaDecJ2000()` when dealing with J2000 coordinates.

**Comment by alex-w** [comment]
Proposed solution depend on issue #3836

**Comment by 3domennotry** [comment]
I fixed this bug. 
I don't think this bug is related to issue #3836.
Please, try and use this file.
[double_stars.ssc.txt](https://github.com/user-attachments/files/16676357/double_stars.ssc.txt)

**Comment by alex-w** [comment]
Not a bug, but solution will not work as expected due issue #3836

**Comment by 3domennotry** [comment]
I have confirmed in stellarium-24.3-qt5-win32.exe.

Roughly fixed.
Unfortunately, problem remains.

These RA and Dec, what is designated?

Maybe, many star pairs are designated in the middle position.

But,
Case of &theta; Ori: &theta;2 Ori is out of Screen.
Case of &zeta; Crv: &zeta; Crv is Center of screen.

![20240801_2024_0923_1](https://github.com/user-attachments/assets/8c86c90c-7132-4e72-a000-6669bea5a142)
![20240801_2024_0923_2](https://github.com/user-attachments/assets/2a6e4f2e-754a-4c5b-8ac2-140ffab7265c)
![20240801_2024_0923_3](https://github.com/user-attachments/assets/8017d3e4-5325-4676-ac55-416e297b33a0)
![20240801_2024_0923_4](https://github.com/user-attachments/assets/f2301060-44dc-4e5a-88e7-46c087e9bd11)

Why don't you adopt the calculation method I created?

thank you.

**Comment by alex-w** [comment]
> Why don't you adopt the calculation method I created?

They will not work correctly due specifics of Search Engine

**Comment by 3domennotry** [comment]
This script(I made) is working fine in my environment(win7).
Does it mean that it does not work correctly in other environments?

thank you.

**Comment by alex-w** [comment]
> This script(I made) is working fine in my environment(win7). Does it mean that it does not work correctly in other environments?

The stars HIP 20648 A, HIP 26221 A, HIP 26235 E, HIP 60157 A, HIP 91919 A, HIP 91919 B, HIP 91926 C, HIP 91926 D, HIP 100027 A will not searched in the scripts nor Search Engine.

**Comment by 3domennotry** [comment]
"search engine specifications" and "issue #3836"
Soory, I finally figured out what it means.

My script, perhaps ignoring the alphabetical part of the HIP.
This isn't sufficient.
