### ISSUE TITLE
show deep sky object compulsorily?

### ISSUE THREAD

**Issue by choir2001** [Stellarium/stellarium#3837]
Stellarium Android and IOS APP
Now I have to zoom in to see the deep sky object, which is not convenient. Sometimes it shows randomly. Is there any switch that shows deep sky object compulsorily regardless of zoom level?

**Comment by gzotti** [comment]
>Stellarium Android and IOS APP

This is the place to discuss issues with the desktop editions. The mobile programs are different, have been developed by other developers, and have their own support channel visible in the respective "about" menus.
