### ISSUE TITLE
Hawaiian Starlines - broken link to Hawaiian Star Compass Landscape

### ISSUE THREAD

**Issue by papakilohoku** [Stellarium/stellarium#384]
In using the Hawaiian Starlines Starlore, you can use the Hawaiian Star Compass Landscape was not located at the hyperlink located in the star lore description (of Hawaiian Starlines). It is pointing to a dead link. Please advise on the location of the landscape in order to download for use.

**Comment by alex-w** [comment]
Please check the latest beta - 0.18.2.6 (0.90.0.16289)
