### ISSUE TITLE
Telescope control moves by itself (only in app, not on mount)

### ISSUE THREAD

**Issue by BreaK-X0** [Stellarium/stellarium#3841]
Hello, I connect my mount through ASCOM and with its respective driver (syncscan app) and everything is fine, I can control the mount perfectly with stellarium, but after a few minutes, or sometimes just seconds, the program slows down enormously and the indicator of where the telescope is pointing starts to move (only virtually, never physically) and gets lost on the horizon. I have reinstalled drivers, stellarium, ASCOM and tried everything.

A solution would be very useful.

Thank you very much for creating this wonderful tool!

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <24.2?>
* Operating system: <W11>
* Graphics Card: <Nvidia GeForce 4060 laptop, last drivers>
* Screen type (if applicable): 3440 x 1440

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
There are several reported but unidentified issues with TelescopeControl on Qt6-based builds, and no voluntary developers to solve them. Does that also happen with a Qt5-based build?

**Comment by BreaK-X0** [comment]
I couldn't tell you, my level is not that high, I'm sorry... :(

It is as if stellarium disconnected from the mount, however I still have control with SynScan Pro in Windows

I just verified that stellarium drops from 20-30 FPS to 0.5 FPS!!

**Comment by gzotti** [comment]
Can you download, install and run the version from stellarium.org that is announced "Windows 7+"? This is the Qt5-based build. If this works, it is yet another manifestation of TelescopeControl issues with the Qt6-based version.

**Comment by BreaK-X0** [comment]
I finally found the problem! It seems that the IPs conflict or something. When working with the wifi module and assigning it an IP (maybe because 192.168.4.1 for the mount and 192.168.1.1 for the router are out of range). When I disconnect the LAN cable from the laptop and remain disconnected from the internet, it works perfectly.

It's a pain, but at least I won't have distractions (internet). 

I hope this at least helps to improve or maybe someone knows a solution to the problem.

Thanks a lot gzotti for your help!

**Comment by gzotti** [comment]
No, that is not related. 192.168.4.1 and .1.1 don't generally see each other. If the mount is 192.168.4.1, your PC would have to be another device in the 192.168.4.* range. Or if you need to be in 192.168.1.* to connect to the Internet, your telescope would need to be configured to use a different address in the 192.168.1.* range.

**Comment by gzotti** [comment]
@BreaK-X0 your problem seems solved. Can we close this?

**Comment by BreaK-X0** [comment]
Gracias!
