### ISSUE TITLE
skycultures tongan file mismatch.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3842]
### Steps to reproduce

(install_dir)/skycultures/tongan/

description.en.utf8
line65
Monuafe Meissa

star_names.fab
line6
 25336|_("Monuafe")

HIP 25336 is &gamma; Ori.
http://simbad.u-strasbg.fr/simbad/sim-id?Ident=HIP%2025336

I do not know Meissa.
Maybe, it is &lambda; Ori.
http://simbad.u-strasbg.fr/simbad/sim-id?Ident=lam+ori
https://www.pas.rochester.edu/~emamajek/WGSN/IAU-CSN.txt

Which Monuafe?
&gamma; Ori or &lambda; Ori.
![20240805_1-1](https://github.com/user-attachments/assets/3dd7c3a3-0697-4328-85fe-a2d5c3014db7)

...And very tiny thing.
description.en.utf8
line63
Betelguese

Maybe, it is Betelgeuse.

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
  + stellarium-24.2-98544be-patch-qt5-win32.exe
  + stellarium-24.2-623f996-patch-qt5-win32.exe

* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by gzotti** [comment]
Yes, Meissa is IAU WGSN's approved name for &lambda; Ori, despite Allen's mentioning as error.
But we need to contact the SC's author. 
Betelguese is an obvious typo and can be fixed by us.

**Comment by alex-w** [comment]
Please use full package for testing sky cultures

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed in stellarium-24.2-19f4d98-qt5-win64.exe (full package).

(I have both environments win7 32bit and win7 64bit.
32bit win7 Full packages(stellarium-24.2-19f4d98-qt5-win32.exe) is not release.)

Thank you very much.
