### ISSUE TITLE
Cannot set time in api - Python

### ISSUE THREAD

**Issue by jdb130496** [Stellarium/stellarium#3843]
I am on Windows 11 machine and I have following python script to test setting of time, time rate:

```
import requests
STELLARIUM_URL='http://192.168.1.3:8090/api/main'
def set_time(julian_day,timerate):
    url = f"{STELLARIUM_URL}/time"
    data = {
        "time": float(julian_day),
        "timerate": float(timerate)
    }
    print(f"Request URL: {url}")
    print(f"Request Data: {data}")
    try:
        response = requests.post(url, json=data)
        print(f"Response Status Code: {response.status_code}")
        print(f"Response Content: {response.text}")
        response.raise_for_status()
        if response.text.strip() == "ok":
            return {"status": "success", "message": "Time set successfully"}
        else:
            return {"status": "error", "message": response.text}
    except requests.exceptions.RequestException as e:
        print(f"Error setting time: {e}")
        return {"status": "error", "message": str(e)}
```

# Example usage
julian_day = 2469344.171527778
timerate = 1.0
result = set_time(julian_day, timerate)
print(result)

I get following output:
>>> set_time(julian_day, timerate)
Request URL: http://192.168.1.3:8090/api/main/time
Request Data: {'time': 2469344.171527778, 'timerate': 1.0}
Response Status Code: 200
Response Content: error: invalid parameters, use time/timerate as double values
{'status': 'error', 'message': 'error: invalid parameters, use time/timerate as double values'}

Can you please look into what wrong am I doing? Why the error at the end? Even though response is 200.

Other details:
Python version: 3.12.4
Stellarium version: 24.2

**Comment by ilkant** [comment]
Just tested that with Stellarium 24.2.212-a42c6a0 and python 3.12.3 on Kubuntu 24.04. No errors.

$ python pythontime.py
Request URL: http://192.168.1.3:8090/api/main/time
Request Data: {'time': 2469344.171527778, 'timerate': 1.0}

I have no http server on my computer just now.

You can see your error message use time/timerate as double values. 
Just use double values.

**Comment by jdb130496** [comment]
Thank you for responding and sorry for the belated response. Actually I am on Windows 11 and using stellarium 24.2.0 (How did you get 24.2.212-a42c6a0?). I am using stable version obtained from stellarium website. Something has changed in the new Stellarium version which you are using. You built it on your own in Kubuntu? My copy pasted text from About tab in Stellarium:

Stellarium 24.2
Version 24.2.0
Based on Qt 6.5.3

I tried again and since url is dhcp auto alloted, it changed as I saw in remote plugin today. Accordingly I changed that part in  code:
``
import requests
STELLARIUM_URL='http://192.168.1.6:8090/api/main'
def set_time(julian_day,timerate):
    url = f"{STELLARIUM_URL}/time"
    data = {
        "time": float(julian_day),
        "timerate": float(timerate)
    }
    print(f"Request URL: {url}")
    print(f"Request Data: {data}")
    try:
        response = requests.post(url, json=data)
        print(f"Response Status Code: {response.status_code}")
        print(f"Response Content: {response.text}")
        response.raise_for_status()
        if response.text.strip() == "ok":
            return {"status": "success", "message": "Time set successfully"}
        else:
            return {"status": "error", "message": response.text}
    except requests.exceptions.RequestException as e:
        print(f"Error setting time: {e}")
        return {"status": "error", "message": str(e)}
        ``
        
        Still getting error while testing on the above example. As you can see, both parameters have been set as double:
        
        >>> julian_day = 2469344.171527778
>>> timerate = 1.0
>>> set_time(julian_day, timerate)
Request URL: http://192.168.1.6:8090/api/main/time
Request Data: {'time': 2469344.171527778, 'timerate': 1.0}
Response Status Code: 200
Response Content: error: invalid parameters, use time/timerate as double values
{'status': 'error', 'message': 'error: invalid parameters, use time/timerate as double values'}

Python Version: 3.12.5 (Updated to latest stable version available for Windows)
Stellarium version 24.2.0 (Checked again. No new version after this.)

I will try it again in archlinux as I have dual booting and post here the results.

**Comment by jdb130496** [comment]
Archlinux is also showing same results.

My stellarium details from About screen in Stellarium on Archlinux:

Stellarium 24.2
Version 24.2.0
Based on Qt 6.7.2

Python Version: 3.12.4

Copy pasted from terminal:

(.venv) [admin@archlinux-nvme Downloads]$ python
Python 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> STELLARIUM_URL='http://127.0.1.1:8090/api/main'
>>> def set_time(julian_day,timerate):
...     url = f"{STELLARIUM_URL}/time"
...     data = {
...         "time": float(julian_day),
...         "timerate": float(timerate)
...     }
...     print(f"Request URL: {url}")
...     print(f"Request Data: {data}")
...     try:
...         response = requests.post(url, json=data)
...         print(f"Response Status Code: {response.status_code}")
...         print(f"Response Content: {response.text}")
...         response.raise_for_status()
...         if response.text.strip() == "ok":
...             return {"status": "success", "message": "Time set successfully"}
...         else:
...             return {"status": "error", "message": response.text}
...     except requests.exceptions.RequestException as e:
...         print(f"Error setting time: {e}")
...         return {"status": "error", "message": str(e)}
... 
>>> julian_day = 2469344.171527778
>>> timerate = 1.0
>>> result = set_time(julian_day, timerate)
Request URL: http://127.0.1.1:8090/api/main/time
Request Data: {'time': 2469344.171527778, 'timerate': 1.0}
Response Status Code: 200
Response Content: error: invalid parameters, use time/timerate as double values
>>> print(result)
{'status': 'error', 'message': 'error: invalid parameters, use time/timerate as double values'}
>>> exit()

**Comment by jdb130496** [comment]
Even in Fedora Rawhide - the result is same:

>>> import requests
>>> STELLARIUM_URL='http://192.168.1.184:8090/api/main'
>>> def set_time(julian_day,timerate):
...     url = f"{STELLARIUM_URL}/time"
...     data = {
...         "time": float(julian_day),
...         "timerate": float(timerate)
...     }
...     print(f"Request URL: {url}")
...     print(f"Request Data: {data}")
...     try:
...         response = requests.post(url, json=data)
...         print(f"Response Status Code: {response.status_code}")
...         print(f"Response Content: {response.text}")
...         response.raise_for_status()
...         if response.text.strip() == "ok":
...             return {"status": "success", "message": "Time set successfully"}
...         else:
...             return {"status": "error", "message": response.text}
...     except requests.exceptions.RequestException as e:
...         print(f"Error setting time: {e}")
...         return {"status": "error", "message": str(e)}
...         
>>> julian_day = 2469344.171527778
>>> timerate = 1.0
>>> set_time(julian_day, timerate)
Request URL: http://192.168.1.184:8090/api/main/time
Request Data: {'time': 2469344.171527778, 'timerate': 1.0}
Response Status Code: 200
Response Content: error: invalid parameters, use time/timerate as double values
{'status': 'error', 'message': 'error: invalid parameters, use time/timerate as double values'}

**Comment by 10110111** [comment]
Where is it documented that JSON is expected by the Remote Control plugin? It isn't AFAICT. The following works for me instead:

```python
def set_time(julian_day,timerate):
    url = f"{STELLARIUM_URL}/time"
    data = "time="+str(julian_day)+"&timerate="+str(timerate)
    print(f"Request URL: {url}")
    print(f"Request Data: {data}")
    try:
        response = requests.post(url, data=data)
        print(f"Response Status Code: {response.status_code}")
        print(f"Response Content: {response.text}")
        response.raise_for_status()
        if response.text.strip() == "ok":
            return {"status": "success", "message": "Time set successfully"}
        else:
            return {"status": "error", "message": response.text}
    except requests.exceptions.RequestException as e:
        print(f"Error setting time: {e}")
        return {"status": "error", "message": str(e)}
```

**Comment by gzotti** [comment]
Yes, most of the API direct commands were created for speed, not elegance. We could show a few more examples in other languages in the User Guide if somebody works them out.

**Comment by jdb130496** [comment]
Thank you @10110111 

That resolved. I am a newbie and still learning. Did not know about json alternative.
