### ISSUE TITLE
Orbit mode "Planets plus selected"

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#3849]
**Is your feature request related to a problem? Please describe.**
I would like to show the orbit of one object in relation to the orbits of the major planets. 

**Describe the solution you'd like**
We need an orbit selection option: Orbits of the major planets (color coded) which is not mutually exclusive to "selected object only". 

**Describe alternatives you've considered**
Currently it seems this is just not possible. Show thousands of orbits, or one and only. 

**Additional context**
Would be helpful to show where that selected object's orbit lies. Maybe add "last N selected objects", so that more than one can be shown at a time. The planet orbits give the relevant context, obviously.

**Comment by ElonVampire** [comment]
收到！
