### ISSUE TITLE
Ojibwe Constellation Art

### ISSUE THREAD

**Issue by pchis13** [Stellarium/stellarium#3851]
I just downloaded the newest version of Stellarium (24.2) last week specifically to gain access  to the Ojibwe constellation art. Online Stellarium tutorials in YouTube show that option, however Ojibwe is no longer in the Sky Culture dropdown menu. How can I get access to this option? Thank you for your help.

**Comment by gzotti** [comment]
https://stellarium.org/skycultures/2022/10/16/CopyrightIssue.html
