### ISSUE TITLE
if skycultures asterism_names.eng.fab is nothing, the list in the search window is not cleared.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3853]
### Expected Behaviour
Asterism list in the search window is cleared.

### Actual Behaviour
Asterism list in the search window is not cleared.

### Steps to reproduce

1. Show "Sky and viewing options" window.
2. Show "Sky Culture".
3. Select the Sky Culture with asterisms. ex. "Modern"
![20240815_1-1](https://github.com/user-attachments/assets/3158b4a1-5bf9-4812-bf25-dd68076739f3)

4. Close Search window.
5. Select the Sky Culture without asterisms. ex. "Maya"
6. Show  Search window.
![20240815_1-2](https://github.com/user-attachments/assets/f9e36d25-c7a9-467b-9051-6485d96cb36c)

Several skycultures folder not inluded "asterism_names.eng.fab".
If "asterism_names.eng.fab" is nothing, Bugs will happen.

Dummy(empty) file is needed.

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
  + stellarium-24.2-98544be-patch-qt5-win32.exe
  + stellarium-24.2-623f996-patch-qt5-win32.exe

* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by alex-w** [comment]
Please use full package for testing sky cultures

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed.
Thank you very much.
