### ISSUE TITLE
skyculture khoi-san : There are a few spelling errors in the files.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3854]
### Steps to reproduce

(install_dir)/skycultures/khoi-san/

description.en.utf8
line 6
Their husband (Aldeberan)

Maybe, it is Aldebaran.
The previous line in this file reads "Pleiades, Aldebaran and Orion".

description.en.utf8
line7
lion (Betelgueuse)

constellation_names.eng.fab
line3
003	"Betelgueuse and Orion's Belt"		_("The Lion stalking Zebra")

Maybe, its is Betelgeuse.
According to constellationsart and this skyculture's star_names.fab.
![20240815_2-1](https://github.com/user-attachments/assets/73e21432-2543-4e8c-bea7-d03ea4c8a3b5)

I don't know how to contact the author.
So I report it here.

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
  + stellarium-24.2-98544be-patch-qt5-win32.exe
  + stellarium-24.2-623f996-patch-qt5-win32.exe

* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by alex-w** [comment]
Please use full package for testing sky cultures

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed in stellarium-24.2-19f4d98-qt5-win64.exe (full package).

(I have both environments win7 32bit and win7 64bit.
32bit win7 Full packages(stellarium-24.2-19f4d98-qt5-win32.exe) is not release.)

Thank you very much.
