### ISSUE TITLE
Tint landscapes orange and red at sunrise/sunset

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3855]
A small but visually beautiful tweak would be for landscape panoramas to progressively tint yellow, orange and red once the Sun rises or sets, to adjust for the different coloring of the scenery.

Could also be applied to 3D Sceneries.

Values could possibly be called from the current extinction reddening tweak.

**Comment by 10110111** [comment]
It's not small if we don't want to put it in by hand, hard-coding the gradients into the scenery.

It's theoretically possible to implement using the techniques of ShowMySky, but there may be some issues, kludges for which were implemented in Bruneton's demo (see e.g. [this discussion](https://github.com/ebruneton/precomputed_atmospheric_scattering/issues/28)).

**Comment by 10110111** [comment]
Hmm, or did you just mean that simply the direct lighting color should change? This may not be hard indeed.

**Comment by Atque** [comment]
> Hmm, or did you just mean that simply the direct lighting color should change? This may not be hard indeed.

Yes, I was thinking something like that. A few other planetaria have it, such as Starry Night.

**Comment by gzotti** [comment]
Just using a "tinted" sunlight color (same as used for e.g. the sun glare) for the landscape is easy. However, I feel the reddening should go away with the sun hiding behind the landscape. Likewise not that hard. In some scenes it may look weird, like the "Trees", with the sun blinking through the trees, it will then blink "white/yellow", depending on whether the sun is hidden behind landscape pixels. I am preparing a PR to test this.
