### ISSUE TITLE
Solar eclipse problems in stellarium

### ISSUE THREAD

**Issue by testori1972** [Stellarium/stellarium#3860]
If you want to calculate the position of the solar eclipse, width of the umbra, sun/moon diameter ratio, etc. "setUseTopocentricCoordinates" must be false, if not false, what is happening, is the position inaccurate including the position of the solar eclipse which I stated above in one of the scripts: "SolarEclipseComputer.cpp"

**Comment by 10110111** [comment]
> "setUseTopocentricCoordinates" must be false

It's already being set to false whenever required, and restored afterwards.

> which I stated above in one of the scripts: "SolarEclipseComputer.cpp"

There's not a single line that you authored in this file. And nothing in the file refers to any scripts.

**Comment by gzotti** [comment]
@testori1972 is this a question (which should at best go into discussions) or an issue report (for which you should fill in the issue report template)? In the latter case, show an actual false result or other reproducible indication of a "Solar eclipse problem" created by running version 24.2.

**Comment by gzotti** [comment]
Nothing will come from here...
