### ISSUE TITLE
there is two Room in Japanese Moon Stations?

### ISSUE THREAD

**Issue by kevinKaiF** [Stellarium/stellarium#3873]
<img width="998" alt="image" src="https://github.com/user-attachments/assets/994788c6-7063-428c-aa30-7834619e2c60">
there is two Room, chinese word "房宿".
right Room should be Encampment，chinese word "室宿"

**Comment by gzotti** [comment]
If it is a translation issue, you can suggest better translations on Transifex. The English terms are "Chamber" for the left and "Room" for the right.

**Comment by freemanli** [comment]
"Room", this term appears in
skycultures/chinese/constellation_names.eng.fab:6, 
skycultures/chinese_medieval/constellation_names.eng.fab:122, skycultures/japanese_moon_stations/constellation_names.eng.fab:15
In Chinese this term means "房宿", but in Japanese it means "室宿".  If we change the translation of "Room", it will also change the Chinese Culture. That's the problem.

**Comment by gzotti** [comment]
@alex-w do we have contextualized names, optionally, per-skyculture? Then the entries in the Japanese Lunar Stations SC can be marked explicitly as Japanese to avoid a possible name conflict.

**Comment by alex-w** [comment]
> @alex-w do we have contextualized names, optionally, per-skyculture? Then the entries in the Japanese Lunar Stations SC can be marked explicitly as Japanese to avoid a possible name conflict.

I can add context for Japanese SC tonight

**Comment by alex-w** [comment]
@freemanli @kevinKaiF please check translations at Transifex

**Comment by freemanli** [comment]
confirmed, thank you.
