### ISSUE TITLE
Some hyperlinks in plugin descriptions lead to dead SourceForge-hosted pages

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#3874]
This can be found in `plugins/Supernovae/src/gui/SupernovaeDialog.cpp` and `plugins/TelescopeControl/src/gui/TelescopeDialog.cpp`. I don't know what the current location of these pages is (are they in the SUG now?), so I just report them here:

http://stellarium.sourceforge.net/wiki/index.php/Historical_Supernovae_plugin#Light_curves
http://stellarium.sourceforge.net/wiki/index.php/Telescope_Control_%28client-server%29
http://stellarium.sourceforge.net/wiki/index.php/Telescope_Control#Third_party_applications

Also, there appear to be some similarly broken SF links on the GitHub-based Wiki, e.g. [here on the main page](https://github.com/Stellarium/stellarium/wiki/).

**Comment by gzotti** [comment]
Thanks, yes that should be cleaned out. This website hosting the protocol also has links to the old wiki. I am not 100% sure we have copied everything to the SUG. @alex-w , did we? Or was something in the old wiki which is now lost.
