### ISSUE TITLE
Segmentation fault on latest Manjaro Linux

### ISSUE THREAD

**Issue by unelsson** [Stellarium/stellarium#3875]
### Expected Behaviour

Stellarium starts with an UI

### Actual Behaviour
Stellarium UI does not open, console gives the following.
```
StelGLWidget constructor
StelGraphicsScene constructor
QRhiGles2: Failed to create temporary context
QRhiGles2: Failed to create context
Failed to create QRhi for QBackingStoreRhiSupport
QPainter::begin: Paint device returned engine == 0, type: 1
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::worldTransform: Painter not active
QPainter::save: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::setWorldTransform: Painter not active
QPainter::end: Painter not active, aborted
Segmentation fault (core dumped)
```

### Steps to reproduce
Any of the following:
A) Using the latest Manjaro as of 9.3.2024, use any AUR package of Stellarium
B) Build from git, then run at console
Note: Running stellarium with --opengl-compat (or -C) (OpenGL Compatibility profile), or --low-graphics (or -L)  (Force low-graphics mode) results in the same error message.

### System
* Stellarium version: d81dc49aa42d0b3235987cfa4e33b87084ae8df5
* Operating system: Linux Manjaro XFCE
* Graphics Card: GeForce GTX 1060 6GB
* Default output of `qmake --version` is Qt 5.15.14, but I also have 6.7.2 installed

### Logfile 
[log.txt](https://github.com/user-attachments/files/16841287/log.txt)

**Comment by alex-w** [comment]
Please install qt6-wayland package

**Comment by unelsson** [comment]
> Please install qt6-wayland package

I have that installed. I also double checked from CMakeCache.txt that the build targets are Qt6 (not Qt5).

**Comment by alex-w** [comment]
@unelsson please check solution from here: https://forum.manjaro.org/t/okular-and-other-qt-applications-do-not-create-any-visible-windows/163130/25

**Comment by unelsson** [comment]
> @unelsson please check solution from here: https://forum.manjaro.org/t/okular-and-other-qt-applications-do-not-create-any-visible-windows/163130/25

This solution does not solve the issue. However, the thread mentions some people have had problems with a package called kvantum-theme-matcha, but that is a dependency of a manjaro-xfce-settings, which I'm not very fond of removing.

I also have no problems with other Qt6 programs, such as Okular.

**Comment by unelsson** [comment]
I now tried removing kvantum-theme-matcha and manjaro-xfce-settings, used the environment variables hinted in the Manjaro forum link above, ran build commands:
```
cmake -DCMAKE_INSTALL_PREFIX=/opt/stellarium ../..
make -j4
```

I'm still getting the same issue.

**Comment by 10110111** [comment]
Are you actually using Wayland, or is it X11? The log doesn't appear to indicate this. For Wayland, what does `eglinfo` say? For X11, what does `glxinfo` say?

**Comment by unelsson** [comment]
Oh darn. I didn't realize there had been an update to some critical parts of the windowing system, but I had not rebooted. Everything else worked, so this possibility somehow just escaped me. That X11->glxinfo tipped me off. Reboot and now it works.

Thanks for you help and sorry I took your time here. Closing the issue.
