### ISSUE TITLE
Screen text overlap of different plugins

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#388]
_Original report by Khalid AlAjaji:_ https://bugs.launchpad.net/stellarium/+bug/1042265

This is a minor issue now. When using the angle measure plugin while information is displayed by the observability plugin, it displays instruction text that overlap the observability info.

An issue to think about is handling texts displayed simultaneously by different plugins on the screen.

**Comment by pacastro** [comment]
Hi, I'm having text overlap within the same plugin. The text displayed by Observability "Today's ephemeris" overlaps with the other observability info available.

I'm using a retina Macbook with OSX 10.14, same bug in fullscreen or windowed mode:

<img width="1136" alt="screen shot 2018-10-23 at 1 29 54 am" src="https://user-images.githubusercontent.com/35240993/47377509-d7add900-d6cb-11e8-953d-9f080500b77c.png">

**Comment by gzotti** [comment]
Must be a Mac specific issue. What happens if you decrease font size?
On WIn10, it scales neatly in the lower left corner.

**Comment by alex-w** [comment]
Please check this snapshot: https://github.com/Stellarium/stellarium-data/releases/download/beta/Stellarium-0.90.0.16357.dmg
