### ISSUE TITLE
i run Windows 11 Home, 64 bit.      Stellarium 24.2  connects to the ASCOM driver GEMINI telescope, but I cannot move the telescope from STELLARIUM.

### ISSUE THREAD

**Issue by Herbstmond** [Stellarium/stellarium#3881]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
As has been reported numerous times, Qt6-based builds have a problem with ASCOM. You can try a Qt5-based build.

**Comment by Herbstmond** [comment]
can you translate this into English for a windows layperson?

**Comment by gzotti** [comment]
Read the Release Notes.

**Comment by Herbstmond** [comment]
Thank you for the info! Hiow do I find a Qt5 based buildSent from my iPhoneOn Sep 4, 2024, at 22:16, Georg Zotti ***@***.***> wrote:﻿
As has been reported numerous times, Qt6-based builds have a problem with ASCOM. You can try a Qt5-based build.

**Comment by Herbstmond** [comment]
Thank you so much!MichaelSent from my iPhoneOn Sep 5, 2024, at 13:12, Georg Zotti ***@***.***> wrote:﻿
Your favourite search engine will provide a multitude of links if you search for "qt5 based stellarium".
