### ISSUE TITLE
 Solar eclipse map are messy in many dates

### ISSUE THREAD

**Issue by worachate001** [Stellarium/stellarium#3894]
### Expected Behaviour
Clean eclipse map.

### Actual Behaviour

It seems the rewrite of AstroCalc/Eclipses in version 24.2 introduced a bug, exporting messy maps for many events.

For example:
1955-06-20
1955-12-14
1956-06-09
...
1973-12-24
1974-06-20
...
2030-06-01
2030-11-25
2031-05-21
2039-06-22

Maps for these dates in version 24.1 are fine.

### Steps to reproduce
Producing a table of solar eclipses and export eclipse map for some dates.

### System
* Stellarium version: 24.2
* Operating system: Ubuntu 24.04

**Comment by alex-w** [comment]
@10110111 it's troubles for vectors:
```
Found an odd number of values of Q while searching for JD of zeta sign change: 3
Unnormalized vector (xi,eta,zeta) found: (0.20844945960752612, 0.00081857771390425604, -1.0112264332987522); Q = 359.99943319107308°
Unnormalized vector (xi,eta,zeta) found: (0.20851056603873813, 0.00062944208033333116, -1.0528205897388283); Q = 359.99990842668194°
Unnormalized vector (xi,eta,zeta) found: (0.20853966115490954, -0.01833002602237066, -5.1639714056051496); Q = 0.00028341593573156853°
Unnormalized vector (xi,eta,zeta) found: (0.20857689875692836, -0.0028912584867579749, -1.8158820566521119); Q = 0.00068947882344303304°
Found an odd number of values of Q while searching for JD of change in number of solutions: 1
Found an odd number of values of Q while searching for JD of change in number of solutions: 3

```

**Comment by 10110111** [comment]
There remain some cutouts in the lines, but at least the core issue with extra senseless lines is fixed.
