### ISSUE TITLE
After threaded Solar System PR merge linking on Linux g++-11 fails

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#3896]
I get the following error on Ubuntu 20.04, g++ 11.4.0-2ubuntu1~20.04:
```
/usr/include/tbb/task_arena.h:449: undefined reference to `tbb::interface7::internal::task_arena_base::internal_current_slot
```

If I comment out `#include <execution>`, linking succeeds. Also note that I get this:
```
-- Checking that std::execution::par is supported by the C++ library - NO
```
This is despite my compiler supporting this functionality. It just needs to link against `libtbb` (via `-ltbb` linker option) for linking to succeed.

**Comment by alex-w** [comment]
Ubuntu 20.04 has EOL date April, 2025 - so, probably we can start dropping support it.

**Comment by alex-w** [comment]
@10110111 what about adding 
```
#ifdef STD_EXECUTION_KNOWN
#include <execution>
#endif
```
Is it fix the linking problem?

**Comment by gzotti** [comment]
There may be systems which work well but cannot be upgraded for stupid reasons. Just last night I upgraded my old (2012) notebook to Ubuntu 24.4. Bad mistake. My Geforce M580GTX needs the nvidia 390 driver which is no longer supported on Ubuntu 24. This laptop is still running great for almost all practical applications (and the old top-end card is still strong for Stellarium), and next year (end of Win10) I had expected using Linux exclusively as "lucky successor".  This came unexpected. Now I have  640x480 resolution. Unusable. I can probably remove the dual-boot and revert to Win10. :-( Or reinstall U22 and attach a warning sticker to the screen bezel to never ever run do-dist-upgrade.

**Comment by 10110111** [comment]
> EOL date April, 2025 - so, probably we can start dropping support it.

It's more than half a year ahead, which means it will happen after two more Stellarium releases.

> Is it fix the linking problem?

It's not a fix, it's a workaround that leads to the parallelization being disabled on a system that actually supports it. The proper solution is to link against TBB, both the CMake test and the Stellarium binary.

Actually, from a bit of googling it seems that this depends on whether `libtbb-dev` is installed. On my machine lots of packages depend on it, so I can't check. Also, maybe in the case the package is lacking we'll get no parallelization, which would also be no good.

**Comment by alex-w** [comment]
> I get the following error on Ubuntu 20.04, g++ 11.4.0-2ubuntu1~20.04:

Hmm... standard version of g++ in Ubuntu 20.04 is 9.3.0 and it can be updated to version 10.5.0 - https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=g%2B%2B

**Comment by 10110111** [comment]
> can be updated to version 10.5.0

Use the [ubuntu-toolchain-r/test PPA](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test). It contains various useful backports of the toolchain.

**Comment by alex-w** [comment]
> > can be updated to version 10.5.0
> 
> Use the [ubuntu-toolchain-r/test PPA](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test). It contains various useful backports of the toolchain.

This is good point for developers, but bad point for users :(

**Comment by 10110111** [comment]
> This is good point for developers, but bad point for users

What do you mean? We don't require new gcc, do we?

**Comment by alex-w** [comment]
@10110111 please install packages `libtbb-dev` and `libtbb2` and try it again...

**Comment by 10110111** [comment]
I have them installed from the beginning...

**Comment by alex-w** [comment]
OK, right now I have installed Ubuntu 20.04.6 into VirtualBox (clean installation). Added GCC 9.4, 10.5, 11.4, 13.1.

Of course I see in cmake output for all of these compilers follow line:
```
-- Checking that std::execution::par is supported by the C++ library - NO
```

GCC 9.4, 10.5 & 13.1 - everything pass OK
GCC 11.4 - I see the linking issue

So, at least in standard environment I see no problem for building Stellarium and probably this is not our problem.

**Comment by 10110111** [comment]
Have you installed `libtbb-dev`?

**Comment by alex-w** [comment]
> Have you installed `libtbb-dev`?

Yes, of course

**Comment by 10110111** [comment]
Does the following link well for you?
```
g++-11 -o test -xc++ - <<< $'#include <execution>\nint main(){}'
```
What about this?
```
g++-11 -o test -xc++ - -ltbb <<< $'#include <execution>\nint main(){}'
```

**Comment by alex-w** [comment]
> Does the following link well for you?

 ```
 g++-11 -o test -xc++ - <<< $'#include <execution>\nint main(){}'
 g++-13 -o test -xc++ - <<< $'#include <execution>\nint main(){}'
 ```

No success

> What about this?
 
```
g++-11 -o test -xc++ - -ltbb <<< $'#include <execution>\nint main(){}'
g++-13 -o test -xc++ - -ltbb <<< $'#include <execution>\nint main(){}'
```

Both OK

**Comment by 10110111** [comment]
> No success

Well, this is the way our code is currently organized: `<execution>` is included, but `-ltbb` is not specified.

And you say Stellarium builds with GCC 13 but not 11. How so? Could you print your linking command line (you can see it by `make VERBOSE=1` or `cmake`'s `--verbose` flag when building)?

**Comment by alex-w** [comment]
A black magic...
[build.log.txt](https://github.com/user-attachments/files/17027383/build.log.txt)
[cmake.log.txt](https://github.com/user-attachments/files/17027387/cmake.log.txt)
[log.txt](https://github.com/user-attachments/files/17027388/log.txt)

**Comment by alex-w** [comment]
This is very weird, but I always see in the log follow line:
`-- Checking that std::execution::par is supported by the C++ library - NO`

Up to Clang 19 and this is sad

**Comment by alex-w** [comment]
Why we didn’t used cmake macro [check_cxx_symbol_exists](https://cmake.org/cmake/help/latest/module/CheckCXXSymbolExists.html)?

**Comment by 10110111** [comment]
Well this is because of the lack of TBB in libraries list, the exact problem I'm facing, just with less severe manifestation. Try using `-DCMAKE_EXE_LINKER_FLAGS=-ltbb`, and I think you'll get a YES.

**Comment by 10110111** [comment]
> Why we didn’t used cmake macro [check_cxx_symbol_exists](https://cmake.org/cmake/help/latest/module/CheckCXXSymbolExists.html)?

This wouldn't help the problem we're facing. And now this may even be suboptimal to switch to this, since I guess we need to also check whether we need to link against `libtbb`.

**Comment by alex-w** [comment]
A sad news - the modern stellarium can be build in Ubuntu 20.04, but we cannot prepare deb-packages for U20.04 due fast_float (at least I didn't find a way to add libfast-foat-dev or using newest compiler for U20.04 on launchpad.net)

**Comment by 10110111** [comment]
Why can't you just use the version from CPM linked statically?

**Comment by alex-w** [comment]
> Why can't you just use the version from CPM linked statically?

Isolated environment - no possible connect to outer hosts to download source code

**Comment by 10110111** [comment]
Maybe you could put the source into the tree just for the build, possibly in a separate branch (having made sure that its license is compatible with this)?
