### ISSUE TITLE
0.15.2: mirror distortion gives odd result

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#390]
_Original report by doctor-pat:_ https://bugs.launchpad.net/stellarium/+bug/1690601

 0.15.2: Turning on mirror distortion gives odd result in Mac/el Capitan. (Macbook Pro Retina)
 Sky blocky gray and white.
 Going back to 0.15.1 - which has quirks but still works.

In 0.15.1, if you save with the mirror distortion selected, quit and relaunch, the whole stellarium window is reduced to the lower left corner of the laptop screen, but at least you can start up as fisheye and turn on mirror (but just don't save the mirror as default).

**Comment by Doctor-Pat** [comment]
IT IS NOT ONLY ON MAC!

As I commented previously it ALSO now fails in Windows 10 laptops.  If you save and close with mirror distortion turned on, then reopen, it reopens in the lower left corner of the window with undistorted view in the rest.  If, while you are fixing this, you could POSSIBLY create a single keystroke to toggle mirror on an off, we could save with mirroring off and then quickly turn it on at launch.  That would at least save several seconds of looking at the fisheye each time we start it up.  Interestingly, I checked the latest beta Stellarium on a HD Asus ROG and it fails too (first time it has failed on a 1920x1080 laptop).  I have 300+ customers with this issue, and loads of teachers, that are all stuck on 15.1

Screenshot from Mac:  High Sierra:
<img width="1280" alt="screenshot 2018-07-27 15 09 32" src="https://user-images.githubusercontent.com/43441732/46079163-f6b45c00-c15b-11e8-97da-c759f9224a01.png">

Screenshot from Windows 10 4K resolution laptop (Dell)
![dell_img_3785](https://user-images.githubusercontent.com/43441732/46079458-cd480000-c15c-11e8-9812-7ac94af80576.jpg)

Photo of screen from Windows 10 Asus ROG 1920x1080 screen:  0.90.16
![asus_img_4035](https://user-images.githubusercontent.com/43441732/46080516-c2db3580-c15f-11e8-90c1-982aa96591c8.jpg)

**Comment by gzotti** [comment]
Must confirm on Win10/FullHD. 
There may be several intermingled oddities here. I may try to solve one that neither involves 4k nor Macs.

**Comment by Doctor-Pat** [comment]
Great!  Thanks!!
Sometimes it does make a difference if you are connected to a projector when you do the save and restart…  then it sometimes behaves itself.

**Comment by gzotti** [comment]
@alex-w , @guillaumechereau, @xalioth  there are viewporteffects called "none" and "sphericMirrorDistorter", which perform the obvious. But it indicates there either have been more possible effects in ancient prehistory (pre-2008), or something which was planned and still could be extended. If this is in effect just a Boolean flag, we should make it one.

**Comment by guillaumechereau** [comment]
I just pushed an attempt at fixing this (44a84366c0d79369dae465942a34401da5b0133d).
On my iMac it makes things a bit better.  I am not sure if that is enough to fix all the issues though.

**Comment by Doctor-Pat** [comment]
Yeah, that makes sense….
I’m not sure I can edit my source code without messing it up…
let me know if there is a beta package I can test...

**Comment by gzotti** [comment]
It at least fixes the problem which I saw on FullHD screen, thanks. Now next beta (weekend?) must be checked on 4k hardware.

**Comment by gzotti** [comment]
Again, @guillaumechereau, @xalioth, @alex-w is there any reason to not convert the viewporteffect={"none"|"sphericMirrorDistorter"} to a Boolean? Would allow simple Property handling, including hotkey etc. Or do you see need for another effect?

**Comment by guillaumechereau** [comment]
If I am correct the string argument was introduced by Florian.  Maybe he planed to add other values at some point?

**Comment by alex-w** [comment]
Yes, the string argument was introduced by Fabien to add other values, but it was a long time ago.

**Comment by gzotti** [comment]
Ah, not Florian, but Fabien, after GSOC2012. On the other hand, StelViewportEffect subclassing opens the possibilities for distortion for VR glasses, right? Then the option (and GUI) should be converted to named enums. (And some volunteers could implement more effects ...)

**Comment by alex-w** [comment]
Please check the latest beta - 0.18.2.6 (0.90.0.16289)

**Comment by Doctor-Pat** [comment]
Hey, GREAT NEWS!!
I installe the latest build on Mac - works perfectly!
On Asus HD:  works great BUT when I save the settings and the view, it comes back with only a 60 degree FOV. Have to reset again and save again and it works.
On Dell it works great but again, I save the view and the settings, it comes back correctly BUT it goes back to 60 degree FOV. I changed to 180 FOV, saved, reopened, still 60 FOV.  then I went in and edited the config file and all is well.
So it’s stll a tiny bit flakey on saving to the config but at least it’s full screen now.

YOU ARE AWESOME!!

**Comment by alex-w** [comment]
Are you pressed "Save View" button for saving FOV settings?

**Comment by Doctor-Pat** [comment]
Yes, definitely I had saved the view before quitting.
By the way, it appears there is a keystroke to go directly to 180 FOV.  
It appears to  be the number 1 in the list, but  how do you click it?

**Comment by gzotti** [comment]
I just found the view settings were not stored to the config file directly. Until now you would have to press "Save view", then "Save settings". Now "Save view" really works independently.

**Comment by marsanta11** [comment]
When Stellarium is opened and spherical mirror distortion is applied it opens very well but it does not save the distortion view and when I open it again the error occurs. In windows 10 profesional.

**Comment by am17107** [comment]
@gzotti hello gzotti i can help you
