### ISSUE TITLE
Translated months in AstroCalc

### ISSUE THREAD

**Issue by taurasg1** [Stellarium/stellarium#3907]
![image](https://github.com/user-attachments/assets/37ad76f6-ef85-419d-a1ab-2ce3b6a3da67)

Month names (short) are not translated in astronomical calculations graphs. 
No untranslated strings like 'Oct' or 'May' found at Transifex

![image](https://github.com/user-attachments/assets/f825fc77-369d-43c2-a807-8bd218b10b62)

**Comment by 10110111** [comment]
Looks like these strings are not reloaded on the fly. If you restart Stellarium having saved your chosen language, they should get fixed.

**Comment by gzotti** [comment]
Indeed, the axes (esp. horizontal time axis) are created with current locale, and I see no clean way of reconfiguring them apart from probably fully deleting and recreating all charts. Or user decides on his/her language and restarts the program.

**Comment by gzotti** [comment]
Yes, like that!

**Comment by taurasg1** [comment]
![image](https://github.com/user-attachments/assets/f12d8122-bb6f-4649-b9fb-947fd1f9a9a3)
Fixed. Thanks.
