### ISSUE TITLE
Selected object information are not saved.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3910]
### Expected Behaviour
Selected object information are saved.

### Actual Behaviour
Selected object information are not saved.

### Steps to reproduce

1. Show Configuration window.
2. Show Information Tab.
![20240923_3-1](https://github.com/user-attachments/assets/7acb4708-67d8-454d-84fa-784bacefc493)

3. Select "Selected object information".
![20240923_3-2](https://github.com/user-attachments/assets/cd52211e-eb4f-49dd-8497-7ab10137b6af)

4. Click save settings button in Main Tab.
5. Quit Stellarium.

6. Start Stellarium.
7. Show Configuration window.
8. Show Information Tab.
![20240923_3-3](https://github.com/user-attachments/assets/13959a07-487c-49aa-86bb-762355d11117)

### System
* Stellarium version: stellarium-24.3-qt5-win32.exe

* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed in stellarium-24.3-600edc8-patch-qt5-win32.exe.
Thank you very much.

**Comment by Jon-guy30** [comment]
Do I open a new issue or report here because I'm experiencing this bug currently on 24.3 qt6 x64 Windows 11?

**Comment by gzotti** [comment]
Why do you think that?

The bug was present in 24.3 which you are using. 
The bug has reportedly been fixed and is therefore no longer present in any current beta or in 24.4.

**Comment by 3domennotry** [comment]
I have now confirmed that this bug is also fixed in stellarium-24.3-600edc8-qt5-win64.exe.
At least, it is fixed in the 32-bit and 64-bit versions of Win7.

**Comment by Jon-guy30** [comment]
Has anyone tested this on Windows 11 'cause I'm on Win11 and it's still there...

Selected custom information
![Skärmbild (77)](https://github.com/user-attachments/assets/f8cbea25-6b19-48da-9e43-387b8279c2cc)
Confirming it's selected
![Skärmbild (80)](https://github.com/user-attachments/assets/b7dee712-1134-4c4c-9bb4-98d6ed9da7e3)
Closed and relaunched the program
![Skärmbild (81)](https://github.com/user-attachments/assets/9e161461-c4bf-4148-bc84-3ec7ec7a3362)

**Comment by gzotti** [comment]
Can you read?

**Comment by Jon-guy30** [comment]
> Can you read?

Oh, I'm sorry, didn't see you said beta 24.4. Ummm. I hope you don't mind me asking where does one obtain the beta? Quickly checked don't see it anywhere.
