### ISSUE TITLE
Stellarium 24.3 can't save eclipses as KML file on Astro Calculator

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#3916]
### Expected Behaviour
Stellarium couldn't export eclipses as KML on Astro Calculator Eclipses. For example a file type KML.
See Stellarium 24.3 User Guide 4.6.8. page 50.

### Actual Behaviour
I see no KML option when I export eclipse data in Astro Calculator. There are Microsoft Excel and CSV, but no KML.

### Steps to reproduce
1. Start Astro Calculator
2. Go to tab Eclipses
3. Calculate for example Sun eclipses
4. Try to save them as KML filetype.

### System
* Stellarium version: <Stellarium 24.3+ (v24.3.268-59c27ab [master]>
* Operating system: <Kubuntu 24.04>
* Graphics Card: <MSI GeForce GT 1030/PCIe/SSE2 2GH LF OC, OpenGL 3.3, driver 3.3.0 NVIDIA 525.147.05>
* Screen type LG 34GK950F 3440x1440

### Logfile 
[log.txt](https://github.com/user-attachments/files/17170947/log.txt)

**Comment by 10110111** [comment]
What would the single KML file contain for the bunch of eclipses being exported? You can export a KML map for each of them separately, but a single map for multiple eclipses doesn't seem to make sense.

**Comment by ilkant** [comment]
> What would the single KML file contain for the bunch of eclipses being exported? You can export a KML map for each of them separately, but a single map for multiple eclipses doesn't seem to make sense.

When I mar one eclipse and then try to save (export) there are no KML option.

**Comment by 10110111** [comment]
Select an eclipse, and _Export map..._ button will become active.

**Comment by ilkant** [comment]
> Select an eclipse, and _Export map..._ button will become active.

Ok. Thanks. FIrst I tried to local sun eclipses. There are no save to map.
