### ISSUE TITLE
Cannot configure telescope with NexRemote external software

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#392]
_Original report by Scott Loucks:_ https://bugs.launchpad.net/stellarium/+bug/1741322

Hello, I recently upgraded to vs 17 from vs 15 and lost telescope connection. I have a Nexstar GPS11 mount and I am connecting to the PC with NexRemote and usb to serial adapter. The Stellarium connection type is external, Nexstar compatible mount with jnow selected and startup button checked. When trying to connect the status reads: "connecting" however it never connects, just hangs there with same status.

Prior to this incident, I was successfully running this same exact setup with vs 15 with no issues. Maybe I have missed something on the configuration process but I cant find my mistake if I have. Stellarium is truly a superb software! I do hope this issue can be resolved.

Thank you -Scott

**Comment by gzotti** [comment]
I have not the right hardware to do anything about it. There may be an issue or not in Stellarium's classic telescope control plugin. OP wrote how he got his system running almost two years ago. Now we have ASCOM support. We can most likely close this.
