### ISSUE TITLE
Real time option not working after restart

### ISSUE THREAD

**Issue by freebrowser1** [Stellarium/stellarium#3922]
### Expected Behaviour
Clicking on the 'real time' button does not set real time on startup

### Actual Behaviour
Real time not working, i.e. the clock on the bottom bar does not tick seconds. 

### Steps to reproduce
Click on the 'real time' button
Click on 'Configuration window' and then both 'Save view' and 'Save settings'
Exit Stellarium
    Now in config.ini the values are correct:

startup_time_mode                         = actual
startup_time_stop                         = true

Start Stellarium again
Clock is not ticking so one has to manually click the real time button.

### System
* Stellarium version: 24,3
* Operating system: Ubuntu 22.04 LTS
* Graphics Card: ?

### Logfile 
[log.txt](https://github.com/user-attachments/files/17178293/log.txt)

**Comment by gzotti** [comment]
You configure startup_time_stop to disable real-time update. What is the time that is then used? Time  (within minute) of program launch, or something else?

**Comment by freebrowser1** [comment]
Time is indeed time of program launch, but the clock does not tick and it is 'paused'.

<img width="350" alt="Screenshot 2024-09-29 at 12 33 39" src="https://github.com/user-attachments/assets/efba4841-2a90-42dc-9421-a0edd0133c0e">

Here another log.

[log.txt](https://github.com/user-attachments/files/17178905/log.txt)

**Comment by alex-w** [comment]
I see a small shift of time in Stellarium in comparison with operating system (normal timerate and actual time are enabled)

**Comment by freebrowser1** [comment]
> I see a small shift of time in Stellarium in comparison with operating system (normal timerate and actual time are enabled)

What do you mean with 'timerate' ? That is zero because of the two vertical (pause) bars.
Which config.ini setting is this ?

**Comment by gzotti** [comment]
> You configure startup_time_stop to disable real-time update. 

This is at least what I understand in this flag.

**Comment by alex-w** [comment]
@freebrowser1 please share`config.ini` file

**Comment by freebrowser1** [comment]
> @freebrowser1 please share `config.ini` file

(added a .txt extension as .ini is not supported by github)
[config.ini.txt](https://github.com/user-attachments/files/17185475/config.ini.txt)
