### ISSUE TITLE
Selection menu display problem

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#393]
_Original report by henrysky:_ https://bugs.launchpad.net/stellarium/+bug/1286797

Selection menu display problem, some have problems while some not...see the image...
Mac OSX 10.9.2 with Stellarium 0.13.0 revision 6616 Intel HD graphics 4000

This problem cannot be reproduced with my Windows 7 with Stellarium 0.13.0 alpha 7.1 ATI Radon mobility 4300/4500 series

**Comment by guillaumechereau** [comment]
I just pushed a fix for this: disabling the rendering cache seems to fix the issue.

**Comment by martignoni** [comment]
I confirm that this fixes indeed the issue (tested with 0.19.0.16840 [master]) on macOS 10.13.6 (17G6030).

**Comment by martignoni** [comment]
For reference: attached video shows the bogus behaviour on released 0.19.0.

[Bug-#393.mp4.zip](https://github.com/Stellarium/stellarium/files/3045253/Bug-.393.mp4.zip)
