### ISSUE TITLE
ASCOM not selectable as "controlled by" in Telescope Control window

### ISSUE THREAD

**Issue by seedless76** [Stellarium/stellarium#3933]
### Actual Behaviour
ASCOM is not selectable
![image](https://github.com/user-attachments/assets/daddb7f2-8931-452c-9b7d-51b8450bb0bd)

### Steps to reproduce
Configuration->Plugins->Telescope Control->Configure->Add New Telescope

### System
* Stellarium version: 24.3
* Operating system: Windows 11 Pro
* ASCOM 6.6.1.3

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/user-attachments/files/17254976/log.txt)

**Comment by gzotti** [comment]
For two years we have now been flooded with reports that Qt6-based builds don't work nicely with Stellarium. If you hold the mouse cursor over the visibly disabled button (or even care to check in the User Guide), you can read what to do: Use a Qt5-based build.

**Comment by seedless76** [comment]
Sorry, I spent two day searching how to fix it but couldn't find any tip. Apologies.
