### ISSUE TITLE
CROOKED SATELLITE ORBIT LINES

### ISSUE THREAD

**Issue by JAY-Githb** [Stellarium/stellarium#3934]
### System
Windows 10

screenshot pasted here

![image](https://github.com/user-attachments/assets/202c4c6b-6413-4643-a4b0-1736d62f1780)

**Comment by JAY-Githb** [comment]
While this is being fixed, how can I get the previous 24.3 to install over this version?
Thanks.

**Comment by gzotti** [comment]
Just install it. Older releases can be found following the "all releases" link from stellarium.org. However, you need 24.2 to avoid the bug.

**Comment by gzotti** [comment]
The Qt5-based builds of 24.3 should also not be affected.

**Comment by ElonVampire** [comment]
收到！

**Comment by gzotti** [comment]
Not a complete fix: I avoid parallelisation when orbit lines are needed. If someone has better insight into the plugin's internals, please go ahead and sort out/avoid the use of static variables inside Satellite class.

**Comment by JAY-Githb** [comment]
Georg, as you suggested, I installed Qt5-based build of 24.3 instead of Qt6 for Windows 10.
That seems to be working.
Thank you.
Jay

**Comment by JAY-Githb** [comment]
I installed this version 

[ This is Stellarium 24.3+ (v24.3.323-6d70819 [HEAD]) - https://stellarium.org/ ] 

Lines are straight. 

Thank you. 

Jay Respler 
Advanced Business Machines Co. 
609-662-7438 
***@***.*** 
Monroe Township, New Jersey

**Comment by JAY-Githb** [comment]
Just checked it. 
Working well. 
Thank you. 

Jay Respler 
Monroe Township, New Jersey
