### ISSUE TITLE
skyculture arabic_lunar_mansions : There is a not match in the file.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3938]
### Steps to reproduce

(install_dir)/skycultures/arabic_lunar_mansions/

not match

description.en.utf8
Line54
&alpha;<sup>1</sup> Cap (Algedi)

Accroding to "https://www.pas.rochester.edu/~emamajek/WGSN/IAU-CSN.txt", Algedi is &alpha;<sup>2</sup> Cap.

These stars are double stars and can probably be separated by the naked eye.
&alpha;<sup>2</sup> Cap brighter than &alpha;<sup>1</sup> Cap.

By the way,
the following 4 stars are double stars that cannot be separated by the naked eye.

Line33
&gamma;<sup>2</sup> Ari

Line42
&gamma;<sup>1</sup> Leo

Line49
&beta;<sup>1</sup>  Sco

Line57
&zeta;<sup>2</sup> Aqr

There were no telescopes or binoculars in this era of sky culture.
I think that it should be described as &gamma; Ari, &gamma; Leo, &beta; Sco and &zeta; Aqr.

### System
* Stellarium version: stellarium-24.3-qt5-win32.exe
* stellarium-24.3-600edc8-patch-qt5-win32.exe

* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by alex-w** [comment]
@kajaji please check this report

**Comment by kajaji** [comment]
> α2 Cap brighter than α1 Cap.
Agree. α2 Cap should be used.

> I think that it should be described as γ Ari, γ Leo, β Sco and ζ Aqr.

For these, the problem is that when using Stellarium search window for γ Leo, β Sco and ζ Aqr it will give the info as custom objects without any proper names.

![Screenshot 2024-10-08 162032](https://github.com/user-attachments/assets/63611fea-ade0-4018-9812-837c905ed0ec)

**Comment by alex-w** [comment]
@kajaji please add numbers after greek letter ;)

**Comment by kajaji** [comment]
Yes, I know. I mean for @3domennotry  suggestion  that it should be described without numbers, then someone might face this issue.

**Comment by 3domennotry** [comment]
In this file, if you write something like "&gamma; Leo", people who see it will search for it as it is, and hit unrelated celestial bodies.
Is this what you mean?

**Comment by kajaji** [comment]
The search in Stellarium will point to a position very close to γ1 Leo, and will not give any info of the actual star.

![Screenshot 2024-10-08 202145](https://github.com/user-attachments/assets/4311bfa3-6f53-4b58-9c6f-d96db4f14045)

![Screenshot 2024-10-08 202236](https://github.com/user-attachments/assets/2711a2ed-8534-47db-aa04-e0cc15092a50)

**Comment by 3domennotry** [comment]
I think that this problem(result in search window) is not related to skyculture.
I think that SkyCulture description file should be true to the source.

About this problem(result in search window),

(install_dir)\Stellarium\stars\default\name.fab
 50583|γ1_Leo
 50583|γ2_Leo

I think we should add to this file.
 50583|γ_Leo

This problem will be solved.

Note that, the simultaneous notation of HR4058 and &gamma;1 Leo(not HR4058 but HR4057) in the above image is a separate issue.
https://github.com/Stellarium/stellarium/issues/3836

For reference.
https://simbad.u-strasbg.fr/simbad/sim-id?Ident=gam+leo
HIP 50583 = &gamma; Leo = 41 Leo

https://simbad.u-strasbg.fr/simbad/sim-id?Ident=HR+4057
gam Leo A = 41 Leo A = gam01 Leo = HR 4057

https://simbad.u-strasbg.fr/simbad/sim-id?Ident=HR+4058
gam Leo B = 41 Leo B = gam02 Leo = HR 4058

thank you.

**Comment by 3domennotry** [comment]
(install_dir)/skycultures/arabic_arabian_peninsula/

description.en.utf8

Line47
β1 Cyg (Albireo)

This is same issue.

**Comment by kajaji** [comment]
> (install_dir)/skycultures/arabic_arabian_peninsula/
description.en.utf8
Line47
β1 Cyg (Albireo)
This is same issue.

What is the issue here?

**Comment by 3domennotry** [comment]
This star is double star that cannot be separated by the naked eye.
There were no telescopes or binoculars in this era of sky culture.
I think that it should be described as "β Cyg".

**Comment by kajaji** [comment]
@alex-w I attach here the updated /skycultures/arabic_lunar_mansions/description.en.utf8 as .txt file. Please rename as .utf8, .utf8 extension is not supported to be uploaded.

[description.en.txt](https://github.com/user-attachments/files/17349891/description.en.txt)

**Comment by alex-w** [comment]
@kajaji thanks!

**Comment by 3domennotry** [comment]
Thank you ,However Line49 not fixed.
