### ISSUE TITLE
skyculture arabic_indigenous : There is a tiny error in the file.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3939]
### Steps to reproduce

(install_dir)/skycultures/arabic_indigenous/

description.en.utf8

Line5
&lt;a href="#footnote-1"&gt;[2]

&lt;a href="#footnote-1"&gt;[2] is not true.
Perhaps, &lt;a href="#footnote-2"&gt;[2] is true.

### System
* Stellarium version: stellarium-24.3-qt5-win32.exe
* stellarium-24.3-600edc8-patch-qt5-win32.exe

* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by alex-w** [comment]
@kajaji please check this report

**Comment by kajaji** [comment]
Yes,
<a href="#footnote-1">[2] should be  <a href="#footnote-2">[2]
Thanks

**Comment by kajaji** [comment]
Thanks
true, The reference should be to the 2nd footnote
