### ISSUE TITLE
Welcome to Stellarium Discussions!

### ISSUE THREAD

**Issue by brighttable** [Stellarium/stellarium#3940]
### Discussed in https://github.com/Stellarium/stellarium/discussions/1398

<div type='discussions-op-text'>

<sup>Originally posted by **alex-w** December  9, 2020</sup>
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.</div>

**Comment by brighttable** [comment]
Hi, I have Stellarium 24.3 (latest version) installed on my M2 Pro Mac mini. The issue: The menu at right-top is crippled. First, the configuration (tool) icon is cut off a little. Second, there is no way to change either sensor (camera) or telescope (lens) from the list. Highlighting does not work. Appreciate all help.

**Comment by alex-w** [comment]
Please attach `log.txt` file from Stellarium

**Comment by brighttable** [comment]
[Uploading log.txt…]()

**Comment by brighttable** [comment]
Did I do (attach) it correctly?

**Comment by alex-w** [comment]
Nope, sorry

**Comment by 10110111** [comment]
> Did I do (attach) it correctly?

You only posted a link to this same issue. If you're trying to do it via email, this might not be possible (at least images don't seem to be accepted by GitHub).

**Comment by 10110111** [comment]
Actually, from the text of the hyperlink it seems that you haven't waited until the log finishes uploading and submitted the comment.

**Comment by brighttable** [comment]
Ok, I will do it again and wait until finish uploading.
[log.txt](https://github.com/user-attachments/files/17292239/log.txt)

**Comment by alex-w** [comment]
Please remove `/Users/koafarwu/Library/Application Support/Stellarium` and run Stellarium again

**Comment by brighttable** [comment]
Ok, got it. Now how do I set the two menus on the left side to always open instead of requiring cursor-hitting? Also, do I need to "save" new settings before closing the app? Where? Thanks

**Comment by alex-w** [comment]
> Ok, got it. Now how do I set the two menus on the left side to always open instead of requiring cursor-hitting? Also, do I need to "save" new settings before closing the app? Where? Thanks

Please check small square buttons on the panels + F2 -> Main -> "Save settings".

In any way many questions will be resolve by Stellarium User Guide - https://stellarium.org/files/guide.pdf

**Comment by alex-w** [comment]
@brighttable could you say what version of Stellarium was installed previously?

**Comment by brighttable** [comment]
I don't really remember, but it was very very old.

**Comment by brighttable** [comment]
Thanks, alex-w. Everything is running well now after a lot of time searching for tips and studying guides.
