### ISSUE TITLE
Sky X sign glitch ?!

### ISSUE THREAD

**Issue by xSkein** [Stellarium/stellarium#3947]
I was looking at the sky in the app to find where the comet is turns out next to the sun there is some kind of x sign looking thing

Phone specs:
OS: Android 13
Package: com.noctuasoftware.stellarium_free
Package Version: 1.12.9 (11149)

Device: realme - RMX3085
Board: RM6785
Accelerometer: true
Compass: true
Gyroscope: true
GLES version: 3.2
Language: en_EG

![Screenshot_2024-10-11-15-21-23-65_c0112e866aafbdadcc5ff93fdb2d9e89](https://github.com/user-attachments/assets/9d0cabcd-fab9-427b-8559-5f28ef219e66)

**Comment by gzotti** [comment]
Although this report is in no way related to the desktop version of Stellarium, it has been reported numerous times. It is easily identified as a photographic artifact in the photographic all-sky survey, caused by reflection of a bright star nearby.
