### ISSUE TITLE
TimeZone for  "Baruun-Urt"  not found:  "Asia/Choibalsan"

### ISSUE THREAD

**Issue by hectorthemonk** [Stellarium/stellarium#3953]
### System
* Stellarium version: Stellarium 24.3+ (v24.3.281-600edc8 [stellarium-next]) 
* Operating system: Arch Linux rolling

### Logfile 
```
StelLocationMgr::loadCitiesBin(): TimeZone for  "Baruun-Urt"  not found:  "Asia/Choibalsan"
StelLocationMgr::loadCitiesBin(): Summary of unknown TimeZones:
"Asia/Choibalsan"
Please report these timezone names (this logfile) to the Stellarium developers.
```

**Comment by alex-w** [comment]
Please share info about your operating system

**Comment by hectorthemonk** [comment]
> Please share info about your operating system

Updated issue above.  Thanks!

**Comment by alex-w** [comment]
@hectorthemonk could you check and share version of installed `tzdata` package?

**Comment by hectorthemonk** [comment]
```console
$ pacman -Qs tzdata
local/tzdata 2024b-2
    Sources for time zone and daylight saving time data
```

**Comment by alex-w** [comment]
> ```
> $ pacman -Qs tzdata
> local/tzdata 2024b-2
>     Sources for time zone and daylight saving time data
> ```

Thanks! It's interesting, version 2024a of tzdata has Asia/Choibalsan time zone. I'll check what is happened between versions.

**Comment by hectorthemonk** [comment]
This might be relevant?

> Asia/Choibalsan is now an alias for Asia/Ulaanbaatar rather than
     being a separate Zone with differing behavior before April 2008.
     This seems better given our wildly conflicting information about
     Mongolia's time zone history.  (Thanks to Heitor David Pinto.)

From https://lists.iana.org/hyperkitty/list/tz-announce@iana.org/thread/IZ7AO6WRE3W3TWBL5IR6PMQUL433BQIE/

**Comment by alex-w** [comment]
Probably yes. Please check `/usr/share/zoneinfo/Asia` directory - it should contain symlink _Choibalsan_.

**Comment by hectorthemonk** [comment]
It contains a file:

```console
$ ls -la /usr/share/zoneinfo/Asia/Choibalsan 
-rw-r--r-- 3 root root 877 Sep 11 01:47 /usr/share/zoneinfo/Asia/Choibalsan
```

```console
$ file /usr/share/zoneinfo/Asia/Choibalsan 
/usr/share/zoneinfo/Asia/Choibalsan: timezone data (fat), version 2, no gmt time flags, no std time flags, no leap seconds, 50 transition times, 4 local time types, 16 abbreviation chars
```

```console
$ zdump -i /usr/share/zoneinfo/Asia/Choibalsan 

TZ="/usr/share/zoneinfo/Asia/Choibalsan"
...
```

**Comment by alex-w** [comment]
This is weird... Wait! Are you using an `AppImage` package or it installed from _AUR_?

**Comment by hectorthemonk** [comment]
Ah! AppImage. Mystery solved I think.

**Comment by alex-w** [comment]
> Ah! AppImage. Mystery solved I think.

Please share full log from Stellarium

**Comment by hectorthemonk** [comment]
[log.txt](https://github.com/user-attachments/files/17411192/log.txt)

**Comment by alex-w** [comment]
@hectorthemonk could you test a Qt6-based AppImage also?

**Comment by alex-w** [comment]
Please test https://github.com/Stellarium/stellarium/actions/runs/11384772593

**Comment by hectorthemonk** [comment]
> Please test https://github.com/Stellarium/stellarium/actions/runs/11384772593

[log-qt5.txt](https://github.com/user-attachments/files/17412746/log-qt5.txt)
[log-qt6.txt](https://github.com/user-attachments/files/17412748/log-qt6.txt)

Issue appears to be fixed in this build .  No log messages about unknown TimeZones.  Thanks!

**Comment by alex-w** [comment]
@hectorthemonk the time zone is correct after fix?

**Comment by hectorthemonk** [comment]
For https://github.com/Stellarium/stellarium/actions/runs/11384772593, selecting `Baruun-Urt, Eastern Asia` in the Location window sets the `Time zone` field to `Asia/Ulaanbaatar` in both the qt5 and qt6 versions.  

For Stellarium 24.3+ (v24.3.281-600edc8 [stellarium-next]), selecting  `Baruun-Urt, Eastern Asia` sets the `Time zone` field  to `System default`.

**Comment by alex-w** [comment]
I hope the time is correct
