### ISSUE TITLE
Gienah: the same name of two stars results in translation problem

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#396]
_Original report by Poker Lee:_ https://bugs.launchpad.net/stellarium/+bug/1617168

ε Cyg and γ Crv have the same name Gienah. But in Chinese (including all Chinese variants) they have different names. Therefore, however the translation is, one of the two stars will be displayed with a wrong name.

**Comment by gzotti** [comment]
We could use "Gienah Gurab" for gamma Crv. (This is "Raven's wing" for clarity.)

**Comment by rachelb418** [comment]
This is still happening and Gienah (gamma Cor) is mistakenly showing as Epsilon Cyg. Can it be fixed (I am using it for education and a Chinese asterism activity—[the Chariot]([url](https://en.wikipedia.org/wiki/Chariot_(Chinese_constellation)))) 
<img width="1113" alt="Screen Shot 2022-10-25 at 4 19 58 AM" src="https://user-images.githubusercontent.com/116681078/197872727-3f1270d0-9eb3-49b9-b1af-44c3cf35c4f3.png">

**Comment by alex-w** [comment]
Do you understand that you report about problem in web edition in the tracker of desktop edition of Stellarium?
