### ISSUE TITLE
Cannot launch under wayland : Qt platform problem [SOLVED]

### ISSUE THREAD

**Issue by yrogge** [Stellarium/stellarium#3967]
### Expected Behaviour
Normal application launch, as worked "before" last system update.

### Actual Behaviour
Freeze when launching (see log attached)

### Steps to reproduce
Simply type "Stellarium" in terminal

### System
* Stellarium version: 24.3.0-upstream1.1~ubuntu24.10.1
* Operating system: Ubuntu 24.10 (oracular) - Wayland display server (but same under XWayland)
* Graphics Card: Intel UHD Graphics (integrated)
* Screen type (if applicable): Lenovo Thinkbook Integrated (1920*1200, 60Hz)

### Logfile 
See attachments
Terminal output: [Stellarium Log.txt](https://github.com/user-attachments/files/17610205/Stellarium.Log.txt)
Log file: [log.txt](https://github.com/user-attachments/files/17610208/log.txt)

**Comment by gzotti** [comment]
Reads like a driver setup problem to me.

**Comment by 10110111** [comment]
Does any other Qt6-based app work? The following hints that the problem may be quite general:

> QEGLPlatformContext: Failed to create context: 3009

Also, do you have a discrete GPU installed, possibly in an NVIDIA Optimus-like way?

**Comment by yrogge** [comment]
I'm not using any NVIDIA driver.
I tried to resintall avery Qt6 stuff, but still same behavior.
The way to bypass is
- either define QT_QPA_PLATFORM=xcb
- or to launch with "stellarium -platform xcb"
Clearly, the problem is related to Wayland

**Comment by 10110111** [comment]
You should report this to your distro maintainers, because this looks like a breakage of Wayland OpenGL support for all Qt6 apps.

**Comment by yrogge** [comment]
OK. I'll do.
Thank you.

**Comment by alex-w** [comment]
Yep, standard packages in Ubuntu are Qt5-based

**Comment by 10110111** [comment]
> The package is from our PPA and standard package may have differences

In any case, the messages from Qt indicate a serious problem with OpenGL support. Or is Qt6 also provided by the PPA?

**Comment by alex-w** [comment]
> > The package is from our PPA and standard package may have differences
> 
> In any case, the messages from Qt indicate a serious problem with OpenGL support. Or is Qt6 also provided by the PPA?

No, we’re using qt packages from standard repository

**Comment by 10110111** [comment]
> No, we’re using qt packages from standard repository

So then indeed, it looks like the standard Qt6 packages are broken.

**Comment by gzotti** [comment]
Can we just add that environment variable to the startup? Or detect the necessity to do so first? (Is there a system configuration where you won't set xcb?)

**Comment by 10110111** [comment]
> Can we just add that environment variable to the startup?

We shouldn't try to work around all possible broken setups.

**Comment by yrogge** [comment]
I agree.
Ubuntu does not even initialize the QT_QPA_PLATFORM variable (to value "wayland" normally) for Qt environments.
If needed, it can be done in the .profile fille at session startup, but selecting "xcb" for all apps would be incoherent.
Hopefully, "Open with QPA platform XCB" is one of the predefined option of the .desktop file used to launch Stellarium.

**Comment by gzotti** [comment]
I did not mean to set xcb globally. But just as we can set some OpenGL variable to ANGLE or SOFTWARE(?) for Windows, we could set another envvar to xcb on Linux, if needed. Is there a way to automatically detect if it's needed?

**Comment by 10110111** [comment]
It seems to me that you are rushing to insert kludges for issues that may well be solved relatively soon by Ubuntu maintainers (assuming the OP has reported it there).

Such things should work out of the box, whether on X11 or on Wayland, and I suppose they used to work before the upgrade. It's just the upgrade that broke them, and, if I understood the OP correctly, it was a system upgrade, not a Stellarium upgrade. If Qt can't figure out that it's on Wayland, or that it should use EGL, or whatever else, there's something broken, and it should be sorted out in the distro, rather than getting worked around by the apps.

**Comment by alex-w** [comment]
The kludge for choosing XCB is included already in desktop file (it was added a long time ago) ;)

**Comment by yrogge** [comment]
Bug has been reported to Ubuntu/Debian Qt6 developpers
<https://bugs.launchpad.net/ubuntu/+source/qt6-base/+bug/2086676>

**Comment by yrogge** [comment]
I found the origin of this bug, and solved it!
It is not related to the Qt platform, but on some incompatibility between GPU libraries.
On Ubuntu 20.10, I simply uninstalled libegl-amber0 and libglx-amber0, and everything is now OK.
Sorry for disturbing Stellarium developers.

**Comment by gzotti** [comment]
Should this go into Debian package installation descriptions? I am not too familiar with that, but something like depends-on/conflicts-with that then triggers the respective changes. What packages then depend on lib*-amber0 and break?

**Comment by yrogge** [comment]
Nothing in standard Ubuntu repositories is depending on them.
And as far as I can check, the problem comes from these two libraries themselves.
In Ubuntu, they are part of the mesa-amber source package, from which the libgl1-amber-dri is perfectly functioning.
And they are nothing equivalent in Debian repositories; libgl1-amber-dri is just a complement to standard libgl1-mesa-dri.

**Comment by gzotti** [comment]
We can add this information to the wiki for other Ubuntuans. (Ubuntuists?) And you could report to or clarify with Ubuntu.

**Comment by yrogge** [comment]
Done. See <https://bugs.launchpad.net/ubuntu/+source/mesa-amber/+bug/2091807>

**Comment by gzotti** [comment]
Can we close this then? Workarounds are described in the FAQ, solutions TBD elsewhere.

**Comment by yrogge** [comment]
Yes.
Thank you.
