### ISSUE TITLE
The 'selectObjectByName' pointer changed to always being 'false'

### ISSUE THREAD

**Issue by Austin-RR** [Stellarium/stellarium#3968]
It appears the behaviour of `selectObjectByName` has changed unexpectedly when upgrading Stellarium from 24.2 to 24.3.  The "**pointer**" parameter seems to always be set to "false" now.

I did a test by completely uninstalling Stellarium (and all custom user files) and then ran the following command immediately from a clean installation of Stellarium:

```
core.selectObjectByName("M31", true);
```

The same command above on version 24.2 displays the selection pointer while version 24.3 does not.

Installation files used for this test on my Windows 10 laptop:
- stellarium-24.2-qt6-win64.exe
- stellarium-24.3-qt6-win64.exe

I also seen the same result on my computer at work that runs Windows 11.  I also tried the following latest snapshot, but I got the same result of the selection pointer never showing:
stellarium-24.3-44fb485-qt6-win64.exe

Thanks!

![24 2](https://github.com/user-attachments/assets/f09a7114-e798-4cc9-9a87-e9ca0feed410)

![24 3](https://github.com/user-attachments/assets/fbd92642-b764-4121-87fe-8c08f04a161f)

**Comment by Austin-RR** [comment]
Hi Alex. Unfortunately, I am unable to find the _flag_show_selection_marker_ option anywhere in my `config.ini` file. (I attached my 24.3 config file here as a TXT file.)

Just out of curiosity, I manually added `flag_show_selection_marker = true` under _[Viewing]_ to the config file in my 24.3 installation.  This edit did not help.  The same test command I used in my original post still does not display the selection pointer. I do not know if this information helps at all, but I thought I would report it anyway.  Thanks!

[config.txt](https://github.com/user-attachments/files/17621802/config.txt)

**Comment by gzotti** [comment]
Weird. It does not show in 24.3, but is OK again in current master.

**Comment by alex-w** [comment]
> Weird. It does not show in 24.3, but is OK again in current master.

I can confirm the issue in current master

**Comment by Austin-RR** [comment]
Glad you confirmed the issue.  It is not a huge issue for me as I can use something like this code as a temporary (until 24.4) fix to have a pointer drawn after selecting the object:

```
MarkerMgr.markerObject("M31",true,"dashed-square","#6c87db",20,false,0);
```

Thanks to everyone!

**Comment by alex-w** [comment]
OK, I found a bad guy - see commit https://github.com/Stellarium/stellarium/commit/447acbabc547b8b6ec63e1ad183d64f576870355#diff-01755750440c16ff90d525856f09485dbca7fa6a7de77f7dc93e05fa746f62b8 Of course it will not work :-/

@gzotti any idea how it fix?

**Comment by gzotti** [comment]
Oops, sorry. I had not seen the pointer call in the end... Now added a docfix.
