### ISSUE TITLE
Moon halo color

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#397]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1641756

From the forum, https://sourceforge.net/p/stellarium/discussion/278769/thread/8a9bc037/?limit=25#dc2f

For some reason, the Moon halo is increasingly reddened when it rises higher. This is obvious nonsense. Apparently this behavior was introduced in 0.11 or 0.12 series.

**Comment by gzotti** [comment]
I close this in favor of #351.
