### ISSUE TITLE
Memorizing ephemeris vsop87 & elp82b from imcce.fr

### ISSUE THREAD

**Issue by testori1972** [Stellarium/stellarium#3971]
So I need to remind you, because ftp.imcce.fr uses the fortran programming language, why can it be changed to c++?

**Comment by gzotti** [comment]
If this question is why imcce uses Fortran and not C++, why do you ask here about this? Or who should change what, to whose benefit? What is the purpose of your post?

**Comment by testori1972** [comment]
> If this question is why imcce uses Fortran and not C++, why do you ask here about this? Or who should change what, to whose benefit? What is the purpose of your post?

why can imcce.fr calculate elp82b & vsop87 using any source code even though it is the Fortran programming language?

**Comment by gzotti** [comment]
Fortran is a time-tested valid language from the 1950s punch-card era still widely used today in science. It was the language of choice when VSOP87 was developed, around 1987, when C++ was in its infancy. But you may be able to contact somebody in Paris who can give a definitive answer to a question the purpose and meaning of which I still don't understand. This is the wrong forum to speculate about other people's work.

**Comment by testori1972** [comment]
> Fortran is a time-tested valid language from the 1950s punch-card era still widely used today in science. It was the language of choice when VSOP87 was developed, around 1987, when C++ was in its infancy. But you may be able to contact somebody in Paris who can give a definitive answer to a question the purpose and meaning of which I still don't understand. This is the wrong forum to speculate about other people's work.

Yes, so why do ephemeris like elp82b and vsop87 have to use coeff and instructions, not according to the fortran source code provided?
