### ISSUE TITLE
External Software/Remote Computer Protocol Documentation

### ISSUE THREAD

**Issue by marsfan** [Stellarium/stellarium#3974]
**Is your feature request related to a problem? Please describe.**
Currently, the telescope control plugin's documentation covers the use of Serial, RTS2, INDI/INDIGO, and ASCOM telescopes. However, there is an additional telescope type in the menu called "External Software or a Remote Computer" that is undocumented in the plugin, so it is unclear how to write an external program to leverage this feature.

**Describe the solution you'd like**
I'd like to see the documentation for the Telescope Control plugin updated to include information on that packet structure used for sending data to/from an external program. 

**Describe alternatives you've considered**
* Reverse Engineer the protocol: I could probably do this, but it would not be as straightforward, and would likely only benefit myself, not any other users

**Additional context**
N/A

**Comment by marsfan** [comment]
Ah. I found the guide. Must have missed it when I was looking before. Its located in ./guide/pictures/Stellarium_telescope_protocol.txt in this repository. Might be useful to add that to the Plugin's readme file.

**Comment by gzotti** [comment]
Guess why this file is in the Guide's source repository. To be shown in Figure 16.18 as of Stellarium 24.3.
The plugin's own README file is from ~2010 and probably obsolete.
