### ISSUE TITLE
Could not open CD Rom

### ISSUE THREAD

**Issue by EdwardDLerner** [Stellarium/stellarium#3983]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
If you don't describe why not opening a CD-ROM has anything to do with Stellarium, I can only close this as fully not our business.

**Comment by EdwardDLerner** [comment]
What?
It’s the CD-ROM that CAME WITH YOUR TELESCOPE!!
Nothing to do with Stellarium?
It has YOUR name on the CD-ROM!
And I cannot open it.

**Comment by 10110111** [comment]
> It’s the CD-ROM that CAME WITH YOUR TELESCOPE!!

We don't see telescopes, and we don't distribute Stellarium on CDs. You need to describe your issue more fully for us to be able to help you.

**Comment by gzotti** [comment]
Do we sell telescopes? Or do we sell or distribute CD-ROMs? No. Did somebody who sold you a telescope (who, which?) provide a copy of our free software on CD-ROM? In the latter case, let's assume it is older than 2 months, therefore outdated. so just download the current version. If we sell telescopes, please show a photo of the box and CD.
