### ISSUE TITLE
sat plugin: do not show new sats by default, OR remember the currently selected category

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3986]
**Is your feature request related to a problem? Please describe.**

Whenever I enable sats, I keep having to disable newly added satellites.
This is because category [all] is the default startup of the plugin, and this cannot be changed.

**Describe the solution you'd like**

- [ ] The [all newly added] category should not be merged with the [all displayed] category. In other words, newly added satellites should not automatically be displayed. 

- [ ] Dynamic categories (ie that change after each restart) require a separate naming so they remain grouped in the list of categories, eg [*NEWLY ADDED*] and [*ALL DISPLAYED*], [*ORBIT ERROR*] etc so the users sees that these are special categories.

- [ ] additionally, the currently selected category should be remembered

**Describe alternatives you've considered**

**Additional context**

**Comment by alex-w** [comment]
> This is because category [all] is the default startup of the plugin, and this cannot be changed.

Wrong sentence, visibility satellites is not dependent with category [all]

> The [all newly added] category should not be merged with the [all displayed] category. In other words, newly added satellites should not automatically be displayed.

Why newly added satellites shouldn't be displayed? Users want to see newly launched starlink satellites without any additional movements.

> Dynamic categories (ie that change after each restart) require a separate naming so they remain grouped in the list of categories, eg [NEWLY ADDED] and [ALL DISPLAYED], [ORBIT ERROR] etc so the users sees that these are special categories.

All special categories (all dynamic categories by the fact) already has [] in their names, so, users already see hat these are special categories.

> additionally, the currently selected category should be remembered

Why? Most categories are dynamically created and remembering dynamic data is bad idea.
