### ISSUE TITLE
47 Tuc image is doubled

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#3996]
The following screenshot was done with stars and the Milky Way disabled. Two issues are apparent, compared with `nebulae/default/smc29-2.png`, which contains an image of 47 Tuc:

1. Many of the stars have fainter copies nearby (enabling stars will show that there's one star instead of two);
2. The middle of 47 Tuc is blown.

This may imply that there are two different images a bit displaced from each other (the blown middle would then be because of addition of two bright images). I tried disabing all DSS checkboxes, but this didn't change anything. Not sure how to find which image is the second one (the first one being made of `smc29-*.png`).

![Screenshot_2024-12-04_17-46-54](https://github.com/user-attachments/assets/fc39b516-3bfa-4026-bfd3-836c0c48812e)

**Comment by 10110111** [comment]
> SMC?

I have no idea about the naming scheme of the images.

**Comment by alex-w** [comment]
Please remove texture for [NGC104](https://github.com/Stellarium/stellarium/blob/master/nebulae/default/n104.png)

**Comment by alex-w** [comment]
SMC = Small Magellanic Cloud

**Comment by 10110111** [comment]
> Please remove texture for NGC104

Yeah, that's it. After removing it along with `smc29-2.png` there are no remnants. Since the SMC texture has a better-resolution image of NGC104, I suppose we should simply remove `n104.png` completely.

**Comment by alex-w** [comment]
+ update CREDITS.md file after removing texture

**Comment by 10110111** [comment]
`CREDITS.md` doesn't appear to mention NGC104 in any form.
