### ISSUE TITLE
ctrl + mouse drag stuck in time mode

### ISSUE THREAD

**Issue by zsarosi** [Stellarium/stellarium#4011]
When using Stellarium on Linux, if I hold the Ctrl key and drag the mouse with the left button pressed to manipulate time, the application works as expected. However, after releasing both the Ctrl key and the left mouse button, the mouse cursor remains in "time-drag" mode and the normal view dragging functionality gets stuck. The view cannot be dragged normally with the mouse until Ctrl + 1 is pressed to reset the navigation mode.

### Expected Behaviour
After releasing the Ctrl key and left mouse button, the mouse should return to normal view-drag mode. The time-drag mode should be disabled, and I should be able to drag the view as usual.

### Actual Behaviour
After releasing Ctrl and the left mouse button, the application remains stuck in "time-drag" mode. The mouse does not function as expected for normal view dragging until I press Ctrl + 1 to reset the view mode.

### Steps to reproduce

1.     Open Stellarium.
2.     Press and hold the Ctrl key and click the left mouse button.
3.     Drag the mouse to change the time (time drag mode).
4.     Release the Ctrl key and left mouse button.
5.     Attempt to drag the view with the mouse as usual (view drag).
6.     The view remains stuck in the "time-drag" mode, and the mouse can no longer drag the normal view.
 
### System
* Stellarium version: 24.3 (Snap)
* Operating system: Ubuntu 22.04
* Graphics Card:  I am using Lenovo T14s (it has integrated Intel chipset, no extra graphics card)
* Screen type (if applicable): Laptop screen

**Comment by gzotti** [comment]
Interesting. On Windows, releasing the Ctrl key immediately switches to view-drag mode.

**Comment by alex-w** [comment]
I can confirm described behaviour in specific case - see screencast.

https://github.com/user-attachments/assets/e8cfce18-e579-4bcf-87d5-6d985be262d6

**Comment by gzotti** [comment]
This looks like the normal (intended) behaviour. While time-dragging you can push the sky into motion (high timelapse) by releasing mouse button while dragging. Then, with the sky spinning, you should be able to drag the scene. (Of course, I don't see when you press Ctrl... [sorry, no audio on this PC, in case you announced it.])

**Comment by alex-w** [comment]
Push the “sky” and release Ctrl under the scene :)

**Comment by alex-w** [comment]
@zsarosi please make a screencast with comments

**Comment by zsarosi** [comment]
here is my screencast regarding the issue.

[Screencast from 16.12.2024 20:00:11.webm](https://github.com/user-attachments/assets/de5ec6ad-5152-45ff-adb8-4d4b62d930cf)

**Comment by alex-w** [comment]
@zsarosi please share file `~/.stellarium/config.ini`

**Comment by zsarosi** [comment]
Here is the config.ini (i had to gzip it), there is nothing special in it, as I have just downloaded Stellarium snap before. I only updated the location to Zurich, everything else should be default.
[config.ini.gz](https://github.com/user-attachments/files/18156866/config.ini.gz)

**Comment by alex-w** [comment]
Can't reproduce the issue in Windows (using attached config) - I'll check it in Ubuntu tonight

**Comment by alex-w** [comment]
Can't reproduce the issue in Ubuntu Linux too

**Comment by zsarosi** [comment]
It is strange: I have two different installation on my Ubuntu 22.04: one from the official software repository v0.20.4 and an other one that is from snap store v24.3.0 and both have the same issue. I also installed Stellarium on an old laptop: Ubuntu 24.04, Stellarium v24.4.0, there is no such issue. Maybe it is some HW-specific issue.

**Comment by gzotti** [comment]
We will not solve a problem in v0.20.4 or snap of 24.3. If it's not reproducible in 24.4 (maybe the snap edition, but its maintainer should state what comes with it), we should close this. It may indeed be a hardware quirk. Will Lenovo solve it?

**Comment by zsarosi** [comment]
I updated on my laptop the snap version to 24.4, it still have the issue. Now, it is either HW-related (graphics card?), or the Ubuntu Version might as well be the problem. 
Since the workaround with the ctrl+1 is a viable solution, we can close the issue.

**Comment by 10110111** [comment]
> graphics card?

No, more likely the interaction between keyboard&mouse input and Wayland or X11, depending on what you're using. If you are on Wayland, try switching to Xorg.

**Comment by zsarosi** [comment]
According to my query:
$ echo "$XDG_SESSION_TYPE"
x11
I am using X11, so no Wayland. I can test it with Wayland.

**Comment by zsarosi** [comment]
So I switched to Wayland:
$ echo "$XDG_SESSION_TYPE"
wayland
and now it works as expected!

**Comment by alex-w** [comment]
So, this is really not our bug
