### ISSUE TITLE
No star name labels

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#4029]
I'm running Stellarium v24.4.362-19ff230 for the first time after merging #3992, without changing anything in the settings. And I get no labels for the stars, only planets are labeled. See the screenshots below.

### v24.4.362-19ff230

![Screenshot_2024-12-27_12-12-43](https://github.com/user-attachments/assets/c99b3b52-6960-4ec3-9b6e-2c4fa691f63e)

### v24.3.349-9940b02

![Screenshot_2024-12-27_12-12-35](https://github.com/user-attachments/assets/c0b90f7e-4bc1-4a3d-aaf8-59b236d5063e)

Log from the problematic version: [log.txt](https://github.com/user-attachments/files/18257303/log.txt).

**Comment by Atque** [comment]
Isn't it just that labels are less densely drawn?

**Comment by alex-w** [comment]
> Isn't it just that labels are less densely drawn?

Yes, but behaviour for density is changed

**Comment by gzotti** [comment]
StarMgr::1239. The bias -2 (last term) was changed to -7, making a large part (half!) of the slider path empty. Resetting to -2 seems to work. But @henrysky should please answer why the value was changed. Probably the slider path can be adjusted to have Sirius labeled with the slider on the left edge. Now it seems it appears (with bias=-2) at slider value 1 of 10.

**Comment by henrysky** [comment]
I can confirm I've changed -2 to -7 at StarMgr.cpp::1239 by accident where I should not (while fixing the flashing of 39 Ser mentioned in #3992 where I need to change a -2 to -7 in another place).
