### ISSUE TITLE
video player broken

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#403]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1735186

VideoPlayer is again broken in 0.16. Sorry for the inconvenience. If required urgently, please try to use version 0.14.3 or 0.15.0

**Comment by miggs125** [comment]
Hey is there any activity on this? could I work on this issue?

**Comment by alex-w** [comment]
No any action for media stuff within Stellarium now

**Comment by gzotti** [comment]
@miggs125 absolutely, you are cordially invited to solve this nasty problem.
