### ISSUE TITLE
smoothly migrate ssystem_minor.ini (and other datafiles)

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#4030]
Similar to #4026  :

Found in logfile:

```
Minor body  2010 TK7 has incomplete data (missing iau_designation or minor_planet_number) 
...
Old-fashioned entry "comet_orbit" found. Please delete line from  "/home/alex/projects/stellarium/configs/master/data/ssystem_minor.ini" section "p2020x1(atlas)"
,,,

```

![image](https://github.com/user-attachments/assets/c6e72dbe-cd95-4f18-b904-17d34b1049ae)

## proposal

Use a migration pattern to smoothly migrate older formats; the average user will not always check the logfile and/or be even able to do this.

## workaround
reset `ssystem_minor.ini` (and lose a lot of customization).

**Comment by gzotti** [comment]
These messages are informative only. Objects are still loaded. "comet_orbit" has been replaced by kepler_orbit which is the default. Missing name parts are just not available for search/name formation.
