### ISSUE TITLE
No stars and broken functions after snapshot installation 24.4.364 / 24.4-24215f9

### ISSUE THREAD

**Issue by StarFlea** [Stellarium/stellarium#4042]
![NoStars](https://github.com/user-attachments/assets/b94fafd6-41e2-4930-8d57-8527bdebda8b)

Hi guys,

after testing the latest patch (Qt5) all my stars have disappeared (even though they are activated in the settings).

In addition, the four buttons on the left of the control bar (constellation lines, constellation labels, constellation art and constellation boundaries) are not working.

The log file shows a lot of error entries here.

I have restarted the PC several times and reinstalled the patch again, but the result remains the same!

Regards!
StarFlea
[log.txt](https://github.com/user-attachments/files/18270915/log.txt)

**Comment by StarFlea** [comment]
Ah, ok, 

als ich die letzte stabile Version (24.4) installiert habe, waren alle Sterne wieder da. Nachdem ich den neuesten Patch abermals darüber installiert habe, waren sie wieder weg.

Das Problem dürfte also in der Installation des Patches liegen...

**Comment by Atque** [comment]
Did you use the patch or the full installer? The star catalog has recently changed, I'm not sure if you need to install the full package.

**Comment by StarFlea** [comment]
YES, I just tried the full package. It works!

So the problem is limited to the patch

**Comment by StarFlea** [comment]
Oh, I see, I should have reloaded the catalogs manually after installing the patch...

**Comment by Atque** [comment]
Keep in mind you need to re-download the catalog files containing the fainter stars as well.

**Comment by alex-w** [comment]
The patch installers are not contained data files - this is expected “problem” when patch is install over release and when data in master has serious changes.
