### ISSUE TITLE
Calculates the eclipses

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#407]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1106741

This feature request from old bug tracker.

It would be good that Stellarium can show and calculates the eclipses and the planets positions up to 100 years in the future and also in the past...like Redshift can do this.

Type of eclipses:
- [x] Lunar eclipses
- [x] Solar eclipses

**Comment by worachate001** [comment]
Is anyone working on this issue or planning to do it soon?

It should be in "Astronomical Calculations", right?

**Comment by alex-w** [comment]
> Is anyone working on this issue or planning to do it soon?

The task in my TODO list, but not for near future
 
> It should be in "Astronomical Calculations", right?

Yes

**Comment by worachate001** [comment]
I'm working on the lunar eclipse. This is an example of what I have so far. You can search for lunar eclipses and go to the moment of greatest eclipse (Note: date and time are in my zone - UTC+7).

![lunareclipseforstellarium](https://user-images.githubusercontent.com/41257965/150092252-b6d10491-a3c4-4a92-8145-f584896179bb.png)

I'm using the icon from transit because I don't know how to add a new one for lunar eclipse (and still don't have it).

Hope to create a pull request soon for review and testing. After this, I will try to create something like this for solar eclipses.

**Comment by alex-w** [comment]
See for example: https://github.com/Stellarium/stellarium/blob/master/data/gui/tabEclipses.png

**Comment by worachate001** [comment]
In my draft of the pull request, it says worachate001 wants to merge 7 commits into Stellarium:master from worachate001:LunarEclipseCalc. It appears that the request include previous changes years ago. I'm not sure how to get rid or manage this situation (the changes look okay with just 3 files that I have made). If I go ahead with the pull request, it shouldn't be a problem, right?

**Comment by gzotti** [comment]
In the tab "Files changed" we can see that 3 files were changed. the total number of commits is usually not important when we squash all changes into one commit on merge. Only large changes are merged as sequence of commits. But we need to review your work first :-)

**Comment by worachate001** [comment]
This is Solar Eclipses Tab for the AstroCalc. I believe this is enough for summary of the eclipse. I can write the code to find duration of totality/annularity, but it will take more time to calculate. Any suggestions are welcome.

![solareclipses](https://user-images.githubusercontent.com/41257965/151186510-159ffe5d-7f28-4d7c-965b-9e8694e3a711.png)

**Comment by gzotti** [comment]
Looks great, thank you. Now, for this tab, I wish to have another checkbox switch: double-clicking on one line should either move to point (and time) of greatest magnitude (TBD: What to do with time zone? Keep current, use LMST?), or should show greatest magnitude at my current location. The latter would of course require you can add local circumstances. (Bessel elements and so on.) The next big challenge would then be an earth map with shadow line (or adding a shadow line to the location panel's earth map) :-)

**Comment by alex-w** [comment]
Well, I see in the new tab calculation greatest eclipses and their locations - I think the time for all of them should be UTC to avoid time zone misunderstanding. The coordinates should follow option "Use decimal degrees" to switch the representation of data - DMS or DD format. Cosmetic fix: the tabs should be at bottom to use homogeneous view of tools (see Graphs or PC tabs as examples).

Of course on the new tab we see "generic" data of solar eclipses. I think we next obvious step will be adding new tab for solar eclipses, where users will see eclipse circumstances for current location and these circumstances should be presented for visible eclipses only (for current location). For example user from Africa shouldn't see data for eclipse, which observable in Asia only.

**Comment by alex-w** [comment]
> I can write the code to find duration of totality/annularity, but it will take more time to calculate.

It would be helpful :)

**Comment by gzotti** [comment]
This would then mean having two tabs: "Solar eclipses (global)" and "Solar eclipses (local)" with different double-click behaviour as suggested above.
