### ISSUE TITLE
Quick Instrument simulation mode

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#409]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1106760

This is feature request from old bug tracker.

A feature to quickly set the Stellarium software to show what you're likely to see through a variety of commonly used optical instruments, a useful feature for people who can't do the necessary maths to save their lives (or just want to get on with observing without having to mess on working these things out, or just want to get an idea of how an instrument they're thinking of buying works before actually buying it).
 e.g.
 BINOCULAR MODE (with ring to show area covered by each type)
 - 8x21
 - 10x21
 - 12x21
 - 7x50
 - 8x50
 - 10x50
 - 12x50
 - 16x50
 - 20x50
 - 15x70

TELESCOPE MODE
 Put the telescope specs in manually (e.g. tube length, lens + eyepiece size), or choose from a range of commonly used scopes (and input the eyepiece), such as:
 - 60mm Tasco thing
 - MEADE ETX range
 - MEADE Lightbridge Range
 - MEADE LX90 range
 - ORION SKYQUEST XT range
 ... and so on.

Got a similar (but not as extensive) feature on the old "STARRY NIGHT BACKYARD SE" software I also use in addition to stellarium.

**Comment by gzotti** [comment]
This simply means "add a few more example entries to the ocular plugin instrument lists", then mark as done.

**Comment by gzotti** [comment]
Why? Probably the request for an Observer Logger tool requires a change in the Oculars plugin (like reading its data). I see a request for a number of widespread instruments to be provided by default, and nothing else. As I understand it, the image circles should not be displayed all at the same time, so this is what Oculars is already doing. Of course, the original request is apparently from pre-Launchpad, and hopelessly superseded.
