### ISSUE TITLE
Greek, Roman and Mayan starlore

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#411]
_Original report by Edward Kramer:_ https://bugs.launchpad.net/stellarium/+bug/1114270

Suggestion from private email by Edward Kramer:

It would be neat to see the folklore of the greek,roman and mayan perspective

- [x] Maya starlore
- [x] Greek starlore
- [x] Roman starlore

**Comment by alex-w** [comment]
Three Greek starlores has been prepared by @sushoff

**Comment by sushoff** [comment]
Roman star lore is based on Greek star lore; 

the Leiden Aratea that I recently added is based on Aratus' didactical poem (Greek) but the style of painting is clearly based on Roman originals
