### ISSUE TITLE
Meade LX200/Nexstar protocol over TCP/IP (e.g SkyFi) for Telescope Control

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#413]
_Original report by Peter:_ https://bugs.launchpad.net/stellarium/+bug/1272800

The Meade LX200 and NexStar serial telescope protocols can be used over TCP/IP using a commercial hardware device like the SkyFi http://www.southernstars.com/products/skyfi/ or a computer running ser2net, e.g. http://stargazerslounge.com/topic/180030-skyfi-with-a-pi/

It is therefore reasonable when setting up Stellarium to talk to a remote telescope via TCP/IP to specify the protocol, in addition to the host (name or IP address) and port.

However, the GUI currently disables the "Device Model" setting which would allow specifying Meade LX200 or NexStar. Instead, the plugin seems to be hard coded to use Stellarium's own binary TCP/IP protocol:
https://svn.code.sf.net/p/stellarium/code/trunk/telescope_server/stellarium_telescope_protocol.txt

One possible work around is to configure a virtual com port which is forwarded to the remote computer's TCP/IP port.

Tested using Stellarium 0.12.4 on Mac OS X.

**Comment by admerge** [comment]
Hi there,

I am very interested in a solution of this issue, because I want to use LX200 over IP... 
Are there any news ?

**Comment by gzotti** [comment]
If somebody with this hardware could send us a working solution (patch, pull request, ...), we could add it. So far, no news. OTOH, "tested with V0.12.4 on MacOSX" means "tried with obsolete version". Can you use Stellarium 0.19.* with any INDI-based solution?

**Comment by gzotti** [comment]
@admerge can you test this with current beta? Stellarium has now ASCOM support, and INDI on MacOS. These hopefully provide solutions.

**Comment by urbanze** [comment]
Someone know how to solve this? I would like to use LX200 instead proprietary stellarium protocol over network. My last option is to create virtual serial device to resend data over network...
