### ISSUE TITLE
Cannot move or select using touch on 0.13.1

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#417]
_Original report by Jeffry Johnston:_ https://bugs.launchpad.net/stellarium/+bug/1403167

I've upgraded to Stellarium 0.13.1 under Ubuntu 14.04 on a Samsung Slate 7. The new multitouch pinch zoom works great. I can also navigate the program using my tablet pen. However, after the upgrade I can no longer navigate the program or look in different directions without using the pen (which used to work fine before the upgrade, of course before the upgrade I had no pinch zoom). Is there a way I can keep both the pinch zoom AND use Stellarium without the pen? The tablet is heavy, and I don't want to accidentally drop it outside while trying to hold it overhead with one hand and pen in the other. Thanks!

**Comment by alex-w** [comment]
I think we fixed it already but I cannot test it.

**Comment by Thomas1664** [comment]
@alex-w It works on my Windows 10 Convertible
