### ISSUE TITLE
Option to select font and size

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#424]
_Original report by Khalid AlAjaji:_ https://bugs.launchpad.net/stellarium/+bug/1505073

font and size can be specified in the config.ini. Can be there an option in the configuration window to select the font and size from the system.

The reason for this request now is that some fonts are behaving better than the default regarding the qt bug: https://bugreports.qt.io/browse/QTBUG-46244 affecting Stellarium panels in Arabic language and reported here: https://bugs.launchpad.net/stellarium/+bug/1498616

Another reason is cosmetic. Some fonts look better.

**Comment by gzotti** [comment]
I have started this. However, some fonts (esp. on the GUI panels) look bad when scaled at runtime, needs some separation.
