### ISSUE TITLE
Add partitions for various circles

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#428]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1590575

Anonymous wish from the forum https://sourceforge.net/p/stellarium/discussion/278769/thread/9ec5c9e6/

OP: I had an idea for a small new feature that could be added to Stellarium.
The Axial Precession circles could have 6 or 8 little white arrow heads spaced at regular angles added to them to show the dirrection of the Axial Precession.

It would also be really great if Stellarium could show approxmately where the Celestial North and South Poles were and will be in the future with 25 little white line marks along the circle for every 1000 years starting at year 0 that can be turned on or off. Not that the year 0 has any special significance for Earth's Axial precession. I just thought it would be a convenient year to start with so it matches the calendar. This way, educators can show students how the direction that Earth's North and South Poles point into space change over time and how Pole stars change with time. Currently, the Axial Precession cycle has a rate that corrosponds to one complete cycle in about 25,772 years. However, the rate varies slightly in a not entirely predictable way due to Earth's equatorial buldge gravatationally interacting with the Sun, Moon and to a much lesser extent, the other planets differently all the time according to Wikipedia.

GZ: Yes, thanks for your interest. There have been similar requests for partitioning the ecliptic, Galactic equator etc. While partitioning those into reguar angles should not be too difficult, exactly the inconstant speed makes that feature request a bit more difficult. It should not be forgotten though.

OP: Ok
If the Precession circles just had the arrow heads on them to show the direction of Axial Precession that would be great.

**Comment by gzotti** [comment]
Almost the same: #370
