### ISSUE TITLE
Show arcseconds/pixel in ocular plugin

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#432]
_Original report by Volker H.:_ https://bugs.launchpad.net/stellarium/+bug/1668090

Further to Bug 1656825:

For a given sensor the published horizontal and vertical pixel sizes, resolutions und sensor dimensions often leave room for interpretation.

For example Cannon published for it's EOS600D sensor:
Chip size: 22,3 x 14,9
Resolution: 5184 x 3456
Pixel size: 4,3 x 4,3
Resolution times pixel size does not accurately match the chip size.

Proposal:
Calculate exact chip sizes from resolutions and pixel sizes.
Calculate FOV and arcsec/pixel from exact chip sizes.
Present results in Stellarium rounded to 1 digit after comma (more are meaningless).

This assures that square pixels have equal h-scales and v-scales.

**Comment by crazyimp** [comment]
Isn't this solved already? The red sensor frame shows values like: 2.1434"/px in the lower right corner. Additionally, the X/Y scale are listed in the sensor selection box (top right corner).
Tested with 0.18.3.16526.

**Comment by alex-w** [comment]
This feature request is almost done, but not complete yet.

**Comment by gzotti** [comment]
@alex-w  Any change?

**Comment by alex-w** [comment]
@gzotti not yet

**Comment by axd1967** [comment]
the **pixel width/height** values (`m_pixelWidth`) are not used in the code, their presence in the GUI leads to needless confusion.

consider one of following:
- set the value to zero in the (copy) constructor
- disable (grey out) or hide the input fields
- add a tooltip or some other indication that indicates that the value is currently not active/not used/ not implemented
- introduce a check between pixel width, chip width and X-resolution 
- if one of the three values above is cleared and the two others are available, it is calculated from the other two values

same for **binning**, currently not used.

**Comment by alex-w** [comment]
Binning is used for calculation of scale, but pixel sizes are really not used. WTF?

**Comment by alex-w** [comment]
I've check the history changes of Oculars plugin and value of pixels size was never used. We may use it to calculate the physical size of the chip for CCD (e.g. FLI publish the resolutions and pixel sizes for CCD's).

@gzotti ?

**Comment by gzotti** [comment]
In principle, when configuring a sensor, any change in Sensor size, pixel size and pixel count implicitly has to adapt the other two. Somehow, I think, we should therefore configure one of the three to "auto". Whether as global switch or as per-sensor value, I don't care.

I have wondered for years why this has been introduced but never activated. Presumably no developer has enough time to fulfill his dreams :-), and currently I have no need to configure sensor pixel sizes :-(

There are some further technical issues with the whole plugin. 

* Get rid of QSignalMapper (to prepare for Qt6)
* Fix what I had tried a year ago (interactive scaling of sensor frame and OAG by mouse wheeling the spinners worked already, but somebody complained it inhibited his manual entering of numbers (decimal point?). You fixed that, somehow, but in a way I'd like to see changed: Now you can enter numbers (pressing Enter), but when using the spinner/mousewheel they don't become immediately effective (You must press Enter or switch to another spinner to see effects of the change!), causing questions as to how to use OAG settings, which I had regarded extremely intuitive with the spinners working properly.) There are too many ways and dissenting preferences to operate GUI elements, it seems.

**Comment by alex-w** [comment]
I've removed pixel size

**Comment by alex-w** [comment]
Please check version 0.20.2.18074
