### ISSUE TITLE
Restore default_shortcuts.json and embedded scripts support

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#434]
_Original report by Gabriele Pacaccio:_ https://bugs.launchpad.net/stellarium/+bug/1299092

This bug report is related to question #245630.

After trying the new 0.13 version I found out that there is no more support to embedded scripts and default_shortcuts.json file like the 0.12 version. I'd like to have these features restored because are very useful to me.

**Comment by gzotti** [comment]
What's the state with this? As of V0.16 you write an .ssc script and declare its shortcut in the script header or reassign it later. Could hardly be made simpler.

Can we close this item?
