### ISSUE TITLE
broken link on webpage

### ISSUE THREAD

**Issue by leonardcj** [Stellarium/stellarium#44]
http://stellarium.org/translation/2017/10/07/planetary-features-call-to-translators.html

still points people to LaunchPad

**Comment by alex-w** [comment]
The link is not broken because this news was published in month before moving to github.

**Comment by leonardcj** [comment]
Ok, technically not broken, but it is prominent and refers localizers to a place you no long localize.  Maybe an editor's note could be added referring to your Transifex project?

**Comment by gzotti** [comment]
@alex-w I think this can be closed? The page still exists, but I don't see a link there from the project homepage. Translation link goes correctly to Transifex.
