### ISSUE TITLE
Text very pixelated on a 4K screen

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#440]
_Original report by Tuomas Teipainen:_ https://bugs.launchpad.net/stellarium/+bug/1698876

I recently acquired a 4K monitor with a resolution of 3840 x 2160, and it seems that stellarium has some problems scaling the texts properly. I can't take a screenshot of the problem because the screenshots end up being 2560 x 1440 instead of my monitor's native resolution, and the text seems fine in them. But basically the text looks like it's still in a smaller resolution and just "enlarged" for 4K, the result being that the text is all pixelated and very hard to read. I'm using 0.16.0 RC2.

It would be nice if I could just turn the whole "app scaling" off. You don't really need that with a 28" monitor.

**Comment by gzotti** [comment]
4k issues have been developed further somewhat since 0.16. Although 4k is not solved, there are enough issues in the list, this does not reflect the current state and can be closed as duplicate.
