### ISSUE TITLE
Ability to set color-opacity ot UI elements

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#441]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1698512

Original report by Anonymous: https://sourceforge.net/p/stellarium/discussion/278769/thread/10ec629d/?limit=25#733b

Certain areas e.g. grid, orbit-lines, is too obtrusive in certain lighting conditions. Maybe have the grid adapt intelligently to day/night lighting conditions. And have option for user to set (slider?) opacity and how close they are/far apart.

**Comment by gzotti** [comment]
OP never specified more details. Just don't overdo this, it can easily lead to GUI clutter.
