### ISSUE TITLE
images not distorted in spheric-mirror mode

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#445]
_Original report by Pawel Rudawy:_ https://bugs.launchpad.net/stellarium/+bug/1558148

I'm using Stellarium in spheric-mirror mode. It works fine.

However, the images created from a file and displayed with "ScreenImageMgr.createScreenImage" function are not distorted, so the resulting compound image seen on the screen (and also projected via a mirror) looks strange.

My code is as follows:

```
core.setSphericMirror(true);
projmod="Stereographic";
core.setProjectionMode(projmod);
core.setGuiVisible(true);
screenx=core.getScreenWidth();
screeny=core.getScreenHeight();
core.clear("natural");
szerilustr=966;
skala=0.8;
xpos=(screenx/2)-(szerilustr*skala/2);
ypos=(screeny/2);
ScreenImageMgr.createScreenImage("aaa","../pics/aaa.png",xpos,ypos,skala,true,1.0,0.03);
core.wait(100.0);
core.exit();
```

**Comment by gzotti** [comment]
Final hint from original discussion:

```
You must use some SkyImage for images to be shown on your planetarium dome.
```
