### ISSUE TITLE
A tour around the solar system

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#450]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1372782

Reported by Anonymous at https://sourceforge.net/p/stellarium/discussion/278769/thread/cd6a4974/

Is there a script available that takes you on a tour around the solar system preferably that loops?
I have looked but cannot seem to find one.

**Comment by jasonincanada** [comment]
Hi Alex, I've written a tour script in my repo here: https://github.com/jasonincanada/stellarium-scripts

It's polaris.ssc, and alternatively moon-hopping.ssc

**Comment by alex-w** [comment]
Hi Jason, I've added links on your scripts on our website: https://stellarium.org/scripts.html

Your scripts looks interesting but all scripts needs fixes. For example all scripts has header 'About', but Stellarium expected header 'Description:'.
