### ISSUE TITLE
Twilight colors

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#452]
_Original report by Marty Lewis:_ https://bugs.launchpad.net/stellarium/+bug/1321782

The current model is simply amber through to black sky when animating through civil, nautical and astronomical twilight.

While this works well a more realistic model would be to have separate hues for each twilight mode

Eg something like this...

civil twilight = golden amber to blue (as it is currently)

nautical twilight = deep orange near horizon grading to indigo

astronomical twilight = indigo near horizon grading to deep purple/black

night =black

Marty

**Comment by gzotti** [comment]
Duplicate of #352
