### ISSUE TITLE
HTTP Interface for Telescope Server

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#456]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1106752

This feature request from old bug tracker.

Could be interesting that the telescope server could read a HTTP request, like GET or POST and move the position of a telescope with a set of variables.

```
Stellarium->POST Request->Telescope Server
Web Page->POST Resquest->Telescope Server
```

An example:
```

POST / HTTP/1.1
 Host: localhost:10000
 User-Agent: Mozilla/5.0 (X11; U; Linux i686; es-ES; rv:1.9.0.13) Gecko/2009080315 Ubuntu/9.04 (jaunty) Firefox/3.0.13
 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8
 Accept-Language: es-es,es;q=0.8,en-us;q=0.5,en;q=0.3
 Accept-Encoding: gzip,deflate
 Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
 Keep-Alive: 300
 Connection: keep-alive
 Content-Type: application/x-www-form-urlencoded
 Content-Length: 33

```
ra=2h08m54.8087&dec=+17d34m19.976

The set of variables:
ra=2h08m54.8087
dec=+17d34m19.976

It's a more standard interface and we could take the telescope control with another controllers, like a web page, and with stellarium as usual.

**Comment by gzotti** [comment]
Does this concern Stellarium's telescope plugin or the ancient Telescope Servers, or both? Should these old telescope servers be hosted on GH, and polished up a bit to fulfill modern requirements? (And who should do that?)
