### ISSUE TITLE
Support FreeDesktop.org XDG basedir specification

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#461]
_Original report by Eric Heintzmann:_ https://bugs.launchpad.net/stellarium/+bug/1088064

Please support FreeDesktop.org XDG basedir specification for stellarium

http://ploum.net/post/207-modify-your-application-to-use-xdg-folders
https://live.gnome.org/GnomeGoals/XDGConfigFolders
http://standards.freedesktop.org/basedir-spec/latest/

**Comment by gzotti** [comment]
Duplicate of #76
