### ISSUE TITLE
Command line control of Stellarium

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#472]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/797951

Hi, I want to suggest a feature. I dont know where else to post this.

Is it possible to program Stellarium so if someone passes variables thru the command line ,ex: "Stellarium.exe -s moon" which will open up Stellarium showing the moon. This will become a very powerful feature when integrating Stellarium with other astronomical software.

Also if someone can develop an extension for chrome and firefox webmasters can embed links on there websites so when a user clicks a link it open up Stellarium with the given query. example: <a href="Stellarium:spica">click to see Spica</a>

Thanks.

**Comment by gzotti** [comment]
1. Solved long ago by 
```
stellarium --startup-script <script>
```
2. Running instances of Stellarium can be called via RemoteControl webserver.
