### ISSUE TITLE
Andromeda asterism lines are incomplete

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#476]
_Original report by Todd:_ https://bugs.launchpad.net/stellarium/+bug/1515951

When showing constellation lines, Andromeda is missing the following line, starting from HIP 677 (Alpheratz) to HIP2912 to HIP4436 to HIP7607. This line is particularly important since it not only completes the lines for the constellation, it really helps in finding the Andromeda galaxy. Verification for this line as part of Andromeda can be found in most any star atlas. My reference happens to be "The Cambridge Star Atlas" 4th ed. 4th printing, 2014, by Wil Tirion. Thank you! And thank you for such an excellent program. Todd Longfellow, Payson, AZ.

**Comment by gzotti** [comment]
It is definitely NOT a bug. The lines are not standardized, and every user can personalize them.
