### ISSUE TITLE
The Moon halo is "broken"

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#477]
_Original report by Tuomas Teipainen:_ https://bugs.launchpad.net/stellarium/+bug/1502495

In the current version of Stellarium the Moon halo has some kind of a weird distortion effect over it. This problem has existed since about version 0.13.0, I think.

The effect looks like a smudged glass that Moon is being viewed through. Also, the edges of the halo appear pixelated. If i move around the smudge pattern appears to remain static, and doesn't move along with the Moon (just like looking through a dirty window or something). Changing the value of "atmosphereybin" to eg. 10 in Config.ini makes the effect more pixelated. Changing it to 100 makes the edges somewhat less pixelated, but also kills my FPS.

I'm also not able to change the halo texture in ssystem.ini. It seems that the halo is somehow generated by the program code in the current version. I think it looks unrealistic and should be replaced with the haloLune.png texture that is found inside the texture folder. Also, the "star" halo of the Moon should probably be disabled by default.

**Comment by gzotti** [comment]
To repeat, you can add in your config.ini:
```
   [landscape]
   atmosphereybin = 75
```
or something higher than the default 44 to get rid of the "smudged glass" effect. It governs the tessellation of the sky.

**Comment by gzotti** [comment]
Works as documented...
