### ISSUE TITLE
Jump to Defined Moments in Diurnal Motion of Objects: rise, transit, set

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#484]
_Original description:_ https://blueprints.launchpad.net/stellarium/+spec/jump-to-defined-moments-in-diurnal-motion

It would be nice to have a feature where you are able to jump to a specific moment in diurnal motion of a selected object, such as: 
- [x] jump to next/previous rise time of selected object,
- [x] jump to next/previous transit time of selected object,
- [x] jump to next/previous set time of selected object.

The user should also be able to define his own moments, such as: the next/previous moment when the selected object is 20 degrees above the horizon. Defining custom moments would allow:
- [x] jumping to the next/previous civil/nautical/astronomical dawn/dusk moments, which could be defined as -6, -12 or -18 degrees,
- [ ] jumping to next/previous rise/set of the selected object if there are some obstacles of known angular height on the horizon.

Jumping to these moments should work like the add/substract 1 sidereal week/day shortcut controls, currently available in Stellarium.

**Comment by axd1967** [comment]
See also #1088

**Comment by alex-w** [comment]
@gzotti we may implement latest item through computing the next/previous set/rise with altitude, which has selected object at moment of call the shortcut. Is it acceptable for you?

**Comment by gzotti** [comment]
This is yet another interesting application. Yes, you can do that, but it will not close this issue. 

Around 2014 I had envisioned this "rise on true horizon" and made the landscape transparency query for this. Then I was busy with other improvements... Finally we could try this in terms of 
* Compute rise on math horizon
* go by minutes (or 4-minutes [1-degree steps]) until object center is above displayed landscape horizon. (or backward for subzero horizons.)
* Not sure if a fine search should then go back in 5-second steps or if this is good enough. Somebody will surely note...

In this case binary search is not advisable if realistic landscapes have weird blocking objects. Also, some exception must be handled for very high asymmetric horizons, which may leave a window e.g. for only some afternoon hours. I fear we must search all the way to math sunset. 

This is for the sun not exactly as sunrise is defined (upper rim), but should be close enough.

**Comment by alex-w** [comment]
> This is yet another interesting application. Yes, you can do that, but it will not close this issue.

Hmm... I re-read the last item and you are right - it will not close this issue.

But I will think about my proposal more, because I see potential problem now - jumping to next/previously day near transit of selected object.

**Comment by alex-w** [comment]
OK, new actions partially resolve the latest point (after some handmain work)

**Comment by alex-w** [comment]
Oops... the issue was solved in december 2021
