### ISSUE TITLE
 Good morning. There is an error in the spherical mirror projection. I have an alienware 17 R4 computer with an NVIDIA GTX 1070 graphics card. Please help. Thank you.

### ISSUE THREAD

**Issue by marsanta11** [Stellarium/stellarium#495]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by marsanta11** [comment]
Good morning. There is an error in the spherical mirror projection. I have an alienware 17 R4 computer with an NVIDIA GTX 1070 graphics card. Please help. Thank you.
Stellarium 18.2
OS WINDOWS 10
NVIDIA GTX 1070

**Comment by gzotti** [comment]
Do you mean #390?

**Comment by gzotti** [comment]
Yes, the message you left in the other thread indicates you are reporting a duplicate. Please use beta of (probably) tomorrow.  Closing.
