### ISSUE TITLE
Scripts should be able to activate plugins

### ISSUE THREAD

**Issue by beltoforion** [Stellarium/stellarium#500]
**Is your feature request related to a problem? Please describe.**
If a Stellarium script requires a plugin there is no guarantee that it will run on a given installation of stellarium. Even if the plugin is present in the installation the script has no means of activating it. Without the proper set of plugins the script will fail.

**Describe the solution you'd like**
Suggestion 1: Add a command similar to the include command to allow scripts to signal a certain plugin is required.
<pre>
requires("CompassMarks");
</pre>

Suggestion 2.A: Add a Plugin Manager to Stellarium that a script can use to activate the plugins it needs.
<pre>
var available = PluginMgr.getFlagPluginAvailable("CompassMarks");
if (!available) {
    core.debug("CompassMarks plugin must be installed to execute this script!")
    core.exit();
}
PluginMgr.setFlagPluginActive("CompassMarks", true);

CompassMarks.setCompassMarks(true);
</pre>

Suggestion 2.B: Use the plugin manager to obtain a reference to the plugin without activating it in stellarium.
<pre>
var compassMarks = PluginMgr.getPlugin("CompassMarks");
if (!compassMarks) {
    core.debug("CompassMarks plugin not installed!")
    core.exit();
}

compassMarks.setCompassMarks(true);
</pre>

**Describe alternatives you've considered**
The only alternative is writing in the script documentation that the script will not run without the plugin being active. People rarely read the documentation even if they do they may not know how to activate the plugins.

**Comment by gzotti** [comment]
You say people rarely read documentation. They also rarely read logfiles. If I develop a script, I know and write into the comment what plugins are expected. And a foreign script should not be run blindly...

The message may look like

    CompassMarks plugin not installed!

instead of 

    script error: "ReferenceError: Can't find variable: CompassMarks" @ line 1

Is the difference worth the effort?

**Comment by beltoforion** [comment]
In my opinion this is a usability issue and its a maintainability issue. Lets take the sample "supernova.ssc" shipped with stellarium. The description states: "The supernovae plugin has to be enabled". 
Problem is: There is no plugin with that name. There is one called "Bright Novae" another one is called "Historical Supernovae". Which one is it? What if you are in a classroom settings and 20 kids have to enable the proper plugin?

A script could tell Stellarium with a requires statement exactly which plugin it needs or it could take care of activating it on its own. No further interactions needed.

**Comment by gzotti** [comment]
I would not care about the Novae plugin if the documentation states it requires the Supernovae plugin. 

Even if it could activate the plugin, it requires a restart of Stellarium. 

My personal opinion is:
https://github.com/Stellarium/stellarium/wiki/FAQ#why-dont-you-implement

However, we take contributions in code. If they don't break other things.

**Comment by beltoforion** [comment]
Ok, I was unaware of the requirement to restart. 

As for the "why-dont-you-implement" document. I share that sentiment. Is there a channel/forum where i can discuss beforehand what would be an acceptable idea that has a chance of getting into the codebase?

**Comment by gzotti** [comment]
We have a forum here: https://groups.google.com/forum/#!forum/stellarium. Of course you can simply file an issue like this, but if you need this function, my best bet is do-it-yourself, there are far more urgent issues on my personal list. Note that some issues stayed on the bug list for almost a decade.

**Comment by gzotti** [comment]
Given that Qt's QtScript module is deprecated and we must find a solution around this fact somewhere around (presumably) 2021 (Qt6?), this could be another requirement for the successor.

**Comment by beltoforion** [comment]
closed; not really that important

**Comment by axd1967** [comment]
While viewing #1542, I was also caught by this nova/sueprnova plugin confusion: I don't see the "supernova" plugin, 

![image](https://user-images.githubusercontent.com/3529789/110956499-f9ff2a80-834a-11eb-8526-313b47c82a1d.png)

but the `supernova.ssc` script says it needs it:

![image](https://user-images.githubusercontent.com/3529789/110956457-ef449580-834a-11eb-92fb-59ea5b3ebf5c.png)

nevertheless, the script runs fine, so at first sight it looks like a matter of changing the formulation in the script docs.

so at first sight this looks like a misnaming issue, as the plugin is somehow started:

```
Creating GUI ...
Loaded plugin "AngleMeasure"
Loaded plugin "ArchaeoLines"
Loaded plugin "Calendars"
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Loaded plugin "EquationOfTime"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "./modules/MeteorShowers/showers.json"
Loaded plugin "NavStars"

>>> Loaded plugin "Novae" <<<

[Novae] version of the catalog: 1
[Novae] loading catalog file: "./modules/Novae/novae.json"
Loaded plugin "Observability"
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at:  "./modules/Oculars/ocular.ini" . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Loaded plugin "PointerCoordinates"
Loaded plugin "RemoteControl"
RemoteControl using QtWebApp version 1.6.4-stellarium
StaticFileController: docroot=/home/alex/projects/stellarium/builds/master/share/stellarium/webroot, encoding=UTF-8, maxAge=60
StaticFileController: cache timeout=60000, size=1048576
Loaded plugin "RemoteSync"
stel.plugin.remoteSync: Plugin initialized
Loaded plugin "Satellites"
[Satellites] loading catalogue file: "/home/alex/projects/stellarium/configs/master/modules/Satellites/satellites.json"
Satellite has invalid orbit: "TIANWANG 1C (TW-1C)" "40926"
Loaded plugin "Scenery3d"
Registering RemoteControl extension service: "scenery3d"
Loaded 1 extensions for "Scenery3d"
stel.plugin.scenery3d: Scenery3d plugin - press KGA button to toggle 3D scenery, KGA tool button for settings
stel.plugin.scenery3d: Initializing Scenery3d renderer...
stel.plugin.scenery3d.renderer: Maximum texture size: 16384
stel.plugin.scenery3d.renderer: Maximum viewport dims: 16384 16384
stel.plugin.scenery3d.renderer: Maximum renderbuffer size: 16384
stel.plugin.scenery3d.renderer: Maximum framebuffer size: 16384
stel.plugin.scenery3d.renderer: Geometry shader supported
stel.plugin.scenery3d.renderer: GL_MAX_TEXTURE_IMAGE_UNITS: 32
stel.plugin.scenery3d.renderer: GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: 192
stel.plugin.scenery3d.renderer: Seamless cubemap filtering enabled
stel.plugin.scenery3d: Initializing Scenery3d renderer...done
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...

>>>> Loaded plugin "Supernovae" <<<<<<<<

[Supernovae] version of the catalog: 1
[Supernovae] loading catalog file: "./modules/Supernovae/supernovae.json"
Loaded plugin "TextUserInterface"
```

**Comment by gzotti** [comment]
@axd1967 The english string says
>The Supernovae plugin has to be enabled.

Is this a translation error in Dutch? You can do that via Transifex, please.

**Comment by axd1967** [comment]
Ah! didin't think of that, yes, thx. But the English version also refers to Supernova

https://github.com/Stellarium/stellarium/blob/da46a111638fbc3a963cd3a73956f7890267b963/scripts/supernova.ssc#L6

**Comment by gzotti** [comment]
I hope our users are able to associate an occasional informal mention of a "Novae" plugin with the "Bright Novae" entry in the plugin list, and "Supernovae" with the "Historical Supernovae" entry.

**Comment by axd1967** [comment]
* IMHO developers should try to stick to the correct naming to minimise confusion; it took me some time to understand the difference between the two, but to a user they are functionally identical, apart from maybe the `note` field. and as far as I can see, the lightcurves are parameterised slightly differently, I'm not sure this matters much for an average user. but I might be mistaken.
* a major difference is the datasource:
** https://stellarium.org/json/supernovae.json
** https://stellarium.org/json/novae.json
It might be interesting to mention in the source json from where the data is originally compiled from, and maybe where the scripts are that generate the data.
