### ISSUE TITLE
Markers and Custom objects created with the CustomObjectMgr cannot be selected at daylight. 

### ISSUE THREAD

**Issue by beltoforion** [Stellarium/stellarium#501]
### Description of the Behaviour
Custom objects created with the CustomObjectMgr cannot be selected at daylight. 

### Steps to reproduce
Open the script console (F12). Paste the following script:

<pre>
CustomObjectMgr.removeCustomObjects();
core.setTimeRate(0);
core.setDate("2018-10-10T12:00:00", "utc");
core.moveToAltAzi(10, 180, 0);
core.wait(0.2);
LandscapeMgr.setFlagAtmosphere(true);
CustomObjectMgr.addCustomObjectAltAzi("Not Selectable!", 10, 180, true);
</pre>

The custom object is created and shown. It cannot be selected. If you change the time to 22:00 the object becomes selectable.

### Additional Context
I was investigating whether i can abuse custom objects to make clickable menus. I wanted to create the custom object and then enter a loop and poll the selected object. I guess technically it would work but i dropped the idea. Other than this hack i have no application for custom objects at daytime so its not really an issue for me.

### System
* Stellarium version: 18.2
* Operating system: Linux Mint

**Comment by gzotti** [comment]
Indeed. This also applies to the markers manually set with Shift-Click (same class, slightly different use).
