### ISSUE TITLE
Markers for ephemeris calculations are positioned wrongly

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#51]
I wanted to check how the Sun will go with time, using the _Astronomical calculations_→_Ephemeris_ facility, but it appears that the markers are slightly off the target. For details see the screenshot below. I've enabled azimuthal grid to be able to see that _Altitude_ in the selected line doesn't match actual altitude in the scene.
![screenshot](https://user-images.githubusercontent.com/6376882/34297338-9e9480da-e728-11e7-974c-933f391e58e5.png)

**Comment by 10110111** [comment]
If I disable atmosphere visualization, then both the marker and the Sun go up, so it doesn't seem related to taking into account refraction vs not taking, at least not directly.

**Comment by alex-w** [comment]
This issue related to refraction.

**Comment by alex-w** [comment]
Thanks for report! The fix will be available in next release.
