### ISSUE TITLE
Light pollution setting reset after restart

### ISSUE THREAD

**Issue by mabatko** [Stellarium/stellarium#515]
### Expected Behaviour
Light pollution value entered manually in "View -> Sky ->Light pollution" should be preserved across restarts.
"Light pollution data from locations database" is preserved after restart.

### Actual Behaviour
Light pollution value is reset to 2 after every restart, no matter if set manually or set by "Light pollution data from locations database" option. 
"Light pollution data from locations database" option is unchecked after restart (even though location is preserved and set correctly).

### Steps to reproduce
Enter "Light pollution" manually. Restart. It's set to 2.
Check "Light pollution data from locations database". Restart. It's unchecked and "Light pollution" is 2.

### System
* Stellarium version: 0.18.2 and 0.90.0.16324
* Operating system: Windows 7
* Graphics Card: ATI Radeon HD 3470

### Logfile 
Can provide if really needed.

**Comment by alex-w** [comment]
Are you saved settings after changes?

**Comment by mabatko** [comment]
> 
> 
> Are you saved settings after changes?

I'm not saving anything. Is there a button for saving settings somewhere?

**Comment by alex-w** [comment]
If you did not pressed button "Save settings" (available through F2) then why you are expected saving the changes of settings?

**Comment by mabatko** [comment]
I wasn't aware of that button/option. I assumed it's saved by default. This bug can be closed then. Issue between chair and keyboard. Thank you!

**Comment by axd1967** [comment]
it is indeed not always 100% obvious what is automatically saved and what needs to be saved manually (but the current behaviour is fine).
