### ISSUE TITLE
Text overlap in Observability plugin

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#517]
I'm using a retina Macbook with OSX 10.14, same bug in fullscreen or windowed mode:

<img width="1136" alt="screen shot 2018-10-23 at 1 29 54 am" src="https://user-images.githubusercontent.com/35240993/47377509-d7add900-d6cb-11e8-953d-9f080500b77c.png">

[log.txt](https://github.com/Stellarium/stellarium/files/2507486/log.txt)

_Originally posted by @pacastro in https://github.com/Stellarium/stellarium/issues/388#issuecomment-432332971_

**Comment by pacastro** [comment]
Fixed in Stellarium 0.90.0.16357.dmg
