### ISSUE TITLE
Location Window map too small

### ISSUE THREAD

**Issue by pacastro** [Stellarium/stellarium#518]
### Expected Behaviour
Map displayed in location window extends to all the space available for it.

### Actual Behaviour
Map displayed in location window is too small using just small area at the center of its available space.

<img width="1136" alt="screen shot 2018-10-24 at 4 47 03 pm" src="https://user-images.githubusercontent.com/35240993/47458186-529bf000-d7af-11e8-88d2-da06c1df32c2.png">

Same behavior with maps of different planets selected.

### Steps to reproduce
Select location window, map displayed for selected planet shows smaller than it should.

### System
* Stellarium version: Stellarium-0.90.0.16362
* Operating system: OSX 10.14
* Graphics Card: Intel HD Graphics 5300, 2.1 INTEL-12.0.34

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/2512146/log.txt)

**Comment by guillaumechereau** [comment]
Can confirm the bug on MacOS.  I will have a look at that.

**Comment by guillaumechereau** [comment]
I pushed a fix.
