### ISSUE TITLE
Menu list slider weird behavior 

### ISSUE THREAD

**Issue by pacastro** [Stellarium/stellarium#519]
### Expected Behaviour
Drag slider up or down on menu list's and the list moves up or down accordingly.

### Actual Behaviour
Drag slider up or down, and menu list moves down or up for a bit and then the movement stop on the slider and the list moves on a weird way. See attached video, it's hard to describe. This problem happens in all the menu list's.

[Screen Recording 2018-10-24 at 10.11.59 PM.zip](https://github.com/Stellarium/stellarium/files/2512895/Screen.Recording.2018-10-24.at.10.11.59.PM.zip)

This is using V0.90.0.16362, if I try with V0.18.2 there is no problem with the slider.

### Steps to reproduce
Using V0.90.0.16362, open any menu that has a list to choose from: location window for example (as the attached video), go with mouse pointer to the slider just right to the list of countries, press mouse button to drag the slider up or down and after a few seconds of dragging the weird behavior starts.

This does not happen with V0.18.2, slider works ok.

### System
* Stellarium version: Stellarium 0.90.0.16362
* Operating system: OSX 10.14
* Graphics Card: Intel HD Graphics 5300, 2.1 INTEL-12.0.34

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/2512918/log.txt)

**Comment by gzotti** [comment]
This is the "kinetic scrolling" which was introduced recently. Don't drag the slider, drag the text inside, like on a smartphone/tablet. 

We may add a config option to the GUI. For now, edit config.ini and set

    [gui]
    flag_enable_kinetic_scrolling          = false

**Comment by pacastro** [comment]
Yep, dragging the text inside works. 

Its nice but slow for moving long list's, grabbing the slider and dragging it fast down/up is faster for searching something you don't remember the name for typing it in...

**Comment by pacastro** [comment]
Edited config.ini and seted kinetoc scrolling flag to false....

Now the slider works OK when grabbed and dragged, AND can drag the text inside the list also.

**Comment by alex-w** [comment]
@gzotti GUI option may be good solution here, but seems introducing this option with state on-the-fly switch will be problematic.

**Comment by gzotti** [comment]
I found a way to do it. :-)
