### ISSUE TITLE
Grouped onscreen Information of selected object 

### ISSUE THREAD

**Issue by t4saha** [Stellarium/stellarium#523]
When all information is on then some info displays outside of the screen. Information may be grouped by type (General,  #Position, Orbital, Catalogs, Additional) and shown in separate tabs on screen as a button layer.
![screenshot from 2018-10-25 16-31-09](https://user-images.githubusercontent.com/34002960/47499852-b93c0f00-d87e-11e8-8d73-94cb1a655f52.png)

**Comment by gzotti** [comment]
You seem to have either a too small screen or too large base font size, or both. Can you edit your config.ini:

     [gui]
     base_font_size                         = 13

And if you don't require some information, select what you can omit in the Information tab of the settings dialog (F2). On my FullHD screen, "All" information bits take about half the screen height.
