### ISSUE TITLE
Не обновляются каталоги звёзд

### ISSUE THREAD

**Issue by Dmitry564** [Stellarium/stellarium#528]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by Dmitry564** [comment]
При начале скачивании стоит отметка 0% и процесс не идёт

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#openssl-problems-in-the-logfile-missing-hips-surveys-cannot-download-additional-star-catalogs-windows
