### ISSUE TITLE
Stellarium 0.18.2 GPU/CPU hungry which causes it to lag on MacBook Pro

### ISSUE THREAD

**Issue by ToniOS11** [Stellarium/stellarium#529]
Ever since version 0.16, Stellarium has been very laggy for me when trying to use it on my MacBook Pro. After a little while, the app will start to make my CPU/GPU, (I only have an integrated GPU), very hot and thus makes the fans rev up like crazy.

Currently running Stellarium version 0.18.2

Device: Mid-2012 13" MacBook Pro, 2.9ghz Intel Core i7 Ivy Bridge, Intel HD Graphics 4000, 16gb DDR3 RAM, OSX 10.11.6

Note: For me, any version of Stellarium prior to 0.16 did not seem to have any of these problems.
![activity_monitor_stellarium-1](https://user-images.githubusercontent.com/36610930/47616187-d693f780-da8f-11e8-9f0c-dcf53cbd35d6.png)

**Comment by alex-w** [comment]
Please attach config.ini and log.txt from Stellarium

**Comment by ToniOS11** [comment]
Looking in the app right now and I can't seem to find either of those two files. Neither of these files are in there.

**Comment by alex-w** [comment]
See  ~/Library/Application Support/Stellarium

**Comment by gzotti** [comment]
Sounds like the old, well-known and often-reported  "My Mac is slow after 0.15.2" problem.

**Comment by alex-w** [comment]
>  After a little while, the app will start to make my CPU/GPU, (I only have an integrated GPU), very hot and thus makes the fans rev up like crazy.

@gzotti see quotation :)

**Comment by ToniOS11** [comment]
Looking in /Library/Application Support and do not seem to have a Stellarium folder in there
![screen shot 2018-10-28 at 9 59 04 am](https://user-images.githubusercontent.com/36610930/47616830-270f5300-da98-11e8-97bd-32b1b9a4b55b.png)

**Comment by gzotti** [comment]
@alex-w yes, it's the first to report "makes the fans rev up like crazy". The reporters from last spring did not mention the fan. But also "Ever since version 0.16, Stellarium has been very laggy for me when trying to use it on my MacBook Pro. " This is what several reporters told us.

@ToniOS11 
 - Please see chapter 5.2 of the Guide for the path.
 - I don't know whether Apple releases updates to the Intel GPU drivers. If yes, try to find those. At least on Windows, HD4000 is definitely capable of running Stellarium. 
- Also an observation: Mac users said it works fine with a mouse, only the touchpad was slow. A few fixes have been applied in the meantime, but something may still be missing.

**Comment by ToniOS11** [comment]
@gzotti That's where I looked and there is no Stellarium folder inside of it. The screenshot I posted in my last comment is the exact location specified in the 5.2 section of the guide. Also Apple updates it's drivers within the regular OS X updates I believe.

As for the touchpad, using a mouse for me doesen't do much good as the lag still exists. Touchpad is just as slow and also doesn't allow me to double tap/click on a object to focus on it anymore. But that is a separate issue from this in my opinion.

**Comment by ToniOS11** [comment]
It honestly feels like the app is not as optimized to run a Intel only GPU Mac.

**Comment by alex-w** [comment]
> Looking in /Library/Application Support and do not seem to have a Stellarium folder in there

It's fun. As I wrote you need `~/Library/Application Support/Stellarium` - why you tried to use other directory?

**Comment by alex-w** [comment]
Could you check our latest binary snapshot?

https://github.com/Stellarium/stellarium-data/releases/download/beta/Stellarium-0.90.0.16375.dmg

**Comment by ToniOS11** [comment]
Tested the latest binary just now. Mouse is slightl better, but only sligthly, touchpad is still very laggy as before along with Stellarium consuming once again over 40% of my CPU/GPU. This then causes it to drop frames like crazy at certain times.

Using a mouse to move around lets it work at 60fps, but sooner or later, the fps just starts dropping like a ton of bricks.

Stellarium right now just cracked 101% of CPU/GPU usage for a brief moment, don't even understand how that is even possible.
![screen shot 2018-10-28 at 12 37 56 pm](https://user-images.githubusercontent.com/36610930/47618894-b9225600-daae-11e8-9863-f1f484198559.png)

**Comment by ToniOS11** [comment]
Will add also that the worst frame dropping occurs whenever you are focused on something and locked on to it as it moves throught the sky.

**Comment by guillaumechereau** [comment]
I couldn't reproduce on my Macbook Air unfortunately.  Not sure if that is because the bug only affects MacBook Pro or if I didn't trigger the issue.

**Comment by alex-w** [comment]
@ToniOS11 do you have problems with new versions of Stellarium still?

**Comment by guillaumechereau** [comment]
I just got a MacBook Pro.  I can confirm there is indeed an issue.  Mostly the laggy touchpad is annoying.  I will make a bisect to see if I can find the cause of this if that is a regression.

**Comment by guillaumechereau** [comment]
OK, at least the trackpad issue is not related to the CPU issue.  The problem here seems to be a bug in the code used to smooth out the zoom animation, not working well with the MacBook Pro trackpad, that sends a lot of small delta.  The wheel handler in StelApp is supposed to accumulate the events to mitigate that, but that still doesn't work well.

I feel like it would be better to pass all the wheel events to the StelMovementManager no matter what and use a better smoothing algo there if possible.

**Comment by guillaumechereau** [comment]
I made a new branch: new-zoom-algo that fixes the trackpad issue on my macbook pro.  The behavior is slightly different that before so would be good to test a bit more to see if it is acceptable in all situation.

The new algo doesn't ease in the zoom animation for small changes, and ease in and out large zoom changes.  The previous algorithm systematically eases in when we zoom out and systematically eases out when we zoom in.  The problem with easing in small zoom changes is that the behavior then depends a lot on the frequency of wheel events, hence the trackpad bug.

**Comment by ToniOS11** [comment]
> @ToniOS11 do you have problems with new versions of Stellarium still?
Haven't been on in in some time as life has just gotten really busy. Anyways, since I first started this issue, I have moved from 10.11.6 El Capitan, to 10.14.6 Mojave. As of this time, I have yet to see any significant issues with Stellarium's trackpad zoom function. What I find now more than anything is that trying to zoom in smoothly is next to impossible as while far smoother in Stellarium Ver. 0.20.3, it ends up being very jerky most of the time. So for example, if I am locked onto a particular star and I go to zoom back out. I will usually, do one or two quick swipes with my fingers on the touchpad. Doing so results in several abrupt stop, go, stop go, etc moments while zooming in or out. Granted, I haven't been using Stellarium as much now, & and a lot of things have changed since I last posted on here.

**Comment by alex-w** [comment]
@guillaumechereau is new branch ready to merge? 

P.S. I can test it on notebook with linux on board, but I did not catch this bug before though.

**Comment by guillaumechereau** [comment]
My branch fixes a bug with macbook trackpad.  I tested it on a macbook pro, and also made sure it still works on my linux computer with a mouse.  I think it is ready to merge.

**Comment by ultrapre** [comment]
The new code cause scaling failure on android version (Qt for Android 5.15.2).

I reverted code here and zoom successfully recovered. Is there special code for different OS? I know less about them..

https://github.com/silas1037/stellarium/commit/0b5a83b685c33d1e8cb4123f5bd76836cfa6338f

Thanks.
