### ISSUE TITLE
Text of ocular onscreen control

### ISSUE THREAD

**Issue by t4saha** [Stellarium/stellarium#53]
When language is selected to Bengali, some texts are outside of ocular on-screen control area.
![ocular onscreen control](https://user-images.githubusercontent.com/34002960/34354995-509158a8-ea58-11e7-8c8e-585ab0f120fc.png)

**Comment by alex-w** [comment]
I cannot confirm the issue. Could you describe steps to reproduce the issue?

**Comment by t4saha** [comment]
it occurs in default settings. Just changed the language

**Comment by alex-w** [comment]
Are you using Windows?

**Comment by gzotti** [comment]
This may even be a font issue. On my Windows (Europe), switching to the most similar glyph set (sorry, I cannot read whether it says "Bengali") shows the panel correctly, but shows numbers and brackets in black (on black ground). And some numbers (only a few) are squeezed in the horizontal axis. Very strange. Seems to be the only language affected by this. But Arab has some right-to-left issues. Maybe I would also have to install some other language support libs?

**Comment by t4saha** [comment]
Ubuntu 17.10

**Comment by alex-w** [comment]
Wait! Which version you have installed?

**Comment by gzotti** [comment]
I tested this now on my old Ubuntu notebook: previous version 0.16.1 had this problem, updated it and 0.17 seems OK. (I see some characters missing in several languages, but this seems font related.)

**Comment by t4saha** [comment]
unity season ubuntu 17.10 with mesa mode

**Comment by gzotti** [comment]
Alexander wanted to know which version of Stellarium you have installed.

**Comment by t4saha** [comment]
Stellarium 0.17
& Stellarium daily build 0.99.1+201712211052~ubuntu17.10.1

**Comment by t4saha** [comment]
Solved in 0.18.2
