### ISSUE TITLE
Rises, Transists and Sets choice won't hold configuration.

### ISSUE THREAD

**Issue by cburford1** [Stellarium/stellarium#532]
In Stellarium 0.18.2 (x86) the rise, transists and sets configuration will not hold.

When I choose **Configuration** > **Information** > **Displayed fields** and select the **Rises, Transists and Sets** option. Then **Configuration** > **Main** > **Save settings.**

Exit and restart Stellarium and the above options are "unchecked" and do not display on selected object until configured again.

**Comment by alex-w** [comment]
Please check latest beta

**Comment by alex-w** [comment]
I cannot reproduce the issue in version 0.18.2 on linux

**Comment by cburford1** [comment]
> Please check latest beta

The beta version seems to fix this issue.
