### ISSUE TITLE
Can't update the new star catalog.

### ISSUE THREAD

**Issue by Anthrwpos** [Stellarium/stellarium#533]
Hi, i'm trying to update to star catalog 5 to 9, but the bar with the progress down right, is to 0 and disappear with no update.
What need to do? I have something wrong?
Thanks.

![42png](https://user-images.githubusercontent.com/20747347/47740356-4a94f200-dc80-11e8-9663-0530b90fde94.png)

**Comment by neao89** [comment]
Same issue here.  I've tried on both 32 and 64bit versions.  Can someone correct the MD5 mismatch?

Logs below:
Downloading file "https://github.com/Stellarium/stellarium-data/releases/download/stars-2.0/stars_4_1v0_2.cat"
Found file  "C:\\Users\\UserName\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_4_1v0_2.cat" , **checking md5sum..
Error: File  "stars\\default\\stars_4_1v0_2.cat"  is corrupt, MD5 mismatch**! Found  "d41d8cd98f00b204e9800998ecf8427e"  expected  "ac67dc390f9d414d61b1db76a5b820e9"

**Comment by alex-w** [comment]
Please check latest beta

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#openssl-problems-in-the-logfile-missing-hips-surveys-cannot-download-additional-star-catalogs-windows

**Comment by Anthrwpos** [comment]
@alex-w With 0.90.0.16375 beta, it works. But is latest that 0.18.2? And need to keep the beta?

**Comment by Anthrwpos** [comment]
@gzotti What is this exactly? Solution or something else?

**Comment by gzotti** [comment]
This is the pointer to the solution given as lament that still not everybody is able to follow instructions in the issue report questionnaire and check existing solutions listed in the wiki/Frequently Answered Questions. 

Yes, beta from last weekend is later than release from August.
If current beta works for you, then keep using it. Usually regard "beta=better".

**Comment by Anthrwpos** [comment]
So, need to download an OpenSSL file to fix the problem?

**Comment by alex-w** [comment]
> So, need to download an OpenSSL file to fix the problem?

No, this is will not help, because version 0.18.2 has broken code for following HTTP redirects

**Comment by Anthrwpos** [comment]
Ok. So, need to wait for the new update?

**Comment by gzotti** [comment]
You said the beta works for you. Use it (or later betas). There is no problem using a beta version. 
Case closed.

**Comment by Anthrwpos** [comment]
But beta can update or it's stays beta? Because it's from July 1.

**Comment by alex-w** [comment]
The current beta will be come on December as release with additional fixes of course.

**Comment by jmlobert** [comment]
When I click on that button, it briefly says "downloading in 4 s", then nothing happens.

**Comment by Anthrwpos** [comment]
@jmlobert Hi, you tried the beta version as suggested above?
