### ISSUE TITLE
Build instructions incorrect

### ISSUE THREAD

**Issue by doug719** [Stellarium/stellarium#537]
### Expected Behaviour
Trying to build stellarium-0.18.2 from source

### Actual Behaviour
1. cannot execute cmake from builds/unix since no CMakeLists.txt
2. if copy CMakeLists from top directory to builds/unix and execute
    cmake -DCMAKE_BUILD_MODE=Release ../../stellarium-0.18.2
   get error:
  CMake Error: The source directory "/home/doug/stellarium-0.18.2/stellarium-0.18.2" does not exist.
3. If in stellarium-0.18.2/src directory
   try   cmake -DCMAKE_BUILD_MODE=Release
    get error:
    CMake Error at CMakeLists.txt:278 (QT5_ADD_RESOURCES):
  Unknown CMake command "QT5_ADD_RESOURCES".

### Steps to reproduce
see above steps
### System
* Stellarium version: 0.18.2
* Operating system: Fedora 28
* Graphics Card: Nvidia gtx 660

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Sorry, but your steps is wrong - please read the instructions

**Comment by gzotti** [comment]
Follow https://github.com/Stellarium/stellarium/wiki/Compilation-on-Linux after https://github.com/Stellarium/stellarium/wiki/Linux-build-dependencies. 
Read path names more carefully, and adapt to your path names.
