### ISSUE TITLE
Show tracks for several selected planets

### ISSUE THREAD

**Issue by psknick** [Stellarium/stellarium#539]
Now there is a possibility to show the track for one selected planet. Please provide a choice of 3-4 planets whose tracks will be visible at the same time.
![2018-11-04-21 27 40](https://user-images.githubusercontent.com/44753018/47968264-8f51cc00-e078-11e8-87e8-13270fd17c9c.jpg)

**Comment by alex-w** [comment]
Just uncheck the second checkbox ;)

**Comment by psknick** [comment]
"Just uncheck the second checkbox ;)"

You do not understand me. I do not need the tracks of all the planets. I want to choose tracks 3-4 planets that interest me.

**Comment by alex-w** [comment]
The enhancement will be available for testing in next beta.

**Comment by alex-w** [comment]
Please test Stellarium version 0.19.0.16893 or later.
