### ISSUE TITLE
17.0 Toolbar Icons Missing

### ISSUE THREAD

**Issue by DonSch** [Stellarium/stellarium#54]
I'm running an older PC with Windows 10 and an ATI Radeon HD 3200 Graphics card.  I launched Stellarium in Angle Mode with previous versions and do so with 17.0 also, and it worked fine previous to the upgrade.  Now when I launch Stellarium my toolbars are blank.  I can use the keyboard shortcuts to bring up thinks like the Azimuth sphere, and when I do click in the toolbars where I think a tool should be I do momentaril get the tool up in the screen but it quickly disappears.  When I launch Stellarium normally, (not in Angle mode ) everything is working fine, but when I exit out my display becomes "garbled" and extremely pixelated and I'm forced to restart the pc before it degenerates so badly my display is completely garbled.  I know this is an issue with my older graphics board but I was wondering if you have any suggestions.  Thanks for a great planetarium software.
[log.txt](https://github.com/Stellarium/stellarium/files/1587524/log.txt)

**Comment by gzotti** [comment]
Blank toolbars were an indication of running ANGLE in DirectX3D v11 mode. But I see you started in v9, so I am afraid there is not much you (or we) can do. Maybe run in MESA mode. Or find a slightly newer graphics card at some electronics junkyard. And of course, keep graphics drivers updated!

**Comment by DonSch** [comment]
Thanks, Gzotti.  I've tried MESA mode just now and it appears to not have either of the side effects we talked about.  I've been looking at newer PCI Express Graphics cards and will probably upgrade my old PC.  Got any recommendations?

Thanks for the quick response.  I appreciate it.

**Comment by gzotti** [comment]
Yes, MESA mode circumvents your GPU totally and computes everything on your processor. 
Your ATI card is technically from 2008. If you are else still happy with your system, really, just try "any" used graphics card made around 2010 or later.

**Comment by DonSch** [comment]
Thanks, again.  
Don
