### ISSUE TITLE
Isolate asterisms

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#541]
Some asterisms are hard to see, as there is no way to isolate them as for now. It would be useful to press Alt+'whatever button' or something, select a star in a particular asterism and have all other asterisms turned off, just like with real constellations.

**Comment by alex-w** [comment]
One star may incorporated into few asterisms and it's not possible to guess what asterism you want to see.

**Comment by Atque** [comment]
@alex-w The same problem happens in several sky cultures (Arabic, Lakota, Maori, Belarusian and possibly a few more), where the same star is part of several constellations, at which Stellarium seems to prioritize one of them over the others. Maybe based on the constellation ID?
