### ISSUE TITLE
Satellites not updating

### ISSUE THREAD

**Issue by cburford1** [Stellarium/stellarium#542]
Satellites not updating at specified interval. Waited longer than indicated **< 1 minute** prompt. Screen capture and log file attached.
![capture](https://user-images.githubusercontent.com/44602435/48175830-46498400-e2d3-11e8-8d50-44d3e6e82028.PNG)
[log.txt](https://github.com/Stellarium/stellarium/files/2560180/log.txt)

**Comment by alex-w** [comment]
What is happens when you press the "Update now" button?

**Comment by cburford1** [comment]
> What is happens when you press the "Update now" button?

The Update Now button will perform the update with no problem.

**Comment by gzotti** [comment]
The update-on-launch did not work properly. However, I am also missing the progress bar.
