### ISSUE TITLE
Stellarium 0.18.2 and GPS

### ISSUE THREAD

**Issue by deetee99** [Stellarium/stellarium#544]
Using a GPS Dongle GPS Glonass. I've modified the section GUI to recognise the correct COM and Stellarium sees it, but when I go to Location and click GPS it just cycles through "Gps Location Fix" and doesn't get the coordinates nor altitude. I have been trying this outdoors.

Model Name:     MacBook Pro
  Model Identifier:     MacBookPro9,1
  Processor Name:       Intel Core i7
  Processor Speed:      2.3 GHz
  Number of Processors: 1
  Total Number of Cores:        4
  L2 Cache (per Core):  256 KB
  L3 Cache:     6 MB
  Memory:       8 GB
  
Chipset Model:  NVIDIA GeForce GT 650M
  Type: GPU
  Bus:  PCIe
  PCIe Lane Width:      x8
  VRAM (Total): 512 MB

Windows 10 Home
  Version 1803
   Build 17134.376

**Comment by alex-w** [comment]
Please show config.ini and log.txt from Stellarium

**Comment by gzotti** [comment]
I have written section 5.5.4 in the Guide for you. Having no Mac, I don't know if you need to set permissions for your user account to access serial connections. But you should use GPSD to avoid that in the first place.

**Comment by deetee99** [comment]
> GPSD
I've no idea what GPSD is...I'm not a developer...nor high tech.

**Comment by alex-w** [comment]
@gzotti he has Windows on this MacBook Pro, so, without log and config (to the checks) we cannot say anuthing about possible troubles.

**Comment by gzotti** [comment]
Ah right. I fail to understand Windows on Mac... 
OK, no GPSD possible. Still section 5.5.4 and previous comments on what's missing applies. Manuals are where non-techs can read to inform themselves.

**Comment by deetee99** [comment]
Took a while to find them

[config.txt](https://github.com/Stellarium/stellarium/files/2573589/config.txt)
[log.txt](https://github.com/Stellarium/stellarium/files/2573590/log.txt)

**Comment by alex-w** [comment]
Hmm. Please check our beta version - https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by deetee99** [comment]
Installed the Beta...reads the longitude and latitude ok, but no altitude.

[config.txt](https://github.com/Stellarium/stellarium/files/2581812/config.txt)
[log.txt](https://github.com/Stellarium/stellarium/files/2581813/log.txt)

**Comment by gzotti** [comment]
Let the GPS run for a few minutes before querying. This looks like an incomplete fix.

**Comment by deetee99** [comment]
DId that...ran it with the proprietary software until it started flashing and all the data was read..then I closed that and when into Stellarium. I'll try it again

**Comment by deetee99** [comment]
Still no luck with this...I think I'll just give up and use and handheld gps

**Comment by gzotti** [comment]
Sorry if this doesn't work for you. Without your hardware, we cannot fix it. Of course, entering coords manually is always possible.
