### ISSUE TITLE
Menu fonts blurred with fractional scaling

### ISSUE THREAD

**Issue by alexara** [Stellarium/stellarium#546]
### Expected Behaviour

Menu fonts are sharp independend of the scaling.

### Actual Behaviour

- A scaling factor of 1.0 makes the menu font tiny but sharp. 
- A fractional scaling of 1.5 or similar makes them blurry. 
- With a scaling of 2.0 the menu fonts become less blurred but seem to be miss anti-aliasing at least.

Here's a screenshot with scaling = 1.5 (equivalent to 144 DPI)
![screenshot_20181110_193530](https://user-images.githubusercontent.com/13819719/48304861-8c942280-e521-11e8-880c-3a11b277a051.png)

**Edit:** You can see the issue better in the following screenshot, especially when you click on it:
![screenshot_20181110_203404](https://user-images.githubusercontent.com/13819719/48305290-3676ad80-e528-11e8-8419-f27bbd1e452e.png)

### Steps to reproduce

1. Set up Stellarium on a device with a HiDPI screen
2. Set the font scaling to something fractional, e.g. 144 DPI
On KDE: Go to the system settings -> display and monitor ->  display scaling
3. Compare the menu fonts to the fonts of the interface at the borders.

### System
* Stellarium version: 0.18.2
* Operating system: Manjaro (KDE) 
* Graphics Card: Intel HD Graphics 620 driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.3 driver: intel unloaded: modesetting resolution: 2560x1440
           OpenGL: renderer: Mesa DRI Intel HD Graphics 620 (Kaby Lake GT2) v: 4.5 Mesa 18.2.4

**Comment by gzotti** [comment]
Patient: It hurts when I press here.
Doctor: Don't press here.

Honestly, I can hardly see the problem. However, next beta allows font scaling, this may help. 
Or maybe send each of us a HiDPI screen so that we can commiserate with you. There are worse issues to fix, though.

**Comment by alexara** [comment]
> Honestly, I can hardly see the problem.

I have to admit, it looks worse in reality than in the screenshot. :)

> However, next beta allows font scaling, this may help.

Sounds promising! I will give you feedback.

> Or maybe send each of us a HiDPI screen so that we can commiserate with you. There are worse issues to fix, though.

You are right, however I wanted to track the issue at least.

**Comment by goetzc** [comment]
I'm also experiencing this issue (on X11, KDE Plasma). 

As this is a Qt application, I think you need to set the `Qt::AA_EnableHighDpiScaling` attribute, as explained [here](https://doc.qt.io/qt-5/highdpi.html).

**Comment by alex-w** [comment]
Please check our AppImage: https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by ericschdt** [comment]
I'd like to give you some feedback. I have tested the latest appimage version `0.19.2.17327` with fractional and though most is now sharp and crisp :), some other parts are not:

![Screenshot_20191031_234658](https://user-images.githubusercontent.com/43318127/67991393-fcb71f00-fc30-11e9-89ed-97a2ea2a00b4.png)

or in the splash screen for example the version number on the top left:

![Screenshot_20191031_235353-1](https://user-images.githubusercontent.com/43318127/67991527-751de000-fc31-11e9-9202-c00ad496dd09.png)


[stellarium_appimage.log](https://github.com/Stellarium/stellarium/files/3796075/stellarium_appimage.log)
