### ISSUE TITLE
Wrong detection of GLSL version

### ISSUE THREAD

**Issue by parolx** [Stellarium/stellarium#549]
### Actual Behaviour
Stellarium does not detect GLSL Version correctly. Ignoring warning about Open GL Version leads to crapped fonts.

Both glCapsViewer and gpuCapsViwer detect correct version, see screenshots.
![opengl](https://user-images.githubusercontent.com/45035312/48480667-77621100-e80b-11e8-8e8e-43584ba41199.png)

### System
* Stellarium version: stellarium-0.18.2-win64
* Operating system: Windows 7 Ultimate Version 6.1, Build 7601, SP1
* Graphics Card: Two graphic cards: NVidia GE Force GT525M and  Intel(R) HD Graphics Family, see screenshots.
![nvidia](https://user-images.githubusercontent.com/45035312/48480439-b774c400-e80a-11e8-818a-6f4f15c8d67c.png)
![intel](https://user-images.githubusercontent.com/45035312/48480453-cce9ee00-e80a-11e8-8f13-627ade321841.png)

### Logfile 
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "2.1.2"
Current Format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelMainView::init
Detected: OpenGL "2.1"
Driver version string: "2.1.2"
GL vendor is "NVIDIA Corporation"
GL renderer is "GeForce GT 525M/PCIe/SSE2"
GL Shading Language version is "1.20 NVIDIA via Cg compiler"
GLSL Version Number detected:  1.2
This is not enough: we need GLSL1.30 or later.
You should update graphics drivers, graphics hardware, or use the --mesa-mode option.
Else, please try to use an older version like 0.12.9, and try there with --safe-mode
Config option main/ignore_opengl_warning found, continuing. Expect problems.

**Comment by alex-w** [comment]
Could you add Stellarium to the high perfomance list of applications and check the log again?

**Comment by parolx** [comment]
Do you mean this list?
![highperf](https://user-images.githubusercontent.com/45035312/48481818-1ccab400-e80f-11e8-876b-52536b75ec25.png)

Has no effect. Does not matter if I change preferred processor in global settings or program specific.

**Comment by alex-w** [comment]
> Do you mean this list?

Yes. Thanks for the info.

**Comment by parolx** [comment]
Also no change if I switch the second display off.

P.S. glCapsViewer uses also Qt5. So should be not difficult to fix it.

**Comment by gzotti** [comment]
Or what happens if you update the Geforce drivers? GPU Caps Viewer indicates a drive date from 2013. Ancient these days.

**Comment by gzotti** [comment]
Timeout.

**Comment by alex-w** [comment]
I think this report shouldn't be simple closed because we really have problem on systems with 2 GPU and, seems, on some systems on 1 GPU (esp. on OSX and Windows). I've checked the code of glCapsViewer and saw, that this software don't use Qt's way to get the OpenGL version. Maybe we should rewrite the function to detect OpenGL and GLSL versions with low-level requests to OpenGL core. But it need experiments.

**Comment by gzotti** [comment]
I have an Optimus notebook, and OpenGL is detected according to whether I run with Intel or Geforce. This report cannot be verified, and OP did not follow up for more than 1 month.

**Comment by 10110111** [comment]
Related question at StackOverflow: https://stackoverflow.com/q/18071669/673852. An answer there does have a suggestion (point (3)).

But yes, until we have a user with an NVIDIA Optimus @ Windows system, we can't check this.

**Comment by gzotti** [comment]
I have an Optimus system, and all works flawlessly. I can select which GPU to use, and yes, when running on batteries, the Intel side good enough, so I would not hardcode preference for a Geforce.
 
OP has a Geforce driver from 2013, which I currently see as source of the problem. However, he did not reply since November 2018, so I assume he has either solved it or lost interest.

**Comment by 10110111** [comment]
> so I would not hardcode preference for a Geforce.

Well, a user (not necessarily the OP) might want to force NVIDIA regardless of AC power availability. It might be good as an option. Not sure though how one would go with the solution in the StackOverflow link: exporting a variable is something done at compile time. It might be possible to make the executable self-modifying (like rename the `NvOptimusEnablement` symbol to disable the preference), but this sounds like a dirty hack.

I guess this report should be closed as abandoned if the user setting to force NVIDIA is not what we want.

**Comment by gzotti** [comment]
You can always force Geforce usage in the Geforce driver panel shown above. This works on my Optimus system with driver 411.63. Maybe OP just would have to update his drivers 311.0 from 2013. 

I had closed it before as OP apparently lost interest. Old drivers are SEP.
