### ISSUE TITLE
program language for Chinese Traditional

### ISSUE THREAD

**Issue by freemanli** [Stellarium/stellarium#55]
Hi,

The program languages for zh_TW (臺灣正體中文) and zh_HK (香港繁體中文) do not work on version 17.0. It seems we only have correct sky culture languages of zh_TW and zh_HK.

Warmest Best,
Freeman

**Comment by alex-w** [comment]
Files with translation of the GUI for both languages was empty due errors in special chars in the files - conversion tool do not run properly for both files. I've fixed the errors and upload translations.

Could you check both languages on Transifex - https://www.transifex.com/stellarium/stellarium ?
