### ISSUE TITLE
Stellarium Crashes on Raspberry Pi 3B(+)

### ISSUE THREAD

**Issue by angelofraietta** [Stellarium/stellarium#550]
### Expected Behaviour
Stellarium will run complex  displays without crashing
### Actual Behaviour
Describe or maybe attach a screenshot?
Find a link to a video showing it. I found that I can get same result running a script
https://drive.google.com/file/d/1T6cfnYuQWCZZQtvNdP5xSiCQmGjgeyKd/view?usp=sharing

### Steps to reproduce
This crashes on raspberry Pi. I first discovered bug when doing rapid remote control changes. I found I could reproduce crash consistently just by running the script double_stars.ssc

It does run some scripts OK, however, I get it to consitently fail on this script

It runs fine on both Mac and Windows - Just Raspberry Pi

### System
* Stellarium version: <Name of downloaded installable file?>
This is shown crashing with https://github.com/Stellarium/stellarium/releases/download/v0.18.2/stellarium-0.18.2.tar.gz

Also tried with latest pull from github - crashes in slightly different place 

* Operating system: <Name, version number>
This was tried with Raspbian stretch.

* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model
 number), driver version?>
This has been tested on Raspberry Pi 3B and Raspberry Pi 3B+

Open GL tested
http://www.raspberryconnect.com/gamessoftware/item/314-trying_out_opengl_on_raspberry_pi_3

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

You will notice in the journal below that this happens as it is crashing

Nov 16 08:46:37 hb-b827eb9089ee kernel: vc4-drm soc:gpu: failed to allocate buffer with size 5595136
Nov 16 08:46:37 hb-b827eb9089ee kernel: vc4-drm soc:gpu: failed to allocate buffer with size 16777216
Nov 16 08:46:37 hb-b827eb9089ee kernel: vc4-drm soc:gpu: failed to allocate buffer with size 16777216

[SystemJournal.txt](https://github.com/Stellarium/stellarium/files/2587199/SystemJournal.txt)

**Comment by gzotti** [comment]
The VC4 OpenGL driver is still described as "experimental" by the Raspberry Foundation. This explains why. I have written my observations here: 
https://github.com/Stellarium/stellarium/wiki/Raspberry-Pi

I observed a similar problem around GPU memory when using the DSS layer. 
Our "official" platforms are x86/x64 systems. You are cordially invited to help improving its stability on Raspberry Pi /ARM as well.

**Comment by angelofraietta** [comment]
Do you get crashing on the same script? I had trouble with installing
messa. If you have it crashing the same, then I will know it is not just
the environment I have built under.

Thanks
-- 
Dr Angelo Fraietta
A.Eng, A.Mus.A, BA(Hons), Ph.D.

Home Page
http://www.smartcontroller.com.au/

There are those who seek knowledge for the sake of knowledge - that is
CURIOSITY
There are those who seek knowledge to be known by others - that is VANITY
There are those who seek knowledge in order to serve - that is LOVE
    Bernard of Clairvaux (1090 - 1153)

**Comment by angelofraietta** [comment]
I did run again from the instructions and it did compile fine. It appears
that that crash is happening with other programs, indicating the
experimental Open GL as you suggested.
I would appreciate if you could try running that script when you get the
chance in December.

-- 
Dr Angelo Fraietta
A.Eng, A.Mus.A, BA(Hons), Ph.D.

Home Page
http://www.smartcontroller.com.au/

There are those who seek knowledge for the sake of knowledge - that is
CURIOSITY
There are those who seek knowledge to be known by others - that is VANITY
There are those who seek knowledge in order to serve - that is LOVE
    Bernard of Clairvaux (1090 - 1153)

**Comment by gzotti** [comment]
Hmm, seems I did not say exactly which December... :-)

double_stars.ssc runs perfectly on my RPi4 (4GB RAM) on current Raspbian Buster. 

However, on the RPi3+, it fails quite soon with access violation. dmesg shows tons of errors:
`     [drm:vc4_bo_create [vc4]] *ERROR* Failed to allocate from CMA:`

There are a few bug discussions in the RPi fora, e.g. https://www.raspberrypi.org/forums/viewtopic.php?t=223363, however I have not found a solution that works. 


I switched off DSO images on my next test, and - voilà - it worked. So there is an issue with texture memory, and the ever growing collection of DSO images will not make things easier. Probably we must provide a little script for texture minimisation (convert all to 128x128px, or provide a reduced collection?) However, I wonder why texture allocation, or rather unsuccessful allocation, is not handled more gracefully?

**Comment by alex-w** [comment]
This is a good task for the community to participate in the contribution into Stellarium. Who wants to help us?

**Comment by alex-w** [comment]
@angelofraietta @gzotti is the problem still alive?

**Comment by gzotti** [comment]
OK, just ran the script twice on my RPi3B+ with Raspbian 10 (buster) and its Stellarium 0.18.3. No issues. Then I saw the background DSO images were switched off. Activated, ran, and -- boom. Memory error. So yes, still active, and I doubt we can do anything here. 

I have not yet updated this RPi3B+ to V11/Bullseye. I also did not self-compile here.

**Comment by gzotti** [comment]
Update for current RPi3B+ Raspberry OS 11/Bullseye: Its repo provides Stellarium 20.4. 

* Default graphics (OpenGL ES 3.2 Mesa 20.3.5) delivers less than 2fps but works. 
* Accelerated graphics (Glamor): Driver again identifies as Broadcom VC4 V3D 2.1. It provides OpenGL ES 2.0 Mesa 20.3.5. Program runs at about 6fps, but fails with the same memory issues when DSO images are visible. 

I have not stepped further into finetuning applications. Let's say RPi3 enjoys partial support...
