### ISSUE TITLE
Objects' raise/set time changes during night

### ISSUE THREAD

**Issue by mabatko** [Stellarium/stellarium#554]
### Expected Behaviour
Raise/culminate/set times are consistent during night

### Actual Behaviour
Raise/culminate/set times change during night

![stellarium-006](https://user-images.githubusercontent.com/41372990/48919943-1f27b080-ee96-11e8-903c-7e26cf58f57d.png)
![stellarium-007](https://user-images.githubusercontent.com/41372990/48919946-2484fb00-ee96-11e8-912e-cd76a94dbdb5.png)

### Steps to reproduce
- pick star on the east
- notice its set time
- speed up time
- notice set time when star is on the west
- there is a ~4 minutes difference

### System
* Stellarium version: stellarium-0.90.0.16394-win64.exe
* Operating system: Windows 7
* Graphics Card: Intel(R) HD Graphics Family

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/2609115/log.txt)

**Comment by alex-w** [comment]
On the first screenshot I see RTS times for 22 November, on the second screenshot RTS times on 23 November. Yes, the difference is ~4 minutes per day and this is correct.

**Comment by mabatko** [comment]
Times change during night gradually. There is not 4 minute jump on midnight.

**Comment by dkechag** [comment]
@mabatko Is correct. The rise/set/transit times for objects vary throughout the day. The HA calculation seems to be off at any time. 
I maintain a Polar Alignment application which calculates refraction, aberration, nutation etc, so it was matching Stellarium from about version 0.14x and on, but I started getting questions lately about why my app does not match Stellarium. So I looked into it and it seems some change was done around the switch to 0.18 (0.18.0 has the flaw, didn't go further back) that messed up (at least) the Hour Angle calculation. Looking into the reported issues, I saw that this one here is related and indeed it is simple to check, just start jumping hour by hour and see rise/set/transit times change around for objects.
Or compare to another source like USNO. Stellarium no longer matches it:
![screenshot 2018-12-03 at 20 39 47](https://user-images.githubusercontent.com/26407891/49400262-9c2b1380-f73b-11e8-827f-3d10dd65747d.png)
![screenshot 2018-12-03 at 20 30 28](https://user-images.githubusercontent.com/26407891/49400270-a51be500-f73b-11e8-8b5c-c4f2f149f640.png)

**Comment by mabatko** [comment]
@alex-w , interestingly enough, the Observability Analysis plugin shows times correctly (consistently). 

I tried version 0.18.1 in which was this feature added and it is broken there as well.

Screenshots from 0.18.3:
![stellarium-008](https://user-images.githubusercontent.com/41372990/50537700-a9cd9080-0b63-11e9-8ea0-757dc359b240.png)
![stellarium-009](https://user-images.githubusercontent.com/41372990/50537703-bbaf3380-0b63-11e9-9ba5-71f9ae040387.png)

**Comment by axd1967** [comment]
indeed, Obs plugin (in version **0.20.1**) does not suffer for this problem (and also correctly shows the transit time)

![image](https://user-images.githubusercontent.com/3529789/79848588-9205c580-83c1-11ea-8c06-06affe244e94.png)

**Comment by axd1967** [comment]
it also looks like
- set time is correct until just before the actual setting, and is recomputed after rise 
- rise time is correct once past rise time and is recomputed at set time
- the plugin probably does not take diameter into account
- the plugin does take refraction into account

at first sight, the plugin gives more correct data that Stellarium.

**Comment by axd1967** [comment]
> Hi folks,
> I'm running 6 astrophysics classes using Stellarium to plan and view the lunar eclipse 5/26/2021 from Manhattan Beach California. Very difficult to plan moonrise and set times if the times change based on what class is studying the program. Any fixes? It makes one feel that Stellarium is not to be trusted if rising/setting times change throughout the day.

As a workaround, consider using the Observability plugin instead (see https://github.com/Stellarium/stellarium/issues/554#issuecomment-617078153) ? Remember to review the plugin's parameters; and the plugin behaves strangely below the horizon.

**Comment by gzotti** [comment]
We will not fix it before May 26. But it is an open issue. When other issues which we consider more important will have been solved, this is on the list of issues which will at some point in time be fixed. However, this is still a voluntary/weekend project. The Zero in the version number has a reason.

The best thing to "plan" some eclipse moonrise or other event is to actually simulate it. Place the moon on the horizon and read the time.

**Comment by h2ologg** [comment]
Got it and thanks. I’ll rewrite my instructions to the students. 

Best,
Dan
