### ISSUE TITLE
Stellarium freezes if it starts in 4k

### ISSUE THREAD

**Issue by Marcoc0202** [Stellarium/stellarium#556]
### Actual Behaviour just when i try to zoom it blocks
Describe or maybe attach a screenshot?
When I open stellarium and try to zoom, it says "loading nebulae" and then it freezes.
### Steps to reproduce
I open stellarium, zoom into a random stars, the problem occurs.
### System
* Stellarium version: <0.90.0 16412>
* Operating system: <Windows 8.1>
* Graphics Card: <nVidia GeForce GTX 970, latest driver>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/2617810/log.txt)

**Comment by alex-w** [comment]
Could you try to run Stellarium in ANGLE mode and attach the log?

**Comment by Marcoc0202** [comment]
I'm sorry Alex, how can I run it in ANGLE mode?

**Comment by Marcoc0202** [comment]
In ANGLE mode it works PERFECTLY. I'm sending you the log. (even if you may not need it now, the problem is resolved) 
[log.txt](https://github.com/Stellarium/stellarium/files/2618461/log.txt)

**Comment by Marcoc0202** [comment]
Alex you're so kind. Super fast response time and the problem solved. I've had this problem for 2 months... Never been on github but this was wayyy too fast than I expected. Thank you so much for the work. I appreciate it so much!

**Comment by guillaumechereau** [comment]
Looks like the sampleShadow map function in the planet shader is the problem.  Not sure how we are supposed to solve this properly, and unfortunately I don't have a 4K screen to try it on.

**Comment by gzotti** [comment]
@guillaumechereau the logfile indicates issue #273. This should be unrelated. @Marcoc0202 you will see no planets in closeup in ANGLE. 
I fail to understand the real problem in #273, probably the pseudo-random function. It has worked with an older ANGLE version, and works on Raspberry Pi's native OpenGL ES2.0. I assume it is an ANGLE bug. 
All of my comments here are unrelated to 4k I think.

**Comment by Marcoc0202** [comment]
Yeah gzotti, I can't see planets, but it's not a problem! :) It's already so much that I can open Stellarium now hahaha

**Comment by alex-w** [comment]
The problem in ANGLE library in newet versions of Qt. We'll include into package old version to resolve the problem.
