### ISSUE TITLE
Information Moon distance

### ISSUE THREAD

**Issue by KnuelleWenzel** [Stellarium/stellarium#557]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by KnuelleWenzel** [comment]
Infotable : Distance Moon Earth is : 365107.861 Mio km, but it is 365107.861 km!!
![bildschirmfoto 2018-11-28 um 11 41 11](https://user-images.githubusercontent.com/43293826/49146635-dabb6b00-f302-11e8-857d-0316abb5ce61.png)
Best regards and thanks for that wonderful program!!
Alfred Knuelle-Wenzel

**Comment by alex-w** [comment]
Please check latest stable version of Stellarium - this issue already fixed.
