### ISSUE TITLE
Trying to add a comet; socket operation timed out

### ISSUE THREAD

**Issue by tempusfugitxxii** [Stellarium/stellarium#559]
Version  18.2
64 bit windows 10

I am trying to add comet 46P/Wirtanen and I get a message "Socket operation timed out"

This is what I did:
Configuration window>plugins>solar system editor>configure>import orbital elements in MPC format>Online search>   typed P/Wirtanen   ----> "Socket operation timed out"

Is there a solution to this issue?

thanks

**Comment by gzotti** [comment]
Please use current Beta version. 

https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#openssl-problems-in-the-logfile-missing-hips-surveys-cannot-download-additional-star-catalogs-windows
