### ISSUE TITLE
Can't find 46P/Wirtanen

### ISSUE THREAD

**Issue by jmlobert** [Stellarium/stellarium#561]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by jmlobert** [comment]
I cannot find comet 46P/Wirtanen in the search window in both versions 17 and 18.2. An older version 15 on another computer finds it just fine. Any idea why this is no longer in the catalog? 
Version 18.2, Windows 64-bit

**Comment by alex-w** [comment]
Are you added the comet 46P/Wirtanen into Stellarium before finding it?

**Comment by jmlobert** [comment]
I did not add anything manually, version 15 shows it, 17 and 18 do not.

**Comment by alex-w** [comment]
Standard ssystem.ini file from series 0.15 doesn't have comet 46P/Wirtanen. Standard config's for the Solar system bodies for series 0.16, 0.17 and 0.18 doesn't have elements for comet 46P/Wirtanen too. 

So, if standard config doesn't have the comet and you didn't add them then why you are expected to find it in the Stellarium?

**Comment by jmlobert** [comment]
Alex, I am not aware of having added anything to version 15, so I don't know why it shows up there. 
Anyway, how is that done, is it one object at a time or is there a database with comets and other objects that can be loaded?

**Comment by alex-w** [comment]
You may freely add or remove any comets and minor planets through Solar System Editor plugin (Shortcut to run the GUI: Ctrl+Alt+S).
