### ISSUE TITLE
Incorrect focal length for C1400 in Ocular plugin

### ISSUE THREAD

**Issue by stereochem** [Stellarium/stellarium#563]
Minor issue: One of the default telescopes, C1400, which seemingly models a Celestron C14 f/11 SCT, incorrectly has a focal length value of 3190mm instead of 3910mm.

Oculars 1.1.8
Stellarium 0.18.2, Windows

**Comment by gzotti** [comment]
This has been fixed a few weeks ago. And the new default instrument list is much larger.
