### ISSUE TITLE
Web on iPad - date/time buttons

### ISSUE THREAD

**Issue by KeesHooyman** [Stellarium/stellarium#568]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by KeesHooyman** [comment]
### Expected Behaviour: Clicking on date/time buttons increase or decrease date/time

### Actual Behaviour: nothing happens
Describe or maybe attach a screenshot? ---

### Steps to reproduce

### System
* Stellarium version: web on iPad, nog problems on windows

**Comment by gzotti** [comment]
Wrong tree to bark up...

Please report issues about stellarium-web where those should be reported.

https://github.com/Stellarium/stellarium-web/issues
