### ISSUE TITLE
Problem with ISS

### ISSUE THREAD

**Issue by PatrickSmithD** [Stellarium/stellarium#569]
The time of appearance of the ISS is out of phase with the real

**Comment by alex-w** [comment]
Are you checked it on the actual TLE?

**Comment by PatrickSmithD** [comment]
I just reviewed it and it's not the same data, how can I correct it?

**Comment by alex-w** [comment]
Please update TLE within Satellites plugin (Alt+Z) and check it again. In any way by default Satellites plugin should update TLE data every 72 hours - please check the date and time of latest update too.

**Comment by PatrickSmithD** [comment]
Update error :(

**Comment by alex-w** [comment]
OK, this explained the mistake in position, but why you have error in updates? Could you attach the log.txt from Stellarium?

**Comment by PatrickSmithD** [comment]
[log.txt](https://github.com/Stellarium/stellarium/files/2693255/log.txt)

**Comment by alex-w** [comment]
Are you have enabled firewall?

**Comment by PatrickSmithD** [comment]
I just deactivated it and it's still updating error

**Comment by alex-w** [comment]
Hmm. Any changes in the log after disabling firewall? Could you open celestrak.com in browser?

**Comment by alex-w** [comment]
Any news?

**Comment by BrentN49** [comment]
I,too, have observed the data presented by Stellarium regarding ISS is inaccuate. The program indicates the data is updated every 72 hrs, however, the data presented does not reflect the true data. When attempting to update with the Update button, I receive the "Update error" as well. I created an account with Space-Track and downloaded the TLE's. I manually updated the Satellites and now see the correct data reflected in the Stellarium program.  The biggest difference I see between the two data sets is the program inherently collects data for the spacestation named ISS wheras the common name in the TLE's I downloaded has the common name of ISS (Zarya) and there is no satellite just named "ISS". The catalog number for the spacestation, however, is the same between the two versions.

**Comment by alex-w** [comment]
@BrentN49 please attach log.txt file

**Comment by BrentN49** [comment]
[ChangeLog.txt](https://github.com/Stellarium/stellarium/files/3448917/ChangeLog.txt)
I don't have a "log.txt" file. I have a "Changelog.txt" file which I have attached.

**Note** This computer has had a few iterations of Stellarium over the years. I've merely loaded the new versions over the old when installing. A couple of days agao I loaded the latest version onto a laptop which never had a previous version installed and I don't experience the same issue. Perhaps that could be reason. I will wait for your response before uninstalling the problem program and trying a clean install of Stellarium on the computer I am experiencing issues with.

**Comment by PatrickSmithD** [comment]
Finally it worked for me in Ubuntu. The problem is still in Windows but since I use Ubuntu everything is perfect

**Comment by PatrickSmithD** [comment]
Thank you very much for your attention and help!

**Comment by alex-w** [comment]
Could you check version 0.19.3 on Windows?

**Comment by BrentN49** [comment]
Hello @alex-w it appears that all is working in this version (0.19.3.1) with regards this issue. The accuracy is even more precise than the ver. 0.19.2 I had installed. According to CalSky there is a transit of the Moon by the ISS on January 10th at 01h20m20.74s from my vantage point at 114.08°W / 50.7°N. As you can see by the attached screenshot the event is modeled quite accurately. There is no issue with the Update Satellite plug-in as far as producing any error (Windows 10). Unfortunately I can't check this version on the old laptop that did produce errors as it finally died!
![Capture2](https://user-images.githubusercontent.com/53197350/71988211-b4961900-31ec-11ea-9137-38d158ef29b3.PNG)

**Comment by alex-w** [comment]
Thanks for info!
