### ISSUE TITLE
LoadLibrary failed with error 1114

### ISSUE THREAD

**Issue by jalbala** [Stellarium/stellarium#57]
I can not start Stellarium. Every time I try, I get the same error: "LoadLibrary failed with error 1114: Error in a dynamic link library initialization routine (DLL)" and the start aborts. I've tried with versions 0.17.0 and 0.16.1 both 32 and 64 bits, and both languages English and Spanish. I use an HP G72 notebook with Intel core i3 with 4 GB of RAM, Windows 10 Pro 64 bit operating system compilation 15063.

**Comment by gzotti** [comment]
https://sourceforge.net/p/stellarium/discussion/278769/thread/39b5d2c0/?limit=25#b808
Please do not crosspost.
