### ISSUE TITLE
Some canned scripts won't run if you do not have western SkyCulture

### ISSUE THREAD

**Issue by angelofraietta** [Stellarium/stellarium#572]
### Expected Behaviour
I would expect constellations_tour to always run if I select it, regardless of why my sky culture is configured for

### Actual Behaviour
If you have another culture set (I used Tukano), the script does not run.

You need to manually (or add to the script) to change to western
Describe or maybe attach a screenshot?

### Steps to reproduce
Set Sky Culture to Tukano
run constellations_tour script

It is only a minor issue, but would be worth fixing so it always runs by adding
`core.setSkyCulture('western');` 

Probably related, but I suspect that the selectObjectByName only works if you have the correct Sky Culture.
EG, this will not work in Tukano, but does in western
`core.selectObjectByName('Spica', true);`

### System
* Stellarium version:0.18.1

**Comment by gzotti** [comment]
Sure. Finding objects by name requires the right context. But we cannot simply say "set Skyculture to Western", as we have several variants of "Western". So it is up to the user to call a script in the correct context. Given that existing scripts mostly have been created as examples and starting points for users' own creations, they are not guaranteed to work perfectly under all circumstances.

**Comment by alex-w** [comment]
Original script was created especially for standard western sky culture. I’ll add new one script for constellations tour for current sky culture (in additional to the constellations_tour.ssc) after 0.18.3 release.
