### ISSUE TITLE
Qt5SerialPort.dll not found error when trying to start release 0.18.3 classic for Win32

### ISSUE THREAD

**Issue by AlexWhiter** [Stellarium/stellarium#573]
### Expected Behaviour
stellarium.exe should start.

### Actual Behaviour
System reports stellarium.exe cannot be started because of missing Qt5SerialPort.dll.

### Steps to reproduce
1. Delete previous installation of Stellatium.
2. Install stellarium-0.18.3-classic-win32.exe.
3. Start stellarium.exe.

### System
* Stellarium version: stellarium-0.18.3-classic-win32.exe
* Operating system: Windows XP x86, SP2 (5.1.2600)
* Graphics Card: NVidia, Geforce 9600 GT, drivers version 6.14.11.7519

### Logfile 

The missing DLL is referenced from libstelMain.dll and Qt5SerialBus.dll.

Version 0.18.2 installs the necessary DLL, so if I first install 0.18.2 and then upgrade to 0.18.3, everything works as expected.
The problem only appears in case of the first-time installation.

**Comment by alex-w** [comment]
Thank you very much for report - it was packing issue and short version of testing process. :( Please download version 0.18.3.1.
