### ISSUE TITLE
New planet magnitude calculation has appeared

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#574]
There has appeared a new way of calculating planetary magnitudes. Mercury and Venus seem to be the ones most affected by this new formula.

The paper:
https://www.sciencedirect.com/science/article/pii/S221313371830009X?via%3Dihub

Stellarium could have this as an additional option for the 5 ways of displaying mangitudes given at the moment.

**Comment by gzotti** [comment]
Thanks, I'll have a look!

**Comment by alex-w** [comment]
[mallama2018.pdf](https://github.com/Stellarium/stellarium/files/3342602/mallama2018.pdf)
