### ISSUE TITLE
Stellarium 0.18.3 Changing font size for the screen has no effect on constellation names 

### ISSUE THREAD

**Issue by kajaji** [Stellarium/stellarium#576]
Expected Behaviour: 
Font size for constellation names should change.
Actual Behaviour
Font size for constellation names stays the same while every other text changes size on the screen.

Steps to reproduce
Configuration window
Tools tab
Font size: screen (change the font size)
System
* Stellarium version: 0.18.3
* Operating system: Windows 10

**Comment by gzotti** [comment]
Probably yes. But we should just make them direct settings, not relative to master font size, to simplify things.
