### ISSUE TITLE
Ubuntu 18.04: 0.18.3 unable to load star catalogs using AppImage with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by fscherie** [Stellarium/stellarium#578]
### Expected Behaviour

using pre-build, ready-to-run appimage 0.18.3 loading star calalogs  from web source should would (configurarion dialog)

### Actual Behaviour

starting star catalog download by pressing button end up with status error 

Error creating SSL context

Other users report problems downloading comet sources from web 

https://sourceforge.net/p/stellarium/discussion/278769/thread/5f50bc15db/

Since 
 
https://bugs.launchpad.net/stellarium/+bug/1738549

states that HTTP was replaced by HTTPS for communication there is a high possibility that the central point of failure is a incompatible OpenSSL release used for building AppImage (as far as I understood 1.1.0 drops some deprecated stuff used in 1.0.x)

So solution would be to provide an additional AppImage for Systems with OpenSSL 1.1.0 - or the OpenSSL release where issue starts. 

### System
* Stellarium version: 0.18.3 AppImage
* Operating system: Ubuntu 18.04 LTS
* Graphics Card: does not apply
* OpenSSL 1.1.0 installed

### Logfile 
n/a

**Comment by alex-w** [comment]
Sorry, we discontinue support an AppImage builds since version 0.20.3 due technical problems of AppImage architecture! Please use snap packages instead.
