### ISSUE TITLE
User interface problems with latest Oculars plug-in

### ISSUE THREAD

**Issue by mcovington** [Stellarium/stellarium#580]
Major problem:

The on-screen box for the Oculars plug-in is not big enough to show all the choices in effect, and there is no way to scroll it to reveal more of them.  In this way a user was unaware that he had chosen a Barlow lens (https://www.cloudynights.com/topic/645071-how-accurate-is-stellariums-fov-calculator/).

Changing the font size from 12 to 10 helps but is not sufficient.  Smaller font sizes are not permitted.

Other problems:

The 0.18.3 release of the Oculars plug-in wiped out my pre-existing telescope, lens, sensor, and eyepiece settings and gave me a motley list of new ones.  I had to create them all again.

When setting up new telescopes, lenses, sensors, or eyepieces, it is not possible to type past the decimal point without selecting the characters to be replaced.

Is there a way to go back to the previous release of this plug-in while sticking with Stellarium 0.18.3?  Alternatively I recommend fixing these bugs immediately, as they are the sort of thing that should have been caught in very early testing.

**Comment by gzotti** [comment]
OK, sorry for that one. Seems I did that while fixing a bunch of other issues around font scaling and unexpected behaviour of the GUI. (Fixing inherited underdocumented code is dangerous!)  To solve for now, add a 1-factor Barlow lens as first lens. However I don't see how the used Lens is _not_ being shown in the top-right GUI panel.

**Comment by alex-w** [comment]
OK, I've found the problem with editing settings for telescopes, lenses, sensors, or eyepieces. The fix will be available for testing in next beta and in the final release (0.19.1).

**Comment by alex-w** [comment]
Please test Stellarium version 0.19.0.16893 or later.

**Comment by mcovington** [comment]
All fixed in 16893 as far as I can tell.  Thanks!
