### ISSUE TITLE
A bug about constellation boundaries

### ISSUE THREAD

**Issue by sunshuwei** [Stellarium/stellarium#582]
If you add the constellation boundaries of another (non-western) skyculture, stellarium will crash when you toggle skycultures.

**Comment by alex-w** [comment]
Please show the log and info.ini from the skyculture.

**Comment by alex-w** [comment]
And share the boundaries file please

**Comment by sunshuwei** [comment]
I added three boundaries for testing.
[constellations_boundaries.zip](https://github.com/Stellarium/stellarium/files/2725285/constellations_boundaries.zip)

**Comment by alex-w** [comment]
Please use `boundaries = own` in the info.ini file

**Comment by sunshuwei** [comment]
> 
> 
> Please use `boundaries = own` in the info.ini file to enable boundaries from the skyculture.
> 
> P.S. In any case I cannot catch a crash when skyculture is changed

Yes. It works perfectly.
Thank you for having solved the problem.
