### ISSUE TITLE
Where are years prior to 100 CE?  Can I get a copy of .9 if those are no longer available?

### ISSUE THREAD

**Issue by robertdknight** [Stellarium/stellarium#583]
Looking for events around year zero and prior.  These worked in stellariaum prior to .9.1 from what I can gather online.  I can't find any online copy of .9.0 anywhere to download.  Can we get years prior to 100 allowed in the Ephemeris calculations?

**Comment by alex-w** [comment]
Are you meant GUI for dates in AstroCalc/Ephemeris tool?
