### ISSUE TITLE
StelFileMgr problem?

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#589]
### Expected Behaviour
Application launches after building

### Actual Behaviour
Application fails to launch

### Steps to reproduce
Windows 10, git checkout 2e959c51

### System
* Stellarium version: master, 2e959c51dfb19cdaf5c4dbaa68a2c6737b44b553 or later
* Operating system: Windows 10

### Logfile 
Crash before logfile is initiated

None of the changes introduced with #586, #587, #588 runs on Windows 10.

**Comment by gzotti** [comment]
I wrote "Crash before logfile is initiated."

For years I have been using the build directory proposed by QtCreator. E.g. in a structure

     d:\StelDev\GIT
                 |--- stellarium
                 |--- build-stellarium-Desktop_Qt_5_12_0_MSVC2017_64bit-Release
                 |--- build-stellarium-Desktop_Qt_5_12_0_MSVC2017_64bit-Default
                 |--- build-stellarium-Desktop_Qt_5_12_0_MSVC2017_64bit-Debug

I am building inside build... and have a link inside stellarium that points to build.../src/stellarium.exe. 
The same process works on my Linux systems. 

     cd stellarium
     ../build/src/stellarium

PATH includes C:\Qt\Qt5.12.0\5.12.0\msvc2017_64\bin to find the Qt libraries.

What do I have to change to make development builds of Stellarium work again?

**Comment by alex-w** [comment]
Ahh... Georg, could you check the latest master?

**Comment by gzotti** [comment]
Hah-- yes, indeed that fixed it. Thanks!
