### ISSUE TITLE
Unable to set screenshot directory to home directory via GUI

### ISSUE THREAD

**Issue by santinod** [Stellarium/stellarium#59]
Whenever I try to set the screenshot directory to my home directory (e.g. /home/user) via the Configuration -> Tools GUI menu, the setting is not retained, and the next time I run stellarium it reverts to /home/user/Stellarium.
Manually setting screenshot_dir in the config.ini works as expected.
Tested on Ubuntu 16.04, stellarium 0.17.0.

**Comment by gzotti** [comment]
This is by design, and documented in the Guide, section 4.3.1. After changing a setting, you must explicitly store the settings in the Configuration panel to be active the next time you run Stellarium.

**Comment by santinod** [comment]
Ah, I see. I was deceived by the behaviour of the Configuration window: if I change a parameter and close then reopen it without explicitly saving the configuration the setting is retained, and I thought this would hold true across program restarts as well.
