### ISSUE TITLE
Screen flickers when night mode + DSS is turned on

### ISSUE THREAD

**Issue by PawelPleskaczynski** [Stellarium/stellarium#595]
Hello,

After turning on night mode and DSS images the screen flickers. The behavior is present on 0.18.2 version on both my machines (I'm using Linux with 4.20 kernel and latest Mesa drivers on laptop and Linux 4.19 with latest Mesa drivers on PC, both devices are with AMD cards). This issue is also present on version built from source code from GitHub.

Here's a video showing this bug: https://youtu.be/3dZlHJ-7Gdk

**Comment by gzotti** [comment]
Confirm on Win10 also. It flickers only until all tiles for the current view have been loaded.

**Comment by gzotti** [comment]
Note that DSS is also available as HiPS. I wanted to suggest you use that in night mode for now, but ... uh oh! Also HiPS flickers in Night Mode!

**Comment by guillaumechereau** [comment]
I found that this bug can be prevented if I comment out:

    StelApp::getInstance().ensureGLContextCurrent()

in StelTexture.cpp

I think the reason is that the call to glWidget->makeCurrent() done by ensureGlContextCurrent will change the bound OpenGL buffer.

I am tempted to remove the call, but I am not quite sure of what side effects this might have.

**Comment by gzotti** [comment]
Good question. From Qt help:

     void QOpenGLWidget::makeCurrent()
     Prepares for rendering OpenGL content for this widget by making the corresponding context current and binding the framebuffer object in that context.
     It is not necessary to call this function in most cases, because it is called automatically before invoking paintGL().

The calls were inserted by Florian who apparently had crashes with Scenery3D without them. (git history) But I cannot trigger a crash in a Scenery3d scene now. We could just try for a few weeks if that is the acceptable solution, but must test the scenery3d on all platforms.

**Comment by guillaumechereau** [comment]
Yes I think so too.  It seems that this was a woraround for a bug that should have been solved an other way.  I don't think the texture code should assume that the OpenGL context is always bound to a Qt widget.

**Comment by gzotti** [comment]
I was not able to trigger an issue with 3D sceneries so far, though, so I pushed this as tentative fix, but keep this issue open.

**Comment by alex-w** [comment]
Please check release 0.19.0 - this issue should be resolved

**Comment by PawelPleskaczynski** [comment]
I installed 0.19.0 and the issue is resolved 😃
