### ISSUE TITLE
Fishy assignment that makes some conditions always true

### ISSUE THREAD

**Issue by GabrielRavier** [Stellarium/stellarium#596]
Hello,

Because of this (unconditional) assignment at https://github.com/Stellarium/stellarium/blob/7fdf273df89ca2cd42b50f456158f7fef53b929f/src/gui/StelGuiItems.cpp#L718, part of the condition at https://github.com/Stellarium/stellarium/blob/7fdf273df89ca2cd42b50f456158f7fef53b929f/src/gui/StelGuiItems.cpp#L760 is always true and this condition https://github.com/Stellarium/stellarium/blob/7fdf273df89ca2cd42b50f456158f7fef53b929f/src/gui/StelGuiItems.cpp#L859 is always true.

If this was intentional, this should be documented. If it wasn't, this is probably a bug and should be fixed.

**Comment by gzotti** [comment]
George Gribkov told us the same a few days ago in https://groups.google.com/forum/#!topic/stellarium/04jFgmumERA.

This seems to be result of some refactoring and is IMHO 100% harmless. Yes, it needs further refactoring, and consequences of proper handling of updatePos needs investigation to understand why it was here in the first place.

**Comment by alex-w** [comment]
I guess I fixed the issue already :)
