### ISSUE TITLE
Weird while loop

### ISSUE THREAD

**Issue by GabrielRavier** [Stellarium/stellarium#597]
Hello,

The condition at https://github.com/Stellarium/stellarium/blob/7fdf273df89ca2cd42b50f456158f7fef53b929f/src/external/qtcompress/qzip.cpp#L617 is always true, because the variable at https://github.com/Stellarium/stellarium/blob/7fdf273df89ca2cd42b50f456158f7fef53b929f/src/external/qtcompress/qzip.cpp#L614 is never changed.

If this is intentional, this should be documented. If this is not, this is probably a bug and should be fixed.

**Comment by gzotti** [comment]
George Gribkov told us the same a few days ago in https://groups.google.com/forum/#!topic/stellarium/04jFgmumERA.

This is an issue in an external module and should probably be reported to the original authors.

**Comment by GabrielRavier** [comment]
I reported this at https://github.com/nezticle/qtcompress/issues/4, so I think this can be closed after they fix the bug and we put a fixed version back in this repo

**Comment by gzotti** [comment]
Thanks!

**Comment by GabrielRavier** [comment]
Seems like this was probably fixed years ago as there isn't even a `qzip.cpp` file anymore...
