### ISSUE TITLE
Memory leak in mesh.c

### ISSUE THREAD

**Issue by GabrielRavier** [Stellarium/stellarium#598]
If execution goes to https://github.com/Stellarium/stellarium/blob/7fdf273df89ca2cd42b50f456158f7fef53b929f/src/external/glues_stel/source/libtess/mesh.c#L312 then newVertex1, newVertex2 and newFace are not freed.

This is likely a bug and should be fixed.

**Comment by gzotti** [comment]
George Gribkov told us the same a few days ago in https://groups.google.com/forum/#!topic/stellarium/04jFgmumERA.

Seems these lines in this external module are from 1994 and were released by SGI in 2008. Is there a newer version of libtess that maybe even improved other things?

**Comment by GabrielRavier** [comment]
I searched around a bit on the internet, and found this : https://github.com/memononen/libtess2
However, "The API was changed to loosely resemble the OpenGL vertex array API." according to the README, so it may not be compatible with this project without changing internal code

**Comment by gzotti** [comment]
I have found https://chromium.googlesource.com/external/skia/third_party/glu/+/82532b9046be34a2ca93b650c5808a0827ecff16/libtess/mesh.c

Same code. 

The whole issue only fires if MakeEdge fails. Apparently this is a rare situation (out of memory?).

**Comment by GabrielRavier** [comment]
Yeah obviously, but a memory leak is a memory leak (which is even more problematic when there is a lack of memory, since a memory leak won't help in making the lack of memory go away)

**Comment by gzotti** [comment]
It is only a leak if it leaks. It leaks only in case of other problems which are probably fatal anyways and therefore were "allowed" in 1994 to cause program abortion. Is there anybody in the chromium project who knows circumstances when this fails (is it out-of-memory only?)? And would they care to handle/fix that properly? 
What is the correct solution? Just add the 3 memfrees in the e==NULL case?
