### ISSUE TITLE
Very weird math in StelHips.cpp

### ISSUE THREAD

**Issue by GabrielRavier** [Stellarium/stellarium#599]
The * operator has priority over the << operator.

This means that in the code https://github.com/Stellarium/stellarium/blob/5d8060cd02c6e7faa9d66c5dd65c56f1412b8ea3/src/core/StelHips.cpp#L271, the code is equivalent to `int nbw = sqrt((12 * 1) << (2 * order));`. This is likely a bug and should be fixed, likely by enclosing the `1 << (2 * order)` in parentheses

**Comment by gzotti** [comment]
George Gribkov told us the same a few days ago in https://groups.google.com/forum/#!topic/stellarium/04jFgmumERA.

Guillaume will hopefully fix it.

**Comment by GabrielRavier** [comment]
I read the article and noticed that these errors weren't fixed, so I filed issues about them, since they weren't fixed. Hopefully having issues that directly say "fix this" should make it so these are fixed soon and not just forgotten.

**Comment by guillaumechereau** [comment]
Thanks for reporting.  I pushed a fix.
