### ISSUE TITLE
Pink sky with 0.16.1 version on linux

### ISSUE THREAD

**Issue by lock042** [Stellarium/stellarium#6]
Since the update, the sky is pink during the day
![capture du 2017-10-17 16-49-57](https://user-images.githubusercontent.com/16907662/31672544-27b50dc6-b35d-11e7-9159-abe37b4dc443.png)

**Comment by gzotti** [comment]
Since which update, on which platform, etc. 
Bugs are please still reported on LaunchPad, following the guidelines from 
https://answers.launchpad.net/stellarium/+faq/2707

**Comment by lock042** [comment]
Oh Sorry for that.
Since 0.16.1 on linux as I said in the title.
Exactly I'm on debian. I will read the faq
