### ISSUE TITLE
GUI creates multiple Screenshot directories 

### ISSUE THREAD

**Issue by santinod** [Stellarium/stellarium#60]
When typing the Screenshot directory name into the Configuration -> Tools GUI, a new directory gets created at each keystroke. For example, entering "/home/user/images" as the directory name (and assuming the "/home/user" prefix was already present in the textbox) causes the "i", "im", "ima", "imag", "image", "images" directories to be created under /home/user.
Ubuntu 16.04, stellarium 0.17.0.

**Comment by gzotti** [comment]
Wow, confirmed also on Win10 :-O - Thanks for reporting!
