### ISSUE TITLE
Faulty contructor for Plane

### ISSUE THREAD

**Issue by GabrielRavier** [Stellarium/stellarium#600]
The code at https://github.com/Stellarium/stellarium/blob/5d8060cd02c6e7faa9d66c5dd65c56f1412b8ea3/plugins/Scenery3d/src/Plane.cpp#L29 creates an unnamed temporary Plane and deletes it right away.

This is probably a bug and should be fixed. Directly calling the constructor like this : `this->Plane::Plane(v1, v2, v3, SPolygon::CCW);` would likely work.

**Comment by gzotti** [comment]
George Gribkov told us the same a few days ago in https://groups.google.com/forum/#!topic/stellarium/04jFgmumERA.

It has been fixed.
