### ISSUE TITLE
Wrong behaviour of Location Dialog

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#602]
### Expected Behaviour
When user clicked on the list of locations then Stellarium should change the location and set time zone from location (if time zone is not user defined!) without changes the flag "Use custom time zone".

### Actual Behaviour
When user clicked on the list of locations then Stellarium changes the location and set time zone from location via enforcement setting the time zone as "Use custom time zone" (with resetting all user settings!). 

Last version with correct behaviour is 0.18.0.

Tested on Ubuntu Linux since version 0.17.0 to master.

### Logfile 
Not applicable here.

**Comment by gzotti** [comment]
Seems to be solved in #654, so far for terrestrial locations.
