### ISSUE TITLE
translation string #86 in the new scripts translation file

### ISSUE THREAD

**Issue by kajaji** [Stellarium/stellarium#603]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by kajaji** [comment]
M22: A Gen of a Globular
Did you mean M22: A Gem of a Globular

**Comment by alex-w** [comment]
Yes, you are right - it's typo. I'll update the script tonight.
