### ISSUE TITLE
Add New City

### ISSUE THREAD

**Issue by koushik-astro** [Stellarium/stellarium#606]
Please add the following city in the location list:
Location: Alipurduar
Latitude: 26° 29′ 20.4″ N
Longitude: 89° 31′ 37.2″ E
Elevation :	93 m

**Comment by gzotti** [comment]
Users can add their own locations very easily. 

Does this site fulfill the criteria based on number of inhabitants, importance for <whatever?>, observatory location,  etc, to justify addition to the default list?

**Comment by alex-w** [comment]
The city has over 65000 citizens - this is acceptable for including in the default list.
