### ISSUE TITLE
Freezed Stellarium in ubuntu 18.04.01. Suddenly get freezed all time

### ISSUE THREAD

**Issue by Leonardo22378470** [Stellarium/stellarium#614]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
#615 is the more appropriate report
