### ISSUE TITLE
Freezed

### ISSUE THREAD

**Issue by Leonardo22378470** [Stellarium/stellarium#616]
### Expected Behaviour

No to freeze

### Actual Behaviour

Stellarium get freezed often. No single action can be described to say "this is way" but get freezed often. Maybe it happendes more when serch an objet. I need to restart the hole pc when it happends.

### System
* Stellarium version: <0.18.3>
* Operating system: <Ubuntu, 18.04.01>
* Graphics Card: < Intel® Core™ i3-4330 CPU @ 3.50GHz × 4

**Comment by gzotti** [comment]
Logfile?
