### ISSUE TITLE
version 0.12 StelSphereGeometry.hpp fixed

### ISSUE THREAD

**Issue by xMeshman** [Stellarium/stellarium#622]
gcc 6.x and 5.4x casts
warning: function returns address of local variable [-Wreturn-local-addr]
The original code dereferenced pointers to variables beyond their lifetime
According to ISO/IEC 9899:2011 6.2.4 §2, "The value of a pointer becomes indeterminate when the object it points to reaches the end of its lifetime."
line 317 STELSPHEREGEOMETRY_HPP . . . 

	//! Get a vector of vertex positions forming the region.
	virtual const QVector<Vec3d>& getFillVertexPositions() const
	{
	        //return getOctahedronPolygon().fillVertices());
		static const QVector<Vec3d>& result(getOctahedronPolygon().fillVertices()); //fix
		return result; 
	}

	//! Get primitive type determining how vertices in vector returned by
	//! getFillVertexPositions() form triangles.
	virtual PrimitiveType getFillPrimitiveType() const 
	{
		return PrimitiveType_Triangles;
	}

	//! Get the outline of the contours defining the SphericalPolygon.
	//! @return a list of vertices which define the contours of the polygon.
	virtual const QVector<Vec3d>& getOutlineVertexPositions() const 
	{
		// This is a workaround around a compiler bug with Clang (as of Clang 3.2).
		// Returning the reference directly results in an uninitialized
		// reference which breaks calling code.
		//const QVector<Vec3d>& result(getOctahedronPolygon().outlineVertices());
		static const QVector<Vec3d>& result(getOctahedronPolygon().outlineVertices()); //fix const
		return result;
	}

**Comment by alex-w** [comment]
Are you really use series 0.12 on the modern PC?

**Comment by xMeshman** [comment]
On Sun, 10 Feb 2019 19:24:25 -0800
Alexander Wolf <notifications@github.com> wrote:

> Are you really use series 0.12 on the modern PC?
> 

Works just fine.

I don't use these types of apps frequently nor extensively, and 0.12 suit my needs fine.
When it comes to type Trilinos, Elmersolver apps, O.K. the latest.

Not much to it with newer versions, my copy was a some two year old testbuild I did
and the almost forgot until my present test of gcc architecture aligned rebuilds
on my building desktop containing ca. 437000 objects in its /usr dir,
and some six billion lines of c/c++/fortran code and just under 50,000 make files on it's dev disk.   

There is people out there with not so modern computers, and it's quite interesting that
the coding I saw went undetected/unpatched for so long, the frame rate increased up to threefold
in the new build.

Old and new ? we are all about 240000 year old bio devices and we're still up and running.
And as I percept it, c/c++/fortran e.t.c sourcecode are eternal, compilers are under revolution.

Rewriting src due to "not so smart" compiler setups,  

With my best!

@xMeshman followed by top500computers on Twitter.
There you can find modern computers.

**Comment by alex-w** [comment]
Thanks for patch!

I've committed it into 0.12 branch - https://bazaar.launchpad.net/~stellarium/stellarium/0.12/revision/5836 and prepared binary packages for Ubuntu Linux - code.launchpad.net/~alexwolf/+archive/ubuntu/stellarium-lts
