### ISSUE TITLE
Trouble with Stellarium

### ISSUE THREAD

**Issue by Classic-steam** [Stellarium/stellarium#629]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by Classic-steam** [comment]
Just loaded Stellarium version 0.11.2.  Located my position in Sydney Australia.  It is about 4:30pm and Stellarium shows sun high in the sky about North-east.  I look out the window and the sun almost due West and about 20 degrees from horizon.  This massive error will put all the other planets out.  How can I correct this.  I am running Windows 7 and I think the graphics card is Nvida

**Comment by alex-w** [comment]
Please check the time zone settings on PC and location in Stellarium.

**Comment by gzotti** [comment]
Version 0.11.2? Please delete this version unless you are interested in software archaeology. Try the current version. If you run Windows on an NVidia card, you more than likely can run it. With current drivers from NVidia of course.

**Comment by Classic-steam** [comment]
Thanks very much.  This was the disc that come with my telescope.  I will try to get the latest version
________________________________
