### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by GSmith1958** [Stellarium/stellarium#63]
I am trying to view the total lunar eclipse in Jerusalem on April 14th in 2033. Shortly after the moon rises, right about at the time the eclipse should begin, the program crashes. I have attempted to run it 5 times and it crashes at the same point every time. This is actually the main reason I downloaded the software so I'm hoping it can be fixed. I am running Windows 10. I tried downloading both the 32 bit and 64 bit versions and the same thing happened with both versions.

Thanks.

**Comment by zvant** [comment]
Same problem here. I am using version 0.17.0 on Windows 10. My location is 31.8639N 117.281E. Tried to use Stellarium to view the lunar eclipse in Jan. 31 2018 and it crashed. I tested the same procedure on version 0.14.3 on ubuntu 14.04 and it worked well.

**Comment by alex-w** [comment]
Stupid bug - when bzr was converting into git we lost texture for Earth shadow.

**Comment by astronomersiva** [comment]
Facing this issue on macOS as well.

**Comment by alex-w** [comment]
@astronomersiva please check the latest beta
