### ISSUE TITLE
DSO positions is error

### ISSUE THREAD

**Issue by sunshuwei** [Stellarium/stellarium#64]
For example.
![image](https://user-images.githubusercontent.com/34102610/34467007-a6e0ee9a-ef20-11e7-82db-bd65a4726adf.jpg)

The magnitude of some DSO is wrong, such as M88, M91。

**Comment by alex-w** [comment]
Sources?

**Comment by sunshuwei** [comment]
![qq 20180120153202](https://user-images.githubusercontent.com/34102610/35181142-72bcb9e2-fdf7-11e7-9ef0-efa25e45656d.png)

**Comment by adrian173486120** [comment]
@cardinot hello i can implement atmosphere on github
