### ISSUE TITLE
The Scripts GUI rendering issue

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#641]
### Expected Behaviour
Listing the list of scripts without artifacts

### Actual Behaviour
![scripts-gui](https://user-images.githubusercontent.com/88731/53619168-f9424280-3c20-11e9-80f5-7a8944816145.png)

[Original report](https://twitter.com/alchymylab/status/1080335045150224384) by Colin Gaudion: Hi, have built stellarium  today with Qt 5.11.2 and new Qt 5.12.0.  With the 5.12.0 version some screen display issues appear to have crept in as per attached.

The issue can be reproduced on macOS with Qt 5.12.1 too.

**Comment by gzotti** [comment]
Bad. Mac Qt bug? Cannot confirm on Win10/Qt5.12.0.

**Comment by alex-w** [comment]
Yes, @guillaumechereau can confirm this bug on mac and I cannot reproduce it on linux.

**Comment by alex-w** [comment]
I hope revision b5d9d1f96fb64d3c4aaf11a1d684e5be093e1293 improve behaviour the list on macs
