### ISSUE TITLE
Add support for original NexStar 5/8

### ISSUE THREAD

**Issue by kall2sollies** [Stellarium/stellarium#648]
**Problem description**
Original NexStar 5/8 do not work with the Celestron NexStar provider included in Stellarium.
According to what is said about HC compatibility at [NexStar Website](https://www.nexstarsite.com), the original NexStar 5/8 have a different protocol than newer ones.

**Feature request**
Implement a "Original NexStar 5/8" provider different than the existing generic NexStar.

**Helping resources**
The protocol of these models is described in the user manual. I successfully tested it in a terminal, and it works.

[NexStar Observer List](https://www.nexstarsite.com/NSOL.htm) supports it too, and is working with this model. Unfortunately, the program's sources are not available.

I can provide the protocol details if required.

I read the source of the generic NexStar provider, and I think the protocols are similar, and may only differ on ASCII chars used to prefix the commands.
If confirmed, it may be a good idea to override the base telescope provider in an abstract NexStar provider, then implement the generic and original NexStar by overriding the abstract NexStar.

**Comment by alex-w** [comment]
Please attach the User Guide.

**Comment by kall2sollies** [comment]
Here is the relevant page of the manual.
![NexStar_5_original_RS232](https://user-images.githubusercontent.com/2419545/54191676-b1d87380-44b6-11e9-9147-e88e54a878b6.JPG)

**Comment by alex-w** [comment]
At the moment one volunteer works on incorporate ASCOM support into Stellarium - is it will be solution for you or do you want to see separate driver for NexStar support (as LX200 and standard NexStar drivers)?

**Comment by kall2sollies** [comment]
I think it would be more clear and give better user experience in Stellarium to see a specific entry for a specific protocol.

**Comment by gzotti** [comment]
Then somebody with a physical NexStar 5/8 should develop, test and send this patch.

**Comment by alex-w** [comment]
> Then somebody with a physical NexStar 5/8 should develop, test and send this patch.

In attached info about NexStar 5/8 protocol is not very difficult and we can implement it, but without guarantee for works due no hardware for testing.

**Comment by kall2sollies** [comment]
I can test this, since I own an original NextStar 5.
I am a developer, but not a C++ one, so I prefer not be in charge of developing the whole thing.
But if someone could provide me with a branch with the code canvas scaffolded, I may try to adapt it and test it.

**Comment by alex-w** [comment]
Please try build https://github.com/Stellarium/stellarium/tree/nextstar5 branch and test it - maybe it will be work...

**Comment by kall2sollies** [comment]
I cloned the repo and checked out the appropriate branch. Do I have to build stellarium completely ? Or can I just build the nexstar5 plugin and deploy it within my regular stellarium installation ?

**Comment by gzotti** [comment]
Currently you must build all. It takes about 5-10 minutes on a modern PC, or an hour on the oldest netbook available, separating that out takes much longer. When you find out how to build plugins dynamically on Windows, you would do us a great favour!

**Comment by alex-w** [comment]
Yes, you should build Stellarium completely because TCP is static plugin

**Comment by alex-w** [comment]
Any news?

**Comment by kall2sollies** [comment]
Not yet sorry, needed to order a new USB/Serial cable in order to be ready to test. Will try to build and let you know as soon as I can.

**Comment by alex-w** [comment]
Any news

**Comment by kall2sollies** [comment]
Not yet sorry, but I will build and try

Le ven. 10 janv. 2020 à 19:06, Alexander Wolf <notifications@github.com> a
écrit :

**Comment by aros71** [comment]
I have an original NexStar5 and the required USB to Serial and connection cable etc. Plus I am very invested in having this work also. Though I am an astronomer not a developer. So not entirely sure how to go about building the code at the link above to test.

**Comment by gzotti** [comment]
I wonder again if there is ASCOM support for this.

**Comment by alex-w** [comment]
> I wonder again if there is ASCOM support for this.

No exactly, because OP was want to get extended Stellarium's driver for Celestron mounts.

@aros71 could you create a development environment and successful build Stellarium from source code by instructions: https://github.com/Stellarium/stellarium/blob/master/BUILDING.md at the startup point?

**Comment by gzotti** [comment]
I have also read that OP wants native support. However, if it is possible to use an existing ASCOM support, what's the point?

**Comment by alex-w** [comment]
> I have also read that OP wants native support. However, if it is possible to use an existing ASCOM support, what's the point?

The request was created after release version 0.19.1 - no ASCOM yet ;)

**Comment by gzotti** [comment]
That's not the point. If the problem of "Driving an Original NexStar" can be solved by using existing drivers in ASCOM/INDI, now, in 2020, why would we need an extra mode in addition? Less code - less maintenance. 

The question is now: Is there ASCOM/INDI support for the original NexStar?

**Comment by kall2sollies** [comment]
OP back in the thread! Well actually I don't know what ASCOM is, and how supporting it would solve the request. But I agree to the fact that less code means less maintenance. Could anyone provide me with a link to understand what ASCOM would imply?

**Comment by gzotti** [comment]
From https://ascom-standards.org/

>  ASCOM is a many-to-many and language-independent architecture, supported by most astronomy devices which connect to Windows and now Linux and MacOS computers.

**Comment by kall2sollies** [comment]
Ok I have to try if my original NexStar 5 is supported (the support list does not provide enough details on supported NexStar iterations).

**Comment by gzotti** [comment]
@kall2sollies Any news here?

**Comment by aros71** [comment]
I'm unable to test because my old NexStar5 mount has died.

*Adam Rosner*
***@***.*** | http://www.rosner.net.nz
+64 (0)22 610 6496

**Comment by theraaen** [comment]
I am a (semi) retired C++ Qt programmer with a NexStar8 GPS and may be interested in taking this on.  The link to the nexstar5 branch appears to be dead.  I will try to get the latest and build it.  
BTW, what version of Qt are you using.  I am currently setup to build Qt  5.15 on PopOS 20.02, Windows 10 and Mac

**Comment by gzotti** [comment]
Please read BUILDING.md in the repository. We have been based on Qt5 for years and are in transition to Qt6, or actually, compatibility with both. The difference is fortunately not that great for us. However, it should run with 5.9 and later. (Again, still usually just a minor effort.)

**Comment by theraaen** [comment]
I was able to build in QtCreator with 5.15.2  (had to ln -s 5.15.2 5.15), with a ton of warnings. Can you point to where the appropriate code for telescope control and perhaps resurrect the nexstar5 branch for me to use as a starting point?  Is there an API for telescope control? 

I have to build a cable before I can try any testing, and probably some sort of serial sniffer.  The display on my hand controller is flaky but I think the rest of it works.

What I would really like to end up with is a WiFi interface, perhaps using a ESP 32 as a WiFi to serial bridge....

**Comment by gzotti** [comment]
The code for the Telescope Control plugin is in plugins/TelescopeControl.

**Comment by theraaen** [comment]
I have yet to drink the CMake kool-aid, and I'm not much with doxygen.  How do I build the doc?

**Comment by gzotti** [comment]
Open https://stellarium.org/ and click "Developers documentation" in the "Collaborate" section.

**Comment by gzotti** [comment]
I would fully rely on INDI/ASCOM/Alpaca support and close this.

**Comment by theraaen** [comment]
OK by me.  I haven't found time to take this on and bought a new mount for my tube.
