### ISSUE TITLE
0.18.3 crashing after ~30 seconds Windows 7 64bit

### ISSUE THREAD

**Issue by aatdalton** [Stellarium/stellarium#649]
--> 

### Expected Behaviour
Looking around with arrow keys or oculars, shifting time, using a custom landscape. Really just using the software in a "normal" manner. 

### Actual Behaviour
Consistently crashes after about ~30 seconds. Windows pops up with message saying "Stellarium... has stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available. This same issue existed in 18.2 but I did not explore it much. Seems to happen with my custom "hardenburg" scenery or with default "geureines" active. The first log is a crash using it normally, jumping around in time, loaded with my scenery, using oculars before crashing. The log (2) was without changing time or using oculars. I also included my custom scenery if that helps or is a cause. 

### Steps to reproduce
Open stellarium, look around for ~30 seconds to 1 min, will always crash with same message. 

### System
* Stellarium version: stellarium-0.18.3-win64
* Operating system: Windows 7 Professional SP1, 64 bit
* Graphics Card: NVidea, GeForce GT 640M LE, 21.21.13.7654 Latest driver (updated today via windows, no change in crash

### Logfile 
Attached as well as config and scenery. 
[log.txt](https://github.com/Stellarium/stellarium/files/2943249/log.txt)
[log (2).txt](https://github.com/Stellarium/stellarium/files/2943250/log.2.txt)
[config.txt](https://github.com/Stellarium/stellarium/files/2943251/config.txt)
[hardenburg.zip](https://github.com/Stellarium/stellarium/files/2943252/hardenburg.zip)

Thanks for any help! I love the software and would enjoy being able to use it normally.

**Comment by alex-w** [comment]
I don't see serious problem in the logs. Could you added Stellarium into list of high performance applications in NVidia settings and check it again?

**Comment by aatdalton** [comment]
I'll try to give that a go in the morning and report back. Anything else I can try in my troubleshooting?

**Comment by gzotti** [comment]
I also cannot see anything suspicious. Nice landscape! For a better match to measured horizon altitudes, you might try calibrated=true. See the User Guide, section 7.1.4, why this is important.  But it is not a solution to your crashes. 

Do you use other graphics-heavy applications, and can you rule out simple overheating? And did you also update Intel graphics drivers recently? Maybe you need to visit intel.com, not just use the Windows software updates, to download latest drivers. (The Core-i-3xxx series was the first that should run without problems.)

**Comment by aatdalton** [comment]
I think it's fixed! The only thing I changed was adding the program to the NVidia high performance list and I just ran it twice for about 5-10 minutes without any crashes. It wasn't in the auto-populated list and I had to add it. Would that mean the drivers weren't detecting it as something that needed to run on the discreet card? 

Thanks for the help! I'm glad this worked out so easily. 

I'll read up on the horizon item. Sounds interesting. Would the scenery be something worth submitting to the stellarium page to share?

**Comment by gzotti** [comment]
Probably Intel drivers would work in ANGLE mode. Or need an update. I don't know how to flag the system to use the Geforce in case more than one GPU is available. You can enable Geforce by default or per-application in the Geforce driver settings.

If the landscape is calibrated reasonably accurately (horizon without curve and in right altitude, use calibrated flag to get the display right) I think it could be welcome. Maybe also find a better color for the bottom texture. You could also label the mountains (see gazetteer function, User Guide section 7.1.7).

**Comment by alex-w** [comment]
I've added code, who indicate to hybrid graphics systems on Windows to prefer the discrete part by default.
