### ISSUE TITLE
Bottom and left toolbars don't show up when hovering at the border

### ISSUE THREAD

**Issue by kekkyojin** [Stellarium/stellarium#660]
### Expected Behaviour
Toolbars should appear after the mouse pointer has been on the border for a few seconds. Then a tooltip should be shwon when hovering over the buttons.

### Actual Behaviour
Toolbars only appear when clicking at the border of the screen. When they do, there are no tooltips shown for the buttons on the toolbars.

If the mouse is in the bottom border, then the Dock is appearing.

### Steps to reproduce
Move the mouse pointer to the bottom border or left border of the screen and wait a few seconds.
### System
* Stellarium version: 0.19.0
* Operating system: macOS 10.14.4
* Graphics Card: Intel HD4000 integrated GPU (Mac mini Late 2012)

**Comment by gzotti** [comment]
Do you run Stellarium in windowed or fullscreen mode?

**Comment by kekkyojin** [comment]
In full-screen mode. When switching to windowed, the toolbars are working as expected. It looks fixed after switching again to full-screen. But next time the application is started it is misbehaving again.

**Comment by gzotti** [comment]
When you click once into the Stellarium window (Fullscreen) after start, does the menu work?

**Comment by gzotti** [comment]
@kekkyojin did you find time to test this procedure?

**Comment by kekkyojin** [comment]
Of course I tried it, @gzotti, as the problem could be caused by any kind of focus stealing. But it didn't work.

Also, it seems the problem happens some times and other ones don't.

**Comment by kekkyojin** [comment]
> You mean the menu did not appear even after you put the focus onto Stellarium's fullscreen window by clicking into it? Does any other interaction work then? Selecting an object?

Stellarium has the focus, as using keyboard cursors and using the mouse to drag the screen works as expected. Selecting an object works as expected, also: it iks hightlighted in red and its information appears on the upper-left secftion of the screen.

> What happens if you press F11 twice, to leave and enter fullscreen mode? (Who receives the F11 signal?)

https://github.com/Stellarium/stellarium/issues/660#issuecomment-478353260

**Comment by kekkyojin** [comment]
[log.txt](https://github.com/Stellarium/stellarium/files/3331023/log.txt)

I am attaching latest log file from latest testing session. Maybe it could help. Sorry for not doing it when creating the issue on GitHub.

**Comment by gzotti** [comment]
I see no problem. 
You could lock the slideout menus with the little arrows in the corner, then store your settings. The menu should at least be visible at next fullscreen start. Not sure if you can live with permanently visible menus?

**Comment by kekkyojin** [comment]
Likely the problem is on my hardware, as I am having lots of issues lately.

**Comment by unpacklo** [comment]
I see this issue today with Stellarium 0.21.3 on macOS 12.3.1. My repro is as simple as opening Stellarium directly into fullscreen mode.

Once the process finishes loading and gets you into fullscreen, no amount of hovering over the bottom left corner will reveal those menus. Clicking in the window and hovering also does nothing. However, clicking right at the edge of those areas will cause the menu to be revealed. After startup, you can fix the problem by command + tabbing to another process and then going back to Stellarium. Once you do this, hovering over the bottom left corner reveals the menus as I expect.

Is there any other info I should provide? I can also debug this issue assuming I can figure out how to build the code locally on my machine and get some guidance on which functions I should be inspecting that would be related to this issue.

**Comment by unpacklo** [comment]
I also just noticed there was a 0.22.0 release so I checked that and this bug still exists for me.

**Comment by alex-w** [comment]
I guess the issue related to set the focus after startup in the fullscreen mode. I need to check it.

**Comment by alex-w** [comment]
Hmm... I can reproduce the issue in version 0.22.1, but not in version 0.19.3

**Comment by alex-w** [comment]
Hmm... this is weird, but versions 0.22.0 (arm64 & x86_64) are OK

**Comment by alex-w** [comment]
@kekkyojin @unpacklo could you share your `config.ini` file?

**Comment by unpacklo** [comment]
config.ini as a text file: [config.ini.txt](https://github.com/Stellarium/stellarium/files/8953283/config.ini.txt)

And some more info about my machine:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/3121968/174911293-45ea9b52-ef4e-481b-9656-77239e1ea370.png">
<img width="678" alt="image" src="https://user-images.githubusercontent.com/3121968/174911388-7b45e50f-9848-4e2e-b194-7cbe1b24fedd.png">

**Comment by unpacklo** [comment]
I managed to get the source and build and noticed the behavior is slightly different. I recorded a video to illustrate https://www.youtube.com/watch?v=bMQD0B0Dz1A

I'm not that familiar with the code, if I wanted to investigate this, what are some promising areas to check?

**Comment by gzotti** [comment]
It looks as if the Mac dock (re-)grabs the focus or avoids hiding in the background, so that Stellarium does not receive the hover events. Only after you have moused-over the dock and have left the dock screen area, Stellarium receives the focus. Not sure if we can simply send some "force-put window in front" at program start, so that the dock is not even visible.

**Comment by alex-w** [comment]
@unpacklo please check the master

**Comment by unpacklo** [comment]
@alex-w Unfortunately, this doesn't appear to solve the toolbar issue.

The dock behavior is a bit different now but I'm not sure if it's related to your code changes because when I went back to commit 45dac7d47e86aa1fcad0771559085c1ec2999570, the behavior is different from the video I posted earlier (dock hides correctly now, even without your code changes).

**Comment by alex-w** [comment]
Bad news :-/

**Comment by alex-w** [comment]
@unpacklo could you please check our latest weekly snapshot (qt6 based version)?

**Comment by unpacklo** [comment]
@alex-w It looks like the weekly with Qt6 fixes the issue for me!
