### ISSUE TITLE
DST setting ignored, results in a time offset of -1 hour

### ISSUE THREAD

**Issue by pizdjuk** [Stellarium/stellarium#662]
### Expected Behaviour
correct time showing

### Actual Behaviour
stellarium is using system time, but ignores DST offset

### Steps to reproduce
set timezone to (in my case germany) and run stellarium
Actual time is for example
12:48:21 CEST

stellarium shows
11:48:21 UTC +01
### System
* Stellarium version: 0.19.0
from launchpad repo
stellarium_0.19.0-1ubuntu1~ppa6~ubuntu16.04.1_amd64.deb

* Operating system: Linux Mint 18.3

**Comment by alex-w** [comment]
Please show screenshot when Location dialog is open

**Comment by pizdjuk** [comment]
omg, just now I noticed my fail.... sorry about that. I didnt see that I've schecked custom time zone....
