### ISSUE TITLE
Stellarium does not run anymore after Mesa update on Linux Mint 19.1

### ISSUE THREAD

**Issue by DHSch** [Stellarium/stellarium#663]
I have a Laptop CPU Intel Core i3 M370 from 2010 with built-in Intel HD graphics (Arrandale/Ironlake)
Running on Linux Mint 19.1, 64-bit, Cinnamon 4.0.9, it usually detects GLSL Version Number 1.2, so it complains "this is not enough" and quits with a segmentation fault.
I get around this by calling Stellarium like this:
   MESA_GLSL_VERSION_OVERRIDE=1.30 stellarium
and it worked perfectly! (as far as I can tell)

But after Linux Mint update manager updated the Mesa package from version 18.0.5 to version 18.2.8, the override no longer works. Now it quits with the segmentation fault again.

How can I fix this?
I don't want to compile an old version of Stellarium. That seems really complicated.

**Comment by gzotti** [comment]
If after a Mesa update the override of Mesa via environment variable hacks does not work any longer, I am tempted to call this a Mesa problem.

**Comment by 10110111** [comment]
> But after Linux Mint update manager updated the Mesa package from version 18.0.5 to version 18.2.8

I doubt that update of Mesa from 18.0 to 18.2 was a regular upgrade — it must have been something like a distro upgrade. If it's so, then Stellarium was most likely upgraded too. Then it may appear that it's not Mesa problem, but rather the increased requirements of Stellarium. In this case, since you don't want to build, I can suggest trying to install an older version from the repository of an older Linux Mint release (this will also require `stellarium-data` package and maybe some others).

Not sure where to find the packages for Linux Mint though. For Ubuntu they can be found at https://packages.ubuntu.com ; these might also work on Mint, since it's Ubuntu-based.

**Comment by DHSch** [comment]
Thank you for your suggestion.

It really was not a distro upgrade. Here is what I did: I installed a whole bunch of updates that were available, after which I found the mentioned problem. Then I reversed it all using Timeshift (rsync), and re-installed them all again, excluding only the Mesa update. The problem disappeared. Then to be 100% sure, I finally added the Mesa update: The problem re-appeared. So it is definitely linked to the Mesa package only. Stellarium was not updated in this process, and it still worked prior to the Mesa update.

Yes, I could find an old version of Stellarium, although I don't know whether that introduces new problems when it was not intended for my distro version.
Or I can solve my problem by never updating Mesa again, which might be safer.

I was just hoping for a simpler way, like a switch in Stellarium that makes it ignore the version mismatch, or something I can configure in Mesa to make the version override work again. 
But there may not be another solution.

**Comment by alex-w** [comment]
Please try set main/check_requirements = false in ~/.stellarium/config.ini file.

**Comment by DHSch** [comment]
YES! It works again! Thank you, that's exactly what I was looking for!

**Comment by gzotti** [comment]
The version check is there to warn against outdated drivers or missing hardware support, but should allow to ignore the one-time warning and continue. Segfault should not happen. However, I don't have such borderline hardware to test anything.

**Comment by gzotti** [comment]
I assume we can close this. Solution works for OP, and nobody sent suggestions.
