### ISSUE TITLE
IC 434 / Horsehead Nebula

### ISSUE THREAD

**Issue by vviss** [Stellarium/stellarium#664]
Hello,

I'm using Stellarium Mobile v1.29.

The app identifies the Horsehead nebula as IC 434, while the latter is another red emission nebula on top of which stands the Horsehead.
While this does not greatly affect users trying to locate these objects, it would be better if the app recognizes IC 434 and the Horsehead as two different nebulae.

**Comment by gzotti** [comment]
This site hosts the desktop version, where those nebulae are clearly separated. Please report issues with Stellarium Mobile to Noctua. https://noctua-software.com/stellarium-mobile
