### ISSUE TITLE
telescope focal lenght

### ISSUE THREAD

**Issue by adrianghes** [Stellarium/stellarium#665]
In the configuration windows "telescope" is impossible set to over 999.00 mm of focal lenght

**Comment by gzotti** [comment]
Cannot confirm. Version, platform, how to reproduce? Please use the report template to report possible problems. Also try whether mouse wheel works for you.

**Comment by adrianghes** [comment]
I’m using the last version of stellarium ( 0.19.0 , but with the previously version the problem was the same ) on MACbook pro ( OS X 10.11.6 (15G22010) ) and I normally use external mouse that running perfectly. I can set every number of focal lenght from 1.00 to 999.90 but over this number the dot disappear ( also using the up/down cursor ) and the number becomes 100000.

**Comment by alex-w** [comment]
Cannot confirm on Mac OS X. Could you rename oculars.ini file and check it again?

**Comment by alex-w** [comment]
Any news?

**Comment by NazarObservatory** [comment]
Hello! I've got that problem... focal length limited 999.90
Solution???

**Comment by alex-w** [comment]
@NazarObservatory where is technical data?

**Comment by alex-w** [comment]
@NazarObservatory @adrianghes please check 0.19.2RC1

**Comment by alex-w** [comment]
timeout

**Comment by alex-w** [comment]
Problem in regional settings for decimal delimiter: https://sourceforge.net/p/stellarium/discussion/278769/thread/41d593e668/?limit=25#1ee8
