### ISSUE TITLE
Preserve settings between installs

### ISSUE THREAD

**Issue by pschroeter** [Stellarium/stellarium#666]
I must be missing something basic and simple, but whenever I upgrade Stellarium I loose my settings and views. When I installed 19.0 I made a copy of the AppData/Roaming/Stellarium folder and restoring it restored my setup.

**Comment by alex-w** [comment]
Please run installer and read the checkbox items at 4rd step.

**Comment by pschroeter** [comment]
Thank you. Let me just say then it's really odd that the box to remove the config files comes checked by default when I run the installer. I usually assume that what an installer wants to do by default is the best option. 
I also searched for a forum to ask more general questions about Stellarium without luck.

**Comment by alex-w** [comment]
It's not odd, because config.ini may be incompatible between versions (for example upgrading from version 0.12.10 to version 0.19.0 will be cause some problem with specific config options).
