### ISSUE TITLE
stellarium synchronization with the mount

### ISSUE THREAD

**Issue by AndreaMatthey** [Stellarium/stellarium#667]
When I use Stellarium with my EQ6 Mount for Telescope Control, often Telescope is not perfectly aligned with what stellarium show in the map.
 For example: if I watch in my CCD image live view Sirio Star, in Stellarium I have some different small position, it show in the center of my field of view rectangle, not Sirio but other. This error is few, sometime 20' +/- 5'.

I would like use one method for synchronize mounth and stellarium

Maybe this function already run… but I never have found it.

**Comment by gzotti** [comment]
1) Stellarium assumes your mount has been aligned correctly. 
2) In the settings, you can select whether positions are given with equinox J2000 or equinox of date. Try to switch to the other setting.

**Comment by alex-w** [comment]
@AndreaMatthey please check latest beta

**Comment by AndreaMatthey** [comment]
Hi Alex,
small question.

How I can copy in the clipboard the
coordinates of one selected object?

It is possible?

Thanks

Andrea,
ITALY

Il 16.11.2019 11:33 Alexander Wolf ha scritto: 

> @AndreaMatthey
[1] please check latest beta 
> 
> --
> You are receiving this because
you were mentioned.
> Reply to this email directly, view it on GitHub
[2], or unsubscribe [3].

--

Andrea Mattei   


Con Tiscali Mobile Smart 30 hai minuti illimitati, 30 Giga e 100 SMS a soli 7,99€ al mese. L'attivazione è gratis e disdici quando vuoi. http://tisca.li/smart30

**Comment by alex-w** [comment]
It’s possible, see details in Help window (F1)

**Comment by axd1967** [comment]
I think this user wanted to be able to perform some kind of sync between the Stellarium coordinate system and the telescope, a but similar to the Sync function in TheSkyX.

The idea is to manually centre the telescope to a known star, find the same star in Stellarium and indicate that the telescope is indeed centred on that star. Stellarium then records this offset and applies this as a simple offset (I think) to all successive slew commands to the telescope.
