### ISSUE TITLE
Stellarium 0.19.0 freezes on startup Windows 10 (1809)

### ISSUE THREAD

**Issue by mkkroeger** [Stellarium/stellarium#668]
I have an HP Spectre x360 (2018) 15.6 inch display with 4K screen resolution. I have Windows 10 (1809) with up-to-date patches and drivers. Stellarium 0.18.3 runs fine on my laptop. I downloaded and installed 0.19.0 (win64). When I launched Stellarium, I saw the splash screen OK. Then, only a part of the window appeared in the upper left corner (maybe 1/4 X 1/8 of the screen). The display was essentially locked - the mouse moved but I could select nothing. I was able to terminate Stellarium via Ctrl-Alt-Delete and bringing up Task Manager to terminate Stellarium. I tried a variety of Compatibility settings and Intel and NVIDIA graphics drivers to no avail. Reinstalling 0.18.3 restored a working version. I have attached the log.txt file from the last time I ran 0.19.0.

[log.txt](https://github.com/Stellarium/stellarium/files/3071315/log.txt)

**Comment by alex-w** [comment]
Could you check our beta: https://github.com/Stellarium/stellarium-data/releases/tag/beta ?

**Comment by mkkroeger** [comment]
Before trying the beta, I reinstalled 0.19.0 and tried the angle mode - that appeared to work. Fullscreen, fonts OK, able to move around, zoom in/out on a planet. I relaunched Stellarium normally and got the tiny window again. This time the tiny window was the normal screen of Stellarium. What was odd, the mouse was working fullscreen. That is, I was able to move direction with my touchscreen, but to close the tiny window I had to move the mouse to where it would go if Stellarium were fullscreen. I relaunched Stellarium again in normal mode and got the what I had gotten othertimes - just a portion of a tiny window that required Task Manager to terminate the process. Do you still want me to try the beta?

**Comment by gzotti** [comment]
Seems it's time to switch to ANGLE for you. But I am not aware of changes in the graphics requirements since 0.18.3, quite odd.

**Comment by mkkroeger** [comment]
Easy enough to use Angle. How is this different?  I have 0.19.0 installed
on an older Asus desktop running Windows 8.1 and 1080p resolution with no
issues. Thanks.

**Comment by gzotti** [comment]
ANGLE translates OpenGL to DirectX. Some GPU/driver combinations require it, although I am surprised that a Geforce misbehaves like that. Usually it's pre-2010 hardware or other vendors. Maybe after your next GPU driver update it will work again...

**Comment by mkkroeger** [comment]
Thank you for the explanation. Then it is odd that 0.18.3 works fine but
0.19.0 requires the Angle option

**Comment by alex-w** [comment]
Please check the beta - we packed different versions of ANGLE library for release and beta

**Comment by mkkroeger** [comment]
I loaded the win64 of 0.19.0.16835. Windows Defender attempted to stop the
installation even though I am running AVG. That's the first time I've seen
that. I told it install anyway with no other issues, accepting the default
options.

I first launched the ANGLE version. I started OK and displayed OK. However,
when I zoomed in on Mars or the Moon, the zoom worked but the planets were
not displayed.

I next launched the regular version. Same behavior as before - displayed
only in upper left corner and I had to Ctrl Alt Del to bring up Task
Manager and kill the process.

I reinstalled 0.19.0 and life is OK again with the ANGLE version.

**Comment by gzotti** [comment]
On Defender alert: https://github.com/Stellarium/stellarium/wiki/FAQ#unsigned-installer-dangerous-to-download-malware

In your original message you mentioned 0.19.0. Was that strictly 0.19.0 or 0.19.0.1? In the latter (released a day after) the problem should be fixed by including ANGLE libraries from an earlier version of Qt. Not sure what is included in the betas now?

**Comment by mkkroeger** [comment]
Help About indicates 0.19.0. However, the setup file
is stellarium-0.19.0.1-win64.exe and its file properties indicate the
product version is 0.19.0.1.

Not sure what changed from 0.18.3 to 0.19.0 since 0.18.3 works fine on my
laptop regarding display whereas 0.19.0 requires the ANGLE option (which is
fine with me).

As I mentioned before I am up-to-date on Windows 10 patches and driver
updates as far as Microsoft and HP are concerned.

**Comment by alex-w** [comment]
Betas has "standard" version of ANGLE and it should be give different rendering for the sky in comparison with releases.

**Comment by gzotti** [comment]
I close this as OP has a working solution.
