### ISSUE TITLE
I can't open deep sky modes in Syrveys like DSS colored

### ISSUE THREAD

**Issue by train11215** [Stellarium/stellarium#671]
### Expected Behaviour
      When I select DSS colored in survey , the original background should have gone, and replaced by new  downloaded pictures. It's true when I using the version 0.18.0.
### Actual Behaviour
      Now I'm using the version 0.19.0.When I select DSS colored in survey,nothing happened.

### System
* Stellarium version: <Stellarium 0.19.0>
* Operating system: <Windows10 家庭中文版 (Falimy Chinese version???)>
* Graphics Card: <Intel(R) UHD Graphics 620  25.20.100.6472
[log.txt](https://github.com/Stellarium/stellarium/files/3102367/log.txt)
>

Thanks a lot!!!

**Comment by alex-w** [comment]
Cannot confirm the issue. Please describe what exactly you doing  (step-by-step).

**Comment by train11215** [comment]
Firstly,I download stellarium 0.19.0 from stellarium.org and installed it. Then I opened it. When I use the version 0.18.0 ,there is a progressing bar in the lower left corner of the screen, reminding me the progress of updating satellites' date. But now,there's no a progressing bar anymore(It's another question).Then,I opened the Sky and viewing options window (F4)(星空及显示 in Chinese), then I clicked the Surveys label (巡测 in Chinese). Finally, I selected the DSS colored option, when I use the version 0.18.0, the original background of the milky way will disappear, and a progressing bar appears in the lower left corner of the screen.But now, none of these two phenomena appear. May you help me solve this problem? Thanks.
![capture1](https://user-images.githubusercontent.com/49854897/56492773-6b4b4f80-651f-11e9-8275-49624520f2fc.JPG)
![capture2](https://user-images.githubusercontent.com/49854897/56492774-6b4b4f80-651f-11e9-949a-3b3699f65443.JPG)
![capture3](https://user-images.githubusercontent.com/49854897/56492775-6be3e600-651f-11e9-967d-e530646facb3.JPG)

**Comment by alex-w** [comment]
Please try select first "DSS colored" item in the list of surveys

**Comment by train11215** [comment]
Still useless.However those item in list of Solar System are responsive.
![capture4](https://user-images.githubusercontent.com/49854897/56493484-cc742280-6521-11e9-8b01-037d602a598b.JPG)
![capyure 5](https://user-images.githubusercontent.com/49854897/56493485-ce3de600-6521-11e9-81b6-d40533beaaa0.JPG)

**Comment by alex-w** [comment]
Oops... sorry, but you need to enable the visualisation of HiPS also - Ctrl+Alt+D or F2 -> Extras tab -> Toggle "Show HiPS button" to enable button for HiPS on bottom bar.

Details in Stellarium User Guide.

**Comment by train11215** [comment]
Cool ! Now I can open DSS2 Blue(XJ+S). But the option DSS colored still doesn't work. And what about the progressing bar? I gonna to read Stellarium User Guide carefully,haha.Thanks a lot!
![capture 6](https://user-images.githubusercontent.com/49854897/56496885-d9970e80-652d-11e9-871e-ad83e9999aac.JPG)

**Comment by alex-w** [comment]
It works for me (the first DSS colored item)

**Comment by train11215** [comment]
Wow , after a long time waiting , I can finally enjoy these wonderful image of DSS colors . Thanks a lot , Alex .
      Now I wonder why I haven't  loading bar ?

**Comment by alex-w** [comment]
I don't remember, but possible we do not add the progress bar for HiPS

**Comment by train11215** [comment]
Emmm, I remember there's a progress bar for HiPS when I use the edition 0.18.0.
Maybe now there should be a progress bar when I updating satellite data...Sorry , there isn't.
Thanks again.

**Comment by alex-w** [comment]
Hmm... Could you switch Stellarium in windowed mode and check the progress bar again?

**Comment by train11215** [comment]
Hi,alex. Today I tried to update satellite date in both Windowed mode and Full Screen mode. Sadly, none of them show a progress bar  in the lower left corner of the screen. Thanks for your help and patience.
The first picture is about Full Screen mode and the second one is about Windowed mode.
<img width="960" alt="Full screen" src="https://user-images.githubusercontent.com/49854897/56633918-a8841e80-6692-11e9-8161-8b6b9f01324b.png">
<img width="960" alt="Windowed mode" src="https://user-images.githubusercontent.com/49854897/56633919-a8841e80-6692-11e9-9abd-2b3182c2bd93.png">

**Comment by acmalko** [comment]
Hi ! Anything new ?
I have exactly the same problem since 2 weeks with 0.18.3 version. 
I've upgraded to 0.19 (and even tried the last beta version) but DSS color survey doesn't load. Some others do. 
Only 2 differences with this version: french language (yes I am) and the progress bar disappeared.
Made a fresh install too, erased all cache and parameters, same problem. 

Any idea ? Thanks
- W10- MSI Gtx970 graphic card with last drivers.

**Comment by gzotti** [comment]
The actual HiPS surveys are not hosted by stellarium.org but somewhere else in various institutes' websites, we are just using them. Probably the site is offline? Or data delivery blocked by some "region" firewall?
For a colored DSS, you can always enable the older DSS layer. See the Guide, section 4.3.3.
And (ceterum censeo) sometimes the logfile has hints of what's going wrong when something does not work as expected.

**Comment by alex-w** [comment]
Let me quote the official IOVA announce:

> Dear HiPS providers, contributors and users,
> 
> The CDS is presently processing a big update all his HiPS by adding the low HiPS orders (Norder0 to 2) - (see IVOA Apps last Interop meeting to have the rational of this action => [slide 12-13 of this presentation](https://wiki.ivoa.net/internal/IVOA/InterOpMay2018Apps/IVOA_Apps_HiPS_news.pdf)). During this operation, the properties file associated to each HiPS will be cleaned (removing obsoleted keys) and upgraded to be fully HiPS 1.0 compatible. Notice that the Allsky.fits, .png, .jpg will be kept for compatibility but could be deprecated in the future.
> 
> This release will start tomorrow for the fifty main used HiPS. This update should be transparent. But do not hesitate to contact us if you detect any problem by using your favorite HiPS client. If we do not receive complaints, we will continue with all other CDS HiPS 10 days later.
> 
> In a second step, in order to keep an homogeneous set of HiPS over the HiPS network :
> 
> We will encourage all HiPS creators to update their own HiPS if they do not already provide low orders (notably if you have generated your HiPS by an Aladin/Hipsgen <10.084 (1 year old) ). This operation can be realized by using a new version of Aladin/Hipsgen with UPDATE action (>10.123 - distributed soon). It is fast (a few seconds per HiPS) and do not require original images.
The HiPS nodes mirroring external HiPS will have to synchronize their copies to retrieve low orders and the updated properties file (for instance by Hipsgen MIRROR action)
Do not hesitate to contact us if more details are required.

Some surveys has problem and we work on the problem.

**Comment by acmalko** [comment]
Many thanks for your both answers

**Comment by alex-w** [comment]
OK, the fix in the master already and it will be available for testing in next beta

**Comment by train11215** [comment]
Cool! Thanks a lot!!!

**Comment by alex-w** [comment]
@train11215 please test version 0.19.0.16908

**Comment by train11215** [comment]
Thanks a lot ,Alex. Let me have a try.

**Comment by acmalko** [comment]
It works 
The 2nd DSS Color is OK :)

**Comment by axd1967** [comment]
Any relation with #1276 ?
