### ISSUE TITLE
when searching for a meteor shower I get an error

### ISSUE THREAD

**Issue by chuckboren3** [Stellarium/stellarium#673]
I get this error Message when I try to search for a Meteor shower for the month of May 2019:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	stellarium.exe
  Application Version:	0.19.0.0
  Application Timestamp:	5c97643d
  Fault Module Name:	ig7icd64.dll
  Fault Module Version:	10.18.10.3308
  Fault Module Timestamp:	52379f0c
  Exception Code:	c0000005
  Exception Offset:	000000000020ddc2
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	1033
  Additional Information 1:	5aae
  Additional Information 2:	5aae8978c38c263412e490f4aac25fec
  Additional Information 3:	dd6d
  Additional Information 4:	dd6d45babc5c7da1a3c2a4ccdecb2fe0

The Stellarium hangs for a moment then quits. What could be causing this to happen?

**Comment by gzotti** [comment]
Stellarium's own logfile could probably help better than this system log. 
https://github.com/Stellarium/stellarium/wiki/FAQ#reporting-a-crash

**Comment by alex-w** [comment]
Please check latest beta - https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by alex-w** [comment]
Any news?

**Comment by alex-w** [comment]
Please check release 0.19.1

**Comment by alex-w** [comment]
timeout
