### ISSUE TITLE
Stellarium 0.12 (revised version) compilation Error under Linux 

### ISSUE THREAD

**Issue by phototropist** [Stellarium/stellarium#674]
I followed the instructions on [http://www.stellarium.org/wiki/index.php/Compilation_on_Linux](url) to compile revised 0.12 version. Using the default configuration, I execute `make` from `{stellarium_sources_path}/builds/unix` and I get this error:

**at 37%, building StelCore.cpp.o:523:43, it says: ISO C++ forbids comparison between pointers and integer (-fpermissive)**

I'm using `make` version GNU 4.1 but I don't see any `-fpermissive` command line option explained on its help. How could I solve the problem?

**Comment by alex-w** [comment]
Are you tried compile source code from 0.12 branch?

**Comment by alex-w** [comment]
I've added fixes: https://github.com/Stellarium/stellarium/tree/0.12
