### ISSUE TITLE
Moon jumps away from its place when observer goes to latitude >89°53'59.99"

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#675]
To reproduce:

1. Go to N89°53'59.99", E0°, elevation 1 m
2. Set date/time to 2021-06-10 11:00:00
3. See the annular solar eclipse
4. Go down in latitude, see the Moon smoothly moving away from the Sun
5. Go back and over the initial latitude, and the Moon jumps away from the Sun, gaining 1.1853° in altitude and stays approximately there with further increase of latitude. The jump happens at latitude N89°54'0"
6. Going down again to initial latitude brings the Moon back onto the Sun.

This jump seen on step 5 seems unphysical.

**Comment by gzotti** [comment]
duplicate of #391.

**Comment by 10110111** [comment]
Indeed.
