### ISSUE TITLE
Possibility to add a landscape as polyline like geneva_horizon.txt in PC for mobile devices

### ISSUE THREAD

**Issue by kha-ce** [Stellarium/stellarium#676]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kha-ce** [comment]
Would you give the users the possibily to add their own horizon, points observed or calculated.
I have for example a text file, for each azimuth is a correspondant altitude in degree, I was surprised when I found it in PC by the folder Geneva landscape, but not found for mobile devices :(

**Comment by gzotti** [comment]
This site actually does not discuss the Mobile version. Please use its own feedback system.

**Comment by axd1967** [comment]
@kha-ce you probably want to discuss this on the site https://www.stellarium-labs.com/ (if I'm not mistaken)
