### ISSUE TITLE
Can't download extra stars catalog.

### ISSUE THREAD

**Issue by Rencer** [Stellarium/stellarium#679]
OS: Manjaro Linux
Steallarium version: 0.18.2

Today I installed Stellarium from the AUR repository, and then I tried to download the extra stars catalogs but nothing happened.
Here is the corresponding lines from the log:

> Downloading file "https://github.com/Stellarium/stellarium-data/releases/download/stars-2.0/stars_4_1v0_2.cat"
Found file  "/home/gofri/.stellarium/stars/default/stars_4_1v0_2.cat" , checking md5sum..
Error: File  "stars/default/stars_4_1v0_2.cat"  is corrupt, MD5 mismatch! Found  "d41d8cd98f00b204e9800998ecf8427e"  expected  "ac67dc390f9d414d61b1db76a5b820e9"

**Comment by alex-w** [comment]
This problem was fixed in newer versions
