### ISSUE TITLE
Surface occlusion even with landscape turned off

### ISSUE THREAD

**Issue by jasonincanada** [Stellarium/stellarium#680]
### Expected Behaviour
Should see Europa from Ganymede

### Actual Behaviour
There's a polygon (presumably Ganymede) in the way of seeing Europa, even with the landscape turned off

### Steps to reproduce

```
core.setDate("2019-05-13T18:00:00", "UTC");
SolarSystem.setFlagLabels(true);

// From Ganymede to Europa at 50 degrees latitude or lower, shows a blank polygon
core.setObserverLocation(0, 50, 100, 0, "", "Ganymede");
StelMovementMgr.setEquatorialMount(true);

core.selectObjectByName("Europa", false);
StelMovementMgr.setFlagTracking(true);
StelMovementMgr.zoomTo(40, 0);

// Hide landscape
LandscapeMgr.setFlagLandscape(false);
LandscapeMgr.setFlagAtmosphere(false);
LandscapeMgr.setFlagFog(false);
```

### System
* Stellarium version: Stellarium 0.19.0
* Operating system: Windows Home 7 Premium (SP1)
* Graphics Card: NVIDIA GeForce GTX 260 (9.18.13.4144)

**Comment by alex-w** [comment]
You are do not turned off the landscape.

Hint: LandscapeMgr.setFlagLandscape(false);

**Comment by alex-w** [comment]
Are you turned on rendering 3D models for Solar system objects?
