### ISSUE TITLE
Default HIPS survey forgotten if started without network

### ISSUE THREAD

**Issue by tammojan** [Stellarium/stellarium#681]
### Expected Behaviour
The selected HIPS survey is 'forgotten' if stellarium is started without internet access.

### Actual Behaviour
No survey shows. If I go to 'Surveys', when the computer is connected to internet again, no survey is selected.

### Steps to reproduce

- Open stellarium, choose one hips survey in the Surveys. Display this survey.
- Close stellarium
- Unplug the internet
- Start stellarium
- Stop stellarium
- Plug the internet back in
- Show survey (using hotkey or the button in the toolbar)

### System
* Stellarium version: 0.19.0
* Operating system: MacOs
* Graphics Card: N/A

**Comment by alex-w** [comment]
From you steps to reproduce:
- Open stellarium, choose one hips survey in the Surveys. Display this survey.
- Close stellarium
- Unplug the internet
- Start stellarium

At first step Stellarium is enables the display of survey and saving state of surveys in config.ini (url of survey and flag for displaying). On second and third steps Stellarium doing nothing for surveys. On the last step Stellarium trying the enable displaying the survey, but the URL of survey is not available and Stellarium removed it from config.ini. 

Why this is happens?

All surveys has own lifetime and Stellarium create a list of surveys every time, when tab Surveys is opened. If URL of some survey is not available then Stellarium think this survey is not exist anymore and it should be removed. This is correct behaviour.

Please try it:
- Open stellarium, choose one hips survey in the Surveys. Display this survey.
- Hide survey (using hotkey or the button in the toolbar)
- Close stellarium
- Unplug the internet
- Start stellarium
- Stop stellarium
- Plug the internet back in
- Show survey (using hotkey or the button in the toolbar)

**Comment by tammojan** [comment]
I can confirm that the survey is remembered if I follow your steps; not showing the survey does not trigger the code that 'forgets' / removes the default survey.

> If URL of some survey is not available then Stellarium think this survey is not exist anymore and it should be removed. This is correct behaviour.

Perhaps it would be useful to check if _any_ url is available before concluding that the survey does not exist anymore.

As background: I have stellarium running on a semi-public computer in the Dwingeloo telescope, where not all operators know the surveys menu. I've taught them to trigger the default survey on/off (the Dwingeloo survey of course), explaining to get to the surveys menu is too hard.

**Comment by alex-w** [comment]
> Perhaps it would be useful to check if any url is available before concluding that the survey does not exist anymore.

How we can check availability of survey without internet connectivity?

**Comment by tammojan** [comment]
> How we can check availability of survey without internet connectivity?

I meant something like this:
```
if (survey not available)
    if (internet available)
        remove survey from list
    else
        don't show survey, but don't remove from list
```

**Comment by tammojan** [comment]
Awesome, thanks!

**Comment by alex-w** [comment]
I've little changed the behaviour of HiPS: when Stellarium started without network then he will disable displaying the HiPS and do not touch any setting for HiPS.

Please check: https://github.com/Stellarium/stellarium-data/releases/download/beta/Stellarium-0.19.0.16864.dmg

**Comment by tammojan** [comment]
I'm afraid your commit breaks HiPS functionality. It seems that the following evaluates to `true`, even though there is internet functionality, and the release build works with HiPS:
```
StelApp::getInstance().getNetworkAccessManager()->networkAccessible()==QNetworkAccessManager::NotAccessible
```

I have checked that just the change in line [85 of loadSources](https://github.com/Stellarium/stellarium/commit/7d36b6c8077cee07a5006c37e28a6e039da33e55#diff-abbd5659e103f1493dca74a832d0b636R85) triggers breaking the HiPS functionality.

For completeness, I'm on a Mac 10.14.4, with Qt 5.12.3.

**Comment by alex-w** [comment]
I’ve tested it on Linux and it works as expected: no network - no HiPS.

**Comment by tammojan** [comment]
Just to make sure: have you also tested that on Linux with network, HiPS still works?

**Comment by alex-w** [comment]
Yes, of course.

**Comment by tammojan** [comment]
I can confirm that `StelApp::getInstance().getNetworkAccessManager()->networkAccessible()` yields `QNetworkAccessManager::NotAccessible`.

If I replace the `return` in [loadSources](https://github.com/Stellarium/stellarium/blob/master/src/core/modules/HipsMgr.cpp#L86) by
```
if (StelApp::getInstance().getNetworkAccessManager()->networkAccessible()==QNetworkAccessManager::NotAccessible)
    qDebug() << StelApp::getInstance().getNetworkAccessManager()->networkAccessible();
```
and leave the rest of the code as before your change, then the HiPS loads fine and the console prints `QNetworkAccessManager::NotAccessible`. I suspect that this is an issue with Qt on MacOS.

**Comment by tammojan** [comment]
Sorry for checking back late (didn't get a notification of a new commit). I can confirm the issue is now fixed.
