### ISSUE TITLE
Archaeolines

### ISSUE THREAD

**Issue by Keystone925** [Stellarium/stellarium#682]
The clickable options at the bottom of the Archaeoline Plugin window fall below the window frame. Is there a way to fix that or is there another way to start the Archaeolines plugin?

Thanks.

**Comment by alex-w** [comment]
Please attach the log file

Hint: https://github.com/Stellarium/stellarium/wiki/FAQ#Reporting_a_crash

**Comment by gzotti** [comment]
What is your screen resolution?
https://github.com/Stellarium/stellarium/wiki/FAQ#netbook-with-only-1024x600-screen
Maybe you can rotate your screen 90°?

**Comment by Keystone925** [comment]
At first I thought it might be the aspect ratio, but ratio was the same on
both of the laptops that I installed Stellarium 0.19.0 on. Both machines
use Windows 10 and have 1366 x 768 resolution with 8.00 GB RAM. Stellarium
works on my older ASUS laptop with Intel i7-3630QM CPU @2.40 GHz. The one
that is giving me problems is an HP with ADM Ryzen 3 2200U with Radeon Vega
Mobile Gfx 2.50 Ghz.

Windows Update said the best driver (ADM Radeon Vega 3 Graphics) is already
installed.

**Comment by Keystone925** [comment]
I was able to switch to Portrait Mode and save the Archaeolines plugin.
Thanks Georg!

**Comment by alex-w** [comment]
Please test Stellarium version 0.19.0.16893 or later.

**Comment by Keystone925** [comment]
Alexander,
I just reinstalled the program and had the same issue. However, I think the
problem may have been my settings. I have a 1366 x 768 screen which makes
the font is so small that it causes eye strain. When the scale is set to
125% it's easier for me to read. At 100% scale, the pop-up window fits the
screen without any problems ... well, the task bar covered the bottom menu
in Stellarium, but that was easily fixed by unlocking the task bar and
moving it to the right side of the screen.

D
