### ISSUE TITLE
bar of options doesn't show up

### ISSUE THREAD

**Issue by hakew** [Stellarium/stellarium#684]
So, I always used the software but lately I'm getting some troubles with it.
When I launch, the bar of options and settings doesn't show for me (like the photo)
![image](https://user-images.githubusercontent.com/50782070/57974959-3358f000-7997-11e9-8c4c-cc2011928a5d.png)

I really wanna know how can I resolve this issue.

PS: I tried all the versions available and still...

**Comment by alex-w** [comment]
Please attach the log from Stellarium and please check the issue in ANGLE mode.

**Comment by alex-w** [comment]
Possible duplicate #660

**Comment by hakew** [comment]
Hey, here's some of the infos from the log:

2019-05-26T20:09:30
Windows 10
Compiled using MSVC++ 12.0 (Visual Studio 2013)
Qt runtime version: 5.6.2
Qt compilation version: 5.6.2
Addressing mode: 32-bit
Total physical memory: 4061 MB
Available physical memory: 376 MB
Physical memory in use: 90%
Total virtual memory: 2047 MB
Available virtual memory: 1923 MB
Processor speed: 3000 MHz
Processor name: Pentium(R) Dual-Core  CPU      E5700  @ 3.00GHz
Processor speed: 3000 MHz
Processor name: Pentium(R) Dual-Core  CPU      E5700  @ 3.00GHz

And i'm sorry but what is Angle mode?

**Comment by gzotti** [comment]
The next 10 lines or so would have told us about the capabilities of your graphics subsystem.

ANGLE: https://github.com/Stellarium/stellarium/wiki/FAQ#angle-mode

**Comment by gzotti** [comment]
@hakew did this answer your question?

**Comment by hakew** [comment]
Sorry for the late reply. 

Yeah, it did help me. Here's a little more from the log:

OpenGL supported version:  "OpenGL ES 2.0 (ANGLE 2.1.99f075dade7c)"
Current Format:  QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior 0, swapInterval 1, profile  0)
StelMainView::init
Detected: OpenGL ES "2.0"
Driver version string: "OpenGL ES 2.0 (ANGLE 2.1.99f075dade7c)"
GL vendor is "Google Inc."
GL renderer is "ANGLE (Intel(R) G41 Express Chipset (Microsoft Corporation - WDDM 1.1) Direct3D11 vs_4_0 ps_4_0)"
GL Shading Language version is "OpenGL ES GLSL ES 1.00 (ANGLE 2.1.99f075dade7c)"
VS Version Number detected:  4
PS Version Number detected:  4
vs/ps version is fine, we should not see a graphics problem.
GLSL ES Version Number detected:  1
GLSL ES version is fine, we should not see a graphics problem.


I guess... This can help to solve the issue?

**Comment by gzotti** [comment]
This means you can run successfully Stellarium in ANGLE mode. Apparently the Intel G41 has problems providing proper OpenGL, support (or you must update its drivers for it to do so).

**Comment by hakew** [comment]
Alright! Thanks a lot!
