### ISSUE TITLE
Неверный часовой пояс Волгоградской области

### ISSUE THREAD

**Issue by Subsanek** [Stellarium/stellarium#686]
В городах Волгоградской области без ручного изменения, до сих пор (версия 0.19) выставляется часовой пояс UTC+3, хотя уже как несколько месяцев наша область перешла на часовой пояс UTC+4.
<img width="287" alt="bug" src="https://user-images.githubusercontent.com/1623621/58116398-b4102a00-7beb-11e9-8dd9-887b756fb929.png">

**Comment by alex-w** [comment]
Сейчас специально проверил часовой пояс Волгограда - всё отработало правильно.

![stellarium-000](https://user-images.githubusercontent.com/88731/58166941-b5555b80-7cac-11e9-8bd4-c780cdaf0d7b.png)

В связи с этим вопрос: а что говорит операционная система об этом часовом поясе (т.е. какое смещение от UTC в Windows)?

**Comment by Subsanek** [comment]
Настройки времени в Windows 10 следующие:
<img width="359" alt="Windows_time_settings" src="https://user-images.githubusercontent.com/1623621/58168873-d69f5300-7c7e-11e9-966c-bc34b88a2e80.png">

**Comment by alex-w** [comment]
Очень интересно. Попробуйте бета-версию - она тоже неправильно смещение для волгоградского часового пояса задаёт?

**Comment by alex-w** [comment]
Просьба проверить последнюю бета-версию

**Comment by Subsanek** [comment]
Попробовал бету stellarium-0.19.0.16873-win64.exe, в ней часовой пояс задаёт правильно (UTC+4).
<img width="410" alt="beta" src="https://user-images.githubusercontent.com/1623621/58451278-548daf00-8102-11e9-85a0-73a87922d233.png">
