### ISSUE TITLE
strange square in the map

### ISSUE THREAD

**Issue by yarikkovrov** [Stellarium/stellarium#69]
Hi, I found an error in displaying stars, etc. in the Stellarium. To find the error, enter NGC 6723 or NGC 6726 in the search. There is an incomprehensible square.Thank you for you work

**Comment by alex-w** [comment]
Just a texture for DSO

**Comment by gzotti** [comment]
The "incomprehensible square" is called a "photograph". It provides non-stellar objects, but also a number of star images not included in Stellarium's database.

**Comment by yarikkovrov** [comment]
Is there other squares in the sky of the Stellarium? and tell me please what it means "DSO"? Thx

**Comment by gzotti** [comment]
Canonical abbreviation for "Deep Sky Object". Yes, most DSO photographs have not been manually fine-tuned to blend perfectly with a dark background. This would take many hours per photograph. You can choose not to display DSO photographs. Please read the Guide for details and all other relevant information about Stellarium.
