### ISSUE TITLE
Declinations are all positive

### ISSUE THREAD

**Issue by astrostubbs** [Stellarium/stellarium#690]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by astrostubbs** [comment]
Hi. This seems a very nice and useful tool! I used it to compute lunar ephemeris with decimal degrees as output. The declinations in the S appear as wrapped positive numbers, for example as 365 deg rather than -5 deg. This is for v 0.19.0. 

![image](https://user-images.githubusercontent.com/7434450/58554331-aeff3c00-81e4-11e9-8e34-0543fd24ef4c.png)

**Comment by alex-w** [comment]
Thanks for report! Fix will be available for checking in next beta.

**Comment by astrostubbs** [comment]
No worries, and thanks for the quick fix!
Chris

Christopher Stubbs
Professor of Physics and of Astronomy
Dean of Sciences
