### ISSUE TITLE
Augmented reality

### ISSUE THREAD

**Issue by Ziggizag** [Stellarium/stellarium#692]
Hi,

I am using Stellarium Pro on an Android smartphone. The question is - is it possible to overlay virtual sky on a phone's live camera view rather than some stored "landscape" picture?

Simple augmented reality feature? Should not be so difficult, IMHO...

**Comment by gzotti** [comment]
This site does not discuss the mobile version, in principle. 

Should not be difficult, if you know how to do it. Patches welcome.

**Comment by TesseractPi** [comment]
The responder indicated this is not the forum site to discuss issues found with the mobile online version.  If anyone knows the site where we can post observed bugs eith the online mobile version, please reference it.
