### ISSUE TITLE
moon warped 

### ISSUE THREAD

**Issue by stephym88** [Stellarium/stellarium#693]
<img width="208" alt="Screen Shot 2019-06-07 at 11 59 32 AM" src="https://user-images.githubusercontent.com/51493081/59127859-761a4200-891d-11e9-8fe6-5c339a4cc8de.png">
Moon looks distorted.  Current Stellarium version installed.  Expect moon to be round or moon phase.  Stopped time and turned off atmosphere to no avail.  
<img width="208" alt="Screen Shot 2019-06-07 at 11 59 32 AM" src="https://user-images.githubusercontent.com/51493081/59127840-6dc20700-891d-11e9-91f2-90fb25273b70.png">

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/FAQ#reporting-a-crash

The questionnaire is here for a reason. 

Looks like you are using ortho projection? Delete config.ini and start over.

**Comment by stephym88** [comment]
Sorry Georg,  I only understand a little of that which is I have a Mac os10.13.6.  I am not a computer tech type person.  I’d like to just turn the moon off but it is a huge bright star when the moon texture is turned off.  
Using equal area projection.  I see the moon changes depending how close to the edge of the globe it is.  
Maybe you can suggest a different program that can provide an image like this without the moon ? I tried sky safari 6 but the stars come out too small to make a poster on my own which I’m trying to do.
Steph

**Comment by gzotti** [comment]
Press P to switch off the planets, or change time to move the Moon elsewhere. And consider using Stereographic projection. Using Ortho, fisheye or equal area (or in fact every other!) correctly distorts the moon when it is at the edge of the visible sphere or edge of usable view.

**Comment by stephym88** [comment]
GEORG! You are a life saver! That Stereographic view is what I was looking for! 
Thanks sooo much:)))
Steph

**Comment by stephym88** [comment]
Hi Georg,

Can I trouble you for some help again?
I’m trying to be able to change the background of the maps to any color.  I saw somewhere there might be a plugin for that?  I’d be willing to hire a tutor to help screen share and show me how to do that, code and all.  I want my maps to look as good as this one below. This is the Stellarium star configuration but they have changed the color to navy and I’ve seen other colors too.  I tried another program that does vector type pdf’s to export but then the lovely glow of the stars you guys have here is diminished.  Or if there is someone you know who likes this artsy stuff and is good at it I would love to talk to them if you know of anyone? Also, is there a way to make all the stars white?  I’ve searched everywhere and they remain yellow on some.

Stephanie

Their version-stars still have the glow 


My version- Stars are perfectly round with no glow. Also the Cartes Du Ciel program is missing some detail in the constellations.

**Comment by gzotti** [comment]
There is no way to remove color from the off-white stars. 
You can assign a screen back ground colour manually in the config.ini. Please see D.1.3 in the User Guide, entry sky_background_color. You can change this colour interactively in the Text User Unterface plugin, see section 12.6, and entry 5.26 in its command list. There is no such setting available from the main program, deliberately.

**Comment by stephym88** [comment]
Ok thanks so much.  I am talking to a coder type guy to figure out how to do this.  So I”m clear with him, I need to install the TUI plugin?  Where do I find this?  Sorry if this sounds stupid.
Steph

**Comment by gzotti** [comment]
Is the User Guide not in your native language? Activating plugins is described in the plugin intro section (11). And by the way, the User Guide has a table of contents. I don't know in which way we else could describe the program? Of course, writing a second and third vbersion, maybe coming to 800 pages. Who would be happy with such a monster?

**Comment by stephym88** [comment]
Yes it would be a monster guide, I understand your frustration.  I thought I did activate it, I just can’t find where that setting would be now.  I watched some tutorials on plugins for stellarium and an icon appears somewhere to use the new setting with the plugins I watched.  I can’t find where the sky background icon setting appears upon restart. 

Thank you for your patience,
Steph

**Comment by gzotti** [comment]
The TUI plugin is described in the Guide as written above. I don't know third-party tutorials. The TUI is silent without any new buttons or icons and works as described.
