### ISSUE TITLE
False alignment of solar eclipse corona

### ISSUE THREAD

**Issue by andrmoel** [Stellarium/stellarium#699]
### Expected Behaviour

The corona of a solar eclipse must be parallel to the sun's ecliptical plate.

### Actual Behaviour

The corona of a solar eclipse is rotated for about 90°. See the screenshot.
edit: I realized the corona is always aligned the same way from the observers view.

![sellarium-corona](https://user-images.githubusercontent.com/35029021/59877477-3d12b080-93a6-11e9-898d-b5b2dda70bdc.jpg)

"La Serena, Chile" 02nd July 2019

**Comment by gzotti** [comment]
Not so fast.

Here is one of the photos which I processed into the Corona. Delta Cnc is also visible. 

It may be that the corona image has never been rotated and is just shown in its alt-azimuthal orientation...

![20080801-130_TSE_180312](https://user-images.githubusercontent.com/18099873/59878616-0d18dc80-93a9-11e9-8b0e-55cd745674ee.JPG)
![stellarium-028](https://user-images.githubusercontent.com/18099873/59878701-3a658a80-93a9-11e9-840e-9c27b2cef3de.png)
