### ISSUE TITLE
Segfault when loading a comet file in Solar System Editor

### ISSUE THREAD

**Issue by francheu** [Stellarium/stellarium#700]
Using 0.19.0 under Linux Mint 19.
In the SSE / Import MPC orbital elements, comet type, file containing a list of objects: got a segmentation error when clicking on the file open button.

**Comment by francheu** [comment]
BTW, this bug does not occur when Stellarium is launched as root (sudo...).

**Comment by gzotti** [comment]
Do you own your ~/.stellarium folder and all files inside?

**Comment by francheu** [comment]
A few files were own by root, namely:
- /home/me/.stellarium/modules/Oculars/oculars.ini
- /home/me/.stellarium/stars/default/stars_4_1v0_2.cat
- /home/me/.stellarium/stars/default/stars_stars_5_2v0_1.cat

Same problem after setting permissions so that I own the

**Comment by gzotti** [comment]
I never used Mint. Is there a package, or did you compile&install yourself?

**Comment by francheu** [comment]
Mint is based on Ubuntu.
I have used the PPA to update Stellarium to v0.19.

**Comment by gzotti** [comment]
Stellarium 0.19.1 was released today. Please update and try again. Maybe delete or rename your ~/.stellarium folder before first launch for a "clean" test. And if problems persist, show your logfile. (~/.stellarium/log.txt)

**Comment by francheu** [comment]
Updated through the PPA, still the same issue.
Here's the end of my log.txt:

Loaded plugin "SolarSystemEditor"
[StelPropertyMgr] Registering object "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
"WARNING: could not find script file %f"

**Comment by alex-w** [comment]
Please show result of running command: cd ~ && ls -al

**Comment by francheu** [comment]
drwxr-xr-x  5 me me  4096 juin  22 17:20  .stellarium

**Comment by alex-w** [comment]
No, please show permissions for Desktop directory

**Comment by francheu** [comment]
Sorry, here's the complete listing:

drwxr-xr-x 31 me me  4096 juin  22 12:40  .
drwxr-xr-x  3 root root  4096 juin  15 23:36  ..
-rw-------  1 me me  2747 juin  22 18:00  .bash_history
-rw-r--r--  1 me me   220 juin  15 23:36  .bash_logout
-rw-r--r--  1 me me  3771 juin  15 23:36  .bashrc
drwxr-xr-x  2 me me  4096 juin  16 01:42  Bureau
drwxr-xr-x 22 me me  4096 juin  22 13:05  .cache
drwxrwxr-x  3 me me  4096 juin  16 20:27  captvty-2.7.14.2
drwxr-xr-x 26 me me  4096 juin  22 17:14  .config
drwx------  3 me me  4096 juin  15 23:44  .dbus
drwxr-xr-x 16 me me  4096 juin  16 23:29  Documents
drwxr-xr-x  2 me me  4096 juin  17 22:45  .FreeCAD
drwx------  3 me me  4096 juin  20 21:10  .gconf
drwxr-xr-x 24 me me  4096 juin  16 21:39  .gimp-2.8
drwx------  3 me me  4096 juin  16 01:42  .gnupg
drwxr-xr-x  4 me me  4096 juin  20 07:44  gPodder
-rw-r--r--  1 me me    22 juin  15 23:36  .gtkrc-2.0
-rw-r--r--  1 me me   516 juin  15 23:36  .gtkrc-xfce
drwx------  8 me me  4096 juin  16 00:16  .gwyddion
-rw-------  1 me me  4334 juin  22 12:40  .ICEauthority
drwxr-xr-x  2 me me  4096 juin  18 19:18  .icons
drwxr-xr-x  3 me me  4096 juin  16 14:36  Images
drwxr-xr-x  3 me me  4096 juin  16 23:28  .java
drwxr-xr-x  4 me me  4096 juin  16 01:43  .linuxmint
drwx------  3 me me  4096 juin  16 01:42  .local
drwx------  3 me me  4096 juin  16 14:18  .macromedia
drwx------  5 me me  4096 juin  16 00:30  .mozilla
drwxr-xr-x  2 me me  4096 juin  16 01:42  Musique
-rw-------  1 me me    69 juin  16 00:16  .octave_hist
drwxr-xr-x 12 me me  4096 juin  16 23:46  .PlayOnLinux
lrwxrwxrwx  1 me me    36 juin  16 20:27 "PlayOnLinux's virtual drives" -> /home/me/.PlayOnLinux//wineprefix/
-rw-r--r--  1 me me   807 juin  15 23:36  .profile
drwxr-xr-x  4 me me  4096 juin  16 16:07  .Qarte
drwxr-xr-x  5 me me  4096 juin  22 20:16  .stellarium
-rw-r--r--  1 me me     0 juin  15 23:44  .sudo_as_admin_successful
drwxr-xr-x  2 me me  4096 juin  20 21:36  Téléchargements
drwxr-xr-x  2 me me  4096 juin  18 19:18  .themes
drwx------  3 me me  4096 juin  16 00:15  .thumbnails
drwxr-xr-x  5 me me  4096 juin  16 23:33  .turtlesport
drwxr-xr-x  3 me me  4096 juin  16 15:59  Vidéos
drwxrwxr-x  4 me me  4096 juin  17 00:33  .wine
-rw-------  1 me me    55 juin  22 12:40  .Xauthority
-rw-------  1 me me 28998 juin  22 20:16  .xsession-errors
-rw-------  1 me me 11997 juin  22 10:17  .xsession-errors.old

**Comment by alex-w** [comment]
Please attach a log.txt and config.ini files after crash

**Comment by francheu** [comment]
[log.txt](https://github.com/Stellarium/stellarium/files/3317144/log.txt)

**Comment by francheu** [comment]
[config.txt](https://github.com/Stellarium/stellarium/files/3317149/config.txt)

**Comment by alex-w** [comment]
OK. I've installed Mint 19.1 into VirtualBox and I've tested various builds of stellarium - the problem of crash in Qt from standard repository. For example you may check our AppImage.

**Comment by francheu** [comment]
I've just downloaded the AppImage and it works fine, thanks for the tip.

**Comment by alex-w** [comment]
@francheu could you attach your /etc/apt/sources.list and /etc/apt/sources.list.d/* files?

**Comment by francheu** [comment]
[sources.list.txt](https://github.com/Stellarium/stellarium/files/3455277/sources.list.txt)

**Comment by francheu** [comment]
[sources.list.d.zip](https://github.com/Stellarium/stellarium/files/3455290/sources.list.d.zip)

**Comment by alex-w** [comment]
Could you check release 0.19.2?

**Comment by francheu** [comment]
Hi, 
Got the update from the PPA and still the same issue...

**Comment by francheu** [comment]
I close this issue. The workaround is to use the AppImage.
