### ISSUE TITLE
telescope control with external software/remote computer is broken

### ISSUE THREAD

**Issue by henrysky** [Stellarium/stellarium#702]
### Actual Behaviour

When clicking telescope control plugin -> configure telescope -> Add -> Select "external software or a remote computer", it seems that Stellarium failed in several way
1. connect button is useless in case of the telescope is selected as "external software or a remote computer", I confirmed with a socket server to listen the default port 10001 but Stellarium never attempt to connect.

2. any telescope selected as "external software or a remote computer" will not be saved when exit Stellarium (but it works with other telescope type)

3. any telescope selected as "external software or a remote computer" cannot be configured as every time you click "configure" it will just show the default create new telescope window  (but it works with other telescope type)

### Expected Behaviour
Expected behavior is observed in Stellarium 0.18.0 but not in >=0.18.1 including the latest 0.19.1. **The telescope control with external software/remote computer is clearly broken between 0.18.0 and 0.18.1**

1. I expect the connect button actually works

2. I expect the configuration will be saved on exit

3. I expect when I click "configure" button allow me to configure the current telescope

### Steps to reproduce

see above

### System
* Stellarium version: 0.19.1 win64
* Operating system: win10 1903 x64
* Graphics Card: Irrelevant

### Logfile 
I can give it on demand but I dont think it is relevant?

**Comment by alex-w** [comment]
Please check version 0.19.1.16966

**Comment by henrysky** [comment]
I can confirm the issue is fixed now

**Comment by alex-w** [comment]
Thanks for report and test!
