### ISSUE TITLE
LoadLibrary failed with error 87: Stellarium will not start in Remote Desktop

### ISSUE THREAD

**Issue by pwarborg** [Stellarium/stellarium#703]
Hi,
Thanks for this great software! I use it since years in various versions on various computers and really love it.
Now I installed Stellarium 0.19.0 on a mini-pc (Shinobee 8GB, 256GB SSD, Win 10 Pro, Intel Celeron, 4 processors, AMD Radeon HD 8330) where I want to use it for telescope pointing in remote operation. This is what I experienced:
* I can start it directly on the mini with no issues.
* When I try to start it from my Windows 10 laptop in a remote session with Microsofts's Remote Desktop, I get an error: "LoadLibrary failed with error 87: Parameter not correct" and it will not start.
* When I start it on the mini and take remote control, it will display okay on my laptop.
In my desperation, I tried the MESO version and the ANGLE version: 
* The MESO version gives the same error (and it will not start).
* The ANGLE version DOES start!
I updated and re-installed the drivers for the AMD graphic card (which is the recommendation in the www for this error) but that does not fix it.
Attempts to remotely start Stellarium from my older Windws 7 Laptop resulted in an exact reproduction of the issue. 
Is there an easy fix to this or is it just safe to go on using the ANGLE version?
Thanks and kind regards,
Pat

**Comment by gzotti** [comment]
I have no idea of internals of remote desktops. If using ANGLE provides a working solution, please by all means use it. Stellarium has not been created with remote desktops in mind.

**Comment by alex-w** [comment]
Please find file atiglpxx.dll and rename it into atiglpxx.dll.bak

**Comment by pwarborg** [comment]
Does not work. I keep getting the same error. The ANGLE mode is the only way to start stellarium remotely.
Thanks, Pat
