### ISSUE TITLE
problem with ig7icd64.dll in next version Stellarium

### ISSUE THREAD

**Issue by didpoy** [Stellarium/stellarium#704]
Hello
I have a problem with ig7icd64.dll:
The bug occurs when opening the software in full screen. The one closes itself under Windows 10 -1903 !
Nom de l’application défaillante stellarium.exe, version : 0.19.1.1, horodatage : 0x5d0e4606
Nom du module défaillant : ig7icd64.dll, version : 10.18.10.3304, horodatage : 0x522e0679
Code d’exception : 0xc000041d
Décalage d’erreur : 0x000000000035f485
ID de rapport : ed63f7f3-10eb-4f2d-a3c8-22be1a2dee92
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :
ID du processus défaillant : 0x1cc8
Heure de début de l’application défaillante : 0x01d529e111e4bedf
Chemin d’accès de l’application défaillante : C:\Program Files\stellarium\stellarium.exe
Chemin d’accès du module défaillant: C:\WINDOWS\SYSTEM32\ig7icd64.dll

I deposited the dll ig7icd64.dll manually in the installation folder and it works.
Which solution to apply?
I uninstalled and reinstalled Stellarium and it's the same.
I tried to re-register the dll, but it sends me an error!
Thank you your helpers.
Cordially.

**Comment by gzotti** [comment]
The name sounds like "Intel Graphics 7 ...". You did not provide Stellarium's log for more identification. Probably you can try the ANGLE version. (Link in your "START/stellarium"  group.)

**Comment by didpoy** [comment]
Thank you. Where is this stellarium log file, I can not find it!

**Comment by gzotti** [comment]
User Guide, section 5.3.

**Comment by didpoy** [comment]
You put me on the track of the graphics card.
I uninstalled my graphical driver and reinstalled it.
Stellarium works perfectly now.
Thank you for the help.
Cordially.
