### ISSUE TITLE
support for OpenGL ES on raspberry and other arm board

### ISSUE THREAD

**Issue by dragonlost** [Stellarium/stellarium#709]
Hello.

I am a developer on the NAFABOX project.  We integrate from the beginning stellarium in the list of available software.  

Since 1 year the board based on arm supports better and better graphic acceleration, which makes possible in theory, the very fluid use of stellarium.  

But the card arm uses OpenGL ES and not OpenGL.  

A week ago, was announced the raspberry pi 4 which finally supports graphics acceleration.  

So I would like to know if in the future it would be possible that stellarium is compatible OpenGL ES 3.0 or higher?

**Comment by alex-w** [comment]
Hint: https://github.com/Stellarium/stellarium/wiki/Raspberry-Pi

**Comment by dragonlost** [comment]
thank you.  I'm going to test this on a tinkerboard and a nanopi M4 under ubuntu.  to see if it is applicable to other systems (rk3399 for nanopi-m4)

**Comment by gzotti** [comment]
I have invested quite some time to test on RPi with the VC4 open-source drivers.  The RPi4 has VC6, not sure about its native graphics capabilities yet. Of course the RPi4 specs are very interesting (but it also uses more power, making it more problematic for battery-powered systems), but I don't have one yet.
In any case, Qt, on which Stellarium is based, requires OpenGL ES2.0, not more.

**Comment by dragonlost** [comment]
ok, i test stellarium with rockchip graphic driver (rk3399 first)

**Comment by gzotti** [comment]
@dragonlost, any results to share?

**Comment by gzotti** [comment]
Stellarium runs well out of the box on RPi 3, 3+, 4. It needs OpenGL ES2, and does not use extra features of ES3. Nowadays, just follow Linux build instructions. There is no longer need to build Mesa or other libs yourself. We cannot comment on graphics support on other boards.
