### ISSUE TITLE
making background sky color configurable

### ISSUE THREAD

**Issue by alexandervlpl** [Stellarium/stellarium#71]
I would like to add a config file option to change the sky background color from black to something else. This is part of a project that uses Stellarium to create artwork.

Can anyone point me in the right direction? I can't find where this black color is set in the code.

**Comment by gzotti** [comment]
Black is likely not set, it is the default non-color with which the frame is initialized. It is assumed you cannot set the cosmic background colour in nature. You can always apply a foreground layer as light pollution layer though. (semi-transparent "light" layer in Landscape.)

**Comment by alexandervlpl** [comment]
Thanks for tip! I already tried playing with light pollution, but it hides stars with lower magnitude and makes the rest appear faded (which is exactly what light pollution should do :smirk: ). I want to avoid these effects and get the clearest possible night sky, only changing the "background color" of the universe.

**Comment by gzotti** [comment]
Yes, but the light layer of landscapes (which can be used to simulate e.g. street lights, bright windows or spotty light pollution from nearby villages or cities) is independent from the global light pollution which reduces starlight. You can even switch off atmosphere and still have it. (This allows brightened spacecraft windows on airless moons...)  On the other hand, there is no background colour to set. (And no, sorry, I don't think we should allow initializing the sky to pink or whatever instead. )

**Comment by gzotti** [comment]
I actually solved it. No more than 2 lines of code needed changes (when hardcoding a color), and I don't see bad side-effects. 

While not generally useful for observing astronomers, it could become a hidden feature. (There may be some applications in art&culture where a dark-blue background looks better. Funny people will show a yellow or pink sky.) I could introduce a new config value [color]/sky_background which relates to a new property of StelMainView. (Allows runtime changes via RemoteControl API.) Or we make it fully open with a color to set in the ConfigDialog. 

Opinions?

**Comment by alex-w** [comment]
Hi!

2018-01-13 17:49 GMT+07:00 Georg Zotti <notifications@github.com>:

> I actually solved it. No more than 2 lines of code needed changes (when
> hardcoding a color), and I don't see bad side-effects.
>
> While not generally useful for observing astronomers, it could become a
> hidden feature. (There may be some applications in art&culture where a
> dark-blue background looks better. Funny people will show a yellow or pink
> sky.) I could introduce a new config value [color]/sky_background which
> relates to a new property of StelMainView. (Allows runtime changes via
> RemoteControl API.) Or we make it fully open with a color to set in the
> ConfigDialog.
>
> Opinions?
>
I think an option color/sky_background and couple string in the User Guide
would be acceptable here.

-- 
With best regards, Alexander
Phone: +7 903 957 3596
Skype: alex.v.wolf

**Comment by alexandervlpl** [comment]
Awesome, thanks for taking care of this! A [color]/sky_background option would be enough for my purposes.

If you can already post a patch with a hardcoded colour, I would greatly appreciate it. My current solution is changing the background on screenshots with an ImageMagick command. Not perfect. ;)

**Comment by gzotti** [comment]
To hardcode today: edit StelMainView.cpp around line 360 (`gl->glClearColor()`). And change MilkyWay.cpp, line 192:	`sPainter.setBlending(true, GL_ONE, GL_ONE); // allow colored sky background`.
Or wait until next beta for a cleaner solution.

**Comment by gzotti** [comment]
Done. You can even use the TextUserInterface plugin to edit sky colour interactively, then store in Configuration Dialog (included in the "Store Settings" like everything else.)
