### ISSUE TITLE
Gregorian date for AstroCalc?

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#711]
I don't know if this is considered a bug or not, but the time in AstroCalc (Ephemeris tab) is in Gregorian calendar, even though the time is set to pre-1582. Example:
![stellarium-196](https://user-images.githubusercontent.com/37028368/60823412-c3513400-a1a7-11e9-9085-f5b3dfbddca6.png)

Note how the ephemeris start date is set to 1503-01-01, but the calculation says 1502-12-22.

**Comment by alex-w** [comment]
Yes, it's limitation of standard QDateTimeEdit widget. OK, I've changed lower limit for dates (valid range is 1600/1/1 - 9999/12/31 now - sorry)
