### ISSUE TITLE
Stellarium 0.19.1 GPS support on MacOS

### ISSUE THREAD

**Issue by rdezon** [Stellarium/stellarium#712]
Installed from Macport or with gpsdX app, gpsd is perfectly functional on macOS. 
Even when running on the default port (2947) Stellarium can't get positions from gpsd.  It Keep saying "GPS: Failed" when clicking on the dialog box button.

I have try to get position directly from device serial port adding gps_interface and gps_baudrate in config.ini (Stellarium user guide chap 5.5.4). The GPS receiver is correctly detected but no position is read. 

**System**
Stellarium version: 0.19.1
Operating system: macOS High Sierra 10.13.6
Graphics Card: Intel Iris
GPS receiver: u-Blox USB attached

**Logfile**
[log.txt](https://github.com/Stellarium/stellarium/files/3380465/log.txt)

**Comment by alex-w** [comment]
Please show config.ini file

**Comment by rdezon** [comment]
USB device like this one are always mapped as usmodemxxxxx on macOS.
I have tried both cu.usbmodemxxxxx and tty.usbmodemxxxxx.
Only cu.usbmodem is ok (tested with cat /dev/cu.usbmodem).
Maybe the attached log.is the one with tty.usbmodem in the config.ini file.
As gpsd works on macOS I would prefer to use it. 
I also tried to add gps_hostname and gps_port in the config.ini file without success.

**config.ini**
[DialogPositions]
Help                                = 722,319
Location                            = 591,273

[DialogSizes]
AstroCalc                           = 936,422
Configuration                       = 882,665
Help                                = 476,441
Location                            = 738,533
Oculars                             = 939,693
Satellites                          = 679,606
Search                              = 507,279
View                                = 983,686

[Satellites]
hint_color                          = 0.0,0.4,0.6
hint_font_size                      = 10
last_update                         = 2019-07-09T12:56:35
orbit_fade_segments                 = 5
orbit_line_flag                     = true
orbit_line_segments                 = 90
orbit_segment_duration              = 20
show_satellite_hints                = false
show_satellite_labels               = true
tle_sources/1/url                   = http://celestrak.com/NORAD/elements/noaa.txt
tle_sources/10/url                  = http://celestrak.com/NORAD/elements/science.txt
tle_sources/2/url                   = http://celestrak.com/NORAD/elements/goes.txt
tle_sources/3/url                   = http://celestrak.com/NORAD/elements/gps-ops.txt
tle_sources/4/url                   = http://celestrak.com/NORAD/elements/galileo.txt
tle_sources/5/add_new               = true
tle_sources/5/url                   = http://celestrak.com/NORAD/elements/visual.txt
tle_sources/6/url                   = http://celestrak.com/NORAD/elements/amateur.txt
tle_sources/7/url                   = http://celestrak.com/NORAD/elements/iridium.txt
tle_sources/8/url                   = http://celestrak.com/NORAD/elements/geo.txt
tle_sources/9/url                   = http://celestrak.com/NORAD/elements/tle-new.txt
tle_sources/size                    = 10
update_frequency_hours              = 72
updates_enabled                     = true

[astro]
flag_bright_nebulae                 = false
flag_extinction_below_horizon       = true
flag_grs_custom                     = false
flag_light_travel_time              = false
flag_milky_way                      = true
flag_nebula                         = true
flag_nebula_display_no_texture      = false
flag_nebula_long_name               = false
flag_nebula_name                    = false
flag_nebula_ngc                     = false
flag_object_trails                  = false
flag_planets                        = true
flag_planets_hints                  = false
flag_planets_labels                 = true
flag_planets_orbits                 = false
flag_star_name                      = true
flag_stars                          = true
flag_telescope_name                 = false
flag_telescopes                     = false
flag_use_de430                      = true
flag_use_de431                      = true
grs_drift                           = 15
grs_jd                              = 2456901.5
grs_longitude                       = 216
labels_amount                       = 3
max_mag_nebula_name                 = 8
meteor_rate                         = 10
milky_way_intensity                 = 1
nebula_hints_amount                 = 3
nebula_scale                        = 1

[color]
azimuthal_color                     = 0.3,0.2,0.1
cardinal_color                      = 0.77,0.22,0.1
const_boundary_color                = 0.3,0.1,0.1
const_lines_color                   = 0.13,0.19,0.24
const_names_color                   = 0.31,0.38,0.46
default_color                       = 0.458,0.509,0.671
dso_circle_color                    = 1.0,0.68,0.20
dso_label_color                     = 0.15,0.65,0.65
ecliptic_J2000_color                = 0.3,0.3,0.1
ecliptic_color                      = 0.6,0.2,0.2
equator_color                       = 0.2,0.2,0.6
equatorial_J2000_color              = 0.1,0.3,0.4
equatorial_color                    = 0.1,0.2,0.3
galactic_color                      = 0.0,0.3,0.2
galactic_plane_color                = 0.5,0.3,0.1
gui_base_color                      = 0.458,0.509,0.671
gui_text_color                      = 0.8,0.87,0.87
horizon_color                       = 0.2,0.6,0.2
meridian_color                      = 0.2,0.6,0.2
object_trails_color                 = 1,0.7,0
planet_names_color                  = 0.46,0.51,0.67
planet_orbits_color                 = 0.69,0.2,0.2
script_console_comment_color        = 1.0,1.0,0.0
script_console_constant_color       = 1.0,0.5,0.5
script_console_function_color       = 0.0,1.0,0.0
script_console_keyword_color        = 1.0,0.0,1.0
script_console_module_color         = 0.0,1.0,1.0
sky_background_color                = 0.000000,0.000000,0.000000
star_label_color                    = 0.4,0.3,0.5
telescope_circle_color              = 0.6,0.4,0
telescope_label_color               = 0.6,0.4,0

[custom_selected_info]
flag_show_absolutemagnitude         = false
flag_show_altaz                     = false
flag_show_catalognumber             = false
flag_show_distance                  = false
flag_show_extra1                    = false
flag_show_extra2                    = false
flag_show_extra3                    = false
flag_show_hourangle                 = false
flag_show_magnitude                 = false
flag_show_name                      = false
flag_show_radecj2000                = false
flag_show_radecofdate               = false
flag_show_size                      = false

[gui]
auto_hide_horizontal_toolbar        = true
auto_hide_vertical_toolbar          = true
base_font_name                      = DejaVuSans.ttf
base_font_size                      = 13
day_key_mode                        = calendar
flag_mouse_cursor_timeout           = false
flag_show_flip_buttons              = false
flag_show_nebulae_background_button = false
gps_baudrate                        = 9600
gps_interface                       = /dev/cu.usbmodem14631
mouse_cursor_timeout                = 10
selected_object_info                = all

[hips]
show                                = false

[init_location]
landscape_name                      = guereins
location                            = 45.7485, 4.84671

[landscape]
atmosphere_fade_duration            = 0.5
atmospheric_extinction_coefficient  = 0.200000002980232
flag_atmosphere                     = false
flag_fog                            = true
flag_landscape                      = true
flag_landscape_sets_location        = false
pressure_mbar                       = 1013
temperature_C                       = 15

[localization]
app_locale                          = fr
date_display_format                 = yyyymmdd
sky_culture                         = western
sky_locale                          = fr
time_display_format                 = system_default
time_zone                           = system_default

[main]
check_updates_enabled               = true
invert_screenshots_colors           = false
restore_defaults                    = false
screenshot_dir                      = /Users/rdezon/Desktop
version                             = 0.19.1

[navigation]
auto_move_duration                  = 1.4
auto_zoom_out_resets_direction      = false
flag_enable_mouse_navigation        = true
flag_enable_move_keys               = true
flag_enable_zoom_keys               = true
flag_manual_zoom                    = false
init_fov                            = 60
init_view_pos                       = 0.27851,0.866613,0.414022
mouse_zoom                          = 10
move_speed                          = 0.0004
preset_sky_time                     = 2451514.25001157
startup_time_mode                   = actual
viewing_mode                        = horizon
zoom_speed                          = 0.00035

[night_color]
azimuthal_color                     = 0.3,0.2,0.1
cardinal_color                      = 0.8,0.1,0.1
const_boundary_color                = 0.8,0.3,0.3
const_lines_color                   = 0.5,0.1,0.1
const_names_color                   = 0.8,0.2,0.2
default_color                       = 0.458,0.509,0.671
ecliptic_color                      = 0.6,0.2,0.2
equator_color                       = 0.2,0.2,0.6
equatorial_color                    = 0.1,0.2,0.3
gui_base_color                      = 0.7,0.2,0.1
gui_text_color                      = 0.9,0.4,0.2
horizon_color                       = 0.2,0.6,0.2
meridian_color                      = 0.2,0.6,0.2
nebula_circle_color                 = 0.2,0.2,0.8
nebula_label_color                  = 0.3,0.3,0.7
object_trails_color                 = 1,0.7,0
planet_names_color                  = 0.8,0.2,0.2
planet_orbits_color                 = 0.8,0.2,0.2
script_console_comment_color        = 0.7,0.0,0.0
script_console_constant_color       = 0.9,0.0,0.0
script_console_function_color       = 0.8,0.0,0.0
script_console_keyword_color        = 0.8,0.0,0.0
script_console_module_color         = 0.8,0.0,0.0
star_circle_color                   = 0.2,0.2,0.8
star_label_color                    = 0.3,0.3,0.7
telescope_circle_color              = 0.6,0.4,0
telescope_label_color               = 0.6,0.4,0

[plugins_load_at_startup]
AngleMeasure                        = false
ArchaeoLines                        = false
CompassMarks                        = false
EquationOfTime                      = false
Exoplanets                          = false
FOV                                 = false
MeteorShowers                       = false
NavStars                            = false
Novae                               = false
Observability                       = false
Oculars                             = true
PointerCoordinates                  = false
Pulsars                             = false
Quasars                             = false
RemoteControl                       = false
RemoteSync                          = false
Satellites                          = true
Scenery3d                           = false
Scenery3dMgr                        = false
SolarSystemEditor                   = true
Supernovae                          = false
TelescopeControl                    = false
TextUserInterface                   = false
TimeZoneConfiguration               = true

[projection]
flag_use_gl_point_sprite            = false
flip_horz                           = false
flip_vert                           = false
type                                = ProjectionStereographic
viewport                            = none
viewportMask                        = none

[scripts]
flag_script_allow_ui                = false
scripting_allow_write_files         = false

[search]
flag_search_online                  = true
simbad_server_url                   = http://simbad.u-strasbg.fr/

[spheric_mirror]
distorter_max_fov                   = 180
dome_radius                         = 5.0
flag_use_ext_framebuffer_object     = false
flip_horz                           = false
flip_vert                           = false
image_distance_div_height           = 2.67
mirror_position_x                   = 0
mirror_position_y                   = 5
mirror_position_z                   = 0
mirror_radius                       = 0.37
projector_alpha                     = 0
projector_delta                     = 10.6
projector_gamma                     = 0.3
projector_phi                       = 0
projector_position_x                = 0
projector_position_y                = 4
projector_position_z                = 0
texture_triangle_base_length        = 8

[stars]
absolute_scale                      = 1
flag_point_star                     = false
flag_star_twinkle                   = true
init_bortle_scale                   = 3
labels_amount                       = 3
mag_converter_max_fov               = 90
mag_converter_min_fov               = 0.001
relative_scale                      = 1
star_twinkle_amount                 = 0.2

[tui]
flag_enable_tui_menu                = true
flag_show_gravity_ui                = false
flag_show_tui_datetime              = false
flag_show_tui_short_obj_info        = false
tui_font_size                       = 15

[video]
fullscreen                          = true
horizontal_offset                   = 0
maximum_fps                         = 10000
minimum_fps                         = 18
screen_h                            = 768
screen_w                            = 1024
screen_x                            = 0
screen_y                            = 0
vertical_offset                     = 0
viewport_effect                     = none

[viewing]
constellation_art_fade_duration     = 1.5
constellation_art_intensity         = 0.449999988079071
flag_azimuthal_grid                 = false
flag_cardinal_points                = true
flag_chart                          = false
flag_constellation_art              = false
flag_constellation_boundaries       = false
flag_constellation_drawing          = true
flag_constellation_isolate_selected = false
flag_constellation_name             = true
flag_ecliptic_J2000_grid            = false
flag_ecliptic_line                  = false
flag_equator_line                   = false
flag_equatorial_J2000_grid          = false
flag_equatorial_grid                = false
flag_galactic_grid                  = false
flag_galactic_plane_line            = false
flag_gravity_labels                 = false
flag_horizon_line                   = false
flag_meridian_line                  = false
flag_moon_scaled                    = false
flag_night                          = false
light_pollution_luminance           = 0.0
moon_scale                          = 4
use_luminance_adaptation            = true

**Comment by gzotti** [comment]
The User Guide is (I think) pretty clear about how to configure Stellarium with gpsd (section 5.5.4). Do NOT configure gps_interface or gps_baudrate. Configure gpsd_hostname and gpsd_port. If that does not work, make sure you are allowed to use gpsd queries on the command line. I developed it on Linux and Windows but cannot test on a Mac.

**Comment by rdezon** [comment]
I tested gpsd configuration only first and direct interface configuration after as it should also work on a Mac. Whatever I'm doing I always have serial port detection in the log.
I'm using the lastest 3.19 gpsd version and dynamic library. Queries from command line with cgps, a command line client provided with gpsd package, are working well.
I also change local port with 127.0.0.1 in gpsd_hostname or with another linux host name running gpsd on my network (with gpsd -G option) without any effect.
What should I see in the log file from gpsd detection ? How I could debug this part ?

**Comment by alex-w** [comment]
I think I know why GPSD is not working properly with version 0.19.1 on macOS. I need some experiments for it.

**Comment by rdezon** [comment]
May I help?

**Comment by alex-w** [comment]
Yes! Please check https://github.com/Stellarium/stellarium-data/releases/download/beta/Stellarium-0.19.1.17038.dmg

**Comment by rdezon** [comment]
Sorry can't test this one as it build for macOS 10.14 only and I'm using macOS 10.13 High Sierra

**Comment by alex-w** [comment]
It's very strange. Please check it: http://astro.altspu.ru/~aw/stellarium/Stellarium-0.19.1.17040.dmg

**Comment by rdezon** [comment]
This one is working well. I can get position from gps. Although there is nothing in the log about it.
[log.txt](https://github.com/Stellarium/stellarium/files/3438941/log.txt)

**Comment by alex-w** [comment]
This is very good! It was package building issue.

Note: at the moment all beta versions required DSO catalog version 3.7!

**Comment by rdezon** [comment]
That's nice that you solved this problem. Using gpsd is very convenient because I travel a lot.
The DSO V3.7 Extended Catalog is not yet available. I had loaded the previous version to use it with the standard Stellarium.
