### ISSUE TITLE
Stellarium and Windows 10 LTSB

### ISSUE THREAD

**Issue by bnred777** [Stellarium/stellarium#713]
### Expected Behaviour
Program starts

### Actual Behaviour
Describe or maybe attach a screenshot?
Program does not start and crashes. I have attached a screenshot. Also, I have tried versions 0.19.1.16986, 0.19.1, 0.19.0, 0.18.3, and 0.16.0. I have tried the 32 bit and 64bit versions of each as well. I have tried running as admin as well. Nothing seems to work.

I am using Windows 10 2016 LTSB on a Eagle3 system (Specifically made for astrophotography) and cannot change the OS. I will attach a screenshot of the event viewer as well. It fails on event id 1000.

### Steps to reproduce
Open the program on Windows 10 LTSB.

### System
* Stellarium version: <Name of downloaded installable file?>Many, see above.
* Operating system: <Name, version number> 10.0.14393
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?> Intel UHD 600 - Driver 25.20.100.6323
![2019-07-11 01_15_51-EAGLE30048 - TeamViewer - Free license (non-commercial use only)](https://user-images.githubusercontent.com/45706408/61026953-80938580-a37a-11e9-850a-0668e910b783.png)
![2019-07-11 01_11_29-EAGLE30048 - TeamViewer - Free license (non-commercial use only)](https://user-images.githubusercontent.com/45706408/61026955-80938580-a37a-11e9-97e6-dd875032a763.png)
![2019-07-11 01_11_29-EAGLE30048 - TeamViewer - Free license (non-commercial use only)](https://user-images.githubusercontent.com/45706408/61026966-88ebc080-a37a-11e9-9f88-af7e56b23583.png)
![2019-07-11 01_15_51-EAGLE30048 - TeamViewer - Free license (non-commercial use only)](https://user-images.githubusercontent.com/45706408/61026967-89845700-a37a-11e9-9636-2609cc16472e.png)

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
On the report I'm clearly see troubles in the drivers for graphics card (google: ig9icd32.dll error)

**Comment by alex-w** [comment]
Fun device!

So, are you tried update Intel drivers already and tried run Stellarium in ANGLE mode?

**Comment by alex-w** [comment]
Could you attach log and crash bump from latest beta?

**Comment by bnred777** [comment]
I feel like a dummy... I didn't know anything about ANGLE mode and it works just fine. Thank you!

**Comment by gzotti** [comment]
@bnred777 is it possible to update Intel graphics drivers on Win10 LTSB? I think there is nothing we can do about this issue except recommending to use ANGLE.

**Comment by gzotti** [comment]
@bnred777 is everything OK when running in ANGLE mode? Then we can close this.

**Comment by bnred777** [comment]
Yep, works perfectly! Thank you!
