### ISSUE TITLE
Graphic issue with Stellarium

### ISSUE THREAD

**Issue by albireo2019** [Stellarium/stellarium#715]
Hello!

I have the following query:

### Expected Behaviour

Deep sky objects, moon etc. are supposed to be graphically displayed when zooming in.

### Actual Behaviour

Objects are not graphically displayed, or at least not detailed. Names are shown. Milky way is displayed. Planets are displayed, but erroneously. Some star clusters are shown, but not very detailed.

### Steps to reproduce

Reinstalled Stellarium, same result. Checked for update of graphics card driver in Windows hardware manager.

### System
* Stellarium version: 0.19.1, 64 Bit version
* Operating system: Windows 7 Ultimate, 64 Bit 
* Graphics Card: ATI Mobility Radeon 4650, driver version 8.632.0.0, Windows says current driver version is already installed

Many thanks for your help in advance.

Best regards,

albireo2019

**Comment by alex-w** [comment]
Please install drivers for graphics card from amd.com website

**Comment by albireo2019** [comment]
Thank you very much! The problem has been resolved with the re-installation of the drivers.

Best regards,

albireo2019
