### ISSUE TITLE
incorrect code in hmsToRad

### ISSUE THREAD

**Issue by wlaun** [Stellarium/stellarium#716]
### Expected Behaviour
hmsToRad in StelUtils.cpp
Convert time in hours, minutes and seconds to radians, 12 hours = PI

### Actual Behaviour
e.g. hmsToRad( 1, 12, 0 ) returns 0.2652900463031 and not 0.3141592653590 = PI/10
e.g., round trip radToHms( hmsToRad (1, 12, 0)  ) returns 1h00m48.000s and not 1:12:00

### System
* Stellarium version: branch master

### best Fix:
 hmsToRad(h, m, s)
    return hmsToHours(h, m, s)*PI/12.0;
}

**Comment by alex-w** [comment]
Thanks @wlaun for report about this stupid bug (I think it was introduced by me when refactoring of code was made) and fix for it
