### ISSUE TITLE
StelToneReproducer seems to use wrong target RGB color space

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#718]
While trying to understand the mismatch between what I see in the sky and what I get on the screen, I've come across the following fact. Current code for tone mapper appears to use Adobe RGB (1998) as the target color space for conversion from XYZ to RGB:

https://github.com/Stellarium/stellarium/blob/7600d03823a3680bbf99f72c7edc3bb3bf0660bb/src/core/StelToneReproducer.cpp#L140-L143

(This is also repeated in `xyYToRGB.glsl`.) But neither in 2003 when this code was added by Fabien Chereau, nor today is the default color space for the monitors anywhere close to Adobe RGB. Instead it's sRGB, which has a smaller gamut due to the green primary being closer to the (same, D65) white point. On the wide-gamut displays like phone/tablet AMOLED ones, it's instead close to Display P3.

Since sRGB also has D65 white point, I don't see the point in the comment before the code.

The result is duller colors than they should be.

It seems that the XYZ-to-sRGB matrix should be used instead, but maybe I'm missing something?

**Comment by alex-w** [comment]
Hmm... I've updated the XYZ-to-RGB matrix (source: http://brucelindbloom.com/index.html?Eqn_RGB_XYZ_Matrix.html). I guess Fabien used XYZ-to-Adobe RGB matrix for historical reasons.

**Comment by gzotti** [comment]
I have observed the same and tried AdobeRGB to sRGB in my gz_atmosphereTweak branch. It looks terrible. Note that there is also some break in low brightness values (don't remember the details now). However, I don't have the original Siggraph paper with the ABCDE parameters, only a preprint with slightly different values.  @alex-w changing this in the master branch will greatly change the appearance!

**Comment by alex-w** [comment]
@gzotti I see no serious difference after change the coefficients. Are you have coefficients for matrix XYZ-to-sRGB with using D65 white point in preprint?

**Comment by gzotti** [comment]
Sorry, I am away from my dev environment until August. I remember that sRGB conversion has some diverging brightness handling for low values, and the result looked bad.

**Comment by alex-w** [comment]
@gzotti I see in your branch the coefficients for matrix has been changes only in shader, but same matrix in the StelToneProducer was not changed.

**Comment by gzotti** [comment]
Maybe I forgot this and it therefore looked bad? Cannot say until I return. But make sure all conversions are applied correctly.
