### ISSUE TITLE
BCE (B.C.) or Negative [-] Dates

### ISSUE THREAD

**Issue by Alkibiades410** [Stellarium/stellarium#72]
First, brilliant program, which has aided me greatly in my current research.  LOVE IT.  That said, I have uncovered a minor glitch.  My work concerns Ancient Greece.  When you move into negative dates (BC/BCE) [eg -432], the years regress by one.  In other words, Julian days prove correct with regard to what happens in the sky, but it renders the date one year too early.  id est, 1563101.370900 renders as 16 July 433, when it is actually 16 July 434 BCE.

**Comment by alex-w** [comment]
Stellarium uses astronomical numeration of years - http://stellarium.sourceforge.net/wiki/index.php/FAQ#.22There_is_no_year_0.22.2C_or_.22BC_dates_are_a_year_out.22

**Comment by gzotti** [comment]
Consider Appendix F of the User Guide essential reading for you!
