### ISSUE TITLE
Interstellar Object type and elements of 1I/Oumuamua

### ISSUE THREAD

**Issue by advanceddigitaldevelopment** [Stellarium/stellarium#721]
Recent updates say: "Added Interstellar Object type and elements of 1I/Oumuamua." But, this does not seem to be the case.

**Comment by alex-w** [comment]
https://github.com/Stellarium/stellarium/blob/master/data/ssystem_minor.ini#L45

Please use Solar System Editor plugin to manage Solar System bodies

**Comment by advanceddigitaldevelopment** [comment]
Alex, thanks, I appreciate your effort. But, as I said, the latest update of Stellarium says that they already "Added Interstellar Object type and elements of 1I/Oumuamua." Therefore, Stellarium seems to need to be fixed because the object is not recognized.
