### ISSUE TITLE
Timing of the sun during transit

### ISSUE THREAD

**Issue by ushikata** [Stellarium/stellarium#722]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by ushikata** [comment]
I am attempting to find a true North baseline at a survey site by sighting on the sun using a theodolite with a solar filter. I find the time of solar midday using Stellarium and sight on the sun centre at midday. I also take several readings before and after midday from the left edge and right edge of the sun and average the results, again using Stellarium.

My problem is that the change in azimuth per second at midday with Stellarium, currently about 26 secs arc per second of time, is twice the actual speed of the sun as measured on site( 2 mins 17 secs to transit), and on Stellarium it reduces to the average as the sun moves away from midday. Along with the Stellarium clock not matching an atomic clock I am having some difficulty getting results I can rely on.


Am I going wrong here somewhere or should I be making some adjustments to the default Stellarium set up?

I am using a year old Lenovo 520 desktop running Windows 10 and the latest version of Stellarium.

**Comment by gzotti** [comment]
Note that with a high sun you will have faster azimuth change. The sun (and other objects) move 15 arcseconds per time second in hour angle. High in the sky the azimuth lines come closer together, maybe this is what confuses you?
In any case, please see appendix F of the User Guide for accuracy notes.

**Comment by ushikata** [comment]
Thanks for the reply Georg. I am aware of the 15 arcsecond per second standard, My confusion comes from changing the time stamp in stellarium by 1 second and noting the sun's azimuth changing by 26 seconds of arc, but only around the time of solar noon. When the time is changed at 6pm, 12 pm or 9 am the change in arc is almost the same as the standard, except in the winter when the situation is reversed, ie, the midday sun slows down and the midnight sun speeds up?  When I measured the actual time the sun took to transit on 24th July it was 137 seconds at 52 degrees latitude, measured with a theodolite.
    On Thursday, 25 July 2019, 19:46:52 BST, Georg Zotti <notifications@github.com> wrote:  
 
 
Note that with a high sun you will have faster azimuth change. The sun (and other objects) move 15 arcseconds per time second in hour angle. High in the sky the azimuth lines come closer together, maybe this is what confuses you?
In any case, please see appendix F of the User Guide for accuracy notes.

**Comment by gzotti** [comment]
You are noticing a projection effect! 
At an altitude of 57°,  a degree in azimuth is just around 32' on the sphere. Display an azimuth grid and use the Angle Measure plugin to teach yourself.

**Comment by ushikata** [comment]
Thanks for the reply gzotti. I don't think I've been clear in my explanation. 

In Stellarium If I left click on the sun, it brings up a list of the suns properties, including azimuth. If I also bring up the time/date table I can change the time/date and the sun list changes to suit. If I change the time to middayish and then alter it in one second increments the azimuth in the sun properties list changes by 26 seconds approx per sec arc, but only around midday. If I change the time to between evening and morning one second difference in the time will change the azimuth by about the average, 15 secs arc. It's not the size of the sun that I'm measuring, just it's azimuth.

**Comment by gzotti** [comment]
You are clear in describing your observations. However, you don't understand my explanations. The distances between azimuths (verticals) are foreshortened when the sun is moving high in the sky. A degree of azimuth is only a degree on the sphere along the horizon, not in 57 degrees altitude. A one-second change in time will change the Sun's Hour Angle by 1 second (time), or 15 arcseconds. 

Apart from the few arcseconds caused by Stellarium's non-computing of aberration (User Guide, App.F) the coordinates are OK, and it is instructive to switch on coordinate grids to understand the various difficult effects of spherical coordinates.
