### ISSUE TITLE
Keyboard customizations don’t stick between startups

### ISSUE THREAD

**Issue by pschroeter** [Stellarium/stellarium#724]
I believe there is a bug where if you set a keyboard command to one that is a built in command for a different command, and then leave the key command slot for the built in command empty, Stellarium reloads the command on startup to fill the slot and creates a conflict.

For example, I set the H key to activate the “Go to home” command. I took the key from the “Horizon line” command which I cleared so I wouldn’t create a conflict. It worked for a while then after shutting down and restarting I found Stellarium had assign H to the BOTH commands creating a conflict. 

I also very much wish when I assign keys in a way that create conflicts, the program would warn you and tell you what command is currently is using it and ask if you want to reassign it, or in the very least told me which other command was using it. (I'll post this on feature requests too.)

**Comment by alex-w** [comment]
I've fixed restoration for removed shortcuts through config.ini file - it will be available for testing in next beta and in 0.19.2 release.

Workaround for version 0.19.1 - just add into config.ini in section [shortcuts] follow line:
actionShow_Horizon_Line = ""
for removing shortcut H from "Horizon line"

**Comment by pschroeter** [comment]
> 
> 
> I've fixed restoration for removed shortcuts through config.ini file - it will be available for testing in next beta and in 0.19.2 release.
> 
> Workaround for version 0.19.1 - just add into config.ini in section [shortcuts] follow line:
> actionShow_Horizon_Line = ""
> for removing shortcut H from "Horizon line"

Thank you for being so quick. I actually got around the problem by not leaving the slot blank and creating an oddball combination to fill it. 
Will the fix allow us to leave the slot empty for commands with built in keyboard commands if we want?

**Comment by alex-w** [comment]
Yes, the patch allow removing built-in shortcuts.

**Comment by alex-w** [comment]
Please check the latest beta
