### ISSUE TITLE
Can’t sync Telescope reticle with selected star.

### ISSUE THREAD

**Issue by daemonhunter66** [Stellarium/stellarium#727]
Hi all. I have Stellarium 19 installed on a W10 laptop, that is attached to Skywatcher HEQ5pro using a serial cable (cable plugs into SynScan hand controller), and the two talk using the built in Telescope Control plugin (so not using EQMod or any other software).
Everything work excellently expect I can’t get the telescope reticle and the selected star to sync up. I slew to a star using Ctrl + 1, and then using the hand controller I centre the star in the eyepiece. Now the telescope reticle and the selected star are misaligned so I try to use Ctrl + 3 to sync them but nothing happens. Is this expected behaviour or is there something else I need to? Is my request even possible?
One extra comment. When I plug in the laptop to the hand controller I just leave it as it is, I don’t activate pc direct mode as I have seen other do with EQMod.
All help appreciated.

**Comment by gzotti** [comment]
There is no sync to star. Stellarium assumes you have properly configured and aligned your mount (e.g. using its own fine adjustments) and just sends GOTO commands.

**Comment by daemonhunter66** [comment]
Oh ok. I thought I read online that Ctrl + 3 synced the two together but that not working for me. Thanks

**Comment by gzotti** [comment]
Where did you read that? The User Guide is authoritative.

**Comment by alex-w** [comment]
@daemonhunter66 please check latest beta
