### ISSUE TITLE
Incorrect grammar for Polaris Galacticum Boeralis (31 Comae Berenices)?

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#729]
I'm really no expert in Latin, but I guess _Polaris_ is feminine (_Stella Polaris_) and thus the name should read:
**Polaris Galactica Borealis**

I have seen examples online using the name as masculine (**Polaris Galacticus Borealis**), but it is certainly not neuter, which is what Stellarium currently suggests.

**Comment by gzotti** [comment]
"Galacticus" would be masculine (-um for neutral), but you are correct if we assume its full name should be "Stella (noun) Polaris (adjective) Galactica (adjective) Borealis (adjective)". It could also be "Polus Galacticus Bor.". 

Now we face a problem: Original source is http://stars.astro.illinois.edu/sow/pgb.html, in which "(Thanks to Latin scholar David Bright.)" has been acknowledged. The star name is not "official" (IAU list) and is in no other list. (Where did you see it online?) Should we stick to the source, or correct this obvious faux pas?

**Comment by Atque** [comment]
@gzotti You have the same source as I do, and that source uses a masculine gender for the name. But I think, since the name _Polaris_ stems from _Stella Polaris_, it should be feminine. With masculine, _Galacticum_ must be changed to _Galacticus_, and if we keep the current neuter version, _Borealis_ need to be changed to _Boreale_, to keep it consistent. But I don't see how _Polaris_ could be neuter (unless it's genitive case! But still we need to choose a gender...).

A real minor issue, I know, but I just stumbled upon it and found it curious.

**Comment by gzotti** [comment]
I changed it to its original (also buggy) spelling.
