### ISSUE TITLE
Showing Moon's day

### ISSUE THREAD

**Issue by jsrendezvous1960** [Stellarium/stellarium#73]
I enjoy Stellarium every day, thanks to your great effort.
In the latest version 0.17.0, it looks that Moon's day or synodic month (0.0-29.5) is not shown. If my understanding is correct, really hope to add this information.

Regards,
A stargazer in Japan

**Comment by alex-w** [comment]
Why you need this info?

**Comment by gzotti** [comment]
Most Asian cultures have things like Lunar Mansions and thus high importance for any geometrical relations about the moon. 
I think we never gave accurate time since last conjunction, or please point me to a version which showed it. We could easily add elongation in ecliptical longitude from the sun (if we don't already?) Would that help?

**Comment by sunshuwei** [comment]
The lunar phase and solar term is very important in the traditional use of the lunar calendar in East Asia. But after all, the West does not use this.

If it is to be added, it can be used as a function of Astronomical calculations, and it can be used to calculate the data related to the lunar calendar.

**Comment by jsrendezvous1960** [comment]
Thank you for discussing my request.  I just recognized that Western culture haven't had Moon's day.

Moon's day is based on luner calender indeed, but it's simply useful to imagine the shape of Moon. E.g. "7" represents the waxing half moon and we have the traditional star festival in July.  "15" is the full moon and we have the moon gazing festival in September. 
So in Japan,  synodic month (0.0-29.5) reprensents  the moon phase.

**Comment by alex-w** [comment]
The solution will be available for testing in next beta.
