### ISSUE TITLE
Telescope does not work

### ISSUE THREAD

**Issue by tsr537** [Stellarium/stellarium#731]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by tsr537** [comment]
When I configure telescope everything appears Ok, it says I am connected , but when I try to slew to a star nothing happens.

**Comment by alex-w** [comment]
Sorry, where is technical details?

**Comment by tsr537** [comment]
hi, My scope is a SkywatcherMK127 on a Syscan EQ3 mount. My computer is 
a HP laptop running Windows10 64. I am using the latest USB to RS-DB9 
Serial Adapter to connect to the hand control set to DIRECT MODE.
Everything works up and including CONNECT in the Telescope plugin, but I 
can not get the scope to slew to a star . I am using Stellarium 0.18.2. 
Also everything works in Cartes Du Ciel..

------ Original Message ------

**Comment by alex-w** [comment]
Please check the latest stable version - the Telescope Control plugin was changed since version 0.18.2

**Comment by gzotti** [comment]
@tsr537 did you check 0.19.2 or a current beta in the last 6 weeks?
