### ISSUE TITLE
Magnitude filter

### ISSUE THREAD

**Issue by jraff114** [Stellarium/stellarium#732]
When using the web version I often find it hard to compare what I'm seeing on a given night to objects on your chart. Not a problem with the downloaded version as there are plenty of ways to adjust this.

A basic apparent magnitude filter would be great, something like a slider bar in view settings that could filter out the dimmer objects above a magnitude and/or reduce their brightness/size on screen to represent local conditions and the users equipment.

Great job on the software, and thank you, it's a game changer!

**Comment by alex-w** [comment]
This feature was implemented already a few years ago - why you do not use it?

**Comment by axd1967** [comment]
This issue should be reopened and moved to https://github.com/Stellarium/stellarium-web-engine/, as the OP refers to the web version (and also points out that the "downloaded version" does offer the feature.)
