### ISSUE TITLE
possible Pluto positioning inaccuracy?

### ISSUE THREAD

**Issue by sjhk14** [Stellarium/stellarium#734]
In Sir Patrick Moore's book  'The next 50 years in Space' there is a photo on page 92 of the original plates Clive Tombaugh took of Pluto at its 'discovery'. So I wound the 'clock' back in Stellarium, to the 26th April 1930 (5:30ish GMT) and low and behold there's Pluto in the vicinity of Wasat (delta Gem)   However, it's nowhere near the position as displayed by Stellarium? Please advise. I can forward these photos, if you need :-) 
cheers
BR 
SJB
by the way Stellarium is the best!!
![pluto position005](https://user-images.githubusercontent.com/53998423/62834813-5d921500-bc49-11e9-8288-b4a28ec19625.jpg)

**Comment by gzotti** [comment]
Are you sure about the dates? If you asked me for image dates, I would suggest:
Location: Flagstaff (UTC-7)
First image: 1930 March 04, probably around 20:55, altitude 76° in the meridian
Second image: 1930 March 01, probably around 21:06, altitude 76° in the meridian

whereas on April 26, 5:30 GMT Pluto was at only 23° altitude in the West, which I regard as pretty unlikely.

**Comment by sjhk14** [comment]
Yes but those dates are in the right 'ball park' when has Pluto been in such close proximity to Wasap? Between 1930 and 1970s it's the position of Pluto within that star field on the photos you can pick up the 2 stars close together, on the right  hand side, with Stellarium but its the actual relationship of Pluto in Stellarium compared with the photo plates I.m on about.

**Comment by sjhk14** [comment]
wasap ?? Wasat!! sorry go Watsap on the brain!!

**Comment by gzotti** [comment]
![stellarium-000](https://user-images.githubusercontent.com/18099873/62836584-13b72800-bc65-11e9-92d8-a3ff3bf229e7.jpg)
![stellarium-001](https://user-images.githubusercontent.com/18099873/62836585-174aaf00-bc65-11e9-9b2a-d3b112fcc082.jpg)

What do you mean? Please compare these images. Close enough for me :-)

**Comment by gzotti** [comment]
I hope @sjhk14 is satisfied with my analysis and replay of his photos. Nothing more to say.
