### ISSUE TITLE
Solar System Observer

### ISSUE THREAD

**Issue by RF52** [Stellarium/stellarium#736]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by RF52** [comment]
Hi,

I've been using Stellarium for a while, and have recently run into an issue that I can't resolve. I'm looking at the Galilean satellites, to compare my telescope observations with Stellarium predictions. Part of this involves creating an "overhead view" of Jupiter to show the position of the moons in their orbits. I am finding an inconsistency, which is described in the following example.

![Image16](https://user-images.githubusercontent.com/54059342/62926688-e70e2800-bdac-11e9-9f13-146956d0b305.jpg)

The image above shows the Stellarium prediction for midnight on June 21 2019.

![C21-000934RGBa++](https://user-images.githubusercontent.com/54059342/62926839-3f452a00-bdad-11e9-841c-2083a24b4bf9.png)

This next image above shows one of my telescope captures, which seems to agree nicely.

![Image14](https://user-images.githubusercontent.com/54059342/62926942-73b8e600-bdad-11e9-8083-1384e50dcfb5.jpg)

The image above is the "Solar System Observer" view from Stellarium, which appears incorrect. The Earth on this image is situated to the bottom left of Jupiter (at an angle of about 50 degrees to the "vertical"), and from this perspective, the three visible moons all appear to "the left" of Jupiter, whereas  the first two images above suggest that Europa is to the left, and Callisto & Ganymede are to the right.

I suspect I am doing something wrong, but have read all the posts I can find, but to no avail. Can someone help me please?

Roger. (Windows 10, Stellarium (0.18.2))

**Comment by gzotti** [comment]
To allow a near-orthogonal view, the Solar System Observer is located very far from the sun, so that light travel time becomes an issue. I also had fun with a Lunar eclipse. To compare with Earth view, it's better to switch off light time correction and accept a temporal mismatch of the ~45 minutes from Jupiter to Earth.

**Comment by RF52** [comment]
Thank you for that prompt response gzotti. I hadn't realised SSO was so far distant. Ive tried creating a new observing point in the ini file:

[ jupiter_observer ]
name = Jupiter Observer
parent = Jupiter
albedo =0.
color =0. , 0., 0.
halo = false
hidden = true
coord_func = ell_orbit
orbit_AscendingNode =0
orbit_Eccentricity =0
orbit_Epoch =2451545.0
orbit_Inclination =90
orbit_LongOfPericenter =0
orbit_MeanLongitude =90
orbit_Period =70000000000
orbit_SemiMajorAxis =14000000
radius =1.
rot_obliquity =90
type = observer

but sadly I still cannot get it to generate an image compatible with the observations and "normal" Stellarium view from my observing point. The new observing point works, but even by time shifting by quite a lot, it is not making a lot of sense to me. 

I have placed Jupiter Observer 100 x Jupiter diameter above its North pole (at least I think I have).

R.

**Comment by gzotti** [comment]
hmm, 14.000.000 km are roughly 1/10 AU. Increase this again by 100 and you have 10AU, resulting in roughly the same light time delay.

**Comment by RF52** [comment]
Arghh - I am a fool! It is surprising how often writing a problem down leads to its solution. I made an error and had assumed Io was  behind Jupiter, rather than in front. 

Jupiter Observer now seems to work a treat!

As a matter of interest, making the distance 1,400,000 Km resulted in significant distortion of the orbit paths, but 14,000,000 gives a very acceptable image - below.

![Jupiter Observer 14MKm](https://user-images.githubusercontent.com/54059342/62945214-3d439100-bdd6-11e9-807e-fa030f41536f.jpg)

It compares well with my earlier prediction when you remember that Earth lies to the "bottom left" of the Stellarium image:

![Image19a](https://user-images.githubusercontent.com/54059342/62946171-1f772b80-bdd8-11e9-8350-e78c32e29c8a.jpg)

Very many thanks for your input.

R.

**Comment by gzotti** [comment]
I think I will add this Jupiter Observer to our default list :-) Thanks for the suggestion.

**Comment by RF52** [comment]
Please do so, you're welcome.

BTW one interesting and very neat behaviour of Stellarium, which I didn't expect, is that if you lock onto a target, Jupiter, using your default Earth based viewing location, freeze the display motion and specify a time, and then if you select the Jupiter Observer location, Stellarium updates your chosen time to allow for the speed of light. At least, I think that's what's happening.

I'm assuming since Jupiter is a SSO then the "compensate for speed of light" option is observed (if you've got it ticked), then assuming the Jupiter Observer in NOT a SSO, the light speed won't be invoked BUT instead your viewing time is altered to allow for it. (In my case the time moved back by just over an hour - I tried it several times.)

R.

**Comment by gzotti** [comment]
@RF52 Your observations around time are governed by timezone handling in the site panel. Only terrestrial sites have timezones. In the status bar (bottom of the screen) you see the time offset as UTC+xx. Should be UTC+00:00 for extraterrestrial sites, unless you choose a timezone manually.

**Comment by alex-w** [comment]
Please check the latest beta

**Comment by RF52** [comment]
Hmm. I've never checked Beta's before! However, I've downloaded:

https://github.com/Stellarium/stellarium-data/releases/download/beta/stellarium-0.19.1.17106-win64.exe

and I get the message "The setup files are corrupted. Please obtain a new copy of the program."

Not sure what's wrong? I've tried 3 times.

**Comment by alex-w** [comment]
@RF52 thanks for report about problem for package! I've fixed it - please check it again.
