### ISSUE TITLE
New mark? Planet velocity vector

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#737]
Suggested by Diego Rodríguez 

Original: https://sourceforge.net/p/stellarium/discussion/278769/thread/d43e954769/?limit=25#18df

Showing where does the Earth is bound at any given time would help in understanding many astronomical phenomena, as the meteor showers radiants. Currently, the only source of this information I can think of is the vector tables generated at the NASA Horizons website. Not exactly easy to visualize. So I guess a cross or any other mark placed in the celestial sphere in the point at the infinite where the planet baricenter seems to go would help, but no idea on the maths needed. So good this feature makes it into a developer's desk.

**Comment by axd1967** [comment]
(implemented with the APEX / ANTIAPEX marker)

**Comment by ferreiradantas12** [comment]
hi georg zotti sorry me I'm back in this year that you asked me for a new check the developer it is working i can describe my issue
