### ISSUE TITLE
prevent accidental sat data overwriting

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#738]
### Expected Behaviour

When I accidentally type in a URL in the bottom entry line , I don't expect to overwrite whatever line was selected 

### Actual Behaviour

The line gets overwritten silently!

![image](https://user-images.githubusercontent.com/3529789/63285893-0f1eef00-c2b7-11e9-8b68-f31f5ab5d280.png)

Describe or maybe attach a screenshot?

### Steps to reproduce

1. Open Sat Config
1. go to Sources tab
1. select a source
1. type in anything in the line at the bottom of the dialog
1. click '+'
1. observe that the line that was selected, has been silently REPLACED. I've lost a line, I don't know what was there before.....

I would expect a confirmation dialog if I replace an existing entgry (because now I've lost an entry, and have no idea what was there before)

### Workaround
The plugin "reset" button seems to restore everything, (except the additonal sources that I collected meanwhile)

### System
* Stellarium version: 0.19.0
* Sat Plugin 0.10.13

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
When you edit a source, it gets changed indeed. I would call this normal behaviour. To add a source, press the Plus button, and then write a new source. This is like in a file explorer in most operating systems: click on an existing filename to rename a file, or click "new file..." to create a new file. 

Resetting means deleting user changes and going back to how it was installed. Normal behaviour.

**Comment by axd1967** [comment]
actually the GUI is somewhat "rough around the edges".

the "sources" tab starts with a line selected, and there is no way to add a new entry other than by clicking "+" (which it claims to do, but it actually overwrites an entry, so the user has to be careful not to edit the input line before clicking "+"), after which "[new source]" appears, the user can type in a value and press "enter" to save.

if the user accidentally types something in the input line and then presses "+" to create a new entry, what was in the input line overwrites the selected entry in the list.

as the help text says "press enter to save", only "enter" should save something. 

the "add" button should not save anything (as its tooltip says, it adds a new source, or more precisely, creates an empty input line).

if the user wants to edit an entry, (s)he selects an entry, which copies that entry in the input line, the user edits the input line and presses "enter" to save the edits. if during the edit work the user presses "+" instead, the app could warn that the input has been changed and has not been saved yet (better), or could simply throw away the user's work and create an empty input line (not so good, but simpler to implement). the "add" button could also be disabled once the user starts editing the input line, so the user can either press "enter" to finish work, or select an entry from the list (and maybe get a warning first).

**Comment by alex-w** [comment]
Please check version 0.20.2.18113
