### ISSUE TITLE
Moon's Age

### ISSUE THREAD

**Issue by 700starman** [Stellarium/stellarium#739]
The moon's age is not correct.  Select any new moon, such as Oct 27, 2019.  Go two to three days ahead at the same time as the new moon (22:38 CDT) and the moon's age is not 2.0 days or 3.0 days.  Please repair the moon's age calculation.

**Comment by gzotti** [comment]
Not sure what you mean. On Stellarium 0.19.1, New Moon is around 2019-10-28 04:00 UT. Two days later, "Moon Age=2.2". This may refer not to calendar days, but to the real speed of the moon. The moon is faster than average, so it moves faster in "age".

**Comment by alex-w** [comment]
@700starman please check a fresh beta - https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by gzotti** [comment]
@700starman does this answer your question?

**Comment by alex-w** [comment]
What is source of your strange "correct" data? Why you are expected see age 21 days and nothing else? Or you do not understand what meanin number 4 after dot?

**Comment by 700starman** [comment]
The date/time of the New moon is from the US Naval Observatory.  Count the number of days past that date and time.

**Comment by gzotti** [comment]
As I have explained in my first response, Stellarium does not simply count solar calendar days, but fractions of the Moon's synodic orbit, expressed in days. The moon goes through apogee on December 5th, therefore is slower than average in the sky in the time between solar conjunction and 2019-12-17, and appears somewhat younger than counted in calendar days. 
It seems that we do not adhere to the way the USNO is counting lunar age, but we also did not promise to do so. Both ways have their merits and shortcomings.

**Comment by 700starman** [comment]
So for normal folks let's forget about using Stellarium to determine the age of the moon

**Comment by alex-w** [comment]
> The date/time of the New moon is from the US Naval Observatory. Count the number of days past that date and time.

Seriously? Where is exactly you take the data, because I cannot find Moon age on the website of the US Naval Observatory. If you just calculating a Moon's age "on fingers" (without fraction of days), then I have a bad news - you do not understand how Moon's age are calculated.

**Comment by 700starman** [comment]
Compute illumination and "age" of Moon.  Illumination is the 
% of visible lunar surface in sunlight (0 = new moon, 100 = full). 
Age is the number of days since new moon (range 0 to ~29.53 days). 
Uses low-precision formulae from Chapters 45-46 of Jean Meeus' 
"Astronomical Algorithms" (Willmann-Bell, 1991). 
Errors, in comparison to the definitive ELP-2000/82 Lunar 
Theory, during the years 1900-2100:

**Comment by 700starman** [comment]
Please do not respond.  I am done.  Of course you are right as is everything in Stellarium.

**Comment by Coirt** [comment]
This is something that could be easily fixed in Stellarium it is also something many people might rely on. For instance I would like to know when and at what time the Moon is 14.765 days old but I can't find this information in any software, I'd have to manually calculate it. You might as well completely remove the moons age from Stellarium because it is a useless number.
