### ISSUE TITLE
Let horizon lower with altitude (masl)

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#740]
It would be highly desirable for the horizon panorama (and possibly also the horizon line?) to automatically lower with increased altitude (masl). Of course most suitable for flat horizons, such as Ocean and Zero horizon, and maybe there could be a line in the landscape config, something like "LowerWithAltitude = true" or something, which also affects rise and set times of celestial objects.

Will it be too difficult with refraction though, or can you lower the whole atmosphere model?

**Comment by gzotti** [comment]
How do you know the distance to the horizon shown in the horizon panorama? Unless you are on the ocean or in the flat desert, you will have features along the horizon line, and closer features will move faster than the far horizon. Better make good and accurate panoramas on a per-use case.

**Comment by Atque** [comment]
@gzotti It is most suitable for flat horizons. How would a 3D scene of this look? And do 3D scenes really change with increased altitude? And by this, I mean increased altitude in the Locations window. I want to see the exact horizon from i.e the summit of Mauna Kea, without having to create a separate landscape for that.

**Comment by gzotti** [comment]
3D scenes do not change with altitude. The apparent horizon line formed by the 3D objects changes when you "go into the air". 

The atmosphere pressure, and with it refraction, can change when you load a landscape with altitude. Details: SUG chapter 7. 

To get an "exact" view, you must obviously make an exact landscape panorama. A good approximation can be made with https://homepage.univie.ac.at/Georg.Zotti/php/panoCam.php

**Comment by Atque** [comment]
I know the pressure changes with altitude with certain parameters in the config of the landscape (however it would be nice to have it changed with altitude automatically), but what is interesting is refraction below the visible horizon. Mauna Kea (4190 m) has a visible horizon of more than 2 degrees below the mathematical horizon line; Stellarium ignores this. Refraction is really messed up then, but of course not in reality. The refraction issue may not be solvable though.

Mainly, this feature request is about perfectly flat horizons. Imagine you are located 5000 m above a perfectly flat horizon, for example a sea.

**Comment by gzotti** [comment]
Well, there is no closed formula for that in the literature that we are aware of. Figure 18.6 in the SUG illustrates the refraction model. Expect bogus below -1° or so.

**Comment by Atque** [comment]
And I guess "moving" the whole refraction model, to lower the horizon accordingly to the horizon line of a higher altitude, is not possible/or will look messed up?

**Comment by gzotti** [comment]
What would be the point in it? The current solution is limited because the model does not support -2° horizons. If we distort the model, it would be wrong everywhere. 

The atmosphere on such locations is known to behave almost unpredictable, so these conditions apparently cannot be modelled without doing a real physical simulation of light transport, which is too time-demanding. 

If you can locate a better refraction model that works also on the highest mountains surrounded by far zero-altitude horizons downto at least -5 degrees, please point our noses to it.

**Comment by Atque** [comment]
That's what I suspected. Do you think lowering the horizon with altitude automatically (for flat horizons) is none of the developers' interest until a better refraction model is found?

**Comment by gzotti** [comment]
It does not make sense but will lead to more confusion than it's worth. So it is not in my interest. Just make a proper landscape (with negative horizon) for that site.

**Comment by Atque** [comment]
I understand, thank you for clarifying. I close this issue now.
