### ISSUE TITLE
Clearing Script Console Output Window

### ISSUE THREAD

**Issue by NotSoRandomOne** [Stellarium/stellarium#750]
First, Thanks for the previous changes! Very cool!

One thing I noticed in previous build and this new master (17131) is there doesn't seem to be any way to clear the script console output window.

The following will show the issue. Rerun it a few times, and the output just keeps growing. Have to restart Stellarium to clear it, as far as I can tell, because 'Clear Text' in the upper right hand dropdown doesn't do anything when the output tab is selected.

<pre>map=core.getSelectedObjectInfo();
core.output(core.mapToString(map));

core.resetOutput();</pre>

(Copy/Paste with Ctrl-V/Ctrl-C!!!!!! So Wonderful!!!! Thanks! Made this post a little easier!)

**Comment by alex-w** [comment]
The "Clear Text" command in upper right dropdown is clearing all labels on the screen - it's OK.

To clearing text in some tab (script, log or output) - please press button "Clear" (see top left corner).

The command `core.resetOutput();` should clearing the output tab of course - so, it's regress.

**Comment by NotSoRandomOne** [comment]
One comment when someone has time to do UI work (if you agree it could be improved) is that the 'Clear' button, the 'File Open' button, and even the SSC button all look like they are disabled. The File Save button looks enabled, and useful, but it is a little hard to tell what the others are because of the greyness used in the colors. If they used the same blues as the File Save button, the problem would be eliminated. This may apply to other windows as well, but I haven't played with them as much.

**Comment by NotSoRandomOne** [comment]
(If you want that as a feature request, let me know and I'll put it in as a new item for you.)

**Comment by alex-w** [comment]
Yes, please fill a new request
