### ISSUE TITLE
Screen is flipped horizontally, only in Stellarium.

### ISSUE THREAD

**Issue by RJStellarium** [Stellarium/stellarium#751]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Please attach screenshot

**Comment by NotSoRandomOne** [comment]
RJStellarium: Go into Configuration window (F2). Select the 'Extras' tab. The second toggle from the top right is for putting flip screen buttons on the command bar, or whatever you want to call it on the bottom left of your screen. Once that toggle is enabled, you can flip your screen using the new buttons on that bar.

**Comment by RJStellarium** [comment]
I got this reply:

RJStellarium: Go into Configuration window (F2). Select the 'Extras' tab. The second toggle from the top right is for putting flip screen buttons on the command bar, or whatever you want to call it on the bottom left of your screen. Once that toggle is enabled, you can flip your screen using the new buttons on that bar.

Not sure that worked but in the help screen CTRL/SHIFT/H worked.

 

Thanks

Rodger Forsyth

Past President

Peterborough Astronomical Association (PAA)
