### ISSUE TITLE
Change buttons to make UI more intuitive

### ISSUE THREAD

**Issue by NotSoRandomOne** [Stellarium/stellarium#752]
When someone has time to do UI work (if you agree it could be improved), in the script edit window the 'Clear' button, the 'File Open' button, the SSC button, and even the stop script button all look like they are disabled. The File Save button looks enabled, and useful, but it is a little hard to tell what the others are because of the greyness used in the colors. If they used the same blues as the File Save button, the problem would be eliminated.

This may apply to other windows as well, but I haven't played with them as much.

**Comment by alex-w** [comment]
Possible will be fix by PR #804

**Comment by axd1967** [comment]
relates to #678 (problematic choice of UI color).

**Comment by alex-w** [comment]
> relates to #678 (problematic choice of UI color).

It’s NOT related to #678.

**Comment by alex-w** [comment]
Please check latest beta (v0.20.1.17945)
