### ISSUE TITLE
Small additions to AstroCalc (very non-urgent feature requests)

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#758]
I would like a few minor additions to the Ephemeris tab in AstroCalc:

- [x] 1. Connecting lines between the markers (of course customizable in color and switchable).
- [x] 2. Lower the minimum time step to 1 minute (currently 10 minutes).
- [x] 3. Perhaps customizable space between date/magnitude lables? E.g. "lable each N steps".

And also a "bug":
When an ephemeris marker is selected (highlighted), it seems impossible to deselect. At least I haven't found a way to do so. :)

**Comment by alex-w** [comment]
Please describe use cases for proposed items.

**Comment by Atque** [comment]
@alex-w 

1. Let's say I want to visualize a comet within a range of  a few years, and I also want to visualize the DSO's it might be passing during those years. Without connecting lines, it is sometimes difficult to tell the ephemeris markers and the DSO markers apart. 

The current path system is tiresome and even annoying, as it requires the user to run through all dates of interest. If it's a 2 year range, and you want day-by-day path, you must scroll through 730 dates... And it is very easy to mess up; and the path disappears if you accidentally select another Solar System object.

2. To see when e.g. the sun set over 1 minute intervals, to easier see at what azimuth it sets.

3. Let's take the comet example once again. It gets messy if I want to use lables, and at the same time use 1 day interval markers.

An addition to number 3: Being able to customize lables, to only show month, month+date, year or something. Currently we are locked with YYYY-MM-DD.

**Comment by gzotti** [comment]
To see the sunset curve (issue 2), it may be easier to use the "Current Sun" line of the ArchaeoLines plugin.

**Comment by Atque** [comment]
@gzotti fair enough, but I find other uses (for example plotting fast comets such as Hyakutake or Near-Earth asteroids).

And Alexander has already fixed that request, many thanks! :)

**Comment by Atque** [comment]
@alex-w It looks good. Connection between markers is what I had in mind when I created this feature request. But of course it would be nice to have a perfectly smooth line no matter how deep you zoom. I don't know how hard that would be to implement.

But would it be possible to hide the markers and just see the line? Because then, we could easily get a smooth line, by choosing to draw it for every hour or similar short timeframe. Now, the line drowns in marker symbols. :)

**Comment by gzotti** [comment]
Not as easy as you may think. The ephemeris is computed for some days or weeks with fixed interval. Zooming in would have to re-initiate creation of data which are then drawn on the fly. It may be possible to apply some spline interpolation scheme while drawing to make the curve smoother, though.

**Comment by Atque** [comment]
@gzotti I see. It seems a bit complicated. An option to hide the markers would be easier. For example show an ephemeris of Saturn from 1st May 2011 to 1st August 2011, by hours, hiding the markers, would result in a nearly perfectly smooth line.

**Comment by alex-w** [comment]
Just check latest changes ;)

**Comment by Atque** [comment]
@alex-w Looks really good now, thank you!

**Comment by alex-w** [comment]
> An addition to number 3: Being able to customize lables, to only show month, month+date, year or something. Currently we are locked with YYYY-MM-DD.

At the moment we use standard date format (as defined by user for whole Stellarium) for labels, but in some cases it may be not very good for show the data. Yes, we may introduce new one option (a dropdown list?) for define the date format of labels, but better way will be introducing euristic tool for formatting date for each labels. Should we follow the classic astronomical calendars and almanac for label?

@gzotti could you suggest something here?

**Comment by alex-w** [comment]
By formal properties this request already fixed and I've closed the bug.

**Comment by gzotti** [comment]
@alex-w on date/label format: Probably depending on interval, only mark one point per day with full day, the hour points with hours only, the first point per month with month number, or such, but this really should depend on the interval setting.
