### ISSUE TITLE
Ctrl-F doesn't seem to be reassignable

### ISSUE THREAD

**Issue by NotSoRandomOne** [Stellarium/stellarium#764]
If 'Ctrl + F' is removed from 'Find' in keyboard assignments, and reassigned to a script, restarting Stellarium undoes the removal from 'Find,' so the script isn't triggered. Nor does the Find window appear.

### System
* Stellarium version: 19.1.17157
* Operating system: Win10

**Comment by gzotti** [comment]
Indeed, setting secondary shortcuts to empty is not handled properly.
