### ISSUE TITLE
slew button on screen

### ISSUE THREAD

**Issue by lovelandco** [Stellarium/stellarium#765]
There should be a "slew" button on the screen. I use a tablet with my scope and don't want to carry a keyboard just to slew the scope (CTRL+1). Otherwise I can do just about anything else I need to do with the touch screen.

**Comment by alex-w** [comment]
OK, what you do not use standard GUI for control the telescope?

**Comment by gzotti** [comment]
The current system requirements also include a keyboard, and I could not think of operating the program without a handful of hotkeys. The touch interface could be improved and completed if somebody feels bothered by that? (Anybody wants to add a "touch buttonbar plugin" just for that? Exchange display screen space for 20 fat buttons? Or develop an entire new touch-friendly menu with fat buttons that can be pressed with average fingers? That's a major project.)

In any case, the regular telescope slew GUI is reachable by just a few button presses, therefore I set this to invalid.

**Comment by lovelandco** [comment]
My tablet allows me to scale the view (zoom), select objects (tap an
object), but I there is not a button to slew my scope.

I realize that for setup, configuration and searching I need the keyboard,
but as I'm viewing, I don't want to have to use the keyboard.

**Comment by gzotti** [comment]
A tablet does not fulfill the hardware requirements. That's a fact. Whether you can circumnavigate the shortcomings depends on your requirements. 
You have the telescope BUTTON in the lower button bar. This calls a GUI to connect a telescope. After connection, a GUI with a fat "Slew" BUTTON allows slewing. What exactly are you missing?
