### ISSUE TITLE
Stellarium crashes when rapidly deleting sensors from the sensor creation page

### ISSUE THREAD

**Issue by fullmetalcoding** [Stellarium/stellarium#767]
### Expected Behaviour
Sensor entries delete without crashing

### Actual Behaviour
Crash to desktop

### Steps to reproduce
Crash occurred when deleting several of the pre-installed sensors that came with Stellarium.
Press "Delete" button on sensor creation panel rapidly under the oculars configuration page. By the fourth or fifth press Stellarium will crash to desktop with no error.  Reproduced crash multiple times. On fourth successive try, did not observe crash. Likely race condition?

### System
* Stellarium version: 0.19.1 (stellarium-0.19.1-1-win64.exe)
* Operating system: Windows 10
* Graphics Card: nVidia GTX 1060 mobile

### Logfile 
Unavailable

**Comment by alex-w** [comment]
Please check the latest beta

**Comment by alex-w** [comment]
I've deleted all sensors without any problem (clean installation of Oculars pluign)

**Comment by alex-w** [comment]
@fullmetalcoding please check latest stable or beta versions

**Comment by alex-w** [comment]
Please attach your oculars.ini file (please rename it to oculars.txt to allow attachment)

**Comment by alex-w** [comment]
Any news?

**Comment by alex-w** [comment]
Could you check the latest beta (v0.20.1.17907) - I think we fix this issue already.

**Comment by alex-w** [comment]
@fullmetalcoding any feedback please

**Comment by gzotti** [comment]
I cannot reproduce a crash on Win10 (current master) either. However, deleting the last sensor zooms in to minFoV (?).
