### ISSUE TITLE
Suggestion: More Asterisms to Add

### ISSUE THREAD

**Issue by bobmeisterr** [Stellarium/stellarium#768]
Hi Georg and Alexander, and Colleagues,

As I previously discussed with Georg, please find below my suggestions for more asterisms to be added. I was able to get two good (official/professional/academic) references for all but one of them, with one good amateur reference and one official/professional/academic reference for the "V of Taurus".  However, I was unable to really find much information about the origins of the asterisms. The "V of Taurus" was recognized by all of the Mesopotamian cultures; as well as Egypt, Greece, and Rome. However, the others were more difficult.

Originally I only discussed "Job's Coffin" and "V of Taurus" with Georg, but since then I've found quite a few others. This is why the delay in my posting this issue. The only snags to all of this list are the asterisms: "Heavenly G", which overlaps horribly with the "Winter Hexagon"; and "Venus' Mirror", which overlaps horribly with "Orion's Belt" and "Orion's Sword". Slight snags include the "Milk Dipper", which makes up part of the "Tea Pot" in Sagittarius; and "Bier", which makes up part of the "Big Dipper", although that one is more clear due to the location of the asterism name. Otherwise, they all fit in great. So I don't know if it might be worth either creating two drop-down selections (and therefore .fabs) for asterisms; or somehow encoding different colored lines for overlapping asterisms, to discriminate them? What do you think?

It should be noted that all the references for these asterisms are American references (American universities, and an American astronomy society). I couldn't find any decent (official/professional/academic) references from other countries. So I don't know if this implies a regional/cultural/national bias (i.e. that these are American, or at least western English-speaking asterisms, some of them might be).

It should also be noted that the asterism "Triangulum Minus" is actually an obsolete constellation, and was created by the Polish astronomer, Johannes Hevelius. I remember seeing a discussion posted on sourceforge.net by another user mentioning a "Hevelius Skyculture" that they were in the midst of creating. So if they finish that skyculture, "Triangulum Minus" might be better added to that .fab, rather than asterisms. Although, I've not seen any update on that discussion. So maybe an "obsolete constellations" skyculture might be a good idea? (maybe called "Western (Hevelius)" or "Western (Obsolete)"?) What do you think?

Hevelius Skyculture discussion:
https://sourceforge.net/p/stellarium/discussion/278769/thread/cd32110e/

I've also added a coupe of alternate names for Asterisms here and there, and also made some added line suggestions for one asterism.

Please find all the details below, and also I've attached a zip file including the updated asterism_names.eng.fab, asterism_lines.fab, and reference.fab - all updated with these new details.

Asterisms Added (abbreviations, names, and reference numbers):

JbC	_("Job's Coffin","asterism")	23, 25
VTa	_("V of Taurus","asterism")	27, 28
TrM	_("Triangulum Minus","asterism")	24, 26
Fly	_("Northern Fly","asterism")	23, 25
Mlk	_("Milk Dipper","asterism")	23, 25
Bier	_("Bier","asterism")	23
BoP	_("Bull of Poniatowski","asterism")	23
GoP	_("Guardians of the Pole (Guards)","asterism")	23, 25
HeG	_("Heavenly G","asterism")	23, 25
SoP	_("Segment of Perseus","asterism")	23
VeM _("Venus' Mirror","asterism")	23, 25

Asterism Lines:

JbC 1 4  102532 101958 101958 101769 101769 102281 102281 102532
VTa 1 5  21421 20894 20894 20205 20205 20455 20455 20648 20648 20889
TrM 1 3  11486 10793 10793 10280 10280 11486
Fly 1 3  13209 13061 13061 12719 12719 13209
Mlk 1 5 92041 92855 92855 93864 93864 93506 93506 92041 92041 90496
Bier 1 4  54061 53910 53910 58001 58001 59774 59774 54061
BoP 1 3  88149 88192 88192 88290 88192 88601
GoP 1 1  72607 75097
HeG 1 8  21421 24608 24608 36850 36850 37826 37826 37279 37279 32349 32349 24436 24436 25336 25336 27989
SoP 1 5  13268 14328 14328 15863 15863 17358 17358 18532 18532 18246
VeM 1 7  26727 26311 26311 25930 25930 25281 25281 26237 26237 26727	 26237 26221 26221 26241

Alternate Names added to existing asterisms:

BA2	_("Honores Friderici (Frederick's Glory)","asterism")
Urn	_("The Y in Aquarius (The Urn or Water Jar)","asterism")
Goa	_("Goatlings (Kids)","asterism")
HDr	_("Dragon Head (Lozenge)","asterism")

Lines added to existing asterisms:

116584 to 117221 (on Honores Friderici/Frederick's Glory):
BA2 1 4  116805 116584 116584 117221 117221 116805 116805 116631

References:

(all, except V of Taurus and Triangulum Minus):
23) University of Northern Iowa: https://sites.uni.edu/morgans/astro/asterisms.html

(Job's Coffin, Northern Fly, Milk Dipper, Guardians of the Pole (Guards), Heavenly G, Venus' Mirror):
25) A Field Guide to the Stars and Planets BY DONALD H. MENZEL, Director, Harvard College Observatory
COLLINS, ST. JAMES'S PLACE, LONDON
http://www.arvindguptatoys.com/arvindgupta/menzel-fieldguide.pdf

Triangulum Minus:
24) Michigan State University: https://web.pa.msu.edu/people/horvatin/Astronomy_Facts/obsolete_pages/triangulum_minor.htm
26) University of Illinois: http://stars.astro.illinois.edu/sow/6tri.html

V of Taurus:
27) Astronomy Club of Tulsa: http://www.astrotulsa.com/cms_files/200812.pdf
28) Bayer University: http://cs.baylor.edu/~hamerly/personal/astro/log.html

Attached files:
[Asterism fabs.zip](https://github.com/Stellarium/stellarium/files/3634521/Asterism.fabs.zip)

Please let me know what you think!

Thank you all :).

**Comment by gzotti** [comment]
Thanks for your work, these are some interesting finds.
We should indeed discern obsolete constellations (Taurus Pon.,  Antinoos, Tri. Minor, Cat, Balloon, Honor Fred. ...)  from currently observed asterisms. Not this week, but we are collecting ideas about further developments around skycultures.

**Comment by axd1967** [comment]
Shouldn't this be Antinous or Antino**ö**s ?

https://github.com/Stellarium/stellarium/blob/dce328a279e3ff3e406630e3afde61109e3204f9/skycultures/almagest/constellation_names.eng.fab#L16

https://en.wikipedia.org/wiki/Antinous
