### ISSUE TITLE
Update Python scripts to Python 3

### ISSUE THREAD

**Issue by IceflowRE** [Stellarium/stellarium#77]
Are there any plans?

I would be interested in it.

**Comment by gzotti** [comment]
Is there a benefit? Added value?

**Comment by IceflowRE** [comment]
Ehhh
Just to cite the python wiki should be enough.
> Short version: Python 2.x is legacy, Python 3.x is the present and future of the language

**Comment by alex-w** [comment]
Apparently the time to switch to use python3 due EOL python2. Could you prepare patches for python code?

**Comment by IceflowRE** [comment]
Are there any tests or how can i prove that the code still works as expected?

**Comment by IceflowRE** [comment]
And which python3 version should be targeted? E.g. `pathlib` was added to python 3.4, and i would like to use it at least. As it makes any file operation much easier.

**Comment by alex-w** [comment]
No special tests for python code (all this code we use as an additional tools) and no special preferences to version of python3.
