### ISSUE TITLE
Cant open safely from Mac since is not from an authorized developer.

### ISSUE THREAD

**Issue by CMonteroMarino** [Stellarium/stellarium#770]
macOS reports this is not possibly to open safely because comes from an unauthorized developer. Which made us hard run the app.

### Expected Behaviour
Just open when requested

### Actual Behaviour
Requests for further permission to open the app.

![Captura de Pantalla 2019-09-22 a la(s) 22 00 43](https://user-images.githubusercontent.com/55678785/65401392-0c675c00-dd85-11e9-8709-0436c65e26f4.png)

### Steps to reproduce
Download
Open file
Open App
Approve for continue

### System
* Stellarium version: <Stellarium-0.19.1.dmg>
* Operating system: <macOS Mojave - 10.14.6>
* Graphics Card: <Intel HD Graphics 5000 1536 MB>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Yes, both Windows and Mac emit a warning because we have not bought some certificate.
https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#unsigned-installer-dangerous-to-download-malware  
Does this happen at every launch now, or just once after installation?

**Comment by CMonteroMarino** [comment]
Yeap it happens every time I open it, the first time i had to "forced" open it, but now it just warns me every time that the app i want to open is not safe. 

If I click that box, i will stop warning me about this safe tip, but will do it for every app that is not safe, not only Stellarium. I obviously trust Stellarium, but I wont click because of any other not authorized app. I don't bother to accept it every time tho.

**Comment by gzotti** [comment]
Does "... en esta imagen..." not mean "in this [disc] image"? I would expect that this only affects the Stellarium folder and its executable contents. I have no Mac to test this assumption, though. But I would expect tens of thousands of complaints from other Mac users, or at least a generally bad reputation in various fora, if every Mac installation had this issue.

**Comment by chrleon** [comment]
> Yeap it happens every time I open it, the first time i had to "forced" open it, but now it just warns me every time that the app i want to open is not safe.
> 
> If I click that box, i will stop warning me about this safe tip, but will do it for every app that is not safe, not only Stellarium. I obviously trust Stellarium, but I wont click because of any other not authorized app. I don't bother to accept it every time tho.

Hello, if you click that button, you allow ONLY Stellarium to start. Other apps will still ask. @CMonteroMarino

**Comment by gzotti** [comment]
Thank you @chrleon , this confirms my assumption and hope that this is still handled in a sane way.  This being FAQ, we can close it.
