### ISSUE TITLE
Stellarium v0.19.1 on Windows10 does not open anymore, blocks computer and cannot make anything anymore with this excellent programm, after installing AMD catalyst center and upgrading my RAM to 8GB. Tried several times reinstalling Stellarium and unistalled catalyst control center. Microsoft edge explorer does not permit downloading stellarium v0.19.1! Please help, what happened here? Currently running stellarium 0.18.2 which I found on the web. Is working slow and not as good as stellarium v0.19.1 before.

### ISSUE THREAD

**Issue by Pitufito** [Stellarium/stellarium#772]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by Pitufito** [comment]
Ok, I`ve been capable now by downloading and reinstalling Stellarium v0.19.1 again on my Laptop, its working but way to slow as before. 

[New Text Document.txt](https://github.com/Stellarium/stellarium/files/3644355/New.Text.Document.txt)

**Comment by gzotti** [comment]
Don't panic. What does "slow" mean? The logfile you sent indicates OpenGL 4.6, seems the GPU drivers are working well. Do other graphics-heavy programs (games, simulations, ...) work?

**Comment by Pitufito** [comment]
Yes, they work like usuall, no problem. Lightroom, Deepskystakker, Autostakkert, Fitswork, and iTunes reproducing Cinemafilms are working good, what I`ve been using so far. 
Slow means, the reponse of Stellarium is rather slow to configure back the program like I used to have it on my PC. Also to quit the program is very slow. Using Stellarium to choose my targets and find Starnames, as measuring distances, finding satelite information and more very usefull functions are straight forward.

**Comment by gzotti** [comment]
It's quite hard to guess how you configured Stellarium "like you used to have it on your PC". Also, "response ... slow to configure" is unclear. If you tick a GUI checkbox, is there a delay, or how can we understand this? Where is the slow response?

If you have stored your favorite settings some time ago, say, in a config.ini from around version 0.14 or later, this should work equally well.  

Note that startup/stop may also depend on the number of installed landscapes or planets.

**Comment by Pitufito** [comment]
Thank you for responding and your effort to help me. 
I think is all about that slower working now, but not excessive, due to the upgrade of my RAM, and that I got my 2 screens color perfiled under Catalyst Control Center. (Normally I use X-rite Color monkey which I cannot use for now, which is more accurate and does not interfere madly with other programs like Stellarium).
I will check what is about the GUI checkbox, sorry I got not much idea what it is. Will have to learn a lot of things... . 
I`m pretty new into Stellarium, I`ve  been using so far SkySafari latest edition on iPad, which I like very much. Stellarium very very good and it helps me a lot parallel to my mount.
I`m so happy now that Stellarium works back again on my portable laptop, which is nearly strictly reserved for astronomy.
Thank you one more time.

**Comment by gzotti** [comment]
It is still not clear in what respect Stellarium "now" appears to be slower than "before" at least as long as "before" is undefined (in terms of version number, release date or similar). If you are in general happy with the program, please close this issue, or else describe the problem so that it can be reproduced. Color monkey sounds like color calibration, this should not harm much. Catalyst should not harm but improve performance. Not sure if newer drivers would help? I say "should", but have no experience with C.M. and no experience without adrenalin drivers on my 1GHz AMD netbook on which I also have only a few fps, but I can live with it while driving my telescope.

**Comment by gzotti** [comment]
I assume @Pitufito is OK if I close this issue. As it seems now, we cannot do anything to make your computer faster. Else please re-open and describe more details.
