### ISSUE TITLE
Indirect telescope controll using Stellarium 0.19.1.1 and SynScan Pro

### ISSUE THREAD

**Issue by acentam** [Stellarium/stellarium#775]
### Expected Behaviour
Stellarium should connect to SynScan Pro 1.17.3 for Windows as a local server and indirectly control the telescope

### Actual Behaviour
The telescope plugin does not connect to the local sever to start the telescope. This configuration does work in Stellarium v0.17.0 with plugin v0.3.0 and SynScan Pro 1.17.3.

### Steps to reproduce
Install Stellarium 0.19.1.1. Configure the telescope plugin to connect to external software. Select the telescope and click connect in the telescope window.

### System
* Stellarium version: 0.9.1.1
* Operating system: Windows 10

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Double of #702

**Comment by acentam** [comment]
Yup, this is a duplicate, and I can confirm that the beta 0.19.1.1 works.
