### ISSUE TITLE
Better looking planet halos

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#781]
I have no idea how to make a pull request, but this is a tweak I made with the planet halos. I just messed with the numbers in the src/core/StelSkyDrawer.cpp and I think it better represents the visual different between bright planets. Look at this comparasion between Venus and Jupiter on March 11 2012:
Old
![stellarium-232](https://user-images.githubusercontent.com/37028368/65829506-af006d00-e2a6-11e9-8767-d5c95795cf37.png)

New
![stellarium-231](https://user-images.githubusercontent.com/37028368/65829514-bd4e8900-e2a6-11e9-84eb-178ef7897b9d.png)

I changed the lines 539 and 540 in the src/core/SteSkyDrawer.cpp.
```
	// TODO: Change drawing halo to more realistic view of stars and planets
	float tStart = 5.f; // Was 3.f: planet's halo is too dim
	float tStop = 10.f; // Was 6.f
	bool truncated=false;
```
Of course one can tweak these even further, but I think this looks much better.

**Comment by Atque** [comment]
Closing this, trying to make a pull request instead. Please ignore the values I posted earlier, they make halos ugly when you zoom in.

**Comment by ferreiradantas12** [comment]
@Atque hello
