### ISSUE TITLE
New Terminology and corrections of conjunctions for AstroCalc search funtions 

### ISSUE THREAD

**Issue by Ironman65** [Stellarium/stellarium#789]
It’s been quite awhile sense I posted anywhere. I’m formally known as Ironman on the old sorceforge forum. Here’s some new terminology that might be used to enhance AstroCalc’s boxes’ conjunctions and opposition searches in the phenomena area. For the inner planets Mercury and Venus. The terms used are Superior conjunction (the far side of the Sun) Greatest elongation East, Inferior conjunction (between Earth and Sun) Greatest elongation West; then back to Superior conjunction. For the outer or Superior planets Mars and beyond is Conjunction (far side of the Sun) Eastern quadrature, Opposition, Western quadrature; and then Conjunction again. I noticed the conjunction terminology is being used for both types of conjunctions for the inner planets which make it confusing! I guess that the Elongation and Quadrature points can be calculated just like the Conjunction and Opposition points as well.  I’ve been a Stellarium user sense Ver. 0.11.0 this program wins hands down in its class! This from an amateur Astronomer for 47 yrs. Thanks for all of you do.

**Comment by gzotti** [comment]
Yes, that terminology can be improved, I second that. Thanks for your input!

**Comment by alex-w** [comment]
Are you really need to know time of reaching of quadrature points? Where is the quadrature points are using in observational astronomy today?

**Comment by gzotti** [comment]
These are the moments near greatest phase angle (max. "side view"), and they (loosely) enclose the opposition loop.  Could be esp. nice for comparison of historic work, but also for modern observers. The planet standstill points (begin/end of retrograde motion) may even be more interesting, currently I miss the English names for these, though.

Currently you can click on an entry in the ephemeris list to set date and center on the planet. Clicking on an ephemeris marker in the sky to select the row in the table, set time and center planet would also be great (but not essential). Or "just" to select and show data for the marker (object name, date&time, magnitude) in the InfoString, without setting date&time.

**Comment by alex-w** [comment]
> These are the moments near greatest phase angle (max. "side view"), and they (loosely) enclose the opposition loop. Could be esp. nice for comparison of historic work, but also for modern observers. The planet standstill points (begin/end of retrograde motion) may even be more interesting, currently I miss the English names for these, though.

It's "Stationary Points" according to https://phys.libretexts.org/Bookshelves/Astronomy_and_Cosmology_TextMaps/Map%3A_Celestial_Mechanics_(Tatum)/8%3A_Planetary_Motions/8.4%3A_Direct_and_Retrograde_Motion%2C_and_Stationary_Points

**Comment by gzotti** [comment]
Ah yes. These would be fine to have! Maybe marked as "Stationary (begin retrograde)" / "Stationary (end retrograde)".

**Comment by alex-w** [comment]
Please check the new beta - https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by axd1967** [comment]
Note: quadrature is useful information as it gives an approximation when an object appears around midnight (true solar time, without taking refraction and inclination/latitude into account). Also, it is the moment that the shadows of the rings of Saturn have a maximum offset and can best be photographed.

**Comment by alex-w** [comment]
> Note: quadrature is useful information as it gives an approximation when an object appears around midnight (true solar time, without taking refraction and inclination/latitude into account). Also, it is the moment that the Saturn shadow has a maximum offset on its rings and can best be photographed.

This proposal should be filled as feature request, not as comment to closed task.
