### ISSUE TITLE
Planet names - polish translation

### ISSUE THREAD

**Issue by pawelszroeder** [Stellarium/stellarium#79]
Hi! I've noticed that in 0.17.0 all polish names of planets are now in english. In version 0.16.1 everything was ok.

**Comment by alex-w** [comment]
This is an effect of introducing context for planetary names (same English name for asteroid and moon may be different translation on Chinese language for example). All translations for planetary names should be revised by translators for checking correct of translations.

**Comment by gzotti** [comment]
No, it is not possible to retrieve the old translations because the new context requires creation of the contextualized translations.

**Comment by pawelszroeder** [comment]
Ok, so for now is better to use previous version :)
Where it is possible to help with translation?

**Comment by alex-w** [comment]
Esp. for Polish language: https://www.transifex.com/stellarium/stellarium/language/pl/
