### ISSUE TITLE
Rises and sets subtly depend on current time inside the same day

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#792]
I'm running Stellarium with location set to "Earth, Saint Petersburg, 11 m" and date 2019-10-09. When in the _Information_ tab of the _Configuration_ dialog I check _Rises, transits and sets_ option and then select the Sun, I see the following contradicting information:

* Current time 17:23:00 UTC+03:00 — Set 18h09m
* Current time 17:24:00 UTC+03:00 — Set 18h08m

That's one minute difference in indicated set time in the same day. When I watch actual sunset with Zero Horizon landscape chosen, I can see the top border of the solar disk disappear at 18:08:47.

Looks like the calculations of rise/set/transit times are imprecise at the scale of tens of seconds, and apparently they are not rounded correctly (truncated?).

**Comment by gzotti** [comment]
Have not looked into the current solution. A good algorithm is given by Meeus, Astronomical Algorithms, 1998.

**Comment by mabatko** [comment]
This sounds similar to https://github.com/Stellarium/stellarium/issues/554

**Comment by kajaji** [comment]
This issue is still there in the latest beta.
