### ISSUE TITLE
Toolbar icons consistency

### ISSUE THREAD

**Issue by martinber** [Stellarium/stellarium#793]
Problem
----------

Hi, a minor thing that bothers me is that some icons are not consistent in style with the others. I really like the icons and I think that the shapes are consistent, but there are some buttons with subtle differences on color and shadow

![icons](https://user-images.githubusercontent.com/6921727/66527888-194db480-ead4-11e9-8a16-f731adb7e5fc.png)

In the image you can see that the AstroCalc icon when disabled is slightly brighter that the others, also when selected it does not have a glow. Icons on the oculars bar are not bright enough when selected, specially the sensor one (the rectangle). Finally on the bottom bar some icons do not glow when selected.

Questions
-----------

I wanted to fix it myself. I was going to adjust the brightness and add blut to some icons manually using GIMP, but I wanted to ask first if there is some vector graphics or high resolution available. Do you think it would be OK to redraw the icons on Inkscape and then generate the PNGs?

**Comment by gzotti** [comment]
Thanks for the offer to do it yourself. Indeed, some icons have no glow in their active state. The icons are in the source directory, and I am not aware of hi-res or vector versions. You could get the sources via git and fix those icons, then make a Pull Request. Please, in this effort, check all plugins.

**Comment by alex-w** [comment]
Good start!
