### ISSUE TITLE
Please, Reduce the Glare of Stars as an Option 

### ISSUE THREAD

**Issue by Shavarshk** [Stellarium/stellarium#794]
During the observation sessions I noticed how difficult it was  to make comparison of the observable star patterns with the stellarium images. At present I think  that much of the problem is due to the glare of the stars possibly depicted in order to be present the maximum of realism as well as for visual appeal. However, this greatly downgrades the practical side of observations and reduces clarity and depth.  

I suggest that there should be an option to turn off the stars glare and leave only spectral data of the observable stars when we visually compare the information which is observed in the sky with the information on the screen with the planetarium. In this suggested option, stars might still be presented according to their relative sizes and all other related information including the spectral information can also be available. 

This option should help to make correct assessment of the star observable patterns and those seen in Stellarium. May I request to consider enabling this option in the next version(s)?

Best regards,

**Comment by alex-w** [comment]
Please use absolute and relative scales for stars to set perfect look of sky for you.

**Comment by gzotti** [comment]
@Shavarshk Do these instructions solve your problem?

**Comment by gzotti** [comment]
We take no answer as "yes".
