### ISSUE TITLE
color picker not visible in fullscreen mode (19.2 Windows)

### ISSUE THREAD

**Issue by dts350z** [Stellarium/stellarium#795]
The color picker dialog for sky markings is not visible when I'm in full screen mode (4K monitor).

Calling dialog is grayed out so I'm stuck. 

If I press esc, the color picker flashes up and then closes and the calling dialog stops being grayed out.

In window mode (vs. full screen) everything seems normal.

**Comment by gzotti** [comment]
Is this https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#some-system-dialogs-colors-screenshot-dir-hidden  ?

Why don't you fill in the issue template, esp. the part on your hardware?

**Comment by dts350z** [comment]
Where can I find the issue template?

This is on Windows 10 Pro 10.0.18362
i7-8700K
32GB Ram
Nvidia GeForce GTX 1070 Driver Version 25.21.14.2600
Display is 3840 x 2160 x 60 Hz 32 bits per pixel

I can try updating the video driver, but the one I currently have was
specifically for CUDA vs. game play, etc.

**Comment by dts350z** [comment]
Switching to the latest GEForce driver, 436.48 released Oct 1, the behavior
is the same.

Windowed mode, even maximized, is OK. Full screen mode has the problem.

Yes Alt+Tab does work.

Screen shot directory change dialog is OK, however.

**Comment by gzotti** [comment]
I don't know how you started your issue report. When you click on "New Issue", you will see instructions how to report. Apparently there are other ways to report which circumnavigate this intended process, but I don't know how you get there and avoid seeing the template. 

Strange that a Geforce 1070 with latest drivers has this issue. But we apparently cannot do anything about it. The FAQ says what we have observed, on some systems there are no problems, on yours you have to live with it, or use ANGLE mode.
