### ISSUE TITLE
Print feature for Bookmark and Tabbed Interface

### ISSUE THREAD

**Issue by Shavarshk** [Stellarium/stellarium#803]
1. Is it possible to include the function of "Print the bookmark"? It is useful to have it on paper.
2. Also I suggest that the bookmarks should be arranged in tabbed interface somewhat similar to browsers but arranged according to the log time and date or sequential order. 

Thank you for considering.

**Comment by alex-w** [comment]
Please explain second sentence - I do not understand why you need many tabs.

**Comment by Shavarshk** [comment]
The tabs are needed for different sessions of observations or/and grouping data into different object types.  This is also useful when it will be necessary to print out as a reminder for info about the given planned session.

**Comment by alex-w** [comment]
It's not bookmarks, it's observing lists

**Comment by Shavarshk** [comment]
It may still be helpful to plan different sessions of the objects on different dates. Why can we not to extend the bookmark into observing lists too?

**Comment by Jocelyn1109** [comment]
@Shavarshk 
Hi,
new features have been developed but not yet released: those are the multiple bookmarks lists and the sort for bookmarks by column.
In the bookmarks window we can now create severals lists of bookmarks with custom name list.

Maybe these new features are what you want. We could add a csv export instead of printing.

**Comment by Shavarshk** [comment]
Hi,
Thank you. what you says seems to be what I had requested. Thank you for the good news. Thank you for the improvement. 
Best regards,
Shavarsh

**Comment by Jocelyn1109** [comment]
@Shavarshk thanks ;)

**Comment by gzotti** [comment]
Just an update of the current state or where this may lead to: 
- no tabs, but we have multiple lists now
- Currently a list can be exported to JSON. Exporting to CSV or XLS seems possible but has no hurry

**Comment by Shavarshk** [comment]
Dear Georg,


This is very kind to inform me. I must say that it is now the second 
version that I can not use Stellarium . It states as usual that no QT 
plugin could be initialized. It is not possible to make use of the 
software starting from the version 1.

Happy New Year!

Best regards,

Shavarsh

**Comment by gzotti** [comment]
You could report an issue, with a logfile revealing details about your system. If this is an older model, maybe a Qt5-based build works for you.

**Comment by gzotti** [comment]
This is hugely outdated. Bookmarks have been replaced by Observing Lists. 

We have still no plans to print lists on paper currently. The list can be exported to JSON format which can be converted with external tools.
