### ISSUE TITLE
coordonnée du royal laboratory grenwich

### ISSUE THREAD

**Issue by TOUBIB33** [Stellarium/stellarium#808]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by TOUBIB33** [comment]
La longitude de greenwich est  0,000532° soit 0°01.92" et non pas 0° 05,32" ce qui est indiqué dans la base des sites. j'espere que ce n'est qu'une erreur de frappe, et qu'il y n'a pas de concequence dans les calculs !
Cela dit , je trouve des differences entre les coordonnées de stellarium et celle de http://f1rzv.free.fr/calculs/AstroCalc.php
Position local 47°230327 (47°13m49.18s) / -2.166430 (-2°9m59.15s)
calcul fait le 18 /10 /2019 a 21H00 soit 19H00 TU
selon F1RVU 
 TS à 0hTH =1h44m44s à greenwich
 TS à 19hTU =20h47m54s à geenwich
 TS local =20h39m14s
 T solaire moyen =18h51m20s
ALTAIR
 AD/DEC= 19°50'59.62"/ 08°52'46.7"
 angle horaire = 0°48m30s
 AZ/HA =198.9554°/ 50.28729°
M31
 AD/DEC= 0°42'56.26"/ 41°17'25.3"
 angle horaire = 19°56m33s
 AZ/HA =74.70286° / 47.12667°

selon STELLARIUM (0.19.1)
   TS local =20h39m15.3s
ALTAIR
 AD/DEC= 297.94170°/ 08.9232° soit 297°56'30.12" / 08°55'23.52'
 AZ/HA =198.5800°/ 50.3863°
M31
 AD/DEC= 10.96196° / 41.3789° soit 10°57'43.056' / 41°22'44.04"
 AZ/HA =74.4314° / 46.9788°

**Comment by axd1967** [comment]
according to Google maps (...), this is the approx. position of the Greenwich Prime Meridian:

51°28'40.6"N 0°00'05.3"W

when selecting Greenwich in Stellarium, one indeed gets this:

![image](https://user-images.githubusercontent.com/3529789/71563621-0f17d280-2a93-11ea-89c9-789b8aed2d94.png)

which longitude corresponds to the IERS ref meridian:

https://en.wikipedia.org/wiki/IERS_Reference_Meridian

(so it looks like the OP made a mistake in the coordinates of Greenwich)

**Comment by gzotti** [comment]
... which may be the reason OP closed the issue months ago.

**Comment by TOUBIB33** [comment]
Thank you for your answer,

That is confirm my opinion

 

 

 

De : alex [mailto:notifications@github.com] 
Envoyé : dimanche 29 décembre 2019 23:38
À : Stellarium/stellarium
Cc : TOUBIB33; State change
Objet : Re: [Stellarium/stellarium] coordonnée du royal laboratory grenwich (#808)

 

according to Google maps (...), this is the approx. position of the Greenwich Prime Meridian:

51°28'40.6"N 0°00'05.3"W

when selecting Greenwich in Stellarium, one indeed gets this:

 <https://user-images.githubusercontent.com/3529789/71563621-0f17d280-2a93-11ea-89c9-789b8aed2d94.png> Image supprimée par l'expéditeur. image

which longitude corresponds to the IERS ref meridian:

https://en.wikipedia.org/wiki/IERS_Reference_Meridian

(so it looks like the OP made a mistake in the coordinates of Greenwich)
