### ISSUE TITLE
Helix Nebula in the location reported incorrectly 

### ISSUE THREAD

**Issue by worrallt** [Stellarium/stellarium#820]
Notice Stellarium shows Helix Nebula crossing the meridian , yet mount shows one hour to flip. checked location of the Helix with CDC and could see it reported correctly 1 hour before flip. Im on 0.19.1

**Comment by gzotti** [comment]
The Helix nebula is where it should be. You are obviously having something wrong in your setup, but without a proper report that would allow error reproduction we cannot do anything. 
https://github.com/Stellarium/stellarium/wiki/FAQ#reporting-a-crash
