### ISSUE TITLE
Some equatorial grid lines are distorted

### ISSUE THREAD

**Issue by ericschdt** [Stellarium/stellarium#826]
### Actual Behaviour

The equitorial grid lines (around -30° only) in the lower left and lower right area are distorted:

![Screenshot_20191031_174418](https://user-images.githubusercontent.com/43318127/67968105-b1841880-fbfe-11e9-9b97-3682e663e449.png)

The azimuthal grid lines are fine.

### Steps to reproduce

I did nothing specifically.

### System
* Stellarium version:  0.19.2 (Manjaro/Arch linux packages)
* Operating system: 
```
Operating System: Manjaro Linux 
Qt Version: 5.13.1
```
* Graphics Card: 
```
Graphics:  Device-1: Intel HD Graphics 620 driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.5 driver: intel unloaded: modesetting resolution: 2560x1440~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 620 (Kaby Lake GT2) v: 4.5 Mesa 19.2.2 
```
* System scaling: 1.5

**Comment by alex-w** [comment]
This is not a bug - it's visualization of refraction affect. Please disable atmosphere for comparison.

**Comment by ericschdt** [comment]
Ah, I should have known it better. Thanks.
