### ISSUE TITLE
Stellarium window scales wrong when entering night mode with fractional scaling 

### ISSUE THREAD

**Issue by ericschdt** [Stellarium/stellarium#827]
### Actual Behaviour

When opened with fractional scaling (like 1.5), Stellarium runs fine until the night mode becomes enabled. In this case the window shrinks to the lower left rectangle until Stellarium becomes restarted. 

![Screenshot_20191031_180301](https://user-images.githubusercontent.com/43318127/67990694-992bf200-fc2e-11e9-9d8b-589c3ae49481.png)

### Steps to reproduce

1) `export QT_SCALE_FACTOR=1.5 && /usr/bin/stellarium`
2) Turn on the night mode

### System
Operating System: Manjaro Linux 
Qt Version: 5.13.1
Graphics:  Device-1: Intel HD Graphics 620 driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.5 driver: intel unloaded: modesetting resolution: 2560

### Logfile 
[stellarium.log](https://github.com/Stellarium/stellarium/files/3796043/stellarium.log)

**Comment by alex-w** [comment]
Could you check scale factor 2?

P.S. Are you build Stellarium from source code?

**Comment by ericschdt** [comment]
> Could you check scale factor 2?
> 
With scale factor 2 it works fine.

> P.S. Are you build Stellarium from source code?

Nope, it's the arch linux package, but for debugging I may compile it for you.

**Comment by ericschdt** [comment]
I have cloned and compiled `Stellarium 0.19.2.950 [master]` (`853e2a14e7354119b431899cacb4e47088985216`): [stellarium_verbose.log](https://github.com/Stellarium/stellarium/files/3797654/stellarium_verbose.log)

There the issue is still valid.

**Comment by ericschdt** [comment]
Works! Thanks @alex-w !
