### ISSUE TITLE
Adjustable line thickness

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#828]
_This feature request from old bug tracker (original autor: Michael Reid)_

I use Stellarium in my lectures and I consistently run into the problem that, even in a fairly dark environment, my students can't see the various lines on the sky, such as the coordinate grids and the constellation lines. It would be enormously helpful to be able to adjust the thickness of these lines to make them more visible.

**Comment by axd1967** [comment]
this is related to #678

**Comment by alex-w** [comment]
No, it's not related to #678

**Comment by axd1967** [comment]
Sorry, but the issue is all about ergonomic problems resulting from a poor choice of colour:
> I consistently run into the problem that, even in a fairly dark environment, my students can't see the various lines on the sky

**Comment by gzotti** [comment]
The request was about line thickness, which has been solved.

If you are unhappy with the colors, please select different ones. It has never been easier - just click the color boxes.

**Comment by Johnnyboy183** [comment]
Where did the constellation line thickness option move? Using 0.19.3 and can't find where the constellation line thickness option went. It used to be in either the sky options, or the markings options, but now it appears to have disappeared altogether.
