### ISSUE TITLE
Missing parts which require HiDPI support

### ISSUE THREAD

**Issue by ericschdt** [Stellarium/stellarium#830]
Just in order to track these issues.

(best to view in original size)

**Pixelated**, i.e. those **low resolution PNGs** should probably be replaced by SVGs:
![arrows](https://user-images.githubusercontent.com/43318127/68031076-c7531580-fcb2-11e9-84cf-fea2bf130512.png)
![checkbox](https://user-images.githubusercontent.com/43318127/68031077-c7531580-fcb2-11e9-8c3b-250e1332cf31.png)
![Screenshot_20191101_152319](https://user-images.githubusercontent.com/43318127/68031256-303a8d80-fcb3-11e9-99fc-e571c2a470fe.png)
![Screenshot_20191101_152410](https://user-images.githubusercontent.com/43318127/68031328-5b24e180-fcb3-11e9-9d4e-470fce0a941b.png)
![map](https://user-images.githubusercontent.com/43318127/68031775-3b41ed80-fcb4-11e9-84bd-e6d95574df7f.png)
![graph](https://user-images.githubusercontent.com/43318127/68032159-05513900-fcb5-11e9-9924-355738fc540d.png)
![calendar](https://user-images.githubusercontent.com/43318127/68032496-ba83f100-fcb5-11e9-8eb5-07081e764d0a.png)
![exit](https://user-images.githubusercontent.com/43318127/68032843-662d4100-fcb6-11e9-8a8a-af18fc791234.png)
![mech](https://user-images.githubusercontent.com/43318127/68032844-662d4100-fcb6-11e9-9ded-d5f2f53d2974.png)
![controls](https://user-images.githubusercontent.com/43318127/68033080-ebb0f100-fcb6-11e9-9b40-41af1084dfee.png)
![lenstele](https://user-images.githubusercontent.com/43318127/68033419-8a3d5200-fcb7-11e9-8038-69e2c1f54a9a.png)
![menu2](https://user-images.githubusercontent.com/43318127/68033746-3f700a00-fcb8-11e9-92cb-7a0acb57caaf.png)

**Misplaced**:
![rec](https://user-images.githubusercontent.com/43318127/68033502-b6f16980-fcb7-11e9-935c-cc7cc335d34a.png)

**When scrolling (not always reproducible)**
![when_scrolling3](https://user-images.githubusercontent.com/43318127/68033003-c02e0680-fcb6-11e9-8b70-13c74cabdce3.png)
![when_scrolling2](https://user-images.githubusercontent.com/43318127/68032846-688f9b00-fcb6-11e9-84c4-dd91489e53fe.png)

### Steps to reproduce

> export QT_SCALE_FACTOR=2.0 && ./src/stellarium

### System
* Stellarium version: Stellarium 0.19.2.950 [master] 
* Operating system: Manjaro KDE
* Graphics Card: driver i915

**Comment by alex-w** [comment]
Please check version 0.20.2.18210

**Comment by alex-w** [comment]
@henrysky @ericschdt @Atque @kajaji please try reproduce all issues from the report in version 0.20.3RC1

**Comment by kajaji** [comment]
For my screen resolution 3840 x 2160 and windows 10 default 250% scaling, best Stellarium scale is between --scale-gui 0.4 and --scale-gui 0.7. 
Stellarium 2.0 scale is not usable except with windows 100% scale.

No issues with oculars misplaced text or with scrolling. This issue was fixed since 18227.

One small issue with Ocular plugin is that the text when not using the On Screen control panel is not controllable 
by the font size.

![FontSze](https://user-images.githubusercontent.com/34771982/93378468-2be47800-f865-11ea-9d2d-ea85051e34ca.png)

**Comment by alex-w** [comment]
> One small issue with Ocular plugin is that the text when not using the On Screen control panel is not controllable
> by the font size.

You marked option to define font size for on-screen control panel text - in any way thanks for notification and I've updated the GUI of the Oculars plugin today.
