### ISSUE TITLE
Version 19.2 glitches

### ISSUE THREAD

**Issue by RF52** [Stellarium/stellarium#831]
I'd like to report some glitches associated with Stellarium 19.2

1. If you install 19.2 without uninstalling 18.2, but cause 19.2 to install in a different folder, (so that I could continue to use both), then what happens is that although apparently all the program files in the old 18.2 folder remain, but the application refuses to run. The splash screen announcing 18.2 appears for about a second and then the process aborts. However 19.2 runs OK. In add / remove programs, there is no longer the option to uninstall 18.2. I had to invoke the uninst.exe file from the 18.2 program folder.

2. Turning to the new version 19.2, the auto update star files does not work. It can be fixed using the workaround at https://sourceforge.net/p/stellarium/discussion/278769/thread/e0679ae8/ posting by "Austin". Clearly the 19.2 exe has not been corrected as this is an old posting.

3. Once (2) was sorted, I downloaded all the star files. I was doing some work on Mizar / Alcor and wanted the name of the star that sits "between them". When I clicked on the star, the designation popped up, but was only described as "star" - no catalogue name or number. I knew this was incorrect since on my free Android version of Stellarium, I had seen the cataloge number HD116798. When I put this number into the "search for star" box, the highlight remained on the selfsame star, but the data changed to the name Stella Ludoviciana. Thereafter clicking on a series of stars, the name Stella Ludoviciana would subsequently always be shown, BUT after a restart of Stellarium it returned to only giving the designation "star". Something seems not to be initialising correctly.

Hope that is useful?

Roger.

**Comment by gzotti** [comment]
1. Parallel installation is possible, but can cause trouble with data files that may have changed. You can create your own start link for the other versions with --user-dir option to set private user data directories. Likewise, the system uninstall only uninstalls the last installed version, but the uninstall link in the start menu is still available. 
2. fixed in several rounds at several times since 2016. The latest discussion was in #786, please try current beta. 
3. clicking on a star only shows what is stored in Stellarium's internal catalog. HD number is none of the data stored for dim stars. If you search for this designation, an online lookup will turn up this star and add names to the display. Admittedly, Stellar Ludoviciana should not be shown for other stars then.

**Comment by RF52** [comment]
Thanks for that Gzotti. Yours answers to (1) and (2) noted.

Re (3), I didn't make myself sufficiently clear, please substitute the following sentence:

Thereafter clicking on a series of **say three** stars, the name Stella Ludoviciana would subsequently always be shown **if the star clicked is the one in question**, BUT after a restart of Stellarium it returned to only giving the designation "star". 

Is there any way of forcing 19.2 to return a "fuller description" of a clicked star, without having to find it on Stellarium Free Android then doing a Google search for the Catalogue number returned by SFA?

R.

**Comment by gzotti** [comment]
No, data retrieved from Simbad (kept at runtime as "user defined object") are not stored to disk for retrieval in later runs.

**Comment by RF52** [comment]
OK, right. So what is the preferred method for getting the ID of a star from Stellarium? I'm having some conversations with a colleague and want to refer to stars by ID rather than by RA and Dec. Had I not managed to find this particular star's ID from "Stellarium Free Android", I cant see any way I could have found it. I apologise if I'm being a bit slow - but there's a linkage here that I can't grasp. I can SEE the star I want to discuss on Stellarium, but I cannot find an ID (name or catalogue number) for it.

Is there a search I can conduct online? I've looked for "find star name number from RA Dec coordinates" (without speech marks), but nothing useful comes up.

**Comment by gzotti** [comment]
There is no way I am aware of that would currently retrieve information about a star for which Stellarium has not stored an ID. 
Or, @alex-w is there already a "search online for more info about the currently selected object"? If Simbad allows a search by coordinates, it may be possible for stars.

**Comment by RF52** [comment]
Oh dear, I thought this would be a trivial question. And btw, I didn't mean to close the thread a while back, clicked the wrong button. I'll await further advice.

**Comment by alex-w** [comment]
@gzotti Nope, it’s not possible without deep refactoring the search tool

**Comment by RF52** [comment]
Thanks for all your support. I'm leaving brief details of my current "workaround" as it may benefit others:
BEGIN
In Stellarium, click on star of interest, info pane pops up in top left corner of screen.
CTRL SHFT C to copy info pane to clipboard.
Open new Notepad, CTRL V to paste info to Notepad.
Select and copy the J2000 RA/Dec data. Paste at end of Notepad document, strip out all characters except 01234567890.+- replacing them with spaces. Copy this edited string. (I have written an exe to do this.)
Open Simbad "simply query", paste in the string.
All data related to star becomes available including image, Name, Catalogue numbers etc.
END
Many thanks.

**Comment by gzotti** [comment]
I have added a simple query for "get all IDs for object at coordinates of selected object". This also works for custom markers set on dim DSOs in DSS or HiPS images. It currently only retrieves identifiers, the query could be enhanced with SIMBAD's scripting language.

**Comment by alex-w** [comment]
Georg, I think your tool for SIMBAD query shouldn't be on the first tab, because this new tool add messy in GUI and log.

**Comment by gzotti** [comment]
Sorry for the debug string.
I think that offering this for gaining more info is a benefit, and here on the first page is the best location. I changed now that the info is cleared when selection is changed, or when somebody types a query. 
Probably we can even query for more data from SIMBAD than just the catalog names. The query language is a bit uncommon. But I think it is too demanding to prettify the monospaced table output, so Courier font is all I can suggest to improve the output view.

**Comment by alex-w** [comment]
It’s may be strange,  but why you not implement the tool in separate tab? Or not as an additional for second tab - search coordinates?

**Comment by gzotti** [comment]
I think the usually empty area under the input field can serve dual-purpose: While searching for a string, results are displayed. When details are queried, the Simbad results are shown. IMHO this is more practical than adding another tab and leave the space empty most of the time.

**Comment by axd1967** [comment]
@gzotti @alex-w 

I was also wondering why SIMBAD seems to be automatically queried; I now notice this.

![image](https://user-images.githubusercontent.com/3529789/133979161-23d6ec38-29c8-4a66-b476-b15977a7ee90.png)

This is not logical:
1. I expect this message on the SIMBAD tab
2. I expect this behaviour only when on the SIMBAD tab
3. also, what is now the need to have a button in the SIMBAD tab as the query is done anyway?
4. if there really is a query (possibly with every keystroke)..., this is an unnecessary load for the SIMBAD servers

**Comment by gzotti** [comment]
One and a half year ago I added the functionality over the usual behaviour of an integrated (pass-through) SIMBAD name search, by adding an extra tab which queries additional information for "what's at the location of the selected object". This object can also be a custom marker when there is no star. E.g. when you see a dim galaxy in the DSS. Or something else in some HiPS image set. And you can still disable the auto-query of tab1 in the options tab.

**Comment by axd1967** [comment]
OK! because indeed it can be disabled - and then indeed it then all makes sense.

Wouldn't the option then better be labeled "Also use SIMBAD" (and the popup would read "include the on-line SIMBAD database when searching" ) rather than just "Use SIMBAD"? That one little word "Also" changes much.

Even better would be to add the option in the first tab, because it applies for that tab only; it's not a general option as far as I can see.
