### ISSUE TITLE
Wrong zooming in Telrad

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#832]
I've noticed a similar-sounding issue with the Telrad.  I've got version 0.19.2 on a Windows 10 PC.  My Oculars are set up to zoom without selecting an object.  If I select the Telrad icon right after launching Stellarium (because I want to orient myself and see where my virtual scope is pointed), my full-sky view zooms out to the maximum amount allowed (FOV 0.00139 degrees).  As a work-around, I can pick any part of the sky, select ocular (CTRL+O), de-select ocular (another CTRL+O, bringing me back out to FOV 60 degrees), and then select the Telrad.  After going in and out of ocular once, the Telrad toggles on and off normally (without zooming way out).
I tested and this behavior happens whether I have checked "Enable only if an object is selected" or not.

_Originally posted by @CharlesCowles in https://github.com/Stellarium/stellarium/issues/137#issuecomment-549669868_

**Comment by alex-w** [comment]
Hmm... it's strange, but I cannot reproduce issue on linux. @gzotti can you check it on windows?

**Comment by gzotti** [comment]
After starting, the first mouse click goes to the Telrad icon. Stellarium zooms in to 10 degrees FOV.
This is both with and without the option "Enable only if an object is selected".

I can then zoom in or out. Everytime on activation of the Telrad, the view zooms to 10°, which seems to be a pretty useful setting. I cannot confirm any issue here.

To not zoom, or zoom to some other FOV, an additional "[ ] zoom to... degrees" (boolean plus value) could be added.

**Comment by CharlesCowles** [comment]
[ocular.txt](https://github.com/Stellarium/stellarium/files/3828664/ocular.txt)

**Comment by alex-w** [comment]
Thanks for oculars.ini file - he help me found the source of issue
