### ISSUE TITLE
Solar Filter Mode

### ISSUE THREAD

**Issue by hvegar** [Stellarium/stellarium#833]
Hello there

I was using stallarium to make some analysis on how is going to be the position of the sun for the transit on November 11 but the sun is too bright on the screen and even when it shows the position of mercury is not possible to see with detail, It is possible to simulate a solar filter, to see this more clear?
Thanks in advance

**Comment by alex-w** [comment]
A zoomig?

**Comment by hvegar** [comment]
Nop, something like a light control, reduce the bright light of the sun

**Comment by gzotti** [comment]
Note that due to a few final astronomical details, simulation time for the Mercury transit is off by a few minutes. Please use some other source.

**Comment by hvegar** [comment]
I will see the transit with a telescope, but to give an explanation of the phenomenon this mode of operation may be usefull

**Comment by gzotti** [comment]
To see it like in a telescope, just zoom in. There is no solar filter mode in Stellarium, and when you zoom out to see the solar glare, Mercury is already too small to be visible. For "Analysis of the position", grids may help.

**Comment by hvegar** [comment]
Thats what I am asking for, If it is posible to simulate a solar filter !

**Comment by gzotti** [comment]
No, there is no particular solar filter mode in Stellarium. Zooming in acts as solar filter.

**Comment by hvegar** [comment]
Yes, you can see the transit but not when the planet is aproaching

**Comment by gzotti** [comment]
You also cannot see this in nature. To see that in the simulation, switch off atmosphere. And consider that the time is off by a few minutes.

**Comment by axd1967** [comment]
this could be solved with #1130

**Comment by gzotti** [comment]
It has also been solved with disabling solar glare in 0.21.0.

**Comment by axd1967** [comment]
this is 0.21:

![image](https://user-images.githubusercontent.com/3529789/117892772-9a28ef80-b2b9-11eb-880c-ae345ae77ba5.png)

toggling atmosphere or Sun glare does not bring out the planet.

a workaround is to remove magnitude limit, then we get this (zoomed in compared to previous shot):
![image](https://user-images.githubusercontent.com/3529789/117893014-f2f88800-b2b9-11eb-8a3e-763aa114e523.png)

(note that this workaround also works in 0.20, I'm not sure how 0.21 improves this?)

**Comment by gzotti** [comment]
OP asked to reduce the bright light. Now we can switch off the glare.
