### ISSUE TITLE
Improve reality adding cicada and wind sound

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#838]
_The feature request moved from old bugtracker._

Dear friends

for great improve reality of your program you should add sound of cicada and wind in the night

This is very easy to do and add new sensorial channel now not used: the sound

**Comment by 10110111** [comment]
Should it really be part of Stellarium? I guess starting a music player with a sample of these sounds looped would be good enough. It's not really something astronomy software should be concerned with.

**Comment by gzotti** [comment]
I totally agree with that.  It would be interesting to develop a real sonification of the universe rendered in Stellarium, though. 

BTW, you can play sounds with scripting. Or really use another program, to keep the scripting queue clean.

I think these sounds were available with some commercial program, which makes it even suspicious to just develop a copy of a non-astronomical feature.

@alex-w Solved 2015, or mark won't-fix?

**Comment by axd1967** [comment]
FYI - there is the AstroSounds project ongoing that intends to convert star data to sound for the benefit of citizens science: https://www.ewi-vlaanderen.be/oproep-citizen-science/astrosounds

https://en.wikipedia.org/wiki/Wanda_D%C3%ADaz-Merced
https://www.ted.com/speakers/wanda_diaz_merced
https://www.youtube.com/watch?v=-hY9QSdaReY

this could maybe somehow be connected in Stellarium , although I don't immediately see how.

**Comment by gzotti** [comment]
3D sonification can be developed in a plugin, but may be platform dependent. Expertise welcome.
But #463 is the better thread to continue on the topic.
