### ISSUE TITLE
state stack for scripting

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#839]
_The feature request moved from old bugtracker._

it would be useful to be able to save the current state of the system in the scripting language and then be able to return to it after a script has been completed.

this could be added as an explicit scripting language command (e.g. save and restore) and/or it could be added as a global option to return to pre-existing state after script finishes.

**Comment by alex-w** [comment]
The feature implemented as script commands but I think it should be revised and improved, because we do not touch this part of scripting engine a long time ago (and we introducing a many new features into scripting engine).

**Comment by gzotti** [comment]
A patch that updates the current script solution came with #849. 
A full solution might be able to interact with the StelPropertyManager and retrieve/restore all properties.

**Comment by alex-w** [comment]
Yes, a full solution (through StelPropertyManager) will be better here and I think we should automate it also - remember the map of properties before script running and restore that map after script stop running - without calling saveState()/restoreState() or something similar.

**Comment by alex-w** [comment]
No, I was wrong! In some cases automate of saving state and restore state are not needed (e.g. short scripts with shortkeys to switch to the  specific state).

I guess the current solution is acceptable and the issue should be closed.

**Comment by gzotti** [comment]
As often, the best solution is somewhere in between: Allow saving/retrieving named states as script commands (must communicate with StelPropertyMgr) to catch all for larger scripting projects, but yes, most scripts must be allowed state changes. The current solution should be OK for now.
