### ISSUE TITLE
lunar positions mismatch

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#84]
### Bug Description
There is a slight error in our ELP2000 lunar positions. I am pretty sure it has been here for years, only now we want to go into higher accuracy.

Compare photo and simulation from the same location. The star (at 2 o'clock in the photo) reappeared seconds before 04:52:12 where Stellarium has it reappearing more than a minute earlier. Camera time was corrected to NTP-adjusted PC, so cannot be more than 1-2sec off. DeltaT setting default near 69s.

Obviously related:
* Eclipse 2017 Bug https://bugs.launchpad.net/stellarium/+bug/1275092

Likely also related:
* Forum discussion https://sourceforge.net/p/stellarium/discussion/278769/thread/374439f7/#9c2b/5620/0694/19fe/9a9b/02a7/e123/e498/fe8b/fb2a

### Original report
https://bugs.launchpad.net/stellarium/+bug/1509659

**Comment by gzotti** [comment]
To be re-confirmed after implementation of aberration...

**Comment by gzotti** [comment]
![TLE20150928_reference](https://user-images.githubusercontent.com/18099873/124269257-f3cfcc80-db3a-11eb-80ae-ad46f7e7c3ed.jpg)
![stellarium-000](https://user-images.githubusercontent.com/18099873/124269334-0a762380-db3b-11eb-9335-53c644870c41.jpg)
Finally coming close!!!
