### ISSUE TITLE
FPS is too low.

### ISSUE THREAD

**Issue by ctq119** [Stellarium/stellarium#842]
### Expected Behaviour
        50 ~ 60 FPS
### Actual Behaviour
 Only 10fps ~ 20fps
![QQ图片20191110225044](https://user-images.githubusercontent.com/13543209/68546140-883d6680-040e-11ea-9741-493b50883660.png)
![QQ图片20191110225104](https://user-images.githubusercontent.com/13543209/68546142-8bd0ed80-040e-11ea-91ed-0163ede2ca34.png)

### System
* Stellarium version: Stellarium 0.19.2
* Operating system: Win10 x64 1903
* Graphics Card: CPU: AMD Ryzen 5 PRO 2500U w/Vega Mobile Gfx   GPU driver:Adrenalin 19.11.1

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/3828589/log.txt)

**Comment by gzotti** [comment]
Please see Appendix D.1.23 of the User Guide how to increase power consumption.
