### ISSUE TITLE
Atmosphere Model

### ISSUE THREAD

**Issue by ferreiradantas10** [Stellarium/stellarium#846]
i can implement a new atmosphere on github

**Comment by ferreiradantas10** [comment]
i need implement the new atmosphere for stellarium web on github or java and see on stellarium web i myself build the new atmosphere trying on github or javascript i like of stellarium web i can not download even i implementing on github editng files of stellarium

**Comment by alex-w** [comment]
Please do fork of stellarium web engine repository and do new model by yourself. Do not need spamming in various reports and various projects by messages "I can implement" and tons links to youtube. If you CAN implement new model, then DO fork and IMPLEMENT it without just messaging "I can implement it, I can implement it, I can implement it".
