### ISSUE TITLE
Oculars：crosshair point to north

### ISSUE THREAD

**Issue by sunshuwei** [Stellarium/stellarium#852]
Oculars overview：
“You can toggle a crosshair in the view. Ideally, I wanted this to be aligned to North. I've been unable to do so. So currently it aligns to the top of the screen.”

Now that there is a compass rose for oculars FOV,  does the crosshair still need to point to north?
Is it better to have a toggle button to switch up or north？

![2019-11-17_212735](https://user-images.githubusercontent.com/34102610/69008094-76fdd800-0981-11ea-8705-7ec8daa1f09f.png)

**Comment by axd1967** [comment]
@sunshuwei where does this compass rose appear?
