### ISSUE TITLE
HiDPI/Mac problem in Ocular plugin/Sensor Frame

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#853]
### Expected Behaviour

no text overlap

### Actual Behaviour

text overlap in oculars sensor frame

### Steps to reproduce

See https://sourceforge.net/p/stellarium/discussion/278769/thread/8e5b2fc5a6/?limit=25

Problem: HiDPI on Mac.

### System
* Stellarium version: 0.19.2
* Operating system: MacOS
* Graphics Card: N/A

### Logfile 

N/A

**Comment by gzotti** [comment]
Duplicate  of #830

**Comment by alex-w** [comment]
Fixed in a63d5a768f7b9189ed71d1f9a4c22b164751371e
