### ISSUE TITLE
Modified Rey starlore to support display of asterisms and ray helpers

### ISSUE THREAD

**Issue by rj1970** [Stellarium/stellarium#855]
The H.A. Rey starlore currently included with Stellarium (version 19.2)  does not display asterism lines and ray helpers. I have taken the Rey starlore files and modified them so all asterisms and ray helpers (either shown in the illustrations or mentioned in the text in the updated 2016 version of the book) can be displayed.

Asterisms:
- Big Dipper (chart 1 in the book)
- Virgin's Diamond (chart 3)
- Great Square (chart 6)
- Great Hexagon (chart 9)
- Serpent's tail (chart 12)
- Serpent's head (chart 12)
- Summer Triangle (chart 13)
- False Cross (chart 16)

Ray helpers:
- Big Dipper via Pole Star to Cepheus' cap (charts 1 & 2)
- Big Dipper via Pole Star, Cassiopeia, Great Square and Whale's snout to Phoenix' head (charts 2, 6 & 15)
- Big Dipper to Regulus (chart 3)
- Big Dipper to Arcturus and Spica (charts 4 & 11)
- Big Dipper to Deneb (chart 5)
- Great Square via Ram to Pleiades (chart 7)
- Big Dipper to Capella (chart 8)
- Big Dipper to Castor (chart 8)
- Sweep from Capella via Castor, Pollux and Procyon to Sirius (chart 8)
- Lion's feet to Hydra's head (chart 10)
- Altair via Goat's horn to Fomalhaut (chart 14)
- Great Square to Water Carrier's head (chart 14)
- Great Square to Fomalhaut (chart 14)
- Andromeda's foot via Ram to Fishes' knot (chart 15)

I would like to contribute the modified files to the Stellarium project.

Kind regards,
Ruud.
[western_rey.zip](https://github.com/Stellarium/stellarium/files/3875676/western_rey.zip)

Edit: two minor corrections
[western_rey.zip](https://github.com/Stellarium/stellarium/files/3879479/western_rey.zip)

**Comment by alex-w** [comment]
Thanks for patch!

**Comment by rj1970** [comment]
Hello Alexander,

Two of the Rey starlore files (the ones describing the asterisms and ray helpers) unfortunately did not get incuded in the 19.3 release. I hope you will be able to include them in the next one.

[western_rey_ asterisms_rayhelpers.zip](https://github.com/Stellarium/stellarium/files/3993179/western_rey_.asterisms_rayhelpers.zip)

Kind regards,
Ruud.

**Comment by alex-w** [comment]
Oops... It was bug in cmake script, sorry.

**Comment by rj1970** [comment]
Hello Alexander, thanks for your message – no problem!

Kind regards, Ruud.
