### ISSUE TITLE
Unable to script StelSkyCultureMgr module?

### ISSUE THREAD

**Issue by NotSoRandomOne** [Stellarium/stellarium#860]
### Expected Behaviour
StelSkyCultureMgr.getCurrentSkyCultureID(); should list the current sky culture in the output window

### Actual Behaviour
script error: "ReferenceError: Can't find variable: StelSkyCultureMgr" @ line 1

### Steps to reproduce
Run the single-line script in the F12 window

### System
* Stellarium version: 19.2

**Comment by gzotti** [comment]
StelSkyCultureMgr is not derived from StelModule, so it is not scriptable. 

There are skyculture related calls in the core scripting object a.k.a. StelMainScriptAPI.

**Comment by NotSoRandomOne** [comment]
Thanks. When there is time, maybe add that info to the docs, because there is nothing at https://stellarium.org/doc/0.19/classStelSkyCultureMgr.html to indicate this.

**Comment by gzotti** [comment]
Oh, indeed that's a doc error in the link list in https://stellarium.org/doc/0.19/scripting.html

**Comment by alex-w** [comment]
StelSkyCultureMgr is derived from QObject, so it can be scriptable,  but after register in scripting engine.

**Comment by alex-w** [comment]
It's strange, but I cannot register the StelSkyCultureMgr in scripting engine, but this is explain why skyculture stuff included in scripting core.

**Comment by gzotti** [comment]
It would be quite easy if we want or need it. (Not sure why it was excluded?)
- derive from StelModule
- implement update() (doing nothing)
- register to StelModuleMgr in StelApp::init()
