### ISSUE TITLE
Toggle moon

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#861]
**Is your feature request related to a problem? Please describe.**
In a large scale view, the Moon is represented as a fat dot independent of its actual illumination. This often gives the impression that the Moon will be clearly visible at the selected moment. One has to zoom in on the Moon or consult the info to find out the actual illumination. This issue is 
most prominent when having a New Moon.

![image](https://user-images.githubusercontent.com/3529789/69533694-91831300-0f78-11ea-90e3-aa5631a45e87.png)

Toggling the "Scale Moon" option provides some relief, but it is zoom scale dependent: when zooming out, the Moon becomes a fat dot again. If Moon Scale is enabled, when zooming out, one can see a transition from a real moon view to a fat dot.

![image](https://user-images.githubusercontent.com/3529789/69534171-8aa8d000-0f79-11ea-8462-3bd5a8856f6c.png)

**Describe the solution you'd like**
One or more of following

- a keyboard shortcut to toggle the "Scale Moon" option so that I can more easily judge the phase
![image](https://user-images.githubusercontent.com/3529789/69533487-32bd9980-0f78-11ea-9c28-4f65136e3bb2.png)
- replace the fat dot with the outline of the moon, or just a correct representation with the few pixels that would be available (this is probably a challenge: compute a disk with correct angular size, with a grey value that corresponds to the actual illumination )
- maybe allow to also define a constant diameter value (pixels) + toggle option rather than a scale, so that the moon is always "readable" independent of the magnification scale. The pixel size could even take the screen scale into account : when zooming in, the Moon scale switches over from a constant diameter size to a 1:1 scale once the disc has the same size as the actual Moon, and when zooming out, the size of the disc shrinks until hitting the minimum diameter size. (always IF the checkbox is set). 

**Describe alternatives you've considered**
Now I need to open the SSO view options dialog and play with toggle and scaling
It looks like the 20x scale seems to be a limit that give an approximate solution when viewing the entire sky.
![image](https://user-images.githubusercontent.com/3529789/69534788-c6906500-0f7a-11ea-92ec-1e99bb848479.png)

**Additional context**

**Comment by alex-w** [comment]
The shortcut for enable/disable scaling of the Moon you may assign by yourself - see "Enlarge Moon" item in Keyboard Shortcuts Editor (F7). Plus you may disable halo around Moon (add halo=false for the Moon in ssystem_major.ini file). Yes, the latest solution is temporary, because it will be reset to default value at the install a new version of planetarium.
