### ISSUE TITLE
Translation errors in Danish

### ISSUE THREAD

**Issue by JonDevDK** [Stellarium/stellarium#865]
In the Danish translation (0.19.2, Windows 64 bit version) the "primary" compass directions (N, S, Ø, V) are correct, but the "secondary" directions have wrong letters. It should be: NE -> NØ, NW -> NV, SW -> SV, SE -> SØ.

![image](https://user-images.githubusercontent.com/58291222/69793821-73602180-11c9-11ea-849d-1e95fe565779.png)

**Comment by gzotti** [comment]
Missing translations fall back to English. You can join the Danish translation team and fix also the other missing 26662 translations: https://www.transifex.com/stellarium/

**Comment by JonDevDK** [comment]
Thanks, I’d love to do that! However, after registering at the transifex site, the url https://www.transifex.com/stellarium/ returns 404 and I can’t find any Stellarium project by searching.

**Comment by gzotti** [comment]
Strange. Maybe forward to https://www.transifex.com/stellarium/stellarium/dashboard/

**Comment by JonDevDK** [comment]
Thx, that works 😊

________________________________
