### ISSUE TITLE
Mouse pointer  disappears (Windows 10)

### ISSUE THREAD

**Issue by Tchibeck** [Stellarium/stellarium#866]
When running Stellarium under Windows 10, if mouse parameter  "show pointer trails" is activated, the pointer cannot be seen in Stellarium, whatether is the form or size chosen for that pointer.

Killing the task "Stellarium" and uncheck mouse option "show pointer trails" solve the problem.

This is just for notification.

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#mouse-cursor-invisible

**Comment by Tchibeck** [comment]
Think you :-)

**Comment by Tchibeck** [comment]
Thank you :-)
Sorry not having read the FAQ
