### ISSUE TITLE
Importing bookmarks from spreadsheet list of items

### ISSUE THREAD

**Issue by NovemberOrionids** [Stellarium/stellarium#869]
Hi,

It would be interesting, I believe, to be able to import bookmarks from a spreadsheet list of items. I understand it is not possible. I understand the only way to import bookmarks is by using a JavaScript Object Notation file, which is impossible to many, including myself.

I suppose spreadsheet list might have required criteria to be easily readable by Stellarium (ex: column A = {catalogue name}; column B {catalogue number} and so on).

Do you plan to make such development?

Thank you

**Comment by gzotti** [comment]
I think JSON provides good support for correct data formats. A spreadsheet in itself has no clear type structure. What you want may best be solved by a Spreadsheet-->JSON export. Given at least 3 spreadsheet programs out there, a common format could be CSV, this could simplify the process into  
1. Export [WhateverSpreadSheet] -->CSV (presumably exists in all spreadsheet programs)
2. convert CSV --> JSON (To be done)
3. import JSON to Stellarium (exists)

Among the issues to be solved in (2) are the usual dot-versus-comma decimal separator issues found in international use. And of course to ensure the user provided a valid structure in the CSV.

**Comment by Jocelyn1109** [comment]
Hi, I worked on new bookmarks feature: the multiple list (https://github.com/Stellarium/stellarium/pull/854). 
Is it possible to have an exemple of a spreadsheet to get an idea of ​​what to do and how to do ?
Currently I learn to develop a CSV parser.

Thanks

Jocelyn

**Comment by gzotti** [comment]
See also #976

**Comment by gzotti** [comment]
We will not define yet another supported format.
