### ISSUE TITLE
Parallax accuracy for the stars

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#87]
### Bug Description
Hello,
I’m using Stellarium 0.12.0 for scientific works with university students. I find it’s a great software which gives good information on the characteristics of the stars.

But, I think that it’s possible to bring an important improvement on the accuracy of the parallax (the distance) of the stars :

1) In Stellarium, parallax is given based on the Hipparcos Catalogue I/239 from 1997.
Now, there is a new, more accurate catalogue : Hipparcos I/311 published in 2007.
Would it be possible to upgrade Stellarium with the last Hipparcos release ?

2) In addition, parallax is provided as a such, with no indication of the related absolute error. It may be technically possible to extract these data from the Hipparcos catalogue for an implementation within Stellarium. It would be very instructive to display the absolute error after each parallax.

For instance :
For HIP 110991 (delta Cep) :
Stellarium parallax (1997) : 3,32 msa.
Catalogue I/311 (2007) : parallax : 3,77 ± 0,16 msa.

For HIP 34088 (dzeta Gem) :
Stellarium parallax : 2,79 msa.
Catalogue I/311 (2007) : parallax : 2,37 ± 0,30 msa.

Hoping someone will add these new information for all the stars…

Best regards

### Original report
https://bugs.launchpad.net/stellarium/+bug/1382306

**Comment by insanetesterftw** [comment]
Perhaps I'm making a mistake but it seems that this two locations contain the files that you are looking for: http://cdsarc.u-strasbg.fr/ftp/cats/I/311/
http://cdsarc.u-strasbg.fr/viz-bin/Cat?I/311

Another program addressed this issue: https://www.ap-i.net/mantis/view.php?id=1158

**Comment by gzotti** [comment]
Instead of updating the old Hipparcos with the newer Hipparcos, consider replacing the catalogs with GAIA DR1 data: http://cdsarc.u-strasbg.fr/viz-bin/Cat?I/337

In the process, a long list of various issues will be solved automatically, or should be solved by thinking about new algorithms or handling of exceptional cases. Like 
 - https://bugs.launchpad.net/stellarium/+bug/648214
 - https://bugs.launchpad.net/stellarium/+bug/1271270
 - https://bugs.launchpad.net/stellarium/+bug/1299412
 - https://bugs.launchpad.net/stellarium/+bug/1756638
 - https://bugs.launchpad.net/stellarium/+bug/1657965
 - https://bugs.launchpad.net/stellarium/+bug/1195285
 - https://bugs.launchpad.net/stellarium/+bug/1195288
 - ...

**Comment by henrysky** [comment]
I have been working with Gaia data and have a local copy of the current DR2 in a server, perhaps I can help with getting Stellarium updated with the latest data.

What is the format of Stellarium data files, as I need to read and modify them with Python? If I have the format and can read it in Python I will try to play with it to see if I can help.

On top of that there is a few issues also need to be sorted out as Gaia does not has bright stars astrometric solution (so ending up a mix of Hippocos and Gaia data in Stellarium, will be confusing if not indicating data source?), Gaia parallax has a zero-point offset (should we correct it?), add parallax and proper motion to every available stars or do a 20% uncertainty cuts, etc?

**Comment by alex-w** [comment]
See Appendix C in Stellarium User Guide and code from https://github.com/Stellarium/stellarium/tree/master/util for details.

This is big task, because our star catalogs need to be updated and refactored - for example stars do not have parallax error and third component (tangent speed) for compute true proper motion.
