### ISSUE TITLE
Crash when selecting 0 in "Lable each N steps, where N is"

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#871]
There is a crash when you select 0 in the lables options in the Extra tabs of the Ephemeris tab in the AstroCalc. Scrolling through the numbers, going below 1 will result in Stellarium crashing.

0 shouldn't even be selectable, because how can you lable each 0 steps? :)

Screenshot of the menu I'm referring to:
![crash](https://user-images.githubusercontent.com/37028368/70361059-9f8e3900-1880-11ea-84cc-dcb2ceda9c59.PNG)

Steps to reproduce:
1. Generate an ephemeris
2. Go into the extra options
3. Under "Lable each N steps...", scroll down until you go below 1
4. The program crashes

**Comment by gzotti** [comment]
Indeed. Thanks for noticing!
