### ISSUE TITLE
AstroCalc Ephemeris Altitude/Time at culmination (suggestion for enhancement)

### ISSUE THREAD

**Issue by jnavasf** [Stellarium/stellarium#872]
Hello,

This is my first post here, I don't know if it is the right place. I am sorry, I can't code.

First of all, I would like to give you all a big THANK for your work and dedication. Stellarium is the wonderful program it is thanks to you all.

As you know, usually, the best moment to observe/photograph the planets or the moon is near their culmination, each day. The air mass is minimum at this point, the turbulence tends to be lower and the seeing better, for that day. 

Because of that, I think it would be very useful if the Ephemeris of AstroCalc would be enhanced adding the possibility of showing and calculating something similar to this (altitude vs time at culmination) for at least for Sun, Moon and planets, or Solar System objects, but at the chosen period of time:

http://efemeridesastronomicas.dyndns.org/xpre_culminacion_lunar.htm

The calculated table could be enough, but it could be even better if the Graph allows a chosen and extended period of time too. So, it could be predicted easily the best/worse years for oppositions, for example.

The table and graph should could be large enough for large periods of time.

Do you think it is an interesting feature? Would it be possible in the near future?

Thanks again.

**Comment by alex-w** [comment]
Are you tried use AstroCalc/Graphs/Graphs already?

**Comment by jnavasf** [comment]
Yes, but I need a table with data (more precise) and longer time (years). I
don't know if I missed the way to do this. I think it is not possible. Am I
wrong?

**Comment by alex-w** [comment]
Yes, it not possible at the moment. And, just for understanding, the table with altitude and time of culmination is not ephemeris table in classical definition.

**Comment by jnavasf** [comment]
Could it be possible to be easily implemented?

**Comment by jnavasf** [comment]
It may be useful to add the age (Moon) and phase (Moon, planets, asteroids...) too. :)

**Comment by gzotti** [comment]
Stellarium should be used as numerical reference data source only after the remaining accuracy issues have been solved, i.e. when Stellarium 1.0 has appeared. Until that, you should have a look into other sources.

**Comment by jnavasf** [comment]
Ok, thank you. I understand it.

Could you suggest where could I find what I am looking for?

**Comment by jnavasf** [comment]
Ok, thank you. I understand it.

Could you suggest where could I find what I am looking for?

**Comment by alex-w** [comment]
So, I can add the requested enhancement, but I think the many people will want to get list of altitude and time of culmination for deep-sky objects also.

**Comment by jnavasf** [comment]
Of course. It would be great! :D
