### ISSUE TITLE
Polaris

### ISSUE THREAD

**Issue by mr-otswons** [Stellarium/stellarium#875]
Hi,
I am new to Github and relatively new to Stellarium. I am wondering if Polaris should be seen as a double star (or triple)? I am seeing only one. Thank you.

**Comment by alex-w** [comment]
Polaris is spectroscopic binary with separation around 0.1 arcsec, so, any planetarium will show it as one star.

**Comment by mr-otswons** [comment]
Ok, I see. So why are there so many threads on various astroforums, such as Cloudy Nights, where people talk about splitting Polaris?
