### ISSUE TITLE
Lunar libration

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#877]
Lunar libration in latitude and longitude would be a neat addition to the infostring that shows when selecting the Moon. It could be useful for those who plan on viewing features close to the lunar limb, such as Mare Orientale and craters around the lunar north pole.

**Comment by gzotti** [comment]
I know, and I have started working on it months ago.  However, numbers will be shown only when the planet axes algorithms work correctly. It should obviously also be possible to show solar elevation for selected surface features, solar colongitude, and more such data.
