### ISSUE TITLE
No halo for sun (latest beta, 0.19.3 RC1)

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#879]
### Expected Behaviour
Sun halo shows.
### Actual Behaviour
No halo shown!
![stellarium-255](https://user-images.githubusercontent.com/37028368/70866110-b9f1a200-1f65-11ea-9857-ae6ca124ae0e.png)

### System
* Stellarium version: 0.19.2.17484, 0.19.3 RC1
* Operating system: Windows 10 64-bit, latest updates
* Graphics Card: GeForce GTX 1070, latest drivers (version 441.66)

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/3965187/log.txt)

The log and screenshot are from a fresh installation.

**Comment by gzotti** [comment]
Yes, I just noticed myself.
