### ISSUE TITLE
bookmark : choose not to go to dtg/location

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#882]
**Is your feature request related to a problem? Please describe.**
I want to slew to an bookmarked object without changing time and/or location

**Describe the solution you'd like**
when I press "Go To..." I would like that
* Time is updated to the bookmarked value (if present) when the dtg checkbox is set, otherwise time is not changed 
* location is updated to the bookmark value (if present) when the location checkox is set, otherwise location is not changed

**Describe alternatives you've considered**
* note the current time and location before clicking "Go to...", and/or
* highlight all bookmarks, _find the one I need_ and manually slew there

**Additional context**

**Comment by alex-w** [comment]
It's maybe strange, but if you do not want to get an automatic setting the time and location for bookmarks then why you just do not to add the bookmarks without specific time and location? Why you need extra 2 checkboxes for situation, when "problem" may be resolved without any additional tools?

**Comment by axd1967** [comment]
I don't ask two extra checkboxes, I propose to use the **existing** checkboxes for the same semantics, but **during the "go to" action** I want them to have a meaning too (because currently, they do nothing during a "go to" action).

in your view I would not be able to fully use the bookmark feature any more, because I would be prohibited from enabling time and/or location, just because later I might want to perform a "go to" without changing other parameters.

**Comment by axd1967** [comment]
@Jocelyn1109 this might also become obsolete with #976 .
the issue here was that the date/location checkboxes 

- are used to include date and/or location
- could be re-used when accessing a bookmark: by unselecting a checkbox, one can disable the jump in time and/or location. this is nice as it can allow to observe a bookmarked object from another location and/or another date/time

**Comment by axd1967** [comment]
@Jocelyn1109 did you read my comment?

**Comment by Jocelyn1109** [comment]
Hello sorry for the late reply.
For now I will do what is written in the document. After the release we compute all end users 
suggestions and remarks and we will make a decision after discussion.

Thanks.

Jocelyn

**Comment by axd1967** [comment]
Merci. Mais avez-vous compris ce que suggère?

**Comment by Jocelyn1109** [comment]
Oui mais c'est une fonctionnalité supplémentaires?

**Comment by gzotti** [comment]
Even if the bookmarks are under redesign, this change was simple enough and indeed can be helpful. When the checkbox is not active, date/location is not restored.

**Comment by axd1967** [comment]
ah! thank you @gzotti
