### ISSUE TITLE
date/time dialog: put focus on day

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#886]
version 0.19.2:

when I open the date/time dialog for the first time, I always need to mouse click a value before I can use the keyboard. There is no apparent workaround for this.

(Could be similar to #275/#311)

**Comment by axd1967** [comment]
@gzotti in 0f87029e0e this seems to have resurfaced.

**Comment by gzotti** [comment]
How can a minuscule change in the configuration dialog cause a problem in the Date/Time panel?

**Comment by axd1967** [comment]
@gzotti also in a748c186ab

**Comment by gzotti** [comment]
I see no relation in code. A Mandelbug?

**Comment by axd1967** [comment]
also in Stellarium 0.20.2.18226 [master]
