### ISSUE TITLE
Earth satellites distance

### ISSUE THREAD

**Issue by JAY-Githb** [Stellarium/stellarium#888]
Would like option to show satellite distance in miles instead of km.
Thank you.

The satellite plug-in is great!  I use it constantly.

**Comment by gzotti** [comment]
The international unit of distance is metre. Messing around with that caused at least one lost spacecraft. I am very much ***not*** in favour of adding miles, rods, chains, gallons, feet, acres, acrefeet,  or whichever historical units one obstinate country is still using.

**Comment by axd1967** [comment]
And this is not labeled as an opinion?

**Comment by gzotti** [comment]
Oida!

**Comment by Anthony-B-Russo10** [comment]
@JAY-Githb 
The meter is a standard unit of measure in the scientific community and most of the planet doesn't mean it should be in this program or other similar programs. Also considering the use of miles resulted in the loss of the ESA's Schiaparelli EDM.

**Comment by JAY-Githb** [comment]
Hello friends.
Relax everyone. I'm not arguing about the merits of the meter. I agree it is the better system and would be pleased to see it adopted in the US.  But the fact is that the mile is still used and what we are accustomed to.  Many programs do offer the option of which system to use and It would a convenience here. I'm not launching a spacecraft so am not worried about a major catastrophe.
While I would like to have the choice, it is not worth getting anyone all worked up about.
I commend everyone who developed Stellarium and the Satellites plug-in.  You did a great job!  I no longer plot positions on paper maps.  The map on my computer screen works much better.
Thank you all for your efforts.

Jay Respler
