### ISSUE TITLE
Astrocalc crash

### ISSUE THREAD

**Issue by francheu** [Stellarium/stellarium#889]
Using 19.3 appimage under Linux Mint.
I try to display the trajectory of comet 88P/Howell from 2019/12/24 until 2020/01/24, every solar day, with markers and date. Once I click on compute ephemeris I get a segmentation error.
But strangely, it works fine with C/2017 T2 or some other comets.
Tested some asteroids, and in some cases it works, and for other it will crash...

Files : MPC asteroids (personally filtered for 2020), and my ssystem_minor.ini

[MPCORB-2019-12-23_filtre2020.txt](https://github.com/Stellarium/stellarium/files/3998027/MPCORB-2019-12-23_filtre2020.txt)
[ssystem_minor.txt](https://github.com/Stellarium/stellarium/files/3998039/ssystem_minor.txt)

**Comment by alex-w** [comment]
Please run `ls -al /usr/share/stellarium` and show the result

**Comment by axd1967** [comment]
I tried 2019-12-12 - 2020-12-24 at 00:00 with 0.19.3, no problem here (Ubuntu 18) (horizontal as well as eq coordinates).

![image](https://user-images.githubusercontent.com/3529789/71416102-5a7b4c80-265f-11ea-97cd-90d994b23210.png)

**Comment by francheu** [comment]
Here it is:
drwxr-xr-x  13 root root  4096 juin  16  2019 .
drwxr-xr-x 377 root root 12288 déc.  22 20:34 ..
drwxr-xr-x   3 root root  4096 sept. 29 17:46 data
drwxr-xr-x  17 root root  4096 juin  22  2019 landscapes
drwxr-xr-x   3 root root 12288 sept. 29 17:46 models
drwxr-xr-x   3 root root  4096 juin  16  2019 nebulae
drwxr-xr-x   4 root root  4096 juin  16  2019 scenery3d
drwxr-xr-x   2 root root 12288 sept. 29 17:46 scripts
drwxr-xr-x  42 root root  4096 sept. 29 17:46 skycultures
drwxr-xr-x   3 root root  4096 juin  16  2019 stars
drwxr-xr-x   2 root root 12288 sept. 29 17:46 textures
drwxr-xr-x   7 root root  4096 juin  21  2019 translations
drwxr-xr-x   5 root root  4096 sept. 29 17:46 webroot

**Comment by alex-w** [comment]
OK, as I feared. Please uninstall stellarium from repository: `sudo apt purge stellarium` and check AppImage again.

**Comment by francheu** [comment]
Ok, no more crash, thanks.

**Comment by francheu** [comment]
Woops, still crashing guys !
As long as the comet is not displayed, AstroCalc will correctly compute the ephemeris. 
Fact is that 88P is below my horizon. If I compute the ephemeris, then hide the ground and look for 88P, once it should appear Stellarium crashes...

**Comment by alex-w** [comment]
Please attach `~/.stellarium/log.txt` after crash

**Comment by francheu** [comment]
Here is the log.
[log.txt](https://github.com/Stellarium/stellarium/files/3998917/log.txt)

**Comment by alex-w** [comment]
I see in log:
> "Loading /usr/share/stellarium/stars/default/stars_0_0v0_7.cat: 0_0v0_7; 4979"
> "Loading /usr/share/stellarium/stars/default/stars_1_0v0_7.cat: 1_0v0_7; 21806"
> "Loading /usr/share/stellarium/stars/default/stars_2_0v0_7.cat: 2_0v0_7; 150850"
> "Loading /usr/share/stellarium/stars/default/stars_3_1v0_4.cat: 3_1v0_4; 425807"

So, you still have installed stellarium from repository

**Comment by francheu** [comment]
Well I purged as you said, but indeed there is still a stellarium folder in /usr/share.
Can I safely remove it manually ?

**Comment by alex-w** [comment]
Yes, `sudo rm -rf /usr/share/stellarium`

**Comment by francheu** [comment]
Ok, that works fine now. Thank you very much.
The new AstroCalc features are really great.
Have a nice Xmas night.

**Comment by axd1967** [comment]
I also noticed that 88P became visible as from a certain magnification (FOV<10d) while being below the horizon.
