### ISSUE TITLE
There is no year Zero in the Western Calendar

### ISSUE THREAD

**Issue by Philgo** [Stellarium/stellarium#89]
Hello,

  When I turn the time back before 1 AD(CE)  the s/w includes a year zero - therefore all years before 1AD are one year out because of this e.g  7 BC is in Stellarium -6 , because year 0, which never existed is allowed in Stellarium - I am not aware that anyone has reported this before.

I have a rather old version of the s/w so this may have been corrected.

**Comment by alex-w** [comment]
Stellarium use astronomical numeration of years, please read the FAQ: http://stellarium.sourceforge.net/wiki/index.php/FAQ#.22There_is_no_year_0.22.2C_or_.22BC_dates_are_a_year_out.22

**Comment by Philgo** [comment]
Thank you very much for your prompt reply.


Obviously there were no 'C' programmers i year 1 AD their arrays all started at 1.


Cheers, Phil😊


________________________________

**Comment by gzotti** [comment]
It has been reported a zillion times and documented in the Guide (section F.8).
