### ISSUE TITLE
Installer blocked by Windows Smart Screen

### ISSUE THREAD

**Issue by Thomas1664** [Stellarium/stellarium#893]
As I wanted to download Stellarium version 0.19.3, Windows Smart Screen identified the installer as Maleware and blocked it. 
Windows 10 Version 1909; build 18363.535

**Comment by gzotti** [comment]
https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#unsigned-installer-dangerous-to-download-malware

**Comment by alex-w** [comment]
Please check out latest beta (v0.19.3.17695) - https://github.com/Stellarium/stellarium-data/releases/tag/beta
