### ISSUE TITLE
A serious question about China`s sovereignty

### ISSUE THREAD

**Issue by wangyaoji365** [Stellarium/stellarium#894]
Dear opeators:
I am a user from China and I mentioned that the "nations" button in your app shows China together with Hongkong,Macao and Taiwan.And that is an obvious and severe  mistake,which shows your app need a improvement about the knowledge of international relationship and political commonsense.So I formally require you to delete "Hongkong,Macao and Taiwan" as single country choices and add these area`s information into China.Hongkong,Macao and Taiwan are all a part of China,all the Chinese people do hope others can respect our sovereignty and emotion.

**Comment by sunshuwei** [comment]
I am also Chinese, but I disagree with you.
On stellarium, such countries and regions include not only Hong Kong, Macau and Taiwan.
Aruba does not label the Netherlands and Guadeloupe does not label France.
This is an astronomy software, please don't politicize it.

**Comment by alex-w** [comment]
The list of countries was obtained from ISO 3166 standard and list of locations was obtained from GeoNames service. Of course the data in both lists are changed sometimes and on next sync maybe something will be changed.

**Comment by wangyaoji365** [comment]
Sorry,I didn`t mean to offend you.However,first,that`s not a political propaganda.I have the freedom of speech and for itself ,a fact,can be expressed.Second, ISO 3166 standard is international for sure,but personally I think it still can be given some improvement so that it will escape from the risk of wrong information,which have shown so much trouble about the misuse.And every Chinese know that there is only one China in the world.That principle is eternal and we always trust it.I do hope the operator can make a balance between the feelings and your rules.

**Comment by gzotti** [comment]
The balance should be maintained by following the international (ISO) standards. If you feel misinformed, please look also elsewhere for better information. 
Given countless examples of political discordance about the exact name, spelling and nationality of many place names, an alternative would be to exclude all location names and use coordinates, exclusively, for all countries with "difficult" politics. We do not want that, for sure. The sky is international, and this program mostly deals with the sky. Location names are for identification purposes and help most users. Whether Macao is a "regular" part of China is indeed not our primary issue.

**Comment by alex-w** [comment]
OK, the list of countries has been updated (synced with modern list of countries from ISO 3166 1-alpha-2) and in relation to this topic - only one item was changed: Taiwan -> Taiwan (Province of China).

**Comment by henrysky** [comment]
I just come across this issue and it seems like he is a typical Chinese gov minion carrying political propaganda for the communist party with the name of free speech which they do not have in China which is pathetic. 

Anyway geopolitics aside and a more practical suggestion. From my previous experience these Chinese gov minions are not gonna stop here and tmr maybe they will ask why South China Sea is not listed as South China Sea (A territory of China) or a specific Moon crater (A territory of China) after they put a Chinese on the moon. They will keep pushing this kind of propaganda to fill their empty broken. I hope Stellarium remains subjective and stick to a single international standard. Although I have to emphasize China always act as a bully to Taiwan on international stage, if Taiwanese people are unhappy they should encourage their gov to stand up for Taiwan more internationally, and I will not see this as blame the victim as Stellarium is a planetarium software and should not carry out any political agenda. A particular International standard is a particular international standard.

**Comment by kahnc** [comment]
@wangyaoji365 Taiwan is not a part of China.

**Comment by wangyaoji365** [comment]
Have some history common sense,please.Taiwan issue is our internal affairs,you need to discern the truth(the real “truth”) before you give the conclusion.Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Stellarium/stellarium"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月4日(星期天) 上午8:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Stellarium/stellarium] A serious question about China`s sovereignty (#894)





 
@wangyaoji365 Taiwan is not a part of China.

**Comment by gzotti** [comment]
Ask the Chinese government about their "truth" (or is that also "alternative facts"?) of events in 1989.
This issue is closed. Discuss your political affairs elsewhere.
