### ISSUE TITLE
oculars: CCD rotation resets scale

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#895]
### Expected Behaviour
Scale does not change when changing CCD rotation angle

### Actual Behaviour
Scale is reset as soon as angle is changed

### Steps to reproduce
1. open image sensor frame
1. zoom in (or out, same behaviour)
1. rotate the sensor angle
1. observe that the screen scale has changed

### System
* Stellarium version: 0.19.3

**Comment by axd1967** [comment]
update: this happens when changing the angle from the top-right on-screen panel, and does not happen when updating the angle from within the oculars dialog > sensors.

**Comment by alex-w** [comment]
All 3 way for rotation of sensor has same behaviour. If you don't want automatic zooming, then you may disable option "Enable scaling FOV for CCD" in sensor view section of the Ocular plugin GUI.

**Comment by axd1967** [comment]
still there is something wrong: the sudden jump is an indication that somewhere there is something inconsistent.

changing the rotation should ONLY change the angle, nothing else. if I want to perform rotation while having zoomed in on a specific region, I don't want the application to touch the scale.

the alternative is to ALWAYS adapt the zoom if that setting you mention is enabled. in that case, I should not be allowed to rescale the screen.

**Comment by alex-w** [comment]
Zooming function is available in CCD mode by users requests.

**Comment by axd1967** [comment]
I seem to be unable to describe the problem.

The problem is not some request to be able to zoom in CCD mode. It is **suspect** that by merely touching the position angle, there is a **sudden** jump in the scale.

This could be an indication of inconsistency between separate areas in the code, a lack of coordination.

**The sudden jump is suspect, and an indication of a bug.**

I see no reason why altering the position angle should trigger a change in scale. The user can always change the scale independently of this action.

**Comment by alex-w** [comment]
I still do not understand you an fullstate, but I'll change behaviour of tool.

**Comment by axd1967** [comment]
works, thanks!
