### ISSUE TITLE
Possible bug with Navigational star button. Is it possible to add a star label button?

### ISSUE THREAD

**Issue by Ironman65** [Stellarium/stellarium#898]
This might be a possible bug? When you turn on the Navigational Stars button, the Navigational stars appear outlined in red, but when you press the button to turn them off; the bright prominent star names appear and remain such as Rigel, Altair; and etc. Turn on the Sky & Viewing options window [F4] notice that the Labels and Marks check box is in the off position. Then turn on the Navigational Stars button and after you turn it off, it automatically puts a check in the check box and turns it on. You have to uncheck it to turn it off again. This has been doing this in previous versions This might be normal, because maybe the way the software is written, if so just disregard. This is not life threatening. Windows 7 32 bit

Is this wish list item possible to add to Stellarium a star label button on the front panel just like the ones that turn on and off the constellations, grids; and etc?

**Comment by alex-w** [comment]
>Is this wish list item possible to add to Stellarium a star label button on the front panel just like the ones that turn on and off the constellations, grids; and etc?

Yes and no. The bottom bar currently is very bloated already and adding new one button looks not very good for this reason. For same reason we added options into GUI to hide the low frequently used buttons from the bottom bar. In any case you may use shortcut Alt+S to toggle visibility of star names and designations. For which reason you want to see additional button to toggle star names on bottom bar (I hope it's really strong reason)?

**Comment by Ironman65** [comment]
Mr. Wolf
Thank you for your response about the star label button, after reading on the reasons why there wasn’t one in the first place. I agree with you 100% to all of the developers. Thank you for all that you do.
