### ISSUE TITLE
Stellarium 17 crashes when panning

### ISSUE THREAD

**Issue by dukestarwalker** [Stellarium/stellarium#90]
Downloaded version 17 of Stellarium and installed on two Macs today ... one running Yosemite the other El Capitan.
App opens fine,  but it crashes EVERY TIME I pan to a new view  direction  ( by Click-Dragging the mouse.)  Does this on both Macs and both OS's.

Version 15  was working fine. Guess I will be downgrading till this is fixed.

**Comment by gzotti** [comment]
Does this happen on first pan immediately after start, or on particular simulation dates? It may have to do with objects which should come into view. As always, the logfile would help. And some developer with a Mac...

**Comment by alex-w** [comment]
Please attach log from Stellarium

**Comment by pierrechastenay** [comment]
Same here with Stellarium 0.17.0.1 (French) and MacOS 10.12.6. I installed a MacOS security upgrade 2 days ago and can't run Stellarium since. In my case, Stellarium quits after I entered moon in the look up bar and the software starts panning in this direction, or I try to change date and time manually to bring the Moon over the horizon. I tried version 15: same thing! I'd love to share a log if you tell me what it looks like and how to generate it. The only thing I have is the log that I can send Apple in case some software has a glitch. Could that help?

**Comment by gzotti** [comment]
We would like to know from @dukestarwalker whether this is another report of the well-known lunar eclipse bug or a new, Mac specific bug.
@pierrechastenay the location of the Logfile is OS version dependent and documented in the Guide.

**Comment by pierrechastenay** [comment]
Now that you mention it, I was trying to get to the Moon mid-eclipse (Jan 31, 2018 @ 8:30 am). Could that be related to my problem?

**Comment by pierrechastenay** [comment]
I just tried it again, changing dates and time after centering on the Moon, and it works fine, until I get close to the time of the Jan. 31 eclipse. This is a known bug?

**Comment by gzotti** [comment]
@pierrechastenay , select any one of #63, #66, #92, #93, #94, #95, #98. All 7 report a problem with lunar eclipse in v0.17.0. What about your mention of 0.15? There was no report on this so far.

**Comment by pierrechastenay** [comment]
Yep! Installed 0.15.2, thinking it would solve the problem, but it's even worse: the minute I type Moon in the look up bar and hit Return, it quits. I tried changing date to April, same thing... I'll try to look up how to send the log file for both.

**Comment by gzotti** [comment]
You have some talent...
@alex-w wasn't there some lookup problem particularly on MacOS in 0.15.2? 
@pierrechastenay don't use the search dialog: does 0.15.2 show any rendering problem when you search the moon on screen? I would be surprised. And yes, we know, 0.15.2 and later versions on Mac do not play well with the touchpad.

**Comment by pierrechastenay** [comment]
There you go. While looking at both log files, there seems to be an issue with satellites not loading? Could that be it?
FYI I don't use the touchpad anymore after you warned me it slowed down Stellarium.
Didn't see any rendering issue...
When you say don't use the search tool, you mean ever?
[Pierre Chastenay Stellarium 17&15 Bugs 31 Jan 2018.docx](https://github.com/Stellarium/stellarium/files/1682838/Pierre.Chastenay.Stellarium.17.15.Bugs.31.Jan.2018.docx)

**Comment by gzotti** [comment]
https://bugs.launchpad.net/stellarium/+bug/1674836

**Comment by pierrechastenay** [comment]
Oh, I see... But that's an issue with 15; Search works fine in 17, as far as I can tell.

**Comment by gzotti** [comment]
Still waiting for @dukestarwalker to tell us whether this is the solved eclipse bug or something else.

**Comment by dukestarwalker** [comment]
Yes, George , my bug was 100 percent eclipse related.  But I also got an alert box about 'Satellites failed to load' or somesuch  ( maybe because I had only used Satellites  once , two years ago , and never installed new orbital elements ?!?

I am no longer using Stellarium v. 0.17.  Went back to 0.15 for now and haven't opened it for a week. I'm not a power user.

**Comment by gzotti** [comment]
OK, thanks. If some satellites report fail to load in the logfile, this is else harmless.
