### ISSUE TITLE
AstroCalc window drawing artifacts on macOS

### ISSUE THREAD

**Issue by paploo** [Stellarium/stellarium#901]
### Expected Behaviour
Expected UI widgets in the Graphs tab of the Astronomical Calculations window to redraw correctly when changed (either by resizing the window or by changing the available controls, e.g. by clicking on a tab).

### Actual Behaviour
During Astronomical Calculations window resize, or when the controls change, e.g. by clicking on one of the bottom-row tabs, the drawing artifacts appear. These artifacts are best seen in the attached screenshots, but can be described as looking like what I'd expect from:
1. A miss-match in mapped texture width when resizing the window, and
2. Drawing of controls over a non-cleared buffer when the controls change.

Note that neither closing and opening the window, nor changing away from the Graphs tab causes it to properly refresh the drawing of the controls.

<img width="1278" alt="Screen Shot 2019-12-30 at 12 31 39" src="https://user-images.githubusercontent.com/69982/71600160-a1a38a80-2b02-11ea-97f9-b2dbfe569904.png">
<img width="1282" alt="Screen Shot 2019-12-30 at 12 31 27" src="https://user-images.githubusercontent.com/69982/71600161-a1a38a80-2b02-11ea-9d6f-677c427520c7.png">
<img width="1286" alt="Screen Shot 2019-12-30 at 12 31 20" src="https://user-images.githubusercontent.com/69982/71600162-a1a38a80-2b02-11ea-9e2d-b3ed5b7fc131.png">
<img width="1283" alt="Screen Shot 2019-12-30 at 12 31 14" src="https://user-images.githubusercontent.com/69982/71600164-a1a38a80-2b02-11ea-8130-73b820eb3366.png">

### Steps to reproduce
The images above were generated by both simply resizing the window, and by clicking on the bottom row of tabs.

### System
* Stellarium version: v0.19.3 (was seen since the introduction of the Astronomical Calculations, but I just got around to reporting it)
* Operating system: macOS 10.15.2 Catalina (note that this was also seen in 10.14 Mojave, so is not a Catalina problem)
* Graphics Card: Radeon Pro 580 8 GB

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/4010955/log.txt)

**Comment by alex-w** [comment]
Could you check the latest beta - https://github.com/Stellarium/stellarium-data/releases/tag/beta ?

**Comment by paploo** [comment]
I gave it a test and the issue is resolved in this build. Thank you!
