### ISSUE TITLE
Both M44 and M48 is named "Beehive Cluster" in Stellarium 0.19.3.

### ISSUE THREAD

**Issue by nkbj** [Stellarium/stellarium#902]
[Stellarium 19.3 Beehive Cluster bug.pdf](https://github.com/Stellarium/stellarium/files/4011908/Stellarium.19.3.Beehive.Cluster.bug.pdf)

Both M44 and M48 has the label "Beehive Cluster" in Stellarium 0.19.3 as shown in the attached screen dump.

**Comment by alex-w** [comment]
It’s not a bug, both clusters have same name.

**Comment by nkbj** [comment]
Do you have a reference for that? I have not been able to find a name for M48 except in Stellarium.

Den 31. dec. 2019 kl. 08.02 skrev Alexander Wolf <notifications@github.com<mailto:notifications@github.com>>:


It’s not a bug, both clusters have same name.

**Comment by alex-w** [comment]
See: Walter Scott Houston, Stephen James O'Meara, Deep-Sky Wonders, Sky Pub Cor, 1998. ISBN 978-0933346932

All names and sources you could found in names.dat file.

**Comment by gzotti** [comment]
Is it possible that this is a simply a misprint in Deep-Sky Wonders? We should not propagate misprints.

**Comment by alex-w** [comment]
I'll check it in the book
