### ISSUE TITLE
Request for a service from stellarium

### ISSUE THREAD

**Issue by sanjitmathew** [Stellarium/stellarium#91]
Is it possible to get a database containing information about the spatial objects against variables like their distance from earth, sun, angle made with other spatial objects.. etc? How much should I pay for such a service?

**Comment by gzotti** [comment]
Have you tried the AstroCalc tab (F10)?

**Comment by sanjitmathew** [comment]
Not yet. I will. thanks😊

**Comment by sanjitmathew** [comment]
@gzotti 
             Is there a way to get it as a database? I want to use it for data analytics.

**Comment by gzotti** [comment]
The angles are variable, time-dependent. No database, but computed on-the-fly. You could program something with the RemoteControl API. But better use NASA's Horizon service for ephemeris data lists, they are more authoritative....

**Comment by sanjitmathew** [comment]
OK
