### ISSUE TITLE
SATELLITES PLUGIN

### ISSUE THREAD

**Issue by JAY-Githb** [Stellarium/stellarium#910]
Stellarium 0.19.3

As an active satellite observer, I've been using the satellites plugin to replace the paper maps I've used for decades.  Very helpful. So far I've been plotting binocular objects and expect to start looking for geosynchronous sats.
I do have some questions and suggestions.
First, who is the author of this helpful plugin?

It takes a while to first start up Stellarium. Can I limit booting to just the data that I need? For instance, I don't need to take time to load constellation pictures, nebulae or deep space objects.

When I click on a star, data appears brightly in the upper left corner. When I click a satellite, that data is much dimmer. Stars and constellation lines are actually brighter than the text description, making the text hard to read. The text should be brighter.

When clicking a satellite,  a lot of interesting data displayed. It would be helpful to also show perigee, apogee, and inclination.

Can I change the diameter of the Telrad circles, or is there a different way to display circles of 3 or 6 degrees?

In 'Satellites Configuration', there are several groups such as amateur and observatory listed.  I know I can add, but can I also remove or rename the groups?

In an earlier version, I was able to add a specific satellite.  Now when I click the + button [Add more satellites], a window opens that says "Get data from update sources", but nothing is added.

Space-track is mentioned as a source of TLE and I do have an account there. Is there a way to have Stellarium log in and update directly from there?

Thanks to any developers who can help.
Jay

**Comment by gzotti** [comment]
The author(s) of the plugin are listed in the plugin's configuration dialog.

You cannot really limit the loading of the default items. Make sure to disable the plugins that you don't need. (e.g. Meteor showers?)

Maybe you can avoid loading deep-sky textures by editing nebulae/default/textures.json. This is not recommended. 

If you have downloaded more star catalogs, of course they need some more loading time. In this case delete the folder stars/default in your Stellarium User Data Directory (see chapter 5 in the User Guide) 

You can probably edit the solar system data files ($USERDATA/data/ssystem_minor.ini) and delete all minor planets and comets. If you are radical enough, copy $PROGRAMDIR/data/ssystem_major.ini into  your $USERDATA/data folder and your even remove planet moons. This may save a second of loading time. 

Constellation pictures are only loaded when needed. I am not sure if deleting all skycultures apart from "western" would help significantly. Or using Western/Rey, which does not define art textures. 

You can also delete landscapes which you never need from the landscapes folder. This reduces loading by another split-second.

All changes in the program directory are of course reverted whenever you are updating the installation. 

Can you change diameters of the Telrad circles on a (real) Telrad? (Is that part of the satellites plugin?)

I cannot answer the other questions, currently I have this plugin disabled and don't care for it.

**Comment by JAY-Githb** [comment]
Georg, even though you don't use the plugin, thank you for taking the time to respond.
I will look into the files that you mention. I'm not a programmer so will be careful in making changes.
I don't use Telrad and it is not part of the satellites plugin. It's just the closest thing I found to seeing a circle with the approximate field of view of my binoculars.
You mentioned Rey. I met him years ago when I was a teenager and we were in an astronomy club in New York. I didn't know his work then, but I was told he was the author of the Curious George books.

**Comment by A-j-K** [comment]
@JAY-Githb @gzotti 
I actually have a custom version of the satellite plugin I use for Satellite work. So far I hadn't planned on doing a PR for this as these customizations are more specific to my workflow and therefore not configurable (so do not provide for the generic case that an Open Source project would require).

I'm just starting out on what I hope to be my first real PR for the project and that's adding "educational packs" for students of Celestial Navigation (I have access to real tutors of CN which I intend to leverage for the "user experience" and testing). However, since I'm new here I have some learning curves to climb (not just the codebase which is large but also learning the full PR process for Stellarium and the projects "etiquette", etc). 

I hope that when I get settled I can take on other such things are improvements for the Satellite plugin, other plugins, bugfixes and feature requests, etc. But first I need to find my way around.

With regards to the Satellite plugin and it's future, I will remember @JAY-Githb as a potential source of user case material if you don't mind?

**Comment by JAY-Githb** [comment]
You're welcome to use me for 'case material'.
Some background:
I've been observing satellites since Sputnik 3 Rkt.  Since then, I've observed a few thousand different objects.  My project is to determine an Intrinsic Magnitude for everything brighter than mag 12.
On the first HST repair mission, a solar panel was detached and sent off in a separate orbit. I was the first person on earth to spot it.
I was responsible for getting NASA to add RCS to the Satellite Situation Report.
I manage VISUAL.TXT for Celestrak.

You can reach me at JayRespler2@yahoo.com

Is there a way to email someone directly here?

**Comment by larawag** [comment]
@A-j-K 
Currently, I implement an extension of the NavStar plugin. 

More precisely, after selecting an celestial object, one can see in the main window LHA, GHA and SHA, the radius of Moon and Sun and the horizontal parallax of the Moon. Additionally, the NavStar window is extended by a prediction tab with the begin and end of the twilight and the sun rising and setting. Currently under investigation is the sight reduction procedure and an add-on to the guide.

If we would collaborate, certainly we could get further improvements of the plugin. What precisely do you plan? 

But, in any case we should move further discussion to #408.

**Comment by A-j-K** [comment]
@larawag OK, let's keep NavStar discussions over on #408 and not pollute this discussion on the Satellites plugin.

**Comment by JAY-Githb** [comment]
One additional item to add to the description that comes up when you click a satellite is either Age in days or actual date of the TLE.  Some objects don't get regular updates and this would let us know how reliable the prediction is.

**Comment by alex-w** [comment]
> Can I change the diameter of the Telrad circles, or is there a different way to display circles of 3 or 6 degrees?

No, because standard Telrad device has strong defined FOV circles. But you may define Telescope/CCD or Telescope/Eyepece for your task.

> In 'Satellites Configuration', there are several groups such as amateur and observatory listed. I know I can add, but can I also remove or rename the groups?

Yes, you can delete and rename the groups, but through editing satellites.json file. 

> In an earlier version, I was able to add a specific satellite. Now when I click the + button [Add more satellites], a window opens that says "Get data from update sources", but nothing is added.

Yes, it's possible, if source hasn't new satellites in comparison with data in satellites.json

> Space-track is mentioned as a source of TLE and I do have an account there. Is there a way to have Stellarium log in and update directly from there?

Satellites plugin (and Stellarium in general of course) do not support credentials for networks. In one side it's problem for security reasons (how to saving login and password?), in other side many websites using own methods of authorization (through cookies or sessions) and implementation of authorization for those websites may be problematic. In any case you always may use proto file:/// for updating TLE from local harddisk.

**Comment by alex-w** [comment]
> One additional item to add to the description that comes up when you click a satellite is either Age in days or actual date of the TLE. Some objects don't get regular updates and this would let us know how reliable the prediction is.

Please fill separate feature request with required additional data for displaying.

**Comment by A-j-K** [comment]
Space Track has a method of acquiring a temporary token within a Cookie that can be used for API calls to get prebuilt Query objects. However, to use it requires your credentials and as @alex-w pointed out, they need to be stored somewhere. My method is a simple bash shell script that downloads Objects from ST and stores them locally and then uses the file:/// as previously noted.

Celestrak has a system to do this too https://www.celestrak.com/SpaceTrack/TLERetriever3Help.php

And Seesatl has posts on the topic such as http://www.satobs.org/seesat/Aug-2012/0319.html

**Comment by alex-w** [comment]
> When I click on a star, data appears brightly in the upper left corner. When I click a satellite, that data is much dimmer. Stars and constellation lines are actually brighter than the text description, making the text hard to read. The text should be brighter.

But you may change the color

**Comment by JAY-Githb** [comment]
That could work but I read the User Guide and can't find how to change colors.

**Comment by alex-w** [comment]
> That could work but I read the User Guide and can't find how to change colors.

Just select group of satellites and press button "Change the color for selected satellites"

**Comment by JAY-Githb** [comment]
I see. I did not realize that descriptive text was the same color as the satellite.
So if the text is bright enough to read, then the whole screen is covered with bright satellite symbols.
Since that can't be, I'll just have to keep the text faint.
Alex, Thank you for the explanation.

**Comment by JAY-Githb** [comment]
>     In 'Satellites Configuration', there are several groups such as amateur and observatory listed. ....t can I also remove or rename the groups?

> Yes, you can delete and rename the groups, but through editing  satellites.json file.

I looked  through  satellites.json and can't find any listing of the groups.  Are they in a particular location in that file?

**Comment by alex-w** [comment]
> I looked through satellites.json and can't find any listing of the groups. Are they in a particular location in that file?

See array "groups" for each satellite

**Comment by JAY-Githb** [comment]
Wow. Opposite of what I looked for.  I thought Groups were pre-set and then a satellite was put in that group.  Instead, if a groups name is given to a particular satellite, then that name shows up in Groups in the Satellites Configuration window.
Alex, thanks for the guidance.

**Comment by alex-w** [comment]
> When clicking a satellite, a lot of interesting data displayed. It would be helpful to also show perigee, apogee, and inclination.

Could you describe your use cases for perigee, apogee and inclination?

**Comment by gzotti** [comment]
I can estimate "just curiosity". Requested data could include just perigee/apogee distances (should be rather simple), or even geographical coordinates of next/previous/closest sub-perigee point, or various other things, up to giving all orbital elements as extrainfo string. Maybe even showing track of selected satellite on an earth map. But maybe there are also expert sites/programs for that?

**Comment by JAY-Githb** [comment]
More than just curiosity. I can have a few dozen sats on the screen at the same time and have to choose targets. If I see a symbol low in the south, and I find that it has low inclination, it becomes an immediate target. If it has inclination higher than my latitude, I know that it can be overhead at some other time and I don't have to look for it now.
Current info gives altitude. If that altitude is near perigee, it becomes a current target since it won't get much closer.  If at apogee, I can skip it for now and wait till it makes a closer approach.
Accuracy to nearest km is fine. Don't need several decimal places.

Items that currently show but can be hidden as they are not needed for observing purposes are Parallactic angle and TEME.

**Comment by JAY-Githb** [comment]
As Georg states, items like ground track are available elsewhere and not needed for making observations.  If someone wants to add that feature though, I certainly do not mind seeing it.

I would like to be able to set color of satellite and the information for it separately.  I need the satellite faint but the text brighter.
Thank you.

**Comment by alex-w** [comment]
I think I can split color data into 3 items and allow select separate colors for info, markers and orbits. It's not big deal.

**Comment by JAY-Githb** [comment]
> 
> 
> I think I can split color data into 3 items and allow select separate colors for info, markers and orbits. It's not big deal.

May not be a big deal for you, but it sure would be a big help for me.  Thank you.

**Comment by alex-w** [comment]
I've added altitude of perigee/apogee into infobox of satellites, but I see something strange for low orbital satellites when I see values of altitude and perigee/apogee. Maybe I'm doing something wrong.

**Comment by gzotti** [comment]
I don't see it. What do you mean? Anything around mixing up perigee distance (from earth's center) and altitude above earth's surface?

**Comment by alex-w** [comment]
Please select ISS and track it one period with comparison of altitude and perigee/apogee

**Comment by gzotti** [comment]
OK, there are slight deviations (~2km?) between orbit apsis distances and actual height above ground. I did not develop or check this code, is there a difference between "spherical" and "ellipsoid" earth body in the two data? (presumably some mean radius used when orbit apsis distance is computed, and ellipsoid used for the current altitude?) Or are the orbit perturbations in the satellite code so large?

**Comment by A-j-K** [comment]
From a satellite hobbyist point of view, 2km is quite good. SOCRATES satellite collision/avoidance software will alert for a conjunction of satellites at a range of 5km or less. 
References:-
https://www.celestrak.com/SOCRATES/
https://celestrak.com/columns/v04n05/#FAQ06

**Comment by JAY-Githb** [comment]
Agreed.  2 km is fine.  With that, any distances shown can be whole km. No decimal point needed. Less to clutter the screen.

**Comment by alex-w** [comment]
Please check the latest beta.

**Comment by alex-w** [comment]
> Agreed. 2 km is fine. With that, any distances shown can be whole km. No decimal point needed. Less to clutter the screen.

OK, I’ll reduce the “accuracy” for distances. I guess the deviation is more than 2 km for LEO.

**Comment by JAY-Githb** [comment]
Hello Alex.
I don't see a current beta. I'll keep looking.

**Comment by alex-w** [comment]
https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by JAY-Githb** [comment]
Finally was able to find and install the beta. 
The ability to assign different colors to satellite and descriptive information make that much easier to use.
The addition of inclination, perigee, apogee are a big help.
I did not expect these enhancements to be accomplished so quickly. Very impressive.
Since my satellites.json file was wiped out when installing the beta, it will take a while to re-create that. I'll check the updating fix then.
THANK YOU all for improving the Satellites plug-in.

**Comment by axd1967** [comment]
it indeed happens too frequently that the JSON data is lost, sometimes because of updates, but more frequently - I suspect - due to sudden program stops, crashes, etc. 

there isn't much one can do about that, except to NEVER empty (reset) a file and then rewrite it, but ALWAYS create a new file with the new content (temporarily renaming it), AND THEN ONLY archive the exiting file (unless this would cause too much files...), AND THEN ONLY rename the active file to its final name; this should avoid data loss that could occur when the write phase of the file is interrupted for any reason. if anything goes wrong in this sequence, no data should be lost.

so, what certainly needs to be improved is that any data file that is for any reason recreated/**updated**, should first be copied with a date/time stamp in the filename (rather than the naive "file.old" pattern), so that a user can restore that file if ever needed. also, datafile upgrades should provide upgrade routines rather than recreating files from scratch (this works only when the file includes a version identifier).
