### ISSUE TITLE
Weird look of Sun corona texture on 4k screen

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#911]
Yet another bug occuring on 4k screens.

The Sun's corona texture is too big for the Sun when using Stellarium at full resolution (3840x2160).

See attached screenshot:
<img width="557" alt="coronaweird" src="https://user-images.githubusercontent.com/37028368/71764319-ce7ee580-2ee6-11ea-99be-db7b7b391b5b.PNG">

**Comment by gzotti** [comment]
On which platform(s) do you see this? No developer has 4k hardware, so it's hard to guess what has to be done.

**Comment by Atque** [comment]
@gzotti Oops, forgot to add that! :)

* Stellarium version: 0.19.3
* Operating system: Windows 10 Home, 64-bit
* Graphics Card: Radeon RX 5700 XT, latest drivers

I have chosen to ignore HDPI screen scaling (if selected, Stellarium runs at 2k resolution and the corona looks fine). It kind of looks like Stellarium scales up the corona texture alone.

**Comment by gzotti** [comment]
Should be fixed, but @Atque Please report again when this is still visible with the next beta (in ~2 weeks or so?)

**Comment by Atque** [comment]
@gzotti Sure, I'll report back if I see it again. Thanks for the fast solution!
