### ISSUE TITLE
bookmarks: remove triple dot in "Go to..." button

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#916]
Convention is to open a dialog box when clicking a button that contains dots: the dots signal that more is to come before something will happen.

In the case of Bookmarks, the button does not open a dialog box, but triggers an immediate action.

**Comment by Jocelyn1109** [comment]
Hi, bookmarks in Stellarium will disappear to be replace by Observing List.
See [#976](https://github.com/Stellarium/stellarium/issues/976).

I think this ticket could be close and  I will take this remark into account during development.

Jocelyn
