### ISSUE TITLE
bookmarks cannot un-highlight after selected bookmark highlight

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#917]
tested on `master` 008684a75171bc51d955c9271d3dea7081595b3f

1. add a few bookmarks
1. **probably irrelevant:** close and reopen bookmark dialog (to ensure no bookmark has focus)
1. click "Clear the highlights" and observe no bookmarks is highlighted (probably irrelevant too)
1. click "Highlight bookmarks"
1. select one bookmark in the list (probably irrelevant)
1. click "Highlight bookmarks" (this one also...)
1. click "Clear the highlights" -> this does not work

Observe that all bookmarks are now still highlighted; also, there is a difference in highlight behaviour between the little circles and the labels.

**Comment by A-j-K** [comment]
I failed to reproduce this.

At step 2, I had to close Stellarium entirely and restart to achieve "no bookmark has focus". Not sure from your instruction if this is what you meant.

At step 6 I failed to find a button "Highlight all" on the dialog. 

Afaict bookmarks seem to work fine. Do you have any more info?

My setup:
Branch: Master (rebased only yesterday)
Windows 10 Pro (Platform: Windows-10.0.17134)
Windows SDK version 10.0.17763.0 to target Windows 10.0.17134
Visual Studio Version 16.4.1 (msvc2017_64)
Qt 5.13.1

**Comment by axd1967** [comment]
I will recheck this ASAP

**Comment by axd1967** [comment]
* on 0.19.3 this is an issue. I opened Stellarium and ran the procedure I detailed above and still have this problem, so I don't understand why you cannot reproduce it.
here is a screenshot at the end of the procedure: 
![image](https://user-images.githubusercontent.com/3529789/72608438-f4fb4280-3922-11ea-9f79-d60b3b8dcae8.png)
notice that none of the bookmarks have a little circle that appears when triggering "highlight  bookmarks", but they are still highlighted:
![image](https://user-images.githubusercontent.com/3529789/72608513-22e08700-3923-11ea-81de-45f46385e118.png)

* on master 4dbdd9540832a9f74124b46bef4a70d09d9cb18e it is the same issue
![image](https://user-images.githubusercontent.com/3529789/72608683-8a96d200-3923-11ea-9539-bf1374691176.png)

for some reason the highlighted bookmarks remain highlighted (cyan in the screenshots).

("Highlight all" should of course be "Highlight bookmarks")

**Comment by A-j-K** [comment]
Ah, I see, that clarifies what "highlights" means. Sorry, I'm new around here. I will try to reproduce this evening when I get home.

**Comment by A-j-K** [comment]
OK, lunchtime, pizza and Stellarium :)

On a computer that had 0.19.1 installed I downloaded 0.19.3.1-win64 and reinstalled. **Confirmed**, the labels remain after clear highlights.

On my development computer I failed to reproduce with master. So downloaded the release version (as above) and reinstalled a standard version of 0.19.3.1 but again, failed to reproduce (the labels do not remain).

**Comment by axd1967** [comment]
So we need someone else to confirm this... on Ubuntu 18.04.

**Comment by A-j-K** [comment]
Well, I did confirm it on Windows 7 machine with an update from 0.19.1 to 0.19.3. However, right now I can't use that machine to debug the issue. The machine I can debug with doesn't exhibit the problem. Annoying situation to be in for me at least.

**Comment by axd1967** [comment]
this issue might become irrelevant once #854  is available,

**Comment by axd1967** [comment]
# It's even simpler.

1. delete the bookmarks JSON file
1. create some bookmarks
1. highlight bookmarks and observe that bookmarks are highlighted AND circled
1. **highlight bookrmarks (again)**
1. clear the highlights

**bug**: observe that there is still highligting present (but no circles).
