### ISSUE TITLE
v0.19.3 crashes when opening or saving scripts

### ISSUE THREAD

**Issue by scottlevine13** [Stellarium/stellarium#918]
Hi, 

(I hope this is the right place for this; I apologize if it's not)

When I try to open or save scripts in the script window in Stellarium v 0.19.3, the application crashes. I have no way that I can think of to work with scripts now. Is there any way to fix this? It was working previously, and I was able to work with scripts.

I'm using v 0.19.3 on Linux Mint Tara 19 w/Cinnamon, and can send additional info later today.

Thanks for all of your work.

--Scott.

**Comment by scottlevine13** [comment]
If it's helpful, here's the info in the Log tab.

{begin}
2020-01-07T21:58:55
Operating System: Linux Mint 19
Compiled using GCC 7.4.0
Qt runtime version: 5.9.5
Qt compilation version: 5.9.5
Addressing mode: 64-bit
MemTotal:        3467320 kB
MemFree:          656244 kB
MemAvailable:    1135916 kB
SwapTotal:       3616252 kB
model name	: AMD A4-6210 APU with AMD Radeon R3 Graphics
cpu MHz		: 1419.852
model name	: AMD A4-6210 APU with AMD Radeon R3 Graphics
cpu MHz		: 1421.821
model name	: AMD A4-6210 APU with AMD Radeon R3 Graphics
cpu MHz		: 1431.140
model name	: AMD A4-6210 APU with AMD Radeon R3 Graphics
cpu MHz		: 1412.292
QProcess: Destroyed while process ("lspci") is still running.
stellarium --startup-script= 
 -----------------------------------------------------
[ This is Stellarium 0.19.3 - https://stellarium.org/ ]
[ Copyright (C) 2000-2019 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "/home/levine/.stellarium/log.txt"
File search paths:
  0 .  "/home/levine/.stellarium"
  1 .  "/usr/share/stellarium"
Config file is:  "/home/levine/.stellarium/config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.5 (Compatibility Profile) Mesa 19.0.8"
Current Format:  QSurfaceFormat(version 4.5, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
StelMainView::init
Detected: OpenGL "4.5"
Driver version string: "4.5 (Compatibility Profile) Mesa 19.0.8"
GL vendor is "X.Org"
GL renderer is "AMD MULLINS (DRM 2.50.0, 4.15.0-74-generic, LLVM 8.0.0)"
GL Shading Language version is "4.50"
MESA Version Number detected:  19
Mesa version is fine, we should not see a graphics problem.
GLSL Version Number detected:  4.5
GLSL version is fine, we should not see a graphics problem.
Cache directory is:  "/home/levine/.cache/stellarium/stellarium"
StelLocation::createFromLine(): TimeZone name for  "Croton on Hudson"  not found. Translating ""  to  "UTC"
StelLocation::createFromLine(): TimeZone name for  "Croton on Hudson, NY"  not found. Translating ""  to  "UTC"
StelLocation::createFromLine(): TimeZone name for  "North pole"  not found. Translating "system_default"  to  "system_default"
Sky language is  "en_US"
Planetary features language is  "en_US"
Application language is  "en_US"
Couldn't load translations for language  "en_US" in section "stellarium-scripts"
Empty translation file for language  "en_US" in section "stellarium-scripts"
Scripts language is  "en_US"
Loading Solar System data (1: planets and moons) ...
Loading from : "/usr/share/stellarium/data/ssystem_major.ini"
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "/home/levine/.stellarium/data/ssystem_minor.ini"
Loaded 97 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15481 / 15592 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl, Itokawa, Lutetia, Steins, Mathilde, Ryugu"
Loading star data ...
"Loading /usr/share/stellarium/stars/default/stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading /usr/share/stellarium/stars/default/stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading /usr/share/stellarium/stars/default/stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading /usr/share/stellarium/stars/default/stars_3_1v0_4.cat: 3_1v0_4; 425807"
"Loading /home/levine/.stellarium/stars/default/stars_5_2v0_1.cat: 5_2v0_1; 7083058"
"Loading /home/levine/.stellarium/stars/default/stars_6_2v0_1.cat: 6_2v0_1; 24670782"
Finished loading star catalogue data, max_geodesic_level:  5
Loading scientific star names from "/usr/share/stellarium/stars/default/name.fab"
Loaded 4507 / 4507 scientific star names
Loading variable stars from "/usr/share/stellarium/stars/default/gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from "/usr/share/stellarium/stars/default/wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from "/usr/share/stellarium/stars/default/cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
Loading parallax errors data from "/usr/share/stellarium/stars/default/hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.8 (standard edition)"
Loaded 94394 DSO records
Loading DSO outline data ...
Loaded 72 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from "/usr/share/stellarium/skycultures/western/star_names.fab"
Loaded 1004 / 1004 common star names
Loading DSO name data ...
Loaded 1085 / 1098 DSO name records successfully
WARNING - No position data for 13 objects: "PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Loaded 82 / 82 asterism records successfully for culture "western"
Loaded 72 / 72 asterism names
stel.OpenGLArray: Vertex Array Objects are supported
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "AngleMeasure"
Loaded plugin "CompassMarks"
Loaded plugin "Satellites"
[Satellites] loading catalog file: "/home/levine/.stellarium/modules/Satellites/satellites.json"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...

**Comment by gzotti** [comment]
You have a startup-script=<empty?> command line argument. While this should not crash but be handled gracefully, what happens if you add a real script name, and what happens if you omit this argument?

**Comment by alex-w** [comment]
The bug is can be reproduced on Mint only and I fear it related to Qt. Could you check other file dialog and other applications, based on Qt?

**Comment by scottlevine13** [comment]
Hi, thanks for getting back to me. I can try what you suggest when I have the time later, sure, but I've been using the defaults all along, and don't recall it crashing until I upgraded on Monday. That is, I've never specified anything for that argument, or even started it from the command line. I've always just started it from within the Cinnamon desktop with the default options.

(btw, I hope this was the right way to contact you; I realize now that I could have gone over Twitter, etc., instead)

**Comment by gzotti** [comment]
No, this is the exactly only right place to deal with possible errors.

**Comment by scottlevine13** [comment]
Just tried starting Stellarium and specifying a startup script at the command line. The script did not run, and did not display in the script tool window. From there, when I tried to open a script, it was the same behavior. Crashed.

If that "Qt" comment above was directed at me, I'm not entirely sure what you mean, but I'm having no problems with any other applications on this computer. For a test, I installed the same version of Stellarium on another PC also running the Mint Tara, and it also crashed at the same place.

I also installed it on a brand new installation of Mint 19.3 Tricia, so it was a clean install of Stellarium, not an upgrade. It crashed there, too.

**Comment by alex-w** [comment]
OK. I've install Mint 19.3 into VirtualBox and I can reproduce the issue for Stellarium from our PPA (problem Qt5Widgets?). And I see no problems when Stellarium builded from source code.

Could you try build Stellarium from source code?

1. Add deb-src address into sources.list
2. sudo apt-get build-dep stellarium
3. sudo apt-get -b source stellarium
4. sudo dpkg -i stellarium*.deb

**Comment by scottlevine13** [comment]
Hi, thanks again for getting back to me. Sure, I'd be glad to install from source, but can you please give me the full URI for step 1 (not the steps to add; I know how to do that). I can't find it on the website. Thanks.

**Comment by alex-w** [comment]
Could you try snap package of Stellarium?

**Comment by scottlevine13** [comment]
Hi, 
I installed today's daily snap. Looks good.. I loaded a script, changed it, ran it again, saved it, reopened it... Looks good. 
Thanks for all the hard work on it!

Scott. 
--
Scott Levine
s.levine@yahoo.com
917-447-5642  
 
  On Wed, May 13, 2020 at 12:12 PM, Alexander Wolf<notifications@github.com> wrote:   


Could you try snap package of Stellarium?

**Comment by scottlevine13** [comment]
Hi, Sorry to bother you about this, but this problem still exists. I haven't seen the fix in the newer versions of Stellarium. Is this still scheduled to release?

Thanks again for everything.

**Comment by alex-w** [comment]
This is not Stellarium's problem.

Please run:
```
echo "export QT_QPA_PLATFORMTHEME=qt5ct" >> ~/.profile
```
and reboot system or do logout/login operations

**Comment by scottlevine13** [comment]
Hi, I'm sorry, I don't understand. It worked when I installed it from the snap in May, but it seems as though the bug has not been deployed with any further releases. It doesn't appear in any of the release notes. Is there any help at all you can give me?

I did what you suggested above, but it didn't make any difference.

Thanks again.

**Comment by alex-w** [comment]
Stellarium uses a standard view for file dialogs for the operating system and if this view is not defined, then any Qt application, who uses non-custom file dialogs, will crash. The util `qt5ct` is used for configuration style for Qt applications and this is very strange, but she has weird behaviour on Mint (at least we have reports about troubles only from Mint users). 

I've played with settings in Mint right now and apparently I was wrong - please replace "qt5ct" to "gtk3" in the `~/.profile` file and, if you want to get a classical Gtk3+ file dialogs, install package `qt5-gtk-platformtheme`.

Each flat package has its own environment and obviously it has correct behaviour for defining the style of Qt applications.

Other way to resolve similar crashes - using own implementation for visual style of file dialogs (and this behaviour was used in Stellarium some time ago), but in this way file dialogs will be looks weird on all operating systems and we'll get many headache to resolve many specific to each operating system (I fear it may be for each distro) issues.

**Comment by gzotti** [comment]
I think this Mint peculiarity should go into the Wiki, under "Common Problems with the current version". And maybe that package qt-gtk-platformtheme should be listed in the dependencies?

**Comment by alex-w** [comment]
> I think this Mint peculiarity should go into the Wiki, under "Common Problems with the current version". And maybe that package qt-gtk-platformtheme should be listed in the dependencies?

I'm on working in check this issue in clean Debian Gnome right now (...installing packages...) to check possible missing required dependencies.

**Comment by alex-w** [comment]
OK, dialogs and visual style of Stellarium on Debian (Gnome) works fine (I cannot see problems on Ubuntu Gnome too) - so, this is Mint specific issue.

**Comment by alex-w** [comment]
OK, updating wiki is done: https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#Crash_Stellarium_on_Linux_Mint_when_opening_or_saving_files
