### ISSUE TITLE
Feature Request: Axial precession

### ISSUE THREAD

**Issue by axet** [Stellarium/stellarium#919]
How about add earth Axial precession? This is circle on sky (south and north) with 26000 years cycle.

https://en.wikipedia.org/wiki/Axial_precession

**Comment by alex-w** [comment]
Is it a joke?

**Comment by axet** [comment]
No. I tested it, stellarium works fine showing correct precession over -10000 +10000 years. Handy, when you want to know what "North pole star" in current "season".

**Comment by alex-w** [comment]
The precession circles was added 3 years ago and I do not understand what you want to add?

**Comment by axet** [comment]
Okkkk. If you say so. I tried all: settings, toolbar, hotkeys no precession. I see only 'ecliptic of date' and equator. I guess I have to look better, according to release notes of 5.0 it has it... BTW: this is amazing software.
