### ISSUE TITLE
Stellarium 17 crashes during 1/31 Lunar Eclipse

### ISSUE THREAD

**Issue by mikerp43** [Stellarium/stellarium#92]
Any attempt to view the Moon during the times of 1/31 eclipse  causes Stellarium to crash. I'm using EST. I can advance the time to 5:51 or later, 60 degree f.o.v. as long as the Moon is not being displayed. Panning to the west, when the Moon becomes visible, the program to crashes. Or, if the Moon is in the field of view, advancing the time beyond 5:51 will cause the program to crash.  
 I knew I wouldn't get to see all of the eclipse, but I guess Stellarium doesn't want me to see an animation, either.  <grin>

**Comment by gzotti** [comment]
Please see #63 and #66. And https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version
