### ISSUE TITLE
Select single asterism

### ISSUE THREAD

**Issue by freemanli** [Stellarium/stellarium#921]
**Is your feature request related to a problem? Please describe.**
Could you add a feature of "select single asterism" just like the feature of "select single constellation"? There are too many lines of asterisms. It's hard to distinguish "heavenly G" from "winter hexagon" and so on for a beginner.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alex-w** [comment]
Double of #541

**Comment by axd1967** [comment]
Be aware that this works only via search (or scripting) **as well as bookmarks**, not by clicking near an asterism as does "single constellation mode".

Nice, but will require further refinement.
