### ISSUE TITLE
big mistake on date

### ISSUE THREAD

**Issue by bystanderzzz** [Stellarium/stellarium#922]
There is a mistake, which may mislead anyone using the software for historical research.
In calculating the years BC, the software adds one year.
The reason lies in the fact that the software allows to set year '0'.
The point is that there is no such year.
There is '1', and there is '-1', but there is no '0'.

**Comment by alex-w** [comment]
No, it’s not mistake.

https://github.com/Stellarium/stellarium/wiki/FAQ#There_is_no_year_0_or_BC_dates_are_a_year_out
