### ISSUE TITLE
stellarium 17 crash when trying to simulate moon eclipse Jan 31 2018

### ISSUE THREAD

**Issue by kajaji** [Stellarium/stellarium#93]
Actually crash for any lunar eclipse.

log:
2018-01-28T14:53:08
Operating System: Windows 10
Product Name: Windows 10 (10.0)
Compiled using MSVC++ 14.0 (Visual Studio 2015)
Qt runtime version: 5.9.3
Qt compilation version: 5.9.3
Addressing mode: 64-bit
Total physical memory: 32589 MB
Available physical memory: 20847 MB
Physical memory in use: 36%
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
C:\Program Files\Stellarium_0.17.0\stellarium.exe --user-dir=C:\Users\kajaj\AppData\Roaming\Stellarium_0.17.0 
 -------------------------------------------------------
[ This is Stellarium 0.17.0 - http://www.stellarium.org ]
[ Copyright (C) 2000-2017 Fabien Chereau et al.         ]
 -------------------------------------------------------
Writing log file to: "C:\\Users\\kajaj\\AppData\\Roaming\\Stellarium_0.17.0\\log.txt"
File search paths:
  0 .  "C:\\Users\\kajaj\\AppData\\Roaming\\Stellarium_0.17.0"
  1 .  "."
Config file is:  "C:\\Users\\kajaj\\AppData\\Roaming\\Stellarium_0.17.0\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.5.0 - Build 22.20.16.4836"
Current Format:  QSurfaceFormat(version 4.5, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
StelMainView::init
Detected: OpenGL "4.5"
Driver version string: "4.5.0 - Build 22.20.16.4836"
GL vendor is "Intel"
GL renderer is "Intel(R) HD Graphics 630"
GL Shading Language version is "4.50 - Build 22.20.16.4836"
GLSL Version Number detected:  4.5
GLSL version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\kajaj\\AppData\\Local\\stellarium\\stellarium\\cache"
Sky language is  "ar"
Planetary features language is  "ar"
Application language is  "ar"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
Texture "./textures/earth-shadow.png" does not exist
Loaded 77 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:/Users/kajaj/AppData/Roaming/Stellarium_0.17.0/data/ssystem_minor.ini"
Texture "./textures/earth-shadow.png" does not exist
Loaded 101 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15449 / 15454 items of planetary surface nomenclature
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_7.cat: 0_0v0_7; 4979"
"Loading .\\stars\\default\\stars_1_0v0_7.cat: 1_0v0_7; 21806"
"Loading .\\stars\\default\\stars_2_0v0_7.cat: 2_0v0_7; 150850"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4506 / 4506 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6916 / 6916 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.3 (standard edition)"
Loaded 90416 DSO records
Loading DSO outline data ...
Loaded 63 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 847 / 847 common star names
Loading DSO name data ...
Loaded 1004 / 1021 DSO name records successfully
WARNING - No position data for 17 objects: "PGC 621, PGC 2345, PGC 2906, PGC 2907, PGC 14098, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  63 for culture "western"
Loaded 53 / 54 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 43 / 44 asterism names
stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\kajaj\\AppData\\Roaming\\Stellarium_0.17.0\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "FOV"
Loaded plugin "MeteorShowers"
MeteorShowersMgr: Loading catalog file: "C:\\Users\\kajaj\\AppData\\Roaming\\Stellarium_0.17.0\\modules\\MeteorShowers\\showers.json"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\kajaj\\AppData\\Roaming\\Stellarium_0.17.0\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
Oculars::validateIniFile ocular.ini exists at:  "C:\\Users\\kajaj\\AppData\\Roaming\\Stellarium_0.17.0\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateIniFile found existing ini file version  3.1
Loaded plugin "Satellites"
[Satellites] loading catalog file: "C:\\Users\\kajaj\\AppData\\Roaming\\Stellarium_0.17.0\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "OSNSAT" "41939"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Initializing planets GL shaders... 
Got location "Riyadh, Ar Riy??, Saudi Arabia (24.6537, 46.7152; Asia/Riyadh)" for IP "93.168.232.180"

**Comment by gzotti** [comment]
Yet another duplicate. See #92 for more.
