### ISSUE TITLE
MACOs Mojave DMG cut not open

### ISSUE THREAD

**Issue by JHofi** [Stellarium/stellarium#931]
### Expected Behaviour
DMG should open
### Actual Behaviour
Mojave cant open the dmg file "Stellarium-0.19.3" because apple cant search for malsoftware.
![grafik](https://user-images.githubusercontent.com/59932586/72460033-552ba080-37cc-11ea-9925-bcb7282bd7f3.png)

### Steps to reproduce
Download dmg and try to open
### System
* Stellarium version: Stellarium-0.19.3.dmg
* Operating system: <Mojave, 10.14.6>
* Graphics Card: Radeon RX 580

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Please read it: https://www.minicreo.com/mac-uninstaller/app-cannot-be-opened-on-macos-catalina.html

**Comment by alex-w** [comment]
Please check this package: https://github.com/Stellarium/stellarium-data/releases/download/beta/Stellarium-0.19.3.17576.dmg

**Comment by alex-w** [comment]
Please check version 0.19.3.17611 (zip & dmg): https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by guillaumechereau** [comment]
I get the same behavior on macOS Catalina.  I can still run stellarium if I use right click -> open.

With the latest beta, I get a different (probably better) error about the identity of the developer. I can still open it with right click -> open.

<img width="431" alt="Screen Shot 2020-01-27 at 3 51 24 PM" src="https://user-images.githubusercontent.com/107679/73157813-32c74a80-411d-11ea-88e5-1d1c914f5105.png">
<img width="431" alt="Screen Shot 2020-01-27 at 3 46 09 PM" src="https://user-images.githubusercontent.com/107679/73157828-3c50b280-411d-11ea-86ac-6af989acb8ae.png">

**Comment by alex-w** [comment]
Please check this archive: https://github.com/Stellarium/stellarium-data/releases/download/beta/Stellarium-0.19.3.17636.zip

**Comment by JHofi** [comment]
Thanks to all, it works with the context open menue.
Great stuff!
