### ISSUE TITLE
Stellarium 0.19.3.1 loads in Windows 10 and then... nothing

### ISSUE THREAD

**Issue by diegorodriguezperegrin** [Stellarium/stellarium#932]
Hello.

I have tried 32 and 64 bits versions and I see Stellarium loading, then attempting to open in the window and then... the application manager says briefly "suspended" and that's it. Nothing. I have added www. to ocurrences of stellarium in the config.ini file, but no help.

Attached the log file. Can you help
?
[log.txt](https://github.com/Stellarium/stellarium/files/4072060/log.txt)

**Comment by gzotti** [comment]
Last line says it tries to load your customized ssystem_minor.ini. Can you delete that?
It is located in the hidden folder C:\Users\rodri00d\AppData\Roaming\Stellarium\data

Adding www. anywhere in the config file will certainly lead to problems.

**Comment by diegorodriguezperegrin** [comment]
I deleted C:\Users\rodri00d\AppData\Roaming\Stellarium\data\ssystem_minor.ini but Stellarium keeps loading, creating ssystem_minor.ini once again, and vanishing. I tried once more after deleting the www occurrences in the config file to leave it back to factory defaults, but again, Stellarium won't show.

Added new log.txt file. Any hint?

[log.txt](https://github.com/Stellarium/stellarium/files/4076270/log.txt)

**Comment by gzotti** [comment]
There are no obvious hints in the log, unfortunately. 

Can you delete also C:\Users\rodri00d\AppData\Roaming\Stellarium\config.ini to reset any strange config values? Further, please test whether it's a hitherto undetected OpenGL issue by running ANGLE mode (just use the link in your start menu/Stellarium group).

**Comment by alex-w** [comment]
I see in the log:
> Trying to copy ssystem_minor.ini to "C:\\Users\\rodri00d\\AppData\\Roaming\\Stellarium\\data\\ssystem_minor.ini"

Please check permissions for directory.

**Comment by gzotti** [comment]
OP said it is "created ... once again", so that should not be the problem.

**Comment by alex-w** [comment]
After loading solar system data should be started plugins, so, maybe some strange happened here. 

Please attach your config.ini too.

**Comment by alex-w** [comment]
Any news?

**Comment by diegorodriguezperegrin** [comment]
Stellarium keeps failing to start. Attached config.ini file. Same with Spout Sender option. Attached config.ini has requested.

Luckily, starting Stellarium (ANGLE Direct3D 11 mode) works, so this may be a good clue.


[config.zip](https://github.com/Stellarium/stellarium/files/4091958/config.zip)

**Comment by gzotti** [comment]
Maybe the Intel graphics driver needs an update, or a recent update broke it? Just keep running in ANGLE mode. Spout will probably not work, but that should be all.

**Comment by diegorodriguezperegrin** [comment]
Yes, since I can run Stellarium I am happy. Many thanks for the support!
