### ISSUE TITLE
Translated screen behind objects

### ISSUE THREAD

**Issue by stewartIM** [Stellarium/stellarium#933]
I am using Stellarium Mobile on a Samsung Galaxy S7. When I disable the atmosphere, and zoom in on various objects, several translated copies of the entire screen appears behind them. It looks as if the objects were translucent filters located in front of the transposed screen. The objects which I have found that do this so far include:
* the rings of Uranus and Neptune,
* the little circles highlighting the moons of planets
* large portions, but not the entirety, of Saturn's rings, which vary with zoom level and position

![Screenshot_20200116-115352_Stellarium](https://user-images.githubusercontent.com/45269342/72545616-4a6a1d80-3857-11ea-8dbd-96254708cf63.jpg)

**Comment by gzotti** [comment]
This is the wrong site to report issues of Stellarium Mobile. Please use the program's own channels. Only issues about the desktop version go here.
