### ISSUE TITLE
Display Rotation Angle and Control of Off-Axis Guider

### ISSUE THREAD

**Issue by wetzelmd** [Stellarium/stellarium#935]
Feature Request

**Describe the solution you'd like**

The Camera and Off-Axis Guider Ocular view in Stellarium is critical when planning an imaging session.  The Ocular controls on the main screen are very good.

What is missing is a Rotation angle and a -15 -5 -1 0 +1 +5 +15 control for the Off-Axis Guider camera rectangle.  The rotation control is available in the Oculars dialog, but having the angle and a way to change it on the main screen just below the camera control would enable quick movement of the camera and the guide camera rotations independently. 

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by alex-w** [comment]
Looks like an enhancement for request #35

**Comment by alex-w** [comment]
@wetzelmd do you want to get info and controls for change the positional angle for OAG on the on-screen panel by the fact?

**Comment by gzotti** [comment]
> 
> 
> Looks like an enhancement for request #35

Not quite. #35 wants to rotate the guide sensor box itself. I have never seen such arrangement, but with yet another group of settings it may be possible... 
This here wants to rotate the OAG with the top-right onscreen menu, not with the instruments menu.

**Comment by wetzelmd** [comment]
As a convenience, I requested to have similar controls on the main screen to rotate the OAG rectangle the sane way the camera sensor rotation is changed.

Mark

**Comment by wetzelmd** [comment]
I tried the development version with the OAG sensor rotation controls.  I works beautifully!

Thank you so much for the addition.

Mark Wetzel
