### ISSUE TITLE
AstroCalc Graph: time not taken into account via keyboard

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#936]
### Expected Behaviour
Update time via keyboard left/right

### Actual Behaviour
When moving the time slider in the Graphs>Monthly Elev by using keyboard left/right, the slider moves but time does not change

### Steps to reproduce
1. select a star, planet, ...
1. open AstroCalc
1. go to Graphs tab
1. click the time slider
1. move the slider left/right via keybaord arrow left/right
oberve that the time is updated, but the graph not.

### System
* Stellarium version: master 4dbdd9540832a9f74124b46bef4a70d09d9cb18e
* Operating system: Ubuntu 18.04
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by axd1967** [comment]
Also, when dragging the time slider, the time changes, but when releasing it, the time advances one hour . There is a small logic error in the routine that updates the displayed time versus what happens when the slider is released.

**Comment by alex-w** [comment]
Current behaviour of slider for time are specially intended only by mouse usage for speed up the GUI.

**Comment by axd1967** [comment]
Strange, because the same mechanism works fine in View > Sky > Labels and Markers`.

If you don't want to fix this, you should at least disable this because more users will try this and discover this bug.

But I don't buy the argument "to speed up the GUI". Yes, there is a lot of calculation going on, but it is up to the user to accept this.

I suspect that the other bug is related to a dirty optimization: when the user drags the slider, the time will jump one hour once the user releases the mouse. **This is also a bug**.
