### ISSUE TITLE
dialogs are difficult to resize

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#937]
### Expected Behaviour

It is very difficult to resize Stellarium dialogs. It looks like the borders are a single pixel wide, forcing the user to aim very precisely before being able to grab a dialog border in order to resize it. 

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: 0.19.3
* Operating system: Ubuntu 18.04
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
I think this was a design decision taken around 2008.

**Comment by martinber** [comment]
Sorry but I did not fix this yet

**Comment by axd1967** [comment]
seems much better now!
