### ISSUE TITLE
EXO PLanets not displaying correctly

### ISSUE THREAD

**Issue by MitchKob** [Stellarium/stellarium#938]
### Expected Behaviour
Exo Planets not displaying correctly.

### Actual Behaviour
Exo planets are displaying as a large blob made up of squares that are made up of small circles. 
![image](https://user-images.githubusercontent.com/58674802/72685092-7544b380-3a9b-11ea-90f1-d20548bfafcd.png)

### Steps to reproduce
Click on Exo Planet tab along bottom of screen, then look to the SSE at about 60 degrees Alt. Between Vega and Deneb.

### System
* This is happening in both 0.19.3 and 0.19.3.17542. 
* Win 10 Home
* Built in

### Logfile 
N/A

**Comment by alex-w** [comment]
It’s correct view.

**Comment by gzotti** [comment]
This is the field of the Kepler "exoplanet hunter" satellite. No wonder it discovered a few...
