### ISSUE TITLE
Date and Time window

### ISSUE THREAD

**Issue by snoitaleR** [Stellarium/stellarium#939]
When the date and time window is active and no hotkeys are active, you have to make an extra right-click past the date and time window to start using the hotkeys. Can this be fixed?

**Comment by gzotti** [comment]
When the date/time window is freshly called, hotkeys like A, S, J, K, L, ... work. 
When you have clicked into the date/time window, the currently highlit input field has focus. 
Press ESC to close the time panel, and hotkeys work again. Or press F5 twice to come back to line 1. 

This is at least the behaviour on Windows10 and version 0.19.3.1. You neither specified version nor OS.

**Comment by alex-w** [comment]
Latest changes in Date and Time dialog related to issue  #886

**Comment by snoitaleR** [comment]
I didn't know that there was a Date and time window state where it responds to hotkeys, but it doesn't matter. I believe that the modality of the window reduces the dynamic capabilities of the program. I think closing the window to perform a small action and then opening it again, and so many times is inconvenient. But this is only an opinion.

**Comment by gzotti** [comment]
The panel itself should not respond to hotkeys (apart from ESC or the respective F\<n\> key to close it), but when focus is on some number spinner, apparently this gobbles the text input that else would trigger some action. Not sure if it is possible to limit keystrokes to \<whatever set of keys seems useful\>. 
The only interaction I regularly perform in the date panel is via mouse wheel. Doing this seems never to affect my hotkeys or set focus to the fields. But there are of course many ways of interaction...

**Comment by snoitaleR** [comment]
Thanks for the mouse wheel. Indeed, the values change and the hotkeys work. I am quite happy with this option.
