### ISSUE TITLE
Stellarium crashing right before the lunar eclipse commences 

### ISSUE THREAD

**Issue by astrogirl84** [Stellarium/stellarium#94]
January 31st at 21:21 stellarium crashes every time without fail.

**Comment by alex-w** [comment]
Yet another duplicate. See https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version for more.

**Comment by alex-w** [comment]
Please use beta version

**Comment by astrogirl84** [comment]
Thank you so much for recommending the BETA  version. it worked. Much appreciated.


Regards, Lina


________________________________
