### ISSUE TITLE
aarch64 / Raspberry Pi 4 / Manjaro throws GLSL Version Number detected:  1.2 This is not enough: we need GLSL1.30 or later.

### ISSUE THREAD

**Issue by ng0177** [Stellarium/stellarium#940]
Any workarounds? Thanks!

```
Mesa version is fine, we should not see a graphics problem.
GLSL Version Number detected:  1.2
This is not enough: we need GLSL1.30 or later.
You should update graphics drivers or graphics hardware.
```

**Comment by gzotti** [comment]
The warning was always targeted towards PC hardware, while SBCs until recently only used OpenGL ES 2.0. 

You should also see 
`You can try to run in an unsupported degraded mode by ignoring the warning and continuing.`

Please tell us whether the application continues to work, and runs nicely, or shows degraded performance. 

Not sure how to force running programs with OpenGL ES2?

**Comment by ng0177** [comment]
The Stellarium application then crashes with a core dump i.e. no warning.

**Comment by gzotti** [comment]
Last time I tried it worked nicely on Raspbian and Ubuntu Mate 16.04. I did not try other distributions.

**Comment by ng0177** [comment]
I understand these are all 32-bit. The only true 64 bit seems aarch64 on RP-4.

Any chance to fix this upstream?

**Comment by gzotti** [comment]
If you send a PR, there is a good chance.

**Comment by ng0177** [comment]
With great pleasure! To which address and your hands?

**Comment by gzotti** [comment]
PR=Pull Request. Here on this site. This means, you add or modify code to solve the problem (because currently you seem the only person to run into this problem), we check that it does not break the other platforms. If all is OK, we accept. Please see the wiki here for building instructions and contribution notes.

**Comment by ng0177** [comment]
OK. Understood. (I misread PR, otherwise not a bad idea to send you Raspberry Pi 4 for testing and solving the problem:-)

**Comment by gzotti** [comment]
I even have an RPi4, but currently no time to explore this unknown terrain. It's usually faster if you do it yourself.

**Comment by ng0177** [comment]
I was able to compile stellarium w/o error messages. However, the problem
> GLSL Version Number detected:  1.2
with subsequent core dump persists. I am stuck here. Do you have any advice for the next steps? N.B. I compiled https://github.com/KhronosGroup/glslang beforehand which seemed to have no effect.

**Comment by alex-w** [comment]
@ng0177 Are you seen it: https://github.com/Stellarium/stellarium/wiki/Raspberry-Pi ?

**Comment by ng0177** [comment]
Yep, aarch64 is 64-bit vs armv8 is 32-bit currently; that is why.

**Comment by gzotti** [comment]
Yes, see above. The RPis used to support OpenGL ES2, not OpenGL. I don't know how to force OpenGL2 mode on an RPi4. The one and only official Raspbian stayed on 32bit. Getting Stellarium to work on the RPi took months of fruitless Qt5 compile attempt on the RPi1B, but finally succeeded after several years of Qt5 and GPU driver development. 

If this was my own problem, my next step would involve a search engine. None of us know details of aarch64. Maybe you only have to persuade Mesa somehow into OpenGL ES mode. Maybe you have to recompile Qt5. Or maybe you just need to set some symlinks in the graphics libraries. Good luck, and yes, we will be happy to integrate your working solution!

**Comment by ng0177** [comment]
`glxinfo | grep -i opengl` reports

```
OpenGL version string: 2.1 Mesa 20.0.0-devel (git-95187083c4)
OpenGL shading language version string: 1.20
..
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.0.0-devel (git-95187083c4)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.1
```0

Can anyone post this output under Raspian?

The aarch64 error message points to OpenGL as opposed to OpenGL ES being used:
```
Mesa version is fine, we should not see a graphics problem.
GLSL Version Number detected:  1.2
This is not enough: we need GLSL1.30 or later.
You should update graphics drivers or graphics hardware.
```

**Comment by gzotti** [comment]
Yes I know. Until last year or so, these ARM devices supported OpenGL ES2, and not "full" OpenGL. Now we seem to have the problem that the device wants to launch in OpenGL mode, and ignores that it would (likely) work in OpenGL ES (2 or 3 does likely not matter). 
In a similar way, Linux PCs with Mesa until recently only reported OpenGL versions, and suddenly Mesa starts reporting OpenGL ES3 in addition... Fortunately they are launching OpenGL by default.
You "only" have to convince Mesa to launch into OpenGL ES.

**Comment by alex-w** [comment]
@ng0177 could you attach the result of cmake run `cmake ../.. > log.txt`?

**Comment by ng0177** [comment]
No need, [this](https://gitlab.freedesktop.org/mesa/mesa/issues/2428) contains one possible solution:

`MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=130 stellarium`

Stellarium then runs on a R-Pi 4 under aarch64 as smooth as on a gaming desktop using OpenGL.

Mesa functions called by stellarium are compatible with both OpenGL and OpenGL ES. Anyone?

**Comment by gzotti** [comment]
Thanks. This solution goes into the wiki.
Stellarium builds on top of Qt, which can use OpenGL or OpenGL ES, depending on platform. On Windows, OpenGL mode = OpenGL, and ANGLE=OpenGLES. On Raspbian with model 3, Mesa and the open-source VC4 driver provide native OpenGL ES2 and no OpenGL, therefore it was never an issue. On RPi4, apparently there is a premiere dual-support OpenGL + OpenGL ES3.

**Comment by gzotti** [comment]
We can close this, given the right setting for MESA.
