### ISSUE TITLE
CORS (Cross-origin resource sharing) for Remote Control plugin

### ISSUE THREAD

**Issue by sebagr** [Stellarium/stellarium#941]
I'm trying to connect to Stellarium using the Remote Control plugin from my website ([https://telescopius.com](https://telescopius.com)), but I'm getting access denied because of CORS. I can circumvent that by installing a Chrome plugin to inject the proper Access-Control-Allow-Origin, but I would like every user to be able to connect to their own Stellarium server without having to install plugins for their browsers.

Is there any reason why CORS is not enabled for the Remote Control plugin, or is it just that there has been no good reason to do it yet?

Enabling this would should be as easy as adding a oneliner with the "Access-Control-Allow-Origin: *" HTTP header to all server responses, so all developers could hook their web apps to local instances of Stellarium.

**Comment by gzotti** [comment]
Just "there has been no good reason to do it yet."

The developer who created this plugin a few years ago unfortunately left the team. Can you do the relevant changes to all places where it matters, and do a PR? It must not break current functionality, which is "just operating Stellarium from a webbrowser".

Do I understand right, you have a web site and want to access an instance of Stellarium running on the local computer to get/set some extra data? I think this should be explicitly have to be "allowed" in the RemoteControl configuration options.

**Comment by sebagr** [comment]
I've never dived into Stellarium code but I can give it a try :)

**Comment by gzotti** [comment]
Look into plugins/RemoteControl. Building instructions are here in the wiki.
