### ISSUE TITLE
Observability plugin wrong output

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#948]
### Expected Behaviour
rise/set times are the same for plugin as for the main app

### Actual Behaviour

![image](https://user-images.githubusercontent.com/3529789/73140459-70729780-4079-11ea-8a3c-ab4dd0258ead.png)

This seems to happen for all locations on Earth. There seems to be an almost universal 20' difference.
The transit/culmination seems to be correct.

### System
* Stellarium version: `master` (please consider adding the SHA1 in the F1 dialog and/or title bar)

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
The plugin was an external contribution. Its interface is far from perfect, and some functionality like rise/set times have meanwhile been added to the main program. You can set some horizon altitude in its interface though, this should help fixing that difference. 

Its internal code organisation is however a nightmare (i.e. spaghetti code). It needs a deep rewrite.

**Comment by axd1967** [comment]
Ah! thanks - the culprit is the minimum angle in the options. I had chosen +5 degrees.

**Comment by A-j-K** [comment]
Is there a connection here with #554 ?
Additionally, if there's a rewrite needed of this plugin I'd be happy to look at that.

**Comment by gzotti** [comment]
Not directly. The rise/set times are computed by two separate functions. We need just one, but completely correct function. If possible, it should optionally also take the real landscape into account (it is possible to test transparency!) 
I have just added a way to let plugins inject extra information to the InfoString, to avoid the ugly collision you may now see between the usual InfoString and output of Observability. See StelObject.hpp.

**Comment by A-j-K** [comment]
@gzotti I take it that last part of your comment on InfoString refers to #947 ? I looked at that patch earlier this evening :)

**Comment by gzotti** [comment]
Yes, that one.

**Comment by alex-w** [comment]
I cannot reproduce the issue

**Comment by axd1967** [comment]
today I tried **version 0.20.1** to find out what will happen for the eclipse of June 5, 2020, and was a bit surprised.

try this:


1. set location to Ghent, Belgium
1. go to date Jun 5, 2020 (eclipse of the moon) time 19 45 00
1. observe (apart from the fact that rise/set changes over time, which is #994)
rise: **2145**
set **0544**
(without atmosphere, add/remove 4')

1. compare with 
https://www.timeanddate.com/moon/belgium/ghent?month=6&year=2020: rise =2143 set=0523
https://heavens-above.com/moon.aspx rise=2143 set=0524

If we forget about the observability plugin, my problem is that the normal rise/transit/set data seems to have a problem with the set time: 20' is significant. This could point to a problem in the calculation of the Moon position, or a wrong constant to decide on when rise/set occurs.

![image](https://user-images.githubusercontent.com/3529789/79847218-b1035800-83bf-11ea-8b55-c390a99752b7.png)

The Obs plugin seem to be consistent (but maybe it is not correct about the angle to be used)
![image](https://user-images.githubusercontent.com/3529789/79848951-19ebcf80-83c2-11ea-9152-95d5a272a55f.png)


Transit seems to be correct:
![image](https://user-images.githubusercontent.com/3529789/79848031-d5abff80-83c0-11ea-99b3-d281a7c5a36d.png)

![image](https://user-images.githubusercontent.com/3529789/79848774-d1ccad00-83c1-11ea-9d49-dae9e918c1f5.png)



so in the end I'm confused: both Obs plugin and Stellarium are using the same model and giving different output, but who is telling me the correct rise/set times? this also depend on the atmosphere and on the semidiameter of the object

**for now, it looks like the Observability plugin is giving a more accurate output that the rise/set data given by Stellarium, except that it does not take diameter into account.**

**Comment by Thomas1664** [comment]
> Not directly. The rise/set times are computed by two separate functions. We need just one, but completely correct function. If possible, it should optionally also take the real landscape into account (it is possible to test transparency!)
> I have just refined the way to let plugins inject extra information to the InfoString, to avoid the ugly collision you may now see between the usual InfoString and output of Observability. See StelObject.hpp.

@gzotti How to access `StelObject` from the plugin?

**Comment by gzotti** [comment]
Ask StelObjectMgr for getSelectedObject(). And then just take the first in the list. 
The correct algorithm for rise/set times is in Meeus, Astronomical Algorithms. He also describes the definitions for extended objects (esp. sun, moon) that today the contact between upper limb of the observable disk and the mathematical horizon is what resembles "sunrise" etc., and not the center of the disk. It may be useful to adjust for refraction or not depending on activated atmosphere. And certainly add the twilight borders 6/12/18° with height of disk center without atmospheric corrections.  Please just don't re-invent the wheel.

**Comment by axd1967** [comment]
Do we know if the calculations have any value? If not, can we just disable the output pending a solution, rather than induce users into error?

**Comment by alex-w** [comment]
I guess we fixed this issue already, need more checks
