### ISSUE TITLE
Comet display of RA and DEC rates

### ISSUE THREAD

**Issue by wetzelmd** [Stellarium/stellarium#949]
**Is your feature request related to a problem? Please describe.**
Request for additional information to be displayed for object on main screen when selected; comets (and asteroids).

**Describe the solution you'd like**
When imaging a comet, PHD2 guiding uses a dRA and dDEC rates (arcsec/hour).  It would be very helpful for Stellarium to display these values on the main window when a comet is selected. 

**Describe alternatives you've considered**
Cartes du Ciel and Sky Safari 6 Pro provide this information.  However, I prefer Stellarium as I use it extensively for imaging session planning.

**Additional context**

**Comment by alex-w** [comment]
I think dRA/dDec may be added for all Solar system objects in speed section.

**Comment by wetzelmd** [comment]
Alexander,

Thank you so much for your reply and fantastic work! I look forward to updates and improvements.

Mark W

**Comment by alex-w** [comment]
@gzotti could you looking it in light of latest changes of solar system stuff?

**Comment by gzotti** [comment]
Well, the problem here is that dRA/dDec cannot easily (directly) be derived from heliocentric speed values. The easy way (apart from finding speed, distance, projection foreshortening, ...) is indeed going an hour back, compute position, and form the difference to the "current" position.
