### ISSUE TITLE
Crashes on lunar eclipse

### ISSUE THREAD

**Issue by bgold-cosmos** [Stellarium/stellarium#95]
Every time I try to view the 1/31/18 lunar eclipse Stellarium crashes.  Version info is Stellarium 0.17.0 on MacOS 10.13.3

Looking at the log, I suspect
```
Texture "/Users/bgold/Applications/Stellarium.app/Contents/Resources/textures/earth-shadow.png" does not exist
```
is a problem, but in case that's a red herring I've attached the full file

[log.txt](https://github.com/Stellarium/stellarium/files/1679532/log.txt)

**Comment by gzotti** [comment]
Hexaplex! See #63, #66, #92, #93, #94 and Wiki https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version
