### ISSUE TITLE
ocular: eyepices cloned for no reason

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#956]
### Expected Behaviour
When I update the aFov of an eyepiece, I expect the field to be updated, nothing else .

### Actual Behaviour
New "My Ocular" eyepiece is created .

### Steps to reproduce

1. open Ocular dialog
1. select an eyepiece
1. select aFOV input
1. type PageUp to increment the value
1. hit ENTER

Bug: although the value is updated in the selected eyepiece, a new eyepiece name d "My Ocular" is also created by ENTER.
 

### System
* Stellarium version: <Name of downloaded installable file?> 0f87029e0e
* Operating system: <Name, version number> Ubuntu 18
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
When you hit ENTER then you call button "Add" and same behaviour you may see for all properties on all instrumental tabs in the Oculars plugin. I do not understand why you expected something else if you called function to creating a new ocular?

P.S. Yes, this behaviour is exist very long time - I guess since creating a plugin.

**Comment by axd1967** [comment]
No, because the keyboard focus is supposed to move from the Add button to the input field where you type a number, so nothing should happen.
Note also that there is no visual indication that the Add button has focus. I don't know if this is a window manager (Kubuntu) or a Qt issue.

Look at the satellite plugin: when one clicks "New group...", the group is created, but no other buttons are triggered.

in the MPC dialog, there are several buttons , none of which are supposed to react upon ENTER (and nothing seems to happen, which is OK).
![image](https://user-images.githubusercontent.com/3529789/73614080-3a469200-45fc-11ea-80f8-f39d58f5d06f.png)

When I click "Oculars" in the Plugin list, ENTER does nothing, which is logical, because an invisible focus is still on the "Oculars" item in the list.

It could be a local issue: https://forum.qt.io/topic/58535/how-to-change-the-color-of-the-focus-widget-in-qt/5 : I can't see any focus indication in dialogs, e.g the F2 config / main dialog does not show anything having focus, and by tabbing I can't see a focus moving around.
