### ISSUE TITLE
Assign Oculars settings a function key

### ISSUE THREAD

**Issue by NotSoRandomOne** [Stellarium/stellarium#964]
**Is your feature request related to a problem? Please describe.**
For new users, the Oculars overlay in the upper right may not be immediately useful. So, if they are like me, they use the 'settings' in it and eliminate the on-screen panel. But then they do something later and need it back, but they can't figure out how to get that overlay to reappear because it isn't mapped to any function key and doesn't pop up like the other windows.

Yes, I now know it is a plugin, and I have to go to the plugin page and click settings, but a new user won't (like I didn't). It looks like it is an expected part of Stellarium, so give it an unused function key, like F9, by default, so the users stand a chance of accidentally finding it.

**Comment by alex-w** [comment]
Assign new shortcut will not help, because plugin already has assigned shortcuts (who read help?) and it has detailed description in Stellarium User Guide (who read guide?).

**Comment by NotSoRandomOne** [comment]
>> Assign new shortcut will not help,..

Place it on the Function key row. Then it would. All of the main windows in Stellarium are triggered through there, except this one.  I actually tried all of them in an effort to bring it up. So whatever shortcut you've assigned to it is inconsistent with your design of using the Function keys for window toggles.

**Comment by alex-w** [comment]
> Place it on the Function key row. Then it would. All of the main windows in Stellarium are triggered through there, except this one. I actually tried all of them in an effort to bring it up. So whatever shortcut you've assigned to it is inconsistent with your design of using the Function keys for window toggles.

It's a plugin, it's not one of main window. Any plugins should not be assigned to any Function keys, because this feature is not from the main program.

**Comment by NotSoRandomOne** [comment]
_You_ know it is a plugin, but a new user will not. Just like they won't know that the meteor showers is a plugin, because it *acts* like it is part of the main program by being automatically installed/executed during the first run.

If you want to keep it as a plugin, a way to overcome the problem is at the first execution of Stellarium pop up a box telling the user which plugins are to be executed, and explaining in that box that they require setting changes to be performed through the plugin's settings. Even allow them to toggle the plugins off if they wish.

That way people don't have to turn to the manual, which you rightly recognize people don't read. And I'm not the only one who won't read something like that for functionality that should be plain to understand from the design.

**Comment by alex-w** [comment]
> _You_ know it is a plugin, but a new user will not. Just like they won't know that the meteor showers is a plugin, because it _acts_ like it is part of the main program by being automatically installed/executed during the first run.
 
Seriously? Are you really think that users cannot press a button and read the text there? Or, maybe, nobody know about buttons on left bar because it hidden by default? Of course we may disable all plugins by default, but we enable frequently used plugins to allow users a good experience at first startup of planetarium without additional interactions.

> If you want to keep it as a plugin, a way to overcome the problem is at the first execution of Stellarium pop up a box telling the user which plugins are to be executed, and explaining in that box that they require setting changes to be performed through the plugin's settings. Even allow them to toggle the plugins off if they wish.

You already didn't read help, didn't read (open?) GUI, didn't read the User Guide and you will read the text on new window? I think you will just close it without reading and in next iteration you will ask the same questions, but with angries for stupid startup window.
 
> That way people don't have to turn to the manual, which you rightly recognize people don't read. And I'm not the only one who won't read something like that for functionality that should be plain to understand from the design.

Nice! Looks like we should change GUI to one big button with text "Make me good". No need reading the User Guide to change settings the Oculars - just investigate the GUI - but if you can't get something, then read explanatory in the Guide. This is common rule for all software.

**Comment by alex-w** [comment]
I hope we shouldn't add and run video course with explanatory of the GUI for newbies at startup of planetarium.
