### ISSUE TITLE
Astronomical Calculations: graphs for any time

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#970]
**Is your feature request related to a problem? Please describe.**
While I can call up graphs for several years in advance in the **Graphs** tab

![image](https://user-images.githubusercontent.com/3529789/74261556-ba0ae580-4cfb-11ea-9f0a-2d482310acd1.png)

I can't do this for a specific year in the **Monthly elevation** graph:
![image](https://user-images.githubusercontent.com/3529789/74261460-934caf00-4cfb-11ea-8c7b-14ceb46f66a5.png)

**Describe the solution you'd like**
Graphs should take time dialog into account

**Describe alternatives you've considered**
Changing the computer clock?

**Additional context**

**Comment by alex-w** [comment]
If you set year 2025 in Stellarium then what year is current in planetarium?

**Comment by axd1967** [comment]
2025 gives this:
![image](https://user-images.githubusercontent.com/3529789/74263274-c8a6cc00-4cfe-11ea-8447-1a6944f1d21e.png)

but still
![image](https://user-images.githubusercontent.com/3529789/74263343-e4aa6d80-4cfe-11ea-8cab-d8cd688c0323.png)


 in the first graph, ... Jupiter was selected. This is an issue of ergonomy in the program. Sigh.

**Comment by gzotti** [comment]
Nothing to sigh upon. Graph labels are spot-on. The grid labels in the first graph could become clearer, but this seems to be oddly difficult to implement.

**Comment by axd1967** [comment]
I think the confusion stems from the different ways to indicate the target object:
- via a dropdown
- by selection in Stellarium

**Comment by axd1967** [comment]
this has been improved in Stellarium (0.20.3-a97df3ebd3 [master] or before)

(subject has been moved to title area)

![image](https://user-images.githubusercontent.com/3529789/102093488-8324c500-3e21-11eb-8c77-6941409fda30.png)
