### ISSUE TITLE
Je tiens a vous féliciter...

### ISSUE THREAD

**Issue by 010lambda** [Stellarium/stellarium#972]
...Pour la qualité de votre logiciel Stellarium.
Il m'a permis de comprendre, prévoir, étudier en virtuel et sur différents
endroits de notre planète, l'univers dans lequel nous vivons.
En termes d'évolution de votre logiciel, j'y verrai avec grand intérêt un 
sélecteur de limites minimales et maximales de distances des corps célestes
visibles par rapport a notre planète. 
Par exemple, seuls les corps entre 6 et 12 AL ou 156 et 157 AL apparaissent etc.
Merci.
T.

**Comment by axd1967** [comment]
translated:

- congrats for good quality, allows me to discover and study the universe around us
- the request is: **is it possible to add a filter that allows to limit celestial objects by min/max range from Earth** (AL? = AU?)

**Comment by alex-w** [comment]
A short answer: no, distance filter is not possible in Stellarium.

**Comment by gzotti** [comment]
It would help to understand a use case. We could easily filter away planetary objects after having determined their distance. But what's the application? Should we then display objects which would naturally be not bright enough to be seen? 
For stars: only the brigher stars have parallax info from Hipparcos, from which distance can be determined. If we limit star rendition to those, we could add a filter. But again, what's the real application?
See also #481, this here can be considered a duplicate.

**Comment by 010lambda** [comment]
Hi Georg,
About the stars distances filter :
The application is simple, approach a spherical 3 D view of our stellar environment by
using distances steps to discover and understand it.
Something like layers of a cosmic onion.
Not only for a "linear observation" of objects, but for a spherical space environment.
Our Humain senses can’t perceive the depth in the stellar vault.

**Comment by gzotti** [comment]
The application may be simple. The way to achieve it is not. 
Please accept Alexander's answer.
There are "Universe explorer" apps better suited for that.
