### ISSUE TITLE
Incorrect moon terminator?

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#973]
I tried a 300 mm lens the other day. With it, I photographed the moon. This photo is from 2020-02-12 23:11 UTC+1, at latitude +58° 16′ N, +11° 27′ E.
![moon](https://user-images.githubusercontent.com/37028368/74569946-e03eb880-4f7b-11ea-849d-576bfd3135eb.jpg)

Compare this photo to the moon in Stellarium:
![stellarium-014](https://user-images.githubusercontent.com/37028368/74570068-314eac80-4f7c-11ea-9dad-e5b1d4623f4f.png)

You can see that both the craters Keldysh and Atlas are illuminated in Stellarium, but not in reality (the two craters north of Hercules). I don't know if this problem lies within the normal map of the moon, or the model of the terminator. Or perhaps linked to the rotation model of the moon?

A bit nitpickish perhaps. :) But I noticed this problem when I tried to use Stellarium to name craters from the photo I took.

**Comment by gzotti** [comment]
I have made many photos of the moon. Exposure time can make a big difference! If you overexpose, you may see some craters in what is now dark. 
Another factor can indeed be the imprecise rotation model. #502 should fix that.

**Comment by Atque** [comment]
Hm, yes, exposure might be a possible answer here. This photo was taken with 100 ISO, 1/50 s exposure at f/5.6. Using higher ISO and shorter shutter speed made the moon too grainy to make out finer details. 300 mm lens might not be enough to test this thoroughly.

Maybe I should test try Nikon P1000 that my collegue has...

**Comment by gzotti** [comment]
Try 1/15s and 1/2s for comparison. This will burn out the bright part, but may add more craters on/behind the terminator. I must admit, it is decades ago that I had much fun in the darkroom selectively shading parts to get a better-balanced print. Now one would mosaic together differently exposed images. We hope to show illuminated craters when they are visible in a telescope, not how they appear in a photo. The brightness is surprisingly hard to get right.

**Comment by Atque** [comment]
Yes, the sights of a human eye is very hard to simulate on a computer screen. I can try to compare with different shutter speeds once the weather gets better. Unfortunately, the moon is visible in the early hours at the time. :/

**Comment by gzotti** [comment]
@Atque any new photos? 
It's not even the human vision, it's a single photo which is hard to simulate. If I make a well-exposed bright part, the terminator will be too dark and some craters are not visible. If I expose those correctly, the well-illuminated part of the lunar disk will be burnt out. Been there, done that. When observing at the eyepiece, our vision can concentrate on the foveal spot, and over-/underexposure is just "imagined away".

**Comment by Atque** [comment]
@gzotti Sorry, I haven't had the opportunity to shoot any more photos. I will try to borrow my colleague's Nikon P1000 to compare long vs short exposure times.

BTW: This is a nice website that may help when comparing the new rotational model to "official" values:
https://svs.gsfc.nasa.gov/4768

**Comment by Atque** [comment]
@gzotti I built your branch, and it seems the terminator i aligned better. I think the PR will close this issue. Look at this GIF comparing the old and new rotation model:

![moon_old_vs_new](https://user-images.githubusercontent.com/37028368/104807230-b9b57d00-57dd-11eb-800a-5738894ef31e.gif)

**Comment by gzotti** [comment]
Thanks for the confirmation. Yes, the old version only had a simple rotation, now I apply multiple corrections, and comparing also numerical libration results to reference solutions shows that we now should have a good solution.

**Comment by Atque** [comment]
It's really nice to see Stellarium is taking huge leaps toward 1.0. Now "all" we need for the Moon is a better texture, because the current one is quite ugly, to be frank.

**Comment by gzotti** [comment]
At least one huge leap, indeed. This one was surprisingly hard, and I needed to find time slots to work on it for days in succession. 

You can activate a HiPS texture layer for the moon, but this has still its own problems with its normal map. The current overall limitation to 2048x1024 texture files is a concession to a large legacy platform of old hardware. But indeed, the current texture has its issues with e.g. a dark Clavius. There are higher-res textures on the web to use instead. Can *you* help us identify good textures 16384x8192 (or at least 8192x4096) for color and normal maps which we could offer instead? (License considerations are important!)

**Comment by Atque** [comment]
@gzotti The licensing is the most difficult part. We have the texture linked here, that looks really nice (yes, even for high latitudes):
https://github.com/briligg/Moonwards-Assets/tree/master/Models/constructs/Planets/Moon/textures

When used in Stellarium in 2k res:
![stellarium-052](https://user-images.githubusercontent.com/37028368/104808623-cb038700-57e7-11eb-9ea4-91f1125f6953.png)

I have no idea about the licensing though. The normal map in the default Stellarium package seems fine, at least it looks good when I use it.
