### ISSUE TITLE
Weird axis orientation of the moon in the latest public beta?

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#974]
I'm using the latest beta (0.19.3.17695), and I have run into an obvious error with the moon. It seems its axis is pointing in the wrong direction. You can see too much of the lunar poles from earth. See the screenshots below.

New values:
![stellarium-018](https://user-images.githubusercontent.com/37028368/74611723-cc6f8f80-50fe-11ea-867e-c8e2585e8efd.png)

Old values:
![stellarium-019](https://user-images.githubusercontent.com/37028368/74611726-dd200580-50fe-11ea-942b-feff2c913187.png)

Clearly, too much of the lunar south pole is visible. And not only is the rotational axis incorrectly positioned; the real rotation seem off too!

However, editing the solarsys_major.ini, and disabling the lines:

> rot_pole_ra=269.9949
> rot_pole_ra1=0.0031
> rot_pole_de=66.5392
> rot_pole_de1=0.0130
> rot_pole_w0=38.3213
> rot_pole_w1=13.17635815

will bring back the old, better axis (which works fine for present day use). I guess this is some kind of preview of the better rotational elements comming up in future releases?

I see other solar system bodies have these parameters, but I haven't investigated them enough. Maybe they are also off?

**Comment by gzotti** [comment]
Yes, it has to do with these pending changes. There are "funny" side effects. Thanks for the warning, I will have to again disable all of this.
