### ISSUE TITLE
Stellarium Ehternet to Telescope Mount?

### ISSUE THREAD

**Issue by rmscott631** [Stellarium/stellarium#977]
Can Stellarium control my Losmandy Gemini 2 telescope mount through ethernet?

**Comment by alex-w** [comment]
Via ASCOM/INDI/INDIGO maybe

**Comment by gzotti** [comment]
@rmscott631 You are in the fortunate position to answer this question by trying to connect cost-free Stellarium to your mount. We are not. Have you tested, and can we close this?

**Comment by rmscott631** [comment]
Hi Georg,

I was not able to find any way to do this, so go ahead and close my query.

Thanks,
Rick



On Jun 19, 2020, at 1:12 AM, Georg Zotti <notifications@github.com> wrote:


@rmscott631 <https://github.com/rmscott631> You are in the fortunate position to answer this question by trying to connect cost-free Stellarium to your mount. We are not. Have you tested, and can we close this?
