### ISSUE TITLE
Crash when displaying lunar eclipse

### ISSUE THREAD

**Issue by Korrectionator** [Stellarium/stellarium#98]
### Expected Behaviour
Should not crash.

### Actual Behaviour
Crashes when displaying lunar eclipse. 100% repeatable.

### Steps to reproduce
1. Uninstall Stellarium 0.16.x, including user data.
2. Install 0.17.0, selecting all options to remove existing data.
3. Set location to Hanoi, Vietnam.
4. Set date to 31/1/2018, time to about 17:45.
5. Set direction to east.
6. Fast forward through time.
7. Moon barely rises above horizon, then Stellarium crashes, just as the eclipse begins.
8. Alternatively set time to about 23:15, then reverse time.
9. Stellarium crashes just as eclipse ends.
10. Same results for 28/7/2018 lunar eclipse.
11. Same results when forcing use of either Intel or NVIDIA GPU.

### System
* Stellarium version: stellarium-0.17.0-win64.exe
* Operating system: Windows 10 Pro version 1709 build 16299.192 (fully up-to-date).
* Graphics Card: Intel HD Graphics 630, driver date 17/10/2017, version 22.20.16.4836, also, NVIDIA GeForce GTX 1050, driver date 23/1/2018, version 23.21.13.9077.

### Logfile 
2018-01-31T22:44:51
Operating System: Windows 10
Product Name: Windows 10 (10.0)
Compiled using MSVC++ 14.0 (Visual Studio 2015)
Qt runtime version: 5.9.3
Qt compilation version: 5.9.3
Addressing mode: 64-bit
Total physical memory: 16235 MB
Available physical memory: 9626 MB
Physical memory in use: 40%
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
C:\Program Files\Stellarium\stellarium.exe 
 -------------------------------------------------------
[ This is Stellarium 0.17.0 - http://www.stellarium.org ]
[ Copyright (C) 2000-2017 Fabien Chereau et al.         ]
 -------------------------------------------------------
Writing log file to: "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\config.ini"  does not exist. Copying the default file.
Config file is:  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.5.0 - Build 22.20.16.4836"
Current Format:  QSurfaceFormat(version 4.5, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
StelMainView::init
Detected: OpenGL "4.5"
Driver version string: "4.5.0 - Build 22.20.16.4836"
GL vendor is "Intel"
GL renderer is "Intel(R) HD Graphics 630"
GL Shading Language version is "4.50 - Build 22.20.16.4836"
GLSL Version Number detected:  4.5
GLSL version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\Korrectionator\\AppData\\Local\\stellarium\\stellarium\\cache"
Sky language is  "en_AU"
Planetary features language is  "en_AU"
Application language is  "en_AU"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
Texture "./textures/earth-shadow.png" does not exist
Loaded 77 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "./data/ssystem_minor.ini"
Texture "./textures/earth-shadow.png" does not exist
Loaded 101 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15449 / 15454 items of planetary surface nomenclature
Could not find the starsConfig.json file: will copy the default one.
Creating directory  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\stars\\default"
Creates file  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\stars\\default\\starsConfig.json"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_7.cat: 0_0v0_7; 4979"
"Loading .\\stars\\default\\stars_1_0v0_7.cat: 1_0v0_7; 21806"
"Loading .\\stars\\default\\stars_2_0v0_7.cat: 2_0v0_7; 150850"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4506 / 4506 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6916 / 6916 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.3 (standard edition)"
Loaded 90416 DSO records
Loading DSO outline data ...
Loaded 63 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 847 / 847 common star names
Loading DSO name data ...
Loaded 1004 / 1021 DSO name records successfully
WARNING - No position data for 17 objects: "PGC 621, PGC 2345, PGC 2906, PGC 2907, PGC 14098, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  63 for culture "western"
Loaded 53 / 54 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 43 / 44 asterism names
stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "Exoplanets"
Creating directory  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets"
[Exoplanets] No Exoplanets section exists in main config file - creating with defaults
[Exoplanets] exoplanets.json does not exist - copying default catalog to  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
[Exoplanets] Default exoplanets.json to  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
[Exoplanets] loading catalog file: "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "FOV"
FOV: no fov section exists in main config file - creating with defaults
Loaded plugin "MeteorShowers"
Creating directory  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers"
MeteorShowersMgr: Loading catalog file: "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
MeteorShowersMgr: Trying to restore the default catalog to "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
MeteorShowersMgr: The default catalog was copied!
MeteorShowersMgr: Starting to update the catalog...
Loaded plugin "Novae"
Creating directory  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Novae"
[Novae] no Novae section exists in main config file - creating with defaults
[Novae] novae.json does not exist - copying default file to "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
[Novae] copied default novae.json to "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
[Novae] loading catalog file: "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
Creating directory  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Oculars"
Oculars::validateIniFile copied default_ocular.ini to  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini"
Loaded plugin "Satellites"
Creating directory  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Satellites"
[Satellites] satellites.json does not exist - copying default file to  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
[Satellites] copied default satellites.json to  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
[Satellites] copied default qs.mag to  "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\qs.mag"
[Satellites] loading catalog file: "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "MOLNIYA 3-3" "08425"
Satellite has invalid orbit: "IRIDIUM 6" "24794"
Satellite has invalid orbit: "IRIDIUM 34" "24969"
Satellite has invalid orbit: "GRACE-2" "27392"
Satellite has invalid orbit: "FLOCK 2E'-2" "41481"
Satellite has invalid orbit: "FLOCK 2E-9" "41571"
Satellite has invalid orbit: "DRAGON CRS-13 DEB" "43061"
Satellite has invalid orbit: "DRAGON CRS-13 DEB" "43062"
Satellite has invalid orbit: "SL-4 R/B" "43064"
Loaded plugin "SolarSystemEditor"
Trying to copy ssystem_minor.ini to "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\data\\ssystem_minor.ini"
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.
Failure getting IP-based location: 
	 "Host freegeoip.net not found"
MeteorShowersMgr: Loading catalog file: "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json_new.json"
MeteorShowersMgr: The catalog was updated!
[Exoplanets] Starting update...
[Novae] starting update...
[Satellites] starting Internet update...
[Satellites] "43061" "DRAGON CRS-13 DEB" has invalid orbit and will be removed.
[Satellites] "43062" "DRAGON CRS-13 DEB" has invalid orbit and will be removed.
[Satellites] "41481" "FLOCK 2E'-2" has invalid orbit and will be removed.
[Satellites] "41571" "FLOCK 2E-9" has invalid orbit and will be removed.
[Satellites] "27392" "GRACE-2" has invalid orbit and will be removed.
[Satellites] "24969" "IRIDIUM 34" has invalid orbit and will be removed.
[Satellites] "24794" "IRIDIUM 6" has invalid orbit and will be removed.
[Satellites] "08425" "MOLNIYA 3-3" has invalid orbit and will be removed.
[Satellites] "43064" "SL-4 R/B" has invalid orbit and will be removed.
[Satellites] satellite added: "43145" "USA 281"
[Satellites] satellite added: "43137" "FOX-1D (AO-92)"
[Satellites] satellite added: "37389" "X-SAT"
[Satellites] purging objects that were not updated...
Satellite removed: "43035" "2017-077B"
Satellite removed: "43036" "2017-077C"
Satellite removed: "43037" "2017-077D"
Satellite removed: "43038" "2017-077E"
Satellite removed: "43059" "2017-079E"
Satellite removed: "24901" "ABS-3"
Satellite removed: "43032" "COSMOS 2524"
Satellite removed: "43006" "CYGNUS OA-8"
Satellite removed: "43031" "CZ-2C R/B"
Satellite removed: "43040" "CZ-3B R/B"
Satellite removed: "43025" "CZ-6 R/B"
Satellite removed: "43061" "DRAGON CRS-13 DEB"
Satellite removed: "43062" "DRAGON CRS-13 DEB"
Satellite removed: "23754" "ECHOSTAR 1"
Satellite removed: "37344" "ELEKTRO-L 1"
Satellite removed: "41481" "FLOCK 2E'-2"
Satellite removed: "41571" "FLOCK 2E-9"
Satellite removed: "27392" "GRACE-2"
Satellite removed: "24969" "IRIDIUM 34"
Satellite removed: "24794" "IRIDIUM 6"
Satellite removed: "43022" "JILIN-01-04"
Satellite removed: "43023" "JILIN-01-05"
Satellite removed: "43024" "JILIN-01-06"
Satellite removed: "43034" "LKW-1"
Satellite removed: "08425" "MOLNIYA 3-3"
Satellite removed: "42756" "PROGRESS-MS 06"
Satellite removed: "43033" "SL-4 R/B"
Satellite removed: "43064" "SL-4 R/B"
Satellite removed: "43028" "YAOGAN-30 D"
Satellite removed: "43029" "YAOGAN-30 E"
Satellite removed: "43030" "YAOGAN-30 F"
Satellite removed: "28082" "ZHONGXING-20"
[Satellites]  41 satellites proposed for removal,  32  removed,  2265  remain.
[Satellites] writing to: "C:\\Users\\Korrectionator\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
[Satellites] update finished. 2051 / 2294 updated, 3 added, 41 missing or removed. 2343 source entries parsed.
Satellite has invalid orbit: "FLOCK 2E-2" "41484"
Satellite has invalid orbit: "OSNSAT" "41939"
Initializing planets GL shaders...

**Comment by gzotti** [comment]
Y.a.D.

**Comment by Korrectionator** [comment]
Made a mistake when I searched for prior reports, sorry #-o
