### ISSUE TITLE
GoTo not work with direct ASCOM driver for iOptron CEM 120  - Version 0.19.3.1-win64 on Windows 10 pro

### ISSUE THREAD

**Issue by AndreaMatthey** [Stellarium/stellarium#984]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
Where is log?

**Comment by AndreaMatthey** [comment]
I have tried also with beta version.
Save result. 

I not have have
problem if I use stellarium scope.

this is log file.

Il 02.03.2020
21:11 Alexander Wolf ha scritto: 

> Where is log? 
> 
> --
> You are
receiving this because you authored the thread.
> Reply to this email
directly, view it on GitHub [1], or unsubscribe [2].

--

Andrea Mattei 



Con Tiscali Mobile Smart 30 4G hai minuti illimitati, 100 SMS e 30 Giga in 4G a soli 8,99€ al mese. http://tisca.li/smart30


2020-03-12T21:11:06
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 14.0 (Visual Studio 2015)
Qt runtime version: 5.9.9
Qt compilation version: 5.9.9
Addressing mode: 64-bit
Total physical memory: 4053 MB
Available physical memory: 1752 MB
Physical memory in use: 56%
Processor speed: 3293 MHz
Processor name: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
Processor speed: 3293 MHz
Processor name: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
Processor speed: 3293 MHz
Processor name: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
Processor speed: 3293 MHz
Processor name: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
C:\Program Files\Stellarium\stellarium.exe 
 -----------------------------------------------------
[ This is Stellarium 0.19.3 - https://stellarium.org/ ]
[ Copyright (C) 2000-2019 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "C:\\Users\\AndreaMattei\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\AndreaMattei\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\AndreaMattei\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.5.13399 Compatibility Profile Context 15.201.1151.1008"
Current Format:  QSurfaceFormat(version 4.5, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
StelMainView::init
Detected: OpenGL "4.5"
Driver version string: "4.5.13399 Compatibility Profile Context 15.201.1151.1008"
GL vendor is "ATI Technologies Inc."
GL renderer is "AMD Radeon HD 5450"
GL Shading Language version is "4.40"
GLSL Version Number detected:  4.4
GLSL version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\AndreaMattei\\AppData\\Local\\stellarium\\stellarium\\cache"
StelLocation::createFromLine(): TimeZone name for  ""  not found. Translating "system_default"  to  "system_default"
StelLocation::createFromLine(): TimeZone name for  "Salerno"  not found. Translating "system_default"  to  "system_default"
Sky language is  "it_IT"
Planetary features language is  "it_IT"
Application language is  "it_IT"
Scripts language is  "it_IT"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\AndreaMattei\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
Loaded 11057 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15582 / 15592 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl, Ryugu"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
"Loading .\\stars\\default\\stars_4_1v0_2.cat: 4_1v0_4; 1692779"
"Loading .\\stars\\default\\stars_5_2v0_1.cat: 5_2v0_1; 7083058"
"Loading .\\stars\\default\\stars_6_2v0_1.cat: 6_2v0_1; 24670782"
"Loading .\\stars\\default\\stars_7_2v0_1.cat: 7_2v0_1; 50733321"
"Loading .\\stars\\default\\stars_8_2v0_1.cat: 8_2v0_1; 92304337"
Finished loading star catalogue data, max_geodesic_level:  8
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4507 / 4507 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
navigation/preset_sky_time is a double - treating as jday: "2458532.36875"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.8 (standard edition)"
Loaded 94394 DSO records
Loading DSO outline data ...
Loaded 72 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 1004 / 1004 common star names
Loading DSO name data ...
Loaded 1085 / 1098 DSO name records successfully
WARNING - No position data for 13 objects: "PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Loaded 82 / 82 asterism records successfully for culture "western"
Loaded 72 / 72 asterism names
stel.OpenGLArray: Vertex Array Objects are supported
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\AndreaMattei\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\AndreaMattei\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\AndreaMattei\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
Oculars::validateIniFile ocular.ini exists at:  "C:\\Users\\AndreaMattei\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateIniFile found existing ini file version  3.1
Loaded plugin "PointerCoordinates"
Loaded plugin "Satellites"
[Satellites] loading catalog file: "C:\\Users\\AndreaMattei\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "DELTA 2 R/B(1)" "20362"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Loaded plugin "TelescopeControl"
[TelescopeControl] Only embedded telescope servers are available.
[TelescopeControl] Adding device model: "Meade AutoStar compatible" "Any telescope or telescope mount compatible with Meade's AutoStar controller." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Meade LX200 (compatible)" "Any telescope or telescope mount compatible with Meade LX200." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Meade ETX70 (#494 Autostar, #506 CCS)" "Meade's ETX70 with the #494 Autostar controller and the #506 Connector Cable Set." "TelescopeServerLx200" 1500000
[TelescopeControl] Adding device model: "Losmandy G-11" "Losmandy's G-11 telescope mount." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Wildcard Innovations Argo Navis (Meade mode)" "Wildcard Innovations' Argo Navis DTC in Meade LX200 emulation mode." "TelescopeServerLx200" 500000
[TelescopeControl] Adding device model: "Celestron NexStar (compatible)" "Any telescope or telescope mount compatible with Celestron NexStar." "TelescopeServerNexStar" 500000
[TelescopeControl] Adding device model: "Sky-Watcher SynScan (version 3 or later)" "Any Sky-Watcher mount that uses version 3 or later of the SynScan hand controller." "TelescopeServerNexStar" 500000
[TelescopeControl] Adding device model: "Sky-Watcher SynScan AZ GOTO" "The Sky-Watcher SynScan AZ GOTO mount used in a number of telescope models." "TelescopeServerNexStar" 500000
connectionType: 3  initString: "Scope:TCP:JNow:localhost:10001:500000"
Creating telescope "Scope:TCP:JNow:localhost:10001:500000" ; name/type/equinox/params: "Scope" "TCP" JNow "localhost:10001:500000"
TelescopeTCP paramaters host, port, time_delay: "localhost" 10001 500000
[TelescopeControl] Loaded successfully 1 telescopes.
QString::arg: Argument missing: "Sincronizza la posizione del telescopio #% 1 sull'oggetto selezionato" , 1
QString::arg: Argument missing: "Annulla l'ultimo comando di rotazione del telescopio #% 1" , 1
QString::arg: Argument missing: "Sincronizza la posizione del telescopio #% 1 sull'oggetto selezionato" , 2
QString::arg: Argument missing: "Annulla l'ultimo comando di rotazione del telescopio #% 1" , 2
QString::arg: Argument missing: "Sincronizza la posizione del telescopio #% 1 sull'oggetto selezionato" , 3
QString::arg: Argument missing: "Annulla l'ultimo comando di rotazione del telescopio #% 1" , 3
QString::arg: Argument missing: "Sincronizza la posizione del telescopio #% 1 sull'oggetto selezionato" , 4
QString::arg: Argument missing: "Annulla l'ultimo comando di rotazione del telescopio #% 1" , 4
QString::arg: Argument missing: "Sincronizza la posizione del telescopio #% 1 sull'oggetto selezionato" , 5
QString::arg: Argument missing: "Annulla l'ultimo comando di rotazione del telescopio #% 1" , 5
QString::arg: Argument missing: "Sincronizza la posizione del telescopio #% 1 sull'oggetto selezionato" , 6
QString::arg: Argument missing: "Annulla l'ultimo comando di rotazione del telescopio #% 1" , 6
QString::arg: Argument missing: "Sincronizza la posizione del telescopio #% 1 sull'oggetto selezionato" , 7
QString::arg: Argument missing: "Annulla l'ultimo comando di rotazione del telescopio #% 1" , 7
QString::arg: Argument missing: "Sincronizza la posizione del telescopio #% 1 sull'oggetto selezionato" , 8
QString::arg: Argument missing: "Annulla l'ultimo comando di rotazione del telescopio #% 1" , 8
QString::arg: Argument missing: "Sincronizza la posizione del telescopio #% 1 sull'oggetto selezionato" , 9
QString::arg: Argument missing: "Annulla l'ultimo comando di rotazione del telescopio #% 1" , 9
TelescopeTCP( "Scope" )::prepareCommunication: Attempting to connect to host "127.0.0.1" at port 10001
TelescopeTCP( "Scope" ): TCP socket error:
 "Connection refused"
TelescopeTCP( "Scope" )::prepareCommunication: Connection attempt timed out
TelescopeTCP( "Scope" )::prepareCommunication: Attempting to connect to host "127.0.0.1" at port 10001
TelescopeTCP( "Scope" ): TCP socket error:
 "Connection refused"
TelescopeTCP( "Scope" )::prepareCommunication: Connection attempt timed out
TelescopeTCP( "Scope" )::prepareCommunication: Attempting to connect to host "127.0.0.1" at port 10001
SlewDialog::loadPointsFromFile(): No pointss loaded. File is missing: "C:\\Users\\AndreaMattei\\AppData\\Roaming\\Stellarium\\modules\\TelescopeControl\\points.json"
TelescopeTCP( "Scope" ): TCP socket error:
 "Connection refused"
TelescopeTCP( "Scope" )::prepareCommunication: Connection attempt timed out
TelescopeTCP( "Scope" )::prepareCommunication: Attempting to connect to host "127.0.0.1" at port 10001
[TelescopeControl] port name: "COM1" ; vendor identifier: 0 ; product identifier: 0
[TelescopeControl] port name: "COM5" ; vendor identifier: 1027 ; product identifier: 24597
[TelescopeControl] port name: "COM1" ; vendor identifier: 0 ; product identifier: 0
[TelescopeControl] port name: "COM5" ; vendor identifier: 1027 ; product identifier: 24597
[TelescopeControl] port name: "COM1" ; vendor identifier: 0 ; product identifier: 0
[TelescopeControl] port name: "COM5" ; vendor identifier: 1027 ; product identifier: 24597
[TelescopeControl] port name: "COM1" ; vendor identifier: 0 ; product identifier: 0
[TelescopeControl] port name: "COM5" ; vendor identifier: 1027 ; product identifier: 24597
[TelescopeControl] port name: "COM1" ; vendor identifier: 0 ; product identifier: 0
[TelescopeControl] port name: "COM5" ; vendor identifier: 1027 ; product identifier: 24597
connectionType: 7  initString: "iOptron CEM120:ASCOM:J2000:ASCOM.iOptron2017.Telescope:true"
Creating telescope "iOptron CEM120:ASCOM:J2000:ASCOM.iOptron2017.Telescope:true" ; name/type/equinox/params: "iOptron CEM120" "ASCOM" J2000 "ASCOM.iOptron2017.Telescope:true"
TelescopeClientASCOM::TelescopeClientASCOM with telescope name  "iOptron CEM120"  and ascomDeviceId  "ASCOM.iOptron2017.Telescope"
Unloaded plugin "TelescopeControl"
Unloaded plugin "SolarSystemEditor"
Unloaded plugin "Satellites"
Unloaded plugin "PointerCoordinates"
Unloaded plugin "Oculars"
Unloaded plugin "Novae"
Unloaded plugin "MeteorShowers"
Unloaded plugin "Exoplanets"
QItemSelectionModel: Selecting when no model has been set will result in a no-op.
QItemSelectionModel: Selecting when no model has been set will result in a no-op.
Downloaded 0 files (0 kbytes) in a session of 181.024 sec (average of 0 kB/s + 0 files from cache (0 kB)).
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.

**Comment by gzotti** [comment]
I see messages around TelescopeTCP, COM1 (not connected?), COM5, and iOptron via ASCOM. Do you have one or four telescopes? Maybe reset all telescope config options and start anew.
Then there is the message "QItemSelectionModel: Selecting when no model has been set will result in a no-op. " Suspicious to me, but I have not developed that part. 
Also, the Italian translator caused a series of QString errors by introducing a space between "%" and the following "1"...

**Comment by gzotti** [comment]
I close this. Too much has changed.
