### ISSUE TITLE
Setting Location and Time continuously comes up incorrectly.

### ISSUE THREAD

**Issue by kalinysta** [Stellarium/stellarium#985]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by kalinysta** [comment]
Just downloaded the 0.19.3 version of Stellarium to upgrade from the 0.18.0 version.  The old version had my location and time correct; however, when I tried to input my location and time in to the 0.19.3 version, the location and time comes up incorrectly, especially the time which was off by about 4 hours.  When I looked in the drop-down menu to see if I could tweak it that way, I find locations such as America/Dawson Creek (? What? where the heck is that? Is that even a real place?) but cities like Atlanta, Boston, DC, Nashville, Houston, Colorado Springs, are not in the database! Even if I went in and put the location as degree/minutes/seconds, the timezone still comes up incorrectly.  I'm very frustrated and sorry that I downloaded this version when the 0.18.0 version worked just fine.  
Also, why is there no way (that I can find) to minimize the screen?  It seems it either is full screen or you have to get out of the program.  That's incredibly inconvenient.  
Thank you for your time and consideration.

**Comment by alex-w** [comment]
> Just downloaded the 0.19.3 version of Stellarium to upgrade from the 0.18.0 version. The old version had my location and time correct; however, when I tried to input my location and time in to the 0.19.3 version, the location and time comes up incorrectly, especially the time which was off by about 4 hours.

What is your location? Which operating system? Where is log from Stellarium?

> When I looked in the drop-down menu to see if I could tweak it that way, I find locations such as America/Dawson Creek (? What? where the heck is that? Is that even a real place?) but cities like Atlanta, Boston, DC, Nashville, Houston, Colorado Springs, are not in the database!

Yes, America/Dawson Creek is time zone name in Canada: https://timezonedb.com/time-zones/America/Dawson_Creek and no, America/Atlanta, America/Boston, America/Nashville, America/Houston or America/Colorado Springs time zones are not exist! Probably your time zone is America/New York, but if New York is very small city for you, then it's not our problem.

> Even if I went in and put the location as degree/minutes/seconds, the timezone still comes up incorrectly.

By default in this case you will see local mean solar time (or some time zone, if you selected it).

> I'm very frustrated and sorry that I downloaded this version when the 0.18.0 version worked just fine.

The list of changes between version 0.18.0 and 0.19.3 is contains 13 pages A4 with font 12pt and yes, changes for the time zones and locations support was many...

> Also, why is there no way (that I can find) to minimize the screen? It seems it either is full screen or you have to get out of the program. That's incredibly inconvenient.

*facepalm* It's incredible! Are you don't see big button in center of bar, where give tooltip "Full-screen mode (F11)"?
![stellarium](https://user-images.githubusercontent.com/88731/75712380-6b4cdc00-5cfa-11ea-96b8-ccf27e2a53d2.jpg)
Of course information about it you may find in Help window (F1) within planetarium and in the Stellarium User Guide in chapter "A First Tour".

The report looks like bad joke... :(

**Comment by kalinysta** [comment]
I'm sorry, this is NOT a joke.  I've been using this program for years and
I use it every day.  New York City being a *small* city?  Are you living on
Vulcan or Mars or something?  NYC is one of the LARGEST cities on the
planet! Yes, my time zone would be the same as NYC.

I am NOT pleased with the 19.3 version.  I resent the fact that you think
my report is a "joke".  It is also obvious from your reply that English is
not your native language.  My guess is you're Chinese.  Figures.

**Comment by alex-w** [comment]
> I've been using this program for years and I use it every day.

I'm have a bit sceptical view for this statement, because not possible to not find the "Full-screen mode" button on bottom bar if you use planetarium every day in duration of few years IMHO.

> New York City being a *small* city?  Are you living on Vulcan or Mars or something?  NYC is one of the LARGEST cities on the planet! Yes, my time zone would be the same as NYC.

Maybe I'm from Ganymede... Sorry, but New York didn't see in list of time zones for America you and you find Dawson Creek instead.

> I am NOT pleased with the 19.3 version.  I resent the fact that you think my report is a "joke". 

Because you didn't give us any technical details for your problem - how we should resolve it, if you know nothing? Yes, we know that you set some location, and... no more details. Are you use location from standard list (which?)? Or you defined some place by yourself and use it? Are you use custom time zone or not? Your operating system has outdated list of time zones or not?

> It is also obvious from your reply that English is not your native language.

Sorry, but apparently English is not your native language too, because you cannot read the tooltips, help, names of time zones and questions for refinement the source of issue. 

> My guess is you're Chinese.  Figures.

Nope. Maybe all people outside U.S. are Chinese for you?..

**Comment by gzotti** [comment]
Calm down a bit.
Click on the map to set an approximate location. The location list will be narrowed down to locations within (IIRC) 5 degrees. When you select a location from the location list, the time zone will be set automatically. If you select to override timezone, you can do so. The list that includes America/Dawson_Creek is not the location list, but the timezone list. If you misuse it, it's your fault. And yes, please see the manual for more insight.

**Comment by alex-w** [comment]
Any news?

**Comment by gzotti** [comment]
This is a question gone wrong. The program has no bug.
