### ISSUE TITLE
Cannot select the Sun after renaming

### ISSUE THREAD

**Issue by libmar96** [Stellarium/stellarium#986]
Back in 2017, I was creating extrasolar systems in Stellarium, just for visualization and transit simulations. To do that, I had to remove all solar system objects in ssystem.ini except the Earth and the Moon (removing = crash). I used the existing Sun for the star, Earth and Moon were set hidden=true. Here is an example what was done: https://www.youtube.com/watch?v=mOAgpwsK7Lw

It was 0.15.X version, which doesn't work for me anymore (it shows very first frame even after installing, so I need to deal with problems in the latest Stellarium version). There are two things that don't work anymore and definitely something was "blocked":
- If you duplicate two suns (two objects have coord_func=sun_special), Stellarium does not load anymore (in 0.15.X it indeed created two suns; two objects with glare).
- If you rename the Sun, eg. to TRAPPIST-1 and I change the rest of objects from parent=Sun to parent=TRAPPIST-1, it works in both versions. But, in 0.19.X it crashes after trying to click on the star (I need to do this before I follow it). In 0.15.X version, there was no crash at all.

This issue makes me unable to create an extrasolar system using star that shows glare. I would have to hide names (so no one will see "Sun") but it also hides 'b', 'c', 'd' etc. identifications of other planets. Setting type=star does not help at all, because "the star" shows phases.

**Comment by alex-w** [comment]
It's interesting - could you attach your ssystem.ini file?

**Comment by gzotti** [comment]
This program is a simulator for our Solar system. Sorry, but your modification is clearly out of scope. Maybe some other older version works for you.
