### ISSUE TITLE
Pulsars don't work after upgrading to Win 10 pro 32 bit

### ISSUE THREAD

**Issue by Ironman65** [Stellarium/stellarium#989]
The pulsars are no longer being displayed after pressing the PSR button after I recently upgraded from Win7 Ultimate SP1 32 bit to Win 10 Pro 32 bit. Everything in Stellarium 19.3 and other software as well works just fine, even the frame rates in Stellarium are still the same, but the only thing that doesn’t work is the pulsars. I figured it might be something got corrupted during the upgrade process. Yes I performed the standard procedures of re installs and etc; still no change. 
I’m posting the info just in case this has happened before. As they say things happen!

**Comment by alex-w** [comment]
Please attach the log from Stellarium. And just as checkpoint - please try update catalog within plugin.

**Comment by Ironman65** [comment]
Here’s the log for you. Yes I have updated the pulsar manually through the plug-ins; and still no go!

2020-03-04T18:23:05
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 14.0 (Visual Studio 2015)
Qt runtime version: 5.9.8
Qt compilation version: 5.9.8
Addressing mode: 32-bit
Total physical memory: 3071 MB
Available physical memory: 1622 MB
Physical memory in use: 47%
Total virtual memory: 2047 MB
Available virtual memory: 1900 MB
Processor speed: 2223 MHz
Processor name: AMD Athlon(tm) 64 X2 Dual Core Processor 4200+
Processor speed: 2223 MHz
Processor name: AMD Athlon(tm) 64 X2 Dual Core Processor 4200+
C:\Program Files\Stellarium\stellarium.exe 
-----------------------------------------------------
[ This is Stellarium 0.19.3 - https://stellarium.org/ ]
[ Copyright (C) 2000-2019 Fabien Chereau et al. ]
-----------------------------------------------------
Writing log file to: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
0 . "C:\\Users\\c\\AppData\\Roaming\\Stellarium"
1 . "."
Config file is: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format: QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version: "4.6.0 NVIDIA 388.13"
Current Format: QSurfaceFormat(version 4.6, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
StelMainView::init
Detected: OpenGL "4.6"
Driver version string: "4.6.0 NVIDIA 388.13"
GL vendor is "NVIDIA Corporation"
GL renderer is "GeForce GT 630/PCIe/SSE2/3DNOW!"
GL Shading Language version is "4.60 NVIDIA"
GLSL Version Number detected: 4.6
GLSL version is fine, we should not see a graphics problem.
Cache directory is: "C:\\Users\\c\\AppData\\Local\\stellarium\\stellarium\\cache"
Sky language is "en_US"
Planetary features language is "en_US"
Application language is "en_US"
Couldn't load translations for language "en_US" in section "stellarium-scripts"
Empty translation file for language "en_US" in section "stellarium-scripts"
Scripts language is "en_US"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\c\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
Loaded 98 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15481 / 15592 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl, Itokawa, Lutetia, Steins, Mathilde, Ryugu"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
"Loading .\\stars\\default\\stars_4_1v0_2.cat: 4_1v0_4; 1692779"
"Loading .\\stars\\default\\stars_5_2v0_1.cat: 5_2v0_1; 7083058"
"Loading .\\stars\\default\\stars_6_2v0_1.cat: 6_2v0_1; 24670782"
"Loading .\\stars\\default\\stars_7_2v0_1.cat: 7_2v0_1; 50733321"
ERROR: SpecialZoneArray( 8 )::SpecialZoneArray: QFile( "./stars/default/stars_8_2v0_1.cat" .map( 5242912 , 553826022 ) failed: "Not enough memory resources are available to process this command."
"Loading .\\stars\\default\\stars_8_2v0_1.cat: 8_2v0_1; - initialization failed"
Finished loading star catalogue data, max_geodesic_level: 7
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4507 / 4507 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.8 (standard edition)"
Loaded 94394 DSO records
Loading DSO outline data ...
Loaded 72 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 1004 / 1004 common star names
Loading DSO name data ...
Loaded 1085 / 1098 DSO name records successfully
WARNING - No position data for 13 objects: "PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Loaded 82 / 82 asterism records successfully for culture "western"
Loaded 72 / 72 asterism names
stel.OpenGLArray: Vertex Array Objects are supported
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "AngleMeasure"
Loaded plugin "ArchaeoLines"
Loaded plugin "CompassMarks"
Loaded plugin "EquationOfTime"
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
[MeteorShowersMgr] Starting to update the catalog...
Loaded plugin "NavStars"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Observability"
Loaded plugin "Oculars"
Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
Oculars::validateIniFile ocular.ini exists at: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateIniFile found existing ini file version 3.1
Loaded plugin "PointerCoordinates"
Loaded plugin "Pulsars"
[Pulsars] File format is wrong! Error: unterminated object at offset 511001
[Pulsars] Copied default pulsars.json to "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\modules\\Pulsars\\pulsars.json"
[Pulsars] Loading catalog file: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\modules\\Pulsars\\pulsars.json"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json_new.json"
[MeteorShowersMgr] The catalog was updated!
Loaded plugin "Quasars"
[Quasars] Version of the format of the catalog: 1
[Quasars] Loading catalog file: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\modules\\Quasars\\quasars.json"
Loaded plugin "Satellites"
[Satellites] loading catalog file: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Loaded plugin "Scenery3d"
Loaded 1 extensions for "Scenery3d"
stel.plugin.scenery3d: Scenery3d plugin - press KGA button to toggle 3D scenery, KGA tool button for settings
stel.plugin.scenery3d: Initializing Scenery3d renderer...
stel.plugin.scenery3d.renderer: Maximum texture size: 16384
stel.plugin.scenery3d.renderer: Maximum viewport dims: 16384 16384
stel.plugin.scenery3d.renderer: Maximum renderbuffer size: 16384
stel.plugin.scenery3d.renderer: Maximum framebuffer size: 16384
stel.plugin.scenery3d.renderer: Geometry shader supported
stel.plugin.scenery3d.renderer: GL_MAX_TEXTURE_IMAGE_UNITS: 32
stel.plugin.scenery3d.renderer: GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: 192
stel.plugin.scenery3d.renderer: Seamless cubemap filtering enabled
stel.plugin.scenery3d: Initializing Scenery3d renderer...done
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Loaded plugin "Supernovae"
[Supernovae] version of the catalog: 1
[Supernovae] loading catalog file: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\modules\\Supernovae\\supernovae.json"
[Exoplanets] Updating exoplanets catalog...
[Novae] Updating novae catalog...
[Novae] Download error: While trying to access "http://stellarium.org/json/exoplanets.json" the following error occured: "Unknown error"
[Pulsars] Updating pulsars catalog...
[Pulsars] File format is wrong! Error: unterminated object at offset 511001
[Pulsars] File format is wrong! Error: unterminated object at offset 511001
[Satellites] starting Internet update...
[Satellites] writing to: "C:\\Users\\c\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
[Satellites] update finished. 1222 / 1598 updated, 0 added, 0 missing or removed. 1842 source entries parsed.
[Novae] already updating... will not start again current update is complete.
[Novae] already updating... will not start again current update is complete.
[Novae] already updating... will not start again current update is complete.
[Novae] already updating... will not start again current update is complete.

**Comment by alex-w** [comment]
I see follow lines:
> [Novae] Updating novae catalog...
> [Novae] Download error: While trying to access "http://stellarium.org/json/exoplanets.json" the following error occured: "Unknown error"
> [Pulsars] Updating pulsars catalog...
> [Pulsars] File format is wrong! Error: unterminated object at offset 511001
> [Pulsars] File format is wrong! Error: unterminated object at offset 511001

It's bad. Seems catalog was downloaded partially. Could you update it again within planetarium?

P.S. Please check this URL in browser: http://stellarium.org/json/pulsars.json and could you share file pulsars.json from your user directory?

**Comment by gzotti** [comment]
BTW why does the Novae plugin access exoplanets.json? Just a typo in the message?

**Comment by alex-w** [comment]
I don't know, but maybe something weird in config.ini after upgrade OS?

**Comment by Ironman65** [comment]
To Alex and Georg 
I did as you requested by going to the suggested URL. This is what I got.

  SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 25433 column 12 of the JSON data

I’m not a computer programmer, but I did some research and discovered, sense Win 10’s release there’s been a lot of problems with it, mostly in the 64 bit architecture; but problems sense then have been reducing. Again thanks for what you all are doing, and I hope all of this helps.

**Comment by alex-w** [comment]
Please attach your pulsars.json, because I cannot reproduce the issue.

**Comment by Ironman65** [comment]
A question. where's the pulsar.json located at? Once I can locate it, I'll get it. Thanks

**Comment by alex-w** [comment]
In the user directory: `C:\Users\c\AppData\Roaming\Stellarium\modules\Pulsars\pulsars.json`

And please attach pulsars.json, what you get through browser.

**Comment by Ironman65** [comment]
I think this is what you were looking for.
[Pulsars.zip](https://github.com/Stellarium/stellarium/files/4296448/Pulsars.zip)

**Comment by alex-w** [comment]
OK, I see the source of problem and thanks for report! The source data has error in the data and I didn't validate that data (column w50). I'll fix it tonight and update the pulsars.json on stellarium.org

**Comment by alex-w** [comment]
OK. Please remove file `C:\Users\c\AppData\Roaming\Stellarium\modules\Pulsars\pulsars.json`, start Stellarium and update pulsars catalog within plugin.
