### ISSUE TITLE
Add a setting for NOT hiding Search Window after clicking the result

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#990]
I always use it to find and observe a lot of DSO. After searching and clicking the object selected from my list, the Search Window will automatically hide, until I call it out next time. I think it will be better if it can give a setting to decide whether to hide.

Stellarium is helping more and more amatuers to start thier Deep Sky Journey. One of the futher improvements of Stellarium may be adding a observing list function to it.

Wish for better. Thank you!

**Comment by kajaji** [comment]
Observing list is available. Astronomical Calculation Window > WUP (What's Up Tonight) tab.

**Comment by alex-w** [comment]
Well, Astronomical Calculations and Bookmarks (Alt+B) maybe very helpful for you.

**Comment by ultrapre** [comment]
> Well, Astronomical Calculations and Bookmarks (Alt+B) maybe very helpful for you.

Thanks, Bookmarks fit in exactly with my wishes.

**Comment by alex-w** [comment]
OK. I hope in future we get a mature observing lists feature :)
