### ISSUE TITLE
How to Open Stellarium in Secondary Display Window?

### ISSUE THREAD

**Issue by ImmersiveTheatres** [Stellarium/stellarium#991]
I have been utilising the new Stellarium functionalities (_'twinkling stars with atmosphere off' & 'meteors with atmosphere off'_) very successfully in my mobile planetariums - thank you for including them!

I now have a new challenge.

I recently upgraded my MacBook Pro and introduced some new spherical mirror projection software. Now it has become important for me to have Stellarium open in the Secondary Display (the planetarium projector) and not the Primary Display (the laptop).

I have researched online and have tried modifying the config line:

**[video]
screen_number                = 1**

This opens Stellarium in the Secondary Display - **but it only shows half of the Stellarium screen / image.**

How can I force Stellarium to open / launch fully in the Secondary Display?

I also use Keyboard Maestro to manipulate application windows between Primary and Secondary Displays - yet Stellarium completely ignores Keyboard Maestro commands. Is there something I can add to the config file to allow Keyboard Maestro to move Stellarium to the secondary Display?

Any advice / solution will be greatly appreciated!

Thanks very much

Mario Di Maggio

**Comment by alex-w** [comment]
Please try define screen size and disable automatic full-screen mode in config.ini file

**Comment by ImmersiveTheatres** [comment]
Thank you for your quick response Alex.

Your 1st suggestion: I have tried disabling fullscreen (see below). But I'm not sure what you mean by defining screen size? I have tried various screen_x and screen_y  values, but it makes no difference.

[video]
**fullscreen                             = false**
maximum_fps                       = 10000
minimum_fps                        = 18
screen_h                               = 1080
screen_number                    = 0
screen_w                               = 1920
screen_x                               = 0
screen_y                               = 0
viewport_effect                   = sphericMirrorDistorter



Your 2nd suggestion: I suspect this might work, but the problem is every time I move the Stellarium window into the second display, it changes / zooms in - _like it is magnified inside windowed mode_ (see images) 

On laptop:
![IMG_7681](https://user-images.githubusercontent.com/59133199/75991959-2dfd6f80-5eef-11ea-9482-b552a44d94a5.JPG)


On projector display:
![IMG_7680](https://user-images.githubusercontent.com/59133199/75991976-35bd1400-5eef-11ea-9cd1-6d5672c2b987.JPG)

**Comment by alex-w** [comment]
Please write a resolution of second screen

**Comment by ImmersiveTheatres** [comment]
It's a normal HD projector: 1920 x 1080

**Comment by gzotti** [comment]
Screen_x/y are not size but offset values. For your second screen you probably should write x=width_of_first_screen, y=0

**Comment by alex-w** [comment]
Please try:
`[video]
fullscreen = false
maximum_fps = 10000
minimum_fps = 18
screen_h = 1080
screen_number = 1
screen_w = 1920
screen_x = 0
screen_y = 0
viewport_effect = sphericMirrorDistorter `

**Comment by ImmersiveTheatres** [comment]
Thanks Alex, but that is exactly the video config settings I have been using (as you can see from my previous message).

When I move the Stellarium window from the laptop to the projector, it automatically "magnifies" the image , as you can see from this video:

https://www.dropbox.com/s/hmjviynvsz4yonh/IMG_7683.MOV?dl=0

**Comment by ImmersiveTheatres** [comment]
> Screen_x/y are not size but offset values. For your second screen you probably should write x=width_of_first_screen, y=0

I tried this but it makes no difference ie. on dragging the window across to the projector it "magnifies" inside the window

**Comment by alex-w** [comment]
OK, let’s test: set screen_number = 1 and fullscreen = true in config.ini, start Stellarium and press F11 twice.

**Comment by gzotti** [comment]
Is your first (Laptop) monitor FullHD or 4k? There may be some Qt environment variables to tweak.

**Comment by ImmersiveTheatres** [comment]
> OK, let’s test: set screen_number = 1 and fullscreen = true in config.ini, start Stellarium and press F11 twice.

Stellarium opens in full screen in the second display (but the image is magnified). Then F11 makes it a window (with magnified image). Then F11 again makes it full screen (with magnified image).

**Comment by ImmersiveTheatres** [comment]
> Is your first (Laptop) monitor FullHD or 4k? There may be some Qt environment variables to tweak.

The MacBook Pro screen resolution is 2560 x 1600

**Comment by alex-w** [comment]
Could you attach log from Stellarium?

**Comment by ImmersiveTheatres** [comment]
[log.txt](https://github.com/Stellarium/stellarium/files/4294117/log.txt)

**Comment by alex-w** [comment]
Aha! Please set environment variable QT_SCALE_FACTOR=1.0 and run Stellarium again

**Comment by ImmersiveTheatres** [comment]
> Aha! Please set environment variable QT_SCALE_FACTOR=1.0 and run Stellarium again

OK, but I'm not sure where to add that line in the config file?

**Comment by alex-w** [comment]
Not in config.ini! Please try run in Terminal.app:
`export QT_SCALE_FACTOR=1.0 && ~/Applications/Stellarium.app/Contents/MacOS/stellarium`

**Comment by ImmersiveTheatres** [comment]
OK when I paste that line in Terminal, I receive:

zsh: no such file or directory: /Users/immersivetheatres2/Applications/Stellarium.app/Contents/MacOS/stellarium


So pasted this:
export QT_SCALE_FACTOR=1.0 && /Applications/Stellarium.app/Contents/MacOS/stellarium

This launches Stellarium on the second display and it also creates plenty of text in Terminal.

But Stellarium looks the same ie. magnified

**Comment by ImmersiveTheatres** [comment]
immersivetheatres2@Domes-MacBook-Pro-2 ~ % export QT_SCALE_FACTOR=1.0 && /Applications/Stellarium.app/Contents/MacOS/stellarium
 -----------------------------------------------------
[ This is Stellarium 0.19.1 - https://stellarium.org/ ]
[ Copyright (C) 2000-2019 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "/Users/immersivetheatres2/Library/Application Support/Stellarium/log.txt"
File search paths:
  0 .  "/Users/immersivetheatres2/Library/Application Support/Stellarium"
  1 .  "/Applications/Stellarium.app/Contents/Resources"
Config file is:  "/Users/immersivetheatres2/Library/Application Support/Stellarium/config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 0, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "2.1 INTEL-14.4.23"
Current Format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 0, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelMainView::init
Driver version string: "2.1 INTEL-14.4.23"
GL vendor is "Intel Inc."
GL renderer is "Intel(R) Iris(TM) Plus Graphics 655"
GL Shading Language version is "1.20"
Detected a high resolution device! Device pixel ratio: 2
Cache directory is:  "/Users/immersivetheatres2/Library/Caches/stellarium/stellarium"
Sky language is  "en_GB"
Planetary features language is  "en_GB"
Application language is  "en_GB"
Couldn't load translations for language  "en_GB" in section "stellarium-scripts"
Empty translation file for language  "en_GB" in section "stellarium-scripts"
Scripts language is  "en_GB"
Loading Solar System data (1: planets and moons) ...
Loading from : "/Applications/Stellarium.app/Contents/Resources/data/ssystem_major.ini"
Loaded 77 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "/Users/immersivetheatres2/Library/Application Support/Stellarium/data/ssystem_minor.ini"
Loaded 103 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15566 / 15579 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl, Puck, Ryugu"
Loading star data ...
"Loading /Applications/Stellarium.app/Contents/Resources/stars/default/stars_0_0v0_7.cat: 0_0v0_7; 4979"
"Loading /Applications/Stellarium.app/Contents/Resources/stars/default/stars_1_0v0_7.cat: 1_0v0_7; 21806"
"Loading /Applications/Stellarium.app/Contents/Resources/stars/default/stars_2_0v0_7.cat: 2_0v0_7; 150850"
"Loading /Applications/Stellarium.app/Contents/Resources/stars/default/stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from "/Applications/Stellarium.app/Contents/Resources/stars/default/name.fab"
Loaded 4506 / 4506 scientific star names
Loading variable stars from "/Applications/Stellarium.app/Contents/Resources/stars/default/gcvs_hip_part.dat"
Loaded 6916 / 6916 variable stars
Loading double stars from "/Applications/Stellarium.app/Contents/Resources/stars/default/wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from "/Applications/Stellarium.app/Contents/Resources/stars/default/cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
navigation/preset_sky_time is a double - treating as jday: "2457594.58542"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.6 (standard edition)"
Loaded 94077 DSO records
Loading DSO outline data ...
Loaded 63 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from "/Applications/Stellarium.app/Contents/Resources/skycultures/western/star_names.fab"
Loaded 876 / 876 common star names
Loading DSO name data ...
Loaded 1064 / 1079 DSO name records successfully
WARNING - No position data for 15 objects: "NGC 7088, PGC 2906, PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  68 for culture "western"
Loaded 57 / 58 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 47 / 48 asterism names
stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "/Users/immersivetheatres2/Library/Application Support/Stellarium/modules/Exoplanets/exoplanets.json"
Loaded plugin "RemoteControl"
RemoteControl using QtWebApp version 1.6.4-stellarium
StaticFileController: docroot=/Applications/Stellarium.app/Contents/Resources/webroot, encoding=UTF-8, maxAge=60
StaticFileController: cache timeout=60000, size=1048576
RemoteControl enabled
HttpListener: Listening on port 8090
Initializing planets GL shaders... 
"StelPainter: Warnings while linking transformShaderProgram shader program:\nWARNING: Could not find vertex shader attribute 'texCoord' to match BindAttributeLocation request.\nWARNING: Could not find vertex shader attribute 'normalIn' to match BindAttributeLocation request.\n"

**Comment by alex-w** [comment]
What about run in Termonal.app: 
1. `echo 'export QT_SCALE_FACTOR=1.0' >> ~/.zshenv`
2. `echo $QT_SCALE_FACTOR`

**Comment by ImmersiveTheatres** [comment]
I will have to leave it now and try again on the weekend. Thank you for your help so far!

**Comment by gzotti** [comment]
That's version 0.19.1. Were there changes or fixes with HiDPI handling in the last 8 months? Esp. on Mac? Have you tried with version 0.19.3?

**Comment by alex-w** [comment]
> That's version 0.19.1. Were there changes or fixes with HiDPI handling in the last 8 months? Esp. on Mac? Have you tried with version 0.19.3?

I don't remember something special for Macs, but changes was here. I think using fresh beta for test will be better that stable 0.19.3, because we near release 0.20.0 already. :-/

**Comment by ImmersiveTheatres** [comment]
OK so are you guys saying on the weekend I should try with 0.19.3?

**Comment by gzotti** [comment]
Alex suggested already trying the current beta instead of 0.19.3. This is identical to 0.19.3, plus latest changes and improvements.

**Comment by ImmersiveTheatres** [comment]
OK I have installed the Beta Stellarium and have tried all the previous suggestions above:

- modifying the config.ini file opens Stellarium in the second display, but magnified

- running export _QT_SCALE_FACTOR=1.0 && /Applications/Stellarium.app/Contents/MacOS/stellarium_ on Terminal opens Stellarium in the second display, but magnified

- running in Terminal:

1. echo 'export QT_SCALE_FACTOR=1.0' >> ~/.zshenv
2. echo $QT_SCALE_FACTOR

 opens Stellarium in the second display, but magnified (see photo below)

![IMG_7697](https://user-images.githubusercontent.com/59133199/76144664-acd2e380-607a-11ea-8588-e79669b96851.JPG)

Selecting F11 twice resizes the window, but Stellarium remains magnified.

**Comment by gzotti** [comment]
To see the state of documentation for such tricky problems: https://doc.qt.io/qt-5/highdpi.html

Maybe you can try instead with 

QT_SCREEN_SCALE_FACTORS=1.0;2.0 
or 
QT_SCREEN_SCALE_FACTORS=1.5;1.0 

It probably depends on actual screen resolutions and the OS's screen order.

**Comment by ImmersiveTheatres** [comment]
> QT_SCREEN_SCALE_FACTORS=1.0;2.0

Apologies, because I'm not familiar with Terminal commands, how do I enter that? Like this?

echo 'export QT_SCREEN_SCALE_FACTORS=1.0;2.0' >> ~/.zshenv
echo $QT_SCALE_FACTOR

**Comment by gzotti** [comment]
I don't know why you echo the other variable. This looks like a "did it work" test. 
Probably:

1. open a terminal
2. echo 'export QT_SCREEN_SCALE_FACTORS=1.0;2.0' >> ~/.zshenv
3. close this terminal.
4. Open a new terminal
5. echo $QT_SCREEN_SCALE_FACTORS

Check the answer. If it is "1.0;2.0", the command worked, and you should be able to start Stellarium *from that terminal*. If you launch Stellarium by pressing some icon, the setting did not necessarily "go through" to the system. On some systems, logging out and back in, or rebooting, may be then required. I don't know the details of MacOS here. Please look into some MacOS system basic instructions about "setting environment variables".

**Comment by ImmersiveTheatres** [comment]
I have been trying all the above commands in Terminal and I think Terminal is not understanding the value '2.0' ie. the second display:

**Last login: Sun Mar  8 08:04:02 on console
/Users/immersivetheatres2/.zshenv:2: command not found: 2.0
/Users/immersivetheatres2/.zshenv:3: command not found: 2.0
/Users/immersivetheatres2/.zshenv:5: command not found: 2.0
immersivetheatres2@Domes-MacBook-Pro-2 ~ %** 


Looking at the QT documentation ( https://doc.qt.io/qt-5/qscreen.html#name-prop ), I have tried calling the second display 'HDMI1' [because the MacBook is connected to the projector HDMI1], but it does not understand it either:

 **immersivetheatres2@Domes-MacBook-Pro-2 ~ % export QT_SCREEN_SCALE_FACTORS=1.0;HDMI1 && /Applications/Stellarium.app/Contents/MacOS/stellarium 
zsh: command not found: HDMI1**

**Comment by ImmersiveTheatres** [comment]
Although the echo seems to work:

**immersivetheatres2@Domes-MacBook-Pro-2 ~ % echo 'export QT_SCREEN_SCALE_FACTORS=1.0;2.0' >> ~/.zshenv
immersivetheatres2@Domes-MacBook-Pro-2 ~ %**

**Comment by ImmersiveTheatres** [comment]
Actually, no, because after closing and re-opening Terminal I get:

Last login: Sun Mar  8 08:06:11 on ttys000
/Users/immersivetheatres2/.zshenv:2: command not found: 2.0
/Users/immersivetheatres2/.zshenv:3: command not found: 2.0
/Users/immersivetheatres2/.zshenv:5: command not found: 2.0
/Users/immersivetheatres2/.zshenv:6: command not found: 2.0
/Users/immersivetheatres2/.zshenv:7: command not found: 2.0
immersivetheatres2@Domes-MacBook-Pro-2 ~ %

**Comment by gzotti** [comment]
Try

`echo 'export QT_SCREEN_SCALE_FACTORS="1.0;2.0"' >> ~/.zshenv`

Replacing 2.0 by HDMI makes no sense. This is a numeric value meaning a scale factor, not a screen name.

**Comment by ImmersiveTheatres** [comment]
IT WORKED!! 😃

When I run this command in Terminal, Stellarium 0.19.1 opens correctly in full screen in the second display:

export QT_SCREEN_SCALE_FACTORS="1.0;2.0" && /Applications/Stellarium.app/Contents/MacOS/stellarium

THANK YOU!

Now I just need to set it up to open correctly when I click the Stellarium icon. Can you please help me to do that?

I have tried rebooting the laptop, but it makes no difference.

I will now also go and research some MacOS system basic instructions about "setting environment variables".

**Comment by gzotti** [comment]
Good! 
You should find out how to set an environment variable system-wide on MacOS (with administrator or root privileges). Or else, whether the actual command that is triggered when clicking on the icon can be edited. On Windows, a user with admin privileges can edit the link in the start menu. No idea whether Mac users can do similar things.

**Comment by gzotti** [comment]
Copied to wiki: https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#mixing-screens-or-projectors-with-high-and-normal-resolutions

**Comment by gzotti** [comment]
A short search provides this as possible solution. Just edit your .zprofile ?

https://medium.com/@mamk2118/setting-up-environment-variables-in-macos-mojave-and-mac-os-catalina-27ea1bb032f3

**Comment by ImmersiveTheatres** [comment]
Believe me, I have been editing .z files for two weeks! 😄 Unfortunately nothing seems to work, absolutely nothing.
