### ISSUE TITLE
South pole of the Moon is completely black

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#992]
Using Stellarium v0.19.3-204-gb8f2034b8b on Linux x86_64 with 32-bit userspace with `nvidia` driver 390.116 for GeForce GTX 750Ti, I'm observing south pole of the Moon being completely black:

![Screenshot - 050320 - 23:53:15](https://user-images.githubusercontent.com/6376882/76024965-0b924300-5f3d-11ea-87e6-1bdf175ff5dd.png)

**Comment by gzotti** [comment]
#974 causes the wrong visibility of the poles. I discovered recently that the area around the poles is never rendered. (missing triangles!)
