### ISSUE TITLE
Is new moon supposed to be visible in Stellarium?

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#997]
Playing with different renderings of the atmosphere, I've noticed that sometimes new moon is too visible (even when zoomed in to avoid the "fat dot" form), unlike in real life. At first I thought it was related to desynchronization with atmosphere rendering, but then I found this with the default atmosphere model too.
Also, sometimes it isn't as unrealistically visible, which makes me wonder, whether Stellarium wants to somehow emphasize the lunar disk (like in the solar eclipse event), or it aims at a more realistic rendering so that the extra visibility is a bug.

Examples of renderings (with the current out-of-the-box atmosphere):

* Invisible Moon (as expected)

![Screenshot - 140320 - 08:20:29](https://user-images.githubusercontent.com/6376882/76675665-e18bf100-65cc-11ea-8e02-926f9db38b89.png)

* Visible Moon (physically wrong but might be on purpose(?))

![Screenshot - 140320 - 08:21:43](https://user-images.githubusercontent.com/6376882/76675666-e3ee4b00-65cc-11ea-95b7-b3c17df166a7.png)

* Visible at eclipse (might be on purpose(?))

![Screenshot - 140320 - 08:36:23](https://user-images.githubusercontent.com/6376882/76675848-efdb0c80-65ce-11ea-81a3-f254ebf488a8.png)

I suppose the second one, where the Moon is too visible, is simply a forgotten/neglected case when the solar flare is rendered as something behind the Moon, thus resulting in too visible lunar disk, because if I zoom in the second case so that the flare is no longer rendered, the Moon is again mostly invisible:
![Screenshot - 140320 - 08:26:05](https://user-images.githubusercontent.com/6376882/76675730-77c01700-65cd-11ea-901a-560c17f3d540.png)
 
So, is the lunar disk of the full moon supposed to be visible? Or should the rendering with the flare behind and similar misrepresentations be fixed?

**Comment by gzotti** [comment]
The slight visibility of the Lunar disc next to the Sun is indeed very much on purpose and intended. There are algorithms which could numerically decide whether it is theoretically visible or not, based on elongation, altitude and atmospheric factors, but these have not been implemented (in fact not even researched in detail yet), otherwise we could add yet another switch for those users aiming at maximum "realism". However, the moon, even if theoretically invisible, would have to mask off planets near solar conjunction or stars which it may occult. You will also see that the solar "glare" is a texture which is rendered in a fixed size in screen space. This is also "unrealistic". When you zoom out to max, you see the solar glare when the sun is way below the horizon. There are effects here and there which you could improve in "just a few hours", if it really annoys you. Feel invited.

**Comment by 10110111** [comment]
By "slight" visibility do you mean the 4th screenshot or the 2nd? Which of these is the supposed look? If the 2nd is not what it was supposed to be, I might try looking into how to fix this.

**Comment by gzotti** [comment]
It is good to know where the moon is in relation to the sun. The current look is basically OK and should be achievable also in later editions. If you want to improve realism, you can add an alternative path with an additional setting ("Hide Moon close to Sun (more realistic)" or "Accurate lunar visibility" or similar.) You can also make a variable-size solar glare that should vanish when you zoom in and should shrink when you zoom out, and probably should vanish when the sun is behind the landscape.

**Comment by 10110111** [comment]
Hmm, I guess all this should be done after I implement the new atmosphere.

Basically, current rendering is quite old-school: independently-rendered planets along with their halo, with the colors somehow deduced based not on the actual image, brightnesses of the objects disregarding their actual brightness ratios (e.g. one can't see anything except the solar disk when using a solar filter in real life, yet in Stellarium we still have blue sky after zooming in to the Sun to see the spots), etc..

I suppose a second rendering engine (enabled by an option in the config) aimed at realism should be added, which would draw all this in a physically-based manner, like
 1. Draw the objects with their real brightnesses into a floating-point texture
 1. Pass this texture to atmosphere renderer, which would take transmittance into account and draw scattered light and the correctly-extincted objects
 1. Post-process the resulting image to blur excessively-bright objects (so that glare will be automagically achieved)
 1. Apply photopic/scotopic adaptation

But OK, until the new atmosphere model is ready, this is just an idea for a future project.

**Comment by axd1967** [comment]
related to #1130
