### ISSUE TITLE
Can't load comets or anything else with 0.19.3 AppImage on Linux x64

### ISSUE THREAD

**Issue by hronellenfitsch** [Stellarium/stellarium#999]
### Expected Behaviour

Stellarium should be able to download comet data or other data (star catalogues).

### Actual Behaviour

All downloads (as far as I can tell) fail with the error message
`Error creating SSL context (error:140A90C4:SSL routines:func(169):reason(196))`

### Steps to reproduce

Open menu (F2), navigate to extras, click on "Get catalog".

### System
* Stellarium version: 0.19.3 AppImage Linux x64
* Operating system: Ubuntu 19.10
* Graphics Card: Nvidia Quadro M500M, Driver 4.6.0 NVIDIA 440.64

### Logfile 

[log.txt](https://github.com/Stellarium/stellarium/files/4339297/log.txt)

**Comment by alex-w** [comment]
This is well known OpenSSL issue for an AppImage generator

**Comment by hronellenfitsch** [comment]
@alex-w is there a workaround available? The "known issues" page only mentions this issue on Windows.

**Comment by francheu** [comment]
There is a similar problem for the online search in the Solar System Editor. 
The import feature works well (thanks for adding Gideon van Buitenen's data), but the online search fails with the following message : 
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
Download error: While trying to access "https://www.minorplanetcenter.net/cgi-bin/mpeph2.cgi?ty=e&TextArea=Vesta&e=-1&d=&l=&i=&u=d&uto=0&c=&long=&lat=&alt=&raty=a&s=t&m=m&adir=S&oed=&resoc=&tit=&bu=&ch=c&ce=f&js=f" the following error occured: "Error creating SSL context (error:140A90C4:SSL routines:func(169):reason(196))"
Unloaded plugin "SolarSystemEditor"

Under Linux Mint, with Stellarium 0.19.3 and 0.20.0.

**Comment by stephencgithub** [comment]
see also https://github.com/openssl/openssl/issues/7481

**Comment by alex-w** [comment]
See also #578

**Comment by alex-w** [comment]
Sorry, we discontinue support an AppImage builds since version 0.20.3 due technical problems of AppImage architecture! Please use snap packages instead.
